### ISSUE TITLE
Won't create new instance on Mac

### ISSUE THREAD

**Issue by JayGummy** [MultiMC/MultiMC5#1000]
Every time I try to create a new instance I receive this error

Instance load failed: Failed to read the assets index!

I am already logged into to my Minecraft Accountant.
Thanks.

**Comment by peterix** [comment]
This is a network related issue.

Please post your MultiMC log. It's located inside the .app

Run MultiMC, try to start a Minecraft instance and look for MultiMC-0.log inside the .app

**Comment by mewthree3100** [comment]
I'm having the same problem is there any way to fix it?

**Comment by peterix** [comment]
Try to follow the instructions above.

**Comment by mewthree3100** [comment]
Where should I post my log?

**Comment by peterix** [comment]
https://gist.github.com/ would work

**Comment by mewthree3100** [comment]
Okay thank you :)

**Comment by mewthree3100** [comment]
What happens after I post it?

**Comment by peterix** [comment]
Well, nothing if you don't...
