### ISSUE TITLE
Forge conflicts between FTB pack and added patch

### ISSUE THREAD

**Issue by Onering20** [MultiMC/MultiMC5#1002]
After updating to MultiMC 5 ver. 0.4.6 while trying to play infinity I get this error:

Error resolving library dependencies between net.minecraftforge:forge:1.7.10-10.13.3.1395-1710ls:universal and net.minecraftforge:forge:1.7.10-10.13.3.1370-1.7.10:universal in [PATH]/ftb/FTBInfinity/patches/net.minecraftforge.json.

I don't know how to fix this, if it is an issue with my pack or how to fix it.

**Comment by peterix** [comment]
Remove the forge patch from it.

**Comment by Onering20** [comment]
How would I remove the patch through MultiMC. Is the patch any other mods loaded into the pack?

**Comment by peterix** [comment]
Like this:
![remove](https://cloud.githubusercontent.com/assets/203326/7812195/5d6c6b1c-03b0-11e5-8912-721f4d3903d2.png)

**Comment by Onering20** [comment]
It doesn't run with out forge installed though what do i replace it with? (it attempts to but the console shows red text and closes without creating a crash log)

**Comment by peterix** [comment]
The console has an Upload button. Use it. Post the link here.

**Comment by Onering20** [comment]
the console closes too quickly to do anything

**Comment by peterix** [comment]
Well, that means the thing exited, not crashed.

You can change that in the settings:
![close](https://cloud.githubusercontent.com/assets/203326/7815579/8de86e1c-03c9-11e5-9250-8c9e4ad3f324.png)

**Comment by peterix** [comment]
Installed infinity in FTB launcher, (did not let it launch, because NOPE), works in mmc out of the box.

What version of infinity do you have problem with?

**Comment by Onering20** [comment]
For clarifying things, here is the log ( http://paste.ee/p/j5NPj ) and the Infinity version is 1.5.1, this is after I removed the forge patch
![capture](https://cloud.githubusercontent.com/assets/5633381/7826902/048b1c92-03e6-11e5-9be7-9d8aaaff7c27.PNG)

**Comment by peterix** [comment]
Then also remove the liteloader one.

Or, you can try the new develop build, because I fixed this a few hours back. Just change to develop update channel in settings and update.

**Comment by kalmondo** [comment]
I was having the same issue with my regrowth pack. Worked fine this morning, came back, and it gave me an almost identical error tonight. Uninstalled and reinstalled forge, works fine now. Thanks for your help peterix!

**Comment by peterix** [comment]
Ow. Having that forge patch file would have been nice. Because that's the root of the problem then.
