### ISSUE TITLE
Suggestion: Option for Changing the Location of the Instances Folder

### ISSUE THREAD

**Issue by shadowfacts** [MultiMC/MultiMC5#1004]
This would be extremely handy for some (specific) uses cases. Let's say that someone has a small (say 128 GB) PCIe SSD used to store only OS X and applications and MultiMC.app was installed in `/Applications/` on the PCIe SSD. The instances would then be located in `/Applications/MultiMC.app/Contents/MacOS/instances/` on the PCIe SSD, if the user had enough instances they could easily begin to take up large amounts of space because the user can't store the instances on a different drive.

**Comment by peterix** [comment]
Already there:
![feature](https://cloud.githubusercontent.com/assets/203326/7800031/3c519b60-030f-11e5-9b55-e60851021dfe.png)

**Comment by Kilobyte22** [comment]
I am fairly sure there is an option for this in settings
