### ISSUE TITLE
Fix weblate

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#1006]
It should be:
- part of the normal salt stack setup
- running on a separate machine from the build server
- backed up to s3 (db, logins, etc.)

**Comment by robotbrain** [comment]
http://robotbrain.info/weblate.tgz

**Comment by robotbrain** [comment]
Due to issues with my server, webate will probably be going down soon.
Namely, i am running out of space for personal stuff because of it.

**Comment by peterix** [comment]
https://github.com/docker-infra/docker-backup
http://www.youtube.com/watch?v=2ZX3F-aFOxQ
http://geoffrey.io/backuping-postgresql-in-docker.html

**Comment by peterix** [comment]
- [ ] add service
- [ ] set up backups
- [ ] set up nginx proxy and make all other services not listen on external interfaces

**Comment by peterix** [comment]
- [ ] update all links to the service
- [ ] write a nice howto for translators to follow

**Comment by peterix** [comment]
- [ ] update all links to the service
    - [ ] check website

**Comment by peterix** [comment]
Continued in #1400

**Comment by Inky1003** [comment]
Peterix, did weblate back working?

**Comment by peterix** [comment]
It's running, obviously.

The issue is that I don't have enough time to be able to manage the translators.

**Comment by Inky1003** [comment]
There's an translator in github.

**Comment by peterix** [comment]
Hmm?

**Comment by Inky1003** [comment]
Yes. See https://github.com/sp614x/optifine/tree/master/OptiFineDoc/assets/minecraft/optifine/lang
