### ISSUE TITLE
Some mcedit packaging uses only .pyc and .sh - add the files to mcedit detection

### ISSUE THREAD

**Issue by AdmiralMemo** [MultiMC/MultiMC5#1009]
While MultiMC can see the older versions of MCEdit, the MCEdit-Unified branch, which is the one being actively developed, is not seen as being valid: https://khroki.github.io/MCEdit-Unified/

**Comment by peterix** [comment]
What names do the binaries have on different OSes?

**Comment by peterix** [comment]
Actually, unless you are on OSX, where I think noone tested this, ever, there is no issue.

**Comment by peterix** [comment]
You should be able to just select the folder with mcedit and it should detect it and work.

**Comment by peterix** [comment]
Tested it on linux and windows. No issues.

**Comment by AdmiralMemo** [comment]
I'm testing on Ubuntu 12.04 and it's not working. :-( I've put MCEdit (version 1.3.2.0) in the ~/mcedit folder and it is not recognized by MultiMC. "Path does not seem to be an MCEdit path." Is it maybe supposed to be in a subfoler or something?

**Comment by peterix** [comment]
It should have the `mcedit.py` script inside. Make sure the script is executable.

**Comment by AdmiralMemo** [comment]
There is mcedit.pyc but no mcedit.py in the folder. Maybe that was the issue? Also mcedit.pyc was not executable. mcedit.sh is executable.

I'm testing making mcedit.pyc executable now... Nope. Doesn't seem to work. Is it safe to rename mcedit.pyc to mcedit.py? I don't want to screw everything up.

**Comment by Heufneutje** [comment]
No. .py and .pyc are very different. Have you tried redownloading MCEdit?

**Comment by AdmiralMemo** [comment]
About 20 times since the issue started (not due to MultiMC, but issues with MCEdit). Has not worked. I did end up renaming mcedit.pyc to mcedit.py and it worked and MCEdit boots up. Not sure why, but I'm not looking a gift horse in the mouth.

**Comment by peterix** [comment]
Right. You are using the linux installer thing?

Looks like it only includes the bytecode versions of some of the files... that's funny, because the bytecode isn't necessarily compatible with the installed version of python... but, not the point.

We should add mcedit.pyc and/or mcedit.sh to the detection code.

**Comment by peterix** [comment]
This should now be fixed in develop.

It will use the shell script that this weird installer provides.
