### ISSUE TITLE
Unnecessary folder generation

### ISSUE THREAD

**Issue by T145** [MultiMC/MultiMC5#1010]
Whenever I run a 1.7.10 profile through MultiMC, some folders that date back to the 1.6.4 days are generated and never used, like "coremods" and "texturepacks." Can this be prevented?

**Comment by peterix** [comment]
Yes.

**Comment by jeep70** [comment]
Any update on this?

**Comment by peterix** [comment]
Nope. I don't see this as any sort of real issue. And fixing it with the current system in place is not worth it.

**Comment by T145** [comment]
Well, it is a little bit annoying for modpack creators, and general users who keep accidentally clicking the wrong directories. And besides, you don't have to actually *fix* it, just delete any excess that's unneeded.

**Comment by peterix** [comment]
Ok. Tested it again and can confirm that this is an issue. It is not supposed to happen too - it's not been written that way on purpose.

I also found a second issue: when you change the Minecraft version, the enabled pages do not change.

**Comment by peterix** [comment]
This does not require wonko.
