### ISSUE TITLE
Mod duplicate checks

### ISSUE THREAD

**Issue by DrZed** [MultiMC/MultiMC5#1013]
A button to push and scan for duplicate mods by looking at the mod id in mod infos and highlighting red the duplicated mod or just a pop up saying this mod is duplicated because my modpack is large and I manually update and frequently forget to delete 1 of the many old versions so after 5 minutes of launching it shows "duplicate mod logistics pipes" or what ever and I have to remove and relaunch another 5 minutes when it could be a 30 second scan

**Comment by peterix** [comment]
Right. Something like this won't be 100%, ever, unless we actually do a fair bit of the loading before starting the game.

Still, probably worth a try.

**Comment by DrZed** [comment]
Thanks :D

**Comment by peterix** [comment]
Alright. Moved the idea to workflowy (Ideas -> Mod list, Ideas-> Wonko, or the #mod-dupes tag):
https://workflowy.com/s/2EyDMcp7CU
