### ISSUE TITLE
Launch error: Optifine 1.8.4

### ISSUE THREAD

**Issue by MulverineX** [MultiMC/MultiMC5#1014]
http://paste.ee/p/fnfWc

**Comment by peterix** [comment]
Cannot reproduce with Minecraft 1.8.4 and OptiFine_1.8.4_HD_U_D4

**Comment by MulverineX** [comment]
Yes and Yes

**Comment by peterix** [comment]
This works without any issues here. So there must be something different about what you did.

Export the instance and put it on some file host.

**Comment by peterix** [comment]
Please retry with 0.4.7 - it has a bit better log output that includes mods and jar mods used.
