### ISSUE TITLE
Crash when customizing older MC versions

### ISSUE THREAD

**Issue by FyberOptic** [MultiMC/MultiMC5#1021]
In 0.4.6, to recreate the crash, create a new instance of something like Minecraft 1.2.5 or 1.4.7, edit instance, and click to customize Minecraft itself.  

I can't do this on pre-existing instances for those versions since it appears to default to the older Jar Mods pane instead.

Apologies if this has been fixed in a recent commit, I don't have an environment set up to try the latest.

**Comment by peterix** [comment]
There is nothing to customize for < 1.6... so maybe that's the issue.

**Comment by peterix** [comment]
```
  298.492 C "Exception: Unable to open the version file a1.0.4.dat: No such file or directory."
  298.492 W Version could not be loaded: "Unable to open the version file a1.0.4.dat: No such file or directory."
```
Those are actually not saved as files. They are baked directly into mmc.

**Comment by peterix** [comment]
Made these impossible to customize, because anything else doesn't really make sense. They are hardcoded and don't work like the newer Mojang versions do.

Anything < 1.6 still works like in MMC4 and older.
