### ISSUE TITLE
"Custom" Forge Versions are causing crashes.

### ISSUE THREAD

**Issue by GustoniaEagle** [MultiMC/MultiMC5#1022]
For full information, see https://github.com/Vazkii/Botania/issues/1015
As you can tell, I thought the problem was initially with the Botania mod, but it turns out that it is actually the fault of MultiMC (see the final comment by me).

This needs to be fixed urgently as whatever you are doing to the Forge versions is causing something wonky.

**Comment by peterix** [comment]
The version is ALWAYS custom. And always was.

**Comment by GustoniaEagle** [comment]
Well that's fun. Turns out that somehow the Botania jar corrupted (might have been when I downloaded it, who knows?) and so caused the crash.
As a result, when I tried to make the same instance using the Curse Client, I used the Curse Client to download the jar, and so used a different and clearly, non-corrupted, jar. This caused me to think that MultiMC was the cause.

Apologies!

**Comment by peterix** [comment]
I'm sorry for the confusion too.

The 'Custom' part just means that the forge patch file is stored inside the instance. It's always been that way. Now it shows 'Custom' for that, because I added a way to customize the default/builtin patches.
