### ISSUE TITLE
sapmanpack

### ISSUE THREAD

**Issue by jprocket45** [MultiMC/MultiMC5#1024]
I have this working fine but as soon as i put all my jar files in MultiMC it will not load and says sapmanpack minimum version required is 2.4.1 but if i load it regular without MultiMC5 it works fine ive tried 2.4.1 and also 2.5.0 neither will load. maybe just me but i cannot figure it out.

**Comment by peterix** [comment]
No idea what this is about at all.

There's an Upload button on the console window. Use it.
