### ISSUE TITLE
Java locations inconsistent after manual java installer upgrade?

### ISSUE THREAD

**Issue by Luke7930** [MultiMC/MultiMC5#1025]
hello their is a bug when I update java offline 8 update 40 to java online 8 update 45
whith multimc 0.4.7 dev -552 for windows

sorry for my english, I'm French =D

**Comment by peterix** [comment]
This doesn't really tell me much.

What is this bug?
If the game doesn't start properly, use the 'Upload' button and post the paste.ee link here.

**Comment by Luke7930** [comment]
There is a bug when I updated java version 8 update 40 offline to java version 8 update 45 online
![captur2](https://cloud.githubusercontent.com/assets/12674641/7901409/8e296420-0785-11e5-95d3-3ff0a42ae798.JPG)
![captur3](https://cloud.githubusercontent.com/assets/12674641/7901411/8e335bb0-0785-11e5-8e5c-9cdb87e434c7.JPG)

**Comment by peterix** [comment]
Alright.

So the problem is that you changed your java version and MultiMC doesn't detect that it's gone after the update/upgrade?

**Comment by peterix** [comment]
Or is it unable to find the new version?

**Comment by Luke7930** [comment]
yes it doesn't detect that after the update

**Comment by peterix** [comment]
[ ] - test on Windows
[ ] - likely: add to JVM check on launch

**Comment by peterix** [comment]
I'm going to assume this was an ancient java installer.updater bug and that this is no longer relevant.
