### ISSUE TITLE
Crash when tracking FTB instances

### ISSUE THREAD

**Issue by megamanzteam** [MultiMC/MultiMC5#1026]
When I check the tracker in MMC5 v0.4.6 for FTB instances the client crashes. I have to go to the cfg to change it to false. 
![untitled](https://cloud.githubusercontent.com/assets/4212359/7898510/f6c6ae0c-06c7-11e5-94fc-e8aa658db0db.jpg)
I notice I am unable to change the launcher location, which maybe the issue. As the exe is located in the FTB folder, not in roaming.

Here is my crash log: http://pastebin.com/KUB4aqea

**Comment by peterix** [comment]
Known issue, already fixed in develop.

If you set the update channel to develop and update, the issue should be gone.
