### ISSUE TITLE
just doesn't work second time

### ISSUE THREAD

**Issue by Dr-gummybears** [MultiMC/MultiMC5#1027]
hi i have multi mc on windows 64 bit i set the memory and all my settings then i track ftb packs (which there are a lot) then no instances so i close multi mc then load up the program and nothing happens so i try the main application not the shortcut nothing again so i reinstall and the same thing happens again

**Comment by peterix** [comment]
Try this one:
http://files.multimc.org/downloads/mmc-develop-win32.zip

Does it work better?

**Comment by Dr-gummybears** [comment]
Yeah thanks it is working great :)

DR gummybears

**Comment by peterix** [comment]
So: this was the FTB tracking crash.

**Comment by peterix** [comment]
You might want to switch to stable once the 0.4.7 version is out.

**Comment by Dr-gummybears** [comment]
Ok thanks 

DR gummybears
