### ISSUE TITLE
Set up travis for building on OS X, multiple versions of Qt and upgraded CMake

### ISSUE THREAD

**Issue by 02JanDal** [MultiMC/MultiMC5#1033]
It seems like travis OS X support is ready now, add it to the build matrix.

[Documentation](http://docs.travis-ci.com/user/osx-ci-environment)

**Comment by 02JanDal** [comment]
Apparently it is not. This issue is also for multiple Qt versions and upgraded CMake.

**Comment by peterix** [comment]
Turned off most of the stuff in feature/travis, and just made it use gcc with c++14.

**Comment by peterix** [comment]
We'll make a new issue once this becomes relevant again...
