### ISSUE TITLE
Make .packignore more configurable

### ISSUE THREAD

**Issue by jikuja** [MultiMC/MultiMC5#1043]
New pack import/export introduced .packignore in instance folders. File seems to be automatically updated to reflect GUI state when pack is exported which means that adding wildcard support into `<instance>/.packdata` is not feasible

Request: add global and maybe internal default packignore to control every pack export automatically
Examples: for files and folder which should be ignored logs/, hs__.log, core._ core, .git/, various desktip metadata files and folders, etc. Are both needed? What if user wants to change internal packignore?

Request 2: Wildcard support in global packignore

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Packs -> Export)](https://workflowy.com/s/2EyDMcp7CU)
