### ISSUE TITLE
Exitcode -1

### ISSUE THREAD

**Issue by legoman9570** [MultiMC/MultiMC5#1044]
http://paste.ee/p/Y1Nf0

**Comment by Heufneutje** [comment]
You have the dev versions of CodeChickenCore and NEI in your mods folder. You probably want the universal versions.

**Comment by legoman9570** [comment]
I changed CodeChickenCore and NEI to universal and it crashed again here's the log, http://paste.ee/p/ry9ci#

**Comment by peterix** [comment]
And the same as above for EnderStorage.

**Comment by legoman9570** [comment]
Thanks! Its working just fine now :)
