### ISSUE TITLE
Twitch libraries don't load

### ISSUE THREAD

**Issue by Wolf68k** [MultiMC/MultiMC5#1045]
With 0.4.8-dev562 the libraries for Twitch don't load no matter what version of Minecraft I use.
In 0.4.7 it's fine. I only use the dev version because of issues in the past and better features.

**Comment by robotbrain** [comment]
This is probably my fault.

**Comment by peterix** [comment]
Reverted the change that lead to this. It should be gone. Reopen if it's still an issue.
