### ISSUE TITLE
unusual multimc crash

### ISSUE THREAD

**Issue by aolko** [MultiMC/MultiMC5#1046]
Was playing while multimc crashed
![wow](http://i.imgur.com/sv8iRh3.png)
Wtf?

**Comment by peterix** [comment]
Known bug.

Minecraft is logging way too much, which causes the log page to fill all available memory. Then it crashes.

See: #1008 

I'm going to fix this in 0.4.8, assigned #1008 to it.

**Comment by aolko** [comment]
wait, i _was_ using 0.4.8 latest DEV

**Comment by peterix** [comment]
That's possible, but #1008 isn't done yet ;)

See:
https://waffle.io/MultiMC/MultiMC5

If Minecraft is logging enough to crash MultiMC, it's probably not good for performance. It might be surprising, but producing human readable text isn't an easy task :)

If you enable the console window:
![settings-console](https://cloud.githubusercontent.com/assets/203326/8010638/16bdf884-0bb2-11e5-96ec-b9ed35a8dd8c.png)

Or just make it show by clicking the tray icon in the corner of the screen, you should see what's happening. The console window normally doesn't show up, unless Minecraft crashes:
![log](https://cloud.githubusercontent.com/assets/203326/8010683/7e16c3bc-0bb2-11e5-9610-c30d3bc9a04c.png)

This is most likely filling with excessive amount of text.

You should fix whatever is causing it.

If you want to just prevent MultiMC from crashing, disabling the 'Keep Updating' checkbox 
should do just that. It will stop putting more of the log in the log page.

**Comment by aolko** [comment]
[log](https://goo.gl/4RpyAV)

**Comment by peterix** [comment]
Fixed in develop: #1008

**Comment by peterix** [comment]
That log... well, it's a power converters cape that can't be rendered. Not sure if it's possible, but disabling capes in power converters could fix that.
