### ISSUE TITLE
Add save/world management

### ISSUE THREAD

**Issue by ThePixelNerd** [MultiMC/MultiMC5#1047]
Ok, first I want to say this application is absolutely invaluable around my house! With 4 of us that play Minecraft, it's a lifesaver being able to use this program!

Ok, my question is, where can I find the skin that I see on the screenshots? It's where the icons look like grass blocks....I don't see the option for that skin anywhere :(

My request is, in the context menu for each instance of the game it shows such things as: 
Edit Instance
Instance Settings
Edit Notes
Manage Screenshots
Etc.
I would like to see the option of: "Open Map/Save Folder" or however you would want to word it.

My kids are constantly downloading maps and it's a headache to tell them or anyone else I might be teaching how to use MultiMC to go into instance folder, minecraft, find the saves folder, extract the save into that folder blah blah blah.

It would be awesome to have a one click link that opened the Saves Folder....or if there was some kind of option to just upload a new save straight into there through the program?!?!?

Thanks again for this amazing program that is miles above all others! God Bless!

**Comment by Kilobyte22** [comment]
Maybe a map management GUI? Wasn't there something like that already? Or was that MultiMC 3/4?

**Comment by peterix** [comment]
It was. And will fit into MMC5 much better.

Actually, I'm just going to do this, because it sounds like fun.

**Comment by peterix** [comment]
There are icon themes in the settings:
Settings -> User Interface -> Icon Theme.

UI themes in general aren't there yet - whatever the OS can offer is used.

**Comment by peterix** [comment]
Should be just like the other folder management pages, except:
- [ ] Add MCEdit integration
- [ ] Add export, not just import
- [ ] Add import from URL
- [ ] Add size column
