### ISSUE TITLE
[bug][locale] Fuzzy locale

### ISSUE THREAD

**Issue by aolko** [MultiMC/MultiMC5#1048]
![scr](http://i.imgur.com/WI3QR3E.png)
Also, window header looks like "Edit instance (%1)"

**Comment by peterix** [comment]
I have no idea... not understanding a single word of Russian doesn't help.

If you can help, here's where:
http://translate.multimc.org/projects/multimc/multimc5/ru/

**Comment by aolko** [comment]
i think the problem is partially in button size (text won't fit)

**Comment by peterix** [comment]
OK... putting this together with all the other translation issues.

**Comment by peterix** [comment]
You can help fix the translations using our [translation server](http://translate.multimc.org)
