### ISSUE TITLE
libstdc++.so.6 leaks into Minecraft

### ISSUE THREAD

**Issue by Holi0317** [MultiMC/MultiMC5#1049]
Hi,

After switching catalyst driver to radeon driver, MultiMC will crash as soon as I launch it.

The crash report are as follows, launched with `LIBGL_DEBUG=verbose`
http://pastebin.com/mPX19yvC

The reason of the crash is because ` libGL: dlopen /usr/lib/xorg/modules/dri/radeonsi_dri.so failed (/home/h/app/MultiMC/bin/libstdc++.so.6: version GLIBCXX_3.4.21 not found (required by /usr/lib/libLLVM-3.6.so)) `. That is caused by libstdc++.so.6 included in MultiMC incompatible with radeonsi driver.

After Googleing, it turns out steam also has this issue because Steam also includes libstdc++.so.6. [soruce](https://bbs.archlinux.org/viewtopic.php?id=193802)

I have replaced libstdc++.so.6 with the one from /usr/lib/ and Minecraft launched successfully.

**Comment by peterix** [comment]
Yeah. The easy way is just to delete MultiMC's `libstdc++.so.6`.

The idea would be to detect the system versions of libraries on start or update and if they are newer, delete the bundled ones.

**Comment by peterix** [comment]
Actually... looked at this again, and this should not be happening at all.
MultiMC and Minecraft should be two distinct things. I have no idea why it is using MultiMC's libstdc++ - it shouldn't be using that. So this is a separate issue from the DLL hell in general.

**Comment by peterix** [comment]
fixed in develop
