### ISSUE TITLE
Environment variables instance settings tab

### ISSUE THREAD

**Issue by SoniEx2** [MultiMC/MultiMC5#1050]
Would be cool to set environment variables before launch. By default it would be set to override the variables MMC currently overrides, so if someone wants to un-override them they can do it just by removing them, instead of having to manually copy them over or just accept it the way it currently is.

Would also make it easier to force MC to use a different PulseAudio output, which I had to use an environment variable for, because it wouldn't let me change it.

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Launching).](https://workflowy.com/s/2EyDMcp7CU)
