### ISSUE TITLE
Rebuild and update

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#1052]
Qt, cmake and other build env things need updating!

**Comment by 02JanDal** [comment]
OS X builder updated to CMake 3.2.2 and Qt 5.4.2. Need to investigate what's required for updating clang.

Also see #1033 for updating travis.

**Comment by peterix** [comment]
Buildbot 0.8.12 is broken, will have to either fix it or downgrade

**Comment by peterix** [comment]
That will have to be reverted if you update clang on OSX

**Comment by peterix** [comment]
Possible fixes for buildbot issues:
* https://github.com/buildbot/buildbot/pull/1708
* `<skelly> peterix: the other fix is to check your config and change: 'github': True  to  'github': {}`
