### ISSUE TITLE
Can't create a modded world! :(

### ISSUE THREAD

**Issue by mooCow1613** [MultiMC/MultiMC5#1058]
I created an instance with mods and forge, all 1.7.10. It lets me load minecraft and I can do things on the homepage. It also says all the mods are there but as soon as I create a world it will say 'shutting down internal sever' and then crash.. I have tried everything and put in each mod one by one but it still crashes.
PLEASE HELP :(

**Comment by Loetkolben** [comment]
To help you we need the Minecraft Log.
When it crashes, click the *Upload Log* button in the console window and give us the link, please.

**Comment by mooCow1613** [comment]
Ok, will do as soon as possible!

**Comment by 11justsomekid** [comment]
I had the exact same problem, so here's my log:

http://paste.ee/p/ll61H

**Comment by peterix** [comment]
No. Your problem is not the same.

**Comment by 11justsomekid** [comment]
It follows his exact details, word for word.

**Comment by Heufneutje** [comment]
"'shutting down internal sever' and then crash" is very generic can have many, MANY different causes.
