### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by youngtomlin** [MultiMC/MultiMC5#1062]
Hello I have a modded survival and the game crashes when you start it up 

Crash Report: http://paste.ee/p/JIsvC

Thanks in advance

**Comment by peterix** [comment]
`MultiMC version: 0.4.6` - update MultiMC

here's the culprit:
```jurassicraft{1.4.0} [JurassiCraft] (JurassiCraft-1.4.0.jar) Unloaded->Constructed->Errored```

And here's the problem:
```cpw.mods.fml.common.LoaderException: java.io.FileNotFoundException: http://pastebin.com/PQgLKE5F```

Dead link (http://pastebin.com/PQgLKE5F) and a badly written mod that's missing basic error checking on unsafe operations.

It was probably using pastebin for update checks. If the thing has any configs, you could try disabling update checks in there.
