### ISSUE TITLE
Fix version comment button size and fix "More news..." button position

### ISSUE THREAD

**Issue by calloatti** [MultiMC/MultiMC5#1066]
The version comment button is too wide:

![image](https://cloud.githubusercontent.com/assets/12817862/8069089/729e4cc0-0ece-11e5-94bf-48f4dcd6de0f.png)

The "More news..." button is not centered in vertical toolbar:

![image](https://cloud.githubusercontent.com/assets/12817862/8069117/9c232034-0ece-11e5-8264-146fa5dce9e7.png)

**Comment by peterix** [comment]
I'm not going to mess with this.
