### ISSUE TITLE
Can't use Steam overlay when launching MultiMC from Steam

### ISSUE THREAD

**Issue by SoniEx2** [MultiMC/MultiMC5#1069]
This is why raping environment variables is bad.

**Comment by robotbrain** [comment]
then you call various crash bugs due to environment variables ok?

**Comment by SoniEx2** [comment]
That's why it should be an OPT-OUT feature instead of a RAPE THE USER feature.

**Comment by 02JanDal** [comment]
We're not raping anyone, and I advice you to read what you're writing, it'll greatly increase the possibility of it getting fixed.

Anyway, take a look at #585, #576 and others. There's an actual reason we're not letting them through. _JAVA_OPTS is another.

Maybe you could tell us which environment variable and which value you expect, then we can consider if we want to let it through.

**Comment by peterix** [comment]
Fixed.

**Comment by twprogrammers** [comment]
Version 0.4.8-dev-564
Steam overlay is not showing on MC or MMC.

**Comment by SoniEx2** [comment]
Works for me?

**Comment by twprogrammers** [comment]
I thought I deleted it in time, but I guess not. I spoke too soon. It only works _after_ it goes full screen, but not while loading.

**Comment by peterix** [comment]
The issue was about environment variables not being passed to the game and more importantly, the native library loader, so Steam can hook into whatever code and add its overlay.

Everything else is up to Steam.

**Comment by Arudarin** [comment]
Not sure if I should create a seperate issue or not, but it's not working on Windows either. 

These are my settings in steam, selecting the MultiMC.exe and passing the command line arguments '-l "1.14.4"'.

https://i.imgur.com/PGvloaJ.png
https://i.imgur.com/LAp47fj.pn

[When I try to enable the Steam Overlay](https://streamable.com/294z0), the mouse cursor disappears and black bars are drawn. If I try clicking somewhere where there would be a button, I hear a noise indicating that it has been pressed.

 I conclude that for some reason, Steam is not drawing it's overlay over MultiMC correctly, whereas it does on the Vanilla Minecraft launcher.

**Comment by Arudarin** [comment]
@peterix ?

**Comment by peterix** [comment]
Please do not necro closed issues from 2015.

**Comment by peterix** [comment]
Open a new one.
