### ISSUE TITLE
Instance sharing

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#1070]
Using existing syncing technology to sync instances between computers.

rsync?
dropbox?
cloud stuff?
FTP?

...
Magic?

Anyway, the idea is to share the stuff you put together with others.

It should also be possible to lock the shared instance - make it always shadow the original.

**Comment by TheDoctorsLife** [comment]
+1 for dropbox/cloud stuff

**Comment by LokiChaos** [comment]
I would go with rsync or maybe git if we're just dealing with plain text*. 

*This assumes mods will be fetched from either the clients local downloaded mod cache or from upstream servers.  As a general policy, I would avoid trying to shove jar files about.  Modders can get fussy and this sidesteps the whole mess of re-distribution.  No one should have to download a given mod more than once on a system and the client should be smart enough to just copy it to instances.

**Comment by AlphaKintari** [comment]
+1
Personally I play my modpack on several different computers, having the ability do sync the pack and worldsaves would save several steps of exporting the pack to Dropbox, then deleting it on the current computer, then re-importing it.

**Comment by peterix** [comment]
Alright. I think we should have an article somewhere about how to set this up, so people can read it. Not necessarilty stuff this functionality straight into MultiMC.

But both are levels of the same.

[Moved to workflowy (Ideas -> Share Instances)](https://workflowy.com/s/2EyDMcp7CU)

**Comment by peterix** [comment]
People can just use other tools to do this. This is massive scope creep.
