### ISSUE TITLE
Not really a bug, but more of a confusion

### ISSUE THREAD

**Issue by ThePixelNerd** [MultiMC/MultiMC5#1071]
I've checked all the documentation I can find and did searches online for the answer but can't seem to find an answer. 

When using worldedit, I can save schematics by using /schematic save filename but where does it save these? I can't seem to find my schematics anywhere so that I can manually add more to the folder.

Thanks again guys for the hard work and amazing program!

**Comment by peterix** [comment]
I think it saves them somewhere in the mods folder, of all things.
