### ISSUE TITLE
Crash when making new world

### ISSUE THREAD

**Issue by legoman9570** [MultiMC/MultiMC5#1074]
So, when I press the create new world button it goes to the loading screen then after 10-20 seconds it crashes. Here's the log, http://paste.ee/p/f1OXN

**Comment by Loetkolben** [comment]
> [22:10:34] [Client thread/ERROR] [FML]: The fluid registry is corrupted. A fluid minechem.fluid.FluidElement mt is not properly registered. The mod that registered this is broken

Try starting without Minechem, it seems to be the problem.

**Comment by legoman9570** [comment]
Ok, so I removed it and it worked. But, is there any way I can keep the mod, without it crashing my game or is that not possible?

**Comment by jikuja** [comment]
Try Minechem-1.7.10-5.0.5.398.jar: "Updates Minechem for use with the new Forge fluid paradigm."

**Comment by legoman9570** [comment]
Yup, its working great now thank you!
