### ISSUE TITLE
MultiMC should be possible to translate before a stable release

### ISSUE THREAD

**Issue by calloatti** [MultiMC/MultiMC5#1077]
I have been translating to spanish using weblate, but I can´t find some still pending strings using the search function in weblate, for example:

"Close", "Help" buttons in edit instance form

"Installation de Forge..." button in edit instance form

**Comment by robotbrain** [comment]
are you using develop? weblate is based on stable.

**Comment by calloatti** [comment]
Yes, is that the problem then?

**Comment by robotbrain** [comment]
the source strings tend to change a lot in develop. i would use a seperate stable install to check your translations

**Comment by robotbrain** [comment]
because the source strings change often in develop, weblate uses the ones from stable

**Comment by calloatti** [comment]
Ok, I just checked, and its funny, some buttons get a whole new (false) meaning.

**Comment by peterix** [comment]
I think I misjudged this when it was reported.

Yes, we need to change the translation process to allow translating new versions a lot sooner than the final stable release.

[Moved to workflowy - (Infrastructure -> Translations)](https://workflowy.com/s/2EyDMcp7CU)

**Comment by peterix** [comment]
We got this now!
