### ISSUE TITLE
Investigate Mod Organizer

### ISSUE THREAD

**Issue by Cheeseless** [MultiMC/MultiMC5#1078]
Mod Organizer is a mod management tool for Bethesda games. What it does that I think would be interesting to have here is it doesn't change any of the files in the instance of the game it runs. What it does is it virtualizes where the mods' files will go when installing them, then it actually glues them together last-minute, without ever changing any of the original files. It doesn't even have any problems with overwriting, since no information is lost. http://sourceforge.net/projects/modorganizer/ The main upshot of the system is basically the information never being altered based on the specific collection of mods. This would be very useful to have in Minecraft, for both updating mods, and keeping them as pristine as possible to prevent bugs.

**Comment by Cheeseless** [comment]
Also, there's some utilities that should be a part of MultiMC already, such as an overwrite fixer for Item IDs and such.

**Comment by Orochimarufan** [comment]
I believe that most of your suggestions would be better off being
implemented in (or at least supported by) forge or more specifically fml.
I'm using MO myself and it achieves the separation by shadowing the Windows
file system functions. This approach comes with its own set of issues and
IMHO in case of Minecraft, since the forge team has actual control over the
mod loading code and it could therefore be implemented more efficiently.
As for conflicts, that should also be handled by the respective parts of
forge or even vanilla (like how they got rid of blockid)
All in all, I don't see much MultiMC should do here, condedering that
Minecraft mods are already way more cleanly separated than e.g. Skyrim mods.

**Comment by peterix** [comment]
Indeed. This isn't needed.

Minecraft mods do not have mod loading dependencies - not ones you could influence in any way. Forge and the mods themselves already handle all of this.

Fixer for any sort of IDs seems like an afterthought at this point... the IDs are dead in current versions, unless mods screw with the registries, which they shouldn't (looking at you, DragonAPI).

For old versions, I'd have to see a *lot* of demand for it.

**Comment by peterix** [comment]
Anyway, will look at the thing for inspiration :)

**Comment by peterix** [comment]
Don't close this.

**Comment by Cheeseless** [comment]
Oops, I'm sorry. I thought you were done with it. I hope you can find something of value in what I now realize was a pretty out-of-place suggestion. Maybe some easier way to know what mods are in the pack r sometihng like that.

**Comment by peterix** [comment]
The games it's for have a lot of static content - manually made worlds - so you can get a lot of conflicts from different mods changing this static content differently and order makes sense...

MultiMC still does that, if you use old Minecraft versions and `jar` mods.

What I'd like to look at is how this Mod Organizer looks and behaves.

**Comment by peterix** [comment]
Uses Qt **AND QML**.

So, it becomes more interesting. QML is something that we would need for theming support and I haven't managed to package it properly yet.

**Comment by Evolution0** [comment]
Some things that would be great to take from MO would be:

* Mod renaming
* Mod grouping
* Categories
* Dependency checks/alerts
* Version checking/alerts

Renaming.. I know to an extent MultiMC already tries to get the actual name but it seems not all mod authors fill out this data? So the option for the user to rename would be nice.

Grouping is nice for a lot of reasons, say you are making a modpack but want separate "modules", you could create for example a group with just magic mods and their deps (libs, add-ons, etc) and if you want to disable them just untick the whole group. Would obviously need some checks to prevent deps from being disabled that other mods outside the group need.

Dependency checks.. not sure, maybe a db would be need to be made if you can't get this info from the jar itself.

MO does its version checking by looking up the name/id on the filename and checking it against the version on Nexus (Could do this with Curse?) I know that wouldn't cover all mods but more and more are moving to curse.

Sorry about the brain dump heh

**Comment by peterix** [comment]
All of this sounds like the current design can't handle it. It will have to be done later, based on the wonko infrastructure.

Definitely not curse. Depending on that sounds like a recipe for endless headaches.

**Comment by 02JanDal** [comment]
As @peterix said, this largely depends on wonko to not be a huge pain to maintain.

This contains some very interesting ideas that a potential new instance format would need to be able to handle and needs to be kept in mind.

**Comment by peterix** [comment]
I'm just not going to look at this. We have plenty of ideas, without looking at other things.
