### ISSUE TITLE
AL lib: (EE) alc_cleanup: 1 device not closed

### ISSUE THREAD

**Issue by EthanCoy** [MultiMC/MultiMC5#1079]
I have used all the mods on my list for quite a few days now with no problems having them load. Out of the blue, the game crashes before it even loads. I have done nothing, no adding or subtracting, or updating any of the files on here. 
I have tried to google the answer, but I am not having any luck. I can give the log if there is some code that you see needs fixing. I would greatly appreciate the fix!

http://paste.ee/p/6XEMw

**Comment by robotbrain** [comment]
make sure your forge is up to date. the error is earlier at 
java.lang.RuntimeException: glCheckFramebufferStatus returned unknown status:33305

**Comment by EthanCoy** [comment]
@robotbrain When I had the 1.7.10 forge installed to match the mods, everything worked fine. I've opened the game up several times with no problems. Could the forge have outdated itself?

**Comment by peterix** [comment]
No, you enabled fullscreen within the game. This breaks the fancy Forge progress bar screen.

You either need to disable it in the Minecraft options file manually, or update Forge.

**Comment by EthanCoy** [comment]
Well, I took off the forge and used the most recent one for that version, and it seemed to fix it. It's odd how the simple things work. Thank you both for your help! It's greatly appreciated!
