### ISSUE TITLE
Add disable/enable for version patches

### ISSUE THREAD

**Issue by ThePixelNerd** [MultiMC/MultiMC5#1082]
I would like to recommend/request the ability to turn off items like forge or liteloader in the same way you can mods. Right now if I want to disable liteloader or forge I either delete them or go into the instance folder and add .disabled at the end of the filename and it would be nice to have a checkbox to toggle just like the mods.

**Comment by peterix** [comment]
Will do, in the wonko branch

**Comment by peterix** [comment]
Or sooner? We'll see :)

[Moved to workflowy (Ideas -> Version patches and instance version).](https://workflowy.com/s/2EyDMcp7CU)

**Comment by peterix** [comment]
This is going to be in next stable.

**Comment by peterix** [comment]
Added in develop.
