### ISSUE TITLE
When Loading up Minecraft Crashes 

### ISSUE THREAD

**Issue by youngtomlin** [MultiMC/MultiMC5#1084]
This is for the Animated Lucky Block, but it crashes when It loads

Thanks in advance

**Comment by loordgek** [comment]
post logs

**Comment by youngtomlin** [comment]
Oh yeah sorry DUH! :(
http://paste.ee/p/JSGRx

**Comment by TheDoctorsLife** [comment]
try disabling swordstone & MutantCreatures
