### ISSUE TITLE
Cannot Mod Minecraft, It keeps crashing after modding

### ISSUE THREAD

**Issue by Mrtucker2** [MultiMC/MultiMC5#1085]
Link: http://paste.ee/p/EkHHC

**Comment by jikuja** [comment]
Don't use 1.8 mods with 1.7.10: NotEnoughItems-1.8-1.0.5.82-universal

Also consider adding mods in smaller patches and then you might ve able to find bad mods....

**Comment by Mrtucker2** [comment]
Wow, i look like an idiot... Thanks so much for helping me!
