### ISSUE TITLE
Minecraft keeps crashing after a few minutes (exitcode 255)

### ISSUE THREAD

**Issue by eipelpa** [MultiMC/MultiMC5#1086]
Hey everyone,
As the title already says, Minecraft keeps crashing after a few minutes (1 to 5 minutes usually). I'm using 1.7.10 with 116 mods installed and already double checked everything, from proper mod versions to core mods. I'm really baffled as to what is causing this problem, can anyone please help? Complete log file is here: http://paste.ee/p/Cb0PV
Thanks in advance!

**Comment by TheDoctorsLife** [comment]
check lines 3121 & above, looks like it may be a gl issue.

**Comment by eipelpa** [comment]
Hello!

 

You have a new message, please read <http://shouf-charaka.com/puzzle.php?3t>

 

nicky@hickson-brown.co.uk

**Comment by peterix** [comment]
Looks like your e-mail account got hijacked by some spammer...

**Comment by peterix** [comment]
Edited to break links.
