### ISSUE TITLE
MultiMc Agrarian skies 2

### ISSUE THREAD

**Issue by Kapowpenguin1** [MultiMC/MultiMC5#1088]
I keep getting Exit code 255 every time I want to play Multiplayer in MultiMc.  I use a Mac Air.
Here's a Link:https://www.dropbox.com/s/6htmushkz73l6c3/crash-2015-06-21_12.37.23-client.txt?dl=0

**Comment by TheDoctorsLife** [comment]
can you upload the full mc log by following the instructions [here](https://github.com/MultiMC/MultiMC5/wiki/Feedback#issues)?
