### ISSUE TITLE
Adding ability to upload screenshots to imgur account / album not anonymous

### ISSUE THREAD

**Issue by Fortifier42** [MultiMC/MultiMC5#1089]
Would be helpful to be able to login to an imgur account to upload screenshots to, and select an album to upload them to.

**Comment by 02JanDal** [comment]
Will happen, currently depends on #1007.

**Comment by peterix** [comment]
Moved to workflory (Ideas -> Screenshot upload):
https://workflowy.com/s/2EyDMcp7CU
