### ISSUE TITLE
MultiMC starts slowly

### ISSUE THREAD

**Issue by LORD-MJ** [MultiMC/MultiMC5#109]
It takes at least 20 seconds for MultiMC to start. It's not horrible, but it could use an improvement. Maybe it's just my machine, I don't know.

System info:
Windows 7 Pro 64-bit
Intel i5 4570 @ 3.2 GHz
8 GB of DDR3 RAM
GTX 670

**Comment by peterix** [comment]
If you are still interested, can you test the current 'develop' build? If you can also provide the log file from the develop version (MultiMC.0.log), that would help a lot.

You can switch to the develop version in the settings and update afterwards.

**Comment by peterix** [comment]
Cannot reproduce.

**Comment by LORD-MJ** [comment]
Sorry for a (very xD) late reply. It would appear that the bug was fixed, as version 0.4.7 starts very quickly. Thank you for looking into this.
