### ISSUE TITLE
Ctrl not behaving as it should in Loader mods

### ISSUE THREAD

**Issue by Evolution0** [MultiMC/MultiMC5#1090]
Rather than allowing a user to click and highlight multiple mods it behaves as if you were holding Shift and highlights everything in between.

Using latest release version 0.4.7 on Windows 8.1 x64.

**Comment by peterix** [comment]
Indeed - the underlying model doesn't support non-contiguous selections.

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Mod list)](https://workflowy.com/s/2EyDMcp7CU)

**Comment by peterix** [comment]
Not a bug, but should be improved...

Related to / dupliacte of #589 #842 #1273

**Comment by peterix** [comment]
It does now.
