### ISSUE TITLE
World crash for all worlds!

### ISSUE THREAD

**Issue by 11justsomekid** [MultiMC/MultiMC5#1091]
I just updated to MultiMC version 0.47, and now none of my worlds work! After I click the "Play Selected World" button, t says, "Shutting Down Internal Server" and gives me this crash:

http://paste.ee/p/ll61H

This affected all my worlds,old and new, so I need it fixed!!!!!HELP!!!!!!!

**Comment by peterix** [comment]
Update optifine.
