### ISSUE TITLE
MultiMC using ubuntu 14.04.2

### ISSUE THREAD

**Issue by rebeccastanke** [MultiMC/MultiMC5#1096]
We are re-purposing XP into school projects for Minecraftschooloflearning.com. The issue we have is MultiMC. We reloaded the computers then downloaded MultiMC which does not execute. We are very new to Unix - We tried the suggestions found on this site, same issue. Could very well be us not knowing what to do.  Is there a way to get MultiMC working on computers much like using Windows? Could someone show me so I can show the kids? We have Java 1.8 installed

**Comment by peterix** [comment]
Actually went and tried installing MultiMC on stock ubuntu. It wasn't a nice experience...

So, here you have a debian/ubuntu package:
http://dethware.org/dl/multimc_1.0-1.deb

It should add the application to menus, give it an icon and make it easy to deploy in general.

The package is a simple wrapper that just installs MultiMC into the the home folder of anyone who runs it: `~/MultiMC`

**Comment by peterix** [comment]
Note that you do need admin/root rights for the machine to install packages.

**Comment by peterix** [comment]
TODO:
- [ ] Automate wrapper package creation
- [ ] Upload the wrapper package to the site during build

**Comment by Kilobyte22** [comment]
May I note that putting the data in ~/.multimc would fit Unix conventions better?

**Comment by RX14** [comment]
:+1: on `~/.multimc`

**Comment by rebeccastanke** [comment]
I got an error wrong architect AMD64

this is an old PC so my guess is I need 32 bit and this install is for 64?

**Comment by peterix** [comment]
I can make a 32bit-compatible package easily, but we no longer do 32bit linux builds of the application. It's a bit tricky with the current setup.

How many computers do you have?

**Comment by peterix** [comment]
If you run this in a terminal:
```
cat /proc/cpuinfo
```
What does that say?

**Comment by rebeccastanke** [comment]
I'm helping families repurposed their old xp computers with Ubuntu. Just
about everyday there are parent asking how to do this. So far I have not
found an easy way to install java and minecraft. I'm up for any method of
installing these apps that these families can do themselves.

**Comment by peterix** [comment]
So, it's all sorts of computers. Sounds tricky.

Got a new version of the package:
http://dethware.org/dl/multimc_1.1-1.deb

It should be able to grab both 32bit and 64bit MultiMC, depending on what you install it on.

**Comment by rebeccastanke** [comment]
It took awhile for me to find the download but once I did I got it working.
I plan to do a few more of these myself while I write up instructions for
the kids to take over to help other kids..  Thankyou for your help.  Is
there an easy way to get java installed for minecraft. Since it takes me
about 3 or more applications of trying this and that I'm probably doing it
wrong

**Comment by RX14** [comment]
```
sudo apt-get install python-software-properties
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
```
should do the trick

**Comment by peterix** [comment]
The package actually installs the default version of java for ubuntu 14.04 - latest java 7.

But this is fine too.

**Comment by peterix** [comment]
Actually made the 32bit builds work again, so you aren't going to get an outdated version.

**Comment by rebeccastanke** [comment]
Well I spoke to soon. Multimc gets to installing mods then it's a hard
freeze. I tried both with and without mods and multimc stops at the same
place.
Setup loading blocks bar finished: texture stitching - missing no took
0.000s

Then hard freeze. keyboard  and mouse do not respond. I have to shut off he
computer then turn it back on.

**Comment by RX14** [comment]
Sounds like an issue with the drivers, maybe these PCs are too old to run minecraft.

**Comment by peterix** [comment]
right... that does sound like a hardware or driver issue...

1. Post the output from the `lspci` and `lsmod` commands - run them in a terminal.
2. You could try an older version of Minecraft.
3. You could try an older version of Forge - one without the new loading screen.
4. Minecraft normally writes a bunch of log files. Even if the graphics card gave up, they'll still be there. Look for anything starting with `hs-err` or similar, and also the latest Forge log.

**Comment by rebeccastanke** [comment]
user1@MSOL-523a4:~$ lspci
00:00.0 RAM memory: NVIDIA Corporation MCP61 Memory Controller (rev a1)
00:01.0 ISA bridge: NVIDIA Corporation MCP61 LPC Bridge (rev a2)
00:01.1 SMBus: NVIDIA Corporation MCP61 SMBus (rev a2)
00:01.2 RAM memory: NVIDIA Corporation MCP61 Memory Controller (rev a2)
00:02.0 USB controller: NVIDIA Corporation MCP61 USB 1.1 Controller (rev a3)
00:02.1 USB controller: NVIDIA Corporation MCP61 USB 2.0 Controller (rev a3)
00:04.0 PCI bridge: NVIDIA Corporation MCP61 PCI bridge (rev a1)
00:05.0 Audio device: NVIDIA Corporation MCP61 High Definition Audio (rev
a2)
00:06.0 IDE interface: NVIDIA Corporation MCP61 IDE (rev a2)
00:07.0 Bridge: NVIDIA Corporation MCP61 Ethernet (rev a2)
00:08.0 IDE interface: NVIDIA Corporation MCP61 SATA Controller (rev a2)
00:08.1 IDE interface: NVIDIA Corporation MCP61 SATA Controller (rev a2)
00:09.0 PCI bridge: NVIDIA Corporation MCP61 PCI Express bridge (rev a2)
00:0b.0 PCI bridge: NVIDIA Corporation MCP61 PCI Express bridge (rev a2)
00:0d.0 VGA compatible controller: NVIDIA Corporation C61 [GeForce 6150SE
nForce 430] (rev a2)
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] K8
[Athlon64/Opteron] HyperTransport Technology Configuration
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] K8
[Athlon64/Opteron] Address Map
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] K8
[Athlon64/Opteron] DRAM Controller
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] K8
[Athlon64/Opteron] Miscellaneous Control
01:05.0 FireWire (IEEE 1394): LSI Corporation FW322/323 [TrueFire] 1394a
Controller (rev 70)
01:0a.0 Communication controller: Conexant Systems, Inc. HSF 56k Data/Fax
Modem
user1@MSOL-523a4:~$ ^C
user1@MSOL-523a4:~$


user1@MSOL-523a4:~$ lsmod
Module                  Size  Used by
bnep                   18895  2
rfcomm                 53664  4
bluetooth             342263  10 bnep,rfcomm
snd_hda_codec_realtek    51029  1
snd_hda_intel          42730  6
snd_hda_codec         164067  2 snd_hda_codec_realtek,snd_hda_intel
snd_hwdep              13272  1 snd_hda_codec
snd_pcm                85501  2 snd_hda_codec,snd_hda_intel
snd_page_alloc         14230  2 snd_pcm,snd_hda_intel
snd_seq_midi           13132  0
snd_seq_midi_event     14475  1 snd_seq_midi
snd_rawmidi            25135  1 snd_seq_midi
kvm                   388083  0
snd_seq                55383  2 snd_seq_midi_event,snd_seq_midi
nouveau               969577  3
psmouse                91033  0
mxm_wmi                12893  1 nouveau
wmi                    18673  2 mxm_wmi,nouveau
video                  18903  1 nouveau
ttm                    72698  1 nouveau
serio_raw              13230  0
drm_kms_helper         46907  1 nouveau
snd_seq_device         14137  3 snd_seq,snd_rawmidi,snd_seq_midi
k8temp                 12842  0
snd_timer              28584  2 snd_pcm,snd_seq
drm                   243792  5 ttm,drm_kms_helper,nouveau
snd                    60871  22
snd_hda_codec_realtek,snd_hwdep,snd_timer,snd_pcm,snd_seq,snd_rawmidi,snd_hda_codec,snd_hda_intel,snd_seq_device,snd_seq_midi
i2c_algo_bit           13197  1 nouveau
soundcore              12600  1 snd
i2c_nforce2            13037  0
mac_hid                13037  0
parport_pc             31981  0
ppdev                  17391  0
lp                     13299  0
parport                40836  3 lp,ppdev,parport_pc
hid_generic            12492  0
usbhid                 47035  0
hid                    87604  2 hid_generic,usbhid
usb_storage            48417  0
pata_acpi              12886  0
firewire_ohci          35529  0
firewire_core          61867  1 firewire_ohci
crc_itu_t              12627  1 firewire_core
sata_nv                23004  2
forcedeth              62140  0
pata_amd               13761  0
user1@MSOL-523a4:~$

**Comment by peterix** [comment]
Right. You are using the open-source drivers for that card... and that simply doesn't work right.

This could help:
http://askubuntu.com/questions/588538/whats-the-correct-driver-to-use-with-a-geforce-6150se-nforce-430-on-lubuntu-14

**Comment by peterix** [comment]
The important part of this:

**Comment by peterix** [comment]
The important part of this:
```
sudo apt-get install nvidia-304
```

Then reboot.

**Comment by rebeccastanke** [comment]
On Sun, Jun 28, 2015 at 2:10 PM, Petr Mrázek <notifications@github.com>
wrote:

> The important part of this:
>
> sudo apt-get install nvidia-304
>
> Then reboot.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MultiMC/MultiMC5/issues/1096#issuecomment-116334175>.
>
that driver install did the trick, it works, thank you, hopefully I wont
have to many like this.

**Comment by peterix** [comment]
Alright. Calling this done. I'll add the packages to our normal build system and put them on the site.
