### ISSUE TITLE
Skin on MultiMc

### ISSUE THREAD

**Issue by UKAGENT1** [MultiMC/MultiMC5#1097]
I'm using the MultiMC launcher with some friends (Running Minecraft 1.7.10) and when  i changed my skin it changed, but then when I changed it soon after, nothing has happened. It works fine on normal Minecraft.
Help?

**Comment by peterix** [comment]
It probably got stuck in a cache or something?

After two months, I suspect it fixed itself... sorry about the response delay.

**Comment by UKAGENT1** [comment]
Thank You for your reply! I think it probably just got stuck like you said

Thanks again
