### ISSUE TITLE
Game crashes on creating a crash report for crashes

### ISSUE THREAD

**Issue by Robijnvogel** [MultiMC/MultiMC5#1098]
I got this:
http://pastebin.com/n5xCivP3
instead of it telling me the actual crash. And that makes solving problems err... problematic.

(And I can not find the original crash in the fml client log either it is just behaving at one moment and on the other it is closing the internal server.)

**Comment by peterix** [comment]
That's not a MultiMC log. Use the upload button.

**Comment by Robijnvogel** [comment]
I already found the cause of the invisible crash (NEI Integration), but I am pretty sure that that crash was not the direct cause of this crashlog generate crash. It crashed on reporting other crashes as well. But not after I removed the Battlegear mod, it seems? hmm, I'll investigate.

http://paste.ee/p/mn5mD
