### ISSUE TITLE
premium account

### ISSUE THREAD

**Issue by vice04** [MultiMC/MultiMC5#1102]
Do i need to have a premium account to launch the game?
It keeps saying this when i sign in my account from MultiMC
"Authentication server didn't specify a currently selected profile. The account exists, but likely isn't premium"

**Comment by Greenphlem** [comment]
Of course you do, you need to own a real copy of the game

**Comment by Kilobyte22** [comment]
You can play the demo on on the official launcher AFAIK. MultiMC does not support that.

**Comment by Kilobyte22** [comment]
Are you trying to tell me something?

**Comment by peterix** [comment]
Nope. Just assigning stuff... maybe I got it wrong here?

**Comment by Kilobyte22** [comment]
Yeah, I doubt this issue needs any assignment ;)

**Comment by peterix** [comment]
If any, then to @Greenphlem because he resolved it.

**Comment by TheDoctorsLife** [comment]
It doesn't allow non collaborators to be assigned.
