### ISSUE TITLE
Explosions Freezing Game Requiring Restart

### ISSUE THREAD

**Issue by VerdExNeon** [MultiMC/MultiMC5#1103]
http://paste.ee/p/KdW8g

What is happening is whenever a creeper or tnt is about to be set off; my game will freeze and become unplayable. This is reoccuring in both a modded and vanilla instance. I can avoid the issue by being on peaceful, but there's no fun in it. I've posted the issue on reddit and was told it may be an invalid sound file, but I don't know how to even look into it to see if it is an issue...

**Comment by peterix** [comment]
Odd.

If you delete the `assets` folder, it should download fresh files.

**Comment by peterix** [comment]
Cause is unknown... and we're unlikely to find out too.
