### ISSUE TITLE
Job 'Specific version download' failed to process

### ISSUE THREAD

**Issue by Sheefou** [MultiMC/MultiMC5#1109]
so when i try to launch a vanilla instance i get this nice little window 

Job 'Specific version download' failed to process:
https://rawgit.com/02JanDal/WonkoTheSaneFiles/master/net.minecraft/1.8.7.json

:3 send halp plz

PC information:
OS: Win 8.1 (64)
Java Version: Fresh install Latest
MultiMC Channel: Unstable

**Comment by peterix** [comment]
Yeah. Don't use the unstable version.
