### ISSUE TITLE
Log in Failure

### ISSUE THREAD

**Issue by vextierium** [MultiMC/MultiMC5#1110]
When I try to add a account i get this error: "Authentication operation failed due to a network error: Unable to init SSL Context: (99)"

Minecraft servers are up and proxy is set to none.

**Comment by TheDoctorsLife** [comment]
can you login with the vanilla minecraft launcher?

**Comment by PsiNAK** [comment]
This is apparently still a problem. Vanilla launcher works fine. MultiMC will not authenticate. Same error.
Debian 9.8 Stable
