### ISSUE TITLE
MultiMC Custom Mod Pack Exitcode -1

### ISSUE THREAD

**Issue by rhbeffect** [MultiMC/MultiMC5#1111]
I built the mod pack for personal use today and it keeps on crashing.

It starts loading the mods but then freezes and exits with exitcode -1 

i dont understand what the log is saying.

Please Help

https://paste.ee/p/i4MLB

**Comment by TheDoctorsLife** [comment]
the issue is with AgriCraft, try updating it/ removing it. that should fix your issue.
