### ISSUE TITLE
Add ubuntu packages

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#1112]
- [ ] to build system
- [ ] to the site

**Comment by spannerman79** [comment]
I am unsure but have you considered the openSUSE build system? https://build.opensuse.org/

I am not sure or cannot remember but there was a linux package that is distributed via the opensuse build system that covered debs, rpms, arch & gentoo packages etc

If not perhaps something via a PPA?

**Comment by 02JanDal** [comment]
Using the OBS would mean we have another piece of infrastructure that is not under our control. I would prefer to have this on the same build server as the rest.

**Comment by peterix** [comment]
Too much effort.

The package and how to make it is already done and part of the codebase. If I have to create an equivalent rpm package, it will be similar - just a wrapper arounf a .desktop entry and a script that will download and install the real builds.

**Comment by peterix** [comment]
Although... maybe building could be done in such a build service? At least it would use the native tools and the right versions of them.

I can make packages using CMake though. Or just generic packaging tools on Arch.

The real work here is testing the packages on the different distros and making sure they pull in all the MultiMC dependencies - and work.

**Comment by peterix** [comment]
Basic package is on the site.
