### ISSUE TITLE
Custom multimc modpack crashes on world startup

### ISSUE THREAD

**Issue by sparkmaster2001** [MultiMC/MultiMC5#1114]
well i have managed to get to the title screen after hours of trial and error but im just compltely stuck here   http://paste.ee/p/Dj9eH

**Comment by Loetkolben** [comment]
```
java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Unknown Source) ~[?:1.8.0_45]
	at mapwriter.Texture.getRGB(Texture.java:77) ~[Texture.class:?]
```
Maybe try without MapWriter?

**Comment by sparkmaster2001** [comment]
kk i shall try it :)

**Comment by sparkmaster2001** [comment]
well i uninstalled all maps exept from opis and this happened  http://paste.ee/p/QO7on

**Comment by Loetkolben** [comment]
Well, still has the same Stacktrace... And Opis has a MapWriter included...
Try disableing it and see if it helps. If it does, try a different version on Opis.

**Comment by sparkmaster2001** [comment]
ah yes it was opis thankyou!!!!!

**Comment by Loetkolben** [comment]
So, I guess it's fixed now. If not, reopen.
