### ISSUE TITLE
Craftbook

### ISSUE THREAD

**Issue by Billabonga** [MultiMC/MultiMC5#1116]
Where do I place 1. World Edit - in mods or in plugins? 2. Craftbook - ditto

**Comment by peterix** [comment]
MultiMC is for modding the client, not the server... so unless you have something strange going on and actually can use bukkit plugins, (almost) everything belongs into the mods folder.

There's a forge version of WorldEdit here:
http://minecraft.curseforge.com/mc-mods/225608-worldedit

Craftbook? No idea.

**Comment by Billabonga** [comment]
Tks for your answers - very much appreciated.

PS As far as I know Craftbook IV is intended as a mod/plugin on Forge and should work on single player as well ... ?

**Comment by peterix** [comment]
I couldn't find a forge version of it.

**Comment by Billabonga** [comment]
its in connection with Sponge ...

http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html

**Comment by Billabonga** [comment]
... which is a client app also

**Comment by TheDoctorsLife** [comment]
Belongs in the mods page (not the jar mods!)

**Comment by TheDoctorsLife** [comment]
Didn't mean to close this yet.

**Comment by Billabonga** [comment]
no problem :) and thx

**Comment by Billabonga** [comment]
Good Morning to you, I have tried everything, but I cannot get Craftbook to work, and it's driving me insane! Can someone please help via Teamviewer or so?

**Comment by Billabonga** [comment]
I gave it a last try because I didn't want to look too stupid, and .... IT WORKS.

**Comment by TheDoctorsLife** [comment]
@Billabonga can you post the fix to this so other people having the same issue can get it working?

**Comment by Billabonga** [comment]
in the .minecraft config file go to Craftbook and the Craftbookconf file. In that file you cut the mechanics that are disabled and set that value =null. Thereafter you paste them   into "mechanics to load", Insert a couple of functions like "Elevator" and "Pipe". "Pipe" doesn't work yet but will be available shortly - as far as I know.

# This contains all disabled mechanics. It is never read internally, but just acts as a convenient place to grab mechanics from.
disabled-mechanics=null
# The list of mechanics to load.
enabled-mechanics=[
    Door,
    Elevator,
    Pipe,
    Footprints,
    TreeLopper,
    Snow,
    EmptyDecay,
    Bridge,
    ICSocket,
    HeadDrops,
    Gate
]

Save the file and you are good to go.

**Comment by Kilobyte22** [comment]
I took myself the freedom to reformat your comment. Hope you don't mind :)

**Comment by Billabonga** [comment]
Thanks - it sort of formatted itself when I sent my comment ....

**Comment by Kilobyte22** [comment]
Github uses markdown for formatting. A line starting with `#` denotes a heading for example.

**Comment by Billabonga** [comment]
OK ... I'll remember next time
