### ISSUE TITLE
Can not download jar file

### ISSUE THREAD

**Issue by leozzyzheng** [MultiMC/MultiMC5#1118]
I'm an user in China, and also a developer.
After install forge `1.8-Forge11.14.3.1450`. 
I want to update some jar file through json file, so I open the `1.8-Forge11.14.3.1450.json` and try to download this:
```
{
	"name": "com.typesafe.akka:akka-actor_2.11:2.3.3",
	"url": "http://files.minecraftforge.net/maven/",
	"checksums": [
		"ed62e9fc709ca0f2ff1a3220daa8b70a2870078e",
		"25a86ccfdb6f6dfe08971f4825d0a01be83a6f2e"
	],
	"serverreq": true,
	"clientreq": true
}
```
If I understand it correctly, the jar file should be
http://files.minecraftforge.net/maven/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
But if I enter the url into web browser , it returns 404. I think there must be some thing wrong.

**Comment by leozzyzheng** [comment]
Or this should be report to Forge not here ? I just notice it just now,

**Comment by peterix** [comment]
The file downloads just fine using MultiMC. There is nothing to fix or report.

Are you making your own launcher?

**Comment by leozzyzheng** [comment]
@peterix  yes , can you open this url to download the file? I think the url is parsed correct

**Comment by peterix** [comment]
Ok.

The file is actually not there. But there's a different one.

The forge people are saving bandwidth by compressing some files with pack200 and lzma2 (xz). The xz container is also extended with a custom suffix that contains the original jar file checksum.

The file is actually here:
`/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar.pack.xz`

URL prefix depends on the mirror.

You'll have to reverse the compression. Xz first, then pack200. 
https://github.com/MultiMC/MultiMC5/blob/develop/logic/forge/ForgeXzDownload.cpp#L196

**Comment by peterix** [comment]
Or you could help with an existing launcher (HINT!) ;)

**Comment by leozzyzheng** [comment]
@peterix Many thanks ! It is different from MC's official library download url logic. Thanks!
