### ISSUE TITLE
gameband support

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#1119]
contact gameband people

**Comment by spannerman79** [comment]
I actually had a look at GameBand - its basically what you can do already with MultiMC except run from a USB 3 flash drive (which I have done before by the way *with* MultiMC) - except having some LCD output for gimmick effect.

A SanDisk 16GB CZ43 is approx $16AUD - where gameband only can store 8GB and costs $79.99USD (approx $108AUD) - over 6 times the cost!

**Comment by peterix** [comment]
That aside, it would seem they lost interest.

I'll close this. Reopen if you disagree.

**Comment by spannerman79** [comment]
Their loss. And I don't disagree personally.

**Comment by peterix** [comment]
I gave the dude all the info needed, link to this issue and so far nothing is happening. Might be just them being busy or this not being a priority... or MultiMC not being a business you can sign a contract with.

Hard to tell without any information.

**Comment by spannerman79** [comment]
> Hard to tell without any information

I know - can only make educated guesses.  Don't get me wrong its good for kiddies - I showed it to my friends 12 year old autistic kid and asked what she thought of it - she wants to know if it can be bought here in Australia now as she wants one badly LOL

But for more "technical" people that understand actual specs and costs like myself can see its "bling-bling" only.

Unless.... no it couldn't be.  Perhaps MultiMC conflicts with their "app" on device as MultiMC is so versatile and cross platform.

Bah who knows
