### ISSUE TITLE
can install forge

### ISSUE THREAD

**Issue by drozone69** [MultiMC/MultiMC5#1120]
multimc is not letting me install forge

**Comment by peterix** [comment]
What Minecraft and Forge version are you using?

**Comment by drozone69** [comment]
1710 and the recommened i got it install is there any possible way to get a older version

**Comment by drozone69** [comment]
of multimc

**Comment by peterix** [comment]
The forge file server (http://files.minecraftforge.net/) is down. So just wait for it to be online again.

And while there are very convoluted ways you can get previous versions, I don't think that would fix a server being down.
