### ISSUE TITLE
Set up some sort of analytics

### ISSUE THREAD

**Issue by 02JanDal** [MultiMC/MultiMC5#1123]
* What service? Google? Piwik? Custom?
* Opt-in? Opt-out?
* What to track? Only start up or all the way down to button clicks?

**Comment by Loetkolben** [comment]
Opt-In :+1:

**Comment by TheDoctorsLife** [comment]
+1 for custom/google
+1 for Opt-In
I think features should be tracked, aka stuff like pack imports/exports, ftb tracking/importing.

**Comment by Kilobyte22** [comment]
I vote for custom. That way we have full control of what happens to data. Also we should actively prompt the user on first launch. I agree on opt-in.

**Comment by 02JanDal** [comment]
Opt-in, but prompting is what I'd vote for too.

Custom means we have to write something ourselves, which I (for once (help what's happening???)) wouldn't want to do. Piwik allows us to have full control of the data since it's self-hosted. The normal problem of having to maintain extra infrastructure applies here, though there exist ready made docker images.

**Comment by peterix** [comment]
+1 for something we don't have to host for testing/development... and to have an abstraction layer.

**Comment by 02JanDal** [comment]
IMO it shouldn't be enabled in development (as in: custom builds). For abstraction layer; do you mean something that sends the analytics to several services or a C++ class?

**Comment by peterix** [comment]
abstract interface and implementation.

**Comment by peterix** [comment]
Let's not do this.
