### ISSUE TITLE
Twitch Libraries

### ISSUE THREAD

**Issue by Niko-Art** [MultiMC/MultiMC5#1125]
I wanted to stream on 1.7.10 files but it said the twitch Libraries were unavailable. please explain this because i want to stream my minecraft to twitch.

**Comment by Niko-Art** [comment]
I Get this in the log

[11:51:28] [Client thread/ERROR]: Couldn't initialize twitch stream

**Comment by RX14** [comment]
Can you post the whole MultiMC log to pastebin and link it here? Also what operating system are you using?

**Comment by peterix** [comment]
If you are running the develop version, then that's a known issue: #1045

**Comment by Niko-Art** [comment]
Windows 8.1 with bing and yes i am running dev because of the ftb tracking issue

**Comment by Niko-Art** [comment]
this is also what happens on the inner_updater stream

**Comment by Niko-Art** [comment]
MultiMC version: 0.4.8-inner_updater-589

Minecraft folder is:
C:/Users/Morgan/Desktop/MultiMC/instances/1.7.10/minecraft

Java path is:
C:/Program Files/Java/jre7/bin/javaw.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx3072m, -XX:PermSize=512m, -Duser.language=en, -jar, C:/Users/Morgan/Desktop/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 21084

Using onesix launcher.

Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/Morgan/Desktop/MultiMC/instances/1.7.10/natives

Traits:
  []

Libraries:
  C:/Users/Morgan/Desktop/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/com/google/guava/guava/15.0/guava-15.0.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/Morgan/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/Morgan/Desktop/MultiMC/versions/1.7.10/1.7.10.jar

Params:
  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, C:/Users/Morgan/Desktop/MultiMC/instances/1.7.10/minecraft, --assetsDir, C:/Users/Morgan/Desktop/MultiMC/assets, --assetIndex, 1.7.10, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {"twitch_access_token":["<TWITCH_ACCESS_TOKEN>"]}, --userType, mojang]

Window size: 854 x 480

Preparing native libraries...
Extracting twitch-platform-5.16-natives-windows-64.jar
Extracting twitch-external-platform-4.5-natives-windows-64.jar
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

[12:04:53] [main/INFO]: Setting user: <PROFILE NAME>
[12:04:53] [main/INFO]: (Session ID is <SESSION ID>)
[12:04:54] [Client thread/INFO]: LWJGL Version: 2.9.1
If on Windows, make sure to provide all of the necessary dll's as specified in the twitchsdk README. Also, make sure to set the PATH environment variable to point to the directory containing the dll's.
[12:04:55] [Client thread/ERROR]: Couldn't initialize twitch stream
[12:04:55] [Client thread/INFO]: Reloading ResourceManager: Default, Nik.zip

Starting up SoundSystem...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
OpenAL initialized.

[12:04:56] [Sound Library Loader/INFO]: Sound engine started
[12:04:58] [Client thread/INFO]: Created: 512x256 textures/blocks-atlas
[12:04:58] [Client thread/INFO]: Created: 256x256 textures/items-atlas

**Comment by Niko-Art** [comment]
Ummm not even the unstable is likeing me this time i can acess the settings but i get this on start broadcast

[Broadcast controller] startCallback got failure: TTV_EC_INTEL_FAILED_ENCODER_INIT

**Comment by peterix** [comment]
Just use stable.

**Comment by Niko-Art** [comment]
I don't wish to use stable because then I cannot use FTB tracking which I
use daily.

**Comment by peterix** [comment]
Have you tried stable recently? I'm not aware of any difference between stable and develop when it comes to FTB tracking.

**Comment by Niko-Art** [comment]
I wasen't aware it was fixed.

**Comment by peterix** [comment]
Assuming fixed.

**Comment by Niko-Art** [comment]
Yes it is all fixed now.
