### ISSUE TITLE
Crashes when attempting to start

### ISSUE THREAD

**Issue by MrExclusive** [MultiMC/MultiMC5#1126]
When I attempt to launch a specific modepack the game crashes and gives an error report, I was hoping someone could look through it and tell me the problem as I don't know how to spot a problem within it. Any help would be appriciated, thanks.

**Comment by peterix** [comment]
Use the upload button to put it on paste.ee and link it here.

**Comment by MrExclusive** [comment]
http://paste.ee/p/09FkX

**Comment by peterix** [comment]
Somehow, you have two copies of openeye... I would suggest removing both, because it doesn't add anything to the game.

**Comment by MrExclusive** [comment]
Oh, whoops. Yeah, that was the problem, must of accidentally put that in there again. Thanks for you help, much appriciated.
