### ISSUE TITLE
Crashes when attempting to start

### ISSUE THREAD

**Issue by MrExclusive** [MultiMC/MultiMC5#1127]
Crash dump - http://paste.ee/p/b57zP
Any help would be appriciated, as I am new to experimenting in this field I don't have much knowledge on the problems.

**Comment by peterix** [comment]
You have some ancient version of the portal gun in there.

**Comment by MrExclusive** [comment]
What exactly do you look for in these files, I've got another error somewhere and I'd like to try and resolve it myself, with some advise.

**Comment by MrExclusive** [comment]
http://paste.ee/p/J11E9 - Other problem I was speaking of

**Comment by peterix** [comment]
google first line of the crash:
```
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: cpw/mods/fml/common/IPlayerTracker
```

You'll find out it's some sort of version mismatch issue.

Forge is a bit silly about reporting where the problem actually happened. But these newer versions are actually showing something.

Look at that long column of `UC`. `UC` is fine, but you'll fine `UE` too. Those are the ones causing the problem. If it crashes later, it will look different. In general, look for things that don't fit into the surrounding pattern.

**Comment by peterix** [comment]
Just update all the iChun mods.

**Comment by MrExclusive** [comment]
Ok, thanks!

**Comment by peterix** [comment]
`java.lang.NoClassDefFoundError` means something is missing. it can be because you are missing a mod some other mod depends on, or you have wrong versions.

In this case, it's `cpw/mods/fml/common/IPlayerTracker`... and that's part of FML/Forge. So it's either a problem with Forge version, or even Minecraft version.

**Comment by peterix** [comment]
It all has to fit together :)

**Comment by MrExclusive** [comment]
Yeah, I see how it kind of works now. You've been very helpful :)

**Comment by peterix** [comment]
Alright :)

**Comment by Kilobyte22** [comment]
First time I actually see someone asking how to read crash logs instead of just letting someone else do it for them :thumbsup:

**Comment by MrExclusive** [comment]
Well I just want to be able to sove the problem and help others

**Comment by TheDoctorsLife** [comment]
+1 for helping others
