### ISSUE TITLE
Crash after launch

### ISSUE THREAD

**Issue by fireguyed** [MultiMC/MultiMC5#1128]
My game keeps crashing and I'm not sure why. The crash log isn't helping me but hopefully someone can figure out why. Here is my crash log: http://paste.ee/p/M2AAT (BTW my minecraft version is 1.7.10)

**Comment by 02JanDal** [comment]
Please upload the full log using the Upload Log button.

**Comment by fireguyed** [comment]
Not sure why it didn't upload the full log last time but here is another one http://paste.ee/p/o9s8L

**Comment by peterix** [comment]
It looks like you are missing something related to projectred... maybe update mrjtp core?
