### ISSUE TITLE
Java binary couldn't be found

### ISSUE THREAD

**Issue by Eudaldca** [MultiMC/MultiMC5#1129]
I just updated to java 8 u 51, and after installing it, MultiMC doesn't seem to detect my java path. I have tried specifying it by myself, which doesn't work, but it's correct path. I've also tried reinstalling java, but the same happens. The only log that I am given by MultiMC is [this one](http://paste.ee/p/hTTYC).
The problem is definitely not with my installation, MC vanilla launcher works fine.

**Comment by peterix** [comment]
Right.

MultiMC writes its own log files.

Open up the java settings, click auto-detect and post the `MultiMC-0.log` file from its folder.

**Comment by Eudaldca** [comment]
@peterix [Boop](http://paste.ee/p/YHUHK). It doesn't let me launch this optifine 1.8.7 instance, but I can with FTB infinity. In the 1.8.7 instance I have optifine installed as a jar mod, because I'm not using forge. I've been always been able to launch it, it only broke when updating Java.

**Comment by peterix** [comment]
Ok... that's a log from something completely different than we were talking about before.

For general game crashes, just use the `update` button on the console window.

**Comment by Eudaldca** [comment]
I don't know why, but recreating the instance worked fine, maybe i messed up something when copying the settings file from an instance to another. Thanks for the support, anyways.

**Comment by AverageComet250** [comment]
Wow so helpful don't necro old threads and I'm pretty sure he already knew this.
