### ISSUE TITLE
Cannot compile source code on Windows

### ISSUE THREAD

**Issue by leozzyzheng** [MultiMC/MultiMC5#1130]
In file:depends/pack200/src/defines.h

    #ifdef _MSC_VER
    #include <windows.h>
    #include <winuser.h>
    #else 
    #include <unistd.h>
    #endif

It should be

    #ifdef _MSC_VER
    #define WIN32_LEAN_AND_MEAN
    #include <windows.h>
    #include <winuser.h>
    #else 
    #include <unistd.h>
    #endif

To prevent redefinition of `byte`.

**Comment by TheDoctorsLife** [comment]
hmm, I wonder why this hasn't been an issue before.

**Comment by peterix** [comment]
Use gcc, not MSVC. We do not support MSVC and do not compile with it.

The only reason why that macro is in place is because pack200 comes from a third-party source.

**Comment by peterix** [comment]
The CI uses the 32bit version of mingw 4.9.1.

**Comment by leozzyzheng** [comment]
@peterix  thanks, I have managed to compile it on MSVC 64bit
