### ISSUE TITLE
Bizarre instance crash

### ISSUE THREAD

**Issue by Thewanildo** [MultiMC/MultiMC5#1131]
I'm trying to make my own private version of Resonant Rise 3 and when I try to add Optifine or some other mods it crashes ;-;
PLS HELP!
http://paste.ee/p/mEQVZ (CRASH LOG)

**Comment by peterix** [comment]
I'm very sorry, but the log is no longer accessible... I didn't get to it in time.

Things that might help:
* Updating optifine
* Removing optifine

Some other person had an issue with 1.7.10 optifine - it crashed together with Buildcraft 7

Can't offer you much else though.
