### ISSUE TITLE
"Updating assets index..." - bad java path

### ISSUE THREAD

**Issue by jilleJr** [MultiMC/MultiMC5#1133]
Noticed that if you have set an invalid java installation path then it fails to start and gets stuck showing _"Updating assets index..."_

![image](https://cloud.githubusercontent.com/assets/2477952/8729933/4c6c0fe6-2bee-11e5-93bf-2711e916f1fb.png)

I tested and invalid java path seems to be the only reason. 

![image](https://cloud.githubusercontent.com/assets/2477952/8730028/d3dea6b4-2bee-11e5-9429-e389011370be.png)

As seen in the example I just removed an `e` at the end of the `javaw.exe`.

My suggestion is that you add a check if the java path is valid before launching, and if not then give an error describing that its the path that's wrong. Instead of _"Updating assets index..."_ which is kinda missleading

**Comment by peterix** [comment]
Thanks for the reproduction scenario. Very helpful :)

**Comment by jilleJr** [comment]
Glad to help :+1:

**Comment by SummitSummit** [comment]
This just saved me pulling out my hair trying to figure out what the problem was.  Thanks so much!

**Comment by peterix** [comment]
In current develop, this is no longer the case.

However:
It would be nice if it said something other than
```
The process failed to start.
Could not launch minecraft!
```

**Comment by peterix** [comment]
I consider this done.
