### ISSUE TITLE
Crash Offendor: org/multimc/EntryPoint.main([Ljava/lang/String;)V

### ISSUE THREAD

**Issue by shader301202** [MultiMC/MultiMC5#1137]
When I tried to load my world, I had a crash with this error: "Offendor: org/multimc/EntryPoint.main([Ljava/lang/String;)V"
Crash log: https://paste.ee/p/VYmfP
I have Java 8 and Minecraft 1.7.10.

**Comment by Loetkolben** [comment]
This
```
[14:39:57] [Client thread/WARN] [FML]: =============================================================
[14:39:57] [Client thread/WARN] [FML]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[14:39:57] [Client thread/WARN] [FML]: Offendor: org/multimc/EntryPoint.main([Ljava/lang/String;)V
[14:39:57] [Client thread/WARN] [FML]: Use FMLCommonHandler.exitJava instead
[14:39:57] [Client thread/WARN] [FML]: =============================================================
```
is just Forge complaining MMCs MC Launcher uses the ```System.exit()```, this is not a problem!

I think your real problem is
>java.lang.IllegalArgumentException: Could not get provider type for dimension -7, does not exist

Did you remove any mod that adds a dimension? Check you configs to find the mod that provides / provided dimension ```-7```. Are you (the character) in this dimension?

**Comment by shader301202** [comment]
No

**Comment by shader301202** [comment]
I've deleted Factorization  and now is all OK :)

**Comment by shader301202** [comment]
I have the next crash:
http://paste.ee/p/vpLnF

**Comment by Loetkolben** [comment]
Does this happeb when you open an ingame GUI?
>java.lang.NullPointerException: Updating screen events
[...]
>Screen name: darkevilmac.archimedes.gui.GuiShip

**Comment by shader301202** [comment]
Yes

**Comment by shader301202** [comment]
Yes

**Comment by Kilobyte22** [comment]
Did you fix this yourself?

**Comment by Loetkolben** [comment]
If you fixed the problem, please post the solution so that others who have the same problem can find it.

**Comment by shader301202** [comment]
I've deleted "Archimede's Ships Plus" and now it works :)

**Comment by shader301202** [comment]
Or not: http://paste.ee/p/C5OyT :(

**Comment by TheDoctorsLife** [comment]
```
java.lang.NullPointerException: Unexpected error
	at cofh.tweak.asmhooks.render.RenderGlobal$RenderWorker.run(RenderGlobal.java:644)
	at cofh.tweak.asmhooks.render.RenderGlobal.func_72722_c(RenderGlobal.java:489)
```
I think cofh is the issue here.

**Comment by shader301202** [comment]
I hope no...

**Comment by Loetkolben** [comment]
Try a different version of CoFH core?

**Comment by shader301202** [comment]
Now it works.

**Comment by shader301202** [comment]
When I tried to load my world with Thaumcraft, I became a crash: http://paste.ee/p/fArBb

**Comment by shader301202** [comment]
Can you say me, why when I tried to launch my server, I became a crash? https://paste.ee/p/sIbeE

**Comment by peterix** [comment]
You got a clent-only mod on a server.

**Comment by shader301202** [comment]
Thanks :)

**Comment by shader301202** [comment]
I had  a crash on my server: https://paste.ee/p/ty8h4

**Comment by peterix** [comment]
Assuming fixed.

**Comment by shader301202** [comment]
I have the next crash: https://paste.ee/p/YZw2j
