### ISSUE TITLE
My Multimc is bugged 

### ISSUE THREAD

**Issue by Bruno12321** [MultiMC/MultiMC5#1138]
My multimc says when i try to load any game is that:Unable to acess jar file 

C:/My Name/Desktop/Games/MultiMC/jars/NewLaunch.jar

**Comment by 02JanDal** [comment]
Please upload the contents of `MultiMC-0.log` to pastebin or similar, and post the link here.

**Comment by Bruno12321** [comment]
All? There a lots of things Or just a part?

**Comment by 02JanDal** [comment]
All of it is best.

**Comment by Bruno12321** [comment]
ok im going now

**Comment by Bruno12321** [comment]
not gone

**Comment by Bruno12321** [comment]
I dont Know How PRTSC

**Comment by Bruno12321** [comment]
i will just copy and paste look

**Comment by 02JanDal** [comment]
Start by updating, you are running an older version (0.4.5).

**Comment by peterix** [comment]
No idea what happened here.

**Comment by peterix** [comment]
Sorry for the delay. It would seem github went a bit derpy there and their database entries got confused.

That's a legacy instance. I still have a few and they still work...

Now, the error above would suggest the `minecraft.jar` isn't actually there.

I would suggest re-creating it from scratch. Start with a new 1.4.7 instance. Add forge and the other jar mods using the MultiMC UI, then copy over any and all mods, configs and saves from the old instance.

**Comment by peterix** [comment]
Note that the new format does require you adding jar mods through the MultiMC UI. It won't magically pick up random files in an `instMods` folder, and it won't let you manually edit `minecraft.jar`. This is mostly to ensure that everything is in a well-defined state and things don't break in the future...

See:
https://github.com/MultiMC/MultiMC5/wiki/Instance-Version - 'Add Jar Mod'
And
https://github.com/MultiMC/MultiMC5/wiki/Jar-Modding
