### ISSUE TITLE
Option to renew cache

### ISSUE THREAD

**Issue by jilleJr** [MultiMC/MultiMC5#1140]
When downloading an instance using the `Import Modpack` option I've noticed it saves the zip file in a cache folder, and uses that file again if you try to download from the same link.

Now I would like a small checkbox for renewing the cache, i.e. downloading it again even if it exists in cache. Instead of having to locate the folder and remove the cached zip manually

Example:
![image](https://cloud.githubusercontent.com/assets/2477952/8787308/b1d45c4c-2f33-11e5-904e-3872f2286ef2.png)

**Comment by peterix** [comment]
This was actually a bug - it wasn't checking for updates on the server.

Fixed in develop.
