### ISSUE TITLE
Game exiting at Initialization stage

### ISSUE THREAD

**Issue by sblack101** [MultiMC/MultiMC5#1143]
I have been trying to create my own modpack for me and my mate to use. to my knowledge all of the mods i am trying to use are the right version and have all of the cores and api's needed to run them. When launching the game it runs up to the initialization stage but then crashes and exits with the exit code 1. How do i stop this from happening?

Here is the log - http://paste.ee/p/Ws6K1

Here is the crash report - http://paste.ee/p/egbPd

**Comment by jackrtades** [comment]
I have a similar problem. 

http://paste.ee/p/MlSEE

**Comment by Loetkolben** [comment]
@sblack101 Maybe try without "SimpleOres"?
>[17:41:16] [Client thread/ERROR] [FML]: Caught exception from simpleores
java.lang.NoSuchMethodError: alexndr.api.content.inventory.SimpleTab.<init>(Ljava/lang/String;Ljava/lang/String;)V

[...]

>cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: alexndr.api.content.inventory.SimpleTab.<init>(Ljava/lang/String;Ljava/lang/String;)V

@jackrtades You have a completely different problem, please open a new issuse.

**Comment by sblack101** [comment]
Simple ores was the problem and i learnt a valuable lesson at the same time add and test mods one at a time lol, thanks for the help for the help.
