### ISSUE TITLE
Crash at Preparing Native Libraries Stage

### ISSUE THREAD

**Issue by nanakisan** [MultiMC/MultiMC5#1144]
As per to title this happens http://paste.ee/p/OER4f  
  
Any and all instances that use 1.7.10 are now non-functional. It will always throw this issue in my face. I originally thought it was forge causing the problem. So using a straight up unmodified vanilla instance. This still happens as shown here http://paste.ee/p/M1XOR

**Comment by nanakisan** [comment]
For clarity on my part
Thinking this was a auth ticket error. I relogged into MC by rebuilding my credentials in MultiMC.
Tried making a brand new instance (1.6.4, 1.8, 1.8.3 all work)
Tried with and without forge as noted in original post

**Comment by RX14** [comment]
Looks like the minecraft download was corrupted to me, try deleting the versions folder in your multimc folder to redownload.

**Comment by nanakisan** [comment]
This comes up
Seems the file doesn't exist on their servers anymore. Can download later versions and older ones. Just not 1.7.10

Failed to download the following files:
http://s3.amazonaws.com/Minecraft.Download/versions//.jar

Reason:Job 'Libraries for instance 1.7.10' failed to process:
http://s3.amazonaws.com/Minecraft.Download/versions//.jar
Please try again.

**Comment by RX14** [comment]
Oops, I broke it more...

Try creating a NEW 1.7.10 instance and launching that, it should fix the existing ones.

**Comment by nanakisan** [comment]
Yep seems whatever caused this is gone now. Any insight as to how the 1.7.10 binary got corrupted?

**Comment by 02JanDal** [comment]
Could be anything, broken download, disk errors etc.

**Comment by RX14** [comment]
Either:
- the download got interupted (MultiMC crashed as it was downloading)
- disk errors
- your internet is bad

**Comment by nanakisan** [comment]
Honestly given the current status of my computer....the disk errors would not shock me in the slightest. Thank you for the assistance.

**Comment by RX14** [comment]
If you google for a bit you will find ways of checking your disk. If it's faulty, you are risking all the data on your PC.

**Comment by nanakisan** [comment]
For some reason or another. The possibility of corruption on data that is constantly used rises significantly. It is most apparent when playing league of legends for a solid hour or more. Hell league even tells me possible data corruption may have occurred xD  
  
Honestly by this point I am waiting for the system to die already.

**Comment by nanakisan** [comment]
anyway thank you for the help

**Comment by RX14** [comment]
1. Perform backups really regularly
2. Why not just get a new disk and install it yourself. HDD are cheap and easy to install. You could even get a SSD and a new HDD at the same time for a performance boost.

**Comment by nanakisan** [comment]
would have to have the money to do it 1st. Last I checked it was $85 for the new 1TB drive that fits my laptop. Not to mention HP wants an additional $25 so I can have the installation disk for my system. xD

**Comment by RX14** [comment]
You don't need the instalation disk if you have a windows 7 licence key, you should be able to download the iso from the internet. Also assuming your laptop fits sata 2.5 inch drives they are a bit cheaper than that.

**Comment by nanakisan** [comment]
Thanks I will look into it

**Comment by nanakisan** [comment]
10 to 1 will just install Linux

**Comment by RX14** [comment]
Eh, lots of games don't work on linux, so I wouldn't recommend it (coming from someone who uses linux). It's honestly easier to just reinstall windows 7. Also, Windows 10 is coming out in about 8 days, you should get a free upgrade from your current windows 7, then clean install Windows 10 on the new disk. This completely bypasses the need for a Windows 7 install disk, as Microsoft should offer Windows 10 iso to download on their website.

**Comment by peterix** [comment]
Just make sure the ISO is burned/written right... looking at those errors ;)

**Comment by RX14** [comment]
If you can, download and burn the disk on another PC.

**Comment by nanakisan** [comment]
Anyway thank you for the help and your ideas are quite noted. Now then back to resuming my modpack development. Peoples poor pathetic souls don't get tormented by themselves you know.

**Comment by peterix** [comment]
If you have a way of testing the current harddrive separately from your computer, I'd say do that, just to rule out that it's actually something else - like the SATA controller or something other than the drive.

**Comment by nanakisan** [comment]
Honestly I think it's just a corrupted driver that is causing my misery. I tested the drive and it came out with zero errors. Even CHKDisk says it's clean. I also did a massive defragmentation of the drive itself. The only thing I get as a clue to the whole bsod issue I have is MEMORY_MANAGEMENT x01a and NTFS_FILESYSTEM x024.  
  
I used to think it was the laptops memory failing. So I bought a 8gb upgrade for the system. Nope no issue there. so yeah...totally stumped. I honestly would rather just have a new laptop.

**Comment by RX14** [comment]
Yeah, this no longer sounds like a disk issue. Run a memory test like so:
1. Go to [memtest86.com](memtestx86.com).
1. Click on the link "Image for creating bootable USB Drive". This will download the file http://www.memtest86.com/downloads/memtest86-usb.zip for Windows.
1. Unpack the ZIP file.
1. Run the imageUSB.exe file and follow onscreen instructions.

**Comment by nanakisan** [comment]
Thanks let it run for roughly 5 solid passes and no fault was found. Took about 7 hours.

**Comment by RX14** [comment]
Well damn, i'm not sure then...

**Comment by nanakisan** [comment]
I'm just gonna say how awesome it was of you guys to sit with me and try to solve my laptops issues. Not often you get a service like that so I thank you immensely.

**Comment by RX14** [comment]
I was bored so *shrug*

**Comment by RX14** [comment]
For the interest, what program did you use to test your drive?

**Comment by nanakisan** [comment]
HD Tune, it was recommended to me by a good friend. Normally in these stupid instances I would go safemode and run Error checking on Windows. But safemode is currently unavailable to me as it locks up at graphics driver for my ATI-Radeon on my laptop.

**Comment by RX14** [comment]
Often manufacturers build in other tests to their HDD in addition to the normal S.M.A.R.T. tests. You could try finding out the manufacturer of the HDD and downloading a test program from their website.

Here looks like a reliable link for doing such tests: http://www.carrona.org/hddiag.html

The site also has a BSOD index, which seems quite useful:

- [MEMORY_MANAGEMENT](http://www.carrona.org/bsodindx.html#0x0000001A)
- [NTFS_FILE_SYSTEM](http://www.carrona.org/bsodindx.html#0x00000024)

Have you checked the physical memory usage of your computer when it BSODs?

**Comment by peterix** [comment]
Assuming this got fixed (as much as a hardware issue can be fixed :) ).
