### ISSUE TITLE
Portuguese translation don´t works in the launcher on win32!

### ISSUE THREAD

**Issue by Inky1003** [MultiMC/MultiMC5#1145]
Hi MultiMC team (sorry my bad english :-P)

I look issues with the portuguese translation. Look my launcher in english (rebooted)

http://j.mp/Multimc_english

But now, look my launcher in portuguese PT(rebooted too)

http://j.mp/Multimc_portuguesePT

And now my launcher in portuguese BR (rebooted too)

http://j.mp/Multimc_portugueseBR

Please if you don´t have an portuguese translation prepared please:

1-Contact me (I´m from Brazil)
2-Use crowdin (https://crowdin.com/)
3-If you don´t want these ones translate from an translator (a tip: https://translate.google.com/)

Thanks

Inky1003

**Comment by Heufneutje** [comment]
MultiMC uses [Weblate](http://weblate.robotbrain.info/projects/multimc/multimc5/) for translations. Feel free to help out with the translation if you like.

**Comment by Inky1003** [comment]
Thank you! @Heufneutje

**Comment by peterix** [comment]
Translations are a big mess right now... Infrastructure issues.

**Comment by peterix** [comment]
See: #1006

**Comment by peterix** [comment]
The translation server now runs at http://translate.multimc.org - feel free to use it. Sorry that it took this long to bring it back.
