### ISSUE TITLE
Suggestion: Connection to link an instance to a git repository

### ISSUE THREAD

**Issue by Krahazik** [MultiMC/MultiMC5#1147]
This is a suggestion as a new feature for MultiMC.

The ability to connect an instance to a git repository for version tracking and updating. We are using a github repository to manage our custom minecraft modpack and MultiMC as our launcher. It would be nice ot be able to connect the instance to the repository so that when we update the pack, the instance could be updated automatically or on command, and only donwload the files which have been changed/updated. Adding abd removing files appropriatly.

**Comment by ChaosTherum** [comment]
I'm going to second this suggestion.

**Comment by peterix** [comment]
Definitely a nice idea. And more likely to happen quickly than any of the other modpack related things.

**Comment by Kilobyte22** [comment]
You can probably already do that somewhat using a custom PreLaunch command

**Comment by jeep70** [comment]
Is this still in the cards? This feature would be very useful for me

**Comment by peterix** [comment]
@jeep70 definitely is.

This is something very desirable. We used git for versioning our own server pack at some point. It will be one of the possible ways to distribute and maintain packs.

Anyway, [Moved to workflowy (Ideas -> Packs)](https://workflowy.com/s/2EyDMcp7CU)
