### ISSUE TITLE
Default instance name when importing to something sensible

### ISSUE THREAD

**Issue by r3pbl4** [MultiMC/MultiMC5#1148]
Idk why but my multiMC dont want to import others modpacks. So to make sure that its bug I make my own export instanse using "Export Instanse" option. I am bad English so I make slide show step to step of my problem.

So to make sure that I cant import instanse I exported my inst.
http://i69.fastpic.ru/big/2015/0726/6f/d592a75c7292fea45292ca9e56c0936f.png

I save this on my desktop
http://i69.fastpic.ru/big/2015/0726/6f/d592a75c7292fea45292ca9e56c0936f.png
Then I choose this inst. to import it
http://i69.fastpic.ru/big/2015/0726/59/ecdb31607965a0568ca580fcf05c5959.png

....And "ok" button should be active, but it doesnt:
http://i70.fastpic.ru/big/2015/0726/c3/92785187c8968c49fcfa22a92340e8c3.png

I hope u understand my problem, and fix this:)

**Comment by peterix** [comment]
Give it a name.

**Comment by r3pbl4** [comment]
Name? What do u mean? Rename archive or modpack? If u about modpack it's already called "ZombiePZDC"

**Comment by peterix** [comment]
The OK button is not active because you didn't give the instance any name.

**Comment by r3pbl4** [comment]
Oh... I understand. U can make that if u dont write name, field for name will be red. Thanks, I will report my inattention to doctor-_-

**Comment by peterix** [comment]
Right now, it's defaulting to 'empty', which makes no sense
