### ISSUE TITLE
QuickMods?

### ISSUE THREAD

**Issue by jbdman** [MultiMC/MultiMC5#1151]
Can you still use 'quickmods' in the latest update? If not, my computer keeps throwing errors on building old versions, can somebody post a Mac OSX build of the latest version supporting quickmods?

**Comment by 02JanDal** [comment]
QuickMods have been discontinued in favour of "Wonko", which is a superset of QuickMods. It'll still be a bit until that's ready though.

**Comment by peterix** [comment]
Hmmm... still, I'd like to know how you used it and why.
