### ISSUE TITLE
[Suggestion] Updating LWJGL

### ISSUE THREAD

**Issue by spannerman79** [MultiMC/MultiMC5#1153]
Currently there is no "easy" method to update LWJGL within MultiMC so I have a suggestion.

Currently with the vanilla minecraft launcher for those on linux and mac there is even a shell script that can automatically update the 2.x branch of LWJGL ( [link](https://gist.github.com/aperson/2086385) ) but that just overwrites LWJGL fully with no ability to "roll back" 

May I suggest the option to "Install LWJGL" option - just like what you have within Edit Instance under Version for installing Forge and Liteloader.

You can find all of the LWJGL versions up to 2.9.3 on sourceforge [here](http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/) - which i found while digging into the linux/mac script i mentioned above.

I'd like to add one thing though - for this it be "clickable" have this set to the dev update branch **only** of MultiMC to reduce the amount of issues opened from kiddies not knowing what they are doing LOL

**Comment by peterix** [comment]
That is comming back at some point for sure.

**Comment by peterix** [comment]
Moved to workflowy, see Ideas -> 'LWJGL is a mess':
https://workflowy.com/s/2EyDMcp7CU

**Comment by peterix** [comment]
Well, this is technically in place, but you either have to package new versions yourself, or they need to be added to the metadata server and hosted somewhere.

In any case, I consider this done.
