### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by dewd777** [MultiMC/MultiMC5#1157]
I need to find my screenshots to get some gear refunded on a server i play on but i have no clue where they are, can someone please help me?

**Comment by peterix** [comment]
![screenshots](https://cloud.githubusercontent.com/assets/203326/9011955/4ce32120-37b1-11e5-952e-73d72e20476d.png)

Either edit instance or the console window when you have the instance running.

Other than that, in the instance folder: instances/whatever/minecraft/screenshots/*

**Comment by dewd777** [comment]
thank you man
