### ISSUE TITLE
Corrupted instance config file

### ISSUE THREAD

**Issue by C3sPO** [MultiMC/MultiMC5#1159]
Trying to get a friend to load an exported instance and he keeps running into the following error:

Failed to download the following files:
http://s3.amazonaws.com/Minecraft.Download/versions//.jar

Reason:Job 'Libraries for instance Test' failed to process:
http://s3.amazonaws.com/Minecraft.Download/versions//.jar
Please try again.

This is on multimc 0.4.8-dev-579.

**Comment by vecronatt** [comment]
same here but i have a different version i have the stable 0.4.7 version i dont know about others

**Comment by peterix** [comment]
Sounds like you have a corrupted instance config file without a set base version.

**Comment by peterix** [comment]
Make a new instance and transfer the relevant parts (mods, configs, saves) into it. You can also manually fix the config file.

**Comment by peterix** [comment]
Ideally, attach the instance.cfg from the instance folder here.

**Comment by 02JanDal** [comment]
No reply, closing.
