### ISSUE TITLE
Add support for alternative sites for uploading images

### ISSUE THREAD

**Issue by Arzte** [MultiMC/MultiMC5#1160]
For  example, I use shutter for my screenshots, & have it upload them to my VPS. I'd like to be able to do the same thing in multimc.

**Comment by Kilobyte22** [comment]
I second that.

**Comment by peterix** [comment]
Agreed.

And maybe we could improve imgur support...

**Comment by peterix** [comment]
Moved to workflowy (Ideas -> screenshot upload):
https://workflowy.com/s/2EyDMcp7CU
