### ISSUE TITLE
Offline mode is broken

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#1163]
It's broken. fix it.

It is impossible to switch to offline mode from the account dialog.
It must be tested - with the cables disconnected.

**Comment by sinanisler** [comment]
"peterix removed this from the 0.4.8 milestone on 14 Aug"

@peterix Why ?

**Comment by peterix** [comment]
AFAIK, this is not an issue without multiauth.

**Comment by sinanisler** [comment]
It would be nice if people able to use multimc offline 
but without auth I think they cant download mc files right ?

**Comment by peterix** [comment]
And offline, you can't download things either...

It's a bit confusing - a Minecraft server in 'offline mode' means it isn't doing auth. The offline mode in MultiMC is there for when you don't have an internet connection.

If you added an account before and have all the game data, offline mode works.
I've been thinking about adding an option for 'no auth'... But aside from a few valid, understandable use cases, it also makes the 'I want to pirate Minecraft' use case too easy.

So, for further discussion...
Offline mode = you don't have an internet connection.
No auth mode = you want to use Minecraft without logging in.

**Comment by peterix** [comment]
This is not a problem in the current codebase.
