### ISSUE TITLE
Hide account names but make them recognizable

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#1166]
Personal info on screen.

**Comment by Kilobyte22** [comment]
I'd suggest keeping first and last 2 chars and masking everything in in between. I'd make that a setting though. Not sure if enabled or disabled by default

**Comment by peterix** [comment]
I was thinking more along the lines of letting the user setting their own display name, if it's not provided by the account type (like a nickname or similar).

Hiding parts of the login should be a last resort kind of measure.

**Comment by Kilobyte22** [comment]
Sorry, mistapped.
That actually is a way better solution. Didn't even think about that.

**Comment by peterix** [comment]
Now partially hidden in develop.

* Account logins are gone from the selection drop-down.
* Account login is obfuscated when the auth token is invalid (re-login dialog).

TODO:
account selection when no account is default must use profiles instead of accounts!

**Comment by peterix** [comment]
Good enough for now, rest must be done in multiauth.

**Comment by peterix** [comment]
Split off the rest of the work here into a new issue.
