### ISSUE TITLE
Show how to make a symlink in the wiki

### ISSUE THREAD

**Issue by TheWhoAreYouPerson** [MultiMC/MultiMC5#1167]
I think it would be handy for an option to merge the assets/objects folder with the one in .minecraft, since they all have an ID there wouldn't be any conflicts, and this option could really help people with smaller hard drives, (I'm specifically thinking of SSD people without a huge HDD yet). I'm not sure whether this should be on or off by default. I would suggest off to remain the portable by default factor, users can always change it in settings.

**Comment by peterix** [comment]
There is nothing in any .minecraft

**Comment by peterix** [comment]
If you want to use the same folder elsewhere, consider using symlinks.

**Comment by peterix** [comment]
http://stackoverflow.com/questions/1951742/how-to-symlink-a-file-in-linux

http://lifehacker.com/5496652/how-to-use-symlinks-in-windows

**Comment by peterix** [comment]
Maybe it could be in the FAQ or the help wiki.

**Comment by TheDoctorsLife** [comment]
Done https://github.com/MultiMC/MultiMC5/wiki/FAQ
