### ISSUE TITLE
D&D of resourcepacks into MultiMC not working on OS X

### ISSUE THREAD

**Issue by 02JanDal** [MultiMC/MultiMC5#1178]
If the resource pack is a folder, on linux you can drag and drop it, on OS X you get the individual files. Zipping the folder doesn't work either.

MultiMC 0.4.8dev 579, OS X 10.9

The resource pack in question: https://dl.dropboxusercontent.com/u/23135995/N3XT.zip (issue both zipped and unzipped)

**Comment by pexner** [comment]
Workaround (but not nice, because d&d a folder should work also) : Click on "Open Folder" in Edit instance -> Resource packs -> Button "View Folder" and drag the Resource-pack folder into the opened folder.

**Comment by peterix** [comment]
There is no issue if you drag actual zip files. Make sure your browser is NOT automatically extracting them!

For loose folders/files, I managed to replicate the issue.

**Comment by peterix** [comment]
manually tested on OSX. The issue is gone.
