### ISSUE TITLE
Fix debian packaging

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#1179]
See comments:
https://github.com/MultiMC/MultiMC5/commit/bbba63eca5a0161a1b5b3bccb7af2070abc629db

**Comment by raphendyr** [comment]
I also started thinking that I could try to make real package. Would help distributing this to me and few friends.

I'll inform if I get that done.

**Comment by 02JanDal** [comment]
What do you mean by "real package"?

**Comment by peterix** [comment]
I assume a package with the binaries inside...

I'll just tell you: that won't be very fun experience unless your distro is pretty much bleeding edge.
