### ISSUE TITLE
Fix SSL

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#1180]
1. The MultiMC website uses SSL provided by cloudflare.
2. Cloudflare fails to charge my credit card every month
3. The site falls back to 'Free' tier and no SSL

This sucks, yell at cloudflare.

**Comment by peterix** [comment]
Related to #1179

**Comment by peterix** [comment]
Related also to:
https://github.com/MultiMC/MultiMC5/commit/bbba63eca5a0161a1b5b3bccb7af2070abc629db

**Comment by Kilobyte22** [comment]
I'm quite surprised at that. I do use free cloudflare myself and it does TLS by default.

**Comment by peterix** [comment]
I had to reset the option a few times because of the 'downgrade to free'. Maybe it is just some bug in whatever automation they have for it?

**Comment by raphendyr** [comment]
Could you contact their support and ask about it?

**Comment by peterix** [comment]
I will. It should happen on the 26th if it's still a problem.
