### ISSUE TITLE
Instance Crash

### ISSUE THREAD

**Issue by SethGodzhell** [MultiMC/MultiMC5#1182]
I cannot for the life of me figure out why this is crashing, and MultiMC keeps coming up in the logs. Can anybody help? http://paste.ee/p/7SSZY

**Comment by 02JanDal** [comment]
Please upload the full log using the _Upload Log_ button.

**Comment by SethGodzhell** [comment]
http://paste.ee/p/TdwYF

**Comment by 02JanDal** [comment]
Try renaming your instance to something not containing a space or a dash.

**Comment by SethGodzhell** [comment]
Made no difference

**Comment by peterix** [comment]
Looks like you have a mod for a different version of Forge or Minecraft than you have.

Also, you haven't updated MultiMC to the latest version. This means it doesn't print what mods you have into the log window... and I can't tell you which mod it is.

**Comment by peterix** [comment]
So, Update :)

**Comment by jikuja** [comment]
[1.8]bspkrsCore-universal-7.01 (2).jar and maybe others.

**Comment by peterix** [comment]
0.4.7 prints a convenient list on launch... anyway, you should be able to replace the mods.

**Comment by SethGodzhell** [comment]
The crash was related to inventory tweaks, and then there were a few mods that were a problem after that. It's all fixed, thank you guys for the support! I didn't realize that there was an update for MultiMC.
