### ISSUE TITLE
No Forge versions available for Minecraft 1.8.8 on OSX install

### ISSUE THREAD

**Issue by abaird** [MultiMC/MultiMC5#1191]
I installed a new version of MultiMC on Mac OSX and despite having ran minecraft at least once, I still am not able to download the list of forge versions.

Here is the logfile: http://pastebin.com/FVxPcjnN. What I did was:
1) start MultiMC
2) select Edit Instance on my vanilla version of Minecraft 1.8.8
3) Click the "Install Forge" button
-> here I get the "No Forge versions are currently available for Minecraft 1.8.8"

I've tried to install other versions of 1.8 Minecraft with the same issue. I can reproduce this on two machines running both Mavericks and Yosemite.

**Comment by abaird** [comment]
Solving my own issue here. Forge is (apparently?) not specified in the JSON file for versions above 1.8. If you change the version from (in my case) 1.8.8 to just 1.8 it loads the Forge versions just fine.

The key here is the log file line that says:
```
   33.191 D "latest" doesn't match. build 1502
```

Looking up build 1502 in the json file shows "mcversion": 1.8

**Comment by robotbrain** [comment]
There is no forge for versions above plain old 1.8.

**Comment by zackp30** [comment]
Has this changed at all?

**Comment by 02JanDal** [comment]
Just check it: http://files.minecraftforge.net/

Compare 1.8 to for example 1.5 (there is both 1.5, 1.5.1 and 1.5.2, but there's only 1.8, and not 1.8.8).

**Comment by zackp30** [comment]
Ah, okay. Thanks! (Very quick response as well. :smile:)
