### ISSUE TITLE
MultiMC 5 0.4.7 crashing: exitcode 1

### ISSUE THREAD

**Issue by MYRQNeuro** [MultiMC/MultiMC5#1192]
Could anybody please tell me what I'm doing wrong? I appreciate all your help very much! 

link to crash log: http://paste.ee/p/MoKLL

**Comment by peterix** [comment]
```
	UCHE	ForestryExtras{3.1} [Forestry Extras] (ForestryExtras-2-3.1_B29.jar) 
```

```
java.lang.NullPointerException
	at forestry.apiculture.genetics.BeeHelper.registerMutation(BeeHelper.java:250) ~[BeeHelper.class:?]
	at forestryextras.items.bees.BeeMutation.<init>(BeeMutation.java:31) ~[BeeMutation.class:?]
	at forestryextras.main.init.FEBees.initMutations(FEBees.java:571) ~[FEBees.class:?]
	at forestryextras.main.init.FEBees.init(FEBees.java:47) ~[FEBees.class:?]
	at forestryextras.main.Main.init(Main.java:49) ~[Main.class:?]
```
Looks like your version of ForestryExtras is not working with your version of Forestry or ForestryExtras is buggy.

**Comment by peterix** [comment]
Someone is maintaining a fork of FE2:
https://github.com/wmrojer/FE2-1.7

Not sure if there are any builds, but it has some fixes in the code already.

**Comment by MYRQNeuro** [comment]
Thank you! I'll try that one!

**Comment by peterix** [comment]
The fork is just slightly updated (last change is ~2 months ago) and the mod looks like it needs a new active maintainer:
https://github.com/wasliebob/FE2-1.7/network

If you can't find or make a new build, maybe one of the existing ones would work with an older version of forestry.

YMMV

**Comment by MYRQNeuro** [comment]
I would have no idea about making a new build. I'm very new to modding and such, which is why I come here for help. :) Would love to learn one day! If it doesnt work, I'll work around it and see if I can find anything similar. Thanks for your help, peterix! :)
