### ISSUE TITLE
Will not install on Mac OX 10.10

### ISSUE THREAD

**Issue by Timetravler** [MultiMC/MultiMC5#1193]
I'm using a mac notebook with OS X 10.10. I downloaded the Mac version of MultiMC5. it will not install, I get the following error "Safari can’t open the file “mmc-stable-osx64-2.tar” because no available application can open it."
Please help.
Thank you

**Comment by peterix** [comment]
I think Safari tries to unpack archives and packed files by default... And doesn't understand that .tar.gz is actually an archive. Other browsers won't do this.

See:
http://apple.stackexchange.com/questions/961/how-to-stop-safari-from-unzipping-files-after-download

OSX should include a tool for extracting archives (https://en.wikipedia.org/wiki/Archive_Utility). You should be able to use it outside the browser.

**Comment by Timetravler** [comment]
I bypassed Safari and went directly to the download file and clicked on the download. It now gives me the error "You can’t open the application “Zipeg.app” because PowerPC applications are no longer supported."

**Comment by peterix** [comment]
Nice... I guess you had that archiver tool and just upgraded to a newer intel-based machine?

I'd say remove that app and install a new version of it.

**Comment by Timetravler** [comment]
a recommendation for an app?

**Comment by peterix** [comment]
None, really. I've never used a mac. But this seems like a useable unarchiver tool:
https://itunes.apple.com/en/app/the-unarchiver/id425424353?mt=12

**Comment by Timetravler** [comment]
Got it !!!   Thank you !  
New problem lol
I am starting a new instance, down to the part of importing a mod pack. Used the button to find the file, clicked on the file but it does not move it to the window, just opens the mod file. Does not put anything in the window.

**Comment by peterix** [comment]
I don't quite understand what you're doing. Ideally attach a screenshot or two :)

The import option works only with previously exported MultiMC instances.

There's also the FTB tracking feature, which means FTB packs you've downloaded using the FTB launcher are also visible in MultiMC.

Everything else is more of a manual process.

**Comment by 02JanDal** [comment]
Assuming fixed, closing.
