### ISSUE TITLE
XCB: Unknown request in queue while dequeueing

### ISSUE THREAD

**Issue by Derpford** [MultiMC/MultiMC5#1198]
When launching an instance, Minecraft finishes pre-init and then hangs with the following error:
>[xcb] Unknown request in queue while dequeuing
>[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
>[xcb] Aborting, sorry about that.
>java: xcb_io.c:179: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.

I'm running Arch Linux, 64 bit.

**Comment by peterix** [comment]
Use the 'Upload' button to upload a full log.

**Comment by Derpford** [comment]
http://paste.ee/p/4UZDC

Here's a log showing the latest attempt at running it. I've since switched distros and updated to MultiMC 5, but I still get this problem.

**Comment by Derpford** [comment]
http://paste.ee/p/k7LDH
Another log. Still having this problem.

**Comment by peterix** [comment]
Try disabling the forge loading screen. It setting should be in a file named splash.properties.
Change the `enabled=true` line to `enabled=false`.

**Comment by Derpford** [comment]
It worked!
