### ISSUE TITLE
java path error (windows 10?)

### ISSUE THREAD

**Issue by tschmeltzer** [MultiMC/MultiMC5#1199]
Hi,

Ever since updating to windows 10, i cant seem to start any minecraft instances. when i try, i get the following and it just hangs there:

```
MultiMC version: 0.4.7

Minecraft folder is:
C:/FTB/direwolf20_17/minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_25/bin/javaw.exe

The java binary "C:/Program Files/Java/jre1.8.0_25/bin/javaw.exe" couldn't be found. You may have to set up java if Minecraft fails to launch.
Checking Java version...
```

The path is correct, but if i copy paste the address it's not there...
From what i can figure out the slashes are turning wrong for windows filepaths. 
Shouldn't it be \ and not the other way / ?

**Comment by peterix** [comment]
The paths are OK.

It shouldn't be trying to use something that it already determined doesn't exists...

Try the develop version - you can switch to it in the settings.

Also in settings - specifically the java part of the settings, you can click the auto-detect button. This should find a usable java version if you have any.

**Comment by peterix** [comment]
Why I'm suggesting 'develop': the whole launch process significantly changed compared to the 'stable' version.

**Comment by tschmeltzer** [comment]
"solved" kinda.

I reinstalled java, and now it's working. didn't change anything in multimc.

Sorry to have reported nothing.

Not sure why it changed anything though.

**Comment by peterix** [comment]
People have been reporting various issues caused by the win10 upgrade.

I think Windows is overriding some file permissions during the upgrade (like making Program Files not writable by users) and it makes things behave strangely.

**Comment by Heufneutje** [comment]
I have noticed similar things with regards to Program Files permissions so I can confirm this.
