### ISSUE TITLE
Config editing in launcher (MMC 6?)

### ISSUE THREAD

**Issue by Robijnvogel** [MultiMC/MultiMC5#1200]
Big feature suggestion (for MultiMC 6 perhaps?):

Editing config files for mods inside/opening them from within the MultiMC Launcher.
This would make editing config files a lot easier. You may be able to automatically pair them with the mods so people do not have to search the config folder by hand. Maybe you could even use the standard Forge config format reader to make it into a neat interface within MultiMC.
I know, I know... I am a lazy man.

Thanks for reading this!

**Comment by peterix** [comment]
Thought about doing this already... This is not practical to do without some sort of reliable mod metadata. Which currently doesn't exist.

So... later.

**Comment by Heufneutje** [comment]
Forge has already implemented an in-game thing for this, although not every mod author really uses it...

**Comment by peterix** [comment]
And it's super clumsy to navigate through the overly large and non-native UIs...

**Comment by Robijnvogel** [comment]
Barely any mod author uses that function in my experience.

I see the difficulties in the implementation, but oh well, at least the suggestion is documented now.

**Comment by peterix** [comment]
Well, I used it in my Friendsss mod :)

I think this can be done in two steps:
1. Just list the configs found in the instance and let the user open them comfortably
2. Add an UI that can work with those configs

The UI would require the config structure to be modelled similarly to XML internally. Then it would use something similart to XPath to bind UI elements to paths within the config.

The config 'layouts' could be then updated separately from the application and possibly be user made.

Another idea I came up with is config snapshots, so you can snapshot your configs while working on them.

[Moved to worflowy (Ideas -> Game and mod config editor)](https://workflowy.com/s/2EyDMcp7CU)

**Comment by Robijnvogel** [comment]
So was this implemented or was this cancelled? 
Was this reduced to a button to open the config folder directly from MMC?

**Comment by peterix** [comment]
I mass-closed all feature request and idea tickets on github.

In general, I think this is doable, but would require constant maintenance - there is no standard config format.
Integrating with a separate project with its own maintainer(s) who are dedicated to keeping it working with everything out there would work.
Someone picking this up and doing it within MultiMC would also work.

I just don't feel like doing it myself, I lack the motivation to maintain something like this.
