### ISSUE TITLE
Support streaming/piped log filtering

### ISSUE THREAD

**Issue by SoniEx2** [MultiMC/MultiMC5#1201]
Add support for opening a shell script/something to filter logs (both before and after MultiMC's personal information filtering).

It should pass the logs into the script's stdin and read from the stdout.

Maybe set some environment variables such as `MMC_INSTANCE_NAME`, `MMC_INSTANCE_PATH`, etc?

**Comment by SoniEx2** [comment]
It could also support commands e.g. instead of just passing the raw log out, you'd have to use `print <line>`.

Or if we ever add log separation stuff, `openlog <logid>` and `printto <logid> <line>`, e.g. `openlog chat` and then `printto chat <SoniEx2> my message` :>

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Logging)](https://workflowy.com/s/2EyDMcp7CU)
