### ISSUE TITLE
SSL Error When Using Firewalled Laptop

### ISSUE THREAD

**Issue by bkeeneykid** [MultiMC/MultiMC5#1202]
On mac, while using a firewalled laptop (Blue Coat Unified Agent to be precise) I cannot login due to a SSL handshake error. The two certificates mentioned in the error log (http://pastebin.com/4NVXg6VE) both have custom trust settings in the Keychain Access app (see attached picture). They are set to always trust, but the error log says it cannot trust the CA certificate for this purpose. Is this a problem with MultiMC or one of it's libraries, like Qt? I have set Java to trust this root certificate by modifying the cacerts file with keytool. 
![image](https://cloud.githubusercontent.com/assets/10481864/9373818/475cf8ae-46b4-11e5-9b3f-4dd0c2615f76.png)

**Comment by peterix** [comment]
Possibly related:
https://forums.aws.amazon.com/thread.jspa?messageID=651274

Also possibly related:
https://bugreports.qt.io/browse/QTBUG-23625

**Comment by peterix** [comment]
This will need a workaround.

**Comment by peterix** [comment]
Hello again, can you test the latest develop build?

**Comment by peterix** [comment]
I'm going to assume 'Yes'.
