### ISSUE TITLE
No Forge Versions for 1.7.10

### ISSUE THREAD

**Issue by spannerman79** [MultiMC/MultiMC5#1205]
MultiMC 0.4.7
Build 561 (stable)
Title and screenshot says it all

![capture](https://cloud.githubusercontent.com/assets/7542384/9421323/7715c33a-48b4-11e5-8733-020a13e2f148.PNG)

Same issue with dev update channel (0.4.8-dev-617)

**Comment by peterix** [comment]
http://files.minecraftforge.net/maven/net/minecraftforge/forge/json is broken. Forge infrastructure bug.

**Comment by spannerman79** [comment]
Ggrreeaatt......
I suppose there is no "simple" way to add in 10.13.4.1448 otherwise?

**Comment by peterix** [comment]
Lemme see if I have a json file around here somewhere...

**Comment by spannerman79** [comment]
:+1: I'd appreciate it.

I assume (if you do have one) it simply goes into `MultiMC\mods\minecraftforge` ?

**Comment by peterix** [comment]
That would be wrong

**Comment by peterix** [comment]
In the instance, put this into `patches/net.minecraftforge.json`:

https://gist.github.com/peterix/157b11485e13e76cf3d5/

**Comment by peterix** [comment]
Hopefully the forge peoples fix it soon :)

**Comment by peterix** [comment]
https://twitter.com/LexManos/status/634876908493082624

**Comment by spannerman79** [comment]
> In the instance, put this into patches/net.minecraftforge.json:

Awesome - thanks!

> Hopefully the forge peoples fix it soon :)
> https://twitter.com/LexManos/status/634876908493082624

Yeap they will get around to it now though. LOL @ Twitter status though.

**Comment by spannerman79** [comment]
Fixed and working (forge issue resolved)
