### ISSUE TITLE
Cannot update anymore (to 0.4.8)

### ISSUE THREAD

**Issue by lstep** [MultiMC/MultiMC5#1206]
```
Couldn't remove file bin/libQt5X11Extras.so.5. Changes were reverted.
See the MultiMC log file for details.
```
There is a `MulitMC/update/backup/` directory, but it is empty, so moving to `backup/bin` fails

**Comment by robotbrain** [comment]
Had the problem 5 minutes before you posted this. Confirmed.

**Comment by peterix** [comment]
Can you post the MultiMC log from the update?

**Comment by peterix** [comment]
Nevermind.

New builds coming right up :)

You will have to update manually.
