### ISSUE TITLE
Cannot see chat.

### ISSUE THREAD

**Issue by TaleOf4Gamers** [MultiMC/MultiMC5#1209]
Earlier today my MultiMC updated to the latest version. (I have dev updates enabled.) and now when I join a server the only things I see in chat are any update notifications for Mods.
I cannot see anything else.
My mods were working before without any issues before updating MultiMC.

MultiMC version: 0.4.8 dev-621.
Mods:
Forge
Optifine
HUDPixel Reloaded.

Thanks in advance.

**Comment by peterix** [comment]
And what happens if you use the stable version?

**Comment by TaleOf4Gamers** [comment]
Never mind I fixed it.
I started a new Minecraft instance and simply reinstalled my mods it started working .
Sorry for the time wasting. ;)
Was a little odd though tbh.

**Comment by peterix** [comment]
Must be some config issue then... If you used something like windiff, meld or other such tool, you might be able to see what's different.
