### ISSUE TITLE
Downloading stops at Getting the library files from Mojang

### ISSUE THREAD

**Issue by PGhostCZ** [MultiMC/MultiMC5#1210]
Hello,

I like to download the latest snapshot everyday and try everything out to not be suprised in the relase. However, a week ago I started experiencing this; I am downloading the latest snapshots, it's getting library files and everything seems OK. Suddenly, that progress bar just stops, always in the range from 40% to 60%, never less, never more. Somehow I always manage to download Minecraft by killing MultiMC using Task Manager, then launching it over and over again, it takes about 20 minutes to finally download Minecraft. Any ideas why does this happen and how to fix it?

**Comment by peterix** [comment]
Check/upload the MultiMC log. It writes one to the same folder it resides in.

MultiMC-0.log is the current, higher numbers are from previous runs.

It should show any errors it's running into.

**Comment by PGhostCZ** [comment]
Alright, I don't understand logs, so, here you go: http://pastebin.com/PMeCS2MG

**Comment by peterix** [comment]
OK... and this is from a run that is stuck?

Anyway, if it isn't, try to do this again with a stuck download.

Another thing you could try is switching to the develop version (it's in the settings, then click the update button). The launch and update stages were rewritten there.

**Comment by PGhostCZ** [comment]
That's weird...
I tried to update MultiMC, it has stuck as well. I killed it, launched it again and accidentaly launched snapshot. It downloaded without any problems.
Brain.exe stopped working.

And yes, that log was that from the stuck run.
