### ISSUE TITLE
Download files in the background when editing instance

### ISSUE THREAD

**Issue by WebFreak001** [MultiMC/MultiMC5#1211]
When I change the Minecraft version it shows a progressbar on top of the window that blocks any operations. It would be nice to have it download in the background because it can take much time depending on internet connection. And one can edit everything else while it downloads.

**Comment by peterix** [comment]
True.

**Comment by marioandluigi878** [comment]
hmm nice idea

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Asynchronous downloads and download management)](https://workflowy.com/s/2EyDMcp7CU)

This is a huge overhaul, waiting to happen.
