### ISSUE TITLE
Minecraft doesn't launch

### ISSUE THREAD

**Issue by Alex2740** [MultiMC/MultiMC5#1212]
When I Launch an instance Minecraft doesn't launch and a windows where whrite : 
"MultiMC version: 0.4.7

Minecraft folder is:
C:/Program Files (x86)/MultiMC/instances/normal/minecraft

Java path is:
java

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx2048m, -Duser.language=en, -jar, C:/Program Files (x86)/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 20756

Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Game exited with exitcode 1." appear.
What do I need to do to solve the problem please?

**Comment by Heufneutje** [comment]
You're most likely trying to give it too much memory since you're using 32-bit Java. I would recommend installing 64-bit Java and then going into MultiMC's settings -> Java tab -> Autodetect and selecting the 64-bit Java.

**Comment by Alex2740** [comment]
thanks it works
