### ISSUE TITLE
MD5 hash of mods next to log file output

### ISSUE THREAD

**Issue by spannerman79** [MultiMC/MultiMC5#1218]
I am not exactly sure if this can be done so I'll try to be clear.

In the MultiMC log file one of the great features is within the log it lists all the mods.  One thing I would like to suggest is that next to those mods a MD5 hash is displayed for those mods.

This could be used check to make sure that the mod is correct (the mod file listing on curse forge has a MD5 hash detail on each file that can be used for comparison.

I'm not expert in programming but I did notice that you use Qt5, and a quick google search and I came across [this](http://doc.qt.io/qt-5/qcryptographichash.html)

**Comment by peterix** [comment]
That would be quite simple to add in a trivial way (not caching the hashes).

Caching the hasehes would need a bit more infrastructure.

Ultimately, I'd like to use SHA-256 for *identifying* files:
http://stackoverflow.com/questions/4014090/is-it-safe-to-ignore-the-possibility-of-sha-collisions-in-practice

**Comment by spannerman79** [comment]
Yeah me too - but until places like Curse Forge move to SHA-256, to prove to another mod author (if mod usage is in question) like what I posted over at https://github.com/TehNut/MoreChisels/issues/25#issuecomment-135984316 MD5 will have to do.

This way even the pasted log shows the MD5 hash, the mod author looks at the hash, compares it to their own records (or external) and sees its identical.

**Comment by peterix** [comment]
No, I'm going to build a system based on sha-256 hashes that uniquely (or very close to that) identifies files. I might just do md5, sha1 and sha-256 at the same time and make it an option which to display.

**Comment by peterix** [comment]
Because then you can map the sha-256 hash back to what the thing is - its metadata...

It will be useful Soon (TM)

**Comment by spannerman79** [comment]
If CPU usage is an issue for generating the hashes make it an option that is disabled by default, accessible to be enabled via Settings?

I have no idea what the actual CPU overhead will be in this case.  Personally I would have it enabled :smile:

**Comment by peterix** [comment]
Nah. It should just be cached and not done until the output is actually needed.

**Comment by peterix** [comment]
Alright, moved this idea to workflowy (Ideas -> Logging -> Add md5...):
https://workflowy.com/s/2EyDMcp7CU
