### ISSUE TITLE
Resource Pack Workbench support?

### ISSUE THREAD

**Issue by spannerman79** [MultiMC/MultiMC5#1219]
Github location: https://github.com/MightyPork/rpw

I want to stay as much as possible away from the vanilla minecraft launcher - hence why I am suggesting this.  But for RPW to work @MightyPork doesn't know how MultiMC works as per https://github.com/MightyPork/rpw/issues/29#issuecomment-105323490

I would consider this more of a "nice to have" capability.

**Comment by MightyPork** [comment]
Let me just clarify how (currently) RPW loads assets:

1. Look for profiles in the `.minecraft/versions/` folder, offer user to select version
2. Find key `assets` in the version JSON
3. Extract assets from the Jar file in selected version
3. Go to `.minecraft/assets/` and from the objects repository fetch corresponding assets, which are aded to stuff extracted from the Jar.
4. Look if there's any mod files in `.minecraft/mods`, and offer to also load assets from them.
5. Finally, RPW saves a structure file & all the copied assets into it's library folder.

This stuff is implemented mostly in [TaskReloadVanilla](https://github.com/MightyPork/rpw/blob/dev/src/java/net/mightypork/rpw/tasks/TaskReloadVanilla.java) and [SequenceReloadVanilla](https://github.com/MightyPork/rpw/blob/dev/src/java/net/mightypork/rpw/tasks/sequences/SequenceReloadVanilla.java) (those are launched from [Tasks](https://github.com/MightyPork/rpw/blob/dev/src/java/net/mightypork/rpw/tasks/Tasks.java#L630)).

If someone sends a PR (NOTE: to the dev branch, please!) that adds MultiMC support, I'll happily merge it.

**Comment by peterix** [comment]
1. does not exist in the vanilla form and nothing should depend on it - it would not be wise.
2. can supply this
3. can supply the jar path
4. can supply the resources path
6. and the mods folder path

So RPW needs the assets key, jar path, assets folder path and mods folder path.
Note that these vary wildly between instances. There is no '.minecraft' anywhere.

If you can work with multiple different instances and not have global state, it will make things easier.
If you can work with files without copying them around, it would be ideal.

**Comment by peterix** [comment]
Basically, any sort of integration should go the other direction - from MultiMC to external tools... simply because I wouldn't want you to depend on MultiMC's internal state, file formats and folder layout.

**Comment by peterix** [comment]
It's the same way with MCEdit - instead of MCEdit having to know about MultiMC, we call it with the save folder it should use. This is less work on both sides.

**Comment by MightyPork** [comment]
> If you can work with multiple different instances and not have global state, it will make things easier.

That's actually a good idea, would mean implementing Eclipse-style workspaces, each with it's own library. Means extra disk space used, but would make RPW more versatile...

>If you can work with files without copying them around, it would be ideal.

Not really... there's fines in the Jar, and I need to fetch them for preview / copying to Respack project... After the initial assets extraction, it doesn't matter if the MC folder is deleted or changed.

Ideas:

If there was a file with the paths (perhaps INI or JSON) , then RPW could ask user to locate this file, and RPW would use the paths for extracting.

Or if the paths are the same in each ".minecraft" instance (honestly I don't understand why it's not all in one place), then RPW can map to that and the file is not needed - but it will of course break when the paths are changed in some future version.

**Comment by 02JanDal** [comment]
Ideally, RPW should be invoked with the data needed, either through cli switches or a file like you mentioned. This is how the AMIDST integration worked (never merged because the author responds so slow).

> honestly I don't understand why it's not all in one place

The entire idea behind MultiMC is to have separate instances. So that you can have an instance with Minecraft 1.5.2 and one with 1.7.10, both with mods, at the same time (with all in one places the mods would get mixed up, resulting in a crash).

**Comment by spannerman79** [comment]
> honestly I don't understand why it's not all in one place

Because people like me are sick of things like;

*  Everything thrown into %AppData% when there is no need for it.  I don't want to buy a new SSD *just* for minecraft when I can run it from an iSCSI drive (on my to do list) via MultiMC
*  Easier to install Liteloader and Forge into each instance - *at will* very easily with just a couple of clicks of the mouse
*  Support to upload log files directly to paste - saves having big long arsed posts where people are too lazy to use a paste service before making issues.

There is much more but in short - using vanilla minecraft after using MultiMC feels like going back to rubbing two sticks together to make a fire.

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Integrate Resource Pack Workbench)](https://workflowy.com/s/2EyDMcp7CU)
