### ISSUE TITLE
SSL error with duplicate certs.

### ISSUE THREAD

**Issue by chrisbecke** [MultiMC/MultiMC5#122]
Scenario: 
I am behind a corporate firewall. For one reason or another there are TWO CA certificates installed with identical subjects in the windows root CA store.
Normal windows apps try both certificates, but MultiMC is only trying (the incorrect) one, resulting in a SSL handshake error when attempting to create an account / log in.

**Comment by peterix** [comment]
Please reopen this issue if it is still a problem in the current version.
