### ISSUE TITLE
linux version can't find itself

### ISSUE THREAD

**Issue by syi666** [MultiMC/MultiMC5#1221]
I usually do $HOME/Downloads/MultiMC 
then ./MultiMC
and the program will launch, that's how I've been doing it for months. Now it refuses to find itself

**Comment by spannerman79** [comment]
"Usually" home is `~/`
Your environment (or bash profile) has changed - this is something you will need to fix/look into as this is not a MultiMC issue.

In terminal window do `cd ~/Downloads/MultiMC` first
