### ISSUE TITLE
Stuck after loading instance with wrong java path

### ISSUE THREAD

**Issue by Yavos** [MultiMC/MultiMC5#1222]
I recently downloaded a MutliMC Minecraft instance to import into my version. In that instance there was a setting for a specific java path that is not available on my system.

The console then keeps being stuck telling me that the Java-Binary couldn't be found and that I should choose a Java version. It does not give me any option to do so however. There's also no way to terminate that process other than killing the task.

You can recreate this by changing the instance-java-path to any non existent file.

I consider this a bug. Proper behaviour would be to terminate the process or give me an option to actually choose a working Java version.

I'm running version 0.4.7

**Comment by peterix** [comment]
This is fixed in develop.
