### ISSUE TITLE
Wrapper script ignored

### ISSUE THREAD

**Issue by mpavkovic** [MultiMC/MultiMC5#1223]
I've created a wrapper script so I can run Minecraft with primusrun (Linux utility that allows you to run programs on dedicated Nvidia GPU instead of integrated Intel GPU), but it seems that MultiMC is completely ignoring it.

Here is what I've set for a wrapper command:
`/home/mpavkovic/MultiMC/primusrun_java.sh`

Script exists and has executable bit set. This is the content of the script:
```
#!/bin/sh  
vblank_mode=0 primusrun /usr/bin/java "$@"
```

I'm have the latest version of MultiMC from development channel, 0.4.8-dev-587

**Comment by peterix** [comment]
Does the same script work on the stable version?

**Comment by mpavkovic** [comment]
No, it doesn't. I've even changed wrapper command to a non-existing script, expecting it to fail on launch, but nothing happens.

**Comment by peterix** [comment]
Does the instance have a per-instance override set?
Are you setting this in the per-instance settings, or globally?

**Comment by mpavkovic** [comment]
Globally. I don't see an option to change a wrapper script per instance.

![screenshot - 09032015 - 02 45 25 pm](https://cloud.githubusercontent.com/assets/803875/9658532/78df3454-524a-11e5-87e8-993aed4108af.png)

**Comment by peterix** [comment]
This should now be fixed in develop.

**Comment by mpavkovic** [comment]
Great. It works now! :+1: 

I only had to slightly change my wrapper script
```sh
#!/bin/sh  
vblank_mode=0 primusrun "$@"
```

**Comment by peterix** [comment]
Alright :)
