### ISSUE TITLE
Asset download errors are not reported as errors.

### ISSUE THREAD

**Issue by chrisbecke** [MultiMC/MultiMC5#123]
My corporate firewall has blocked (Temporailly I hope) access to resources hosted on minecraft.net

Attempts to access
http://resources.download.minecraft.net/c1/c109b985a7e6d5d3828c92e00aefa49deca0eb8c
are, instead of the assed, given a http 304 response directing to an error page. MultiMC is reporting that the asset was successfully downloaded in MultiMC-X.log, consequently corrupting the install.

**Comment by peterix** [comment]
Redirects are now handled and we are checking the checksums I think... soo. Closing.
