### ISSUE TITLE
MultiMC does not include image manipulation libraries

### ISSUE THREAD

**Issue by Derpford** [MultiMC/MultiMC5#1231]
Running on 64bit Void Linux. Having a couple of problems.
The first is that there isn't really a package to install libpng12, which is apparently the version you're using. All I had to do was link libpng16 (current version) to libpng12.so.0, but that's something you might look into fixing further down the line.

The current, more pressing problem, however, is this:

>Error: MultiMC is missing the following libraries that it needs to work correctly:
>	/home/derpford/MultiMC/plugins/iconengines/libqsvgicon.so:, /home/derpford/MultiMC/plugins/imageformats/libqgif.so:, /home/derpford/MultiMC/plugins/imageformats/libqico.so:, /home/derpford/MultiMC/plugins/imageformats/libqjpeg.so:, /home/derpford/MultiMC/plugins/imageformats/libqsvg.so:, >/home/derpford/MultiMC/plugins/platforms/libqxcb.so:, 
>Please install them from your distribution's package manager.

I'm...not sure what these libraries are, but I do know that they're where they claim to be--each of the mentioned libs are in their directories, just as the error describes them. This is very odd.

**Comment by peterix** [comment]
Odd. Haven't seen this pop up on IRC.

I assume these are actually not loading because something else is missing/broken. Like the libpng.

One way to check is to just use `ldd` on the libraries and see what they need.

**Comment by Derpford** [comment]
On libqxcb:
>libxcb-sync.so.0 => not found
On libsvgicon:
>libQt5Svg.so.5 => not found
In the imageformats folder:
>libQt5Svg.so.5 => not found

So I need libQt5Svg and libxcb-sync.

**Comment by peterix** [comment]
See, all thouse should already be included

**Comment by peterix** [comment]
Your best bet right now is to get libpng12 from a different distro and put it in the MultiMC bin folder.

**Comment by Derpford** [comment]
I've gotta wonder why on earth these libraries wouldn't be included. There
has to be some mistake.

I'll just have to use a different launcher for a little while.

*--Chris Scott*

**Comment by peterix** [comment]
They are included.

**Comment by Derpford** [comment]
This is most baffling.

*--Chris Scott*

**Comment by peterix** [comment]
So the idea would be to add libpng, libjpeg and friends...

**Comment by peterix** [comment]
For now: if you add this library to the MultiMC `bin` folder, it should help.

http://www.megafileupload.com/9ivE/libpng12.so.0

I took it from the Ubuntu 14.04 libpng12 package

**Comment by Derpford** [comment]
Success. Maybe that file needs to be added to the bin folder in the
download?

*--Chris Scott*

**Comment by peterix** [comment]
Yep
