### ISSUE TITLE
Feature Request: Text About

### ISSUE THREAD

**Issue by JavaGamer** [MultiMC/MultiMC5#1237]
This Is Just a Small feature,When You Click On The Mod There a About Section
![6fuydkhwysdk8yfrgfwhduy8fuasiao](https://cloud.githubusercontent.com/assets/5355337/9829071/f7a31d90-58bd-11e5-9b37-e06ebc4d885b.png)
I Just Asking That I Can Copy It For My Use

**Comment by peterix** [comment]
That's a good idea, and easy to do :)

**Comment by JavaGamer** [comment]
Thanks.

**Comment by peterix** [comment]
Alright.

You won't be able to select both the top part and the bottom part at the same time. They are different text areas... Anyway, this is now implemented in develop.

See builds:
http://ci.multimc.org/waterfall
