### ISSUE TITLE
Add reddit button

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#1238]
So it's not a ghost town.

**Comment by RegisDeVallis** [comment]
Just discovered /r/MultiMC, and subbed. You should probably make a post in /r/Minecraft covering why people should switch, and make a sticky post in /r/MultiMC giving an overview of what it is and why people should use. It might be a good idea to link the git to both those posts so other people see how active this project is. 

Also, if you ask, the /r/minecraft mods might link your subreddit on their Other Links section in the side bar. 

Just a suggestion, my reddit is /u/Regis_DeVallis. I browse reddit more often than github, (not a surprise), and I could help out if you need it.

**Comment by peterix** [comment]
That's sounds better than just surprising everyone with a new mystery button :)

**Comment by peterix** [comment]
We actually seem to need a license for having the icon in MultiMC:

https://www.reddit.com/about/alien/

**Comment by RegisDeVallis** [comment]
You could have a drop down menu in the launcher called something like "Links", and reference the website, github, and reddit page there.

**Comment by peterix** [comment]
No need for that yet. There's plenty of space in the main toolbar.

**Comment by peterix** [comment]
Sent the e-mail to  licensing@reddit.com

Let's wait and see :)

**Comment by RegisDeVallis** [comment]
Sweet. Can't wait to see the response. 

Also, since your here, I am happy to help with the project, but I have very little experience and only know java.

**Comment by peterix** [comment]
They didn't respond. I assume that means it's OK.

This is still an open issue because I didn't do all the other things like posting a sticky on the MMC subreddit.

**Comment by peterix** [comment]
I made a sticky post with links to all the different places.

**Comment by peterix** [comment]
https://www.reddit.com/r/MultiMC/comments/40eane/hello_and_welcome_to_rmultimc/

**Comment by peterix** [comment]
Hopefully this will do :)
