### ISSUE TITLE
[Enchancement] "Better" imgur support

### ISSUE THREAD

**Issue by spannerman79** [MultiMC/MultiMC5#1248]
When uploading screenshots I assume that you use the imgur api, I was doing a little digging around and noticed that the api allows for [OAuth](https://api.imgur.com/oauth2)

This could be useful for people that already have an account on imgur for easier management for screenshots that have been uploaded instead of copy/pasting the Delete hash somewhere safe - if needed.

**Comment by Heufneutje** [comment]
Duplicate of #1089.

**Comment by spannerman79** [comment]
Ah yes - my bad.  Closing
