### ISSUE TITLE
Crash ?

### ISSUE THREAD

**Issue by Trel12** [MultiMC/MultiMC5#1249]
I had instill the OreSpawn mod 1.7.10 when I load the world it said shutting down internal. i got the newest 1.7 forge. please help

**Comment by 02JanDal** [comment]
Please upload the full log using the "Upload Log" button, and post the link you get here.

**Comment by Trel12** [comment]
-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.10.4
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 141256864 bytes (134 MB) / 481611776 bytes (459 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 4 mods loaded, 4 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OreSpawn{1.7.10.20} [OreSpawn] (Ore-Spawn-Mod-1.7.10.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.7.10-Forge10.13.2.1230
	LWJGL: 2.9.1
	OpenGL: Intel HD Graphics 4000 OpenGL Engine GL version 2.1 INTEL-10.6.31, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by 02JanDal** [comment]
We need the **full** log. There is a button called **Upload**/**Upload Log** (depending on translation). Clicking it will give you a link. Post that link here.

**Comment by Trel12** [comment]
where is it ?

**Comment by 02JanDal** [comment]
On the console window (the one with all the text that's open when an instance is running. If the window closes to quickly after the instance exits you'll change the setting for closing the console window.

**Comment by Trel12** [comment]
![screen shot 2015-09-20 at 8 22 16](https://cloud.githubusercontent.com/assets/14359849/9980704/116eb28e-5fd5-11e5-806b-90c7148ac33d.png)

**Comment by 02JanDal** [comment]
That is not MultiMC, that is the vanilla launcher. This issue tracker is only for MultiMC issues.

**Comment by Trel12** [comment]
then where can i find it ?

**Comment by 02JanDal** [comment]
Assuming "it" means the MultiMC launcher: https://multimc.org/

**Comment by Trel12** [comment]
how do i use this ?

**Comment by Trel12** [comment]
Is this because the mod does not come in forge it is a folder ?
