### ISSUE TITLE
AL lib: (EE) alc_cleanup: 1 device not closed

### ISSUE THREAD

**Issue by infernalspectre** [MultiMC/MultiMC5#1251]
Hey I have been getting this error log recently. Before this last update, both to java and multimc these modpacks worked together. And I have checked running vanilla worked just fine. 
Here is the error log: https://paste.ee/p/PY66X

**Comment by TheDoctorsLife** [comment]
Have you tried making/ using a different modpack? or just forge and minecraft on its own?

**Comment by Heufneutje** [comment]
Seems to be related to the Forge splash screen. Try disabling that in the config and see if that works.
