### ISSUE TITLE
Minecraft exited with exitcode -1

### ISSUE THREAD

**Issue by Art4943** [MultiMC/MultiMC5#1252]
http://paste.ee/p/0z1rM

It's a clean instance of minecraft 1.7.10 with no mods installed, crashing before startup, any ideas what the problem is?

**Comment by TheDoctorsLife** [comment]
By searching your error, it seems your graphics drivers are out of date. Please check out this page http://hopper.minecraft.net/help/pixel-format-not-accelerated/
