### ISSUE TITLE
Random closing of MMC5

### ISSUE THREAD

**Issue by wujekbrezniew** [MultiMC/MultiMC5#1253]
Aplication closes itself in random moments when i don't use it. 
For example: I play Minecraft and MultiMC works in background. Then it closes immediately and i get an error, something like "visual Microsoft error" . 
If it happens again, I send some screens.

**Comment by peterix** [comment]
If you can, grab the log it wrote before the crash too. MultiMC-0.log is always the newest one.

**Comment by wujekbrezniew** [comment]
But there is no information in log :(

**Comment by peterix** [comment]
Well, there is. It's probably not detailed enough, but there are very few things that could cause this. And more logging can be added.

**Comment by wujekbrezniew** [comment]
Your welcome 
http://pastebin.com/tXRCMdhB

**Comment by peterix** [comment]
Please reopen this if it still the case with `0.4.10`
