### ISSUE TITLE
Mine craft crashes with exit code 1 

### ISSUE THREAD

**Issue by serenal84** [MultiMC/MultiMC5#1256]
https://bugs.mojang.com/secure/attachment/100541/minecraft+crash+report.txt

**Comment by serenal84** [comment]
Same mods work on other computers. Mine rafts works without mods.

**Comment by peterix** [comment]
```
net.minecraft.client.renderer.StitcherException: Unable to fit: missingno - size: 16x16 - Maybe try a lowerresolution resourcepack?
```
And
```
OpenGL: Intel 965/963 Graphics Media Accelerator GL version 1.5.0 - Build 7.14.10.1437, Intel
```

Sounds like that integraed intel GPU doesn't have enough graphics memory.

Things that can help:
* If your system has dual GPU (integrated intel + dedicated AMD or NVidia), try renaming MultiMC.exe to Minecraft.exe - the graphics drivers look at the file name to decide which GPU to use.
* Remove all texture/resource packs.
* Somehow assign more memory to the Intel GPU? I never tried this, but it should be possible...
