### ISSUE TITLE
Graphic Card bug

### ISSUE THREAD

**Issue by PaponZ** [MultiMC/MultiMC5#1258]
Hi guys I've a gaming notebook with an nvidia gtx960M but MultiMC refresh the game with the graphic card integrated in the cpu....Can you explain me why?Do you have any solution?Because I have 20 fps and memory is like 15% used.

**Comment by 02JanDal** [comment]
Try renaming MultiMC.exe to Minecraft.exe or minecraft.exe, sometimes that fixes it on mobile graphics. You could also see if there is some control panel that allows you to whitelist MultiMC and/or java to use the "real" graphics card.
