### ISSUE TITLE
Exit code 255

### ISSUE THREAD

**Issue by julioplayz** [MultiMC/MultiMC5#1261]
I have an exit code 255 on my modpack, i have the latest version of java but it still wont load up. help please here is the report http://paste.ee/p/3pbHZ

**Comment by dmodoomsirius** [comment]
looks like your issue is ayriahud

**Comment by julioplayz** [comment]
let me check

**Comment by julioplayz** [comment]
well what i didnt put is that it works until i load one of the worlds then shuts down

**Comment by julioplayz** [comment]
IT WORKED THANKS wow same day service

**Comment by julioplayz** [comment]
how do i close this?
