### ISSUE TITLE
help again

### ISSUE THREAD

**Issue by julioplayz** [MultiMC/MultiMC5#1265]
http://paste.ee/p/PcBH0 i dunno this code it doesnt even load

**Comment by peterix** [comment]
You seem to be missing some mod dependencies:
* AnimationAPI
* whatever is missing for the zelda sword skills mod

Look at their pages and read the installation instructions.

**Comment by julioplayz** [comment]
meaning what? i dont know what "dependencies" mean

**Comment by julioplayz** [comment]
plus the zelda mod works just fine

**Comment by julioplayz** [comment]
ok i took out the zelda mods and it loads but i put battele gear and dual hot bar

**Comment by julioplayz** [comment]
and now thats not working

**Comment by Heufneutje** [comment]
Dependencies are mods that other mods require to be able to work.

**Comment by julioplayz** [comment]
OH thats what that is ok so i installed that and i took out zelda and i took out dual hotbars i believe would crash the game when i load a world

**Comment by julioplayz** [comment]
paste.ee/p/HRZwu now this is cooky

**Comment by julioplayz** [comment]
ok i got it working thanks for all the help!
