### ISSUE TITLE
Linux version stores data DIRECTLY in ~/ (home folder)

### ISSUE THREAD

**Issue by alien2003** [MultiMC/MultiMC5#1266]

**Comment by 02JanDal** [comment]
It would only do this if you put it there, meaning the start script (`MultiMC`) in ~/MultiMC, the main executable in `~/bin/MultiMC` etc. It uses the directory the start script is placed in as the data root.

**Comment by peterix** [comment]
Which linux version? Did you use the new deb package?

**Comment by alien2003** [comment]
Ubuntu 14.04 x64
latest .deb. It happenned few hours ago

**Comment by peterix** [comment]
Alright. Fixed it.

The new .deb is here: https://files.multimc.org/downloads/multimc_1.1-2.deb
