### ISSUE TITLE
Bug with groups character encoding

### ISSUE THREAD

**Issue by Naheulf** [MultiMC/MultiMC5#1272]
If I name a group "moddé" (modded in french), they are no problem until i close MultiMC.
But, when I restart it, the group name is "moddÃ©". At the next launch it's "moddÃƒÂ©" then "moddÃƒÆ’Ã‚Â©" etc...

I get the same in Notepad++ by read the file "./instances/instgroups.json" in ANSI, convert in UTF-8, read in ANSI, convert in UTF-8, ...

Note : they are no bug with the instance name.

**Comment by 02JanDal** [comment]
This was recently (last night in fact) fixed (439c6b43a3432e604afbcef74c36ae5fb73de12b). See also #1268.
