### ISSUE TITLE
Cannot find any Java Installations

### ISSUE THREAD

**Issue by Warlockwolfe** [MultiMC/MultiMC5#1284]
I've been trying to start my game but it doesn't work because it can't find Java. I have tried the auto detect multiple times and tried the browse thing too and it still can't launch at all.

Error Report

```
MultiMC version: 0.4.7

Minecraft folder is:
C:/Users/John/Desktop/For You ;D/Microsoft/Multimc stuff/MultiMC/instances/Tims Server/minecraft

Java path is:
C:/Users/John/Desktop/For You ;D/Private/Microsoft/runtime/jre-x64/1.8.0_25/bin/javaw.exe

Checking Java version...
Could not start java:


Check your MultiMC Java settings.
 ```
I've got no clue what to do

**Comment by 02JanDal** [comment]
Having a `;` in the path might be an issue. Try putting both MultiMC and Java in a place that doesn't contain that character in the path.

**Comment by Warlockwolfe** [comment]
If I just rename the folder would that be alright?

**Comment by 02JanDal** [comment]
Depends on what's in it, and how it was installed. MultiMC would be alright with it. You can always try and change it back if it doesn't work.

**Comment by Warlockwolfe** [comment]
Okay so I moved stuff around and I've opened the new MultiMc thing and it can now find a Java version but when I click test it is just saying 

The specified java binary didn't work with the arguments you provided:

I get the same error from the first post when trying to open it as well

**Comment by Warlockwolfe** [comment]
Okay I've solved it I think it was an issue because of the folder or something but now I'm opening my instance and during the launching its crashes and goes back to the instance screen not giving me a crash report or anything

**Comment by Warlockwolfe** [comment]
Alright I've fixed it thanks for all your help
