### ISSUE TITLE
I can't add DivineRPG Without Crashing

### ISSUE THREAD

**Issue by TheMaxShaft** [MultiMC/MultiMC5#1285]
I keep trying to add DivineRPG, and I can't load it, here is the crash log: http://paste.ee/p/2rEpG

The code is 255

**Comment by peterix** [comment]
You have two mods trying to use dimension -28 at the same time. Galacticraft and DivineRPG, most likely. You'll have to fix this in their configs.

**Comment by TheMaxShaft** [comment]
I recoded all the configs to fix this already, please help! Here are the configs  http://www.mediafire.com/download/ns84llsfx2vpblz/config.zip

**Comment by peterix** [comment]
Does it work with a new world?

**Comment by TheMaxShaft** [comment]
No that is what causes it to crash, I can't use old worlds due to terrain gen

**Comment by peterix** [comment]
Well, then you'll have to checge the configs to not break your world(s). The dimension ID for that dimension can't change. It has to change in the other mod that you are adding, not the one you already have.

I hope you have backups.

**Comment by TheMaxShaft** [comment]
Which dimension?

**Comment by peterix** [comment]
Whatever is -28 in the old worlds

**Comment by TheMaxShaft** [comment]
so there is a dimension conflict of -28?

**Comment by peterix** [comment]
It looks like it.

**Comment by TheMaxShaft** [comment]
ok I will try to fix it

**Comment by TheMaxShaft** [comment]
I fixed the dimensions in galacticraft, but there was no dimension 28 in DivineRPG

**Comment by TheMaxShaft** [comment]
Whoops wrong button

**Comment by TheMaxShaft** [comment]
I had to upload the paste with media fire, the error was too large on pastebin and paste.ee 
http://www.mediafire.com/view/86wgb8vug1fgcm3/Bug_Report.txt

**Comment by peterix** [comment]
```
java.lang.NullPointerException
	at net.divinerpg.utils.events.UpdateChecker.isUpdateAvailable(UpdateChecker.java:25) ~[UpdateChecker.class:?]
	at net.divinerpg.client.render.gui.GUIOverlay.drawOverlay(GUIOverlay.java:31) ~[GUIOverlay.class:?]
	at net.divinerpg.utils.events.EventOverlay.renderOverlay(EventOverlay.java:20) ~[EventOverlay.class:?]
```

It crashes while looking for updates.
If there is a way to disable looking for updates, do that.
