### ISSUE TITLE
I cant start my modpack..

### ISSUE THREAD

**Issue by ScipioCZ** [MultiMC/MultiMC5#1286]
Hi, I created a modpack on version 1.5.2, but i cant start it.. I have this error every time, when i try it. https://cloud.githubusercontent.com/assets/15162499/10550191/cdb845ac-7445-11e5-8670-8813eeb3389b.png
.

**Comment by peterix** [comment]
Use the upload button for uploading the log. This is hard to use stuff into google - and it's missing most of the log.

**Comment by ScipioCZ** [comment]
http://paste.ee/p/KwMD2 here..

**Comment by wlhlm** [comment]
This looks like you're missing TWL, which I think is provided by [GuiAPI](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1276886-1-5-2-guiapi-an-advanced-gui-toolkit). Try to add that to your modpack.

**Comment by ScipioCZ** [comment]
Ok, give me moment

**Comment by ScipioCZ** [comment]
http://paste.ee/p/Sk7wg

**Comment by ScipioCZ** [comment]
so?

**Comment by peterix** [comment]
I haven't used 1.5.2 in a while, so take this with a grain of salt :)

Instead of the `mods` folder, GuiAPI needs to be in `coremods`. A few other mods you have might have to go there too. Possibly CCC, NEI, the shader mod and generally anything that has 'core' in the name.

**Comment by peterix** [comment]
Check any installation instructions the mods come with, if they are still available.

**Comment by ScipioCZ** [comment]
When I move some mods to Core Mods, game exit with -1

**Comment by peterix** [comment]
let's look at the logs then

**Comment by ScipioCZ** [comment]
http://paste.ee/p/eMxVO .. I have an idea.. can u create working modpack for me?

**Comment by loordgek** [comment]
can you you post a pic from your mods and coremods folder

**Comment by peterix** [comment]
Just look at the log. It has mod lists.

**Comment by loordgek** [comment]
why are you using 1.5.x?
@peterix oops dint see that

**Comment by RX14** [comment]
@loordgek why not?

**Comment by peterix** [comment]
I would disable some of those mods first. Optifine, the shader mod, the dynamic lights mod. Check their installation instructions.

And no, I don't want to make modpacks for people. They would find out I'm doing it and then I wouldn't do anything else :P

**Comment by loordgek** [comment]
1.5.x is old

**Comment by peterix** [comment]
I don't think that's an argument. 1.5.2 had some mods that non longer exist. It is unique. It can't be fully replaced by later versions.

**Comment by RX14** [comment]
@loordgek people should be able to play with whatever MC version they would like

**Comment by loordgek** [comment]
all the mods can you get for 1.7.10 and some for 1.8
