### ISSUE TITLE
AL lib: (EE) alc_cleanup: 1 device not closed

### ISSUE THREAD

**Issue by Sandrituky** [MultiMC/MultiMC5#1290]
When I finally made my server works after a few hours of trying, then the client is now what is not working anymore. I changed a few mods, according to the server, it worked before. 
Here's the full log: 
http://paste.ee/p/VHgeO

I have no idea how to solve this, I've already looking for a solution during hours... :/ Can anyone help me please? Thank you!

#GameProblem

**Comment by 02JanDal** [comment]
Please reopen if this is still an issue. The paste.ee timed out, so you'd have to post a new log.
