### ISSUE TITLE
Help me with my multimc pack crash

### ISSUE THREAD

**Issue by Mattyproxx** [MultiMC/MultiMC5#1292]
https://paste.ee/p/eLzog

**Comment by 02JanDal** [comment]
Take a look at this line:

    [16:49:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.OutOfMemoryError: PermGen space

Can you guess what the issue is? If not, have you tried putting that line (or parts of it) into Google?

**Comment by Mattyproxx** [comment]
What???

**Comment by 02JanDal** [comment]
You've taken enough of our time, so it's only fair if you get to spend a bit of your own, solving YOUR issue. I could just give you a solution, but then what would you learn?

**Comment by Mattyproxx** [comment]
There isn't enough ram space???

**Comment by 02JanDal** [comment]
Close.

**Comment by Mattyproxx** [comment]
I have to dedicate more ram to the pack

**Comment by Mattyproxx** [comment]
But i have only 4 GB of ram

**Comment by 02JanDal** [comment]
Pretty much, but it's not general memory that it's out of, it's out of PermGen space (separate memory pool used by Java applications before Java 8). To solve this, you can either upgrade to Java 8 (remember to also set MultiMC to use it), or go into the settings for the MultiMC instance and increase the PermGen memory for the instance. Don't set it to high though, try doubling the current value until it works.

**Comment by 02JanDal** [comment]
Assuming this was resolved. Reopen if not.
