### ISSUE TITLE
help me with my issue

### ISSUE THREAD

**Issue by Jallox** [MultiMC/MultiMC5#1295]
http://paste.ee/p/Oh7yd it's a crash report

**Comment by 02JanDal** [comment]
Please upload the full log using the Upload Log button. This is a crash report, we want the full log.

**Comment by Jallox** [comment]
this is the crash report

**Comment by Jallox** [comment]
i clicked the upload button

**Comment by 02JanDal** [comment]
You are on the "Other Logs" page. Go to the "Minecraft Log" page.

https://github.com/MultiMC/MultiMC5/wiki/Minecraft-Logs

**Comment by peterix** [comment]
Yes, but don't go fishing for it in the other logs page. Use the main log.

**Comment by Jallox** [comment]
where is the minecraft log page???
in the instance options????

**Comment by peterix** [comment]
run the instance, it will crash, and should show the log/settings window with the full log

you can also enable always showing the log window in the settings.

**Comment by 02JanDal** [comment]
When running an instance, and after it has crashed, you'll have a window called `Console window for <instance>`. Here you have several pages you can choose from on the left, one of them is called _Minecraft Log_. It'll contain a colorful area of text, as well as several buttons, one of them being _Upload_.

**Comment by peterix** [comment]
Normally, the window is hidden and is accessible from the taskbar tray area.

**Comment by Jallox** [comment]
waiting for the crash

**Comment by Jallox** [comment]
http://paste.ee/p/GGaYw this is the log

**Comment by Jallox** [comment]
found the problem??????

**Comment by 02JanDal** [comment]
Given that we haven't answered: no

This is not an instant support service, everyone here is doing this for in their spare time, for free. Adjust your expectations accordingly.

**Comment by peterix** [comment]
It's an issue with villager type IDs. You will have to tweak these in agricraft config(s).

**Comment by Jallox** [comment]
where is this config???

**Comment by Jallox** [comment]
i found the config

**Comment by Jallox** [comment]
it's set on 10 what i have to do???

**Comment by peterix** [comment]
If you just want to get rid of the problem, pick a safe, unlikely number. Like 76. (and hope it's not used yet)

If you want to do it right, you would have to check all the mods and see if they add villager types. And figure out which numbers are used. And clean up the mess...

This is something that should be handled by the underlying API (Forge), but it's either not there, or not done right by Agricraft...

**Comment by Jallox** [comment]
i did it

**Comment by peterix** [comment]
OK. I did some more digging around in code of both Forge and AgriCraft:

You are using an old version that still has this villager ID. Newer versions assign it automatically, but not necessarily right... If you update agricraft, you might end up with missing or changed villagers.

**Comment by Jallox** [comment]
solved the problem....
you suggest some anti-lag solutions????

**Comment by Jallox** [comment]
like optifine

**Comment by peterix** [comment]
fastcraft and optifine. Just make sure you actually measure if it helps.

**Comment by Jallox** [comment]
i already have fastcraft but the lag doesn't reduces.....

**Comment by Jallox** [comment]
do you have other lag reducer mods??????????

**Comment by peterix** [comment]
Not really. I solved that problem with excessive hardware upgrades. Look around :)
