### ISSUE TITLE
Better instructions for how to upload the correct log

### ISSUE THREAD

**Issue by 02JanDal** [MultiMC/MultiMC5#1296]
Both extending https://github.com/MultiMC/MultiMC5/wiki/Minecraft-Logs and maybe producing some sort of instruction video.

No idea what specifically to add, but people frequently seem to have issue with uploading the right log. Often it's about the console window having closed, or being hidden, so maybe something about that, also something about Crash report vs. Full log.

**Comment by peterix** [comment]
[Moved to workflowy (Chores)](https://workflowy.com/s/2EyDMcp7CU)

**Comment by peterix** [comment]
That wiki page is really good enough. People finding it is probably more of a problem.
