### ISSUE TITLE
Game gets stuck during launch

### ISSUE THREAD

**Issue by Nateolocity** [MultiMC/MultiMC5#1298]
http://paste.ee/p/T7ZvT

The game gets stuck during initialization. Here's a picture of MC in it's frozen state. 
http://s13.postimg.org/wbm5xeq07/Capture.jpg
I've tried reverting to the recommended version of forge, to no avail.

**Comment by 02JanDal** [comment]
Caused by: java.lang.OutOfMemoryError: PermGen space

You ran out of PermGen. Either switch to Java 8 (where it's no longer needed) or go into the instance settings in MultiMC and find the setting for PermGen and increase it (try doubling).

**Comment by Nateolocity** [comment]
It worked! Thanks.
