### ISSUE TITLE
Some characters in path break MultiMC updates (^, possibly others)

### ISSUE THREAD

**Issue by Practiclycrp** [MultiMC/MultiMC5#1299]
0.4.8/675, Unable to change to a different update branch http://i.imgur.com/HQJYc06.png

**Comment by 02JanDal** [comment]
Please put the contents of MultiMC-0.log on pastebin or similar, and post the link here.

**Comment by Practiclycrp** [comment]
http://pastebin.com/wyQrCFDc

**Comment by peterix** [comment]
Can you test this after removing the '^' from that folder name?

**Comment by Practiclycrp** [comment]
It seems that was the problem, I was able to change back to the stable branch. http://pastebin.com/3pQhma65

**Comment by peterix** [comment]
I cannot reproduce this on Windows XP or 8.1

The updater works with this `^` character in the path for me...

So, idk. If you can add more information to this, please do.

**Comment by Practiclycrp** [comment]
It's not consistent? I added various symbols, which at first I wasn't able to change update channels, but after restarting the program once it was fine. http://i.imgur.com/YecF9WG.png http://pastebin.com/FY9pyWxa
