### ISSUE TITLE
Direct instance launch leaves behind a process

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#1300]
When launching my Minecraft Instance using the MultiMC -l parameter on Windows the MultiMC.exe process doesn't quit after I close the game. It's leaving no GUI behind, so I have to kill it using a task manager. (The logging window is set to close after the game quits.)

Game running:
![before (game running)](https://cloud.githubusercontent.com/assets/2636101/10649406/40f48808-7844-11e5-9c79-18949ad3440c.png)

Game quit, MultiMC still running in the background without a visible GUI (no tray bar icon either):
![after (game quit)](https://cloud.githubusercontent.com/assets/2636101/10649407/43c3a51e-7844-11e5-8eb6-c02260178f50.png)

**Comment by peterix** [comment]
This should now be fixed.

**Comment by p-schneider** [comment]
Thanks, as of Version 0.4.8-dev-676 I no longer have MultiMC processes left behind.
