### ISSUE TITLE
KeyBind Tab in Instances for Minecraft KeyBinds

### ISSUE THREAD

**Issue by Doty1154** [MultiMC/MultiMC5#1302]
The ability to set keybinds in minecraft just from the launcher would be great, although you would need to run mc once to setup the files. Also possibly global keybinds for MC only keys, Example: Sprint could be auto binded to shift and crouch to ctl. 

![keybinds](https://cloud.githubusercontent.com/assets/7087748/10708518/2ab812f8-79c0-11e5-9a41-b8c320a856f2.png)

**Comment by peterix** [comment]
Moved to workflowy
