### ISSUE TITLE
Not recognizing liteloader 1.8

### ISSUE THREAD

**Issue by fishmealx** [MultiMC/MultiMC5#1303]
I manually put it in there, but the profile still won't show up. Thanks.

**Comment by 02JanDal** [comment]
Please describe in more detail what you did.

**Comment by fishmealx** [comment]
Well, once I realized that MultiMC wasn't automatically recognizing the 1.8 liteloader when I clicked the download button, I took the entire contents of my vanilla .minecraft folder and put it in the instance folder for MultiMC. My vanilla instance already had liteloader installed, but I don't see that profile in the list, only Forge.
Any way you could just make the download liteloader button work for the 1.8 beta? It's here:  http://jenkins.liteloader.com/job/LiteLoaderInstaller/
Thanks.

**Comment by Slikrick** [comment]
Those aren't betas. They are development/alpha builds. You can add those builds to multimc as described here: https://github.com/MultiMC/MultiMC5/issues/676 on your own. When it is officially released in the normal location multimc will recognize liteloader by default

**Comment by peterix** [comment]
What @Slikrick said.

Grab this file (raw):
https://gist.github.com/peterix/d5571257e7d4511a9018#file-com-mumfrey-liteloader-json

and put it where it belongs. It comes with instructions.
