### ISSUE TITLE
Add mirror links for downloads

### ISSUE THREAD

**Issue by ppoozl** [MultiMC/MultiMC5#1304]
Can you change your download method from http to https,http://s3.amazonaws.com has been blocked in my network,but https://s3.amazonaws.com works fine.

**Comment by 02JanDal** [comment]
I'm surprised this isn't already the case.

@peterix: can you recall if there was some specific reason for this?

This should be a quick and easy change though.

**Comment by peterix** [comment]
Sometimes one form of download fails and the other works. We should try both.

In case where it is `https` vs. `http`, it is a downgrade when it comes to security though. Maybe it should ask before doing that, and always try `https` first.

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Download component files from mirrors)](https://workflowy.com/s/2EyDMcp7CU)
