### ISSUE TITLE
Cross-Platform

### ISSUE THREAD

**Issue by Aidoboy** [MultiMC/MultiMC5#1307]
Can I make MultiMC Cross-Platform by overlaying the archives over each other, or would that cause problems? Are there any other ways I could do it?

**Comment by 02JanDal** [comment]
That'd probably not go to well. Please explain what you want to achieve, not how you want want do it.

**Comment by Aidoboy** [comment]
I want to be able to use my MultiMC instances in Ubuntu and Windows. I found the place in the settings that lets me set the folders, and now I feel silly.
