### ISSUE TITLE
True FTB Support

### ISSUE THREAD

**Issue by robotbrain** [MultiMC/MultiMC5#1309]
- [x] Downloading
- [ ] Import from FTB launcher

**Comment by robotbrain** [comment]
- [ ] Processing
  - [ ] pack.json handling
  - [ ] Forge/liteloader detection

**Comment by robotbrain** [comment]
- [ ] Pack listing 
- [ ] Pack version listing 
- [ ] Icon grabbing

**Comment by peterix** [comment]
Alright. moving this to workflowy / scrapping it for now. It will become bullet points.

[Moved to workflowy (Ideas -> Packs)](https://workflowy.com/s/2EyDMcp7CU).

**Comment by peterix** [comment]
This is actually close to finished. Only thing missing are private pack codes.

**Comment by peterix** [comment]
Well, it's as done as it will ever be.
