### ISSUE TITLE
MultiMC5 Fatal Error crash...strange...

### ISSUE THREAD

**Issue by minecraftYOUniversity** [MultiMC/MultiMC5#1310]
I have a modpack custom designed by the awesome guys at McProhosting.  My daughter and I, same house; different computers) are building a Minecraft School.  We were both able to get on and play, but now her account (regardless of computer played on) returns a fatal error as soon as she gets on the server.  Here is the crash report...which is strange that it didn't log the actual crash....Something else I noticed while launching....44 mods preinitialize and initilize; however, only 42 listeners do.  Could be contributing to the problem???  Maybe?  I am going through the log again too

http://paste.ee/p/Xp3UA

**Comment by peterix** [comment]
I don't really see much in that log. A few errors that might need correcting, but nothing obviously related to what you describe. A screenshot of the error could help.

Probably harmless:
```
[17:31:14] [Client thread/INFO] [AgriCraft]: Error when reading mutation: resulting stack is not correct (line: AgriCraft:seedNitorWart=minecraft:nether_wart+AgriCraft:seedTulipOrange)
```

Are these instances on two different computers? Maybe try copying over the instance from the one that works.

**Comment by minecraftYOUniversity** [comment]
it happens on both computers.  Here's a 4 min video of what's going on that I can see.....[rendering]

**Comment by peterix** [comment]
Hmm... that's not a link

**Comment by minecraftYOUniversity** [comment]
Nope.  Sorry.  I dont want to waste your time, so I clipped the video to show what needs to be shown so instead of 4 mins, its a min and a half.  Here's the link for the video https://multicraft.mcprohosting.com/index.php?r=server/ftp&id=461148

**Comment by peterix** [comment]
Oh my... can you just put it on something I can access?
Like some public file share, or youtube.

**Comment by minecraftYOUniversity** [comment]
Sorry.  There's no easy way of doing this....loading to YouTube

**Comment by minecraftYOUniversity** [comment]
https://youtu.be/wrgiowqs8F4

**Comment by minecraftYOUniversity** [comment]
I should mention what I have done to fix this already:

deleted and added player again
deleted and reloaded instance from the original working modpack
deleted and reinstalled Minecraft
checked for updated drivers
manually added her as op

**Comment by peterix** [comment]
I can see some sort of error on top of the log here:
https://www.youtube.com/watch?v=wrgiowqs8F4&feature=youtu.be&t=54s

I can't see the game connecting to any servers in the previously posted log. Try to log in to the server as her, then click the upload button on the console window. If it doesn't get all of it, then that's a second issue...

**Comment by minecraftYOUniversity** [comment]
http://paste.ee/p/BaCJv

still doesnt show the fatal error occured

**Comment by peterix** [comment]
Well, there's a lot of errors mentioned, all related to some dinosaur egg from jurassicraft:
```
[18:54:01] [Client thread/ERROR] [FML]: A severe problem occurred during the spawning of an entity at ( -126.375,64.0, 393.65625)
java.lang.IndexOutOfBoundsException: readerIndex(69) + length(4) exceeds writerIndex(69): SlicedByteBuf(ridx: 69, widx: 69, cap: 69/69, unwrapped: UnpooledHeapByteBuf(ridx: 1, widx: 70, cap: 70/70))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1160) ~[AbstractByteBuf.class:?]
	at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:611) ~[AbstractByteBuf.class:?]
	at to.uk.ilexiconn.jurassicraft.data.entity.entity.EntityDinoEgg.readSpawnData(EntityDinoEgg.java:346) ~[EntityDinoEgg.class:?]
```

That's something I haven't seen yet. Either a bug in the mod, or a side effect of updating the mod.

**Comment by minecraftYOUniversity** [comment]
Hmmm....maybe contact the guys at McProhosting that created the modpack.  That doesnt sound like something I can fix on the client side

**Comment by minecraftYOUniversity** [comment]
What I find strange is that I dont seem to be affected, so it didnt seem to be an issue with the modpack (in my inexperienced opinion) or I would expect both of us to experience issues from a server side issue.  If it were a file issue, we also would both be experiencing the issues as well...our files are identical.

**Comment by peterix** [comment]
It might simply depend on you being in a different place on the server.

**Comment by minecraftYOUniversity** [comment]
I see in the log reference to a native file folder.  Again, I am inexperienced.  Im a video producer, not a programmer :)  There isnt a folder called native on our machines

**Comment by peterix** [comment]
That's because this is created on launch and deleted on exit. And it should be entirely unrelated to the issue.

**Comment by minecraftYOUniversity** [comment]
ok  Thanks.  I'll contact the hosting platform for further discussion.

**Comment by peterix** [comment]
OK. I'm going to close this issue, because it's clearly game related.
