### ISSUE TITLE
Add support for game file mirrors (China)

### ISSUE THREAD

**Issue by cqjjjzr** [MultiMC/MultiMC5#1311]
Hi there. it's me again 0w0.

last time i talk to you about components, and now i know it is impossible for a long time.
but i think it's good to add auto update support. You know, some server is forge-based and their mod is often changes. so I think, you can add auto update function, such as read a json when start a instance, so check is the package updated. if it is, the launcher can download the latest mod from the address in json, or - 
build a central repository, and let it global avaliable, then the modder, pluginer, developer can add resource here. and let somebody build mirrors and so on. so the resources are very easy to get & use. is it good, huh?
and about the download source. the Mojang offical download site is very slow for other country. but, there is somebody built the Mojang mirror, some launcher can use them. but, the multimc is still cannot use these mirror, so i hope the download source select is added to mmc, such as :user give an address, MultiMC access this address for a json, and parse it to get the download info, and we can get faster download.
I'll try to implements those function, but don't look at me, of course.
best wishes.
CharlieJiang

**Comment by 02JanDal** [comment]
This is being worked on somewhat actively (I hope to get a bit of stuff done after my exam today), see the [feature/wonko](https://github.com/MultiMC/MultiMC5/tree/feature/wonko) branch, as well as the [MMCWonko/WonkoTheSane](https://github.com/MMCWonko/WonkoTheSane) repository, which is sort of the backend.

If you have any further questions feel free to come to [#MultiMC on esper.net](http://webchat.esper.net/?nick=&channels=MultiMC), I'm only available a bit today, but from tomorrow you can ping me whenever you want. (of course you can also reply to this issue if you prefer that)

**Comment by cqjjjzr** [comment]
Err....
92% translated.
But some wrong is in the templete.
such as the Resource Packs in console window.
@02JanDal

**Comment by 02JanDal** [comment]
Being slowly (currently not at all) worked on.

**Comment by wrincewind** [comment]
I hate to be a drag, but... any update on the progress of this?

**Comment by peterix** [comment]
I recognize this, and it shouldn't have been closed.

**Comment by cqjjjzr** [comment]
I'm surprised to find this issue still alive:P
have a look at https://blog.bangbang93.com/article/59c23c08e003c174011f9ef1
