### ISSUE TITLE
Strings/Translation inconsistencies

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#1313]
Resource packs and texture packs - described as 'mods' by the mod info control. Fix it.

Some things are marked for translation and shouldn't. For example the licenses in the About dialog. Mark more stuff as not to be translated.

**Comment by cqjjjzr** [comment]
yes this is some problem in the program.

**Comment by cqjjjzr** [comment]
and, the Install Forge page is not marked as translated. but it needs translate.

**Comment by peterix** [comment]
Also, title bar:
![multimc](https://cloud.githubusercontent.com/assets/6622592/10940404/17453a54-8341-11e5-9243-a15b1cfee801.png)

**Comment by peterix** [comment]
All of the above should be fixed now in the develop version.
