### ISSUE TITLE
[Request] Ability to install any Minecraft version manually

### ISSUE THREAD

**Issue by jchoi071** [MultiMC/MultiMC5#1314]
Currently, only the latest snapshots are shown in the versions list, both in MultiMC and in the vanilla launcher, probably because Mojang doesn't list old snapshots. On the vanilla launcher, installing an old snapshot is trivial - just download the client .jar and .json files and the version appears in the launcher. On MultiMC, you can't do that. The only versions shown are the ones listed by Mojang for download. Please make it easier to install any version of Minecraft, not just the ones Mojang lists.

**Comment by peterix** [comment]
This will have to be done on top of the wonko infrastructure once that's in place.

**Comment by peterix** [comment]
Soon™

**Comment by jchoi071** [comment]
I just found out how to do this myself. If you make a new instance with any version, click "customize" in the instance settings, then click edit, you can just copy the contents of the desired version's .json to the .json that opens.

**Comment by peterix** [comment]
Just keep this open.

**Comment by peterix** [comment]
This is indeed already possible, if you are careful enough.

However:
* The Minecraft jar is not a library -> Make it an ordinary library!
* Make libraries redistributable with the instance (libraries folder inside)?
* Allow adding custom files to local library cache (for crud like FTB) - just be aware that files not backed by remote repositories could be hard to get back
* When exporting a pack, the local custom libraries should be exported along with the pack

[Moved to workflowy (Ideas -> Version patches and instance version)](https://workflowy.com/s/2EyDMcp7CU)

**Comment by peterix** [comment]
Done in develop, it's just missing UI.

**Comment by peterix** [comment]
I believe the necessary parts are in place. Json patch editor could be nice, but that's really outside the scope of support for custom jars.
