### ISSUE TITLE
Permisson request: Reprint in MCBBS

### ISSUE THREAD

**Issue by cqjjjzr** [MultiMC/MultiMC5#1315]
Hi there.
I'm cqjjjzr, CharlieJiang.

I think MultiMC is a amazing launcher. But as you see. There are only a few Chinese users of MultiMC. A lot of Chinese player dont know what is MultiMC? So i think it's time to reprint MMC in MCBBS(Minecraft中文论坛)(http://www.mcbbs.net/). It is the most popularity Minecraft forum in China. And my entire post will obey the rule below and rule you specified

1. I **WILL NOT** take any credits (except translate) of your software and I **WILL** print your offical link completely(include github and offical site).
2. I **WILL NOT** take any money or spensor from your software, I will never use adf.ly.and similer link. and I will make every effort to ensure no others use the MMC to take money.
3. In case of firewall(government cause) Maybe I'll upload the software to a mirror link(**AD-FREE**) and very like Dropbox such as BaiduPan(http://pan.baidu.com/).
4. i will give offical link to post, and i'll clearly note "Offical Link click here first".

I'll be very appreciate if you can give my permission. But, thank you any way because you bring me a amazing launcher.

Sincerely,
CharlieJiang
11/5/2015

**Comment by peterix** [comment]
Hello!
This sounds like a good thing. It shouldn't be necessary in my opinion, but you certainly do have the permission.

**Comment by cqjjjzr** [comment]
http://www.mcbbs.net/forum.php?mod=viewthread&tid=519460
Finally......

**Comment by peterix** [comment]
Thank you.

Sorry for no reply on IRC. At that time, we were all asleep.
