### ISSUE TITLE
Download from mirrors

### ISSUE THREAD

**Issue by 02JanDal** [MultiMC/MultiMC5#1317]
It should be possible to download stuff from mirrors in wonko. Check the validity of downloads using sha256 + size.

The same for MultiMC itself, possibly together with switching it over to using wonko too.

**Comment by peterix** [comment]
For the metadata, we should sign the metadata files. That way, they can be mirrored too.

**Comment by cqjjjzr** [comment]
Game Download/Forge/Liteloader Mirror in china: http://bmclapi.bangbang93.com/

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Download component files from mirrors, Ideas -> Set up / use file mirror in China)](https://workflowy.com/s/2EyDMcp7CU)

**Comment by cqjjjzr** [comment]
I'm sorry to tell you, Bangbang93 is not welcome anybody change his server.
but if needed, I can host a server in China.
