### ISSUE TITLE
Big IO usage on Linux 

### ISSUE THREAD

**Issue by Cysioland** [MultiMC/MultiMC5#1318]
Visible particularly when connecting/disconnecting to a server, and easily measurable with iotop. The IO is mostly reads.

**Comment by peterix** [comment]
Are you talking about Minecraft or MultiMC?

**Comment by Cysioland** [comment]
MultiMC process, it's clearly visible with iotop.
6 lis 2015 18:22 "Petr Mrázek" <notifications@github.com> napisał(a):

**Comment by peterix** [comment]
And that is while Minecraft is connecting to a server, or in some other situation?

**Comment by Cysioland** [comment]
Occurs randomly, but also when Minecraft connects/disconnects. It didn't
occur with Technic Launcher.

**Comment by peterix** [comment]
Make sure it's not iotop screwing up. I've seen similar tools not detecting the forked java process as a separate thing before.

**Comment by Cysioland** [comment]
Java could be seen separately at moments.
6 lis 2015 18:27 "Petr Mrázek" <notifications@github.com> napisał(a):

**Comment by peterix** [comment]
OK. I'll look into it.
