### ISSUE TITLE
Resource Pack Woes 

### ISSUE THREAD

**Issue by Dragonracer73** [MultiMC/MultiMC5#1329]
Hello,
First let me start by saying I love this Mod Launcher. It is by far the quickest and best for my low end system. My issue is, as implied by the title, that I cannot get a custom made resource pack to load on the launcher. I have tried several methods such as Gimp, Paint.net, and Mightyporks RPW, to no avail.
I'm trying to combine my favorite packs into a mash up and I thought for sure that RPW would have been my solution.I have followed certain Mojang Parameters to the "T",such as theMCmetadata and Png in the main assets folder.  The packs work fine alone but as soon as I unzip copy and paste the nessaceery info into a new zipped folder, it doesn't show up on the resource pack left hand side. Any Help would be appreciated. Thank you.

**Comment by Heufneutje** [comment]
Resource packs go into the same folder as they would on an instance of the vanilla Minecraft launcher. Does your resource pack work in the vanilla launcher?

**Comment by Dragonracer73** [comment]
Haven't tried that yet but I will.(vanilla launcher) I drop my resource packs in under the resource pack tab in the multimc launcher

**Comment by peterix** [comment]
Open the actual folder and check if it works properly

**Comment by Dragonracer73** [comment]
No Heufneutje it doesn't load into the vanilla game not sure what I did wrong, as stated in above post I'm using RPW trying to combine Halcyon days, Sphax,and Isabella all are 16x as I have a low end system. Acer (glorified laptop in a box, and called a tower) maybe I need a detaled walkthrough of what i'm doing wrong I thought RPW was supposed to be click change zip and go but apparently not.

**Comment by Dragonracer73** [comment]
Think I figured it out Iwasn't exporting Ziped files off of RPW. I'm such a derpy newb thanx for help though

**Comment by wlhlm** [comment]
Minecraft doesn't need a zipp'ed resourcepack, it can work fine with bare directories as long as it has a `.mcmeta` file.
