### ISSUE TITLE
Integrate with new paste.ee API

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#1333]

**Comment by peterix** [comment]
See:
http://beta.paste.ee/wiki/API:Keys
http://beta.paste.ee/apidoc/

**Comment by nikkiii** [comment]
New API Reference: http://pastee.github.io/docs/

**Comment by peterix** [comment]
@nikkiii how soon is this needed?

**Comment by nikkiii** [comment]
@peterix The old API will work fine for years to come, no rush, and the release of the beta to production has been delayed for a bit too.

**Comment by peterix** [comment]
Very well then. I am moving all ideas / feature requests to workflowy, here: https://workflowy.com/s/2EyDMcp7CU

So, I will reopen this as a 'feature' once I am ready to do it. Ping me if anything changes.
