### ISSUE TITLE
Symbolic Links

### ISSUE THREAD

**Issue by ScottKillen** [MultiMC/MultiMC5#1335]
Can we have an option to tell MultiMC not to follow symbolic links when deleting and instance?

I use symbolic links for things like large resource packs and mods...and removing an instance containing the symlinks also removes the target of the link.

(At least this is the behavior on Windows...)

**Comment by Kilobyte22** [comment]
This is weird. We used to have that bug a couple months ago (#228) and it was fixed. Now it's back?

**Comment by peterix** [comment]
This is already fixed. Tested it on windows 7 and it works fine. Make sure you actually have an up-to-date version.

**Comment by ScottKillen** [comment]
Thanks! Will do.
