### ISSUE TITLE
New snapshot features dont show up.

### ISSUE THREAD

**Issue by Eisys** [MultiMC/MultiMC5#1338]
A while back when subtitles were added and I updated to that snapshot, they didn't come up even though I had them enabled.
I fixed that by completely reinstalling MultiMC and making my instances again from scratch.

Now in 15w47b, new sounds were added to the game and yet again, I'm not getting them.

If I use the default launcher and use 15w47b, the sounds work like normal.

I have 2 instances. One with 1.8 and a few mods. 2nd one for snapshot stuff. I update the snapshot instance to the latest snapshot every time one is released.

So what could be causing this? Perhaps MultiMC isn't downloading some necessary files for these updates.

**Comment by 02JanDal** [comment]
What happens if you delete the `assets/` folder?

**Comment by peterix** [comment]
Just delete the index files, not the data objects

**Comment by Eisys** [comment]
@peterix That fixed it. Thanks.

**Comment by peterix** [comment]
Alright. Try the develop version and see if it's fixed.
It should be - it's grabbing the asset indexes now, instead of keeping the old ones around forever.

**Comment by Eisys** [comment]
It does, indeed, seem fixed.
