### ISSUE TITLE
Launcher crashes when game ends while uploading screenshot

### ISSUE THREAD

**Issue by jochembroekhoff** [MultiMC/MultiMC5#1339]
I was uploading a screenshot and closed the game, but the launcher crashed. Tested again, but same result. In the log file I didn't find something looks like an error.
I don't know if it is only happening on Windows systems.

**Comment by peterix** [comment]
I received a similar report before... but it didn't have the important bit of information: game closing at the same time as the upload runs.

Shouldn't be too hard to fix.

Can you also check if the same happens in the development version? You can switch to it in settings and then update.

**Comment by jochembroekhoff** [comment]
Updated to development version, but it's happening also there.

**Comment by peterix** [comment]
Should be fixed in develop now.

**Comment by jochembroekhoff** [comment]
Yes, it's fixed.
