### ISSUE TITLE
Custom libraries in instance?

### ISSUE THREAD

**Issue by LewisTehMinerz** [MultiMC/MultiMC5#1340]

**Comment by peterix** [comment]
There's absolutely no reason for it so far.

**Comment by LewisTehMinerz** [comment]
For me, there is. This mod wants to install itself as a library in the .minecraft folder, so I added it to the libraries folder in the MultiMC files (Yes, I did put it in valid folders). Also, I set my 1.8.8 to be custom, so it would let me edit the JSON.

**Comment by peterix** [comment]
What mod?

**Comment by LewisTehMinerz** [comment]
It's at this link: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292688-xray-mod-1-6-4-1-8-8-vanilla-forge-liteloader

(Note: I do not want to use this for bad. I want to use it to catch hackers on servers)

**Comment by LewisTehMinerz** [comment]
When the installer is ran (by double clicking the .jar) it adds it as a library in .minecraft and adds a JSON to point to it. No idea why they did it like that. (Oh yeah, 4.1.6 is my version that I'm installing. I don't want 4.4)

**Comment by peterix** [comment]
So it's not compatible. It would have to be repackaged.

**Comment by LewisTehMinerz** [comment]
I figured out how to set the 1.8.8 JAR to be custom, so I can edit a JSON file. I added the following to line 87 (above the Twitch library):
```JSON
"name": "net.minecraftxray:xray:4.1.6",
            "natives": {
                "linux": "linux",
                "osx": "osx",
                "windows": "windows"
            },
```

**Comment by LewisTehMinerz** [comment]
And I have all the native jar files (basically, 3 copies of it but with -windows, -osx and -linux on the ends.)

**Comment by peterix** [comment]
So it even has native libs? ... wat.

**Comment by LewisTehMinerz** [comment]
Well, read above.

**Comment by peterix** [comment]
That's not a mod in my books... more like a crazy custom thing. I might as well add a custom magical thing for Better Than Wolves while at it.

**Comment by peterix** [comment]
Does it have a maven repo?

**Comment by LewisTehMinerz** [comment]
Not that I can see.

**Comment by LewisTehMinerz** [comment]
For some reason, the library/mod is an installer when you double click it, and when you double click the library, it also runs the same installer, so it just copies itself over.

**Comment by peterix** [comment]
That's really ugly.

**Comment by LewisTehMinerz** [comment]
I know.

**Comment by LewisTehMinerz** [comment]
Join me in #mcxrayissue on esper.net for more talking, don't want this to turn into a massive log of just chat.

**Comment by peterix** [comment]
```
MultiMC
Coming soon!
```

I hope never. Because I don't want to deal with people adding anything on top of MultiMC. Because I'll break it without even knowing it.

**Comment by peterix** [comment]
The current instance format won't last that long...

**Comment by LewisTehMinerz** [comment]
Well, adf.ly updated their stupid ad-block detection.. (trying out a different XRay mod.)

**Comment by LewisTehMinerz** [comment]
Fixed.

**Comment by peterix** [comment]
See:
https://gist.github.com/peterix/83d8fd1dcc3d4ac55fbd

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292688-xray-mod-1-6-4-1-8-8-vanilla-forge-liteloader?page=117#c2370
