### ISSUE TITLE
Custom Mod Pack Fails

### ISSUE THREAD

**Issue by rhbeffect** [MultiMC/MultiMC5#1343]
I recently tried to rebuild FTB Monster so i could play with updateds mods and throw a few of my favourites in to play with but whenever i launch the pack is crashes at the end of initializing mods phase one and give me exit code -1

anybody able to help please

**Comment by peterix** [comment]
Attach a link to the log (you can upload it from the console window)

**Comment by rhbeffect** [comment]
https://paste.ee/p/Y3Jg7#

this is the link it gives me

**Comment by rhbeffect** [comment]
feel as thought it will be something stupid that has caused it

**Comment by rhbeffect** [comment]
closed it by accident :(

**Comment by Slikrick** [comment]
Do not use Forestry 4.x with reika's mods until he updates his compat. So either downgrade forestry and its addons or dont use reika's mods.

**Comment by peterix** [comment]
Yeah, there's also a potion ID conflict or two between reika mods and Ars Magica.

**Comment by Slikrick** [comment]
Also binnie's mods appear to be included, which also aren't compatible with forestry 4 yet either. So i definitely suggest downgrading that

**Comment by rhbeffect** [comment]
ill give it a try now. thanks guys

**Comment by rhbeffect** [comment]
you guys are AMAZING 

i take my hat off to all of you :D

**Comment by rhbeffect** [comment]
its taken you guy 30 mins to sort out what has taken me over an hour to try and figure out
