### ISSUE TITLE
Fatal errors were detected during the transition from CONSTRUCTING to PREINITIALIZATION. Loading cannot continue

### ISSUE THREAD

**Issue by mjc4wilton** [MultiMC/MultiMC5#1345]
So I am building a FTB modpack. I downloaded all the mods and put them into MiltiMC to get configs and stuff correct and verify that everything works. I ran into quite a few errors, I was able to fix them though until I got here. I searched online and everything and apparently nothing wants to work for me. 

Heres the error log:
http://pastebin.com/CHjwCcFY

**Comment by peterix** [comment]
mcheli is a weird, weird mod. look inside the zip. There's a readme file. Try to read it.

It looks like you have to extract parts of the zip and put them in mods and assets folders in some way... It's all in japanese and I have no idea what it actually says...

**Comment by mjc4wilton** [comment]
Peterix I've tried disabling MCHeli, Thats not the problem

**Comment by peterix** [comment]
Then you have multiple problems.

**Comment by mjc4wilton** [comment]
IDK, I'll take a look into it

**Comment by mjc4wilton** [comment]
Peterix, I messed around some more, got a little farther, then another error so yeah:
http://pastebin.com/vjr52JuK

**Comment by peterix** [comment]
That looks like some sort of incompatibility between forestry and binnie mods.

Maybe downgrade forestry?

**Comment by wlhlm** [comment]
Binnie's Mods do not support Forestry 4.

Either downgrade Forestry or remove Binnie's. Note that the latter can also affect other mods. For example FTB Infinity is currently stuck with old versions, because of Binnie's. From the Changelog:

> Mods that cannot be updated due to Binnie's Mods not supporting Forestry 4:
> - Bdlib
> - Forestry
> - Gendustry
> - Immersice Engineering
> - Magic Bees
> - NEI Addons
> - NEI Intergration
