### ISSUE TITLE
[Client thread/WARN] [FML]: Offendor: org/multimc/EntryPoint.main([Ljava/lang/String;)V

### ISSUE THREAD

**Issue by drago87** [MultiMC/MultiMC5#1348]
I'm having a bit of a problem. i have a home made modpack that works on the vanilla louncher but when i remade the pack with MultiMC i get this error

http://paste.ee/p/QPiNU

i alocate 8gb of ram and 512 permgen (the same as i use with the vanilla louncher)
i only copied the mods and the config folder from the vanilla louncher.
i'm using the same version of Forge (10.13.4.1564)
i have tried with and without -Dforge.forceNoStencil=true (i'm using this with te vanilla louncher)

**Comment by peterix** [comment]
update forge relocation - it seems to be outdated

**Comment by peterix** [comment]
If that doesn't help and if you have a '1.7.10' folder inside the mods folder, consider removing it. Some mods download more stuff and put it there and it can go all sorts of wrong.

**Comment by peterix** [comment]
Found some random forum with the same error and it was suggested to use java 7... for whatever reason. So, that's another thing to try.

**Comment by drago87** [comment]
forge relocation was the wrong verson. apperently it downloaded an old version.

And that seams to have been it. tanx
