### ISSUE TITLE
Add a close button to the UI

### ISSUE THREAD

**Issue by fusionmc-evilscoop** [MultiMC/MultiMC5#1349]
When streaming multimc via steam, all windows decorations etc are removed, leaving no way to close multimc without rdp'ing to remote machine.

Can you please add a close or exit button somewhere in the application so its more steam stream friendly.

Thanks

**Comment by peterix** [comment]
As a workaround, plain old Alt+F4 might work. If you have a keyboard.

That aside, how does that even work with multiple windows?

**Comment by fusionmc-evilscoop** [comment]
ahhh alt-f4 will try tonight, yes heyboard is still active, so is mouse on the window

have to say multi mc apart from this minor issue does work well on the stream...not tried on a steam link yet though

**Comment by fusionmc-evilscoop** [comment]
Just to update, alt f4 does indeed work...
This may/may not be an issue on a steam link if using controller rather than keyb/mouse, but for now workaround is good.

**Comment by fusionmc-evilscoop** [comment]
why was this closed.
its a quick fix, but moving forward into oculous territory, controllers wont have an alt-f4 but will have mouse support.
This will need something doing at some point.

**Comment by peterix** [comment]
@02JanDal probably got a bit overzealous with the close button :)

**Comment by peterix** [comment]
It most likely will get closed once I move it over to the real idea/planning list.

**Comment by peterix** [comment]
So, there's a need for a close button in the short term, and a theme/layout more usable in this kind of situation later.

[Moved to workflowy (Ideas -> Support fullscreen/single application view)](https://workflowy.com/s/2EyDMcp7CU)
