### ISSUE TITLE
Writing a file to desktop

### ISSUE THREAD

**Issue by Practiclycrp** [MultiMC/MultiMC5#1350]
When launched, MultiMC writes a file to the desktop even though it's ran in it's own folder on the desktop. ( MultiMC v0.4.7 Stable branch Windows 7x64 )
Unable to include the file into this post, I'll include a link with a download.
https://db.tt/wQlzqcQF
MultiMC-0.log
http://pastebin.com/FqXQqMbM

**Comment by 02JanDal** [comment]
Content of the file:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<variables>
    <config name="@default"/>
</variables>
```

Anyone have any ideas of what this is for?

**Comment by peterix** [comment]
I'm pretty sure MultiMC does not write any XML, ever. It must be something else, unrelated to MultiMC.
