### ISSUE TITLE
Some weird java 1.8 problems

### ISSUE THREAD

**Issue by SHIuSH** [MultiMC/MultiMC5#1351]
I have 2 modpacks:
* first needs any java
* second needs java 1.8 or newer.

These 2 packs are on MultiMC and default Minecraft launcher.

Nvidia videocard that is suposed to be used for javaw.exe.

And here is the problem:
First pack is working fine on both launchers(uses nvidia videocard), but second only works OK on default launcher(javaw.exe launched by MultiMC is not using nvidia videocard)

P.S. If game is not using nvidia, PC just overheats, because of weak integreated INTEL  videocard

**Comment by peterix** [comment]
Reformatted for readability :)

**Comment by 02JanDal** [comment]
Try renaming MultiMC.exe to minecraft.exe
