### ISSUE TITLE
[Linux] Cannot open folders under Ubuntu GNOME

### ISSUE THREAD

**Issue by Mach12** [MultiMC/MultiMC5#1352]
When I switched from Unity to GNOME (on Ubuntu desktop), all buttons in MultiMC that were supposed to open a folder stopped doing it. No error report or what, just not doing it.

I assume you were using Unity short-cuts or something like that. If I may suggest something, how about a fallback to just calling Nautilus? Most Ubuntus have it... or have Dolphin.

**Comment by peterix** [comment]
all it does is call default open on a local path. so your system is likely not configured properly
