### ISSUE TITLE
Modded minecraft instances not loading - exitcode 1 error

### ISSUE THREAD

**Issue by ziba1** [MultiMC/MultiMC5#1353]
Hi, today I just downloaded this program, as I want to, edit a mod-pack myself and 2 friends play on our server to have some additional mods we want to play with, and delete some of the mods we just don't play with.
So I installed this program and... well couldn't figure out how to directly add the pack to the program as an instance, so made a vanilla instance and added the mods to the vanilla instance by going into the mod folder of the pack on my machine.  And also adding the configs from the pack as well.

Not done anything else, but decided to boot up the pack to make sure its working before trying to modify it.

Booted up and a console window appears giving me a load of logs  but nothing happens, the logs say "game exited with exitcode 1"
Gave a quick google of the error and its apparently a java issue ?  My java is up to date 

I dont know what to do now, brand new to this program and to the world of editing modpacks.

heres a pastebin of the bootup logs

Cheers 

http://pastebin.com/bKq3Q5mS

**Comment by 02JanDal** [comment]
The name of your instance ends with a space, try creating a new instance (or copying this one) and make sure the name does not end with a space.
