### ISSUE TITLE
Server resource packs do not work

### ISSUE THREAD

**Issue by JamesTheCoder** [MultiMC/MultiMC5#1363]
When you say yes to a server resource pack, your game will crash instantly. This works regardless of whether mods are installed. The logs below include optifine but that is not necessary.

Logs:
[latest.log.txt](https://github.com/MultiMC/MultiMC5/files/67783/latest.log.txt)
[crash-2015-12-20_11.08.33-client.txt](https://github.com/MultiMC/MultiMC5/files/67782/crash-2015-12-20_11.08.33-client.txt)
[Paste.ee link](http://paste.ee/p/v8qL8)

**Comment by 02JanDal** [comment]
Please upload the full log using the Upload Log button, and post the link you get here.

**Comment by JamesTheCoder** [comment]
Have updated original issue.

**Comment by 02JanDal** [comment]
Possibly related to this line from the vanilla launcher changelog: `1.6.13	July 1, 2015	
Launcher now creating folder "server-resource-packs" in game directory.`

**Comment by JamesTheCoder** [comment]
**Update.** I have written a patch in MCP that fixes the issue for 1.8.9. Am now trying to add this functionality to MultiMC - will make a pull request when done.

**Comment by 02JanDal** [comment]
This issue was already fixed in 432e812. Fixing this in MCP, only for 1.8.9, would mean that versions prior to that wouldn't be fixed, nor would versions without forge. See also #1275 for the issue that tracked this (it should've been linked here earlier).
