### ISSUE TITLE
Skin Changing Issue - MultiMC

### ISSUE THREAD

**Issue by GreenJelly64** [MultiMC/MultiMC5#1364]
So I change my skin a lot because I play Pixelmon and create custom trainers. Recently I tried changing my skin and it updated in Minecraft (Not MultiMC) but didn't update on my account (MultiMC). I am playing in 1.7.10 so my skin should change immediately.

**Comment by peterix** [comment]
Try the develop version (you can switch to it in the settings and then update)

**Comment by peterix** [comment]
Reopen if it still is an issue in 0,4,8
