### ISSUE TITLE
[Recommendation] Image Behind instances

### ISSUE THREAD

**Issue by MagicCraftMaster** [MultiMC/MultiMC5#1366]
it would be nice to have a feature where you could add a custom image behind you instances like the cat button with a drop down or something.

this is by no means an issue i just had no clue where to put a recommendation.
i love to use MultiMC and i only use it the only times i don't is when i need a FTB, Technic, etc. modpack

**Comment by wlhlm** [comment]
(BTW, MultiMC supports FTB instances directly, see Settings -> MultiMC -> Features -> Track FTB instances)

**Comment by MagicCraftMaster** [comment]
i know it supports FTB instances by default i just don't use that to get them

**Comment by peterix** [comment]
Soon (TM).

It's possible we'll have full theme support sooner than this.

**Comment by peterix** [comment]
[Moved to worflowy (Ideas -> Theming)](https://workflowy.com/s/2EyDMcp7CU)
