### ISSUE TITLE
Dependency library installation hint is nonsense on Arch Linux

### ISSUE THREAD

**Issue by gmaslov** [MultiMC/MultiMC5#1370]
On Arch Linux I received this message when trying to launch MultiMC:

    Error: MultiMC is missing the following libraries that it needs to work correctly:
        libpng12.so.0, libpng12.so.0, libpng12.so.0, libpng12.so.0, libpng12.so.0, libpng12.so.0, 
    Please install them from your distribution's package manager.

    Hint: sudo pacman -S community/sage-mathematics community/sage-mathematics community/sage-mathematics community/sage-mathematics community/sage-mathematics community/sage-mathematics 

sage-mathematics is a very strange package to recommend installing as a dependency. The recommendation should be libpng12 from the AUR: https://aur.archlinux.org/packages/libpng12/

**Comment by peterix** [comment]
Fixed by including libpng12.so.0 in the generic package.

**Comment by peterix** [comment]
It's likely the package does somehow contain the library... maybe it would work as expected if it used yaourt or something similar. But the underlying issue should be gone.

**Comment by gmaslov** [comment]
Thanks for fixing this! :-)
