### ISSUE TITLE
Windows launch instances via shortcuts?

### ISSUE THREAD

**Issue by spiral6** [MultiMC/MultiMC5#1372]
I'd like to launch an instance of MultiMC via a shortcut on the desktop. How do I do so? There are no instructions that I can find that allow me to do so.

**Comment by wlhlm** [comment]
#253

**Comment by spiral6** [comment]
I've tried the launcher parameters, but it still doesn't work. Maybe the instructions aren't clear enough, but I thought adding the parameters to the Target box of the shortcut would work?

**Comment by peterix** [comment]
You need the devel version. You can switch to that by changing the update channel in settings and updating.

I have no idea what 'target' is, but you need to run it like this:
`MultiMC -l "ID of Instance"`

Where the ID is the name of its folder (not the display name in MultiMC).

**Comment by 02JanDal** [comment]
Done in develop.
