### ISSUE TITLE
Java issue?

### ISSUE THREAD

**Issue by docwalliday** [MultiMC/MultiMC5#1380]
After installing forge multimc started giving the following error:

[03:24:40] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.7.0_79, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jdk1.7.0_79\jre

I've tried changing versions of java and removing and re-installing forge, help is appreciated!

**Comment by loordgek** [comment]
that is not a error

**Comment by peterix** [comment]
Just use the upload button and link the log uploaded to paste.ee here.

**Comment by KamranMackey** [comment]
@docwalliday That isn't an error, as you can see by `[main/INFO]`. Errors would be classified as `[main/ERROR]`.
