### ISSUE TITLE
Modpack stopped working all of a sudden!

### ISSUE THREAD

**Issue by MinerX96** [MultiMC/MultiMC5#1381]
Here is the log: https://paste.ee/p/M0vEJ

I have tried pretty much everything. Turning computer on and off, reinstalling Minecraft several times, and even trying to install java 7 and 8, yet nothing works. I'm not sure what happened. It was working the night before. I haven't added any new mods, left the memory allocation at default and I come online today with not only my modpack but even vanilla Minecraft not running in MultiMC5. I have spent two hours trying to fix this and I am quite frustrated now. Any help would be appreciated! Thanks!

**Comment by peterix** [comment]
Interesting. There's pretty much nothing in that log. Only that it failed fast.

If you use the 'test' or 'auto detect' button in multimc java settings, what happens?

What version of Windows is that? What sort of security software are you using?

**Comment by MinerX96** [comment]
I am using Comodo as a security software, using windows 8, and when I press the auto detect button it says no java versions available.

Sorry for the late reply.

**Comment by peterix** [comment]
MultiMC writes its own log - MultiMC-0.log is the latest one from the current run, everything with higher numbers if older.

Upload the log with you trying the various autodetection and test buttons.

**Comment by MinerX96** [comment]
I'm not sure how to do that. Also when I press the test button this comes up:

**Comment by MinerX96** [comment]
The specified java binary didn't work.
You should use the auto-detect feature, or set the path to the java executable.

**Comment by peterix** [comment]
Well, the log says that java can be found here:
```
C:/Program Files/Java/jre1.8.0_66/bin/javaw.exe
```

Is it actually there?

**Comment by MinerX96** [comment]
Yes.

**Comment by MinerX96** [comment]
Sorry. Actually no it's not here. Should I try to reinstall Java?

**Comment by peterix** [comment]
Check `C:/Program Files/Java/` and see what's there - do you have any other java installs in there?

**Comment by MinerX96** [comment]
No.

**Comment by peterix** [comment]
Alright, install java.

**Comment by MinerX96** [comment]
Okay, I have installed Java .

**Comment by peterix** [comment]
The autodetect should work now.

**Comment by MinerX96** [comment]
It still says no versions available. Is there a certain version of Java I should get?

**Comment by peterix** [comment]
Right. That's weird. Are you installing it system-wide, or in some per-user way?

You can grab java here:
http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

If your system is 64bit, grab the 64bit version.

**Comment by MinerX96** [comment]
Okay. I installed 64 bit java again. I am installing it system wide.

**Comment by MinerX96** [comment]
This is something I found quite odd. I looked in my vanilla minecraft with the official launcher and it has the same java directory that I tried in MultiMC.

**Comment by peterix** [comment]
The java installer writes the location in the registry and mmc reads that. If you have Java installer and this doesn't work... then something really weird happened.

However, you can also always point MultiMC to the actual javaw.exe, if it doesn't detect the install. So just click the browse button next to the java path and select an actual, existing javaw.exe

The current vanilla launcher actually comes with its own copy of java. So you could make MultiMC use that too - and probably get rid of the system-wide install, if you don't need it for something else.

I plan to go this route too - just make mmc download a version of java so people don't have to deal with this.

**Comment by peterix** [comment]
The next version will actually allow bundling java with mmc. So far, if you have the develop version, you can have java in the mmc folder and it will work, using a relative path. It's ready for the next step :)

**Comment by MinerX96** [comment]
I pointed MultiMC to an actual javaw.exe. It still shows up with the same error. I tried increasing the memory. I know I keep rambling on but wherever I put java or whatever version I use it still comes up with the same error. 

You were also talking about a develop version. Is there a way to download that? If so that might help MultiMC find the java location.

**Comment by peterix** [comment]
It's in the settings. Just change the update channel and update.

**Comment by peterix** [comment]
Can you upload the log?

It's in the MultiMC folder. Just run MultiMC, click the test button in the java settings and put the contents of MultiMC-0.log on a site like paste.ee

**Comment by MinerX96** [comment]
Here is the log: https://paste.ee/p/B01da

I also updated my MultiMC

**Comment by MinerX96** [comment]
I updated it to the developer version and MultiMC ran! I am so happy! Thanks peterix!

**Comment by peterix** [comment]
Now that's an extra mystery!

Alright. That developer version should turn into a new stable version soon-ish. Once that happens, I'd suggest going back to stable, because I'll be doing some crazy things to the dev one :)

**Comment by MinerX96** [comment]
Okay! Thanks again!
