### ISSUE TITLE
Is this like the technic Launcher?

### ISSUE THREAD

**Issue by Badcholo** [MultiMC/MultiMC5#1386]
I was looking for an alternative to the technic launcher. I have not been able to set it up properly to download my modpack successfuly with my dropbox link having the folder configured and setup in different ways. Also is there a way to include in my modpack, the forge version?

**Comment by peterix** [comment]
Well, the technic launcher is aimed at people who just want to play a pre-made modpack.

MultiMC is for power users and making modpacks. There's an option to export and import modpacks built in - those are basically zip files with the instance inside. And this 'just works' - with MultiMC.

You'll have to give me more details - or even include the links. Because I have no idea what exactly are you doing.

**Comment by Badcholo** [comment]
Yes, i have created modpacks and would like to distribute them to players so that they can play on my custom modpack servers. As the technic launcher, i would like to give players a link to MultiMC and make it easy for them to download my pre-setup modpack with configs-resource packs ect.

**Comment by Badcholo** [comment]
How would i go about importing my zip modpack, what is the file format? or if anything special.
I currently have my zip modpack like the techinic launcher wants it with the forge in the bin folder and then of course mods, configs, ect.

**Comment by KuroNeko87** [comment]
best bet is to create your modpack and launch it, test it, fix id conflicts, etc then delete anything you don't want like saves, options, usernames, etc

navigate to your instances folder and then zip the folder that has your instance. zip format

**Comment by peterix** [comment]
Nope. There's actually a better option.

Use the export feature. You don't have to delete anything, it lets you select what gets exported and remembers it for the future.

Then you can install such exported pack either using the resulting zip file directly, or using an URL (any accessible http link will work).

**Comment by KuroNeko87** [comment]
oohhh i like that one!

**Comment by Badcholo** [comment]
Oh i see, I'll try that, Thanks.

**Comment by peterix** [comment]
The export is right on the main window action toolbar. Import is part of the new instance dialog.

**Comment by peterix** [comment]
One thing it doesn't do though is pack updates. So, it's not entirely like launchers made specifically for modpacks.

**Comment by Badcholo** [comment]
I understand, i actually like clean installs instead of updating it, sometimes it seems to bug out. I really preffer the modpack to be reinstalled, plus the data is saved to the server so that should be fine.

**Comment by Badcholo** [comment]
I think i will like this better as well for when i'm working on my modpacks, Thanks so much.

**Comment by peterix** [comment]
When you (and your users) have some experience with it, I'd love to get some feedback. It's not buggy or broken, but I suspect the usability could be improved.

**Comment by Badcholo** [comment]
I'd love to. I'm pretty excited about using it.

**Comment by peterix** [comment]
Closing - if you have any questions, just ask :)
