### ISSUE TITLE
Mac/OSX Main window and log window stuck in full screen

### ISSUE THREAD

**Issue by J4bber** [MultiMC/MultiMC5#1387]
I accidentally clicked the green button at the top of the windows on my Mac and not they are stuck in full screen mode.  when I click the green button again, it just "looks at me funny" :)  I have tried all the keyboard shortcuts also, but havent found anything that will take it out of full screen.  This is the latest versions of MultiMC5 and OSX...

**Comment by peterix** [comment]
It's El Capitan? The App Store is just giving me `(null)` errors today.

**Comment by F4ndroid** [comment]
Try holding the Option key while clicking the expand (green) button on the top-left of the window.

**Comment by peterix** [comment]
Oh. OK.

I have no idea what's going on there. Looks like the UI framework we use does something wrong in this case.

**Comment by peterix** [comment]
Possibly related:
https://bugreports.qt.io/browse/QTBUG-39210

**Comment by peterix** [comment]
I managed to confuse it first time - I somehow ended up with a black screen that didn't react to anything - but now it works fine.

This is on Yosemite.

**Comment by J4bber** [comment]
So I did some more testing and it is actually Yosemite having the problem.
I have this on another system that has El Capiton and it is working fine
there.

**Comment by peterix** [comment]
So, something between some versions of OSX and Qt5... ok.

**Comment by peterix** [comment]
Please re-test with current develop build.
