### ISSUE TITLE
DNF in launch script

### ISSUE THREAD

**Issue by KuroNeko87** [MultiMC/MultiMC5#1390]
include dnf in the launch script
add before yum

	# dnf
	elif which dnf &>/dev/null; then
		LIBRARIES=`echo "$DEPS_LIST" | grep -oP "[^, ]*"`
		COMMAND_LIBS=`for LIBRARY in $LIBRARIES; do dnf whatprovides $LIBRARY; done`
		COMMAND_LIBS=`echo "$COMMAND_LIBS" | awk -vORS=" " '{ print $1 }'`
		INSTALL_CMD="sudo dnf install $COMMAND_LIBS"

**Comment by peterix** [comment]
OK. That doesn't produce a very nice output as the install hint.

The script should also pass the list of missing libraries through `sort -u` before resolving them, and then pass the list of packages it comes up with through `sort -u`.

**Comment by peterix** [comment]
`dnf` also suggests installing 32bit libraries while being 64bit... this thing is buggy.

**Comment by peterix** [comment]
This is now as good as it gets... there's still the xcb issue though. I have no idea what to do with that.
