### ISSUE TITLE
[1.7.10][Modded] crashreport opening "controls" pannel

### ISSUE THREAD

**Issue by UzeJah** [MultiMC/MultiMC5#1394]
This is my crashreport when i want to open the controls pannel ingame. It is the same mod than FTB infinity evoled just with a couple more mods but it doens't work.

http://paste.ee/p/cY5C2

**Comment by peterix** [comment]
This is a mod bug, not anything we could fix.

```
-- Affected screen --
Details:
	Screen name: modwarriors.notenoughkeys.gui.GuiControlsOverride
```

I assume this notenoughkeys mod is involved. Try to contact its author.
