### ISSUE TITLE
SSL/TLS handshake failed on OSX

### ISSUE THREAD

**Issue by Dogylover200** [MultiMC/MultiMC5#1398]
When ever i try to import a link it shows that it completes but it isn't there idk if its a visual bug or i have to restart MultiMC but can you help anyone?

**Comment by 02JanDal** [comment]
Please upload MultiMC-0.log to pastebin or similar, and post the link here.

**Comment by Dogylover200** [comment]
http://pastebin.com/UkiuQkGB The modpack link: https://dries007.net/downloads/EntWorld_v3.2.3.zip

**Comment by 02JanDal** [comment]
```
42.975 D Downloading  "https://dries007.net/downloads/EntWorld_v3.2.3.zip"
44.200 C Failed  "https://dries007.net/downloads/EntWorld_v3.2.3.zip"  with reason  6
```

"the SSL/TLS handshake failed and the encrypted channel could not be established"

A workaround would be to download the zip file using a normal web browser.

**Comment by Dogylover200** [comment]
ok thanks

**Comment by Dogylover200** [comment]
When i try to make the modpack it says (Failed to extract modpack) help here?

**Comment by 02JanDal** [comment]
Please pastebin MultiMC-0.log again.

**Comment by Dogylover200** [comment]
http://pastebin.com/9Qcpt7ED

**Comment by peterix** [comment]
Which OSX is this?

**Comment by peterix** [comment]
Also, try the develop version of MultiMC. You can switch to it in the settings (update channel) and then update.

**Comment by peterix** [comment]
Now tracked.

I have no idea what happens... chrome on linux can grab that file just fine. So does MultiMC.

The two issues I see here:
* MultiMC is not logging the OS and OS version in its log. All I know is that you use OSX.
* The SSL errors are not logged fully.

So, I can't diagnose this in any way.

**Comment by peterix** [comment]
I've updated the version of Qt to 5.6, dropped support for OSX 10.7, and effectively switched away from OpenSSL.

This should now work flawlessly in current develop versions.
