### ISSUE TITLE
1.8.9 bug with screenshots!!

### ISSUE THREAD

**Issue by 00Small00** [MultiMC/MultiMC5#1399]
When you make a screenshot and open it via the lake freezes maynkraft!!

**Comment by peterix** [comment]
Ok.

I create a 1.8.9 instance.
I run the instance.
I make a screenshot wit the menu open.
I upload said screenshot from MultiMC.

It works without issues.

Is this what you are doing?
What operating system are you using?

Post a link to the log uploaded using the `Upload` button.

**Comment by 00Small00** [comment]
OK
1) I open maynkraft 1.8.9
2) I go in the world
3) to take screenshots
4) Open
5) Hangs
Windows 7 SP1
![screenshot_1](https://cloud.githubusercontent.com/assets/16637899/12371505/8d09d340-bc3e-11e5-9270-ab47d052efe2.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/16637899/12371506/8d0c1cc2-bc3e-11e5-83df-0ad4ab01aa01.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/16637899/12371507/8d11b754-bc3e-11e5-9424-dede99f3edda.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/16637899/12371508/8d14612a-bc3e-11e5-8cc3-ac33924575c2.png)

**Comment by peterix** [comment]
That is java crashing. Hard. In native code.

Which is probably a graphics bug of some sort. So, something with optifine, the graphics driver or some hardware issue.

Have you tried without optifine? Have you tried updating optifine?

**Comment by 00Small00** [comment]
ohne optifine das selbe.

**Comment by 00Small00** [comment]
without optifine same

**Comment by Badcholo** [comment]
Minecraft does that all the time with many different launchers. I'd check and make sure your video driver is updated and working properly. Also this seems to happen to me lots when i have any browser open or other resource intensive program running in the background, such as having too many curse pages open or playing music and browsers open.

**Comment by peterix** [comment]
So, some sort of race condition in java... nice. This is most likely a java bug.

**Comment by Badcholo** [comment]
I would assume so. It almost appears as if java is trying to catch up with something. If i close down all other programs after like 30sec it starts working properly again. He may also need to allocate more ram to java and make sure he is using java8 64 bit.

**Comment by peterix** [comment]
You may be talking about a second issue... It can't come back from a hard crash.
