### ISSUE TITLE
Crash with instance, probably related to core mods

### ISSUE THREAD

**Issue by Tinster101** [MultiMC/MultiMC5#1405]
I googled the exception, that is, `java.lang.NoClassDefFoundError: net/minecraftforge/fml/relauncher/IFMLLoadingPlugin`, and it seems to be mostly related to missing core mods, but I can't figure out if any are missing!

[Full crash log](http://paste.ee/r/qkgk3)

**Comment by Kilobyte22** [comment]
That looks suspiciously like you have a mod for a wing version of Minecraft. From your modlist that seems to be Wawla (it's for 1.8 judging by the name). Possibly there are others.

**Comment by Tinster101** [comment]
Ok, thanks for replying so quickly. I skimmed through the modlist, but must've missed that one. Will report back with results.

**Comment by Tinster101** [comment]
Ok, no idea what happened, it crashed once, then I deleted the 1.7.10 folder in the mod folder that appeared (I read something about it being unnecessary and causing duplicate mod crashes). I loaded it up again, it did the "CB's DepLoader is setting up your minecraft environment" thing then [crashed again](http://paste.ee/p/Jywxb).  
Any clues?

**Comment by Kilobyte22** [comment]
You are still having a 1.8 mod in there (iron chest). If removing that doesn't fix it and you still get the same error, try removing all mods that don't have a Minecraft version number in their name and adding them one-by-one until it crashes.

**Comment by Tinster101** [comment]
Sure, will do

**Comment by DrZed** [comment]
CustomBackgrounds-1.0 = 1.8, 1.8.8, 1.8.9
http://minecraft.curseforge.com/projects/custom-backgrounds/files/2220095
Inventory Tweaks 1.59 (API) for Minecraft 1.8 you need 1.58

**Comment by DrZed** [comment]
I searched through your crash and looked at all mods... Found those 1.8 mods in there, remove and downgrade... Learn to read the versions they're meant for on curse, it's not hard to see...

**Comment by peterix** [comment]
Assuming fix by removing or replacing wrong mods.
