### ISSUE TITLE
This happens everytime

### ISSUE THREAD

**Issue by AllthestuffPlays** [MultiMC/MultiMC5#1406]
Everytime i run minecraft it just crashes im using MultiMC but this have never happen before.
This is the crash

**EDIT (@02JanDal): removed jumbled mess**

i dont know if it should be (shutdown with the code -1.) cause im swedish and it normaly says avslutades med koden -1. so i dont know if it should be that

**Comment by 02JanDal** [comment]
Please upload the full log using the Upload log button, and post the paste.ee link here.

**Comment by AllthestuffPlays** [comment]
That is the full log

**Comment by 02JanDal** [comment]
It wasn't, and also it was completely unreadable.

**Comment by AllthestuffPlays** [comment]
MultiMC version: 0.4.7Minecraft folder is:C:/Users/Milton/Desktop/Minecraft/MultiMC/instances/1.8/minecraftJava path is:javaJava Arguments:[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -jar, C:/Users/Milton/Desktop/Minecraft/MultiMC/jars/NewLaunch.jar]Minecraft 5188Using onesix launcher.Main Class:  net.minecraft.client.main.MainNative path:  C:/Users/Milton/Desktop/Minecraft/MultiMC/instances/1.8/nativesTraits:  []Libraries:  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/com/mojang/realms/1.7.55/realms-1.7.55.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar  C:/Users/Milton/Desktop/Minecraft/MultiMC/versions/1.8.9/1.8.9.jarParams:  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, C:/Users/Milton/Desktop/Minecraft/MultiMC/instances/1.8/minecraft, --assetsDir, C:/Users/Milton/Desktop/Minecraft/MultiMC/assets, --assetIndex, 1.8, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {}, --userType, mojang]Window size: 854 x 480Preparing native libraries...Extracting twitch-platform-6.5-natives-windows-32.jarExtracting twitch-external-platform-4.5-natives-windows-32.jarExtracting jinput-platform-2.0.5-natives-windows.jarExtracting lwjgl-platform-2.9.1-natives-windows.jar[20:49:25] [Client thread/INFO]: Setting user: <PROFILE NAME>[20:49:25] [Client thread/INFO]: (Session ID is <SESSION ID>)[20:49:26] [Client thread/INFO]: LWJGL Version: 2.9.1[20:49:26] [Client thread/ERROR]: Couldn't set pixel formatorg.lwjgl.LWJGLException: Pixel format not accelerated	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.1.jar:?]	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.1.jar:?]	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252) ~[lwjgl-2.9.1.jar:?]	at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.1.jar:?]	at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.1.jar:?]	at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.1.jar:?]	at ave.ap(SourceFile:521) [1.8.9.jar:?]	at ave.am(SourceFile:363) [1.8.9.jar:?]	at ave.a(SourceFile:310) [1.8.9.jar:?]	at net.minecraft.client.main.Main.main(SourceFile:124) [1.8.9.jar:?]	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]---- Minecraft Crash Report ----// Surprise! Haha. Well, this is awkward.Time: 1/13/16 8:49 PMDescription: Initializing gameorg.lwjgl.LWJGLException: Pixel format not accelerated	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)	at org.lwjgl.opengl.Display.createWindow(Display.java:306)	at org.lwjgl.opengl.Display.create(Display.java:848)	at org.lwjgl.opengl.Display.create(Display.java:757)	at org.lwjgl.opengl.Display.create(Display.java:739)	at ave.ap(SourceFile:534)	at ave.am(SourceFile:363)	at ave.a(SourceFile:310)	at net.minecraft.client.main.Main.main(SourceFile:124)	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)	at java.lang.reflect.Method.invoke(Unknown Source)	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)	at org.multimc.EntryPoint.listen(EntryPoint.java:170)	at org.multimc.EntryPoint.main(EntryPoint.java:54)A detailed walkthrough of the error, its code path and all known details is as follows:----------------------------------------------------------------------------------------- Head --Stacktrace:	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)	at org.lwjgl.opengl.Display.createWindow(Display.java:306)	at org.lwjgl.opengl.Display.create(Display.java:848)	at org.lwjgl.opengl.Display.create(Display.java:757)	at org.lwjgl.opengl.Display.create(Display.java:739)	at ave.ap(SourceFile:534)	at ave.am(SourceFile:363)-- Initialization --Details:Stacktrace:	at ave.a(SourceFile:310)	at net.minecraft.client.main.Main.main(SourceFile:124)	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)	at java.lang.reflect.Method.invoke(Unknown Source)	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)	at org.multimc.EntryPoint.listen(EntryPoint.java:170)	at org.multimc.EntryPoint.main(EntryPoint.java:54)-- System Details --Details:	Minecraft Version: 1.8.9	Operating System: Windows 7 (x86) version 6.1	Java Version: 1.8.0_66, Oracle Corporation	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation	Memory: 464833144 bytes (443 MB) / 519110656 bytes (495 MB) up to 1037959168 bytes (989 MB)	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0	Launched Version: MultiMC5	LWJGL: 2.9.1	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.	GL Caps: 	Using VBOs: No	Is Modded: Probably not. Jar signature remains and client brand is untouched.	Type: Client (map_client.txt)	Resource Packs: 	Current Language: ~~ERROR~~ NullPointerException: null	Profiler Position: N/A (disabled)	CPU: <unknown>#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Milton\Desktop\Minecraft\MultiMC\instances\1.8\minecraft\crash-reports\crash-2016-01-13_20.49.27-client.txtMinecraft avslutades med koden -1.

**Comment by 02JanDal** [comment]
Same issue. Use the upload log button, and post the paste.ee **LINK** here.

**Comment by AllthestuffPlays** [comment]
This is the log i copied from the crash

**Comment by AllthestuffPlays** [comment]
wait

**Comment by AllthestuffPlays** [comment]
http://paste.ee/p/khxK3 do you mean this im swedish and not so good at english so i wont be able o talk too much

**Comment by AllthestuffPlays** [comment]
#to

**Comment by AllthestuffPlays** [comment]
you will have to fix this problem i gtg!

**Comment by 02JanDal** [comment]
See #1283 for what seems to be the same issue. What graphics card are you using? It looks like it might be to old, but you could also try updating the drivers.

Titta på #1283 för vad som verkar vara samma problem. Vilken typ av grafikkort använder du? Det verkar som om den kan vara för gammal, men det kan gå att lösa genom att uppdatera drivrutinerna.

**Comment by AllthestuffPlays** [comment]
my graphics card is new i just changed it today and i am going to update the drivers

**Comment by AllthestuffPlays** [comment]
my graphics card is new i just changed it today and i am going to update the drivers

**Comment by AllthestuffPlays** [comment]
the drivers are already updated

**Comment by 02JanDal** [comment]
Do you maybe have some sort of on-board integrated graphics card?

**Comment by AllthestuffPlays** [comment]
And what is on-board integrated i dont know? im sorry but i dont know

**Comment by 02JanDal** [comment]
A second graphics card built into the computer.

Something to try: Can you launch Minecraft using the vanilla (Mojang) launcher?

**Comment by AllthestuffPlays** [comment]
no i just have one graphics card i can try to launch it from the vanilla launcher but i wont be able to do some things in the inventory thats why i use MultiMC

**Comment by AllthestuffPlays** [comment]
Nope it dosent work

**Comment by 02JanDal** [comment]
Ok, not a MultiMC issue then. Please report this to the [official Minecraft bugtracker](https://bugs.mojang.com/browse/MC) instead. Make sure to post the log from the vanilla launcher and not MultiMC there, otherwise you probably won't get any help.

**Comment by AllthestuffPlays** [comment]
ok thanks!
