### ISSUE TITLE
MultiMC Java Crash

### ISSUE THREAD

**Issue by MrsMeowys** [MultiMC/MultiMC5#1407]
Hello,

Multimc is not working on my computer at all when I try to create singleplayer worlds.
I even tried it without mods, and still gives me a crash.
I already searched everywhere, tried everything and nothing worked.
It says it's a java error, but I tried FTB and Vanilla minecraft and they work smoothly. It's just MultiMC giving me errors.
I alredy tried re-install java, allocate more memory, clean registry, install new java updates, updating my drivers, nothing of this worked.
Report: http://pastebin.com/SELQzbm5
I'm kinda desperate, I need to update my modpack and will be impossible without testing in singleplayer first.

Thank you.

**Comment by peterix** [comment]
You are running Evolve, most likely with the overlay enabled. I'm guessing they blacklist the other launchers to get rid of the problem, but do not blacklist MultiMC...

```
0x000007fee7c20000 - 0x000007fee7cbe000     C:\Program Files\Echobit\Evolve\Drivers\EvolveGameTracker_64.dll
0x000007fed7a40000 - 0x000007fed7c09000     C:\Program Files\Echobit\Evolve\Drivers\EvolveOverlayHelper_64.dll
0x000007feebac0000 - 0x000007feebae0000     C:\Program Files\Echobit\Evolve\EvolveEasyHook_64.dll
0x000007fed8e10000 - 0x000007fed8ef9000     C:\Program Files\Echobit\Evolve\Drivers\EvolveOverlayHelperOGL_64.dll
```

See:
https://www.evolvehq.com/games/minecraft/topics/troubleshooting-minecraft-crashes-when

**Comment by MrsMeowys** [comment]
I actually found the fix somewhere.
To rename MultiMC.exe to Minecraft.exe...

**Comment by peterix** [comment]
That will mess with updates a bit, at least the one from 0.4.7 to 0.4.8, when it comes. You'll end up with a MultiMC.exe when you update. Further updates after that will be fine though.

**Comment by MrsMeowys** [comment]
I confirm it works without evolve running. I'll let them know.
Thank you for your work and fast support!
Best regards.
