### ISSUE TITLE
Custom MC Versions

### ISSUE THREAD

**Issue by colt05** [MultiMC/MultiMC5#1409]
Hello.
Is there a way to add a Minecraft version that is currently on Mojang's servers? Like 15w14a?
Thanks,
colt05

**Comment by QuImUfu** [comment]
Yes, there is a way.
You can chance the version loaded to something completely custom, by pressing the customize button in instance settings (Version tab) and than the edit button.
Then chance the opened net.minecraft.json to load the version you want.
This can be done easily by using the vanilla json, for 15w14a: https://s3.amazonaws.com/Minecraft.Download/versions/15w14a/15w14a.json
and locking for changes. (note: the lwgl things are in a separate file in MultiMC)
The resulting file for 15w14a locks like this:
http://paste.ee/p/G3XFT

**Comment by colt05** [comment]
Ok thanks!
