### ISSUE TITLE
Update Error (0.4.7 to 0.4.8)

### ISSUE THREAD

**Issue by rocorreia** [MultiMC/MultiMC5#1413]
When I try to update  my MultiMc from 0.4.7 to 0.4.8, an error message appears before completeng the download of the "29 update files". I thought I could download 0.4.8 from the website, but what would happen to my instances on 0.4.7? Would they get carried over to the newer version? If anyone could help I´d appreciate. Also, I´m using Windows 7 ultimate, although I don`t know how this information can be used (or if it can even be used at all).

Error Message: 
Failed to download update files: Job 'Update Files' failed to process:
http://files.multimc.org/files/251e93666d4eb9d5e3efc6fd199980e1-Qt5Widgets.dll
http://files.multimc.org/files/6092f283732807b21e4ac306b70ae4ac-Qt5Core.dll
http://files.multimc.org/files/e189ac2cc8fd526b458634ac5d601070-Qt5Gui.dll

**Comment by peterix** [comment]
The instances are completely contained in the 'instances' folder. That's everything you **should** need.

If you use FTB tracking, or have copies of FTB instances made through the 'copy instance' function, you'll also need `libraries`.

If you limit the stuff carried over this way, it will cause a lot of stuff to redownload.

So, you can keep all this:
* accounts
* assets
* icons
* instances
* libraries
* mods
* versions
* accounts.json
* metacache
* multimc.cfg
