### ISSUE TITLE
Can't connect to mojang servers

### ISSUE THREAD

**Issue by Joviks** [MultiMC/MultiMC5#1417]
I updated to 0.4.8 last night and now it tells me the web/account/skin/auth/session servers are all down everytime I start MultiMC and it asks me for offlinemode name when I try to launch an instance

**Comment by peterix** [comment]
What sort of network connection do you have?

What OS do you use?

Some people reported it not working on Windows 7 while using a wifi connection.

For now, you can grab the previous version here:
https://www.dropbox.com/s/wx9gpomqo5834eq/mmc-stable-win32.zip?dl=0

**Comment by peterix** [comment]
Duplicate of #1408
