### ISSUE TITLE
Huge ping spikes while using MultiMC

### ISSUE THREAD

**Issue by TzZek** [MultiMC/MultiMC5#1422]
When MultiMc is First Started the Ping Issue Begins - http://prntscr.com/9sr888

Instantly spiking my ping anywhere from 400-12000ms+

**Comment by peterix** [comment]
This is related to the introduction of the Qt bearer plugins.

**Comment by peterix** [comment]
Related:
https://github.com/MultiMC/MultiMC5/issues/1417
https://github.com/MultiMC/MultiMC5/issues/1408

Upstream Qt bug:
https://bugreports.qt.io/browse/QTBUG-40332

I'll have to remove this feature from Qt entirely.

**Comment by peterix** [comment]
Also found here:
https://github.com/mumble-voip/mumble/issues/1585

The Qt bug has been closed by changing the plugin source code, but it was still a problem even without any plugins present:
https://bugreports.qt.io/browse/QTBUG-40332?focusedCommentId=280093&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-280093

**Comment by peterix** [comment]
@TzZek test this one: https://files.multimc.org/downloads/mmc-develop-win32.zip
it's with the previous Qt version and shouldn't have the problem.

If you can confirm that it doesn't lag anymore, I'll rebuild stable with this Qt.

**Comment by fusionmc-evilscoop** [comment]
This also affects streaming via steam, causing a lag spike every few secs which pauses the display for a moment each time.

Hope its gets fixed, as atm its unplayable via steam stream in current version.

**Comment by peterix** [comment]
Try the version above. Before running it, remove the plugins\bearer folder. See if that helps.

**Comment by peterix** [comment]
@fusionmc-evilscoop

**Comment by fusionmc-evilscoop** [comment]
will do, just double checked by rolling back a version and was ok...will try that dev one now

**Comment by fusionmc-evilscoop** [comment]
Ok version above, without bearer folder...nice stable graph ping etc  (steam stream f6)
With bearer folder, spike every few secs...
Thankfully dont have to start minecraft to see it with the steam graphs :D

**Comment by peterix** [comment]
OK. I'm going to push a stable version with this.
