### ISSUE TITLE
MC Crash on Launch - Clean Install

### ISSUE THREAD

**Issue by Zanano** [MultiMC/MultiMC5#1425]
Modded: http://paste.ee/p/1fDZZ
Clean: http://paste.ee/p/sGRhI
MC Crashes on launch via MultiMC. Clean install, not even Forge installed.
The attached paste is from a non-clean install, same error.

Edit: Added clean install log.

**Comment by 02JanDal** [comment]
What kind of graphics card are you using?

**Comment by Zanano** [comment]
GTX 960M.

**Comment by Zanano** [comment]
My PC crashed and now it works. Huh.
