### ISSUE TITLE
Issue with Mac/Forge

### ISSUE THREAD

**Issue by Regner6** [MultiMC/MultiMC5#1426]
I'm currently at my friends house on his mac and he wanted me to show him how to make a mod pack.

This is an issue we are having with forge.

https://gyazo.com/9b9092adc9a1ec08248ef2daf8b3cf77

**Comment by Slikrick** [comment]
Disable the forge loading screen in the config file "splash.properties" or reload your textures by going into the texture pack menu and exiting.

Its a known issue with mac and forge, not multimc related.

**Comment by peterix** [comment]
Maybe we could disable the splash screen on platforms where this is an issue. All it does is break graphics drivers there...

**Comment by peterix** [comment]
Added that idea to workflowy (Ideas -> Disable Forge splash screen on platforms where it causes problems):
https://workflowy.com/s/2EyDMcp7CU

I am assuming disabling the spash screen helped though.
