### ISSUE TITLE
MultiMC 0.4.9/0.4.10 Crazy slow load times and freezing issues

### ISSUE THREAD

**Issue by Theotherguy1223** [MultiMC/MultiMC5#1427]
ever since MultiMC updated to 0.4.9, my game has been loading crazy slow and I keep getting block lag and sent back in time, to the point that I wait up to a minute to 2-3 chunks to load. MultiMc takes up to 5 tries to delete worlds and occasionally freezes and hangs.

I have tested this with normal minecraft and various different instances, both modded and unmodded. I have also tested it across multiple version of the game and the issue persists only in MultiMC.

I have Windows 8.1 and I have allotted all the different instances 5gb of RAM

**Comment by peterix** [comment]
OK. Let's figure this out :)

Grab https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx if you don't have it already.

Once you have both running, click the upload button and post the log here.

In process explorer, check what MultiMC and java actually use vs. what you get in other launchers. Post screenshots here.

**Comment by Theotherguy1223** [comment]
Setup:
![Image] (http://puu.sh/mGwoC/39b39cbf42.png)
![Image] (http://puu.sh/mGxkC/d82c424680.png)

Screenshots:
![2016-01-23_08 41 41](https://cloud.githubusercontent.com/assets/12008758/12530566/7283867a-c1b0-11e5-83f2-ff24489d01e4.png)
![2016-01-23_08 41 58](https://cloud.githubusercontent.com/assets/12008758/12530567/7286b296-c1b0-11e5-80ba-81105edd6242.png)
![2016-01-23_08 42 10](https://cloud.githubusercontent.com/assets/12008758/12530569/7287800e-c1b0-11e5-999b-814545d1c0e8.png)
![2016-01-23_08 42 26](https://cloud.githubusercontent.com/assets/12008758/12530568/7286f1a2-c1b0-11e5-8e48-049fd1da6ae9.png)

Log:
http://paste.ee/p/WT6Yx

Note* This instance I'm using has OptiFine_1.8.9_HD_U_H1 in it, but I tested a duplicate of it without optifine, and it has the same issue, I can do this for the Vanilla Instance if you want instead.

**Comment by peterix** [comment]
Right.

Go into the global java settings and click that auto detect button. Select an actual java install. You have some system global default selected and it uses `java.exe`, it should be using `javaw.exe`.

Instead of 5GB max, use 4GB min AND max memory.

Try these java arguments:
```
-Xmn2G -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=60 -XX:-UseAdaptiveSizePolicy
```

**Comment by peterix** [comment]
The explanation of those arguments and settings can be found here:
https://workflowy.com/s/2EyDMcp7CU

Ideas -> Java -> Java args optimization

**Comment by peterix** [comment]
Do you use that integrated GPU, or do you have a dedicated one also?

Another thing to try is to rename `MultiMC.exe` to `Minecraft.exe`... some graphics drivers depend on file names like that.

**Comment by Theotherguy1223** [comment]
I have an integrated AMD Radeon R5

**Comment by Theotherguy1223** [comment]
Attempt 2 with suggestions:
Setup:
![9ac748cf91](https://cloud.githubusercontent.com/assets/12008758/12530788/3e1a710c-c1b8-11e5-8f4b-ed7f6c97b601.png)
![67fced542a](https://cloud.githubusercontent.com/assets/12008758/12530787/3e17c8f8-c1b8-11e5-88cf-f8907d590fa4.png)

Screenshots:
![2016-01-23_09 54 50](https://cloud.githubusercontent.com/assets/12008758/12530801/7473b4d4-c1b8-11e5-9b17-fc5bc5871535.png)
![2016-01-23_09 55 13](https://cloud.githubusercontent.com/assets/12008758/12530802/76d670a4-c1b8-11e5-9dc9-a73853cb5e2e.png)
![2016-01-23_09 55 23](https://cloud.githubusercontent.com/assets/12008758/12530803/7866426e-c1b8-11e5-88f2-96a03caaab2c.png)
![2016-01-23_09 55 39](https://cloud.githubusercontent.com/assets/12008758/12530804/7a161652-c1b8-11e5-957e-971c0ca3f80b.png)
![2016-01-23_09 55 49](https://cloud.githubusercontent.com/assets/12008758/12530805/7bc5632c-c1b8-11e5-859c-2156e29643ce.png)

Log:
http://paste.ee/p/XLgOj

**Comment by Theotherguy1223** [comment]
I accidentally closed Minecraft before uploading the log this time, so I hope that the saved log is enough information

**Comment by peterix** [comment]
Basically, this makes no sense to me. And this also happens without Optifine?

There's nothing in MultiMC - that I am aware of - that could affect the running Java process this way.

The only option here is to find when this started happening. I am planning to upload all the previous versions of MultiMC anyway, so this can be tested once those are available. I'll just upload the development versions too.

**Comment by Theotherguy1223** [comment]
Here is a clean Version:
Setup:
![7ad98d0396](https://cloud.githubusercontent.com/assets/12008758/12530974/9ca35c7a-c1bd-11e5-85ca-7f051e11d38a.png)
![4e805f9d6a](https://cloud.githubusercontent.com/assets/12008758/12530976/9ca41354-c1bd-11e5-86b4-1d2834df8dd3.png)
![d6c5805ada](https://cloud.githubusercontent.com/assets/12008758/12530975/9ca3db1e-c1bd-11e5-8c2b-d556ae37a9f9.png)
![15c33a4391](https://cloud.githubusercontent.com/assets/12008758/12530981/d8554b98-c1bd-11e5-8608-fa783296cc33.png)

Screenshots:
![2016-01-23_10 37 31](https://cloud.githubusercontent.com/assets/12008758/12530999/08ea1e96-c1be-11e5-8f25-0902f475a31c.png)
![2016-01-23_10 37 39](https://cloud.githubusercontent.com/assets/12008758/12530998/08e96b04-c1be-11e5-9448-6a19271ed2e8.png)
![2016-01-23_10 38 11](https://cloud.githubusercontent.com/assets/12008758/12530997/08e9665e-c1be-11e5-9ef1-d87876647666.png)
![2016-01-23_10 38 42](https://cloud.githubusercontent.com/assets/12008758/12530996/08e870e6-c1be-11e5-976a-55eed99fb0f7.png)

Log:
http://paste.ee/p/7eJvm

It seems to load even slower without Optifine, and my FPS never seems to get above 10 without Optifine, but on the normal launcher, my fps is always at least 30 on a clean install of 1.8.9

**Comment by peterix** [comment]
Still makes no sense...

Let's try the same java as the mojang launcher uses:
http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html#jre-8u25-oth-JPR

Download the tar.gz version instead of the installer. Extract it somewhere - you'll need some sort of archiver utility like 7zip. Set it up in MultiMC using the browse button (...) and selecting the javaw.exe inside.

**Comment by Theotherguy1223** [comment]
Before I do that, I tried with the argument and memory in the previous step: 
Setup:
![a9b73cebd8](https://cloud.githubusercontent.com/assets/12008758/12531045/5367e29a-c1bf-11e5-8c2d-1000daefa78e.png)
![96f657da9a](https://cloud.githubusercontent.com/assets/12008758/12531044/5365fc3c-c1bf-11e5-86f5-d1e94c6e9c02.png)

Screenshots:
![2016-01-23_10 49 27](https://cloud.githubusercontent.com/assets/12008758/12531049/611f0c1a-c1bf-11e5-87b0-c35107176e0c.png)
![2016-01-23_10 47 00](https://cloud.githubusercontent.com/assets/12008758/12531051/61245e86-c1bf-11e5-8bf5-dc4640aa6c6b.png)
![2016-01-23_10 48 18](https://cloud.githubusercontent.com/assets/12008758/12531052/6126736a-c1bf-11e5-9bb7-60b20ec398a2.png)
![2016-01-23_10 49 24](https://cloud.githubusercontent.com/assets/12008758/12531050/6123ec76-c1bf-11e5-9a4f-fbf04a9853c3.png)

Log:
http://paste.ee/p/xLeRY

The game still ran slow, and kept getting huge spikes of lag, but my fps was better than ever, 40-50+ with no Optifine

**Comment by peterix** [comment]
The slow chunk loading and lag is... game processing - CPU, not graphics. It looks like it is throttled somehow.

**Comment by Theotherguy1223** [comment]
Which version should I try the new Java on? does it matter?

**Comment by peterix** [comment]
Let's keep it simple and say vanilla 1.8.9.

**Comment by Theotherguy1223** [comment]
ok, I'll do that without the Java arguments then

**Comment by Theotherguy1223** [comment]
I'm trying to launch it with the new Java, but I just keep getting this message:
![50d0588dc7](https://cloud.githubusercontent.com/assets/12008758/12531177/f30e9f58-c1c1-11e5-9308-5c5e8b90c592.png)
![3ff51ebd07](https://cloud.githubusercontent.com/assets/12008758/12531181/0d3dfa7c-c1c2-11e5-8519-8f2df5fc276f.png)

**Comment by peterix** [comment]
Sounds like you got the 32bit version. Grab the one with x64 in the name if you haven't.

**Comment by Theotherguy1223** [comment]
Setup:
![0b16f2a7ba](https://cloud.githubusercontent.com/assets/12008758/12531228/1775b60a-c1c3-11e5-867e-3a291b2a03c8.png)
![0b3c9ea9ae](https://cloud.githubusercontent.com/assets/12008758/12531227/17754a12-c1c3-11e5-9dc5-5f42e62f27fc.png)

Screenshots:
![2016-01-23_11 15 52](https://cloud.githubusercontent.com/assets/12008758/12531233/24751544-c1c3-11e5-9e53-15b24a8ecc41.png)
![2016-01-23_11 17 23](https://cloud.githubusercontent.com/assets/12008758/12531231/247443f8-c1c3-11e5-9fed-a94bd078223c.png)
![2016-01-23_11 16 49](https://cloud.githubusercontent.com/assets/12008758/12531230/2473ab28-c1c3-11e5-971b-b947ad3be42b.png)
![2016-01-23_11 16 58](https://cloud.githubusercontent.com/assets/12008758/12531232/247476c0-c1c3-11e5-8d64-a37c0aa6ff0e.png)

Log:
http://paste.ee/p/6kj87

The world seems to be loading a bit better, and faster, but still not as well or as fast as vanilla on the default Launcher, but almost as well.

Also, after hitting "quit game" on the main menu of the game, MultiMC crashes 3/3 times 1 Hardcrash, and 2 "MultiMC has encountered a problem and needs to close"

**Comment by peterix** [comment]
So.

This should work:
* `MultiMC.exe` renamed to `Minecraft.exe`
* Using java `1.8.0_25`.
* Using min/max memory both set to 4GB (I see you have never done that. try it. it's better, it will never have to resize the memory pool and giving Minecraft more than 4GB is really not required. It's enough even for the largest modpacks.)
* Using the java args: `-Xmn2G -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=60 -XX:-UseAdaptiveSizePolicy`

Does closing it using the X button make a difference? It really *shouldn't* crash. Can you upload the MultiMC-0.log file right after such a crash?

**Comment by peterix** [comment]
The world should load almost instantly in 1.8+...

**Comment by Theotherguy1223** [comment]
Setup:
![3a82c5e7e5](https://cloud.githubusercontent.com/assets/12008758/12531398/a05b0fd4-c1c7-11e5-9f41-247eced2e211.png)
![80c2185bb3](https://cloud.githubusercontent.com/assets/12008758/12531399/a05e02de-c1c7-11e5-9e8d-9e18030dc467.png)

Screenshots:
![2016-01-23_11 47 04](https://cloud.githubusercontent.com/assets/12008758/12531403/b296e7ea-c1c7-11e5-94e8-0a7877098119.png)
![2016-01-23_11 49 16](https://cloud.githubusercontent.com/assets/12008758/12531405/b29e4846-c1c7-11e5-9455-9d3223c8adfe.png)
![2016-01-23_11 49 27](https://cloud.githubusercontent.com/assets/12008758/12531406/b29eb1dc-c1c7-11e5-94ea-4ced001354d7.png)
![2016-01-23_11 49 38](https://cloud.githubusercontent.com/assets/12008758/12531404/b29d781c-c1c7-11e5-9594-76f312df196a.png)

Log:
http://paste.ee/p/Cur3X

At first, only the chunk I was standing in loaded, and every other chunk loaded slower than ever before, but after about a minute or so, the chunk loading was fine.

Also, MultiMC not crashing anymore.

**Comment by peterix** [comment]
MultiMC should have no effect on Minecraft chunk loading. For all intents and purposes, it's a separate process...

The chunk 'loading' is taking the already loaded chunk and sending it to the graphics memory. So something is going on in there. Can't really tell what and I'm not familiar enough with the AMD APUs.

Maybe check if it's actually running at full power?
http://support.amd.com/en-us/kb-articles/Pages/CPUAPUnotrunningatfullspeed.aspx

**Comment by peterix** [comment]
Other than that, I don't know...

I'll check the code for what could possibly cause a crash after java exits.

**Comment by Theotherguy1223** [comment]
I'm not sure how this worked, but I backed up my instances, re-installed MultiMC, changed all the java version paths back to default javaw.exe and the memory back to 1g min, 4 gigs max, and everything seems to be fixed now, I am still having the "nothing loads for a few seconds after I start" issue, but otherwise, the game runs fine now.

**Comment by peterix** [comment]
Alright...

I'll file this along with all the other mystery issues :)

Some of the suggestions here will go into the next MultiMC version though.
