### ISSUE TITLE
Cannot connect via lan since updates.

### ISSUE THREAD

**Issue by grydian** [MultiMC/MultiMC5#1428]
This was working back in 4.7 and since the latest updates I cannot connect via lan.  One computer can see it and it times out the other can't see it at all when before it would show up perfectly in multiplayer menu with no effort.  Let me know if you need logs or something.

**Comment by peterix** [comment]
The game generally chooses the network interface to bind to at random. If you are using more than one network interface (for example running virtual machines on an internal network), this can happen.

Is this the case?

**Comment by grydian** [comment]
Sorry didn't get a notification about the response...  I use file sharing and have several windows 7 pcs hooked up to the router.  I also have a synology disk server but there are no virtual machines as far as I know.  Does general file sharing create virtual machines?

**Comment by peterix** [comment]
No, it generally doesn't.

Let's see what is Minecraft actually doing.

Start Minecraft and a LAN server. Then [check what local address and port it uses](http://www.howtogeek.com/howto/28609/how-can-i-tell-what-is-listening-on-a-tcpip-port-in-windows/). You should be able to connect to that directly from the other machines. But you shoud also now know what network address it is listening on.

Check the list of network interfaces:
* Run `cmd.exe`.
    * In it, run: `ipconfig -a`.
    * Or alternatively: `ipconfig -a 1> C:\interfaces.txt 2>&1` and then look at `C:\interfaces.txt`

Is minecraft listening on the same network as the rest of the minecraft instances are using for discovery?

**Comment by peterix** [comment]
The next level of this would be capturing network traffic with a tool like `wireshark`, but I think just checking what IPs, ports and networks are involved should give you a good enough idea.

**Comment by peterix** [comment]
^^ Fixed the `ipconfig` command a bit :)

**Comment by grydian** [comment]
I used to be a webhost tech support.  So IPs are no problem for me.  I did try to manually connect to the IP and port number.  It would time out.  I tried hosting with both machines and using the IPs to try to direct connect even though it was not auto detected as it normally does.

**Comment by grydian** [comment]
I put the file you had me make in a pastebin.  All the computers trying to play minecraft are on the same shared network and have no problems seeing each other files.  Here is a pasetbin.com link of what you asked for.   http://pastebin.com/qDtkhhSH   Thats file you had me make.  fyi people need to launch cmd in administrator mode for files to be created.

**Comment by peterix** [comment]
So, a perfectly normal local LAN. Except some things do not see each other?

Check your firewall rules. Give the home router a restart.

**Comment by Chomper32** [comment]
Try going to the PC you want the world to be hosted from and doing this:


Click the Start button, select Run.

Type CMD and press Enter.

A Command prompt window will open. Type ipconfig and press Enter.

Several lines of information will be displayed. The IP address looks like "149.72.61.234" - yours will probably have different numbers near the end.

Then take that IP address and type it into your other computer. However, at the end of it, put a colon (:) and type in the number that Minecraft says when you open it to lan (EX: Lan world hosted on 56352). You would got to the other computer and (just using the examples I use, you would use your own) type in: 149.72.61.234:56352

That would be the direct connect ip and even though it isn't showing up you should be able to connect.

**Comment by grydian** [comment]
I did that before I reported the bug.  I cannot direct connect even when I manually use the IP address and the newly created port numbers.

**Comment by grydian** [comment]
I also power cycled the router before I reported the bug as well.  Also nothing in my LAN is having problems.  I have a disk server and all computers can see it and share files with each other.

**Comment by Chomper32** [comment]
Ok, sorry

**Comment by grydian** [comment]
No worries just eager to be playing with my son again.

**Comment by QuImUfu** [comment]
Try disabling the windows firewall completely. 
It often behaves random and blocks things it should not, even if everything is configured properly.
(Or you could just start a minecraft-server on one of you computers.)

**Comment by Chomper32** [comment]
I mean, if you wanted you could make a worldwide server and just not give anyone the ip. That would make it so you could also still play. A video on how to do this is here: http://youtu.be/volejWbTIKY

**Comment by peterix** [comment]
Assuming this is no longer relevant.
