### ISSUE TITLE
MutiMC won't open with update MulitMC 5 with OSX 10.7.5

### ISSUE THREAD

**Issue by bgreenlaw** [MultiMC/MultiMC5#1429]
I just installed MultiMC 5 update and now it won't open, I gives me a message saying that the application quit unexpectedly each time i try to open it. I have tried reinstalling everything but it still won't open. I have a macbook from early 2008 with 5GB ram and OSX Lion 10.7.5. Before installing this update MultiMC worked fine with no problems. Please help,

thank, BlakeG
![screen shot 2016-01-24 at 11 00 05 am](https://cloud.githubusercontent.com/assets/16865850/12537306/a818e954-c289-11e5-89eb-b956b96bf89a.png)

**Comment by wlhlm** [comment]
See #1410. Why use such an old operating system. 10.7 has been unsupported for _years_.

**Comment by bgreenlaw** [comment]
But the new update says its for 10.7 +

**Comment by bgreenlaw** [comment]
I fixed it

**Comment by bgreenlaw** [comment]
I went through my downloads and pulled out the old download file.
