### ISSUE TITLE
Crashing Issue with MultiMC

### ISSUE THREAD

**Issue by FIGBERTMC** [MultiMC/MultiMC5#1430]
Whenever I play on Hypixel, or am to active (e.g, excessive jumping, swinging my fists a lot) on a server, my MultiMC/Minecraft Crashes. I have uninstalled and reinstalled, but nothing changes. The error says that it could not write a core dump, and that by default mini-dumps are not enabled on a windows machine. I am a youtuber, and this is very troublesome. It has also happened a multitude of times on singleplayer, but not as much. I have looked through my settings and cannot find how to enable mini-dumps. Does anyone know how to fix it? HALP!

**Comment by peterix** [comment]
Crashes, especially completely weird random crashes like  that could be a sign of a hardware problem. Without any details, it's hard to say what's happening.
