### ISSUE TITLE
HOW TO ENABLE MODS

### ISSUE THREAD

**Issue by kingstarlord1st** [MultiMC/MultiMC5#1431]
hello

i need help. hello i am trying to make a modpack for  the public but for some reason it is saying when i got to the mods folder that most if not all mods were disabled.

pls help

i need this quick pls

**Comment by peterix** [comment]
MultiMC can enable/disable mods. This is done with checkboxes next to the mods in the mod lists (see loader mods page in edit instance, for example).

Disabling a mod pretty much just appends '.disabled' to the filenames, so you can also rename the files back on a file manager.

Other than that, idk.

**Comment by peterix** [comment]
Assuming fixed.
