### ISSUE TITLE
MultiMC5 wont start a unedited vanilla instance (1.8.9)

### ISSUE THREAD

**Issue by eatyba12** [MultiMC/MultiMC5#1432]
So I downloaded MultiMC today and set it up with the help of some videos (they were for the correct OS). But when I selected to run my new instance I got this log. How can I fix this?
[09HlC.txt](https://github.com/MultiMC/MultiMC5/files/102750/09HlC.txt)

**Comment by QuImUfu** [comment]
Does minecraft work with the normal launcher?
what GPU?
seems to be an Driver problem.

**Comment by peterix** [comment]
I am assuming this is with intel integrated graphics.

Rename MultiMC.exe to Minecraft.exe. Test it.

Try using older java - namely 1.8.0_25. You can get it here:
http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html#jre-8u25-oth-JPR

Download the .tar.gz version appropriate for your computer - in your case Windows x64. Extract it somewhere. Set MultiMC to use the `javaw.exe` inside that as the java version.

**Comment by eatyba12** [comment]
Yes Minecraft works, when I rename MultiMC.exe as Minecraft.exe it still
dosent work heres a new log http://paste.ee/p/olSlO. And Ill try the Java
one in a bit.

**Comment by peterix** [comment]
Strange log...

<PREFERREDLANGUAGE> all over the place. I wonder where that's coming from

**Comment by eatyba12** [comment]
Tried using Java 1.8.0_25 and here is the log for that
http://paste.ee/p/38Ji3

**Comment by eatyba12** [comment]
GPU is Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz (4 CPUs), ~2.3GHz

**Comment by peterix** [comment]
You are still suing 1.8.0_71

**Comment by peterix** [comment]
Assuming fixed. You need to use at most 1.8.0_55. The driver and hardware is according to Intel no longer supported. I have a workaround in the works, but until then, you'll need to use old Java for Minecraft.

See:
https://github.com/LWJGL/lwjgl/issues/119#issuecomment-173983180
https://software.intel.com/en-us/forums/graphics-driver-bug-reporting/topic/607695

The situation sucks. You would be better off with Windows 8.1 or 7. Or even Linux at this point. Older Intel IGPUs are a trap on Windows 10!
