### ISSUE TITLE
HELP Exception in thread "AE2 VersionChecker" AL lib: (EE) alc_cleanup: 1 device not closed Process exited with code -1.

### ISSUE THREAD

**Issue by kingstarlord1st** [MultiMC/MultiMC5#1434]
hello 

i have trouble with my muiltimc.
 when i try to see if my mod pack work it always show Exception in thread "AE2 VersionChecker" AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.

I DONT KNOW WHAT To DO PLS HELP I REALLY WANT TO RELEASE THIS PACK TO TECHNIC AND MAKE IT INTO A SERIES.

also here is a link to my paste pls CAN ANYONE FIGURE OUT WAT IS THE PROBLEM. https://paste.ee/p/qvzg3

THANK YOU FOR SEEING MY REQUSET I WOULD REALLY LOVE IT IF I GET A REPLY IN THE FIRST 24 HOURS THANK YOU.

**Comment by peterix** [comment]
Looks like you have one corrupted file:
14167934041_JurassiCraft-Mod-1.7.10 (1).jar

And you should remove powersuitaddons-1.7.10-901.jar - it's been merked into the main powersuits mod back in september.

**Comment by kingstarlord1st** [comment]
what do u mean

**Comment by kingstarlord1st** [comment]
DUDE WHAT DO YOU MEAN CORRUPTED FILE
