### ISSUE TITLE
i dont understand what to do with corrupted file

### ISSUE THREAD

**Issue by kingstarlord1st** [MultiMC/MultiMC5#1435]
hello

i juts wnat to know how to fix corrupted files and how to fix them so i can get it up and running

here a link to my previous issuse pls help i dont know what to do with the corrupted file.
https://github.com/MultiMC/MultiMC5/issues/1434#issuecomment-174837256

**Comment by peterix** [comment]
Just delete it and download a fresh copy.

**Comment by kingstarlord1st** [comment]
dude i dont need need to it workd

**Comment by kingstarlord1st** [comment]
HORAAY
