### ISSUE TITLE
Separate modpack import from 'new instance'

### ISSUE THREAD

**Issue by K4N0** [MultiMC/MultiMC5#1436]
I  was wondering how hard it would be to support a modpack launch button. 
I was thinking of a button that a user could select. Then paste the link to the instance location and it would auto create the instance with the modpack name and logo. I understand it is very simple currently to make an instance, but some users are so lazy that they just don't want to deal with such things.

**Comment by peterix** [comment]
This is there. Click new instance and instead of selecting a vanilla version, select paste in the pack link.

You mean like splitting this from the 'new instance' dialog entirely and turning it into its own separate thing?

**Comment by Badcholo** [comment]
Yes, a separate thing. It would make things easier for users whose only purpose is to launch modpacks. If they wish later on, they can see the full potential of the program.

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Packs -> Import)](https://workflowy.com/s/2EyDMcp7CU)

**Comment by peterix** [comment]
I think that now it is better - you have a whole dialog with separate pages for each.

I consider this done.
