### ISSUE TITLE
Permanent Settings

### ISSUE THREAD

**Issue by K4N0** [MultiMC/MultiMC5#1437]
I would like to suggest a way to make your minecraft video, optifine, servers.dat and personal settings permanent for all instances of that version of the game. That way you can right click on the instance and "set personal settings" to that instance. That way you have a permanent way to save your settings for all servers. Also Mini maps are always lost since they are saved in the client config folder.

**Comment by peterix** [comment]
Similar things have been suggested before, but it was by using symlinks to keep things synchronized all the time. Sadly, symlinks require admin access ot registry hacks on windows...

So, I like this approach more.

**Comment by peterix** [comment]
For now, you can do something similar:
* Create an instance.
* Run it.
* Set it up the way you like it.
* Instead of creating more instances from scratch, copy this one.

That won't allow you to freely copy-paste and apply settings, but it's a good workaround.

**Comment by Badcholo** [comment]
I understand. From a modpack user point of view. I was hoping to make things easier for users who will be using this to launch modpacks. In case i need to update the modpack, they wouldn't have to re-do their settings again. I understand there is no updating modpacks yet, so when they re-install the instance to update the modpack, i didnt' want to make them have to re-do all their settings or copy files and such.

**Comment by peterix** [comment]
Moved to [workflowy (Ideas -> Instance templates and default personal settings)](https://workflowy.com/s/2EyDMcp7CU).

**Comment by peterix** [comment]
This is really an extension of #413
