### ISSUE TITLE
Update problem (not latin path)

### ISSUE THREAD

**Issue by efimov90** [MultiMC/MultiMC5#1438]
![bug](https://cloud.githubusercontent.com/assets/1447790/12605471/61ba9b70-c4d6-11e5-9828-ce42d6a8d8f7.PNG)

When i was try to update by integrated updater i get this error. May be it is a problem with not latin codepage. Original username is "Сергей".

Logs:
[MultiMC.zip](https://github.com/MultiMC/MultiMC5/files/106134/MultiMC.zip)

**Comment by peterix** [comment]
If you are updating from 0.4.7, this is a known issue and you'll have to update manually. The updater there couldn't handle paths that wouldn't translate to the default system latin codepage.

Updating from say 0.4.8 to 0.4.10 should be fine. The old updater is no longer used.

**Comment by peterix** [comment]
Yeah. this is 0.4.7. Just grab latest version on the website. and move your data over.

If you don't feel like doing this, you can always move MultiMC straight into a drive root folder and it should update just fine.

**Comment by efimov90** [comment]
No this is bug on 0.4.8

-----Исходное сообщение-----
От: "Petr Mrázek" <notifications@github.com>
Отправлено: ‎27.‎01.‎2016 9:34
Кому: "MultiMC/MultiMC5" <MultiMC5@noreply.github.com>
Копия: "efimov90" <efimov90@gmail.com>
Тема: Re: [MultiMC5] Update problem (not latin path) (#1438)

If you are updating from 0.4.7, this is a known issue and you'll have to update manually. The updater there couldn't handle paths that wouldn't translate to the default system latin codepage.
Updating from say 0.4.8 to 0.4.10 should be fine. The old updater is no longer used.

**Comment by peterix** [comment]
You are running 0.4.7, the updater in that version can't handle unicode paths. I can't fix it retroactively without running that same updater... Even if I classify this as a bug, there's nothing I can do about it.

**Comment by efimov90** [comment]
Oh.. I see, may be i want to update to 0.4.8, but not to do this because of this problem.
