### ISSUE TITLE
WHAT MOD IS AT FAULT

### ISSUE THREAD

**Issue by kingstarlord1st** [MultiMC/MultiMC5#1439]
HELLO,

i have made a modpack PurelyAnarchy on the tehcnic laucher i want to know what is at fault here. i want to know what mod keeps crshing me PLS HELP.

HERE IS THE CRASH REPORT. https://paste.ee/p/AtgDQ
 PLS CAN I GET A REPONSE WITHING 24 HOURS OF THIS POST PLS HELP

**Comment by dmodoomsirius** [comment]
cpw.mods.fml.common.LoaderException: java.lang.OutOfMemoryError: Java heap space 

you ran out of memory.

**Comment by kingstarlord1st** [comment]
how to fix that

**Comment by kingstarlord1st** [comment]
DUDE HELP HOW TO FIX THE MEMORY THING

**Comment by peterix** [comment]
In the settings, increase java memory:
https://github.com/MultiMC/MultiMC5/wiki/Java-settings
https://github.com/MultiMC/MultiMC5/wiki/Increasing-Java%27s-memory-allocation

The amount depends on what your system has available and what java (32bit or 64bit) you use.

**Comment by peterix** [comment]
If you can afford to give Minecraft 4GB of RAM, you can use these settings:
https://workflowy.com/s/z2H77Wc8rH

It's a good set of defaults :)

**Comment by kingstarlord1st** [comment]
i only have 4gb

**Comment by peterix** [comment]
Then don't use those. Just give it min/max 2GB and you should be fine.

**Comment by peterix** [comment]
Assuming fixed.
