### ISSUE TITLE
MultiMC unable to launch on Windows 10 Pro 64-bit Insider Preview build 14251

### ISSUE THREAD

**Issue by scalda** [MultiMC/MultiMC5#1440]
Hi all,
I have just updated windows 10 to the latest build on the fast ring and i no longer can run multimc.

this it the error i get:@ the application was unable to start correctly (0xc0000142).

any help would be great thanks

scalda

**Comment by P3t3rU5** [comment]
@scalda got that error as well, it seems it broke on microsoft part, not multimc.

I'd suggest rolling back since even some store apps are breaking as well.

**Comment by scalda** [comment]
Thankyou I'm rolling back now

**Comment by DreadWingKnight** [comment]
The OBS project is also seeing that error come up on the insider preview track for windows 10 updates.

Side-effect of running alpha versions of an OS.

**Comment by scalda** [comment]
That's is true, I have reported it to Microsoft so will help in the long run

**Comment by peterix** [comment]
Alright. I'm assuming no action is needed here.

**Comment by peterix** [comment]
If you can link the Microsoft bug report here, please do so.

**Comment by peterix** [comment]
Let's just keep this open until Microsoft fixes it...

**Comment by P3t3rU5** [comment]
The 14257 build of Windows 10 Insider Preview works again.

**Comment by peterix** [comment]
Good job Microsoft, I guess :)

It would be nicer to know what actually happened on their end, but I'm not going to investigate.
