### ISSUE TITLE
MultiMC unable to launch on Windows 10 Pro 64-bit Insider Preview build 14251

### ISSUE THREAD

**Issue by KamranMackey** [MultiMC/MultiMC5#1441]
Hi. MultiMC is unable to launch on the latest Windows Insider Preview build. It throws a `0xc0000142` error on launch. As far as I know, that error code means that the application is having trouble initializing the DLL files. Please see if you can fix this. Thanks!

**Comment by peterix** [comment]
Duplicate of #1440 

This is not a MultiMC issue, this is a Windows 10 issue. I'd advise reporting this to Microsoft and linking the report in #1440 - hopefully it is publicly visible and can actually be tracked.

**Comment by peterix** [comment]
I'm going to reuse the title for #1440
