### ISSUE TITLE
Minecraft error. RAM.

### ISSUE THREAD

**Issue by REUSSofficial** [MultiMC/MultiMC5#1446]
If i set Maximum memory allocation 2048 MB and Java Runtime Parameters -Xincgc -Xmx3072M. Minecraft: Could not reserve enough space for 2097152KB object heap
If i set Maximum memory allocation 1280 - 2048 MB
Minecraft: Could not reserve enough space for XXXXXXXKB object heap

If i set Maximum memory allocation 512 - 1152 MB
Minecraft: Exception in thread "Thread-18" AL lib: (EE) alc_cleanup: 1 device not closed
java.lang.OutOfMemoryError
Process exited with code -1.

plz hlp mi

**Comment by peterix** [comment]
Right. do not use that extra -Xmx parameter.
If you have the actual physical RAM for it, it sounds like you are using 32bit Java.

Please run the game and when it actually crashes, click the Upload button. Post the link you get here :)

**Comment by REUSSofficial** [comment]
http://paste.ee/p/knpUe

**Comment by peterix** [comment]
Right. That doesn't tell us much, except that it is using some default java path.

Go in the main MultiMC settings (screwdriver and monitor icon on the toolbar). Open up the Java tab and click auto-detect.

If there's a 64bit Java version on your system, it should find it and you should select it and use it.

If not, you'll have to install 64bit (x64) Java from:
http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

Then set it up in MultiMC.

If you actually have 32bit OS or hardware, then that obviously doesn't work, and the maximum you will be able to use is ~1500MB

**Comment by REUSSofficial** [comment]
Thank you. Actually my java was 32 bit. I don't know why the java website thought I have a 64 bit system

**Comment by peterix** [comment]
Because it wants to install itself into your browser, which is most likely 32bit.
