### ISSUE TITLE
doesnt open after instaling force

### ISSUE THREAD

**Issue by deKeetAruba** [MultiMC/MultiMC5#1447]
Hello,
I have installed 1.7.2 on multimc5. It runs well. But when i install Force with it, it will not open anymore. Please help. Dick.

**Comment by peterix** [comment]
Run it, once it comes up with the console window and the error in it, click the 'Upload' button. Post the link you get from that here.

**Comment by deKeetAruba** [comment]
http://paste.ee/p/rjeOG

**Comment by peterix** [comment]
You need to add this mod:
http://files.minecraftforge.net/LegacyJavaFixer/legacyjavafixer-1.0.jar

**Comment by peterix** [comment]
It should really be part of these 'broken' Forge releases, but that is something MultiMC is not set up to do automatically just yet...

**Comment by peterix** [comment]
Issue is that Java 8 changed the behavior for some basic data structures and Forge depended on it. The mod restores the behavior back to what Forge expects it to be.

**Comment by deKeetAruba** [comment]
thanks, its working now. finaly have Ironman mod running for the kids

**Comment by peterix** [comment]
Alright! :)
