### ISSUE TITLE
Now i can load chicken coremod 1.7.2 

### ISSUE THREAD

**Issue by deKeetAruba** [MultiMC/MultiMC5#1448]
Not running chicken coremod. link is this.

http://paste.ee/p/HHJI9

thanks Dick

**Comment by peterix** [comment]
Well, CCC is there, the world you are loading complains about NEI missing though...

So install a matching version of NEI for the CCC you have.

You can get both here:
http://chickenbones.net/Pages/links.html

**Comment by deKeetAruba** [comment]
Had that done, now it runs minecraft, but cant get into mod options. says:
test1
test2
disabled

and i cant open NEI

**Comment by deKeetAruba** [comment]
this is the link http://paste.ee/p/O4lTf

**Comment by peterix** [comment]
There are no mod options in 1.7.2. It was not fully implemented back then.

NEI not opening... I vaguely remember that being an issue in one of the very old versions - 1.4.6? Not in this one.

Try pressing `o` in game with the crafting screen open?

**Comment by deKeetAruba** [comment]
With NEI installed, when i hit E the game shuts down. I done it 3 times.
When i delete chickencore and NEI, then it works again.

When Xaero’s Minimap loading, the game doesnt even open.

**Comment by peterix** [comment]
More errors, more logs needed :)

Crash when NEI opens could mean it can't deal with some of the modded items. Try to disable the other mods one by one and see when it starts working.

As for the minimap, logs? :)

**Comment by deKeetAruba** [comment]
this is the log from loading minimap. with superherocore and iron man loaded ang KeepInventory.
http://paste.ee/p/QeOfo

**Comment by deKeetAruba** [comment]
this is the log from loading minimap. with superherocore and iron man loaded
http://paste.ee/p/xk51A

**Comment by deKeetAruba** [comment]
this is the log from loading only minimap.
http://paste.ee/p/oyl7q

all 3 chrashed

**Comment by peterix** [comment]
Hm. Right.

That mod is only for 1.7.10 and 1.8, not 1.7.2.

**Comment by deKeetAruba** [comment]
Thanks, but cant find that mod for 1.7.2  lol  

its is log from only running NEI. it chrashed when i hit E.
http://paste.ee/p/q9yV6

**Comment by peterix** [comment]
http://www.minecraftforum.net/forums/support/modded-client-support/2159897-solved-java-lang-nosuchmethoderror-net-minecraft?comment=6

**Comment by peterix** [comment]
You may have to use a different minimap mod then

**Comment by peterix** [comment]
Or use a different Minecraft release. 1.7.10 has been around for a lot longer and has more mods.

**Comment by deKeetAruba** [comment]
I will see if i can get ironman mod for 1.7.10 and then install 1.7.10 for it. thanks and i let you know if all works

**Comment by deKeetAruba** [comment]
hello, have all running on 1.7.10  thanks.

**Comment by peterix** [comment]
Alright :)
