### ISSUE TITLE
MultiMC title screen group issue

### ISSUE THREAD

**Issue by Trochu7** [MultiMC/MultiMC5#1450]
Hello everyone,

When I set the group of my instance, everytime I restart the multimc client it switch to the default group.

**Comment by peterix** [comment]
What is the MultiMC version?
What are the exact names and folder names of the group and instace?
What OS are you running this on?

**Comment by Trochu7** [comment]
MultiMC používám 0.4.7 a Windows 7 Home Premium 64 bit

Jde o to, že mám kupu instancí a rozdělil jsem si je do různých skupin a jedna z instancí se pokaždé když restartuju launcher vrátí zpět do defaultní skupiny.

**Comment by peterix** [comment]
Tohle by melo byt uz opraveno. Zkus 0.4.10
