### ISSUE TITLE
Build instructions for OSX are missing the 'make install' step

### ISSUE THREAD

**Issue by 1byte2bytes** [MultiMC/MultiMC5#1451]
My custom compiled version of MultiMC cannot detect any Java installs, but the one downloaded from the official website detects 5 Java installs. ([picture](https://i.gyazo.com/f91118cbb1559e638a7c32d91fa7f768.png)) The official launcher is on the left, the custom one on the right. The custom compiled version of MultiMC is built with no modifications to the code from the stable branch.

**Comment by peterix** [comment]
How do you run this custom build? Did you install it with `make install`?

**Comment by 1byte2bytes** [comment]
I just double click the .app after running `make`. The Mac instructions didn't mention `make install`, did I miss a step?

**Comment by peterix** [comment]
Odd... If you want to look, the full build logs are here:
http://ci.multimc.org/builders/osx64

**Comment by peterix** [comment]
Specifically, this step:
http://ci.multimc.org/builders/osx64/builds/693/steps/install/logs/stdio

The .app should have the two jars inside.

**Comment by peterix** [comment]
And you can set the install prefix during cmake configuration. For example:
`-DCMAKE_INSTALL_PREFIX:PATH=/Users/jan/buildslave/mmc2/osx64/build/out/install/`

**Comment by 1byte2bytes** [comment]
Hmmmm, the custom compiled version of MultiMC seems to be missing .jar and .dylib files inside the .app, despite those files being inside the build folder.

**Comment by 1byte2bytes** [comment]
Yeah, there is a *lot* missing for some reason. The build looked fine to me though. Everything went to 100% without any errors.

**Comment by peterix** [comment]
The build is not the same as the install... it should pack in a lot of the extra dependencies that are normally not found on the system.

**Comment by 1byte2bytes** [comment]
Perhaps that should be mentioned on the Mac portion of the [build page?](https://github.com/MultiMC/MultiMC5/blob/44db72ead568fe7ce22e1999aac02fd9aac9beea/BUILD.md)

**Comment by peterix** [comment]
Makes sense :)

**Comment by peterix** [comment]
Done.
