### ISSUE TITLE
Minecraft Crashing 

### ISSUE THREAD

**Issue by xenephos** [MultiMC/MultiMC5#1452]
This is after a fresh install of MultiMC AND after the newest Java update. I at first thought it was because of the mods, but it gives me the same error (the one shown below) with a fresh vanilla instance. I have been able to use MultiMC before, so this is a new error I'm getting.

> MultiMC version: 0.4.10-733Minecraft folder is:instances/1.81/minecraftJava path is:C:/Program Files (x86)/Java/jre1.8.0_71/bin/javaw.exeJava Arguments:[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -jar, C:/Games/MultiMC/jars/NewLaunch.jar]Minecraft process ID: 7876Using onesix launcher.Main Class:  net.minecraft.client.main.MainNative path:  C:/Games/MultiMC/instances/1.81/nativesTraits:  []Libraries:  C:/Games/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar  C:/Games/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar  C:/Games/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar  C:/Games/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar  C:/Games/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar  C:/Games/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar  C:/Games/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar  C:/Games/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar  C:/Games/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar  C:/Games/MultiMC/libraries/io/netty/netty-all/4.0.15.Final/netty-all-4.0.15.Final.jar  C:/Games/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar  C:/Games/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar  C:/Games/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar  C:/Games/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar  C:/Games/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar  C:/Games/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar  C:/Games/MultiMC/libraries/com/mojang/realms/1.6.1/realms-1.6.1.jar  C:/Games/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar  C:/Games/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar  C:/Games/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar  C:/Games/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar  C:/Games/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar  C:/Games/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar  C:/Games/MultiMC/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar  C:/Games/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar  C:/Games/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar  C:/Games/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar  C:/Games/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar  C:/Games/MultiMC/versions/1.8/1.8.jarParams:  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, C:/Games/MultiMC/instances/1.81/minecraft, --assetsDir, C:/Games/MultiMC/assets, --assetIndex, 1.8, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {}, --userType, mojang]Window size: 854 x 480Preparing native libraries...Extracting twitch-platform-6.5-natives-windows-32.jarExtracting twitch-external-platform-4.5-natives-windows-32.jarExtracting jinput-platform-2.0.5-natives-windows.jarExtracting lwjgl-platform-2.9.1-natives-windows.jar[14:27:51] [Client thread/INFO]: Setting user: <PROFILE NAME>[14:27:51] [Client thread/INFO]: (Session ID is token:<ACCESS TOKEN>:<PROFILE ID>)[14:27:55] [Client thread/INFO]: LWJGL Version: 2.9.1[14:27:56] [Client thread/ERROR]: Couldn't set pixel formatorg.lwjgl.LWJGLException: Pixel format not accelerated	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.1.jar:?]	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.1.jar:?]	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252) ~[lwjgl-2.9.1.jar:?]	at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.1.jar:?]	at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.1.jar:?]	at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.1.jar:?]	at bsu.am(SourceFile:510) [1.8.jar:?]	at bsu.aj(SourceFile:352) [1.8.jar:?]	at bsu.a(SourceFile:299) [1.8.jar:?]	at net.minecraft.client.main.Main.main(SourceFile:120) [1.8.jar:?]	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]---- Minecraft Crash Report ----// But it works on my machine.Time: 2/4/16 2:27 PMDescription: Initializing gameorg.lwjgl.LWJGLException: Pixel format not accelerated	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)	at org.lwjgl.opengl.Display.createWindow(Display.java:306)	at org.lwjgl.opengl.Display.create(Display.java:848)	at org.lwjgl.opengl.Display.create(Display.java:757)	at org.lwjgl.opengl.Display.create(Display.java:739)	at bsu.am(SourceFile:523)	at bsu.aj(SourceFile:352)	at bsu.a(SourceFile:299)	at net.minecraft.client.main.Main.main(SourceFile:120)	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)	at java.lang.reflect.Method.invoke(Unknown Source)	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)	at org.multimc.EntryPoint.listen(EntryPoint.java:170)	at org.multimc.EntryPoint.main(EntryPoint.java:54)A detailed walkthrough of the error, its code path and all known details is as follows:----------------------------------------------------------------------------------------- Head --Stacktrace:	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)	at org.lwjgl.opengl.Display.createWindow(Display.java:306)	at org.lwjgl.opengl.Display.create(Display.java:848)	at org.lwjgl.opengl.Display.create(Display.java:757)	at org.lwjgl.opengl.Display.create(Display.java:739)	at bsu.am(SourceFile:523)	at bsu.aj(SourceFile:352)-- Initialization --Details:Stacktrace:	at bsu.a(SourceFile:299)	at net.minecraft.client.main.Main.main(SourceFile:120)	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)	at java.lang.reflect.Method.invoke(Unknown Source)	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)	at org.multimc.EntryPoint.listen(EntryPoint.java:170)	at org.multimc.EntryPoint.main(EntryPoint.java:54)-- System Details --Details:	Minecraft Version: 1.8	Operating System: Windows 10 (x86) version 10.0	Java Version: 1.8.0_71, Oracle Corporation	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation	Memory: 465553072 bytes (443 MB) / 519110656 bytes (495 MB) up to 1037959168 bytes (989 MB)	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0	Launched Version: MultiMC5	LWJGL: 2.9.1	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.	GL Caps: 	Using VBOs: No	Is Modded: Probably not. Jar signature remains and client brand is untouched.	Type: Client (map_client.txt)	Resource Packs: []	Current Language: ~~ERROR~~ NullPointerException: null	Profiler Position: N/A (disabled)#@!@# Game crashed! Crash report saved to: #@!@# C:\Games\MultiMC\instances\1.81\minecraft\crash-reports\crash-2016-02-04_14.27.57-client.txtProcess exited with code -1.MultiMC: Log upload triggered at: 04 Feb 2016 14:28:07 -0600

**Comment by wlhlm** [comment]
Here's the culprit:

```
[Client thread/ERROR]: Couldn't set pixel formatorg.lwjgl.LWJGLException: Pixel format not accelerated 
```

Java fails to detect your graphics card. This most likely has been caused the Java update. Try downgrading.

See #1282, #1283

**Comment by peterix** [comment]
Duplicate
