### ISSUE TITLE
Whenever I load a world my game crashes. 

### ISSUE THREAD

**Issue by PurpleFox327** [MultiMC/MultiMC5#1454]
I'm always able to make a new world after I delete or remove the previous worlds but whenever I try to get back on the world my game crashes. All the mods seem to be loading fine also. 

Here's the logs from start to crash: 
http://paste.ee/p/YgJcP
(I couldn't paste it because it was to long)

**Comment by RX14** [comment]
It's an escaping error in your wailanbt config. 

In `names['91']='Jack o'Lantern'` you need to escape it like this `names['91']='Jack o\'Lantern'`.

**Comment by PurpleFox327** [comment]
@RX14 How would I go about doing this?

**Comment by RX14** [comment]
Anywhere where you have a `'` character in a string in your config file, replace it with `\'`.

The config file looks like it's written in javascript, you need to follow the escaping rules of that.

At the very minuimum replace the 1 line in my example and see if it still breaks.

**Comment by PurpleFox327** [comment]
@RX14 I meant how would I get to the config, I apologize. I'm not good at configuration/ect.

**Comment by peterix** [comment]
This is clearly not a MultiMC issue. Ask the mod author, or whoever put those configs together for assistance.

**Comment by RX14** [comment]
There is aparrently a version which fixes this in the link here: https://github.com/exzhawk/wailanbt/issues/21#issuecomment-63946241
