### ISSUE TITLE
MultiMC crashed with exit code 1 HELP

### ISSUE THREAD

**Issue by Chomper32** [MultiMC/MultiMC5#1455]
I'm trying to put together a custom modpack but it isn't working. However, yesterday I was able to create a world and run it, but today, when I tried to enter that world it crashed, whenever i try to make a new world it crashes as well. Please help.

Just FYI I am running on my home built windows 10 PC

A complete log of the crash is available here:
https://paste.ee/p/iFwci

**Comment by Loetkolben** [comment]
This is a (native) JVM crash, this means it's most likely not Minecraft's but Java's fault:
> The crash happened outside the Java Virtual Machine in native code.

To further help you we need the error report at
> An error report file with more information is saved as:
C:\Users\Brad Kelly\Downloads\mmc-stable-win32 (4)\MultiMC\instances\InsaneCraft\minecraft\hs_err_pid2860.log

**Comment by rabdag123** [comment]
I am experiencing the same issue if you could help fix this it would be great.

**Comment by peterix** [comment]
That's a crash in the graphics driver...

**Comment by rabdag123** [comment]
i got something like this also from the report http://paste.ee/p/cQIwh

**Comment by peterix** [comment]
@rabdag123 you have a completely different problem. Please open a separate issue.

**Comment by rabdag123** [comment]
ok

**Comment by rabdag123** [comment]
how do i open an issue

**Comment by peterix** [comment]
There's a new issue button on this page.

**Comment by Loetkolben** [comment]
@rabdag123 https://github.com/MultiMC/MultiMC5/issues/new

**Comment by Chomper32** [comment]
@peterix 

I'll add the log

**Comment by Chomper32** [comment]
Here is a pastebin or the log hs_err_pid

https://paste.ee/p/3Zmd4#

**Comment by peterix** [comment]
This really is a crash inside the graphics driver. There isn't much you can do besides bugging NVidia about it. The driver shouldn't crash.

As for workarounds:
* try removing optifine
* try renaming MultiMC.exe to Minecraft.exe - sometimes graphics drivers react to this...

**Comment by Chomper32** [comment]
@peterix 

The thing is, it worked yesterday, so I shouldn't have to rename it, should it?

**Comment by peterix** [comment]
If it worked yesterday and now it doesn't, something changed between yesterday and now.

Could be a driver update.
Could be that the graphics card began to overheat (check on the temps - there are tools for that. or you can just look at it)
Could be... anything.

The rename shouldn't affect anything, but sometimes does.

**Comment by Chomper32** [comment]
@peterix 
The only thing I've done since yesterday is upload a YouTube video and play vanilla Minecraft from MultiMC, which worked.

**Comment by peterix** [comment]
Nope. Which is why I'd suspect hardware, or software updates.

**Comment by Chomper32** [comment]
@peterix 

So what is your suggestion on what I should do?

**Comment by peterix** [comment]
Aside from the above, none.

**Comment by Chomper32** [comment]
So If it doesn't work (the things listed above) than that pa k is just broken?

**Comment by Chomper32** [comment]
It finally worked after removing optifine, Thanks Guys!
