### ISSUE TITLE
MultiMC Crash "Not Found Coremod data"

### ISSUE THREAD

**Issue by rabdag123** [MultiMC/MultiMC5#1456]
I am no expert at coding but I can understand a little bit. The report comes up with an error and a continual sequence of messages relating to coremods. http://paste.ee/p/cQIwh

**Comment by Chomper32** [comment]
What mods are you using?

**Comment by jikuja** [comment]
There is mod for MC 1.8. Go through your mod list and remove offending mod.

**Comment by rabdag123** [comment]
the ones i downloaded i thought to make sure that they were 1.7.10 but ill check again

**Comment by Chomper32** [comment]
You seem to be running 1.8.9 with 1.7.10 mods. Correct me if I'm wrong.

![image](https://cloud.githubusercontent.com/assets/17101739/12869609/8be6c382-ccf2-11e5-8549-26f14f835b9b.jpeg)

**Comment by jikuja** [comment]
Nope: 
`[16:17:14] [main/INFO] [FML/]: Forge Mod Loader version 7.99.36.1558 for Minecraft 1.7.10 loading`

**Comment by rabdag123** [comment]
the original one was 1.8.9 but I used the change version feature on the instance

**Comment by rabdag123** [comment]
so I thought that would help fix it

**Comment by Chomper32** [comment]
Maybe...
Try making a new 1.7.10 instance and adding the mods 1 by 1 and testing them so you know which one isn't working.

**Comment by rabdag123** [comment]
Jikuja was right I found 2 copied versions of the same mods but for 1.8

**Comment by Chomper32** [comment]
Ahhh, yea, that's not gonna work

**Comment by jikuja** [comment]
Or search log for strings containing "1.8" or read the log and find last loaded mod before the crash.

**Comment by rabdag123** [comment]
I don't know how they got there i'm going to try it again without them

**Comment by Chomper32** [comment]
You're gonna need to get those mods for 1.7.20 before they work

**Comment by rabdag123** [comment]
thanks you guys

**Comment by Chomper32** [comment]
No problem

**Comment by Chomper32** [comment]
Comment if it works

**Comment by rabdag123** [comment]
ok it takes a while

**Comment by Chomper32** [comment]
Ok, sounds good

**Comment by Chomper32** [comment]
You should also get Optifine for better speed

**Comment by Chomper32** [comment]
Just a suggestion

**Comment by rabdag123** [comment]
YAY it worked

**Comment by Chomper32** [comment]
Yippee, you can now close this post

**Comment by Chomper32** [comment]
Thx
