### ISSUE TITLE
My Pack Wont Launch I Need HELP!! PLZ!!!!

### ISSUE THREAD

**Issue by ZCrafter** [MultiMC/MultiMC5#1459]
I have no idea what to do, I keep getting "Process exited with code 1"

http://paste.ee/p/ZVGxx#

**Comment by wlhlm** [comment]
```
appliedenergistics2-rv0-beta-28
```
You are using an ancient version of AE2 which requires MC 1.7.2. Please update.

**Comment by ZCrafter** [comment]
I downloaded and installed the stable v10 and I still get the same error message.

**Comment by wlhlm** [comment]
I don't think it is the same error. "Process exited with code 1" just means that Minecraft crashed, but it doesn't indicate any specific error. Please paste the log again.

**Comment by ZCrafter** [comment]
http://paste.ee/p/sTYRh

**Comment by wlhlm** [comment]
There are many more mods in your list that require 1.7.2, in fact you even have mods for MC 1.6.4 in there. Unfortunately, this won't work as mods are generally only compatible with one version of Minecraft and you can't mix them. You either have to go through your modlist and update the mods to their latest version for MC 1.7.10, or update the modpack.

On Curse you can [filter mods by Minecraft version](http://www.curse.com/mc-mods/minecraft?filter-project-game-version=1.7.10&filter-project-sort=1).

Examples are:
```
twilightforest-1.7.2-2.1.0
QuarryPlus-1.6.4-1.5.5.3
Railcraft_1.7.2-9.0.0.0
...
```

There are many more incompatible mods in your modlist.

**Comment by ZCrafter** [comment]
thanks I went through and I think I updated everything and it still crashes

http://paste.ee/p/7Vew8

**Comment by ZCrafter** [comment]
I deleted the fast leaf decay but now it says it ended with code: -1

http://paste.ee/p/oeQXN

**Comment by peterix** [comment]
Well, it says it in the log. It ran out of memory.

**Comment by ZCrafter** [comment]
I increased my max memory to 3200 MB and it still stops at the same spot

http://paste.ee/p/0x1LQ

**Comment by Slikrick** [comment]
you do not have bdlib, which AE2stuff requires

**Comment by ZCrafter** [comment]
ok I added it and it still failed

http://paste.ee/p/8xbjD

**Comment by robbix1206** [comment]
"355. java.lang.OutOfMemoryError: Java heap space"
You have not enough RAM to register all the textures so the game crash.

**Comment by ZCrafter** [comment]
what can I do to increase my ram??

**Comment by peterix** [comment]
in the java settings. if you actually have enough RAM in your computer. if you don't, you'll have to reduce what minecraft tries to allocate instead. or add more memory to your system.

**Comment by ZCrafter** [comment]
All that is in the java setting is memory min/max permgen and java arguments, and this is on my laptop so I cant add more RAM so is there anything I can do to reduce my RAM usage.

**Comment by ZCrafter** [comment]
http://paste.ee/p/kvWfn

**Comment by Badcholo** [comment]
try optifine mod. Standard works pretty well without even configuring it. It helps increase fps, but i am unsure if it will help with your issue.

**Comment by peterix** [comment]
What happens if you remove fastcraft?

**Comment by ZCrafter** [comment]
I took out fastcraft and every time I launched it told me I needed something else so I added CoFH Core, EnderCore, iChunUtil, and Lunatrius and

http://paste.ee/p/Jv8pJ

**Comment by peterix** [comment]
[20:07:59] [Client thread/ERROR] [FML]: The mod MineFactoryReloaded (MineFactory Reloaded) requires mod versions [CoFHCore@[1.7.10R3.1.0,1.7.10R3.2.0)] to be available

Looks like you need a specific version of CoFH Core. From the log, it's not clear which one you have, so check that.

**Comment by ZCrafter** [comment]
It old me to add a couple of mods and update a few but then it told me to add mantle 1.7.10 .0.3.2 then it didn't even launch.

http://paste.ee/p/8CNL1

**Comment by ZCrafter** [comment]
http://paste.ee/p/wJrqc

**Comment by peterix** [comment]
http://www.curse.com/mc-mods/minecraft/224828-libsandstone

**Comment by ZCrafter** [comment]
I added it and...

http://paste.ee/p/5yhwB

**Comment by peterix** [comment]
```
[15:07:36] [main/ERROR] [FML]: Unable to read the jar file LibSandstone-1.0.0.jar - ignoring
```

There's something wrong with it. Probably not a `.jar` file.

**Comment by ZCrafter** [comment]
I added the mod and it shows its in the folder but when it crashes and I go to the folder its not there 

http://paste.ee/p/uz2By

**Comment by ZCrafter** [comment]
I need help, I'm so confused with this

http://paste.ee/p/sj3WY

**Comment by QuImUfu** [comment]
Created a Pack with the same mods (updated). 
It works.
Download:
[CopyForZCrafter.zip](https://dl.dropbox.com/s/xbqpy30y908w62l/CopyForZCrafter.zip?dl=0)
import via "new Instance".

**Comment by peterix** [comment]
Right... I'm just going to say that this is solved now. You got it on a silver platter :P
