### ISSUE TITLE
problem with my multimc (MAC)

### ISSUE THREAD

**Issue by megadog123** [MultiMC/MultiMC5#1460]
I've been trying to make an instance with my friends using 1.7.10 mods and I am 100% certain that the mods are updated because my friends are able to use the instance but I am the only one who cant. i have the pastebin and would like it if someone can help my issue. Thanks
http://paste.ee/p/7Fffd

**Comment by BoomBoomLHack** [comment]
`[21:06:07] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:488]: Caused by: java.lang.UnsupportedClassVersionError: cofh/asm/LoadingPlugin : Unsupported major.minor version 51.0`
Unsupported Java version.
Are you SURE that your Mac has Java 8 installed?

**Comment by megadog123** [comment]
I installed the latest java version but the problem might be that I didn't delete the older version of java before downloading Java 8.

**Comment by megadog123** [comment]
Also just to make sure, I deleted java and redownloaded it with the correct version but its still giving me the same problems.

**Comment by BoomBoomLHack** [comment]
1. Click this 
![6e7c725b031416307bfe1aca01308567](https://cloud.githubusercontent.com/assets/9440126/12877508/5dcf127e-cde2-11e5-8698-08d76519fa85.png) icon in MultiMC's home screen.
2. Click the Java tab on the left.
3. Click the Auto-Detect button on the Java Runtime section.
4. Press the Test button.
5. A dialog should pop up and said something like:
"Java version reported: 1.8.0_45"

**Comment by megadog123** [comment]
Yea I fixed the mod so the launcher pops up but when it gets to 7/7 the launcher just randomly closes and says: Process exited with code 255.

**Comment by megadog123** [comment]
heres the pastebin if you wanted it btw.
http://paste.ee/p/BZzSD

**Comment by megadog123** [comment]
nevermind it didnt work now and when I tried your steps and I clicked the one with a star multimc crashes

**Comment by peterix** [comment]
`Java Version: 1.6.0_65, Apple Inc.`

That's the ancient Apple java.

If you can, get the actual crash report from OSX.
