### ISSUE TITLE
Exit Code -1

### ISSUE THREAD

**Issue by PotatoWarriorMC** [MultiMC/MultiMC5#1461]
This happened to me on my last modpack so i changed to another modpack and the same thing happened it was working yesterday now it doesnt
[MjA4r.txt](https://github.com/MultiMC/MultiMC5/files/121796/MjA4r.txt)

**Comment by peterix** [comment]
http://forum.feed-the-beast.com/threads/crash-upon-loading-world-ticking-memory-connection.118915/

**Comment by peterix** [comment]
World corruption... is bad. Basically, you'll have to strip logi pipes from the world or remove its files somehow if they are separate from the region files.
