### ISSUE TITLE
MultiServers

### ISSUE THREAD

**Issue by tipapro** [MultiMC/MultiMC5#1462]
Adding interaction with custom servers, binding them to the modpacks. Make MultiServers(as MultiMinecraft).I play with friends in a variety of modpacks and keep the server. I would like that all my servers were in the one program(as modpacks)

**Comment by peterix** [comment]
This has been suggested many times... So far, this is out of reach.

MultiMC must first gain the ability to run and track more than one running thing at a time. This will allow running multiple instances with different logins.

Then it needs a way to mark mods/resources as 'server side', 'client side' or 'both sides', to allow creating server packs.

Running local servers comes after that - mostly for testing packs.

After that, managing remote servers will require quite a bit more work.

**Comment by peterix** [comment]
I'm planning to work on the first step of this for the next version, because if done right, it will also fix a lot of issues people are having with bad display drivers on Windows.

**Comment by peterix** [comment]
You can look at the complete TODO/ideas list here: 
https://workflowy.com/s/2EyDMcp7CU

Everything related to server support is tagged with #launch-agent

**Comment by peterix** [comment]
How do you manage those servers right now? Are they manageable through some sort of API? Maybe SSH? Can you run more programs next to those servers?

**Comment by cqjjjzr** [comment]
NO api avaliable
but you can try to write a version of mcserver(like the bukkit or cauldron)

**Comment by peterix** [comment]
I'm gonna say no and move on.

**Comment by cqjjjzr** [comment]
Yea it's unnecessary to build a project just like MultiCraft..
