### ISSUE TITLE
keeps crashing., don't know why. Help?

### ISSUE THREAD

**Issue by Evan-mckay123** [MultiMC/MultiMC5#1469]
here's the crash file

http://paste.ee/p/g7wnY

**Comment by peterix** [comment]
The mods you have there add too many monsters to the game and it ran out of numbers to track them.

http://www.minecraftforum.net/forums/support/modded-client-support/2300150-no-more-entity-indices-left

You'll need to remove some mods.

Google for the error messages first, please.
