### ISSUE TITLE
MultiMC Modpack Crash

### ISSUE THREAD

**Issue by TheNetworker15289** [MultiMC/MultiMC5#1470]
A MultiMC Modpack Crash, Need Help

http://paste.ee/p/u85Dh

**Comment by peterix** [comment]
You have some mods for different versions of Minecraft than 1.7.10:

CodeChickenCore-**1.8**-1.0.5.34-universal
AbyssalCraft-**1.8.9**-1.9.0-pre-3

Check the rest too... if it continues crashing.
