### ISSUE TITLE
Keeps crashing after few seconds 

### ISSUE THREAD

**Issue by deKeetAruba** [MultiMC/MultiMC5#1471]
http://paste.ee/p/3oYxa

I can play no more, is this also a java bug?
And is there a fix for?

Thanks Dick

**Comment by peterix** [comment]
Crash in intel graphics driver... if you also have a dedicated GPU, you can try renaming `MultiMC.exe` to `Minecraft.exe`.

Or even if you don't have a dedicated GPU. It just can't hurt anything.

**Comment by peterix** [comment]
As for graphics drivers:
https://help.mojang.com/customer/portal/articles/928493-error-bad-video-card-driver

**Comment by peterix** [comment]
Do not rely on whatever Windows decided to install automatically.
