### ISSUE TITLE
Java errors

### ISSUE THREAD

**Issue by Goswami1** [MultiMC/MultiMC5#1472]
I am running into Java errors every time I try to launch an instance.

When I test after putting in the correct path to my Java.exe it shows this error:
"The specified java binary didn't work with the arguments you provided"

When I run the instance I get this error:
"Java path is:
C:/Program Files (x86)/Java/jre1.8.0_73/bin/java.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2128m, -Xmx3128m, -Duser.language=en, -jar, C:/Users/*/Desktop/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 5096

Error occurred during initialization of VM
Could not reserve enough space for 3203072KB object heap
Process exited with code 1."

I've ran it by auto detect and unchecking the ram allocated amount but then it will launch and start installing then crash. When changing the amount of ram it always has the same errors. I have tested this via my desktop and laptop, I have up to date Java and the correct minecraft and forge versions. 

Any advice would be appreciated. Thank you.

**Comment by QuImUfu** [comment]
As far as i can tell, you are trying to allocate more than 3GB Ram to 32 bit Java. 
Install 64 Bit java (if you already have 64bit Java  installed choose it in the  settings) or give Java (minecraft) less memory. 
(1.5GB is usually enought).

**Comment by Goswami1** [comment]
That fixed the problem thank you!
