### ISSUE TITLE
Fatal Error Issue - Please Help :)

### ISSUE THREAD

**Issue by Mutleymuffin** [MultiMC/MultiMC5#1476]
# Fatal Error!

Hi whenever i try to join a server, I get a message come up that says a fatal error has occurred.

Can anyone help me, I have tried reinstalling MultiMC and the modpack twice but to no prevail.

If you need like console log things you will have to explain where I find them :)

This is a thing http://paste.ee/p/svm9W

**Comment by peterix** [comment]
Console window, Upload button.

![image](https://cloud.githubusercontent.com/assets/203326/13046673/751d07c6-d3da-11e5-82ce-9e4f94ae05bd.png)

Normally, it is not shown while playing, but you can open it from the tray area - it should have the same icon as the instance.

**Comment by Mutleymuffin** [comment]
http://paste.ee/p/svm9W

**Comment by peterix** [comment]
The log is no longer there, sorry. I guess I either forgot about this or noone could figure it out.
