### ISSUE TITLE
0.4.10-73 Error Updating Instance

### ISSUE THREAD

**Issue by LanceShield** [MultiMC/MultiMC5#1480]
Screenshot: http://i.imgur.com/3nBjeDy.png

Whenever I try to update my Snapshots instance, I get this error.

Instance load failed: Failed to download the following files:
http://s3.amazonaws.com/Minecraft.Download/versions//.jar

Reason:Job 'Libraries for instance Snapshot' failed to process:
http://s3.amazonaws.com/Minecraft.Download/versions//.jar
Please try again.

**Comment by wlhlm** [comment]
See #1453
