### ISSUE TITLE
Snapshots past 16w04 don't download

### ISSUE THREAD

**Issue by adosikas** [MultiMC/MultiMC5#1483]
Every version past 16w04 won't download showing this error:
![screenshot](http://i.imgur.com/dBJl0eX.png)

Log:

    6.774 D "Version index"  started.
    6.817 D Downloading  "http://s3.amazonaws.com/Minecraft.Download/versions/16w07b/16w07b.json"
    6.986 D "Version index" succeeded.
    6.986 D Task succeeded
    6.993 D Task succeeded
    6.993 D "Snapshot" : downloading libraries
    6.994 C Exception: "The base version file of this instance was meant for a newer (18) version of the vanilla launcher than this version of MultiMC supports (14)."
    6.994 W Couldn't apply profile patches because:  "The base version file of this instance was meant for a newer (18) version of the vanilla launcher than this version of MultiMC supports (14)."
    6.994 D "Libraries for instance Snapshot"  started.
    6.995 D Downloading  "http://s3.amazonaws.com/Minecraft.Download/versions//.jar"
    7.103 C Failed  "http://s3.amazonaws.com/Minecraft.Download/versions//.jar"  with reason  QNetworkReply::NetworkError(ContentOperationNotPermittedError)
    7.104 D Downloading  "http://s3.amazonaws.com/Minecraft.Download/versions//.jar"
    7.217 C Failed  "http://s3.amazonaws.com/Minecraft.Download/versions//.jar"  with reason  QNetworkReply::NetworkError(ContentOperationNotPermittedError)
    7.217 D Downloading  "http://s3.amazonaws.com/Minecraft.Download/versions//.jar"
    7.328 C Failed  "http://s3.amazonaws.com/Minecraft.Download/versions//.jar"  with reason  QNetworkReply::NetworkError(ContentOperationNotPermittedError)
    7.329 D Downloading  "http://s3.amazonaws.com/Minecraft.Download/versions//.jar"
    7.442 C Failed  "http://s3.amazonaws.com/Minecraft.Download/versions//.jar"  with reason  QNetworkReply::NetworkError(ContentOperationNotPermittedError)
    7.443 C "Libraries for instance Snapshot" failed.
    7.443 C Task failed:  "Job 'Libraries for instance Snapshot' failed to process:\nhttp://s3.amazonaws.com/Minecraft.Download/versions//.jar"
    7.443 C Task failed:  "Failed to download the following files:\nhttp://s3.amazonaws.com/Minecraft.Download/versions//.jar\n\nReason:Job 'Libraries for instance Snapshot' failed to process:\nhttp://s3.amazonaws.com/Minecraft.Download/versions//.jar\nPlease try again."
   
Using latest git version on ArchLinux x86_64 (compiled with multimc5-git package from AUR, same error with 0.4.10).

**Comment by wlhlm** [comment]
See #1453

**Comment by adosikas** [comment]
Whoops, missed that
