### ISSUE TITLE
French translation has wrong string for application title bar

### ISSUE THREAD

**Issue by Luke7930** [MultiMC/MultiMC5#1484]
Hello, when I launch multimc (version of developement) the application have for name "version : on win32". It was the same with the version stable.

**Comment by peterix** [comment]
Did you get it here: https://multimc.org/ ?

**Comment by peterix** [comment]
Also, do you use a translation? And if so, which one?

**Comment by Luke7930** [comment]
I get in multimc.org and I use a translation, when i use the defauld language there is no problem. I use the language french.

**Comment by peterix** [comment]
Ok. The French translation needs work then.

**Comment by Loetkolben** [comment]
In the german version, this is also "broken".
This is most likely caused by incorrect translations (the %-tokens were forgotten).
See german versaion as an example: https://github.com/MultiMC/MultiMC5-translate/blob/master/de.po#L2121-L2131

**Comment by peterix** [comment]
Well, there is a process for fixing these now. Actually, it's been there all along.
