### ISSUE TITLE
Invalid Credentials when using correct credentials. 

### ISSUE THREAD

**Issue by Spyblox007** [MultiMC/MultiMC5#1485]
I go to type in my username and password, but it tells me I am using incorrect credentials, even though they work on minecraft.net. It suddenly started happening, and I don't know how to fix it.

**Comment by peterix** [comment]
Mojang broke something on their end. Not even their launcher works.

**Comment by peterix** [comment]
If you have a logged in account already, the token refresh is fine.

**Comment by Spyblox007** [comment]
It logged me out, and because it wasn't letting me log in, I removed my account and tried adding it again. How long until you think mojang will fix this?

**Comment by peterix** [comment]
I pinged Grum on IRC... but I assume they'll have a million kids screaming at them in a few hours if it doesn't get fixed fast.

**Comment by peterix** [comment]
Looks like I lost access to only one of my accounts.

**Comment by peterix** [comment]
So. This is likely two unrelated incidents.

Do you use the version of MultiMC from multimc.org?

**Comment by Spyblox007** [comment]
I don't know, it was working an hour ago. My brother wasn't able to log
into his account either.

**Comment by peterix** [comment]
Does it work in the mojang launcher for you?

**Comment by Spyblox007** [comment]
I haven't tried it there, but my brother can't log inrto his minecraft. I
can log in to minecraft.net.

**Comment by peterix** [comment]
Then try.

**Comment by Spyblox007** [comment]
Can't use my pc right now.

**Comment by Spyblox007** [comment]
Its working now.
