### ISSUE TITLE
PLS SOMEONE HELP

### ISSUE THREAD

**Issue by kingstarlord1st** [MultiMC/MultiMC5#1486]
Hello,

I REALLY NEED HELP LS I DONT KNOW WHAT MODS IS AT FAULT. PLS HELP

HERE IS THE PASTE BIN: https://paste.ee/p/6qeUE

PLS ANYONE HELP. I WOULD LIKE A RESPONSE WITHIN 24 HOURS OF THIS TICKET

THANKS 

Kingstarlord1st

**Comment by QuImUfu** [comment]
OpenModsLib, a dependency of Openblocks is missing, and JurassiCraft is corrupted, redownload it.

**Comment by kingstarlord1st** [comment]
What do you mean

**Comment by peterix** [comment]
Assuming this was fixed.
