### ISSUE TITLE
It stops loading, Need help

### ISSUE THREAD

**Issue by Unicornkiller4** [MultiMC/MultiMC5#1487]
Stops loading when initializing mods 
 Log of it loading http://paste.ee/p/V4F7o# 
please help

**Comment by peterix** [comment]
Read the log, it's there. If you make your own packs, you should learn how to read it.

Anyway, you have multiple mods registering dimension ID 51. One of them is `com.tihyo.superheroes`, the other is unknown.

Check mods for what dimensions they register - you should be able to start the game without `superheroes` and teleport over to dimension 51 to check what's there.
