### ISSUE TITLE
Symbol Lookup Error on Linux

### ISSUE THREAD

**Issue by Derpford** [MultiMC/MultiMC5#1488]
When I download and run the latest version of MultiMC, I get this error:
/home/derpford/MultiMC/bin/MultiMC: symbol lookup error: /usr/lib/libGL.so.1: undefined symbol: xcb_unregister_for_special_event

I just ran a system-wide update, so it's not an old GL version. I've no idea what to do here. Building it myself is a headache I don't want to deal with right now.

**Comment by peterix** [comment]
Yeah. If your system drags random incompatible libraries into the display drivers, this happens.

The workaround is to install system Qt 5 - **if you have at least version 5.4.1 available from system ** and to delete most libraries from MultiMC.

In `bin/` keep only:
```
jars
MultiMC
libMultiMC_logic.so
libnbt++.so
updater
librainbow.so
```

In the main folder, remove the plugins folder.

**Comment by Derpford** [comment]
OK, removed the specified files. Now the error is:
```
/home/derpford/MultiMC/bin/MultiMC: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/derpford/MultiMC/bin/libMultiMC_logic.so)
/home/derpford/MultiMC/bin/MultiMC: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/derpford/MultiMC/bin/libnbt++.so)
```

**Comment by peterix** [comment]
You may have to also keep `libstdc++.so.6`.

What distro/distro version is it?

**Comment by Derpford** [comment]
Thaaat would've been nice to know a moment ago, but I still have the tarball, so no big deal.

Distro is Void Linux 64bit; no version info from lsb_release.

**Comment by Derpford** [comment]
Success! Adding libstdc++ to the bin folder led to a successful launch.

**Comment by peterix** [comment]
OK. It will most likely break on updates, because they grab all the files.

Fix for this is planned, but it's hard to say when that will happen - packaging for a lot of different distros and making the updates work with that.
