### ISSUE TITLE
Command line instance launching doesn't work on Linux

### ISSUE THREAD

**Issue by Xaero252** [MultiMC/MultiMC5#1489]
As the title states, the somewhat recently added ability to launch instances with the command line flag for use in desktop shortcuts or launchers does not work on Linux. 
Here's the output when running multimc5 -l "TPPI2"
http://paste.ubuntu.com/15148713/
Doesn't seem to register the flag at all, this was built from git.

**Comment by peterix** [comment]
For FTB tracked instances, you have to add a prefix. So it's 'FTB/TPPI2'.

**Comment by Xaero252** [comment]
I see, I've just tried again, same exact response:
multimc5 -l "FTB/TPPI2"
logs:
http://paste.ubuntu.com/15149897/
Opens the MultiMC window as if no flags were appended.

**Comment by QuImUfu** [comment]
Tested it with my setup, on lubuntu with newest dev version Command line instance launching is working as intended, even for FTB Instances.
Maybe it should stated somewhere that the "Instance ID" is the name of the Folder the instance is in, not the name of the instance.

**Comment by Xaero252** [comment]
I downgraded to the 0.4.1 pre-built release available on the AUR, which pointed me at a flaw in the packaging solution. There is nothing wrong with multimc; the package comes with a script that calls the actual multimc application, which determines where to store profile data (XDG_CONFIG_HOME or ~/.multimc5 based on user environment) This is a clean solution, however it does NOT pass arguments forward to the application (missing "$@") after adding argument forwarding, multimc5 works as intended, I'll be notifying the package maintainers of this issue.

**Comment by peterix** [comment]
Oh. OK.

I can't help you with third party packages.
