### ISSUE TITLE
Could please someone help me with this error 

### ISSUE THREAD

**Issue by Deaththekidoo** [MultiMC/MultiMC5#1491]
I don't know why but this keeps happening 
Mods: Galacticcraft (with planets and micdoddodlecore)
[http://paste.ee/p/PRrVT#](script src="http://paste.ee/e/PRrVT"></script)
If someone could help me that would be great (and that quick pls)

anyway thx

P.S: Just copy the link

**Comment by Loetkolben** [comment]
The log contains multiple
> java.lang.OutOfMemoryError: unable to create new native thread

errors. Increase the RAM assigned to Minecraft in the instance's settings. If you are on a 64bit OS and not using 64bit Java, install it and select it in MultiMC's settings dialog.
