### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005)

### ISSUE THREAD

**Issue by benstuwie** [MultiMC/MultiMC5#1495]
## System Information

Windows 10, Nvidia GT 750m, 8gb ram, Java v8 u 73
(OS: Windows 10.0 , 64 bit Build 10586 (10.0.10586.0)

CPU:total 8 (4 cores per cpu, 2 threads per core) family 6 model 60 stepping 3, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, avx2, aes, clmul, erms, lzcnt, ht, tsc, tscinvbit, bmi1, bmi2

Memory: 4k page, physical 8333592k(3334124k free), swap 9644312k(3273740k free)

vm_info: Java HotSpot(TM) 64-Bit Server VM (25.73-b02) for windows-amd64 JRE (1.8.0_73-b02), built on Jan 29 2016 17:38:49 by "java_re" with MS VC++ 10.0 (VS2010)) according to mc

MultiMC version: 5

Operating System: Windows 10
## Summary of the issue or suggestion:

I crash a lot of times a day, 10+
## What should happen: 

I should not crash
## Steps to reproduce the issue (Add more if needed):
1. Open game
2. Play
3. Be sad because it crashed 
## Suspected cause:

No clue :(
## Logs/Screenshots:

http://pastebin.com/Umw1vKLA
## Additional Info: 

Don't think this a multi mc problem. I get excited with error code 1, -1 and one that is a lot longer. Even crash on normal mc, but I don't know where else to turn. Please help <3

**Comment by peterix** [comment]
http://www.freefixer.com/library/file/HMIPCore64.dll-75628/

Sounds like some sort of weird crapware that injects itself into random applications and makes them crash. Remove it.

**Comment by peterix** [comment]
https://steamcommunity.com/app/271590/discussions/0/611703898449729167/
