### ISSUE TITLE
[BUG] [Minor] MultiMC update while instance executed

### ISSUE THREAD

**Issue by spannerman79** [MultiMC/MultiMC5#1500]
## System Information

MultiMC version:
0.4.11-develop-747
## Operating System:

Windows 10 x64 
## Summary of the issue or suggestion:

Only applies while using the dev update channel due to number of updates.  If MultiMC starts and you start an instance, during that time the update checker finds an update both the instance and update happens at the same time.
## What should happen:

Prevent start of instances until update check has confirmed no updates available.
## Steps to reproduce the issue (Add more if needed):

Already provided in Summary
## Suspected cause:

N/A
## Logs/Screenshots:

Google for "Application not responding" images :stuck_out_tongue_winking_eye:

**Comment by Loetkolben** [comment]
I would opt for "Do not start updating process until no instance is running"

**Comment by peterix** [comment]
Going to test this in 0.5.0:
https://workflowy.com/s/2EyDMcp7CU#/14d7c77e0063

**Comment by peterix** [comment]
This is now fixed, see GH-1874
