### ISSUE TITLE
"undefined symbol: xcb_wait_for_reply64" on startup

### ISSUE THREAD

**Issue by RTHauke** [MultiMC/MultiMC5#1501]
System Information
---
**MultiMC version:**  0.4.10 and earlier

**Operating System:**  Linux 64-bit, Java 8
**Processor:** Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
**Memory:** 16 GB

**Kernel**
```
Linux 3.11.10-34-desktop #1 SMP PREEMPT Wed Jan 20 14:13:45 UTC 2016 (1e76e80) x86_64 x86_64 x86_64 GNU/Linux
```
**java -version**
openjdk version "1.8.0_72"
OpenJDK Runtime Environment (build 1.8.0_72-b15)
OpenJDK 64-Bit Server VM (build 25.72-b15, mixed mode)

**df -h /home**
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda3       768G  521G  247G  68% /home

**glxinfo**
name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: NVIDIA Corporation
server glx version string: 1.4
...
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 660 Ti/PCIe/SSE2
OpenGL core profile version string: 4.3.0 NVIDIA 352.79

Summary of the issue or suggestion:  
---
"undefined symbol: xcb_wait_for_reply64" on start, will not run

What should happen:  
---
Provide update/fix or possible troubleshooting steps.

Steps to reproduce the issue (Add more if needed):
---
1.  Use fresh installation of current.

2.  cd  {installpath}

3.  ./MultiMc

Suspected cause:  
---
Possible incompatibility with new libs.  Worked back in December but doesn't now.  There have been a ton of security updates since then to Linux and Java.

Logs/Screenshots:
---
```
user@host:~/mcother/MultiMC> ./MultiMC 
MultiMC Dir: /home/user/mcother/MultiMC
No missing dependencies found.
/home/user/mcother/MultiMC/bin/MultiMC: symbol lookup error: /usr/lib64/libX11.so.6: undefined symbol: xcb_wait_for_reply64
```

Additional Info:  
---
Not that it means anything, but other launchers are working fine, i.e. FTB (non-Curse) and LITW

**Related libraries**
```
host:/usr/lib64 # ls -l libX11*
lrwxrwxrwx 1 root root      19 Dec 14 19:56 libX11-xcb.so -> libX11-xcb.so.1.0.0
lrwxrwxrwx 1 root root      19 Feb 21 06:46 libX11-xcb.so.1 -> libX11-xcb.so.1.0.0
-rwxr-xr-x 1 root root    6064 Nov 24 04:02 libX11-xcb.so.1.0.0
lrwxrwxrwx 1 root root      15 Dec 14 19:56 libX11.so -> libX11.so.6.3.0
lrwxrwxrwx 1 root root      15 Dec 14 19:56 libX11.so.6 -> libX11.so.6.3.0
-rwxr-xr-x 1 root root 1302168 Nov 24 04:02 libX11.so.6.3.0
```

**Comment by peterix** [comment]
Linux is not an operating system. What distro is this and what version of it?

**Comment by peterix** [comment]
You might have to remove some of the libraries that come with MultiMC to get it to work.

**Comment by RTHauke** [comment]
OpenSUSE 13.1, but a distribution isn't an OS either!  :)

I will try pulling some of the supplied libraries and post results.

**Comment by RTHauke** [comment]
I removed _MultiMC/bin/libxcb.so.1_ and it appears to be working.  I'll update if I see any issues from doing so.

**Comment by RTHauke** [comment]
Seems to be working fine.  Thank you!

**Comment by peterix** [comment]
You might have to repeat this after updates.

**Comment by peterix** [comment]
I'm planning to fix this, but binary distribution on linux is not easy. It will take some time to build up the infrastructure needed for that.

**Comment by Seegras** [comment]
On Debian/Sid I had to delete most of the libxcb-* libraries in the bin folder; except libxcb-sync. Also, since I recompiled, I had to delete libQt5*.
