### ISSUE TITLE
./bin/MultiMC: symbol lookup error: /usr/lib64/libX11.so.6: undefined symbol: xcb_wait_for_reply64

### ISSUE THREAD

**Issue by joserobjr** [MultiMC/MultiMC5#1504]
System Information
64 bits 12 GiB RAM

MultiMC version:
I can't see but it's latest published today

Operating System:
openSUSE Leap 42.1 x86_64

Summary of the issue or suggestion:
It's not starting after the latest updates

What should happen:
I installed my system recently, it was working fine with the outdated softwares but after everything got updated MultiMC fails to launch.

FTB and Technic are launching fine

Steps to reproduce the issue (Add more if needed):
1. Download MultiMC5
2. tar -zxf mmc-stable-lin64.tar.gz
3. cd MultiMC5
4. ./MultiMC5

Results:
MultiMC Dir: /home/joserobjr/Downloads/MultiMC
No missing dependencies found.
/home/joserobjr/Downloads/MultiMC/bin/MultiMC: symbol lookup error: /usr/lib64/libX11.so.6: undefined symbol: xcb_wait_for_reply64

Suspected cause
I don't know

Logs/Screenshots:
![image](https://cloud.githubusercontent.com/assets/3679022/13394562/00e60d8c-dec8-11e5-96a1-6bad7301a7ef.png)

Additional Info:
---

**Comment by peterix** [comment]
https://github.com/MultiMC/MultiMC5/issues/1501

**Comment by peterix** [comment]
See the linked issue. Deleting bin/libxcb.so.1 could fix it.

**Comment by joserobjr** [comment]
Thank you, it worked! I forgot to search on the closed issues, sorry for the duplication.
