### ISSUE TITLE
MultiMC 5 version 0.4.1 wont update to 0.4.11

### ISSUE THREAD

**Issue by Win7yes** [MultiMC/MultiMC5#1505]
System Information:
I'm not sure what I need to put here.
MultiMC version:
0.4.1
Operating System:
Windows 8
Summary of the issue:
Trying to update MultiMC from 0.4.1 to 0.4.11, but it always gets stuck at the end.
It claims it's downloading 29 update files even tho it doesn't show any change to the progress bar.

What should happen:
Well I guess it should finish and update properly.

Steps to reproduce the issue (Add more if needed):

1. Start MultiMC

2. When it asks to update, click Update Now

3. It should get stuck somewhere near the end

Suspected cause:
None

Logs/Screenshots:

[MultiMC-1.txt](https://github.com/MultiMC/MultiMC5/files/151574/MultiMC-1.txt) Log of the last time I attempted to download the update.

**Comment by peterix** [comment]
Just grab a fresh version and copy over your instances.
