### ISSUE TITLE
[IDEA]An integrated installation of Optifne

### ISSUE THREAD

**Issue by tipapro** [MultiMC/MultiMC5#1506]
Can you make an integrated installation of Optifne(as Forge)?

**Comment by peterix** [comment]
Something like that, yes. But not the way you think.

Each of the existing packages has a special format for version lists. Optifine has none, so I would have to maintain that next to the existing packages.

It needs a more general solution, and there will be one. I want to get rid of the direct dependency on the lists published by Mojang, Forge and Liteloader too - first.

See:  https://workflowy.com/s/2EyDMcp7CU -> Ideas -> Version lists, Wonko package management and a few others.

**Comment by peterix** [comment]
Plenty of work has been done on this already. It's just nowhere near done.

**Comment by ask6155** [comment]
Can you do it like TLauncher?
It doesn't even say on home screen that its optifine it just says modified version
put it just next to the install forge button on the console
