### ISSUE TITLE
with nei game doesnt open

### ISSUE THREAD

**Issue by deKeetAruba** [MultiMC/MultiMC5#1510]
## System Information

MultiMC version:

Operating System:
## Steps to reproduce the issue (Add more if needed):

1.

2.

3.

**Comment by deKeetAruba** [comment]
http://paste.ee/p/c0HG6
this is report
playing 1.7.10

**Comment by whitephoenix0** [comment]
This is not a MultiMC issue so please do not post issues regarding your own modpack. The crash is because you either don't have CodeChickenCore (a dependency for NEI) installed, or you have an incompatible version.
