### ISSUE TITLE
How do i update MultiMC without reinstalling it? 

### ISSUE THREAD

**Issue by gtakingg** [MultiMC/MultiMC5#1513]
Before submitting this issue, please make sure you have:

System Information
Intel(R) core i5-2400 CPU @ 3.10 ghz 8gb RAM  GTX 750ti
MultiMC version:

Operating System:
Windows 7

Summary of the issue or suggestion:
What it says in the title basically

What should happen:
Update?
## Steps to reproduce the issue (Add more if needed):

1.

2.

3.

Suspected cause:
Needing to delete something?

Logs/Screenshots:
Not needed

Additional Info:
None

**Comment by whitephoenix0** [comment]
Go to the folder where you installed MultiMC and run "updater.exe"
