### ISSUE TITLE
Mojang Accounts with multiple minecraft users don't work.

### ISSUE THREAD

**Issue by luker2009** [MultiMC/MultiMC5#1517]
System Information Windows 8.1 on a Pavilion g7
---
MultiMC version: 0.4.11-751

Operating System: Windows 8.1

Summary of the issue or suggestion: 
---
Mojang Accounts with multiple minecraft users don't work.

What should happen:
---
I should be able to choose between the accounts which all have different UUIDs

Steps to reproduce the issue (Add more if needed):
---
1. Use a mojang account with multiple minecraft users (For example: DaQa)

2. Open multiMC and try to login with mojang account.

Suspected cause:
---
Authentication server didn't specify a currently selected profile. The account exists, but doesn't have one specific profile.

Logs/Screenshots:
---
http://i.imgur.com/2xvEi8f.png

**Comment by peterix** [comment]
So, how do you even get such an account?

**Comment by luker2009** [comment]
It's not common but it occasionally happens, for example http://namemc.com/s?lol and http://namemc.com/s?DaQa (on mobile right now but will update with official mojang api links)

**Comment by peterix** [comment]
I am not asking 'if' it happens, but 'how do I make ity happen'. I have no way to test this.

**Comment by luker2009** [comment]
I'm not sure exactly, I did some experimenting and was able to generate yggdrasil sessions with different profiles selected, I can share that code with you. (And for testing purposes I can give you temporary access to such an account if needed)

**Comment by jikuja** [comment]
Which case this is

1. Multiple accounts which have used common username (like those links) or
2. One account containing multiple profiles? (yes, data structures in mojang's code vanilla launcher support that but I've never seen anyone with multiple profiles)

**Comment by luker2009** [comment]
Both, there had been a bug that created multiple profiles with the same username for a time, I believe Mojang has since fixed it however and I believe fixed the glitched accounts (Making this issue not a problem, yet.)
Should I close the issue since I believe this is no longer an issue?

**Comment by peterix** [comment]
I will consider this when there's a legitimate way to get multiple profiles per account.
