### ISSUE TITLE
Keeps Crashing

### ISSUE THREAD

**Issue by Plasmo322** [MultiMC/MultiMC5#1518]
So MultiMC keeps crashing when I have these mods installed and I have no idea why. Can someone please tell me whats wrong and how I can fix it? I know it works because I played with these exact mods in this launcher a few months ago and now its not working for some reason. I changed nothing.

Crash Log: http://pastebin.com/dKdGKPWn

Mod List: http://pastebin.com/zC1D8iNW

PLEASE GET BACK TO ME ASAP!!!!!!!

I dont know if this is MultiMC being a B*** or my modpack so please dont get mad at me im not good at reading crash reports.. like at all....

**Comment by whitephoenix0** [comment]
This is a problem with your modpack. It looks like your problem is immibis microblocks. Try removing it or using an older version.

**Comment by Plasmo322** [comment]
I've solved the issue a few days prior to your comment. Closing the issue. Thanks anyway!
