### ISSUE TITLE
Subgroups

### ISSUE THREAD

**Issue by SoniEx2** [MultiMC/MultiMC5#1522]
## System Information

MultiMC version: N/A

Operating System: N/A
## Summary of the issue or suggestion:

There should be a way to have groups inside groups. These would be purely for perfectionists/OCPD people.
## What should happen:

The group selector, when a group is selected, would give you a subgroup selector below it. That subgroup selector, when a subgroup is selected, would give you another subgroup selector below it. And so on.
## Steps to reproduce the issue (Add more if needed):

N/A
## Suspected cause:

N/A
## Logs/Screenshots:

N/A
## Additional Info:

N/A

**Comment by peterix** [comment]
I don't see how this would fit into the UI... not to mention that it's all custom UI and not easy to write.

Well, it's an idea. I'll track it on workflowy - it's in Ideas, Instance view, Allow nesting groups.

But don't really expect it to happen any time soon.
