### ISSUE TITLE
Website Issues

### ISSUE THREAD

**Issue by jeg623** [MultiMC/MultiMC5#1523]
I went to download optifine and it only found one version
![capture](https://cloud.githubusercontent.com/assets/17114650/13895963/14d72ebe-ed39-11e5-8958-4f97e4f41e9e.PNG)

**Comment by Jerzerak** [comment]
How is this a MultiMC issue?

**Comment by Loetkolben** [comment]
First of all, this is not a MultiMC issue, nor in any way related. Please keep in mind this is a bug tracker for MutliMC5, and not Minecraft or Minecraft-related issues. As this is Optifine related, we cannot help.
Secondly, the page itself tells you the reason:
> All files containing original or modifed Minecraft code and resources have been removed.
Some popular 1.6 and 1.7 versions may be cleaned up later.
