### ISSUE TITLE
Can't use optifine of 1.9

### ISSUE THREAD

**Issue by Small-Ku** [MultiMC/MultiMC5#1525]
System Information
---
MultiMC version:
0.4.12-develop-759
Operating System:
Windows 10 Home 64bit
Summary of the issue or suggestion:
---
Can't load optifine with Launchwrapper in 1.9 (also with forge)
What should happen:
---
Optifine loaded
Steps to reproduce the issue (Add more if needed):
---
1.Basic to add a instance with 1.9

2.Follow https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine

3.(Optional)Change "net.minecraft:launchwrapper:1.8" to "net.minecraft:launchwrapper:1.9"

Suspected cause:
---

Logs/Screenshots:
---
Log:http://paste.ee/p/42gzA
Additional Info:
---
Version of Forge for 1.9:12.16.0.1780
Version of OptiFine:1.9.0 HD U A3 pre

Log when loading optifine with forge(still process exited with code -1):http://paste.ee/p/eCCyg
My "optifine.json":http://paste.ee/p/W7PQr
> Sorry for bad English :P

**Comment by NolanSyKinsley** [comment]
Optifine and Forge are not compatible on 1.9 yet, optifine has to update to take account for forge's changes.

**Comment by Small-Ku** [comment]
@NolanSyKinsley
Forge:http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.9.html
Optifine(Preview versions):http://optifine.net/downloads

**Comment by NolanSyKinsley** [comment]
Yes, they both have 1.9 versions available, but optifine is still using the old forge mappings, so it is not compatible with forge on 1.9 yet.

**Comment by Small-Ku** [comment]
@NolanSyKinsley Thank you :P

**Comment by peterix** [comment]
Yeah... that `optifine.json` will also not work because of the changes made to all current optifine versions...
I'm trying to get that fixed... 

Newest developments:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272953-optifine-hd-h3-fps-boost-hd-textures-shaders-and?comment=50401
