### ISSUE TITLE
Feature Request: ability to launch instances from CLI

### ISSUE THREAD

**Issue by zekesonxx** [MultiMC/MultiMC5#1528]
Very big fan of MultiMC, but it doesn't function super well with Steam Big Picture / In-Home Streaming (or other ten-foot display systems for that matter).

While a complete controller-compatible UI would be awesome, I also can understand how much work that would take. However, being able to launch directly into an instance would remove most of the issues and provide a more seamless experience, ex `multimc5 --launch "FTB"`.

Thanks!

**Comment by TNTUP** [comment]
Already implemented, what I've seen its -l <instance> to launch. I tried and it works :)

**Comment by zekesonxx** [comment]
Indeed it does. It looks like the Arch Linux script for launching MultiMC doesn't pass command line parameters to MultiMC, so I'll see about getting that fixed.
