### ISSUE TITLE
Updating from 0.4.7 to 0.4.11 never finishes

### ISSUE THREAD

**Issue by mkobler** [MultiMC/MultiMC5#1531]
System Information
---
MultiMC version: 0.4.7

Operating System: Linux Ubuntu

Summary of the issue or suggestion:
When updating to latest version (0.4.11), the update never finishes.  It appears to get stuck on downloading the libQt5Widgets.so.5 and never makes it past.  Log attached below.

What should happen:
---

Steps to reproduce the issue (Add more if needed):
---
1. Start update

2.

3.

Suspected cause:
---

Logs/Screenshots:
---
[MultiMC-0.txt](https://github.com/MultiMC/MultiMC5/files/185946/MultiMC-0.txt)

Additional Info:
---

**Comment by QuImUfu** [comment]
Just [download](https://files.multimc.org/downloads/mmc-stable-lin64.tar.gz) the newest version and replace your current version (located in ~/.local/share/multimc if installed via .deb).
(Take care not to remove/replace the instances folder)

**Comment by mkobler** [comment]
Worked, thx!
