### ISSUE TITLE
FTB Errors Out in MultiMC - Will Not Open

### ISSUE THREAD

**Issue by Doominatrixx** [MultiMC/MultiMC5#1533]
## MultiMC version:

Product Version 5 - File Version 1.0.0.0
## Operating System:

Windows 10 (64bit)
## Summary of the issue or suggestion:

Whenever I click "Play" on any Modpack, I get the error report shown below in the paste.ee link. Even if I do not use MultiMC, they still will not load directly from FTB either.

---
## What should happen:

I expected to play the game after pressing "play".
## Steps to reproduce the issue (Add more if needed):
1. Import Modpacks from FTB
2. Press "Play" after selecting desired modpack to play.
3. Press "Play" on a different modpack to see if the issue is with all modpacks or just the one.
## Suspected cause:

Possibly Java? This is a new computer so I had to install Java x64 myself. I did install the link that Oracle "said" was 64Bit, and I do have the most updated version of Java via their version checker. But that wouldn't explain things just not even opening :/ I don't think...
## Logs/Screenshots:

http://paste.ee/p/i50Wt
## Additional Info:

When I first got everything installed on this new machine, FTB did work correctly. The very next day, nothing would work. No modpacks would load. It would download the files but the moment the game was supposed to start up, something would immediately crash it and it would toss me back to the launcher. Same thing happens with MMC, I get an error log and nothing will load.

**Comment by peterix** [comment]
Right. This is a mismatch between FTB versions of Minecraft and Mojang's versions of Minecraft... FTB updates the `guava` library to version 16 in the Minecraft version and doesn't include it in the Forge version.

Try the develop builds of MultiMC - you can switch to those in the settings and update.

**Comment by Doominatrixx** [comment]
Hello, Peterix!

Thank you for the response!

Is this what you mean?  http://i.imgur.com/nFoPSpy.png

If so, I still get this: http://paste.ee/p/UQgRy

**Comment by peterix** [comment]
You didn't update. The log is from the same version as before.

**Comment by Doominatrixx** [comment]
Oh my, I am not very techy with these things. So after selecting "Development" from that drop down menu, I clicked the close button. Is there a step I am missing?

**Comment by peterix** [comment]
Yep. Click the update button (box with up arrow), or restart MultiMC.

**Comment by Doominatrixx** [comment]
Oh my gosh, it hates me :(  http://paste.ee/p/W6ZcH

**Comment by peterix** [comment]
So it's actually a problem that wasn't fixed yet.

So a workaround: Add Forge to the instance - with the same version that FTB would normally use. In your case, `1614`.

**Comment by Doominatrixx** [comment]
Wow! I love you long time :D http://i.imgur.com/R1USYJT.png

It is now working :D You rock! Thank you so very much!

**Comment by peterix** [comment]
Alright. Going to fix this for sure for the next version.

You might want to switch back to the stable version if you don't want to test devel builds :)

**Comment by Doominatrixx** [comment]
*facedesk* Yeah I probably should have done that, unless you need me to test it? I don't mind :) It's the least I can do for your help and quick response!

**Comment by peterix** [comment]
Hm... it's probably better if you stay on this devel version until the next stable release.

**Comment by Doominatrixx** [comment]
Fantastic! Thank you very much for the help!

**Comment by Doominatrixx** [comment]
Well, I thought it was fixed :( It won't go passed a certain point. I tried both devel and stable. - http://paste.ee/p/sh3Iu

**Comment by peterix** [comment]
`java.lang.OutOfMemoryError`

You have to give it more memory. The default of 512M - 1024M is fine for vanilla, but really not enough for modded instances. You can find the java options in the settings (monitor+screwdriver icon).

**Comment by Doominatrixx** [comment]
Oooh! I typically give 4 Gigs, I'm not sure why I thought memory settings would transfer from my FTB client.. -facedesk- Thanks again ^_^

**Comment by TheDoctorsLife** [comment]
Is this fixed?

**Comment by peterix** [comment]
AFAIK, no. Needs testing. User has a workaround.

**Comment by Doominatrixx** [comment]
Oh dear... What broke on this one? o.O http://paste.ee/p/kdahC  I did follow all of your steps in this thread, but there's no help for this poor thing :octocat:

**Comment by peterix** [comment]
This is not relevant anymore.
