### ISSUE TITLE
Minecraft Crashed with exit code -1

### ISSUE THREAD

**Issue by FireFan454** [MultiMC/MultiMC5#1534]
System Information
---
MultiMC version: 11.4

Operating System: Windows 10

Summary of the issue or suggestion: 
--- 
Whenever I launch any instance of Minecraft modded or not, it crashes.
What should happen:
--- 
Until this morning, the instance launched perfectly fine

Steps to reproduce the issue (Add more if needed):
---
1. Every time an instance of MultiMC is launched it crashes without me ever seeing a minecraft window.

Suspected cause:
--- 
My Java was updated this morning, I can't think of another cause.

Logs/Screenshots:
--- 
https://paste.ee/p/LoSYP

**Comment by jikuja** [comment]
Did your machine get updates? Did something crash before you started playing MC?

**Comment by FireFan454** [comment]
The only update was a Java update

**Comment by jikuja** [comment]
Download jre-8u51-windows-x64.exe http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html#jre-8u51-oth-JPR After installing that
 java version restart MMC and configure it to use java 8u51.

**Comment by peterix** [comment]
This is most likely related to https://github.com/MultiMC/MultiMC5/issues/1276

If you use intel HD2000 or similar old integrated GPU, you need an older java version - or a hardware upgrade.

You can grab Java from here:
files.multimc.org/downloads/jre-8u51-windows-x64.zip (64bit)
http://files.multimc.org/downloads/jre-8u51-windows-i586.zip (32bit)

Extract the appropriate (32bit or 64bit) Java somewhere
Select the javaw.exe from that  (Settings -> Java -> Java path ... -> select the javaw.exe)

**Comment by peterix** [comment]
Continued in #1535
