### ISSUE TITLE
.minecraft folder

### ISSUE THREAD

**Issue by chrisbecke** [MultiMC/MultiMC5#1536]
Please consider using the vanilla launchers .minecraft folder to retrieve the library jar's and assets. Even better, write back to it.

When using multiple launchers it is really annoying that each one has to do a full download of stuff that is already on the PC.

**Comment by 02JanDal** [comment]
This has been requested before, the issue is that we have to treat the stuff in `.minecraft` very carefully. We might at some point add getting stuff from there, but we will certainly not write anything back.
