### ISSUE TITLE
Error downloading paste.ee/api when api key is invalid.

### ISSUE THREAD

**Issue by dmodoomsirius** [MultiMC/MultiMC5#1537]
## System Information

MultiMC version: 0.4.12-develop-761

Operating System: Windows 
## Summary of the issue or suggestion: 

when api key is disabled yet the key is in the http://paste.ee/ account api settings page. I get "Network error: Error downloading http://paste.ee/api - server replied: Internal Server Error" when trying to upload a log file.

**Comment by peterix** [comment]
![image](https://cloud.githubusercontent.com/assets/203326/14069471/90fb1c2c-f49a-11e5-98a5-3326ab6b26bb.png)
Like this?

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
