### ISSUE TITLE
Process exited with code 1.

### ISSUE THREAD

**Issue by ArtimisFowl888** [MultiMC/MultiMC5#1541]
MultiMC version: 0.4.11

Operating System: Win 10

 issue:(side note this happens with vanilla Minecraft also)
Error occurred during initialization of VM
Could not reserve enough space for 2883584KB object heap
Process exited with code 1.

Logs:
MultiMC version: 0.4.11-751

Minecraft folder is:
instances/skyblocks/minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/java.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms640m, -Xmx2816m, -Duser.language=en, -jar, C:/Users/zac/Downloads/mmc-stable-win32/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 12392

Error occurred during initialization of VM
Could not reserve enough space for 2883584KB object heap
Process exited with code 1.

**Comment by TacoGS** [comment]
Try installing and using 64 Bit Java if you haven't already.

**Comment by ArtimisFowl888** [comment]
That worked thanks.

**Comment by TacoGS** [comment]
No problem, have a good day.
