### ISSUE TITLE
Problem with Java 8 on MultiMC5

### ISSUE THREAD

**Issue by nialacat** [MultiMC/MultiMC5#1544]
MultiMC version: 0.4.11-751

Minecraft folder is:
instances/vanilla/minecraft

Java path is:
C:/Users/Tiffy/Downloads/Java_Download.exe

Checking Java version...
Could not start java:

Check your MultiMC Java settings.
 I had Java 7 and the same thing happened. I tried auto detecting and it said that no versions were currently available. I tried re-booting MultiMC and re-installing Java 8 but it still didn't work. What do I do?

**Comment by jikuja** [comment]
Where did you download java? Excutable in your javapath looks something I would not install into my machine.

If you downloaded your java from legit source, did you actually install it by running the excutable you downloaded?

**Comment by nialacat** [comment]
I've tried multiple sites and one of the downloads never came with .exe but I uninstalled all of the ones that ended with .exe and still had the same problem. I got it from www.java.com/en/

**Comment by QuImUfu** [comment]
"C:/Users/Tiffy/Downloads/Java_Download.exe" doesn't look like a Java jre. 

* Delete it, and uninstall all other versions of  Java on you computer (in system settings, software).

* Download and install Java from [this] (http://www.java.com/en/download/windows_manual.jsp) site, the offline version  for your [architecture] (http://hubpages.com/technology/How-to-check-your-system-architecture).

* After the installation press auto-detect in the Java tab of the MultiMC settings.

* It should find Java automatically, test if everything works (with the test button right of the auto-detect button).

**Comment by peterix** [comment]
No response in more than a year... closing.
