### ISSUE TITLE
latest update causes hang on survival ground movement on world load

### ISSUE THREAD

**Issue by modderchris** [MultiMC/MultiMC5#1545]
System Information
-----------------------------
MultiMC version:
0.4.11

Operating System:
windows 7 ultimate x64
windows 7 enterprise x64 (testing on only)                             

Summary of the issue or suggestion:
----------------------------------------------
using movement keys while on the ground causes javaw.exe from jre7_u55 to hang and never respond (two hours waiting)
What should happen:
------------------------------
It should play exactly like the technic launcher ?
trying to move on a client or server world causes "Not responding"

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. change of mods to default tekkit main

2. windows reinstall (see above)

3. alternate launcher (no issue with both modpacks(see above))

Suspected cause:
---------------------------
multimc newlaunch.jar upon 0.4.1X update chain "do tick ingame" thread

Logs/Screenshots:
----------------------------
[https://www.dropbox.com/s/lspsg8b7hx5pn3v/MultiMCHangLog.txt?dl=0] Console Log
(given as text due to extreme size of mod quantity)

Additional Info:
---------------------------
same hardware
1. same MSI Twin FROZR III graphics card
                        2GB GDDR5 256bit
                        1280 stream processors
                        raedon HD 6XXX series
                       900-945(*2)mhz core
                       1200-1250(*2)mhz memory
2. same Gigabyte GA-970A-D3P
3. same AMD Phenom II x4 B50 codename Denab 3.2Ghz
4. same 8x2 + 4x2 DDR3 1600 (clocked 1333(*1)) ram set
5. new EVGA 850w 80-PLUS Gold Modular EATX PSU
6. 1-year-old WD 1TB Blue (storage and games(including MultiMC))
7. 18-month-old WD 1TB Blue (OS and Java/C++/ect.)

*1-2: ram(*1) and gpu(*2) can hit much higher speeds than standard via OC but I tried default automatic bios configuration as to confirm hardware was not the Issue

Note 2: Technic launcher on latest update works flawlessly for several hours on both modpacks = Confirmed MultiMC Issue

Note 3: update 0.4.9 confirmed no issue or change in modpack since

Note 4: Optifine can cause same issues as walking by changing settings although optifine does not make any other difference

Note 5: Issue only occurs AFTER World rendering STARTS

**Comment by modderchris** [comment]
EDIT: log is only of the newagecraft tecnic pack
IE. I can upload a Tekkit Main log If Needed

**Comment by peterix** [comment]
None of that makes it a confirmed MultiMC issue.

First, try the develop version. You can switch to that in the settings and update.

If it doesn't work on the develop version, remove and reinstall Forge.


If it still doesn't work, try this:
https://files.multimc.org/downloads/mmc-stable-win32-0.4.9-728.zip

**Comment by modderchris** [comment]
The fact that I used another launcher with the same EXACT modpack that worked fine PROVES it is a MultiMC issue

**Comment by modderchris** [comment]
UPDATE: 0.4.9 doesn't work but technic still does

**Comment by peterix** [comment]
Then something else changed on your system.

**Comment by peterix** [comment]
What the hell, buttons.

**Comment by modderchris** [comment]
Nope same system for past 18 months and multimc worked back then only now(approx. 2 months ago It changed
PSU is new but that doesn't matter

**Comment by modderchris** [comment]
new log ending including error code

2016-04-02 14:23:08 [INFO] [Minecraft-Client] [CHAT] [Rei's Minimap] 1 Waypoints loaded for newagecraft.ddns.net
2016-04-02 14:23:09 [INFO] [STDOUT] [Mekanism] Minecraft is in offline mode, could not check for updates.
2016-04-02 14:23:09 [INFO] [Minecraft-Client] [CHAT] Version 4.7.0pre11 of ProjectRed available.
2016-04-02 14:23:09 [INFO] [Minecraft-Client] [CHAT] - ADDED: Network Valve pipe
2016-04-02 14:23:09 [INFO] [Minecraft-Client] [CHAT] - ADDED: Network Latency pipe
2016-04-02 14:23:09 [INFO] [Minecraft-Client] [CHAT] - FIX: Major routed pipe bug breaking auto-crafting
2016-04-02 14:23:09 [INFO] [Minecraft-Client] [CHAT] - FIX: Craft/pull filters on request pipe
2016-04-02 14:23:09 [INFO] [Minecraft-Client] [CHAT] - FIX: Routed pipe pathfinding bugs
2016-04-02 14:23:09 [INFO] [Minecraft-Client] [CHAT] - CHANGE: Slight performance improvement for routed pipes
2016-04-02 14:23:09 [INFO] [STDOUT] Setting up custom skins
2016-04-02 14:23:09 [INFO] [STDOUT] Setting up custom skins
2016-04-02 14:23:09 [INFO] [STDOUT] Setting up custom skins
2016-04-02 14:23:09 [INFO] [STDOUT] Setting up custom skins
2016-04-02 14:23:09 [SEVERE] [Galacticraft] Galacticraft update check failed! Trying again in 15 seconds
2016-04-02 14:23:10 [INFO] [PortalGun] [2.0.2] Received world props from server.
2016-04-02 14:23:10 [INFO] [STDOUT] Inserted super call into axm.c
[OptiFine] Expand tessellator buffer, old: 524288, new: 1048576
2016-04-02 14:23:14 [INFO] [STDOUT] computercraft: Searching for RedPowerWorld...
2016-04-02 14:23:14 [INFO] [STDOUT] computercraft: RedPowerWorld not found.
2016-04-02 14:23:20 [INFO] [EE3] DynEmc system initialized after 22354 ms
2016-04-02 14:23:24 [SEVERE] [Galacticraft] Galacticraft update check failed! Trying again in 15 seconds
Process crashed with exitcode -805306369.

**Comment by modderchris** [comment]
Wait maybe switching from Gigabyte GA-970A-DS3P to Gigabyte GA-970A-D3P was the issue but the same features are availible down to the number and arrangement of pci/pcie slots

**Comment by modderchris** [comment]
only difference is 8 pin cpu vs 4 pin cpu power

**Comment by modderchris** [comment]
and D3P contains serial port header but it is disabled

**Comment by modderchris** [comment]
Not running beta bios either

**Comment by modderchris** [comment]
I'll test using DS3P and see if it is different

**Comment by modderchris** [comment]
No it HAS to be a Multimc issue because the motherboard swap had the same issue
I know this as fact because:
A: the only hardware change that effects software running properly(IE. motherboard, ram, cpu, hdd, graphics card(not PSU, case, cooler) has been proven not to be the Issue
B: the ONLY software upgrade/installation/uninstallation was MultiMC
C:the technic launcher runs the modpack flawlessly
and
D: Absolutely NOTHING was changed about the modpack since the last time it worked on MultiMC

all of these points proves without a shadow of a doubt to any rational person that this issue is a MulticMC bug

**Comment by modderchris** [comment]
so as I said can you test to see what the issue is and resolve it because I really like MultiMC but if I can no longer run redstone-in-motion or rei's minimap due to the MultiMC engine not liking the programming I will not recomend it to anyone or use it myself

**Comment by modderchris** [comment]
I can send a direct link to my modpack or you can use tekkit main because they both are broken on the latest update

**Comment by jikuja** [comment]
Java versions, java crashlog from windows' reliability monitor?

**Comment by QuImUfu** [comment]
do you use the **same** command line options?
(ram, maybe GC?)
2gb ram may not be enough for such an huge pack.

**Comment by peterix** [comment]
@modderchris please go through the steps I described above, *confirm* or *deny* that it works, and provide full logs for each failure.

There is nothing to go on here, only completely unrelated details.

**Comment by peterix** [comment]
And don't forget to remove an re-add Forge in 0.4.9, if you use the same instance folder.

**Comment by peterix** [comment]
You somehow have optifine, although it isn't in the mod list. How? Did you use the `1.6.4` folder in the `mods` folder? If so, what **else** is there?

What I did:
* Grabbed the pack from technic (newagecraft).
* Added the same version of OptiFine
* Works. See log: https://paste.ee/p/rYJMS - this is the closest I can get to your setup. Giving it 2GB is a bit tight, but works.

The pack does not have optifine by default. Try without optifine. Actually, try the pack as-is without any extras. Do not use that `1.6.4` folder.

Try renaming `MultiMC.exe` to `Minecraft.exe` - sometimes graphics drivers look at the executable names to enable extra features/hacks to keep things going...

**Comment by modderchris** [comment]
I used 1.5gb with the technic launcher and optifine in the 1.6.4 folder and
had no issues if it works with another launcher It should work with multimc
so fix it I'm not testing any other ways because I have already explored
all possibilities before and after 0.4.9 so stop telling me to try again.
already tried:
with and without optifine
with 1.5gb 2gb 4gb
with permsize 512m
with another launcher (works with 1.5gb default permsize and optifine in
1.6.4 folder)

if it works with another launcher in the same settings it should work with
multimc so either it its bad programming or one of the libraries is damaged
or incompatible

**Comment by peterix** [comment]
So, you won't. I cannot help you.

**Comment by peterix** [comment]
Cannot reproduce issue.
