### ISSUE TITLE
Coremod support?

### ISSUE THREAD

**Issue by ThexXTURBOXx** [MultiMC/MultiMC5#1546]
As I looked after all the Loader Mods, I saw, that MultiMC shows the 1.8.9-folder (in this case it is 1.8.9) as a Mod with the version "Folder". What about adding support to show the coremods that are inside of it? That would be pretty cool.

System Information

-----------------------------

MultiMC version: 0.4.12-develop-763

Operating System: Windows 8.1, 64x

-----------------------------

Screenshot:

!["1.8.9-mod"](https://cloud.githubusercontent.com/assets/12763829/14229828/809bdd9a-f93f-11e5-9c50-5301a483649d.jpg)

**Comment by QuImUfu** [comment]
Already on [workflowy] (https://workflowy.com/s/2EyDMcp7CU).
Under the bullet point Mod list.

**Comment by ThexXTURBOXx** [comment]
Ah ok, sorry. Didn't know about the link. I close this then ^^
