### ISSUE TITLE
Minecraft is crashing and I don't have an idea why

### ISSUE THREAD

**Issue by shader301202** [MultiMC/MultiMC5#1548]
## System Information

MultiMC version: 0.4.11-751

Operating System: Windows 10
## Steps to reproduce the issue (Add more if needed):
1. I moved in Minecraft.
2. I moved again.
3. The game crashed.
## Additional Info:

I don't know which mod is the cause for this crash, so I posted it here. Please say me which mod is the cause :)

**Comment by QuImUfu** [comment]
Generally just try it. 
Deactivate the first half of the mods, if the problem still exist, reactivate this half, and deactivate the other half. When you have the working half, re-add the mods one-by-one till you have pinpointed one mod causing the crash.
Updating all the mods very often solves crashes (some of your mods are outdated).

**Comment by peterix** [comment]
```
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_60]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_60]
	at com.enderio.core.common.util.Scheduler.runTasks(Scheduler.java:120) ~[Scheduler.class:?]
	at com.enderio.core.common.util.Scheduler.onClientTick(Scheduler.java:113) ~[Scheduler.class:?]
```

In this case, enderio was doing something and it crashed... so maybe focus on that.

**Comment by shader301202** [comment]
peterix, You are right. The game is crahing only because of Ender IO. Every time the game crashes, I become this: 
`EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.1.0 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.13B1 from extrautilities-1.2.12.jar).`
When I remove Extra Utilities, there is Railcraft etc.

**Comment by ceacer1** [comment]
The exact same thing happens to me when I try go on to one certain server (Mineplex.com) and i have no idea why please fix this
