### ISSUE TITLE
Crash When I Start A New Game In Modded Instance

### ISSUE THREAD

**Issue by CondeDuke** [MultiMC/MultiMC5#1550]
## System Information

MultiMC version:

Operating System:
## Summary of the issue or suggestion:

Every time that i go play in any instance: 1.8, 1,7.10, 1.7 and at last one mod it's crash.
## What should happen:

It shouldn't crash.
## Steps to reproduce the issue (Add more if needed):

1.

2.

3.
## Suspected cause:

None.
## Logs/Screenshots:

http://paste.ee/p/n0z1z
## Additional Info:

N/A

**Comment by QuImUfu** [comment]
1. This is not the full log uploaded via the upload button in the console window.
2. Advanced Spawn Control Mod is for 1.7.10, but you are trying to use it with 1.8, causing this crash.

**Comment by peterix** [comment]
Log is dead, this no longer has any value. No response in a year... closing.
