### ISSUE TITLE
Allocated RAM error

### ISSUE THREAD

**Issue by MrVideo** [MultiMC/MultiMC5#1551]
## System Information

MultiMC version:
0.4.11-751
Operating System:
Windows 10 64 bit
## Summary of the issue or suggestion:

Minecraft doesn't start telling me "Invalid maximum heap size: -Xmx4096m
The specified size exceeds the maximum representable size." even though my computer has 16 GB of RAM installed.
## What should happen:

Minecraft should be launched.
## Steps to reproduce the issue (Add more if needed):
1. Create an instance, go to options and on "Maximum memory allocation" insert the value 4096
2. Launch the instance
## Suspected cause:

I have no clue, on my Mac it used to work every time.
## Logs/Screenshots:

[Log per GitHub.txt](https://github.com/MultiMC/MultiMC5/files/224430/Log.per.GitHub.txt)

**Comment by Heufneutje** [comment]
You probably have 32-bit Java installed. Try installing 64-bit Java and re-running the Java detector in MultiMC.

**Comment by peterix** [comment]
No response in a long time... closing.
