### ISSUE TITLE
MultiMC compatibility error with D3DGear recording software

### ISSUE THREAD

**Issue by elder-sign** [MultiMC/MultiMC5#1554]
System Information
-----------------------------
MultiMC version: Latest

Operating System: winxp 32bit

Summary of the issue or suggestion:
----------------------------------------------
dll conflict with D2DGear recording software

What should happen:
------------------------------
MultiMC should not throw an error every few seconds, the persistence of the errors is such that the program in unable to be closed internally, instead it must be closed through Task Manager and using end process. The error only shows up when D3DGear is also running.

Error Message Pop-Up below

MultiMC.exe - Entry Point Not Found
The procedure entry point _except_handler4_common could not be located in the dynamic link library msvcrt.dll 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install MultiMC

2.Install D3DGear

3. Attempt to run both programs at the same time.

Suspected cause:
---------------------------

D3DGear monopolizing the dll. 

Logs/Screenshots:
----------------------------

![multimc error](https://cloud.githubusercontent.com/assets/17489358/14764015/cdb353e0-0954-11e6-90a1-e6644c48a60d.jpg)

Additional Info:
---------------------------

**Comment by Heufneutje** [comment]
Wouldn't it be their issue in that case? Also, Windows XP is extremely old. Is this reproducable on a modern OS?

**Comment by elder-sign** [comment]
Reproducible on 7 and 8, haven't tried 10, was in contact with the developer of d3dgear and they patched it on their end so that it should work in the future.

**Comment by peterix** [comment]
Well, got nothing to add really...  Only that I couldn't possibly do anything about a hack like that injecting code into MultiMC.
