### ISSUE TITLE
Exception Access Violation Error

### ISSUE THREAD

**Issue by reddvilzz** [MultiMC/MultiMC5#1555]
I keep getting this crash now, but 2 almost 1 week ago everything works just fine. Sometimes the crash is about [nvoglv64.DLL+0x858f24] and sometimes about the one I posted on the log. What can I do to fix this issue?

[https://paste.ee/p/n5SvS]

System Information
-----------------------------
MultiMC version: 0.4.11-751

Operating System: Windows 10 64 bit

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Start FTB Infinity Evolved
2. Play around for a couple of minutes
3. Suddenly Crashed

Suspected cause:
---------------------------
1. Something related to nvidia I guess?
2. Shaders? Before I don't get flickers when using shaders, but recently when I walk I get flickers

**Comment by whitephoenix0** [comment]
That paste link doesn't exist, please rehost it even though I doubt this is an issue with multimc.

**Comment by reddvilzz** [comment]
I've solved the problem and indeed it is nothing to do with multiMC itself. It is because the threaded optimization was on while I used shaders
