### ISSUE TITLE
Exporting tracked FTB instances produces broken packs

### ISSUE THREAD

**Issue by DDzwiedziu** [MultiMC/MultiMC5#1556]
System Information
-----------------------------
MultiMC version: 0.4.11, 0.4.12-develop-725

Operating System: Ubuntu 16.04 LTS

Summary of the issue or suggestion:
----------------------------------------------
MultiMC segfaults when importing a pack exported by itself or another instance.

What should happen:
------------------------------
No segfault

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download The Ferret Buisinnes 0.1.3 from the FTB Launcher

2. Refresh MultiMC

3. Add Translocators 1.1.2.15, Logistic Pipes 0.9.3.114, OptiFine HD U D3, EnderTech 0.3.2.405, update Agricraft to 1.5.0.

4. Export to a zip file (the zip itself is correct)

5. Import the zip in MultiMC (same or another instance).

6. boom 

Suspected cause:
---------------------------
Suspected the version file because of the last message in the log, but it's contents are OK in the zip.

Logs/Screenshots:
----------------------------
    ----SNIP----
        84.816 D copying file "/tmp/MultiMC5-EYbkIM/The Ferret Business/TheFerretBusinessIcon.png"  -  "/home/dzwiedziu/.multimc5/instances/TheFerretBusinessDupa/TheFerretBusinessIcon.png"
        84.816 D copying file "/tmp/MultiMC5-EYbkIM/The Ferret Business/version"  -  "/home/dzwiedziu/.multimc5/instances/TheFerretBusinessDupa/version"
        84.845 W QObject::connect: invalid null parameter
    ./MultiMC: line 93:  6654 Segfault   (core dumped) "${MMC_DIR}/bin/MultiMC" -d "${MMC_DIR}" "$@"

Coredump: https://drive.google.com/file/d/0B8GKLPDelswmSWhEWEhURUF4WHc/view?usp=sharing

Additional Info:
---------------------------

**Comment by peterix** [comment]
I'm not sure if a coredump is useful in this case. I do not have debug symbols.

Can you put the exported pack somewhere instead?

**Comment by DDzwiedziu** [comment]
I'll PM it to you, as posting the link here would in 99% break someone's mod licence.

**Comment by peterix** [comment]
OK... exporting tracked FTB instances is definitely not intended... This simply cannot work and will have to be disabled.

The crash is from FTB instances not creating an update task. Trivial to fix.

You will have to make a copy of the instance in MultiMC first - this separates it from FTB. You should also remove any FTB pack version files and add in normal Forge (see version tab in edit instance).

**Comment by peterix** [comment]
Alright. It is now disabled and the crash is fixed - in the develop build.

You will have to turn the tracked FTB instance into a MultiMC instance by copying it.
