### ISSUE TITLE
modded minecraft instance crash before creating new world

### ISSUE THREAD

**Issue by vadrieriand** [MultiMC/MultiMC5#1557]
System Information
-----------------------------
MultiMC version: 0.4.11-751 win 32

Operating System: windows 10 64 bit

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------
logged in to a new world

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.main menu fine no crash

2. creating new world

3. freeze then crash

Suspected cause:
---------------------------
unkown

Logs/Screenshots:
----------------------------
http://pastebin.com/bZMu9uKs

Additional Info:
---------------------------
this is a my modded minecraft instance

**Comment by TheDoctorsLife** [comment]
Can you provide the full log please?

**Comment by Loetkolben** [comment]
Please upload the complete log using the _"Upload Log"_-Button in the Console Window and give us the link. We need the whole log to help you.

**Comment by vadrieriand** [comment]
nevermind guys , solved it myself it was mine chem , thanks
