### ISSUE TITLE
minor inconvenience

### ISSUE THREAD

**Issue by vadrieriand** [MultiMC/MultiMC5#1558]
## System Information

MultiMC version: 0.4.11-751 32 on win32 bit

Operating System: windows 10 64 bit
## Summary of the issue or suggestion:

mod tab on creative missing
## What should happen:

it should show up
## Steps to reproduce the issue (Add more if needed):

1.-

2.-

3.-
## Suspected cause:

no clue
## Logs/Screenshots:

<a href="http://s1316.photobucket.com/user/vadrieriand/media/github%20help_zpsiqwn2mtp.png.html" target="_blank"><img src="http://i1316.photobucket.com/albums/t614/vadrieriand/github%20help_zpsiqwn2mtp.png" border="0" alt=" photo github help_zpsiqwn2mtp.png"/></a>

log 1
http://pastebin.com/1RTcGvT9

log 2 ( continued from log 1)
http://pastebin.com/5S8r2upD
## Additional Info:

self made modpack

**Comment by deframet** [comment]
Are the other pages blank? Or just the last page?
