### ISSUE TITLE
FTB instances loose icons 0.4.12-develop-778

### ISSUE THREAD

**Issue by KaizenNeko** [MultiMC/MultiMC5#1559]
**MultiMC version:** 0.4.12-develop-778
**Operating System:** Windows 10 version 1511 (build 10586.216)
**Summary of the issue:** With the 0.4.12-develop-778 release all FTB instances revert to default MultiMC icons.

Screenshots:
----------------------------
Build 771:
![screenshot 2016-05-01 18 14 29](https://cloud.githubusercontent.com/assets/1039807/14944672/af1d15d6-0fc8-11e6-82ad-e0bc721d4189.png)

Build 778:
![screenshot 2016-05-01 18 03 47](https://cloud.githubusercontent.com/assets/1039807/14944650/b1a6a64c-0fc7-11e6-90e1-a02795245c29.png)

**Comment by Loetkolben** [comment]
Can confirm for Win7 Pro x64

**Comment by peterix** [comment]
Should be fixed. Reopen if not.
