### ISSUE TITLE
Add White-space stripping.

### ISSUE THREAD

**Issue by Lelahelry** [MultiMC/MultiMC5#1560]
Hello, I have a problem : when I launch Minecraft it crashes and I have this log : 
MultiMC version: 0.4.11-751

https://paste.ee/p/0Dc4K

I don't know what to do, help me please, my operating system is Windows 10 x64.

**Comment by peterix** [comment]
Rename the instance folder so that it doesn't end in a space.

**Comment by Lelahelry** [comment]
Thank you !

Sorry if there are errors, I'm french and I haven't finished learning english.

**Comment by peterix** [comment]
Related to #156

**Comment by peterix** [comment]
So, let's add whitespace stripping :)

**Comment by peterix** [comment]
And, done. Will be in next stable release.
