### ISSUE TITLE
Translation mistake - polish

### ISSUE THREAD

**Issue by mszekiel** [MultiMC/MultiMC5#1561]
## System Information

MultiMC version:  0.4.11.751

Operating System: Windows 10 64-bit
## Summary of the issue or suggestion:

Polish translation mistake on main screen of application, right side menu. "Export instance" is translated as "Edit instance".

It should be "Eksportuj instancję" than "Edytuj instancję".

**Comment by TheDoctorsLife** [comment]
Feel free to send a pr with that fixed and any other errors to [here](https://github.com/MultiMC/MultiMC5-translate)
