### ISSUE TITLE
NEI&TFC Crash

### ISSUE THREAD

**Issue by REUSSofficial** [MultiMC/MultiMC5#1562]
Not Enough Items and TerraFirmaCraft crash. 
I'm trying to look at any recipe and happens crash.
Report:
[crash-2016-05-07_13.23.16-client.txt](https://github.com/MultiMC/MultiMC5/files/253315/crash-2016-05-07_13.23.16-client.txt)
Log:
http://paste.ee/p/6psR8

**Comment by QuImUfu** [comment]
Update TFC and TerraFirmaCraftNEIplugin to their newest versions (or versions fitting to each other).
You should also update MultiMC, it only got better :) (has nothing to do with this crash).

I recreated you pack with all mods updated, you are free to use it (or not to use it ^^).
[Download](http://dl.dropbox.com/s/cu4dw2r5limwai1/tfc%20Modpack.zip)

**Comment by REUSSofficial** [comment]
Thanks!

**Comment by TheDoctorsLife** [comment]
@REUSSofficial Is this fixed?

**Comment by REUSSofficial** [comment]
Yes
