### ISSUE TITLE
Feature Request: Checksums or GPG Signing of Releases

### ISSUE THREAD

**Issue by tanto259** [MultiMC/MultiMC5#1568]
For better security when downloading the releases, it'll be good to verify either SHA1 checksums or even by signing the releases using GPG.

**Comment by peterix** [comment]
You mean releases of MultiMC?

**Comment by tanto259** [comment]
Yes

**Comment by peterix** [comment]
Alright. This likely won't happen with the current build system, site and update repository. I do plan to have general purpose package management included at some point... and these should include both - checksums AND signing.
