### ISSUE TITLE
[JAVA 9] MultiMC crashes when launching game

### ISSUE THREAD

**Issue by BobGamer455** [MultiMC/MultiMC5#1571]
Hello!

I have recently came across an that prevents any instance from launching when using **Java 1.9.0**. I have tested, and found out it's not a minecraft-sided problem,because the game launched without any problems using the official launcher.
I have java 9 Build 118
I am running "**MultiMC 5 - Version 0.4.12-develot-785 on win32**"
I am using _Windows 10 Pro ; version 1511 ; OS build 10586.318 ; x64_
I have an _AMD A10-7800_ CPU; _AMD R7 240_ 2GB GPU; _8 GB DDR3 700Mhz_ RAM
Log from console:  http://pastebin.com/EDimPgGx
I tried all versions from 1.6.4 up to 1.9.4, all give the same crashlog.
I hope you can fix this!

**Comment by QuImUfu** [comment]
Can confirm, this doesn't happen under Linux but it definitely does under Windows 10 32 bit.
Can also confirm that it doesn't happen with the vanilla launcher.

**Comment by peterix** [comment]
This is likely not going to be fixed with the current launcher part.

Requirements:
* Native code launcher part, using JNI to instantiate the JVM
* It needs to be both 32bit and 64bit on linux and win32, regardless of what MultiMC uses
* So, ideally fully static linked and just added to the normal builds

For what else it should do:
https://workflowy.com/s/2EyDMcp7CU#/?q=%23launch-agent%2B
Expand all the bullet points.

**Comment by peterix** [comment]
This also involves changes to user configuration and java detection - we won't be using the executables anymore.

**Comment by MauveCloud** [comment]
Java 9 officially released today, and I ran into this (tried both the "stable" and "development" update channels).  I guess I'll switch MultiMC back to Java 8 for now, but I'll keep an eye on this issue in case this gets fixed.

**Comment by peterix** [comment]
Java 9 is not going to be supported any time soon. It breaks too many things.

**Comment by peterix** [comment]
Curren version (0.6) should have no issues with Java 9 anymore. You will still find out that it doesn't work with mods... so it's sort of useless IMO. Closing.
