### ISSUE TITLE
Code #1 help (think too many mods?)

### ISSUE THREAD

**Issue by SmallEnderman** [MultiMC/MultiMC5#1575]
I wanted to create a own modpack. First i only added the mod witchery for version 1.7.10 and that worked fine, than i added other mods such as thaumcraft, bloodmagic ect and it didn't work after that. it said minecraft was stopped with code 1. Please help me because i badly want to make my own modpack with the support of multimc.

http://paste.ee/p/AsGeY

**Comment by wlhlm** [comment]
> [09:42:55] [main/ERROR]: An error occurred trying to configure the minecraft home at C:\Users\Gaby\Desktop\MultiMC\instances\Smallos\minecraft for Forge Mod Loader
java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit

You are missing CodeChickenCore, which is required by NEI.

**Comment by wlhlm** [comment]
@SmallEnderman Did the above solve it for you? If so, please close this issue.
