### ISSUE TITLE
Java Not Being Detected or Executing

### ISSUE THREAD

**Issue by Jagahkiin2014** [MultiMC/MultiMC5#1578]
System Information
-----------------------------
MultiMC version: 0.4.11-751

Operating System: Windows 10 Home 64-bit

Summary of the issue or suggestion:
----------------------------------------------
When trying to launch any instance, there is a Java error. I've uninstalled and reinstalled Java several times. I've changed the MultiMC Java directory settings and pointed it to javaw.exe and java.exe but it still won't work.

What should happen:
------------------------------
Java should be detected at least.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open the launcher

2. Launch any instance

3. Get Java error

Suspected cause:
---------------------------
N/A

Logs/Screenshots:
----------------------------
![alt text](http://i.imgur.com/8QK8Jcn.png)
![alt text](http://i.imgur.com/lwqDpsD.png)
![alt text](http://i.imgur.com/trNNeU5.png)
![alt text](http://i.imgur.com/CM8V22n.png)

Additional Info:
---------------------------
Using Java runtime 8 update 91 (64-bit)
I've also tried the developmental version of MultiMC

**Comment by peterix** [comment]
Looks like your multimc install is not complete, or has broken file permissions.

You should have these:
![image](https://cloud.githubusercontent.com/assets/203326/15635532/d55b58a6-25e0-11e6-998c-82fa9b85f964.png)


Easiest solution is likely to grab a fresh copy.

**Comment by Jagahkiin2014** [comment]
Yep, that worked. Thank you so much.

**Comment by freshbee1** [comment]
i have that 2 files, but i still cant run it
