### ISSUE TITLE
Optifine 1.9.x won't load as a .jar file in MultiMC (not forge...)

### ISSUE THREAD

**Issue by mdedmon** [MultiMC/MultiMC5#1580]
## System Information

Model Name: iMac
  Model Identifier: iMac14,2
  Processor Name:   Intel Core i7
  Processor Speed:  3.5 GHz
  Number of Processors: 1
  Total Number of Cores:    4
  L2 Cache (per Core):  256 KB
  L3 Cache: 8 MB
  Memory:   32 GB

MultiMC version:
Version 0.4.11-713 on osx64

Operating System:
El Capitan Version 10.11.5
## Summary of the issue or suggestion:

Before version 1.9 of Minecraft & Optifine, you could add the optifine.jar file into the Instance with no trouble. Now, with 1.9.x version of Minecraft & Optifine, when adding any version of 1.9.x of Optifine, the jar file is ignored.
## What should happen:

Create 1.9.4 instance. Edit the instance and select "Add jar mod", point to the 1.9.4 version of Optifine and add it to the instance. 
## Steps to reproduce the issue (Add more if needed):
1. Download the "OptiFine 1.9.4 HD U B4"
2. Create MultiMC Instance using Minecraft 1.9.4
3. Edit the instance, select "Add jar mod"
4. Find the jar mod you downloaded in step 1.
5. Save and run the instance.
6. Optifine is not running.
## Suspected cause:

Not sure - There is a section in the log file that might point to the issue.  (entire log file is below)
Jar Mods:
  OptiFine_1.9.4_HD_U_B4 (2) (dc4b12e1-de2a-4b2a-8fac-daafc3f34eac.jar)

Params:
  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, /Applications/MultiMC/MultiMC.app/Contents/MacOS/instances/1.9 Pre4/minecraft, --assetsDir, /Applications/MultiMC/MultiMC.app/Contents/MacOS/assets, --assetIndex, 1.9, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userType, mojang, --versionType, custom]
## Logs/Screenshots:

MultiMC Log:
MultiMC version: 0.4.11-713

Minecraft folder is:
instances/1.9 Pre4/minecraft

Java path is:
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java

Java Arguments:
[-XX:+UseConcMarkSweepGC, -XX:+CMSIncrementalMode, -XX:-UseAdaptiveSizePolicy, -Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -Xdock:icon=icon.png, -Xdock:name="MultiMC: 1.9", -Xms2048m, -Xmx8192m, -Duser.language=en, -jar, /Applications/MultiMC/MultiMC.app/Contents/MacOS/jars/NewLaunch.jar]

Minecraft process ID: 1353

Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
Using onesix launcher.

Main Class:
  net.minecraft.client.main.Main

Native path:
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/instances/1.9 Pre4/natives

Traits:
  []

Libraries:
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/mojang/netty/1.6/netty-1.6.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/mojang/authlib/1.5.22/authlib-1.5.22.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/mojang/realms/1.8.19/realms-1.8.19.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/it/unimi/dsi/fastutil/7.0.12_mojang/fastutil-7.0.12_mojang.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/instances/1.9 Pre4/minecraft.jar

Jar Mods:
  OptiFine_1.9.4_HD_U_B4 (2) (dc4b12e1-de2a-4b2a-8fac-daafc3f34eac.jar)

Params:
  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, /Applications/MultiMC/MultiMC.app/Contents/MacOS/instances/1.9 Pre4/minecraft, --assetsDir, /Applications/MultiMC/MultiMC.app/Contents/MacOS/assets, --assetIndex, 1.9, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userType, mojang, --versionType, custom]

Window size: 1920 x 1080

Preparing native libraries...
Extracting jinput-platform-2.0.5-natives-osx.jar
Extracting lwjgl-platform-2.9.1-natives-osx.jar

[23:57:38] [Client thread/INFO]: Setting user: <PROFILE NAME>
[23:57:38] [Client thread/INFO]: LWJGL Version: 2.9.1
[23:57:39] [Client thread/INFO]: Reloading ResourceManager: Default, ChromaHills128x-1.9-v.1.zip
[23:57:39] [Sound Library Loader/INFO]: Starting up SoundSystem...
[23:57:39] [Thread-5/INFO]: Initializing LWJGL OpenAL
[23:57:39] [Thread-5/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
2016-05-29 23:57:39.739 java[1353:228367] 23:57:39.739 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
[23:57:39] [Thread-5/INFO]: OpenAL initialized.
[23:57:40] [Sound Library Loader/INFO]: Sound engine started
[23:57:40] [Client thread/WARN]: Texture minecraft:textures/blocks/cake_bottom.png with size 120x120 limits mip level from 4 to 3
[23:57:40] [Client thread/WARN]: textures: dropping miplevel from 4 to 3, because of minimum power of two: 8
[23:57:40] [Client thread/INFO]: Created: 8192x4096 textures-atlas
Clipboard copy at: 29 May 2016 23:58:18 -0600

**Comment by QuImUfu** [comment]
Optifine does not support loading as jar mod anymore, you have to install it via [this](https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine) way.
I dont know why there is the:
```json
        {
            "name": "org.multimc.hacks:OptiFineHack:1",
            "MMC-absoluteUrl": "http://files.multimc.org/downloads/OptiFineHack-1.jar"
        }
...
        "+tweakers": [ "org.multimc.hacks.OptiFineHackTweaker" ]
```

part in the file.

This does work, too:
```json
{
    "+libraries": [
        {
            "insert": "prepend",
            "name": "net.minecraft:launchwrapper:1.12"
        },
        {
            "insert": "prepend",
            "MMC-depend": "hard",
            "MMC-hint": "local",
            "name": "optifine:OptiFine:1.9.4_HD_U_B4"
        }
    ],
    "+tweakers": [ "optifine.OptiFineTweaker" ],
    "fileId": "optifine.OptiFine",
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "mcVersion": "1.9.4",
    "name": "OptiFine",
    "order": 100,
    "version": "1.9.4_HD_U_B4"
}
```
You still need to copy and rename the OptiFine_1.9.4_HD_U_B4.jar to <MMC>/libraries/optifine/OptiFine/1.9.4_HD_U_B4/OptiFine-1.9.4_HD_U_B4.jar

**Comment by robotbrain** [comment]
Extract the optifine jar, there is another one inside that works as a jar mod.

**Comment by peterix** [comment]
The part you omitted fixes some bugs. Earlier 1.8.9 and 1.9 versions do not work without it.

**Comment by Eudaldca** [comment]
@mdedmon You have to extract optifine (double click the jar file, extract) before adding it as a jar mod. That's how I currently am using it.
