### ISSUE TITLE
My skin dosent work,Even when Im online in my world

### ISSUE THREAD

**Issue by ErfanTZ** [MultiMC/MultiMC5#1584]
## System Information

MultiMC version:0.4.11-751

Operating System:PC
## Summary of the issue or suggestion:

my skin wont work,Even though Im online
## What should happen:

appearing my skin in my worlds
## Steps to reproduce the issue (Add more if needed):

1.

2.

3.
## Suspected cause: Don't know

Logs/Screenshots:
![2016-05-24_11 00 51](https://cloud.githubusercontent.com/assets/19792812/15848859/91e767a2-2ca4-11e6-87af-5f61b0a42a4c.png)

---

**Comment by QuImUfu** [comment]
What Minecraft version/mods are you using?
I can't reproduce in Vanilla 1.9.4, 1.10-pre2, 1.7.10, 1.8.9 on my Linux and on my Windows PC.
My skin gets properly downloaded again when i remove the skin folder in assets, too.

**Comment by ErfanTZ** [comment]
I use all the version for mods. But I use some of the versions on playing and downloading mapsIn conclusion my skin isnt appering with mods and without mods

Sent from Yahoo Mail on Android 
 
  On Wed, 8 Jun, 2016 at 8:14 am, QuImUfu<notifications@github.com> wrote:   
What Minecraft version/mods are you using?
I can't reproduce in Vanilla 1.9.4, 1.10-pre2, 1.7.10, 1.8.9 on my Linux and on my Windows PC.
My skin gets properly downloaded again when i remove the skin folder in assets, too.

**Comment by peterix** [comment]
Hm. Well, I can't really help you with that. Couldn't then, can't now.

As of now, skins are only correctly working (without modding the game) in Minecraft 1.7 and above.
