### ISSUE TITLE
MultiMC not attaching cout to the console.

### ISSUE THREAD

**Issue by GenuineSounds** [MultiMC/MultiMC5#1586]
## System Information

MultiMC v5 0.4.11-751
Windows 10
## Summary of the issue or suggestion:

CMD not displaying cout on Windows.
## Suspected cause:

Application configuration with Visual Studio.
## Logs/Screenshots:

![Screenshot](https://cloud.githubusercontent.com/assets/945942/15894538/3a6ff0a6-2d3b-11e6-94df-23e47ebc68c8.png)

**Comment by peterix** [comment]
This has been fixed a long time ago.
