### ISSUE TITLE
Mirror Server in China

### ISSUE THREAD

**Issue by cqjjjzr** [MultiMC/MultiMC5#1588]
hi there.
as you talked in #1317 , we need a mirror server in china. recently I built a server and it's now avaliable.
so if you have idea to work on that, you can email me cqjjjzr@126.com

(http on 80 port may be unavaliable)

**Comment by peterix** [comment]
I've seen you on IRC, but you never stay around long enough. This is probably better...

So far, I have no idea what to put there - MultiMC uses the official Mojang/Forge/etc. servers.

**Comment by peterix** [comment]
I'd say start with the things that are the slowest when downloading in China.

**Comment by cqjjjzr** [comment]
- First I must admit. Everything is slow.
- Structure the system? OK. Just build a server program, it gets data from servers of Mojang, Forge, LL etc. Then, make a protocol or format to let MMC Client can read them. Just like a mirror Server.
- Just a interface can MMC download things instead of offical servers.
I started to build mirror program. but you still need to add interfaces to resolve my protocol.

**Comment by peterix** [comment]
Current Mojang metadata mirror scripts are here:
https://github.com/MultiMC/mojangversions

So:
* start with Mojang data
    * use the metadata checker scripts to walk through the metadata and collect all the data
    * create a viable mirror of it
    * adapt the metadata to point to a mirror

**Comment by cqjjjzr** [comment]
Well, I started write a library to let launchers parse the mirror link.
details at [https://github.com/cqjjjzr/MinecraftMirrorClient](url)

**Comment by peterix** [comment]
Hello, I'm just going to use this, because I don't know how to talk to you otherwise.

No you are not banned... I'm just busy. You would notice if you were banned because you wouldn't be able to join the channel.

It would be better if you had an IRC bouncer. Or we need to switch to some other way of communication. Can you use the discord server? It has persistent history, unlike raw IRC.

**Comment by cqjjjzr** [comment]
well... The Mojang server & client is all completed. I'm working on Forge and LiteLoader.

**Comment by peterix** [comment]
Closing because I'm removing/moving all feature suggestions and ideas to a different place.
