### ISSUE TITLE
Very, very slow on Linux

### ISSUE THREAD

**Issue by KeepOnDigging** [MultiMC/MultiMC5#159]
Hi guys,

Thanks for creating this fantastic launcher. I'm just loving it on my Mac and PC.

But today I installed it on my Linux box, and it's just terribly slow.

Like, I click Accounts and it takes 20 seconds for the menu to pop up. Then another 20 seconds to select add. Then when the window comes up, it takes another 20 seconds for it to detect my keystrokes. When it does detect them, it enters the whole email address in one go. Then the password, same thing, another 20 seconds. Click Save… you guessed it, another 20 seconds.

After about a minute, I see an error message saying Yggdrasil failed.

Linux box is running a fully updated Centos 6.

Nothing odd is showing up in the console, system shows no load or other strange issues. Other apps are running fine while this is happening.

Any clues would be appreciated, because I would love to have MultiMC running on this box! I'm happy to do any testing and debugging you are willing to walk me through :)

Thanks again for this great utility!

KeepOnDigging!

**Comment by peterix** [comment]
Absolutely not interested in supporting RHEL here. That belongs on servers, not desktops.

However, if you are still interested, the current 'develop' and 'unstable' branches put timestamps in the log files (starting at 0, for the time when MultiMC started).

A log from the current version would help.

**Comment by KeepOnDigging** [comment]
The machine is a media server, file server and in-house Minecraft server, so CentOS is an appropriate OS. But it sits in my living room so it also runs the standard suite of desktop applications.

The dependencies of the latest MultiMC are beyond what I have available on that machine. But when I rebuild it I'll try MultiMC again and let you know how it goes.

**Comment by peterix** [comment]
Yeah... we use quite bleeding-edge stuff compared to the usual server setup :) Latest Qt5?

Current linux builds are done on Ubuntu 12.04

**Comment by KeepOnDigging** [comment]
I guess I could set up Ubuntu on a VPS.

One of the advantages of running a proper server OS: rock solid virtualisation.

**Comment by peterix** [comment]
I would hope that whatever issue there was is now resolved. Then again, hard to say.

Which version of CentOS this is?

**Comment by KeepOnDigging** [comment]
CentOS 6.5, with a bunch of additions and upgrades to support the HTPC. Which means upgrading it will be more of a rebuild.

**Comment by peterix** [comment]
Replicated, but the amount of hoops you have to jump through to even get it to run on ancient CentOS/RHEL is ridiculous.

I'd suggest using a more up-to-date and desktop oriented OS.

Won't fix.

**Comment by KeepOnDigging** [comment]
Adding some info for completeness.

I installed Ubuntu on this machine and MultiMC runs well. But minecraft doesn't, 6 fps and lock ups due to some incompatibility in the OpenGL stack.

I also installed CentOS7, and MultiMC runs well (after disabling an included library) and Minecraft also runs well (50 fps and no crashes in direwolf20 pack).

Thanks again for MultiMC, it makes managing multiple profiles and mod packs so easy :)

**Comment by peterix** [comment]
Hmm. It sucks that you can't have both without messing around with the libraries...

Which library is it?

**Comment by peterix** [comment]
Is it one of the xcb libraries?

**Comment by KeepOnDigging** [comment]
Yes, I just deleted libxcb.so.1 and it works fine.
If you want to address this problem, I guess I should start a new issue.
I was really just updating this issue so people know what their best options are for Minecraft/MultiMC on Linux.
