### ISSUE TITLE
MultiMC is missing libraries

### ISSUE THREAD

**Issue by samuraiworrior111** [MultiMC/MultiMC5#1591]
System Information
-----------------------------
MultiMC version: Linux 32-bit 

What should happen:
------------------------------
Runs through terminal to open MultiMC

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download MultiMC

2. Extract MultiMC

3. Attempt to open through terminal

Suspected cause:
---------------------------
missed downloading libraries

Logs/Screenshots:
----------------------------
Error: MultiMC is missing the following libraries that it needs to work correctly:
	libGL.so.1, libICE.so.6, libSM.so.6, libX11-xcb.so.1, libX11.so.6, libXau.so.6, libXdmcp.so.6, libXi.so.6, libXrender.so.1, libfontconfig.so.1, libfreetype.so.6, libglib-2.0.so.0, libgobject-2.0.so.0, libz.so.1, 
Please install them from your distribution's package manager.

Hint (please apply common sense): 

Additional Info:
---------------------------

**Comment by peterix** [comment]
You have to have those on your system.

**Comment by peterix** [comment]
What distro is this? Do you have X11 installed?

**Comment by samuraiworrior111** [comment]
Im brand new at this i dont know what the distro is and i dont this so.

**Comment by samuraiworrior111** [comment]
Would it be better if i just tried using the 64 version?

**Comment by peterix** [comment]
type `uname -a` in the terminal and tell me what it says

**Comment by wlhlm** [comment]
Open up a terminal and run the following two commands and paste the output here:
```
cat /etc/os-release
```
```
uname -a
```

**Comment by samuraiworrior111** [comment]
Linux localhost 3.10.18 #1 SMP Thu May 12 00:16:56 PDT 216 x86_64 x86_64 x86_64 GNU/Linux

**Comment by samuraiworrior111** [comment]
and with cat it says no such directory

**Comment by samuraiworrior111** [comment]
Linux localhost 3.10.18 #1 SMP Thu May 12 00:16:56 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by peterix** [comment]
You should use thebit version.

**Comment by samuraiworrior111** [comment]
ill try it

**Comment by samuraiworrior111** [comment]
I guess 32 doesnt like to work, its fine now. Thank you so much!
