### ISSUE TITLE
Code - 1 Error

### ISSUE THREAD

**Issue by GeneralBaconator1324** [MultiMC/MultiMC5#1592]
MultiMC version: 0.4.11-751Minecraft folder is:instances/My Modpack/minecraftJava path is:C:/ProgramData/Oracle/Java/javapath/java.exeJava Arguments:[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx2048m, -Duser.language=en, -jar, C:/Users/AriazFam/Desktop/MultiMC/jars/NewLaunch.jar]Minecraft process ID: 3476Using onesix launcher.Main Class:  net.minecraft.client.main.MainNative path:  C:/Users/AriazFam/Desktop/MultiMC/instances/My Modpack/nativesTraits:  []Libraries:  C:/Users/AriazFam/Desktop/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/com/google/guava/guava/15.0/guava-15.0.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar  C:/Users/AriazFam/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar  C:/Users/AriazFam/Desktop/MultiMC/versions/1.7.10/1.7.10.jarParams:  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, C:/Users/AriazFam/Desktop/MultiMC/instances/My Modpack/minecraft, --assetsDir, C:/Users/AriazFam/Desktop/MultiMC/assets, --assetIndex, 1.7.10, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {}, --userType, mojang]Window size: 854 x 480Preparing native libraries...Extracting twitch-platform-5.16-natives-windows-64.jarExtracting twitch-external-platform-4.5-natives-windows-64.jarExtracting jinput-platform-2.0.5-natives-windows.jarExtracting lwjgl-platform-2.9.1-natives-windows.jar[14:18:21] [main/INFO]: Setting user: <PROFILE NAME>[14:18:21] [main/INFO]: (Session ID is token:<ACCESS TOKEN>:<PROFILE ID>)[14:18:22] [Client thread/INFO]: LWJGL Version: 2.9.1[14:18:22] [Client thread/ERROR]: Couldn't set pixel formatorg.lwjgl.LWJGLException: Pixel format not accelerated  at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.1.jar:?]  at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.1.jar:?] at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252) ~[lwjgl-2.9.1.jar:?]   at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.1.jar:?] at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.1.jar:?]   at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.1.jar:?]   at bao.ag(SourceFile:327) [1.7.10.jar:?]    at bao.f(SourceFile:713) [1.7.10.jar:?] at net.minecraft.client.main.Main.main(SourceFile:148) [1.7.10.jar:?]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?] at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]  at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?] at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]---- Minecraft Crash Report ----// Hi. I'm Minecraft, and I'm a crashaholic.Time: 6/14/16 2:18 PMDescription: Initializing gameorg.lwjgl.LWJGLException: Pixel format not accelerated   at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)   at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)  at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)    at org.lwjgl.opengl.Display.createWindow(Display.java:306)  at org.lwjgl.opengl.Display.create(Display.java:848)    at org.lwjgl.opengl.Display.create(Display.java:757)    at org.lwjgl.opengl.Display.create(Display.java:739)    at bao.ag(SourceFile:340)   at bao.f(SourceFile:713)    at net.minecraft.client.main.Main.main(SourceFile:148)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)  at java.lang.reflect.Method.invoke(Unknown Source)  at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)   at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)    at org.multimc.EntryPoint.listen(EntryPoint.java:170)   at org.multimc.EntryPoint.main(EntryPoint.java:54)A detailed walkthrough of the error, its code path and all known details is as follows:----------------------------------------------------------------------------------------- Head --Stacktrace:   at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)   at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)  at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)    at org.lwjgl.opengl.Display.createWindow(Display.java:306)  at org.lwjgl.opengl.Display.create(Display.java:848)    at org.lwjgl.opengl.Display.create(Display.java:757)    at org.lwjgl.opengl.Display.create(Display.java:739)    at bao.ag(SourceFile:340)-- Initialization --Details:Stacktrace:    at bao.f(SourceFile:713)    at net.minecraft.client.main.Main.main(SourceFile:148)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)  at java.lang.reflect.Method.invoke(Unknown Source)  at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)   at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)    at org.multimc.EntryPoint.listen(EntryPoint.java:170)   at org.multimc.EntryPoint.main(EntryPoint.java:54)-- System Details --Details:  Minecraft Version: 1.7.10   Operating System: Windows 10 (amd64) version 10.0   Java Version: 1.8.0_92, Oracle Corporation  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 938160136 bytes (894 MB) / 1029177344 bytes (981 MB) up to 1908932608 bytes (1820 MB)   JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx2048m    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0  Launched Version: MultiMC5  LWJGL: 2.9.1    OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.  GL Caps:    Is Modded: Probably not. Jar signature remains and client brand is untouched.   Type: Client (map_client.txt)   Resource Packs: []  Current Language: ~~ERROR~~ NullPointerException: null  Profiler Position: N/A (disabled)   Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used Anisotropic Filtering: Off (1)#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\AriazFam\Desktop\MultiMC\instances\My Modpack\minecraft\crash-reports\crash-2016-06-14_14.18.23-client.txtProcess exited with code -1.MultiMC: Log upload triggered at: 14 Jun 2016 14:18:58 -0500

**Comment by peterix** [comment]
Let me guess: you have an intel integrated GPU. Something like the HD2000 or HD3000?

If so, you shouldn't be using Windows 10, because it's not supported there.

And if so, you can work around the issue by using Java older that 8u60

**Comment by GeneralBaconator1324** [comment]
It says its a Intel(R) Pentuim(R) CPU G620T

**Comment by peterix** [comment]
If you use an older integrated Intel GPU (HD2000, HD3000), you will have to use an older version of Java.

Either one of those should work:
* https://files.multimc.org/downloads/jre-8u51-windows-x64.zip (64-bit)
* https://files.multimc.org/downloads/jre-8u51-windows-i586.zip (32-bit)

Download it, extract it into the MultiMC folder so it shows up like this:
![image](https://cloud.githubusercontent.com/assets/203326/24775694/31ee8d8a-1b1e-11e7-81d5-eff24add7de2.png)

Then set it up in MultiMc like this:
![image](https://cloud.githubusercontent.com/assets/203326/24775746/5c45fb22-1b1e-11e7-8615-e9ba6d667d7f.png)

Obviously only on Windows 10 :)

If you want the full background about this issue, see:
<details>
https://github.com/LWJGL/lwjgl/issues/119
https://github.com/MultiMC/MultiMC5/issues/1276 (and many other)

I tried contacting Intel about it, they said they will not fix their drivers because the hardware is unsupported on Windows 10:
http://www.intel.com/content/www/us/en/support/graphics-drivers/000005526.html
And Microsoft got an another person to boost their Windows 10 numbers, even though the hardware is not supported properly there.
</details>
