### ISSUE TITLE
Ever since updating to windows 10, i just keep getting this error. Anyone know how to help?

### ISSUE THREAD

**Issue by clufs** [MultiMC/MultiMC5#1597]
## System Information

MultiMC version:
5
Operating System:
Windows 10
Summary of the issue or suggestion:
Can't launch since I updated to windows 10

What should happen:
Should launch normally

Suspected cause:
Windows 10

Logs/Screenshots:
http://paste.ee/p/pmNMX

**Comment by Heufneutje** [comment]
```
[21:57:47] [Client thread/ERROR]: The following problems were captured during this phase
[21:57:47] [Client thread/ERROR]: Caught exception from MoCreatures
java.lang.RuntimeException: Unknown character ']
```

Your version of MoCreatures seems broken. Remove it or update it.

**Comment by peterix** [comment]
Or its config file is broken.
