### ISSUE TITLE
Periodic crash issue with modpack instance brought over from ATLauncher

### ISSUE THREAD

**Issue by sp823** [MultiMC/MultiMC5#1598]
It takes me multiple attempts to start the modpack. There are no changes from one attempt to the next yet sometimes it fails and sometimes it succeeds and the failure point is not always in the same place. Everything works fine every time when loading the instance from ATLauncher.

Crash 1:
Minecraft log:
http://pastebin.com/hSG7mPcJ
Java crash log:
http://pastebin.com/5nJAErS3

Crash 2:
Minecraft log:
http://pastebin.com/arjnCaug
Java crash log:
http://pastebin.com/dgWU7hVz

Success (attempt 3):
Minecraft log:
http://pastebin.com/cTiPAp72

**Comment by peterix** [comment]
Looks like a graphics driver bug related to the Forge splash screen:
```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 4811  org.lwjgl.opengl.GL11.nglClear(IJ)V (0 bytes) @ 0x00007ffad8b12644 [0x00007ffad8b12600+0x44]
J 10310 C2 org.lwjgl.opengl.GL11.glClear(I)V (19 bytes) @ 0x00007ffad920de94 [0x00007ffad920de40+0x54]
j  cpw.mods.fml.client.SplashProgress$3.run()V+136
```

This is usually a problem when the driver can't handle rendering from multiple threads.

So, look for the `splash.properties` file in the instace's config folder and disable the splash screen in it.
