### ISSUE TITLE
Feature Request: allow the adding of custom light sources to the dynamic lights module

### ISSUE THREAD

**Issue by patrickclank9** [MultiMC/MultiMC5#1601]
Perhaps just a config option where we can list other mod items and a light intensity value.
Also perhaps an option to make all enchanted items glow.

**Comment by escman1999** [comment]
._. what does this have to do with the multimc launcher?

**Comment by gdude2002** [comment]
Yeah, this has nothing to do with MultiMC. Find the GitHub for the mod you're thinking of.

**Comment by peterix** [comment]
Hmm... it's an interesting idea...

Mod configuration is already in the big idea tree on workflowy, but the mod is also configured by **deleting stuff from inside its jar**:
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/1.8.9/DynamicLights/resources/readme.txt

Existing related ideas and issues:
* https://github.com/MultiMC/MultiMC5/issues/1200
* https://workflowy.com/s/2EyDMcp7CU#/0bee775587ce

Closing, moved to workflowy.

**Comment by patrickclank9** [comment]
Oh whoops. This was ment for Optifine's dynamic lights addon. I must have just clicked on the wrong tab and submitted it here. But apparently it was interpreted as another idea, so yay?

**Comment by peterix** [comment]
And for a completely different mod...

Yay :D
