### ISSUE TITLE
Making a ModPack.

### ISSUE THREAD

**Issue by Cardboard2** [MultiMC/MultiMC5#1602]
Recently I've been trying to make a modpack for me and my brother to play on. I've came across an error with Buildcraft Combustion Engines, but when i look at the crash report i can't see anything wrong with it. I was hoping someone could help.

[crash-2016-06-19_13.16.30-client.txt](https://github.com/MultiMC/MultiMC5/files/322080/crash-2016-06-19_13.16.30-client.txt)

Sorry forgot to say that this error occurs only when i open you Combustion Engines inventory.

**Comment by Cardboard2** [comment]
Sorry forgot to say that this error accurs only when

**Comment by peterix** [comment]
That version of buildcraft is not compatible with latest Forge for 1.7.10.

At some point in the 1.7.10 branch, Forge changed how fluids work. So mods generally expects one or the other behaviour. 

You will have to update buildcraft, or downgrade Forge. If you downgrade, it might break other mods.

**Comment by Cardboard2** [comment]
ok i'll try that now. Thanks

**Comment by Cardboard2** [comment]
Thank you. It worked
