### ISSUE TITLE
Asset index error without any details.

### ISSUE THREAD

**Issue by kreynes** [MultiMC/MultiMC5#1603]
I know there has been similar errors, but mine provides no details as to what exactly failed with this damn asset index.
http://paste.ee/p/OSEjs

Windows 10.
Java 8u91.

**UPDATE:** Digging into assets/indexes/1.7.10.json i have found that the file contains an html markup of my ISP, saying that content is blocked in the Russian Federation. Any way to work around that without a VPN?

**UPDATE2:** So, https://s3.amazonaws.com is blocked by my isp. how gr8.

**Comment by peterix** [comment]
Most likely not...

At some point, we'll have the ability to use mirrors, but it's not there yet... So, VPN it is.

The next stable version should check the file for correctness instead of assuming that whatever the server sent back is OK. So, it will be apparent that the file was bad.

**Comment by peterix** [comment]
Blocking s3 ... that's ridiculous. It's a really generic 'cloud' storage solution that a lot of things use.

**Comment by kreynes** [comment]
@peterix It's just a shame i need to run it through proxy every time, since it's always fetching that...:<
Yeah. The whole Russian Federation is ridiculous. I was outraged by that fact.

**Comment by kreynes** [comment]
@peterix Is there a way to reach your out of github? im getting more crashes. Your help would be highly appreciated.

**Comment by peterix** [comment]
The MultiMC IRC or discord... but most likely IRC

**Comment by peterix** [comment]
it's #MultiMC on esper.net

http://webchat.esper.net/?nick=&channels=MultiMC <- IRC webchat
