### ISSUE TITLE
Exited with code -1.

### ISSUE THREAD

**Issue by kreynes** [MultiMC/MultiMC5#1604]
http://pastebin.com/XkjKSuH6

I'd assume this points me here https://github.com/MultiMC/MultiMC5/blob/e32d7238c9f76b86e2738e8cd2cfae5876cb6992/libraries/launcher/org/multimc/EntryPoint.java#L54

And with the fact that it all has to do with a listener, might it be because I'm using a proxy (my ISP blocks some website, thus i cannot fetch the assets/indexes)?

**Comment by peterix** [comment]
Delete `C:/Minecraft/MultiMC/versions/1.7.10/1.7.10.jar`

**Comment by kreynes** [comment]
@peterix I love you.

**Comment by TheDoctorsLife** [comment]
@kreynes Is this issue fixed? If so please close it.

**Comment by peterix** [comment]
Well, I'll just assume it is.
