### ISSUE TITLE
MultiMC Crash; 1st Run and subsequent; Exit code -1

### ISSUE THREAD

**Issue by pigrocks426** [MultiMC/MultiMC5#1607]
## System Information

MultiMC version: 0.4.11-751 on win32

Operating System: Windows 10 Pro (x86) Ver. 1511 Build 10586.420 on Intel Core 2 Duo E8500 (x64)
## Summary of the issue or suggestion:

New install of MultiMC5 crashes on first and subsequent runs of any instance (tested for all regular release versions 1.0 - 1.10.2), returning exit code -1 . No mods or changes to default configurations have been applied.
## What should happen:

Presumably, typical vanilla functionality should be experienced.
## Steps to reproduce the issue (Add more if needed):
1. Downloaded/unpacked MMC to C:\Program Files\MultiMC; Ran MultiMC.exe .
2. Successfully added default profile; Created new instance of vanilla 1.10.2 .
3. Choosing "Play" or "Play Offline" starts loading process, then crashes with exit code -1 . The same crash report happens for any unmodified instance of any regular release from 1.0 - 1.10.2 .
## Suspected cause:

Unknown. Windows 10, maybe?
## Logs/Screenshots:

http://paste.ee/p/pi99o
## Additional Info:

Other details:
- Java Ver. 8 Update 91, Build 1.8.0_91-b15
- Intel Q35 Express Chipset native video
- 2.99 usable of 8GB RAM installed (don't know why x86 was chosen instead of x64)
- System is clean of malware/viruses/rootkits

This is my first time configuring MultiMC on a machine running Windows 10 OS. I have used it before, successfully, on various other hardware/OS configurations. The system's owner ok'd reverting back to Win 7 Pro by clean install, but I was trying to avoid the work (doing this for a friend; can't convince them to switch to Gnu/Linux). I'm not presently an experienced coder, but I have a moderate technical background. I will self-educate where necessary in order to fix this, and maybe engage in coding again if needed. Any help given is much appreciated. Thanks! :)

**Comment by peterix** [comment]
See: https://github.com/MultiMC/MultiMC5/issues/1606
