### ISSUE TITLE
Authentication operation cancelled

### ISSUE THREAD

**Issue by Mkidman** [MultiMC/MultiMC5#1611]
System Information
-----------------------------
MultiMC version: 0.4.11-751

Operating System: Win 7

Summary of the issue or suggestion:
----------------------------------------------
I just installed MultiMC but it does not let me add my account.  It says "Authenticating: Sending request..." and then after a bit it says "Authentication operation cancelled."

What should happen:
------------------------------
It should let me add my account

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. attempt to add account...

2.

3.

Suspected cause:
---------------------------
I suspected a firewall issue but I temp disabled windows firewall and nothing changed when i tried again

Logs/Screenshots:
----------------------------
    0.007 D MultiMC 5, (c) 2013-2015 MultiMC Contributors
    0.008 D Version                    :  "0.4.11-751"
    0.008 D Git commit                 :  "a3cd3d5ff18215a475ed6b5f231f3f02ccd668f7"
    0.008 D Git refspec                :  "refs/heads/stable"
    0.008 D Work dir before adjustment :  "C:/Users/Kidman/Desktop/MultiMC"
    0.008 D Work dir after adjustment  :  "C:/Users/Kidman/Desktop/MultiMC"
    0.008 D Adjusted by                :  "Command line C:/Users/Kidman/Desktop/MultiMC"
    0.008 D Binary path                :  "C:/Users/Kidman/Desktop/MultiMC"
    0.008 D Application root path      :  "C:/Users/Kidman/Desktop/MultiMC"
    0.011 D Detected default console font: "Courier" , substitutions: ""
    0.012 D FTB Launcher paths: "C:/Users/Kidman/AppData/Roaming/ftblauncher" and "C:/Users/Kidman/AppData/Local/ftblauncher"
    0.012 D Attempting to read "C:/Users/Kidman/AppData/Roaming/ftblauncher/ftblaunch.cfg"
    0.012 W Couldn't open "C:/Users/Kidman/AppData/Roaming/ftblauncher/ftblaunch.cfg" : "The system cannot find the path specified."
    0.012 W This is perfectly normal if you don't have FTB installed
    0.013 D Your language is "en"
    0.022 W libpng warning: iCCP: known incorrect sRGB profile
    0.034 D Started watching  "C:/Users/Kidman/Desktop/MultiMC/icons"
    0.035 D Instance path              :  "instances"
    0.035 D Loading Instances...
    0.036 D Loading accounts...
    0.036 D Detecting proxy settings...
    0.036 D Using no proxy is an option!
    0.036 D Downloading Translations Index...
    0.036 D "Translations Index"  started.
    0.070 D "Status JSON"  started.
    0.074 D Loading builtin version list.
    0.076 W Blacklisted legacy version ignored:  "rd-160052"
    0.488 D Reloading news.
    0.488 D "News RSS Feed"  started.
    0.488 D Checking for updates.
    0.488 D Channel list isn't loaded yet. Loading channel list and deferring update check.
    0.488 D Loading the channel list.
    0.488 D "Update System Channel List"  started.
    0.488 D "Checking for notifications"  started.
    0.612 D Downloading  "http://files.multimc.org/translations/index"
    0.617 D Downloading  "http://status.mojang.com/check"
    0.617 D Downloading  "http://multimc.org/rss.xml"
    0.617 D Downloading  "http://files.multimc.org/update/win32/channels.json"
    0.618 D Downloading  "http://files.multimc.org/notifications.json"
    5.140 D Loading the channel list.
    5.140 D "Update System Channel List"  started.
    5.259 D Downloading  "http://files.multimc.org/update/win32/channels.json"
   49.301 C Task failed:  "Authentication operation cancelled."
   52.042 D Paged dialog close requested
   52.044 D Paged dialog close approved
   52.044 D Paged dialog geometry saved

Additional Info:
---------------------------
Sorry, it would not let me use the upload log tool

**Comment by tarix29** [comment]
This is probably because you used mcleaks. This is not a problem with MultiMc; you would get a similar error with any other Minecraft Launcher. You can fix it by opening %SystemRoot%\System32\drivers\etc\hosts and removing everything with mojang in it.
