### ISSUE TITLE
Does MultiMC apply proxy arguments to Minecraft if a proxy is specified in the launcher?

### ISSUE THREAD

**Issue by daniel-dsouza** [MultiMC/MultiMC5#1612]
## System Information

MultiMC version: 0.4.11-703

Operating System: Ubuntu 16.04 

Java Version:
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
## Summary of the issue or suggestion:

When connecting through a http or socks proxy, the MultiMC launcher is able to download the files it needs. However, when starting up pack with a mod that does an update check (e.g. Optifine, COFH, Mekanism), Forge will get stuck after throwing a connection error.
## What should happen:

I would hope that MultiMC is able to set proxy variables when launching Minecraft, so that the executable is aware that it needs to use a proxy
## Steps to reproduce the issue (Add more if needed):
1. Add a proxy to MultiMC
2. Launch a pack with a mod that connects to the internet
3. Wait for an error
## Suspected cause:

MultiMC is not adding proxy arguments at launch.
## Additional Info:

```
java.net.ConnectException: Connection timed out
...
```

```
[Thread-12/ERROR]: An error occured while connecting to URL 'https://dl.dropbox.com/u/90411166/Mod%20Versions/Mekanism.txt.'
```

**Comment by nikhiljha** [comment]
For ease of implementation:

HTTP Proxies:
-Dhttp.proxyHost=[HOST] -Dhttp.proxyPort=[PORT] -Dhttp.nonProxyHosts=127.0.0.1|localhost

HTTPS Proxies:
-Dhttps.proxyHost=[HOST] -Dhttps.proxyPort=[PORT] -Dhttps.nonProxyHosts=127.0.0.1|localhost

Socks (V5) Proxies:
-DsocksProxyHost=[HOST] -DsocksProxyPort=[PORT] -Djava.net.socks.username=[USER] -Djava.net.socks.password=[PASS]

Of course with MultiMC you can always add these manually if you're having this issue.
