### ISSUE TITLE
MultiMC5 crashing instantly on launch - macOS

### ISSUE THREAD

**Issue by lutherins** [MultiMC/MultiMC5#1614]
## System Information

MultiMC version:Latest Mac Version

Operating System:macOS El Captain 
## Summary of the issue or suggestion:

instant Crash on open 
## What should happen:

Should launch properly and open app
## Steps to reproduce the issue (Add more if needed):

1.Click App icon

2.Instant Crash

3.
## Suspected cause:

No idea?
## Logs/Screenshots:

[//]: http://pastebin.com/LAdbC3Fb or error report

**Comment by Heardy92** [comment]
I'm getting the exact same problem and have no idea how to solve it. Did you sort it out after?

**Comment by peterix** [comment]
I believe this has been since fixed / replaced with a warning dialog that ttells you how to correct the problem.
