### ISSUE TITLE
Can't connect to multiplayer servers

### ISSUE THREAD

**Issue by xXJetstreamXx** [MultiMC/MultiMC5#1618]
## System Information

MultiMC version: 0.4.11-751

Operating System: Windows 10 Home 

Summary of the issue or suggestion:

---

I try to connect to multiplayer servers and it gives me the error: "Failed to login: The authentication servers are currently down for maintenance". I checked the servers on the official site for the servers of Mojang ([Link](https://help.mojang.com/)). I also tested it with the normal Minecraft Launcher and it works.
## What should happen:

Minecraft connects to the server normally.
## Steps to reproduce the issue (Add more if needed):
1. Start MultiMC (version given above)
2. Make new instance for Minecraft 1.10.2 / 1.10
3. Run this instance (hit play)
4. try to connect to a server (e.g. play.wynncraft.de)
## Suspected cause:

I have no real idea.
## Logs/Screenshots:

No error-log given. Just the basic log info:
"[17:59:23] [Client thread/INFO]: Connecting to play.wynncraft.com, 25565"

Additional Info:

**Comment by DreadWingKnight** [comment]
Nothing we can do if the authentication servers are down or the server you're trying to connect to can't reach them.

**Comment by xXJetstreamXx** [comment]
@DreadWingKnight As I said in my report, the problem has to be on the side of MultiMC, because I can connect to the server using normal Minecraft and the servers are online as well.

**Comment by DreadWingKnight** [comment]
At that stage of the process, multimc isn't involved. The server is doing the authentication, not your client and not multimc.

**Comment by jikuja** [comment]
Did you test same servers with vanilla launcher? Server side log?

**Comment by xXJetstreamXx** [comment]
@DreadWingKnight Well I was wondering about the same thing - but how could this be? I mean: same minecraft version, just downloaded through other launchers and just one of them connects to the server. Is there maybe a problem when MultiMC passes the information for the login to the minecraft.jar?

**Comment by xXJetstreamXx** [comment]
@jikuja I tested the same servers (multiple ones) on both launchers - vanilla and MultiMC. I also have no mods installed and use the same profile. As for the logs of the server I can't access them because the servers aren't hosted by myself or something like that.

**Comment by peterix** [comment]
https://www.youtube.com/watch?v=EnkkrKkprI0

**Comment by Mysticalii** [comment]
Well i kind of think that this might be because MultiMC might have been counted as a cracked launcher which only lets you connect to cracked servers...

**Comment by peterix** [comment]
That is pure nonsense, because the server has absolutely no way to detect that.
