### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by julioplayz** [MultiMC/MultiMC5#1619]
System Information
-----------------------------
MultiMC version: 0.4.11

Operating System: Mac OSX El Capitan

Summary of the issue or suggestion: Crashing while loading a mod
----------------------------------------------

What should happen: I try to load two mods, Optifine and Custom items on 1.7.10 and it crashes
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Install both mods

2. Install Forge

3. Run

Suspected cause: The CustomItems Mod
---------------------------

Logs/Screenshots: http://paste.ee/p/zJrLx
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
```
Caused by: java.lang.NoClassDefFoundError: codechicken/nei/api/IConfigureNEI
```

Looks like you need to install NEI.

**Comment by QuImUfu** [comment]
Yep, that is a known bug in Custom Items. See https://github.com/0tho/CustomItems/issues/40
