### ISSUE TITLE
Add support for Steam Overlay on macOS

### ISSUE THREAD

**Issue by PixelArray** [MultiMC/MultiMC5#1621]
## System Information

MultiMC version: 0.4.12-develop-760

Operating System: macOS 10.11 El Capitan
## Steps to reproduce the issue (Add more if needed):
1. Launch MultiMC through Steam
2. Launch a Minecraft Instance
3. Press shift+tab to open the overlay and nothing happens.

**Comment by QuImUfu** [comment]
Under Linux it does work very well.

**Comment by peterix** [comment]
Well, someone bugged me long enough and made me do it there...

I've never tried steam on linux.

**Comment by QuImUfu** [comment]
An workaround may be creating a wrapper script that sets all steam environment variables for Minecraft. I do not know wether this will work with OSX but it does under Linux.
How to:
 - find the OSX command to list all environment variables
 - run it once without Steam and pipe the output to some file. Under Linux:"printenv > env1.txt"
 - run it once with Steam piping the output to another file. Under Linux:   
**Target:** xterm -e "printenv > env2.txt"  
**Start in:** /home/you_username/
 - delete everything from file 2 that is also set in file 1 and hasn't changed. 
 - make a wrapper script that sets those environment variables. If the SDL_GAMECONTROLLERCONFIG= variable gets broken into 3 lines, leave it out. Under Linux:  

```bash
#!/bin/bash
ENABLE_VK_LAYER_VALVE_steam_overlay_1=1 IgnoreChildProcesses= LD_LIBRARY_PATH=:/home/bambus/.local/share/Steam/ubuntu12_64:/home/bambus/.local/share/Steam/ubuntu12_64:/home/bambus:/home/bambus/bin LD_PRELOAD=:/home/bambus/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so:/home/bambus/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so OpenVRStreamingEnabled= SDL_VIDEO_X11_DGAMOUSE=0 Steam3Master=127.0.0.1:57343 SteamAppId=0 SteamAppUser=quimufu STEAM_CLIENT_CONFIG_FILE=/home/bambus/.local/share/Steam/steam.cfg SteamControllerAppId=2147483649 SteamGameId=14258429401342410752 SteamLauncherUI= SteamNoOverlayUI=0 STEAM_RUNTIME=0 STEAMSCRIPT=/usr/bin/steam STEAMSCRIPT_VERSION=100052 SteamStreaming= SteamStreamingAllowGameVsync= SteamStreamingForceWindowedD3D9= SteamStreamingHardwareEncodingAMD=0 SteamStreamingHardwareEncodingIntel=1 SteamStreamingHardwareEncodingNVIDIA=1 SteamStreamingMaximumResolution= SteamTenfoot=0 SteamUser=username StreamForOpenVR=0 StreamingTargetAudioChannels= SYSTEM_LD_LIBRARY_PATH= SYSTEM_PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin TEXTDOMAINDIR=/usr/share/locale TEXTDOMAIN=steam $@
```
 - than add it to MMC as wrapper command.

This will most likely not work perfectly (time in Game, Game you are playing), but the overlay will show up and can be used. (warning: with Steam-overlay Minecraft needs at least 2GB Ram)
