### ISSUE TITLE
Process exited with code -1

### ISSUE THREAD

**Issue by legoman9570** [MultiMC/MultiMC5#1624]
System Information
-----------------------------
**MultiMC version**: 0.4.11-751

**Operating System**: Windows 10

**Summary of the issue or suggestion**: Minecraft crashing when I have the Plant Mega Pack installed.
----------------------------------------------

**What should happen**: Not crash and work :)
------------------------------

**Suspected cause**: Conflicting mod and/or possibly something else.
---------------------------

**Logs/Screenshots**:
----------------------------
http://paste.ee/p/oZTVI

**Additional Info**: I tried looking into the crash, couldn't find any non compatible mods. But you never know I could have missed one.
---------------------------

**Comment by F4ndroid** [comment]
Change enabled to false in config/splash.properties

**Comment by legoman9570** [comment]
Changed to false but still crashed. Here is the new log http://paste.ee/p/XlCHU

**Comment by F4ndroid** [comment]
This looks like an issue with Garden Core's integration with Plant Mega Pack.
See https://github.com/jaquadro/GardenCollection/issues/49
Post the log there.

**Comment by legoman9570** [comment]
I see, so is there a fix or do I need to remove a certain mod?

**Comment by legoman9570** [comment]
Ok thanks
