### ISSUE TITLE
MultiMC Redownloads Version 1.7.1.0 Every Launch Results No Custom Jar Modification

### ISSUE THREAD

**Issue by jredfox** [MultiMC/MultiMC5#1627]
MultiMC Redownloads Version1.7.1.0 Every Launch.  I compiled a class that extends the array list of the biomes from byte to integer. I replaced this class ahu.class with my own one(ahu.class).  It however downloads the .jar everytime. I wanted multimc to test to see if the mod would even work but, I can't even test it here, the vanilla launcher or the technic launcher. One year ago I remember you could still have base class edits and the launcher would load your custom version. What is going on? I even made the instance customized .jar and nothing.  I tried making it a jar mod but, that didn't work. It loaded both vanilla's ahu.class and my ahu.class (mine class was in a zip called ahu.zip) and it didn't know what to do so it had a memory leak and closes always before it goes to the main menu.  I just want to extend the freaken id limits so I can actually make a modpack more then 135 mods.  I want biomes, entities , orespawn and other mods with lots of ids all in one. It doesn't even get a chance to load my class because, it downloads vanilla every launch.    

Crash upon failer to overwrite jar class: http://pastebin.com/GT4hEEZx

Here is my class. http://www.mediafire.com/download/laaq7gn7u7cdmge/ahu.class

**Comment by peterix** [comment]
This works as intended, you will have to use a jar mod.

What you have is a bug in your own code.

**Comment by peterix** [comment]
Or simply not enough memory... from the looks of it, it might be trying to create an array that is bigger than what would fit into the Java heap.

**Comment by peterix** [comment]
https://plumbr.eu/outofmemoryerror/requested-array-size-exceeds-vm-limit

**Comment by jredfox** [comment]
Can you try this before jumping to a conclusion? you have a 64bit you try putting this on 1g min 2g max.  If it's still running out of memory it's loading both biome array lists at once and isn't replacing the ahu.class.

**Comment by peterix** [comment]
The class is replaced, but you introduced a bug. You will have to fix it, and you will have to understand what you're doing.

**Comment by jredfox** [comment]
what bug did I introduce? did it crash was it a memory issue?

**Comment by jredfox** [comment]
Most modpacks don't use multi mc they either use technic , vanilla or ftb launcher. do you know of a way to get around these launchers downloading the jar thing? I mean I can fix up forge and vanilla until they are good for 1.7.10, 1.8.9 , 1.1.0 but, although I love multi mc I like the vanilla launcher better for modpacks development.

**Comment by peterix** [comment]
As I said, it works as intended. Use a jar mod. I will never let you mess with the version jars - it would violate the isolation between instances and cause unexpected issues for users.

**Comment by peterix** [comment]
What you should be doing is using ASM based core mods, or a custom build of forge (where your changes would be extra patches).

**Comment by jredfox** [comment]
one last question when does your jar mods load? is it before or after vanilla , before or after forge. in vanilla forge's way forge loads first partially , then vanilla then forge again.  if your jar mod is loading after forge loads that could be the problem

**Comment by peterix** [comment]
The jar mod is used to assemble a custom minecraft jar before launch, as if you were constructing it manually.

**Comment by jredfox** [comment]
about coremods and asm. according to elix_x you can convert the ids to integer but, it breaks when another mod calls upon the array list.  He had already attempted it and said he could support it dynamically using asm but, it would be nearly impossible. This is when I said screw it base class editing time. I want my 3000 biome modpack and 400 dimension modpack.

**Comment by peterix** [comment]
This is a rather fundamental change to how the game works, so you'll have difficulties, no matter how you change the class files.

Just disassembling/recompiling the code will make it easier to make your changes and test them, but could break other mods because the code changed too much and their patching no longer works...

Or, as you saw, something else tries to allocate a huge array and makes the game crash, because it's suddenly not 256 elements, but INT_MAX elements.

**Comment by peterix** [comment]
And if a mod is expecting the IDs to be 'byte', you may run into issues with the higher numbers getting truncated when used by the mods.

**Comment by peterix** [comment]
This also likely changes the world format... unless Mojang does save these numbers as integers.

**Comment by jredfox** [comment]
actually i can confirm it doesn't replace the class. It works for vanilla then It loads the main screen for forge but, if I change the id limit of any modded biome to 256 it crashes saying array list out of bounds at biome gen base.

**Comment by peterix** [comment]
It does replace the class.

**Comment by jredfox** [comment]
then why does it say list out of bounds?  http://pastebin.com/GTQmaneT

**Comment by peterix** [comment]
Because it actually works? You replaced the class, it crashes because you did.

**Comment by jredfox** [comment]
at net.nevermine.dimension.DimensionOrganizer.<clinit>(DimensionOrganizer.java:43)

so you saying I need to re-initilize the biome array list? I don't know how to do that

**Comment by peterix** [comment]
I'm saying that you are trying to change something that noone else expects to change, forge included.

If you want to use forge and forge mods with your customized Minecraft, there's a very high chance that you will also have to fix **those**.

**Comment by peterix** [comment]
Basically, look at what's going on in BiomeGenBase.java:159

This file is patched by Forge. So... who knows if the line numbers even match. Hopefully they do.

**Comment by jredfox** [comment]
well I did find alot of places in that class that stored obfuscated code as byte I am going to experiment and change all of them to short and see what happens.  

The only way you could expand ids with forge is if the ids are > vanilla list use your own definitions transfer it to your ids and hope your a wizzard and that nothing breaks.  I am not advanced in java and won't be till I take the classes in college.

**Comment by peterix** [comment]
Hm, don't expect college to teach you anything really advanced... that's something that is up to you and your own initiative.

Your problem is that there's a LOT of stuff out there that depends on the data being a certain type. If this was somehow a behaviour - pure code - it would be fine... but changing a data type that gets used all over the place is not simple. You won't be able to do it by tweaking one file. More like tens or hundreds of files across many projects... Minecraft, Forge, mods, etc.

I'm not sure where all the places those IDs are used are. But just guessing:
* world save format
* network packets
* rendering? (biomes have an effect on the look of the world after all)
* forge patches that have anything to do with {biomes, dimensions, ...}
* every mod that does anything with {biomes, dimensions, ...}

For example, Forge adds a biome registry to avoid using raw IDs in mods. Your changes would have to be reflected there also.

**Comment by peterix** [comment]
AFAIK, the file is patched at runtime, so the line numbers likely won't match anymore...

Maybe you can guess what the code was by looking at the patch and the original file.

Patch:
https://github.com/MinecraftForge/MinecraftForge/blob/86ccfb1d682137290692989dcd92d21503bd5e7a/patches/minecraft/net/minecraft/world/biome/BiomeGenBase.java.patch

**Comment by peterix** [comment]
```
At the level of the Java Virtual Machine, every constructor written in the Java programming language (JLS §8.8) appears as an instance initialization method that has the special name <init>. This name is supplied by a compiler. Because the name is not a valid identifier, it cannot be used directly in a program written in the Java programming language.
```

So, that's the constructor. Look for a constructor.

**Comment by jredfox** [comment]
it seems to refer to vanilla biome array list there is more code but, since this isn't in eclipse I don't know where what or why this code is there.

**Comment by peterix** [comment]
From the mod:
```
package net.nevermine.dimension.abyss;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import java.awt.Color;
import java.util.List;
import net.minecraft.world.biome.BiomeGenBase;
import net.nevermine.izer.Blockizer;

public class BiomeGenAbyss extends BiomeGenBase
{
  public BiomeGenAbyss(int par1)
  {
    super(par1);
    func_76735_a("Abyss");
    this.field_76752_A = Blockizer.AbyssGrass;
    this.field_76753_B = Blockizer.AbyssStone;
    this.field_76751_G = 100.0F;
    this.field_76762_K.clear();
    this.field_76761_J.clear();
    this.field_76766_R = false;
    this.field_82914_M.clear();
    this.field_76750_F = 0.0F;
  }

  @SideOnly(Side.CLIENT)
  public int func_76731_a(float par1)
  {
    return Color.RED.getRGB();
  }
}
```
So it's calling the constructor that takes a single `int`... as long as the decompiler didn't screw up. The mod is not open source.

**Comment by jredfox** [comment]
my code didn't touch the parameters it just changed the extent to which the arrays capacity was.  I think I found the error Just let me test this. Then we will know once in for all if it was multimc or forge.

**Comment by peterix** [comment]
This means that it's calling:
```
public BiomeGenBase(int p_i1971_1_)
```
Which calls:
```
public BiomeGenBase(int p_i1971_1_, true)
```

I don't have the original file, only the patch... but if I had to guess, the size of field_76773_a is too small.

Basically, you should replace arrays with some other container, or just pick a larger constant for the array size that isn't INT_MAX.

**Comment by peterix** [comment]
Well, it definitely is NOT MultiMC. It could never be.

**Comment by jredfox** [comment]
well that parameter is calling this which again has nothing to do with the biome array list itself.  
http://pastebin.com/3WKYJTA7

**Comment by jredfox** [comment]
sorry getting off topic maybe you could help me with this if you would like please on the mc forums or even a github for this?

**Comment by peterix** [comment]
Well, I think I helped you as much as I could. You are looking at the actual problems now.

The launcher used is irrelevant, as long as you don't try using [Java Agent](https://docs.oracle.com/javase/7/docs/api/java/lang/instrument/package-summary.html), which MultiMC doesn't support yet.

Everything else is me extrapolating from incomplete information... I'm not involved with actual Minecraft modding, although it might sound like that :)

**Comment by jredfox** [comment]
java agent I think that's what the crash said.

**Comment by jredfox** [comment]
http://pastebin.com/dqzxD6Zp

read this. this is from vanilla launcher is this what you are talking about and do you think you can find the problem?

**Comment by jredfox** [comment]
earlier you said to replace the arrays under integer.max_value i did that here is my only edit

From byte 
private static final ahu[] aD = new ahu[256];

To short
private static final ahu[] aD = new ahu[32767];

**Comment by peterix** [comment]
No, you are not using java agent. I think one japanese mod used it at some point...

As for that log, I am not interested in looking at anything related to the vanilla launcher. I do not work on it, I do not use it and I do not plan to ever support it.

**Comment by jredfox** [comment]
Ok I understand. I just want to get it working with all launchers.  If it works with vanilla then I could patch it with technic via .json edits, and other things.  The problem is definitely forge being stubborn.  I just compiled a single edit to biome gen base jungle id from 21 to 233 with no other modifications threw that in and crash as the same as the biome array list but, this time also with biome dictionary class to.
