### ISSUE TITLE
Will not run under Debian Sid, undefined symbol error

### ISSUE THREAD

**Issue by pwnage-pineapple** [MultiMC/MultiMC5#1629]
System Information
-----------------------------
MultiMC version: 0.4.11

Operating System: Debian Sid

Summary of the issue or suggestion: /home/zack/.local/share/multimc/bin/MultiMC: symbol lookup error: /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0: undefined symbol: xcb_get_reply_fds

----------------------------------------------

What should happen: 
------------------------------
It should start up and reach the instance selection menu

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Run /opt/multimc/run.sh on an up-to-date Debian Sid system

Suspected cause:
---------------------------
An undefined symbol

Logs/Screenshots:
----------------------------
http://paste.ee/p/LDZeJ

Additional Info:
---------------------------

**Comment by peterix** [comment]
Remove some or all of the highlighted files from `/home/zack/.local/share/multimc/bin/`:
![image](https://cloud.githubusercontent.com/assets/203326/17122512/5500cc44-52dc-11e6-84f5-1467c685fada.png)

**Comment by peterix** [comment]
Sadly, I simply cannot make one build magically work with every single distro release out there...

**Comment by pwnage-pineapple** [comment]
Your fix worked, closing issue

**Comment by peterix** [comment]
You will likely run into the same issue when MultiMC updates. In that case, just remove the files again.

**Comment by Spice-King** [comment]
I should note I have the exact same issue with Ubuntu 16.04. Moved all the ```lib-xcb*``` files to a temp subdirectory for testing. Had to move back just ```libxcb-sync.so.0```, as in 16.04 there is not a copy of that so version in the repo. The tool ```apt-file``` found that a ```libxcb-sync.so.1``` exists in the package ```libxcb-sync1```, which happened to be pre-installed for other things.

16.04 has been a bit of a black sheep to me. Full ZFS support is nice, but a kernel that causes the screen to flicker black is kinda an issue that should be fixed already. Might be time to give Arch Linux a spin, or maybe try Fedora for a change.
