### ISSUE TITLE
Code 1 is the bane of my existance!!!

### ISSUE THREAD

**Issue by LogicGaming** [MultiMC/MultiMC5#1634]
Simple request, fix your program here is the log... if add to the ram it ends up like the log and if I leave it runs out of memory

```
                       Comment anything I need to add for you to help me please!!! this is ****ing crap
```

MultiMC version: 0.4.11-751

Minecraft folder is:
instances/Modpack Backup/minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/java.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1500m, -Duser.language=en, -jar, C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/jars/NewLaunch.jar]

Minecraft process ID: 9692

Error occurred during initialization of VM
Could not reserve enough space for 1536000KB object heap
Process exited with code 1.

**Comment by 02JanDal** [comment]
How much memory do you have available?

**Comment by Shadows-of-Fire** [comment]
Error occurred during initialization of VM
Could not reserve enough space for 1536000KB object heap
Process exited with code 1.
Stop using 32-bit Java.

**Comment by LogicGaming** [comment]
I have 16 gb of memory



I used the 64 bit version of java and this happened

MultiMC version: 0.4.11-751

Minecraft folder is:
instances/Modpack Backup/minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_102/bin/javaw.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1536m, -Duser.language=en, -jar, C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/jars/NewLaunch.jar]

Minecraft process ID: 5724

Using onesix launcher.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/instances/Modpack Backup/natives

Traits:
  []

Libraries:
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/com/mojang/netty/1.6/netty-1.6.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar (missing)
  C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/versions/1.7.10/1.7.10.jar

Mods:
  
  advancedgenetics-1.7.10-1.5.9
  AnimationAPI-1.7.10-1.2.4
  AOBD-2.8.4
  AppleCore-mc1.7.10-1.1.0
  appliedenergistics2-rv2-stable-10
  Armourers-Workshop-1.7.10-0.38.1.98
  Aroma1997Core-1.7.10-1.0.2.16
  Aroma1997s-Dimensional-World-1.7.10-1.1.0.1
  AromaBackup-1.7.10-0.0.0.5
  1.7.10_AM2-1.4.0.008
  Artifice-1.7.10-1.1.5R-399
  AsieLib-1.7.10-0.4.5
  backpack-2.0.1-1.7.x
  bdlib-1.9.4.109-mc1.7.10
  BiblioCraft[v1.11.4][MC1.7.10]
  BiblioWoods[BiomesOPlenty][v1.9]
  BiblioWoods[Natura][v1.5]
  BigReactors-0.4.3A
  BiomesOPlenty-1.7.10-2.1.0.1465-universal
  BloodMagic-1.7.10-1.3.3-17
  Botania r1.8-242
  buildcraft-7.1.14
  buildcraft-compat-7.1.3
  Carpenter's Blocks v3.3.7 - MC 1.7.10
  CartFixes-1.7.10-0.1.0
  ChickenChunks-1.7.10-1.3.4.19-universal
  Chisel-2.9.4.10
  CodeChickenCore-1.7.10-1.0.7.47-universal
  CoFHCore-[1.7.10]3.1.0B1-321
  CompactSolars-1.7.10-4.4.39.315-universal
  ComputerCraft1.75
  Computronics-1.7.10-1.6.0
  DeathCounter-4.0.0
  Decocraft-2.2.1_1.7.10
  DefaultWorldGenerator-1.7.10-0.1-b13-client
  denseores-1.6.2
  DogeMod_0.5.2_[1.7.10]
  DragonAPI 1.7.10 V10c
  DynamicLights-1.7.10
  EnchantingPlus-1.7.10-3.0.2-d
  EnderIO-1.7.10-2.3.0.422_beta
  EnderIOAddons-1.7.10-2.3.0.422_beta-0.9.13.041_beta
  EnderZoo-1.7.10-1.0.15.32
  EnderCore-1.7.10-0.2.0.31_beta
  EnderStorage-1.7.10-1.4.7.37-universal
  EnderTech-1.7.10-0.3.2.405
  INpureCore-[1.7.10]1.0.0B9-62
  ExtraCells-1.7.10-2.3.3b162
  extrautilities-1.2.12
  ExtraTiC-1.7.10-1.4.5
  Factorization-1.7.10-0.8.88.7
  FastLeafDecay-1.7.10-1.1
  fastcraft-1.21
  Flans Mod-1.7.10-4.10.0
  FoodPlus-1.7.2-3.2rS
  Forbidden Magic-1.7.10-0.57
  forestry_1.7.10-4.2.1.48
  Fossils_Archeology_Revival-1.7.10_Build-7.2.1
  FTBLib-1.7.10-1.0.12.1
  FTBUtilities-1.7.10-1.0.12
  funky-locomotion-1.7.10-beta-7
  GalacticraftCore-1.7-3.0.12.404
  Galacticraft-Planets-1.7-3.0.12.404
  gendustry-1.6.3.132-mc1.7.10
  GraviSuite-1.7.10-2.0.3
  AttachableGrinder-4.0.0
  growthcraft-1.7.10-2.3.1-complete
  HQM-The Journey-4.4.4
  HardcoreEnderExpansion  MC-1.7.10  v1.8.4
  Hats-4.0.1
  HatStand-4.0.0
  HelpFixer-1.0.7
  HungerOverhaul-1.7.10-1.0.0
  AdvancedMachinesAS-1.7.10
  iChunUtil-4.2.2
  industrialcraft-2-2.2.808-experimental
  InventoryTweaks-1.59-dev-156
  ironchest-1.7.10-6.0.62.742-universal
  IvToolkit-1.2
  Jabba-1.2.1a_1.7.10
  logisticspipes-0.9.3.70
  ModularPowersuits-0.11.0.290
  magicbees-1.7.10-2.4.0
  magicalcrops-4.0.0_PUBLIC_BETA_3
  Mantle-1.7.10-0.3.2b
  Mekanism-1.7.10-8.1.7.252
  MekanismGenerators-1.7.10-8.1.7.252
  MekanismTools-1.7.10-8.1.7.252
  MFR Compat - Magical Crops v1-2-1
  MicdoodleCore-1.7-3.0.12.404
  MineFactoryReloaded-[1.7.10]2.8.1B1-168
  MineMenu-1.7.10-1.2.0.B44-universal-client
  MmmMmmMmmMmm-1.6
  More-Planets-1.7.10-1.3.0-Pre-6
  More-Planets-ASM-1.7.10
  Morph-Beta-0.9.2
  MrCrayfishFurnitureModv3.4.8(1.7.10)
  mystcraft-1.7.10-0.12.3.01
  natura-1.7.10-2.2.0.1
  Necromancy-1.7.10a
  neiaddons-1.12.14.40-mc1.7.10
  NEIIntegration-MC1.7.10-1.1.0
  NetherOres-[1.7.10]2.3.1RC1-19
  NoMoreRecipeConflict-0.2(1.7.10)
  NotEnoughResources-1.7.10-0.1.0-121
  NotEnoughItems-1.7.10-1.0.5.118-universal
  IC2NuclearControl-2.3.3a-Exist
  Numina-0.4.0.131
  ObsidiPlates-1.7.10-universal-3.0.0.18
  OpenBlocks-1.7.10-1.4.4
  OpenComputers-MC1.7.10-1.5.20.38-universal
  OpenEye-0.6-1.7.10
  OpenModsLib-1.7.10-0.8
  OpenPeripheral-1.7.10-AIO-5
  OptiFine_1.7.10_HD_U_C1-client
  Pam's HarvestCraft 1.7.10Lb
  PiP-4.0.0-client
  PlayerAPI-1.7.10-1.4
  PneumaticCraft-1.7.10-1.12.2-145-universal
  ProgressiveAutomation-1.7.10-1.6.29
  ProjectRed-1.7.10-4.7.0pre9.92-Compat
  ProjectRed-1.7.10-4.7.0pre9.92-Base
  ProjectRed-1.7.10-4.7.0pre9.92-Mechanical
  ProjectRed-1.7.10-4.7.0pre9.92-World
  ProjectRed-1.7.10-4.7.0pre9.92-Fabrication
  ProjectRed-1.7.10-4.7.0pre9.92-Lighting
  ProjectRed-1.7.10-4.7.0pre9.92-Integration
  Railcraft_1.7.10-9.8.0.0
  RandomThings-2.2.4
  RecurrentComplex-0.9.6.3
  RedstoneArsenal-[1.7.10]1.1.1-89
  RefinedRelocation-mc1.7.10-1.1.12
  Reliquary-1.2
  RenderPlayerAPI-1.7.10-1.4-client
  roguelike-1.7.10-1.3.6.3
  SimplyJetpacks-MC1.7.10-1.5.3
  squidless-1.7.10-0.6.1
  statues-1.7.10-2.1.4
  StevesAddons-1.7.10-0.10.16
  StevesCarts2.0.0.b18
  StevesFactoryManagerA93
  StevesWorkshop-0.5.1
  Sync-4.0.0
  TabbyChat-1.7.10-1.11.2.2-liteloader
  Thaumcraft-1.7.10-4.2.3.5
  thaumcraftneiplugin-1.7.10-1.7a-client
  thaumicenergistics-0.8.10.10
  ThaumicExploration-1.7.10-1.1-53
  ThaumicTinkerer-2.5-1.7.10-517
  secretroomsmod-1.7.10-4.7.1.406
  twilightforest-1.7.10-2.3.7
  ThermalDynamics-[1.7.10]1.1.0-161
  ThermalExpansion-[1.7.10]4.1.0B1-234
  ThermalFoundation-[1.7.10]1.2.1-109
  TiCTooltips-mc1.7.10-1.2.5-client
  TConstruct-1.7.10-1.8.8
  TMechworks-1.7.10-0.2.14.100
  Translocator-1.7.10-1.1.2.15-universal
  [1.7.10]Treecapitator-universal-2.0.4
  mod_VoxelCam_1.3.2_mc1.7.10-client
  lib_voxellib_2.3.1_mc1.7.10-client
  mod_voxelMap_1.5.17_for_1.7.10
  mod_voxelmenu_4.1.4_mc1.7.10
  res_voxelmenumusic_v_mc1.7.10
  Waila-1.5.10_1.7.10
  WailaHarvestability-mc1.7.10-1.1.5
  WAILAPlugins-MC1.7.10-0.2.0-23
  warpbook-1.7.10_2.0.36
  WarpDrive-1.7.10-1.3.13
  witchery-1.7.10-0.24.1
  worldedit-forge-mc1.7.10-6.0-beta-01
  WR-CBE-1.7.10-1.4.1.9-universal
  Yampst-Not The 1.7.10 Pack-1.0.1

Params:
  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/instances/Modpack Backup/minecraft, --assetsDir, C:/Users/Epickiller/Desktop/OneFolder/Random Files Not Used Often/Multimc/assets, --assetIndex, 1.7.10, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {}, --userType, mojang, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]

Window size: 854 x 480

Preparing native libraries...
Extracting twitch-platform-5.16-natives-windows-64.jar
Extracting twitch-external-platform-4.5-natives-windows-64.jar
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

[11:24:20] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[11:24:20] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: cpw.mods.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_102]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_102]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_102]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Process exited with code 1.

**Comment by Heufneutje** [comment]
You don't appear to have Forge installed or it got corrupted.

**Comment by KingDGrizzle** [comment]
Reinstall forge..

And shoudn't it be -Xmx1500mb ?

**Comment by Heufneutje** [comment]
[No it shouldn't.](https://docs.oracle.com/cd/E22289_01/html/821-1274/configuring-the-default-jvm-and-java-arguments.html)

**Comment by peterix** [comment]
Hmm.. bad advice here... sorry.

It was incompatible mods. `FoodPlus-1.7.2-3.2rS` is definitely for 1.7.10. There might have been others.

Anyway, closing, this is most likely way past its shelf life ~_~
