### ISSUE TITLE
Themeing on windows

### ISSUE THREAD

**Issue by Bottersnike** [MultiMC/MultiMC5#1636]
I've seen all of the screenshots from the Linux version, and I was wondering if we could get an option in the windows version to switch over to the linux theme because personally I prefer the way that linux one looks.
Thanks.

**Comment by peterix** [comment]
Adding it to the theming item on workflowy:
https://workflowy.com/s/2EyDMcp7CU#/4bf315c7da67

Some of the other items there are more likely to happen sooner.
The most likely thing to happen soon is on top.
