### ISSUE TITLE
Code 1 issue; invalid maximum heap size.

### ISSUE THREAD

**Issue by Trusty-Mccoolguy** [MultiMC/MultiMC5#1637]
System Information
-----------------------------
MultiMC version: 0.4.11-751

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------

When I try to use MultiMC to play, even vanilla instances can't be used. It won't pass the startup stage with the code.

What should happen:
------------------------------

The game should be able to run vanilla MC. I haven't even tried mods yet.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MC

2. Click instance (I've tried everything between 1.7.10 to 1.10.2)

3. Press play

Suspected cause:
---------------------------

I suspect it has something to do with RAM and/or my Java version? I'm not sure. I know that I'm using Intel, and as such I needed a workaround for the java's initial error, but now I'm running into another issue.

Logs/Screenshots:
----------------------------

http://pastebin.com/q97KvwR4

Additional Info:
---------------------------

When I go below 4096 MB to see if I can fix the size, it does this.

http://pastebin.com/h3F1xHdh

When I first ran into issues, it wasn't with the current error code.

I first ran into a code -1 error, so I started looking at 1615 because it shared the code -1 issue I was getting prior to the workaround I was trying. 1615 led me to 1606 which explained that my OpenGL issue is due to needing an older version of java for the sake of getting around my Intel with Windows 10 issue. I gave the older java (I tried both 8u51 and 8u25) its own folder without making it my system's java, so that I could use it for the MultiMC java alone. It gives me the Code 1 error in response.

(Actual code -1 initial error here for the sake of providing as much information as I can. This is the first issue I ran into.)

http://pastebin.com/sYcu7GyS

I've been careful not to do anything that can't be easily undone, so anything you tell me to do, I can do without an issue. I consider myself fairly computer literate, so I can follow most instructions easily and know that I didn't mess up the Java.

Additionally, my RAM and processor specs, exactly as provided in my system information:

Processor: Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz 2.50GHz
Installed memory (RAM): 7.90GB
System Type: 64-bit Operating System, x64-based processor

Thank you for reading this over, in advance, and for any help you may be able to provide!

**Comment by Loetkolben** [comment]
First of all, from my experiences, error code `-1` does not really indicate a special error with most (modern) applications. With Minecraft, you're better of searching for exceptions and stacktraces.
If I understood corrently, you get `org.lwjgl.LWJGLException: Pixel format not accelerated` when using up-to-date systemwide java, and with the old, MMC-only java you get `Could not reserve enough space for 4063232KB object heap` or something else along the lines of "not enough memory".
So is the java you downloaded 64bit? If not, download the 64bit version or try with less RAM and the MMC-only java.

**Comment by peterix** [comment]
You should use 64bit Java older than 8u60.

What GPU do you actually have?

**Comment by Trusty-Mccoolguy** [comment]
Yes, the java is 64-bit. My graphics card info is here.

http://imgur.com/a/qCgHZ

**Comment by peterix** [comment]
Please provide fresh logs.

**Comment by Trusty-Mccoolguy** [comment]
Sure thing. This is what it just gave me trying the MMC java and less ram (2176MB)

http://pastebin.com/B9JxBKpr

And 1024MB http://pastebin.com/97DQA8LW

And even less, at ~700MB http://pastebin.com/K68hYzS7

Doesn't like me no matter how much or how little RAM I try to pour into it.

**Comment by peterix** [comment]
```
    Java Version: 1.8.0_91, Oracle Corporation
```
That will never work with this GPU. You need to use older than 1.8.0_60

**Comment by peterix** [comment]
Fix HD3000 bugs with Java 8u60 and newer
* Download http://files.multimc.org/downloads/jre-8u51-windows-x64.zip
* Extract the folder jre1.8.0_81 from the archive into the MultiMC folder
* Set MultiMC to use the javaw.exe from inside that

**Comment by Trusty-Mccoolguy** [comment]
I've been using 8u51. That was the game's natural java, *not* the one I downloaded, as I was asked to use??

**Comment by peterix** [comment]
None of the logs show you using a java version that would work.

You still use 1.8.0_91.

**Comment by peterix** [comment]
Make sure you are setting it up right.

If you are changing Java in the main settings, make sure you do not have an override set in the instance's settings.

**Comment by Trusty-Mccoolguy** [comment]
Okay, that was a thing that I wasn't aware of, but it still doesn't seem to be working.

MultiMC version: 0.4.11-751

Minecraft folder is:
instances/Vanilla 1.7.10/minecraft

Java path is:
C:/Users/Aze/Downloads/jre1.8.0_25/bin/javaw.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx5888m, -Duser.language=en, -jar, C:/Users/Aze/Downloads/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 8576

Invalid maximum heap size: -Xmx5888m
The specified size exceeds the maximum representable size.
Process exited with code 1.

**Comment by peterix** [comment]
And now give it less memory, your system probably doesn't have 5888MB of free memory.

**Comment by Trusty-Mccoolguy** [comment]
Ahhhh! Yes. Thank you.

I'm sorry I ended up bothering you both about something I really should have been able to spot if I wasn't an idiot, but I was really lost. Thank you so much for helping me. : ]

**Comment by peterix** [comment]
The GPU mess is not all that obvious. I had to decompile the intel drivers to find out what's going on a few months back.

Anyway, cheers!

**Comment by Akip25** [comment]
Anyone else having that issue i fixed it by updating to 64 bit java :)

**Comment by Richardsnts1** [comment]
estou com mesmo problema =/
tenho 32gb de ram das quais 16gb estão livres, java está na ultima versao disponivel (x64) porem nao consigo passar de 1024mb, qualquer valor acima disso crash a inicialização. E só com isso de memoria nao dá nem pra iniciar o minecraft direito =/
Estou tentando rodar na versão 1.16 com o forge mais recente
