### ISSUE TITLE
error in starting VM

### ISSUE THREAD

**Issue by swimpedothenerd** [MultiMC/MultiMC5#1638]
MultiMC version: 0.4.11-751

Minecraft folder is:
instances/1.10.2/minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/java.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1550m, -Duser.language=en, -jar, C:/Users/**********/Desktop/*********/*************************/Minecraft mmc/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 5648

Error occurred during initialization of VM
Could not reserve enough space for 1587200KB object heap
Process exited with code 1.

Please Help!

**Comment by swimpedothenerd** [comment]
i tried to adjust the java memory and i updated java but that did not work

**Comment by Bottersnike** [comment]
It looks like you need even more memory. Try increasing the PermGen and the allocated RAM even more. Give it at least 2GB (It's after 1.5872GB).

**Comment by peterix** [comment]
I'd say exactly the opposite. You seem to be using a 32bit system, or 32bit Java. To use more than roughly 1500MB for the Java heap space, you need to use a 64bit computer, with a 64bit OS and 64bit Java.

The 1500 number can vary. It could be a bit less in your case, try 1400.

If your computer is 32bit, you need new hardware.
If your OS is 32bit, you need to install a 64bit one.
If your Java is 32bit, uninstall it and install the 64bit version.

**Comment by swimpedothenerd** [comment]
peterix i am using a 64bit os and java i clicked on the windows download and it did not give me an option do download 64bit  i will try alocating it 2 gb

**Comment by peterix** [comment]
http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

**Comment by peterix** [comment]
Use the `Windows x64 Offline` version.

**Comment by swimpedothenerd** [comment]
no a 64bit multi mc

**Comment by peterix** [comment]
What?

**Comment by swimpedothenerd** [comment]
that is the program i am having problems with when i open it on the top it says like multimc5 verson ###.#### on win32
i have a 64 bit os

**Comment by swimpedothenerd** [comment]
and i tried alocating it 2gb but i got the same error with the reserve amount being 20004800kb  or somthing

**Comment by swimpedothenerd** [comment]
like 2.48gb or somthing

**Comment by peterix** [comment]
It doesn't matter what CPU architecture is multimc built for. I will make a 64bit version when Microsoft releases a viable consumer OS that only supports 64bit CPUs. No sooner.

Your problem is either not enough RAM or 32bit Java.

**Comment by swimpedothenerd** [comment]
IT WORKED!!!
Thanks for your help

**Comment by peterix** [comment]
Alright :)
