### ISSUE TITLE
Make instance windows independent from main window

### ISSUE THREAD

**Issue by EddwardR** [MultiMC/MultiMC5#1639]
System Information
-----------------------------
MultiMC version: 0.4.12-develop-805

Operating System: Windows 10, latest update - win32

Summary of the issue or suggestion: 
----------------------------------------------
The latest update brought in the ability to edit the instance and relaunch from the log window. Sadly, it isn't possible to minimize separate windows from MultiMC (e.g. minimize the instance selector, leave the log open)

What should happen:
------------------------------
Minimizing one window will only minimize that one to the taskbar, leaving the others where they were.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Open any instance, leave the instance selector open

2.Minimize instance selector

Suspected cause:
---------------------------
Everything is handled as one window with sub-windows for the logs (and probably more)

Logs/Screenshots:
----------------------------
/don't think it's possible to log window status in Windows/

**Comment by peterix** [comment]
This is still very much a work in progress :)

I plan to make them behave like browser tabs in chrome.

**Comment by peterix** [comment]
Implemented in ec05ca2775eec75ce2248b3b575f030c198ff2ee
