### ISSUE TITLE
Can't compile on Windows

### ISSUE THREAD

**Issue by wb9688** [MultiMC/MultiMC5#1641]
System Information
-----------------------------
MultiMC version: commit cf0694a0cb9041c14cc0e06b9495590baacead73  
Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
I can't compile on Windows.

What should happen:
------------------------------
That it compiles successfully.

Steps to reproduce the issue:
-------------------------------------------------------------
Following the [build guide](https://github.com/MultiMC/MultiMC5/blob/develop/BUILD.md).

Suspected cause:
---------------------------
`gmtime_r` doesn't exist on Windows/MinGW.

Logs/Screenshots:
----------------------------
![Screenshot](https://cloud.githubusercontent.com/assets/9780201/17485157/0bd62f3a-5d8d-11e6-906f-d07891867de4.png)

Additional Info:
---------------------------
I've installed the latest version of all the tools I needed to install.

**Comment by peterix** [comment]
I've never seen such an issue.

Are you absolutely sure that you use MinGW toolchain and Qt 5.4.1?

**Comment by wb9688** [comment]
I'm 100% sure that I'm using the latest Qt and MinGW…

**Comment by peterix** [comment]
Well, that's the thing... MultiMC does not build with the latest Qt on Windows

**Comment by wb9688** [comment]
OK, why? Woudn't it be better if it worked with the latest Qt?

**Comment by peterix** [comment]
If it actually works...

5.5.1 ended up having a critical bug in its networking library that caused lag for people on wifi connections.
I haven't tried 5.6 or 5.7. I will at some point, but I'd prefer to work on something tangible instead of swapping out libraries for no apparent reason.

**Comment by peterix** [comment]
Sounds like I should fix BUILD.md, right?

**Comment by wb9688** [comment]
BUILD.md says that you should use 5.4.1, but that sounds like "that was the
latest version when writing, so I'll just use the latest version". It
should mention in bold smething like  "WARNING: MAKE SURE YOU'RE USING
VERSION 5.4.1" or something like that.

**Comment by peterix** [comment]
You can always look at what the ci server does:
http://ci.multimc.org/builders/win32/builds/806

**Comment by wb9688** [comment]
Btw it works fine on Linux with the latest Qt. I'll test downgrading Qt tomorrow and let you know if it worked.

**Comment by peterix** [comment]
As for any versions that are different than the ci server: I have no idea if it will work.

I definitely want to move on to Qt 5.7+ at some point, but it has some issues on Windows. Qt 5.6 changed how the zlib library is bundled, so MultiMC can't use it anymore and has to supply its own. Parts of MultiMC (still) depend on that on Windows.

**Comment by wb9688** [comment]
Why is the CI using Qt 5.4.2-small while you mentioned Qt 5.4.1?

**Comment by peterix** [comment]
Hm. Guess I remembered the version number wrong. The machine knows better :)

**Comment by wb9688** [comment]
OK, but what's that `small` suffix?

**Comment by peterix** [comment]
Custom build without the embedded browser engine and ICU libraries. I don't use them for anything, it doesn't make sense to bundle them just because what I use was built against them.

**Comment by wb9688** [comment]
@peterix Now I'm getting the following error with both CLI and GUI:
![Screenshot](https://cloud.githubusercontent.com/assets/9780201/17508900/9a53b784-5e17-11e6-98a4-d318c4d67b81.png)
Is there a way to disable the tests?
