### ISSUE TITLE
Directly launching an instance via command line parameter --launch no longer working

### ISSUE THREAD

**Issue by p-schneider** [MultiMC/MultiMC5#1642]
System Information
-----------------------------
MultiMC version: 0.4.12-develop-806

Operating System: Windows 10 x64

Summary of the issue or suggestion:
I used to launch my game instance directly with the -l (or --launch) parameter. After a recent Update it stopped working. I think I was on 0.4.12-develop-799 before but I'm not sure about that. Launching MultiMC normally and launching the instance from there is working fine.
----------------------------------------------

What should happen:
------------------------------
The game should launch the desired Instance chosen by (-l "instance id" or "--launch "instance id").

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Have at least one Instance set up in MultiMC

2. Try to launch that instance using the -l or --launch command line parameter

3. MultiMC shows the dialog while connecting to mojang session servers (maybe 1-2 seconds), but doesn't load the game afterwards and I don't see a Minecraft related process in the task manager.

Suspected cause:
---------------------------
one of the latest changes, from within the past few weeks, mabye days

Logs/Screenshots:
----------------------------
https://gist.github.com/p-schneider/7a75660dec403b360fe4d6f71759a022

**Comment by peterix** [comment]
Should be fixed in the next build (once it finishes).

It will always create an instance window that you can minimize (if you want to keep MultiMC around), or close (if you don't). The tray icon and the special handling of this window is gone.
