### ISSUE TITLE
"<PREFERREDLANGUAGE>" showing in Minecraft logs

### ISSUE THREAD

**Issue by p-schneider** [MultiMC/MultiMC5#1643]
System Information
-----------------------------
MultiMC version: `0.4.12-<PREFERREDLANGUAGE>velop-807` :-), the issue has been around for at least half a year

Operating System: shouldn't matter; Windows 10 x64

Summary of the issue or suggestion:
----------------------------------------------
Every occurrence of the 2 character long string `de`, even within other words like co**de**, is being replaced with `<PREFERREDLANGUAGE>` in the Minecraft logs. (Could be `en` or whatever for other accounts.) The readability of the logs is therefore decreased.

What should happen:
------------------------------
The preferred language should not be hidden in the logs. (Or another way should be used to only replace it where the actual preferredLanguage would be visible in the logs.)

Steps to reproduce the issue:
-------------------------------------------------------------
1. Have a Mojang account where Yggdrasil supplies the `preferredLanguage` attribute in the `user` `properties` object.

2. launch an instance of Minecraft

3. find the string `<PREFERREDLANGUAGE>` all over the logs

Suspected cause:
---------------------------
[MinecraftInstance::createLaunchTask(...) calls `process->setCensorFilter(createCensorFilterFromSession(session));`](https://github.com/MultiMC/MultiMC5/blob/bc6d1b5304f715ad0d8be27efd6630f820572da4/api/logic/minecraft/MinecraftInstance.cpp#L466)
[MinecraftInstance::createCensorFilterFromSession(...) iterates all properties for the user object (including `preferredLanguage`) and calls addToFilter(...) for each](https://github.com/MultiMC/MultiMC5/blob/bc6d1b5304f715ad0d8be27efd6630f820572da4/api/logic/minecraft/MinecraftInstance.cpp#L272-L277)

[LaunchTask::onLogLine(...) replaces the line: `line = censorPrivateInfo(line);`](https://github.com/MultiMC/MultiMC5/blob/e2f3652a0f5fc51736cbda7ac4e337a597f3aed1/api/logic/launch/LaunchTask.cpp#L194)
[LaunchTask::censorPrivateInfo(...) does the replacing according to the list that had been set by setCensorFilter(...)](https://github.com/MultiMC/MultiMC5/blob/e2f3652a0f5fc51736cbda7ac4e337a597f3aed1/api/logic/launch/LaunchTask.cpp#L116-L125)

The Yggdrasil response from https://authserver.mojang.com/refresh (and https://authserver.mojang.com/authenticate accordingly) looks like this for my account: (`"requestUser": true`)
```JSON
{
  "accessToken": "12345678987654321234567898765432",
  "clientToken": "12345678987654321234567898765432",
  "selectedProfile": {
    "id": "12345678987654321234567898765432",
    "name": "my_player_name"
  },
  "user": {
    "id": "12345678987654321234567898765432",
    "properties": [
      {
        "name": "preferredLanguage",
        "value": "de"
      }
    ]
  }
}
```
I can only test Yggdrasil with my own account, others might have preferredLanguage set to en or other values or not even have that attribute in the API response for their accounts.
I don't know how Mojang got this value (de in my case), I may have set my language to German the moment i bought Minecraft. I don't see an option on [account.mojang.com](https://account.mojang.com/me) or [minecraft.net](https://minecraft.net/de/profile/) to set it to a different language or to remove it.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
The very first lines of my log look like this (just to give an example, I think there is no need to upload a log here):
```
MultiMC version: 0.4.12-<PREFERREDLANGUAGE>velop-807

Minecraft fol<PREFERREDLANGUAGE>r is:
instances/1.10/minecraft
```

Proposed Solution:
-------------------------
`preferredLanguage` should be ignored in [MinecraftInstance::createCensorFilterFromSession (around line 275)](https://github.com/MultiMC/MultiMC5/blob/bc6d1b5304f715ad0d8be27efd6630f820572da4/api/logic/minecraft/MinecraftInstance.cpp#L275)

Additional Info:
---------------------------
A comment in #1432 shows that the `<PREFERREDLANGUAGE>` thing has been around for at least half a year.
This issue is not important, it doesn't break stuff. It just has annoyed me for quite some time and i finally took time to find the cause.
I saw the latest commit and revert for fc198dd regarding "rework of minecraft log" but that shouldn't change anything regarding `<PREFERREDLANGUAGE>` because that (reverted) commit was still using `LaunchTask::censorPrivateInfo(...)` like before.

**Comment by peterix** [comment]
I don't get this property from Mojang, so I couldn't test it.

Anyway, should be fixed in current develop builds. Please confirm.

**Comment by peterix** [comment]
So, how about now?

**Comment by p-schneider** [comment]
Much better now! Thanks for the fix.
MultiMC version: 0.4.12-**de**velop-812 no longer has `<PREFERREDLANGUAGE>` in the logs.
