### ISSUE TITLE
Mod file name in Loader Mods 

### ISSUE THREAD

**Issue by calloatti** [MultiMC/MultiMC5#1644]
## System Information

MultiMC version: 0.4.12-develop-813

Operating System:Windows 7 
## Summary of the issue or suggestion:

Add a "File Name" column to the "Loader Mods" screen in the "Edit Instance" window.

Right now the only columns are "Name" and "Version" and this makes it difficult to associate a jar file to a mod name when trying to update mods.

So a "File Name" column would be great.

**Comment by peterix** [comment]
Moved to workflowy: https://workflowy.com/s/2EyDMcp7CU#/c1d402342063
