### ISSUE TITLE
Main window and console window not hiding on game start

### ISSUE THREAD

**Issue by ChrisLane** [MultiMC/MultiMC5#1645]
## System Information

MultiMC version: 0.4.12-develop-768

Operating System: Arch Linux - (Linux 4.7-1)
## Summary of the issue or suggestion:

Both the main MultiMC window and console window are still present after an instance has been started.

The option "Show console while the game is running?" is unchecked.
## What should happen:

I expect at least the console window to disappear when the game is running due to the "Show console while the game is running?" setting being unchecked.

In Windows, the main menu also disappears when the game is running and so I was also expecting this behaviour.
## Steps to reproduce the issue (Add more if needed):
1. Extract MultiMC files.
2. Run MultiMC.
3. Uncheck "Show console while the game is running?" in the settings.
4. Run an instance and watch the console never disappear.
## Suspected cause:

No idea.
## Logs/Screenshots:

http://paste.ee/p/RBVAA

**Comment by peterix** [comment]
Works as intended right now. The whole thing is changing and you are on `develop`, so you get to see it as it happens :)

The intention is to have tabs for instance windows, much like browser tabs, and have the main window always around. You may have noticed that you can have multiple instance windows open now, along with the main window. You may have also noticed that you can close the whole thing and it keeps Minecraft running.

The ultimate goal is to make MultiMC close completely if you have that option on, and to reattach and fetch logs from Minecraft if you open it again.

Not every option will work at all times. I will fix small details like this later.

**Comment by peterix** [comment]
See:
https://workflowy.com/s/2EyDMcp7CU#/c7ee0438e25a

**Comment by ChrisLane** [comment]
Awesome. Thanks for responding 👍

On 16 Aug 2016, at 01:30, "Petr Mrázek" <notifications@github.com<mailto:notifications@github.com>> wrote:

Closed #1645<https://github.com/MultiMC/MultiMC5/issues/1645>.

**Comment by peterix** [comment]
This should now be fixed.
