### ISSUE TITLE
Process Exited with -1 code once again...

### ISSUE THREAD

**Issue by SPACEFACE2394** [MultiMC/MultiMC5#1647]
i only have have two mods and it won't work... very odd...
Code:http://paste.ee/p/wkRgt# website

MultiMC version: 0.4.11-751Minecraft folder is:instances/RyanCraft 1.0.0/minecraftJava path is:C:/ProgramData/Oracle/Java/javapath/java.exeJava Arguments:[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -jar, C:/Users/Caldwell family/Documents/MultiMC/jars/NewLaunch.jar]Minecraft process ID: 6692Using onesix launcher.Main Class:  net.minecraft.launchwrapper.LaunchNative path:  C:/Users/Caldwell family/Documents/MultiMC/instances/RyanCraft 1.0.0/nativesTraits:  []Libraries:  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1558-1.7.10/forge-1.7.10-10.13.4.1558-1.7.10-universal.jar  C:/Users/Caldwell family/Documents/MultiMC/versions/1.7.10/1.7.10.jarMods:  weaponmod-1.14.3  OptiFine_1.7.10_HD_U_A4Params:  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, C:/Users/Caldwell family/Documents/MultiMC/instances/RyanCraft 1.0.0/minecraft, --assetsDir, C:/Users/Caldwell family/Documents/MultiMC/assets, --assetIndex, 1.7.10, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {}, --userType, mojang, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]Window size: 854 x 480Preparing native libraries...Extracting twitch-platform-5.16-natives-windows-32.jarExtracting twitch-external-platform-4.5-natives-windows-32.jarExtracting jinput-platform-2.0.5-natives-windows.jarExtracting lwjgl-platform-2.9.1-natives-windows.jar[19:03:06] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker[19:03:06] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker[19:03:06] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker[19:03:06] [main/INFO]: Forge Mod Loader version 7.99.36.1558 for Minecraft 1.7.10 loading[19:03:06] [main/INFO]: Java is Java HotSpot(TM) Client VM, version 1.8.0_91, running on Windows 10:x86:10.0, installed at C:\Program Files (x86)\Java\jre1.8.0_91[19:03:06] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.7.10_HD_U_A4.jar[19:03:06] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker[19:03:06] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker[19:03:06] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker[19:03:06] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker[19:03:06] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker[19:03:06] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker[19:03:06] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: acceptOptions[19:03:06] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: injectIntoClassLoader[19:03:07] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ClassTransformer[19:03:07] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine URL: file:/C:/Users/Caldwell%20family/Documents/MultiMC/instances/RyanCraft%201.0.0/minecraft/mods/OptiFine_1.7.10_HD_U_A4.jar[19:03:07] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ZIP file: java.util.zip.ZipFile@145e5c6[19:03:07] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper[19:03:11] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557[19:03:11] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc[19:03:11] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper[19:03:11] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker[19:03:13] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker[19:03:13] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker[19:03:13] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: getLaunchArguments[19:03:13] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}[19:03:15] [main/INFO]: Setting user: <PROFILE NAME>[19:03:19] [Client thread/INFO]: LWJGL Version: 2.9.1[OptiFine] [OptiFine] OptiFine_1.7.10_HD_U_A4[OptiFine] Fri Aug 19 19:03:21 MDT 2016[OptiFine] OS: Windows 10 (x86) version 10.0[OptiFine] Java: 1.8.0_91, Oracle Corporation[OptiFine] VM: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation[OptiFine] LWJGL: 2.9.1[OptiFine] OpenGL: AMD Radeon HD 8240 version 4.5.13399 Compatibility Profile Context 15.200.1060.0, ATI Technologies Inc.[OptiFine] OpenGL Version: 4.0[OptiFine] OpenGL Fancy fog: Not available (GL_NV_fog_distance)[OptiFine] Maximum texture size: 8192x8192[OptiFine] Checking for new version[OptiFine] Version found: D6[19:03:22] [Client thread/INFO]: Forge Mod Loader has detected optifine OptiFine_1.7.10_HD_U_A4, enabling compatibility features[19:03:23] [Client thread/INFO]: Attempting early MinecraftForge initialization[19:03:23] [Client thread/INFO]: MinecraftForge v10.13.4.1558 Initialized[19:03:23] [Client thread/INFO]: Replaced 183 ore recipies[19:03:23] [Client thread/INFO]: Completed early MinecraftForge initialization[19:03:23] [Client thread/INFO]: Found 0 mods from the command line. Injecting into mod discoverer[19:03:23] [Client thread/INFO]: Searching C:\Users\Caldwell family\Documents\MultiMC\instances\RyanCraft 1.0.0\minecraft\mods for mods[19:03:48] [Client thread/INFO]: Forge Mod Loader has identified 4 mods to load[19:03:49] [Client thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge, weaponmod] at CLIENT[19:03:49] [Client thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge, weaponmod] at SERVER[19:03:50] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Balkon's WeaponMod[19:03:50] [Client thread/INFO]: Processing ObjectHolder annotations[19:03:50] [Client thread/INFO]: Found 341 ObjectHolder annotations[19:03:50] [Client thread/INFO]: Identifying ItemStackHolder annotations[19:03:50] [Client thread/INFO]: Found 0 ItemStackHolder annotations[19:03:50] [Client thread/INFO]: Configured a dormant chunk cache size of 0[19:03:51] [Client thread/INFO]: Applying holder lookups[19:03:51] [Client thread/INFO]: Holder lookups applied[19:03:51] [Client thread/INFO]: Injecting itemstacks[19:03:51] [Client thread/INFO]: Itemstack injection complete[OptiFine] *** Reloading textures ***[OptiFine] Resource packs: Default[19:03:51] [Sound Library Loader/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: [19:03:51] [Sound Library Loader/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...[19:03:51] [Thread-7/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL[19:03:51] [Thread-7/INFO]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005[19:03:51] [Thread-7/INFO]: [paulscode.sound.SoundSystemLogger:errorMessage:131]: Error in class 'LibraryLWJGLOpenAL'[19:03:51] [Thread-7/INFO]: [paulscode.sound.SoundSystemLogger:errorMessage:132]:     Unable to initialize OpenAL.  Probable cause: OpenAL not supported.[19:03:51] [Thread-7/INFO]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     ERROR MESSAGE:[19:03:51] [Thread-7/INFO]: [paulscode.sound.SoundSystemLogger:message:69]:         Could not locate OpenAL library.[19:03:51] [Thread-7/INFO]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     STACK TRACE:[19:03:51] [Thread-7/INFO]: [paulscode.sound.SoundSystemLogger:message:69]:         org.lwjgl.openal.AL.create(AL.java:151)[19:03:51] [Thread-7/INFO]: [paulscode.sound.SoundSystemLogger:message:69]:         org.lwjgl.openal.AL.create(AL.java:102)[19:03:51] [Thread-7/INFO]: [paulscode.sound.SoundSystemLogger:message:69]:         org.lwjgl.openal.AL.create(AL.java:201)[19:03:51] [Thread-7/INFO]: [paulscode.sound.SoundSystemLogger:message:69]:         paulscode.sound.libraries.LibraryLWJGLOpenAL.init(LibraryLWJGLOpenAL.java:164)[19:03:51] [Thread-7/INFO]: [paulscode.sound.SoundSystemLogger:message:69]:         paulscode.sound.SoundSystem.CommandNewLibrary(SoundSystem.java:1576)[19:03:51] [Thread-7/INFO]: [paulscode.sound.SoundSystemLogger:message:69]:         paulscode.sound.SoundSystem.CommandQueue(SoundSystem.java:2572)[19:03:51] [Thread-7/INFO]: [paulscode.sound.SoundSystemLogger:message:69]:         paulscode.sound.CommandThread.run(CommandThread.java:121)[19:03:52] [Sound Library Loader/INFO]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     ERROR MESSAGE:[19:03:52] [Sound Library Loader/INFO]: [paulscode.sound.SoundSystemLogger:message:69]:         Could not locate OpenAL library.[19:03:52] [Sound Library Loader/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: [19:03:52] [Sound Library Loader/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...[19:03:52] [Thread-9/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: Switching to No Sound[19:03:52] [Thread-9/INFO]: [paulscode.sound.SoundSystemLogger:message:69]:     (Silent Mode)[19:03:52] [Sound Library Loader/INFO]: [paulscode.sound.SoundSystemLogger:message:69]: [19:03:52] [Sound Library Loader/INFO]: Sound engine started[19:03:54] [Client thread/INFO]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----// Sorry :(Time: 8/19/16 7:03 PMDescription: Initializing gamejava.lang.NoSuchMethodError: net.minecraft.client.renderer.texture.TextureMap.<init>(ILjava/lang/String;Z)V	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:540)	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)	at net.minecraft.client.main.Main.main(SourceFile:148)	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)	at java.lang.reflect.Method.invoke(Unknown Source)	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)	at java.lang.reflect.Method.invoke(Unknown Source)	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)	at org.multimc.EntryPoint.listen(EntryPoint.java:170)	at org.multimc.EntryPoint.main(EntryPoint.java:54)A detailed walkthrough of the error, its code path and all known details is as follows:----------------------------------------------------------------------------------------- Head --Stacktrace:	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:540)-- Initialization --Details:Stacktrace:	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)	at net.minecraft.client.main.Main.main(SourceFile:148)	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)	at java.lang.reflect.Method.invoke(Unknown Source)	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)	at java.lang.reflect.Method.invoke(Unknown Source)	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)	at org.multimc.EntryPoint.listen(EntryPoint.java:170)	at org.multimc.EntryPoint.main(EntryPoint.java:54)-- System Details --Details:	Minecraft Version: 1.7.10	Operating System: Windows 10 (x86) version 10.0	Java Version: 1.8.0_91, Oracle Corporation	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation	Memory: 214246576 bytes (204 MB) / 519110656 bytes (495 MB) up to 1037959168 bytes (989 MB)	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_A4 4 mods loaded, 4 mods active	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 	UCH	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 	UCH	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) 	Launched Version: MultiMC5	LWJGL: 2.9.1	OpenGL: AMD Radeon HD 8240 GL version 4.5.13399 Compatibility Profile Context 15.200.1060.0, ATI Technologies Inc.	GL Caps: Using GL 1.3 multitexturing.Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.Anisotropic filtering is supported and maximum anisotropy is 16.Shaders are available because OpenGL 2.1 is supported.	Is Modded: Definitely; Client brand changed to 'fml,forge'	Type: Client (map_client.txt)	Resource Packs: []	Current Language: English (US)	Profiler Position: N/A (disabled)	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used	Anisotropic Filtering: Off (1)[19:03:54] [Client thread/INFO]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Caldwell family\Documents\MultiMC\instances\RyanCraft 1.0.0\minecraft\crash-reports\crash-2016-08-19_19.03.54-client.txtProcess exited with code -1.Clipboard copy at: 19 Aug 2016 19:04:03 -0600MultiMC: Log upload triggered at: 19 Aug 2016 19:04:08 -0600

**Comment by QuImUfu** [comment]
This is caused by your old and not supported OptiFine version, get the newest for you MC-version [here](http://optifine.net/downloads).

**Comment by SPACEFACE2394** [comment]
I have a quick question for you that doesn't have any code. I'm trying to add a account but when i press OK it says in red letters above the fill-out things it says: Authentication server didn't specify a currently specified profile. and more but i think that all that is valuable, Thanks!

**Comment by QuImUfu** [comment]
1. you should open a new issue, and close this one if the newer OptiFine version fixed you first problem.
 2. your issue about your second problem should include a Screenshot and the "MultiMC-0.log" file in you MultiMC-Folder.

**Comment by SPACEFACE2394** [comment]
Thanks!
