### ISSUE TITLE
SSL handshake failed Windows

### ISSUE THREAD

**Issue by pknova** [MultiMC/MultiMC5#1648]
I'm using version 0.4.11 and this is also happening to me. It was working fine for me until today when it kept asking me to login offline. I first changed my proxy to 'none'. When that didn't work I deleted my minecraft account and attempted to add it again and that's when I got this error message.

**Comment by techmage528** [comment]
same thing can only cannot login or chose version above 1.5.2

**Comment by peterix** [comment]
You do not have a working, unfiltered network connection...
