### ISSUE TITLE
Some bugs with the new separate instance window

### ISSUE THREAD

**Issue by QuImUfu** [MultiMC/MultiMC5#1652]
System Information
-----------------------------
MultiMC version:
"0.4.12-develop-771"

Operating System:
GNU/Linux Lubuntu 64 bit

Summary of the issues:
----------------------------------------------
Issue 1: changes in the Instance settings tab (e.g. Java memory) will be applied when the instance window is closed and reopened and not instantly. (example: If you change your memory setting to something else, and then press launch, the instance gets started with the previous memory setting.) 

Issue 2: a rather minor bug, when you close the game and the instance window the play button does not get re-enabled and still is grayed out. To make it available again you have to switch to a different Instance and back.

Suspected cause:
---------------------------
Issue 1: The settings get saved only on closing the instance window, not on pressing the Launch-Button, too.  
Issue 2: No idea. Probably Herobrine.

Logs/Screenshots:
----------------------------
Issue 1: No Logs/informative screenshots possible.  
Issue 2: No Logs. Screenshot: ![2016-08-23-092412_1280x1024_scrot](https://cloud.githubusercontent.com/assets/9885301/17883595/b97fcd26-6913-11e6-8fd6-7c73dce4db82.png)

**Comment by peterix** [comment]
OK. Added to https://workflowy.com/s/2EyDMcp7CU#/c7ee0438e25a

**Comment by peterix** [comment]
Should be fixed. Reopen if you disagree :)

I also made it save when you launch from the main window and have the instance window open.

**Comment by peterix** [comment]
Actually, first issue is fixed, I split this in workflowy, but not here...

**Comment by peterix** [comment]
Alright. Now it should be done.
