### ISSUE TITLE
New option(?) "don't modify minecraft.jar"

### ISSUE THREAD

**Issue by filip3712** [MultiMC/MultiMC5#1654]
System Information
-----------------------------
MultiMC version: 0.4.12-develop-817
Operating System: Windows 10

Summary of the issue or suggestion: 
----------------------------------------------
Add new checkbox in options instances "Modify minecraft.jar: Yes/No"

What should happen: 
------------------------------
I play on minecraft server what need his own build "minecraft.jar"(antycheat) and when i add this minecraft.jar now to MultiMC, program modifying minecraft.jar(md5 this "antycheat" can't change because can't join server)

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch MultiMC
2. Select instance
3. Click "Settings Instance" and "Java" 
4. And Check or Uncheck "Modifying .jar"

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------

Additional Info:
---------------------------

**Comment by peterix** [comment]
Can you give me a link to this thing?

**Comment by filip3712** [comment]
This "AntyCheat" minecraft.jar? Sure, this is official link to this pack:
http://blazingpack.pl/
This pack can't modify in anything possible(can't change MD5 this file)

Sorry for my english, not for good :/
Thanks for answer :)

**Comment by peterix** [comment]
This thing has a zero chance of working in MultiMC and many different configurations of the vanilla launcher.

Just reading its decompiled code:
* It replaces Mojang's AuthLib, which is very suspect. Maybe breaking auth. Maybe stealing legitimate sessions.
* Its logic for locating game folders is entirely wrong - you cannot use it with any other game folder than `~/.minecraft`.
* It auto-updates, which I will not allow in MultiMC.
* The `blazingpack_1.7.10App.jar` is heavily obfuscated = too hard to read for me to tell what it does.
* It includes a significant portion of the vanilla game code, but recompiled. This likely breaks the Minecraft EULA. This isn't a major point... a lot of other things do and Mojang AFAIK does nothing about it. See relevant excerpt:

> # ONE MAJOR RULE
> The one major rule is that you must not distribute anything we've made unless we specifically agree to it. By "distribute anything we've made" what we mean is:
> 
> * give copies of our Game to anyone else;
> * ...
> 
> unless we specifically agree to it. And so that we are crystal clear, "the Game" or "what we have made" includes, but is not limited to, the client or the server software for our Game and includes Minecraft Pocket Edition on all platforms. It also includes updates, patches, downloadable content, add-ons, or modified versions of a Game, part of those things, or anything else we've made.

I would call it dangerous until proven safe. I will not support it. I would suggest not using it. There are many other packs which do none of this nonsense.

**Comment by peterix** [comment]
If you want, you could try using the 'App' part as a jar mod. In a sandboxed environment like a throw-away virtual machine.
