### ISSUE TITLE
Multimc cant find codechickenlib

### ISSUE THREAD

**Issue by trotzor** [MultiMC/MultiMC5#1655]
System Information
-----------------------------
MultiMC version: 4.11-751

Operating System: Windows 7

Summary of the issue or suggestion:
----------------------------------------------
after importing "Project Ozone 2 - reloaded" to multimc from curse, minecraft crashes on launch.
The proper forge version is installed, as is the mod Codechickenlib, which is mentioned in the crash log.

Logs/Screenshots:
----------------------------
http://paste.ee/p/HaPNN

Additional Info:
---------------------------
The modpack works fine from curse... I'm probably missing something silly, but for the life of me, I cannot find what it might be. :(

**Comment by peterix** [comment]
No. That pack can't find its own butt :)

Delete the 1.7.10 folder in the mods folder. Delete any instance of codechickenlib you find.

**Comment by trotzor** [comment]
After actually sleeping for a night, I found that deleting Codechickenlib and reinstalling codechickencore did the trick! I knew it was something silly :P
