### ISSUE TITLE
MultiMC not recognizing snapshot versions of liteloader even when they are in the versions.json manifest file.

### ISSUE THREAD

**Issue by chexo3** [MultiMC/MultiMC5#1660]
System Information
-----------------------------
MultiMC version: 0.4.11-751 on win32 

Operating System: 64 bit Windows 10 (Not sure why it says I'm on win32, probably a 32 bit binary)

Summary of the issue or suggestion: It says there are no 1.10.2 versions of liteloader available, without listing snapshot versions. Even when the versions.json file contains an entry for 1.10.2, which both the file I downloaded from liteloader.com and that was already with MultiMC have. 
----------------------------------------------

What should happen: It should list snapshot versions.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Attempt to create an instance with liteloader on 1.10.2.
2. Dialog box says no versions for 1.10.2.

I know it looks somewhat stupid, but this is all I have.

Suspected cause:
---------------------------
Parsing error, or intentionally hardcoded for some reason. (But why? Just add a warning.)

Logs/Screenshots:
----------------------------
Could not figure out how to upload MultiMC logs instead of minecraft logs, will manually paste and link. https://paste.ee/r/fVxVV

Additional Info:
---------------------------
If this intentionally disallowed, please explain why.

**Comment by peterix** [comment]
This is already done, use develop version of MultiMC.

**Comment by chexo3** [comment]
ok

**Comment by chexo3** [comment]
ok

**Comment by chexo3** [comment]
ok
