### ISSUE TITLE
Oversized instance icons can cause failure

### ISSUE THREAD

**Issue by DDzwiedziu** [MultiMC/MultiMC5#1663]
## System Information

MultiMC version: 0.4.11 (with libxcb.so.1 linked from OS)

Operating System: Kubuntu 16.04
## Summary of the issue or suggestion:

Other packs run fine, this one with the icon implodes.
## What should happen:

Click mouse - run modpack
## Steps to reproduce the issue (Add more if needed):
1. Download Vazkii's curse downloader https://github.com/Vazkii/CMPDL/releases
2. Use it to download https://minecraft.curseforge.com/projects/universal-interdimensional-escape
3. Make an empty 1.7.10 instance, install Forge (the downloader tells the version required)
4. Run the instance once and quit.
5. Locate the directory made by the downloader, and copy it's contents into the instance folder. Bluntly overwrite the contents.
6. Download the pack icon from the page on curse (hint:  use your browser's dev tools). Rename it to the pack name (with spaces or without, removing the spaces doesn't change the result).
7. Click on the default icon in the right-hand column to change it. Add new, select the downloaded image. Re-select it in the icon chooser. Accept it.
8. Try to run the pack. MultiMC implodes with the log below.
## Suspected cause:

Packaged libs, duh /s

Image thingamajig.
## Logs/Screenshots:

```
  204.692 W QWidget::setLayout: Attempting to set QLayout "" on ConsoleWindow "", which already has a layout
  204.727 D Task succeeded
  204.727 D Task succeeded
  204.727 D Task succeeded
  204.727 D Instance either provides a version file or doesn't need an update.
  204.727 D "Universal: Interdimensional Escape" : downloading libraries
  204.727 W Order file doesn't exist. Ignoring.
  204.727 D Reading "net.minecraftforge.json"
  204.728 D "Libraries for instance Universal: Interdimensional Escape"  started.
  204.729 W The X11 connection broke: Maximum allowed requested length exceeded (code 4)
XIO:  fatal IO error 2 (Nie ma takiego pliku ani katalogu) on X server ":0"
      after 3648 requests (3648 known processed) with 0 events remaining.
```
## Additional Info:

Message if you would like to receive the ready pack (do not want to publicly redistribute it).

**Comment by QuImUfu** [comment]
Can confirm and reproduce. 
Happens if the picture is to big, not connected to the modpack. 
4096x4096 px seems to be to much, the same picture resized to 1024x1024 does work.

**Comment by Wealthyturtle** [comment]
Lel

**Comment by Janrupf** [comment]
Since this is getting attention again, I want to note that I don't know if this actually classifies as a Qt, MultiMC or X11 bug/limitation. Because it looks like its X11 having issues here, maybe its a Xorg limitation or just a X11 limitation in the protocol.

**Comment by peterix** [comment]
Practically, we shouldn't keep 2000x2000 bitmaps around in memory to paint 64x64 icons with them. That's just dumb.
