### ISSUE TITLE
Error Code (-)1?

### ISSUE THREAD

**Issue by GarebearNF** [MultiMC/MultiMC5#1664]
System Information
-----------------------------
MultiMC version: 5

Operating System: Windows 10

Summary of the issue or suggestion: 
----------------------------------------------
Upon trying to re-log into a created world that was worked in, the game crashes with the last line reading "Process exited with code -1."

What should happen: 
------------------------------
The world works when I originally create it, it's only when trying to re-access the world that it crashes.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create instance containing the following mods:
Pixelmon 4.30 Beta 8
Optifine 1.89
MrCrayfish's Furniture Mod 4.0.1
Decocraft 2.3.3
More Player Models 1.8.9

2. Create a new world.

3. Exit to main screen and re-enter world.

Suspected cause:
---------------------------
I think there may just be a mod conflict somewhere in the background.

Logs/Screenshots:
----------------------------
http://paste.ee/p/ZJuWK

Additional Info:
---------------------------

**Comment by peterix** [comment]
Definitely a mod problem... happening during world loading. It is not related to MultiMC.

**Comment by QuImUfu** [comment]
This is a conflict between pixelmon and one of the other mods (had no time to figure out witch mod exactly) at world creation (they a creating a corrupted world file).
Workaround:
Start world with only pixelmon activated, then add all the other mods. (or first the others than Pixelmon)

**Comment by yunusemresteel** [comment]
The game mode is not loaded, the world does not turn directly closes. no solution to the error code -1. (Translation: google translation)

**Comment by khionu** [comment]
Error Code -1 means the process closed in an errored state. Nothing more.

A work around was found, that should be sufficient, as long as @GarebearNF can verify that this issue is over. Even so, it's not a MultiMC issue.

**Comment by GarebearNF** [comment]
Yes, the work around worked. This is no longer is an issue. Thanks.

Sent from my iPhone

On Oct 6, 2016, at 6:01 PM, Khionu Sybiern <notifications@github.com<mailto:notifications@github.com>> wrote:


Error Code -1 means the process closed in an errored state. Nothing more.

A work around was found, that should be sufficient, as long as @GarebearNF<https://github.com/GarebearNF> can verify that this issue is over. Even so, it's not a MultiMC issue.

-
