### ISSUE TITLE
MultiMC Not Opening

### ISSUE THREAD

**Issue by Heardy92** [MultiMC/MultiMC5#1665]
## System Information

MultiMC version: 5

Operating System: Mac OS 10.12 Beta
## Summary of the issue or suggestion:

When opening MultiMC, it closes straight away and gives an error message.
## What should happen:

It should open.
## Steps to reproduce the issue (Add more if needed):
1. Open MultiMC.
2. Error Message
## Suspected cause:

Not suitable for 10.12 Beta maybe?
## Logs/Screenshots:

http://paste.ee/r/3k37D
http://imgur.com/a/45r4U

**Comment by PRSop2000** [comment]
I'm having the same issue on the official release of macOS Sierra 

App will instantly crash with this error: http://paste.ee/p/n6y34

**Comment by nate2014jatc** [comment]
Bumping this, friend of mine is also having issues

**Comment by peterix** [comment]
Can you look at the log file?It should be in the `.app`.

Let's say you have it in `/Volumes/VOLUME/*/MultiMC.app`
Then the log file should be in `/Volumes/VOLUME/*/MultiMC.app/Contents/MacOS/MultiMC.0.log`

Is there a lot of repeating messages in the log?

**Comment by peterix** [comment]
As a workaroud, it seems that putting it in /Applications stops this from happening.

**Comment by peterix** [comment]
When ran from a terminal, it seems that it has no issues no matter where it is. Starting it using the icon fails...

**Comment by peterix** [comment]
Well, those don't help.

But if I take the `.app` and move it to Applications, it works. It also still work when I move it back to wherever it was originally extracted...

So moving the `.app` magically fixes it. I think the OS is doing something wrong until the `.app` is marked somehow.

**Comment by peterix** [comment]
Bad news, I cannot fix this. It's not a problem in the code, it's 10.12 breaking non-signed applications.

Take the tarball from the website:
https://files.multimc.org/downloads/mmc-stable-osx64.tar.gz

Double clicking it will extract it. If you probe the extracted files with `xattr -l MultiMC.app`, you get something like this:
```
MultiMC.app: com.apple.quarantine: 0081;581218d7;Google\x20Chrome;891952EC-07FB-4A51-B3C9-EEE1FE9E3662
MultiMC.app/Contents: com.apple.quarantine: 0081;581218d7;Google\x20Chrome;891952EC-07FB-4A51-B3C9-EEE1FE9E3662
MultiMC.app/Contents/Frameworks: com.apple.quarantine: 0081;581218d7;Google\x20Chrome;891952EC-07FB-4A51-B3C9-EEE1F
```

In this state, the application will not run hen clicked.
If you right click and `Open` in Finder, the application will get different attrs (`00c1`):
```
MultiMC.app: com.apple.quarantine: 00c1;581218d7;Google\x20Chrome;891952EC-07FB-4A51-B3C9-EEE1FE9E3662
MultiMC.app/Contents: com.apple.quarantine: 00c1;581218d7;Google\x20Chrome;891952EC-07FB-4A51-B3C9-EEE1FE9E3662
MultiMC.app/Contents/Frameworks: com.apple.quarantine: 00c1;581218d7;Google\x20Chrome;891952EC-07FB-4A51-B3C9-EEE1FE9E3662
```
In this state, the application is crippled by the OS and does not work (crashes).

After you move it to `/Applications` or `~/Applications`, it gets a different attr set:
```
MultiMC.app: com.apple.quarantine: 01c1;581218d7;Google\x20Chrome;891952EC-07FB-4A51-B3C9-EEE1FE9E3662
MultiMC.app/Contents: com.apple.quarantine: 00c1;581218d7;Google\x20Chrome;891952EC-07FB-4A51-B3C9-EEE1FE9E3662
MultiMC.app/Contents/Frameworks: com.apple.quarantine: 00c1;581218d7;Google\x20Chrome;891952EC-07FB-4A51-B3C9-EEE1FE9E3662
```
At this point, the application works and is no longer crippled.

I was able to short circuit the whole process by using the following command:
```
xattr -wr  com.apple.quarantine '01c1;581218d7;Google\x20Chrome;891952EC-07FB-4A51-B3C9-EEE1FE9E3662' MultiMC.app
```
The application runs after this...

**Comment by Orcinuss** [comment]
Here is a fix for mac users:
https://www.tekrevue.com/tip/gatekeeper-macos-sierra/

**Comment by peterix** [comment]
It now tells you what to do instead of crashing. I consider this fixed.
