### ISSUE TITLE
Cannot get game past Forge step 5/7!

### ISSUE THREAD

**Issue by WingedBoots** [MultiMC/MultiMC5#1669]
## System Information

MultiMC version: 5

Operating System: Windows 7
## Summary of the issue or suggestion:

Forge loads all mods and gets through initialization, but right when it gets to 5/7, I get an error and it shuts down. It says Process exited with code -1. I had Buildcraft installed and that was causing problems so I uninstalled that. I also had an issue with it not reading the newest MrTJPCore for Project RED, so I installed an older version and that went through fine. But now it won't get past the initialization steps.
It would be greatly appreciated if you could help me with this. :)
## Logs/Screenshots:

http://paste.ee/p/AY7L4

Edit: Removed Runic Dungeons which was causing the duplicate enchantment id. Made it to the main menu, we'll see what happens from here.

**Comment by jikuja** [comment]
Did you fix Duplicate enchantment id after adding mod?

**Comment by WingedBoots** [comment]
I wasn't sure how to do that.

**Comment by Heufneutje** [comment]
A lot of mods that come with enchantment IDs allow you to modify them through their config files. If they don't provide that option you'll have to inform the mod authors about it.
