### ISSUE TITLE
MultiMC error 1

### ISSUE THREAD

**Issue by Kavexx** [MultiMC/MultiMC5#1672]
System Information
-----------------------------
MultiMC version: Last version (0.4.11)

Operating System: Windows 8.1 64 bit

Summary of the issue or suggestion:
----------------------------------------------
My MultiMC have error 1when I want to play

What should happen:
------------------------------
Minecraft shoulp be open with MultiMC

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. I click on the buton play in MultiMC

2. Logs appaers with the error 1

Suspected cause: conflict between mods
---------------------------

Logs/Screenshots:
----------------------------
http://paste.ee/p/9z7qh

Additional Info:
---------------------------

**Comment by peterix** [comment]
Looking at the mod list, you have duplicated mods. Remove or disable the mod versions you don't intend to use.

**Comment by Kavexx** [comment]
Thanks, it working without the duplicated mods but I have forgotten to add DamageIndicators and now same error.

**Comment by jikuja** [comment]
Are you 100% it's same error? new log?

**Comment by Kavexx** [comment]
I d'ont understand, I have retry to start with DamageIndicators and this time it working.
