### ISSUE TITLE
MultiMC error 255

### ISSUE THREAD

**Issue by Kavexx** [MultiMC/MultiMC5#1673]
System Information
-----------------------------
MultiMC version: Last version (0.4.11)

Operating System:Windows 8.1 64bit

Summary of the issue or suggestion:
----------------------------------------------
When opening MultiMC and I play with it, I can play but I can't hit anything. 

What should happen:
------------------------------
I should play without crash.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.I play with MultiMC

2.I can step in the world 

3.I hit something and crash

Suspected cause:
---------------------------
Java out of memory

Logs/Screenshots:
----------------------------
http://paste.ee/p/Ahxqe

**Comment by MajorGeneralRelativity** [comment]
What amount of RAM do you have allocated?

**Comment by jikuja** [comment]
Did you try increasing memory allocation? If not was there a problem which prevented the change? 

Are you using 64-bit java? If not install it and configure MMC to use it.

**Comment by deframet** [comment]
Operating System: Windows 8.1 **(x86)** version 6.3
We can't do anything

**Comment by jikuja** [comment]
Not 100% sure, please see: https://blogs.oracle.com/DieterDeramoudt/entry/beware_when_detecting_32_and for reference.

**Comment by deframet** [comment]
I didn't know about that, still I would not recommend playing with only 1gb

**Comment by MajorGeneralRelativity** [comment]
Yeah, but he may not have known that

**Comment by Kavexx** [comment]
Memory allocated: 2048 MB

**Comment by MajorGeneralRelativity** [comment]
Not according to that log

**Comment by Kavexx** [comment]
Sorry, When I change the allocated memory I have crash

**Comment by MajorGeneralRelativity** [comment]
Crashlog when you have 2GB allocated?

**Comment by Kavexx** [comment]
When I have 1024 MB

**Comment by Kavexx** [comment]
And if I change for add MB I have crash

**Comment by MajorGeneralRelativity** [comment]
Can you please post the crashlog for when you allocate more RAM?

**Comment by Kavexx** [comment]
http://paste.ee/p/unLSN

**Comment by MajorGeneralRelativity** [comment]
You only allocated 1.1 GB of RAM, and it is still running out of RAM. You need at least 1.5 GB probably

**Comment by Kavexx** [comment]
ok I test

**Comment by jikuja** [comment]
Let's recap this thing: 

Do you have 64-bit java installed or not? Did you try installing and using it?

Is your operating system 32-bit or 64-bit?

How much memory your machine has?

**Comment by Kavexx** [comment]
http://paste.ee/p/H2XjX
crash

**Comment by MajorGeneralRelativity** [comment]
@Kavexx do you have 64-bit java? If no, you probably need it

**Comment by Kavexx** [comment]
I have Java 32 bit b

**Comment by deframet** [comment]
How much RAM do you have?

**Comment by QuImUfu** [comment]
Kavexx is using 32 bit Java on 32 bit windows. He can't use 64 bit Java. I also want to know how much ram Kavexx has. 1.5 GB should work on 32 bit if he has enough ram (left).

**Comment by MajorGeneralRelativity** [comment]
@QuImUfu As previously mentioned further up in the thread, he does not necessarily have 32 bit windows. JVM os identification is bad

**Comment by deframet** [comment]
@jikuja thinks Java misdetected the os arch

**Comment by jikuja** [comment]
> Kavexx is using 32 bit Java on 32 bit windows. 

Do you know something we don't? I already gave a link which explains why java reports wrong OS bitness information.

**Comment by MajorGeneralRelativity** [comment]
Plus, he says he has 64 bit Windows

Operating System:Windows 8.1 64bit

**Comment by QuImUfu** [comment]
sorry, my bad.
windows could still be 64 bit. *shame on me*

**Comment by Kavexx** [comment]
Ok guys it working fine

**Comment by MajorGeneralRelativity** [comment]
Awesome

**Comment by QuImUfu** [comment]
if everything is working now, please close the issue.

**Comment by Kavexx** [comment]
But I don't understand why because Monday I've download Java 64bit and I was Jva 32 bit

**Comment by MajorGeneralRelativity** [comment]
Programming is magic.

**Comment by QuImUfu** [comment]
For future similar problems @Kavexx or others might run into: 
 - It maybe only works if there are few enough programs open, depending on the amount of free memory.
 - Always make sure the right version and architecture of Java is chosen in the mmc java-settings. (This might explain that mmc still used 32 bit Java although Kavexx already installed 64 bit Java.)

**Comment by Kavexx** [comment]
ok thanks
