### ISSUE TITLE
[Bug] Keep Updating Unchecked Doesn't stop updating console.

### ISSUE THREAD

**Issue by DrZed** [MultiMC/MultiMC5#1675]
MMC 5 0.4.12-617
MC 1.7.10
Java 8 u102
Windows 10 Insider Edition Professional version 14936

Unchecking "Keep Updating" doesn't stop the console logging.
http://puu.sh/rrRLV.png

**Comment by peterix** [comment]
Yeah. I also noticed. It will need to be fixed :)

**Comment by DrZed** [comment]
Thanks

**Comment by peterix** [comment]
Fixed in develop
