### ISSUE TITLE
Windows 32bit will not allow me to allocate enough Ram.

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [MultiMC/MultiMC5#1681]
System Information
-----------------------------
MultiMC version: 5

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
I would like to run a LARGE number of mods which in turn require a lot of ram, but because the only version available for Windows is the 32 bit, I can't allocate more than 1500MB of ram, which isn't enough (it's most certainly much less than I have available on my system).

What should happen:
------------------------------
I should be able to download a 64 bit version of MC for Windows and be able to allocate 6144MB of ram like Mac or Linux users can.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
I really don't think this section is necessary...

Suspected cause:
---------------------------
Ditto.

Logs/Screenshots:
----------------------------
Also superfluous.

Additional Info:
---------------------------
None.

**Comment by peterix** [comment]
You can use 64bit java.

See:
https://github.com/MultiMC/MultiMC5/wiki/Java-settings

Click the Auto-detect button and select 64bit java.
