### ISSUE TITLE
multimc shows java 32 bit in my f3 screeen, having trouble with mods could that be why

### ISSUE THREAD

**Issue by grannypatty** [MultiMC/MultiMC5#1682]
System Information
-----------------------------
MultiMC version: multi mc

Operating System windows 8.1 pro 64 bit

Summary of the issue or suggestion:
----------------------------------------------

I am having probs with different instances and just noticed today that the f3 screen shows that java is 32 bit
it says java 8.1....32 bit  is this possibly the issue that could cause crashes and even not being able to get into any games?
What should happen:
------------------------------
being able to get int the game
it not crashing once I do

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.i haven't taken any steps yet due tot he fact that I thought id better ask for help before deleting files etc

2.

3.

Suspected cause:
---------------------------

java 32 bit should be 64 bit  but I don't know how to change it or if it needs changed
Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
You have 32bit Java installed and selected in MultiMC.

If you also have a 64bit version installed, you can switch to it in the Java settings - just use the auto-detect button and select the 64bit version of Java.

If you don't have it, you can get it from the Oracle website here:
http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

Get `Windows x64 Offline` - that's the installer for the 64bit version.

**Comment by grannypatty** [comment]
where do I find the java settings? im sorry for eing such a noob//// id happily pay for help if you or someone you know could help me.. I can also open remote acces for someone to help if you know of anyone,  or you, I will pay 50 dollars for someone to set all this up for me.. please help.. granny




________________________________

**Comment by grannypatty** [comment]
in multimc where do I find the java setting to switch?

**Comment by peterix** [comment]
On the toolbar, there's an icon that opens the settings dialog (Change settings.) - normally looks like a screen and screwdriver icon.
Then switch to Java.

**Comment by peterix** [comment]
I believe this has been answered.
