### ISSUE TITLE
Multimc keeps giving me the process exited with code -1

### ISSUE THREAD

**Issue by Zavesh** [MultiMC/MultiMC5#1683]
System Information
Windows 10
16gb ram
## 8 core 3.5 ghz processor

MultiMC version: 0.4.11-751

Operating System: Windows 10
## Summary of the issue or suggestion:

When ever I use asielib - 4.5 it gives this issue I am having with multimc although when I get rid of it, multimc tells me I need it. This is of course an issue.
## What should happen:

It should except either having or not having asielib.
## Steps to reproduce the issue (Add more if needed):
1. Use all of the mods and settings
2. Click play
3. Be delightfully irritated
## Suspected cause:

Multimc has an issue accepting asielib even though it needs it
## Logs/Screenshots:

[mOybR.txt](https://github.com/MultiMC/MultiMC5/files/518761/mOybR.txt)

**Comment by QuImUfu** [comment]
1. This is an mod issue and not caused by mmc
2. You can most likely fix it by updating you mods. Some of these mod versions are antique. From the log i can only see that Thaumic Energistics was involved, maybe updating only this mod could be successful, too.

**Comment by Zavesh** [comment]
thank you seeing if it will work

**Comment by peterix** [comment]
Any news?
