### ISSUE TITLE
MultiMC's Dark theme makes white text on white buttons.

### ISSUE THREAD

**Issue by Drullkus** [MultiMC/MultiMC5#1690]
<img width="535" alt="screen shot 2016-10-21 at 9 32 50 am" src="https://cloud.githubusercontent.com/assets/5010174/19605712/8c68f16e-9771-11e6-8f73-5509877ab89e.png">

![notext](https://cloud.githubusercontent.com/assets/5010174/19605785/11953280-9772-11e6-94a5-e88e3913386a.jpg)

**Comment by peterix** [comment]
Press escape! ABORT!

**Comment by peterix** [comment]
I've made it use the Fusion theme. It's not as pretty, but the problem should be gone. Is it?

**Comment by peterix** [comment]
Already fixed in develop
