### ISSUE TITLE
Workaround for launchwrapper and forge jars order is possibly required

### ISSUE THREAD

**Issue by mezz** [MultiMC/MultiMC5#1692]
## System Information

MultiMC version: MultiMC 5 0.4.12-develop-819

Operating System: Windows 10
## Summary of the issue or suggestion:

Logs no longer show [ModName] prefixes. There is no way to tell which mod created a line logged to the console.

Example snippet:

```
[21:48:13] [Client thread/INFO]: Beginning postInit...
[21:48:13] [Client thread/INFO]: Registering plugin: mezz.jei.plugins.vanilla.VanillaPlugin ...
[21:48:14] [Client thread/INFO]: Registered  plugin: mezz.jei.plugins.vanilla.VanillaPlugin in 96 ms
```
## What should happen:

Each line should have a prefix showing which mod created the log.

Example snippet:

```
[21:48:13] [Client thread/INFO] [JEI/JEI]: Beginning postInit...
[21:48:13] [Client thread/INFO] [JEI/JEI]: Registering plugin: mezz.jei.plugins.vanilla.VanillaPlugin ...
[21:48:14] [Client thread/INFO] [JEI/JEI]: Registered  plugin: mezz.jei.plugins.vanilla.VanillaPlugin in 96 ms
```
## Steps to reproduce the issue (Add more if needed):
1. Create a new MultiMC instance.
2. Install Forge and [JEI](https://minecraft.curseforge.com/projects/just-enough-items-jei)  or any other mod that logs to console.
3. Run the game and create a new world, see the log.
## Suspected cause:

Recent reworkings of MultiMC logging.
## Logs/Screenshots:

See snippets above.
## Additional Info:

This is extremely important for solving bug reports sent to me.  
Without the prefix it is much harder and sometimes impossible to find what I'm looking for in a log.

**Comment by peterix** [comment]
That's not up to MultiMC to decide. That's all forge and the use of log4j without any sensible configuration besides classpath order and random log4j configs contained in random jars.

I have no idea what to do with this.

**Comment by mezz** [comment]
I'm sorry it's a pain, but this is not an issue with other launchers so I have to assume MultiMC is doing something different in these latest versions.

**Comment by peterix** [comment]
MultiMC prints the list of loaded jars to the log. Can you give me that, compared to some other launcher?

**Comment by peterix** [comment]
I just put forge and a few mods into 1.10 and it looks OK to me.
![image](https://cloud.githubusercontent.com/assets/203326/19612644/1370d944-97e8-11e6-93a8-e949be3eeb62.png)

**Comment by peterix** [comment]
So there must be something weird about that specific instance.

**Comment by mezz** [comment]
I apologize, I did not test a minimal setup before reporting. 
This most likely requires a specific (misconfigured?) mod.
I'll let you know when I find it.

**Comment by peterix** [comment]
Most logging issues I saw up to now were basically from unexpected changes to the classpath order and locale settings.
Log4j picks up the first config it finds... and if the order is different than expected, it can be a different config.

**Comment by mezz** [comment]
That makes sense.
I'm not able to track down the mod causing the issue, in fact I'm not sure it's a mod.
I loaded a pack instance from a zip and it has the logging issue. If I make a new MultiMC instance and copy all the same mods in, it works.

Broken instance from zip: https://gist.github.com/mezz/0de9a16bf06c7123d31b494077e9f70e
Working instance with same mods: https://gist.github.com/mezz/aa52f0766a2cdc3053b2c3efc1058478

It does look like they have different ordering.

**Comment by mezz** [comment]
In the working instance, forge is much higher in the list.

**Comment by peterix** [comment]
![image](https://cloud.githubusercontent.com/assets/203326/19612875/6faba062-97e9-11e6-8e0e-3bf4a18f580c.png)

The forge jars are backwards.

I think this is actually fixed in the develop version. If you are running that and reinstall forge, it should keep the right order.

**Comment by mezz** [comment]
Confirmed, reinstalling Forge fixed the ordering.

**Comment by peterix** [comment]
Ok, this is already fixed then :)

I want to release a new stable version soon... ideally sometime next week or the week after that.

**Comment by mezz** [comment]
Ok thanks! 
Is there any way to have MultiMC update these "legacy" packs as they are imported? This issue will most likely remain for a long time after you update. It would be nice if I could just ask people to update their MultiMC as a single step instead of also reinstalling Forge.

**Comment by peterix** [comment]
Currently, there is not. Maybe something like 'always put forge and launchwrapper jars in a defined order'... but I'm not sure if I want that in the code to be honest. I'd rather get rid of special cases than add more.

The real solution is to just say it uses 'Forge 2107' instead of embedding a whole custom forge version file. This requires the forge version files being available separately - which also means they would be fixable. It's not something I can apply retroactively though -- not without potentially breaking things.

**Comment by peterix** [comment]
I'll see how ugly the code would be :)

**Comment by peterix** [comment]
Fixed in both stable and develop now, at least when you install Forge again.

I really do not want to add any hacks for this.

Instead, I'll work on a proper solution -- do not put well known version files inside instances. I need this for importing packs and proper pack support in general anyway.

**Comment by peterix** [comment]
https://workflowy.com/s/2EyDMcp7CU#/af039d9877fa
