### ISSUE TITLE
MultiMC crashes with exitcode -1

### ISSUE THREAD

**Issue by bucko1979** [MultiMC/MultiMC5#1694]
## System Information

MultiMC version:
0.4.11-751
Operating System:
Windows 10 64-bit
## Summary of the issue or suggestion:

I load up minecraft with multiMC and the game fails to load and just crashes with exitcode -1
## What should happen:

The game should take 0-2 mins to load up and then you'll be taken to the title screen
## Steps to reproduce the issue (Add more if needed):
1. Open MultiMC
2. Create a new instance
3. Play the instance by double clicking the instance
## Suspected cause:

OpenGL
## Logs/Screenshots:

http://paste.ee/p/y9P0f
## Additional Info:

No additional info, sorry

**Comment by QuImUfu** [comment]
If you are using intel graphics than this is a duplicate of #1276.
Try the workaround mentioned in this issue.  
If you are not using an intel graphics make sure you drivers are up-to date.
