### ISSUE TITLE
Feature Request: Custom minecraft versions

### ISSUE THREAD

**Issue by MattSturgeon** [MultiMC/MultiMC5#1696]
It should be possible to create instances with a custom minecraft jar/json pair.

For example, on 2b2t it is almost manditory to play with a hacked client like Impact. This is easy with the vanilla launcher, yet almost imposible with multimc.

**Comment by peterix** [comment]
![image](https://cloud.githubusercontent.com/assets/203326/19746928/f29bbd8e-9bd8-11e6-88da-7eef04bed62f.png)

Do you really trust this?

Because I don't.

**Comment by peterix** [comment]
If you do, add it as a jar mod. But I'm not touching this mess.

**Comment by MattSturgeon** [comment]
That is called obfuscated code. I trust it as much as any other propietary code.

However it is largely irrelivant to the particular feature request. I'm confident this applies in more use cases than just my specific one.

**Comment by peterix** [comment]
It's already there. You just have to use it. Add it as a jar mod.

**Comment by MattSturgeon** [comment]
I have tried adding it as a jar mod. This does not work. Why is it not possible to simple add a new "version" with the jar and json files?

**Comment by peterix** [comment]
Why it doesn't work as a jar mod is that it uses filenames with a lot of weird characters that don't pass through MultiMC's zip library. That's the actual problem.

**Comment by MattSturgeon** [comment]
interesting. I still feel there should be a more intuative way to have custom versions, perhaps the version list should simply detect directories in the versions directory, similar to how the default launcher does. Theoretically this would bypass the zip library all together.

**Comment by peterix** [comment]
I would prefer such weird customizations to be entirely contained inside instances. This makes them portable. You can take the instance and not care if the person you got it from has a weird 'version' that you don't.

**Comment by peterix** [comment]
I guess the other problem is that I started out with the Mojang json format. It is limiting. It treats the Minecraft json as a special case, while it's a plain old library like all the other jars Minecraft is made of. The problem simply wouldn't be there if it was using the library system instead of this one-off thing.

**Comment by MattSturgeon** [comment]
Well then perhaps add a "use custom minecraft version" to the instance system. It would work similar to adding a mod, but instead simply add a new mc jar to use over the default ones, and still be portable.

To me this is more intuitive than expecting a user to know that custom versions should be added as a mod, even if they aren't actually mods. It also avoids using zip libraries to combine the jars.

An alternative would be to file bugs upstream with the zip library in question, though important, to me this feels like a seperate issue.

**Comment by peterix** [comment]
this has been since fixed. MultiMC now has a feature for replacing the main jar.

**Comment by rafalohaki** [comment]
![image](https://user-images.githubusercontent.com/20607107/217136219-46398773-746e-4991-939f-47b99319e75b.png)
its not working. tried to replace jar version. its loading but as not custom jar. there is problem with loading json file for custom jar but i cant see such an option. no problem with vanilla. tlauncher is only option from custom launcher but i dont trust it so... vanilla is only the way. If there is such an option, pls tell me. On vanilla i just create new folder in versions and its done...

**Comment by metaacalled** [comment]
We need to be able to import a custom jar with a custom JSON file. Versions come with bot.
