### ISSUE TITLE
Instances with Liteloader Fail to Launch

### ISSUE THREAD

**Issue by Orcinuss** [MultiMC/MultiMC5#1697]
## System Information

MultiMC version:
v0.4.1.2 dev 799
Operating System:
MacOS 10.12.1
## Summary of the issue or suggestion:

Instance fails to launch when Liteloader is installed using MC 1.10.2. Console returns the error found here: http://paste.ee/p/t8YxQ
## What should happen:

Instance should launch normally
## Steps to reproduce the issue (Add more if needed):
1. Create a new instance
2. Install Liteloader 1.10.2-SNAPSHOT
3. Launch Instance
## Suspected cause:

http://repo.mumfrey.com/ is not available or not a thing.
## Logs/Screenshots:

http://paste.ee/p/t8YxQ

**Comment by peterix** [comment]
```
 106.700 D Downloading  "http://dl.liteloader.com/versions/com/mumfrey/liteloader/1.10.2-SNAPSHOT/liteloader-1.10.2-SNAPSHOT.jar"
  106.700 D Download cache hit  "https://launcher.mojang.com/mc/game/1.10.2/client/dc8e75ac7274ff6af462b0dcec43c307de668e40/client.jar"
  106.738 D Following redirect to  "http://redirector.liteloader.com/snapshot/1.10.2-SNAPSHOT/jar"
  106.739 D Downloading  "http://redirector.liteloader.com/snapshot/1.10.2-SNAPSHOT/jar"
  106.739 D Download redirected: "http://redirector.liteloader.com/snapshot/1.10.2-SNAPSHOT/jar"
  106.959 D Following redirect to  "http://repo.mumfrey.com/content/repositories/snapshots/com/mumfrey/liteloader/1.10.2-SNAPSHOT/----release.jar"
  106.960 D Downloading  "http://repo.mumfrey.com/content/repositories/snapshots/com/mumfrey/liteloader/1.10.2-SNAPSHOT/----release.jar"
  106.960 D Download redirected: "http://repo.mumfrey.com/content/repositories/snapshots/com/mumfrey/liteloader/1.10.2-SNAPSHOT/----release.jar"
  107.122 C Failed  "http://repo.mumfrey.com/content/repositories/snapshots/com/mumfrey/liteloader/1.10.2-SNAPSHOT/----release.jar"  with reason  QNetworkReply::NetworkError(UnknownServerError)

```

**Comment by peterix** [comment]
It's there, but the redirects go to something that's broken. It's a server side issue, triggering a client side issue.

**Comment by RubenNL** [comment]
ok, but is it possible that its cached on the multimc server, so if 
forge/liteloader is offline, it uses the multimc server?

Verzonden met AquaMail voor Android
http://www.aqua-mail.com


Op 27 oktober 2016 20:29:15 schreef Petr Mrázek <notifications@github.com>:

**Comment by peterix** [comment]
There is no multimc server involved here. The only thing I can do is make sure that it keeps working if you already have an old liteloader snapshot jar for the same mc version.

**Comment by Orcinuss** [comment]
When you add the .json patch, could you possibly fetch the liteloader instances from their jenkins server instead?
http://jenkins.liteloader.com/job/LiteLoader%201.10.2/

**Comment by peterix** [comment]
Two issues:
* MultiMC does not prefer existing file when the remote file is no longer accessible
* Liteloader's server is somehow broken.

I'll fix the first one and I've poked Mumfrey on IRC. Hopefully he'll fix it eventually :)

**Comment by RubenNL** [comment]
its an 502 error

Verzonden met AquaMail voor Android
http://www.aqua-mail.com


Op 27 oktober 2016 20:26:59 schreef Petr Mrázek <notifications@github.com>:

**Comment by peterix** [comment]
Should work now, as long as you have the liteloader snapshot already. This brings snapshots more in line with normal downloads.

**Comment by peterix** [comment]
Rest needs to be fixed by @Mumfrey

**Comment by peterix** [comment]
Seems to be fine now!

**Comment by Mumfrey** [comment]
Sorry about that, the nexus server went down at the weekend and it took me a little while to fix it!

**Comment by peterix** [comment]
Well, I assumed you were busy. Thank you :)
