### ISSUE TITLE
Does MultiMc have a 64 bit version?  thanks in advance for any help...Granny

### ISSUE THREAD

**Issue by grannypatty** [MultiMC/MultiMC5#1698]
## System Information

MultiMC version:

Operating System:
## Steps to reproduce the issue (Add more if needed):

1.

2.

3.

**Comment by peterix** [comment]
On Windows, it doesn't need one.
On Linux, there's both a 64bit and 32bit version.
On macOS, there's only the 64bit version (32bit is not needed).
