### ISSUE TITLE
I need to remove the file libxcb.so.1 after every update for MultiMC to work

### ISSUE THREAD

**Issue by Hund** [MultiMC/MultiMC5#1699]
I'm running Arch Linux and currently version 0.4.11-703 of MultiMC.

After every update I have to manually delete the file `/bin/libxcb.so.1` from the MultiMC folder. If I don't, this is what happens:

```
$ multimc
No missing dependencies found.
/home/johan/.multimc/bin/MultiMC: symbol lookup error: /usr/lib/libX11.so.6: undefined symbol: xcb_wait_for_reply64
/home/johan/.bin/multimc: line 3: syntax error near unexpected token `fi'
/home/johan/.bin/multimc: line 3: `fi'
```

What's up?

**Comment by peterix** [comment]
Well, that's a thing. I can either include these and break some linux distributions, or not include them and breaks some other distributions.

I'm inclining towards not including any libraries and letting users install everything that's required.

Arch linux is probably the best distro for Qt compatibility and you should have no issues if only the files specific to MultiMC are kept.

However, doing this would break many old distribution versions:
https://docs.google.com/spreadsheets/d/1WsTGABWr5i243SdB7YMjbgzcMG8XdIbfZ5AYRP4x7t8/edit?usp=sharing

So, I don't really know what to do yet.

**Comment by Hund** [comment]
But the file I need to remove is provided by MultiMC?

**Comment by peterix** [comment]
yes

**Comment by Hund** [comment]
Ah, sorry. I'm tired. It took a moment to understand what I read. :D

**Comment by Hund** [comment]
But why not automatically delete the file when you update MultiMC as it just gets downloaded by itself the next time you start MultiMC?

**Comment by peterix** [comment]
Should be fixed in the new build, as soon as it finished.
