### ISSUE TITLE
cant log in

### ISSUE THREAD

**Issue by blasterdark08** [MultiMC/MultiMC5#1700]
hi i have a problem. i cant log in in multimc. everytime i log in i get : SSL Handshake failed. i dont think its my system becaus long ago it still works. but here are my specs:

Processor Intel(R) Core(TM)2 Quad CPU Q6600 @ 2.40GHz

Video Card Intel(R) G41 Express Chipset

RAM 4.0 GB

Operating System Microsoft Windows Vista Home Premium Edition Service Pack 2 (build 6002), 32-bit

 can someone help me please,

**Comment by Heufneutje** [comment]
Provide a full log, as explained in the issue template, as well as [here](https://github.com/MultiMC/MultiMC5/wiki/Log-Upload).

**Comment by QuImUfu** [comment]
@Heufneutje 
I don't think he can send a minecraft log if he can't login?
@blasterdark08 
You should upload the {MMC-Dir}/MultiMC-0.log file to a site like http://paste.ee/ . And give us the link.
You can also try to access https://authserver.mojang.com with Internet Explorer (other browsers might not use only system certificates) to make sure it is not your system's fault. (if Internet Explorer shows some sort of error message, it is your system's fault)
