### ISSUE TITLE
Insemnificant Issue | When updating one file, it says updating 1 files

### ISSUE THREAD

**Issue by vladfrangu** [MultiMC/MultiMC5#1701]
## System Information

MultiMC version: 0.4.10-develop-834

Operating System: Windows 7 Professional x64
## Summary of the issue or suggestion:

When the update box appears, if only 1 file needs to be updated, it says "Downloading 1 update files", instead of file. This isn't really an issue, but its a thing I've noticed

**Comment by KingDGrizzle** [comment]
Gonna close this as it's pretty much dead.
