### ISSUE TITLE
Mod Compatiblity Detection

### ISSUE THREAD

**Issue by StealthyExpertX** [MultiMC/MultiMC5#1704]

**Comment by StealthyExpertX** [comment]
This would show a star icon next to your mod that's in your mod manger's folder if the mod is compatible with your set up, and if it is not it would show a red X showing that its not and if it has been known to cause crashes but some times works it would have ! symbol next to it and if the Mod compatibility is unknown it would have the ? symbol to show the compatibility of this mod is unknown and if so the user could click on the question mark and submit a form to the Developers if it worked or not it would also include a log witch would be added to the form when sending that shows the mods he had installed what version ect...

This feature would be amazing and I think a lot of Minecraft Players would benefit from this and increase the amount of players that use MultiMC.

**Comment by peterix** [comment]
The amount of data I would have to collect and process on some backend server would be insane... as long as the collection is automatic, I guess that would be fine though.

On the client side, when the game {successfully loads, loads a world, connects to a server, crashes during launch, crashes after launch}, a report would be sent to some server, including the full mod list.

On the server side, it would require some heavy duty statistical model on top of a set of all mods and their involvement in crashes.

Prerequisites:
1. Mod identification based on SHA-256 hashes - done on the client in the background when MultiMC is idle
2. Something that can determine probabilities of crash of each mod based on {mod1 ... modn} -> final_state
3. Something that can do basic crash analysis to rule out false positives ('out of memory' crashes, GPU problems, flukes and noise in general)
4. Server infrastructure to handle all this

1 and 4 would be useful even without this...

Would it be amazing? Yes. Will it happen any time soon? No. Still, keeping this one around :)

**Comment by nikhiljha** [comment]
Let's try to simplify the problem, @peterix.

1. Why would you identify mods with SHA256 Hashes? Can't you just look in the jar and identify the mod with the `mcmod.info` file?

Example from JourneyMap:

```
{
  "modListVersion": 2,
  "modList": [{
    "modid": "journeymap",
    "name": "JourneyMap",
    "description": "JourneyMap: Real-time map in-game or in a web browser as you explore. JourneyMap API: v1.11-1.3-SNAPSHOT. Built: 2016-12-10-12:55:04.",
    "version": "1.11-5.3.2",
    "mcversion": "1.11",
    "url": "http://journeymap.info",
    "updateUrl": "",
    "authorList": ["techbrew", "mysticdrew"],
    "logoFile": "assets/journeymap/ui/img/ico/journeymap144.png",
    "screenshots": [],
    "dependants":[],
    "dependencies": ["Forge@[13.19.1.2188,)"],
    "requiredMods": [],
    "useDependencyInformation": true
  }]
}
```

2. Yup this is the hard part. For now we can just ensure that the `requiredMods` and `dependencies` are all there and working. Currently the mod just fails to load. MultiMC checking this would be pretty cool (and not that hard to do when combined with 1 I think).

3. I got nothing.

4. No need if you just look at mcmod.info.

**Comment by peterix** [comment]
In general, that file is filled with unreliable information, or is missing entirely. It is unusable.

**Comment by peterix** [comment]
Well, this is just not happening without a platform to support it. This platform doesn't exist, and nobody is building it. I'll keep this in my notes...
