### ISSUE TITLE
Implement passing of proxy settings to the game

### ISSUE THREAD

**Issue by Kewlname** [MultiMC/MultiMC5#1706]
MultiMC has been great so far, but proxy does not seem to work for me. My collage blocks us from minecraft servers, so I tried using the proxy settings to bypass the restriction. I used both HTTP and SOCKS 5, and tried plenty of each. I can connect to servers fine if I am using wifi off campus, but once I get on school grounds and try to log onto a minecraft server, it times out. The school's wifi is not slow. Please help me, because I want to play my Minecrafts again. Thank you. From Me.

**Comment by Kewlname** [comment]
BTW, I am on Mac

**Comment by peterix** [comment]
The proxy only works fro MultiMC, not Minecraft. I've never added the bits needed to pass the proxy settings to the game.

The Minecraft proxy support has also been a bit spotty over time. There's an open bug for it, but it can also serve as instructions on how to set it up:
https://bugs.mojang.com/browse/MC-38872

So, looks like all you have to do is pass the right java arguments.

**Comment by Kewlname** [comment]
Thank you for responding so quickly, and thank you for the advice, but do you know if there is another way for me to get around my school's restrictions? Its okay if no.

**Comment by peterix** [comment]
It depends on what they block. Can you use VPN? Can you tunnel through SSH?

If you can't do any of that, you could always get mobile internet using an USB dongle or figure out how to share your mobile internet with your computer. This assumes you actually use a something in your posession. It's probably not OK to connect random hardware to school computers.

**Comment by Kewlname** [comment]
Thank you so much

**Comment by peterix** [comment]
Hm. Closing this, becayse the game just doesn't support it.
