### ISSUE TITLE
Using "play offline" attempts to contact the mojang servers to log in

### ISSUE THREAD

**Issue by Samistine** [MultiMC/MultiMC5#1709]
MultiMC version: MultiMC 5
Operating System: Windows 7x64

Summary of the issue or suggestion & Steps to reproduce the issue:
----------------------------------------------
One Liner: Using "play offline" attempts to contact the mojang servers to log in.

After initially signing on downloading everything to the point where it can be played offline;
then closing everything out, isolating the program from the main interwebs, and finally reopening;
right-clicking on the instance and selecting play offline opens a box trying to refresh my authentication.

This usually ends up taking a minute on my end to fail before launching the instance.
Additionally, while being connected to the internet and launching an instance in "offline mode" it will tell me that my authentication has expired and make me log in. :unamused: 

What should happen:
------------------------------
MultiMC should not try to communicate with Mojang, at all, when clicking play offline.

Suspected cause:
---------------------------
MultiMC attempts to connect and only play offline as a fallback, however play offline should do what it says and *play offline*

**Comment by peterix** [comment]
It checks the account and then doesn't use the actual login details - Minecraft is effectively offline. You need a valid account and if you are **actually online**, it will check that you have one.

You should be able to interrupt the account refresh though.

**Comment by peterix** [comment]
This has been changed in 0.6 to only contact remote servers if you launch online.
