### ISSUE TITLE
Created: 2048x2048 textures/blocks-atlas after that i can´t do anithing

### ISSUE THREAD

**Issue by Lboylphd** [MultiMC/MultiMC5#1710]
System Information
-----------------------------
MultiMC version: 5

Operating System: Windows 10 Home

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
It starts normaly at the end it names 
[19:43:24] [Client thread/INFO]: Created: 2048x2048 textures/blocks-atlas
After that Mineraft lags very hard
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.I reser my Laptop (done)

2.Reinstall Java (done)

3.Look after the mods (done)

Suspected cause:
---------------------------

Logs/Screenshots:
http://pastebin.com/Az8hTkY4
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
It's probably running out of resources? maybe?

A 2048x2048 texture doesn't seem all that big though. It's been supported by graphics cards for a loong time now. Even cheap phones can do it.

http://feedback.wildfiregames.com/report/opengl/feature/GL_MAX_TEXTURE_SIZE#1024

**Comment by jikuja** [comment]
Try updating GPU drivers, using real GPU or check if someone enabled texture compression.

**Comment by Lboylphd** [comment]
I done all wat you sad it didn´t works

**Comment by jikuja** [comment]
Can you share version numbers and screenshot of GPU driver settings?

**Comment by Lboylphd** [comment]
jes shure

**Comment by Lboylphd** [comment]
moment please

**Comment by Lboylphd** [comment]
It is an Amd Radeon R7 M265 with 2 GB Decated VRam 
and the settings are on this link https://www.dropbox.com/s/gag2no6z50reonw/RADEON%20EINSTELLUNGEN%2009.11.2016%2018_07_32.png?dl=0

**Comment by peterix** [comment]
It's a crazy thing, but if you have AMD switchable graphics in a laptop, try this:

* Close MultiMC
* Rename MultiMC.exe to Minecraft.exe
* Run (the now renamed) MultiMC and see if that helped

**Comment by Lboylphd** [comment]
No it wont work

**Comment by jikuja** [comment]
Anyway problem is that you MC is using HD graphics, not your discrete GPU. Intel's drivers are just crappy and has bad perfomance. ref: https://www.reddit.com/r/feedthebeast/comments/3wsecy/to_anyone_whos_wondering_what_the_solution_to_my/ and https://www.reddit.com/r/feedthebeast/comments/3xy2ej/the_return_of_the_intel_issue/ and https://github.com/LWJGL/lwjgl/issues/127

**Comment by Lboylphd** [comment]
It didn´t find an driver update

**Comment by TheBlueTroll** [comment]
as described by jikuja, the issue is minecraft/java has decided to use the intel gpu over the AMD switchable one, as shown by the line in your log posted:
"    GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.15.4248' Renderer: 'Intel(R) HD Graphics 4400'"
the intel HD 4400 is not terribly good at doing anything 3d, but its great for 2d graphics and low power usage.
so lets start with: 

- make sure the charger for the laptop is plugged in (some laptops wont even use the other gpu without it).
-  check the settings in your gpu driver (usually in the task-bar on the bottom right) that the external gpu is used for multimc.exe and/or java.exe.

if you still have issues, could you please post more information about your computer, such as: Brand, Model number, Amd driver version installed

**Comment by peterix** [comment]
Just a clarification: This is generally decided by the GPU drivers. In the past, renaming MultiMC.exe made the drivers recognize the started java processes as requiring the discrete GPU.

**Comment by Lboylphd** [comment]
TheBlueTroll
The Intel GPU is Running how i can force it and thank you @everybody how help me

**Comment by QuImUfu** [comment]
Ich nehme aufgrund des Screenshots an, das du ein Deutscher oder zumindest Deutschsprachig bist :)

Du öffnest Crimson, über Desktoprechtsklick oder TrayIcon, wählst unten "Einstellungen" und dann das erste Button "Zusätzliche Radeon Einstellungen". Dann öffnet sich die alte CCC Oberfläche und du solltest (hoffentlich) irgendwo die Einstellung zum erzwingen der Grafikkarte per Programm finden.

Vielleicht gibt es auch viel einfacher einen eintrag im Desktopmenu wie in http://de.community.dell.com/techcenter/enterprise-client/w/wiki/1284.amd-umschaltbare-grafiken-konfigurieren beschrieben.

Wenn das nicht geht musst du halt in den Crimson Einstellungen nachsehen ob du so eine Einstellung irgendwo findest. 

Kann leider nicht nachsehen, da ich kein Windows mehr nutze.
Falls du einen Ort wo du es einstellen kannst findest, stelle am besten sowohl MultMC (multimc.exe) als auch Java (javaw.exe) als Radeon-GPU beschleunigt ein.

**Comment by Lboylphd** [comment]
Hey ja ich komme aus Deutschland und danke dir ich habe es geschafft ich war kurz davor es zu finden und ich war auch schon im alten Menü und dann hast du mir noch mach sehr geholfen Vielen dank an dich ;)

**Comment by Lboylphd** [comment]
Now it works

**Comment by TheBlueTroll** [comment]
good to hear, have a  fun time with minecraft now ;)
