### ISSUE TITLE
Themes don't seem to respect button states

### ISSUE THREAD

**Issue by Heufneutje** [MultiMC/MultiMC5#1711]
System Information
-----------------------------
MultiMC version:
0.4.12-develop-844

Operating System:
Microsoft Windows [Version 10.0.14393]

Summary of the issue or suggestion:
----------------------------------------------
Buttons look exactly the same in their enabled and disabled states when the Bright or Dark theme is applied.

What should happen:
------------------------------
The buttons should have a distinguishable disabled look, like they do in the System theme.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Load up MultiMC with the System theme and open the instance settings of any instance. Note the disabled states of the "Remove" button while "Minecraft" is selected.

2. Switch themes to either the Dark or Bright theme.

3. Look at any instance again and note that the buttons that looked disabled before now look exactly the same as the enabled buttons.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
Log:
http://paste.ee/p/SzrMz

Side by side comparison:
![comparison](https://cloud.githubusercontent.com/assets/1357231/20034122/4a0045d6-a3b3-11e6-984b-5fddf209acd4.png)

**Comment by peterix** [comment]
Already fixed this in a separate branch.

**Comment by peterix** [comment]
I guess I have an ID for it now :)

**Comment by peterix** [comment]
Shold be fixed now :)
