### ISSUE TITLE
Qt5 or Qt4??

### ISSUE THREAD

**Issue by GabrielTK** [MultiMC/MultiMC5#1712]
Good Afternoon,
After reading the README.md and the BUILD.md, I tried to build this project in Qt5, but I've got an error saying that only Qt4 is supported. But in the readme it says Qt 5 and in the [BUILD.md (Windows/Dependencies)](https://github.com/MultiMC/MultiMC5/blob/develop/BUILD.md#dependencies) too!!
So, what should I do to build it???
Thank you,
Gabriel

**Comment by peterix** [comment]
You need Qt5. Maybe you have both and it's not detecting it right?

**Comment by peterix** [comment]
You should use Qt 5.4.x - the mingw32 version, not visual studio. Visual studio probably can't compile MultiMC.

**Comment by peterix** [comment]
That won't work without some code and build system changes.

**Comment by GabrielTK** [comment]
So, what do I need to do to get it working??? (Sorry for taking your time)

**Comment by peterix** [comment]
These things:
https://github.com/MultiMC/MultiMC5/blob/develop/BUILD.md#dependencies

It's also helpful to have the dumpbin.exe tool from Visual Studio around - the equivalent tool from mingw32 is horribly slow and makes the `mingq32-make install` take forever.

And it's helpful to use the ci setup as reference:
http://ci.multimc.org/builders/win32/builds/850/steps/configure/logs/stdio

You can see all the environment variables and command line parameters passed there.

**Comment by GabrielTK** [comment]
Ok, I'm going to try it, but @peterix , Can I ask you just a little question?? Do you know what widget is used to display the instances in MultiMC??? I can't find it! 
Thank you,
Gabriel

**Comment by peterix** [comment]
It's a custom widget:
https://github.com/MultiMC/MultiMC5/tree/develop/application/groupview
