### ISSUE TITLE
MultiMC crashes when a new modpack is installed from FTB legacy launcher with the FTB tracking on.

### ISSUE THREAD

**Issue by AssasinAsha** [MultiMC/MultiMC5#1713]
System Information
-----------------------------
MultiMC version:
0.4.12-develop-804

Operating System:
Linux 4.4.0-45-generic. It's technically an instance of Ubuntu, later converted into lUbuntu, currently using simply LXDE. Not exactly sane but shouldn't have an impact.

Summary of the issue or suggestion:
----------------------------------------------
If I install a modpack using the FTB legacy launcher (in this case, the "FTB Resurrection" modpack) MultiMC crashes with [this log](http://pastebin.com/ZUzi1ZBb). When I executed MultiMC from console I got the following line outside the log:

`./MultiMC: line 93: 23797 Segmentation fault      (core dumped) "${MMC_DIR}/bin/MultiMC" -d "${MMC_DIR}" "$@"`

Can't find the dump, though. My less-than-stellar understanding of Linux might be the culprit here.
Just in case, 23797 is simply PID.

Deleting the modpack folder from the FTB launcher folder allows MultiMC to start.
Curiously enough, though, if I open MultiMC, then install the modpack from FTB launcher, while keeping MultiMC open, and then press the refresh button in MultiMC, all is well. No issues, no nothing, as in [this log](http://pastebin.com/VrmRFapA).

As expected, disabling FTB tracking for the duration of a new install does not cause issues. It is a hassle, though. 
Similarly, upgrading/downgrading already existing modpacks has no negative repercussions.

What should happen:
------------------------------
MultiMC should open without crashing upon detecting a new modpack at startup.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install a new modpack using FTB legacy launcher.
2. Open MultiMC.

Suspected cause:
---------------------------
Sorry, I have no idea.
Now, there is this issue #1689 , which this might be an example of, but I'm not qualified to tell.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
1. Log when crash: http://pastebin.com/ZUzi1ZBb
2. Log when curiosity: http://pastebin.com/VrmRFapA
Both pastes are set for one month deletion. I have local copies which I can provide again, should the need arise.

Additional Info:
---------------------------
None that I can think of. Some of my description of the issue probably applies, though.

**Comment by peterix** [comment]
> As expected, disabling FTB tracking for the duration of a new install does not cause issues. It is a hassle, though.

So... this only happens when you have MultiMC open during the install in FTB?

**Comment by AssasinAsha** [comment]
Ah, sorry. I tend to write complicated things.
No, it doesn't. If I have MultiMC open during install, everything works. No crashes during or after install.
The crash happens if I have MultiMC closed during install. When I try starting it after, it won't work.
It's strange.

**Comment by AssasinAsha** [comment]
I also checked now and if I have MultiMC open during install, but close it after install _without clicking the "reload instances" button in MultiMC GUI_ it will crash on next launch.
As long as MultiMC is open, I can install new modpacks however I please. If MultiMC is not open and detects a new modpack from FTB Launcher when starting up, it will crash.

**Comment by peterix** [comment]
Cool, I should be able to do something about this. Thank you for testing it :)

Also, what pack are you adding?

**Comment by AssasinAsha** [comment]
In this particular issue, it was FTB Resurrection.
But I think all of them don't install. I tried FTB Retro SMP and that broke. I'll try FTB Infinity for 1.10, just give me a moment do download.

**Comment by AssasinAsha** [comment]
Yes, it breaks for FTB Infinity Lite as well. It also crashes for third party packs, such as "Ultimate Questpack" and "GT New Horizons".

**Comment by peterix** [comment]
So, something is either unavailable or broken when instances are being loaded

**Comment by peterix** [comment]
Should be fixed now, just wait for all the builds to finish and upload :)

**Comment by AssasinAsha** [comment]
Indeed, it is. Works like a charm, thank you!
