### ISSUE TITLE
[Suggestion]Console input

### ISSUE THREAD

**Issue by ppoozl** [MultiMC/MultiMC5#1717]
Can you add console input so we can type commands?

**Comment by peterix** [comment]
I have no idea if the client even accepts input. Probably doesn't - and in MultiMC's case, it is taken by the MultiMC launcher part.

But I'll check :)

**Comment by ppoozl** [comment]
I am so sorry. The client do not support input from console. I must be mistaken from the servers' .Sorry again for bother.

**Comment by peterix** [comment]
Yeah, looks like it's all related to server... I can't find anything that would allow access to the console from outside the client. It would probably require a mod that opens a named pipe or socket that MultiMC could connect to.

**Comment by peterix** [comment]
The answer is no.
