### ISSUE TITLE
IDK what to call this issue - minor bug

### ISSUE THREAD

**Issue by brodycas3** [MultiMC/MultiMC5#1718]
Follow the actions that I do with my mouse. http://i.imgur.com/WVqLBbJ.gifv

**Comment by Heufneutje** [comment]
What exactly is this issue I'm not seeing? The issue template exists for a reason. Just providing a gif makes tracking an issue really hard.

**Comment by peterix** [comment]
Works as expected. Yes, you can select text in labels and dialogs where I thought it might be beneficial.
