### ISSUE TITLE
Suggestion: Some sort of "I know what i am doing" option

### ISSUE THREAD

**Issue by QuImUfu** [MultiMC/MultiMC5#1723]
I do not want MultiMC to tell me my minimum RAM for Minecraft, like it does in the moment. It only allows setting min RAM to 256 and max to 512. MC does run completely fine on a weak PC with lowest settings if you give it only 128-256MB Ram. This is especially true for very old versions of MC. Also i would like to be able to kill my instance when my PC hangs without having to wait for that dialog box to pop up.

But i can see the general purpose of this minimum-setting and all the warning dialog's, as there are enough people that screw up their settings (e.g. use 32 bit java and more than 2 GB RAM) and having complains from people setting their RAM to low or accidentally deleting their instance in addition would not help anyone. Additionally nearly all PC nowadays have plenty of RAM so that is no problem, too.

That is why i want to suggest an option, maybe even a command line parameter to tell MultiMC:
"i do really know what i am doing. I do not need warning dialog's (eg. when deleting an instance or killing a game...), nor do i need MMC checking my settings whether they are within certain parameters. I do promise not to complain if something goes wrong."

But i can also understand if you do not want to add something maybe not very easy to code just for one guy. :)

**Comment by peterix** [comment]
Noted, added to workflowy:
https://workflowy.com/s/2EyDMcp7CU#/277da486d3a3
