### ISSUE TITLE
Linux updates need better detection of failed update

### ISSUE THREAD

**Issue by SoniEx2** [MultiMC/MultiMC5#1726]
I need to replace the update mechanism so I can remove libxcb.so.1 (see #1699)  after updates.

My idea is to replace the update mechanism with a shell script, then when it gets called I replace the script with the original updater, then I run the updater, then I move the (updated?) updater out of the way, and finally restore my script. Then I nuke libxcb.so.1.

**Comment by peterix** [comment]
It is no longer used. Current versions include the updater only so that very old versions are able to update.

**Comment by peterix** [comment]
To clarify:
Old versions first download the updater, then feed it the update script and exit. The updater then does the rest of the job.
Current versions download the whole update, replace all the files while the application is running, start a new copy and if that successfuly starts, exit. If it doesn't start, the files are rolled back and you get a dialog box that says the update failed.

Question is:
Why is it not detecting that the update failed?

As for the linux problem: I'll remove `libxcb.so(\..*)?` and that should keep things compatible.

**Comment by SoniEx2** [comment]
You really need to modularize MultiMC, even if just so I can do this.

**Comment by peterix** [comment]
No. And that is final.

Only these states should be a result of the update:
* You get a fully updated MultiMC.
* You keep the working version you already have.

**Comment by SoniEx2** [comment]
I want a modular MultiMC just so you do less work to keep it working for me.

**Comment by peterix** [comment]
I am not going to discuss this with you again.

**Comment by peterix** [comment]
Should be fixed in the new build, as soon as it finished.
