### ISSUE TITLE
MMC not starting up

### ISSUE THREAD

**Issue by Daswf852** [MultiMC/MultiMC5#1730]
System Information
-----------------------------
MultiMC version: 0.4.11-703

Operating System: Ubuntu 16.10 (yaketty)

Summary of the issue:
----------------------------------------------
Multimc doesent startup.

Logs/Screenshots:
----------------------------
    Starting from first warning

    0.124 W Blacklisted legacy version ignored:  "rd-160052"
    0.124 D Loading local version list.
    0.124 D Loaded version "16w42a" from local version list.
    0.124 D Loaded version "1.10.2" from local version list.
    0.125 D Loaded version "1.8.9" from local version list.
    0.125 D Loaded version "1.8" from local version list.
    0.125 D Loaded version "1.7.10" from local version list.
    0.134 D Reloading news.
    0.135 D "News RSS Feed"  started.
    0.135 D Checking for updates.
    0.135 D Channel list isn't loaded yet. Loading channel list and deferring update check.
    0.135 D Loading the channel list.
    0.135 D "Update System Channel List"  started.
    0.135 D "Checking for notifications"  started.
    /home/dogewithfez/.local/share/multimc/bin/MultiMC: symbol lookup error: /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0: undefined symbol: xcb_get_reply_fds

**Comment by TheBlueTroll** [comment]
fun times, you have a incompatable version of libxcb-dri3.so.0, which is a library dealing with graphics , specifically the x window interface, direct rendering interface library, considering that you hve ubuntu 16.10 its fairly likely it isnt out of date, but if you could start by doing "**sudo apt-get update && sudo apt-get upgrade**" we can remove out of date stuff as a issue.

**Comment by TheBlueTroll** [comment]
as a additional, try following the steps in this issue, which is about the exact same thing you are experiencing 
https://github.com/MultiMC/MultiMC5/issues/1693
good luck.

**Comment by jonbobbly** [comment]
I also have this issue. I have yet to get it it running.

**Comment by TheBlueTroll** [comment]
try following the steps in #1693, which i stated in my previous comment.

**Comment by jonbobbly** [comment]
That did actually work, though I still had to figure out **which** xcb file to delete. (it was **bin/libxcb.so.1** for anyone that was confused like me. The rest of the libxcb files seem to be fine as is.) 

Perhaps that info should go into an faq?

**Comment by nikhiljha** [comment]
Yup, that file needed to be deleted on my Fedora install as well. I think peterix fixed it, so it'll be there in the next update.
