### ISSUE TITLE
URGENT - Deleted unprotected folders C drive

### ISSUE THREAD

**Issue by gLynx4** [MultiMC/MultiMC5#1731]
MultiMC: 0.4.11-751
OS: Windows 8.1

Yesterday:
I clicked screenshots on the console window and saw a screenshot named "C:", it didn't have a preview image. I thought it was a bug so I clicked delete.. I thought everything was all fine.

Today:
I look for my "C:\Code" folder... it's gone...
I think back to yesterday when I deleted a suspicious named screenshot.
It appears to have only deleted that folder and no system protected folders (e.g. Program Files and Windows)
I don't have any MultiMC logs.. if I can recover my stuff, I can probably get a log.
So far no luck recovering my code folder.
I have no idea how to reproduce this or why it happened but it happened so maybe there should be a protection in place that only deletes screenshots if they are in the minecraft folder.

Does QT shred files when deleted?

:cry: :cry:

**Comment by peterix** [comment]
It deletes stuff. That is - it doesn't move it to a magical folder somewhere. So, it's gone.

The files may be possible to restore, if you have a normal spinning hard-drive.
The idea is to turn it off, boot from something else ([like this for example](https://www.linux.com/learn/get-your-data-back-linux-based-data-recovery-tools)) and don't let the machine write to the drive. The longer you run it with writes enabled, the more stuff actually gets overwritten and destroyed.

If you have an SSD ... I have no idea. Those nuke the data shortly after it's marked as deleted to make future writes fast.

The only sure way of preventing something like this is backups. Github is nice for code. If not github, you can set up version control on a VPS, or use any of the other code hosting solutions out there.

As for the bug:
It can happen when the `screenshots` folder can't be created. For example, if there's a file named `screenshots` already there. But that's definitely not the only possible cause.
![image](https://cloud.githubusercontent.com/assets/203326/20474636/c0fabac0-afc7-11e6-8874-631306428076.png)

**Comment by peterix** [comment]
Alright. It shouldn't show the drives in the develop version anymore - at least in the case I discovered.

**Comment by peterix** [comment]
It's now as paranoid as I can make it...
