### ISSUE TITLE
crashing on launch after last update today (yesterday it works)

### ISSUE THREAD

**Issue by Cronosus** [MultiMC/MultiMC5#1732]
System Information
-----------------------------
MultiMC version: 0.4.12 dev878
Operating System: W10

What should happen:
------------------------------
instance not launch

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. on launch instance

Suspected cause:
---------------------------
library problem?

Logs/Screenshots:
----------------------------
http://paste.ee/p/yQaCX

**Comment by peterix** [comment]
You have a lot of duplicated mods. That simply doesn't work. Remove or disable the versions you don't intend to use.

**Comment by Cronosus** [comment]
ah.. i see it now.. but how this happens? yesterday i play it and doday this.. :D
