### ISSUE TITLE
Launching via the commandline doesn't recognize renamed instances

### ISSUE THREAD

**Issue by Strahan201** [MultiMC/MultiMC5#1733]
System Information
-----------------------------
MultiMC version: 0.4.11-751

Operating System: Windows 7 Pro x64

Summary of the issue or suggestion:
----------------------------------------------
I just renamed an instance from "Forge 1.10.2" to "Forge_1.10.2" so when I launch via the command line I do not have to waste time with double quotes.  Alas, it still requires the original instance name to launch automatically.

What should happen:
------------------------------
I'd think that renaming the instance should also rename whatever it looks at when it evaluates command line launching.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create an instance
2. Highlight it and press F2 to rename
3. Rename to something else
4. Attempt to launch it via multimc -l (new instance name)
5. When it fails to launch, try multimc -l (original instance name) and you'll see it work

Suspected cause:
---------------------------
I suspect it looks at the file system when you pass the instance name, not whatever it is in the configuration because I noticed the instance folder did not change name.

Logs/Screenshots:
----------------------------
http://www.sylvcraft.com/multimc.png

Additional Info:
---------------------------
I noticed in further testing (to determine if it was just a space that messes it up or any sort of renaming, and it's the latter) that under Windows instance name is case sensitive.  Makes sense in a *ix environment where the FS is sensitive, but under Windows it'd be nice if -l wasn't case sensitive as the FS is not.

**Comment by peterix** [comment]
Instance ID is not instance name. It is the name of the folder. Rename the folder instead.

**Comment by Strahan201** [comment]
Oh, I had incorrectly assumed you'd use what you saw in the launcher.  Thanks, sorry for submitting an invalid report.

**Comment by peterix** [comment]
I needed some unique ID to identify instances. Anything that would come from inside the instance could end up being a duplicate - any IDs or names specified in a config file simply wouldn't work.
Contents of a folder already can't have duplicate names, so it works. 

At some point, I'd like to make it also rename the folders, but the mapping can't be exact. Java doesn't launch when you use some characters in paths for example.
So even if you would rename the instance, it wouldn't necessarily end up with the same folder name.

If you hover over the instance icons, it shows the real instance path in a tooltip. The folder name is the ID :) For tracked FTB instances 'FTB/folder name' is the ID.
