### ISSUE TITLE
Exited with Code -1

### ISSUE THREAD

**Issue by HoppinAround** [MultiMC/MultiMC5#1734]
I were already in the Menu were you can select Singleplayer and so on but after 2 seconds it crashed.
I have Java 64 1.8_25
the log is uploaded here:
http://paste.ee/p/OnfuT
I really dont know whats the problem!

**Comment by Loetkolben** [comment]
Frist of all, but probably unrelated, "Flan's Mod" has problems reading some of it's config (?) files: `Reading file failed : Bandana [...] java.lang.NumberFormatException: For input string: "Your"`. It was expecting an number and got "Your".

`java.lang.NullPointerException: Rendering screen [...] at enviromine.handlers.EM_EventManager.onRender(EM_EventManager.java:1536)` -> I guess a mod named "enviromine" has a / is the problem. Remove it and try again,
