### ISSUE TITLE
Java Problem

### ISSUE THREAD

**Issue by SPACEFACE2394** [MultiMC/MultiMC5#1735]
MultiMC version: 0.4.11-751Minecraft folder is:instances/MagicCraft 1.0/minecraftThe java binary "" couldn't be found. Please set up java in the settings.

http://paste.ee/p/E1ms6#

**Comment by QuImUfu** [comment]
set you java-binary in the settings. see:
https://github.com/MultiMC/MultiMC5/wiki/Java-settings

**Comment by SPACEFACE2394** [comment]
it doesn't say anything about java binary.

**Comment by Loetkolben** [comment]
Settings > Java, in the _Java Runtime_ "box" click _Autodetect_ and choose the version with the start next to it.

**Comment by SPACEFACE2394** [comment]
it says no versions available.

**Comment by Loetkolben** [comment]
Well, do you have any version of java installed? What OS?

**Comment by SPACEFACE2394** [comment]
i installed the latest version of java after all this happened

**Comment by SPACEFACE2394** [comment]
"that"

**Comment by QuImUfu** [comment]
Then search for the "javaw.exe" executable (on windows, on other systems "java") and add it manually. (Settings > Java, in the Java Runtime "box" click the "..." button, and chose the "javaw.exe" (or "java")  file.) 
It would be nice if you could tell us the location of the Java executable on you PC.

**Comment by SPACEFACE2394** [comment]
search-ms:displayname=Search%20Results%20in%20MultiMC&crumb=System.Generic.String%3Ajava&crumb=location:C%3A%5CUsers%5CCaldwell%20family%5CDocuments%5CMultiMC\java 
i think i may be wrong

**Comment by QuImUfu** [comment]
if i understand that cryptic path correctly you have installed Java not to the defaut location.
While this is possible MMC won't find it automatically as it does only check the default installation locations.
You can however choose the executable manually via Settings > Java, in the Java Runtime "box" click the "..." button, and choose the "javaw.exe" file. 
if you do not know where it is, search for "javaw.exe via the windows search function available on you windows version. Then find out where on you Computer it is located. (Right click ->open containing folder)

**Comment by SPACEFACE2394** [comment]
okay so i found the javaw.exe file but it is now saying that it needs to be fixed or disabled
here is the java file path:
C:/Program Files (x86)/Java/jre1.8.0_91/bin/javaw.exe

**Comment by peterix** [comment]
So you have an outdated installation of 32bit java - on a 64bit computer - that *maybe* doesn't work.

What is saying that *"it needs to be fixed or disabled"*?

Anyway, I would suggest the following steps:
* Uninstall each and every java you may have. There's no point using 32bit java for Minecraft.
* Install this one: http://javadl.oracle.com/webapps/download/AutoDL?BundleId=216434

**Comment by SPACEFACE2394** [comment]
MultiMC version: 0.4.11-751

Minecraft folder is:
instances/MagicCraft 1.0/minecraft

The java binary "" couldn't be found. Please fix the java path override in the instance's settings or disable it.

This is just getting stupid
Java path:
C:/Program Files/Java/jre1.8.0_111/bin/java.exe

**Comment by SPACEFACE2394** [comment]
i installed your link and did all that stuff

**Comment by peterix** [comment]
![image](https://cloud.githubusercontent.com/assets/203326/20651641/3bc35ea8-b4e9-11e6-9fe6-7391dce880d0.png)
![image](https://cloud.githubusercontent.com/assets/203326/20651648/4f399b6e-b4e9-11e6-942e-e6bc8e0c94b4.png)

Make sure this is disabled in all your instances.

**Comment by SPACEFACE2394** [comment]
thanks man that worked!

**Comment by ff6f8d68** [comment]
can you also help me my log: https://mclo.gs/rVkyVf7
