### ISSUE TITLE
Code -1 exit

### ISSUE THREAD

**Issue by DarkMatter980** [MultiMC/MultiMC5#1736]
http://paste.ee/p/DK8g2
 
MultiMC version: 0.4.11-751

Minecraft folder is:
instances/MagicCraft 1.0/minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_111/bin/java.exe

Java Arguments:
[/usr/bin/java,XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms6000m, -Xmx6000m, -Duser.language=en, -jar, C:/Users/Caldwell family/Documents/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 3512

Error: Could not find or load main class .usr.bin.javaProcess exited with code 1.

Please Help

**Comment by peterix** [comment]
Remove `/usr/bin/java` from MultiMC's - or the instance's - java settings.

**Comment by DarkMatter980** [comment]
thanks that worked
