### ISSUE TITLE
MultiMC5 does not seem to read custom.json after pre-launch command

### ISSUE THREAD

**Issue by oddstr13** [MultiMC/MultiMC5#174]
Version: 0.2.1-dev208  
Platform: win32 (Windows7 x86_64)
Log: http://oddstr13.openshell.no/paste/UzQ8Fl4j/

IRC log (for reference): http://oddstr13.openshell.no/paste/UzRDoz2X/

**Comment by peterix** [comment]
custom.json is now deprecated.

Continued as #864
