### ISSUE TITLE
PC freezes after MultiMC makes multiple threads after long play time. (suspected)

### ISSUE THREAD

**Issue by panslothda** [MultiMC/MultiMC5#1740]
System Information
-----------------------------
MultiMC version: 0.4.11-70

Operating System: 4.8.11-1-ARCH #1 SMP PREEMPT Sun Nov 27 09:26:14 CET 2016 x86_64 GNU/Linux

Summary of the issue or suggestion:
MultiMC keeps on making threads that let the pc in the end freeze and need to coldreestart pc with power button press.

What should happen:
------------------------------
uhm not freeze pc? :D

Steps to reproduce the issue (Add more if needed):
---------------------------
1. start any modpack/minecraft version

2. play for like a hour

Suspected cause:
---------------------------
No clue

Logs/Screenshots:
----------------------------
![img_20161202_142601](https://cloud.githubusercontent.com/assets/19254254/20825074/9555f276-b89c-11e6-9719-72ecee69bf5c.jpg)

Additional Info:
---------------------------
i was able to use a second ttl to take a screenshot of htop but that was also completely unresponsive. system is up to date from official repos. The issue does only appear when i use multimc regular minecraft or other programs don't cause the issue.

**Comment by peterix** [comment]
That is Java - Minecraft. MultiMC is using Java only as a means to start the game. So unless you had this many *processes*, it cannot be involved in this way.

**Comment by peterix** [comment]
Also, it looks more like a memory leak, not anything to do with threads... If you let it going for a while, the OOM killer will eventually kill something. And you can read about that if you run `dmesg`.

**Comment by QuImUfu** [comment]
If i interpret that picture correctly, you have more than 16 GB ram+ 4 GB swap, and java does only use a little bit more than 4 GB, so it is definitely not mc's fault. 
If you are in the same situation again on press "shift + h" to stop htop from listing all the threads and look what really uses all the memory. 
As peterix sad it is most likely a memory leak in some program.

**Comment by peterix** [comment]
If MultiMC is involved, I would suspect the Minecraft log to be the source of the issues. The version you are using **should** have a sane maximum log size already set though:
![image](https://cloud.githubusercontent.com/assets/203326/20842110/9addaa94-b8b6-11e6-8668-c277f0ba83f9.png)

100000 lines ~= units of megabytes. Not what you're seeing there.

You should also be able to monitor memory use long before you run out of memory. So, do that.

**Comment by peterix** [comment]
Hmm... so what as the issue, just for the record?

**Comment by panslothda** [comment]
@peterix didnt saw that you wrote another message Sorry bout that. In the end i didn't figure it out but it just vanished. I dont know till know what caused it but the freeze that happened regularly just vanished. Maybe i updated something in my system that was causing it or an update in MultiMC when i switched to development branch changed something that caused it. No clue sadly. But it all working now perfectly fine and im happy :)
