### ISSUE TITLE
cant launch minecraft

### ISSUE THREAD

**Issue by xWizardtree** [MultiMC/MultiMC5#1744]
MultiMC version: 0.4.11-751
Operating System: win 7 32 bit

every time i try to open minecraft using multiMC it opens the console window and then this happens in the log :

MultiMC version: 0.4.11-751

Minecraft folder is:
instances/1.8/minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/java.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -jar, C:/Users/Jake/Desktop/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 2096

Process exited with code 1.

**Comment by Dog3403** [comment]
Do You Have Any Mods Installed?
