### ISSUE TITLE
process exited with code 1 HELP!!!

### ISSUE THREAD

**Issue by genieblock** [MultiMC/MultiMC5#1750]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by genieblock** [comment]
http://paste.ee/p/FLyfG

**Comment by genieblock** [comment]
not sure what to do with this

**Comment by genieblock** [comment]
[13:38:16] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:560]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\pc user\Desktop\multimc\MultiMC\instances\Nimbus skyblock\minecraft\crash-reports\crash-2016-12-12_13.38.16-client.txt
Process exited with code -1.

**Comment by QuImUfu** [comment]
mods for 1.9.x and 1.7.x, do not work with 1.10.x . 
Remove all the mods for 1.9.x and 1.7.x.

**Comment by peterix** [comment]
If you read the log, you will see that two mods have problems:
```
	UCE	Psi{r1.0-36} [Psi] (Psi-r1.0-36.jar) 
	UCE	Quark{beta-40} [Quark] (Quark-beta-40.jar) 
```

Both mods have some issue with `BlockMetaVariants`. I'm not sure what the cause really is.

You could try updating the mods, as the erroring file is not part of the current source code of Quark.

**Comment by peterix** [comment]
Well, there are some mods that work between 1.9 and 1.10... I think.

it's a bit unusual and confusing when that happens, but 1.9.x and 1.10 are compatible enough, so some modders release one build for both.

**Comment by QuImUfu** [comment]
@peterix 
O.o , i did not know that.
@genieblock 
Updating all the mods fixes the problem, i remade your instance with all mods updated, download it [here](https://dl.dropbox.com/s/flqwb1e0scmk0mu/genieblockRemake.zip).

**Comment by peterix** [comment]
Haha, this is like... super premium service.

We should charge for that, somehow ;)

**Comment by genieblock** [comment]
lol i really appreciate this help thankyou ill let you know if it all works on my system.

**Comment by genieblock** [comment]
nope this still not working its telling me i have ran out of memory. is there anyway to make it  for low spec computers?

**Comment by peterix** [comment]
Use the upload button :)

**Comment by genieblock** [comment]
http://paste.ee/p/x4NzG

**Comment by genieblock** [comment]
lol i think i should just give up with these modpacks i never get anywhere with them as i always have problems lol

**Comment by peterix** [comment]
Looks like you are running a 32bit OS on a 64bit CPU:
```
Operating System: Windows 7 (x86) version 6.1
Athlon(tm) 64 X2 Dual Core Processor
```

How much RAm does the computer have?

With 32bit OS and/or Java, the absolute maximum you can give to Minecraft on Windows is about 1500MB. Try to raise the maximum to that, or just under that if it fails sooner (1495MB).

If it doesn't work, you will have to remove mods.

**Comment by genieblock** [comment]
the ram in the computer is 2.5gb which is very low to be making modpacks i know... ill give it a go and let you know

**Comment by genieblock** [comment]
if it comes to it and i have to remove mods ill look into which can be removed so it still works. cos i know some mods only work if they have other mods

**Comment by genieblock** [comment]
i think upgrading my ram would be a good idea tho and the motherboard can handle up to 16gb

**Comment by peterix** [comment]
The machine is a bit old... 10+ year old CPU. Maybe you can find some RAM sticks cheap :)

**Comment by genieblock** [comment]
http://paste.ee/p/sKuqn...........i will have to remove mods, uping the MB did not help

**Comment by genieblock** [comment]
yh its DDR2 ram so ill have a look round see what i can find. i know there is a shop near me that has them 8gb for £15. maybe i just need someone that can make modpacks for low spec pc for now till i can get the money together to get some ram lol

**Comment by peterix** [comment]
That honestly looks like a different problem.

First, it couldn't load some 3d models. Then the GPU driver crashed.

What is inside this?
```
C:\Users\pc user\Desktop\multimc\MultiMC\instances\Nimbus skyblock\minecraft\hs_err_pid4932.log
```

**Comment by genieblock** [comment]
that folder makes no sence to me what so ever lol

**Comment by genieblock** [comment]
is there anyway of posting it on here so you can see it

**Comment by peterix** [comment]
You can use https://gist.github.com/ or https://paste.ee/

**Comment by genieblock** [comment]
https://gist.github.com/genieblock/aa2f27311256fbc25cdb4ad85636aa8e

**Comment by peterix** [comment]
Well, maybe it also ran out of GPU memory?
It's hard to say, really. Anyway, the GPU driver crashed while working with textures: https://www.opengl.org/sdk/docs/man2/xhtml/glTexSubImage2D.xml

This could also be a bug in Minecraft or some of the mods...

The best thing you could do is this:
Disable all mods and start with just Forge.
Add mods one by one - start with those you want the modst - and see when it starts crashing.

**Comment by genieblock** [comment]
ok i really appreciate the help if i have any more problems down the line ill set up a new thread so we can get this one closed

thanks again

**Comment by genieblock** [comment]
lol unless you would like to make me a light skyblock modpack lol

**Comment by QuImUfu** [comment]
if you delete the "Building Bricks", "Chisel", "Chisels & Bits" mod it runs good enough with 1.5 GB ram.
If you use OptiFine it runs much better with only 1408MB. That might work on you pc.

**Comment by genieblock** [comment]
appreciate the input @QuImUfu ill try it out now

**Comment by genieblock** [comment]
that did not work @QuImUfu so im trying it out with uping the permgen

**Comment by genieblock** [comment]
http://paste.ee/p/GclK7 still did not work, ill leave it for now. i do ask tho if any of you have the time to make me up a skyblock modpack for a system that runs 32bitOS on 2.5gb (so a modpack that will only take up 1gb ram usage) it would be much appreciated :) im getting such a head ache from stopping and starting this

**Comment by genieblock** [comment]
it might be beacause of my GPU  aswell as its only a geforce 8400 GS

**Comment by QuImUfu** [comment]
in the pastee you linked you have not set the memory setting to 1408MB. 
As i sad it needs at least that much memory, and with this setting your OS should still have enough ram left. 
As of Java 8 the permgen setting does not have any effect. A geforce 8400 GS should at least be able to run the game, maybe the fps will be very low.

as of the crash in http://paste.ee/p/sKuqn , maybe setting enabled=false in splash.properties will fix this

**Comment by genieblock** [comment]
http://paste.ee/p/c8dWW  would this mean that my java needs updating as it closed before it has even opened

**Comment by peterix** [comment]
You have duplicated mods.

You also have mods that are not for the version of minecraft you are using there (you have 1.7.10, you have mods for 1.10.2).

**Comment by peterix** [comment]
Also, this doesn't seem to be the original issue...

**Comment by genieblock** [comment]
some mods from 1.10 can be used with 1.7.10

**Comment by peterix** [comment]
No.
