### ISSUE TITLE
too much ram

### ISSUE THREAD

**Issue by crusher42** [MultiMC/MultiMC5#1753]
System Information
-----------------------------
MultiMC version: 0.4.00-703

Operating System: linux mint 17.3

Summary of the issue or suggestion:
useing to much ram i got it set at 1.5 gb over time it slowly creeps up seen it go up to 2.5 gb

**Comment by peterix** [comment]
A Java or native memory profiler might help you find out what is leaking or using up memory... Other than that, it's not something I can help you with.

**Comment by peterix** [comment]
And what is 0.4.00-703? Where did you get that?
