### ISSUE TITLE
MultiMC doesn't appear to start in Qt5 on Wayland

### ISSUE THREAD

**Issue by YoshiRulz** [MultiMC/MultiMC5#1755]
System Information
-----------------------------
MultiMC version: 0.4.11 (stable)

Operating System: Arch Linux x64 kernel 4.8.13-1-ARCH

Summary of the issue or suggestion: 
----------------------------------------------
The GUI for MultiMC won't appear because Qt can't "find or load the platform plugin 'wayland'."

What should happen:
------------------------------
The menu should open.

Steps to reproduce the issue:
-------------------------------------------------------------
1. Use the Plasma 5 desktop with Wayland instead of X.

2. Download the [Linux generic x64 tarball](//files.multimc.org/downloads/mmc-stable-lin64.tar.gz) and extract it.

3. Run `.../MultiMC/MultiMC`.

Suspected cause:
---------------------------
Nobody ever thought to check for anything other than X11 in the Qt dependencies.

Logs/Screenshots:
----------------------------
* [Console output of MultiMC](//pastebin.com/kNGW57rX)

**Comment by YoshiRulz** [comment]
To clarify: MultiMC runs as usual with both X and Wayland (given the `QT_QPA_PLATFORM` environment variable was unset). I had to remove `.../MultiMC/bin/libxcb.so.1` per #1501.

**Comment by peterix** [comment]
Wayland is definitely not supported.

**Comment by peterix** [comment]
That said, it would likely be best to remove all the bundled libraries and plugins that can be provided by the system...

From MultiMC:
* Remove the `plugins` folder entirely.
* In `bin`, keep only the highlighted files:
![image](https://cloud.githubusercontent.com/assets/203326/21388190/7778d78a-c77b-11e6-9f59-50ff0db30db4.png)

**Comment by peterix** [comment]
Does that work?

**Comment by YoshiRulz** [comment]
Removing those libraries solves the issue, thanks!
