### ISSUE TITLE
../libMultiMC_logic.so: undefined reference to `nbt

### ISSUE THREAD

**Issue by srakitnican** [MultiMC/MultiMC5#1756]
Hello,

Following up from issue #1379, I am trying to pull out libnbt++ from MultiMC, got libnbtplusplus package to build successfully, but I am not having luck linking it to MultiMC. At some point on compile I get this.

```
../libMultiMC_logic.so: undefined reference to `nbt::value::at(std::string const&)'
../libMultiMC_logic.so: undefined reference to `nbt::tag_compound::at(std::string const&)'
../libMultiMC_logic.so: undefined reference to `nbt::io::read_compound(std::istream&, endian::endian)'
../libMultiMC_logic.so: undefined reference to `nbt::tag_compound::put(std::string const&, nbt::value_initializer&&)'
../libMultiMC_logic.so: undefined reference to `nbt::io::write_tag(std::string const&, nbt::tag const&, std::ostream&, endian::endian)'

```

I had to modify headers path of the library, so that it is under its own subdirectory under /usr/include/. I did modify MultiMC sources accordingly.

I am modifying MultiMC sources with following commands.

```
sed -i '/^add_subdirectory.*libnbtplusplus/d' CMakeLists.txt
for header in io/stream_reader.h tag_string.h tag_primitive.h; do
  sed -i "s|^#include[ tab]\+<${header}>|#include <libnbtplusplus/${header}>|" logic/minecraft/World.cpp
done
```

Library can be found here: https://copr.fedorainfracloud.org/coprs/srakitnican/minecraft/package/libnbtplusplus/

Is there anything else for me to try, or I've reached a dead end?

**Comment by peterix** [comment]
Hmm... I'm not sure if this is a good idea. It's just making it harder to maintain.

What I've done in the dev version now is give all the shared libraries a `MultiMC_` prefix, so they can't clash with any system libraries. This IMHO removes the need to have a separate package for the libraries.

**Comment by peterix** [comment]
If you are making any other changes (patches) needed for packaging, I'd be interested in seeing those.
