### ISSUE TITLE
Minecraft crashed with exitcode 255

### ISSUE THREAD

**Issue by nickykantakom** [MultiMC/MultiMC5#1758]
I have a problem with the Modpack I created and it works sometimes but now my Minecraft won't start.
I got the following report after Minecraft crashed:
http://pastebin.com/pTPihwMR
The bottom of the log just says "AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 255."
I hope you guys can help me! Thanks for reading!

**Comment by QuImUfu** [comment]
Most likely updating OptiFine will fix that problem but you should probably update all mods that are outdated. 
I recreated your mods folder with the newest versions of the mods. Download it [here](https://github.com/MultiMC/MultiMC5/files/672803/mods.zip).
You should update forge, too.

**Comment by nickykantakom** [comment]
Thanks, that solved the problem!
