### ISSUE TITLE
Feature request - zip file has a manifest for mc version and forge version that get auto installed?

### ISSUE THREAD

**Issue by prozacgod** [MultiMC/MultiMC5#1759]
Wondering how hard it would be to make a MultiMC zip file contain the mc version and the core loader versions, exclusively the stuff that MMC already supports (like forge) and minecraft version data.

This would help keep packs a bit smaller when distributing.  And help with distributing without distributing proprietary files as in minecraft binaries.

**Comment by primetoxinz** [comment]
it does that already when you click export on an instance with forge installed

**Comment by prozacgod** [comment]
I'm seeing this now, apologies - Where is the forge version information retained?

I can see how it works with the minecraft version information.

Or is forge just included in the zip file?

**Comment by primetoxinz** [comment]
the forge version should be in <instance>/patches/net.minecraftforge.json near the end of the file

**Comment by prozacgod** [comment]
are the  "+libraries": []     "+tweakers": [] attributes necessary or will it be auto populated when a zip file gets inflated?

**Comment by primetoxinz** [comment]
everything exported is necessary

**Comment by prozacgod** [comment]
Thank you, most helpful
