### ISSUE TITLE
MMC does not update folders name

### ISSUE THREAD

**Issue by Fanamy** [MultiMC/MultiMC5#176]
Version: 0.3.1
Platform: lin32 (Ubuntu 13.10)

Folders in Instances don't update when an Instance is renamed. They keep their creation name.

It doesn't create issues or conflicts between instances but it can be a bit confusing when browsing Instances folder.

Thanks. :)

**Comment by Hyphen** [comment]
Should we expect this?

**Comment by peterix** [comment]
Sometime this year, possibly. I'm consolidating all the suggestions from here on workflowy and will plan some releases based on what I get.

Moved to [workflowy (Ideas -> Instance view)](https://workflowy.com/s/2EyDMcp7CU).
