### ISSUE TITLE
[Feature] Command line parameter to install forge to an instance 

### ISSUE THREAD

**Issue by primetoxinz** [MultiMC/MultiMC5#1760]
It would be convenient to the ability to run `MultiMC --forge <instance id> <forge-version>` to install forge to that instance. This would allow other applications to convert other pack formats, like Curse packs, to MultiMC packs through command line alone, without having to generate the patch files themselves.

**Comment by peterix** [comment]
No, I don't think this would be necessary.

Instead, some config file should refer to the version you want to use and MultiMC having a version list - similarly to how Minecraft is handled right now.

**Comment by Eufranio** [comment]
I also would like to install Forge by command line =/
