### ISSUE TITLE
Little loader 1.10.2 crash related to player list

### ISSUE THREAD

**Issue by GH-Harry** [MultiMC/MultiMC5#1762]
System Information
-----------------------------
MultiMC version: 4.11-713

Operating System: osx sierra

Summary of the issue or suggestion:
----------------------------------------------
By installing liteloader to a instance in 1.10.2 the game crashes when trying to create a world and hints towards the player list (singleplayer)

What should happen:
------------------------------
World simply create like in older versions of mc instead of crashing

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Make a fresh instance of 1.10.2

2. Use the built in installers in edit instance to install forge and liteloader for 1.10.2

3. Launch the game and try to create a new world

Suspected cause:
---------------------------
Liteloader server issue perhaps. I don't really know (something to do with player list)

Logs/Screenshots:
----------------------------
[2016-12-29-6.log.gz](https://github.com/MultiMC/MultiMC5/files/677118/2016-12-29-6.log.gz)

Additional Info:
---------------------------
This happens only and purely with liteloader as regardless of the forge version (or if forge is even installed) the crash happens and this has only been tested in singleplayer

**Comment by peterix** [comment]
The log looks like LiteLoader and Forge do not apply their changes to the game in the right order, but I'm not sure what the problem actually is.

Can you alo attach the normal log? Just hit Upload on the log page after the crash - it should have a lot more information about the loaded libraries and other bits and pieces involved.

**Comment by peterix** [comment]
@Mumfrey - help?

**Comment by Mumfrey** [comment]
This happens when two criteria are met:

* Forge is installed alongside liteloader
* The **original** LiteLoader 1.10.2 release file is used

There is a patch I have to apply to LiteLoader's refmap because forge outright *removes* a public method from `PlayerList`. However for some utterly unknown reason, when I did the initial release build, the patch failed to apply properly. The issue was found and corrected quite quickly but the broken file is still floating around in the wild in a couple of places.

To fix this:

* Simply re-download the liteloader release jar or use the SNAPHOT

**Comment by GH-Harry** [comment]
thank you i'll try to download a snapshot then also sorry for the really late response (have had a LOT of internet issues and hasn't able to do much of anything when it comes to this stuff)

**Comment by GH-Harry** [comment]
I tried reinstalling liteloader with and without forge before and after the multimc update and everthing seems to work fine (Also how exactly do i close the thread i'm very new to how github works and can't quite figure it out)

**Comment by GH-Harry** [comment]
I tried a few things and the results are that the liteloader download (before the 0.5.0 update) seems to work fine with and without forge and the release download (after the 0.5.0 update) crashes (in the same way the issue is listed) with forge but works fine without it however the snapshot download (after the 0.5.0 update) works fine with and without forge.

**Comment by GH-Harry** [comment]
Should the issue be closed as there is a solution or kept open as technically the issue will still occur if people try the combination of liteloader (release download) with forge (i'm very new to github and can't tell what should i do in this scenario)?

**Comment by peterix** [comment]
You will need to delete the original liteloader release jar. In a terminal:
```
rm -f "/Applications/MultiMC 2.app/Contents/MacOS/libraries/com/mumfrey/liteloader/1.10.2/liteloader-1.10.2.jar"
```

@Mumfrey this is a problem. Do you overwrite releases like that regularly? Why not make a new one and increment the version instead?

**Comment by Mumfrey** [comment]
> @Mumfrey this is a problem. Do you overwrite releases like that regularly? Why not make a new one and increment the version instead?

No I've basically only ever done it in this one instance because it was a corrupted artefact and it had been live for such as short time, the md5 and etag were updated accordingly.

**Comment by peterix** [comment]
Alright. Guess a few people managed to grab it anyway. If anyone else has this problem, I will just tell them to delete the jar.

**Comment by Mumfrey** [comment]
> Alright. Guess a few people managed to grab it anyway. If anyone else has this problem, I will just tell them to delete the jar.

I think what happened is that it was cached by cloudflare, meaning it was "available" for longer than I anticipated.
