### ISSUE TITLE
Instance Crash

### ISSUE THREAD

**Issue by ThisIsntAnUsername** [MultiMC/MultiMC5#1765]
System Information
-----------------------------
MultiMC version: 0.4.11-751

Operating System: Windows

Summary of the issue or suggestion: The instance crashes before the game launches
----------------------------------------------

What should happen: The game should launch and show the title screen
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install this version of multimc

2. Install these mods

3. Launch the instance

Suspected cause: From what i've read on other reports maybe a core mods conflict.
---------------------------

Logs/Screenshots: http://paste.ee/p/myoLu
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:This is a curse pack and i used CurseDownloader to download the mods
---------------------------

**Comment by QuImUfu** [comment]
you have added 1.7.10 to the 1.10.2 mods in you mod folder. This does not work. 
Additionally the modpack seems to be made for 1.10.2 while your MC version is 1.7.10.

**Comment by ThisIsntAnUsername** [comment]
Thanks! I just reinstallated it in 1.10.2 and it works fine.
