### ISSUE TITLE
Using one installation with multiple users does not give an error but does not work.

### ISSUE THREAD

**Issue by QuImUfu** [MultiMC/MultiMC5#1766]
System Information
-----------------------------
MultiMC version:
0.4.12-develop-851

Operating System:
Lubuntu 64 bit

Summary of the issue or suggestion:
----------------------------------------------
MultiMC does not support multiple users using one Installation.

But it does not give a proper error message and breaks at lots of points silently.

So i would suggest to check the permissions of the files in the MMC folder or check for the problem in some other way and to give a proper error message at startup.

**Comment by peterix** [comment]
Yes. A lot of such errors are not handled.

**Comment by peterix** [comment]
It's not supposed to be shared between users this way.
