### ISSUE TITLE
Possible Memory Leak in Java Garbage Collector for Multi-Mc 5

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MultiMC/MultiMC5#1768]
System Information
OS Name	Microsoft Windows 10 Pro
Version	10.0.14393 Build 14393
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	ZER0BYTES-HQ
System Manufacturer	Gigabyte Technology Co., Ltd.
System Model	Z97X-Gaming 3
System Type	x64-based PC
System SKU	To be filled by O.E.M.
Processor	Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz, 3501 Mhz, 4 Core(s), 4 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. F7, 9/18/2015
SMBIOS Version	2.7
Embedded Controller Version	255.255
BIOS Mode	Legacy
BaseBoard Manufacturer	Gigabyte Technology Co., Ltd.
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Desktop
Secure Boot State	Unsupported
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.14393.206"
User Name	ZER0BYTES-HQ\Zer0Bytes-HQ
Time Zone	Central Standard Time
Installed Physical Memory (RAM)	20.0 GB
Total Physical Memory	19.9 GB
Available Physical Memory	14.3 GB
Total Virtual Memory	22.9 GB
Available Virtual Memory	15.8 GB
Page File Space	3.00 GB
Page File	C:\pagefile.sys
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

-----------------------------
MultiMC version: MultiMC-5 Version 0.4.11-751 on win32

Operating System: Windows 10 Latest Professional

Summary of the issue or suggestion:
When I launch a Minecraft instance multiple times I noticed more and more slowdown each time. (I don't mean opening multiple instances.)
----------------------------------------------

What should happen:
------------------------------
The memory should clear but it doesn't seem to. I noticed after multiple uses without closing Multi-Mc 5 that my computer starts to crawl.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch a mine-craft instance. (More then 150 mods preferable.) Try my pack to see if its something in my pack.

2. Close instance and reload the instance. (Should only take about 2 or 3 launches to really be noticed.)

Suspected cause:
---------------------------
Something is locking in ram.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
Suspected possible issues with multi-mc garbage collector.

**Comment by QuImUfu** [comment]
i don't think this is even possible. 
MultiMC uses your system Java and it stops Java completely after one instance is closed.
Freeing memory when a process exits is handled by your OS.
Check what is using your system resources via the Taskmanager.

But  there seems to be some sort of Memory problem in MultiMC itself.
Start instances, close them again ... repeat and slowly (very slowly) the RSS size increases. i tested it up to 80mb from 40mb when freshly launched.

**Comment by peterix** [comment]
That honestly sounds like you still have a few copies of java running in the background, rather than any sort of issue with MultiMC using memory.

Check your processes. See what is actually growing.

In the current dev version, a launch 'eats' about 300KB. I'm not sure where the memory is going yet, but it's freed on exit, so it's not leaked.
