### ISSUE TITLE
multimc..I don't know what it means when it says to extract it anywhere

### ISSUE THREAD

**Issue by grannypatty** [MultiMC/MultiMC5#1769]
System Information
-----------------------------
MultiMC version:  5 

Operating System: windows 8.1 pro 64 bit

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by grannypatty** [comment]
I just don't know why to do with the file to make it to where I can open it , wherever I put it?, then open multimc just don't know where to put the rear file

**Comment by nikhiljha** [comment]
Make a folder on your desktop called "MultiMC"

Open the multimc file you downloaded, inside there are a lot of files. Put them all inside the MultiMC folder on your desktop. Open MultiMC.exe to start MultiMC.
