### ISSUE TITLE
Pixelmon

### ISSUE THREAD

**Issue by poqdavid** [MultiMC/MultiMC5#1770]
System Information
-----------------------------
MultiMC version: 5

Operating System: Windows 10 64Bit

Summary of the issue or suggestion:
----------------------------------------------
Well I am trying to load the Pixelmon mod from `\libraries\pixelmon\Pixelmon\1.10.2-5.0.0-universal` and my client just crash's, the thing is that everything works fine when I load the mod using `Loader mods`.

What should happen:
------------------------------
I need to load the mod using patches please help me fix a correct config for this mod

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
http://paste.ee/p/BifmY

Additional Info:
---------------------------
```
{
	"+libraries": [ 
		{
			"name": "pixelmon:Pixelmon:1.10.2-5.0.0-universal",
			"MMC-hint": "local"
		}
	],
	"fileId": "pixelmon.Pixelmon",
	"mcVersion": "1.10.2",
	"name": "Pixelmon",
	"order": 200,
	"version": "1.10.2-5.0.0-universal"
}
```

**Comment by QuImUfu** [comment]
That is because Pixelmon **is** a loader mod, and **not** a tweaker mod and needs to be installed into the mods folder because of this.
Using it as tweaker mod won't work in the vanilla Minecraft launcher, too.
Why do you want to load it as tweaker mod?

**Comment by poqdavid** [comment]
Well the thing is pixelmon mod is pretty large and I need to have different setups so I was think If some how I can have like 1 Pixelmon-1.10.2-5.0.0-universal.jar and I can use it in different instances

**Comment by QuImUfu** [comment]
Link it. That is the only way i know. 
Maybe a symlink is enough or you'll need to hardlink it.

**Comment by poqdavid** [comment]
How i do that?

**Comment by peterix** [comment]
Symlinks on Windows require being an Administrator or tweaking things through group policy:
http://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

**Comment by poqdavid** [comment]
Well if you guys add a option like global loader mod so we can have like 1 folder for mods and different configs

**Comment by peterix** [comment]
There simply is no good way of doing this on Windows without having admin access to the system.
