### ISSUE TITLE
Crash with Spongeforge on MC1.8.9, exit code 1

### ISSUE THREAD

**Issue by Lightsockie** [MultiMC/MultiMC5#1771]
System Information
-----------------------------
MultiMC version: 0.4.11-703

Operating System: Linux (Arch)

Summary of the issue or suggestion: 
----------------------------------------------
MultiMC crashing when adding spongeforge to my mod list. Currently working on a Modpack, and trying to add spongeforge to the list, but I get an "exit code 1". In order to try and isolate the problem, this instance has only MC1.8.9, Forge 1.8.9-1890, and SpongeForge (built targeting Forge 1.8.9-1890). The server version, built with Forge's installer and a copy/paste of the mods, runs successfully. (That's why I'm barking up your tree)

What should happen:
------------------------------
Minecraft1.8.9 launches with Forge and SpongeForge loaded

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create an instance for MC1.8.9

2. Install Forge version 11.15.1.1890

3. Drop Spongeforge version 1.8.9-1890-4.2.0-BETA-1762 into the mod folder
(Download: [here](http://files.minecraftforge.net/maven/org/spongepowered/spongeforge/1.8.9-1890-4.2.0-BETA-1762/spongeforge-1.8.9-1890-4.2.0-BETA-1762.jar))
4. Run the instance

Suspected cause:
---------------------------
 `[15:16:24] [main/INFO]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1527]: java.lang.ClassNotFoundException: The specified class 'net.minecraft.client.Minecraft' was not found`

Logs/Screenshots:
----------------------------
[//]: # http://paste.ee/p/SmRbU

Here's a copy of the log, without Spongeforge: http://paste.ee/p/2R9hb

**Comment by QuImUfu** [comment]
This is fixed in the development channel.
You need to reinstall forge to get an instance created in stable working.
Switch to the development update channel via Settings -> MultiMC ->Feautures ->Update Channel=Development.

**Comment by Lightsockie** [comment]
I tried running my instance after upgrading to the dev channel, and still got the error. I then, however, built a new instance and tried running sponge, and it worked.

So problem is fixed in the dev channel, thanks mate
