### ISSUE TITLE
Liteloader and 1.9

### ISSUE THREAD

**Issue by mendel3** [MultiMC/MultiMC5#1773]
Is it just me or when I try to get liteloader for 1.9 by clicking the install liteloader button, it says that there are no versions. There definitely is a 1.9 version for liteloader because I am using it for my regular minecraft launcher. If it just doesn't recognize that there is one, how would I add it to my instance?

I am on a MacBook Air Version 10.12.2

**Comment by QuImUfu** [comment]
This is fixed in the development channel.
Switch to the development update channel via Settings -> MultiMC ->Feautures ->Update Channel=Development.

**Comment by peterix** [comment]
Or to the new stable version :)
