### ISSUE TITLE
Request - Desktop instance shortcuts?

### ISSUE THREAD

**Issue by Squirtle8459** [MultiMC/MultiMC5#1776]
I'm not sure if this even exists, as I've tried many ways to do so.. 
I have many instances as was curious if I there was a way to add a launcher shortcut to the desktop to launch the main ones I use.. Versus running MultiMC itself and launching it through there..

**Comment by peterix** [comment]
Yes, you can.

If you run it like this: `MultiMC -l "ID"`.

The ID is the name of its folder, not the visual name. In case of tracked FTB instances, the ID is `FTB/folder name`.

**Comment by Squirtle8459** [comment]
Thank you!, this has been resolved now!

**Comment by Paradigm999** [comment]
Would it possible to add a method inside of MultiMC that would create the shortcut on the desktop for me?
I had no issues creating the shortcut but some of my friends aren't very good with computers and will have more problems trying to get this to work. 
This feature could just be included in the right-click context menu for the instance.

**Comment by MulverineX** [comment]
Is this possible on linux?
