### ISSUE TITLE
Probleme when breaking glass

### ISSUE THREAD

**Issue by Dan3a** [MultiMC/MultiMC5#1781]
When i break a block make the glass breaking sound my game freeze and not crash 0 crash reports and 0 error code

Windows 7 64bit Family Edition
(Packard Bell Imedia S3720
![probleme](https://cloud.githubusercontent.com/assets/21985756/21846424/6141e934-d7f7-11e6-8419-472511958dc1.JPG)

**Comment by MRebhan** [comment]
Umm.. this is kind of not related to MultiMC at all.
