### ISSUE TITLE
Add a simple way to replace libraries from the UI

### ISSUE THREAD

**Issue by mezz** [MultiMC/MultiMC5#1782]
The current method of using your own Forge jar is a bit of work to do each time (see https://github.com/MultiMC/MultiMC5/issues/553).

Since I sometimes need to test experimental builds of Forge against packs, it would be very helpful to have an easier method. Maybe a magic place in the instance folder to drop the custom forge jar and have it override everything else.

**Comment by peterix** [comment]
There is a magic place already with 0.5.0. You can put the file in `$instance/libraries/`

You do have to tweak the forge version a bit though - MultiMC has to be instructed to prefer local files.

Replace:
```
        {
            "name": "net.minecraftforge:forge:1.7.10-10.13.4.1558-1.7.10:universal",
            "url": "http://files.minecraftforge.net/maven/"
        },
```
With:
```
        {
            "name": "net.minecraftforge:forge:1.7.10-10.13.4.1558-1.7.10:universal",
            "MMC-hint": "local"
        },
```
Your file can then be `$instance/libraries/forge-1.7.10-10.13.4.1558-1.7.10-universal.jar`.

Or to make it even simpler:
```
        {
            "name": "net.minecraftforge:forge:custom",
            "MMC-hint": "local"
        },
```
Which results in `$instance/libraries/forge-custom.jar`.

![image](https://cloud.githubusercontent.com/assets/203326/21961268/4e94a9d2-db05-11e6-9634-76fb5d08f7d6.png)

**Comment by mezz** [comment]
Thanks, that's a bit easier than what I was doing. 
I should be able to keep reusing the same instance once I have it set up this way.

**Comment by mezz** [comment]
@peterix where is the new location for putting this?
```
        {
            "name": "net.minecraftforge:forge:custom",
            "MMC-hint": "local"
        },
```
My instance's `patches` folder is empty.

**Comment by peterix** [comment]
Click the `Customize` button.

**Comment by mezz** [comment]
Thanks, that adds a file there. 
Before I had "minecraft" selected when I clicked Customize, so I thought it only customized minecraft and I reverted it. I didn't check the patches folder in the meantime.

**Comment by peterix** [comment]
Yep.
The need to use the `Customize` button comes from MultiMC no longer creating these files from scratch on install. They are pre-generated and stored on https://meta.multimc.org. The instances then only contain version numbers.

**Comment by peterix** [comment]
Automating these steps and allowing to override libraries with custom files could be interesting... as long as it wouldn't confuse normal users.

@mezz are you OK with this manual approach?

**Comment by mezz** [comment]
I've been doing it manually with your instructions for a while now, and it works fine. It's still kind of a pain though.
