### ISSUE TITLE
Replace missing tray icon feature

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#1785]
Summary of the issue or suggestion:
----------------------------------------------
Put in some replacement for hiding the MultiMC windows when the game is started.

* Minimize on launch.
* Minimize to tray by hiding all windows?
* Give the tray icon a way to show individual windows? Maybe Steam style?

Anyway:
https://workflowy.com/s/2EyDMcp7CU#/e7051c210ac6

**Comment by peterix** [comment]
The tray features should be entirely optional, there are environments where tray icons no longer exist.

**Comment by darthvader45** [comment]
That is a good feature to add.

**Comment by TNTUP** [comment]
That would be nice to have it back XD Sadly I haven't kept old MMC releases which had it XD

**Comment by QuImUfu** [comment]
@TNTUP some older releases are available here:
 https://github.com/MultiMC/MultiMC5/releases

Please note that old versions are not supported (and are afaik not starting newer MC versions). If you run into an issue you can not reproduce in the newest version, you are on you own.

**Comment by muniategui** [comment]
Are there any news about that feature ? I'm waiting for it also

**Comment by darthvader45** [comment]
I'd wait, in the meantime RBTray works great as a workaround.

**Comment by muniategui** [comment]
Wow thanks for the program didn't know about it

**Comment by darthvader45** [comment]
No problem, I personally prefer it over anything else.

**Comment by TNTUP** [comment]
Rip suggestion, I haven't noticed any commits related to this issue, anyways I don't even use MultiMC but still its a great launcher for FTB modpacks which I still uses :) Btw, Happy Late New Year Peterix!

**Comment by peterix** [comment]
I'm mass closing all of those and moving them to a mind map kind of thing.

**Comment by TNTUP** [comment]
Aah okie! Thanks for the clarification ;)
