### ISSUE TITLE
Minecraft Crash! PLZ HELP!

### ISSUE THREAD

**Issue by Dog3403** [MultiMC/MultiMC5#1787]
Minecraft Keeps crashing and I don't no why plz help. I will post log!
Type in the like below to go to my log!
http://paste.ee/p/bBJT1

**Comment by QuImUfu** [comment]
This is caused by a enchantment id conflict. 
Just change the enchantment id's in "{Instance_DIR}/config/LOT.cfg".

**Comment by Dog3403** [comment]
ok I tried and its not working!

**Comment by QuImUfu** [comment]
post the link to the new log. 
Maybe the values you have chosen are used, too.
They should not be the same as any of the ench. id's in "{Instance_DIR}/config/Arcana_RPG.cfg".
You should aso check the nevermine and Custom Npcs configs, they should also contain enchantment id's.
