### ISSUE TITLE
When clearing the checkbox for custom pre/post commands, the commands themselves get cleared

### ISSUE THREAD

**Issue by oddstr13** [MultiMC/MultiMC5#179]
< Oddstr13> is there any particular reason for custom commands clearing when i uncheck the checkbox? 
    <@peterix> yes. to make them no longer apply
    < Oddstr13> isn't that handled by a boolean?
    < Oddstr13> OverrideCommands=true|false
    <@peterix> could be done that way... yes
    < Oddstr13> would be handy to be able to just uncheck the box, but the command still being there, for temporarily disabling the update script
    <@peterix> put it on github issues

Before unchecking: http://puu.sh/7S8nt.png  
Unchecking then hitting ok: http://puu.sh/7S8ow.png  
Looking at settings again: http://puu.sh/7S8pJ.png

**Comment by peterix** [comment]
This IMHO works as intended. Sorry...
