### ISSUE TITLE
Copying an FTB instance causes a "Unknown instance type" and can't be edited // fixed by editing instance.cfg

### ISSUE THREAD

**Issue by DDzwiedziu** [MultiMC/MultiMC5#1794]
System Information
-----------------------------
MultiMC version: 0.5.0-871

Operating System: Linux

Summary of the issue or suggestion: 
----------------------------------------------
copying an FTB instance causes a "Unknown instance type" and can't be edited

What should happen:  
------------------------------
the exactly same thing, just the opposite .)

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Have an working FTB modpack instance tracked by MultiMC (SkyFactory 3.0.5 in this case).

2. Copy the instance in MultiMC (doing that by ```cp -r``` causes the same effect [!]). 

3. The instance appears almost instantly and shows with a white "X" sign in red circle. In the status bar "Unknown Instance type" is shown. Any launch options are grayed out.

4.  Trying to edit the pack shows something like this: http://imgur.com/a/tzOYu

~Suspected~ cause:
---------------------------
In the ```instance.cfg``` changing the line ```InstanceType=OneSixFTB``` to ```InstanceType=OneSix``` fixes the issue.

Logs/Screenshots:
----------------------------
[//]: # http://imgur.com/a/tzOYu

Additional Info:
---------------------------

**Comment by peterix** [comment]
Fixed in develop.
