### ISSUE TITLE
MINECRAFT CRASH!

### ISSUE THREAD

**Issue by Dog3403** [MultiMC/MultiMC5#1797]
It crashes and I have no idea heres the log!

http://paste.ee/p/MrLIL

**Comment by peterix** [comment]
That looks like a corrupted world.

**Comment by Dog3403** [comment]
corrupted? is there anyway to fix it?

**Comment by LandKingdom** [comment]
You could try to regenerate the chuck with an external tool, or restore a backup, if you have one. If you regenerate the chunk, you'll 100% lose everything in that chunk.

**Comment by Dog3403** [comment]
whats a external tool?

**Comment by LandKingdom** [comment]
Anything not made by Mojang, like MultiMC. You could MCEdit for your world, but I don't know if it works with mods
