### ISSUE TITLE
Active Instances' Context Menu is disabled

### ISSUE THREAD

**Issue by khionu** [MultiMC/MultiMC5#1804]
System Information
-----------------------------
MultiMC version: https://github.com/MultiMC/MultiMC5/commit/0a6af3cff3adf6df641b1ed99aaeac0f4ea4e252

Operating System: Linux Mint 18.1 MATE x64

Summary of the issue or suggestion:
----------------------------------------------
When you have a running instance, if you right click, it will open the context menu for as long as you hold the click. The options are all grayed out/disabled.

What should happen:
------------------------------
Have the context menu, if not all options in it.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Run instance

2. Right click on it.

Suspected cause:
---------------------------
I've only had this issue since the status icons that show whether the instance is running, crashed, etc were added. Maybe they are creating an issue from being above them on the Z coordinate? I don't think this is likely, given I see the correct context options for an Instance, just disabled, but maybe.

**Comment by peterix** [comment]
This is no longer the case.
