### ISSUE TITLE
Simple spelling error

### ISSUE THREAD

**Issue by BloodDragon26** [MultiMC/MultiMC5#1807]
Not as much a bug as it is a spelling error that I noticed.

"MultiMC stopped watching the game log because the log length surpassed 100000 lines.
You may have to fix your mods because the game is still loggging to files and likely wasting harddrive space at an alarming rate!"

In that line logging is misspelled. There is an extra "g" in the middle of the word. Just felt I should let you know!

**Comment by peterix** [comment]
Fixed in develop.
