### ISSUE TITLE
My instance will no longer launch 

### ISSUE THREAD

**Issue by don8life** [MultiMC/MultiMC5#1810]
System Information
-----------------------------
MultiMC version:
     0.5.0-929

Operating System:
     Windows 10

Summary of the issue or suggestion:
----------------------------------------------

When we try to launch the instance we want to play, the console window comes up.  We click launch at the bottom, but it just keeps showing that window.  I looked through the log and don't see anything that says anything about an error, but I am not sure exactly what I'm looking at.

What should happen:
------------------------------

The game should run

Logs/Screenshots:
----------------------------

http://paste.ee/p/NzpS0

**Comment by peterix** [comment]
Interesting. Did this ever work?

MultiMC is not supposed to be placed in any system folders. This includes any sort of `Program Files`,  `bin` or similar. It is not meant to be run using any sort of Administrator/root account either.

**Comment by peterix** [comment]
Grab a fresh download from the site, put it on your desktop, or somewhere in your home folder. Test with vanilla first.

**Comment by don8life** [comment]
Yes, it has worked several times.  Then it wouldn't, so we restarted the computer and it would work the first try, then the same thing happened.  And now even restarting the computer doesn't help.  Thanks!

**Comment by peterix** [comment]
Well, the log is gone. And I have no idea what happened. If you have any more infomration, reopen and tell me.
