### ISSUE TITLE
I am getting an error message, help!

### ISSUE THREAD

**Issue by supersweetdude** [MultiMC/MultiMC5#1812]
System Information
-----------------------------
MultiMC version: 0.5.0 (The latest version as of now)

Operating System: Mac OS X

Summary of the issue or suggestion: I am getting an Error message and I dont know what to do
----------------------------------------------

What should happen: Me logging in seamlessly
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Whenever I try to log in this pops up

2.

3.

Suspected cause: My java is the most recent, so I have no idea
---------------------------

Logs/Screenshots: http://paste.ee/p/r4Yal
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info: Im getting an error I wish I wasn't
---------------------------

**Comment by peterix** [comment]
Make sure that world download mod is actually meant for the version of minecraft you are trying ot use it with.
