### ISSUE TITLE
Entity related crash (I guess)

### ISSUE THREAD

**Issue by tevrenos** [MultiMC/MultiMC5#1815]
I am playing an instance with approx 60+ mods i had a crash a while ago, the game crashed 4 times repeatedly for the same reason, here is the first crash log, 

https://paste.ee/p/jWDdZ

I was unable to understand what exactly caused the crash, it fixed itself after the 4th crash.. but ı obviously want to understand what causes it. can someone please guide me here.

**Comment by QuImUfu** [comment]
It is an issue with the MCA mod in vanilla code when a villager gets converted to a zombie. 
It won't get fixed but can be worked around by setting:
````B:"Enable infection?"=false````
in the MCA-Config.

see:
https://github.com/WildBamaBoy/minecraft-comes-alive/issues/620

**Comment by tevrenos** [comment]
thank you very much, ill try that

**Comment by tevrenos** [comment]
I tried that, and FYI I also edited the forge.cfg; "B:removeErroringEntities=true" and "B:removeErroringTileEntities=true", all seems perfectly fine for now.
