### ISSUE TITLE
[Feature Request] Checkboxes that fire an instance refresh after custom commands run

### ISSUE THREAD

**Issue by kotoroshinoto** [MultiMC/MultiMC5#1817]
Some nifty tools exist or could possibly be written that can be run via the pre-launch or post-launch commands.

if someone is setting up a modpack to run via multimc and autoupdate prior to launch, it'd be nifty to be able to change minecraft version/forge_version, and other such multimc managed settings during this update step, however currently there is no way to induce an instance refresh between the pre-launch command and the actual launch of the client (meaning those changes probably wouldn't happen  without force-killing the client and manually refreshing, which is a big kludge).

I dont know the functional sequence order that multimc currently uses for these things, but my thought is that to do this properly would likely require that the pre-launch command operates before multimc checks the MC version and liteloader/forge version selections and downloads/installs any required assets.

reference issue with one particular nifty tool: https://github.com/XDjackieXD/PackUpdate/issues/11#issuecomment-280419914

**Comment by peterix** [comment]
That is intentional. The per-launch and post-exit scripts are not meant to manipulate the instance in any significant way. Especially not change any versions.

**Comment by peterix** [comment]
Looked at that other repo. Interesting.

Anyway, I would like to keep updates fully in control of the user.

**Comment by kotoroshinoto** [comment]
entirely up to you guys, the instance settings would be what enable the updating in cases like this, so technically its user choice to allow this. I just figured i'd give a heads up for the idea.

**Comment by peterix** [comment]
Yeah, MultiMC is not even supposed to be extensible this way. The commands are there only for the user, not a third party providing tools. If you use them for updating your modpacks, you are possibly overriding something the user wanted to do, which is fundamentally wrong.

So, no.
