### ISSUE TITLE
Erratic keyboard behavior after issuing any command.

### ISSUE THREAD

**Issue by jewooldridge** [MultiMC/MultiMC5#1820]
System Information
-----------------------------
MultiMC version:
0.5.0-945 (Win32)

Operating System:
Windows 10 Professional (Version 10.0.14393 Build 14393)

Summary of the issue or suggestion:
----------------------------------------------
Erratic keyboard behavior in Minecraft 11.2 after issuing any command, such as /tp ~ ~+1 ~.  Navigation keys (WASD) will alternate between not responding at all and acting like they're being held down when they're not.  If I hit the W key, either nothing will happen, or I'll start moving forward and keep moving forward after I release the key.

What should happen:
------------------------------
Would expect the navigation keys to operate normally.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.  Clean install of Java 8, 64-bit.  No other java instances are installed.

2.  Clean install of MultiMc 5

3.  Vanilla Minecraft 11.2, no mods, no forge

4.  Create new world, default settings.

5.  Walk around for a few seconds.

6.  Enter /tp ~ ~+1 ~.

7.  Walk around again for a few seconds and the erratic keyboard behavior should be obvious.

Suspected cause:
---------------------------
Unknown

Logs/Screenshots:
----------------------------

[MultiMC Log.txt](https://github.com/MultiMC/MultiMC5/files/786218/MultiMC.Log.txt)

Additional Info:
---------------------------
This is a brand new computer (Dell XPS 15).  Other than Microsoft Office, not much else is installed on this machine yet.  I'm running Bitdefender security software.

I've tried swapping keyboards from a hardwired USB keyboard to a Logitech wireless keyboard.  The issue was present with both. 

I installed a new, clean instance of Minecraft using the default Minecraft launcher and haven't been able to recreate the problem.  I've only been able to create the issue using MultiMc.  

I have a nearly identical setup running on a MacBook Pro 15 (late 2013), Windows 10 (bootcamp).  I can't recreate the issue there either.

**Comment by peterix** [comment]
Cool. That actually sounds like a bug!

As the thing that handles input and output in Minecraft is LWJGL, and MultiMC makes Minecraft use a slightly older version, you could try using a newer version.

On the version page, select LWJGL, click `Customize` and `Edit`. It should open in a text editor.

Then replace all of the instances of `2.9.1` with `2.9.4-nightly-20150209` and save the file.

See if that helps.

**Comment by peterix** [comment]
Now you could just change the version from the UI... Well, closing this.
