### ISSUE TITLE
Error Messages Galore After Playing Minecraft for a Couple of Hours

### ISSUE THREAD

**Issue by Theta1996** [MultiMC/MultiMC5#1822]
System Information
-----------------------------
MultiMC version: 0.5.0-945

Operating System: Windows 10 Home - 64-bit

Summary of the issue or suggestion:
----------------------------------------------
Since the last update you guys released for MultiMC, I keep getting the same error message appear on my screen after just a couple or three hours of playing my instance ([Link here to image](https://www.dropbox.com/s/wjfzimpbrtr03zj/Screenshot%202017-02-21%2000.51.50.png?dl=0)). This has happened every time I've played since the update.

What should happen:
------------------------------
The game should run and error mesages shouldn't be appearing saying the MultiMC has has requested to terminate unusually.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Play game for about 2-3 hours

2.

3.

Suspected cause:
---------------------------
No Idea

Logs/Screenshots:
----------------------------
Can't find any logs from MultiMC itself, but from the instance links [here](https://www.dropbox.com/s/c9ajvn50eyci8db/2017-02-19-1.log?dl=0)

Additional Info:
---------------------------

**Comment by peterix** [comment]
Hmm... not sure. It would be worth it to do some soak testing though.

**Comment by peterix** [comment]
¯\\\_(ツ)\_/¯
