### ISSUE TITLE
Cannot connect to server missing blocks and items

### ISSUE THREAD

**Issue by panslothda** [MultiMC/MultiMC5#1823]
System Information
-----------------------------
MultiMC version:
-----------------------------
0.5.0-develop-886

Operating System:
-----------------------------
Arch Linux x64 
Kernel 4.9.9-1-ARCH

Summary of the issue or suggestion:
----------------------------------------------

Every time i try to connect to the server of a modpack me and a few friends play on i get the following error message: [Netty Epoll Client IO #0/ERROR] [FML]: Failed to connect to server: there are 2 missing blocks and items

What should happen:
------------------------------
I should be able to connect

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Make instance

2. start instance

3. click connect to server

Suspected cause:
---------------------------
no clue tbh at this point

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

The whole startup log: https://paste.ee/p/ESeCY

Relevant part when trying to connect to server: https://paste.ee/p/xBQHC

Server console while trying to connect: http://pastebin.com/pzULSFZN (Note the missing 2 mods are normal and server side. all other players also don't have them and can connect)

Additional Info:
---------------------------

Normally i would say it isn't an issue with MultiMC and a modpack issue but at this point i kinda don't see anymore what we could try.

What we tried to fix problem:

- Make sure other people can play on the server. 

- Export instance of a friend who also uses MultiMC (on windows tough) who is able to connect with that    instance to the server and importing it into MultiMC and try to connect. 

- Completely delete all files of MultiMC and redownload instance and MultiMC and make a fresh installation of it. 

- Download server config and try it directly like that in the client. 

- look at server console while trying to connect.  (no error message)

- deleting player.dat file on server so no corrupted profile

So ye at this point we don't think its a problem with the modpack. Everyone else is able to join with that exact instance. I'm the only one that uses MultiMC with Linux so this is literally the only variable we didn't test that could be different. If this turns out to not be Multi MCs fault i'm terribly sorry but i cant think of another possibility.

**Comment by peterix** [comment]
The only thing I can think of is filename differences between windows and linux.

Do you have a link to the pack?

**Comment by panslothda** [comment]
Sure: https://www.curseforge.com/projects/259031

**Comment by QuImUfu** [comment]
how can one get (temporarily) whitelisted for the server? 
I would like to try if i can join using linux and MultiMC.

**Comment by panslothda** [comment]
give me your MC name and i can see that owner Whitelists you :)

**Comment by QuImUfu** [comment]
i'm QuImUfu in Minecraft, too.

**Comment by panslothda** [comment]
Welp seems like QulmUfu isn't a minecraft account. https://mcuuid.net/?q=QulmUfu and http://i.imgur.com/GHlZZg8.png

**Comment by QuImUfu** [comment]
You have to write it all lowercase to use/do something with it, but it is displayed with uppercase letters.
![quimufu](https://cloud.githubusercontent.com/assets/9885301/23245171/d2c378ac-f98a-11e6-975a-fd6aa42ad5a7.png)
idk why :confused: 
see:
https://mcuuid.net/?q=quimufu

**Comment by QuImUfu** [comment]
@panslothda  
have you tried to whitelist me as quimufu without the uppercase letters?

**Comment by panslothda** [comment]
Waiting for owner of server to try it. He wasnt online yet :) will tell you when he tells me that it happened

**Comment by panslothda** [comment]
Well i wasn't able to solve the issue but since the server i'm playing on will switch the modpack in like a few days doesn't matter anymore at this point thanks for the try tough everyone.
