### ISSUE TITLE
mods do not seem to be added to minecraft

### ISSUE THREAD

**Issue by kiingkiller** [MultiMC/MultiMC5#1826]
every time i load the game up it simply says that forge is installed and thats it, every other mod i install simply does not appear, i've tried to load it into jar, in the mods folder and non of them work. im only trying to get it to install on mod currently.

**Comment by peterix** [comment]
You will have to be a lot more specific than that.

**Comment by kiingkiller** [comment]
sorry, 
1.7.10
i have tried journey map and not enough items, both appear in the mod page on the program but when i launch it nether of them appear.

**Comment by Dinoway** [comment]
I'm Having Problems installing Optifine To My minecraft version when using MultiMC

**Comment by QuImUfu** [comment]
@kiingkiller 
i made a short video showing the installation of these mods (NEI (with Code Chicken Core) and JourneyMap) with MultiMC:
https://www.youtube.com/watch?v=0O0rFEPyhLs
if you do it this way, it should work.
@Dinoway 
for information about Optifine and MMC see:
https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine
