### ISSUE TITLE
Memory Increase Results In Crash (Java 64bit)

### ISSUE THREAD

**Issue by arceus4932** [MultiMC/MultiMC5#1831]
System Information
-----------------------------
MultiMC version: 0.5.0-945

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Opening the instance with memory higher than default, results in a crash.

What should happen:
------------------------------
The game should open fine without crashing with higher allocated memory.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Click on Instance- Then Launch

2. Game crashes, produced log (Every time)

Suspected cause:
---------------------------
Issue with the Java thinking it is 32 bit? No clue.

Logs/Screenshots:
----------------------------
https://paste.ee/p/AU7JC

Additional Info:
---------------------------
- My system, browser and java are 64 bit, I do not understand why MultiMC Says it is not 64.

- It is worth noting, with default memory, I can OPEN the instance, but it is laggy beyond playable. The instance works 100% fine on my laptop, with no lag at all (I have more memory allocated there)

- I have 6.9 usable GB or RAM, and am trying to allocate 2GB.

- In the log(Lines 12 and 15), it says my system is 64 bit and Java is not, but I've redownloaded 4 times and it is indeed 64 bit.

**Comment by Heufneutje** [comment]
Then you might have some other 32-bit version installed somewhere else and MultiMC is using the wrong one. In the MultiMC settings, under the Java tab you can make it auto-detect all versions of Java you have installed. After that you can select the 64-bit version.
