### ISSUE TITLE
Organise mods in (virtual) folders or categories

### ISSUE THREAD

**Issue by ghost** [MultiMC/MultiMC5#1835]
Basically, having a long list of mods is rather disorganised. Would it be possible to implement some sort of organisation? preferably in a folder-tree kind of fashion. E.g.
Having root-folders/categories like tech, magic, decoration etc. but also so that we can place library-mods together with their dependants.

**Comment by peterix** [comment]
I added it to workflowy: https://workflowy.com/s/2EyDMcp7CU#/9f5db2bb35d3

This does conflict with the other ideas alerady on there, but it sounds interesting.
