### ISSUE TITLE
Importing instances from Curse Client / "twitch Client"

### ISSUE THREAD

**Issue by Yijare** [MultiMC/MultiMC5#1837]
System Information
-----------------------------
MultiMC version:  0.5.0-945win32

Operating System: Win7Ultimate64bit

Summary of the issue or suggestion:
----------------------------------------------
Importing instances from Curse fail, because the launcher does not provide instance.cfg

What should happen:
------------------------------
Generate instance.cfg on import

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. zip up the instance you want to import

2. hit import

Suspected cause:
---------------------------
curse launcher provides no instance.cfg

Logs/Screenshots:
----------------------------
![mc5-error](https://cloud.githubusercontent.com/assets/5788141/23825762/34911cb2-0690-11e7-98d9-7c19a0dc8a16.png)

Additional Info:
---------------------------

**Comment by peterix** [comment]
This is not intended to work.
