### ISSUE TITLE
Crash Report that doesn't seem to link to any particular mod

### ISSUE THREAD

**Issue by Primal-Ursus** [MultiMC/MultiMC5#1838]
The report doesn't seem to link to any of my mods, perhaps it's a launcher issue? Here's the crash log
http://pastebin.com/iYEr9EkS

**Comment by peterix** [comment]
Provide a full log. Crash logs do not contain enough information to even begin any sort of investigation.

**Comment by Primal-Ursus** [comment]
http://pastebin.com/d54vAVLT Directly from the MultiMC Log

**Comment by peterix** [comment]
The instance has mods for multiple versions of Minecraft. As you can see, the 1.8.0 optifine is failing to patch the 1.7.10 vanilla class files. Not all of the mods list the Minecraft version, but at least using the right version of Optifine would help.

**Comment by Primal-Ursus** [comment]
Ah sorry, didn't realise when I downloaded it thanks for the help!
