### ISSUE TITLE
Paste.ee API & MultiMC errors

### ISSUE THREAD

**Issue by spannerman79** [MultiMC/MultiMC5#1839]
Version: 0.5.0-develop-947

It seems the Paste.ee API changed.  Thus it is causing issues whenever you try to enter your own API key in (developer or user key obtained via Paste.ee) - entering either in logs this to MultiMC log

`paste.ee reported error: "error_invalid_key"`

Both myself and LostOfThought#0089 (Discord) tried ourselves and still the same issue.

"New" Paste.ee API reference docs - https://pastee.github.io/docs/

**Comment by spannerman79** [comment]
Possible alternatives;

[Gist](https://developer.github.com/v3/gists/) Requires [OAuth Scope](https://developer.github.com/v3/oauth/#scopes)

To shorten Gist URL's could have support for [Polr Project](https://docs.polr.me/en/latest/) - [API](https://docs.polr.me/en/latest/developer-guide/api/)

Polr would/could tie in with modpack authors that might use MultiMC instead of other platforms (Technic/Curse) - if/when MultiMC has the ability to read/deploy modpacks and the pack updates 😛

**Comment by peterix** [comment]
I will fix the issue, if there is one. Any suggestions about expanding the functionality do not belong here.

**Comment by peterix** [comment]
Also, URL shortening is a horrible idea. I will never do that.

**Comment by peterix** [comment]
Alright. this is now fixed...

Reading my comments above? Uhh... I guess I wasn't having a good day. Sorry.
