### ISSUE TITLE
Instance mod list export

### ISSUE THREAD

**Issue by scorpion421** [MultiMC/MultiMC5#184]
First of all: Thank you for the continuation of MultiMC - can't get mentioned too often :).

My ideas:

• When you open "Manage Mods", there could be a button to export the list of all mods. In the exporting-window, there are a following options:
[X] Read mcmod.properties
[X] Use regular expression for exporting
[X] Exclude folders in /mod/ directory
[X] Recursive listing of all mods
(•) Export as CSV
(•) Export as HTML
(•) Export as TXT

• mcmod.properties editor
This would be a mighty feature - not only for users - also for developers.
It should be a simple editor, just filling out a mask.
This could be a context-feature by clicking on the specific mod, or simply selecting it and having a separated button with "Edit".

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Mod list)](https://workflowy.com/s/2EyDMcp7CU)
