### ISSUE TITLE
Pastebin like sites

### ISSUE THREAD

**Issue by spannerman79** [MultiMC/MultiMC5#1840]
As per @peterix request via Discord here is a list of pastebin like sites

#### Hastebin.com

- Can be self hosted ( https://github.com/seejohnrun/haste-server ) and has a client ( https://github.com/seejohnrun/haste-client )  Seems you can do a direct `POST` https://github.com/diethnis/standalones/blob/master/hastebin.sh#L30..L38
- Restricted to 512KB on non-self hosted ( [Source](https://github.com/diethnis/standalones/blob/master/hastebin.sh#L23) )

#### uPaste.me

- No API access unless your a member aka anon posting. Limited to 250kb
- Limited to 500kb as member/with API key
- Cheaper then Pastebin.com ( [Info](http://upaste.me/perks) )

#### Pastie.org

Unable to check - I keep on getting Cloudflare's [522](https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522-Connection-timed-out) errors

#### OneTimeSecret

One time use paste. Useless for sharing log files. After the first click/access paste is destroyed.  More suited to sharing sensitive data (eg non stripped MultiMC log, IP, UUID, https://onetimesecret.com/about )

#### Pastebin.com

_If I didn't include this others would suggest it @peterix 😛_ 

- API information http://pastebin.com/api
- 👎 obtrusive advertising http://i.imgur.com/fi6pGPa.png

**Comment by Scotsguy** [comment]
The last working [snapshot](https://web.archive.org/web/20161210162426/http://pastie.org/) of Pastie.org is from December of 2016, but I can't seem to find anything about an upload limit.

Also, do these maybe have to do with [my screenshot](https://cdn.discordapp.com/attachments/134843027553255425/292304845292175380/unknown.png) :P ?

**Comment by QuImUfu** [comment]
what about:
**ghostbin.com**
 - has some sort of [api](https://ghostbin.com/paste/p3qcy)
 - 1 MByte file size limit
 - no advertisements
 - can't scroll sidewards

**Comment by Scotsguy** [comment]
[Privatebin](privatebin.info)?

- Has an [API](https://github.com/PrivateBin/PrivateBin/wiki/API)
- Can be self-hosted
- There's a list of public [privatebins](https://github.com/PrivateBin/PrivateBin/wiki/PrivateBin-Directory) (each with their own paste limits?)
- Expiry times from burn on read to never
- Optional Passwords
