### ISSUE TITLE
My MultiMC is broken

### ISSUE THREAD

**Issue by KostasX98** [MultiMC/MultiMC5#1841]
I Downloaded MultiMC and it crashes when i try to play.
I reinstalled it 2 times but its still crashes i dont know if thats because im from Windows 10.

**Comment by peterix** [comment]
You cannot install it, because it has no installer. Are you sure you got the right thing?

What do you mean by `crashes`?

**Comment by KostasX98** [comment]
Im trying to Launch minecraft 1.11.2 from MultiMC and shows me the Minecraft Log

**Comment by KostasX98** [comment]
Im trying to Launch minecraft 1.11.2 from MultiMC and shows me the Minecraft Log

**Comment by peterix** [comment]
I'm sorry, but that's like saying that your car doesn't start.

Click that Upload button and give me the link to the uploaded log.

**Comment by KostasX98** [comment]
https://paste.ee/p/LYct2

**Comment by QuImUfu** [comment]
Likely another duplicate of #1276. Intels drivers for old iGPU's do not Work with newer Java versions. Worked around by using an java version older than 8u60 for MultiMC.

**Comment by peterix** [comment]
Indeed, the best course of action is to use this java: https://files.multimc.org/downloads/jre-8u51-windows-x64.zip

Extract it somewhere in MultiMC's folder and set the `javaw.exe` as the Java to use in MultiMC.

**Comment by KostasX98** [comment]
Thanks for the help, its finnaly working!
But how i can install 5zig and Optifine with MultiMC ?

**Comment by tehbasshunter** [comment]
If you have forge installed you can copy the jar into your mods folder for the instance.

**Comment by GmanAtheist** [comment]
WOW!. Great support . Thanks . This will help a lot of people. :-)
