### ISSUE TITLE
EC_curve_nist2nid could not be located in ssleay32.dll

### ISSUE THREAD

**Issue by robertmaxton42** [MultiMC/MultiMC5#1843]
System Information
-----------------------------
MultiMC version: 0.5.1

Operating System: Windows 10 Home Insider Preview (15048)

Summary of the issue or suggestion:
----------------------------------------------

Upon running MultiMC, I get an error dialog:

    The procedure entry point EC_curve_nist2nid could not be located in the dynamic link library (...)\MultiMC\ssleay32.dll

This is a fresh download of MultiMC. Upon clicking "OK," MultiMC configures itself and loads, but immediately crashes (presumably because it can't find the function it needs.)

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download and unpack MultiMC

2. Run MultiMC.exe

Logs/Screenshots:
----------------------------
http://pastebin.com/JFtEGS2e

**Comment by peterix** [comment]
Works on Windows XP.

**Comment by peterix** [comment]
And Windows 7.

**Comment by robertmaxton42** [comment]
...um, okay, but changing operating systems isn't really an option for me.

**Comment by Heufneutje** [comment]
Does it work on a stable version of Windows 10 rather than the beta you're running now? Technical previews aren't meant to be run as a general use OS.

**Comment by robertmaxton42** [comment]
Resolved by updating to the latest version in the Slow track and also reinstalling VC++ Redistribution 2015. Unfortunately I did both in the same reboot, so I don't know which resolved the problem, but I suspect it was the latter.

**Comment by peterix** [comment]
MultiMC does not use the VC++ runtimes, it is built with GNU tools only.... So I'd guess it is some sort of library loader bug in Windows.
