### ISSUE TITLE
I honestly have no clue what caused the fatal error. I have listed the stuff I do leading up to it

### ISSUE THREAD

**Issue by RiddlerStorm** [MultiMC/MultiMC5#1850]
System Information
-----------------------------
MultiMC version: 0.5.0-945

Operating System: Windows

Summary of the issue or suggestion:
----------------------------------------------
I am trying to paste a saved schematic to make sure it works. When I try my minecraft crashes immediately. It has pasted it once so I know it works, but I can't get it to do it again. It is driving me crazy.

What should happen:
------------------------------
It should paste the saved schematic from minecraft world edit.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open minecraft and do the command //schem load teapot

2. Then do the command //paste

3. Then crash and cry in a corner (if you're me)

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/eofOq

Additional Info:
---------------------------

**Comment by peterix** [comment]
```
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
```

Your Minecraft ran out of memory. Give it more than the default 512-1024MB. That is only sufficient for playing completely unmodded vanilla these days.
