### ISSUE TITLE
[Latest Dev Build - 0.5.0-develop-913] Jar Specified is Null

### ISSUE THREAD

**Issue by cjburkey01** [MultiMC/MultiMC5#1853]
System Information
-----------------------------
MultiMC version:
0.5.0-develop-913

Operating System:
**MacOSX 10.12.4**

Summary of the issue or suggestion:
----------------------------------------------
Upon launch, the console just shows `Instance update failed because: Null jar is specified in the metadata, aborting...`

What should happen:
------------------------------
The game should launch normally.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Try using the latest dev build

2. Launch 1.11.2

Suspected cause:
---------------------------
Something wrong with how the version jar is found on Mac.  Actually, it may be a connectivity error, I couldn't upload the logs, either: `MultiMC: Log upload failed!`

Logs/Screenshots:
----------------------------
Actually, couldn't upload the log from the launcher.
[Here's the log](https://paste.ee/p/nPg8j)

Additional Info:
---------------------------
Launcher functions perfectly fine if running on stable channel, it only begins to error when updating.  Downgrading fixes.

**Comment by QuImUfu** [comment]
Can confirm on Lubuntu Linux 16.10

**Comment by panslothda** [comment]
And on Arch linux with newest dev build

**Comment by peterix** [comment]
Well, things are actually changing in develop now. And I shouldn't push changes late in the night while half asleep :)

Should be all in sync now.

**Comment by flcmc** [comment]
@cjburkey01  0.5.0-develop-913 isn't the latest development build, 0.5.0-develop-949 is the latest.

**Comment by peterix** [comment]
http://ci.multimc.org/waterfall ... see different build numbers on different kinds of build.

**Comment by flcmc** [comment]
Wasn't aware that the build numbers were different, assumed that they all matched up.

**Comment by peterix** [comment]
Anyway, FTB is broken now... and probably legacy instances.
![image](https://cloud.githubusercontent.com/assets/203326/25021236/c882d076-2091-11e7-93e0-1ebae05b91ce.png)

**Comment by cjburkey01** [comment]
@peterix Even new instances have the same issue upon launching.  They don't even download any assets.

**Comment by peterix** [comment]
Are you sure? Because I don't really see that.

**Comment by cjburkey01** [comment]
@peterix I tried it on 1.11.2, I'll have to try it again later, can't right now.

**Comment by Monkeyfume** [comment]
I'm still having this issue. In fact, I've had it on two different builds on two different computers with two different 1.12.2 clients.

**Comment by peterix** [comment]
@Monkeyfume  Not sure how this is related to an issue from 2017. Don't assume similarly sounding things are the same and please open a new issue.

I'll just close this one, because it's been dead for 2 years..
