### ISSUE TITLE
Bad User Practice Can Lead to MultiMC Crash

### ISSUE THREAD

**Issue by flcmc** [MultiMC/MultiMC5#1854]
System Information
-----------------------------
MultiMC version: 0.5.0-develop-950

Operating System: Windows

Summary of the issue or suggestion:
----------------------------------------------
MultiMC completely crashes when the user tries to kill an instance that has already been terminated.

When killing an instance, MultiMC should check if the instance is still open.

This may also be an issue when the user tries to kill a frozen instance that closes before confirmation of killing the instance.

What should happen:
------------------------------
Nothing should happen when user tries to kill the instance.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch any instance

2. Press the Kill button, but don't actually confirm it.

3. Close Minecraft. 
 
4. Go back to the MultiMC console and confirm killing the instance.

Suspected cause:
---------------------------
MultiMC doesn't check if the instance is already closed.

Logs/Screenshots:
----------------------------
No Logs, MultiMC simply crashes.

**Comment by peterix** [comment]
Good one. There's likely a lot of those around.

**Comment by peterix** [comment]
Should be fixed in develop.
