### ISSUE TITLE
[Simple Request] Add Launch Offline Button to Instance UI.

### ISSUE THREAD

**Issue by flcmc** [MultiMC/MultiMC5#1855]
System Information
-----------------------------
MultiMC version: 0.5.0-develop-950

Operating System: Windows

Summary of the issue or suggestion:
----------------------------------------------
Sometimes I find it to be such a hassle that there is no Launch Offline button on the Instance UI. I was wondering if you could add the button just like on the main UI.

Logs/Screenshots:
----------------------------
Instance UI:
![offline](https://cloud.githubusercontent.com/assets/27444769/25022033/609d3872-2062-11e7-955d-eb1ba00e788c.PNG)
Main UI:
![main](https://cloud.githubusercontent.com/assets/27444769/25022037/6832a6da-2062-11e7-9ac1-fb3ca9e1c624.PNG)

**Comment by peterix** [comment]
Makes sense :)

**Comment by flcmc** [comment]
Implemented in develop (0132fd99291e359aae4af184c5f57ace21bf9863).
