### ISSUE TITLE
Meta files do not update when changed on server side

### ISSUE THREAD

**Issue by SPACEFACE2394** [MultiMC/MultiMC5#1856]
https://paste.ee/p/Qg3US
Please Help

**Comment by peterix** [comment]
Interesting.

What are the contents of that instance's `patches` folder?

Is there a forge json in there?

And if so, can you post it here?

**Comment by peterix** [comment]
Does the version page of the instance look like this? Or are any of the listed versions marked as 'Custom'?
![image](https://cloud.githubusercontent.com/assets/203326/25055462/3c90f822-2163-11e7-9289-1adc5f31976b.png)

**Comment by SPACEFACE2394** [comment]
{
    "+libraries": [
        {
            "insert": "replace",
            "name": "org.apache.commons:commons-lang3:3.3.2"
        },
        {
            "insert": "replace",
            "name": "com.google.guava:guava:17.0"
        },
        {
            "insert": "prepend",
            "name": "lzma:lzma:0.0.1"
        },
        {
            "MMC-hint": "forge-pack-xz",
            "insert": "prepend",
            "name": "org.scala-lang:scala-xml_2.11:1.0.2",
            "url": "http://files.minecraftforge.net/maven/"
        },
        {
            "MMC-hint": "forge-pack-xz",
            "insert": "prepend",
            "name": "org.scala-lang:scala-swing_2.11:1.0.1",
            "url": "http://files.minecraftforge.net/maven/"
        },
        {
            "MMC-hint": "forge-pack-xz",
            "insert": "prepend",
            "name": "org.scala-lang:scala-reflect:2.11.1",
            "url": "http://files.minecraftforge.net/maven/"
        },
        {
            "MMC-hint": "forge-pack-xz",
            "insert": "prepend",
            "name": "org.scala-lang:scala-parser-combinators_2.11:1.0.1",
            "url": "http://files.minecraftforge.net/maven/"
        },
        {
            "MMC-hint": "forge-pack-xz",
            "insert": "prepend",
            "name": "org.scala-lang:scala-library:2.11.1",
            "url": "http://files.minecraftforge.net/maven/"
        },
        {
            "MMC-hint": "forge-pack-xz",
            "insert": "prepend",
            "name": "org.scala-lang.plugins:scala-continuations-plugin_2.11.1:1.0.2",
            "url": "http://files.minecraftforge.net/maven/"
        },
        {
            "MMC-hint": "forge-pack-xz",
            "insert": "prepend",
            "name": "org.scala-lang.plugins:scala-continuations-library_2.11:1.0.2",
            "url": "http://files.minecraftforge.net/maven/"
        },
        {
            "MMC-hint": "forge-pack-xz",
            "insert": "prepend",
            "name": "org.scala-lang:scala-compiler:2.11.1",
            "url": "http://files.minecraftforge.net/maven/"
        },
        {
            "MMC-hint": "forge-pack-xz",
            "insert": "prepend",
            "name": "org.scala-lang:scala-actors-migration_2.11:1.1.0",
            "url": "http://files.minecraftforge.net/maven/"
        },
        {
            "MMC-hint": "forge-pack-xz",
            "insert": "prepend",
            "name": "com.typesafe:config:1.2.1",
            "url": "http://files.minecraftforge.net/maven/"
        },
        {
            "MMC-hint": "forge-pack-xz",
            "insert": "prepend",
            "name": "com.typesafe.akka:akka-actor_2.11:2.3.3",
            "url": "http://files.minecraftforge.net/maven/"
        },
        {
            "insert": "prepend",
            "name": "org.ow2.asm:asm-all:5.0.3"
        },
        {
            "insert": "prepend",
            "name": "net.minecraft:launchwrapper:1.12"
        },
        {
            "MMC-depend": "hard",
            "insert": "prepend",
            "name": 

Theres the only files in the patches folder i can't take a picture of the console window though i don't know how

**Comment by SPACEFACE2394** [comment]
file*

**Comment by peterix** [comment]
Does the Minecraft entry has a green checkmark next to it?

**Comment by peterix** [comment]
Anyway, you are missing a lot of the things from the actual Minecraft json file.

This is where it should be:
![image](https://cloud.githubusercontent.com/assets/203326/25056970/a0f39ec4-216c-11e7-9232-a64bf6d3a1bf.png)

What's inside?

If you remove it and restart MultiMC, it should grab a fresh copy and work.

**Comment by SPACEFACE2394** [comment]
Thanks it works!

**Comment by peterix** [comment]
Alright. I think I see what's wrong... new files are not pulled when they change on the server side. Just blast the whole meta folder into high heavens whenever this happens again. I'll be working on a fix.

**Comment by SPACEFACE2394** [comment]
Thanks!

**Comment by peterix** [comment]
Not fixed yet ;)

**Comment by peterix** [comment]
I believe this is now actually fixed.
