### ISSUE TITLE
Freezing while launching an instance

### ISSUE THREAD

**Issue by Profitmann** [MultiMC/MultiMC5#1857]
System Information
-----------------------------
MultiMC version:
0.5.0-887
Operating System:
Linux Mint 17
Summary of the issue or suggestion:
----------------------------------------------
After a few minutes into the launching sequence of an instance, my whole computer freezes up and I have to restart my computer. I am able to move my mouse around, but my computer won't accept any keyboard input.

What should happen:
------------------------------
The instance should launch as usual, without any errors.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Be me

Suspected cause:
---------------------------
The operating system? Not sure, I'm sort of a noob to linux

Logs/Screenshots:
----------------------------
https://paste.ee/p/0Hyw6 - fml-client-1.log
https://paste.ee/p/b3zUw - fml-client-2.log
https://paste.ee/p/NF66I - fml-client-latest.log
https://paste.ee/p/EV0so - fml-junk-earlystartup.log
https://paste.ee/p/C0KPu - latest.log

Additional Info:
---------------------------

**Comment by QuImUfu** [comment]
In the log there is no problem visible. I think this might be a graphics driver issue. 
Is Vanilla Minecraft working?
post the output of:
````
sudo lshw -c video
````
and
````
sudo glxinfo -B
````

**Comment by Profitmann** [comment]
1st:
 *-display               
       description: VGA compatible controller
       product: GT216GLM [Quadro FX 880M]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a2
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nouveau latency=0
       resources: irq:35 memory:d2000000-d2ffffff memory:c0000000-cfffffff memory:d0000000-d1ffffff ioport:5000(size=128) memory:d3080000-d30fffff

2nd: (had to do sudo glxinfo -b instead since -B didn't work)
33

**Comment by Profitmann** [comment]
Nevermind, I fixed it by updating my drivers in the Driver Manager from nouveau to 3.4 (or something like that)

**Comment by QuImUfu** [comment]
If you want to use the open (Nouveau) driver in future (you may decide to do that because the closed nvidia Driver, at least on my PC, randomly crashes the X server on newer versions of ubuntu), you have to disable the forge splash screen in "minecraft/config/splash.properties" (set enabled=false). It needs the driver to support something Nouveau doesn't support.
Warning: the open driver is bugged and slow, if possible keep the closed one you have now installed over "Additional Drivers"/"Driver Manager".
