### ISSUE TITLE
Old Jarmods broken, develop-956 build

### ISSUE THREAD

**Issue by LoganPaul1** [MultiMC/MultiMC5#1860]
System Information
-----------------------------
MultiMC version: 0.5.0 Dev 956

Operating System: Windows 10 64bit

Summary of the issue or suggestion:
----------------------------------------------
All jarmods that were previously added no longer load. If I add a new jarmod it works perfectly fine but the ones that currently are in there (while reporting everything is fine and dandy) do not load. Tested on 1.2.5 and b1.7.3

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. In a previous build, create an instance of any version and add a jarmod to it

2. Update to build 956

3. Bask in the glory of the non-working jarmods

Suspected cause:
---------------------------
The patch on April 17th (NOISSURE jar mods as libraries, fix for customizing net.minecraft

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

[MultiMC-0 (DESKTOP-B7KL1NM's conflicted copy 2017-04-01).txt](https://github.com/MultiMC/MultiMC5/files/939529/MultiMC-0.DESKTOP-B7KL1NM.s.conflicted.copy.2017-04-01.txt)
![2017-04-19_21 08 55](https://cloud.githubusercontent.com/assets/19847740/25210757/070a9784-2547-11e7-88a2-ef256616170a.png)

Additional Info:
---------------------------
I believe the specific problem I had starts at line 382 of the log

**Comment by peterix** [comment]
Fixed in develop. I can load old jar mods fine now.
