### ISSUE TITLE
MultiMC Failure to Retrieve Required Libraries

### ISSUE THREAD

**Issue by idkwasgoinon** [MultiMC/MultiMC5#1861]
System Information
-----------------------------
MultiMC version: 0.5.0-945 on win32

Operating System: Windows 7

Summary of the issue or suggestion:
----------------------------------------------
I tried to launch my modded instance of 1.11.2, but MultiMC got stuck on the window that said "Getting the library files from Mojang..." After a few minutes of nothing happening, I clicked abort and I got the following message:

"Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance 1.11.2' aborted.."

What should happen:
------------------------------
I played the same instance last night and everything worked fine. It shouldn't spend more than a second retrieving libraries from mojang. I think whatever has gone wrong is probably something I've done since I am clumsy with this sort of stuff, but I don't know how to solve it. 

As far as I know, I did not do anything differently when trying to launch the game.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
MultiMC version: 0.5.0-945

Minecraft folder is:
instances/1.11.2/minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_131, using 64-bit architecture.

Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance 1.11.2' aborted..

MultiMC: Log upload triggered at: 20 Apr 2017 12:20:07 -0400

Addition Info:
--------------

I dunno if this helps but I have a few mods installed, including:
Animania
Decocraft
Harvestcraft
Xaero's minimap
Xaero's world map
Worldedit

Please let me know if I can provide any additional information!

**Comment by Armored-Dragon** [comment]
I'm having the same issue, but only with any instance that has LiteLoader installed. Forge works fine.

**Comment by peterix** [comment]
@idkwasgoinon can you upload the `MultiMC.0.log` file while it's stuck like that?
Just make sure you remove any personal info from it. It will have your MC account name/e-mail in there. Unlike the Minecraft logs, this stuff is not censored in the application log.

@Armored-Dragon what version of liteloader and Minecraft?

**Comment by fawkes-01** [comment]
I'm having the same issue. Liteloader is causing it, since a fresh 1.11.2 version runs with Forge but not Forge and Liteloader. MMC version is 0.5.0-908, running Minecraft 1.11.2. It sits for a while, but seems to progress normally after some time.

**Comment by peterix** [comment]
@Mumfrey looks like something server-side got broken,

```
18.340 D Downloading  "http://dl.liteloader.com/versions/com/mumfrey/liteloader/1.11.2-SNAPSHOT/liteloader-1.11.2-SNAPSHOT.jar"
18.517 D Following redirect to  "http://redirector.liteloader.com/snapshot/1.11.2-SNAPSHOT/jar"
18.518 D Downloading  "http://redirector.liteloader.com/snapshot/1.11.2-SNAPSHOT/jar"
18.522 D Download redirected: "http://redirector.liteloader.com/snapshot/1.11.2-SNAPSHOT/jar"
39.763 D Following redirect to  "http://repo.mumfrey.com/content/repositories/snapshots/com/mumfrey/liteloader/1.11.2-SNAPSHOT/----release.jar"
39.763 D Downloading  "http://repo.mumfrey.com/content/repositories/snapshots/com/mumfrey/liteloader/1.11.2-SNAPSHOT/----release.jar"
39.767 D Download redirected: "http://repo.mumfrey.com/content/repositories/snapshots/com/mumfrey/liteloader/1.11.2-SNAPSHOT/----release.jar"
99.882 C Failed  "http://repo.mumfrey.com/content/repositories/snapshots/com/mumfrey/liteloader/1.11.2-SNAPSHOT/----release.jar"  with reason  QNetworkReply::NetworkError(TimeoutError)
99.882 D Download failed in previous step: "http://repo.mumfrey.com/content/repositories/snapshots/com/mumfrey/liteloader/1.11.2-SNAPSHOT/----release.jar"
```

**Comment by Armored-Dragon** [comment]
Yes, it only seems to happen with Minecraft 1.11.2 + LiteLoader. I just worked around this by using Forge to load the LiteLoader jar. (extracted from installer downloaded from the CI server)

**Comment by peterix** [comment]
If you already had the liteloader snapshot, this could help:
![image](https://cloud.githubusercontent.com/assets/203326/25274888/b4b63798-2692-11e7-81e7-32659930db9c.png)

On the version page of the instance, select the liteloader version, edit, remove the highlighted line from the json, save and reload in MultiMC.

**Comment by fawkes-01** [comment]
I tried this, didn't seem to help.

**Comment by peterix** [comment]
Until this is resolved, you could add it as a forge mod (just drop the `-release` file from jenkins into the `mods` folder).
http://jenkins.liteloader.com/job/LiteLoader%201.11.2/lastSuccessfulBuild/artifact/build/libs/liteloader-1.11.2-SNAPSHOT-release.jar

Or you could put it in the json, replacing the whole section:
```
        {
            "MMC-hint": "always-stale",
            "name": "com.mumfrey:liteloader:1.11.2-SNAPSHOT",
            "MMC-absoluteUrl": "http://jenkins.liteloader.com/job/LiteLoader%201.11.2/lastSuccessfulBuild/artifact/build/libs/liteloader-1.11.2-SNAPSHOT-release.jar"
        }
```

It should grab the latest version from the jenkins without going through the broken redirects.

**Comment by Bjarno** [comment]
I also have this problem, even when using a vanilla version of both versions 1.11.2 and 1.8.9 and I get this error.

Version 0.5.0-custom (built in AUR), running Arch Linux.

**Comment by peterix** [comment]
@Bjarno cannot reproduce this with vanilla here... It's likely a separate issue.

**Comment by peterix** [comment]
And, cannot reproduce this with the current version. If I could, I would simply fix it on the metadata server :)

**Comment by jammeister1884** [comment]
im having a problem with an instance with fabric api and the replay mod on it. could somebody help as it is saying unsatisfied link error and failed to load library

**Comment by peterix** [comment]
Please don't Necro closed issues. Make a new one and attach logs there
