### ISSUE TITLE
How do i add a shortcut for a modpack on ubuntu 16.04

### ISSUE THREAD

**Issue by bartolo05** [MultiMC/MultiMC5#1862]
System Information
-----------------------------
MultiMC version:5

Operating System: ubuntu 16.04

Summary of the issue or suggestion: how to add unity shortcut for modpack

my question is simple, how do i add a shortcut for a modpack on ubuntu 16.04
also, should 
MultiMC5 -l "10.2" 
run the modpack named "10.2" from terminal? if so it doesn't for me

**Comment by peterix** [comment]
The value is an instance ID. This is basically the folder name of the instance, not its name in the UI.
For tracked FTB instances it's `FTB/$folderName`.
