### ISSUE TITLE
Imgur Upload seems to be broken.

### ISSUE THREAD

**Issue by flcmc** [MultiMC/MultiMC5#1864]
System Information
-----------------------------
MultiMC version: 0.5.0-develop-964

Operating System: Windows

Summary of the issue or suggestion: 
----------------------------------------------
Using the built in imgur upload feature doesn't work. None of the screenshots are actually uploaded and the imgur link has no screenshots.

What should happen:
------------------------------
The images should be uploaded

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Go to screenshots section on the left

2. Select a screenshot (or more).

3. Hit the upload button. 

4. Go to the link provided

5. See no pictures have been uploaded.

Suspected cause:
---------------------------
Perhaps the imgur api has changed. Not entirely sure.

Logs/Screenshots:
----------------------------
https://imgur.com/a/VnLEK

**Comment by peterix** [comment]
The tasks still seem to succeed (in the log, obviously nothing is uploaded), this will need some debugging.

**Comment by peterix** [comment]
![image](https://cloud.githubusercontent.com/assets/203326/25309217/66c88c12-27c7-11e7-8836-2f32a629e260.png)

Screenshot upload seems to work. Album creation also. The screenshots just don't seem to be attached to the album.

**Comment by peterix** [comment]
Looks like a problem on imgur side right now, I'll have to contact them if this persists.

**Comment by peterix** [comment]
Contacted imgur support.

**Comment by peterix** [comment]
It was a change on imgur side, it now requires deletehashes intead of IDs when creating albums.
