### ISSUE TITLE
Can't run the pack if I'm root user

### ISSUE THREAD

**Issue by frenchiveruti** [MultiMC/MultiMC5#1867]
Hello, is there a way to override the "only as normal user" mode of MultiMC? I'm using a Linux distribution that only works as a root user (Puppy linux) and I can't find a way to use MultiMC as a "root" instead of a "non-root" user, is there any "permission" that I can change?
Thanks

**Comment by peterix** [comment]
https://github.com/MultiMC/MultiMC5/blob/develop/application/package/linux/MultiMC#L11

This is the reason.

You should be able to just copy the script, tweak it and use it instead of the original.

**Comment by frenchiveruti** [comment]
Wow that was fast haha
Thanks, may I know the technical reason behind this behaviour?
I'll just delete the line as is but I'm curious if I should avoid doing something stupid.

**Comment by peterix** [comment]
Technical reason... not really. It's more of a people problem. There are people out there who run everything as admin/root for no good reason.

If you know how to work around a simple if statement in a script, I assume you aren't blindly running commands only because someone told you so.

You have a technical reason for running as root - the distro works that way.

**Comment by peterix** [comment]
So, yeah. I just try to steer people away from doing silly things.
That includes not running applications that don't need it as root, manually messing with Minecraft jars, putting multiple Minecraft versions in one huge messy folder, .... etc.

There's really nothing that would really prevent you from doing it if you try hard enough. I just try to make the less sane options harder so people don't do it by accident.

**Comment by frenchiveruti** [comment]
Aaah that's fine then, thanks for the hard work and I totally understand your reasoning, there's a phrase that says:
"Programming is easy, but making the program work for people who doesn't understand programming is the hard part"
I'll go to enjoy muh minecraft hehe.
