### ISSUE TITLE
crash after building a beach chair and trying to sit in it, memory leak?

### ISSUE THREAD

**Issue by SegarJJ** [MultiMC/MultiMC5#1868]
System Information
-----------------------------
MultiMC version:
0.5.0-945

Operating System:
win 10 64b, running win32 multimc

Summary of the issue or suggestion:
----------------------------------------------
seems like memory ran out, 

What should happen:
------------------------------
not crash, if possible

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. mc 1.10.2, with only decocraft 2.3.6.1_1.10.2

2. 3 minutes into a session some strange colors started to show up, and then in a short time, the crash.  I placed a beach chair and was trying to sit in it.

Suspected cause:
---------------------------
seems like memory ran out, memory leak? idk

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
https://paste.ee/p/xufa5

**Comment by Heufneutje** [comment]
The default amount of RAM (512MB min and 1GB max) is almost never enough for modded Minecraft nowadays. In the instance settings you can assign it more memory. You might also want to get the 64-bit version of Java, as you're using 32-bit Java right now and that can't use any more than 1.5 GB of RAM.

**Comment by peterix** [comment]
`strange colors started to show up`

Or overheating graphics card. Make sure you are frame limiting it to something reasonable or using vsync.

**Comment by peterix** [comment]
And yes, the crash is looking like not enough memory/graphics driver crash.

**Comment by SegarJJ** [comment]
I took both suggestions.  moved to 64-bit java and also bumped the memory up substantially.  I have yet to experience another crash recently.

**Comment by peterix** [comment]
Alright. I assume this is resolved.
