### ISSUE TITLE
MultiMC Process persists after "closing"

### ISSUE THREAD

**Issue by flcmc** [MultiMC/MultiMC5#1875]
System Information
-----------------------------
MultiMC version: 0.5.0-develop-974

Operating System: Windows

Summary of the issue or suggestion:
----------------------------------------------
After the user decides to close minecraft after running MultiMC -l [instance]. The MultiMC process is still opened in the background and can only be closed from the Task Manager or by forcibly closing it with ctrl + c in the terminal you started it in (that is if you started it from a terminal).

What should happen:
------------------------------
MultiMC process end along with along with the Minecraft instance

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
Method 1
1. Open a MultiMC instance with MultiMC -l [instance]

2. Close Minecraft either after it opens or by killing it with the kill button before it starts.

3. Find that the MultiMC process is still open in the background.

Method 2
1. Make sure you have no default Minecraft account set.

2. Open a MultiMC instance with MultiMC -l [instance]

3. When prompted to select an account, click cancel.

4. Find that the MultiMC process is still open in the background.

Suspected cause:
---------------------------
MultiMC doesn't do anything after the instance of Minecraft is closed.

**Comment by peterix** [comment]
Related to #1873

**Comment by peterix** [comment]
MultiMC will now exit after an instance is closed, as long as there are no windows left behind.
It will not create a main window, unless you actually launch it normally.
Direct launch of instance does not - by default - not create an instance window. This has to be enabled in the settings, or the instance has to crash.

I consider this a good enough solution until MultiMC can track running instances even through its own restart.

Closing {#1873, #1874, #1875}
