### ISSUE TITLE
Feature Request: Allow user to specify GB in Java settings memory allocation

### ISSUE THREAD

**Issue by calloatti** [MultiMC/MultiMC5#1877]
System Information
-----------------------------
MultiMC version: 0.5.0-develop-985

Operating System:

Windows 7

Summary of the issue or suggestion:
----------------------------------------------

In the Settings-Java-Memory-Min and Max memory allocation textboxes, allow the user to press "G" to specify GB and "M" to go back to MB

What should happen:
------------------------------

Let user specify GB by pressing "G" for example: "6G"

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
N/A

Suspected cause:
---------------------------
N/A

Logs/Screenshots:
----------------------------
N/A

Additional Info:
---------------------------
N/A

**Comment by CraftMechanics** [comment]
Java uses MB to specify memory allocation, in order to prevent confusion between Megabytes, Gigabytes, Mebibytes, and Gigibytes, the memory allocation unit should stay as it is.

**Comment by calloatti** [comment]
Sorry, but no.

>-Xmssize
Sets the initial size (in bytes) of the heap. This value must be a multiple of 1024 and greater than 1 MB. Append the letter k or K to indicate kilobytes, m or M to indicate megabytes, g or G to indicate gigabytes.

http://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html

**Comment by peterix** [comment]
I personally think it should stay as it is.

* MB is the unit used by MultiMC in config files, introducing units would complicate the code.
* KB is too fine across the whole range of values that make sense for Minecraft.
* GB is too coarse at the lower end of the sensible range.
* Introducing units beyond the current display of `MB` would also complicate the UI.
* It is not necessary for anything to actually work.
