### ISSUE TITLE
MultiMC refuses to download the Narrator DLLs in 17w18b, or load them if present

### ISSUE THREAD

**Issue by zontargs** [MultiMC/MultiMC5#1878]
System Information
-----------------------------
MultiMC version: 0.5.0-945

Operating System: Windows 8.1

Summary of the issue or suggestion: MultiMC fails to download Windows native DLLs for Narrator, and will not recognize them if manually installed
----------------------------------------------

What should happen: The Mojang launcher running the 17w18b snapshot will download \libraries\com\mojang\text2speech\1.0.10\text2speech-1.0.10-natives-windows.jar and use the SAPIWrapper_x64.dll or SAPIWrapper_x86.dll located inside to run the narrator function.

MultiMC will not download this JAR, and if it is copied over from the Mojang launcher's directory, MultiMC will not locate and use it: 

[Client thread/INFO]: [STDOUT]: ERROR : Couldn't load Narrator library : Unable to load library 'SAPIWrapper_x64': Native library (win32-x86-64/SAPIWrapper_x64.dll) not found in resource path ([file:/V:/MultiMC/jars/NewLaunch.jar, file:/V:/MultiMC/libraries/com/mojang/patchy/1.0/patchy-1.0.jar, file:/V:/MultiMC/libraries/com/github/oshi/oshi-core/3.4.2/oshi-core-3.4.2.jar, file:/V:/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar, file:/V:/MultiMC/libraries/net/java/dev/jna/jna-platform/4.4.0/jna-platform-4.4.0.jar, file:/V:/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar, file:/V:/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar, file:/V:/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar, file:/V:/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar, file:/V:/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar, file:/V:/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar, file:/V:/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar, file:/V:/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar, file:/V:/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar, file:/V:/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar, file:/V:/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar, file:/V:/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar, file:/V:/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar, file:/V:/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar, file:/V:/MultiMC/libraries/com/mojang/realms/1.10.8/realms-1.10.8.jar, file:/V:/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar, file:/V:/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar, file:/V:/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar, file:/V:/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar, file:/V:/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar, file:/V:/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar, file:/V:/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar, file:/V:/MultiMC/libraries/com/mojang/text2speech/1.0.10/text2speech-1.0.10.jar, file:/V:/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar, file:/V:/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar, file:/V:/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar, file:/V:/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar, file:/V:/MultiMC/versions/17w18b/17w18b.jar])

------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create fresh MultiMC installation

2. Create and run a 17w18b snapshot

3. Note that \libraries\com\mojang\text2speech\1.0.10\text2speech-1.0.10-natives-windows.jar does not exist, and will not be loaded even if copied over from the Mojang launcher

Suspected cause:
---------------------------

Unknown. Even if the JAR is copied over, renamed, DLLs extracted, etc. the snapshot will not load them. The Mojang launcher will load them just fine.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

**https://paste.ee/p/Q4Ghe**

Additional Info:
---------------------------

**Comment by peterix** [comment]
Already fixed in develop, see: https://github.com/MultiMC/MultiMC5/commit/8e58d61150b0bdbe9eb91065d36342f3004fe97b
