### ISSUE TITLE
MultiMC Update window does not save it's size and position.

### ISSUE THREAD

**Issue by calloatti** [MultiMC/MultiMC5#1882]
System Information
-----------------------------
MultiMC version: 0.5.0-develop-993

Operating System: Windows 7 64

Summary of the issue or suggestion:
----------------------------------------------
The MultiMC Update window that pops up when you check for new updates does not remember it's size and position.

What should happen:
------------------------------
The MultiMC Update window that pops up when you check for new updates should remember it's size and position.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open the MultiMC Update windows by clicking on the check for new updates toolbar button

![image](https://cloud.githubusercontent.com/assets/12817862/25773920/cedee086-325c-11e7-8ec2-9ef39a4291be.png)

2. Resize and reposition the window, click update now

![image](https://cloud.githubusercontent.com/assets/12817862/25773926/e7fa7cb0-325c-11e7-9f7e-70f5188237cb.png)

3. Close the window and open it again. It's size and position revert to its original state.

![image](https://cloud.githubusercontent.com/assets/12817862/25773930/fc078e46-325c-11e7-94ec-1fe3203cfcbe.png)

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
I can't save the position, it's automatically put over the top of the main window. I can save the size.

**Comment by peterix** [comment]
Should be fixed.
