### ISSUE TITLE
If discord exists on the computer, use a websocket to open invite, rather than the browser

### ISSUE THREAD

**Issue by MichaelPriebe** [MultiMC/MultiMC5#1884]
While no proof that this is possible,
https://www.reddit.com/r/discordapp/comments/5beqz4/how_does_inbrowser_discord_detect_whether_one_has/

Someone has said it might be if you change the websocket origin,
https://www.reddit.com/r/discordapp/comments/59u26x/how_can_i_open_discord_with_intent_based_uri/d9boolo/

A neat quality of life feature.

**Comment by peterix** [comment]
This is currently simply too involved and the existing solution works.

See:
https://discordapp.com/developers/docs/topics/rpc

Reverse engineering would be needed...

**Comment by peterix** [comment]
```
#!/bin/python2
from websocket import create_connection
import ssl

ws = create_connection("wss://localhost:6463/?v=1", sslopt={"check_hostname": False, "cert_reqs": ssl.CERT_NONE, "ca_certs": "cacert.pem"})
req = '{"cmd":"INVITE_BROWSER","args":{"code":"a2HG92j"},"nonce":"4d7fc561-907b-4ab5-977c-4c00a80b910f"}'
print ("Sending", req)
ws.send(req)
print "Sent"
print "Receiving..."
result =  ws.recv()
print "Received '%s'" % result
ws.close()
```

This connects, and then does nothing useful.
Some way of grabbing a valid `nonce` would be needed. Would have to look at the decrypted ssl traffic. The key must be somewhere in the desktop app.

**Comment by MichaelPriebe** [comment]
The problem is the invite you are using is expired. Of course it would not pop up on discord.

**Comment by peterix** [comment]
It does nothing anyway.

**Comment by theLMGN** [comment]
Sorry for reviving an old issue here, but this was among the first of the Google results for this, the nonce doesn't actually matter, as long as one **is** there, it will work. The only authentication done is checking if the websocket connection has a `Origin` header, and it's value is `https://discord.com`

```
const WebSocket = require('ws');

const ws = new WebSocket('ws://127.0.0.1:6463/?v=1', {
  origin: 'https://discord.com'
});
ws.on('message', function incoming(data) {
    console.log(data);
    ws.send(`{"cmd":"INVITE_BROWSER","args":{"code":"discord-testers"},"nonce":"You can put any string here. It just needs to be present"}`)
    ws.close()
});
```

**Comment by Zetabite** [comment]
Dont necro bumb, make a new issue

**Comment by theLMGN** [comment]
@Zetabite I know that bumping is bad practice, but if you had read my comment, you'd know my reason for bumping it.
`Sorry for reviving an old issue here, but this was among the first of the Google results for this,` Making a new issue would of been irrelevant.

**Comment by Zetabite** [comment]
If you agree, why do it then.

**Comment by kb-1000** [comment]
I don't see how this is relevant in any way, or why this issue even exists.
Anyways. This is a Minecraft launcher. Not a Discord library.
And it's not written in JS, it's written in C++.

**Comment by theLMGN** [comment]
![image](https://user-images.githubusercontent.com/12257112/102701132-b618ef80-424b-11eb-82bf-5f2b0ef76af5.png)
I thought that if anyone was trying to solve the same problem as me, and had found this (singular!) issue relating to the subject, I'd add it here, causing at worst, an email or a notification that will go away when clicked on.

I mentioned the JavaScript code because that was what I was working in. peterix wrote his example in Python. If I had followed @Zetabite's advice and created another issue, that would create a irrelevent, spam issue. 

I knew this wouldn't of been any help to the MultiMC issue, but if anyone was researching how to solve this issue, and found this as the only search result on Google, I'd leave my findings here just to help them.

**Comment by Zetabite** [comment]
still overly random. If you made a post somewhere else of that kind, google would probably show it, since there doesnt seem to be much of it. Here is not the right place. But i respect your effort

**Comment by kb-1000** [comment]
I'm pretty sure Discord doesn't like people randomly connecting to that websocket and sending events.
That's the reason why it's _undocumented_.
