### ISSUE TITLE
Proxy page enhancment

### ISSUE THREAD

**Issue by Zekken01** [MultiMC/MultiMC5#1886]
We should have a thing saying that this is only for the launcher and not Minecraft

![6pvcdha](https://cloud.githubusercontent.com/assets/19770864/25825329/a925860a-3410-11e7-9cd6-8ac6f7a93a64.png)

**Comment by peterix** [comment]
On workflowy: https://workflowy.com/s/2EyDMcp7CU#/ddf86ccc7207

**Comment by peterix** [comment]
![image](https://cloud.githubusercontent.com/assets/203326/25887705/704cbd40-3563-11e7-92a5-ab561329df9b.png)
