### ISSUE TITLE
Check if files are present when launching in offline mode

### ISSUE THREAD

**Issue by AffeAli** [MultiMC/MultiMC5#1887]
System Information
-----------------------------
MultiMC version: custom build from 8a526fab0e0d8c7baec0abc022ef62fb72a262ae (May 9)

Operating System: Arch Linux

Summary of the issue or suggestion:
----------------------------------------------
Minecraft launch failes when the first launch is in offline mode and the minecraft version wasn't downloaded previosly.

What should happen:
------------------------------
MultiMC downloads the needed files or display a message that the first start needs to be online.

Steps to reproduce the issue:
-------------------------------------------------------------
1. Create a new instance with a minecraft version never used in this MultiMC install (like an old snapshot).

2. Launch it in offline mode

Suspected cause:
---------------------------
MultiMC is not downloading the needed minecraft version when in offline mode.

Logs/Screenshots:
----------------------------
https://paste.ee/p/Q2lIE

**Comment by peterix** [comment]
Well, it's offline mode. It's not meant to download anything, because it assumes you are actually offline and doesn't make you wait through all the network timeouts.

**Comment by peterix** [comment]
Maybe it could check if anything is missing (and plenty of things are missing there).

**Comment by VADemon** [comment]
Bump, I just bumped into that issue. It's very weird to get onesixlauncher stacktraces from launching because you assume if starts launching, it must've already taken care of verifying/downloading files.
