### ISSUE TITLE
libwep error

### ISSUE THREAD

**Issue by Champerson** [MultiMC/MultiMC5#1888]
The libwebp has updated and now it can be found in **/usr/lib/libwebp.so.7** this is causing the following error: 
![]( http://i.imgur.com/hjk9pom.png "") 
*~~sorry for my english~~*
**NOTE:** i'm is using Arch Linux

**Comment by Champerson** [comment]
i have solved with: `sudo ln /usr/lib/libwebp.so.7 /usr/lib/libwebp.so.6`

**Comment by peterix** [comment]
Rebuild the package?
