### ISSUE TITLE
Help me error 1

### ISSUE THREAD

**Issue by AfinnityRekt** [MultiMC/MultiMC5#1891]
System Information
-----------------------------
MultiMC version:

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Doesnt Start

What should happen:
------------------------------
Start the fudging game

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------

Suspected cause:
---------------------------
missing files?

Logs/Screenshots:
----------------------------

[New Paste.txt](https://github.com/MultiMC/MultiMC5/files/998940/New.Paste.txt)

Additional Info:
---------------------------
Just added a mod

**Comment by flcmc** [comment]
Would be helpful to debug if you included the entire log. You triggered a log upload while Minecraft was still being started up.

**Comment by peterix** [comment]
Incomplete, closing.
