### ISSUE TITLE
Fork naming

### ISSUE THREAD

**Issue by Oleg-Arkhipov** [MultiMC/MultiMC5#1893]
README states:

> ...we don't want people using the "MultiMC" name when redistributing the project. This means people must take the time to go through the source code and remove all references to "MultiMC", including but not limited to the project icon and the title of windows, (no MultiMC-fork in the title).

Could you clarify, please? Is removing MultiMC from windows titles and all other texts **which user can possibly see in running program** (except "About" as stated specifically in README) enough? Or I have to replace even all occurrences in the source code itself, like namespace/class/variable names?

**Comment by peterix** [comment]
Only the obvious things are necessary. The main reason is to not confuse the users.
