### ISSUE TITLE
Default to Mojang LWJGL 2.9.4 for Minecraft <= 1.12 (older are buggy)

### ISSUE THREAD

**Issue by kargaroc** [MultiMC/MultiMC5#1894]
System Information
-----------------------------
MultiMC version:
    0.5.0-887-lin64

Operating System:
    OS: Arch Linux 
    Kernel: x86_64 Linux 4.10.13-1-ARCH
    Resolution on monitor 1: 1920x1080 144hz
    Resolution on monitor 2: 1920x1080  60hz
    DE: XFCE4
    WM: Xfwm4
    CPU: Intel Core i5-2500 @ 4x 3.7GHz
    GPU: GeForce GTX 660
    RAM: 16384 MiB

Summary of the issue or suggestion:
----------------------------------------------
Minecraft starts without issues, but when I close Minecraft, the monitor resets to 60hz

What should happen:
------------------------------
Minecraft should not reset the refresh rate upon exit

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.
    Have a Linux-based OS
    Have a monitor that is not 60hz, and have it set to anything greater than 60hz

2.
    Launch Minecraft on the >60hz monitor

3.
    Close Minecraft, and the screen should reset to 60hz.

Suspected cause:
---------------------------
This is a known-and-fixed LWJGL issue.  However, MultiMC uses old versions that have the bug by default.  You can work around this by setting the version manually, but you need to do it per-instance, and for old legacy instances it's not an option at all.  This makes it much more tedious to use with 144hz monitors, and cripples old modpacks that rely on the legacy file structure.

Logs/Screenshots:
----------------------------
none

Additional Info:
---------------------------
If the latest LWJGL could be forced on all instances, than that would fix the issue.

**Comment by peterix** [comment]
Interesting.

If you switch over to the develop version and use the newer LWJGL versions, does it work right?

**Comment by peterix** [comment]
See:
https://aur.archlinux.org/packages/multimc-git

**Comment by kargaroc** [comment]
After building the latest git version and trying it, I noticed that I can indeed choose the LWJGL version easily, which allows me to pick the latest version, but I still have to do it per-instance, which means all the time on 144hz.

**Comment by peterix** [comment]
So, defaulting to latest 2.* LWJGL is one thing.
Crashing legacy instances is a second thing.

**Comment by peterix** [comment]
Can you open a separate issue for the broken legacy packs and describe your setup there a bit more?
* are you actually using the new AUR package?
* Where and how are the instances / data stored
* Maybe a backtrace from gdb (although  should be able to reproduce the problem based on the previous).

**Comment by peterix** [comment]
This should really be part of a more general solution based on defaulting to recommended dependencies and `Minecraft < 1.13` depending on `LWJGL < 3`.

I will not hardcode this.

**Comment by peterix** [comment]
We now have the necessary logic for this, the metadata just has to be changed to set the suggested LWJGL version to 2.9.4.

**Comment by peterix** [comment]
Done.
