### ISSUE TITLE
Launching legacy instances crashes MultiMC

### ISSUE THREAD

**Issue by kargaroc** [MultiMC/MultiMC5#1895]
System Information
-----------------------------
MultiMC version:
commit d70c783de8ae842ea175ee92902c31c088c2ddda (latest as of right now)
built manually, not from the AUR

Operating System:
OS: Arch Linux 
Kernel: x86_64 Linux 4.10.13-1-ARCH
Resolution on monitor 1: 1920x1080 144hz
Resolution on monitor 2: 1920x1080  60hz
DE: XFCE4
WM: Xfwm4
CPU: Intel Core i5-2500 @ 4x 3.7GHz
GPU: GeForce GTX 660
RAM: 16384MiB

Summary of the issue or suggestion:
----------------------------------------------
When launching a Legacy instance, MultiMC crashes with a segmentation fault.

What should happen:
------------------------------
The legacy instance should launch as expected

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.
Build the commit mentioned above from source

2.
Import a legacy instance from somewhere

3.
Launch the instance from the interface

Suspected cause:
---------------------------
    Thread 1 "MultiMC" received signal SIGSEGV, Segmentation fault.
    0x00007ffff6bb540f in LegacyUpdate::lwjglStart() ()
        from /home/225gb/install/bin/libMultiMC_logic.so
I don't know other than this.

Logs/Screenshots:
----------------------------
https://pastebin.com/raw/bGKfV2hn

Additional Info:
---------------------------
1.6 instances work just fine
Building with GCC instead of Clang does not fix the bug
Swapping the lwjgl files in the instance bin/ directory for known working ones does not fix the bug

**Comment by peterix** [comment]
Should be fixed now.
