### ISSUE TITLE
Code -1

### ISSUE THREAD

**Issue by SPACEFACE2394** [MultiMC/MultiMC5#1896]
https://paste.ee/p/w0DmU
it just randomly stopped

**Comment by Heufneutje** [comment]
```
[18:04:27] [Client thread/ERROR] [FML]: Caught exception from harrypottermod
java.lang.IllegalArgumentException: ID is already registered: Basilisk
```

You have multiple mods trying to register the same entity ID. Remove this mod or the mod that it's conflicting with.

**Comment by SPACEFACE2394** [comment]
is it possible to change the id?

**Comment by Heufneutje** [comment]
I'm not sure as I am not familiar with the mod itself. If it's possible it would be in the mod's config file. Alternatively you could report it to the mod author.

**Comment by SPACEFACE2394** [comment]
K I try that Thanks!

using namespace std;

int main()
{
	cout <<"From Master Coder Ryan\n";
	return 0;
}

**Comment by peterix** [comment]
You are missing `#include <iostream>`, also `using namespace std;` is kinda overkill.

jk
