### ISSUE TITLE
Latest Version not shown

### ISSUE THREAD

**Issue by ubguc** [MultiMC/MultiMC5#1897]
System Information
-----------------------------
MultiMC version:0.6.0-develop-946

Operating System:Kubuntu

Summary of the issue or suggestion:
----------------------------------------------
The newest version of Minecraft is not available through MultiMC. 
It is not shown in the list of versions, I did click "refresh" and also shut down MultiMC and tried again. 
I then waited several hours and re attempted it, but there is no change.
Pre-release 3 (1.12-pre3) was out on the 17th but it cannot be downloaded, the last version showing in the versions list is Pre Release 2 (1.12-pre2)
There is no issue with internet, MultiMC is accessing the web and is able to show and download other versions ok.
What should happen:
------------------------------
I should see the latest version, 1.12-pre3 when I am making a new instance or updating an old one, in the list of available versions.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Open MultiMC

2.Attempt to create a new instance (or update an existing instances version)

3.The latest version - 1.13-pre3 does not show up :(

Suspected cause:
---------------------------
I don't know??

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
I don't think this makes a log..........

Additional Info:
---------------------------

**Comment by peterix** [comment]
Looks like the machine that syncs versions is not running. I haven't fully set up the redundant automation for that yet - I've been running the sync scripts on my own home machine. It needs a reboot. Or it was shut down by someone because there was a storm.

I'm on a business trip to Israel and will return tomorrow.

**Comment by peterix** [comment]
Should be there now.
