### ISSUE TITLE
Make MultiMC run other Clients

### ISSUE THREAD

**Issue by loper12** [MultiMC/MultiMC5#1898]
# Summary of the suggestion:
----------------------------------------------
I wan't to be able to make MultiMC able to use other clients.

# What should happen:
------------------------------
You should be able to run other clients.

**Comment by peterix** [comment]
What do you even mean by that?

**Comment by loper12** [comment]
Like if I wanted a custom client to, make it run faster, and it's not a jar file, unlike [optifine](http://optifine.net/downloads).

**Comment by loper12** [comment]
And it's not accessible via the minecraft lib customization.

**Comment by loper12** [comment]
This is what happens when you try the minecraft lib customization:
MultiMC version: 0.6.0-develop-1034


Minecraft folder is:
instances/Wurst 1.11/minecraft


Java path is:
C:/Program Files/Java/jre1.8.0_121/bin/javaw.exe


Java is version 1.8.0_121, using 64-bit architecture.


Instance update failed because: Failed to download the assets index:
Job 'Asset index for Wurst 1.11' failed to process:
c:UsersDtheEAppDataRoaming.minecraftversionsyourjarhereversionyourjarhereversion.json.

**Comment by peterix** [comment]
So. I'm pretty sure wurst works as a jar mod.
The version you are running also supports replacing the main jar, although it's not exposed in the UI yet.

However, I'd like to know what you tried already - and how that json you used looks like.

**Comment by peterix** [comment]
Basically, tell me what you're actually trying to add and what you did up to this point.

**Comment by peterix** [comment]
MultiMC now supports replacing the main jar.
