### ISSUE TITLE
Graphic not drawn properly when start

### ISSUE THREAD

**Issue by Usernm0** [MultiMC/MultiMC5#1899]
Sometimes multimc not load graphic properly and window after start looks like this:
http://i.imgur.com/3m1C7k5.png or 
http://i.imgur.com/94qcGpe.png

Everything become ok, if i minimize window and open it back.

I use two monitor configuration, maybe it matters.

**Comment by peterix** [comment]
Interesting. I've never seen it do that before.

Does the develop version do it too?

Try it:
https://files.multimc.org/downloads/mmc-develop-win32.zip

**Comment by Usernm0** [comment]
Everything works well on develop version, on old version works too. 

I test start few time before post issue here and it's reproduce all time. I think something wrong with my system not related to multimc, but it's strange why only multimc stop drawing interface on some stage when loading.

**Comment by peterix** [comment]
Well, we never found out. And 0.6.0 is released, and supposedly has fixed this issue.
