### ISSUE TITLE
cannot press buttons after resizing screen

### ISSUE THREAD

**Issue by loper12** [MultiMC/MultiMC5#1901]
System Information
-----------------------------
MultiMC version: Latest Dev, and MultiMC 0.5.0-945

Operating System: Windows 10 Home

Summary of the issue or suggestion:
----------------------------------------------
You cannot use minecraft after you resize.

What should happen:
------------------------------
You should be able to press buttons

Most likely reason of crashing:
-------------------------------------
Enum GL ERROR

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Update to the latest dev in 0.6.0(or stay at MultiMC 0.5.0-945)

2. Open minecraft

3. Resize your window

4. Get mad and kill the process when it stops working.

Log:
-----------------------------
https://paste.ee/p/NaHe4

Additional Info:
---------------------------
HELP PLZ!!

**Comment by loper12** [comment]
IT DOESN'T EVEN WORK IN THE OLDER VERSION!!

**Comment by peterix** [comment]
You could try a newer version of LWJGL (changing that is easy in dev).

**Comment by peterix** [comment]
Anyway, that honestly sounds like a problem with tthe game, not the launcher. Closing.
