### ISSUE TITLE
I DONT CHANGE MY MODPACK LOGO !

### ISSUE THREAD

**Issue by MProXD** [MultiMC/MultiMC5#1903]
System Information Core i5, 8GB ram , Laptop
-----------------------------
MultiMC version:5

Operating System: Windows 10

Summary of the issue or suggestion: I don't change my modpack icon.
----------------------------------------------

What should happen: I don't now
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. I create a new modpack. 

2.I want more beautiful logo

3.I create a new logo

4. I'm right clicked my modpac and open the logo select GUI. I'm click the add new ıcon and select my new ıcon.

Suspected cause: I dont now
---------------------------

Logs/Screenshots: 
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info: PLEASE SLOVE MY PROBLEM. AND I'M TURKISH. I DONT KNOW ENGLİSH VERY GOOD. IF I'M DO ERROR I'M VERY SAD :D
---------------------------

**Comment by QuImUfu** [comment]
Could you upload the logo you try to use?
And explain what is not working when you add it?
The only problem with instance icons i know about is #1663 
If this is a different problem we need additional information and the multimc log.

**Comment by peterix** [comment]
Sorry, but I don't know what to do about this... Closing.
