### ISSUE TITLE
Is it possible to add a checker for the server?

### ISSUE THREAD

**Issue by aescraftbr** [MultiMC/MultiMC5#1904]
I want to make a client for my server, that everyone needs it to access the server. This could be bypassed, but the server is really small and I don't think the players would try to bypass this.

The idea is to force everyone to use the same launcher and restrict the acess to custom hacked clients.
Thanks!

**Comment by peterix** [comment]
I'm not sure if I want to do anything like that. If you need help with development or building MultiMC, or reusing parts of it, stop by on Discord...
