### ISSUE TITLE
Skin is missing after teleporting across dimensions

### ISSUE THREAD

**Issue by HetNeSS** [MultiMC/MultiMC5#1905]
System Information
-----------------------------
MultiMC version: 0.5.0-945

Operating System: Win 7 x64

Summary of the issue or suggestion: Skin is missing after the teleporting
----------------------------------------------

What should happen: Skin should stay along the whole playthrough
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Enter a mp server mc.olcraft.ru

2. Set your home by using the "/set home" command. Teleport to /spawn, then back to /home and back to /spawn. Spent some time on a local mob arena (one of the local big gates "minigames" across the spawn), and after the round ends, /ma leave and try to go /spawn, from the lobby, And finally, use /home

3. Profit!

Suspected cause: Probably, something about new minecraft version (1.11.2). Or some problems with launcher. Licensed account, not pirate version
---------------------------

Logs/Screenshots:
----------------------------
Chat - https://paste.ee/p/FAxkD
Forge mod loader - https://paste.ee/p/2KVIn
Vid - https://youtu.be/rMlShMraKg0
Additional Info:
---------------------------

**Comment by peterix** [comment]
Definitely not a MultiMC problem. It does nothing with skins and does not interfere with the game after launching it.
