### ISSUE TITLE
1.12 support

### ISSUE THREAD

**Issue by chicken3600** [MultiMC/MultiMC5#1906]
As I am writing this, Minecraft 1.12 came out yesterday. So I thought I would load it up and try playing it.
I went into the New Instance screen and then went into Select Version. 1.12 was not there. A bunch of snapshots were there, but 1.12 was not. Please fix this because I cannot play 1.12 because of this.

**Comment by Chewsterchew** [comment]
You can press "Refresh" to show the latest versions. It appeared there when I clicked it, let me know if this works.

**Comment by peterix** [comment]
If you are running the develop version, the automation that synchronizes the version files between Mojang and the MultiMC repositories only runs when my home machine is online.
I'm going to fix that before the stable release, but right now, it's just turned off when I'm at work.

**Comment by peterix** [comment]
Yep. It now runs every hour on a dedicated server.
