### ISSUE TITLE
MultiMC version:0.5.0-945  Operating System:windows10  

### ISSUE THREAD

**Issue by Aknightofvoid** [MultiMC/MultiMC5#1907]
System Information
-----------------------------
MultiMC version:0.5.0-945

Operating System:windows 10

Summary of the issue or suggestion:How to delete groups truly？i only delete the superficial group‘s name，but if i want to create a group， the group's name still in the options of display。
----------------------------------------------

What should happen:Can you teach me or add a delete group function？
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Click on the right of the 'more group‘’, the main interface before deleting the group will still appear in the option

2
3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:.i dont know how to delete the excess group ， or you didn't make this feature

---------------------------

**Comment by Loetkolben** [comment]
I assume you want to delete the group name from the dropdown menu when chaning the group of an instance?
In this case, just make sure no instance is part of the group to delete and than restart MultiMC. The group should have disappeared. (At least this does work for me: v0.6.0-develop-1036)

**Comment by peterix** [comment]
Yes. Groups stay around until you actually start MultiMc without a single instance that uses them. MultiMC also remembers the last used group name, and should offer it by default.
This is done intentionally to make it not forget the groups while you're working with them. Think about the case of removing the last instance from a group and then wanting to add other instances to it.

**Comment by Aknightofvoid** [comment]
@Loetkolben thank you very much！！

**Comment by Aknightofvoid** [comment]
@peterix yes， but can you add the function of a mobile group? I want to sort。

**Comment by peterix** [comment]
mobile group? I'll have to think about that.
