### ISSUE TITLE
Forge -universal jar is not being downloaded, instance cannot run

### ISSUE THREAD

**Issue by Squaredude** [MultiMC/MultiMC5#1908]
System Information
-----------------------------
MultiMC version: 0.5.0-945 on win32

Operating System: Windows 7 64bit

Summary of the issue or suggestion: Forge libraries not downloaded properly, lacking the -universal package. I propose that MultiMC either downloads the -universal package or shows an error stating it can't be downloaded.
----------------------------------------------

What should happen:
------------------------------
Installing Forge on an instance should download all the required Forge jars to work as soon as you hit "Launch".

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create instance with any version that supports Forge

2. Install Forge through MultiMC

3. Attempt to launch the instance

Suspected cause: MultiMC is not downloading a required library which seems to be the -universal package. When I manually download this package and put it in the appropriate folder ( \MultiMC\libraries\net\minecraftforge\forge\ [version] ),  then launch the instance, the issue is resolved.
---------------------------

**Comment by peterix** [comment]
I don't see this. Which Forge version are you talking about?

**Comment by calloatti** [comment]
https://www.reddit.com/r/feedthebeast/comments/6gk7gr/forge_112_doesnt_download_libraries/

**Comment by peterix** [comment]
If this is the case, this is not interesting. Stop installing barely working prereleases of Forge.

**Comment by calloatti** [comment]
I am just guessing that is the problem OP has.

**Comment by Squaredude** [comment]
>If this is the case, this is not interesting. Stop installing barely working prereleases of Forge.

That has nothing to do with me, please read the usernames of the people you're replying to.

I've been having this issue consistently for versions 1.10 and 1.11.

**Comment by peterix** [comment]
MultiMC writes a log file - current log is MultiMC.0.log, increasing numbers mean older logs.
So, open up MultiMC, try to start an instance with Forge and once it fails, look at the log file and post the part where it tries to download the files.

**Comment by peterix** [comment]
I still don't understand what's going on here, or if there even is a problem. Without logs, or any information about which version you are even trying to use, there's not much I can do with this.
