### ISSUE TITLE
Translation issue (french)

### ISSUE THREAD

**Issue by flapili** [MultiMC/MultiMC5#1910]
Hi, sorry i'm not English but i'll try to write correclty :)

the Translation in french of button  for  open reddit is false ("Ouvrez la page MultiMC sur Patreon" in place of "Ouvrez la page MultiMC sur Reddit" ).
is really really minor bug or Errol of translation but a minor problem remains a problem :)

I use MultiMc 5 build 1036.

**Comment by peterix** [comment]
Should be fixed as soon as the translation builds finish.
