### ISSUE TITLE
Crash of minecraft error 1 

### ISSUE THREAD

**Issue by Buliamoisava** [MultiMC/MultiMC5#1912]
MultiMC version: 0.5.0-945
------------------------------
When i'am playing with any mods, on a solo map or on a server
after some time  minecraft crash.
I updated my drivers
Uninstall and install Java 
And i didn't find solution 

Logs/Screenshots:
----------------------------
https://paste.ee/p/Bjb9Y

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz

**Comment by peterix** [comment]
Start with actually uploading the full log. Vanilla crash logs do not provide enough context to even begin understanding what went wrong.
