### ISSUE TITLE
Impossible to get Java

### ISSUE THREAD

**Issue by isipare** [MultiMC/MultiMC5#1915]
System Information
-----------------------------
MultiMC version: 0.5.0-945 on win32

Operating System: Windows 10 Home

Summary of the issue or suggestion: 
----------------------------------------------
MultiMC detect Java but then error "The specified java binary didn't work with the arguments you provided:"

This a new computer; so first time setting up MultiMC on this.

What should happen:
------------------------------
It should work.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
Sorry I have no idea how to reproduce it. It just happens all the time for me. I can't get java on MultiMC.

Suspected cause:
---------------------------
No idea. I do have the jars folder in MultiMC's folder.

Logs/Screenshots:
----------------------------
there is no log.

Additional Info:
---------------------------
![image](https://user-images.githubusercontent.com/29578856/27344562-014c3e4e-55e7-11e7-994e-1917b37e957d.png)
![image](https://user-images.githubusercontent.com/29578856/27344570-0aabf6e6-55e7-11e7-9b8a-2e67112c6e18.png)

**Comment by peterix** [comment]
You cannot run 32bit java with that much memory. Remove it and install 64bit java if you want to use more than 1500 MB

**Comment by isipare** [comment]
OMG thank you so much. Since my version of Windows is 64 bit I did not even think I could download anything else than 64 bit apps ...

**Comment by peterix** [comment]
Hm. maybe it could detect that specific case and show a sensible error message instead of this.

**Comment by Heufneutje** [comment]
Maybe we could also give the user a warning when their default Java on a 64-bit OS is 32-bit? These kinds of issues show up on a fairly regular basis and people are often confused about it.

**Comment by peterix** [comment]
It says so in the game log - but with the default of not showing the log, people often don't see it. And even when they do, they often seem to not read it.

It would have to be obnoxious and annoying.

Honestly, maybe it would just be better to bundle Java on Windows, where people have all these issues.

**Comment by Heufneutje** [comment]
That would probably also do the trick. The vanilla launcher already does this as well since starting with 1.12 only Java 8 is supported.

**Comment by peterix** [comment]
Yeah. Except the Java it installs is outdated... It is outdated because Intel sucks at maintaining drivers for their integrated GPUs, but still outdated. I've seen it cause issues already, where the user had to use updated Java, because the one bundled with the Mojang launcher simply didn't work.

A solution is needed...
