### ISSUE TITLE
[Minor Bug?] "Kill Minecraft?" Dialog box still visible

### ISSUE THREAD

**Issue by Nykorin** [MultiMC/MultiMC5#1917]
System Information
-----------------------------
MultiMC version: Latest Dev Build (Version 0.6.0-develop-1036)

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Dialog box of "Kill Minecraft?" still visible in preview window from taskbar

What should happen:
------------------------------
It should not appear

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Kill Minecraft.

2. Relaunch Minecraft.

3. Preview MultiMC Console from task bar.

Suspected cause:
---------------------------
Unsure

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![Image](https://i.imgur.com/CHcOzPd.png)

Additional Info:
---------------------------
I am currently using a start menu replacer called Start10 from Stardock

**Comment by peterix** [comment]
That is most likely a bug in other software... and I see no way to fix it in MultiMC, because it has no concept of anything like a taskbar.
