### ISSUE TITLE
"View Folder" buttons doesn't work on Debian

### ISSUE THREAD

**Issue by ghost** [MultiMC/MultiMC5#1918]
System Information
-----------------------------
MultiMC version: 0.5.1-887 lin64

Operating System: Debian GNU/Linux 8 (jessie) 64-bit
Desktop Environment: Gnome 3.14.1

Summary of the issue or suggestion:
----------------------------------------------
Every single "View Folder" button does not work. It simply does nothing. I've tested every button I've found.

What should happen:
------------------------------
After pressing button appropriate folder should be opened in "Files".

Additional Info:
---------------------------
_Not tested on another machines with Linux/Debian/Debian-derived OS._

**Comment by peterix** [comment]
I suspect this is broken configuration of whatever desktop environment you are using - or it's missing entirely.
MultiMC should never know what "Files" is. It just asks the equivalent of `xdg-open` to open the folder.

**Comment by Sfaxx** [comment]
My desktop environment is Gnome. I've added details to system info.
I've checked `xdg-open` in terminal and it works like a charm. It also cannot be permission problem because it worked in terminal without super user or root permissions (just as regular user).
