### ISSUE TITLE
Error code 255 with only optifine and forge

### ISSUE THREAD

**Issue by kronokiller** [MultiMC/MultiMC5#1919]
System Information
-----------------------------
MultiMC version: MultiMC 5 0.5.0-887 on lin64

Operating System: Ubuntu 17.04

Summary of the issue or suggestion:
----------------------------------------------
I just downloaded MultiMC5 and so far I have linked my account, downloaded both of the 1.12 versions of optifine (OptiFine_1.12_HD_U_C2.jar and OptiFine_1.12_HD_U_C3.jar) and tried two different versions of forge (one had a bug next to it so I moved down a version) The forge versions were 14.21.0.2373 and 14.21.0.2372 I am not sure if this is a problem with MultiMC, Forge, Java, Optifine, or something else but I would appreciate some help.

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------
I am not sure if this is a problem with MultiMC, Forge, Java, Optifine, or something else.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

https://paste.ee/p/5CuY3

Additional Info:
---------------------------
I get error code 0 with the newest forge loader
 It ran fine when I ran it without Optifine.
Also doesn't work when I use Iron Chests mod instead of Optifine

If someone suggests a couple things they know work so I can check that it isn't the mod or forge, that would be great

I hear that I should be using Java 7. If so, Oracle doesn't allow everyone to have Java 7 for free anymore. (that was from an old post)

**Comment by QuImUfu** [comment]
It seems that in 1.12 Optifine and the newer versions of forge do not work together. OptiFine alone and Forge alone do work :) 
It does also work if you downgrade to forge version 14.21.0.2368 or lower.

**Comment by kronokiller** [comment]
i also had problems with forge and iron chests (i figured that was a fairly standard mod to try)

**Comment by Heufneutje** [comment]
> I hear that I should be using Java 7. If so, Oracle doesn't allow everyone to have Java 7 for free anymore.

Whoever told you that is wrong. Java 7 is not even supported anymore and both Minecraft and Forge are now built against Java 8 in 1.12 meaning that any older version of Java wouldn't even be able to run Minecraft (properly) anymore.

**Comment by kronokiller** [comment]
I went down to 2368 and that didn't work either

**Comment by QuImUfu** [comment]
sorry, i meant 14.21.0.2362

**Comment by kronokiller** [comment]
do you think that will work with 1.12? from the looks of it, because of the new crafting recipe thing, forge is going to have to have a bit of work before  a recommended stable release

**Comment by kronokiller** [comment]
That one worked, Thanks. I'll close this in a couple minutes. (in case you want to add something in case someone looks later)

**Comment by QuImUfu** [comment]
it works on my PC. But yes forge and all other 1.12 ports seem very much alpha. Iron Chests and OptiFine do not work together in the moment (in my tests). I would wait a bit before making a 1.12 modpack :D
