### ISSUE TITLE
Crashing issue with Forge and mods

### ISSUE THREAD

**Issue by julioplayz** [MultiMC/MultiMC5#1922]
System Information
-----------------------------
MultiMC version:0.5.0-908

Operating System: Mac

Summary of the issue or suggestion: Crashing upon loading mc
----------------------------------------------
Crashing upon loading mc

What should happen:
------------------------------
It should load Minecraft 1.9.4 forge with the mods Crayfish, More player models, Decocraft, Flat colored, Chisels&Bits, CustomNpcs

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Load Minecraft with 1.9.4 with all the mods listed above

2.

3.

Suspected cause:
---------------------------
Problem with mods

Logs/Screenshots:
----------------------------
[//]: # 
https://paste.ee/p/13XYr

Additional Info:
---------------------------

**Comment by peterix** [comment]
Increase the java memory settings. The default (512 - 1024 MB) is not enough for mods.

**Comment by brodycas3** [comment]
You mean for *most mods.
