### ISSUE TITLE
Crash with Optifine and Forge in Minecraft 1.12

### ISSUE THREAD

**Issue by Greency99** [MultiMC/MultiMC5#1924]
System Information
-----------------------------
MultiMC version: 0.5.0-945

Operating System: Windows 10 Home 64 bits

Summary of the issue or suggestion:
----------------------------------------------
Minecraft crashes if I add optifine with Forge in Minecraft 1.12

What should happen:
------------------------------
The game should load correctly

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install Optifine

2.

3.

Suspected cause:
---------------------------
A bug with Optifine or with MultiMC

Logs/Screenshots:
----------------------------
https://paste.ee/p/X94HE

**Comment by peterix** [comment]
Update optifine or downgrade to older forge.

**Comment by Greency99** [comment]
Optifine updated to version C4. Works now.
