### ISSUE TITLE
Can't reserve enough space, even after max memory adjustment.

### ISSUE THREAD

**Issue by Strmbrkr** [MultiMC/MultiMC5#1925]
System Information
-----------------------------
MultiMC version:
0.5.0-945 on win32

Operating System:
Windows 64 bit

Summary of the issue or suggestion:
----------------------------------------------
When trying to run MC 1.7.10, receive crash report about being unable to reserve space.

What should happen:
------------------------------
Minecraft runs, hopefully without everything becoming invisible due to memory limitations.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC

2. Run instance with 1024 MB min and 2048 MB max memory allocation

3. Receive crash report

Suspected cause:
---------------------------
Computer may have trouble dealing with the 20 or so mods in one instance. If not, no idea.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

https://paste.ee/p/dkpKM
(I don't know if this is the appropriate way to upload the log, sorry.)

Additional Info:
---------------------------
After much research, I have made sure I am running Windows 64 bit, have the latest Java installed, and messed around with the max and min memory allocation settings. It used to work for 128 min and 1024 max, but now gives same error log as larger settings.

**Comment by peterix** [comment]
```
Java is version 1.8.0_131, using 32-bit architecture.
```

Get 64-bit java.

**Comment by Strmbrkr** [comment]
Oof. Embarrassing how simple that solution was. Thought for sure I had 64, but maybe I should've looked closer. Thank you for your help!
