### ISSUE TITLE
Suggestion: Add a shader packs tab to instance, if optifine is installed

### ISSUE THREAD

**Issue by bogger33** [MultiMC/MultiMC5#1926]
Optifine adds a shaderpacks folder to minecraft for storing your shaders. It'd be cool if i could manage my shaders straight from multimc, just like I can with my resource packs.

**Comment by Heufneutje** [comment]
Just optifine? I thought the shaders mod could run without optifine nowadays. Could just enable it all the time.

**Comment by bogger33** [comment]
the shaders mod does run without optifine but is forge incompatible.

**Comment by peterix** [comment]
Yep, this is a good idea. Once we have a way to add optifine. Or detect it.

**Comment by bogger33** [comment]
well you can just add optifine like you can add any other mod. You could detect it by mod ID string

**Comment by peterix** [comment]
I do not want to do things this way, special casing things like that would reduce code quality over time...

Here's what I want it to do:
1. it computes a hash of the mod file
2. it looks this up in a database of known files and maps it to a name and version
3. this is used to grab the metadata file for that name and version
4. the metadata file says that this version of this mod has shader packs in a specific folder inside the instance (or some other arbitrary resource).

**Comment by bogger33** [comment]
why do you think it reduces code quality? With all due respect, using the mod ID string, something that's meant to be an identifier, used in mod code all over the place to check if other mods are loaded for compatibility/addon purposes seems like a better and more future-proof solution than hashing mod files, which will break with every update, or custom compiled version (which is less of a problem in this case because optifine is not open source)

**Comment by peterix** [comment]
There is no such thing as a mod ID.
