### ISSUE TITLE
Suggestion: Support for Technic and/or Curse/Twitch launchers

### ISSUE THREAD

**Issue by BoxOfFlex** [MultiMC/MultiMC5#1928]
Would be nice to have support for other launchers than FTB, mainly cause FTB is now integrated into Curse/Twitch client now. Only thing is the file structure is changed from FTB where its just the files in one folder without an instance.json or anything and no icons are downloaded on either. It would still be nice to have everything concentrated into one launcher though.

(sorry if its a duplicate suggestion)

**Comment by tehbasshunter** [comment]
Technic is being considered right now but not in the near future.  
  
Curse packs are possible with the dev branch of the launcher.

**Comment by peterix** [comment]
Pretty much, that.

To clarify what the future plans are...
I really don't want to add the sort of integration with launchers (other software running on the same machine).
If anything, I would like to remove it in favor of direct integration with the platforms they connect to. So, you can expect full integration of Technic at some point (it's work in progress) and import of curse packs (similarly to how import of exported MultiMC instances works).
