### ISSUE TITLE
Idea: Add autodownload for curseforge

### ISSUE THREAD

**Issue by strifel** [MultiMC/MultiMC5#1933]
**# This is just an idea not an issue.**
Add a download button for curse so you just put in a curse link and autodownload the mod, in the right mc version. 

This would be a very cool and useful tool for modpack creaters

**Comment by CNife** [comment]
I love this feature too, but I don't think it could be implemented easily.

**Comment by peterix** [comment]
It ... could be implemented fairly easily now. But I do not know if it should be.

**Comment by peterix** [comment]
There is no such thing as a 'curse link'
