### ISSUE TITLE
Issues with MultiMC, Source unknown

### ISSUE THREAD

**Issue by JacobGino01** [MultiMC/MultiMC5#1936]
System Information
-----------------------------
MultiMC version: 0.5.0-945 on win32

Operating System: Windows 10

Summary of the issue or suggestion: 
----------------------------------------------
Attempts to run instances resulting in a crash (I assume of the Minecraft Client)

What should happen:
------------------------------
Should run Minecraft 1.12 with forge 1.12-14.21.1.2389 (Custom) and the following mods/resource packs:
-Just Enough Items 4.7.1.71
-LuntriusCore 1.2.0.40
-OptiFine_1.12_HD_U_C2
-Schematica-1.12-1.7.8
-ToroHealth Damage Indicators 1.12-11
-Xaero's Minimap 1.13.1 Fair-Play
-PureBDcraft 256x MC112
I've already double-checked that all mods have any required side modes (such as schematica and luntriusCore) and I've allocated plenty of space to the program. I'll link the crash report. (sorry if this a stupidly  easy issue I know nothing about coding and I've already redownloaded all these mods/resource packs)
[crash-2017-07-24_21.45.13-client.txt](https://github.com/MultiMC/MultiMC5/files/1171857/crash-2017-07-24_21.45.13-client.txt)

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download all above mods/resource packs on the corresponding version

2. Run through MultiMC as a 1.12 instance

3.

Suspected cause:
---------------------------
(I'm sorry I have no idea)

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
logs linked above

Additional Info:
---------------------------
I know nothing about this kind of stuff so if this is something kinda dumb I apoligize.

**Comment by peterix** [comment]
Please use the upload button on the main log. Crash logs are not that useful.
