### ISSUE TITLE
I've an issue with launching my modpack in MultiMC

### ISSUE THREAD

**Issue by Mattycapz** [MultiMC/MultiMC5#1938]
Here it's the log with the error: https://paste.ee/p/0kY8A
**Please help me**

**Comment by QuImUfu** [comment]
You have installed some mods for a wrong version of minecraft. Make sure all mods are for 1.7.10.
e.g. BetterFPS,BiomesOPlenty etc.

**Comment by Mattycapz** [comment]
I reinstalled the correct versions and it gives me this error: https://paste.ee/p/Zt2ZU

**Comment by tehbasshunter** [comment]
You downloaded the wrong copy of NEI. You grabbed the dev version.

**Comment by Mattycapz** [comment]
I changed NEI version and it gives me this: https://paste.ee/p/fGw2s
