### ISSUE TITLE
Texture Pack Crash!

### ISSUE THREAD

**Issue by BaconFlavorHair** [MultiMC/MultiMC5#1939]
MultiMC version:
-----------------------------
0.5.0-945

Operating System:
-----------------------------
Windows 10

Summary of the issue or suggestion:
----------------------------------------------
When I change Texture Packs, Minecraft b.1.3 Crashes

What should happen:
------------------------------
The Texture Pack changing

Suspected cause:
---------------------------
Version of Windows not supported
"WARNING: Found unknown Windows version: Windows 10"

Logs/Screenshots:
-------------------------
MultiMC version: 0.5.0-945

Minecraft folder is:
instances/b1.3b/minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_131/bin/javaw.exe

Java is version 1.8.0_131, using 64-bit architecture.

Main Class:
  

Native path:
  C:/Users/snodg/Downloads/mmc-stable-win32/MultiMC/instances/b1.3b/natives

Traits:
traits texturepacks
traits legacyLaunch

Libraries:
  C:/Users/snodg/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/snodg/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/snodg/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/snodg/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/snodg/Downloads/mmc-stable-win32/MultiMC/versions/b1.3b/b1.3b.jar
  C:/Users/snodg/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/snodg/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-windows.jar

Params:
   

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1408m, -Xmx6986m, -Duser.language=en]

Minecraft process ID: 12588

Using onesix launcher.

Launching with applet wrapper...
28
Setting user: <PROFILE NAME>, token:<ACCESS TOKEN>:<PROFILE ID>
Jul 27, 2017 10:42:11 PM net.java.games.input.DefaultControllerEnvironment getControllers
WARNING: Found unknown Windows version: Windows 10
Jul 27, 2017 10:42:12 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Attempting to use default windows plug-in.
Jul 27, 2017 10:42:12 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.DirectAndRawInputEnvironmentPlugin

Starting up SoundSystem...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
OpenAL initialized.

Process crashed with exitcode -805306369.

**Comment by QuImUfu** [comment]
what texture pack did you try to load? Can not reproduce.

**Comment by BaconFlavorHair** [comment]
https://www.planetminecraft.com/texture_pack/lego-craft/

**Comment by BaconFlavorHair** [comment]
The Texture Pack maybe corrupted, other Texture Packs work.

**Comment by QuImUfu** [comment]
On my pc that texture pack works fine. Maybe your download got corrupt.
