### ISSUE TITLE
Help! "Invalid Maximum Heap Space" Whilst trying to start a Modpack. (MultiMC)

### ISSUE THREAD

**Issue by ArcadeWolf** [MultiMC/MultiMC5#1940]
System Information
-----------------------------
MultiMC version: 0.5.0-945

Operating System: Windows 10 Home 64-bit

Summary of the issue or suggestion:
 Whenever I try to start a custom modpack, the following issue arises; "Invalid maximum heap size: -Xmx4096m
The specified size exceeds the maximum representable size." 
One fix I've tried is, of course, changing the Memory allocation yet no matter what it will not work. 

I also tried uninstalling and reinstalling both MultiMC and Java. On the opening screen where you set the memory allocation of which your PC will allow, I'm restricted to a minimum of 512 and a maximum of 1280. whether or not this is an issue I'm not sure but all together I'm clueless. 
----------------------------------------------

What should happen: The Modpack SHOULD start as normal.
------------------------------

Suspected cause: Memory Allocation?

Logs/Screenshots:
----------------------------

![image](https://user-images.githubusercontent.com/30525138/28713920-0acf98a2-7389-11e7-8789-9f38882e9b8e.png)

![image](https://user-images.githubusercontent.com/30525138/28714123-edf31460-7389-11e7-9568-976510360481.png)

Additional Info:
---------------------------
The following are some of my PC specs:

Processor: Intel Core i5-7500 Kaby Lake CPU, 4 Cores, 3.4 - 3.8GHz
Graphics Card: NVIDIA GeForce GTX 1060 6GB
Motherboard: Gigabyte Z270-Gaming K3 Motherboard
Memory: 8GB DDR4 2133MHz Memory (2 x 4GB Sticks)
Hard Drive: Seagate 2TB 7200RPM Hard Disk

**Comment by ArcadeWolf** [comment]
Thank you for your reply, I tried reinstalling a separate Java yet the same thing occured

**Comment by QuImUfu** [comment]
Have you chosen the 64 bit java Installation in the MultiMC settings?
Are you sure you have installed the 64 bit java version?
The whole log (via upload button) would help.
