### ISSUE TITLE
SSL Context Error on Debian 9.1.0

### ISSUE THREAD

**Issue by Duplicitous** [MultiMC/MultiMC5#1942]
System Information
-----------------------------
MultiMC version: Current Stable Release

Operating System: Debian 9.1.0

Summary of the issue or suggestion: 
----------------------------------------------
"Authentication operation failed due to a network error: Unable to init SSL Context: (99)"

What should happen:
------------------------------
I should be able to log into my Minecraft account but I don't appear able to. It responds with the above quote.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install and launch MultiMC.

2. Try logging into your account.

Suspected cause:
---------------------------
The root of the problem is the SSL libs packaged with Debian currently. I've attempted other solutions mentioned on this GitHub page (creating a link to the .so files from your system to the bin folder of MultiMC; removing all files except for the libMultiMCs; installing the 32-bit versions of SSL and dependencies; trying both the .deb and .tar.gz versions of the client) but all to no avail.

Logs/Screenshots:
----------------------------
https://paste.ee/p/t4LnP

**Comment by XylexRayne** [comment]
I just got MultiMC on my Newly installed Debian 9.1.0 environment and having this issue as well.

**Comment by QuImUfu** [comment]
Tested it with a fresh Debian 9.1.0 installation and the workaround mentioned in #1784 still works perfectly.
(delete all libraries under MultiMC/bin except the ones starting with "libMultiMC_" and libxcb-sync.so.0)
This is a duplicate of #1784

**Comment by Duplicitous** [comment]
While I attempted this earlier with no success, I was then under the impression that I was to delete the libxcb-sync.so.0 along with all the other files. Now that I've deleted those files and left the libxcb-sync.so.0 file alone and intact, it now allows me to log into the client. Thank you for particularly pointing out the libxcb file. I must have somehow grazed past that.
