### ISSUE TITLE
Add support for RAR jar mods

### ISSUE THREAD

**Issue by Zekken01** [MultiMC/MultiMC5#1943]
You should add support for adding RAR files as jar mods because a lot of old mod authors used to package their mods in RAR files. Also, some people don't know how to repackage them.

**Comment by QuImUfu** [comment]
Just curious. What mod is using a RAR file? I have never meet one.

**Comment by peterix** [comment]
Some ancient jar mods.

**Comment by peterix** [comment]
Tracked on workflowy: https://workflowy.com/s/2EyDMcp7CU#/867658544da2

**Comment by calloatti** [comment]
I have downloaded all the mod files data from curseforge. The number of mod files in rar format is negligible.

I can provide the exact numbers if you want them.

**Comment by brodycas3** [comment]
well, I was more talking about jar mods but I didn't realize that people
still used anything other than .jar for forge mods. I would like that
number also.

**Comment by calloatti** [comment]
Just edited the comment with the numbers...

**Comment by brodycas3** [comment]
instead of posting the comment saying you changed that comment you could
have posted the numbers in this comment -_-
