### ISSUE TITLE
Failing to import a 1.12 curse modpack.

### ISSUE THREAD

**Issue by dmodoomsirius** [MultiMC/MultiMC5#1944]
System Information
-----------------------------
MultiMC version: Version 0.6.0-develop-1049

Operating System: Windows 10

Summary of the issue or suggestion: Failing to commit instance when importing a curse pack.
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.  attempt to inport any 1.12 modpack from curse and it either fails to copy overrides or commit the instance.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots: https://gist.github.com/dmodoomsirius/ce289b93fa870d84e6b44970ff0ca3ca
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
I suspect external influence. Maybe antivirus interference.

**Comment by dmodoomsirius** [comment]
Peterix you are correct. Kaspersky was not allowing it to do so. I told Kaspersky to ignore multimc and it worked perfectly.

**Comment by peterix** [comment]
Right. So I might have to interact with AV vendors again.

You can probably imagine my enthusiasm :)

**Comment by sciolizer** [comment]
Ran into the same problem. Adding a Windows Defender exclusion fixed it.

**Comment by Drecondius** [comment]
It's not just AV, curse itself randomly rejects connections to the data server. I believe it's their DDoS protection algorithm as this happens on Linux and Mac systems as well.
