### ISSUE TITLE
Crashing while launching forge 1.12 instance

### ISSUE THREAD

**Issue by kotsho** [MultiMC/MultiMC5#1945]
System Information
-----------------------------
MultiMC version: Version 0.5.0-887

Operating System: Linux

Summary of the issue or suggestion:
----------------------------------------------

What should happen: Launch Minecraft 1.12 with forge
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install forge for 1.12

2. Launch Minecraft

3.

Suspected cause:
---------------------------

Logs/Screenshots:
https://paste.ee/p/F9rmx
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info: Thanks you very much for reading :)
---------------------------

**Comment by S10MC2015** [comment]
You put it as what should happen xd

**Comment by peterix** [comment]
Well, the log is gone. Closing.
