### ISSUE TITLE
Error: job 'modpack download' failed to process

### ISSUE THREAD

**Issue by LuciousLisa** [MultiMC/MultiMC5#1946]
System Information
-----------------------------
MultiMC version: 0.5.5-887

Operating System: Linux (Debian 9)

Summary of the issue or suggestion:
----------------------------------------------
Unable to import modpack through link when creating a new instance.

What should happen:
------------------------------
A new instance with the specified modpack should be created.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Click 'new instance'

2. Select option 'Import Modpack (local file or link)'.

3. Paste link to Curseforge page, i.e. https://minecraft.curseforge.com/projects/project-ozone-lite

4. Click 'OK' button

5. Receive error window (Gnome): 'job 'modpack download' failed to process'

Suspected cause:
---------------------------
Unknown

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
http://imgur.com/a/cpvMl

Additional Info:
---------------------------
I have also tried this with a different modpack that isn't in Beta status, but that didn't give different results.  
Unsure if it's related, but I have also noticed that the application fails to fetch the changelog, of which I have provided an additional screenshot. For searching purposes; this particular error reads 'Job 'Changelog' failed to process'.

**Comment by tehbasshunter** [comment]
You're doing 2 things wrong.  
  
1. Curse importing only works on the dev version of MMC. You can change to that channel by clicking the clipboard and switching the update channel right there.  
2. You're using the wrong link. You actually want to use this link for the importing: https://minecraft.curseforge.com/projects/project-ozone-lite/files/2459979/download

**Comment by peterix** [comment]
Indeed. Random website links are not intended to work. If what you get from the link using a dumb downloader is not a valid modpack zip file, it is not a valid link.

**Comment by LuciousLisa** [comment]
Thanks for the info. I'll wait for the next release, I don't want to use a dev. version for a number of reasons. Hopefully it'll be soon, considering I've also had to deal with issue #1784.
