### ISSUE TITLE
Failed  "https://cursemeta.dries007.net/233114/2315475.json"  with reason  QNetworkReply::NetworkError(ContentOperationNotPermittedError)

### ISSUE THREAD

**Issue by torndar** [MultiMC/MultiMC5#1947]
System Information
-----------------------------
MultiMC version: 0.6.0-develop-1049

Operating System: Win10

Summary of the issue or suggestion:
----------------------------------------------
Can't import Curse packs, get an error about resolving mods.

What should happen:
------------------------------
Pack should import.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download and try to import a Curse modpack

Suspected cause:
---------------------------
cursemeta.dries007.net outage/overload

Logs/Screenshots:
----------------------------
   13.533 D Fixing permissions for extracted pack files...
   13.571 D Pack appears to be from 'Flame'.
   13.586 D Task "Flame::FileResolvingTask(0x4795880)" started
   13.587 D Task "NetJob(Mod id resolver)" started
   13.587 D Downloading  "https://cursemeta.dries007.net/233114/2315475.json"
   13.587 D Downloading  "https://cursemeta.dries007.net/228932/2333195.json"
   13.588 D Downloading  "https://cursemeta.dries007.net/235279/2287442.json"
   13.588 D Downloading  "https://cursemeta.dries007.net/226406/2264779.json"
   13.588 D Downloading  "https://cursemeta.dries007.net/231868/2331048.json"
   13.588 D Downloading  "https://cursemeta.dries007.net/64578/2322348.json"
   14.770 C Failed  "https://cursemeta.dries007.net/233114/2315475.json"  with reason  QNetworkReply::NetworkError(ContentOperationNotPermittedError)
   14.770 D Download failed in previous step: "https://cursemeta.dries007.net/233114/2315475.json"
   14.770 D Downloading  "https://cursemeta.dries007.net/221696/2316201.json"
   15.329 C Failed  "https://cursemeta.dries007.net/228932/2333195.json"  with reason  QNetworkReply::NetworkError(ContentOperationNotPermittedError)
   15.329 D Download failed in previous step: "https://cursemeta.dries007.net/228932/2333195.json"
   15.329 D Downloading  "https://cursemeta.dries007.net/241967/2344547.json"
   15.409 C Failed  "https://cursemeta.dries007.net/231868/2331048.json"  with reason  QNetworkReply::NetworkError(ContentOperationNotPermittedError)
   15.409 D Download failed in previous step: "https://cursemeta.dries007.net/231868/2331048.json"

**Comment by torndar** [comment]
The forbidden issue seems to be resolved but not I'm getting not found errors for some of the metadata files.
 2879.474 C Failed  "https://cursemeta.dries007.net/61811/2457485.json"  with reason  QNetworkReply::NetworkError(ContentNotFoundError)

**Comment by dries007** [comment]
Sorry, 100% my fault. I'm moving server hosts. I'll update you when it's back up. Shouldn't be more then 30 minutes hopefully.

**Comment by dries007** [comment]
Alright, the static file system is back up, now 90% of all files should work. I'm still working on the dynamic system, that is a little harder to test.

**Comment by dries007** [comment]
Should be fixed now. I'm sorry for the inconvenience.

**Comment by torndar** [comment]
Working for me, thanks!
