### ISSUE TITLE
Not creating .MultiMc folder on LInux

### ISSUE THREAD

**Issue by coreybruce** [MultiMC/MultiMC5#1948]
>Not creating .MultiMc folder on LInux and dumps all files to home folder
>Even after setting .MultiMC, instances, mods, lwjgl and mods the launcher still downloads all the files and runs from my home folder instead of .MultiMC

**Comment by QuImUfu** [comment]
The instances, libraries... folders are generated at the same place the MultiMC start script (named MultiMC) is placed. it you place this script in .MultiMC, the folders do generate there. You can link to the script if you want to start MultiMC from a different location.

**Comment by MggMuggins** [comment]
Did you install from the .deb, or from a tarball? Or from source? The way I have it set up, the multimc folder is in ```~/.local/share``` and I have a .desktop file that I use to run the script without a terminal. See #1702 for some specific .desktop issues I had.

**Comment by coreybruce** [comment]
I installed the deb file, it use to just make a .MultiMC folder but now it doesn't

**Comment by coreybruce** [comment]
I fixed it by correcting the symlink in ~/.local/share
