### ISSUE TITLE
Possible integration of Vazkii's Curse modpack downloader?

### ISSUE THREAD

**Issue by Lucifirius** [MultiMC/MultiMC5#1950]
Would it be possible to get Vazkii's Curse modpack downloader integrated so users can download a modpack and have an instance created for it? 

https://github.com/Vazkii/CMPDL

**Comment by peterix** [comment]
The dev version already contains something similar.

**Comment by calloatti** [comment]
One feature some people on Reddit mentioned is the ability to update modpacks, that is, currently you can import a modpack but there is no way to update the instance when there is a new version of the modpack.

Maybe add a feature to be able to update an instance created from a modpack? It does not seem to be more complicated than the initial import right?

**Comment by codewarrior0** [comment]
It's a bit more complicated. For example, the updater needs to throw away old versions of mods without throwing away any mods the user might have added to the pack.
