### ISSUE TITLE
Implement ServerSync modpack support

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MultiMC/MultiMC5#1951]
https://github.com/superzanti/ServerSync/issues/67

@peterix we have a dilemma with how to make ServerSync update automatically on launch I suggested that the author work with the Multi-MC team because I know you are very dedicated in terms of development as is the Dev of ServerSync. If you feel annoyed with this post please explain and then close it otherwise I also see this as a way to continue to pull people towards the two most amazing Minecraft additions I have seen to date.

**Comment by glindsey** [comment]
I'm going to second this feature request as I really think it would be a _killer_ feature for accessing modded Minecraft servers via MultiMC.

**Comment by peterix** [comment]
This could be one of the supported modpack 'platforms', when I get to implementing those.

**Comment by P3rf3ctXZer0** [comment]
@peterix thank you for considering this @rheimus and I appreciate your consideration. His application is absolutely incredible.

**Comment by YannikSc** [comment]
Why was this closed?
Is it implemented (and I can't find it) or was it dismissed?
If it was dismissed, then why?
Does nobody wanted to implement it (in this case, I would take a look at it) or is it simply not a wanted feature at all anymore?

**Comment by Zetabite** [comment]
I dont know of any modpack platform that has a working of doing this

**Comment by jamierocks** [comment]
Truth be told this doesn't even need MMC integration anyway, just write a component that includes that library and sets the appropriate main class.
