### ISSUE TITLE
archive does not contain instances.cfg

### ISSUE THREAD

**Issue by Cenrus** [MultiMC/MultiMC5#1953]
System Information
-----------------------------
MultiMC version:
MultiMC Version 0.5.0-945 on win32 - MultiMC 5
Operating System:
Windows 10
Summary of the issue or suggestion:
----------------------------------------------
Due to errors with the Twitch app, I have had to manually install Project Ozone 2. However; attempting to create a new instance of the latest Project Ozone 2 returns an error message: archive does not contain instance.cfg

What should happen:
------------------------------
The modpack (installed from https://mods.curse.com/modpacks/minecraft/244939-project-ozone-2-reloaded/2440935) can be made into an instance

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install Project Ozone 2 from the link above

2. Put the zipped file into MultiMC\instances

3. Attempt to create a new imported modpack instance, using the zipped file.

Suspected cause:
---------------------------
Unknown.

Logs/Screenshots:
![image](https://user-images.githubusercontent.com/31044876/29328234-c0997aea-81e9-11e7-82fe-1ac64f377c50.png)

----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
Unused

**Comment by flcmc** [comment]
Curse import is currently only on the develop branch.

**Comment by Cenrus** [comment]
Okay. How do you recommend I install the modpack?

**Comment by flcmc** [comment]
By switching to the develop branch by going to multimc settings and importing the modpack zip file.

**Comment by Cenrus** [comment]
The issue is fixed. thanks for the help!
