### ISSUE TITLE
MultiMC can't even run Vanilla Mincraft!  Help!

### ISSUE THREAD

**Issue by EpicHedgehogGamer** [MultiMC/MultiMC5#1955]
System Information
-----------------------------
MultiMC version: Version 0.5.0-945 on win32

Operating System: IDK

Summary of the issue or suggestion:
MultiMC plainly won't work, it doen't launch any version of Vanilla Minecraft.  Yet it the ordinary Minecraft launcher works just fine.
----------------------------------------------

What should happen: Minecraft should properly launch, as usual.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. I have no idea since this isn't modded or anything.

Suspected cause:
---------------------------
MultiMC isn't giving me a very good first impression.

Logs/Screenshots:
----------------------------
https://paste.ee/p/ZSIA4

Additional Info:
---------------------------
My first time using MultiMC, so this isn't the best first impression.

**Comment by brodycas3** [comment]
`OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.`

You either need to get drivers for your GPU or update them.

**Comment by EpicHedgehogGamer** [comment]
Ugh, if that's the case than that's just annoying, seeing as I just got this PC from my Uncle who is a Computer Wiz.  Figured he would've had made everything as powerful as possible.

**Comment by QuImUfu** [comment]
In this case:
Have you plugged you monitor in you discrete graphic card, if you have one?
I'm asking because if you uncle really knows a lot about pc's, he should have installed the Driver for the best graphic solution.

**Comment by EpicHedgehogGamer** [comment]
I have no idea what that is so I'm gonna say I probably don't have one.
Also my Uncle was probably just lazy.
I guess it doesn't really matter, I'm planning on buying a laptop soon anyway.  So I'll leave the issues for my little sister to sort out if she ever wants to play a modpack. Lol
