### ISSUE TITLE
Java not being detected on OSX 10.7.5 (lion)

### ISSUE THREAD

**Issue by GH-Harry** [MultiMC/MultiMC5#1957]
System Information
-----------------------------
Macbook Pro 2,2 maxed at 3gb ram
MultiMC version: 
0.5.0.908
Operating System:
OSX 10.7.5 (lion)
Summary of the issue or suggestion:
----------------------------------------------
It fails to detect both java 1.8_144 and 1.6.0_65 on initial setup saying that there hasn't been selected a version or something doesn't work and crashes when trying to do it from inside MultiMC.

What should happen:
------------------------------
It should simply detect the java version.

Steps to reproduce the issue:
-------------------------------------------------------------
1. Get a working copy of OSX 10.7.5 and java 8 or 6.

2. Run MultiMC and select java on the selection screen or select it in MultiMC.

3. Have it not detect java or crash respectively.

Suspected cause:
---------------------------
Sometype of 10.7 incompatibility can't really say much else.

Logs/Screenshots:
----------------------------
https://youtu.be/u0bhtLLjH9o
http://i.imgur.com/VP515oJ.png
http://i.imgur.com/eg6ygTA.png
[MultiMC-0.log.zip](https://github.com/MultiMC/MultiMC5/files/1237179/MultiMC-0.log.zip)

Additional Info:
---------------------------
Legacy version of vanilla launcher still works so the java copies don't seem to be the culprit.

**Comment by peterix** [comment]
Hm. Interesting...

The fact that it gets listed in there means that it should work. Otherwise it wouldn't have been listed at all.

Can you attach the MultiMC log? It's `MultiMC.0.log` inside the `.app` - make sure you go through the steps in that video and get the log after that, so it actually does have the information in it.

**Comment by GH-Harry** [comment]
[MultiMC-0.log.zip](https://github.com/MultiMC/MultiMC5/files/1237168/MultiMC-0.log.zip)

**Comment by GH-Harry** [comment]
[MultiMC-0.log.zip](https://github.com/MultiMC/MultiMC5/files/1237173/MultiMC-0.log.zip)
I got a fresh copy of the MultiMC and did purely what I had showed in the video (I had tried running 1.6.4 just to see the error message in the previous one) and got a second log incase that helps

**Comment by peterix** [comment]
Odd... I could swear there were comments here.

Anyway, can you try using the develop version?

You can grab it here:
https://files.multimc.org/downloads/mmc-develop-osx64.tar.gz

**Comment by GH-Harry** [comment]
I just tried the development build and the result seems identical but here's the 0 log from the dev build incase it helps
[MultiMC-0.log.zip](https://github.com/MultiMC/MultiMC5/files/1237350/MultiMC-0.log.zip)

**Comment by peterix** [comment]
We don't support 10.7 anymore, I think.
