### ISSUE TITLE
Easter Eggs do not work

### ISSUE THREAD

**Issue by QuImUfu** [MultiMC/MultiMC5#1958]
System Information
-----------------------------
MultiMC version:
0.6.0-develop-971
Operating System:
Lubuntu 64bit

Summary of the issue or suggestion:
----------------------------------------------
The little easter egg icons are not displayed anymore, if you name an instance for example "btw" no herobrine icon appears.

Logs/Screenshots:
----------------------------
![easter_egg_working](https://user-images.githubusercontent.com/9885301/29497590-f547521c-85ea-11e7-8d29-c73c101bee93.png)
![easter_egg_not_working](https://user-images.githubusercontent.com/9885301/29497591-f9430a3c-85ea-11e7-9a90-09ca329fda03.png)

Additional Info:
---------------------------
it does also happen with the latest stable version but not in 0.4.11

**Comment by peterix** [comment]
This is a critical issue.

**Comment by peterix** [comment]
Let's make some new ones instead.
