### ISSUE TITLE
Text resizes to an unreadable size when opening fullscreen on an external monitor

### ISSUE THREAD

**Issue by parkcitymedia** [MultiMC/MultiMC5#1964]
System Information
-----------------------------
MultiMC version: 0.5.0-887

Operating System: AntergOS (lin64)

Summary of the issue or suggestion:
----------------------------------------------
Text became extremely small after switching to fullscreen ingame (minecraft vanilla 1.12.2)

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. 

2. 
3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
I ... don't know what to do about this. Please provide more details and ideally a screenshot that shows the issue. Reopen if this is still a problem.
