### ISSUE TITLE
[Suggestion] Automatically Create Instance for Imported Modpacks

### ISSUE THREAD

**Issue by 132ikl** [MultiMC/MultiMC5#1965]
System Information
-----------------------------
MultiMC version:
0.5.1

Operating System:
Arch Linux x64

Summary of the issue or suggestion:
----------------------------------------------
When you import a modpack, if the archive isn't specifically made for MultiMC, you won't be able to make an instance because the archive doesn't contain an instance.cfg. The program should be able to automatically figure out the directory structure and anything it can't figure out it can have the user fill out. This would make it easier to import modpacks from Curse or other websites.

What should happen:
------------------------------
Select "Import Modpack"
Paste link
The launcher figures out what folder the mods are in, the configs, etc, and asks the user anything it can't figure out on its own.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Select "Import Modpack"

2. Paste link from Curse, for example the Age of Engineering modpack: 
https://minecraft.curseforge.com/projects/age-of-engineering/files/2461598/download

3. You recieve the message "Archive does not contain instance.cfg".

**Comment by QuImUfu** [comment]
Support for curse is added in develop, but iirc you have to download the zip and import it afterwards.

**Comment by peterix** [comment]
That's not correct.

Anyway, it doesn't contain anything to identify how to handle the contents. If I implemented that as you ask, with curse packs, you would end up with useless stubs that are missing most of the mods.

The pack format matters. Guessing is a bad idea.

**Comment by QuImUfu** [comment]
I did not say his idea is implemented (i already thought this would be impossible (at least for curse packs), but was not sure so i said noting about that), i only mentioned that if he wants to add a curse pack, he could, because support for the curse pack format is added in develop.
Sorry if that was not clear. :D

**Comment by peterix** [comment]
Alright. The facts:
* Curse pack import is in develop branch already. And it is correct.
* Guessing what to do based on the contents is bound to end up with a broken result. You will absolutely have to fix it manually anyway. If I did the curse support that way, you wouldn't be able to install most curse packs at all. Maybe with one or two exceptions - the ancient FTB pyramid packs actually do contain all the necessary mods.

**Comment by jonqrandom** [comment]
@132ikl no guarantees, but here's a fairly easy workaround that i found shifting a modpack i'm working on from (ugh) twitch app to multiMC; 
install the modpack via twitch, then export it and in the export dialogue make sure the "mods" folder is ticked (it won't be by default). 
then you can import *that* .zip through multiMC's new instance import modpack dialogue. 
no promises, but it worked for me.

**Comment by 132ikl** [comment]
@jonqrandom I'm on Linux so I can't use the Twitch App in the first place. I've been using Vazkii's CMPDL but it's still annoying to have to download it from there and then move it to the MultiMC folder every time there's an update. Hopefully that won't be as much of an issue with the Curse Import.

**Comment by flcmc** [comment]
You can update to the develop branch and import curse zip files.

**Comment by jonqrandom** [comment]
@132ikl i'm ever so sorry, i made a huge mistake; i'm on dev channel updates anyways, i guess i clicked it by reflex when i installed. deleted my other comment to avoid spreading my misinformation. 
again, sincere apologies!

**Comment by 132ikl** [comment]
@jonqrandom No worries, it's still valid information. It just only applies to the Windows version and could still be useful information for others.  For any Windows users in the future finding this information, here's what jonqrandom posted originally:
"no guarantees, but here's a fairly easy workaround that i found shifting a modpack i'm working on from (ugh) twitch app to multiMC;
install the modpack via twitch, then export it and in the export dialogue make sure the "mods" folder is ticked (it won't be by default).
then you can import that .zip through multiMC's new instance import modpack dialogue.
no promises, but it worked for me."
