### ISSUE TITLE
[Suggestion] Make the instance name the name of the modpack

### ISSUE THREAD

**Issue by jambonmcyeah** [MultiMC/MultiMC5#1966]
System Information
-----------------------------
MultiMC version: 
0.6.0-develop-973

Operating System:
Arch Linux x64

Summary of the issue or suggestion:
----------------------------------------------
When importing curse modpacks, the name of the modpack is not the name of the instance and the icon is not the modpack icon.

What should happen:
------------------------------
When importing modpacks, the name of the curse modpack should be set to the actual modpack name and the icon should be set to the actual modpack icon

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Select "Import Modpack"

2. Paste link from Curse, for example the All The Mods modpack:
https://minecraft.curseforge.com/projects/all-the-mods/files/2455070/download

3. The icon of the instance is the default curse icon and the name of the instance is download

Logs/Screenshots:
----------------------------
![image](https://user-images.githubusercontent.com/21069675/29624660-ab96aa50-87f7-11e7-8ec8-fb0263536f47.png)

**Comment by peterix** [comment]
I will not be fixing this. the packs do not contain this information.

**Comment by peterix** [comment]
Although... some partial workaround could be applied, at least for the name.

**Comment by piepie62** [comment]
I think that the name would only require a couple lines of code added, but this is so minor that I don't really want to create a PR for it. Since the MultiMC instance import already has this, wouldn't adding these lines at line 269 in InstanceImportTask do it?
`if(!pack.name.isEmpty())
        {
            instance.setName(pack.name);
        }
        else
        {
            // default to a neutral name
            instance.setName("New Instance");
        }`

**Comment by zebMcCorkle** [comment]
Here's your code formatting:

```cpp
if (!pack.name.isEmpty()) {
    instance.setName(pack.name);
} else {
    // default to a neutral name
    instance.setName("New Instance");
}
```

**Comment by peterix** [comment]
That's nice, but the packs simply do not provide the name inside in the vast majority of cases.

**Comment by peterix** [comment]
Fixed the original post and removed the comment about formatting.

**Comment by piepie62** [comment]
I understand that some (if not most) may not include a name, but it seems to me like just having something this simple would help in quite a few cases. Looking at a few of the modpacks (more of which I will check later), of the four I have checked so far (which I realize is a small sample size; again, I will check more later) all of them had the name included in their manifest.json.

**Comment by peterix** [comment]
Hm. It's true that I was testing older packs... and there, it was basically none. So, it sounds like this is worth investigating.

**Comment by piepie62** [comment]
Yeah, I was looking at the packs that are near the beginning sorted by popularity. I don't know about older or less-popular packs though. I can look at more later, right now I cannot download any more to test. Stupid firewalls.

**Comment by peterix** [comment]
Well, when I put the feature together, I was basically only testing the oldest packs -  the ones that came from FTB like the original pyramid one. They didn't include proper names.

Anyway, if names are in newer packs, then some sort of detection of missing names / nonsense names could work.

IDK. I would hate to end up with everything being names 'example pack' because the pack authors were too lazy to fix the json or something.

**Comment by piepie62** [comment]
Yeah, that is a good point. I can understand that sentiment.

**Comment by piepie62** [comment]
Also, I have a hacky idea for the image. The webpages for the modpacks (on curseforge, not sure about just curse) have the icons on them, so if the page was downloaded as raw html, then the link should be in about the same place for every one because the basic layout of the webpage is the same, right?

**Comment by peterix** [comment]
I could do this properly - if I wanted to. The API wrapper that grabs all the mod information also grabs all the pack information.

This is stepping on Amazon's/Twitch's/Curse's toes. My infrastructure runs on Amazon S3. I do not know what they will do if I actually make their whole client thing obsolete.
So, I am intentionally limiting the amount of integration with curse - and I will keep this ugly/crappy/requiring manual steps/badly discoverable on purpose.

FUD. Don't you hate it? I do.

**Comment by piepie62** [comment]
See, in my opinion this is not, because it only provides one functionality of it. Yes, it is an important part of their client, but equally as important are the voice/text client, the modpack creation part, and whatever else there is about actual Twitch stuff in it (haven't actually looked at the client since the merge thing). Not to mention that they almost certainly have a better way to do it, considering that they developed the system and

**Comment by peterix** [comment]
I will learn what is acceptable when I get the cease&desist letter.

**Comment by piepie62** [comment]
I have also just read through Twitch's Terms of Service, and it appears that it is perfectly acceptable. Modpacks would be considered "User Content," and there is no security feature that stops this from happening given that this is exactly what someone could do manually with the download button. I still maintain that this is your decision, but I just wanted to provide my view based on my interpretation of Twitch's Terms.

**Comment by peterix** [comment]
No, you cannot do this manually with the download button.

**Comment by piepie62** [comment]
With multiple download buttons you can, that's what I meant

**Comment by peterix** [comment]
No, you cannot.

**Comment by piepie62** [comment]
What do you mean? How can you not?

**Comment by piepie62** [comment]
Not the icon, I guess

**Comment by peterix** [comment]
Not the mods either.

**Comment by piepie62** [comment]
If you download the zip file and open up the manifest file, with a bunch of copying and pasting you would eventually be able to download a modpack using the IDs provided in there.

**Comment by piepie62** [comment]
Ah

**Comment by piepie62** [comment]
That is true

**Comment by piepie62** [comment]
Okay, then I will stop talking about this. Sorry for the trouble I may have caused you.

**Comment by peterix** [comment]
I am not going to add hacks that depend on website layout that could change (intentionally or not) the next day. That way lies madness.

**Comment by piepie62** [comment]
That also makes sense, I can understand that.

**Comment by piepie62** [comment]
Just a thought that I had.

**Comment by peterix** [comment]
Well, I'll see what I can do.

**Comment by peterix** [comment]
The answer is: nothing.
