### ISSUE TITLE
Job 'Modpack download' failed to process

### ISSUE THREAD

**Issue by Starwort** [MultiMC/MultiMC5#1968]
System Information
-----------------------------
MultiMC version:
0.5.0-887lin64
Operating System:
Fedora 25
Summary of the issue or suggestion:
----------------------------------------------
I tried to import my modpack released on Curse (is beta). An error dialog box popped up with the message:
"Job 'Modpack download' failed to process:
https://minecraft.curseforge.com/projects/starworts-skyblock/files/2459658/download"

What should happen:
------------------------------
MultiMC downloads and installs the modpack

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Click "new" button in to left

2. Select import modpack

3. Paste `https://minecraft.curseforge.com/projects/starworts-skyblock/files/2459658/download` into the box

4. Error dialog

Suspected cause:
---------------------------
MultiMC did not process the download?

Logs/Screenshots:
----------------------------

My linux is buggy and won't take screen shots, but dialog reads

Error -- MultiMC 5
Job 'Modpack download' failed to process:
https://minecraft.curseforge.com/projects/starworts-skyblock/files/2459658/download

Additional Info:
---------------------------
N/A

**Comment by QuImUfu** [comment]
curse modpack import is only available in the development update channel, switch to it in the settings and it should work. 
I can download said modpack on my PC (Lubuntu 17.10 64bit).

**Comment by Starwort** [comment]
ok thanks
will try now

**Comment by Starwort** [comment]
still not working @ 0.6.0-develop-97lin64...
Also noteworthy for anyone who stumbles onto this and can't be bothered to read the tooltips (like I generally don't); settings is 5th icon and you have to restart before it tries to update

**Comment by QuImUfu** [comment]
Can you upload your MultiMC-0.log to a site like paste.ee and post a link?

**Comment by Starwort** [comment]
ok

[MultiMC-0.txt](https://github.com/MultiMC/MultiMC5/files/1254280/MultiMC-0.txt)

**Comment by QuImUfu** [comment]
````
"Could not create folder for /home/toby/Desktop/MultiMC/cache/minecraft.curseforge.com/projects/starworts-skyblock/files/2459658/download" 
````
seems to be the real problem.
Can you think of something preventing MultiMC from creating that folder in your installation? 
Can you manually create the folders (/home/toby/Desktop/MultiMC/cache/minecraft.curseforge.com/projects/starworts-skyblock/files/2459658)?

**Comment by Starwort** [comment]
it has them up to the number... idk why it didn't make the last one
