### ISSUE TITLE
Unable to import instance

### ISSUE THREAD

**Issue by Nykorin** [MultiMC/MultiMC5#1971]
System Information
-----------------------------
**MultiMC version:**
Version 0.6.0-develop-1095 on win32

**Operating System:**
Windows 10 x64

Summary of the issue or suggestion:
----------------------------------------------
Cannot import instance from exported instance.
"Unable to commit instance"

What should happen:
------------------------------
It should import the instance with no error

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download a fresh copy of MultiMC
2. Set up with Development update channel and update
3. Change folders for Instances, Mods, Lwjgl, and Icons to look into ../data/ instead of C:/MultiMC/data
4. Import existing instance exported from another MultiMC client

Suspected cause:
---------------------------
Probably not registering shortened paths like ../data instead of C:/MultiMC/data

Logs/Screenshots:
----------------------------
[MultiMC-0.log](https://pastebin.com/q61PMhnL)
```
413.107 W It is not possible to commit "C:/Users/nerok/Desktop/Minecraft/MultiMC/data/instances/_MMC_TEMP/{96bacdc1-5919-4a09-8d2d-6c419747c54d}/Custom" because it is not in "../data/instances/_MMC_TEMP/{96bacdc1-5919-4a09-8d2d-6c419747c54d}"
413.323 C Task "InstanceImportTask(0x6acb600)" failed:  "Unable to commit instance"
```

Additional Info:
---------------------------
I setup MultiMC in, perhaps, a strange way with main client files housed in C:/MultiMC/client folder and the rest (instances, mods, lwjgl, and icons) in C:/MultiMC/data folder. This time around trying shortened directories like ../data/instances instead of full path C:/MultiMC/data/instances.

**Tested with full folder path for importing, import was successful.**

**Comment by peterix** [comment]
This should be fixed now in develop.
