### ISSUE TITLE
Version mismatch in 0.5.1-945

### ISSUE THREAD

**Issue by yoyokenny** [MultiMC/MultiMC5#1975]
System Information
-----------------------------
MultiMC version: 0.5.1-945

Operating System: Windows 7

Summary of the issue or suggestion:
----------------------------------------------
Version mismatch in app, shows as 0.5.0-945 instead of 0.5.1-945

What should happen:
------------------------------
Version in app should be shown as 0.5.1-945

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download current stable (0.5.1-945)

2. Extract

3. Run MultiMC

Suspected cause:
---------------------------
Forgotten version number edit.

Logs/Screenshots:
----------------------------
![multimc version mismatch 1](https://user-images.githubusercontent.com/1491033/29991954-ea8dfdd8-8fd3-11e7-8810-d01b34e93874.png)
![multimc version mismatch 2](https://user-images.githubusercontent.com/1491033/29991953-ea8a22ee-8fd3-11e7-8b91-45937870898a.png)

Additional Info:
---------------------------

**Comment by peterix** [comment]
Not going to fix this.
