### ISSUE TITLE
Ubuntu installer desktop icon doesn't show up properly

### ISSUE THREAD

**Issue by azuntik** [MultiMC/MultiMC5#1976]
System Information
-----------------------------
MultiMC version:
0.5.0-887 on lin64

Operating System:
Kubuntu 17.04

Summary of the issue or suggestion:
----------------------------------------------
When using the Ubuntu installer, the SVG icon that is dropped in /opt/multimc isn't being used by the .desktop configuration file. Instead, you see a generic icon.

What should happen:
------------------------------
The MultiMC icon should appear.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install MultiMC on Kubuntu 17.04 using the Ubuntu installer

2. Check the entry at /usr/share/applications. The .desktop file appears to be properly formatted, but a generic icon is used by the system.

Suspected cause:
---------------------------
¯\\\_(ツ)_/¯

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
To fix this myself, I copied /opt/multimc/icon.svg to /usr/share/pixmaps/multimc.svg
I then modified the multimc.desktop file, changing icon=/opt/multimc/icon.svg to icon=multimc
Looks beautiful after that. My suggestion would be to modify the installer to drop the SVG icon into /usr/share/pixmaps on install. I think that's a pretty standard way of doing things.

**Comment by peterix** [comment]
I'm going to call this an ancient KDE bug, and close it as such.
