### ISSUE TITLE
Unable to get Allthemods to work on Minecraft 1.12.1

### ISSUE THREAD

**Issue by Razgriz700** [MultiMC/MultiMC5#1978]
System Information
-----------------------------
MultiMC version: 0.6.0-develop-1061

Operating System: Windows 10 x 64

Summary of the issue or suggestion: Unable to get multimc to launch allthemods mod pack
----------------------------------------------

What should happen: Followed a Youtube Video to install the instance yet It wouldn't launch. I should of launched
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.  unknown
2.

3.

Suspected cause: unknown
---------------------------

Logs/Screenshots: https://paste.ee/p/yMzUL
----------------------------
MultiMC version: 0.6.0-develop-1061

Minecraft folder is:
instances/allthemods 3 v.3.1/minecraft

Java path is:
C:/Users/Lane/Documents/MultiMC/Java/bin/javaw.exe

Java is version 1.8.0_144, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/Lane/Documents/MultiMC/instances/allthemods 3 v.3.1/natives

Libraries:
  C:/Users/Lane/Documents/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Lane/Documents/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/Lane/Documents/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Lane/Documents/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Lane/Documents/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/Lane/Documents/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Lane/Documents/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Lane/Documents/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Lane/Documents/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Lane/Documents/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Lane/Documents/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/Lane/Documents/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/Lane/Documents/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/Lane/Documents/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/Lane/Documents/MultiMC/libraries/com/mojang/realms/1.10.17/realms-1.10.17.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/net/minecraftforge/forge/1.12.1-14.22.0.2467/forge-1.12.1-14.22.0.2467-universal.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/jline/jline/2.13/jline-2.13.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/com/mojang/minecraft/1.12.1/minecraft-1.12.1-client.jar (missing)

Native libraries:
  C:/Users/Lane/Documents/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar (missing)
  C:/Users/Lane/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-windows.jar (missing)

Mods:
  ActuallyAdditions-1.12.1-r119
  ActuallyBaubles-1.12-1.1
  AdditionalBanners-1.12-1.5.39
  AIImprovements-1.12-0.0.1b3
  AkashicTome-1.2-9
  angelRingToBauble-1.12-0.3.0.46+306787e
  AppleCore-mc1.12.1-2.2.2
  AppleSkin-mc1.12-1.0.7
  appliedenergistics2-rv5-alpha-4
  Aroma1997Core-1.12.1-1.3.0.0.b121
  Aroma1997s-Dimensional-World-1.12.1-2.0.0.0.b56
  astralsorcery-1.12-1.6.1
  AutoRegLib-1.3-13
  badwithernocookiereloaded-1.12.1-1.7
  Baubles-1.12-1.5.1
  bdlib-1.14.1.6-mc1.12
  BedBugs-1.12-1.0.1
  BetterBuildersWands-1.12-0.11.1.245+69d0d70
  BiblioCraft[v2.4.3][MC1.12.0]
  binnie-mods-1.12.1-2.3.0.60
  BiomesOPlenty-1.12-7.0.0.2291-universal
  blockdrops-1.12-1.3.0
  Blur-1.0.4-14
  Bookshelf-1.12.1-2.1.431
  Botania r1.10-346
  BrandonsCore-1.12-2.3.2.129-universal
  Ceramics-1.12-1.3.2
  Chameleon-1.12-4.1.3
  Chisel-MC1.12-0.0.13.16
  chiselsandbits-14.6
  clarity-1.0
  CodeChickenLib-1.12-3.1.1.288-universal
  CoFHCore-1.12-4.3.5.13-universal
  CoFHWorld-1.12-1.0.1.8-universal
  ColossalChests-1.12-1.6.5
  CommonCapabilities-1.12-1.4.0
  Controlling-3.0.2
  CookingForBlockheads_1.12.1-6.3.6
  CosmeticArmorReworked-1.12.1-v1
  CraftingTweaks_1.12.1-8.1.5
  CraftTweaker2-1.12-4.0.4
  CTM-MC1.12-0.2.2.7
  cucumber[1.12]-1.0.0
  CustomMainMenu-MC1.12-2.0.6
  Cyclic-1.12-1.7.10
  CyclopsCore-1.12-0.10.17
  DarkUtils-1.12.1-1.7.169
  DefaultOptions_1.12.1-9.2.4
  DoomlikeDungeons-1.9.3-MC1.12
  Draconic-Evolution-1.12-2.3.3.261-universal
  ElevatorMod-1.12-1.3.4
  embers-0.221
  EnderStorage-1.12-2.4.0.119-universal
  environmentaltech-1.12.1-2.0.2d
  Exchangers-1.12-2.4
  ExtraRails-1.12-1.3.0
  extrautils2-1.12-1.6
  ExtremeReactors-1.12-0.4.5.34
  fairylights-2.1.1-1.12
  FastLeafDecay-v14
  fencejumper-1.12-1.0.0
  flatcoloredblocks-mc1.12-6.4
  foamfix-0.7.4-1.12-anarchy
  forestry_1.12.1-5.5.0.181
  Forgelin-1.5.1
  FTBLib-4.0.5
  FTBUtilities-4.0.3
  funky-locomotion-1.12-alpha-0.0.1
  gendustry-1.6.5.4-mc1.12
  generators-0.9.20.5-mc1.12
  gravestone-1.9.0
  Guide-API-1.12-2.1.4-57
  Harvest-1.12-1.2.4-16
  ImmersiveEngineering-0.12-71
  immersivepetroleum-1.12-1.1.3
  industrialcraft-2-2.8.16-ex112
  IndustrialWires-1.5-15
  IntegratedDynamics-1.12-0.8.7
  IntegratedTunnels-1.12-1.3.2
  InventoryTweaks-1.63+beta.108
  ironchest-1.12-7.0.31.818
  jei_1.12.1-4.7.8.92
  jeibees-0.9.0.2-mc1.12
  journeymap-1.12.1-5.5.0b3
  JustEnoughResources-1.12.1-0.8.4.24
  KleeSlabs_1.12-5.3.2
  lostcities-1.12-1.0.0
  MagicBooks-2.1.1
  Mantle-1.12-1.3.1.21
  mcjtylib-1.12-2.4.4
  MCMultiPart-2.2.2
  Mekanism-1.12.1-9.4.0.318
  MekanismGenerators-1.12.1-9.4.0.318
  MekanismTools-1.12.1-9.4.0.318
  modnametooltip_1.12.1-1.9.0
  moreoverlays-1.12-mc1.12
  Morpheus-1.12-3.3.2
  Morph-o-Tool-1.2-15
  MouseTweaks-2.8-mc1.12.1
  mysticalagradditions[1.12]-1.2.3
  mysticalagriculture[1.12]-1.6.3
  Natura-1.12-4.3.0.17
  NetherPortalFix_1.12.1-5.3.9
  NoMobSpawningOnTrees-1.2.1-mc1.12
  NotEnoughIDs-1.5.4.1
  notenoughwands-1.12-1.5.9
  oeintegration-2.2.0
  OpenComputers-MC1.12.1-1.7.0.4
  OpenGlider-1.12.1-1.1.0
  OreExcavation-1.4.105
  Pam's HarvestCraft 1.12.1b
  PersonalCars-1.4
  pressure-1.3.1.2-mc1.12
  Psi-r1.1-52
  QuantumStorage-1.12-4.4.0
  Quark-r1.2-104
  QuickLeafDecay-MC1.12.1-1.2.4
  rangedpumps-0.5
  ReAuth-3.5.1
  RebornCore-1.12.1-3.2.7.95-universal
  RedstoneArsenal-1.12-2.3.5.13-universal
  RedstoneFlux-1.12-2.0.1.2-universal
  refinedstorage-1.5.17
  refinedstorageaddons-0.1.1
  ResourceLoader-MC1.12-1.5.2
  rftools-1.12-6.13
  rftoolsctrl-1.12-1.6.8
  rftoolsdim-1.12-5.04
  roots-2-0.025
  rustic-0.4.1
  SBM-WoodenShears-1.12-0.0.1b8
  ShadowMC-1.12-3.8.0
  shetiphiancore-1.12.0-3.5.1
  SimpleSponge-1.12-3.5
  Skyblocks-0.1.1-alpha-1.12.1
  SoulShards-TOW-1.12-2.7.3-52
  SpiceOfLife-mc1.12-1.3.10
  StevesCarts-1.12.1-2.4.7.40
  StorageDrawers-1.12.1-5.3.0
  StorageDrawersExtras-1.12-3.1.0
  TConstruct-1.12-2.7.2.19
  TechReborn-1.12.1-2.6.13.189-universal
  terraqueous-1.12.0-1.4.2
  theoneprobe-1.12-1.4.18
  ThermalCultivation-1.12-0.1.1.6-universal
  ThermalDynamics-1.12-2.3.5.12-universal
  ThermalExpansion-1.12-5.3.5.19-universal
  ThermalFoundation-1.12-2.3.5.14-universal
  TinkerToolLeveling-1.12-1.0.2b
  Toast Control-1.12-1.1.1
  topaddons-1.12-0.15.1
  Traverse-1.12-1.2.1-22
  UniDict-1.12.1-1.0
  usefulnullifiers-1.4.1
  valkyrielib-1.12.1-2.0.2c
  WanionLib-1.12.1-1.0
  WaterStrainer-1.12-3.2.0
  Waystones_1.12.1-4.0.15
  xnet-1.12-1.4.0
  Xtones-1.12-1.0.5-8
  zerocore-1.12-0.1.0.9

Params:
  --username  --version MultiMC5 --gameDir C:/Users/Lane/Documents/MultiMC/instances/allthemods 3 v.3.1/minecraft --assetsDir C:/Users/Lane/Documents/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Couldn't extract native jar 'C:/Users/Lane/Documents/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar' to destination 'C:/Users/Lane/Documents/MultiMC/instances/allthemods 3 v.3.1/natives'
Couldn't extract native jar 'C:/Users/Lane/Documents/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar' to destination 'C:/Users/Lane/Documents/MultiMC/instances/allthemods 3 v.3.1/natives'
Couldn't extract native jar 'C:/Users/Lane/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-windows.jar' to destination 'C:/Users/Lane/Documents/MultiMC/instances/allthemods 3 v.3.1/natives'
MultiMC: Log upload triggered at: 02 Sep 2017 23:56:33 -0500
MultiMC: Log uploaded to: https://paste.ee/p/1QTjK
MultiMC: Log upload triggered at: 03 Sep 2017 00:04:07 -0500
MultiMC: Log uploaded to: https://paste.ee/p/ca3BV
Clipboard copy at: 03 Sep 2017 00:05:41 -0500
MultiMC: Log upload triggered at: 03 Sep 2017 00:05:44 -0500

Additional Info:
---------------------------

**Comment by kevinkjt2000** [comment]
I was able to get All the Mods 3 to work just fine in a new instance using the ruby gem curse client https://github.com/amcoder/curse_client

**Comment by peterix** [comment]
That is irrelevant. It was imported properly already.

**Comment by peterix** [comment]
That's a lot of missing libs tho... make sure you launch online. Offline mode doesn't run the update.

**Comment by Heufneutje** [comment]
I've had this issue with a regular MultiMC instance at one point as well. Though I haven't been able to reproduce it in the latest dev version.

**Comment by peterix** [comment]
Yeah, same... I even fixed a bug like that recently. But this is a newer version than that.

Either this is a regression, or a different bug. Or it was launched offline... ?

**Comment by Razgriz700** [comment]
I'll attempt to launch it online and offline again

**Comment by peterix** [comment]
Assuming fixed.
