### ISSUE TITLE
MultiMC fails to start.

### ISSUE THREAD

**Issue by Braggar** [MultiMC/MultiMC5#1979]
System Information
-----------------------------
MultiMC version: 0.5.0-887

Operating System: Debian Testing

Summary of the issue or suggestion:
----------------------------------------------
MultiMC completely fails to start.

What should happen:
------------------------------
MultiMC should start.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download latest linux64 MultiMC

2. Encounter ssl errors and delete the libs in bin as suggested in #1942

3. Be unable to run MultiMC

Suspected cause:
---------------------------
I have no earthly clue.

Logs/Screenshots:
----------------------------

    0.018 W Couldn't open "/home/adalwulf/.ftblauncher/ftblaunch.cfg" : "No such file or directory"
    0.018 W This is perfectly normal if you don't have FTB installed
    0.039 W ""
    0.041 W Blacklisted legacy version ignored:  "rd-160052"
    0.071 W QMetaObject::connectSlotsByName: No matching signal for on_actionDeleteGroup_triggered()
    0.176 W QPaintDevice: Cannot destroy paint device that is being painted

**Comment by Seegras** [comment]
Same here. 

Suspected cause: Linked Qt now definitly too old. Please recompile with a recent Qt. 

Then the SSLv2-error from #1942 ALSO wouldn't show up, even when the libraries are in the bin directory.

**Comment by peterix** [comment]
It would. I would still compile with the older OpenSSL.

**Comment by peterix** [comment]
Also, you likely deleted too much - or not enough - if it doesn't run.

**Comment by QuImUfu** [comment]
As it seems, multimc is actually not working on debian testing anymore, regardless of deleted (or not deleted) library files. Either Networking does not work or MultiMC doesn't start.
I can post a core dump, if requested.
A self-compiled version is working fine.

**Comment by QuImUfu** [comment]
Deleting **all** libraries except the ones starting with libMultiMC_ and the plugins folder as well (as peterx mentined in #1992) fixes this without recompiling.

**Comment by peterix** [comment]
We'll need some workaround for this.

**Comment by peterix** [comment]
Resolving as fixed, will be in stable release later today.
