### ISSUE TITLE
Texture pack not loading properly through MultiMC

### ISSUE THREAD

**Issue by LittleWhiteElk** [MultiMC/MultiMC5#1980]
System Information
-----------------------------
MultiMC version: 0.5.0-945

Operating System: windows 10 x 64

Summary of the issue or suggestion:
----------------------------------------------
After adding a resource pack to an instance via the resource packs' tab in 'edit instance', launched the game only to find the textures weren't showing up as they were supposed to.

What should happen:
------------------------------
Textures should be appearing on blocks and items.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Edit instance

2. Go to resource packs tab

3. Add

4. Selected a realism texture pack

5. Enabled and launch

6. Or: locate the 'resource packs' folder in the 'instance folder' and drop the texture pack in

> C:\Users\USER\Downloads\MultiMC\instances\1.12.1\minecraft\resourcepacks

Suspected cause:
---------------------------
Unknown

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
The title screen is showing the texture pack as normal.
![2017-09-04_21 12 46](https://user-images.githubusercontent.com/31615990/30020075-b8d1ace2-91b6-11e7-99c6-e07eb81701c6.png)
The texture pack has indeed been loaded.
![2017-09-04_21 13 00](https://user-images.githubusercontent.com/31615990/30020102-d81247f6-91b6-11e7-8558-2f41ada7b679.png)
Not showing any texture on any of the blocks like it's supposed to.
![2017-09-04_21 13 20](https://user-images.githubusercontent.com/31615990/30020125-e95bc276-91b6-11e7-9c83-4a7f3221957b.png)
![2017-09-04_21 13 33](https://user-images.githubusercontent.com/31615990/30020139-f08d20e4-91b6-11e7-87cb-2d9de2fcc630.png)
![2017-09-04_21 13 44](https://user-images.githubusercontent.com/31615990/30020147-f4997688-91b6-11e7-9652-801c91972fe0.png)

Additional Info:
---------------------------
I've checked the resource pack file to make sure none of the actual textures are missing, but they're all there.

**Comment by tehbasshunter** [comment]
Do you have optifine installed by chance?

**Comment by LittleWhiteElk** [comment]
@tehbasshunter Not that I no of, no.

**Comment by tehbasshunter** [comment]
What kind of graphics card do you have?

**Comment by LittleWhiteElk** [comment]
@tehbasshunter I don't think it's a graphics card issue as the texture pack works fine when I run the game through the normal launcher but my card is Intel(R) HD Graphics 520

**Comment by QuImUfu** [comment]
could you post a link to a uploaded log (via the upload button in MultiMC's Console window)?

**Comment by LittleWhiteElk** [comment]
@QuImUfu Here's the log from the last time I launched and tried the pack. https://paste.ee/p/T82zH

**Comment by QuImUfu** [comment]
The log indicates that you graphic solution does not have enough memory. 
As you have an igp, it shares memory with your system. Because you said it worked with the vanilla launcher, this might be caused by minecraft using to much system memory so you graphic solution is not able to allocate enough. Try limiting the memory minecraft can use to 1024 mb (lowest amount possible with default settings and without crash at render distance 8, with this texture pack). Additionally make sure nothing is running in the background while starting minecraft.

**Comment by LittleWhiteElk** [comment]
@QuImUfu How do I limit the memory Minecraft uses? I'm not very tech savvy so I need a bit of help

**Comment by QuImUfu** [comment]
in MultiMC under Instance Settings-> Settings -> Memory

**Comment by LittleWhiteElk** [comment]
@QuImUfu Set max memory it can use to 1024 mb (with lowest settings and render distance of 8) but it didn't seem to help.
