### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Mattyproxx** [MultiMC/MultiMC5#1987]
My game remains stuck on the 7/7 step of forge mod loading and Minecraft stops working, help me.
Here's the log: https://paste.ee/p/dZHgx
Thanks
![crash](https://user-images.githubusercontent.com/15181561/30168356-73a3c6fc-93e9-11e7-9fe9-00c4d50b69b7.JPG)

**Comment by jambonmcyeah** [comment]
This is bug tracker for MultiMC not a support thread for generic Forge/Minecraft problems
