### ISSUE TITLE
Add a button for install on one-click optifine 

### ISSUE THREAD

**Issue by PinkFloyd1213** [MultiMC/MultiMC5#1989]
Can you add a button like "install forge" for installing optifine ?

**Comment by brodycas3** [comment]
Possibly if it didn't break their TOS.

**Comment by yoyokenny** [comment]
> Possibly if it didn't break their TOS.

That's only if the files are redistributed. There is a way for direct links to the .jar for OptiFine
The TOS (The Copyright section on the OptiFine forum thread) doesn't mention anything about direct linking.

For technical purposes, the format of a direct link is this:
htt p://optifine.net/download?f=OptiFine_${optifine_version}.jar
(remove the space in "htt p")

The only other problem is an index of all the versions available.

**Comment by PinkFloyd1213** [comment]
Yes it would be completed! Rest to wait for the answer of the creator.

**Comment by peterix** [comment]
I think this was discussed before, but I really don't remember the details... anyway, I really want to start adding more things to the metadata soon. Optifine is one of the most requested things, so it will be first... in some form or another.

**Comment by Simix2017** [comment]
Hi,
I think a great idea would be the ability to install optifine without minecraft forge so that you can install it for minecraft 1.13.x

**Comment by tehbasshunter** [comment]
You already can. https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine
