### ISSUE TITLE
0.6.0-develop-1067:  no longer recognizes legacy instances

### ISSUE THREAD

**Issue by alyandon** [MultiMC/MultiMC5#1990]
System Information
-----------------------------
MultiMC version:  0.6.0-develop-1067

Operating System:  Windows 10 x64

Summary of the issue or suggestion:
----------------------------------------------
Updated to latest nightly and legacy instances have a red X along with a message in the status bar that reads "Unknown instance type"

What should happen:
------------------------------
Things should work

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.  Not really sure but likely use an older version to create an old Minecraft (say 1.5.1) instance and then update to latest.

Suspected cause:
---------------------------
A bug?  :-D

Logs/Screenshots:
----------------------------
None

**Comment by alyandon** [comment]
Attaching instance config from one of the Legacy instances

[instance.txt](https://github.com/MultiMC/MultiMC5/files/1301234/instance.txt)

**Comment by tehbasshunter** [comment]
Peterix nuked some code for instances made it earlier versions of MMC. Assuming it's not modded you can drag the world save folder into a new instance.  If it is modded you're going to have to wait.
  
He's already aware of the problem and said he'll do something to remedy it.

**Comment by alyandon** [comment]
Alright, thanks for the info.  I'll convert the instances over to another launcher for the time being.

**Comment by peterix** [comment]
You can just convert them to normal MultiMC instances. All the old versions are supported.

**Comment by alyandon** [comment]
@peterix  Not sure what you mean by that as they are already MultiMC instances - they just happen to be pre-1.6 so I can't launch them anymore with the current developer version.

**Comment by alyandon** [comment]
Alright, I fixed the instance configs by renaming IntendedJarVersion to IntendedVersion and changing InstanceType from Legacy to OneSix.

After that, starting MultiMC and re-adding the appropriate version of forge seemed to fix it.

**Comment by peterix** [comment]
If all you did is use forge, then that's the way to do it. Yes.

I'm working on a proper migration tool for these old instances that will account for the weirder things involved in old Minecraft modding.

**Comment by alyandon** [comment]
Yep, these are all modded forge instances.  Anyway, I didn't know if this was a bug or not so that's why I reported it.

**Comment by peterix** [comment]
This is now solved by having a migration mechanism built in. Please open new issues if that fails.

**Comment by alyandon** [comment]
Will do.  Thanks.
