### ISSUE TITLE
i dont cant enter in modpack

### ISSUE THREAD

**Issue by MarconesJr** [MultiMC/MultiMC5#1991]
MultiMC version: 0.5.0-945

Minecraft folder is:
instances/TumaticoMapa/minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/javaw.exe

O Java é da versão 1.8.0_144, usando arquitetura de 64-bit

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/marco/Desktop/MultiMC/instances/TumaticoMapa/natives

Libraries:
  C:/Users/marco/Desktop/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  C:/Users/marco/Desktop/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/marco/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/marco/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/marco/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/marco/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/marco/Desktop/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/marco/Desktop/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/marco/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/marco/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/marco/Desktop/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/marco/Desktop/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/marco/Desktop/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/marco/Desktop/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/marco/Desktop/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/marco/Desktop/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/marco/Desktop/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/marco/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/marco/Desktop/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/marco/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/marco/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/marco/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/marco/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/marco/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/marco/Desktop/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/marco/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/marco/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/marco/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/marco/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/marco/Desktop/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/marco/Desktop/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/marco/Desktop/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/marco/Desktop/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/marco/Desktop/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/marco/Desktop/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/marco/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/marco/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/marco/Desktop/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/marco/Desktop/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/marco/Desktop/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/marco/Desktop/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/marco/Desktop/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/marco/Desktop/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/marco/Desktop/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1566-1.7.10/forge-1.7.10-10.13.4.1566-1.7.10-universal.jar
  C:/Users/marco/Desktop/MultiMC/versions/1.7.10/1.7.10.jar
  C:/Users/marco/Desktop/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/marco/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-windows.jar
  C:/Users/marco/Desktop/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar
  C:/Users/marco/Desktop/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Mods:
  [1.7.10]BugfixMod-universal-2.5.0
  1.7.10-Pistronics2-v0.5.8
  1.7.10-SpaceCore-0.7.14
  AgriCraft-1.7.10-1.4.6-hotfix
  animalsPlus-1.2
  appliedenergistics2-rv3-beta-2
  ArchimedesShips-1.7.1
  BetterTitleScreen-1.7.10-1.1
  BiblioCraft[v1.10.4][MC1.7.10]
  BiomesOPlenty-1.7.10-2.1.0.1364-universal
  Biome-Wand-Mod-1.7.10
  Botania r1.8-247
  BrandonsCore-1.0.0.10-bugfix
  buildcraft-7.0.16
  Carpenter's Blocks v3.3.6 - MC 1.7.10
  Chisel2-2.5.1.44
  CodeChickenCore-1.7.10-1.0.7.46-universal
  CoFHCore-[1.7.10]3.0.3-303
  CoFHLib-[1.7.10]1.0.3-175
  compactmachines-1.7.10-1.21
  ComputerCraft1.73
  deathaudio-1.0
  denseores-1.6.2
  Draconic-Evolution-1.7.10-1.0.2-Snapshot_9
  EnderCore-1.7.10-0.2.0.31_beta
  EnderIO-1.7.10-2.3.0.421_beta
  EnderStorage-1.7.10-1.4.7.37-universal
  EnderTech-1.7.10-0.3.2.388
  ExtraTiC-1.7.10-1.4.5
  extrautilities-1.2.12
  Farseek-1.0.8
  fastcraft-1.21
  FastLeafDecay-1.7.10-1.1
  forestry_1.7.10-3.6.2.19
  funky-locomotion-1.7.10-beta-5c
  GardenOfGlass
  growthcraft-apples-1.7.10-2.1.0
  growthcraft-bamboo-1.7.10-2.1.0
  growthcraft-bees-1.7.10-2.1.0
  growthcraft-cellar-1.7.10-2.1.0a
  growthcraft-core-1.7.10-2.1.0a
  growthcraft-fishtrap-1.7.10-2.1.0a
  growthcraft-grapes-1.7.10-2.1.0
  growthcraft-hops-1.7.10-2.1.0
  growthcraft-rice-1.7.10-2.1.0a
  gud_thaumicnei-1.2.3
  ImmersiveEngineering-0.6.5.1
  InventoryTweaks-1.58-147
  ironchest-1.7.10-6.0.62.742-universal
  Jabba-1.2.1a_1.7.10
  journeymap-1.7.10-5.1.0-unlimited
  LagFix-2.0.1-mc1.7.10-forge
  LaunchGui-1.7.10-2.0-17-client
  LunatriusCore-1.7.10-1.1.2.21-universal
  Mantle-1.7.10-0.3.2
  MemoryCleaner-1.4-mc.1.7.10
  Minechem-1.7.10-5.0.5.398
  MineFactoryReloaded-[1.7.10]2.8.0-104
  MmmMmmMmmMmm-1.6
  MobiusCore-1.2.5_1.7.10
  MorePlayerModels_1.7.10b
  mystcraft-1.7.10-0.12.1.00
  natura-1.7.10-2.2.0.1
  neiaddons-1.12.10.33-mc1.7.10
  NEIIntegration-MC1.7.10-1.0.11
  NotEnoughItems-1.7.10-1.0.5.111-universal
  OpenBlocks-1.7.10-1.4.3
  OpenModsLib-1.7.10-0.7.3
  Opis-1.2.5_1.7.10
  OptiFine_1.7.10_HD_U_C1
  PlanetguyLib-1.6.0.1
  ProjectRed-1.7.10-4.7.0pre5.89-Base
  ProjectRed-1.7.10-4.7.0pre5.89-Compat
  ProjectRed-1.7.10-4.7.0pre5.89-Lighting
  Railcraft_1.7.10-9.6.1.0
  RedstoneArsenal-[1.7.10]1.1.1B1-85
  Schematica-1.7.10-1.7.6.121-universal
  Steves-Factory-Manager-Mod-1.7.10
  StorageDrawers-1.7.10-1.7.5
  TConstruct-1.7.10-1.8.8
  Thaumcraft-1.7.10-4.2.3.5
  ThermalDynamics-[1.7.10]1.1.0-161
  ThermalExpansion-[1.7.10]4.0.3B1-218
  ThermalFoundation-[1.7.10]1.2.0-102
  TiCTooltips-mc1.7.10-1.2.5
  TMechworks-1.7.10-0.2.14.100
  VersionChecker-1.1.9
  Waila-1.5.10_1.7.10
  WailaHarvestability-mc1.7.x-1.1.2
  WailaNBT-1.7.10-1.4
  witchery-1.7.10-0.24.1
  WR-CBE-1.7.10-1.4.1.9-universal
  zCraftingManager 0.7.5 mc1.7.10
  Ztones-1.7.10-2.2.1

Params:
  --username  --version MultiMC5 --gameDir C:/Users/marco/Desktop/MultiMC/instances/TumaticoMapa/minecraft --assetsDir C:/Users/marco/Desktop/MultiMC/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType  --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2304m, -Xmx1024m, -Duser.language=en]

ID do Processo do Minecraft: 14880

Error occurred during initialization of VM
Initial heap size set to a larger value than the maximum heap size
Minecraft foi fechado com o código de saída 1.
Clipboard copy at: 14 Sep 2017 09:50:36 -0300

**Comment by peterix** [comment]
`-Xms2304m, -Xmx1024m`

I don't know how you managed to do that... But setting the minimum larger than maximum will not work.
