### ISSUE TITLE
Combination of MultiMC and Optifine causing system lag.

### ISSUE THREAD

**Issue by Gummin** [MultiMC/MultiMC5#1994]
System Information
-----------------------------
MultiMC version: 0.5.0-945

Operating System: Windows 10 Pro

[Detailed Specs](https://pcpartpicker.com/user/zaka888/saved/Zvdv6h)

Summary of the issue or suggestion:
----------------------------------------------

When I open the game my PC suddenly starts dying, mouse movement becomes extremely slow despite CPU, GPU, RAM and Disk usage being very low.
It's so bad that my computer ends up _completely_ unusable throughout the duration of the lag.

List of things that cause this extreme lag:
The stage of opening the game before the loading screen occurs.
Going fullscreen.
Changing GUI scale.

There are plenty more but I won't be bothering to list them for the time being.

Logs/Screenshots:
----------------------------
[MultiMC Log](https://pastebin.com/z01DehXh)
[Forge Log](https://pastebin.com/HvWngv0Q)

Additional Info:
---------------------------
This problem only occurs when MultiMC and Optifine are present if one or the other is missing the problem isn't there.
I've reinstalled Windows, Java and MultiMC but to no avail.
This problem exists pre and post creators update.
This problem does NOT occur in OptiFine_1.9.4_HD_U_B6 and **EVERY** version below.
This problem DOES occur in OptiFine_1.9.4_HD_U_D7 and **EVERY** version above.
By every, I mean transcending through Minecraft and Optifine versions.
So it seems pre-cease and desist Optifine works just fine while post cease and desist Optifine does not work.
I do not have the specific version of where this problem started happening since sp614x had to remove all of the old Optifine versions such as 1.9.4 Ultra B6 from his website from the aforementioned cease and desist.

I'm sure the response I'm going to get is "Go complain to Optifine." and "Go complain to MultiMC." from both sides but here it is. I hope you're able to approach sp614x so you can work this out assuming you even need to collaborate to fix this issue.

I'm not even really sure how MultiMCs/Optifines existence is causing this but it sure is frustrating.

**Comment by QuImUfu** [comment]
So this does not happen with the vanilla launcher?
I can not reproduce this on Linux or Windows 10. However with different and much older machines.
You can download most OptiFine versions from one or more of these sites:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286605-b1-4-1-9-optifine-history or http://optifine.net/downloads or https://web.archive.org/web/20160316133001/https://optifine.net/downloads

I do not think this changes anything, but you could try switching to the MultiMC development update channel and see if the problem persists.
Have you tried switching to an older driver version?
Have you reported the issue to @sp614x anywhere?

**Comment by Gummin** [comment]
Vanilla launcher behaves as expected, no hitches or crippling slowdowns.
I have not tried the dev versions, so I'll try and figure out how to do that sometime.
I have not tried downgrading any drivers.
I have not yet reported this to sp614 since I've been very sick and have not had the will to continue what I've been doing here until now so I'll try to get that done sometime soon™.

Seems the Optifine versions I was testing weren't actually removed in the mass removal like I thought.
I'll look into them a bit more when I have the time.
Thanks for all the download links, will be really helpful.

Sorry for the rushed and delayed everything, I've been very sick and generally exhausted the past week and even now I'm still recovering but I'll keep working on this when I'm able.

**Comment by peterix** [comment]
Hm. That really looks like a graphics driver problem. Maybe NVidia is the right place to complain, but I'm not sure what sort of effect would that have.

So, any news?

**Comment by Gummin** [comment]
Yes, I was going to mention but kept getting sidetracked, it does sound like a graphics driver issue.
I'll get off my ass and do some downgrading today.

**Comment by Gummin** [comment]
Completely forgot about this, but they finally found the issue (it started affecting the popular video player MPC-HC) and it was fixed in 391.24 WHQL
