### ISSUE TITLE
Java 9 compatibility is not there

### ISSUE THREAD

**Issue by Zavesh** [MultiMC/MultiMC5#1997]
System Information
Windows 10 - 64 bit: 16gb ram

MultiMC version: 0.5.0-945

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Whenever I try to launch... even in a fresh instance, it will give me the code and issue labeled in the log.

What should happen:
------------------------------
It should load without this issue

https://paste.ee/p/FRoih

**Comment by flcmc** [comment]
Java 9 is not compatible with MultiMC and won't be for a long time.

**Comment by Zavesh** [comment]
ty!

**Comment by peterix** [comment]
Well, it can't get any better. I'll have to bundle Java 8 and strongly discourage using anything else.
