### ISSUE TITLE
Maybe Java issue, need help

### ISSUE THREAD

**Issue by Satuno** [MultiMC/MultiMC5#2003]
System Information
-----------------------------
MultiMC version: 0.5.0-945

Operating System: Windows 10

Summary of the issue or suggestion: Minecraft does not startup
----------------------------------------------

What should happen: It should open Minecraft
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a Minecraft Instance

2. Try to open it

3. It will show the red X

Suspected cause:
---------------------------

Logs/Screenshots: https://paste.ee/p/4xSc8 , https://www.pic-upload.de/view-33991686/Unbenannt.png.html

----------------------------

Additional Info: I tried Java 8 and 9. None of them are working...
---------------------------

**Comment by peterix** [comment]
Yes. Use java 8, not java 9.

**Comment by Satuno** [comment]
Like i said i uninstalled both, and tried both.. same error

**Comment by peterix** [comment]
The log is from failing java 9. Java 9 will never work with current modded minecraft. It cannot.

So, start over with just java 8 and post a new log.

**Comment by Joly0** [comment]
Btw Java 9 does work with the normal Mc Launcher and also modded Minecraft. Its the Libraries in Multimc that make it unable to start Multimc with Java 9. Normal launcher does not have them in that way

**Comment by peterix** [comment]
AFAIK, it does not work for anything other than pure vanilla. Current modded Minecraft + Java 9 will never work, it is impossible.

The dev version of MultiMC contains the necessary changes on MMC side... it probably breaks things for the few people who use unicode paths on Windows, but that's a long term unfixed Java bug... Sadly, I can no longer work around it with Java 9 being what it is...

**Comment by peterix** [comment]
Nothing to add here, do not use Java > 8.
