### ISSUE TITLE
Suggestion - expand external tools

### ISSUE THREAD

**Issue by xannor** [MultiMC/MultiMC5#2009]
I have just started using this to maintain my custom pack and server. I switched because the curse/twitch client has made minecraft a 3rd class citizen and I am tired of its neglect and issues. There are two tools I use in tandem with multimc that seem to work well for my needs. I use freefilesync to sync my multimc instance and my server instance mod lists. I also just started using openminemods to update my mods, finally removing any need for the twitch client.

What I would like to see is the external tools expanded to add file sync and mod updater options, so they could be launched by instance or from somewhere in the ui. 

The only other suggestion would be a virtual instance so I could map my server folder and possibly use some of the multimc features with it (as far as mod and config management goes.)

**Comment by peterix** [comment]
OK. This issue needs to be split into separate ones for all those ideas presented here.
