### ISSUE TITLE
MultiMC.exe trojan?(Kaspersky)

### ISSUE THREAD

**Issue by filip3712** [MultiMC/MultiMC5#2011]
System Information
-----------------------------
MultiMC version: Latest Develop
Operating System:W10 Pro
Summary of the issue or suggestion: Kaspersky antivirus saying "MultiMC.exe" is Trojan(WTF?)
----------------------------------------------
Logs/Screenshots:
----------------------------
screenShu: http://scr.hu/2i3i/877pe
Zippyshare.com: http://www99.zippyshare.com/v/jj90ODig/file.html
Additional Info:
I see this first time, what happend?
---------------------------

**Comment by peterix** [comment]
A fine example of antivirus being useless and harmful.

**Comment by peterix** [comment]
https://www.virustotal.com/#/url/5e2965b5d96bc5cd637c6a365e970da02c9c9883780a6ab55f93694fd3e92671/detection
https://www.virustotal.com/#/url/acfc11e66e2d74b7fee61089fceb377bc4ab5dc7e27455cfe667b889d81b1b76/detection

**Comment by peterix** [comment]
Just make sure you got it from the official website and not some random other source.

**Comment by filip3712** [comment]
Yes, i'm always downloading MutliMC from official site "multimc.org"
Now i'm using ESET Nod32 Antivirus and everything is ok

Thanks for help :)
