### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by julioplayz** [MultiMC/MultiMC5#2016]
System Information
-----------------------------
MultiMC version: 0.5.0-908

Operating System: OSX El Capitan

Summary of the issue or suggestion: 
----------------------------------------------
Crashing while loading MC

What should happen:
------------------------------
It should load perfectly

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add the "Flat colored blocks", "Chisels and Bits" "MrCrayfish Furniture mod" and "Optifine" for 1.12

2. Run

3.

Suspected cause:
---------------------------
A mod perhaps

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/mcafo

Additional Info:
---------------------------

**Comment by Leomelonseeds** [comment]
Try removing Chisels and Bits

**Comment by peterix** [comment]
No response, closing.
