### ISSUE TITLE
[IDEA] Instance Shortcuts

### ISSUE THREAD

**Issue by julioplayz** [MultiMC/MultiMC5#2018]
I have an idea, what if you could add instance shortcuts to your desktop or taskbar, that way you can quick open an instance without having to open multimc first!

**Comment by QuImUfu** [comment]
Already possible. 

Make a link to MultiMC with the command line parameter :
```
-l, --launch <launch> launch the specified instance (by instance ID)
```
instance id is the name of the instance folder.
Linux example:
/home/bambus/MultiMC/MultiMC -l "Better Than Wolves"
Windows example (not tested):
C:\\Users\bambus\MultiMC.exe -l "Better Than Wolves"

It was already suggested to add a way to do that from MultiMC, it is on workflowy: https://workflowy.com/s/2EyDMcp7CU#
