### ISSUE TITLE
Add back hide/close on launch.

### ISSUE THREAD

**Issue by ReiDaTecnologia** [MultiMC/MultiMC5#2020]
I remember i can do this before but now i can't, this feature was removed?

**Comment by peterix** [comment]
Hmm... you can just close it and it will be effectively hidden. But OK.

**Comment by link00000000** [comment]
As a workaround for the time being I made two very small AutoHotkey scripts to do this. Just point the pre-launch and post-launch commands located at Edit Instance > Settings > Custom Commands to the binaries.

[HideMultiMC.exe](https://drive.google.com/file/d/1jl4i8oaV2XNCfFNfhuQYAl_M2vwrZ-0q/view?usp=sharing)
[ShowMultiMC.exe](https://drive.google.com/open?id=1z96dgVSWURAHlYySo3Qh1XK67pDTEMj-)

If you feel uncomfortable downloading random binaries from some guy on the internet (which you should), the source is available in [this gist](https://gist.github.com/link00000000/a11d77ab9749744f9245b6f552ff5996).

**Comment by ReiDaTecnologia** [comment]
I think your guys didn't understood what i said at that time (maybe because of my bad english xD) but what i meant is:
Launch a modpack>Main MultiMC gui (With the instances and stuff) hide and the console gui opens.
Close a modpack: Main MultiMC gui comeback.

iirc multimc also appears in the system tray but i could be wrong mainly because i forgot totally about this issue xD
