### ISSUE TITLE
AL lib: (EE) alc_cleanup: 1 -  Process exited with code -1

### ISSUE THREAD

**Issue by Lart-Iste** [MultiMC/MultiMC5#2021]
System Information
-----------------------------
MultiMC version: 5.0-945

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------

After creating an instance with forge, during loading or connecting to the server the game crash, always with the same error...

What should happen:
------------------------------

Game start, loading, play

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Use AL lib (I'm not sure)

2. Launch an instance

3. during the loading of the modded game or by joining a server with forge

Suspected cause:
---------------------------

Any idea

Logs/Screenshots:
----------------------------

[Minecraft Log](https://paste.ee/p/lSLPO)

Additional Info:
---------------------------

**Comment by ReiDaTecnologia** [comment]
**AL lib: (EE) alc_cleanup: 1** - This message is nothing, ignore it.
**Process exited with code -1** - This is how the instance/process have closed. ("0" Normal close. "-1" Crash/Error)

Looking in the log i found the real problem: 
**java.lang.NoSuchMethodError: net.minecraft.profiler.Profiler.startSection(Ljava/lang/Class;)V**
You have optifine right? making a simple search i found one interesting thing. Optifine are having some problems with latest Forge version, so one solutions is downgrade the version to 2228, [See](http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/mods-discussion/2819448-ticking-block-entity-java-lang-nosuchmethoderror).

**Comment by Lart-Iste** [comment]
Problem solved, you are awesome, a million of thanks !
