### ISSUE TITLE
MultiMC crash during play after loading, max 2 min of gameplay before crash

### ISSUE THREAD

**Issue by manofhonor1012** [MultiMC/MultiMC5#2025]
System Information
-----------------------------
MultiMC version: Version 0.5.0-945

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
I downloaded MultiMC and created a Vanilla instance of MC 1.10.2. I made sure it loaded properly, and then I copied that instance and created an instance for modding. All mods are for that version of MC and loaded properly, allowing me to play for a couple minutes before crashing. I tried 3 times, and I crashed after about 2 minutes of gameplay each time.

What should happen:
------------------------------
I should be able to play my mods without issue

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Have MC 1.10.2 instance on Multi MC

2. Have the 1.10.2 versions of the following mods:
Baubles
CodeChickenCore
CodeChickenLib
Just Enough Items
Mantle
Not Enough Items
Optifine
Botania
Blood Magic
Guide Api
Minecraft Forge and its addons

3. Run the instance and play

Suspected cause:
---------------------------
I wish I could put something here, but I'm not well versed in this stuff

Logs/Screenshots:
----------------------------
https://paste.ee/p/SKDmg

**Comment by peterix** [comment]
1. Please use 64bit java, the long even says you should, right at the top.
2. You will have to give Minecraft a bit more memory than the default 512 - 1024M. That's fine for vanilla, but adding more to the game leads to it needing more.
