### ISSUE TITLE
Launching MultiMC (on fresh Ubuntu 17.10 installation) sends me into an infinite loop of my screens turning on and off

### ISSUE THREAD

**Issue by Trophonix** [MultiMC/MultiMC5#2027]
System Information
-----------------------------
MultiMC version: Whatever version is the one available on [the site](https://multimc.org/#Download) as a debian pacakage.

Operating System: Ubuntu 17.10

Summary of the issue or suggestion:
----------------------------------------------
I installed Multi-MC because the official Minecraft launcher is [currently having Linux issues of their own](https://bugs.mojang.com/browse/MC-121292), and everything seemed fine at first. I opened it up and set up a vanilla 1.8.9 instance and a forge+liteloader 1.8.9 instance, moved in my mods, and the game started up fine. Then, I closed it and went and worked on something else for a bit, came back and re-opened MultiMC, and that's when the issue occurred.

I don't know exactly what's happening. Maybe it's crashing my graphics drivers which is sending them into a loop of restarting and crashing? 

So anyway, I tried deleting the multimc files in ~/.local/share/ and uninstalling then reinstalling the launcher, and the problem continued. I'm not 100% sure if this is a bug in MultiMC or if it's just me, but I'd really like to be able to use MultiMC, and plus if it is a bug I don't want to just leave it and maybe result in a bug not getting fixed soo... yeah.

What should happen:
------------------------------
The launcher should open

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install MultiMC to a Ubuntu 17.10 instance via the .deb package on the website

2. Run it

3. Close and re-run it

Suspected cause:
---------------------------
I honestly don't know. I didn't install any new things or change anything after the successful first launch.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
It sounds like those instructions for uploading requires being able to open the launcher, so I manually uploaded MultiMC-2.log to paste.ee.

https://paste.ee/p/a3uqj

Additional Info:
---------------------------
I'm running the latest JDK/JRE installed with `apt install openjdk-8-jdk`
Graphics driver version is 384.90, installed with `apt install nvidia-384`

**Comment by peterix** [comment]
Sounds like something really, really crazy going on... probably somewhere between Xorg, Qt, your graphics driver and the window manager. MultiMC itself does nothing with screens.

As a possible (I am simply guessing here) workaround, you could try removing all the bundled dependencies and let MultiMC use your system's libraries instead. These can be removed:
![image](https://user-images.githubusercontent.com/203326/32043874-40192fc4-ba3c-11e7-999b-1ee83c2739fa.png)

Make sure you have Qt5 and its Svg library installed as system packages though.

**Comment by peterix** [comment]
The launcher files - including the binaries - should all be in `~/.local/share/multimc/`.

**Comment by peterix** [comment]
Well, I assume this got fixed at some point. Also, ancient ubuntu is obsolete.
