### ISSUE TITLE
whenever I launch my mod file it says the window size then stops launching

### ISSUE THREAD

**Issue by Coroth2112** [MultiMC/MultiMC5#2028]
System Information
-----------------------------
MultiMC version: 0.5.2

Operating System: Windows?

Summary of the issue or suggestion:
----------------------------------------------
whenever I launch my mod file it says the window size then stops launching

What should happen:
------------------------------
it should launch normaly

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. wat is

2. this

3. question

Suspected cause:
---------------------------
idk

Logs/Screenshots:
----------------------------
MultiMC version: 0.5.2-1096

Minecraft folder is:
instances/1.7.10 mod test backup/minecraft

Java path is:
C:/programdata/oracle/java/javapath/java.exe

Java is version 1.8.0_144, using 32-bit architecture.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  D:/Games/MINECRAFT/MultiMC/instances/1.7.10 mod test backup/natives

Libraries:
  D:/Games/MINECRAFT/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  D:/Games/MINECRAFT/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  D:/Games/MINECRAFT/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  D:/Games/MINECRAFT/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  D:/Games/MINECRAFT/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  D:/Games/MINECRAFT/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  D:/Games/MINECRAFT/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  D:/Games/MINECRAFT/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  D:/Games/MINECRAFT/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  D:/Games/MINECRAFT/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  D:/Games/MINECRAFT/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  D:/Games/MINECRAFT/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  D:/Games/MINECRAFT/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  D:/Games/MINECRAFT/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  D:/Games/MINECRAFT/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  D:/Games/MINECRAFT/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  D:/Games/MINECRAFT/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  D:/Games/MINECRAFT/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  D:/Games/MINECRAFT/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  D:/Games/MINECRAFT/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  D:/Games/MINECRAFT/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  D:/Games/MINECRAFT/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  D:/Games/MINECRAFT/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  D:/Games/MINECRAFT/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  D:/Games/MINECRAFT/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  D:/Games/MINECRAFT/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  D:/Games/MINECRAFT/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  D:/Games/MINECRAFT/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  D:/Games/MINECRAFT/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  D:/Games/MINECRAFT/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
  D:/Games/MINECRAFT/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  D:/Games/MINECRAFT/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  D:/Games/MINECRAFT/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  D:/Games/MINECRAFT/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  D:/Games/MINECRAFT/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  D:/Games/MINECRAFT/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  D:/Games/MINECRAFT/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  D:/Games/MINECRAFT/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  D:/Games/MINECRAFT/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  D:/Games/MINECRAFT/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  D:/Games/MINECRAFT/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  D:/Games/MINECRAFT/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  D:/Games/MINECRAFT/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  D:/Games/MINECRAFT/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  D:/Games/MINECRAFT/MultiMC/libraries/com/mumfrey/liteloader/1.7.10_04/liteloader-1.7.10_04.jar
  D:/Games/MINECRAFT/MultiMC/versions/1.7.10/1.7.10.jar
  D:/Games/MINECRAFT/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  D:/Games/MINECRAFT/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-windows.jar
  D:/Games/MINECRAFT/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-32.jar
  D:/Games/MINECRAFT/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-32.jar

Mods:
  1.7.10-MB_Battlegear2-Bullseye-1.0.8.0
  backpack-2.0.1-1.7.x
  Better HUD by NukeDuck [1.7.10][1.1a]
  CubeWorldV3.1BF (Minecraft V1.7.10)
  DynamicLights-1.7.10
  farlanders-1.7.10-v1.2b
  Forge-1.7.10-installer
  GalacticraftCore-1.7-3.0.8.262
  Galacticraft-Planets-1.7-3.0.8.262
  malisiscore-1.7.10-0.14.0
  malisisdoors-1.7.10-1.13.2
  Mantle-Mod-1.7.10
  MCA-4.1.2 MC-1.7.10
  MicdoodleCore-1.7-3.0.8.262
  mod_XrayV2.01
  MoVillages-1.2.0.jar
  MrCrayfishFurnitureModv3.3.5(1.7.10)
  RadixCore-1.3.1 MC-1.7.x
  Rediscovered-1.7.10-1.1
  RedstonePasteMod-1.7.10-1.6.2 (1)
  TConstruct-Mod-1.7.10
  Tinkers-Mechworks-Mod-1.7.10
  ToggleBlocks-1.1.0-1.7.2-10

Params:
  --username  --version MultiMC5 --gameDir D:/Games/MINECRAFT/MultiMC/instances/1.7.10 mod test backup/minecraft --assetsDir D:/Games/MINECRAFT/MultiMC/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType  --tweakClass cpw.mods.fml.common.launcher.FMLTweaker --tweakClass com.mumfrey.liteloader.launch.LiteLoaderTweaker

Window size: 854 x 480

Additional Info:
---------------------------

**Comment by v0idst4r** [comment]
Please provide more information. At least logs.

**Comment by peterix** [comment]
Well, there's a log. But we might need the MultiMC log, not the Minecraft one...

What if you switch to the develop version?
See: https://github.com/MultiMC/MultiMC5/wiki/Switching-update-channels
