### ISSUE TITLE
Minecraft Instance Crashed within 3 to 4 minutes of play

### ISSUE THREAD

**Issue by Razgriz700** [MultiMC/MultiMC5#2030]
System Information
-----------------------------
MultiMC version: 0.6.0-develop-1098

Operating System: Windows 10 64bit

Summary of the issue or suggestion:
----------------------------------------------
Would begin to play within my world and then Minecraft will completely crash. I've been playing for the past couple of days without a problem yet now it all of sudden happened.

What should happen:
------------------------------
Be able to play normally like I have the past several days.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Load Minecraft Allthemods for 1.10

2. Make sure all mods are up to date

3. Remove Diet Hopper

Suspected cause:
---------------------------
Possibly a java crash.
I used to have problems with diet hopper but I have fixed that by removing diet hopper mod.

Logs/Screenshots:
----------------------------
https://paste.ee/p/jMAns

Additional Info:
---------------------------
I'm in the process of learning how to read the error reports and overall the minecraft console. I would like any tips for understand crash reports better.

**Comment by peterix** [comment]
Some sort of renderer error caused by mods? The class it crashed in is part of vanilla though.

```
java.lang.NullPointerException: Batching chunks
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:94)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:60)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:199)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Razgriz700** [comment]
I'm going over the list of mods I had began using in world on my last backup prior to this crash to see if I can narrow down which mod it would be though, all I had done was finish my house and began to start setting up a power gen farm from using tree oil (thermal expansion).
