### ISSUE TITLE
Minecraft not responding and invisible to computer?

### ISSUE THREAD

**Issue by sonicwaffles** [MultiMC/MultiMC5#2031]
System Information
-----------------------------
MultiMC version: MultiMc5 version 0.6.0-develop-1043

Operating System: Mac OS 10.12.6

Summary of the issue or suggestion:
----------------------------------------------

Whenever I launch an instance (vanilla or modded) minecraft opens but I cannot interact with it in any way. Cannot click any menu options and the only way to close is to kill the instance through MultiMC. The minecraft icon in the dock also no longer appears and it is not listed in the 'force quit' menu.

What should happen:
------------------------------

Should be able to interact with minecraft and have the computer register it is open?

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. 

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

https://paste.ee/p/8SPDn

https://ibb.co/gPQk5m
a screenshot showing the computer not registering minecraft is open.

Additional Info:
---------------------------

**Comment by QuImUfu** [comment]
does this also happen with the vanilla launcher?
Is it possible to alt-tab into minecraft?

**Comment by peterix** [comment]
Fixed. See #2026 - it is related.
