### ISSUE TITLE
Can't download latest Forge.

### ISSUE THREAD

**Issue by Blatts12** [MultiMC/MultiMC5#2032]
**System Information:**
-----------------------------
MultiMC version: 0.6.0-develop-1099

Operating System: Windows 10

**Summary of the issue or suggestion:**
----------------------------------------------
Can't download latest forge version.
It don't appear on a list.

**What should happen:**
------------------------------
Latest version of Forge appears on the list.

**Steps to reproduce the issue (Add more if needed):**
-------------------------------------------------------------
1.Try to download latest forge...

**Suspected cause:**
---------------------------
https://i.imgur.com/PQeMcwb.png
tbh I don't know.

**Logs/Screenshots:**
----------------------------
https://i.imgur.com/dQvxdpl.png

https://i.imgur.com/KpvxJoK.png

**Comment by peterix** [comment]
Working on it. No ETA.

**Comment by ClaudiusMinimus** [comment]
Same issue for Version 0.6.0-develop-1019
Platform: lin64

**Comment by peterix** [comment]
Should be fixed now.
