### ISSUE TITLE
[Suggestion] Personalize our paths

### ISSUE THREAD

**Issue by korey03** [MultiMC/MultiMC5#2034]
System Information
-----------------------------
MultiMC version: 0.5.2-1096

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Personalize our paths for Resources Packs, Worlds, Screenshots

What should happen:
------------------------------
For example I have 3 profiles with the same minecraft version and I want the same Resources Packs on each one. Instead of copying the same resources packs 3 times I have a custom path on the 3 profiles who regoups my 1.8.9 resources packs. Personally I hate logs so I would to use my Windows variable %tmp% for it.

I don't know if the game restricted that.

**Comment by peterix** [comment]
This idea has been floating around for a long time... and I can only say thatt the game doesn't really support tthis sort of partial overlap between instances.
You can either smash things together completely, or not at all.
There are some workarounds, like using symlinks, but on Windows, using that requires admin rights:
https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

If Windows fully supported symlinks, this would be a lot simpler.
