### ISSUE TITLE
Client crashes when joining server

### ISSUE THREAD

**Issue by TrueeMu** [MultiMC/MultiMC5#2035]
System Information
-----------------------------
MultiMC version: 5 - 0.5.2 

Operating System: Windows 7

Summary of the issue or suggestion:
----------------------------------------------
I joined a server, after joining I was teleported out then the game crashed, I was teleported back to spawn and was able to explore for about 10 minutes before it crashed again. I deleted the modpack and re-installed it, and had my player data deleted and was able to join and play just fine for about 15 minutes before I began to crash again. Tested in single player with no issues whatsoever (run the game around 120 fps on average, dips to about 90 in rain/forests). We are pretty certain it is not a server-wide issue because there are around 10-15 other people who play on the server with no problems.

What should happen:
------------------------------
I should just be able to join and play normally.

Suspected cause:
---------------------------
No clue

Logs/Screenshots:
----------------------------
https://paste.ee/p/9U9F9

Additional Info:
---------------------------
I've uninstalled/reinstalled multimc and the modpack and deleted my player data to no avail. No one else on the server has this problem, and singleplayer runs perfectly fine 

Computer Specs (Just in case) : 
---------------------------
Intel i7 4700
nVidia GTX 750 Ti
8gb ddr3 ram
1tb hdd
etc etc

**Comment by peterix** [comment]
```
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000002b3f2d77, pid=13112, tid=0x0000000000002df4
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ig75icd64.dll+0x472d77]
```
That's an **Intel** graphics driver crash.

What is in this file?
`C:\Users\Will\Downloads\mmc-stable-win32\MultiMC\instances\BridgetBethardy-1.7.10-1.2.2\minecraft\hs_err_pid13112.log`

**Comment by TrueeMu** [comment]
https://paste.ee/p/Z9oau

**Comment by peterix** [comment]
I don't understand why would you use both the intel and nvidia driver at the same time... that's just weird. Is this some dual graphics laptop?

**Comment by TrueeMu** [comment]
It's a 2013-2014 Alienware M14x so it is a laptop, not sure if it runs dual graphics, I have another computer that's running amd with a 6670 I think.

**Comment by TrueeMu** [comment]
*6870 mb

**Comment by TrueeMu** [comment]
Alright from looking it up, I need to set the 750 as my default gpu, optimus sets intel graphics as default gpu from the factory. I'll try that.

**Comment by peterix** [comment]
Actually using the 750ti is your best bet.

**Comment by TrueeMu** [comment]
Yeah that's what I was saying, by default it seems to not set the 750ti as my default gpu. I'm messing with it and trying to get it to work.

**Comment by TrueeMu** [comment]
Aha! I set the 750ti as my default gpu and it seems to be working so far. Appreciate the help.
