### ISSUE TITLE
have problem run multimc on windows 7 professional 

### ISSUE THREAD

**Issue by kideocash** [MultiMC/MultiMC5#2040]
System Information
-----------------------------
MultiMC version:

Operating System: windows 7.0 professional

Summary of the issue or suggestion:
----------------------------------------------
multimc will not run

What should happen:
-----------------------------
it worked before until i updated to new version now does not work under windows 7 
i do not see a way to get the old version 
 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.  tried run it sereral times did not work 

2. i then tried it on library computer using windows 10 it worked

3. i then tried run it on windows 7 computer at library - it detected something wrong with the file and
  deleted it - it think it was a virus checker that they use there that did it

Suspected cause:
---------------------------
I think mcmulti  is somehow a windows 10 installer program now that does not work 
for other windows computer like winodws 7 and below 

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	MultiMC.exe
  Application Version:	1.0.0.0
  Application Timestamp:	01b3e2a8
  Fault Module Name:	MultiMC.exe
  Fault Module Version:	1.0.0.0
  Fault Module Timestamp:	01b3e2a8
  Exception Code:	c0000005
  Exception Offset:	000a83a7
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
![multimc error](https://user-images.githubusercontent.com/33734443/32915824-d10c3176-cadf-11e7-92d3-db4966d17d67.jpg)

**Comment by peterix** [comment]
Show me the MultiMC log file -- `MultiMC.0.log` is always the latest one. Hopefully it will point out at which point it crashed.

You could also try the dev version: https://files.multimc.org/downloads/mmc-develop-win32.zip

**Comment by peterix** [comment]
See: #2055 - probably the same problem.

**Comment by peterix** [comment]
And then nothing was said for a year. OK.
