### ISSUE TITLE
Possible bug or poor internet?

### ISSUE THREAD

**Issue by Markfoix** [MultiMC/MultiMC5#2042]
System Information
-----------------------------
MultiMC version: current release

Operating System: Dell Windows 7 Ultimate

Summary of the issue or suggestion:
----------------------------------------------
All maps of 1-player games log out within 45 seconds of logging in. In all maps I am not using any internet due to no internet available

What should happen: game logs out within 45 seconds
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. No internet connection and run MultiMC

2. Start any version of Minecraft either 1.10.0 or higher with either mods or no mods

3. Run a single player map

Suspected cause: poor internet connection and/or bug in upgraded release

**Comment by QuImUfu** [comment]
can you post a minecraft log?

**Comment by Markfoix** [comment]
It turns out my 1 player maps have fixed themselves. I also had the same issue for multiplayer one of which is fixed. I will upload my log for the issue within the next 2 hours.

**Comment by Markfoix** [comment]
https://pastebin.com/Hwp37VBe is the link for the log.

**Comment by zjjpp** [comment]
if this is resolved please close it @Markfoix :)

**Comment by Markfoix** [comment]
It is fixed for all my 1-player worlds however same issue resides in a multiplayer game and I can not pinpoint the location besides my internet which does not makes sense as all multiplayer games would be affected but it is just the one.

If you could help that would be great otherwise I will stop playing on that server til who knows when if ever. Everything is up-to-date on my end besides something in the computer that I can not identify.

**Comment by Markfoix** [comment]
Here is a picture of the error message I get when joining a server. It is the only server that is giving me issues. It is Minecraft version 1.12.2 where the one that is fine is 1.7.10.

https://drive.google.com/file/d/1I_07EU4QVieysh6JmNuNB8b67q4U7ouK/view?usp=drivesdk

**Comment by QuImUfu** [comment]
this seems to be (probably) the severs fault. What sever are you trying to connect to? Does the same server work with a different version of MC? Maybe the server is not updated properly to 1.12.2.

**Comment by Markfoix** [comment]
As far as I know, I am the only one having this issue and I am the only one using MultiMC plus using phone internet to connect.

If it was server based, would more people be affected at a time?

**Comment by QuImUfu** [comment]
https://bugs.mojang.com/browse/MC-38565
seems to describe pretty much the same problem and concludes that this error happens because of an vanilla minecraft bug that seemingly randomly affects some players with some versions of Minecraft.
Some people think it has someting to do with network issues, so you using phone internet could be the reason why it only affects you.

**Comment by Markfoix** [comment]
Okay, thank you for confirming that. If internet is to blame on that, how would single player worlds be affected?

To prevent or solve this in the future?

**Comment by QuImUfu** [comment]
Those are questions i can't answer. :D
Maybe Mojang will fix it in a future release, apart from that, no idea.

**Comment by Markfoix** [comment]
Okay, thank you for the help.
