### ISSUE TITLE
Feature Request - Persistent collapsed instance groups

### ISSUE THREAD

**Issue by asliceofkate** [MultiMC/MultiMC5#2043]
I wold really _really_ love it if MultiMC remembered which instance groups I had minimized the next time I launch the program.

**Comment by ask6155** [comment]
It's really useful only if you have a 'crapton' of instances.

**Comment by Heufneutje** [comment]
Not really. I only have about 8 of them but some of their are old modded instances I want to keep around, but not launch on a regular basis.

**Comment by peterix** [comment]
See:
https://github.com/MultiMC/MultiMC5/issues/851
https://workflowy.com/s/2EyDMcp7CU#/083be7fb521d

**Comment by peterix** [comment]
Duplicate of #851
