### ISSUE TITLE
Minecraft freezes and doesn't come back

### ISSUE THREAD

**Issue by randombobawesome** [MultiMC/MultiMC5#2046]
System Information
-----------------------------
MultiMC version:0.52

Operating System: Ubuntu 17.10

Summary of the issue or suggestion:
----------------------------------------------
Minecraft Freezes 

What should happen:
------------------------------
it should be fixed

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.start minecraft

2.open any world

3. wait

Suspected cause:
---------------------------
 multimc because atlauncher works fine

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
... you might want to include some more information than this.

**Comment by randombobawesome** [comment]
like what

**Comment by peterix** [comment]
like, anything.

a log would be a good start

**Comment by randombobawesome** [comment]
[2017-11-22-1.log.gz](https://github.com/MultiMC/MultiMC5/files/1497324/2017-11-22-1.log.gz)
is that better

**Comment by peterix** [comment]
Well, it's something, but doesn't show anything that could help idenifying the problem.

There are some errors, but it seems these are from it loading some invalid stuff:
```
[12:02:32] [Thread-3/ERROR]: Error in class 'CodecJOrbis'
[12:02:32] [Thread-3/ERROR]: Ogg header not recognized in method 'readHeader'.
[12:02:32] [Thread-3/ERROR]: Error in class 'CodecJOrbis'
[12:02:32] [Thread-3/ERROR]: Error reading the header
```

Maybe that's just a corrupted file... Try deleting the assets folder and let it redownload?

But, I am looking for the actual log, not this. This is some tiny fragment Minecraft writes in its folders and is far from useful.

This is what I'm looking for:
![image](https://user-images.githubusercontent.com/203326/33147688-f78de5a4-cfc8-11e7-85bb-e9886bab1a0b.png)

**Comment by peterix** [comment]
Handled on discord.
