### ISSUE TITLE
Minecraft doesn't launch

### ISSUE THREAD

**Issue by TheBlueKingLP** [MultiMC/MultiMC5#2047]
System Information
-----------------------------
MultiMC version: 0.9.0-945

Operating System: Windows 10

Summary of the issue or suggestion: After I clicked launch, Minecraft doesn't appear
----------------------------------------------

What should happen: Minecraft appears
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
unknown

Suspected cause: unknown
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://i.imgur.com/wUMAjTq.png

Additional Info: No crash report or error
---------------------------

**Comment by QuImUfu** [comment]
Could you post the whole log in the window you took a screenshot of? 
Preferably formatted as "code"( \<\> button in the editor).

**Comment by TheBlueKingLP** [comment]
`MultiMC version: 0.5.0-945


Minecraft folder is:
instances/1.12/minecraft


Java path is:
C:/Program Files/Java/jre1.8.0_144/bin/javaw.exe


Java is version 1.8.0_144, using 64-bit architecture.


Main Class:
  net.minecraft.client.main.Main

Native path:
  O:/MultiMC.app/Contents/MacOS/instances/1.12/natives

Libraries:
  O:/MultiMC.app/Contents/MacOS/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  O:/MultiMC.app/Contents/MacOS/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  O:/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  O:/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  O:/MultiMC.app/Contents/MacOS/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  O:/MultiMC.app/Contents/MacOS/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  O:/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  O:/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  O:/MultiMC.app/Contents/MacOS/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  O:/MultiMC.app/Contents/MacOS/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  O:/MultiMC.app/Contents/MacOS/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  O:/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  O:/MultiMC.app/Contents/MacOS/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  O:/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  O:/MultiMC.app/Contents/MacOS/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  O:/MultiMC.app/Contents/MacOS/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  O:/MultiMC.app/Contents/MacOS/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  O:/MultiMC.app/Contents/MacOS/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  O:/MultiMC.app/Contents/MacOS/libraries/com/mojang/realms/1.10.17/realms-1.10.17.jar
  O:/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  O:/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  O:/MultiMC.app/Contents/MacOS/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  O:/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  O:/MultiMC.app/Contents/MacOS/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  O:/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  O:/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  O:/MultiMC.app/Contents/MacOS/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  O:/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  O:/MultiMC.app/Contents/MacOS/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  O:/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  O:/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  O:/MultiMC.app/Contents/MacOS/versions/1.12/1.12.jar
  O:/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  O:/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir O:/MultiMC.app/Contents/MacOS/instances/1.12/minecraft --assetsDir O:/MultiMC.app/Contents/MacOS/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480`
- End Of Log -

**Comment by Proximyst** [comment]
Download the Windows version, not Mac..
https://files.multimc.org/downloads/mmc-stable-win32.zip

**Comment by gellatio** [comment]
Ignore Proxi. She's gay

**Comment by peterix** [comment]
And try to use it without mixing it together with the mac version first.

Btw, did this ever work?

**Comment by gellatio** [comment]
SPONSORED CONTENT
[Watch] What Are You Forgetting?
BY SAMSUNG
Origin
On July 29th, 2017, Redditor Niekish submitted the earliest known variation of the copypasta in the comments section of a post on /r/CringeAnarchy:[1]

To be fair, you have to have a very high IQ to understand Rick and Morty. The humour is extremely subtle, and without a solid grasp of theoretical physics most of the jokes will go over a typical viewer’s head. There’s also Rick’s nihilistic outlook, which is deftly woven into his characterisation- his personal philosophy draws heavily from Narodnaya Volya literature, for instance. The fans understand this stuff; they have the intellectual capacity to truly appreciate the depths of these jokes, to realise that they’re not just funny- they say something deep about LIFE. As a consequence people who dislike Rick & Morty truly ARE idiots- of course they wouldn’t appreciate, for instance, the humour in Rick’s existential catchphrase “Wubba Lubba Dub Dub,” which itself is a cryptic reference to Turgenev’s Russian epic Fathers and Sons. I’m smirking right now just imagining one of those addlepated simpletons scratching their heads in confusion as Dan Harmon’s genius wit unfolds itself on their television screens. What fools.. how I pity them. 😂

And yes, by the way, i DO have a Rick & Morty tattoo. And no, you cannot see it. It’s for the ladies’ eyes only- and even then they have to demonstrate that they’re within 5 IQ points of my own (preferably lower) beforehand. Nothin personnel kid 😎

**Comment by TheBlueKingLP** [comment]
@Proximyst I just unzip Windows version inside my Mac version
@peterix It was working yesterday,but when I try to launch Minecraft today,it wasn't working
@gellatio What are you talking about?

**Comment by peterix** [comment]
So, it suddenly broke. That's interesting.

Does a separate, freshly downloaded version work? The reason for trying that is to rule out any sort of external change that could be causing this.

**Comment by TheBlueKingLP** [comment]
Freshly downloaded version work just fine, I don't think there is any external change.

**Comment by peterix** [comment]
So it's something that happened to that particular copy of MultiMC.

Do other instances work, or does it affect all instances?

**Comment by TheBlueKingLP** [comment]
None of my instances work.

**Comment by TheBlueKingLP** [comment]
and now i can't even click launch,the launcher just crashed

**Comment by peterix** [comment]
Check your system for malware and make sure the O: drive is not dying.

**Comment by peterix** [comment]
btw, what is the O: drive?

**Comment by TheBlueKingLP** [comment]
O drive is my unraid Share

**Comment by TheBlueKingLP** [comment]
if o die,that means i need to replace the bad hdd and rebuild the array

**Comment by peterix** [comment]
It honestly sounds like the data getting corrupted over time, or something breaking the access permissions.

I've seen MultiMC crash on start like that when it can't write to its folder(s). It *should* pop up an error dialog when the log file can't be created tho... so that's a possible regression.

I've never tested everything on an unreliable system -- the only well tested part that should be hardened against such problems is the update mechanism.

**Comment by TheBlueKingLP** [comment]
I'll try to move my old instants to my new multimc

**Comment by peterix** [comment]
Ideally copy, not move, just to be sure. You can always delete something later :)

**Comment by TheBlueKingLP** [comment]
fixed by copying.
