### ISSUE TITLE
Browsing for folders in settings and hitting cancel changes paths to '.'

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#2050]
System Information
-----------------------------
MultiMC version: stable, dev

Operating System: any

Summary of the issue or suggestion:
----------------------------------------------
Cancelling browse dialogs is accepted as valid input.
Any and all browse (`...`) buttons may be affected. Check them all.

Suspected cause:
---------------------------
Not handling return values of modal dialogs correctly.

**Comment by Dushess** [comment]
Closing the window does the same?

**Comment by peterix** [comment]
Fixed in develop. At least all the cases of this I could find.
