### ISSUE TITLE
Suggestion: Multiplayer Server List Management

### ISSUE THREAD

**Issue by FayneAldan** [MultiMC/MultiMC5#2053]
There should be an option to manage your multiplayer server list on a profile, with the options of importing and exporting as text or nbt (original server list format), plus the option to merge a server list file (text or nbt) into the already existing server list. Optionally, it could also ping the servers in the list for the MOTD and player counts.

**Comment by peterix** [comment]
Sounds like a cool idea. It could also be able to launch and connect to the server directly -- where this option is available.

**Comment by ask6155** [comment]
The instances server list is in the server.dat file right?

**Comment by peterix** [comment]
Indeed.

**Comment by MulverineX** [comment]
This would probably prove helpful https://docs.gameapis.net/docs/mc/query for inside the client

**Comment by peterix** [comment]
That's some third party thing... I would rather do exactly what the game does.

**Comment by peterix** [comment]
This needs to be implemented: http://wiki.vg/Server_List_Ping

**Comment by peterix** [comment]
Another idea: Allow marking one of the servers as 'autoconnect'. If there is such a server, MultiMC would launch the instance with the options necessary for automatically connecting to the selected server.
