### ISSUE TITLE
Failed to start when clicking the exe

### ISSUE THREAD

**Issue by Brum8842** [MultiMC/MultiMC5#2055]
System Information
-----------------------------
MultiMC version: 

Operating System: win 7

Summary of the issue or suggestion:
----------------------------------------------
starting the program, nothing happens, looking at the event viewer  comes up with an error.

What should happen:
------------------------------
starting the program should start it

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------
unknown

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/wQ8vm
https://paste.ee/p/HAg5J

Additional Info:
---------------------------

**Comment by peterix** [comment]
1. These don't belong in there:
```
LoadedModule[3]=C:\Program Files\AVAST Software\Avast\aswhookx.dll
LoadedModule[47]=C:\Program Files (x86)\IObit\Advanced SystemCare\HPProtectNotify32.dll
```

That aside, scan and clean your system with something else like malwarebytes. It seems to have worked for other people with this problem.

If you can tell me what it removes to make it work again, it will help me figure out what is actually going on.

**Comment by Brum8842** [comment]
I don't know why those two programs would get loaded with multimc, that never happened before and I had these two programs for years and still can launch multimc. 

How do i go about stopping multimc from loading those modules in the first place?

I have already scanned my computer with malwarebytes and nothing out of the ordinary pops up.

**Comment by ask6155** [comment]
do a fresh install and start it but
don't delete the original multimc

**Comment by peterix** [comment]
If these were always there, they are probably fine.

Do a scan with malwarebytes, remove anything that looks funny and if it runs after that, get me the report from that scan:

![image](https://user-images.githubusercontent.com/203326/33516315-1f2783f4-d771-11e7-819e-576c0098361a.png)

![image](https://user-images.githubusercontent.com/203326/33516313-12d91a40-d771-11e7-89ea-27ee2408618e.png)

**Comment by Brum8842** [comment]
malwarebytes came back with nothing found https://paste.ee/p/FEnEE

I unzipped a new copy of Multimc and ran that but it still comes up with the appcrash error in the event viewer

**Comment by peterix** [comment]
It IS the 'Advanced SystemCare'. Just tested it on a burner windows VM. Installing that thing makes multimc crash on start.

**Comment by ask6155** [comment]
IT's an IOBIT package
found it

**Comment by Brum8842** [comment]
Why now I've never had any problem with it before?

**Comment by peterix** [comment]
Maybe they broke something with an update?

**Comment by Brum8842** [comment]
so I uninstalled the advance systemcare and reinstalled a previous version and it works now, like you said the newer version v11 did something that causes a crash.

**Comment by Moistopheles** [comment]
By turning off '**Homepage Advisor'** under the protect tab in Advanced system care, I have resolved the issue. I don't know why it interferes with multimc but that's what fixed it for me at least.

**Comment by AusiMods** [comment]
as Moistopheles says disabling homepage adviser resolves the issue. 
Note just disabling notify in the adviser makes no difference the complete module needs to be turned off.

**Comment by peterix** [comment]
Can you guys report it to iobit so they can fix it on their end? Because that's a really weird bug, and I have no way to fix it on my end.

**Comment by AusiMods** [comment]
Already reported but dont let that stop others as this may be a case of the more the merrier :)

**Comment by peterix** [comment]
Definitely. If there's some public view of that report, please link it here.

**Comment by AusiMods** [comment]
Sorry to say no public view available in either bug report area(website) or feedback area(program)
`Our support team will get back to you via email as soon as possible depending on the request quantity (normally within 48 hours).`

**Comment by AusiMods** [comment]
Upgrading Advanced System Care (ASC) to version **11.1.0.198** has resolved this issue at least for me.
With that being the case this issue can be classed as resolved.

Thank you

**Comment by Moistopheles** [comment]
Can confirm, the latest update allows ASC's Homepage Advisor and MultiMC to be run simultaneously.

**Comment by peterix** [comment]
Alright!
