### ISSUE TITLE
Instant crash when launching instance, specific to my computer.

### ISSUE THREAD

**Issue by kirbystarman** [MultiMC/MultiMC5#2056]
System Information
-----------------------------
MultiMC version: 0.5.2-1096

Operating System: Windows 10 64bit

Summary of the issue or suggestion:
----------------------------------------------
When I go to launch my instance in MultiMC, 'Pack 0', the game doesn't even launch, instead a  long log appears in the Minecraft Log (lots of red writing). My two friends have both successfully launched the modpack and can play with each other on their servers, so it isn't the modpack that's the problem. I'm very confused as to what's causing the problem and I can't seem to find the solution online. 

What should happen:
------------------------------
The game should launch with all the mods and multiplayer working, no crashing whatsoever. 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install the modpack (Pack 0: https://www.mediafire.com/file/3kx24yyqqg069dz/Pack%200.zip) and the latest version of MultiMC.

2. Download and select the latest version of Java to run and drag the modpack to the instances folder. (it crashes at any RAM value).

3. Launch and see if you get the same crash issue as I do.

Suspected cause:
---------------------------
In the logs, as you will see, there is lots of "Unable to load..." messages, it could be to do with missing files maybe. It could be to do with either MultiMC, or my computer hardware.

Logs/Screenshots:
----------------------------
I'm very sorry but MultiMC is refusing to let me upload the log, it says: 

MultiMC: Log upload triggered at: 03 Dec 2017 17:27:10 +0000
MultiMC: Log upload failed!

So I've uploaded it manually (I don't know if this matters): 

https://paste.ee/p/1YMGT

Additional Info:
---------------------------
My hardware: 

Nvidia GTX 750TI
8gb RAM
AMD FX 4100 Quad-Core Processor 3.60 GHz
Windows 10 64bit

**Comment by peterix** [comment]
Remove java 9.
Install java 8.

**Comment by kirbystarman** [comment]
I don't think it's possible to feel more embarrassed than I do currently.
Thanks you very much however ! :D

**Comment by peterix** [comment]
There's no need to be embarrassed -- now you know. It's just the usual minefield of trying to keep things working :)

**Comment by kirbystarman** [comment]
I'm afraid I spoke too soon, the game launched and I received another crash log:

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:61)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499)

FULL LOG: https://paste.ee/p/qWI2D

**Comment by peterix** [comment]
https://bugs.mojang.com/browse/MCL-7376?focusedCommentId=387018&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-387018

**Comment by kirbystarman** [comment]
Wonderful! Many thanks again!
