### ISSUE TITLE
Latest Dev update won't launch

### ISSUE THREAD

**Issue by PurpleHel** [MultiMC/MultiMC5#2058]
System Information
-----------------------------
MultiMC version: Latest update/0.5.2-1011 lin64

Operating System: Kubuntu 17.10

Summary of the issue or suggestion:
----------------------------------------------
When updating to the newest dev update, it won't launch. I did a clean install of the multimc .deb I had saved, problem persists.

What should happen:
------------------------------
It should launch.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Click update on the 'new version' notification

2. Let update install

3. Get notification new update won't launch, with 'do you want to roll back' option. (Kudos whoever put that in!)

Suspected cause:
---------------------------
*shrug*

Logs/Screenshots:
----------------------------
https://imgur.com/xgBRbUN

Additional Info:
---------------------------

**Comment by dje4321** [comment]
Issue has already been filed
https://github.com/MultiMC/MultiMC5/issues/2057

**Comment by peterix** [comment]
Yeah, the rollback option is there just for such occasions - broken linux dependencies, windows antivirus doing 'strange things' and similar :)

You can get a fresh copy of the develop build here: https://files.multimc.org/downloads/mmc-develop-lin64.tar.gz
Try to remove the libz file, see if that runs. It does on Arch.

**Comment by PurpleHel** [comment]
Yup, removing libz fixed it.

**Comment by peterix** [comment]
Alright, closing this one, if you have any more comments, continue in #2057
