### ISSUE TITLE
Instances being placed in MMC_DIR

### ISSUE THREAD

**Issue by dje4321** [MultiMC/MultiMC5#2059]
System Information
-----------------------------
MultiMC version: Version 0.6.0-develop-1046

Operating System: Fedora 27

Summary of the issue or suggestion:
----------------------------------------------
MultiMC placing new instances in MMC_DIR 

What should happen:
------------------------------
Creating a new instance should place it in MMC_DIR/instances. If MMC_DIR/instances does not exsist then it should be created.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download and run the latest DEV build, extract it, and run it

2. Go though the setup process and create a new instance

Suspected cause:
---------------------------
Instances folder is not created after setup. Creating the instances folder resolves the issue

Logs/Screenshots:
----------------------------
https://hastebin.com/joquqoxubo.erl

Additional Info:
---------------------------
Only repeatable when downloading the dev branch directly. Not repeatable when upgrading from stable to the latest dev branch.

**Comment by peterix** [comment]
Should be fixed.
