### ISSUE TITLE
[Develop] Bundled openssl depends on MSVC redist 2013

### ISSUE THREAD

**Issue by fixator10** [MultiMC/MultiMC5#2060]
System Information
-----------------------------
MultiMC version: 0.6.0-develop-1133

Operating System: Windows 10 v1709 Build 16299.64

Summary of the issue or suggestion: 
----------------------------------------------
MMC5 develop unable to get most data from web (news, connection to mojang auth servers)

What should happen:
------------------------------

On checking updates: Should appear changelog or "nothing" messages
On adding account: It shouldn't give out error

Steps to reproduce the issue:
-------------------------------------------------------------
1. Launch MMC5

2. Check for updates

3. Get error about "github api unavailable" (it is available actually via browser)

4. Check news line in "statusbar"

5. Can see only "Loading news"

6. Try to add account

7. Get `Error creating SSL context () (99)` error

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

![MMC5 Update window with "Loading news"](https://Moeka.is-a-good-waifu.com/8bacb6.png)
![Adding account](https://Moeka.is-a-good-waifu.com/7a021f.png)
[MMC5 Logs](https://Moeka.is-a-good-waifu.com/ac6e64.log)

![Availability of mmc news rss](https://Moeka.is-a-good-waifu.com/fc9daf.png)
![Availability of github api](https://Moeka.is-a-good-waifu.com/ae0f13.png)
![Availability of MC auth servers](https://Moeka.is-a-good-waifu.com/a67bdb.png)

Additional Info:
---------------------------
This started happens about version 1130, but now it even doesn't even let me start any MC instance. (I have "reinstalled" MMC5 completely (removed all folders, except `instances` and reunpacked release MMC, then updated it to MMC develop)), before that i has added account and i wasnt able to join online servers (invalid session ingame error), now i can't even add an MC account

Changelogs in updating is available, but updating is working

**Comment by peterix** [comment]
Can you post the `MultiMC.#.log` log file(s)? The one with 0 is always the latest one.

**Comment by fixator10** [comment]
[MMC5 Logs](https://moeka.is-a-good-waifu.com/ac6e64.log)

**Comment by peterix** [comment]
If you download and install the 32bit vesion of this:
https://www.microsoft.com/en-us/download/details.aspx?id=40784

Does it work?

**Comment by fixator10** [comment]
Yep.
`vcredist_x86` fixed problem

**Comment by peterix** [comment]
Let's keep this open.

I'll have to provide a build of openssl that does not depend on MS libraries like that.

**Comment by peterix** [comment]
This should now be fixed in the latest build, please test.

**Comment by fixator10** [comment]
Seems fine without MSVC redist 2013 x86 now
(x64 was not helping when issue was actual)
![](https://Moeka.is-a-good-waifu.com/7772a0.png)
