### ISSUE TITLE
I want to do 1.12 modpacks but i have no internet on my pc

### ISSUE THREAD

**Issue by deathmurloc33** [MultiMC/MultiMC5#2061]
so I want to do 1.12 modpacks but my main pc I use to play has no internet and multimc only shows up to 1.5.4 when I don't have internet I'm wondering how to get 1.12 to show up without internet

**Comment by peterix** [comment]
You will have to run it on a machine that does have an internet connection.

You can bring it along on an external drive, plug it in somewhere and let it grab all the things it needs - just launch an instance once with an internet connection and it should continue working when you go offline.
