### ISSUE TITLE
MultiMC is not loading when an instance is being launched. 

### ISSUE THREAD

**Issue by Overlord5591** [MultiMC/MultiMC5#2067]
System Information
-----------------------------
MultiMC version: MultiMC5

Operating System: Windows 7

Summary of the issue or suggestion:
----------------------------------------------
I am having a directory or folder error with multiMC when I try to launch it, 

What should happen:
------------------------------
The MultiMC should launch the server modpack and launch the minecraft application normally.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download MultiMC

2. Download server resource pack

3. Install forge through MultiMC (ver 14.23.0.2512) (as recommended from post that server resource pack is on)

4.  Run the Instance In MultiMC

Suspected cause:
---------------------------
I don't understand what the syntax is telling me

Logs/Screenshots:
----------------------------
MultiMC version: 0.5.2-1096

Minecraft folder is:
instances/Vorecraft1.12.2 (1)/minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 1.8.0_151, using 64-bit architecture.

Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance Vorecraft1.12.2 (1)' failed to process:
http://files.minecraftforge.net/maven/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar.pack.xz
http://files.minecraftforge.net/maven/com/typesafe/config/1.2.1/config-1.2.1.jar.pack.xz
http://files.minecraftforge.net/maven/jline/jline/2.13/jline-2.13.jar
http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.0.2512/forge-1.12.2-14.23.0.2512-universal.jar
http://files.minecraftforge.net/maven/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
http://files.minecraftforge.net/maven/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar.pack.xz
http://s3.amazonaws.com/Minecraft.Download/versions//.jar
https://libraries.minecraft.net/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
https://libraries.minecraft.net/lzma/lzma/0.0.1/lzma-0.0.1.jar
https://libraries.minecraft.net/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
https://libraries.minecraft.net/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
https://libraries.minecraft.net/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
https://libraries.minecraft.net/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
https://libraries.minecraft.net/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-windows.jar
https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar.

Clipboard copy at: 13 Dec 2017 17:56:48 -0600

Additional Info:
---------------------------
Thank you for reviewing this issue!

**Comment by Dushess** [comment]
http://files.minecraftforge.net/maven/com/typesafe/akka/ is unreachable or removed. Impossible to download libraries from described adresses.

**Comment by peterix** [comment]
http://files.minecraftforge.net/maven/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar.pack.xz works just fine

Also, this shows that the version json has not been correctly loaded: http://s3.amazonaws.com/Minecraft.Download/versions//.jar

... so this must be some sort of network issue on your end, or between you and Mojang.

**Comment by Overlord5591** [comment]
Would it be the firewall maybe? Or is this beyond that?

**Comment by peterix** [comment]
Do these load using a browser? Then it's probably some sort of local firewall.
If they don't load at all, it's probably further down in the network, or it's something that affects your system as a whole.

**Comment by peterix** [comment]
Well, reopen if this is sttill an issue. I still think it's some general network or firewall problem.
