### ISSUE TITLE
backup level.dat is being used on creation of new world even in new instance

### ISSUE THREAD

**Issue by Adarcer** [MultiMC/MultiMC5#2068]
System Information
-----------------------------
MultiMC version: 0.5.2-1096

Operating System: Win7-64 Intel core I7-4770k 3.50GHz, 16GB ram 

Summary of the issue or suggestion:
----------------------------------------------
"backup level.dat is being used" error and kick back too menu screen, even on creation of new world in old instance. even tried a new profile same issue. can play old worlds but new worlds will not work or even load. renaming the "level.dat_old" to something like "level.dat_old***" allows old game too load so level.dat is not corrupted, it just seems to be defaulting to the backup automatically.

Logs/Screenshots:
Crash Log= https://pastebin.com/pmW7BCrS
[fml-client-latest.log](https://github.com/MultiMC/MultiMC5/files/1557756/fml-client-latest.log)

Not saying this is a bug ... I just need advice on how too get past this

**Comment by peterix** [comment]
That is not a MultiMC log. Please use the upload button from tthe Minecraft page of the instance dialog.
