### ISSUE TITLE
cannot find MultiMc.exe error

### ISSUE THREAD

**Issue by JohnnyDBlanco** [MultiMC/MultiMC5#2070]
hello, this is my first time trying to download/use Multimc.
when i download it i put it in my ddocuments folder and extract the files, but when i go to click on MultiMc.exe i get a message saying that it cannot find a path to MultiMc.exe and then the icon for it disappears from the folder. 
I already looked at #2004 and that did not work.

**Comment by peterix** [comment]
That honestly sounds like some crazy antivirus doing things it shouldn't.

1. Make sure you got MultiMC from the real website: https://multimc.org/
   If you got it elsewhere, it might not be OK.
2. Scan and clean your system with this, just to be sure there is no interference: https://www.malwarebytes.com/
3. Try turning off everything that could be doing this (anti-whatever software, mostly).
