### ISSUE TITLE
Need maintenance on Chinese translations

### ISSUE THREAD

**Issue by LasmGratel** [MultiMC/MultiMC5#2072]
System Information
-----------------------------
MultiMC version:0.6.0-develop-1138

Operating System:Windows 10

Summary of the issue or suggestion:
----------------------------------------------
There is plenty of untranslated strings in Weblate, but I haven't seen anyone who is maintaining these translations.
Also, the `zh.po` is updated 10 months ago which is much slower than the speed MultiMC updating, I have to switch to English so that I am able to set up correctly.

**Comment by cqjjjzr** [comment]
I'm the maintainer of MultiMC Chinese translation.
The latest translation is updated 10 months ago because the latest MMC stable release is released 10 months ago. I'll post a new file but you should know, the new string in the develop channel version of MMC is not added to *template.pot* so I'm unable to translate them. A good suggestion is to use stable version.

**Comment by LasmGratel** [comment]
but the problem is that stable version has conflicts either

**Comment by peterix** [comment]
Indeed, the translations reflect the state of the stable version, which is now quite old. I did make the 0.5.2 release, but I don't think that includes any UI changes. 

If there's something wrong, you can either use [weblate](http://translate.multimc.org/) or use [poedit](https://poedit.net/) and make a pull request to the [translations repo](https://github.com/MultiMC/MultiMC5-translate).

I'm still not entirely sure if weblate is actually any good - it would need a lot more active translators to work the way it was intended to.

Without any infrastructure changes, the only way to improve the situation would be to release stable versions more often.

**Comment by peterix** [comment]
See: https://github.com/MultiMC/MultiMC5-translate/pull/24

**Comment by peterix** [comment]
Stable 0.6.x is out, and the translations have been updated.
