### ISSUE TITLE
Backwards compatibility for dev branch exported instances

### ISSUE THREAD

**Issue by BoxOfFlex** [MultiMC/MultiMC5#2073]
Pretty much I distribute modpacks with a small group of friends through MultiMC and I use dev branch for latest features and such, but a lot of problems arise when doing this.

Either the instance doesn't have forge (even when imported on dev branch) or its marked as "incompatible", which is understandable with how many layout changes have happened since stable.

Some of my friends aren't the brightest when it comes to computers and I often have to spend forever either getting them setup for it not to work or attempting to walk them through getting to dev branch, usually both.

If any of the devs don't want to figure out a solution for this, that's fine, I'll try my hardest to try and deal with being impatient with these few people.

**Comment by Heufneutje** [comment]
Considering how much the format had to be changed to support Minecraft 1.13 snapshots I doubt that's happening. The proper way to solve this would be a new stable version.

**Comment by peterix** [comment]
Indeed, and 0.6 is out now, with all the goodies included :)
