### ISSUE TITLE
Debian - dpkg post removal script errors when update-desktop-database is not installed

### ISSUE THREAD

**Issue by oddstr13** [MultiMC/MultiMC5#2074]
System Information
-----------------------------
MultiMC version: 0.4.7 (https://files.multimc.org/downloads/multimc_1.1-2.deb)

Operating System: Debian 8 (Jessie)

Summary:
---------------------------
Debian - dpkg post removal script errors when `update-desktop-database` is not installed, leaving the system broken.

Additional Info:
---------------------------

```
$ sudo dpkg -i multimc_1.1-2.deb 
(Reading database ... 161155 files and directories currently installed.)
Preparing to unpack multimc_1.1-2.deb ...
Unpacking multimc (1.1-2) over (1.1-2) ...
/var/lib/dpkg/info/multimc.postrm: 3: /var/lib/dpkg/info/multimc.postrm: update-desktop-database: not found
dpkg: warning: subprocess old post-removal script returned error exit status 127
dpkg: trying script from the new package instead ...
/var/lib/dpkg/tmp.ci/postrm: 3: /var/lib/dpkg/tmp.ci/postrm: update-desktop-database: not found
dpkg: error processing archive multimc_1.1-2.deb (--install):
 subprocess new post-removal script returned error exit status 127
/var/lib/dpkg/tmp.ci/postrm: 3: /var/lib/dpkg/tmp.ci/postrm: update-desktop-database: not found
dpkg: error while cleaning up:
 subprocess new post-removal script returned error exit status 127
Processing triggers for mime-support (3.58) ...
Errors were encountered while processing:
 multimc_1.1-2.deb
```

This leaves the package system in a broken state.
```
$ sudo apt install desktop-file-utils
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: The package multimc needs to be reinstalled, but I can't find an archive for it.
```
Easy workaround is to comment out the `update-desktop-database` file in `/var/lib/dpkg/info/multimc.postrm`

Content of the script in question
```sh
$ cat /var/lib/dpkg/info/multimc.postrm
#!/bin/sh
set -e
update-desktop-database
```

Something like this could work. Alternatively changing the `set -e` command might help (I'm not familiar with what this does, but my guess is that `-e` enables error propagation).
```sh
#!/bin/sh
set -e
if hash update-desktop-database 2> /dev/null; then
    update-desktop-database
fi
```

**Comment by peterix** [comment]
I've added a dependency on `desktop-file-utils` to the latest version of the package. This should now be fine with `1.2-1`.
