### ISSUE TITLE
Minecraft 1.12.2 (Vanilla) don't start

### ISSUE THREAD

**Issue by TheLonlyGuy1** [MultiMC/MultiMC5#2077]
System Information
-----------------------------
MultiMC version: 0.5.2

Operating System: WIN10

Summary of the issue or suggestion:
----------------------------------------------
Whenever I start the instance it just ends in errors

What should happen:
------------------------------
Minecraft should start

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a instance (vanilla 1.12.2)

2. Start the instance

Suspected cause:
---------------------------
I don't know

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://pastebin.com/SqcJHNq0

Additional Info:
---------------------------

**Comment by peterix** [comment]
Please use Java 8.

**Comment by TheLonlyGuy1** [comment]
I have the latest Java version

**Comment by peterix** [comment]
You do have the latest java version, which is the problem. Remove it, install java 8. And the Mojang launcher is entirely irrelevant here.

**Comment by TheLonlyGuy1** [comment]
Isn't the latest version of Java 8 151 (I've already installed that)?

**Comment by peterix** [comment]
Then use it. You are not using it.

**Comment by TheLonlyGuy1** [comment]
How?

**Comment by peterix** [comment]
Open the java settings, use the auto-detect and select it.

**Comment by TheLonlyGuy1** [comment]
That's what I've done

**Comment by peterix** [comment]
If you are still having that issue then no.

**Comment by TheLonlyGuy1** [comment]
Thanks I've resolved the issue

**Comment by peterix** [comment]
Alright :)
