### ISSUE TITLE
1.12.2 freezes and closes immediately upon entering a world, even in vanilla.

### ISSUE THREAD

**Issue by Failbird105** [MultiMC/MultiMC5#2082]
System Information
-----------------------------
MultiMC version: 

Operating System: 

Summary of the issue or suggestion: 
----------------------------------------------
0.6.0
Windows 8.1
When I load up a world in 1.12.2, even if I'm playing unmodded, it freezes immediately after loading, and says that Java Platform SE has stopped working, forcing me to close Minecraft.

What should happen:
------------------------------
I should be able to load the world and play as normal.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Start Minecraft in a 1.12.2 instance

2. Open world

3. Immediate Freeze

Suspected cause: 
---------------------------
Unknown, at first I believed it might have been Java, so I updated Java, it kept happening, then I thought it might have been MultiMC, so I updated to version 0.6.0, it kept happening, then I thought it might have been my graphics driver, so I tried to update that but it told me it was the wrong one for my system(note: the company that made my computer says otherwise.)

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
[https://paste.ee/p/Hqo6l](https://paste.ee/p/Hqo6l)

Additional Info:
---------------------------

**Comment by bitcynth** [comment]
Have you tried it with 64bit Java?

**Comment by Failbird105** [comment]
Can't believe I didn't think about that. However now I have and it didn't work.

**Comment by Heufneutje** [comment]
Does the vanilla launcher do the same thing? MultiMC just launches the game and shouldn't affect anything after it is launched.

**Comment by Failbird105** [comment]
Can't believe I hadn't thought of that either, but I tried it, and yeah, it does the same thing.

**Comment by peterix** [comment]
Please always provide an updated log from your last attempt. It helps to keep things clear with cold, hard evidence :)

**Comment by Failbird105** [comment]
There is no log. Literally, no crash log, no hs_err_pid, nothing. Believe me I've checked everywhere I can think of every time it happens and there is nothing to find.

**Comment by peterix** [comment]
Even if the instance magically 'doesn't crash, but crash silently anyway', you should be able to `Edit Instance` and inspect what happened in the `Minecraft Log`.

**Comment by peterix** [comment]
Also, do you by chance use `IoBit Advanced SystemCare`?

**Comment by Failbird105** [comment]
Oh you were referring to the MultiMC minecraft log, I wasn't using mutliMC that last time because I was told to check if non-MultiMC Minecraft still has the issue. As for IoBit, no I don't.

**Comment by Failbird105** [comment]
here's the log from the attempt I just made using MultiMC after re-installing 1.12.2 [https://paste.ee/p/aHWnn](url)

**Comment by peterix** [comment]
The reason why I'm asking about that IoBit thing is because it basically causes similar problems with MultiMC itself. It injects DLLs into every process on the system and causes crashes.

Other things do that too:
* Some driver packages
* Overlays
* Malware
* Antivirus
* The Apple network service discovery thing that gets installed along with iTunes
* And so on, and so forth...

Let's check the Windows event log and try to determine where it is crashing. This is the rough idea of how to use it:
https://www.cyberlink.com/support/faq-content.do?id=10449

**Comment by Failbird105** [comment]
Alright, so, I've made some progress. I uninstalled bytefence(the things constantly trying to rub itself into my face anyway) and tried what you said(best I could figure it out anyway, my computer doesn't exactly work like most), the log I got from that is here: [https://paste.ee/p/BH8iu](url)

Then I tried playing again on 1.12(not 12.2), it broke as well, but I did get a log out of it this time. That's right here: [https://paste.ee/p/HCcjg](url)

**Comment by peterix** [comment]
That's an Intel integrated GPU driver crash. Does that machine have a second, dedicated GPU next to this intel thing?

**Comment by peterix** [comment]
Please attach the full dxdiag report so we can figure out what is wrong. You can do it like this:

## In Windows 7:

* Click on the `Start` Button.
* In the Search Box type `dxdiag` and press `<Enter>`. The DirectX Diagnostic Tool pop-up window should appear.
* Click on `Save all Information.`
* Save the information to your Desktop, keep the file name as is.
* Attach the file here.

## In Windows 8, Windows 10:
* Press the `[Windows]+[R]` keys on your keyboard to bring up the Run command.
* In the `Run` command box, type in `dxdiag` and press `<Enter>`. The DirectX Diagnostic Tool pop-up window should appear.
* Click on `Save all Information.`
* Save the information to your Desktop, keep the file name as is.
* Attach the file here.

Here is an example of what the DirectX Diagnostic Tool will look like:

![dxdiag example](https://user-images.githubusercontent.com/203326/34328124-4489aa8e-e8d6-11e7-9984-0f5e8561564b.png)

**Comment by Failbird105** [comment]
[DxDiag.txt](https://github.com/MultiMC/MultiMC5/files/1601125/DxDiag.txt)
There. As for a second GPU, I have no idea.

**Comment by peterix** [comment]
So, it is the only GPU in the system. You could try checking for driver updates:
https://www.intel.com/content/www/us/en/support/detect.html

Hopefully that helps.

**Comment by peterix** [comment]
You may have to uninstall the current driver first:
https://translate.google.com/translate?hl=en&sl=fr&u=http://forum.minecraft-france.fr/threads/impossible-de-lancer-un-monde-1-10-x.36243/&prev=search

**Comment by Failbird105** [comment]
The DSA just doesn't work for me for some reason. It keeps giving me errors. As for the other thing, how would I go about uninstalling the driver anyway?

**Comment by peterix** [comment]
I'm not sure.

This is just very similar errors I found with the exact same hardware, resolved by updating/replacing drivers.
