### ISSUE TITLE
Cannot run Minecraft after Vivecraft installation

### ISSUE THREAD

**Issue by polyzium** [MultiMC/MultiMC5#2084]
System Information
-----------------------------
MultiMC version: 0.6.0-1154

Operating System: Windows 10 64bit

Summary of the issue or suggestion:
----------------------------------------------
Vivecarft simply breaks an MC instance unless you remove its json file in your instance's patches folder

What should happen:
------------------------------
Minecraft should launch with no problems

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install vivecraft by following [this manual](http://www.vivecraft.org/multimc/)

2. Because vivecraft's entry won't appear in the Version section of "Console window for etcetc", add an empty patch entry thing? ("Add Empty" button at the right)

3. Paste vivecraft's json onto that.

4. Press "Reload" and run the game

Suspected cause:
---------------------------
Probably the URL is hardcoded into the source code?

Logs/Screenshots:
----------------------------
[link](https://paste.ee/p/uxrrU)

Additional Info:
---------------------------
I don't know why MMC wants to download vivecraft from amazon servers, it should download things as described in the json file

**Comment by spannerman79** [comment]
From that "manual" link provided

`Note: MultiMC 0.6 is no longer compatible with these instructions. Stay tuned.`

**Comment by polyzium** [comment]
Fixed in latest revisions of vivecraft installer
