### ISSUE TITLE
Possible SSL certificate error on macOS 10.9 and older

### ISSUE THREAD

**Issue by ngmatt8652** [MultiMC/MultiMC5#2085]
System Information
-----------------------------
MultiMC version: 6.0.0

Operating System: OSX 10.9.5

Summary of the issue or suggestion:
error message is
Instance update failed because: Component metadata update task failed while downloading from remote server:
Job 'Download of meta file index.json' failed to process:
https://v1.meta.multimc.org/index.json
Job 'Download of meta file net.minecraft/1.7.10.json' failed to process:
https://v1.meta.multimc.org/net.minecraft/1.7.10.json.
----------------------------------------------

What should happen: instance should load
------------------------------

Steps to reproduce the issue (Add more if needed): cannot reproduce on any other computer
-------------------------------------------------------------
1.

2.

3.

Suspected cause: unknown
------------------
---------------------------

**Comment by gabrielkiss** [comment]
I have the same problem, I launch project ozone 2 and it just launches vanilla 1.7 minecraft

**Comment by peterix** [comment]
Can you download and attach this? https://v1.meta.multimc.org/net.minecraft/1.7.10.json

**Comment by gabrielkiss** [comment]
Here are the files
[mmc-pack.json.txt](https://github.com/MultiMC/MultiMC5/files/1598568/mmc-pack.json.txt)
[1.7.10.json.txt](https://github.com/MultiMC/MultiMC5/files/1598570/1.7.10.json.txt)

**Comment by ngmatt8652** [comment]
sooooo, where do I put them?

**Comment by gabrielkiss** [comment]
just download that file and upload it to paste.ee for example peterix wants to see if you download it correctly because that's what the log message seems to indicate

**Comment by peterix** [comment]
Ok. I think that might not have been the same problem.

Anyway, here's what happened in @gabrielkiss's case:
Forge somehow ended up above Minecraft in the version list. This causes it to not work. If you move it below Minecraft, it's all fine again.

@ngmatt8652 now, can you upload those files? Because your problem is most likely different.

**Comment by peterix** [comment]
specifically, grab https://v1.meta.multimc.org/net.minecraft/1.7.10.json with a browser and attach it here. Do the same with https://v1.meta.multimc.org/index.json

If the browser gives you some sort of error, take a screenshot of it.

**Comment by ngmatt8652** [comment]
ok I downloaded the files (sorry for the delay) and they downloaded just fine on chrome

**Comment by ngmatt8652** [comment]
[1.7.10.json.txt](https://github.com/MultiMC/MultiMC5/files/1602345/1.7.10.json.txt)
[mmc-pack.json.txt](https://github.com/MultiMC/MultiMC5/files/1602346/mmc-pack.json.txt)

**Comment by peterix** [comment]
Can you check the MultiMC.#.log log?
On macOS, you need to inspect the inside of the `MultiMC.app` - specifically `MultiMC.app/Contents/MacOS/MultiMC.#.log`.
Please do not upload the file, just check if there are SSL errors present.

I found this:

**Comment by ngmatt8652** [comment]
yep the error is 2.455 C Download "https://multimc.org/rss.xml" SSL Error # 1  :  "The root CA certificate is not trusted for this purpose" don't know what that means but it might be why the twitch luncher never worked either, is it fixable?

**Comment by peterix** [comment]
You have a very old, unsupported version of macOS. It is entirely possible Apple no longer updates the root SSL certificates in it, so it won't recognize new ones. The other possibility is that it doesn't recignize the kind of certificate multimc.org uses -- it requires SNI.

I don't have an older system around for testing.

Can you try with Safari? This would hopefully give us more details than looking at custom applications. Try https://v1.meta.multimc.org/net.minecraft/1.7.10.json in Safari, take note of any security warnings or errors.

**Comment by Zirking** [comment]
I came from #2093, I work with osX version 10.8.5 and had the same problem.

I could also download those things just fine. I normally use chrome too, but for this case I used Safari. And it worked.

So I looked into the certificates from my computer too, but I don't see the required SNI there.
Can you explain more about what you mean by requiring SNI? Does that mean there needs to be a certificate with SNI in the name, or is it also possible it's called completely different?

**Comment by spannerman79** [comment]
I don't have a Mac, and I have no idea if this will work - so proceed with extreme caution

http://www.macfreek.nl/memory/Install_CA_Certificates

**Comment by ngmatt8652** [comment]
I am wary of doing this, unfortunately it looks like my only option is to upgrade to the ugly as sin el capitan (Sierra is far too new and will break certain apps on my computer) so I am guessing there is no good fix for this

**Comment by peterix** [comment]
The alternative would be to build absolutely everything, including a proper version of OpenSSL. Apple doesn't maintain the copy in macOS properly, even in the newer versions. I thought switching to Qt 5.6, which uses `Secure Transport` would actually make things better. Instead it seems to be one of these 'damned if you do, damned if you don't' situations...

Hopefully updating the OS would help. I build and test on 10.12.

**Comment by spannerman79** [comment]
> I am wary of doing this, unfortunately it looks like my only option is to upgrade to the ugly as sin el capitan

This was done back before Letsencrypt certs were part of Java (pre 8u101/102) which causes similar issues with invalid certs.

**Comment by ngmatt8652** [comment]
updating to el captain did fix it (along with a host of other problems) the only problems I have now are the typical "they changed all the basic stuff for the worse" problems, so the only option to fix the problem is indeed to upgrade your OS.

**Comment by peterix** [comment]
So I'm calling this a bug, with a workaround of 'update to a supported release of macOS'.

**Comment by Blackcomet** [comment]
Where do I place the file? I had to edit it to the right format, but it still gives me the same error. I'm using windows 8.1.

**Comment by phit** [comment]
closing in favor of https://github.com/MultiMC/MultiMC5/issues/2443
