### ISSUE TITLE
"Update when MultiMC closes" actually updates right now

### ISSUE THREAD

**Issue by Yarillo4** [MultiMC/MultiMC5#2088]
System Information
-----------------------------
MultiMC version: 0.4.2

Operating System: Windows 7

Summary of the issue or suggestion:
----------------------------------------------
When a new update happens, MultiMC asks you if you wish to update now, later, or when the software exits. When you click "Upon closing MultiMC", it actually starts downloading right away and opens a [window](https://i.imgur.com/sCKZlp7.png) that stops you from doing anything

What should happen:
------------------------------
The software should update upon closing. If a download needs to start, it should happen in an independant window that doesn't stop you from actually using the software

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Have an old version like 0.4.2

2. Launch it

3. Press "Update when the software exits"

Suspected cause:
---------------------------
You wanted to start the download right away to save time and do the update later on, but you forgot that the "Please hold" window prevents the user from using MultiMC.

Solution: Make that specific window independant ("unattached" ?)

**Comment by peterix** [comment]
This option is actually gone in 0.5, and there's no point fixing something that is gone...

But I'll definitely keep the idea around for the next time I mess with updates.

**Comment by peterix** [comment]
Tracked on workflowy: https://workflowy.com/s/2EyDMcp7CU#/3464d5f991b6
