### ISSUE TITLE
Cannot install forge from instance settings

### ISSUE THREAD

**Issue by ckykenken** [MultiMC/MultiMC5#2090]
System Information
-----------------------------
MultiMC version: 0.6.0-1154

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Cannot install forge on newly created instances, the "install forge" box stuck at 0% and the list is empty

What should happen:
------------------------------
A list of available versions of forge can be chosen

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. create an instance

2. edit instance

3. install forge

Suspected cause:
---------------------------
unknown

Logs/Screenshots:
----------------------------
![default](https://user-images.githubusercontent.com/26035978/34512324-aff6bf46-f09c-11e7-9d26-794b3af8e720.PNG)

**Comment by ckykenken** [comment]
Now it turns out to be normal, without knowing any reason.

**Comment by peterix** [comment]
Can you check the `MultiMC.#.log` ? It must be some networking error, but I'd like to know what the error is. Look for downloads of `index.json` files.

The logs have increading numbers - the higher the number, the older it is. So `0` is most recent.

**Comment by grydian** [comment]
I had the same issue and was able to load a different version of forge by first removing the old forge and installing a new one.  In the log that part that clued me into this fix was.  "forge" is already loaded.  Here is a pastebin for the part of the log that gets added when I try to install a new version of forge when one is already installed.   https://pastebin.com/YK28jT9w

**Comment by peterix** [comment]
@grydian I don't think that is the same problem.

**Comment by grydian** [comment]
Should I open a separate issue for my problem?  I was able in the past to change the version of forge without having to remove it first.  This started happening after the last update.  I totally don't mind making a new issue on github.

**Comment by peterix** [comment]
Please do. This part of MultiMC has been entirely overhauled and has new, exciting bugs that need squashing :)

**Comment by Dushess** [comment]
Latest stable version, got this too, any instance.
Will give the log later.

**Comment by JonathanxD** [comment]
Same happens on Linux (precisely `Linux arch 4.13.12-1-ARCH`). I was able to fix that by removing forge and installing new one, without any problem (like @grydian had). If you experience the same issue as @grydian and understands how to edit json files, you can go to instance directory (ex: MultiMC/instances/INSTANCE_NAME) and open `mmc-pack.json` and remove forge from the list (with MultiMC closed obviously).

**Comment by peterix** [comment]
You likely have a different, second problem. This doesn't sound anything like the original post describes.

**Comment by 132ikl** [comment]
Having the same issue. Here's the log:

https://pastebin.com/qCk7Me3Q

**Comment by Dushess** [comment]
Bump, latest dev version, same thing.
https://pastebin.com/MUFESJRU

**Comment by peterix** [comment]
@Dushess what is the problem in your case? I don't see anything in the logs to be honest.

**Comment by peterix** [comment]
All of you, make separate issues.

**Comment by peterix** [comment]
@132ikl removing and re-adding forge should fix that.

**Comment by 132ikl** [comment]
That did not work. I previously tried removing and readding forge, creating
a new installing and adding forge, and reinstalling multimc from bin and
source. None of this worked. I have a new computer so this is not an issue
for me personally but if you would like more data from the other computer
to fix the issue I'll supply it.

**Comment by peterix** [comment]
Sure, any problem related to the instance format is a serious one. 

This is weird:
```
C "Could not open /home/steveoy132ikl/.local/share/multimc/meta/net.minecraftforge/.json for writing"
```

This is really weird:
```
   21.637 C Exception: "Couldn't open multimc.cfg for writing: Existing file multimc.cfg is not writable"
   21.637 C Couldn't open multimc.cfg for writing: Existing file multimc.cfg is not writable
```

I think it could be some problem with broken filesystem permissions? Combined with something else?

**Comment by 132ikl** [comment]
Welp, now I feel stupid. I had created another user with most startup
services disabled so that I could run modpacks on my low-end machine. Turns
out that I gave that user permissions for a lot of MultiMC files, but not
enough to break it entirely. A quick chown -R fixed that. Thanks!

**Comment by ask6155** [comment]
Is this still @ckykenken 's issue?
I'm totally confused

**Comment by Dushess** [comment]
@peterix Already works, now rewriting old [custom] forge instance with new unified.

**Comment by ckykenken** [comment]
It was my issue but someone reopened it

**Comment by ckykenken** [comment]
It was my issue but someone reopened it

**Comment by peterix** [comment]
Yes, if you have an problem and aren't 100% sure it's the same thing as something already reported on github, open a new issue. We can always close it and mark it as duplicate. Making sense of multiple people talking over each other is not a good approach.
