### ISSUE TITLE
Cannot connect to MultiMC meta

### ISSUE THREAD

**Issue by Zirking** [MultiMC/MultiMC5#2093]
System Information
-----------------------------
MultiMC version:
0.6.0-1095

Operating System:
MacOS 10.8.5
Java 1.8.0_151  64bit

Summary of the issue or suggestion:
----------------------------------------------
I can't connect to the meta of MultiMC, this means I can't download a new version to create a new instance, but also means I can't play any existing instance.
Also trying to create a new instance does not solve this problem, as you can't select a version file.

What should happen:
------------------------------
The game should run or there should be a list of all the possible versions.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
Just opening any existing instance is enough.
Or creating a new instance.

Suspected cause:
---------------------------
The MultiMC server won't respond to my operating system.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
The log where I try to open optifine 1.12.2: https://paste.ee/p/QDW51
A log where I try opening 1.13 snapshot 17w50a: https://paste.ee/p/hRbrC
Here you can see 2 (if needed I'll post more) screenshots when I try to create a new instance: https://ibb.co/album/fuOZ3v

Additional Info:
---------------------------
There is almost no info in the minecraft logs, so I don't know how to help you. If there is more information needed, please ask!

**Comment by peterix** [comment]
See: https://github.com/MultiMC/MultiMC5/issues/2085#issuecomment-355191789

Please check the MultiMC log. Do not post the whole thing here though, unlike the Minecraft logs, it is not censored and can contain personal information. Just look for SSL errors.

**Comment by Zirking** [comment]
This is what I could find:

 6210.316 C Failed  "https://v1.meta.multimc.org/net.minecraft/index.json"  with reason  QNetworkReply::NetworkError(SslHandshakeFailedError)
 6210.316 D Download failed in previous step: "https://v1.meta.multimc.org/net.minecraft/index.json"
 6210.316 D Downloading  "https://v1.meta.multimc.org/net.minecraft/index.json"
 6210.824 C Download "https://v1.meta.multimc.org/net.minecraft/index.json" SSL Error # 1  :  "The root CA certificate is not trusted for this purpose"
 6210.824 W Unimplemented code.
 6210.824 C Certificate in question:
 ""

And that last line is what I see popping up everywhere

**Comment by peterix** [comment]
OK. This is definitely the same problem as #2085 -- let's continue there.
