### ISSUE TITLE
MC 1.12.2 & Liteloader - Missing resources

### ISSUE THREAD

**Issue by spannerman79** [MultiMC/MultiMC5#2094]
System Information
-----------------------------
MultiMC version: 
0.6.0-develop-1157
Operating System:
Win10
Summary of the issue or suggestion:
----------------------------------------------
Liteloader json contains a 404'ed resource

What should happen:
------------------------------
Um... run and start? 😛 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Create new 1.12.2 instance in fresh multimc5 environment that has been switched to dev channel - no cache of meta

2.Add Liteloader 1.12.2 (snapshot)

3.Run instance

Suspected cause:
---------------------------
liteloader json contains a reference to a resource that no longer exists

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

```
92.409 C Task "Update(0x4e63554)" failed:  "Instance update failed because: Game update failed: it was impossible to fetch the required libraries.\nReason:\nJob 'Libraries for instance 1.12.2 Test' failed to process:\nhttps://libraries.minecraft.net/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar.\n\n"
```

That is referenced in the liteloader json file  - line 11
```
{
    "+tweakers": [
        "com.mumfrey.liteloader.launch.LiteLoaderTweaker"
    ],
    "formatVersion": 1,
    "libraries": [
        {
            "name": "net.minecraft:launchwrapper:1.12"
        },
        {
            "name": "org.ow2.asm:asm-all:5.2"
        },
        {
            "MMC-hint": "always-stale",
            "name": "com.mumfrey:liteloader:1.12.2-SNAPSHOT",
            "url": "http://dl.liteloader.com/versions/"
        }
    ],
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "name": "LiteLoader",
    "releaseTime": "2017-11-28T14:44:31+11:00",
    "requires": [
        {
            "equals": "1.12.2",
            "uid": "net.minecraft"
        }
    ],
    "type": "snapshot",
    "uid": "com.mumfrey.liteloader",
    "version": "1.12.2-SNAPSHOT"
}
```
Additional Info:
---------------------------
This was originally first found out by @Lunamann#3921(Discord)
I was able to reproduce this result constantly over and over. as outlined under "Steps to reproduce"

**Comment by peterix** [comment]
@Mumfrey it seems the metadata in the installer is not matching the metadata in http://dl.liteloader.com/versions/versions.json ... specifically, the `url` attributes are in the installers and are missing on the website.

**Comment by d-faure** [comment]
As a workaround:
* Follow the 1 to 3 steps above to recreate the issue, then quit the launcher.
* Use a text editor and modify the  `meta/com.mumfrey.liteloader/1.12.2-SNAPSHOT.json` file like below.

Change:

    ...
        {
            "name": "org.ow2.asm:asm-all:5.2
        },
    ...

to:

    ...
        {
            "name": "org.ow2.asm:asm-all:5.2",
            "url": "http://repo.liteloader.com/"
        },
    ...

That should do the trick.

**Comment by peterix** [comment]
This should no longer be necessary. See:
https://v1.meta.multimc.org/com.mumfrey.liteloader/1.12.2-SNAPSHOT.json
