### ISSUE TITLE
Translations need updating

### ISSUE THREAD

**Issue by cyber01** [MultiMC/MultiMC5#2095]
When importing an assembly with curse (by dragging and dropping onto the MultiMC window), the unpacking (extraction) of the assembly begins, apparently there should be some value for the variable, but instead it shows %1

![import](http://puu.sh/yUJKu.png)

I use MultiMC 1157 dev

**Comment by spannerman79** [comment]
I don't drag and drop - I actually go through the process of creating a new instance and selecting it (see screenshot)

![import](https://user-images.githubusercontent.com/7542384/34608282-aaecd212-f26b-11e7-8e34-978f7cc69c5f.PNG)

**Comment by peterix** [comment]
Look at all this nonsense:
http://translate.multimc.org/search/?q=Downloading+mods...&search=ftx&source=on&target=on&type=all&ignored=False

**Comment by peterix** [comment]
Well, I have no idea what this was about, and the screenshot is gone.
