### ISSUE TITLE
Couldn't extract native jar

### ISSUE THREAD

**Issue by Habeeb-M** [MultiMC/MultiMC5#2098]
MultiMC version:
0.6.0-1154 

Operating System:
WIndows 10
Summary of the issue or suggestion:
----------------------------------------------
The instance does not load properly and the main error says: "
Couldn't extract native jar 'C:/Users/habee/GoogleDrive/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar' to destination 'C:/Users/habee/GoogleDrive/MultiMC/instances/MobFarmTesting/natives'"

What should happen:
------------------------------
It should launch normally. It had launched perfectly earlier today but now it won't. I have checked for spaces in the directory but it doesn't seem like there are any.

Logs/Screenshots:
----------------------------
https://pastebin.com/fKdAFqrE

**Comment by spannerman79** [comment]
`GoogleDrive`?  i'd say there is something else keeping the file open ie oplock. More then likely your "GoogleDrive" sync

**Comment by Habeeb-M** [comment]
No, exited google drive and it still wouldn't run.

**Comment by peterix** [comment]
Check the MultiMC log (`MultiMC.0.log`) right after this happens. Is there anything more in there about the error?

This sort of problem is often caused by permissions, the files being locked and interference from other applications (malware, antivirus, etc.). You could try temporatily disabling or getting rid of such things.

**Comment by Habeeb-M** [comment]
Here's the log:
https://pastebin.com/3qJYZWEs

**Comment by peterix** [comment]
That does look like some sort of permission problem.

Unless it's something absolutely weird, you should be able to clear the 'read only' flag on thw MultiMC folder.

This looks like a decent enough guide about how to do it:
https://www.nibbleguru.com/67_remove-read-only-attribute-windows-10/

**Comment by Habeeb-M** [comment]
I think it's absolutely weird. This has been the most glitchy thing I've ever seen. MultiMC used to work fine before, hardly any crashes. I think something changed recently. I failed to set permissions for the folder itself, and after many repeats, I couldn't make it read-only either. A big problem with this issue is sometimes it works perfectly and sometimes it doesn't. 


I also have some other issues. There's [this reddit post](https://www.reddit.com/r/feedthebeast/comments/7ner2x/cannot_delete_libmfxsw64dll_multimc/) I made, and the issue still persists. Sometimes when I delete instances from the file itself(not inside the launcher) it stays there. A few days later it's not there. So weird.

I get this error a lot, as well as a few others that I've never seen with anything else, and nothing comes up when I google them. Actually, thinking about it, my router's been acting up lately, sometimes I have no internet, sometimes I do. Could that be the problem?

**Comment by KyleStulen** [comment]
Soooo incase someone happens to google into this page somehow, I ran into the same problem just now on win10. 
Somehow the designation for which user 'owns' the natives folder in the instance was magically set to not have a user and then no one could access it. 
Then based on some Microsoft support article not related to this issue at all. I launched windows in safe mode using msconfig (cmd prompt) and then launched the instance offline there (game failed to launch), then the instance magically worked again during a normal boot. 
¯\_(ツ)_/¯

**Comment by Habeeb-M** [comment]
After I made that comment over a month ago, I removed MultiMC from my Google Drive and just put it on my desktop, and I haven't ran into any of these issues again. Hope this helps!

**Comment by ForsakenHarmony** [comment]
Yeah there's some very weird issue with files, not sure if multimc somehow causes it, but I don't really see any other way (except maybe a mod)

I messed around with permissions then ended up deleting a couple of folders until i could finally get it to work

**Comment by Zetabite** [comment]
Could be a NTFS corrupted entry. NTFS likes to lock things and give them weird attributes when something gets corrupted.

**Comment by Heufneutje** [comment]
Or something else that keeps the files in use like a synced/shared folder or a virus scan.

**Comment by ForsakenHarmony** [comment]
It was not in a synced folder and there's not antivirus running

a bit weird for the same entry to get corrupted on multiple machines?

**Comment by spannerman79** [comment]
> No, exited google drive and it still wouldn't run.

@Habeeb-M for the hell of it I created a testing Win10 VM with googles own official sync.  When you "exit" it all you are doing is ending the taskbar icon - yes the actual taskbar icon has its own exe.

Google sync has two other process running - another executable that reads/writes to the storage location and a windows service that controls the latter executable (or vice versa I didn't dig too much into which controls what on those two)

You need to let google sync sync everything first, then pause it. It _has_ to finish its checks first before you pause otherwise oplock won't be released.

So yes - my post ( from https://github.com/MultiMC/MultiMC5/issues/2098#issuecomment-355803193 ) applies.

**Comment by Kerbin-Fiber** [comment]
If anyone else finds this page from a web search, like I did, here's what worked for me.

Open command prompt and type in, `tasklist` then hit enter. Look if `javaw.exe` is running. If it is, close Command Prompt and run it with administrator privileges. Then, once open, type in, `taskkill /F /IM javaw.exe` 

Then boom, try running Minecraft, should work if it's just Java sneakily staying open after closing or a crash.

**Comment by Syogren** [comment]
Writing in 2022 to note that what Kerbin-Fiber recommended worked for me.  Thank you so much, I had no idea what to do!

**Comment by Noxmore** [comment]
Another easier fix that worked for me is to just delete the "natives" folder in the effected instance.

**Comment by aaronneedshelpo** [comment]
> 

doesnt work for me says that the task is killed i will paste a log here

https://pastebin.com/YC93YzTe
