### ISSUE TITLE
cant atl tab out of game since last update

### ISSUE THREAD

**Issue by crusher42** [MultiMC/MultiMC5#2100]
System Information
-----------------------------
MultiMC version: 0.6.0-1069

Operating System: linux mint 18.2

Summary of the issue or suggestion:
----------------------------------------------
cant atl tab out of game since last update while AFK Fishing Farm keybind link to a keyboard key

What should happen:
------------------------------
stop doing action

**Comment by peterix** [comment]
That honestly sounds more like some weirx X / window manager / game problem, rather than anything to do with MultiMC. Are you sure?

**Comment by crusher42** [comment]
yes I am sure I have not changed anything changing Forge installing mods since the last update

just in case if I'm wrong I will test it on my partners computer  which is Linux Mint 17.3

**Comment by peterix** [comment]
The one thing that comes to mind is the LWJGL changes. MultiMC now prefers to use the LWJGL version that the Minecraft version you are using came with. The previous (hardcoded) default of using 2.9.1 is no more.

So maybe if things changed for you, check which LWJGL version is used. Changing it to 2.9.1 might fix your problem.
