### ISSUE TITLE
Failed to start minecraft

### ISSUE THREAD

**Issue by GhostZero91** [MultiMC/MultiMC5#2107]
System Information
-----------------------------
MultiMC version: 0.6.0-develeop-1164

Operating System: Windows 10

Summary of the issue or suggestion: Failed to start Minecraft
----------------------------------------------

What should happen: Normal start
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Clean download of new instance 1.7.10

2. Recommended Forge download and installation

3. Add mods and run the instance

Suspected cause: AppleCore
---------------------------

Logs/Screenshots: https://paste.ee/p/TD2s8
----------------------------

Additional Info:
---------------------------

**Comment by peterix** [comment]
You probably have multiple core mods patching the same thing.

**Comment by GhostZero91** [comment]
How do i know which one?

**Comment by Heufneutje** [comment]
By removing mods one by one until it stops crashing.
