### ISSUE TITLE
Launce McEdit no longer available

### ISSUE THREAD

**Issue by FeedTheChunk** [MultiMC/MultiMC5#2108]
System Information
-----------------------------
MultiMC version: Version 0.6.0-develop-1164 on win32

Operating System:Win10 64bit

Summary of the issue or suggestion:
----------------------------------------------
The ability to launch McEdit from the right click menu, or anywhere else that I can see, is no longer available.  In earlier version of MultiMC there was the ability to right click on an instance and under the "Launch" menu was the option to start McEdit.

What should happen:
------------------------------
There should (or at least there was) an option to launch McEdit from the right click menu on the instance.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
This was entirely moved to the instance window. Use `View Worlds`.
