### ISSUE TITLE
Modifying sounds causes them to be replaced by assets

### ISSUE THREAD

**Issue by RealDovahbear** [MultiMC/MultiMC5#2111]
Summary of the issue or suggestion:
----------------------------------------------
Whenever I change a sound in the files, starting up the game will replace those with the default sounds as if I never even touched them. While this an intentional feature, it really should have some way to disable it. I can't do this with resource packs because I'm using beta 1.7.3, before RC packs. This is very annoying, as I just want the old door, bow, and explosion sounds.

What should happen:
------------------------------
Asset replacing/automatic file updates should be an option (if that's the cause)

Suspected cause:
---------------------------
Likely the asset function

**Comment by peterix** [comment]
In old versions, the game is downloading the files. Mod the game to not do that.
