### ISSUE TITLE
Crashing on any modpack instance (Vanilla runs fine)

### ISSUE THREAD

**Issue by merendero** [MultiMC/MultiMC5#2112]
MultiMC version: 0.6.0-develop-1164

Operating System: Windows 7

All modpacks I try to play crashes on startup (loads thinkgs up to the last step and then BAM). Tried multiple packs of multiple versions. Vanilla Minecraft plays just fine. I'm downloading the packs, placing them on the MultiMC folder and using the import option. I also placed "LegacyJavaFixer-1.0.jar" on the folder. Any suggestions?

Log: https://paste.ee/p/Kkt7n

Thank you

**Comment by peterix** [comment]
That's a crash in the graphics drivers... either caused by misuse in mods, or by a bug in the driver. Or maybe both.

Update your drivers (nvidia) and see if it helps.

**Comment by merendero** [comment]
Hey, thanks for the reply. My drivers are up to date but I managed to solve the issue by changing the "mods" folder on the settings. I created a new folder called mods and changed the path to it. Have no idea why this was causing problems (I have total permissions on the folder) but it worked for all instances.

Thank you!

**Comment by peterix** [comment]
That's like replacing a lightbulb in your car and somehow fixing you nighbor's bike while doing it... makes no sense to me.

¯\_(ツ)_/¯
