### ISSUE TITLE
No instances run

### ISSUE THREAD

**Issue by Anstone5** [MultiMC/MultiMC5#2114]
I am on the newest version and when i try enter any instance it crash i create a new one with no mods and it crashed too.
This is the log.

MultiMC version: 0.6.0-1154

Minecraft folder is:
D:/b/MultiMC/instances/1.12.21/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_141/bin/javaw.exe

Java is version 1.8.0_141, using 64-bit architecture.

Main Class:
  net.minecraft.client.main.Main

Native path:
  D:/b/MultiMC/instances/1.12.21/natives

Libraries:
  D:/b/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  D:/b/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  D:/b/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  D:/b/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  D:/b/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  D:/b/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  D:/b/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  D:/b/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  D:/b/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  D:/b/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  D:/b/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  D:/b/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  D:/b/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  D:/b/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  D:/b/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  D:/b/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  D:/b/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  D:/b/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  D:/b/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  D:/b/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  D:/b/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  D:/b/MultiMC/libraries/com/mojang/realms/1.10.17/realms-1.10.17.jar
  D:/b/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  D:/b/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  D:/b/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  D:/b/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  D:/b/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  D:/b/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  D:/b/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  D:/b/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  D:/b/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  D:/b/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  D:/b/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  D:/b/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir D:/b/MultiMC/instances/1.12.21/.minecraft --assetsDir D:/b/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 5468

Process crashed with exitcode -1073740791.

**Comment by peterix** [comment]
http://www.minecraftforum.net/forums/support/unmodified-minecraft-client/2788787-error-exit-code-1073740791
https://bugs.mojang.com/browse/MC-112780

If you use nvidia graphics, you may have to change your driver version.
