### ISSUE TITLE
Game freezes after generating world on EVERY instance

### ISSUE THREAD

**Issue by CKTheUltimate** [MultiMC/MultiMC5#2115]
System Information
-----------------------------
MultiMC version:0.6.0-1154

Operating System:Windows 10

Summary of the issue or suggestion:Game freezes after generating world on EVERY instance
----------------------------------------------

What should happen:Nothing would happen.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Generate a new world

2.Wait for a few seconds after created

3.Game stays at same frame FOREVER

Suspected cause: Updated to this version. 0.5.X cause no problem,also for plain minecraft client.
---------------------------

Logs/Screenshots:Not Applicable
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:The game stays at same frame,but not the background activities.I can still hear mobs sound and when I lower the cursor and click,there is dirt break sound.But the screen just won't change.It is like playing minecraft in .mp3 format.
---------------------------

**Comment by peterix** [comment]
As there is nothing that would interact with the actual game in MultiMC, there must be something not so sane about your system.

Make sure you do not have weird things injecting code into applications - malware, antivirus, game overlays, etc.

Make sure you have updated drivers for your graphics card. DO NOT settle for whatever came with Windows update. Go to the vendor's website and get the real drivers.

Realistically, whatever it is, it probably does something stupid to determine the process is Minecraft and avoids doing 'things' when that's the case.

**Comment by CKTheUltimate** [comment]
Update:The issue only occurs on fullscreen or full-windowed mode of Multi-mc minecraft clients(works fine on mini windows and normal minecraft launcher).

All my drivers are fine and there are no strange things for now except Multi-mc freezing issue.
Another direction I've gone to is java,but no matter what java software I select for Multi-mc,nothing changes.

I've tested the identical instance on my mac,everything is fine no matter what happened.But my windows PC just won't let me run Multi-mc on fullscreen. Any other suggestions?

**Comment by peterix** [comment]
That honestly makes very little sense and I would suspect something about your system being weird... Maybe some interference from a feature added in Windows 10?

**Comment by peterix** [comment]
Specifically, this: https://www.tenforums.com/tutorials/8637-turn-off-game-bar-windows-10-a.html

What happens when you turn all of this off?

**Comment by peterix** [comment]
Also:
https://www.reddit.com/r/Overwatch/comments/6sdn4s/if_you_play_overwatch_on_windows_10_consider/

>If you want to disable it for games across the board (which is what I did), go to your general Windows settings (windows key > type "settings" > gaming > game bar > "record clips, screenshots..." OFF > UNCHECK "show game bar when I play fullscreen games microsoft has verified").
>
>Note that you have to turn the game bar off AND uncheck "show game bar when I play..." Just doing one doesn't fully disable the overlay.

**Comment by Janrupf** [comment]
I know this bug from plain Java when launching a subprocess... The VM just hangs but uses up a great amount of memory. This could be a Java bug. This never happened to me again since I'm using Linux Mint. Maybe it's a problem with the jvm and the way it interact with parent processes.
