### ISSUE TITLE
Cannot login on computer where minecraft.net is restricted.

### ISSUE THREAD

**Issue by MrJoCrafter** [MultiMC/MultiMC5#2116]
System Information
-----------------------------
MultiMC version: 6.0

Operating System: Win10

Summary of the issue or suggestion:
----------------------------------------------
Add functionality to login to account on computer where minecraft.net is restricted.

What should happen:
------------------------------
Multimc works just fine, but trying to log in to an account doesn't work.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. download multimc on computer where minecraft.net is restricted

2. make instance

3. try to log in to account

Suspected cause:
---------------------------
minecraft.net is restricted

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
there should be a way to just create a dummy account (i.e. cracked account) if this is not fixable.

**Comment by calloatti** [comment]
I don't think this is going to happen.

**Comment by MrJoCrafter** [comment]
That's why i said just make a cracked account feature

**Comment by peterix** [comment]
No, this is not going to happen.

**Comment by QuImUfu** [comment]
i have a (kind of) related question:
What sites are needed to be whitelisted in order to be able to use MultiMC fully?
@MrJoCrafter
If you want to use MultMC somewhere the access to the minecraft pages is blocked, create a USB Stick with MultMC and at least one instance installed. You will be able to play this instance in offline mode on another PC.

**Comment by MrJoCrafter** [comment]
multimc.org and minecraft.net

**Comment by peterix** [comment]
This should be a more complete list, with the important ones on top in **bold**:
* **multimc.org - updates, notifications, patron credits in the about dialog, news, metadata**
* **mojang.com - skin change, mojang APIs, including authserver**
* **minecraft.net - downloading minecraft files**
* **minecraftforge.net - downloading forge files**
* **liteloader.com - downloading liteloader files**
* maven.org - fallback for some library downloads
* github.com - dev channel changelogs
* githubusercontent.com - dev channel changelogs
* crafatar.com - minecraft skins (head icons) in UI
* paste.ee - log upload
* imgur.com - screenshot upload
* cursemeta.dries007.net - curse mod resolving for modpack import
* cursecdn.com - curse mod downloads for modpack import
* google-analytics.com - analytics

**Comment by QuImUfu** [comment]
@peterix thanks
@MrJoCrafter 
you could also use a VPN to circumvent any restrictions a Network might have (if the protection approach the admin uses is lax enough to allow you to connect to your home ip on at least one port)

**Comment by peterix** [comment]
And yes, you can totally play offline. In version 0.6.0, it no longer re-checks the account when you use offline mode. But you have to have one.
However, offline means offline - you need all the necessary files to be locally available. You also need an account that was previously used online. So, grab the files when on a network that doesn't limit you. If you can launch an instance in online mode once, it ***should*** work offline forever.

**Comment by MrJoCrafter** [comment]
Vpns break on the wifi, the best solutions is cracked account.

**Comment by peterix** [comment]
The best solution has been described above. Non-mojang accounts will never be supported, unless the services needed for auth cease to exist.

**Comment by Dioarya** [comment]
I Agree on having a feature for cracked account




BECAUSE PAYPAL WONT WORK

**Comment by Janrupf** [comment]
Nope! It's not gonna happen. There will **never** support for cracked accounts.
