### ISSUE TITLE
Minecraft stops after trying to start it

### ISSUE THREAD

**Issue by SmallEnderman** [MultiMC/MultiMC5#2118]
**BEFORE I BEGIN I MIGHT BE IN THE WRONG PLACE... but couldnt find anywhere else to put it in**

So i've tried to make my own modpack which i've added a bunch of 1.10.2 mods in it, also with the required Cores for the mods... Now i've launched my game and sometimes i've had 1.12 version mods or not the right version of a core... but it would say that in minecraft itself... now... My console gave me the output of all mods being turned off which caused the game to stop? Can anyone help me fix it?

https://paste.ee/p/pfmuh

**Comment by QuImUfu** [comment]
CraftStudio-1.0.0.93-mc1.12-alpha
is for mc 1.12 while your are using a 1.10.2 instance.

**Comment by SmallEnderman** [comment]
ooh okay let me test that

**Comment by SmallEnderman** [comment]
Even now that it works...somehow the loading speed is very... VERY slow and it doesnt have that many mods... is there anything i could do to like try to speed it up? (it almost took over 30 minutes to complete loading immersive engineering... even now it's still not done)

**Comment by QuImUfu** [comment]
you have not given Minecraft enough memory. 
Give it at least 3GB and install 64bit java 8. 
in my experience in heavily modded instances profit from following Java command line options in order to minimize GC lags and memory usage:
```
-XX:+UnlockExperimentalVMOptions -XX:+UseStringDeduplication -XX:+UseG1GC
```

**Comment by SmallEnderman** [comment]
yeah... about that... I've tried to add more GB but appreantly it says i dont have enough space for it? i made it towards have the same GB as my previous modpack i made for 1.7.10... which worked fine back then... that was 1024 and 2048... i tried it now again but it doesnt work anymore... is there a way i could fix it?

**Comment by QuImUfu** [comment]
as i said, install 64 bit java. You can not give MC much more than 2GB with 32bit java.

**Comment by SmallEnderman** [comment]
it works now thanks... and sorry if i've been a bother
