### ISSUE TITLE
MultiMC resizing issue

### ISSUE THREAD

**Issue by africalinguist** [MultiMC/MultiMC5#2119]
System Information
-----------------------------
MultiMC version: 0.6.0-1154

Operating System: Windows 8

Summary of the issue or suggestion:
----------------------------------------------
When I resize the window to make it shorter the scroll bar does not appear, nor can I scroll using my scroll wheel.

What should happen:
------------------------------
I should be able to scroll using the scroll wheel.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
Unknown, but I do have many instances and divisions (see pictures)

Suspected cause:
---------------------------
Unknown

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![kids at 20-01-2018 08-13-50](https://user-images.githubusercontent.com/26539285/35178663-79064e90-fdba-11e7-8570-6836b4a71688.png)

Additional Info:
---------------------------

**Comment by peterix** [comment]
Interesting. It fixes itself when the window is created again (after MultiMC restart, or after tell it to open again while it is running in the background).

**Comment by africalinguist** [comment]
True, but then this:
![kids at 22-01-2018 12-09-47](https://user-images.githubusercontent.com/26539285/35206883-0169823e-ff6e-11e7-8f73-aa1d2188af09.png)
happens when you resize the window, should it? when you scroll up it doesn't fix it.

**Comment by peterix** [comment]
Fixed it in develop.
