### ISSUE TITLE
Game won't start

### ISSUE THREAD

**Issue by Jake09144224** [MultiMC/MultiMC5#2120]
MultiMC 5 Version 0.6.0-1154
Windows 10(64-Bit)
Whenever I launch my game it simply doesn't work I tried with MultiMC and official Minecraft launcher, I have no mods installed on my computer.
Console log: https://paste.ee/p/Cfs3T

**Comment by peterix** [comment]
Start with using 64bit java:
http://javadl.oracle.com/webapps/download/AutoDL?BundleId=230542_2f38c3b165be4555a1fa6e98c45e0808

Install that, make sure MultiMC is using 64bit, not 32bit java.

---

You have some graphics related problem as well, so please attach the full dxdiag report so we can figure out what is wrong. You can do it like this:

* Press the `[Windows]+[R]` keys on your keyboard to bring up the Run command.
* In the `Run` command box, type in `dxdiag` and press `<Enter>`. The DirectX Diagnostic Tool pop-up window should appear.
* Click on `Save all Information.`
* Save the information to your Desktop, keep the file name as is.
* Attach the file here.

Here is an example of what the DirectX Diagnostic Tool will look like:

![dxdiag example](https://user-images.githubusercontent.com/203326/34328124-4489aa8e-e8d6-11e7-9984-0f5e8561564b.png)

**Comment by Jake09144224** [comment]
[DxDiag.txt](https://github.com/MultiMC/MultiMC5/files/1649480/DxDiag.txt)

**Comment by peterix** [comment]
You could try updating the drivers: https://www.geforce.com/drivers/results/112596

**Comment by Jake09144224** [comment]
Thanks
