### ISSUE TITLE
Bring back FTB support in some form

### ISSUE THREAD

**Issue by chaos234** [MultiMC/MultiMC5#2124]
Long time, it was possible that MMC supported FTB Launcher.

Since I hate and do not use this fuuuu Curse/Twitch bullshit I falled back to the Legacy FTB Launcher but since MMC updated his version I now missing all my FTB instances.

Means either this feature comes back please or can I get a link to the last version which has supported the FTB Launcher? Will then Block MMC from updating becuase I loved this feature.

**Comment by peterix** [comment]
Yeah, FTB tracking is gone. You can find previous releases here: https://github.com/MultiMC/MultiMC5/releases

As for the way forward, you should be able to import packs downloaded from the curse website(s). If I'm going to bring something like it back, it will be direct import from the old FTB platform, without involving its launcher...

**Comment by cmohler** [comment]
I'd appreciate it if you could add this feature back in. It's the main reason I use MultiMc.

**Comment by Janrupf** [comment]
If the ftb team allows it MultiMC could support ftb mangement and instance download itself.
See here: 
https://forum.feed-the-beast.com/threads/server-api.121687/
and here
https://github.com/Slowpoke101/FTBLaunch/tree/master/src/main/java/net/ftb/download

Would be a nice feature, wouldn't it?

**Comment by cmohler** [comment]
Thanks @peterix for considering the return of managed FTB instances to multimc!
Janrupf's idea of having MultiMc download the FTB instances directly and then manage them would be ideal!

**Comment by peterix** [comment]
See #2172 - it would be cool to sort the packs by minecraft version

**Comment by Heufneutje** [comment]
I like this new approach. Especially since it doesn't require the FTB launcher.

**Comment by peterix** [comment]
Indeed, this is what it would have been if were not told to not do it back when FTB was a new thing. This it what it **SHOULD** be.

That said, I am tired of saying no to users on behalf of others. If someone still opposes this, they should speak for themselves.

**Comment by enki1337** [comment]
I wonder if it might be useful to check if the old setting for "Track FTB Instances" is enabled and let the user know that the feature is no longer available. After a long hiatus from MC, it was quite confusing to update MultiMC and only be left with a handful of vanilla instances.

**Comment by brodycas3** [comment]
Perhaps make MultiMC import them Peterix? Since that one beature was added.

**Comment by Barhandar** [comment]
Official FTB tracking is nonfunctional for some reason at the moment even in 0.5.0-945 (after having launched 0.6.2-1222 separately and some account issues). As in, the packs themselves still exist in FTB's folder but don't show up in the instance list of MultiMC. Unofficial packs (such as Regrowth) are still listed and work.

Please restore tracking of _existent_ FTB instances.

**Comment by peterix** [comment]
I do not want any sort of tracking of anything -- not the way it was done before anyway. It made the code ugly and hard to maintain.

The parts that the tracking depended on are now gone and I really do not want to bring them back.

Only one-way import into MultiMC makes sense.

**Comment by peterix** [comment]
I see full support of the old FTB platforms including pack updates, and optional import from the FTB launcher locations as the only way forward.
