### ISSUE TITLE
MultiMC Won't Use "javaw" executable from jPortable

### ISSUE THREAD

**Issue by MitchelValentine** [MultiMC/MultiMC5#2125]
System Information
-----------------------------
MultiMC version: Version 0.6.0-1154, Build Number: 1154, Platform: win32

Operating System:
Windows
Summary of the issue or suggestion:
----------------------------------------------
jPortable DOES NOT WORK with MultiMC.

What should happen:
------------------------------
When selecting the "javaw" binary inside of the Java folder generated by

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download jPortable from https://portableapps.com/apps/utilities/java_portable

2. Use the installer to extract it. It will generate a folder called "Java".

3. Go to "bin". All the Java-related executables, including "java", "javaw" and "javaws" are in there.

Suspected cause:
---------------------------
???

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
If it does not work, then it is not a valid version of java. Don't use something broken.

Youc an get the real version of portable java by downloading it from oracle, here:
http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

Grab the `.tar.gz` one for Windows, extract it somewhere (you will need a real archive extractor tool), use that version of Java.

**Comment by MitchelValentine** [comment]
How to extract this as a portable?

**Comment by peterix** [comment]
Extract and use. There is nothing else to it...

**Comment by MitchelValentine** [comment]
Thank you so much! I'll test this and move it around a bit...

**Comment by peterix** [comment]
If you put the extracted java inside MultiMC's folder (for example in `MultiMC\jvm\`), it can use a relative path to it and the whole thing can be moved anywhere.

**Comment by peterix** [comment]
Reopen if this is still a problem. I am going to add bundled/default java runtime to MultiMC soon though.
