### ISSUE TITLE
Minecraft fails to start with Forge (not a mod issue)

### ISSUE THREAD

**Issue by GeorgeBgk** [MultiMC/MultiMC5#2126]
System Information
-----------------------------
MultiMC version: 0.6.1-1118

Operating System: macOS High Sierra 10.13 (17A405)

Summary of the issue or suggestion:
----------------------------------------------
Minecraft fails to start with Forge and returns a `java.lang.reflect.InvocationTargetException`

What should happen:
------------------------------
The game should start

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create an instance

2. Install forge

3. Launch it

Suspected cause:
---------------------------
Don't know. Forge maybe?

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/LogtD

Additional Info:
---------------------------
None

**Comment by peterix** [comment]
Remove java 9, use java 8.
