### ISSUE TITLE
French translate duplication

### ISSUE THREAD

**Issue by attilavv** [MultiMC/MultiMC5#2127]
![mult](https://user-images.githubusercontent.com/35277791/35585274-cee40b5a-05f7-11e8-9848-ca355744b95c.jpg)

In French translation it is duplacation.
For "Export Instance" in US possible French translate is "Exporter l'instance".

**Comment by peterix** [comment]
https://github.com/MultiMC/MultiMC5-translate/blob/master/fr.po#L2242-L2243

You could fix it. It looks easy :)

**Comment by peterix** [comment]
Pretty nmuch anything marked as `fuzzy` needs looking at and I don't quite understand the language beyong being able to spot some obviously wrong things...

This is probably wrong too:
https://github.com/MultiMC/MultiMC5-translate/blob/master/fr.po#L2310

**Comment by attilavv** [comment]
Yes that right.

msgid "Support MultiMC"
msgstr "À propos de MultiMC"

"A propos de" it is "about"
"Supporter MultiMC" tips and other donation is news in French. But "supporter" is massive used on Twitch.

I am locking for fix it, me or a member of my team.

**Comment by Azuxul** [comment]
It's done,
I have updated translation file with chnages of this issue.

It just remains to accept pull request.

**Comment by peterix** [comment]
Merged i :)

If you want to help wih the ttranslation some more, I'd suggest actually cloning the repository on your machine and using poedit to make changes:
https://poedit.net/
