### ISSUE TITLE
Unable to create instance using latest snapshot. (18w05a)

### ISSUE THREAD

**Issue by Veritas83** [MultiMC/MultiMC5#2128]
No matter which branch, stable or dev. Available versions to create an instance does not populate with the currently available snapshots.

I've tried completely removing and re-installing MultiMC to no avail. This has happened many times before. Usually it will resolve itself when the next snapshot is released. Thus making 18w05a completely unplayable using MultiMC until another snapshot is released.

Rarely switching between stable and dev branches has fixed it. Not this time thou.

<img src="https://i.gyazo.com/2dbeb75c7c6e0334ffa517507a12b6c1.png">

**Comment by peterix** [comment]
Fixed.

**Comment by peterix** [comment]
http://ci.multimc.org/builders/meta-update/builds/4790/steps/run-update/logs/stdio
