### ISSUE TITLE
Discord says playing "multimc" instead of "Minecraft"

### ISSUE THREAD

**Issue by danielzgtg** [MultiMC/MultiMC5#2131]
System Information
-----------------------------
MultiMC version: 0.6.1-1092

Operating System: Ubuntu 17.10

Summary of the issue or suggestion:
----------------------------------------------
Discord shows that I am playing "multimc".

What should happen:
------------------------------
Discord should show that I am playing "Minecraft".

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC.
- Discord will show "Playing multimc" in both the member list and "Games" settings.

2. Launch a vanilla 1.12.2 instance.
- Discord will still show "Playing multimc"

3. Close the instance, and Launch a forge 1.12.2 instance with DiscordSuite (workaround).
- Discord will now show "Playing Minecraft" in the member list (correctly), and
- Discord will still show "multimc Now playing!" in "Games" settings, and
- There will be an added game without a name but with hover text showing a path to the java binary.

Suspected cause:
---------------------------
- MultiMC might be telling Discord that it is a game.
- Discord might think that MultiMC is a game.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Log:
```
    0.114 W QMetaObject::connectSlotsByName: No matching signal for on_actionInstanceSettings_triggered()
    3.652 W Account "[EMAIL]" is now in use.
    4.849 W QCoreApplication::postEvent: Unexpected null receiver
   28.305 W Account "[EMAIL]" is no longer in use.
```

Discord developer console of detection: ![image](https://user-images.githubusercontent.com/25646384/35763240-ad600d3c-0875-11e8-9aa8-e13b1824e80c.png)
Member list in step 1 & 2: ![image](https://user-images.githubusercontent.com/25646384/35763269-6e901c68-0876-11e8-8db1-9c75d972e51a.png)
Games settings in step 1 & 2: ![image](https://user-images.githubusercontent.com/25646384/35763264-554be98a-0876-11e8-87d8-b9d18f958160.png)
Member list in step 3: ![image](https://user-images.githubusercontent.com/25646384/35763245-d6a2d7f6-0875-11e8-8f65-6d7896a46fd4.png)
Games settings in step 3: ![image](https://user-images.githubusercontent.com/25646384/35763250-06055186-0876-11e8-9833-70d320c830aa.png)
Member list with vanilla launcher: ![image](https://user-images.githubusercontent.com/25646384/35763351-3cccbb76-0878-11e8-92b5-eac6f9cfcd1a.png)
Games settings with vanilla launcher: ![image](https://user-images.githubusercontent.com/25646384/35763355-594ab8c0-0878-11e8-89ec-98f88b330104.png)

Additional Info:
---------------------------
Vanilla ***launcher*** is not detected as a game (correct).

**Comment by Dushess** [comment]
Since it detects IDEA and GoogleChrome as game, he just catch process on top (MultiMC) and show it as current active app.

**Comment by peterix** [comment]
I cannot do anything about Discord having features that are badly designed and implemented.
