### ISSUE TITLE
Upload Skin Unknown error

### ISSUE THREAD

**Issue by BillyGoatNinja326** [MultiMC/MultiMC5#2134]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------
While in the Manage Accounts section of MultiMC I cannot upload a skin file to any of my accounts. I continue to get an "unknown error" response and no uploading of skin.

What should happen:
------------------------------
I would like someone to look into this issue and see if there is a possibility of a corrupted MultiMC file somewhere or if the connecting destination for how it is ran is correct.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Clicked onto manage accounts. Clicked to highlight the appropriate account.
2. Clicked on upload skin and chose the model its based on for skin style.
3. Find file of skin I wish to upload and select.
4. Click Upload
**Error**
Unknown error occured

Suspected cause:
---------------------------
Possible that steps to which a skin need be uploaded are not appropriate due to website information changing or authorization of third party accounts to upload skin may not be supported anymore???

Logs/Screenshots:
----------------------------
Didn't up load any due to the simplistic nature of this

Additional Info:
---------------------------
THANK YOU FOR YOUR WONDERFUL LAUNCHER!!!!
I have a server I run and several that I play on both private and public so this helps to organize both the versions and the mod files used.

**Comment by peterix** [comment]
Well, I can't replicate your problem. Maybe it was the skin service having a hiccup? Do you still have problems with changing the skin? If so, get me the MultiMC log file (MultiMC.0.log) from right after you trigger the problem.

However, someone else reported that using the Alex skin didn't work. Sure enough, that is what happened. We have been using some very old code from before this stuff was stable. So, I'll fix that as part of this.

**Comment by peterix** [comment]
I found a condition under which this can happen.

When you use a `file://` URL when picking the skin on linux, it will fail. Using normal filesystem path works. MultiMC should normalize the path before trying to use it.

**Comment by peterix** [comment]
OK. This should have a few followups:
* implement setting the skin from remote URLs
* implement only changing the model

**Comment by peterix** [comment]
@BillyGoatNinja326 can you check the develop version and see if this fixed your problem?
At worst, we'll actually find out what problem it was.

**Comment by peterix** [comment]
Well, I'll just assume this is fine and close it, because I can't find any more problems with it. You should get better error dialog boxes now, if there is something wrong too.

**Comment by MummyPig-exe** [comment]
egg
