### ISSUE TITLE
Minecraft Crashed While Loading Mods

### ISSUE THREAD

**Issue by Fred1124** [MultiMC/MultiMC5#2139]
System Information
-----------------------------
MultiMC version:
0.6.1
Operating System:
Windows 10 Home
Summary of the issue or suggestion:
----------------------------------------------
Minecraft crashes in the mod loading phase.

What should happen:
------------------------------
Minecraft should launch into the home screen.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Add Mods

2.Run Minecraft

3.Wait for Crash

Suspected cause:
---------------------------
Guide-API mod

Logs/Screenshots:
----------------------------
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.133.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 2/11/18 8:37 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Level Up HP (leveluphp)
Caused by: java.lang.NoClassDefFoundError: kotlin/TypeCastException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:522)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: kotlin.TypeCastException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 46 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 931685000 bytes (888 MB) / 2041577472 bytes (1947 MB) up to 5622464512 bytes (5362 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx6032m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 55 mods loaded, 55 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version          | Source                                          | Signature                                |
	|:----- |:------------------- |:---------------- |:----------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft           | 1.12.2           | minecraft.jar                                   | None                                     |
	| UC    | mcp                 | 9.42             | minecraft.jar                                   | None                                     |
	| UC    | FML                 | 8.0.99.99        | forge-1.12.2-14.23.2.2611-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge               | 14.23.2.2611     | forge-1.12.2-14.23.2.2611-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | micdoodlecore       |                  | minecraft.jar                                   | None                                     |
	| UC    | appliedenergistics2 | rv5-stable-8     | appliedenergistics2-rv5-stable-8.jar            | None                                     |
	| UC    | baubles             | 1.5.2            | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UC    | bibliocraft         | 2.4.3            | BiblioCraft[v2.4.3][MC1.12.0].jar               | None                                     |
	| UC    | guideapi            | 1.12-2.1.4-57    | Guide-API-1.12-2.1.4-57.jar                     | None                                     |
	| UC    | bloodmagic          | @VERSION@        | BloodMagic-1.12.2-2.2.1-83.jar                  | None                                     |
	| UC    | codechickenlib      | 3.1.5.331        | CodeChickenLib-1.12.2-3.1.5.331-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | redstoneflux        | 2.0.1            | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UC    | brandonscore        | 2.3.7            | BrandonsCore-1.12-2.3.7.140-universal.jar       | None                                     |
	| UC    | chancecubes         | 1.12.2-3.1.0.217 | ChanceCubes-1.12.2-3.1.0.217.jar                | None                                     |
	| UC    | chiselsandbits      | 14.13            | chiselsandbits-14.13.jar                        | None                                     |
	| UC    | cofhcore            | 4.3.10           | CoFHCore-1.12.2-4.3.10.5-universal.jar          | None                                     |
	| UC    | cofhworld           | 1.1.1            | CoFHWorld-1.12.2-1.1.1.12-universal.jar         | None                                     |
	| UC    | densemetals         | 1.0.2            | densemetals-1.12.2-1.0.2.jar                    | None                                     |
	| UC    | thermalfoundation   | 2.3.10           | ThermalFoundation-1.12.2-2.3.10.6-universal.jar | None                                     |
	| UC    | draconicevolution   | 2.3.8            | Draconic-Evolution-1.12-2.3.8.279-universal.jar | None                                     |
	| UC    | enderstorage        | 2.4.2.126        | EnderStorage-1.12.2-2.4.2.126-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | exnihilocreatio     | 1.12-0.1.7       | exnihilocreatio-1.12-0.1.7.jar                  | None                                     |
	| UC    | extracells          | 2.5.11           | ExtraCells-1.12.2-2.5.11a48.jar                 | None                                     |
	| UC    | jei                 | 4.8.5.147        | jei_1.12.2-4.8.5.147.jar                        | None                                     |
	| UC    | mantle              | 1.12-1.3.1.21    | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UC    | tconstruct          | 1.12.2-2.9.0.55  | TConstruct-1.12.2-2.9.0.55.jar                  | None                                     |
	| UC    | extrautils2         | 1.0              | extrautils2-1.12-1.7.3.jar                      | None                                     |
	| UC    | zerocore            | 1.12-0.1.1.0     | zerocore-1.12-0.1.1.0.jar                       | None                                     |
	| UC    | bigreactors         | 1.12.2-0.4.5.46  | ExtremeReactors-1.12.2-0.4.5.46.jar             | None                                     |
	| UC    | ic2                 | 2.8.53-ex112     | industrialcraft-2-2.8.53-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
	| UC    | galacticraftcore    | 4.0.1.133        | GalacticraftCore-1.12.2-4.0.1.133.jar           | None                                     |
	| UC    | galacticraftplanets | 4.0.1.133        | Galacticraft-Planets-1.12.2-4.0.1.133.jar       | None                                     |
	| UC    | hatchery            | 2.1.2            | hatchery-1.12.2-2.1.2.jar                       | None                                     |
	| UC    | ichunutil           | 7.1.4            | iChunUtil-1.12.2-7.1.4.jar                      | None                                     |
	| UC    | hats                | 7.0.0            | Hats-1.12.2-7.0.2.jar                           | None                                     |
	| UC    | hatstand            | 7.0.0            | HatStand-1.12.2-7.0.1.jar                       | None                                     |
	| UC    | inventorypets       | 1.4.9.9b         | inventorypets-1.12-1.4.9.9b.jar                 | None                                     |
	| UC    | leafdecay           | 1.0.0.2          | leafdecay-1.0.0.2-mc1.12.2.jar                  | None                                     |
	| UC    | shadowmc            | 3.8.0            | ShadowMC-1.12-3.8.0.jar                         | None                                     |
	| UE    | leveluphp           | 1.1.1            | leveluphp-1.12.2-1.1.1.jar                      | None                                     |
	| UC    | malisiscore         | 1.12.2-6.4.0     | malisiscore-1.12.2-6.4.0.jar                    | None                                     |
	| UC    | malisisdoors        | 1.12.2-7.3.0     | malisisdoors-1.12.2-7.3.0.jar                   | None                                     |
	| UC    | moreplanets         | 2.0.12           | More-Planets-1.12.2-2.0.12-GC132.jar            | b3468b224a74e296555ad7efeb35f482e6f445de |
	| UC    | morph               | 7.1.2            | Morph-1.12.2-7.1.2.jar                          | None                                     |
	| UC    | nei                 | 2.4.1            | NotEnoughItems-1.12.2-2.4.1.233-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | harvestcraft        | 1.12.2o          | Pam's+HarvestCraft+1.12.2o.jar                  | None                                     |
	| UC    | pixelmon            | 6.1.0            | Pixelmon-1.12.2-6.1.0-universal.jar             | None                                     |
	| UC    | portalgun           | 7.0.0            | PortalGun-1.12.2-7.0.1.jar                      | None                                     |
	| UC    | projecte            | 1.12-PE1.0.0     | ProjectE-1.12-PE1.2.0.jar                       | None                                     |
	| UC    | rftools             | 7.27             | rftools-1.12-7.27.jar                           | None                                     |
	| UC    | sync                | 7.0.0            | Sync-1.12.2-7.0.1.jar                           | None                                     |
	| UC    | thermalexpansion    | 5.3.10           | ThermalExpansion-1.12.2-5.3.10.15-universal.jar | None                                     |
	| UC    | trashslot           | 8.4.6            | TrashSlot_1.12.1-8.4.6.jar                      | None                                     |
	| UC    | twilightforest      | 3.6.345          | twilightforest-1.12.2-3.6.345-universal.jar     | None                                     |
	| UC    | xaerominimap        | 1.14.8           | Xaeros_Minimap_1.14.8_Forge_1.12.jar            | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.133.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4835' Renderer: 'Intel(R) HD Graphics 6000'
	AE2 Version: stable rv5-stable-8 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

Additional Info:
---------------------------
https://paste.ee/p/hyva4

**Comment by Fred1124** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.133.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 2/11/18 8:55 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Level Up HP (leveluphp)
Caused by: java.lang.NoClassDefFoundError: kotlin/TypeCastException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:522)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: kotlin.TypeCastException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 46 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1395892464 bytes (1331 MB) / 2310537216 bytes (2203 MB) up to 5622464512 bytes (5362 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx6032m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 56 mods loaded, 56 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version           | Source                                          | Signature                                |
	|:----- |:------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft           | 1.12.2            | minecraft.jar                                   | None                                     |
	| UC    | mcp                 | 9.42              | minecraft.jar                                   | None                                     |
	| UC    | FML                 | 8.0.99.99         | forge-1.12.2-14.23.2.2611-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge               | 14.23.2.2611      | forge-1.12.2-14.23.2.2611-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | micdoodlecore       |                   | minecraft.jar                                   | None                                     |
	| UC    | appliedenergistics2 | rv5-stable-8      | appliedenergistics2-rv5-stable-8.jar            | None                                     |
	| UC    | baubles             | 1.5.2             | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UC    | bibliocraft         | 2.4.3             | BiblioCraft[v2.4.3][MC1.12.0].jar               | None                                     |
	| UC    | guideapi            | 1.12-2.1.4-57     | Guide-API-1.12-2.1.4-57.jar                     | None                                     |
	| UC    | bloodmagic          | @VERSION@         | BloodMagic-1.12.2-2.2.1-83.jar                  | None                                     |
	| UC    | codechickenlib      | 3.1.5.331         | CodeChickenLib-1.12.2-3.1.5.331-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | redstoneflux        | 2.0.1             | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UC    | brandonscore        | 2.3.7             | BrandonsCore-1.12-2.3.7.140-universal.jar       | None                                     |
	| UC    | chancecubes         | 1.12.2-3.1.0.217  | ChanceCubes-1.12.2-3.1.0.217.jar                | None                                     |
	| UC    | chiselsandbits      | 14.13             | chiselsandbits-14.13.jar                        | None                                     |
	| UC    | cofhcore            | 4.3.10            | CoFHCore-1.12.2-4.3.10.5-universal.jar          | None                                     |
	| UC    | cofhworld           | 1.1.1             | CoFHWorld-1.12.2-1.1.1.12-universal.jar         | None                                     |
	| UC    | densemetals         | 1.0.2             | densemetals-1.12.2-1.0.2.jar                    | None                                     |
	| UC    | thermalfoundation   | 2.3.10            | ThermalFoundation-1.12.2-2.3.10.6-universal.jar | None                                     |
	| UC    | draconicevolution   | 2.3.8             | Draconic-Evolution-1.12-2.3.8.279-universal.jar | None                                     |
	| UC    | enderstorage        | 2.4.2.126         | EnderStorage-1.12.2-2.4.2.126-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | exnihilocreatio     | 1.12-0.1.7        | exnihilocreatio-1.12-0.1.7.jar                  | None                                     |
	| UC    | extracells          | 2.5.11            | ExtraCells-1.12.2-2.5.11a48.jar                 | None                                     |
	| UC    | jei                 | 4.8.5.147         | jei_1.12.2-4.8.5.147.jar                        | None                                     |
	| UC    | mantle              | 1.12-1.3.1.21     | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UC    | tconstruct          | 1.12.2-2.9.0.55   | TConstruct-1.12.2-2.9.0.55.jar                  | None                                     |
	| UC    | extrautils2         | 1.0               | extrautils2-1.12-1.7.3.jar                      | None                                     |
	| UC    | zerocore            | 1.12-0.1.1.0      | zerocore-1.12-0.1.1.0.jar                       | None                                     |
	| UC    | bigreactors         | 1.12.2-0.4.5.46   | ExtremeReactors-1.12.2-0.4.5.46.jar             | None                                     |
	| UC    | ic2                 | 2.8.53-ex112      | industrialcraft-2-2.8.53-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
	| UC    | galacticraftcore    | 4.0.1.133         | GalacticraftCore-1.12.2-4.0.1.133.jar           | None                                     |
	| UC    | galacticraftplanets | 4.0.1.133         | Galacticraft-Planets-1.12.2-4.0.1.133.jar       | None                                     |
	| UC    | hatchery            | 2.1.2             | hatchery-1.12.2-2.1.2.jar                       | None                                     |
	| UC    | ichunutil           | 7.1.4             | iChunUtil-1.12.2-7.1.4.jar                      | None                                     |
	| UC    | hats                | 7.0.0             | Hats-1.12.2-7.0.2.jar                           | None                                     |
	| UC    | hatstand            | 7.0.0             | HatStand-1.12.2-7.0.1.jar                       | None                                     |
	| UC    | inventorypets       | 1.4.9.9b          | inventorypets-1.12-1.4.9.9b.jar                 | None                                     |
	| UC    | ironchest           | 1.12.2-7.0.34.820 | ironchest-1.12.2-7.0.34.820.jar                 | None                                     |
	| UC    | leafdecay           | 1.0.0.2           | leafdecay-1.0.0.2-mc1.12.2.jar                  | None                                     |
	| UC    | shadowmc            | 3.8.0             | ShadowMC-1.12-3.8.0.jar                         | None                                     |
	| UE    | leveluphp           | 1.1.1             | leveluphp-1.12.2-1.1.1.jar                      | None                                     |
	| UC    | malisiscore         | 1.12.2-6.4.0      | malisiscore-1.12.2-6.4.0.jar                    | None                                     |
	| UC    | malisisdoors        | 1.12.2-7.3.0      | malisisdoors-1.12.2-7.3.0.jar                   | None                                     |
	| UC    | moreplanets         | 2.0.12            | More-Planets-1.12.2-2.0.12-GC132.jar            | b3468b224a74e296555ad7efeb35f482e6f445de |
	| UC    | morph               | 7.1.2             | Morph-1.12.2-7.1.2.jar                          | None                                     |
	| UC    | nei                 | 2.4.1             | NotEnoughItems-1.12.2-2.4.1.233-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | harvestcraft        | 1.12.2o           | Pam's+HarvestCraft+1.12.2o.jar                  | None                                     |
	| UC    | pixelmon            | 6.1.0             | Pixelmon-1.12.2-6.1.0-universal.jar             | None                                     |
	| UC    | portalgun           | 7.0.0             | PortalGun-1.12.2-7.0.1.jar                      | None                                     |
	| UC    | projecte            | 1.12-PE1.0.0      | ProjectE-1.12-PE1.2.0.jar                       | None                                     |
	| UC    | rftools             | 7.27              | rftools-1.12-7.27.jar                           | None                                     |
	| UC    | sync                | 7.0.0             | Sync-1.12.2-7.0.1.jar                           | None                                     |
	| UC    | thermalexpansion    | 5.3.10            | ThermalExpansion-1.12.2-5.3.10.15-universal.jar | None                                     |
	| UC    | trashslot           | 8.4.6             | TrashSlot_1.12.1-8.4.6.jar                      | None                                     |
	| UC    | twilightforest      | 3.6.345           | twilightforest-1.12.2-3.6.345-universal.jar     | None                                     |
	| UC    | xaerominimap        | 1.14.8            | Xaeros_Minimap_1.14.8_Forge_1.12.jar            | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.133.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4835' Renderer: 'Intel(R) HD Graphics 6000'
	AE2 Version: stable rv5-stable-8 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
https://paste.ee/p/zKPOp

**Comment by tehbasshunter** [comment]
You're still missing forgelin.

**Comment by Fred1124** [comment]
Thank you
