### ISSUE TITLE
Crashing on any modpack instance (exitcode -1073741819)

### ISSUE THREAD

**Issue by merendero** [MultiMC/MultiMC5#2140]
MultiMC version: 0.6.1-develop-1188

Operating System: Windows 7

All modpacks I try to play crashes on startup (loads things up to the last step and then BAM). Tried multiple packs of multiple versions. Vanilla Minecraft plays just fine. I'm downloading the packs, placing them on MultiMC/mods folder and using the import option. I had the same issue before but managed to get it working for a day, then started crashing again. The log's last line is: Process crashed with exitcode -1073741819.

Log: https://paste.ee/p/DCsds#s=0&l=2022

Edit: forgot to mention, NVIDIA drivers are up to date (390.77) and Java ver. is Update 161 - 64 bits.

Thanks!

**Comment by peterix** [comment]
OK... this looks weird. According to this: https://borncity.com/win/2017/10/02/virtualbox-is-causing-file-system-error-1073741819/ it may be some sort of sound codec error.

It also crashed right after initializing sound.

So maybe that's not a coincidence?

Also see:
http://borncity.com/win/2016/12/10/windows-10-file-system-error-1073741819-extended-attributes-are-in-consistent/

**Comment by merendero** [comment]
I ended up uninstalling an unecessary Realtek HD audio software that was really not needed so thanks for the advice, but still getting the error. There's a difference in the last line of the log: 

[18:15:27] [Forestry Greenhouse Client/INFO] [forestry]: Starting greenhouse thread
[18:15:27] [main/INFO] [draconicevolution]: Checking Doc Versions
Process crashed with exitcode -1073741819.

I checked the pages you linked but my UAC has been disabled since Win7 installation, I never leave it on. I also tried to run the game without any sound but that doesn't work either. Gods that's annoying, got a new PC and Minecraft still giving me trouble haha.

**Comment by peterix** [comment]
Well, it's a hard crash of some sort...

This is what Mojang says about it: http://hopper.minecraft.net/help/exit-code/code-1073741819/

What I'd say is check what the Windows event log says. And try to find out what libraries are loaded into the `javaw.exe` process using Process Hacker. For that, see: https://github.com/MultiMC/MultiMC5/issues/2135#issuecomment-364040088

**Comment by merendero** [comment]
So I reinstalled Java, MultiMC and re-downloaded some packs. A few work and they are different MC versions. Vanilla still working fine (tried multiple versions) and some packs bring me this log:

https://paste.ee/p/HIvGm

There's this nvoglv64.DLL+0xc36f94 showing up as the problem but, as I mentioned, the drivers are up to date. Maybe there's something I could do with the NVIDIA panel? I'm quite new with NVIDIA stuff so I'm not sure.

I also tried the Process Hacker you suggested. Here's the result:

https://paste.ee/p/tAiNS

Again, thanks for the help.

**Comment by peterix** [comment]
That definitely look slike a GPU driver crash.

Can you post this? `E:\MultiMC\instances\FTBInfinity-3.0.2-1.7.10\minecraft\hs_err_pid7888.log`

**Comment by peterix** [comment]
OH...
avutil-ttv-51.dll
... avutil-ttv-51.dll is usually located in the 'c:\Program Files (x86)\Raptr Inc\Raptr\twitch\x64\' folder.

Remove this Raptr thing.

**Comment by merendero** [comment]
Sure
https://paste.ee/p/iDcTP

Weird, I searched this DLL but found nothing. I don't have anything Raptr related and the DLL isn't on the Twitch either.

**Comment by merendero** [comment]
Hey peterix, I got it working by downgrading the NVIDIA driver to a July/2017 version. It really is the damn driver. Thing is, no one else complained so I'm screwed. Just hoping this gets fixed somehow on an update. Thanks for your help!

**Comment by peterix** [comment]
Report it to nvidia. If you don't, they'll never know.

**Comment by Kore-Development** [comment]
If anybody is still getting this issue I fixed it by switch from Java 11 to Java 8.

**Comment by Kore-Development** [comment]
Before I was using AdoptOpenJDK 11, and now I'm using Oracle Java 8. I'm sure AdoptOpenJDK 8 and other versions of Java 8 would work too.
