### ISSUE TITLE
Skins Servers are always shown offline

### ISSUE THREAD

**Issue by ScribbleLP** [MultiMC/MultiMC5#2143]
System Information
-----------------------------
MultiMC version: 0.6.1-develop-1188

Operating System:Windows 10 Fall creators Update, win32

Summary of the issue or suggestion: 
---------------------------------
Skins Server are always down, help.mojang.com say they are up

Clicking on the refresh arrow to the right doesn't fix this

What should happen: 
------------------------------
Skins Icon should not appear Offline

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Since I can't resolve the problem I can't reproduce it, Sorry...

2. I tried to disable internet: All the other Icons get updated. Internet connection back up: Everything updates except for Skins

3.

Suspected cause:
---------------------------
Icon Issues?

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
[Screenshot](https://puu.sh/zmXXV/13b9b71bd5.png)
[Arrow doesn't refresh it](https://puu.sh/zmYe8/4f3da99ee1.gif)

Additional Info:
---------------------------

**Comment by peterix** [comment]
The old one has been decomissioned:
https://bugs.mojang.com/browse/WEB-985

**Comment by peterix** [comment]
I also:
* removed the web and account web status -- you can see their status by just opening them... So there's no point showing the status.
* Added the API status, because the API is used by MultiMC for certain tasks (and will be likely used for more in the future).

Fixed in develop.
