### ISSUE TITLE
World Load Crash

### ISSUE THREAD

**Issue by Fred1124** [MultiMC/MultiMC5#2145]
System Information
-----------------------------
MultiMC version:
0.6.1
Operating System:
Windows 10 Home
Summary of the issue or suggestion:
----------------------------------------------
Minecraft crashes as I load world

What should happen:
------------------------------
Minecraft should let me in the world

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add mods

2. Launch Minecraft

3. Create world

Suspected cause:
---------------------------
No Clue

Logs/Screenshots:
----------------------------
---- Minecraft Crash Report ----

WARNING: coremods are present:
  HammerCoreCore (HammerCore-1.12.2-1.9.6.5.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.133.jar)
  SFRCore (SolarFluxReborn_1.12.2-3.42r.jar)
  SRM-Core (secretroomsmod-1.12.2-5.2.7.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 2/14/18 11:35 AM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at com.wynprice.secretroomsmod.handler.HandlerUpdateChecker.onPlayerTick(HandlerUpdateChecker.java:59)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_854_HandlerUpdateChecker_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:364)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:190)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.wynprice.secretroomsmod.handler.HandlerUpdateChecker.onPlayerTick(HandlerUpdateChecker.java:59)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_854_HandlerUpdateChecker_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:364)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:190)

-- Player being ticked --
Details:
	Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP)
	Entity ID: 150
	Entity Name: Fred1124
	Entity's Exact location: 5708.28, 82.00, -18386.96
	Entity's Block location: World: (5708,82,-18387), Chunk: (at 12,5,13 in 356,-1150; contains blocks 5696,0,-18400 to 5711,255,-18385), Region: (11,-36; contains chunks 352,-1152 to 383,-1121, blocks 5632,0,-18432 to 6143,255,-17921)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@708cd5dd
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 663500880 bytes (632 MB) / 3225944064 bytes (3076 MB) up to 5622464512 bytes (5362 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx6032m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 77 mods loaded, 76 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                      | Version                      | Source                                          | Signature                                |
	|:--------- |:----------------------- |:---------------------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft               | 1.12.2                       | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                     | 9.42                         | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                     | 8.0.99.99                    | forge-1.12.2-14.23.2.2611-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                   | 14.23.2.2611                 | forge-1.12.2-14.23.2.2611-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | micdoodlecore           |                              | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | securitycraft           | v1.8.4.1                     | [1.12.x]+SecurityCraft+v1.8.4.1.jar             | None                                     |
	| UCHIJAAAA | appliedenergistics2     | rv5-stable-8                 | appliedenergistics2-rv5-stable-8.jar            | None                                     |
	| UCHIJAAAA | baubles                 | 1.5.2                        | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCHIJAAAA | bibliocraft             | 2.4.3                        | BiblioCraft[v2.4.3][MC1.12.0].jar               | None                                     |
	| UCHIJAAAA | guideapi                | 1.12-2.1.4-57                | Guide-API-1.12-2.1.4-57.jar                     | None                                     |
	| UCHIJAAAA | bloodmagic              | @VERSION@                    | BloodMagic-1.12.2-2.2.1-83.jar                  | None                                     |
	| UCHIJAAAA | codechickenlib          | 3.1.5.331                    | CodeChickenLib-1.12.2-3.1.5.331-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux            | 2.0.1                        | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | brandonscore            | 2.3.7                        | BrandonsCore-1.12-2.3.7.140-universal.jar       | None                                     |
	| UCHIJAAAA | chameleon               | 1.12-4.1.3                   | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCHIJAAAA | chancecubes             | 1.12.2-3.1.0.217             | ChanceCubes-1.12.2-3.1.0.217.jar                | None                                     |
	| UCHIJAAAA | chiselsandbits          | 14.13                        | chiselsandbits-14.13.jar                        | None                                     |
	| UCHIJAAAA | cofhcore                | 4.3.10                       | CoFHCore-1.12.2-4.3.10.5-universal.jar          | None                                     |
	| UCHIJAAAA | cofhworld               | 1.1.1                        | CoFHWorld-1.12.2-1.1.1.12-universal.jar         | None                                     |
	| UCHIJAAAA | cucumber                | 1.0.4                        | cucumber-1.12-1.0.4.jar                         | None                                     |
	| UCHIJAAAA | densemetals             | 1.0.2                        | densemetals-1.12.2-1.0.2.jar                    | None                                     |
	| UCHIJAAAA | thermalfoundation       | 2.3.10                       | ThermalFoundation-1.12.2-2.3.10.6-universal.jar | None                                     |
	| UCHIJAAAA | draconicevolution       | 2.3.8                        | Draconic-Evolution-1.12-2.3.8.279-universal.jar | None                                     |
	| UCHIJAAAA | enderstorage            | 2.4.2.126                    | EnderStorage-1.12.2-2.4.2.126-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | exnihilocreatio         | 1.12-0.1.7                   | exnihilocreatio-1.12-0.1.7.jar                  | None                                     |
	| UCHIJAAAA | extracells              | 2.5.11                       | ExtraCells-1.12.2-2.5.11a48.jar                 | None                                     |
	| UCHIJAAAA | jei                     | 4.8.5.147                    | jei_1.12.2-4.8.5.147.jar                        | None                                     |
	| UCHIJAAAA | mantle                  | 1.12-1.3.1.21                | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UCHIJAAAA | tconstruct              | 1.12.2-2.9.0.55              | TConstruct-1.12.2-2.9.0.55.jar                  | None                                     |
	| UCHIJAAAA | extrautils2             | 1.0                          | extrautils2-1.12-1.7.3.jar                      | None                                     |
	| UCHIJAAAA | zerocore                | 1.12-0.1.1.0                 | zerocore-1.12-0.1.1.0.jar                       | None                                     |
	| UCHIJAAAA | bigreactors             | 1.12.2-0.4.5.46              | ExtremeReactors-1.12.2-0.4.5.46.jar             | None                                     |
	| UCHIJAAAA | forgelin                | 1.6.0                        | Forgelin-1.6.0.jar                              | None                                     |
	| UCHIJAAAA | cfm                     | 4.1.5                        | furniture-4.1.5-1.12.2.jar                      | None                                     |
	| UCHIJAAAA | ic2                     | 2.8.53-ex112                 | industrialcraft-2-2.8.53-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | galacticraftcore        | 4.0.1.133                    | GalacticraftCore-1.12.2-4.0.1.133.jar           | None                                     |
	| UCHIJAAAA | galacticraftplanets     | 4.0.1.133                    | Galacticraft-Planets-1.12.2-4.0.1.133.jar       | None                                     |
	| UCHIJAAAA | ichunutil               | 7.1.4                        | iChunUtil-1.12.2-7.1.4.jar                      | None                                     |
	| UCHIJAAAA | gravitygun              | 7.0.0                        | GravityGun-1.12.2-7.0.1.jar                     | None                                     |
	| UCHIJAAAA | hammercore              | 1.9.6.5                      | HammerCore-1.12.2-1.9.6.5.jar                   | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHIJAAAA | hatchery                | 2.1.2                        | hatchery-1.12.2-2.1.2.jar                       | None                                     |
	| UCHIJAAAA | hats                    | 7.0.0                        | Hats-1.12.2-7.0.2.jar                           | None                                     |
	| UCHIJAAAA | hatstand                | 7.0.0                        | HatStand-1.12.2-7.0.1.jar                       | None                                     |
	| UCHIJAAAA | teslacorelib            | 1.0.12                       | tesla-core-lib-1.12-1.0.12.jar                  | None                                     |
	| UCHIJAAAA | industrialforegoing     | 1.12.2-1.12.1                | Industrial-Foregoing-Mod-1.12.2.jar             | None                                     |
	| UCHIJAAAA | inventorytweaks         | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar                    | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | ironchest               | 1.12.2-7.0.34.820            | ironchest-1.12.2-7.0.34.820.jar                 | None                                     |
	| UCHIJAAAA | leafdecay               | 1.0.0.2                      | leafdecay-1.0.0.2-mc1.12.2.jar                  | None                                     |
	| UCHIJAAAA | shadowmc                | 3.8.0                        | ShadowMC-1.12-3.8.0.jar                         | None                                     |
	| UCHIJAAAA | leveluphp               | 1.1.1                        | leveluphp-1.12.2-1.1.1.jar                      | None                                     |
	| UCHIJAAAA | malisiscore             | 1.12.2-6.4.0                 | malisiscore-1.12.2-6.4.0.jar                    | None                                     |
	| UCHIJAAAA | malisisdoors            | 1.12.2-7.3.0                 | malisisdoors-1.12.2-7.3.0.jar                   | None                                     |
	| UCHIJAAAA | mcmultipart             | 2.3.0                        | MCMultiPart-Mod-1.12.2.jar                      | None                                     |
	| UCHIJAAAA | moreplanets             | 2.0.12                       | More-Planets-1.12.2-2.0.12-GC132.jar            | b3468b224a74e296555ad7efeb35f482e6f445de |
	| UCHIJAAAA | morph                   | 7.1.2                        | Morph-1.12.2-7.1.2.jar                          | None                                     |
	| UCHIJAAAA | mysticalagriculture     | 1.6.2                        | Mystical-Agriculture-1.12.jar                   | None                                     |
	| UCHIJAAAA | nei                     | 2.4.1                        | NotEnoughItems-1.12.2-2.4.1.233-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | harvestcraft            | 1.12.2o                      | Pam's+HarvestCraft+1.12.2o.jar                  | None                                     |
	| UCHIJAAAA | portalgun               | 7.0.0                        | PortalGun-1.12.2-7.0.1.jar                      | None                                     |
	| UCHIJAAAA | projecte                | 1.12-PE1.0.0                 | ProjectE-1.12-PE1.2.0.jar                       | None                                     |
	| UCHIJAAAA | thermalexpansion        | 5.3.10                       | ThermalExpansion-1.12.2-5.3.10.15-universal.jar | None                                     |
	| UCHIJAAAA | redstonearsenal         | 2.3.10                       | RedstoneArsenal-1.12.2-2.3.10.4-universal.jar   | None                                     |
	| UCHIJAAAA | rftools                 | 7.27                         | rftools-1.12-7.27.jar                           | None                                     |
	| UCHIJAAAA | secretroomsmod          | 5.2.7                        | secretroomsmod-1.12.2-5.2.7.jar                 | None                                     |
	| UCHIJAAAA | simplyjetpacks          | 2.2.2.28                     | SimplyJetpacks2-1.12.2-2.2.2.28.jar             | None                                     |
	| UCHIJAAAA | solarfluxreborn         | 3.42r                        | SolarFluxReborn_1.12.2-3.42r.jar                | None                                     |
	| UCHIJAAAA | somanyenchantments      | 0.3.0                        | SoManyEnchantments+V0.3.1+(1.12.2).jar          | None                                     |
	| UCHIJAAAA | soulshardstow           | 1.12-2.7.4-53                | SoulShards-TOW-1.12-2.7.4-53.jar                | None                                     |
	| UCHIJAAAA | storagedrawers          | 1.12-5.2.5                   | StorageDrawers-1.12.2-5.3.4.jar                 | None                                     |
	| UCHIJAAAA | sync                    | 7.0.0                        | Sync-1.12.2-7.0.1.jar                           | None                                     |
	| UCHIJAAAA | trashslot               | 8.4.6                        | TrashSlot_1.12.1-8.4.6.jar                      | None                                     |
	| UCHIJAAAA | twilightforest          | 3.6.345                      | twilightforest-1.12.2-3.6.345-universal.jar     | None                                     |
	| UCHIJAAAA | veinminer               | 0.38.1                       | Vein-Miner-Mod-1.12.jar                         | None                                     |
	| UCHIJAAAA | veinminermodsupport     | 0.38.1                       | Vein-Miner-Mod-1.12.jar                         | None                                     |
	| UCHIJAAAA | xaerominimap            | 1.14.8                       | Xaeros_Minimap_1.14.8_Forge_1.12.jar            | None                                     |
	| UCHIJAAAA | teslacorelib_registries | 1.0.12                       | tesla-core-lib-1.12-1.0.12.jar                  | None                                     |
	| UD        | solarfluxreborncore     | 3.42r                        | minecraft.jar                                   | None                                     |

	Loaded coremods (and transformers): 
HammerCoreCore (HammerCore-1.12.2-1.9.6.5.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.133.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
SFRCore (SolarFluxReborn_1.12.2-3.42r.jar)
  com.pengu.solarfluxreborn.core.SFRSerializedTransformer
SRM-Core (secretroomsmod-1.12.2-5.2.7.jar)
  com.wynprice.secretroomsmod.core.UVTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv5-stable-8 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [GCEntityPlayerMP['Fred1124'/150, l='New World', x=5708.28, y=82.00, z=-18386.96]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

Additional Info:
---------------------------
https://paste.ee/p/HmfcT

**Comment by peterix** [comment]
Sounds like a mod bug. Specifically a broken update checker:
https://github.com/AbrarSyed/SecretRoomsMod-forge/blob/master/src/main/java/com/wynprice/secretroomsmod/handler/HandlerUpdateChecker.java

Report it to the author of the secret rooms mod here:  https://github.com/AbrarSyed/SecretRoomsMod-forge/issues

If this is still a problem.

**Comment by Fred1124** [comment]
Do you know where to put the code to?

**Comment by peterix** [comment]
Just disable the update checker in the mod's config...

**Comment by peterix** [comment]
You know the mod's name, it shouldn'tt be that hard to find.
