### ISSUE TITLE
Can't import instance (includes testing old solutions + Logfile)

### ISSUE THREAD

**Issue by PumaBlack** [MultiMC/MultiMC5#2146]
Win7 64 Bit
MultiMC - 0.6.1 - 1177

I am not able to import an instance (exported with MMC). 
Error: "Unable to commit instance"
Solution [here](https://github.com/MultiMC/MultiMC5/issues/1971) was tested. No result.

My log: [pastebin](https://pastebin.com/Q70wZHL7)

What else can i do? Thanks in advance.

**Comment by peterix** [comment]
Now that's odd.
```

  286.981 W Failed to move "D:/Spiele (Install)/MultiMC/instances/_MMC_TEMP/{7597431d-ac63-4457-b4c7-40657394aa42}" to "D:/Spiele (Install)/MultiMC/instances/cbcb"
  286.981 D Failed to commit instance "cbcb" Initiating backoff: 1
  286.981 D Adding  "icons/Slimeball.png"
  287.480 W Failed to move "D:/Spiele (Install)/MultiMC/instances/_MMC_TEMP/{7597431d-ac63-4457-b4c7-40657394aa42}" to "D:/Spiele (Install)/MultiMC/instances/cbcb"
  287.480 D Failed to commit instance "cbcb" Initiating backoff: 2
  288.494 W Failed to move "D:/Spiele (Install)/MultiMC/instances/_MMC_TEMP/{7597431d-ac63-4457-b4c7-40657394aa42}" to "D:/Spiele (Install)/MultiMC/instances/cbcb"
  288.494 D Failed to commit instance "cbcb" Initiating backoff: 4
  290.499 W Failed to move "D:/Spiele (Install)/MultiMC/instances/_MMC_TEMP/{7597431d-ac63-4457-b4c7-40657394aa42}" to "D:/Spiele (Install)/MultiMC/instances/cbcb"
  290.502 D Failed to commit instance "cbcb" Initiating backoff: 8
  294.513 W Failed to move "D:/Spiele (Install)/MultiMC/instances/_MMC_TEMP/{7597431d-ac63-4457-b4c7-40657394aa42}" to "D:/Spiele (Install)/MultiMC/instances/cbcb"
  294.516 C Task "FolderInstanceStaging(0x66e01b8)" failed:  "Failed to commit instance, even after multiple retries. It is being blocked by something."
```

Now, what's happening is that MultiMc can't move the folder finished instance folder. That's really the final step.
It does try several times, in the hope that whatever has been blocking the move will stop blocking it. Usually that's antivirus scanning, where the AV vendor just assumes that you don't move things right after creating them, locks the files in place and checks them.

So, maybe whitelisting the `instances/_MMC_TEMP` in whatever AV software you have could help?

The other causes could be:
* Broken filesystem permissions
* `instances/_MMC_TEMP` and `instances` being on different filesystems (the move must be trivial/atomic, that's the whole point of it)

**Comment by PumaBlack** [comment]
I'll check that. Thanks for the quick response and the hints.

**Comment by peterix** [comment]
Assuming this got fixed, closing.
