### ISSUE TITLE
Instance with name starting with a "." is invisible

### ISSUE THREAD

**Issue by africalinguist** [MultiMC/MultiMC5#2154]
System Information
-----------------------------
MultiMC version: 0.6.1 develop-1107

Operating System: Ubuntu 16.04

Summary of the issue or suggestion:
----------------------------------------------
When I create an instance thats name starts with a "." the instance does not show up. I investigated and renamed the instance folder without the period, it showed up in the list immedialy

What should happen:
------------------------------
MultiMC should compensate and replace the period with "_" or remove it from the folder name

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. create an instance with a name starting with "."

2. rename the instance folder without the period

Suspected cause:
---------------------------
It is a hidden folder because of the period

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![screenshot from 2018-02-18 18-41-47](https://user-images.githubusercontent.com/26539285/36351628-6dfa4730-14db-11e8-85d1-d2f952f3e3cf.png)

Additional Info:
---------------------------

**Comment by peterix** [comment]
Should be fixed in develop.
