### ISSUE TITLE
MultiMC thinks that my mojang account isn't premium and doesn't let me log in

### ISSUE THREAD

**Issue by iiiiiiiiiiiinst** [MultiMC/MultiMC5#2156]
System Information
-----------------------------
MultiMC version: 
MultiMC 0.6.1

Operating System: 
Windows 10

Summary of the issue or suggestion:
----------------------------------------------
 I tried to log in to MultiMC with my mojang account and it said: Authentication server didn't specify a currently selected profile. The account exists, but likely isn't premium. Which isn't true, my account is premium. I don't know how to prove MultiMC that my account is premium and I d

What should happen:
------------------------------
MultiMC should let me log in with my account 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Open MultiMC

2.Go to Manage accounts

3.Click on Add

4.Enter your e-mail adress and your password

5.I don't know why it does this to me

Suspected cause:
---------------------------
I have no clue

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![login multimc](https://user-images.githubusercontent.com/36629113/36380349-3d619090-1582-11e8-9759-6b4ade809583.PNG)

Additional Info:
---------------------------
I hope it get fixed
Thank you for reading it all!

**Comment by peterix** [comment]
Well, all I can say is that this is what the available documentation is:
http://wiki.vg/Authentication#Response

MultiMC is sending the `agent`:
https://github.com/MultiMC/MultiMC5/blob/develop/api/logic/minecraft/auth/flows/AuthenticateTask.cpp#L52-L59

So, the request should be correct, and the response doesn't have a current profile for Minecraft.

Either the account is not premium (most likely), or this is some error on the Mojang side (less likely), or the protocol changed and MultiMC needs to change (I hope not...).

**Comment by peterix** [comment]
What is your Minecraft name or uuid?

Are you using any 'alt dispensers' or other such stuff?

**Comment by P3rf3ctXZer0** [comment]
Quick question @peterix can you double check minecraft account security - more and more people keep trying to steal my account. I am on the dev build of multimc - wanted to help test and it plays nicer with windows 10.

**Comment by peterix** [comment]
Double check what exactly?

**Comment by P3rf3ctXZer0** [comment]
Not sure I am not a coder. I fear there may be a loophole though.

**Comment by peterix** [comment]
Like any other piece of code reading the auth tokens from disk? Or any other running piece of code on your computer reading the password from memory as you type it?

I can't do anything about that.

**Comment by peterix** [comment]
That said, I am closing this because the OP is not responding. If you have questions, ask on Discord.
