### ISSUE TITLE
When I click on my launcher to start, it shows the following error '' MultiMC has stopped working ''.

### ISSUE THREAD

**Issue by Dejotah** [MultiMC/MultiMC5#2158]
I had the _TLauncher_ until yesterday, but I installed MultiMC with the intention of having a better Launcher, so it made the same error, I decided to remove the TLauncher and reboote, it worked perfectly, I even put mods in the 3 versions that I used to play in the TLauncher, by yesterday it worked perfectly. But today when I woke up and went to play. Unfortunately, this error occurs without my being able to change.

Help?

**Comment by peterix** [comment]
If you get a fresh copy from https://multimc.org/, does that work?

**Comment by peterix** [comment]
No response, closing.
