### ISSUE TITLE
Wrong skin server status

### ISSUE THREAD

**Issue by Janrupf** [MultiMC/MultiMC5#2159]
###System Information
-----------------------------
MultiMC version:
MultiMC 5 build 0.6.1-1092 lin64

Operating System:
Linux Min 18.3 (Cinnamon edition) x64

###Summary of the issue or suggestion:
----------------------------------------------
MultiMC says that the skin server is offline, but it isn't. Screenshots below...

###What should happen:
------------------------------
It should display that the skin server is online

###Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC, thats it

Suspected cause:
---------------------------
No idea, maybe broken link or something?

Logs/Screenshots:
----------------------------
![image](https://user-images.githubusercontent.com/25827180/36440959-69b69948-1671-11e8-8c6e-8c033f81549a.png)

**Comment by brodycas3** [comment]
Aware and fixed in Develop version.

**Comment by Janrupf** [comment]
Yep, thank you, updating to dev fixed it :)

**Comment by hyuntoe** [comment]
5th April 2018
I'm using MMC5 ver 0.6.1-1177 on win32 ( Windows10 )

exactly same issue :(

when will you release the next ver?

**Comment by Janrupf** [comment]
Maybe this weekend ;)

**Comment by peterix** [comment]
Dupliacte of https://github.com/MultiMC/MultiMC5/issues/2143
