### ISSUE TITLE
[Feature Request] Allow building modpacks from online databases

### ISSUE THREAD

**Issue by kreezxil** [MultiMC/MultiMC5#2160]
TwitchApp and previously CurseLauncher allowed you to build your modpack from the CurseForge library. However, TwitchApp, has begun to break down and there doesn't seem to be a fix in sight. I've reported it.

I'd like to see this functionality brought over to MultiMC. The ability to browse the mods for the branch of the forge the pack uses and add mods to it easily thusly.

If other databases exist, accessing them would be also be great.

And finally be able to export a curseforge compliant pack file.

**Comment by Janrupf** [comment]
Could be combined with #2124

**Comment by peterix** [comment]
I am not going to do anything that interacts with curse directly.

**Comment by peterix** [comment]
And I will definitely not use the curse pack format. It is simply worse than MultiMC instances.

**Comment by peterix** [comment]
The only online database I am willing to consider is my own, with full control over the data formats and no way for a third party to kill it off.

**Comment by peterix** [comment]
As for the details of what is very likely going to happen... Consider this reddit comment thread:
https://www.reddit.com/r/feedthebeast/comments/7xlr77/realistically_speaking_how_feasible_would_it_be/dua2ppq/

**Comment by peterix** [comment]
As for the old FTB stuff... it is a modpack platform. I don't see how it would combine with this in any sensible way. It's more of a separate system for grabbing modpacks, similarly to how I would like to keep curse/twitch a separate system for grabbing modpacks and not depend on it in any way that would cripple MultiMC if access to it was denied in the future.

**Comment by kreezxil** [comment]
I don't see the Curse API vanishing anytime soon. And this being Open
Source software, people can expect that things like that might happen in
the future, and they can expect that as long ans the Open Source initiative
continues that at that point in the future when things change the software
will change too. But to be stalwart and not even provide a capability based
upon a fear is the equivalent of shouting "The King is Dead!" when the king
is not dead at all.

Also, no one is going to flock to your database so long as Curse continues
to share revenue with modders, mod pack designers, resource pack creators,
and other various forms of game altering extension developers. They've been
doing it since their creation going on at least a minimum of 4 years now.
It is the primary reason you'll see that when someone puts in their
overview license that you may not distribute their mod via any other
platform except for CurseForge.com. Because if their creation is elsewhere
they won't get Curse Reward Points from it.

Yes, you'll get people going to your database, but what draw will they have
for doing it? You have a chance right now, while the Curse/Twitch team
twiddles it's thumbs to get some major notoriety by allowing MultiMC to
build mod packs thru the use of the Curse API. And it would be super nice
if you could export said modpacks in the Curse approved format.Granted one
can simply copy the configs and mods over to a profile made in the Twitch
Launcher and then export and have it just the same. But why make things
difficult and make the little llamas jump unnecessarily over fences?

**Comment by peterix** [comment]
1. There is no usable Curse API. I would have to reverse engineer the protocols AND force everyone to have a goddamn Curse account. And have I mentioned it is completely undocumented, and could change without warning? You want me to make MultiMC depend on that? THAT is completely insane and unacceptable on so many levels.

2. I think you misunderstood what I said. I am not going to host any data. Have you ever heard of a search engine? Or an index? That's what I am willing to build and use. I can feed it the curse metadata, and any other metadata from any other source, just fine. On a server. Where I have good control over what is happening and can correct problems before they get to the users. With no need for cooperation, or rehosting of mods.

So, no. Absolutely not. Interacting directly with Curse is a great way to walk into a trap. And I do not need to engage in anal alpinism.

**Comment by peterix** [comment]
From a logistical point of view, having control over the metadata service (https://v1.meta.multimc.org) is absolutely critical. It means that if there is any problem in the platforms it gathers data from, I am likely the only one affected by it, and I have time to react.

If MultiMC connects to some random API of someone else... and they only care about their own client and nothing else... what do I end up with? The first change they make means I'm pushing software updates on a very tight schedule to every MultiMC user. I might be on a business trip at the time. I might not be able to even do it in weeks, while everything is burning. Pushing updates costs money too.

Would you want to be in this situation? If yes, go ahead and have fun.

I want to be in a situation where if I react to something upstream breaking after a few days or a week, 99.99% of the users will not notice. I also want to be able to monkey patch stuff until there is a proper solution. It allows me to sleep at night and hopefully, in the future, will allow me to not burn most of my vacation time on emergencies and changes that need to be pushed or everything will break...

**Comment by peterix** [comment]
All of this would be very different if it was possible to cooperate with Curse directly. We talked some years ago. Their conditions (only doing this on linux) were not acceptable. I couldn't think straight at the mere mention of Curse for a few years...

**Comment by harleypig** [comment]
There is https://cfwidget.com but I don't know how tightly the author is working with curseforge. That api has been available since 2013.
