### ISSUE TITLE
MultiMC Crashing when Loading Modded clients

### ISSUE THREAD

**Issue by YoshiPlays** [MultiMC/MultiMC5#2162]
System Information
-----------------------------
MultiMC version: 0.6.1-1177

Operating System: win32

Summary of the issue or suggestion: The game will crash when I try to load any modded client. Vanilla works fine, but when I try Forge / Liteloader, it doesn't work. It's been working since October of 2017, but now it suddenly doesn't.
----------------------------------------------

What should happen:
------------------------------
Game starts as normally

Suspected cause:
---------------------------
I installed JDK (Java development kit) yesterday and haven't loaded MultiMC since today. That might be the root cause

Logs/Screenshots:
----------------------------
https://paste.ee/p/aC933

**Comment by tehbasshunter** [comment]
You need Java 8. 9 doesn't work.
