### ISSUE TITLE
Launching instances directly using -l / --launch not working (anymore?)

### ISSUE THREAD

**Issue by Gambleon** [MultiMC/MultiMC5#2163]
System Information
-----------------------------
MultiMC version: 0.6.1-develop-1110

Operating System: ArchLinux (lin64)

Summary of the issue or suggestion: 
----------------------------------------------
Instances cannot be launched (anymore?) by using command line arguments

What should happen: 
------------------------------
The specified instance should launch and the MultiMC window close.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open Terminal

2. `MultiMC -l <instanceId>` or `MultiMC --launch <instanceId>` with instanceId being the folder name living withing instances/ which should be started. This has been verified using a pre-launch command and writing the value to disk.

The instanceId was "AgeOfEngineering-1.1.2" in case dots or hyphens cause errors...

3. Wait for MultiMC to start and recognize that no instance is being launched

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: [mmc-launch.log](https://pastebin.com/gBPbxGTh) [mmc-launch2.log](https://pastebin.com/2c9rwhKb)

Does anybody know why this feature does not work anymore?

**Comment by Gambleon** [comment]
I thought this was a nice and useful feature...

**Comment by peterix** [comment]
And it is still there.

Here is a log fragment that shows it working:
```
[peterix ~/minecraft/src/MultiMC]$ multimc -l 1.11.2
    0.001 D <> Log initialized.
    0.008 D MultiMC 5, (c) 2013-2018 MultiMC Contributors
    0.008 D Version                    :  "0.6.1-custom"
    0.008 D Git commit                 :  "22b32fce126a0de8d002f67048792a89513f4e8a"
    0.008 D Git refspec                :  "refs/heads/develop"
    0.008 D Work dir before adjustment :  "/home/peterix/minecraft/src/MultiMC"
    0.008 D Work dir after adjustment  :  "/home/peterix/.local/share/multimc"
    0.008 D Adjusted by                :  "XDG standard /home/peterix/.local/share/multimc"
    0.008 D Binary path                :  "/usr/bin"
    0.008 D Application root path      :  "/usr"
    0.008 D ID of instance to launch   :  "1.11.2"
    0.008 D <> Paths set.
```

It looks like the command line option wasn't there, or didn't get passed through by the scripts?

**Comment by Gambleon** [comment]
I just tried it again - and it works. I could've sworn it did not work back then and I tested it for sure...
