### ISSUE TITLE
Crash when making new worlds

### ISSUE THREAD

**Issue by coolman9902** [MultiMC/MultiMC5#2166]
System Information
-----------------------------
MultiMC version:
1.6.1-1177
Operating System:
windows 10
Summary of the issue or suggestion:
----------------------------------------------
minecraft/muti-mc crashes when loading/creating a new world

What should happen:
------------------------------
load minecraft - no problems
generate new world-crashes

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------
dont know

Logs/Screenshots:
----------------------------
  [https://paste.ee/p/Ebu5Q](url)

Additional Info:
---------------------------

**Comment by Janrupf** [comment]
This is not MultiMC's fault,
`mapmakingtools.handler.ScreenRenderHandler.onPreRenderGameOverlay(ScreenRenderHandler.java:81)` is causing the error.
So Mapmakingutils is causing the crash... A mod or something?

**Comment by coolman9902** [comment]
yes i tried to get rid of but then a new mod is the problem

**Comment by coolman9902** [comment]
also it runs fine on the minecraft launcher it only on mutimc that it crashes

**Comment by coolman9902** [comment]
fixed it it was mapmaker mod i edited the config to turn off the overlay thx for your help
