### ISSUE TITLE
Idea - Implement "newest version" option in version lists

### ISSUE THREAD

**Issue by africalinguist** [MultiMC/MultiMC5#2167]
It would be good if you could have two more options in the version list, 
1. Newest version and 
2. Newest snapshot
these would be good to have, the instances could check for updates on multimc start, then download them when the "download all" button is pressed or when the instance is run

**Comment by Janrupf** [comment]
Was thinking about this too. Could be inregrated with Modpack version handlers.

**Comment by peterix** [comment]
If vanilla was handled like a modpack platform, sure :)
