### ISSUE TITLE
MultiMc it wont open

### ISSUE THREAD

**Issue by Kirolos2011** [MultiMC/MultiMC5#2168]
System Information
-----------------------------
MultiMC version: 0.6.1

Operating System: Windows 10

Summary of the issue or suggestion: It tells me that it does not find the file to start MULTIMC What can I do?
----------------------------------------------

What should happen: Windows tell me it isn't find MultiMc file 
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Janrupf** [comment]
Do you mean when you try to start it from your desktop? If so, check where the link points to and if the file specified there exists

**Comment by peterix** [comment]
Can you tke a screenshot of what is Windows telling you?

**Comment by peterix** [comment]
Assuming this got fixed, closing.
