### ISSUE TITLE
AL lib: (EE) alc_cleanup: 1 device not closed

### ISSUE THREAD

**Issue by BiggieCheese1234** [MultiMC/MultiMC5#2169]
I have been having this issue for a while now. I have tried updating forge and disabling splash screen and none of those worked. The crash happens about 2 minutes once I start my world. https://paste.ee/p/xCkaJ this is the crash log.

**Comment by Janrupf** [comment]
`AL lib: (EE) alc_cleanup: 1 device not closed`  is just happening because Minecraft crashes!
```
java.lang.NullPointerException: Exception in server tick loop
	at com.flansmod.apocalypse.common.CommonProxyApocalypse.sendPlayerToApocalypse(CommonProxyApocalypse.java:230)
[...]
```
Flansmod is the problem... Maybe Apocalypse flan or something?

**Comment by peterix** [comment]
No response, closing.
