### ISSUE TITLE
Forge versions outdated (Linux)

### ISSUE THREAD

**Issue by LuciousLisa** [MultiMC/MultiMC5#2170]
System Information
-----------------------------
MultiMC version: 0.6.1-develop-1110 on lin64

Operating System: Debian 9

Summary of the issue or suggestion:
----------------------------------------------
Latest version of Forge for Minecraft 1.12.2 is 14.23.2.2619.
Highest available version of Forge in MultiMC is 14.23.1.2589.

What should happen:
------------------------------
The latest Forge version should be available in the 'Select Forge version' window in MultiMC.

Steps to reproduce the issue:
-------------------------------------------------------------
1. Create new (vanilla) instance in MultiMC

2. Edit instance

3. Select tab 'Version'

4. Click 'Install Forge'

5. Scroll up

Suspected cause:
---------------------------
Unknown

Logs/Screenshots:
----------------------------
https://i.imgur.com/5GKRZVK.png

Additional Info:
---------------------------
I have also installed MultiMC in a Windows 7 VM. The problem does not occur in version 0.6.1-develop-1195 on win32. The list is fully updated on that instance.  
Instances that have been created with the latest Forge version in the Windows 7 VM version of MultiMC cannot be launched as a Linux instance after export/import.

**Comment by peterix** [comment]
As you can see, it is right there on top:
https://v1.meta.multimc.org/net.minecraftforge/

And in the UI:
![image](https://user-images.githubusercontent.com/203326/36676286-8f3e5a68-1b0b-11e8-8e51-778e289b18b2.png)

So, something weird must be going on on your machine. Can you share the `MultiMC.0.log` from right after you try to reproduce the problem? It should be in the data folder along with all the other things (`instances`, `meta`, `multimc.cfg`, and so on).

**Comment by LuciousLisa** [comment]
My file is written with a dash, I'm assuming this is what you mean though, right?
[MultiMC-0.log](https://pastebin.com/w3fp9bit)

**Comment by peterix** [comment]
Alright, it failed to initialize the OpenSSL libraries. Try the workaround from #1784 -- it should help.

**Comment by LuciousLisa** [comment]
Yep, resolved. For future reference, these were the (only) files that I needed to remove: https://i.imgur.com/4ZvstuW.png  
Thank you for the support!

**Comment by peterix** [comment]
Alright. One more reason to stop distributing Qt on linux :)
