### ISSUE TITLE
Allow running the same instance multiple times at the same time

### ISSUE THREAD

**Issue by TNTUP** [MultiMC/MultiMC5#2175]
System Information
-----------------------------
MultiMC version: 0.6.1-develop-1197

Operating System: Windows 10 x64 Professional

Summary of the issue or suggestion:
----------------------------------------------
Allow running more than one instance with a w/o warning. Mojang's launcher allows that and prints a warning. Shouldn't cause issues because I've been running the same instances on MagicLauncher for years without issues. 

What should happen:
------------------------------

Should be able to launch the same instance if already running

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch one instance

2. Try to launch the same instance already running

3. SSSSSSSSSSSSSS boom.

Suspected cause:
---------------------------
MultiMC does not allow running the same instance if already running

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Don't think a suggestion requires a log?

Additional Info:
---------------------------

Thats all  :) PS: Bring the tray icon back (I have replied back to) <3

**Comment by peterix** [comment]
It does cause issues, some of them non-trivial. The warning is well placed, and I decided to not even support this based on what can happen.

Maybe if you play vanilla and only connect to servers? But even then your server list can get corrupted.

**Comment by TNTUP** [comment]
Been running MagicLauncher for years and I didn't experience corruptions. Using Forge 1.12.2 and a few client side mods only and running the same profile like 2-4 times without issues. Even with FTB_Launcher.exe I can run like 3 same launchers in the same working directory without issues :P 

I don't think that should cause issues with MultiMC... or throw a warning like the Mojang launcher does^^ Else I can dupe the instance but thats more diskspace (anyways this is not an issue, but I had made a custom partition on my external HDD to 16GB, I'd need to increase it haha :')

Still using MagicLauncher due to features not implemented/not supported in MultiMC so I'm stuck to this ML launcher I'm using for years trying to replace it :/ I do acknowledge this suggestion won't be added/supported but can be something to add x)

But thanks for your explanation Peterix! Its fine if this suggestion gets declined, I'll just dupe the instance into another to workaround what I need XD

**Comment by peterix** [comment]
I'm no saying that it won't happen, but there are many things that honesly need to happen much sooner or will affect many more people if they are not done.

MultiMC basically never allowed to run an instance more than one time. It could be started multiple times itself, which people used to get around that, and shot themselves in the foot with it before. I made it possible to run multiple different instances from within one MultiMC, and then made it impossible to start MultiMC multiple times.

What you are asking for is further work in this same direction -- multiple running copies of an instance.

This has several issues:
* The instance can currently hold only one 'launch task', wih everything that belongs to that - logs, internal state, updates, etc.
* It is not clear how a second copy of an instance should launch... What if it is a pack that autoupdates? It could just end up all messed up... So the two launches should not intersect -- you will absolutely never solve this problem without tracking the state of those multiple launches and without locking.
* Some of the launch tasks (like extracting native libraries, building the main jar and a few others) would have to be decoupled from the launch, and would have to track their state independently. For example, i is impossible to overwrite DLL files that are in use on Windows.
* How should this be represented in the UI? Some UI changes would be required for the result to not be messy and confusing.

Just copying the instance is way easier right now.

**Comment by TNTUP** [comment]
Seems my email reply didn't work, welp.

Hm yeah :/

- Though with MagicLauncher, or with FTB's Legacy launcher only FTBL throws an exception with native extraction being in use but it can be safely ignored because it will use those ones already extracted and it runs without problems^^

- I don't use the autoupdater modpack, but in that point you're right, that will indeed cause problems, but like something "Allow launching the same instance" but disables "Auto Updater" with a warning, else re-enable Auto Update and disable "Allow launching ...." thing

- It can use the same natives already extracted if the instance is already running^^

- Don't need UI change? The option is grayed so it can be enabled "Play instance" https://i.qcfb.ca/20180305092942.png

Thats I'll do right now, thats seems the easiest option^^

Again thanks for your answers and concerns! I'd be sure get patreon someday to support MultiMC developement (Supporting MultiMC devlopment, not for this feature ofc!)

**Comment by peterix** [comment]
No, it cannot be safely ignored. Maybe you can judge that for youurself in some particular case, but it is generally unsafe. Once the game is running, parallel launches should not run updates... and probably shouldn't run pre0launch/post-exit commands, because people use them for that purpose. I cannot 'disable' auto-updaters, because they do not operate withing MultiMC, and I simply do not know what they are.

And yes, UI changes are absolutely necessary. How do you read logs from one of the running copies? How do you even know which is which? This is already a problem with launching different instances side by side, but becomes much messier with identical ones. I would consider getting custom window titles working for the game above version 1.5.2 a must for this.

Maybe combined with some sort of way to easily open the instance window/raise the game window for the individual running copies of minecraft.

**Comment by kikawet** [comment]
I think this is a good idea since even if you don't want to launch the same insta multiple times it should be allowed to do it with a different account at least

**Comment by Janrupf** [comment]
This needs some special handling, a complicated but good Idea would be to allow a option to create a temporary instance from another.

**Comment by jredfox** [comment]
what if you duplicated an instance on double click instead of just not allowing it to happen
