### ISSUE TITLE
Turning off auto pause?

### ISSUE THREAD

**Issue by Distinctish** [MultiMC/MultiMC5#2178]
MultiMC version: 0.6.1-1118

Operating System: OS High Sierra

Summary of the issue or suggestion:
----------------------------------------------
Should be able to turn off autopause when focus is lost (command+tab). On regular mc you can just go to options.txt and change pauseOnLostFocus:true to false but I'm not sure how to make that happen on this.

What should happen:
------------------------------
I literally just wanna be able to come back to it and not have it be paused, like I said it's a thing in options and I'm not about to download a whole ass mod when it's just writing false where there's a true.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Command+tab (or just slide on touchpad with 3 fingers)

2. go back to minecraft

3. and it's paused :////// 

Suspected cause:
---------------------------
it's set on true........................

Logs/Screenshots:
----------------------------
do I really gotta

Additional Info:
---------------------------

**Comment by peterix** [comment]
Well, you can turn it off :)

Each instance gets its own `.minecraft` folder, with its own `options.txt` file. Select the instance, click `Instance Folder`, open `.minecraft` and you should find it there.

**Comment by iarspider** [comment]
Or just press F3+P while in-game

**Comment by brodycas3** [comment]
Or just open the inv screen before tabbing out.

**Comment by peterix** [comment]
Well, that's just how the game works...
