### ISSUE TITLE
help skyfactory

### ISSUE THREAD

**Issue by bdog8805** [MultiMC/MultiMC5#2180]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
help im new to the multimc stuff and i was using the twitch app before and then it just stopped working and now im just trying to play skyfactory any help with downloading skyfactory 3 because i dont know how to do it

**Comment by peterix** [comment]
You can get the pack from here (or similar `files` pages):
https://www.feed-the-beast.com/projects/ftb-presents-skyfactory-3/files

* Download the zip.
* Drag&Drop it on top of the mian MultiMC window.
* Click the necessary buttons to make it do its thing.

Things you may run into:
* Wrong java -- make sure you have java 8!
* Not enough memory given to java -- a big pack like that will not work with the defaults. 4GB is maybe fine?

You can change the Java stuff in the settings:
https://github.com/MultiMC/MultiMC5/wiki/Java-settings
