### ISSUE TITLE
Failed To Start Minecraft - Forge Issues

### ISSUE THREAD

**Issue by CalicoCactus** [MultiMC/MultiMC5#2181]
System Information 
Macbook Air Late 2015 8 gb's of ram and 200 gbs of memory
-----------------------------
MultiMC version:
MultiMc 0.6.1-1118

Operating System:
Mac OSX High Sierra

Summary of the issue or suggestion:
----------------------------------------------
Essentially when I add forge to 1.7.10 with NO mods, it crashes immediately, within 5 seconds

What should happen:
------------------------------
It should open up and behave like normal

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Make a 1.7.10 instance

2. Add forge

3. Launch

Suspected cause:
---------------------------
No idea...

Logs/Screenshots:
----------------------------
https://paste.ee/p/WsfI4

Additional Info:
---------------------------
Whenever I remove forge and things, it works fine, but ANY version I try it always breaks like this... Please help! I have a 14 hour car trip TOMORROW!

**Comment by peterix** [comment]
```
Java is version 9.0.4, using 64-bit architecture.
```

Remove java 9. Install java 8.

**Comment by CalicoCactus** [comment]
Thank you!
