### ISSUE TITLE
Feature Request: INST_MC_VERSION

### ISSUE THREAD

**Issue by Thiana** [MultiMC/MultiMC5#2182]
Could you please add the version of minecraft being invoked to the pre-launch variables? This will allow automatic copying/updating of required resource packs or mods for an instance. Thanks.

https://github.com/MultiMC/MultiMC5/blob/1a43f2829743cb88ace3f650d3e060725990c1f1/api/logic/minecraft/MinecraftInstance.cpp#L327

**Comment by peterix** [comment]
So, here's what I'm thinking.

Let's abandon this hack of putting modpack/custom update logic into pre-launch.

It should have its own, separate launch step that happens before the update step, and is based on the instance/modpack only, not user preferences.
