### ISSUE TITLE
Mincraft crashs while loading a world

### ISSUE THREAD

**Issue by fejp** [MultiMC/MultiMC5#2183]
System Information
-----------------------------
MultiMC version: 0.6.1 -1177 (and latest development version, tried both, but reated on former version)

Operating System:  Windows 8.1

Minecraft version: 1.10.2 and 1.12.2 (didn't tried it with older versions)

Summary of the issue or suggestion:
----------------------------------------------
If I try to launch a world the game crashes with a java crash. No crash report is created. This happens althought no mod and not even Forge is installed. I tried diffrent java versions (jre 1.8.0 - 74/121/161) too, which always leads to the same result. Neither in my normal minecraft launcher nor in the feed the beast launcher there are similar errors.

What should happen:
------------------------------
World should load normally.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a new instance.

2. Launch the game.

3. Create a new world or load a world which was already created.

Suspected cause:
---------------------------
No idea.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/frx6K

Sometimes it also looks like this:
https://paste.ee/p/uc7Dp

Additional Info:
---------------------------

EDIT second log

**Comment by peterix** [comment]
So... there's nothing in that log that would point to any problem or solution. It just stops running for no clear reason.

Check the Windows event log: https://www.youtube.com/watch?v=J6vUOyxmU1o
Is there anytthing related to Java crashing in there?

**Comment by fejp** [comment]
No, there is not. But I noticed something very weird: If I run MultiMC on my GPU the crash vanishes. I already checked if I'm using the newest kernel version for my CPU (Intel Core i5).

**Comment by fejp** [comment]
While getting the second error there was something in the windows evet-log:

[Windows events.zip](https://github.com/MultiMC/MultiMC5/files/1821807/Windows.events.zip)

**Comment by peterix** [comment]
Well, I have no idea how to work with those files, and this is probably not relevant anymore? Reopen if it is...
