### ISSUE TITLE
skins not reading

### ISSUE THREAD

**Issue by neojapan92** [MultiMC/MultiMC5#2184]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
There's nothing to go on here... so just guessing.

If you mean the broken skins in old releases, I can't really help you without adding things that would probably clash with mods.
You will have to mod legacy versions of the game yourself in order to get skins working.
