### ISSUE TITLE
Minecraft crashes on launch on Fedora 27

### ISSUE THREAD

**Issue by AdultFriend** [MultiMC/MultiMC5#2185]
System Information
-----------------------------
MultiMC version: 0.6.1-develop-1117, Also occurs on latest stable build

Operating System: Fedora 27

Summary of the issue or suggestion:
----------------------------------------------
Minecraft crashes on launch. Have tried with vanilla 1.12.2 and  Infinity Evolved 1.7. Have attempted to launch using OpenJDK and Java 9, both with the same results.

What should happen:
------------------------------
Launch Minecraft.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install MultiMc on Fedora 27

2. launch a instance of Minecraft.

Suspected cause:
---------------------------
Java

Logs/Screenshots:
----------------------------
https://paste.ee/p/J4Zpl

Additional Info:
---------------------------

**Comment by peterix** [comment]
Weird:
```
OpenJDK 64-Bit Server VM warning: You have loaded library /home/Sammy/Games/MultiMC/instances/1.12.2/natives/liblwjgl.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
```

The actual problem:
```
Caused by: java.lang.UnsatisfiedLinkError: /home/Sammy/Games/MultiMC/instances/1.12.2/natives/liblwjgl64.so: /lib64/libXrandr.so.2: undefined symbol: _XEatDataWords
```

Here's something that looks related:
https://www.reddit.com/r/linux_gaming/comments/4osvmu/torchlight_2_crashing/

And don't use java 9, that will only make things worse.

**Comment by AdultFriend** [comment]
Thank you, I was able to find the issue, it turned out to be related to Lutris:

https://github.com/lutris/lutris/issues/226

After disabling the lutris runtime I have been able to launch minecraft with no problems.

**Comment by peterix** [comment]
Alright. Just weirdly compiled third party libraries then :)

If this was actually in Fedora, everyone would have a problem Soon(TM).
