### ISSUE TITLE
Error: Could not create the java virtual machine

### ISSUE THREAD

**Issue by dvdcd** [MultiMC/MultiMC5#2186]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------
Upon launching any instance, i get a "Error: Could not create the java virtual machine"

What should happen:
------------------------------
Minecraft Starts

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch MultiMC

2. Start a instance

3. Blamo

Suspected cause:
---------------------------
I reinstalled java recently, and that's when the issue arose 

Logs/Screenshots:
----------------------------
https://paste.ee/p/rTuC8
https://gyazo.com/6d65a4d37a5f5def6ac6b07f08b24b92

Additional Info:
---------------------------

**Comment by dvdcd** [comment]
Fixed, My Max Memory Was Too High

**Comment by QuImUfu** [comment]
you need to install/use 64bit Java if you want to assign more memory than ~3GB..
