### ISSUE TITLE
[Suggestion] Allow MultiMC to quickly import unzipped instance folders the same way it does with zipped ones

### ISSUE THREAD

**Issue by TheDeviantCrafter** [MultiMC/MultiMC5#2187]
System Information

Speccy snapshot: http://speccy.piriform.com/results/PSav8fhCAjFDaHkXTqlfYXj

MultiMC version:

0.6.1-1177 stable

Operating System:

Windows 10 Pro 64-bit

Summary of the issue or suggestion:

MultiMC lets you quickly import a zipped folder containing a modpack. This is fantastic for quickly distributing  modpacks, but it only works with zipped folders. I would like it to work with unzipped folders as well.

When moving an instance from Twitch to MultiMC, there are two ways to do it currently:

1. Zip the folder, then have MutliMC unzip it. With large modpacks this can take several minutes.

2. Construct a new instance, select the appropriate Forge and Minecraft versions, and move the files over manually.

What should happen:

Dragging an unzipped folder containing a modded Minecraft instances (mods, config, saves...) and dropping it onto the MultiMC window should install that folder like it does with zipped folders containing the same data.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download a modpack and place the unzipped folder on your desktop

2. Open MultiMC and keep it as the top window, but not maximized so you can still see your desktop

3. Drag the folder from your desktop to the MultiMC window

Suspected cause:

It's expecting a zipped folder and can't handle other file types

Logs/Screenshots:
----------------------------

MultiMC-0.log file: https://paste.ee/p/Qtx39

Screenshots of the issue: https://imgur.com/a/wnRsr

**Comment by QuImUfu** [comment]
Why would you copy a twitch/curse launcher instance to MultiMC? Curse support is already in place. Download the modpack zip from curse and drop it into MultiMC. MultiMC will then download and install the modpack.
Installing instances from other launchers have to be done manually one way or another so adding folder import is nearly useless.

**Comment by TheDeviantCrafter** [comment]
It's useful when building custom packs. Building packs is easier in the
Twitch launcher  since you can install mods and their dependencies in a few
clicks.

Once I start playing the pack, MultiMC is faster and supports newer
versions of Java.

**Comment by QuImUfu** [comment]
Twitch launcher has a feature to export packs. Use that and import them with MultiMC. It will redownload the mods so if you have a slow internet connection, it might not be an option. But it only requires two clicks.

Apart from that:
Using the curse website to download mods is very easy as well, dependencies are linked at the downloads page and searching and downloading mods is simple, too.

On the other hand importing packs directly from the curse launcher (and other launchers) might be a nice to have feature. I do however not expect it to be implemented soon/at all.

**Comment by Janrupf** [comment]
Well, the pack support is really changing at the moment, but I agree with QulmUfu. Always be carefull when speaking about twitch/curse... Support is requested really often but Twitch is really not MultiMC friendly, so it is always a bit of trying to do the best

**Comment by peterix** [comment]
This is probably better handled in documentation.

You can use symlinks to map the mods folder of your MultiMC instance(s) to whatever twitch folder.

See for example:
https://www.reddit.com/r/feedthebeast/comments/4j9jai/how_do_you_export_your_instances_from_curse_to/

**Comment by peterix** [comment]
Anyone willing to write a clear and concise wiki page for this?

**Comment by phit** [comment]
Curseforge support has been added a while ago, if you still need this linking take a look at e.g. https://redd.it/8itxun
