### ISSUE TITLE
Big icons (.ico) not rendered correctly

### ISSUE THREAD

**Issue by iarspider** [MultiMC/MultiMC5#2188]
System Information
-----------------------------
MultiMC version: 0.6.1-1177

Operating System: Windows 7

Summary of the issue or suggestion:
----------------------------------------------
Big icons (e.g. 500x500) are not rendered correctly: https://www.dropbox.com/s/dfkliw1uwyea5gf/MultiMCBad.png?dl=0

If I resize the icon to a smaller size (e.g. 92x92) it is rendered correctly: https://www.dropbox.com/s/pvdti9gn1imn0es/MultiMCGood.png?dl=0

What should happen:
------------------------------

Any size icons should render correctly

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download a big modpack icon (e.g. https://media.forgecdn.net/avatars/141/791/636544733395786830.png)

2. Convert to .ico using IfranView (or, I think, any other tool). Converted icon: https://www.dropbox.com/s/yntgp6tjakfflhd/636544733395786830.ico?dl=0

3. Assign this icon to an instance

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
Try not converting to `.ico`.

**Comment by iarspider** [comment]
Ah, I see what you mean. New to me :)

**Comment by peterix** [comment]
The .ico is kinda broken.

* It contains the same 25KB png file, which is fine when extracted out of it
* It also contains ~700KB of some unindentified garbage
* It shows up wrong outside of MultiMC

So, I think the file itself is broken, and that Qt doesn't handle that brokenness as well as Windows does.

**Comment by calloatti** [comment]
The Windows ICO file format is a mess, not even MS own DOT NET libraries and the gdiplus libraries handle all cases correctly. I had to write from scratch my own methods to handle them to be able to correctly extract the stored images and transparency masks, that can be in multiple formats and different storage methods. After all it is a format that evolved over decades and had to maintain backward compatibility. I will not expect Qt to handle them correctly either. Just stay away from ICO files.

**Comment by peterix** [comment]
Yeah.

Anyway, the `icotool` available on common linux distributions seems to produce valid icon files with embedded png files... So if you are going to make `.ico` icons, try using that.
Make a pile of different sized png files (with proper alpha layer), run `icotool` on that, it works.

**Comment by peterix** [comment]
https://linux.die.net/man/1/icotool

**Comment by peterix** [comment]
And btw, that does extract the one embedded png file out of that ico just fine... so I trust this tool more than both Qt and irfanview.
