### ISSUE TITLE
Suggestion: Launch after download finished checkbox

### ISSUE THREAD

**Issue by bogger33** [MultiMC/MultiMC5#2191]
When importing a new pack, the download can take a bit of time. If the "Please wait..." screen had a checkbox to automatically launch after the import is finished, you could walk away, or just have the screen on your other monitor without having to check progress

**Comment by brodycas3** [comment]
Is it really that hard to open it after importing that you want to make the devs put in way more work than it would take you to do a double click?

**Comment by bogger33** [comment]
it's a suggestion. If the devs don't like it, they can say no and close the issue, problem solved. I wasn't demanding anything, just suggesting a feature that I think is a good idea.

**Comment by brodycas3** [comment]
I'm sorry, I just am a little angry right now. I didn't mean to take it out on you.

**Comment by bogger33** [comment]
That's okay, I appreciate the apology
