### ISSUE TITLE
Issues with Java Detection and Memory Allocation

### ISSUE THREAD

**Issue by Forcefulmocha6** [MultiMC/MultiMC5#2192]
System Information
-----------------------------
MultiMC version: Stable Version 0.6.1 & Develop Version 0.6.1-Develop-1204

Operating System: 16 Gb Ram

Summary of the issue or suggestion:
----------------------------------------------
I'm trying to allocate more RAM to my MultiMC so I can run a modpack I'm creating. I found out that my MultiMC is only auto-detecting x32 java, when I know I have x64 and I made sure by downloading it again and restarting my computer. It will detect it if I manually locate it, but it won't let me allocate more than 1408 mb RAM, and even sometimes no more than 1280 mb, it switches randomly. I've looked it up and it says you can't allocate more then 1.5 Gb with x32, but if I should be able to if I'm using x64. And if I try to allocate more then that It will give a message saying "The specified java binary didn't work with the arguments you provided:" Check the images below for visual representation, and please help!

What should happen:
------------------------------
It should allow me to allocate more than 1408 mb of RAM when I have x64 java.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Try to allocate more than 1408 mb max RAM.
     Don't really know how else too.

Suspected cause:
---------------------------
I have no idea and I'm getting pissed at the fact that It won't detect and let me use the full capacity that my computer has.

Logs/Screenshots:
----------------------------
 When trying to detect the x64 java. ![capture2](https://user-images.githubusercontent.com/37562837/37630945-add0e640-2bbd-11e8-80d3-b7b2b23c9e94.PNG)
When trying to allocate 1280 mb or lower of RAM. ![capture1](https://user-images.githubusercontent.com/37562837/37631025-1726fb5c-2bbe-11e8-856b-0671f4791220.PNG)
When Trying to allocate 1408 mb or higher of RAM. ![capture](https://user-images.githubusercontent.com/37562837/37631056-3aeb5ff6-2bbe-11e8-8f12-08ffe4710d17.PNG)

Additional Info:
---------------------------
Ask for any other needed info and I'll provide it as best as I can!

**Comment by QuImUfu** [comment]
i still think there is no 64 bit version of java installed. Try uninstall all java versions you have installed and download and install 64bit java.

**Comment by Forcefulmocha6** [comment]
@QuImUfu  I tried what you suggested, even restart inbetween downloading and reinstalling and nothing changed. It's the same.

**Comment by peterix** [comment]
Well, that's clearly 32bit java in all those screenshots (`Program Files (x86)` is a dead giveaway.).

Here's the 64bit offline installer:
http://javadl.oracle.com/webapps/download/AutoDL?BundleId=230542_2f38c3b165be4555a1fa6e98c45e0808

The normal installer will happily install 32bit java becauise it wants to sneak a plugin into your browser.

**Comment by Forcefulmocha6** [comment]
@peterix I can try using that installer tomorrow; how is the offine installer different from the online one (I used the online installer)? Not sure if it helps in anyway, but I tried using the normal minecraft launcher and allocating RAM with it, and so far its let me allocate 7 Gb RAM.

**Comment by QuImUfu** [comment]
The normal minecraft launcher comes with an own, separate installation of 64bit Java to bypass a Intel GPU driver bug and prevent memory issues.
The online installer seemingly prefers installing a 32bit version even on a 64bit OS. This is because 32bit browsers do not work with 64bit java plugin.

**Comment by AtomicAstronaut** [comment]
You're using 32 bit java, upgrade to 64, this should fix your issue, @Forcefulmocha6.

**Comment by Curunir** [comment]
It should be noted that the Windows Online installer, for some ethereal reason, still defaults to 32bit Java for pretty much everybody. Oracle really needs to get their shit together on that one.

**Comment by peterix** [comment]
Assuming this got fixed, closing.
