### ISSUE TITLE
Im trying to run Blood n Bones 1.1.5 - 1.6.4. Whenever i run it i recieve an error which say mincraft can't be started. I'm using Java 9. 

### ISSUE THREAD

**Issue by Executor911** [MultiMC/MultiMC5#2193]
System Information
-----------------------------
MultiMC version: 5 0.6.1-1177

Operating System: 

Summary of the issue or suggestion:
----------------------------------------------
Failed to start Minecraft error when i try to run Blood n Bones 1.15-16.4

What should happen:
------------------------------
Blood n Bones should run

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Launch Blood n Bones 

2.

3.

Suspected cause:
---------------------------
Might be because I'm using java 9

Logs/Screenshots:
----------------------------
https://paste.ee/p/K37Og

Additional Info:
---------------------------
If the issue is that I'm running Java 9, before i ran Java 8 and i had memory allocation problems.

**Comment by peterix** [comment]
Stop using java 9.

**Comment by peterix** [comment]
If you are on Windows, this is the (only) right Java to use:
http://javadl.oracle.com/webapps/download/AutoDL?BundleId=230542_2f38c3b165be4555a1fa6e98c45e0808

**Comment by Executor911** [comment]
Thanks for helping.
One more thing sometimes i receive a not enough memory error, is there anything i can do to fix that.

**Comment by peterix** [comment]
1. When you click the Test button, it should say that platform is 64bit (aamd64, x86_64, etc.):
![image](https://user-images.githubusercontent.com/203326/37652990-a71869c4-2c3d-11e8-98a1-21f20fdfdfa7.png)

2. Make sure you give it enough memory (Minimum/Maximum memory allocation)

**Comment by Executor911** [comment]
It doesn't allow me to allocate more than 1408mb of memory

**Comment by peterix** [comment]
That sounds like you are using 32bit java.

**Comment by Executor911** [comment]
Thank you so much. Its fixed now.
