### ISSUE TITLE
Instance crashing as soon as mods are added

### ISSUE THREAD

**Issue by Silverfrostfox9** [MultiMC/MultiMC5#2194]
System Information
-----------------------------
MultiMC version:

Operating System:
Windows 10
Summary of the issue or suggestion:
----------------------------------------------
I've had a problem with the instance not launching or loading other than a black screen and then it crashes. As far as I can tell, as soon as I add mods (any mod) it stops working. It seems to be something with the Onesix launcher as I have already fixed the Java issue. 

What should happen:
------------------------------
It should go to the Minecraft loading screen with all the mods loading and the tool hammering

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.  Add a mod

2. Press Launch

3.  A black Minecraft screen that crashes roughly 30 seconds later

Suspected cause:
---------------------------
OneSix Launcher

Logs/Screenshots:
----------------------------
[//]: # https://pastebin.com/udm36sZs (Crash Report)
[//]: # https://pastebin.com/GdcWRCq0 (Full log)

Additional Info:
---------------------------

**Comment by peterix** [comment]
Update optifine and use java 8.
