### ISSUE TITLE
SSL - Handshake faild

### ISSUE THREAD

**Issue by Alroy1000** [MultiMC/MultiMC5#2195]
**System Information:** See the second screen

**MultiMC version:** 0.6.1

**Operating System:** _first:_ Windows 8.1 / _now:_ Windows 10

**Summary of the issue or suggestion:**
SSL-Handshake failure at account connecting

**What should happen:**
If I want connect an account to MMC, I get an SSL-Handshake failuer with the statment that I use Windows XP and that I have to Update my root certificats

**Steps to reproduce the issue (Add more if needed):**
It's complicated to reproduce the error because on my laptop (settings same as here[Windows 10 / Same software background]) I don´t get this error the network is also the same one so there can´t be the failure and I donßt have another pc were I can try to reproduce

**Suspected cause:**
I think there a problem with the SSL-Certificates on my PC and I´vh look for problem answers all on google but I can´t find a way for manual updating the root certificates 

**Logs/Screenshots:**
_log:_ https://pastebin.com/4xSuRQJh
_screen of the error window:_ https://www.pic-upload.de/view-35040001/report.jpg.
_screen of system values:_  https://www.pic-upload.de/view-35040038/report2.jpg.html

Additional Info:

**Comment by Janrupf** [comment]
I know this problem from Linux, sometimes certificates don't get installed... Maybe thats the case for Windows to?
You should be able to view the certs in the Java control panel somewhere under Security if I remember right

**Comment by Alroy1000** [comment]
First thank you for your quick awnser,
But I can´t find the certs I need. I´ve downloded the certs URIs from log and instaled them but it don´t work any time.
If you have an Idea waht certs are missing this time I´ll thank you if you send me this certs.
My PC have generally a problem with SSL-Certs e.g. in Chrome I can´t open minecraft.net (missing SSL-trusted cert) 
My Pc is build by picking up components of three generations tower of myself and the Disk also three Years old and if you have an Idea to Update or clen all certs in Pc I´ll thank you so much if you give me a hint
LG and sorry for this stupid question but I walk in an circal and can´t come out (2 years Developer education) Thank you in this time

PS: this is translated by myself I hope you can read all and understand my complex Grama thinking

**Comment by Janrupf** [comment]
I don't know if I can just send you this certs :D
But maybe this helps: https://community.spiceworks.com/topic/584022-missing-or-invalid-root-certificates-on-windows-7-64bit
Be carefull, haven't tried this!

PS: I can understand your grammer, I'm german too :laughing:

**Comment by MrDiamond123** [comment]
Is the time set correctly? (Is the year 2018?) 

Sometimes this makes the certs look like they are from the future and not work.

**Comment by Alroy1000** [comment]
Thank you for all but nothing has worked,
at the end I´ve cleard nearly all certificats and reset Windows after this all problebms away.
I don´t know wwaht problems have been there but now it´s all perfekt and work so perfakt like my Laptop again
