### ISSUE TITLE
Snapshot Instances Crashing

### ISSUE THREAD

**Issue by pc1653** [MultiMC/MultiMC5#2196]
MultiMC version: 0.4.11-751

Operating System: Windows 10

 Snapshot instances are crashing. Loading up game files of previous full releases works just fine though. I'm not entirely sure if it is MultiMC that is causing this (probably not) but I cant load the main launcher on my computer so I cant test. 

Snapshot 18w10d log
----------------------------------------------------------------------------------------
MultiMC version: 0.4.11-751

Minecraft folder is:
instances/Bleeding Edge Vanilla/minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/java.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -jar, E:/Users/Matt/Desktop/Games/Minecraft/Multimc/jars/NewLaunch.jar]

Minecraft process ID: 7640

Using onesix launcher.

Main Class:
  net.minecraft.client.main.Main

Native path:
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/instances/Bleeding Edge Vanilla/natives

Traits:
  []

Libraries:
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/mojang/brigadier/0.1.24/brigadier-0.1.24.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/org/lwjgl/lwjgl/3.1.2/lwjgl-3.1.2.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.1.2/lwjgl-jemalloc-3.1.2.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/org/lwjgl/lwjgl-openal/3.1.2/lwjgl-openal-3.1.2.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/org/lwjgl/lwjgl-opengl/3.1.2/lwjgl-opengl-3.1.2.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/org/lwjgl/lwjgl-glfw/3.1.2/lwjgl-glfw-3.1.2.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/org/lwjgl/lwjgl-stb/3.1.2/lwjgl-stb-3.1.2.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/versions/18w10d/18w10d.jar

Params:
  []

Window size: 854 x 480

Preparing native libraries...
Extracting lwjgl-3.1.2-natives-windows.jar
Extracting lwjgl-jemalloc-3.1.2-natives-windows.jar
Extracting lwjgl-openal-3.1.2-natives-windows.jar
Extracting lwjgl-opengl-3.1.2-natives-windows.jar
Extracting lwjgl-glfw-3.1.2-natives-windows.jar
Extracting lwjgl-stb-3.1.2-natives-windows.jar
Extracting text2speech-1.10.3-natives-windows.jar
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.UnsatisfiedLinkError: E:\Users\Matt\Desktop\Games\Minecraft\Multimc\instances\Bleeding Edge Vanilla\natives\lwjgl.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at org.lwjgl.system.Library.loadSystem(Library.java:161)
	at org.lwjgl.system.Library.loadSystem(Library.java:151)
	at org.lwjgl.system.Library.loadSystem(Library.java:102)
	at org.lwjgl.system.Library.loadSystem(Library.java:66)
	at org.lwjgl.system.Library.<clinit>(Library.java:49)
	at org.lwjgl.system.MemoryAccessJNI.<clinit>(MemoryAccessJNI.java:13)
	at org.lwjgl.system.Pointer.<clinit>(Pointer.java:22)
	at org.lwjgl.system.Platform.mapLibraryNameBundled(Platform.java:80)
	at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:602)
	at bzk.B(SourceFile:2071)
	at net.minecraft.client.main.Main.main(SourceFile:50)
	... 8 more
Exiting with -1
Process exited with code -1.
--------------------------------------------------------------------------------------------------------

Full Release 1.12.2
--------------------------------------------------------------------------------------------------------
MultiMC version: 0.4.11-751

Minecraft folder is:
instances/Bleeding Edge Vanilla/minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/java.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -jar, E:/Users/Matt/Desktop/Games/Minecraft/Multimc/jars/NewLaunch.jar]

Minecraft process ID: 9112

Using onesix launcher.

Main Class:
  net.minecraft.client.main.Main

Native path:
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/instances/Bleeding Edge Vanilla/natives

Traits:
  []

Libraries:
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/mojang/realms/1.10.19/realms-1.10.19.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  E:/Users/Matt/Desktop/Games/Minecraft/Multimc/versions/1.12.2/1.12.2.jar

Params:
  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, E:/Users/Matt/Desktop/Games/Minecraft/Multimc/instances/Bleeding Edge Vanilla/minecraft, --assetsDir, E:/Users/Matt/Desktop/Games/Minecraft/Multimc/assets, --assetIndex, 1.12, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userType, mojang, --versionType, release]

Window size: 854 x 480

Preparing native libraries...
Extracting text2speech-1.10.3-natives-windows.jar
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

[18:27:03] [Client thread/INFO]: Setting user: <PROFILE NAME>
[18:27:05] [Client thread/INFO]: LWJGL Version: 2.9.1
[18:27:05] [Client thread/INFO]: Reloading ResourceManager: Default
[18:27:09] [Sound Library Loader/INFO]: Starting up SoundSystem...
[18:27:09] [Thread-3/INFO]: Initializing LWJGL OpenAL
[18:27:09] [Thread-3/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[18:27:09] [Thread-3/INFO]: OpenAL initialized.
[18:27:10] [Sound Library Loader/INFO]: Sound engine started
[18:27:14] [Client thread/INFO]: Created: 1024x512 textures-atlas
[18:27:16] [Client thread/INFO]: Narrator library for x64 successfully loaded
--------------------------------------------------------------------------------------------------------------

**Comment by peterix** [comment]
Update MultiMC.

**Comment by pc1653** [comment]
Is it not on the latest version? I got an update notification and I hit the update button

**Comment by tehbasshunter** [comment]
MMC5 is the latest.

**Comment by pc1653** [comment]
Ok...

**Comment by peterix** [comment]
0.4.11-751 is about 2 years old. You will need 0.6.x to run current snapshots.

**Comment by pc1653** [comment]
I see... That fixed it. I guess the update didn't work the first time. Guess I haven't used MultiMc in a while if it's that old. Anyways thanks for the help
