### ISSUE TITLE
Feature Profiling: WIndows - JProfiler not working

### ISSUE THREAD

**Issue by mmarquezs** [MultiMC/MultiMC5#220]
Plataform: Windows 7 (64 bits)

The settings menu when configuring JProfiler it doesn't work. 
It tries to search for a bin folder with a file called "jprofiler", and clearly it doesn't found it because it's called "jprofiler.exe". Changing the name to jprofiler without extension it works but it shouldn't be needed.
After that the menu works but then when running minecraft with jprofiler it seems to work it shows some message on the console about jprofiler but it hangs.

**Comment by peterix** [comment]
This is now fixed in the 'unstable' branch.
