### ISSUE TITLE
Javafx isn't found (Ubuntu)

### ISSUE THREAD

**Issue by MrDiamond123** [MultiMC/MultiMC5#2200]
System Information
-----------------------------
MultiMC version: 0.6.1-1092

Operating System: lin64 (Ubuntu LTS/KDE Neon 5.12)

Summary of the issue or suggestion: Can't start game 
----------------------------------------------

What should happen: The Game starts
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Try to start the game 

Suspected cause: javafx not loading correctly
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://gist.github.com/MrDiamond123/687b4aff0667e5120492d8de220ba647

**Comment by MrDiamond123** [comment]
I got the JavaFX thing working (i hope)
Now i get this
' Exception in thread "main" java.lang.ClassCastException: jdk.internal.loader.ClassLoaders$AppClassLoader (in module: java.base) cannot be cast to java.net.URLClassLoader (in module: java.base)
	at at.chaosfield.updaterUpdater.JarRunner.addFile(JarRunner.java:13)
	at at.chaosfield.updaterUpdater.UpdaterUpdater.<init>(UpdaterUpdater.java:56)
	at at.chaosfield.updaterUpdater.UpdaterUpdater.main(UpdaterUpdater.java:24)
'

**Comment by peterix** [comment]
I cannot tell you anything based on random fragments of logs. ost the full log.

**Comment by MrDiamond123** [comment]
Minecraft folder is:
/home/diamond/.local/share/multimc/instances/enderiotest_multimc/.minecraft


Java path is:
/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java


Java is version 1.8.0_151, using 64-bit architecture.


Running Pre-Launch command: java -jar "/home/diamond/.local/share/multimc/instances/enderiotest_multimc/.minecraft/UpdaterUpdater.jar" "https://server.enderio.com/enderiotestpack.cfg" "PackInfo.cfg" "/home/diamond/.local/share/multimc/instances/enderiotest_multimc/.minecraft" "PackUpdate.jar"
Exception in thread "main" java.lang.ClassCastException: jdk.internal.loader.ClassLoaders$AppClassLoader (in module: java.base) cannot be cast to java.net.URLClassLoader (in module: java.base)
	at at.chaosfield.updaterUpdater.JarRunner.addFile(JarRunner.java:13)
	at at.chaosfield.updaterUpdater.UpdaterUpdater.<init>(UpdaterUpdater.java:56)
	at at.chaosfield.updaterUpdater.UpdaterUpdater.main(UpdaterUpdater.java:24)
Process exited with code 1.
Pre-Launch command failed with code 1.

**Comment by MrDiamond123** [comment]
nvm now i think it is just the updater script doing this

**Comment by peterix** [comment]
You are running it with a different java than minecraft, and it is clearly only compatible with java 8 or older.

**Comment by MrDiamond123** [comment]
i am running it with java 8

**Comment by MrDiamond123** [comment]
Confirmed it is the run script
