### ISSUE TITLE
Make log upload filtering configurable (player name optional)

### ISSUE THREAD

**Issue by calloatti** [MultiMC/MultiMC5#2201]
System Information
-----------------------------
MultiMC version:

0.6.1 develop 1205

Operating System:

win32 Windows 7

Summary of the issue or suggestion:
----------------------------------------------
Log upload to paste.ee includes the acual Minecraft user name.

What should happen:
------------------------------
Maybe it would be best for privacy reasons to edit out the actual Minecraft user name when uploading logs to paste.ee

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Upload a log

If I am not mistaken this did not happen before, but now it does. I seem to recall reading an issue about now displaying the user name in the log but can't find it.

**Comment by peterix** [comment]
Damed if you do, damned if you don't...

Some people want it for chat logs, you seem to not want it.

**Comment by peterix** [comment]
Maybe this needs to be configurable.

**Comment by calloatti** [comment]
Yeah, I understand the problem. But having your MC name in an uploaded crash report raises some privacy issues I think. 

For example, in my case I recently uploaded a crash log to report a bug in a mod, and it included my 11 year old son MC user name. I am kind of not comfortable with that.

It would be great if this could be configured for the paste.ee upload function.

**Comment by peterix** [comment]
Makes sense.
