### ISSUE TITLE
failed to download assets

### ISSUE THREAD

**Issue by africalinguist** [MultiMC/MultiMC5#2204]
System Information
-----------------------------
MultiMC version: 0.6.1-develop-1121

Operating System: Ubuntu 16.04

Summary of the issue or suggestion:
----------------------------------------------
MultiMC fails to start instance because of "Failed to download assets"

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. create new instance

2. download assets

3. it will fail

Suspected cause:
---------------------------
incorrect metadata? I don't really know

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
all the logs are different
1.6 starts OK
1.10 starts OK
1.11 starts OK

log for 1.12:
https://paste.ee/p/7FfVR

log for 1.13 snapshot (18w11a):
https://paste.ee/p/d9xVB

Additional Info:
---------------------------
this also affects my sister on windows 8.1

**Comment by africalinguist** [comment]
please fix this soon, I'm working on a map and want to update it on PMC

**Comment by Janrupf** [comment]
Try to open the following links in a browser:
1. http://resources.download.minecraft.net/4a/4abff4296bb82cefebf944968ee9ef19847ff878 
2. http://resources.download.minecraft.net/f2/f227b629a2bcca9c0d9351f386a6ad39e3. a4d172e http://resources.download.minecraft.net/fa/fa8388f718415adbf64a32b03d853283d1059d72.

**Comment by africalinguist** [comment]
had to download one more asset in the 'ae' group, but apart from that it worked
