### ISSUE TITLE
MultiMC crashed when clicked "Add Instances"

### ISSUE THREAD

**Issue by WitherZuo** [MultiMC/MultiMC5#2205]
# Problem:
**After updated MultiMC, if I clicked "Add Instances", MultiMC will crash. Previous versions are no problem. And some UI can not show normally.** 

# System&Software:
**OS: Windows 10 Home (1709-16299.309)
Launcher Version: 0.6.1-develop-1207**

**Comment by WitherZuo** [comment]
## Some screenshots:
## Crashed:
![2018-03-27](https://user-images.githubusercontent.com/25317916/37961053-d52daf7a-31e9-11e8-91e4-075527279785.png)
![2018-03-27 1](https://user-images.githubusercontent.com/25317916/37961090-f0fd4210-31e9-11e8-8971-42ee6ee894ba.png)

## UI:
![2018-03-27 2](https://user-images.githubusercontent.com/25317916/37961230-5199834a-31ea-11e8-8372-7bc2e96984e6.png)

**Comment by Janrupf** [comment]
Can you give us the MultiMC log?

**Comment by peterix** [comment]
Use the stable version for now as a workaround.

**Comment by nastro1995** [comment]
I am having the exact same problem as @WitherZuo,

OS: Windows 10 Pro 64bit (16299.248)
and launcher version is: mmc5 version 0.6.1-dev-1207

**Comment by WitherZuo** [comment]
@Janrupf 
I found the log file, but......nothing can show or cause this problem, it's so strange...really
[MultiMC-0.log](https://github.com/MultiMC/MultiMC5/files/1851753/MultiMC-0.log)

**Comment by peterix** [comment]
It's a plain old crash bug ... it didn't happen on linux, at least not while I tested it. I'll most likely fix it today when I get back from work.

**Comment by jpmac26** [comment]
I know you're already planning on fixing the bug, but I just wanted to confirm that I'm experiencing it too, an immediate crash upon clicking "New Instance". The log file doesn't seem to have any information regarding the crash, and using an empty "instances" folder doesn't fix the problem either. I am using Windows 10 Pro 64-bit, with the latest updates.

**Comment by hedgehog1029** [comment]
Segfault here on Linux. I pulled the stacktrace as well, to hopefully ease debugging.
https://hastebin.com/magidiqijo.pas

**Comment by TheGlitch76** [comment]
Can reproduce.
If it helps, I have a AMD CPU on Windows 10 (latest) x64.

**Comment by Turmfalke2** [comment]
4c7ea0f9 works fine

@peterix the issue with using the old stable version that curse modpack imports isn't working

**Comment by 0xb00b** [comment]
i have the same issue, this is what i get if i run the .sh file from the CLI 

./MultiMC: line 93: 24877 Segmentation fault      (core dumped) "${MMC_DIR}/bin/MultiMC" -d "${MMC_DIR}" "$@"

**Comment by peterix** [comment]
This should be fixed now.

**Comment by 0xb00b** [comment]
Can confirm, latest update fixed the problem for me. Thank you very much!

**Comment by peterix** [comment]
And the UI layout oddities too, as soon as the next build finished.

**Comment by WitherZuo** [comment]
Thanks!:grinning:
