### ISSUE TITLE
Modded Instance Crashing (java.lang.reflect.InvocationTargetException)

### ISSUE THREAD

**Issue by Korwai** [MultiMC/MultiMC5#2207]
System Information
-----------------------------
MultiMC version: 0.6.1

Operating System: Windows 8.1

Summary of the issue or suggestion: Unable to start Minecraft.
----------------------------------------------

What should happen: Minecraft should start.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add the instance (https://minecraft.curseforge.com/projects/awakening/files/2544792/download)

2. Run it. It should crash.

Suspected cause: No idea.
---------------------------

Logs/Screenshots: https://paste.ee/p/iBFpl
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info: I tried importing a copy of this mod (that worked) through a friend and it still hasn't worked. I was also able to run vanilla MC on 1.7.10. I also played with RAM usage (tried 4608MB) and also didn't work. Not really sure what's causing it.
---------------------------

**Comment by Heufneutje** [comment]
Use Java 8. Java 9 will not work.
