### ISSUE TITLE
sounds not working

### ISSUE THREAD

**Issue by 367757475** [MultiMC/MultiMC5#2209]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen: when minecraft boots up it is supposed to have sound, note i am using 1.7.3 beta. 
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. unknown

2.

3.

Suspected cause: unknown... HELP!!!
---------------------------

Logs/Screenshots:
![capture](https://user-images.githubusercontent.com/37887899/38065263-2461b14a-32b7-11e8-8043-dba4b2c38330.PNG)

----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Janrupf** [comment]
I think thats the same issue as always, the old links are broken. I don't knoe if this affects all old versions but some if them are just gone.

**Comment by peterix** [comment]
Yeah... This will need some workaround... Is Mojang hosting these files still?

**Comment by Jilms** [comment]
so I had this issue as well, but I fixed it. So I'm pretty sure that the game tries to look for the correct resources(sounds) and if it cant find the right resources it tries to download them from a dead link. The way I fixed this is just replacing the resources folder in the instance I was using with the one I had from beta 1.7.3(Don't remember where I downloaded from them but I have them)

**Comment by 367757475** [comment]
thank you Jilms for your help, I would like to have those resource files if you wouldn't mind.

**Comment by 367757475** [comment]
i found another resources folder online, the only problem is you have to hit F3 and S at the same time. Is there any way ti fix this because i am lazy and don't feel like doing that,

**Comment by peterix** [comment]
You can get the sounds here: https://mega.nz/#F!U3owiTzK!QtYRYthO4i7Cyshf2MWmNg

**Comment by Revemohl** [comment]
Given how this issue is known but has been going unsolved for about two months (https://bugs.mojang.com/browse/WEB-1004), would it be possible for MultiMC's servers to locally host the sound files for older versions and for the program itself to download them from there until some activity happens from Mojang's side?

**Comment by peterix** [comment]
I believe that this should be solved in an official way, without me rehosting files.

**Comment by QuImUfu** [comment]
i made a very simple bash script that takes files from /assets/objects and copies them into the resources folder format expected by minecraft beta.

https://gist.github.com/QuImUfu/c0284fe6e3cf8e5ddb93fa0b8b96dfd3

Some files that belong into the resources folder are not included in the files in the /assets/objects folder.
i made a zip containing those files.

https://dl.dropbox.com/s/e8n9tvio25ac7yb/resources.zip

together these are exactly the files listed on http://s3.amazonaws.com/MinecraftResources and match on md5sum.

so to create a beta resources folder on Linux:
 - use MultiMC to start any legacy instance once (to download the assets)
 - download and copy the script to {MMC_DIR}/assets/objects
 - execute it
 - download the zip and extract it into the resource folder created in /assets/objects by the script
 - copy/move the resource folder into your beta instance

**Comment by peterix** [comment]
I wonder if the files are there, but simply don't have an index that would point to them. And seeing how the files on the server are simply checksums, maybe it would be worth it to just reconstruct the indexes and backfill them into the legacy versions...

**Comment by Fixer-007** [comment]
Has this problem for 1.2.5 too, it worked before.

**Comment by peterix** [comment]
This should now be fixed.

**Comment by Fixer-007** [comment]
I did a quick test with new beta 1.7.3 and release 1.2.5 instances and sounds worked for me, thanks a lot :)
