### ISSUE TITLE
Sound not working

### ISSUE THREAD

**Issue by linnnylinnylinux** [MultiMC/MultiMC5#2212]
SO in no matter what verion or with mods or not the sound wont play! idk why pls halp!

**Comment by Dushess** [comment]
Old instances? Like 1.8.3b?

**Comment by Janrupf** [comment]
Duplicate of #2209 and MANY other issues... Mojang removed these files so we are searching for a way to get them

**Comment by linnnylinnylinux** [comment]
ok

**Comment by Timolino456** [comment]
I have this problem too. It's with all new instances with old alpha or beta versions (I haven't tried it with any release version yet..)

**Comment by peterix** [comment]
Duplicate of https://github.com/MultiMC/MultiMC5/issues/2209
