### ISSUE TITLE
When removing mods, coremods are not uninstalled.

### ISSUE THREAD

**Issue by CJL48** [MultiMC/MultiMC5#2213]
System Information
-----------------------------
MultiMC version:
5 - 0.6.1-1177
Operating System:
Windows 10
Summary of the issue or suggestion:
----------------------------------------------
Coremods are not removed from jar when disabled/removed from Loader Mods

What should happen:
------------------------------
The coremods should be removed.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Have an instance with coremods that keep the instance from running (crash during initialization).

2. Remove offending mods.

3. Note continued presence of coremods.

Suspected cause:
---------------------------
No clue.

Logs/Screenshots:
----------------------------
[//]: # https://paste.ee/p/6GRtM

Additional Info:
---------------------------

**Comment by CJL48** [comment]
Going into <MultiMCRoot> and deleting the contents of the versions folder did not remove the mods.
I literally cannot play Minecraft because your launcher won't let me remove broken coremods.

**Comment by peterix** [comment]
I simply don't understand what you mean.

**Comment by CJL48** [comment]
I am removing mods that modify the minecraft binary from MultiMC's instance modlist. When I start minecraft after this, the coremods associated with these mods are still there, and I cannot get rid of them. Because these coremods are causing minecraft to crash while starting up, this is preventing me from playing that instance of minecraft.

**Comment by peterix** [comment]
Then remove those too... Some of the stuff needs to be removed from `mods/$MinecraftVersion/`.
The only things that end up there are files automatically downloaded by other mods... which is basically a ticking time bomb.

**Comment by CJL48** [comment]
...thank you. I'm sorry I bothered you about this.

**Comment by CJL48** [comment]
It's started happening again, and this time there is nothing in mods/$minecraftversion or version to delete. I won't lie, I'm extremely disappointed that MultiMC doesn't handle core mods correctly.

**Comment by CJL48** [comment]
I've been quite clear that MultiMC is starting minecraft instances containing core mods which should have been uninstalled from those instances. My conclusion is that MultiMC does not handle removal of core mods correctly, and in fact obscures jar and coremod locations, making it almost impossible to remove core mods which are no longer useful.
THAT is what I mean.

**Comment by peterix** [comment]
I simply do not understand what you mean. Core mods have absolutely nothing to do with anything. Actually, they are handled correctly, where they are even relevant (you get a separate core mod page in versions where they are in a separate folder).

Again, can you be clear about what is actually the problem?

**Comment by CJL48** [comment]
...When I get a crash report, it says that coremods are installed. Some of these coremods are associated with mods that I had removed from that minecraft instance. Ergo, coremods are NOT handled correctly: if they were, they would either be automatically removed, or I would be able to remove them.

**Comment by CJL48** [comment]
...on further inspection, the logs that I have do not make the problem clear, and I may have been overreacting to problems caused by other sources. I apologize for bothering you.

**Comment by peterix** [comment]
Forge devs have some very low opinions of core mods (mods that directly mess and alter the game code). So there's some scary language in the logs...

As for automatically removing anything... that's just not going to happen with mods as they are now. Nothing has enough information to decide when something isn't needed. That requires understanding.

If you have problems with launching modded Minecraft, share the logs.

**Comment by peterix** [comment]
I guess the problem is stuff being autodownloaded by some other mod? But I'm guessing here...

**Comment by peterix** [comment]
@CJL48 can you export such a broken instance and share it?

**Comment by calloatti** [comment]
Some mods either download a separate core mod jar or extract from inside them a separate core mod jar. My guess is that there is no way for MultiMC to know about what those mods are doing, so it's up to the user to delete those extra core mod jars added by certain mods.

**Comment by peterix** [comment]
Extract? That's a new one...

So here's what I think of extracting more mods out of mods:
- this should be strictly prohibited
- the launcher should prevent the game from adding, moving, deleting or otherwise changing its own files at runtime
- it should be made impossible by making the mods folder not writable
- it should be also made impossible by replacing the default java nio filesystem provider with one that prevents writing to and creating files outside of specific folders (saves, config, server resource packs, ...)
- anyone whose mods break should clean up their act and stop doing this.

**Comment by calloatti** [comment]
This started when Forge guidelines changed, in that core mods should be on its own standalone signed jar. So mod makers either download the core mod jar or extract it from the mod jar to make it easier to use the mod by not having to download a separate core mod jar.

So basically an intended solution to a problem created more unforeseen problems. That's life I guess.

**Comment by calloatti** [comment]
For example:

`ImmersiveEngineering-0.12-80-361.jar`

Extracts

`ImmersiveEngineering-0.12-80-361-core.jar`

When first run.

**Comment by peterix** [comment]
That is so ugly.

**Comment by peterix** [comment]
'core mods' -> Right in the `mods` folder, or in the case of some really terrible things, `mods/$version/`. If they are in some other place, I blame the modders and/or Forge for failing to behave in expected ways.

The Minecraft jars are not useful for anything, unless you simply want to poke around in them and look at all the snowman obfucated class files... In that case, look at the logs:
```
  C:/Users/Chris Long/Documents/Games/MinecraftForge/MultiMC/libraries/com/mojang/minecraft/1.10.2/minecraft-1.10.2-client.jar
```
Any changes made to those will be reverted by MultiMC. Please do not mess with them.

**Comment by peterix** [comment]
That said, it is simply not clear what your problem is.

**Comment by peterix** [comment]
Like, the only thing that's certain is that you are confused. And I am further confused by the confusion, and by all of these mods behaving even worse than before.

**Comment by peterix** [comment]
Is there a `modlist.json` anywhere in the instance?
