### ISSUE TITLE
MultiMC crashing after loading Forge for 1.7.10

### ISSUE THREAD

**Issue by 1Mehdi05** [MultiMC/MultiMC5#2214]
System Information
-----------------------------
MultiMC version: MultiMC 5 version 0.6.1-1177

Operating System: Windows 7 Home Premium

Summary of the issue or suggestion:
----------------------------------------------
MultiMC crashes after installing Forge for Minecraft 1.7.10

What should happen:
------------------------------
Minecraft should load with Forge

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install MultiMC 5

2. Install Minecraft 1.7.10 instance

3. Install Forge to Minecraft 1.7.10 instance

4. Launch 1.7.10 instance

Suspected cause:
---------------------------
Possibly Java related

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
Here is Log
https://paste.ee/p/U3hXb

Additional Info:
---------------------------
I tried legacyjavafixer that I saw in another post & it still crashes

**Comment by QuImUfu** [comment]
Do not use MultiMC on not mounted network device. java crashes out as it seemingly doesn't support UNC Paths.
You could try including it as ?network drive? (i do not know how that's called in englisch). 
executing
```net use X: \\MEHDI-7HP\Users\Mehdi\AppData\Roaming\MultiMC``` 
in a terminal should create a new device with the letter X. Open MutiMC in that folder and then start the instance. That may or may not work (idk)

That is if you are actually trying to open MultiMC installed on a remote PC. If it is actually installed on your pc and you are only accessing it over network (why?), open the folder properly over {YOUR ROOT DEVICE LETTER}:\Users\Mehdi\AppData\Roaming\MultiMC\ (you may have to enable show hidden folders in folder settings)

This is untested, i do not use windows anymore.

**Comment by jikuja** [comment]
Please, post a full log with `upload` button.

**Comment by 1Mehdi05** [comment]
Here is Log from Upload button
https://paste.ee/p/GLhA8

**Comment by Heufneutje** [comment]
Your computer still seems to think MultiMC is running from some sort of network drive (which is probably where it loads your Windows user profile from). Move MultiMC to a different location like your desktop or your documents folder. MultiMC does not belong in AppData.

**Comment by 1Mehdi05** [comment]
I moved the folder to the desktop; deleted and it still threw the error; deleted & reinstalled forge and it still threw an error. So I deleted the entire instance; reinstalled the instance, reinstalled forge & now it is working. Thank you all Very Much
