### ISSUE TITLE
【Feature Request】Add "Set Java Priority" Setting

### ISSUE THREAD

**Issue by WitherZuo** [MultiMC/MultiMC5#2215]
## Feature Request:
Add "Set Java Process Priority" setting in MultiMC please, it can make Minecraft to run smoother.

## Example Command:
wmic process where name="javaw.exe" call setpriority 128

**Comment by QuImUfu** [comment]
you can already do this using wrapper commands. 
```START /HIGH```
should start Java with high priority. Can not test, not using windows and the start command is not very user friendly as it sometimes seems to bug.
