### ISSUE TITLE
Game crashed before starting, and don't know why.

### ISSUE THREAD

**Issue by MightyPiggie** [MultiMC/MultiMC5#2217]
System Information
-----------------------------
MultiMC version:
0.6.1

Operating System:
Windows 10
10.0.16299 Build 16299

Java Version:
Version 8 Update 161
Summary of the issue or suggestion:
----------------------------------------------
I try to start a mod pack. But when I start it it crashed before starting.
Heres the log: https://paste.ee/p/60zfc

What should happen:
------------------------------
It should start and not crash instantly.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Start the mod pack.

Suspected cause:
---------------------------
I don't know.

Logs/Screenshots:
----------------------------
https://paste.ee/p/60zfc

**Comment by peterix** [comment]
Using 32bit java.

You can get 64bit java here:
http://javadl.oracle.com/webapps/download/AutoDL?BundleId=230542_2f38c3b165be4555a1fa6e98c45e0808

**Comment by MightyPiggie** [comment]
Thanks this fixed it :)
