### ISSUE TITLE
Crash at startup with symbol lookup error (xcb_dri3_get_supported_modifiers)

### ISSUE THREAD

**Issue by QuImUfu** [MultiMC/MultiMC5#2218]
System Information
-----------------------------
MultiMC version:
0.6.1-1127

Operating System:
Lubuntu 17.10 

Summary of the issue or suggestion:
----------------------------------------------
Crash at Startup logging:
```
MultiMC Dir: /home/bambus/MultiMC
No missing dependencies found.
/home/bambus/MultiMC/bin/MultiMC: symbol lookup error: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: xcb_dri3_get_supported_modifiers
```

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. install padoka ppa (git/unstable Graphic stack) (seems to contain newer libxcb* as well)

2. update your system (apt update&apt upgrade)

3. watch MultiMC crash with that error

Suspected cause:
---------------------------
Outdated bundled libxcb-* libs

Additional Info:
---------------------------
Worked around by simply deleting all libxcb-* libs from {MMC-ROOT}/bin.

**Comment by OvermindDL1** [comment]
Still happening on update

**Comment by wundrweapon** [comment]
Confirmed on latest stable, Void Linux glibc amd64. Renaming all the provided libxcd-* SOs to have .bak at the end worked around the issue

**Comment by peterix** [comment]
We no longer ship those libraries, so it should be fine.
