### ISSUE TITLE
Program closes while trying to detect java in settings using autodetect button

### ISSUE THREAD

**Issue by Bfk98** [MultiMC/MultiMC5#2219]
System Information
-----------------------------
MultiMC version:
0.6.1-develop-1127 on lin64
Operating System:
4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Summary of the issue or suggestion:
----------------------------------------------
when going in to settings on a instance and trying to locate Java using the auto detect button
program abruptly closes.

What should happen:
------------------------------
 usually a windows comes up to select the version you would like to use

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. select instance . right click to edit instance

2.select settings  slect java tick box ,
![mybug](https://user-images.githubusercontent.com/36626390/38191906-d5a1ec70-366a-11e8-96e2-e004d4720323.png)
press auto detect on Java page

3.porgram closes

Suspected cause:
---------------------------
unsure

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Janrupf** [comment]
Can you please give us more information about your version, system, javaversion etc...

**Comment by Bfk98** [comment]
![image](https://user-images.githubusercontent.com/36626390/38192205-17e1f1c4-366c-11e8-807f-0a9a5b3d8f74.png)
There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
* 0            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      auto mode
  1            /opt/java/jdk-9/bin/java                         100       manual mode
  2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode

**Comment by mitdyl11** [comment]
![multimc_2018-04-02_18-23-48](https://user-images.githubusercontent.com/679646/38193141-0217b4a0-36a3-11e8-9166-ffe0e22a4047.png)
Also happening to me but only started since a recent update, it works in the global multimc settings but not the instance settings

**Comment by peterix** [comment]
Should be fixed now.
