### ISSUE TITLE
Can't launch the game - java error

### ISSUE THREAD

**Issue by Luysita** [MultiMC/MultiMC5#2221]
**# System Information**
-----------------------------
**MultiMC version:** 0.6.1-1177

**Operating System:** Windows 10 64b

# **Summary of the issue or suggestion:**
Hello, today I assigned more ram to multimc but suddently the chunks started being transparent then I restarted the game. After that the game didn't work anymore following with the java issue:
https://pastebin.com/XSYgLV96
I also am not using any mods, just clean vanilla 1.12.2.
I also tried to re-install java 64b without any success.
Any help is appreciated, thank you!

**Comment by peterix** [comment]
That is a GPU-related crash.

Did you try rebooting the machine after that?

**Comment by peterix** [comment]
Please follow this and upload the report from DxDiag here:
https://github.com/MultiMC/MultiMC5/wiki/Using-DxDiag

**Comment by peterix** [comment]
And please use the Upload button in MultiMC and post the normal log too.

**Comment by Luysita** [comment]
MultiMC error: https://paste.ee/p/qczIY
DxDiag Info: https://pastebin.com/6r9Y4Pnu

**Comment by peterix** [comment]
Alright... so this is some sort of laptop with dual graphics?

The crash is at instruction 0x00007ffdfba70398. This is the closes thing to that, but it's essentially out of range...:
```
0x00007ffdfad20000 - 0x00007ffdfba38000     C:\WINDOWS\SYSTEM32\ig8icd64.dll
```

1. It seems that you are using the integrated Intel GPU instead of the NVidia one. Try to fix that.

2. This looks very suspect, try to remove it:
```
0x00007ffe0d970000 - 0x00007ffe0da0e000     C:\Program Files\Echobit\Evolve\Drivers\EvolveGameTracker_64.dll
0x00007ffe06940000 - 0x00007ffe06b09000     C:\Program Files\Echobit\Evolve\Drivers\EvolveOverlayHelper_64.dll
0x00007ffe242a0000 - 0x00007ffe242c0000     C:\Program Files\Echobit\Evolve\EvolveEasyHook_64.dll
0x00007ffe05ab0000 - 0x00007ffe05b99000     C:\Program Files\Echobit\Evolve\Drivers\EvolveOverlayHelperOGL_64.dll
```

3. You may need to update GPU drivers - both Intel and NVidia.

**Comment by Luysita** [comment]
Oh I uninstalled that software and now works smoothly! Thank you so much for the support!
