### ISSUE TITLE
McLeaks.net Not working

### ISSUE THREAD

**Issue by RobsPlayz** [MultiMC/MultiMC5#2222]
System Information
-----------------------------
MultiMC version:0.61

Operating System:Windows 10 32 bit

Summary of the issue or suggestion: McLeaks.net not working.
----------------------------------------------

What should happen: Login. duh
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
no

**Comment by peterix** [comment]
Intended.
