### ISSUE TITLE
i buy minecraft on window 10 and i can't connect my accout to multimc why?

### ISSUE THREAD

**Issue by Randamick** [MultiMC/MultiMC5#2223]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
If you bought the windows 10 version, then you don't have the java version. If you bought the java version, you have both...

So if you don't have the java version, I can't really help you.

**Comment by Janrupf** [comment]
I think that this should be more clearly on both sides, our (MultiMC) and on minecraft.net.

**Comment by peterix** [comment]
Windows 10... there is no windows 10 anything in MultiMC...

If there will ever be a win32, linux and/or mac version of bedrock, I'll consider it. Until then, this is sadly something I can't do anything about.
