### ISSUE TITLE
Game crashes when trying to load PlusTiC

### ISSUE THREAD

**Issue by jefferyrlc** [MultiMC/MultiMC5#2225]
System Information
-----------------------------
MultiMC version: 0.6.1

Operating System: Windows 7 Professional

Summary of the issue or suggestion:
----------------------------------------------
Client crashes on loading the PlusTiC mod. Mod loads fine with vanilla launcher.

What should happen:
------------------------------
Game starts normally

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. create an instance and install forge

2. Install PlusTiC

3. Start game

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

https://paste.ee/p/EBxed
Additional Info:
---------------------------

**Comment by peterix** [comment]
See: https://github.com/Landmaster/PlusTiC/issues/159

Disable ender io compatibility, or update the mod.

**Comment by 132ikl** [comment]
+1. Are you going to fix this?

**Comment by Janrupf** [comment]
Thats not MultiMC related... Its just modders doing weird things with their mods.

**Comment by 132ikl** [comment]
Disregard, it seems a reinstall fixed this issue.
