### ISSUE TITLE
Suggestion - FTB UI versions list

### ISSUE THREAD

**Issue by brodycas3** [MultiMC/MultiMC5#2229]
I suggest to have some sort of max height that the versions can extend to as to not take up half the screen, And have a scrollbar.
![61wsusg](https://user-images.githubusercontent.com/19770864/38449917-52f5f984-39e3-11e8-9cd2-6cfab847e8ae.png)

**Comment by Janrupf** [comment]
O o, thats Qt xD
I'll see what I can do
