### ISSUE TITLE
multimc will not load a forge 1.6.4 modpack

### ISSUE THREAD

**Issue by davidarad02** [MultiMC/MultiMC5#223]
i play on a private modpack and every time i try to load it, the console stops saying:
2014-04-18 22:18:10 [INFO] [ForgeModLoader] Also searching /Users/davidfamily/Downloads/Sifacraft 2 mac beta 2/MultiMC.app/Contents/MacOS/instances/Jokerpack 1.1/minecraft/mods/1.6.4 for mods
i usually kill is because it never loads (belive me, i left it running for 24 hours and it didnt work....) and i didnt play with this modpack for over 3 weeks now, and i was hoping that you will get an update that will fix this, so please help me trouble shoot it. :)

**Comment by crunkazcanbe** [comment]
I can not get forge 965 for 1.6.4 to start up myself running latest stable multimc as of today .

**Comment by peterix** [comment]
Can't reproduce and I haven't seen the problem mentioned since.

The issue is/was java with forge/FML infinitely recursing into some symlinked folders. It probably doesn't do that anymore.
