### ISSUE TITLE
Order instances by version

### ISSUE THREAD

**Issue by ZeProf2Code** [MultiMC/MultiMC5#2230]
# **Please, can you make an option that sorts with versions of minecraft (From 1.12.2 to 1.0) for example**

**Comment by peterix** [comment]
You mean sorting the instance view?

**Comment by ZeProf2Code** [comment]
Yes

**Comment by ZeProf2Code** [comment]
Can you do it please?

**Comment by peterix** [comment]
Sure, it sounds like a good idea.
It's just that right now, this sort of information is not even loaded unless you take a closer look at the instance, to keep the load times low.

If I do this, it should not force loading of everything for people who don't use it.

**Comment by ZeProf2Code** [comment]
Okay, thanks
