### ISSUE TITLE
MultiMC jvisualvm crash

### ISSUE THREAD

**Issue by Zekken01** [MultiMC/MultiMC5#2234]
System Information
-----------------------------
MultiMC version:
 latest develop 
Operating System:
 Windows 10
Summary of the issue or suggestion:
----------------------------------------------
Launch an instance with jvisualvm

What should happen:
------------------------------
Not crash and burn

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Do not have the java jdk and have jre instead

2.  Maybe having an old idk or both makes it freak out.

3. Installed versions  https://i.imgur.com/SeHUBdb.png

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![image](https://user-images.githubusercontent.com/19770864/38473537-7c3dd30c-3b5f-11e8-853b-d4ac6225b65d.png)

Additional Info:
---------------------------

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to reply and I'll reopen this issue. I was not able to reproduce this with visualvm 1.3.9.0 and setting the instance Java to an JRE.
