### ISSUE TITLE
FTB modpacks don't install with the new tool

### ISSUE THREAD

**Issue by Nyacreeps** [MultiMC/MultiMC5#2235]
System Information
-----------------------------
MultiMC version: latest

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
When trying to install a FTB modpack with the new integrated menu, multi MC downloads the ZIP file and then shows the error message "Failed to move unzipped minecraft!"

What should happen:
------------------------------
Modpack should install and launch

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Try to download a FTB modpack with the integrated menu

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![bug](https://user-images.githubusercontent.com/38208295/38489854-d4bf4262-3be7-11e8-9c82-55e9199b3139.png)

Additional Info:
---------------------------
Installing modpack via a link on curseforge still works

**Comment by peterix** [comment]
Which pack is that?

**Comment by Nyacreeps** [comment]
This is for every FTB modpack

**Comment by peterix** [comment]
OK. All that does is move/rename a folder. And that is failing for some reason.

I'd suspect antivirus doing something weird, as usual.

**Comment by Nyacreeps** [comment]
Indeed it was that... I didn't tried. Sorry to have wasted your time and thank you for the quick response!

**Comment by peterix** [comment]
Nah, it's yet another thing that will need a retry scheme, or a rewrite to avoid antivirus nonsense :)

**Comment by Novocastrian** [comment]
Hi there, 

I have the same error with the latest MultiMC version (0.6.11-1430 as of this comment). I added MultiMC to Windows Firewall and rebooted, and it still errors when downloading the FTB Ultimate pack via the UI. I've tried 4 times, and the temp files still exist in multimc/instances/_mmc_temp/. Do I need to manually pull the packs from twitch launcher/curse to fix this?
