### ISSUE TITLE
MultiMC Log crash

### ISSUE THREAD

**Issue by PercabethRomione** [MultiMC/MultiMC5#2236]
MultiMC version: 0.6.2-1222

Minecraft folder is:
F:/Pc/Minecraft/Minecraft Helpers/MultiMC/instances/UDCCT pack/minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/javaw.exe

Java is version 9.0.4, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/instances/UDCCT pack/natives

Libraries:
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-windows.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar
  F:/Pc/Minecraft/Minecraft Helpers/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Mods:
  [1.7.10] BetterLoadingScreen-em-1.3.8
  [1.7.10]Better_Furnaces_V4.3
  [1.7.10]BFCompatV3.1
  [1.7.10]DamageIndicatorsMod-3.2.3-client
  [1.7.10]InstantMassiveStructuresMod2
  [1.7.10]Treecapitator-universal-2.0.4
  [MC1.7.10]deconstruction[v2.2.5]
  1.7.10_AM2-1.4.0.009
  1.7.10-MB_Battlegear2-Bullseye-1.0.8.3
  1.7.10-Pistronics2-v0.6.4
  ABO-MC1.7.10-BC7.1release4.0.9
  AbyssalCraft Integration-1.7.10-1.4.7
  AbyssalCraft-1.7.10-1.9.1.3-FINAL
  Adventure Backpack
  AdventurersAmulets-1.7.10-1.5.0c
  ae2stuff-0.5.0.55-mc1.7.10
  aether-1.7.10-1.6
  AgriCraft-1.7.10-1.5.0
  AnimationAPI-1.7.10-1.2.4
  antiqueatlas-4.2.2-1.7.10
  AoA-2.4.B
  AOBD-2.8.4
  AOBDsingularities-1.0.4
  AppleCore-mc1.7.10-1.1.0
  appliedenergistics2-rv3-beta-6
  arcane_engineering-0.2.7
  ArchimedesShips-1.7.1
  ArchitectureCraft-1.7.2-mc1.7.10
  Archmagus-1.7.10-0.6.0
  Aroma1997Core-1.7.10-1.0.2.16
  Aroma1997s-Dimensional-World-1.7.10-1.1.0.1
  AromaBackup-1.7.10-0.0.0.5.b20
  Artifacts-1.1.3
  Automagy-1.7.10-0.26.2
  Avaritia-1.11
  Avaritiaddons-1.4
  BaseIO-1.7.10-0.1.0.0-27
  bdlib-1.9.4.109-mc1.7.10
  BetterAchievements-1.7.10-0.1.0
  BetterBuildersWands-0.6.1-1.7.10r80+358ee26
  BetterFps-1.0.1
  BiblioCraft[v1.11.2][MC1.7.10]
  BiblioWoods[BiomesOPlenty][v1.9]
  BiblioWoods[Natura][v1.5]
  BigReactors-0.4.3A
  Billund-1.7.10-0.2.0
  binnie-mods-1.7.10-2.0.22.7
  BiomesOPlenty-1.7.10-2.1.0.1396-universal
  BloodArsenal-1.7.10-1.2-5
  BloodMagic-1.7.10-1.3.3-13
  BluePower-1.7.10-0.2.962-universal
  Botania r1.8-249
  BotanicGarden-1.7.10-0.1
  BrandonsCore-1.0.0.12
  Brewcraft-1.7.10-1.3.3
  Brewing-API-1.7.2-1.2.0
  buildcraft-7.1.18
  BuildcraftAdditions-1.7.10-2.2.5
  buildcraft-compat-7.1.5
  Carpenter's Blocks v3.3.7 - MC 1.7.10
  ChanceCubes-1.7.10-2.1.1.95
  ChestTransporter-2.0.3-MC1.7.10
  ChickenBones-1.7.10-J7
  ChickenChunks-1.7.10-1.3.4.19-universal
  Chisel2-2.3.10.37
  ChiselTones-1.7.10-1.0-1
  chocolateQuest-1.7.10-1.0
  Chunk Pregenerator Version 1.2
  CodeChickenCore-1.7.10-1.0.7.47-universal
  CoFHCore-[1.7.10]3.1.4-329
  compacter-1.1.0.12-mc1.7.10
  compactmachines-1.7.10-1.17
  CompactSolars-1.7.10-4.4.39.315-universal
  compactstorage-1.7.10-release-2.0.0.9-universal
  ComputerCraft1.74
  ConvenientRecipes-1.7.10-1.3.1
  cookingbook-mc1.7.10-1.0.140
  coroutil-1.1.2
  CraftTweaker-1.7.10-3.0.11
  CustomMainMenu-MC1.7.10-1.8-client
  CustomNPCs_1.7.10d
  custompets-1.7.10-1.0.5-universal
  CustomThings-MC1.7.10-0.0.3-55
  D3Core-1.7.10-1.1.0.22
  dark_menagerie-1.7.10-beta-3.1a
  darkcore-0.3-86
  DeadlyWorld-1.7.10-1.0.2
  DeathCounter-4.0.0
  Decocraft-2.4.2_1.7.10
  defaultkeys-mc1.7.10-1.0.4-client
  DefaultWorldGenerator-1.7.10-0.1-b13-client
  denseores-1.6.2
  DifficultLife-1.2.1710.3
  DivineRPG.1.4.1.3
  DoggyTalents-1.7.10-1.14.2.311-universal
  DoomlikeDungeons-1.10.0-MC1.7.10
  Draconic-Evolution-1.7.10-1.0.1c
  Dragon-Mounts-Mod-1.7.10
  DummyCore1.13
  eiramoticons-mc1.7.10-1.2.85-final
  EJML-core-0.26
  emeraldobsidianmod-1.7.10-1.3.1
  EnchantingPlus-1.7.10-3.0.2-d
  Enchiridion-1.7.X-1.2b
  enderbatteries-MC1.7.10-0.1-5
  EnderCompass-1.7.10-1.1
  EnderCore-1.7.10-0.2.0.39_beta
  EnderIO-1.7.10-2.3.0.429_beta
  EnderIOAddons-1.7.10-2.3.0.427_beta-0.10.13.56_beta
  EnderStorage-1.7.10-1.4.7.37-universal
  EnderZoo-1.7.10-1.0.15.32
  EnhancedPortals_1.7.10-universal-3.0.12
  EquivalentEnergistics - 0.7 - 1.7.10
  EquivalentExchange3-1.7.10-0.3.0.547
  EssentialCraftv4.6.1710.70Unofficial
  EternalSingularity-1.7.10-1.0.4
  Eureka-1.7.10-3.0.2
  Ex-Astris-Rebirth-MC1.7.10-1.01-45
  excompressum-mc1.7.10-1.1.113
  Ex-Nihilo-1.38-49
  extrabiomesxl_1.7.10-3.16.4
  ExtraButtons-1.7.10.1
  ExtraCells-1.7.10-2.2.73b129
  Extra-Golems[1.7.10]-1.20
  ExtraGolemsTinkersAddon[1.7.10]-1.08
  ExtraTiC-1.7.10-1.4.5
  extrautilities-1.2.11
  Factorization-1.7.10-0.8.98
  fairylights-1.4.0-1.7.10
  fastcraft-1.23
  FlatBedrock-1.0.2
  FlatSigns-1.7.10-universal-2.1.0.19
  Flesh2Lether [1.7.10b]
  FoodPlus
  Forbidden Magic-1.7.10-0.575
  forestry_1.7.10-4.2.16.64
  FoxLib-1.7.10-0.7.0
  FTBLib-1.7.10-1.0.18.3
  FTBTweaks-1.0.2
  FTBUtilities-1.7.10-1.0.18.3
  FullThrottle_Alchemist-1.7.10-1.0.18a
  funky-locomotion-1.7.10-beta-4
  gadomancy-1.7.10-1.0.7.3
  GalacticraftCore-1.7-3.0.12.502
  Galacticraft-Planets-1.7-3.0.12.502
  gases-1.5.2-1.7.10
  gasesCore-1.5.2-1.7.10
  gasesFramework-1.0.6-1.7.10
  gasesFrameworkCore-1.0.6-1.7.10
  gemsplus-1.7-mc1.7.10
  gendustry-1.6.3.132-mc1.7.10
  gilded-games-util-1.7.10-1.9
  Gravestone
  GravityGun-4.0.0-beta
  GreenThumb-1.7.10-1.1.0.8
  growthcraft-1.7.10-2.6.2-complete
  Guide-API-1.7.10-1.0.1-29
  HammerTime-1.3.6
  HardcoreEnderExpansion  MC-1.7.10  v1.8.5
  Harvest-1.7.10-1.0.0-2
  Hats-4.0.1
  HatStand-4.0.0
  Headcrumbs-1.7.3
  HelpFixer-1.0.7
  hopperductmod-1.7.10-1.3.2
  HungerOverhaul-1.7.10-1.0.0
  iChunUtil-4.2.2
  IguanaTinkerTweaks-1.7.10-2.1.6
  ImLookingAtBlood-1.7.2-1.1a
  ImmersiveEngineering-0.7.7 (1)
  immersiveintegration-0.6.8
  industrialcraft-2-2.2.785-experimental
  InfernalMobs-1.7.10
  InfiniBows-1.7.10-universal-coremod-1.3.0.20
  InGameInfoXML-1.7.10-2.8.1.82-universal
  INpureCore-[1.7.10]1.0.0B9-62
  Insta House v 6.3
  inventorypets-1.7.10-1.4.9.6-universal
  InventoryTweaks-1.59-dev-156
  IrishLuck-1.7.10-0.0.8
  IronBackpacks-1.7.10-1.2.19
  ironchest-1.7.10-6.0.62.742-universal
  ItemBlacklist-1.7.10-1.2.0.8
  IvToolkit-1.2
  Jabba-1.2.1a_1.7.10
  JACB-1.7.10-1.0.2
  JustAFewFish-1.4.1_for_1.7.10
  KaratGarden-0.1.0-[1.7.10]
  Killer Pacman
  Ladders-0.5.0-MC1.7.10
  LagFix-2.0.1-mc1.7.10-forge
  legacyjavafixer-1.0
  Legends Core-1.8.3
  llibrary-0.4.3-1.7.10
  logisticspipes-0.9.3.132
  LookingGlass-1.7.10-0.2.0.01
  Loot++-0.24_for_1.7
  LootBags-1.7.10-2.0.12
  Lots of Food-1.7.10 v7
  Lucky-Cases-1.7.10-1.4.0
  LunatriusCore-1.7.10-1.1.2.21-universal
  LycanitesMobsComplete 1.13.0.5 [1.7.10]
  magicalcrops-4.0.0_PUBLIC_BETA_3
  magicbees-1.7.10-2.4.0
  magneticraft-0.6.1-final
  malisiscore-1.7.10-0.14.1
  malisisdoors-1.7.10-1.13.0
  Mantle-1.7.10-0.3.2a
  Mariculture-Base-1.7.10-1.2.4
  MC Helicopter
  mcjtylib-1.6.1
  Mekanism-1.7.10-9.0.2.271
  MekanismGenerators-1.7.10-9.0.2.271
  MekanismTools-1.7.10-9.0.2.271
  Metallurgy-1.7.10-4.0.9.148
  MetallurgyClassicMachines-1.7.10-1.0.3.75
  MetallurgyCore-1.7.10-4.0.5.30
  MFR Compat - Magical Crops v1-2-1
  MicdoodleCore-1.7-3.0.12.502
  Mineable and Craftible Drops
  Minechem-1.7.10-5.0.5.406
  MineFactoryReloaded-[1.7.10]2.8.0-104
  MineMenu-1.7.10-1.2.0.B44-universal-client
  MineTweakerRecipeMaker-1.7.10-1.1.1
  Minions-1.7.10
  MobAmputation-4.0.0-client
  MobDismemberment-4.0.0-client
  MobiusCore-1.2.5_1.7.10
  ModTweaker2-0.9.6
  ModularPowersuits-0.11.0.283
  MoreCommands_1.7.1710
  MoreEnchantments-1.7.10-1.3.2.1
  More-Planets-1.7.10-1.4.3-GC502
  MorePlanetsExtras-4.0
  Morph-Beta-0.9.3
  Morpheus-1.7.10-1.6.4
  MouseTweaks-2.4.4-mc1.7.10-client
  movingworld-1.7.10-1.7.12B
  mpbasic-1.7.10-1.0.0
  mputils-1.7.10-1.0.8
  MrCrayfish's Furniture Mod
  Mutant Creatures
  mystcraft-1.7.10-0.12.3.00
  natura-1.7.10-2.2.0.1
  neiaddons-1.12.14.40-mc1.7.10
  NEIIntegration-MC1.7.10-1.0.13
  NEIlootbags-1.7.10-1.1.2
  NetherOres-[1.7.10]2.3.0-12
  netherportalfix-mc1.7.10-1.1.0
  NoMobSpawningOnTrees-1.2.0-mc1.7.10
  nomorerain-1.7.10-0.0.1
  NoMoreRecipeConflict-0.2(1.7.10)
  NotEnoughIDs-1.4.3.4
  NotEnoughItems-1.7.10-1.0.5.120-universal
  NotEnoughKeys-1.7.10-1.0.0b29
  NotEnoughResources-1.7.10-0.1.0-128
  NOVA-2015-10-09-universal
  NuclearCraft-1.9e--1.7.10
  Numina-0.4.0.131
  ObsidiPlates-1.7.10-universal-3.0.0.18
  OlympianMod1.1.3
  omlib-1.10.2-3.0.0-101
  OpenBlocks-1.7.10-1.4.4
  OpenComputers-MC1.7.10-1.7.0.1085-universal (3)
  OpenModsLib-1.7.10-0.8
  OptiFine_1.7.10_HD_C1
  orespawn-1.7.10-20.3
  Origin
  p455w0rdslib-1.7.10-1.0.4
  PackGuard-1.7.10-2.3.0d
  Pam's Get all the Seeds 1.7.10a
  Pam's Harvest the Nether 1.7.10a
  Pam's HarvestCraft 1.7.10i
  Pam's Mob Drop Crops 1.7.10a
  peaether-1.7.10-PEA1.0.0
  Peripherals++-1.2.9
  PlayerAPI-1.7.10-1.4
  PneumaticCraft-1.7.10-1.12.7-150-universal
  PortalGun-4.0.0-beta-6
  PortalGunSounds
  PortalGunSounds.pak
  PotionCore-1.2_beta_for_1.7.10
  PotionIDHelper-1.0.4
  Power-Gems-Mod-1.7.10
  ProjectE-1.7.10-PE1.10.1
  ProjectRed-1.7.10-4.7.0pre9.92-Base
  ProjectRed-1.7.10-4.7.0pre9.92-Compat
  ProjectRed-1.7.10-4.7.0pre9.92-Fabrication
  ProjectRed-1.7.10-4.7.0pre9.92-Integration
  ProjectRed-1.7.10-4.7.0pre9.92-Lighting
  ProjectRed-1.7.10-4.7.0pre9.92-Mechanical
  ProjectRed-1.7.10-4.7.0pre9.92-World
  ProjectSuperhuman - 2.0 - Beta 3 - 1.7.10
  qCraft-1.2
  QmunityLib-1.7.10-0.1.114-universal
  QuantumFlux-1.7.10-1.3.4
  QuantumStorage-1.7.10-1.4.2
  Railcraft_1.7.10-9.7.0.0
  RandomThings-2.2.2
  RebornCore-1.1.0.15-universal
  RecurrentComplex-0.9.6.3
  RedstoneArsenal-[1.7.10]1.1.2-92
  Redstonic-v1.4.11
  Reliquary-1.7.10-1.2.1.483
  RenderPlayerAPIEnhancer-1.7.10-1.4
  ResourceLoader-1.2-client
  rftools-3.50
  RikMuldsCore_1.0c
  roguelike-1.7.10-1.4.4
  Ruins-1.7.10
  Sanguimancy-1.7.10-1.1.9-31
  SBM-CardboardBoxes-1.7.10-0.0.1b5-universal
  Schematica-1.7.10-1.7.6.131-universal
  secretroomsmod-1.7.10-4.7.1.413
  Shatter-4.0.0-client
  Simple Diamonds1.7.10_Build1.121
  SimpleLabels-1.7.10-1.0-9
  SimplyJetpacks-MC1.7.10-1.3.2
  SmartRender-1.7.10-2.1
  Snad-1.7.10-1.6.01.31a
  SolarExpansion-Basic-1.6a
  SolarFlux-1.7.10-0.8b
  SpecialMobs-1.7.10-3.2.2
  SpiceOfLife-mc1.7.10-1.2.3
  SquidAPI-1.1.15
  Stacy'sWolvesMod-1.7.10-1.1.2a
  StevesCarts2.0.0.b18
  StevesWorkshop-0.5.1
  StorageDrawers-1.7.10-1.10.7
  StorageDrawers-BiomesOPlenty-1.7.10-1.1.1
  StorageDrawers-Forestry-1.7.10-1.1.2
  StorageDrawers-Misc-1.7.10-1.1.2
  Super Ores V1.3 mc-1.7.10
  supercraftingframe-1.7.10.3
  Superheroes Unlimited-1.7.10-5.0 Alpha 4.2
  Sync-4.0.0
  TabbyChat-1.7.10-1.11.2.2-fml-client
  Tails-1.7.10-1.3.1
  Tainted-Magic-r7.82
  Talismans2-1.7.10-1.1.6
  tardismod-1.7.10-0.994-124-DS
  tcinventoryscan-mc1.7.10-1.0.11
  tcnodetracker-1.7.10-1.1.2
  TConstruct-1.7.10-1.8.7
  Technomancy - 0.12.5 - 1.7.10
  Telepads-1.7.2_1.7
  Teletubbies-1.7.10-0.5.4
  TerraArts-1.1.1710.27
  Thaumaturgical Knowledge-0.1.5.2 - 1.7.10
  Thaumcraft-1.7.10-4.2.3.5
  ThaumcraftMobAspects-1.7.2-2A
  thaumcraftneiplugin-1.7.10-1.7a
  ThaumicBases-1.3.1710.4
  ThaumicEquivalence-1.7.10-1.0.4
  ThaumicExploration-1.7.10-1.1-53
  thaumichorizons-1.7.10-1.1.9
  ThaumicInfusion-1.7.10-3.83
  ThaumicTinkerer-2.5-1.7.10-164
  TheCampingMod_2.1g
  thermalcasting-0.0.3
  ThermalDynamics-[1.7.10]1.1.0-161
  ThermalExpansion-[1.7.10]4.0.3B1-218
  ThermalFoundation-[1.7.10]1.2.0-102
  ThermalSingularities-1.7.10-1.2
  ThermalSmeltery-1.3.1.4
  TiConAutoToolStation-1.7.10-1.1.2
  TiCTooltips-mc1.7.10-1.2.5-client
  tinkersdefense-1.3.7
  TMechworks_mc1.7.10_0.2.8
  TorchTools-1.7.10-1.2.0.26
  Transformers Mod
  Translocator-1.7.10-1.1.2.16-universal
  TravellersGear-1.7.10-1.16.6
  treeGrowingSimulator-0.0.4
  tropicraft-6.0.5
  Twilight Forest Portal Catalyst-1.7.10 [Version 3]
  twilightforest-1.7.10-2.3.7
  Uncrafted 1.7.10 (v.2.2.0)
  UniDict-1.7.10-2.9.2
  Universal Singularities [Version 8]-1.7.10
  Vampirism-1.7.10-0.7.9
  VeinMiner-1.7.10_0.21.2.43
  VeinMiner-1.7.10-0.36.0.496+28a7f13
  VendingMachinesRevamped_1.1.0_1.7.10
  VillagersNose-1.7.10-1.3c
  vorbis-java-core-0.8-20150201.161816-1
  Waila-1.5.10_1.7.10
  WailaHarvestability-mc1.7.10-1.1.3-client
  WanionLib-1.7.10-1.8
  waterhooks-1.2.1
  Wawla-1.0.5.120
  Weeping Angels
  WirelessCraftingTerminal-1.7.10-rv3-1.8.7.4b
  witchery-1.7.10-0.24.1
  WitchingGadgets-1.7.10-1.1.10
  wolfarmor-1.3.0.1
  worldedit-bukkit-6.0
  xprings-1.7.10-1.3.0
  Youtuber Structures
  Youtubers+ Mod
  z[1-7-10]_Lucky_Block_v5-1-0
  ZDoctorBB-1.7.10-Server
  Ztones-1.7.10-2.2.1

Params:
  --username  --version MultiMC5 --gameDir F:/Pc/Minecraft/Minecraft Helpers/MultiMC/instances/UDCCT pack/minecraft --assetsDir F:/Pc/Minecraft/Minecraft Helpers/MultiMC/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType  --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2048m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 5396

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1.

**Comment by QuImUfu** [comment]
use Java 8. 9 is afaik not working for modded minecraft.

**Comment by peterix** [comment]
You can find a suitable version of Java here:
https://java.com/en/download/manual.jsp

Specifically this one: http://javadl.oracle.com/webapps/download/AutoDL?BundleId=230542_2f38c3b165be4555a1fa6e98c45e0808

**Comment by PercabethRomione** [comment]
thanks ill try

**Comment by PercabethRomione** [comment]
didnt work

**Comment by Heufneutje** [comment]
Then you have other problems as well. Please upload a new log.

**Comment by PercabethRomione** [comment]
it pops up the same thing

**Comment by QuImUfu** [comment]
in this case you may have to set up MultiMC to use the correct version of java (Settings->Java -> autodetect -> choose 1.8)
