### ISSUE TITLE
MultiMC

### ISSUE THREAD

**Issue by StarfireSky** [MultiMC/MultiMC5#2237]
System Information
-----------------------------
MultiMC version: 0.6.2

Operating System: windows 10

Summary of the issue or suggestion:
----------------------------------------------
When I updated to the new version all of a sudden my antivirus comes on and takes the MultiMC.exe to quarantine and I end up deleting it I try to redownload it and extracting it to my desktop and I run into the same problem the exe file gets moved to the quarantine every time. What is going on.

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.have Panda Internet Security

2.extract MultiMC to desktop

3.then the antivirus will move the MultiMC exe file to Quarantine

Suspected cause:
---------------------------
There might be a virus in the new version of the MultiMC.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by brodycas3** [comment]
There is no virus in MultiMC it's a false positive. Make an exception for it in your antivirus.
https://www.virustotal.com/#/file/6f0c81841da405849233bfa9953adb18fc96d02c61a609d3b85ff5de615d449b/detection

**Comment by StarfireSky** [comment]
What do you mean brodycas3 make an exception for it in my antivirus. I did and it still did not work.

**Comment by peterix** [comment]
Well, there is absolutely nothing I can do about this. Your AV thing software likely works off a whitelist and until they whitelist the new binaries, it will not work.

You will have to either configure it yourself, or bug them about the false positive.

**Comment by StarfireSky** [comment]
I went back to version 0.5.0 of MultiMC and it is working just find but as soon as I update it to the new version that is where to trouble begins. Why is version 0.5.0 works just find for me but not the new version I think that is weird.

**Comment by Heufneutje** [comment]
There is nothing weird about the version. The only weird thing is your antivirus detecting a false positive for some reason or another, which you should report to them.
