### ISSUE TITLE
divide by zero in instance creation

### ISSUE THREAD

**Issue by brodycas3** [MultiMC/MultiMC5#2238]
pasting
```c++
int main()
{
    int i = 1 / 0;
}
```
into the create an instance causes weird stuff

**Comment by peterix** [comment]
Instance naming needs some filtering:
* normalize whitespace to single spaces
* strip newlines and weird characters

For the on-disk name:
* strip/ASCII-ize unicode

**Comment by peterix** [comment]
Also see:
https://github.com/MultiMC/MultiMC5/issues/847
https://github.com/MultiMC/MultiMC5/issues/1105
https://github.com/MultiMC/MultiMC5/issues/1674

**Comment by peterix** [comment]
This particular instance of this problem has been fixed in develop.
