### ISSUE TITLE
Server list Reset

### ISSUE THREAD

**Issue by Mark154872** [MultiMC/MultiMC5#2243]
System Information
-----------------------------
MultiMC version: Lasted

Operating System:
Windowns 10 64x
Summary of the issue or suggestion:
The list of servers is reset when I click to update

What should happen:
Should not reset

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
That is actually a bug in the game. See: https://bugs.mojang.com/browse/MC-39583

Still unfixed. And I can't really do much about it right now.

**Comment by Mark154872** [comment]
But this happens when I use MultiMC, using the normal minecraft launcher does not reset

**Comment by peterix** [comment]
This has nothing to do with what launcher you use.

**Comment by peterix** [comment]
And where is MultiMC located (what path on the filesystem)?

**Comment by Mark154872** [comment]
Avast
The files are in a saved folder in the documents
And not

**Comment by peterix** [comment]
Antivirus software can interfere with file access. Try to disable it temporarily as an experiment and see what happens.

**Comment by Heufneutje** [comment]
Or add an exception to your antivirus to exclude the server list.
