### ISSUE TITLE
[Fixed]Unable to use more then 1GB of memory (How to fix)

### ISSUE THREAD

**Issue by superpowers04** [MultiMC/MultiMC5#2244]
How to Fix This Problem:
Make Sure To Have A 64 Bit Java :D

**Comment by peterix** [comment]
You are most likely using 32bit java. Get the 64bit one:
http://javadl.oracle.com/webapps/download/AutoDL?BundleId=230542_2f38c3b165be4555a1fa6e98c45e0808

And make sure MultiMC uses it (look at the architecture column of the java version list). You can change Java by using the 'auto detect' button in the java settings.

**Comment by superpowers04** [comment]
I know im late to comment back but thanks for the help it fixed it
