### ISSUE TITLE
Fail to launch a forge-installed instance, and reason shows"it was impossible to fetch the required libraries. "

### ISSUE THREAD

**Issue by RisingInIris2017** [MultiMC/MultiMC5#2247]
System Information
-----------------------------
MultiMC version:
MultiMC 0.6.2 released!
Operating System:
Windows 10 Home
Summary of the issue or suggestion:
When I tried to run a Forge-installed Minecraft 1.12.2 instance,  MultiMC failed to run the game if choose the *"Launch"* option, but _"Launch Offline"_ works well.
I have tested two instances. One is Forge 14.23.3.2668, while the other is Forge 14.23.3.2655. They have the same issue, which is reported in this Issue.
----------------------------------------------

What should happen:
------------------------------
Game should be launched properly.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Choose an instance

2.Click "Launch".  

Suspected cause:
---------------------------
Console window says:
Reason:
Job 'Libraries for instance BLTest' failed to process:
http://files.minecraftforge.net/maven/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar.pack.xz.
Maybe it is similar to [this Issue](https://github.com/MultiMC/MultiMC5/issues/1118), which is already closed.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
I tried several times to use the "Upload" button to upload the Console window's output, but it failed, showing "Connection timed out". Considering that the log is short, I paste it here instead.

`MultiMC version: 0.6.2-1222

Minecraft folder is:
D:/Applications/Minecraft_Java_Edition/MultiMC/instances/1.12.21/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_161/bin/javaw.exe

Java is version 1.8.0_161, using 64-bit architecture.

Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance BLTest' failed to process:
http://files.minecraftforge.net/maven/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar.pack.xz. `

Additional Info:
---------------------------

**Comment by RisingInIris2017** [comment]
I am regretted to say that English is not my mother tongue, but I tried to report the Issue properly.

**Comment by peterix** [comment]
#1118 is definitely not related.
Are you able to download that file in a browser?

**Comment by RisingInIris2017** [comment]
Sure, I am able to download that file in a browser.
Well, before I post this Issue, I only noticed the "akka-actor" and have searched all Issues here, and I found the Issue #1118.  I know little about this file and its function, so my suspicion is only based on its name.
