### ISSUE TITLE
I get logged out of my account every time I connect to a different network!

### ISSUE THREAD

**Issue by NoahJelen** [MultiMC/MultiMC5#2250]
System Information
-----------------------------
MultiMC version:
0.6.2

Operating System:
Linux Mint 18.3 with Linux 4.13

Summary of the issue or suggestion:
----------------------------------------------
Every time I connect to a different network, I get logged out of my minecraft account.

What should happen:
------------------------------
I should be able to stay logged into my minecraft account even if I change what network I'm connected to

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Launch MultiMC

2.Log into a minecraft account (if not done already)

3.Change what network the computer is connected to

4. Try to launch an instance of minecraft
Logs/Screenshots:
----------------------------
![image](https://user-images.githubusercontent.com/29718341/38998850-5552f2b0-43a5-11e8-8045-8a6e0fa2cf60.png)

**Comment by peterix** [comment]
I cannot fix this. It is the server recognizing where you are logging in from and refusing you.

This is a measure against account stealing.
