### ISSUE TITLE
Can't Install Forge

### ISSUE THREAD

**Issue by St0n3henge** [MultiMC/MultiMC5#2251]
System Information
-----------------------------
MultiMC version: 5

Operating System: win 10

Summary of the issue or suggestion: I can launchminecraft but won't launch when I add Forge
----------------------------------------------

What should happen: It should work with Forge
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. I added Forge Version 1.2.2.1147 for Mineccraft 1.7.2

2. I launched the instance

3. The instance would not launch

Suspected cause:
---------------------------
I don't have a clue. I just got this program and i'm not very good at it.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

https://paste.ee/p/BXoIv

Additional Info:
---------------------------
I use Windows 10 on a 64 bit system.

**Comment by peterix** [comment]
Either use a later version of Forge, or the http://files.minecraftforge.net/LegacyJavaFixer/legacyjavafixer-1.0.jar mod.

**Comment by QuImUfu** [comment]
note: there is no version of forge *for 1.7.2 and 1.6.4* that works without that mod.
