### ISSUE TITLE
Login to Mojang account good but not likely to be premium

### ISSUE THREAD

**Issue by samsung80** [MultiMC/MultiMC5#2253]
Hello when I want to connect to MultiMc with my account Mojang he tells me that this account is likely to be premium, I'll show you the screenshots (yes I'm French)

I already change my password.

![capture](https://user-images.githubusercontent.com/38624651/39096846-2ae0e07a-4655-11e8-85a0-960ac7cf9f17.PNG)
![capture](https://user-images.githubusercontent.com/38624651/39096895-a1d403f6-4655-11e8-9d99-c999b0cbea26.PNG)

**Comment by peterix** [comment]
Well, no idea. I'd say check the log, but it's been so long that this is just kinda sad.

Reopen if you still care.
