### ISSUE TITLE
MultiMC has problems with fetching meta file on Linux

### ISSUE THREAD

**Issue by Mcpg** [MultiMC/MultiMC5#2256]
System Information
-----------------------------
MultiMC version: 0.6.2-843

Operating System: Debian Testing

Summary of the issue or suggestion:
----------------------------------------------
When trying to create a new instance MultiMC throws this error:

> List update failed:
> Job 'Download of meta file net.minecraft/index.json failed to
> process:
> https://v1.meta.multimc.org/net.minecraft/index.json`

(The problem doesn't appear on Windows. Both 32-bit and 64-bit versions are faulty)

What should happen:
------------------------------
MultiMC should properly fetch index.json metafile.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Start MultiMC

2. Press `Add Instance` button

Suspected cause:
---------------------------
Maybe MultiMC has problems with using SSL library.

Logs/Screenshots:
----------------------------

![Error](https://user-images.githubusercontent.com/8002811/39314283-32c06fc8-4974-11e8-9350-1f7750b3cd47.png)

>   409.310 D Task "NetJob(Download of meta file net.minecraft/index.json)" started
>   409.313 D Downloading  "https://v1.meta.multimc.org/net.minecraft/index.json"
>   409.330 W QSslSocket: cannot call unresolved function SSLv23_client_method
>   409.330 W QSslSocket: cannot call unresolved function SSL_library_init
>   409.330 C Failed  "https://v1.meta.multimc.org/net.minecraft/index.json"  with reason  99
>   409.330 D Download failed in previous step: "https://v1.meta.multimc.org/net.minecraft/index.json"
>   409.331 D Downloading  "https://v1.meta.multimc.org/net.minecraft/index.json"
>   409.348 W QSslSocket: cannot call unresolved function SSLv23_client_method
>   409.348 W QSslSocket: cannot call unresolved function SSL_library_init
>   409.348 C Failed  "https://v1.meta.multimc.org/net.minecraft/index.json"  with reason  99
>   409.348 D Download failed in previous step: "https://v1.meta.multimc.org/net.minecraft/index.json"
>   409.349 D Downloading  "https://v1.meta.multimc.org/net.minecraft/index.json"
>   409.365 W QSslSocket: cannot call unresolved function SSLv23_client_method
>   409.365 W QSslSocket: cannot call unresolved function SSL_library_init
>   409.365 C Failed  "https://v1.meta.multimc.org/net.minecraft/index.json"  with reason  99
>   409.365 D Download failed in previous step: "https://v1.meta.multimc.org/net.minecraft/index.json"
>   409.365 D Downloading  "https://v1.meta.multimc.org/net.minecraft/index.json"
>   409.381 W QSslSocket: cannot call unresolved function SSLv23_client_method
>   409.381 W QSslSocket: cannot call unresolved function SSL_library_init
>   409.381 C Failed  "https://v1.meta.multimc.org/net.minecraft/index.json"  with reason  99
>   409.381 D Download failed in previous step: "https://v1.meta.multimc.org/net.minecraft/index.json"
>   409.381 C Task "NetJob(Download of meta file net.minecraft/index.json)" failed:  "Job 'Download of meta file net.minecraft/index.json' failed to process:
> https://v1.meta.multimc.org/net.minecraft/index.json"

**Comment by peterix** [comment]
Yes, your system does not have a compatible version of openssl installed.

Try installing `openssl1.0`

**Comment by Mcpg** [comment]
I actually have 1.0.2 on the system.
Installing package `libssl1.0-dev` fixed the problem on Debian.

**Comment by peterix** [comment]
I should stop bundling Qt. That's what I should do.

That is on the TODO list...

**Comment by Scottbert85** [comment]
How do I just manually give it the json file it wants?
