### ISSUE TITLE
multimc wont open after a system restore.

### ISSUE THREAD

**Issue by mattrix444** [MultiMC/MultiMC5#2258]
System Information
-----------------------------
MultiMC version: 0.6.2

Operating System: windows 10 ultimate

Summary of the issue or suggestion:
----------------------------------------------
i did a system restore yesterday and now multimc wont open. i re downloaded it and extracted it as i did before but the loading circle pops up but then nothing happens. just looking for advice thanks :)

**Comment by peterix** [comment]
Well, sorry for not responding... I guess noone had any idea what might be wrong.
