### ISSUE TITLE
again i cant open minecraft i installed codechicken lib it didnt show the same but it crashed

### ISSUE THREAD

**Issue by ManvisPlayz** [MultiMC/MultiMC5#2259]
https://paste.ee/p/wyLJy

**Comment by savosdarkran** [comment]
The error you are receiving is because Java is running out of memory.  Try increasing the amount of ram you give the instance.  Right now it's only getting 1G max.

**Comment by ManvisPlayz** [comment]
thx


2018-04-27 16:26 GMT+03:00 Savos Darkran <notifications@github.com>:
