### ISSUE TITLE
 Apache Maven library folder was not in the format expected

### ISSUE THREAD

**Issue by 3jlowes** [MultiMC/MultiMC5#2260]
System Information
-----------------------------
MultiMC version: MultiMC 5

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Unable to launch. Failed to start minecraft. An error occurred trying to configure the Minecraft home

Suspected cause:
---------------------------
No idea. I was using multimc fine just a few days ago

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/WgDOm

**Comment by peterix** [comment]
Looks like a forge bug to me.

**Comment by 3jlowes** [comment]
How do you know? Any suggestions on what I can do to get minecraft launching?

**Comment by peterix** [comment]
Try either build 2655 or latest. Preferably 2655.

**Comment by 3jlowes** [comment]
Well I loaded forge 2674 and worked fine (latest) Thanks for your help!
