### ISSUE TITLE
Authentication failure in game (after successful login with MultiMC)

### ISSUE THREAD

**Issue by NotLogan** [MultiMC/MultiMC5#2261]
System Information
-----------------------------
MultiMC version: 0.6.2-1137

Operating System: Ubuntu 18.04 bionic (Budgie desktop)

Summary of the issue: 
----------------------------------------------
Authentication/sign-in within MultiMC works, game launches and detects servers; however, it fails to contact Mojang's authentication server.

MultiMC status icons detect auth servers are online.
Single player works perfectly, and using the official launcher does not have this issue.

What should happen:
------------------------------
The authentication from the MultiMC launcher should remain when launching the game

Steps to reproduce the issue:
-------------------------------------------------------------
1. Launch any instance within MultiMC after logging in.

2. Open up multiplayer and attempt to join a server. (servers should appear to be normal)

3. Error message: "Failed to login: The authentication servers are currently down for maintenance." (however, they are not down)

Suspected cause:
---------------------------
User account information transfer issue between MultiMC and the game itself.

Logs/Screenshots:
----------------------------
Minecraft: https://paste.ee/p/G3x1u
MultiMC: https://hastebin.com/osuhayujow.java

![image](https://user-images.githubusercontent.com/38818416/39400334-1ba25596-4af4-11e8-97a5-df975fe02058.png)

![image](https://user-images.githubusercontent.com/38818416/39400337-26b015d6-4af4-11e8-95a6-9ccb994087f8.png)

Additional Info:
---------------------------
I have tried Java 8 and 10 with identical results. And as I mentioned above, the vanilla client works without problem using the same install.

Reinstall does not solve issue
Applies to Lutris install and clean install (if that matters at all)

**Comment by QuImUfu** [comment]
Can not reproduce.
Joining a server with a fresh installation of ubuntu budgie works flawless on my PC.

**Comment by peterix** [comment]
This is a problem with Java, its SSL certificate store, and how things are packaged onm 18.04.

Workaround:
```
sudo sed -i 's/keystore.type=\s*pkcs12/keystore.type=jks/' /etc/java-*/security/java.security
sudo rm /etc/ssl/certs/java/cacerts
sudo update-ca-certificates -f
```

Upstream bug: https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/1739631

**Comment by Janrupf** [comment]
So, had the same problem... if removing the certs does not work, purge all java packages (ALL).
This is going to uninstall MultiMC but your instances are not lost.
Use `apt get install openjdk-8-jdk` to install java. This may break dpkg/apt, but running `apt install -f` fixes it.
Now install MultiMC angain and have fun playing on servers.

**Comment by peterix** [comment]
Upstream bug has `Fix Released`, closing.
