### ISSUE TITLE
MultiMC Modpack fail

### ISSUE THREAD

**Issue by TrippinRome** [MultiMC/MultiMC5#2263]
I have been trying to play a minecraft modpack (Project Ozone: Reloaded) on linux MultiMc launcher, I've added the instance for the modpack but every time I click launch an error message says 

> Instance update failed because: Failed to read the assets index!.

And Every time I click the launch offline it asks me what nickname I'd like to go by offline and then does nothing.

Here is the complete log when I click the launch button after selecting the modpack instance.

> MultiMC version: 0.6.2-1137

Minecraft folder is:
/home/layton/Desktop/Ozone/MultiMC/instances/Project+Ozone+2+Reloaded-2.4.0/.minecraft

Java path is:
/usr/bin/java

Java is version 1.8.0_171, using 64-bit architecture.

Instance update failed because: Failed to read the assets index!.

MultiMC: Log upload triggered at: 29 Apr 2018 01:04:59 -0400

**Comment by Janrupf** [comment]
We do not need the Minecraft Log... We need the MultiMC Log. MultiMC writes detailed error messages if thy are not from minecraft into multimc.log (<- this file name can be a bit different). This is the important file.

**Comment by peterix** [comment]
Hmmm... if I were to guess, I would guess it was some network issue. Oh well.
