### ISSUE TITLE
"Failed to start Minecraft" bug with Forge installed

### ISSUE THREAD

**Issue by b1tchduck** [MultiMC/MultiMC5#2264]
System Information
-----------------------------
MultiMC version: 0.6.2-1137

Operating System: lin64 (Ubuntu 18.04)

Summary of the issue or suggestion:
----------------------------------------------
Minecraft fails to launch when Forge is installed via the "Install Forge" button.

What should happen:
------------------------------
Forge should launch and run as expected, but instead the console spits out a "Minecraft failed to start" error due to (i think?) the OneSix Launcher

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a new instance

2. Install forge from within MultiMC

3. Attempt to launch the program.

Suspected cause:
---------------------------
Unknown - the log indicates something about "OneSix" but i'm not sure what that is.

Logs/Screenshots:
----------------------------
https://paste.ee/p/pXVIt is the same long I get every time.

Additional Info:
---------------------------
Forge was working fine yesterday after upgrading to Bionic Beaver (18.04), and all prior Forge boots worked fine on 16.04. I'm not sure why it's suddenly refused to launch any of my Forge profiles - my vanilla ones (versions 1.12 and a b1.0) work perfectly fine.

**Comment by Heufneutje** [comment]
Java versions 9 and above do not currently work with Forge. Try Java 8.
