### ISSUE TITLE
Can't login to minecraft account - linux based on debian, multimc5

### ISSUE THREAD

**Issue by Tavarnarmo** [MultiMC/MultiMC5#2265]
Hello,
I tried to run multiMC 5 on BunsenLabs Helium linux distro (based on debian stable) but can't login to minecraft. When I removed qt5 files from multimc binary folder it don't run at all.

System Information
-----------------------------
MultiMC version:
5

Operating System:
BunsenLabs Helium

Summary of the issue or suggestion:
Can't login to minecraft.
----------------------------------------------

What should happen:
Should be able to login.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Install BunsenLabs Helium.

2. Install multiMC 5.

3. Try to login to minecraft.

Suspected cause:
---------------------------
No idea.

Logs/Screenshots:
----------------------------

Additional Info:
---------------------------

**Comment by peterix** [comment]
I'll need to at least see the log (`MultiMC.0.log`) to be able to help you at all.

1. Run MultiMC
2. Try to log in
3. Attach the log it produces here, make sure to anonymize it

**Comment by Tavarnarmo** [comment]
`    0.000 D <> Log initialized.
    0.000 D MultiMC 5, (c) 2013-2018 MultiMC Contributors
    0.000 D Version                    :  "0.6.2-1137"
    0.000 D Git commit                 :  "6284f070c19053ae2bcf26dd9bccac2e0d35477f"
    0.000 D Git refspec                :  "refs/heads/stable"
    0.000 D Work dir before adjustment :  "/home/.../.local/share/multimc"
    0.000 D Work dir after adjustment  :  "/home/.../.local/share/multimc"
    0.001 D Adjusted by                :  "Command line /home/.../.local/share/multimc"
    0.001 D Binary path                :  "/home/.../.local/share/multimc/bin"
    0.001 D Application root path      :  "/home/.../.local/share/multimc"
    0.001 D <> Paths set.
    0.007 D Detected default console font: "Noto Mono" , substitutions: ""
    0.008 D <> Settings loaded.
    0.008 C Exception: "Unable to open /home/.../.local/share/multimc/translations/index for reading: No such file or directory"
    0.008 C Translations Download Failed: index file not readable
    0.008 W Selected invalid language "" , defaulting to "en"
    0.008 D Your language is ""
    0.008 D <> Translations loaded.
    0.008 D <> Updater started.
    0.009 D Started watching  "/home/.../.local/share/multimc/icons"
    0.009 D <> Instance icons intialized.
    0.009 D <> Icon themes initialized.
    0.009 D ""
    0.009 D Loading theme "custom"
    0.026 D No theme json present.
    0.062 D No theme css present.
    0.106 D <> Widget themes initialized.
    0.106 D Instance path              :  "instances"
    0.106 D Loading Instances...
    0.106 D <> Instances loaded.
    0.106 D Loading accounts...
    0.106 C "Failed to read the account list file (accounts.json)."
    0.106 D <> Accounts loaded.
    0.106 D <> Cache initialized.
    0.106 D Detecting proxy settings...
    0.106 D Using no proxy is an option!
    0.106 D <> Proxy settings done.
    0.106 D Downloading Translations Index...
    0.106 D Task "NetJob(Translations Index)" started
    0.107 D <> Icon theme set.
    0.107 D <> Application theme set.
    0.148 D Analytics info not seen by user yet (or old version).
    0.263 D Downloading  "http://files.multimc.org/translations/index"
    0.271 W QSslSocket: cannot resolve CRYPTO_num_locks
    0.271 W QSslSocket: cannot resolve CRYPTO_set_id_callback
    0.271 W QSslSocket: cannot resolve CRYPTO_set_locking_callback
    0.271 W QSslSocket: cannot resolve ERR_free_strings
    0.271 W QSslSocket: cannot resolve sk_new_null
    0.271 W QSslSocket: cannot resolve sk_push
    0.271 W QSslSocket: cannot resolve sk_free
    0.271 W QSslSocket: cannot resolve sk_num
    0.271 W QSslSocket: cannot resolve sk_pop_free
    0.271 W QSslSocket: cannot resolve sk_value
    0.271 W QSslSocket: cannot resolve SSL_library_init
    0.271 W QSslSocket: cannot resolve SSL_load_error_strings
    0.271 W QSslSocket: cannot resolve SSLv3_client_method
    0.271 W QSslSocket: cannot resolve SSLv23_client_method
    0.271 W QSslSocket: cannot resolve SSLv3_server_method
    0.271 W QSslSocket: cannot resolve SSLv23_server_method
    0.272 W QSslSocket: cannot resolve X509_STORE_CTX_get_chain
    0.272 W QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
    0.272 W QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
    0.272 W QSslSocket: cannot resolve SSLeay
    0.272 W QSslSocket: cannot resolve SSLeay_version
    0.272 W QSslSocket: cannot call unresolved function CRYPTO_num_locks
    0.272 W QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
    0.272 W QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
    0.272 W QSslSocket: cannot call unresolved function SSL_library_init
    0.272 W QSslSocket: cannot call unresolved function SSLv23_client_method
    0.273 W QSslSocket: cannot call unresolved function sk_num
    0.549 D Download succeeded: "http://files.multimc.org/translations/index"
    0.549 D Task "NetJob(Translations Index)" succeeded
    0.549 D Got translations index!
    5.514 D Task "NetJob(Translation for pl)" started
    5.515 D Downloading  "http://files.multimc.org/translations/pl.qm"
    5.651 D Download succeeded: "http://files.multimc.org/translations/pl.qm"
    5.652 D Task "NetJob(Translation for pl)" succeeded
    5.652 D Got translation: "pl"
    5.652 D Loading Application Language File for pl ...
    6.845 D Task "JavaListLoadTask(0x2570250)" started
    6.845 D Linux Java detection incomplete - defaulting to "java"
    6.865 D Probing the following Java paths: 
    6.865 D   "java"
    6.865 D   "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java"
    6.865 D   "/usr/lib/jvm/java-8-openjdk-amd64/bin/java"
    6.865 D   "/usr/lib/jvm/java-9-openjdk-amd64/jre/bin/java"
    6.865 D   "/usr/lib/jvm/java-9-openjdk-amd64/bin/java"
    6.865 D Task "JavaCheckerJob(0x256e020)" started
    6.865 D "Java detection"  started.
    6.865 D Env: ignoring "QT_IM_MODULE" "compose"
    6.865 D Env: ignoring "QT_ACCESSIBILITY" "1"
    6.866 D Env: ignoring "LD_PRELOAD" ""
    6.866 D Env: ignoring "QT_FONTPATH" "/home/.../.local/share/multimc/fonts"
    6.866 D Env: ignoring "QT_QPA_PLATFORMTHEME" "gtk2"
    6.866 D Env: ignoring "QT_PLUGIN_PATH" "/home/.../.local/share/multimc/plugins"
    6.866 D Env: ignoring "LD_LIBRARY_PATH" "/home/.../.local/share/multimc/bin:"
    6.866 D Env: ignoring "QT_LINUX_ACCESSIBILITY_ALWAYS_ON" "1"
    6.866 D "Running java checker: java-jar /home/.../.local/share/multimc/bin/jars/JavaCheck.jar"
    6.867 D Env: ignoring "QT_IM_MODULE" "compose"
    6.867 D Env: ignoring "QT_ACCESSIBILITY" "1"
    6.867 D Env: ignoring "LD_PRELOAD" ""
    6.867 D Env: ignoring "QT_FONTPATH" "/home/.../.local/share/multimc/fonts"
    6.868 D Env: ignoring "QT_QPA_PLATFORMTHEME" "gtk2"
    6.868 D Env: ignoring "QT_PLUGIN_PATH" "/home/.../.local/share/multimc/plugins"
    6.868 D Env: ignoring "LD_LIBRARY_PATH" "/home/.../.local/share/multimc/bin:"
    6.868 D Env: ignoring "QT_LINUX_ACCESSIBILITY_ALWAYS_ON" "1"
    6.868 D "Running java checker: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java-jar /home/.../.local/share/multimc/bin/jars/JavaCheck.jar"
    6.869 D Env: ignoring "QT_IM_MODULE" "compose"
    6.869 D Env: ignoring "QT_ACCESSIBILITY" "1"
    6.869 D Env: ignoring "LD_PRELOAD" ""
    6.869 D Env: ignoring "QT_FONTPATH" "/home/.../.local/share/multimc/fonts"
    6.869 D Env: ignoring "QT_QPA_PLATFORMTHEME" "gtk2"
    6.869 D Env: ignoring "QT_PLUGIN_PATH" "/home/.../.local/share/multimc/plugins"
    6.869 D Env: ignoring "LD_LIBRARY_PATH" "/home/.../.local/share/multimc/bin:"
    6.869 D Env: ignoring "QT_LINUX_ACCESSIBILITY_ALWAYS_ON" "1"
    6.869 D "Running java checker: /usr/lib/jvm/java-8-openjdk-amd64/bin/java-jar /home/.../.local/share/multimc/bin/jars/JavaCheck.jar"
    6.871 D Env: ignoring "QT_IM_MODULE" "compose"
    6.871 D Env: ignoring "QT_ACCESSIBILITY" "1"
    6.871 D Env: ignoring "LD_PRELOAD" ""
    6.871 D Env: ignoring "QT_FONTPATH" "/home/.../.local/share/multimc/fonts"
    6.871 D Env: ignoring "QT_QPA_PLATFORMTHEME" "gtk2"
    6.871 D Env: ignoring "QT_PLUGIN_PATH" "/home/.../.local/share/multimc/plugins"
    6.871 D Env: ignoring "LD_LIBRARY_PATH" "/home/.../.local/share/multimc/bin:"
    6.871 D Env: ignoring "QT_LINUX_ACCESSIBILITY_ALWAYS_ON" "1"
    6.871 D "Running java checker: /usr/lib/jvm/java-9-openjdk-amd64/jre/bin/java-jar /home/.../.local/share/multimc/bin/jars/JavaCheck.jar"
    6.872 D Env: ignoring "QT_IM_MODULE" "compose"
    6.872 D Env: ignoring "QT_ACCESSIBILITY" "1"
    6.872 D Env: ignoring "LD_PRELOAD" ""
    6.873 D Env: ignoring "QT_FONTPATH" "/home/.../.local/share/multimc/fonts"
    6.873 D Env: ignoring "QT_QPA_PLATFORMTHEME" "gtk2"
    6.873 D Env: ignoring "QT_PLUGIN_PATH" "/home/.../.local/share/multimc/plugins"
    6.873 D Env: ignoring "LD_LIBRARY_PATH" "/home/.../.local/share/multimc/bin:"
    6.873 D Env: ignoring "QT_LINUX_ACCESSIBILITY_ALWAYS_ON" "1"
    6.873 D "Running java checker: /usr/lib/jvm/java-9-openjdk-amd64/bin/java-jar /home/.../.local/share/multimc/bin/jars/JavaCheck.jar"
    6.884 D Java checker has failed to start.
    6.885 D "Java detection" progress: 1 / 5
    8.051 D STDOUT "os.arch=amd64
java.version=1.8.0_171
"
    8.051 W STDERR ""
    8.051 D Java checker finished with status  0  exit code  0
    8.051 D Java checker succeeded.
    8.051 D "Java detection" progress: 2 / 5
    8.051 D STDOUT "os.arch=amd64
java.version=1.8.0_171
"
    8.051 W STDERR ""
    8.051 D Java checker finished with status  0  exit code  0
    8.051 D Java checker succeeded.
    8.051 D "Java detection" progress: 3 / 5
    8.159 D STDOUT "os.arch=amd64
java.version=9-Debian
"
    8.159 W STDERR ""
    8.159 D Java checker finished with status  0  exit code  0
    8.159 D Java checker succeeded.
    8.159 D "Java detection" progress: 4 / 5
    8.160 D STDOUT "os.arch=amd64
java.version=9-Debian
"
    8.160 W STDERR ""
    8.160 D Java checker finished with status  0  exit code  0
    8.160 D Java checker succeeded.
    8.160 D "Java detection" progress: 5 / 5
    8.161 D Task "JavaCheckerJob(0x256e020)" succeeded
    8.161 D Found the following valid Java installations:
    8.161 D   "9-Debian" "64" "java"
    8.161 D   "1.8.0_171" "64" "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java"
    8.161 D   "1.8.0_171" "64" "/usr/lib/jvm/java-8-openjdk-amd64/bin/java"
    8.161 D   "9-Debian" "64" "/usr/lib/jvm/java-9-openjdk-amd64/bin/java"
    8.161 D Task "JavaListLoadTask(0x2570250)" succeeded
    8.162 D Env: ignoring "QT_IM_MODULE" "compose"
    8.162 D Env: ignoring "QT_ACCESSIBILITY" "1"
    8.162 D Env: ignoring "LD_PRELOAD" ""
    8.162 D Env: ignoring "QT_FONTPATH" "/home/.../.local/share/multimc/fonts"
    8.162 D Env: ignoring "QT_QPA_PLATFORMTHEME" "gtk2"
    8.162 D Env: ignoring "QT_PLUGIN_PATH" "/home/.../.local/share/multimc/plugins"
    8.162 D Env: ignoring "LD_LIBRARY_PATH" "/home/.../.local/share/multimc/bin:"
    8.162 D Env: ignoring "QT_LINUX_ACCESSIBILITY_ALWAYS_ON" "1"
    8.163 D "Running java checker: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java-Xms512m -Xmx1024m -jar /home/.../.local/share/multimc/bin/jars/JavaCheck.jar"
    8.206 D STDOUT "os.arch=amd64
java.version=1.8.0_171
"
    8.207 W STDERR ""
    8.207 D Java checker finished with status  0  exit code  0
    8.207 D Java checker succeeded.
   17.518 D Analytics enabled by user.
   17.519 D Wizard result = 1
   17.546 W QMetaObject::connectSlotsByName: No matching signal for on_actionInstanceSettings_triggered()
   17.548 D Task "NetJob(Status JSON)" started
   17.549 D Reloading news.
   17.549 D Task "NetJob(News RSS Feed)" started
   17.549 D Checking for updates.
   17.549 D Channel list isn't loaded yet. Loading channel list and deferring update check.
   17.549 D Loading the channel list.
   17.549 D Task "NetJob(Update System Channel List)" started
   17.549 D Task "NetJob(Checking for notifications)" started
   17.562 D Viewport size "694x563"
   17.562 D RAM size is 7927 MB
   17.620 D "Distributor ID:	BunsenLabs
Description:	BunsenLabs GNU/Linux 9.4 (Helium)
Release:	9.4
Codename:	helium
"
   17.625 D [Analytics] "ScreenView: Main Window"
   17.625 D <> Main window shown.
   17.625 D Downloading  "http://status.mojang.com/check"
   17.626 D Downloading  "http://multimc.org/rss.xml"
   17.626 D Downloading  "http://files.multimc.org/update/lin64/channels.json"
   17.626 D Downloading  "http://files.multimc.org/notifications.json"
   17.733 D Location header:  QUrl( "https://multimc.org/rss.xml" ) 
   17.733 D Following redirect to  "https://multimc.org/rss.xml"
   17.733 D Downloading  "https://multimc.org/rss.xml"
   17.733 D Download redirected: "https://multimc.org/rss.xml"
   17.760 W QSslSocket: cannot call unresolved function SSLv23_client_method
   17.760 W QSslSocket: cannot call unresolved function SSL_library_init
   17.792 W QSslSocket: cannot call unresolved function SSLv23_client_method
   17.792 W QSslSocket: cannot call unresolved function SSL_library_init
   17.792 C Failed  "https://multimc.org/rss.xml"  with reason  99
   17.792 D Download failed in previous step: "https://multimc.org/rss.xml"
   17.792 D Downloading  "https://multimc.org/rss.xml"
   17.823 W QSslSocket: cannot call unresolved function SSLv23_client_method
   17.824 W QSslSocket: cannot call unresolved function SSL_library_init
   17.824 C Failed  "https://multimc.org/rss.xml"  with reason  99
   17.824 D Download failed in previous step: "https://multimc.org/rss.xml"
   17.824 D Downloading  "https://multimc.org/rss.xml"
   17.852 W QSslSocket: cannot call unresolved function SSLv23_client_method
   17.852 W QSslSocket: cannot call unresolved function SSL_library_init
   17.876 D Download succeeded: "http://files.multimc.org/notifications.json"
   17.910 D Task "NetJob(Checking for notifications)" succeeded
   17.910 C Failed  "https://multimc.org/rss.xml"  with reason  99
   17.910 D Download failed in previous step: "https://multimc.org/rss.xml"
   17.910 D Downloading  "https://multimc.org/rss.xml"
   17.919 D Download succeeded: "http://status.mojang.com/check"
   17.919 D Task "NetJob(Status JSON)" succeeded
   17.919 D Finished loading status JSON.
   17.919 D Status loading succeeded.
   17.938 W QSslSocket: cannot call unresolved function SSLv23_client_method
   17.938 W QSslSocket: cannot call unresolved function SSL_library_init
   17.938 C Failed  "https://multimc.org/rss.xml"  with reason  99
   17.938 D Download failed in previous step: "https://multimc.org/rss.xml"
   17.938 C Task "NetJob(News RSS Feed)" failed:  "Job 'News RSS Feed' failed to process:
https://multimc.org/rss.xml"
   17.938 D Failed to load news: "Failed to load news RSS feed:
Job 'News RSS Feed' failed to process:
https://multimc.org/rss.xml"
   18.108 D Download succeeded: "http://files.multimc.org/update/lin64/channels.json"
   18.108 D Task "NetJob(Update System Channel List)" succeeded
   18.109 D Successfully loaded UpdateChecker channel list.
   18.109 D Checking for updates.
   18.109 D m_repoUrl =  "http://files.multimc.org/update/lin64/stable/"
   18.109 D Task "NetJob(GoUpdate Repository Index)" started
   18.109 D Downloading  "http://files.multimc.org/update/lin64/stable/index.json"
   18.202 D Download succeeded: "http://files.multimc.org/update/lin64/stable/index.json"
   18.202 D Task "NetJob(GoUpdate Repository Index)" succeeded
   18.202 D Finished downloading repo index. Checking for new versions.
   18.202 D Processing repository version list.
   21.238 D Selected index 0 channel id "stable"
   44.435 D Task "AuthenticateTask(0x2392a40)" started
   44.474 W QSslSocket: cannot call unresolved function SSLv23_client_method
   44.474 W QSslSocket: cannot call unresolved function SSL_library_init
   44.475 C Task "AuthenticateTask(0x2392a40)" failed:  "Authentication operation failed due to a network error: Unable to init SSL Context:  (99)"
   47.370 D [Analytics] "Query string = v=1&tid=UA-87731965-2&cid=e685bd5c-785a-49c4-bd82-224a7ae2e4f1&t=screenview&ul=pl-pl&vp=694x563&sr=1920x1080&aip=1&cd=Main Window&an=MultiMC5&av=0.6.2-1137&cd1=&cd2=&cd3=64&cd4=64&cd5=Linux&cd6=4.9.0-6-amd64&cd7=bunsenlabs&cd8=9.4&cm1=512&cm2=1024&cm3=7927&qt=29744"
   47.384 W QSslSocket: cannot call unresolved function SSLv23_client_method
   47.384 W QSslSocket: cannot call unresolved function SSL_library_init
   47.393 W QSslSocket: cannot call unresolved function SSLv23_client_method
   47.393 W QSslSocket: cannot call unresolved function SSL_library_init
   47.393 W QString::arg: Argument missing: Error posting message: %s, Unable to init SSL Context: 
   47.393 D [Analytics] "Error posting message: %s"
   77.370 D Task "NetJob(Status JSON)" started
   77.371 D [Analytics] "Query string = v=1&tid=UA-87731965-2&cid=e685bd5c-785a-49c4-bd82-224a7ae2e4f1&t=screenview&ul=pl-pl&vp=694x563&sr=1920x1080&aip=1&cd=Main Window&an=MultiMC5&av=0.6.2-1137&cd1=&cd2=&cd3=64&cd4=64&cd5=Linux&cd6=4.9.0-6-amd64&cd7=bunsenlabs&cd8=9.4&cm1=512&cm2=1024&cm3=7927&qt=59746"
   77.371 D Downloading  "http://status.mojang.com/check"
   77.381 W QSslSocket: cannot call unresolved function SSLv23_client_method
   77.381 W QSslSocket: cannot call unresolved function SSL_library_init
   77.381 W QString::arg: Argument missing: Error posting message: %s, Unable to init SSL Context: 
   77.381 D [Analytics] "Error posting message: %s"
   77.514 D Download succeeded: "http://status.mojang.com/check"
   77.514 D Task "NetJob(Status JSON)" succeeded
   77.514 D Finished loading status JSON.
   77.515 D Status loading succeeded.
  107.370 D [Analytics] "Query string = v=1&tid=UA-87731965-2&cid=e685bd5c-785a-49c4-bd82-224a7ae2e4f1&t=screenview&ul=pl-pl&vp=694x563&sr=1920x1080&aip=1&cd=Main Window&an=MultiMC5&av=0.6.2-1137&cd1=&cd2=&cd3=64&cd4=64&cd5=Linux&cd6=4.9.0-6-amd64&cd7=bunsenlabs&cd8=9.4&cm1=512&cm2=1024&cm3=7927&qt=89745"
  107.379 W QSslSocket: cannot call unresolved function SSLv23_client_method
  107.380 W QSslSocket: cannot call unresolved function SSL_library_init
  107.380 W QString::arg: Argument missing: Error posting message: %s, Unable to init SSL Context: 
  107.380 D [Analytics] "Error posting message: %s"
  137.370 D Task "NetJob(Status JSON)" started
  137.371 D [Analytics] "Query string = v=1&tid=UA-87731965-2&cid=e685bd5c-785a-49c4-bd82-224a7ae2e4f1&t=screenview&ul=pl-pl&vp=694x563&sr=1920x1080&aip=1&cd=Main Window&an=MultiMC5&av=0.6.2-1137&cd1=&cd2=&cd3=64&cd4=64&cd5=Linux&cd6=4.9.0-6-amd64&cd7=bunsenlabs&cd8=9.4&cm1=512&cm2=1024&cm3=7927&qt=119746"
  137.371 D Downloading  "http://status.mojang.com/check"
  137.385 W QSslSocket: cannot call unresolved function SSLv23_client_method
  137.385 W QSslSocket: cannot call unresolved function SSL_library_init
  137.386 W QString::arg: Argument missing: Error posting message: %s, Unable to init SSL Context: 
  137.386 D [Analytics] "Error posting message: %s"
  137.510 D Download succeeded: "http://status.mojang.com/check"
  137.510 D Task "NetJob(Status JSON)" succeeded
  137.510 D Finished loading status JSON.
  137.510 D Status loading succeeded.
  167.370 D [Analytics] "Query string = v=1&tid=UA-87731965-2&cid=e685bd5c-785a-49c4-bd82-224a7ae2e4f1&t=screenview&ul=pl-pl&vp=694x563&sr=1920x1080&aip=1&cd=Main Window&an=MultiMC5&av=0.6.2-1137&cd1=&cd2=&cd3=64&cd4=64&cd5=Linux&cd6=4.9.0-6-amd64&cd7=bunsenlabs&cd8=9.4&cm1=512&cm2=1024&cm3=7927&qt=149745"
  167.379 W QSslSocket: cannot call unresolved function SSLv23_client_method
  167.380 W QSslSocket: cannot call unresolved function SSL_library_init
  167.380 W QString::arg: Argument missing: Error posting message: %s, Unable to init SSL Context: 
  167.380 D [Analytics] "Error posting message: %s"
  197.370 D Task "NetJob(Status JSON)" started
  197.371 D [Analytics] "Query string = v=1&tid=UA-87731965-2&cid=e685bd5c-785a-49c4-bd82-224a7ae2e4f1&t=screenview&ul=pl-pl&vp=694x563&sr=1920x1080&aip=1&cd=Main Window&an=MultiMC5&av=0.6.2-1137&cd1=&cd2=&cd3=64&cd4=64&cd5=Linux&cd6=4.9.0-6-amd64&cd7=bunsenlabs&cd8=9.4&cm1=512&cm2=1024&cm3=7927&qt=179746"
  197.371 D Downloading  "http://status.mojang.com/check"
  197.380 W QSslSocket: cannot call unresolved function SSLv23_client_method
  197.381 W QSslSocket: cannot call unresolved function SSL_library_init
  197.381 W QString::arg: Argument missing: Error posting message: %s, Unable to init SSL Context: 
  197.381 D [Analytics] "Error posting message: %s"
  197.506 D Download succeeded: "http://status.mojang.com/check"
  197.506 D Task "NetJob(Status JSON)" succeeded
  197.506 D Finished loading status JSON.
  197.506 D Status loading succeeded.
  227.370 D [Analytics] "Query string = v=1&tid=UA-87731965-2&cid=e685bd5c-785a-49c4-bd82-224a7ae2e4f1&t=screenview&ul=pl-pl&vp=694x563&sr=1920x1080&aip=1&cd=Main Window&an=MultiMC5&av=0.6.2-1137&cd1=&cd2=&cd3=64&cd4=64&cd5=Linux&cd6=4.9.0-6-amd64&cd7=bunsenlabs&cd8=9.4&cm1=512&cm2=1024&cm3=7927&qt=209745"
  227.384 W QSslSocket: cannot call unresolved function SSLv23_client_method
  227.384 W QSslSocket: cannot call unresolved function SSL_library_init
  227.384 W QString::arg: Argument missing: Error posting message: %s, Unable to init SSL Context: 
  227.385 D [Analytics] "Error posting message: %s"
  251.752 D Paged dialog close requested
  251.753 D Analytics enabled by user.
  251.753 D Paged dialog close approved
  251.753 D Paged dialog geometry saved
`

**Comment by Heufneutje** [comment]
...Just attach the file, don't copy it into a comment. Can you even read what you just posted?

**Comment by peterix** [comment]
How do you even end up with docx as a linux user...

**Comment by peterix** [comment]
Please do it again, and this time, only attach the file. Do not put it in MS Word

**Comment by peterix** [comment]
Sorry for the delay, I only get notified about changes if you add new comments :)

Try to install `openssl1.0` and see if that helps.

**Comment by Tavarnarmo** [comment]
No problem, checked and I have already installed openssl 1.1.0.

**Comment by peterix** [comment]
No, I mean `openssl1.0` - that `1.0` is not in the version field, it's part of the package name.

**Comment by peterix** [comment]
See: https://tracker.debian.org/pkg/openssl1.0

**Comment by Tavarnarmo** [comment]
Installed but still no luck, the same error as before.

**Comment by Janrupf** [comment]
See #2256, he installed `openssl1.0-dev`, that fixed it

**Comment by Tavarnarmo** [comment]
That helped for logging, thank you very much :) I have now another error, this time with nvidia drivers but will try to do something with this tomorrow.

**Comment by Janrupf** [comment]
A little note:
Today I worked on MultiMC and got this error. But the downloaded version already worked. So, looks like that means if there are some dev dependencies, you need the dev version which makes sense. But why that sometimes happens when downloading precompiled multimc... Maybe the develop channel?

**Comment by peterix** [comment]
Yes. MultiMC needs to stop bundling Qt.
