### ISSUE TITLE
Can only run a single instance of Minecraft once per reboot

### ISSUE THREAD

**Issue by gradeonmagus** [MultiMC/MultiMC5#2266]
System Information
-----------------------------
MultiMC version: 0.62 stable

Operating System: Windows 10

Summary of the issue or suggestion: 
----------------------------------------------
I can open a single instance of Minecraft (modded or unmodded) once, then every time I try to open it again it crashes with Error Code -1 until I reboot my system. 

What should happen:
------------------------------
I can open an instance whenever I want. 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Start an instance once. 

2. Close it out. 

3. Attempt to reopen it. 

Suspected cause:
---------------------------
Your guess is as good as mine. I've disabled mods such as BetterFPS, Fastcraft, Optifine, or simply attempted to run mod packs without them only to get the same result. I've also made sure that I only use Java 8 64x, not 7 or 9. 

Logs/Screenshots:
----------------------------
https://paste.ee/p/8lkqA

Additional Info:
---------------------------

**Comment by Janrupf** [comment]
Can you upload the log? (There is a button for this in the console window).

**Comment by gradeonmagus** [comment]
Here ya go, just tried to run it a second ago. 

https://paste.ee/p/d1cvM

**Comment by gradeonmagus** [comment]
[DxDiag.txt](https://github.com/MultiMC/MultiMC5/files/1976227/DxDiag.txt)

**Comment by peterix** [comment]
That's the current version of the driver.

Reboot -- does it help?

Reinstall the driver from http://www.nvidia.com/download/driverResults.aspx/133648/en-us -- does it help?

**Comment by gradeonmagus** [comment]
I can reboot and it'll work exactly once, as I said above. I'll try reinstalling the driver.

**Comment by QuImUfu** [comment]
@peterix he already said he can start minecraft once per boot.

**Comment by peterix** [comment]
Right... 

Looked up some driver news and got this:
https://www.neowin.net/news/nvidias-39731-geforce-drivers-are-causing-a-pc-reset-loop-for-some-users
https://www.neowin.net/news/nvidia-says-new-drivers-coming-very-soon-to-replace-buggy-39731-release

So they made some major change to the drivers and various things broke. You may want to try the hotfix driver, or rolling back to a known good version.

**Comment by gradeonmagus** [comment]
...Yep, that did it. I didn't even think to check the driver since MC's the only thing I've booted up in the past couple of weeks and there wasn't any noticeable issues with anything else on my computer. 

Thanks!
