### ISSUE TITLE
Minecraft MultiMC Process exited with code 255 for every tried modpack! (linux Comp.)

### ISSUE THREAD

**Issue by Rome2002** [MultiMC/MultiMC5#2267]
I have been trying to play some modpacks on the MultiMC launcher, and I have been using the curseforge website to download the modpacks and make them into an instance. ( I have to do it this way because I have Linux Mint on my computer and there currently is no launcher for twitch on a linux computer.) I create the instance, then I launch the modpack and it gets to 7/7 on the minecraft laoding screen and then just crashes and says Process exited with code 255. My computer starts to heat up every time I try to load from MultiMC I have the current Java on it. Im not too good with computers so any help would be appreciated. Like I said before it gets all the way to 7/7 and then it freezes loading the recipes or modeloader and then crashes showing the crash report.
>

**Comment by QuImUfu** [comment]
upload and link the minecraft log by pressing the upload button in the launcher and pasting the link to your response.
