### ISSUE TITLE
Ubuntu 18.04 default-jre is openjdk-11-jre

### ISSUE THREAD

**Issue by covers1624** [MultiMC/MultiMC5#2268]
System Information
-----------------------------
MultiMC version: Linux install wrapper 1.1-2

Operating System: Ubuntu 18.04

Summary of the issue or suggestion:
----------------------------------------------
Hello!
Installing multimc on Ubuntu 18.04 results in multimc installing default-jre, As of Ubuntu 18.04 `openjdk-11` is now the default.
As a result the game refuses to start because as you know Forge does not run on anything above java 8
```
covers1624@DASH:~/Downloads$ sudo apt install ./multimc_1.1-2.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'multimc' instead of './multimc_1.1-2.deb'
The following additional packages will be installed:
  default-jre default-jre-headless openjdk-11-jre openjdk-11-jre-headless
Suggested packages:
  default-java-plugin fonts-ipafont-gothic fonts-ipafont-mincho fonts-wqy-microhei | fonts-wqy-zenhei
The following NEW packages will be installed:
  default-jre default-jre-headless multimc openjdk-11-jre openjdk-11-jre-headless
0 to upgrade, 5 to newly install, 0 to remove and 5 not to upgrade.
Need to get 0 B/39.6 MB of archives.
After this operation, 184 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
```
Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Fire up Ubuntu 18.04 & install.

2. Create instance with forge installed.

3. Crash.

Suspected cause:
---------------------------
Forge due to many changes in the jre does not run on anything after Java 8, i suggest changing the dependency to `openjdk-8-jre`.

**Comment by covers1624** [comment]
https://github.com/MultiMC/MultiMC5/issues/2267 is likely related to this.

**Comment by Janrupf** [comment]
Thats right, but this is more an issue with forge than multimc itself. Some poeple prefer using other PPA's for java. So just selecting java 8 might not be a good solution.

**Comment by peterix** [comment]
It would honestly be better to remove the dependency altogether, because MultiMC itself does not directly depend on Java (nor do I ever want it to).

It is the instances being launched that depend on Java, and it's often **different ranges of Java versions**.

So, let's drop that dependency.

**Comment by jikuja** [comment]
One solution is to use recommends instead of dropping it. Or some other not so hard dependency.

**Comment by peterix** [comment]
That is something I want to do in the future, but java is not a valid package from the point of view of the MultiMC dependency resolver yet.

**Comment by peterix** [comment]
I've updated the package on the website. Please check, but I assume it's fine now :)

**Comment by UnMe0w** [comment]
Just `sudo apt remove openjdk-11-jre`
