### ISSUE TITLE
Crashes on startup with QSslSocket errors

### ISSUE THREAD

**Issue by werl** [MultiMC/MultiMC5#2271]
System Information
-----------------------------
MultiMC version: 0.6.2

Operating System: Linux (Fedora 28)

Summary of the issue or suggestion:
----------------------------------------------
Crashing on startup with a bunch of 'QSslSocket: cannot resolve' and 'QSslSocket: cannot call unresolved function' errors.

What should happen:
------------------------------
Launch without issue

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. update to latest Fedora

2. install MultiMC

3. run MultiMC

Suspected cause:
---------------------------
seems to be described here https://github.com/rstudio/shiny/issues/1796#issuecomment-315843920

Logs/Screenshots:
----------------------------
https://paste.ee/p/XFZZw

Additional Info:
---------------------------
It seemed to work fine only a couple days ago

**Comment by perlguy** [comment]
Looks like the Fedora openssl 1.0 compatability library (compat-openssl10) updated from 'm' to 'o'.   If  you update the symlinks in the MultiMC/bin directory it should start working again (it did for me).

before:
lrwxrwxrwx. 1 1000 1000       16 Feb 16 14:47 libssl.so -> libssl.so.1.0.2m
lrwxrwxrwx. 1 1000 1000       27 Feb 16 14:46 libssl.so.1.0.2m -> /usr/lib64/libssl.so.1.0.2m

after:
lrwxrwxrwx. 1 1000 1000       16 May 15 12:14 libssl.so -> libssl.so.1.0.2o
lrwxrwxrwx. 1 1000 1000       27 May 15 12:14 libssl.so.1.0.2o -> /usr/lib64/libssl.so.1.0.2o

**Comment by werl** [comment]
I don't see any symlinks in the MultiMC/bin folder. and nothing with ssl in the name either

**Comment by perlguy** [comment]
I must have added those manually sometime in the past for a different issue... I just removed the symlink and it still works.  I *was* getting the same errors you're seeing though, before updating/removing the links, so it sounds like your problem is still MMC not being able to find the 1.0 version of the OpenSSL libs,  Do you have compat-openssl10 installed?  (apologies in advance if you've already checked that)

**Comment by werl** [comment]
Fixed, with a temporary workaround. I had to remove 'openssl-devel' then install 'compat-openssl-10-devel'. The only issue is that I'm not sure how long I can go with this without running into bigger issues

**Comment by waerloga** [comment]
I was able to make a temporary workaround by linking
`bin/libssl.so -> /usr/lib64/libssl.so.1.0.2o`

**Comment by AR-Calder** [comment]
I ran into this issue on Fedora 29. I also managed to work around it using the linking method:
```
cd MultiMC/bin
ln -s /usr/lib64/libcrypto.so.10 libcrypto.so  
ln -s /usr/lib64/libgcrypt.so.20 libgcrypt.so  
ln -s /usr/lib64/libssl.so.10 libssl.so  
```

**Comment by jturnism** [comment]
I'm also having this issue with MultiMC on Fedora 30. The workaround I found is to 

1. Extract MultiMC.
2. Delete everything inside but the bin folder.
3. Pull out all the files from bin into the parent folder.
4. Delete empty bin folder.
5. Delete all lib files without MultiMC in name.
6. chmod +x MultiMC

Then it's good to launch and works fine. Which is weird considering how much stuff I delete.
If anyone is still interested in this issue I have the log file from before doing any of my workaround here : https://pastebin.com/a4rDC1eQ

**Comment by peterix** [comment]
Resolving as fixed, will be in stable release later today.
