### ISSUE TITLE
SevTech can't launch

### ISSUE THREAD

**Issue by martinhelge** [MultiMC/MultiMC5#2272]
System Information
-----------------------------
MultiMC version: 0.6.2-1163

Operating System: OSX 10.13.4

Summary of the issue or suggestion: SevTech can't launch 
----------------------------------------------

What should happen: SevTech should launch.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Start SevTech with launcher

2.

3.

Suspected cause: Some Java-error
---------------------------

Logs/Screenshots:
----------------------------
[//]: https://paste.ee/p/yplo5

MultiMC version: 0.6.2-1163

Minecraft folder is:
/Applications/MultiMC.app/Contents/MacOS/instances/SevTech+Ages-3.0.7/minecraft

Java path is:
/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/bin/java

Java is version 10.0.1, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /Applications/MultiMC.app/Contents/MacOS/instances/SevTech+Ages-3.0.7/natives

Libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/realms/1.10.19/realms-1.10.19.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/minecraftforge/forge/1.12.2-14.23.2.2651/forge-1.12.2-14.23.2.2651-universal.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/jline/jline/2.13/jline-2.13.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-osx.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar

Mods:
  [1.12]MoVillages-1.5.4
  A Block of Charcoal-1.1
  AbyssalCraft Integration-1.12.2-1.6.2
  AbyssalCraft-1.12.2-1.9.4.9
  ActuallyAdditions-1.12.2-r134
  ActuallyBaubles-1.12-1.1
  advancedmortars-1.12.2-1.6.20
  Animalium-0.3.7
  antiqueatlas-1.12.2-4.4.8
  AppleCore-mc1.12.2-3.1.1
  AppleSkin-mc1.12-1.0.9
  appliedenergistics2-rv5-stable-11
  armoreablemobs-1.12-1.1.6-4
  astikoor_horse-carts-1.1.0a
  astralsorcery-1.12.2-1.8.10
  AutoRegLib-1.3-17
  base-1.12.2-3.7.1
  Baubles-1.12-1.5.2
  bdlib-1.14.3.12-mc1.12.2
  BedrockBGone-1.12.2-5.0-b7
  Better With Addons-0.40hotfix
  BetterAdvancements-1.12.2-0.0.7.42
  BetterBuildersWands-1.12-0.11.1.245+69d0d70
  BetterFoliage-MC1.12-2.1.10
  BetterFps-1.4.8
  BetterWithMods-1.12-2.1.15
  BiblioCraft[v2.4.3][MC1.12.0]
  BloodMagic-1.12.2-2.2.12-97
  BNBGamingCore-1.12.2-0.7.2
  BNBGamingLib-1.12-2.11.1
  bonsaitrees-1.0.4-b71
  Bookshelf-1.12.2-2.3.544
  buildcraft-builders-7.99.16
  buildcraft-core-7.99.16
  buildcraft-factory-7.99.16
  buildcraft-robotics-7.99.16
  buildcraft-silicon-7.99.16
  buildcraft-transport-7.99.16
  Caliper-1.12.2-1.1.35
  car-1.2.11
  CarryOn MC1.12.2 v1.8
  CD4017BE_lib-1.12.2-6.2.3
  Ceramics-1.12-1.3.4
  Chameleon-1.12-4.1.3
  Chargers-1.12.2-1.0.0.1
  ChickenASM-1.12-1.0.2.7
  Chisel-MC1.12.2-0.2.0.31
  chiselsandbits-14.16
  ClientTweaks_1.12.2-3.1.6
  Clumps-3.0.0
  CodeChickenLib-1.12.2-3.1.8.341-universal
  ColouredTooltips-1.12.2-1.0.4
  CommonCapabilities-1.12-1.4.0
  compactmachines3-1.12.2-3.0.11-b207
  ContentTweaker-1.12.2-4.5.0
  Controlling-3.0.6
  CookingForBlockheads_1.12.2-6.3.26
  CraftStudio-1.0.0.93-mc1.12-alpha
  CraftTweaker2-1.12-4.1.8
  CTM-MC1.12-0.2.3.12
  cucumber-1.12-1.1.0
  CustomMainMenu-MC1.12.2-2.0.8
  Cyclic-1.12.2-1.14.9
  CyclopsCore-1.12.2-0.11.5
  DarkUtils-1.12.2-1.8.208
  DeathCompass-0.0.3
  DefaultOptions_1.12.2-9.2.7
  despawningspawners-1.1
  DimensionalControl-1.12.2-2.10.2
  DimensionStages-1.12.2-1.0.18
  Dung Pipe-1.1
  ElevatorMod-1.12.2-1.3.6
  EmberRootZoo-1.12-1.3.7
  EnchantmentDescriptions-1.12.2-1.1.8
  EnderStorage-1.12.2-2.4.2.126-universal
  enderutilities-1.12.2-0.7.8
  environmentaltech-1.12.2-2.0.9c
  extendedcrafting-1.12-1.3.1
  ExtraPlanets-1.12.2-0.3.3
  FancyBlockParticles-1.12.x-2.4.0
  FarmingForBlockheads_1.12.2-3.1.12
  Farseek-1.12-2.2.5
  FastWorkbench-1.12.2-1.3.1
  FatCat-0.0.5
  Ferdinand's Flowers-1.10.1b-1.12
  findme-1.12.2-1.0.1-5
  foamfix-0.9.9.1-1.12.2-anarchy
  Forgelin-1.6.0
  ForgeMultipart-1.12.2-2.4.1.57-universal
  Galacticraft-Planets-1.12.2-4.0.1.176
  GalacticraftCore-1.12.2-4.0.1.176
  GalacticraftTweaker-1.12.2-1.0.1
  GameStages-1.12.2-1.0.85
  generators-0.9.20.12-mc1.12.2
  Geolosys-1.12.2-1.8.10c
  GobbleCore-1.12-0.1.6.35
  Guide-API-1.12-2.1.5-60
  Harvest-1.12-1.2.6-18
  HorsePower-1.12.2-2.6.1.62
  HuntingDimension-1.12.2-1.0.24
  Hwyla-1.8.25-B40_1.12
  immcraft-1.12-1.4.1
  ImmersiveEngineering-0.12-82
  immersivepetroleum-1.12.2-1.1.9
  immersivetech-1.12-1.3.8
  ImprovedBackpacks-1.12.2-1.2.0.2
  incontrol-1.12-3.8.0
  InductiveLogistics-1.12.2-1.2.1
  industrialforegoing-1.12.2-1.9.0-163
  InfoAccessories-1.12.2-1.0.6
  IntegratedDynamics-1.12.2-0.11.11
  InventoryTweaks-1.64-dev
  IronBackpacks-1.12.2-3.0.7-10
  ironchest-1.12.2-7.0.40.824
  ironjetpacks-1.12-1.0.4
  ItemStages-1.12.2-1.0.33
  IvToolkit-1.3.3-1.12
  jei_1.12.2-4.9.1.175
  journeymap-1.12.2-5.5.2
  JourneyMapStages-1.12.2-1.0.3
  Just A Raft Mod-1.1.2
  JustAFewFish-1.7_for_1.12
  JustEnoughPetroleum-0.1
  justthetips-1.12-1.0.1.1
  KleeSlabs_1.12.2-5.4.9
  LootTableTweaker-1.12.2-1.1.14
  MagmaMonsters-0.3.0
  Mantle-1.12-1.3.2.24
  mcjtylib-1.12-2.6.7
  Mekanism-1.12.2-9.4.10.345
  Mercurius-1.12.2
  MicdoodleCore-1.12.2-4.0.1.176
  MJRLegendsLib-1.12.2-1.1.3
  mobends-0.24_for_MC-1.12
  MobGrindingUtils-0.3.6
  MobStages-1.12.2-1.0.7
  modtweaker-4.0.10
  modular-routers-1.12.2-3.1.4
  modularmachinery-1.9.4
  Morpheus-1.12-3.3.2
  MouseTweaks-2.8-mc1.12.1
  mpbasic-1.12.2-1.4.8
  MPUtils-1.12.2-1.5.6
  MTLib-3.0.4
  multiblockstages-1.0.1
  MundaneRedstone-1.1.3
  mystagradcompat-1.2
  mysticalagradditions-1.12-1.2.8
  mysticalagriculture-1.12-1.6.9
  natura-1.12.2-4.3.2.49
  NaturesCompass-1.12.2-1.5.1
  Neat 1.4-15
  NetherEx-1.12-2.1.14.15
  noRecipeBook_v1.1.0formc1.12.2
  NotEnoughItems-1.12.2-2.4.1.233-universal
  NoWorldgen5You-1.12.2-1.0.6
  Nutrition-1.12.2-3.0.0
  OceanFloor-1.12-1.0.1
  oeintegration-2.3.3
  OreExcavation-1.4.118
  OreStages-1.12.2-1.0.26
  Overloaded-1.12.2-0.0.51
  pickletweaks-1.12-2.0.16
  Placebo-1.12.2-1.3.4
  PlayerAPI-1.12.1-1.0
  playerskin-1.12.2-1.0.5
  pneumaticcraft-repressurized-1.12.2-0.6.4-186
  PowerAdapters-1.12.2-1.0.9
  Prestige-1.12.2-1.0.15
  PrimalChests-1.0.3
  PrimalCore-1.12.2-0.6.53
  PrimalTech-0.3.2
  ProgressionTweaks-1.12.2-0.3.40
  prospectors-1.0.1
  QuantumStorage-1.12-4.5.0
  Quark-r1.4-123
  QuickLeafDecay-MC1.12.1-1.2.4
  rangedpumps-0.5
  RealisticItemDrops-1.2.12
  ReAuth-3.5.2
  RebornCore-1.12.2-3.8.1.271-universal
  RebornStorage-1.12.2-3.0.6.43
  RecipeStages-1.0.8
  RecurrentComplex-1.4.7
  RedstoneFlux-1.12-2.0.1.2-universal
  refinedstorage-1.5.33
  refinedstorageaddons-0.3
  ResourceLoader-MC1.12.1-1.5.3
  rftools-1.12-7.33
  rftoolsctrl-1.12-1.8.1
  roadrunner-1.0.1
  rustic-1.0.4
  Scannable-MC1.12-1.6.2.13
  SevTweaksNPC-0.0.3
  simpleautorun-1.12.2-1.2.0
  simplegenerators-1.12.2-2.0.9a
  SimpleStorageNetwork-1.12.2-1.2.4
  SimplyArrows-1.12.2-1.0.4
  SmoothFont-1.12.2-1.15
  SpartanShields-1.12.2-1.4.1
  spatialservermod-1.3
  StevesCarts-1.12.2-2.4.18.92
  stg-1.12.2-1.2.3
  StorageDrawers-1.12.2-5.3.6
  Streams-1.12-0.4.3
  StuffASockInIt-1.12.2-1.1.14
  supersoundmuffler-1.12.1-1.0.2.9
  TallGates-1.12.2-1.0.0.1
  TConstruct-1.12.2-2.10.0.75
  tesla-core-lib-1.12.2-1.0.14
  The Beneath-1.12.2-1.4.1
  TheBetweenlands-3.3.8-universal
  ThirstyBottles-1.12.2-1.1.4
  TinkersComplement-1.12.2-0.2.3b
  TinkerStages-1.12.2-1.0.14
  TinkerToolLeveling-1.12-1.0.4
  TipTheScales-1.12.2-1.0.1
  Toast Control-1.12.2-1.5.0
  togetherforever-1.12.2-1.0.7-13
  TombManyGraves-1.12-4.0.3
  Totemic-1.12.2-0.11.1
  tothebatpoles-1.12-1.1.0.0
  Translocators-1.12.2-2.5.0.70-universal
  Traverse-1.12.2-1.5.3-58
  Triumph-1.12.2-1.12.0
  trumpetskeleton-1.12-1.0.2.1
  tumbleweed-1.11-0.4.5
  twilightforest-1.12.2-3.6.345-universal
  Uppers-0.0.6
  valkyrielib-1.12.2-2.0.9b
  ViesCraft-1.12.2-5.6.1
  VillagerTrades-1.12-0.6.4
  Waddles-1.12.2-0.6.0
  WailaStages-1.12.2-1.0.22
  WanionLib-1.12.2-1.5
  WaterControlExtreme-1.0.2
  WaterStrainer-1.12-3.2.0
  Wawla-1.12.2-2.5.256
  weirdinggadget-1.12.2-2.0.5-universal
  WildCrops-1.12-1.0.1
  Wither Skeleton Tweaks-1.12.2-2.6.0
  Wopper-1.12-r5
  xnet-1.12-1.6.9
  YNot-0.2.2
  yoyos_1.12.2-1.2.2.20

Params:
  --username  --version MultiMC5 --gameDir /Applications/MultiMC.app/Contents/MacOS/instances/SevTech+Ages-3.0.7/minecraft --assetsDir /Applications/MultiMC.app/Contents/MacOS/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: SevTech+Ages-3.0.7", -Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 62205

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code 255.
MultiMC: Log upload triggered at: 16 May 2018 09:49:09 +0200

Additional Info: None
---------------------------

**Comment by tehbasshunter** [comment]
You can't use any java version greater than 8. Switch and that should fix it.

**Comment by martinhelge** [comment]
Ok. Do you know how I should go about that? I've been trying to google it, but haven't been successful. Do I need to delete my current version of Java, and will it conflict with the normal Minecraft Java-launcher?

**Comment by tehbasshunter** [comment]
You don't need to. Just use this to grab the installer https://java.com/en/download/manual.jsp

**Comment by martinhelge** [comment]
Ah, fantastic. Thank you very much!
