### ISSUE TITLE
Could not load Java.lang

### ISSUE THREAD

**Issue by drmason29** [MultiMC/MultiMC5#2273]
System Information
-----------------------------
MultiMC version: 0.6.2-1222

Operating System: Windows 7 Home Premium

Summary of the issue or suggestion:
----------------------------------------------

So I updated either Minecraft to 1.12.7 or updated the modpack I was using at the time, Sevtech. Note this was originally on the twitch launcher. It gave me a corrupted Minecraft error so I tried most of the repair options. None worked. I then uninstalled Minecraft completely, as well as Java, reinstalling both. After which I decided to use MultiMC instead, as I have heard much better things about it then the Twitch launcher. However it also wouldn't work. I think I tried the Twitch launcher and it worked once or twice but was still unreliable. I reinstalled pretty much everything and am now at the current point/issue.
If I open vanilla Minecraft either using MultiMC or the old Jar launcher, there is no problem. If I open it using the new launcher or if I have Forge installed on MultiMC, it doesn't work. Older versions such as 1.7 function both in vanilla and in Forge.

What should happen:
------------------------------
Minecraft should load.

Suspected cause:
---------------------------
Either Forge or Java errors.

Logs/Screenshots:
----------------------------
MultiMC version: 0.6.2-1222

Minecraft folder is:
D:/Programs/MultiMC/instances/Forge/.minecraft

Java path is:
D:/Programs/Java/bin/java.exe

Java is version 1.8.0_172, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  D:/Programs/MultiMC/instances/Forge/natives

Libraries:
  D:/Programs/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  D:/Programs/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  D:/Programs/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  D:/Programs/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  D:/Programs/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  D:/Programs/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  D:/Programs/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  D:/Programs/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  D:/Programs/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  D:/Programs/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  D:/Programs/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  D:/Programs/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  D:/Programs/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  D:/Programs/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  D:/Programs/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  D:/Programs/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  D:/Programs/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  D:/Programs/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  D:/Programs/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  D:/Programs/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  D:/Programs/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  D:/Programs/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  D:/Programs/MultiMC/libraries/com/mojang/realms/1.10.19/realms-1.10.19.jar
  D:/Programs/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  D:/Programs/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  D:/Programs/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  D:/Programs/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  D:/Programs/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  D:/Programs/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  D:/Programs/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  D:/Programs/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  D:/Programs/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  D:/Programs/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  D:/Programs/MultiMC/libraries/com/mumfrey/liteloader/1.12.2-SNAPSHOT/liteloader-1.12.2-SNAPSHOT.jar
  D:/Programs/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.3.2655/forge-1.12.2-14.23.3.2655-universal.jar
  D:/Programs/MultiMC/libraries/jline/jline/2.13/jline-2.13.jar
  D:/Programs/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  D:/Programs/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  D:/Programs/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  D:/Programs/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  D:/Programs/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  D:/Programs/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  D:/Programs/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  D:/Programs/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  D:/Programs/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  D:/Programs/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  D:/Programs/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  D:/Programs/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  D:/Programs/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  D:/Programs/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  D:/Programs/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  D:/Programs/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  D:/Programs/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  D:/Programs/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:

Params:
  --username  --version MultiMC5 --gameDir D:/Programs/MultiMC/instances/Forge/.minecraft --assetsDir D:/Programs/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass com.mumfrey.liteloader.launch.LiteLoaderTweaker --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx6024m, -Duser.language=en]

Minecraft process ID: 4528

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi in java.library.path, C:\Users\Dillon\AppData\Local\Temp\jansi-64-3691643668461019086.dll: Access is denied]
	at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
	at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
	at org.fusesource.jansi.internal.Kernel32.<clinit>(Kernel32.java:37)
	at org.fusesource.jansi.WindowsAnsiOutputStream.<clinit>(WindowsAnsiOutputStream.java:52)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.logging.log4j.core.appender.ConsoleAppender.getOutputStream(ConsoleAppender.java:263)
	at org.apache.logging.log4j.core.appender.ConsoleAppender.getDefaultManager(ConsoleAppender.java:226)
	at org.apache.logging.log4j.core.appender.ConsoleAppender.createDefaultAppenderForLayout(ConsoleAppender.java:172)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.setToDefault(AbstractConfiguration.java:581)
	at org.apache.logging.log4j.core.config.DefaultConfiguration.<init>(DefaultConfiguration.java:47)
	at org.apache.logging.log4j.core.LoggerContext.<init>(LoggerContext.java:86)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:171)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:145)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:74)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:227)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:618)
	at net.minecraft.launchwrapper.LogWrapper.configureLogging(LogWrapper.java:14)
	at net.minecraft.launchwrapper.LogWrapper.log(LogWrapper.java:28)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:94)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1.
MultiMC: Log upload triggered at: 16 May 2018 10:11:05 +0200

**Comment by werl** [comment]
To start with some simple fixes, it seems that you don't have proper permissions to jansi as seen in the following line `C:\Users\Dillon\AppData\Local\Temp\jansi-64-3691643668461019086.dll: Access is denied]`

**Comment by drmason29** [comment]
I noticed that line, but when I went to the local temp folder that file wasnt there. From my very limited coding experience and some Google-Fu, I understand it is a java library but I don't understand as to how or why it is missing. There is another jansi file in there but it has the wrong numbers. I changed the permissions on it anyways, no change.

**Comment by peterix** [comment]
If I had to guess -- and I see no other alternative -- I'd say you have problems with some antivirus or similar software messing up how the OS works.

Turn it off temporarily, see what happens.

**Comment by drmason29** [comment]
I don't have any anti-virus software installed other than Windows security essentials. Disabled the real time protection from that but still no change. What other sort of OS-changing programs would have that sort of effect?

**Comment by peterix** [comment]
Well, no idea. Sorry. Closing because it's been half a year.
