### ISSUE TITLE
Minecraft crash

### ISSUE THREAD

**Issue by Dolay2002** [MultiMC/MultiMC5#2274]
My minecraft in 1.12.2 vanilla crash, I do not know why. It's the crash report, pease help me.
[crash-2018-05-16_14.33.27-client.txt](https://github.com/MultiMC/MultiMC5/files/2009136/crash-2018-05-16_14.33.27-client.txt)

And Log of minecraft :
[Log Minecraft.txt](https://github.com/MultiMC/MultiMC5/files/2009150/Log.Minecraft.txt)

**Comment by peterix** [comment]
This looks like a graphics driver issue.

Please attach the full dxdiag report so we can figure out what is wrong. You can do it like this:

* Press the `[Windows]+[R]` keys on your keyboard to bring up the Run command.
* In the `Run` command box, type in `dxdiag` and press `<Enter>`. The DirectX Diagnostic Tool pop-up window should appear.
* Click on `Save all Information.`
* Save the information to your Desktop, keep the file name as is.
* Attach the file here.

Here is an example of what the DirectX Diagnostic Tool will look like:

![dxdiag example](https://user-images.githubusercontent.com/203326/34328124-4489aa8e-e8d6-11e7-9984-0f5e8561564b.png)

**Comment by spannerman79** [comment]
```
org.lwjgl.LWJGLException: Pixel format not accelerated
Operating System: Windows 10 (amd64) version 10.0
```
Use Java8u51 or upgrade your graphics hardware.

Common problem with older Intel gfx hardware on Windows 10.
http://hopper.minecraft.net/help/pixel-format-not-accelerated/

**Comment by peterix** [comment]
It's not clear what GPU is used yet... If it's something like Intel HD 2000 or 3000, then sure, using olde Java will help.

I'd like to see the DxDiag report first though.

**Comment by spannerman79** [comment]
Considering 
```
Minecraft folder is:
C:/Users/packard bell/AppData/Roaming/MultiMC/instances/1.12.2/.minecraft
```
*packard bell* being the "user" I'd say it is Intel HD 2/3000

Might even have been a Vista -> Win7 -> (free) Win10 upgrade path as Packard Bell's system restore/default install user was always the company name with the older XP/Vista out of the box experience setups.

**Comment by peterix** [comment]
Interesting... that's something I simpy wouldn't see myself. Still, let's see the report :)
