### ISSUE TITLE
Cannot log in to add account, Server Replied : Forbidden

### ISSUE THREAD

**Issue by Amextris** [MultiMC/MultiMC5#2275]
System Information
-----------------------------
MultiMC version:0.6.2-1222

Operating System:Win 10

Summary of the issue or suggestion:
----------------------------------------------
I can't log in to the minecraft server to add my account to MultiMC, every time I try:An unknown error occurred when trying to communicate with the authentication server: Error transferring https://authserver.mojang.com/authenticate - server replied: Forbidden.

What should happen:I should be able to log in and add a minecraft account.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Launch MultiMC

2.Click "Add" to add minecraft account."

3.Enter login information,(correctly, I made sure), and click OK.

Suspected cause:I am at school, that blocks game related things, but I am using a vpn that bypasses that and allows me to go anywhere unrestricted. (ultrasurf VPN)
---------------------------

Logs/Screenshots:No logs.
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by QuImUfu** [comment]
@Janrupf he said he uses the ultrasurf VPN with is no VPN. it is some mix between a proxy, an vpn and a browser addon. eg. some kind of VPN software that, by design, works only with browsers and requires no root access because of that.
