### ISSUE TITLE
Exit Code 1 can't figure out

### ISSUE THREAD

**Issue by DirtyDango** [MultiMC/MultiMC5#2276]
System Information
-----------------------------
MultiMC version: 0.6.2

Operating System: Windows 10 Pro

Summary of the issue or suggestion: I am trying to launch a new mod pack and I keep getting an exit code 1.
----------------------------------------------

Logs/Screenshots:
----------------------------
MultiMC version: 0.6.2-1222

Minecraft folder is:
C:/Users/ester/OneDrive/Desktop/MultiMC/instances/FTBContinuum-1.0.1-1.12.2/minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_171, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/ester/OneDrive/Desktop/MultiMC/instances/FTBContinuum-1.0.1-1.12.2/natives

Libraries:
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/com/mojang/realms/1.10.19/realms-1.10.19.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.3.2689/forge-1.12.2-14.23.3.2689-universal.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/jline/jline/2.13/jline-2.13.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/ester/OneDrive/Desktop/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  ActuallyAdditions-1.12.2-r135
  AdvancedRocketry-1.12.2-1.4.0-80
  ae2stuff-0.7.0.4-mc1.12.2
  AppleCore-mc1.12.2-3.1.1
  AppleSkin-mc1.12-1.0.9
  appliedenergistics2-rv5-stable-11
  AutoRegLib-1.3-17
  badwithernocookiereloaded-1.12.2-2.12
  base-1.12.2-3.7.2
  Baubles-1.12-1.5.2
  bdlib-1.14.3.12-mc1.12.2
  bedpatch-2.2-1.12.2
  BetterAdvancements-1.12.2-0.0.5.17
  BetterBuildersWands-1.12-0.11.1.245+69d0d70
  BetterQuesting-3.5.256
  BetterQuestingTriggerer-1.0
  BiblioCraft[v2.4.3][MC1.12.0]
  binnie-mods-1.12.2-2.5.0.165
  blockcraftery-0.1.3
  Bookshelf-1.12.2-2.3.544
  careerbees-0.4.0
  Chameleon-1.12-4.1.3
  Charset-Lib-0.5.0.246
  ChestTransporter-1.12.2-2.8.8
  ChickenASM-1.12-1.0.2.7
  Chisel-MC1.12.2-0.2.0.31
  chiselsandbits-14.16
  Clumps-3.0.0
  CodeChickenLib-1.12.2-3.1.8.341-universal
  CoFHCore-1.12.2-4.4.1.12-universal
  CoFHWorld-1.12.2-1.1.1.12-universal
  Controlling-3.0.6
  CookingForBlockheads_1.12.2-6.3.26
  CraftTweaker2-1.12-4.1.8
  CTM-MC1.12-0.2.3.12
  CustomMainMenu-MC1.12.2-2.0.8
  DarkUtils-1.12.2-1.8.207
  DefaultOptions_1.12.2-9.2.7
  diethopper-1.1
  efab-0.0.36
  elulib-0.1.12
  EnderStorage-1.12.2-2.4.2.126-universal
  engineersdoors-0.7.2
  EngineersWorkshopReborn-1.12.2-1.0.6.31
  environmentaltech-1.12.2-2.0.10a
  Exchangers-1.12.2-2.7.2
  ExtraCells-1.12.2-2.5.13a56
  extrautils2-1.12-1.7.6
  ExtremeReactors-1.12.2-0.4.5.48
  FastWorkbench-1.12.2-1.3.2
  flatcoloredblocks-mc1.12-6.6
  fluxnetworks-1.12.2-3.0.8
  foamfix-0.9.9.1-1.12.2-anarchy
  forestry_1.12.2-5.8.0.290
  Forgelin-1.6.0
  ForgeMultipart-1.12.2-2.4.2.58-universal
  FTBGuides-1.0.2.6
  FTBLib-5.0.2.14
  FTBUtilities-5.0.2.14
  gendustry-1.6.5.8-mc1.12.2
  Harvest-1.12-1.2.6-18
  ImmersiveEngineering-0.12-82
  immersivepetroleum-1.12.2-1.1.9
  industrialforegoing-1.12.2-1.9.0-163
  InitialInventory-3.0.0
  InventoryTweaks-1.63
  IronBackpacks-1.12.2-3.0.7-10
  ironchest-1.12.2-7.0.40.824
  JEHC-1.12.2-1.5.1.0
  jei_1.12.2-4.9.1.179
  jeibees-0.9.0.5-mc1.12.2
  jeiintegration_1.12.2-1.5.1.36
  journeymap-1.12.2-5.5.2
  LibVulpes-1.12.2-0.2.8-31-universal
  LootTableTweaker-1.12.2-1.1.14
  MagicBees-1.12.2-3.1.9
  Mantle-1.12-1.3.2.24
  mcjtylib-1.12-2.6.7
  minetogether-1.10.2-1.8.7
  modtweaker-4.0.12
  moreoverlays-1.13-mc1.12.1
  Morpheus-1.12-3.3.2
  MouseTweaks-2.8-mc1.12.1
  MTLib-3.0.4
  natura-1.12.2-4.3.2.49
  NetherPortalFix_1.12.1-5.3.13
  oeintegration-2.3.3
  OpenBlocks-1.12.2-1.7.6
  OpenModsLib-1.12.2-0.11.5
  OreExcavation-1.4.118
  p455w0rdslib-1.12-2.0.29
  Pam's HarvestCraft 1.12.2u
  PrettyBeaches_1.12.2-1.0.3
  ProjectE-1.12-PE1.3.0
  Quark-r1.4-123
  QuickLeafDecay-MC1.12.1-1.2.4
  rangedpumps-0.5
  reauth-3.6.0
  RebornCore-1.12.2-3.8.1.271-universal
  RedstoneArsenal-1.12.2-2.4.2.9-universal
  RedstoneFlux-1.12-2.0.1.2-universal
  refinedstorage-1.5.33
  ResourceLoader-MC1.12.1-1.5.3
  rftools-1.12-7.33
  rftoolsctrl-1.12-1.8.1
  rftoolspower-1.12-1.0.0
  sampler-1.73
  SimpleLogic-0.5.0.239
  SimplyJetpacks2-1.12.2-2.2.4.34
  Snad-1.12.1-1.7.09.16a
  sonarcore-1.12.2-5.0.9
  SpiceOfLife-mc1.12-1.3.11
  SplashAnimation-0.1.0
  StandardExpansion-3.4.141
  StevesCarts-1.12.2-2.4.18.92
  StorageDrawers-1.12.2-5.3.6
  StorageDrawersExtras-1.12-3.1.0
  TConstruct-1.12.2-2.9.1.65
  TechReborn-1.12.2-2.15.6.642-universal
  Tesla-1.12.2-1.0.63
  tesla-core-lib-1.12.2-1.0.14
  theoneprobe-1.12-1.4.22
  ThermalCultivation-1.12.2-0.2.0.6-universal
  ThermalDynamics-1.12.2-2.4.1.10-universal
  ThermalExpansion-1.12.2-5.4.2.27-universal
  ThermalFoundation-1.12.2-2.4.1.15-universal
  TinkerToolLeveling-1.12-1.0.4
  TipTheScales-1.12.2-1.0.1
  topaddons-1.12.2-1.6.0
  torchmaster_1.12.2-1.6.4.62
  Translocators-1.12.2-2.5.0.70-universal
  Traverse-1.12.2-1.5.3-58
  UniDict-1.12.2-2.5b
  valkyrielib-1.12.2-2.0.10b
  WanionLib-1.12.2-1.5
  WirelessCraftingTerminal-1.12.2-3.9.64
  WR-CBE-1.12.2-2.3.0.27-universal
  xnet-1.12-1.6.9
  YABBA-1.1.2.7
  zerocore-1.12-0.1.2.1

Params:
  --username  --version MultiMC5 --gameDir C:/Users/ester/OneDrive/Desktop/MultiMC/instances/FTBContinuum-1.0.1-1.12.2/minecraft --assetsDir C:/Users/ester/OneDrive/Desktop/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx5120m, -Duser.language=en]

Minecraft process ID: 2252

Using onesix launcher.

2018-05-16 18:46:17,943 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[18:46:18] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:46:18] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraftforge.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_171]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Process exited with code 1.
Clipboard copy at: 16 May 2018 18:47:57 -0400

**Comment by peterix** [comment]
Try moving it out of OneDrive.

**Comment by DirtyDango** [comment]
I moved it directly to my C drive and still get the same issue.

**Comment by Janrupf** [comment]
Try to move it somewhere where it has full read/write access and is not in OneDrive. Does windows now only have this OneDrive desktop directory?
