### ISSUE TITLE
Exceptions are catched by values rather than const&

### ISSUE THREAD

**Issue by sylveon** [MultiMC/MultiMC5#2277]
In multiple places of the source code, we can see the following snippet:

    catch (Exception e)

This results in a memory copy when an exception is thrown. The correct form should be

    catch (const Exception &e)

My compiler found this in `application/MultiMC.cpp` (line 177), `application/UpdateController.cpp` (line 334) and `application/themes/CustomTheme.cpp` (lines 69, 120, 174 and 188)

**Comment by peterix** [comment]
That seems fairly minor.

Can you make a pull request for it?

**Comment by peterix** [comment]
And what compiler do you use?

**Comment by sylveon** [comment]
I'm not even sure what compiler that Cmake ended up picking, but I have gcc 8.1.0 and Clang 6.0.0 on my system. I'll make a pr in a few minutes.
