### ISSUE TITLE
Was Launching fine, Now Keeps Auto-Crashing

### ISSUE THREAD

**Issue by xLeprachaun86x** [MultiMC/MultiMC5#2279]
System Information
-----------------------------
MultiMC version: MultiMC 5 - version 0.6.2 - 1222

Operating System: win10 64-bit

Summary of the issue or suggestion: Will not launch instance
----------------------------------------------
It was playing fine for the last few days, then all of a sudden, it stoped working, and started to auto crash everytime i clicked on the launch button, online or offline, if need bee the crash report is her; https://paste.ee/p/JJXCe

What should happen: I Dont Know
------------------------------
Prefferably tell me why it keeps crashing on me, and what i an do to fix it and start playing it again

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Janrupf** [comment]
Maybe some AV messing with MultiMC and preventing it to extract the natives.

**Comment by peterix** [comment]
Maybe

* Sometimes Minecraft keeps running in the background. Make sure there's no leftover Java process running -- a reboot should do that. Or you can look at the system processes and kill any leftover Java.
* If that doesn't help, delete `C:/Users/dma_l/Desktop/MultiMC/instances/1.12.2/natives`
