### ISSUE TITLE
MultiMC follows directory symlinks during instance copy on Windows

### ISSUE THREAD

**Issue by JRoush** [MultiMC/MultiMC5#228]
As mentioned in https://github.com/MultiMC/MultiMC5/issues/42, I use symlinks to set up centralized resourcepack folders, config files, etc.  The issue is that MultiMC recursively follows directory symlinks during copy and delete operations, so if I tell MultiMC to delete one of my instances then it will nuke all of my centralized stuff too.  On the other hand, if I delete the instance folder manually in Windows Explorer then it just deletes the symlinks without following them.

Would it be possible to make the "Copy/Delete Instance..." commands treat symlinks opaquely?

Details:
MultiMC 0.3.2-dev236
Windows Vista
This issue occurs _only for contents of symlinked directories_.  The actual directory that the link targets is not deleted, just emptied, and links to individual files do not result in the targeted file being deleted.  This is an issue with the way MultiMC (or Qt) _recurses_ while looking for things to delete.

**Comment by peterix** [comment]
Fixed copying on linux: it preserves symlinks now.

**Comment by peterix** [comment]
Will fix deletion next.

Deletion works fine on linux and does not follow symlinks. The situation is worse on Windows.

**Comment by peterix** [comment]
Should be fixed in unstable and needs testing

**Comment by peterix** [comment]
OK.
Instance copy and delete on unix flavors is fixed.
Instance delete on Windows is fixed.

Instance copy on Windows is still doing a deep copy.

So, the possible data loss has turned into a slight inconvenience. I'll keep the issue open because of that.

**Comment by peterix** [comment]
The last bit is sadly a bit crazy:
http://stackoverflow.com/questions/24113324/how-to-copy-directory-symbolic-link-as-a-link-to-the-target

**Comment by peterix** [comment]
This is not practical to fix.
