### ISSUE TITLE
[Linux, custom compiled] Can't run any MC-Version (with or without mods) - liblwjgl64.so

### ISSUE THREAD

**Issue by liketechnik** [MultiMC/MultiMC5#2280]
System Information
-----------------------------
MultiMC version: 0.6.1-custom

Operating System: Gentoo Linux 64bit, multilib install (64 and 32 bit libraries)(installed Oracle Java JDK 8 u172, strangely its u162 in the log)

Summary of the issue or suggestion:
----------------------------------------------
Unable to start MC (with our without mods, regardless of version or modpack), it quickly errors the library liblwjgl.so had stack guard disabled (see logs), then crashes. 

What should happen:
------------------------------
MC should start normally.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add any Minecraft/Modpack to MultiMC.

2. Start it...

3.

Suspected cause:
---------------------------
No idea, maybe an incompatible Java version, or an incorrect path variable (although I double checked the path settings). Other idea: I recently made my system completely multilib compatible to be able to run 32bit applications. Is MultiMC downloading the wrong natives?

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
Sevtech Ages, v 3.6.0: https://gist.github.com/liketechnik/1390f40cbcc8d12a928df72ede2ec1d0#file-sevtech-ages-v-3-6-0-log
Vanilla, v 1.12.2: https://gist.github.com/liketechnik/1390f40cbcc8d12a928df72ede2ec1d0#file-vanilla-v-1-12-2-log

[Upload to paste.ee failed]

Additional Info:
---------------------------
- I tried to find the library in the given path, but for all instances, the directory natives did not exist. 
- I although tried to manually redownload the lwjgl libraries via the settings menu, that also didn't fix the issue.
- I don't use the precompiled version, but a locally compiled one.

[Edit: Formatting issues]

**Comment by Janrupf** [comment]
Interesting, looks like your Java installation is missing AWT (which is one of Java's windowing frameworks) native libraries. How did you install Java?

**Comment by peterix** [comment]
Looks like you only have the headless verison of java.

**Comment by liketechnik** [comment]
Yep, you're right guys, somehow I thought it'd be cool to install the jdk with the ```headless-awt``` flag, which is why I don't have the awt libraries. Thanks for your help, everything's working like a charm now. And btw, I really appreciate your work for the launcher, I really couldn't imagine using another one.
