### ISSUE TITLE
OneDrive causes game crashes on launch

### ISSUE THREAD

**Issue by blakjak08** [MultiMC/MultiMC5#2281]
*I am completely new to this and not really sure what is suppose to happen in the first place*

System Information
-----------------------------
MultiMC version: **0.6.2-1222**

Operating System: Windows 10 Pro

Summary of the issue or suggestion:
----------------------------------------------
After adding mods to MultiMC in a new instance or even add a modpack from the zip folder, the launcher gets about halfway loaded before it get a game crash. 

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------
CodeChickenLib?

Logs/Screenshots:
----------------------------
[https://pastebin.com/nHNXjMxj](url)
[https://pastebin.com/s7FbRiBw](url)

Additional Info:
---------------------------
this is the log for SevTech Ages, but even when I tried a different modpack and another instance without CodeChickenLib, it still happened just the same. That crash report is the 2nd one listed.

**Comment by tehbasshunter** [comment]
You mind uploading the full log?

**Comment by blakjak08** [comment]
hang on a min and i'll get it for you.

**Comment by blakjak08** [comment]
Here you go [https://pastebin.com/u0ZzJmEz](url)

**Comment by QuImUfu** [comment]
move MultiMC out of OneDrive.

**Comment by blakjak08** [comment]
that worked, at least for now. why does one folder cause that problem?

**Comment by tehbasshunter** [comment]
I believe it's because onedrive is possibly trying to sync the files as they update and it's a little hard to do that when the files are in use.
