### ISSUE TITLE
List Update Failed: meta/json file failed to process

### ISSUE THREAD

**Issue by Blackcomet** [MultiMC/MultiMC5#2282]
System Information
-----------------------------
MultiMC version:0.6.2-1222

Operating System:8.1

Summary of the issue or suggestion:
----------------------------------------------
When creating a new instance I receive a pop-up saying "job 'download of meta file net.minecraft/index.json' failed to process".
When I click [refresh] I receive the same pop-up.

What should happen:
------------------------------
A new instance is created, allowing me to start a game.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.click add instance 

2.clicking refresh

Suspected cause:
---------------------------
Missing file

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
I can't find the [upload] button that the wiki says to click that allows me to upload screenshots.

**Comment by nmagod** [comment]
I'm experiencing this specifically when I "migrate" an old instance (for example, FTB Retro SSP as in the screenshot) and then try to launch it afterwards.
![unknown](https://user-images.githubusercontent.com/30885355/47097563-359c7580-d221-11e8-8fb1-9d4b3b58667c.png)

**Comment by peterix** [comment]
Can you share one of those instance before migration?
