### ISSUE TITLE
cursemeta.dries007.net returns a 502/524

### ISSUE THREAD

**Issue by Blackcatz1911** [MultiMC/MultiMC5#2283]
System Information
-----------------------------
MultiMC version: 0.6.2-develop-1226

Operating System: Win7

Summary of the issue or suggestion: 
----------------------------------------------

https://cursemeta.dries007.net/ returns a 502/524 and so the json files cannot be downloaded.

What should happen:
------------------------------
Download with no issues

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Try to import zip file

2. MultiMC starts to import Mods

3. MultiMC fails to download due to 502/524

Suspected cause:
---------------------------

Wrong/faulty server config or overload?

Logs/Screenshots:
----------------------------
MultiMC.log: https://paste.ee/p/P0Acv
HTML Answer from cloudflare 524: https://paste.ee/p/6ESWF
HTML Answer from cloudflare 502: https://paste.ee/p/rpDli

**Comment by TSM-EVO** [comment]
Also having this issue.
