### ISSUE TITLE
Account is currently not logged in, when it should be.

### ISSUE THREAD

**Issue by darthvader45** [MultiMC/MultiMC5#2285]
Not sure why, I'm pretty sure I've been logged in for quite some time.

System Information
-----------------------------
MultiMC version: 0.6.2

Operating System: Windows 10 April 2018 update

Summary of the issue or suggestion:
----------------------------------------------
Even though my account was logged in to add it, I still receive an error saying my account is not currently logged in when launching an instance.

What should happen:
------------------------------
Instance launches, no prompt to login.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.
Make sure account is added.
2.
Attempt to launch instance.
3.
Message pops up.
Suspected cause:
---------------------------
Possibly not remembering the fact the account is logged in.

Logs/Screenshots:
----------------------------
![account not logged in](https://user-images.githubusercontent.com/2816420/40451631-33f9dafc-5ead-11e8-9392-16afa2f7e4af.PNG)

Additional Info:
---------------------------

**Comment by spannerman79** [comment]
This is common if you use something like OneDrive to sync/backup MultiMC.

Another issue that arises (not MultiMC fault - blame Mojang) is if your IP address changes or your login creds become invalid then you will need to re-auth.

**Comment by darthvader45** [comment]
IP never changed, password hasn't changed (which would be the only reason
the creds would become invalid aside from some big problem on Mojang's
side), so no idea why this randomly happens.

Golden rule in Minecraft: Never dig straight down.

**Comment by Heufneutje** [comment]
I'm guessing it's a thing on Mojang's end then. MultiMC keeps you logged in as long as your authentication token is valid. If Mojang says it's invalid, MultiMC has to request a new one by making you log in again.

**Comment by darthvader45** [comment]
Which sucks.  Mojang should really work on their tokens.  Make em last
longer.

Golden rule in Minecraft: Never dig straight down.

**Comment by peterix** [comment]
They shold last forever, unless the service decides you did something fishy.

I cannot fix this, even working for the company. It's a bigger task than one dude can dix alone.
