### ISSUE TITLE
FTB Modpack Update

### ISSUE THREAD

**Issue by megamarw1** [MultiMC/MultiMC5#2287]
It would be very nice to have a possibility to update FTB Modpacks without reinstalling them manually, if an update is there.

**Comment by peterix** [comment]
See:
https://github.com/MultiMC/MultiMC5/issues/1506
https://github.com/MultiMC/MultiMC5/issues/1605
https://github.com/MultiMC/MultiMC5/issues/1777
https://github.com/MultiMC/MultiMC5/issues/1989
https://github.com/MultiMC/MultiMC5/issues/2289

If anything, all this needs to be squashed together into one issue.

**Comment by Janrupf** [comment]
Yep, thats a planned feature, but not only for FTB Packs. There should also be an option to update to latest Vanilla.
