### ISSUE TITLE
Native Optifine

### ISSUE THREAD

**Issue by megamarw1** [MultiMC/MultiMC5#2289]
A button for native installaton and updating for optifine if forge is installed, so you don't have to download and update it manually. Would be very nice and usefull.

**Comment by peterix** [comment]
See:
https://github.com/MultiMC/MultiMC5/issues/1506
https://github.com/MultiMC/MultiMC5/issues/1605
https://github.com/MultiMC/MultiMC5/issues/1777
https://github.com/MultiMC/MultiMC5/issues/1989

If anything, all this needs to be squashed together into one issue.
