### ISSUE TITLE
Building fails when using qt 5.11

### ISSUE THREAD

**Issue by kargaroc** [MultiMC/MultiMC5#2291]
Support for using qt5_use_modules() was dropped in Qt 5.11

I tried building on Arch which has Qt 5.11, and got this

```
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Using override nbt++ name: MultiMC_nbt++
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
CMake Error at libraries/ganalytics/CMakeLists.txt:15 (qt5_use_modules):
  Unknown CMake command "qt5_use_modules".


-- Configuring incomplete, errors occurred!
See also "/home/terus/Desktop/MultiMC5-0.5.2-final/Build/CMakeFiles/CMakeOutput.log".
```

**Comment by kdb424** [comment]
Still getting this error installing on Arch Linux from the aur on the git package. Build is cleaned on every attempt as files are stored in /tmp so seems broken still at least on Arch.

**Comment by Janrupf** [comment]
Yes, the PR needs to be merged... but for some reason git bugged on the CI so that the build failed. Or it is something different that @peterix has to check.

**Comment by kdb424** [comment]
Exact same error still as far as I can see. Just retried it, and no change.

**Comment by kdb424** [comment]
CMake Error at libraries/ganalytics/CMakeLists.txt:15 (qt5_use_modules):
  Unknown CMake command "qt5_use_modules".
Still getting the error, but will continue watching this and updating you as I see changes if you'd like.

**Comment by Janrupf** [comment]
Just look here: https://github.com/MultiMC/MultiMC5/pull/2304
Until this is merged it will not work!

**Comment by kdb424** [comment]
Noted. Thank you for the update on that. I'll keep an eye there.

**Comment by peterix** [comment]
Well, I am finally situated here in Sweden and got to this now.

Let's continue where we left off :)
