### ISSUE TITLE
error while loading shared libraries: libMultiMC_gui.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by MagentaRuby** [MultiMC/MultiMC5#2292]
System Information
-----------------------------
MultiMC version: multimc_1.2-1.deb

Operating System: Ubuntu 18.04 64-bit

Summary of the issue or suggestion:
----------------------------------------------
MultiMC doesn't launch, but displays an error if run in a terminal.

What should happen:
------------------------------
MultiMC should launch.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download the .deb package.

2. Install it.

3. Attempt to run `/opt/multimc/run.sh`

Suspected cause:
---------------------------
A library didn't get installed or it's looking in the wrong location?

Logs/Screenshots:
----------------------------
```
ruby@ruby-Lenovo-Z710   /opt/multimc
 > ./run.sh 
MultiMC Dir: /home/ruby/.local/share/multimc
No missing dependencies found.
/home/ruby/.local/share/multimc/bin/MultiMC: error while loading shared libraries: libMultiMC_gui.so: cannot open shared object file: No such file or directory
```

**Comment by peterix** [comment]
So what is in `/home/ruby/.local/share/multimc`?

Run:
```
find /home/ruby/.local/share/multimc > ~/multimc.txt
```
And upload the ~/multimc.txt here.

**Comment by MagentaRuby** [comment]
https://gist.github.com/MagentaRuby/e86c9855bff0381b2744b5bdda9c6ffb

**Comment by peterix** [comment]
Looks like it failed to download...

Delete `/home/ruby/.local/share/multimc` and trry again :)

**Comment by MagentaRuby** [comment]
That worked. Thanks.
