### ISSUE TITLE
Can't use OptiFine - hangs on "getting library files from mojang"

### ISSUE THREAD

**Issue by Straighten-Your-Back** [MultiMC/MultiMC5#2303]
I followed the instructions outlined [here](https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine) - my Optifine version is OptiFine_1.12.2_HD_U_D3.jar

Here is the contents of the "empty" I created:

```
{
    "formatVersion": 1,
    "+libraries": [
        {
            "name": "net.minecraft:launchwrapper:1.12"
        },
        {
            "name": "optifine:OptiFine:1.12.2_HD_U_D3",
            "MMC-hint": "local",
            "MMC-filename": "OptiFine_1.12.2_HD_U_D3.jar"
        }
    ],
    "+tweakers": [ "optifine.OptiFineTweaker" ],
    "fileId": "optifine.OptiFine",
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "requires": [
        {
            "uid": "net.minecraft",
            "equals": "1.12.2"
        }
    ],
    "name": "OptiFine",
    "version": "1.12.2_HD_U_D3"
}
```
The optifine jar is inside both MultiMC/instances/1.12.2/libraries, AND MultiMC/instances/1.12.2/.minecraft/libraries - I had to make both folders, but neither seems to work. I'm assuming I've put it in the wrong "libraries" folder (given that I had to make them in the first place). but I can't find an existing one to put it in. That particular line of the instructions was very vague.

**Comment by tehbasshunter** [comment]
Any particular reason you're not installing alongside forge?

**Comment by Straighten-Your-Back** [comment]
The exact same thing happens if I try to do it via forge - I assumed it was because I'm already using a liteloader-required mod, and the two are incompatible.

**Comment by peterix** [comment]
optifine is only compatible with things it is explicitly compatible with... which is usually the one version of forge it is built for/tested for.
With anything else, all bets are off.

That said, if it's stalling on downloads, ot has nothong to do with optifine and everything to do with either your network, or the server simply not responding.

Check multimc.0.log file for more details about what is going on with the download.
