### ISSUE TITLE
Please compatible with screen which size is 1366x768

### ISSUE THREAD

**Issue by WitherZuo** [MultiMC/MultiMC5#2308]
<h3>System Information: </h3>
MultiMC version: 0.6.2 and all previous versions<br>
Operating System: Windows 10 Home 17134.81<br>
Summary of the issue or suggestion: Can not show all the things of User interface on 1366x768 screen<br>
----------------------------------------------<br>
<h3>What should happen:</h3>
 Can show all the things of user interface.<br>
------------------------------<br>
<h3>Steps to reproduce the issue (Add more if needed):</h3>
 Open the launcher on a device (like laptop) which screen size is 1366x768, then see the launcher ui.<br>
-------------------------------<br>
<h3>Screenshot:</h3>
![tempsnip](https://user-images.githubusercontent.com/25317916/41013231-b0c46280-6977-11e8-8539-62be35eee667.png)

**Comment by WitherZuo** [comment]
Maybe can resize the window by user is a good idea....❤

**Comment by kb-1000** [comment]
Fixed by e4273d6a174ffb771728f32b5e2a8a36096c4e21.
