### ISSUE TITLE
Upgrading multi-MC results in loss of instances.

### ISSUE THREAD

**Issue by keybounce** [MultiMC/MultiMC5#2315]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

There is a serious bug in multi-MC on the Mac.

My first attempt to upgrade (previously running a 2016 version) was simply deleting my old multi-MC application, and putting in the new one. All of my instances were lost. The new instance folder was inside the multi-MC application. This is a major no-no, especially if the same computer is being used by 2 different people. There is a per user Library/application support directory where per app preferences and data storage is supposed to be placed.

After restoring my old one from backup, and verifying that I had my whole list of instances, I did the upgrade from inside the program. Only one instance survived; all the others were lost.

What should happen:
------------------------------
1. Upgrading should not lose instances.

2. Instance information should not be stored inside the application folder.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Start with multi-MC 5 version 0.4.11 – 713.

2. Have a 1.7.10 pack, and several "FTB" packs, ranging from actual 1.5.2 FTB packs to 1.7.10 FTB packs, and a couple of 1.4.7 local packs that are labeled as legacy FTB packs.

3. Upgrade.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

I cannot find a log for multi-MC 5

Additional Info:
---------------------------

**Comment by Janrupf** [comment]
Why not letting MultiMC upgrade itself? Or did you use the MultiMC update mechanism? And if tracked FTB Packs dissapeard... the FTB dupport was reworked and tracking was removed. Install then via MultiMC now.

**Comment by peterix** [comment]
Yes. FTB tracking was removed. All your FTB packs are still accessible through the legacy FTB launcher.

The portable builds always store data in the application folder and do not touch the rest of the system.
