### ISSUE TITLE
SKCraft modpack support

### ISSUE THREAD

**Issue by NikkyAI** [MultiMC/MultiMC5#2322]
I hope we can give multimc native support for skcraft packs (or a self defined derivate format)

the sk pack format is generally sensible and just gets messy in the libraries section which we do not have to care for because we can just grab the minecraft and forge versions and use existing multimc logic

this was implemented by me already as a pre-launch command that would update the mmc-pack.json
https://github.com/elytra/Voodoo/tree/master/multimc/installer
feel free to use this code as reference or inspiration

the basic steps are:

1. read and parse pack from remote location  
2. check the installed pack
maybe cancel if the versions match
3. pull minecraft and forge versions from the pack
4. popup feature dialog
5. iterate though all tasks
  depending on if the files exists, the task exists in the current and/or the previously installed pack and the correctlness of the sha1 hash of the file  
delete or overwrite the file from the specified location (or cache)

**Comment by peterix** [comment]
The links no longer lead anywhere...
