### ISSUE TITLE
FTB Legacy installer not aborting

### ISSUE THREAD

**Issue by vertex101** [MultiMC/MultiMC5#2323]
System Information
-----------------------------
MultiMC version: 0.6.2-develop-1228

Operating System: Windows 7

Summary of the issue or suggestion: when using the FTB legacy installer when u hit the abort button it does not stop it keeps going until fully installed
----------------------------------------------

What should happen: when u hit the abort button it should stop the process not keep going
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. start to install a modpack from FTB legacy installer

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

https://imgur.com/a/AgnhIy5

Additional Info:
---------------------------

**Comment by Janrupf** [comment]
To be honest, its a known bug, but nobody complained so far 😀.

**Comment by kaeptmblaubaer1000** [comment]
I do complain

**Comment by peterix** [comment]
Fix'd
