### ISSUE TITLE
Game consistently fails to start.

### ISSUE THREAD

**Issue by TheScrawl** [MultiMC/MultiMC5#2324]
System Information
-----------------------------
MultiMC version: 0.6.2-develop-1228 on win32

Operating System: Windows 10 x64

Summary of the issue or suggestion:
----------------------------------------------
Attempting to run modded instances results in a crash for unclear reasons

I thought it might be a java problem, so I uninstalled my older java installation and installed Java 10.
I have tried deleting my install and downloading again multiple times.
I also tried changing to development branch, but that did not seem to work either.

What should happen:
------------------------------
The game should start without crashing.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Remove all old versions of Java and install Java 10

2. Download MultiMC and unzip to a folder

3. Run with dedicated graphics instead of integrated (using integrated causes other issues)

3. Create a new non-vanilla instance. In my case I am using FTB Infinity Evolved, and I have also tried with a custom mod set.

Suspected cause:
---------------------------
Could be a java issue? However Minecraft with the official launcher works fine.
Could be an issue with the downloads too, downloading files seems to take extraordinarily long, and its possible something is going wrong along the way.

Logs/Screenshots:
----------------------------
https://paste.ee/p/JhvQy

Additional Info:
---------------------------
I am running an Acer laptop with an i5-4210U, 8gb of ram and a Geforce 820m

**Comment by peterix** [comment]
Java 10 will never work with modded Minecraft, for all current versions of modded Mionecraft. Start with Java 8, and then we might get somewhere.

**Comment by TheScrawl** [comment]
I did wonder if this was the issue. I will install Java 8 now.

**Comment by peterix** [comment]
There could be more issues of course, but this is the one you are running inrto now :)

Make sure it's 64bit Java.

**Comment by TheScrawl** [comment]
This did appear to fix my problems, thanks for all the help :)
