### ISSUE TITLE
Building from AUR, why older java version are needed to be installed?

### ISSUE THREAD

**Issue by Rencer** [MultiMC/MultiMC5#2329]
I'm using the Arch based Manjaro Linux and the latest OpenJDK Java version 10.
When try to install MultiMC from AUR, it requires (makedepend) java-environment>=8, so any Java version which is 8 or later AND java-environment<10 which is any Java that is OLDER than 10.
I really don't want to install any older Java versions. Is that possible to build MultiMC just with version 10, without installing any older versions?

**Comment by jikuja** [comment]
No, modded minecraft will not work with java 9 or newer.

**Comment by Rencer** [comment]
Oh, I dind't know that. Thanks for the very quick answer!
