### ISSUE TITLE
MultiMC not obey "Max/Min memory allocation config" and just give all memory to Client

### ISSUE THREAD

**Issue by ReiDaTecnologia** [MultiMC/MultiMC5#2331]
System Information:
RAM: 8GB
Processor: Intel Core i3 2120
Video Card: NVIDIA GeForce GT 240
MultiMC version:
0.6.2-1222
Operating System:
Windows 7 Ultimate x64
Summary of the issue or suggestion:
When i configure MultiMC to only allocate specified memory, he just don't obey and give all memory to him without being impeded. Tested in Vanilla Launcher with the same modpack (All The Mods 3) and the Vanilla Launcher obey and just give 1GB (Default memory allocation config) to him until "Out Of Memory Error" appear, looks like Vanilla Launcher fight bravely with Forge to don't allow him to pass the 1GB config and make him don't pass more than 1,8GB! while MultiMC allow him pass freely without stop, don't obeying the config.
What should happen:
Obey the specified min and max memory allocated in the config
Steps to reproduce the issue (Add more if needed):
1) Put any amount of memory in the config (Even 128 work).
2) Launch any Instance.
3) See in the Task Manager, the javaw.exe memory going up without being impeded.
Suspected cause:
Internal MultiMC issue?
Logs/Screenshots:
N/D
Additional Info:
If you want i can test in the VirtualBox to see if it's OS issue, not MultiMC issue.

**Comment by Janrupf** [comment]
A log would be very helpful. Click the upload button in the "Minecraft Log" tab in the instance settings and paste the link here.

**Comment by ReiDaTecnologia** [comment]
I know but don't have nothing in the log because it's not Minecraft issue and i don't put a log because i thought it's obvious. Unless the MultiMC have a logging system?

**Comment by peterix** [comment]
Java issue, definitely won't fix.

**Comment by peterix** [comment]
And without a log, there is nothing to go on. So, attach a log.

**Comment by ReiDaTecnologia** [comment]
Now he start to work as should he do. I will keep my eye open to see if it's a rare or occasional problem.
