### ISSUE TITLE
moreplayer models

### ISSUE THREAD

**Issue by MasterTheFantasy** [MultiMC/MultiMC5#2333]
hi, I wanted to tell you that multi mc does not make me work the mod moreplayermodels to all my friends works but I could not know why?

What happens: the changed skin they see it but then when I sit down or lie down I do not see myself sitting and lying instead I see them lying down and sitting I would like to solve it as soon as possible, it could be my problem but I did the same thing my friend but my pc does not work while in my friend and my brother works, I would like to understand why it does not work. I tried to search on the internet but I did not find solutions so I contacted the MultiMc staff, thank you for reading the message and good work !!

**Comment by Janrupf** [comment]
Can you upload the Minecraft log? But that sounds like an error in MorePlayerModels itself.

**Comment by MasterTheFantasy** [comment]
I do not think this is the problem nor the mod more player models,
because my friends all work perfectly, they gave me their mod ect ...
I did the same procedure but it does not work giving me the problem:
that they do not they see me when I do certain actions: sit down lying
down ect ...




2018-07-06 14:45 GMT+02:00 Janrupf <notifications@github.com>:

**Comment by Heufneutje** [comment]
Without the Minecraft log we won't be able to help you.
