### ISSUE TITLE
Force --tweakClass to not be ignored?

### ISSUE THREAD

**Issue by Cynosphere** [MultiMC/MultiMC5#2334]
I am trying to make a pure optifine only instance for someone since they can't use the regular launcher due to space issues and Forge uses too much RAM for them (as they have a low RAM).
The only issue I have is whenever I try to run it, it says `Completely ignored arguments: [--tweakClass, optifine.OptiFineTweaker]`.

Is there anyway I can bypass this so it uses the tweakClass param?

**Comment by peterix** [comment]
You are reinventing a wheel.

Please see: https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine

**Comment by Cynosphere** [comment]
Didn't know that existed, thanks.
