### ISSUE TITLE
MultiMC crashes every time I load a world.

### ISSUE THREAD

**Issue by EpicPie** [MultiMC/MultiMC5#2338]
System Information
-----------------------------
MultiMC version: MultiMC5 Version 0.6.2
Operating System: Microsoft Windows Version 1803
Summary of the issue or suggestion:
----------------------------------------------
I downloaded MultiMC today and started using it after I added all my mods i wanted to use. The first world I loaded worked perfectly fine. Later I realized that one of my mods hadn't been added. I then added the mod and loaded another world. This time I was playing for about 30 seconds before my game screen turned entirely light blue and then my game closed. On the bottom of the MultiMC where it shows how long you have played it said the game had crashed and my Instance icon had a red circle with a white x in it on the right hand corner. At first i thought it was the mod i had added so i took it out and loaded another world but the same thing happened, I played for 30 seconds then my game screen turns blue and crashes. I watched a tutorial on how to add the mods and they all work perfectly fine but my game keeps crashing. I tried switching to the development version and it still crashes.      

What should happen:
------------------------------
I should Launch my Instance and then play my game normally. 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Go to MultiMC 

2. Launch my Instance

3. Play my world

Suspected cause:
---------------------------
I honestly have no idea i have never used MultiMC before.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
My Log Link again: https://paste.ee/p/36syl

Additional Info:
---------------------------
After the red x appears it wont let me edit my Instance.

**Comment by QuImUfu** [comment]
The log does indicate the instance exited normally. 
Did the game really crash?

**Comment by EpicPie** [comment]
@QuImUfu Yes, after the game screen goes blue and then exits at the bottom of my MultiMC page where it says how long i have played for it says "crashed".

**Comment by QuImUfu** [comment]
are you sure you uploaded the log of a crashed launch?  
the log you linked states:   
Process exited with code 0.  
This indicates that MultiMC thinks it exited normally, MultiMC should not show the red x after the launch that led to that log.   
Can you upload another log of a launch where the instance crached?  
Apart from that i have no idea how to help you, because the linked log does not indicate **anything** special/suspicious. (afaik)

**Comment by EpicPie** [comment]
@QulmUfu I just loaded it up again and let it crash and then uploaded the log again, here it is. https://paste.ee/p/4XGNx

**Comment by QuImUfu** [comment]
this crash seems to be caused by Copious Dogs.  
You might want to try downloading and using the latest version for 1.7.10 from:  
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/wip-mods/2375611-copious-dogs-mod

**Comment by EpicPie** [comment]
@QulmUfu Oh I really didn't think it was my mods because the first game I loaded worked completely fine but let me go delete my old one and download that one and see if it works. :)

**Comment by EpicPie** [comment]
@QulmUfu So i downloaded the new one and loaded my game and it was working perfectly fine except for a little lag but then it did the exact same thing again. https://paste.ee/p/WwWGv here's the new log

**Comment by QuImUfu** [comment]
in this case i can only suggest removing Copious Dogs completly, as it is bugged.  
You could sent that report to the devs as well, and hope they fix it.

**Comment by EpicPie** [comment]
@QuImUfu Will do, thank you for all you help. :)

**Comment by EpicPie** [comment]
@QuImUfu  So sorry to bug you again but I took my Copious Dogs out and it has been working fine but now its crashing on me again? https://paste.ee/p/oAmM6

**Comment by peterix** [comment]
Looks like a broken mod. Try disabling the version checks in bibliocraft.

**Comment by peterix** [comment]
Also, this is not a MultiMc issue.
