### ISSUE TITLE
Resource packs, when importing a Curse Modpack, are installed to the mods folder

### ISSUE THREAD

**Issue by fisher521** [MultiMC/MultiMC5#2340]
System Information
-----------------------------
MultiMC version: 0.6.2-1222

Operating System: Windows 10 Home

Summary of the issue or suggestion: 
----------------------------------------------
Resource packs, when importing a Curse Modpack, are installed to the mods folder

What should happen:
------------------------------
Resource packs should be installed to the resourcepacks folder

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. From the MultiMC main menu, click "Add Instance"

2. Choose "Import From Zip"

3. Paste the download link of a Curse modpack that has a resourcepack in the box

Suspected cause:
---------------------------
<sup>I have no clue</sup>

Logs/Screenshots:
----------------------------
![image](https://user-images.githubusercontent.com/29507110/42734957-e0dde13c-887e-11e8-88bb-95365bb9670a.png)

Additional Info:
---------------------------

**Comment by peterix** [comment]
Which pack is this?

**Comment by fisher521** [comment]
https://minecraft.curseforge.com/projects/survival-rediscovered

**Comment by Scotsguy** [comment]
I can reproduce the problem.
My log if you need them: https://paste.ee/p/CwHa7

**Comment by dries007** [comment]
Should be fixed now.

**Comment by Scotsguy** [comment]
It's fixed. Resource Packs go in the Resource Pack Folder, and mods still go in the mods folder
