### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Broadwind** [MultiMC/MultiMC5#2343]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------
I can't make an Instance, whenever I try it says ''No versions currently available'' in the Vanilla section. I think my MultiMC can't access my Minecraft application.

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Broadwind** [comment]
Also this pops up :List update failed:
Job 'Download of meta file net.minecraft/index.json' failed to process:
https://v1.meta.multimc.org/net.minecraft/index.json

**Comment by QuImUfu** [comment]
MultiMC seems to be unable to connect to the internet.
Upload MultiMC-0.log to provide further information.

**Comment by storay** [comment]
Same issue, checked the log and this is what came up:


    1.793 W QSslSocket: cannot call unresolved function SSLv23_client_method
    1.793 W QSslSocket: cannot call unresolved function SSL_CTX_new
    1.793 W QSslSocket: cannot call unresolved function SSL_library_init
    1.793 W QSslSocket: cannot call unresolved function ERR_get_error
    1.793 W QSslSocket: cannot call unresolved function ERR_get_error
    1.816 W QSslSocket: cannot call unresolved function SSLv23_client_method
    1.816 W QSslSocket: cannot call unresolved function SSL_CTX_new
    1.816 W QSslSocket: cannot call unresolved function SSL_library_init
    1.816 W QSslSocket: cannot call unresolved function ERR_get_error
    1.816 W QSslSocket: cannot call unresolved function ERR_get_error


This happens before MultiMC tries to download any file from a MultiMC related URL, responds with error **reason 99**.

**Comment by peterix** [comment]
Yes, you need openssl 1.0. likely, your distro has 1.1, but 1.0 is still installable next to it. Check your package repos for openssl-1.0

**Comment by peterix** [comment]
Oh. Mac. Nevermind. Update the OS.

**Comment by Broadwind** [comment]
yea thx it worked

**Comment by Broadwind** [comment]
new problem tho...

**Comment by Broadwind** [comment]
not sure if this is only 1.12.2 but when ever I install forge in an instance, it keeps crashing

**Comment by Broadwind** [comment]
even if I pick the star one

**Comment by Broadwind** [comment]
this is what it shows if it helps

**Comment by Broadwind** [comment]
Minecraft folder is:
/Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/instances/Wurst/.minecraft


Java path is:
/usr/bin/java


Java is version 10.0.2, using 64-bit architecture.


Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/instances/Wurst/natives

Libraries:
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/net/minecraftforge/forge/1.12.2-14.23.4.2705/forge-1.12.2-14.23.4.2705-universal.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/jline/jline/2.13/jline-2.13.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-osx.jar
  /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar

Params:
  --username  --version MultiMC5 --gameDir /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/instances/Wurst/.minecraft --assetsDir /Users/Broadwind/Desktop/MultiMC.app/Contents/MacOS/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: Test", -Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 1131


Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code 255.

**Comment by QuImUfu** [comment]
use java 8, 10 is not working for modded minecraft.
