### ISSUE TITLE
Allow attaching "default accounts" to instances

### ISSUE THREAD

**Issue by gbl** [MultiMC/MultiMC5#2344]
I have several MC accounts - my own, my friend, my kid - and sometimes I log in more than one of them, so I keep separate instances for them. Which means I have a configuration "Alice 1.12 with all mods" and another "Bob 1.12 with all mods". Of course, the Alice and the Bob account are both configured in MultiMC.

Unfortunately, it happens way too often that I want to start "Alice 1.12 with all mods" and forget to check the account selection, meaning I start that config with the Bob account. What I'd like to do is optionally link each instance to an account - whenever that instance gets selected, the "current account" selection box adjust accrodingly, so double-clicking always starts with the correct account. If I select the instance first, then change the account, I can still run it with a different account than it's linked to.

I already implemented this in a fork, I'll happily send you a pull request if you think this could be a good feature.

**Comment by peterix** [comment]
See: https://github.com/gbl/MultiMC5/commit/ed9db0e68d15325d45b0fafcda7e146776818aab
