### ISSUE TITLE
total time played 

### ISSUE THREAD

**Issue by MelanX** [MultiMC/MultiMC5#2345]
I think it's cool that you can see from every modpack how long you've been playing it.  What would appeal to me more personally is something that shows how long I have been playing with Minecraft instances from MultiMC.  So to speak all modpacks together at a single time. Is that a possible thing?

If the English was stupid: translated by German with the deepl translator.

**Comment by peterix** [comment]
Sure, I don't see why not :)

**Comment by Elvarion** [comment]
Sad to see this is still not a feature :p 
Ive been doing it manually by adding the time spent from previous packs into the ones I currently play xD
