### ISSUE TITLE
Failed to start minecraft, InvocationTargetException

### ISSUE THREAD

**Issue by Designation6of10** [MultiMC/MultiMC5#2346]
I'm putting together a modpack with my friends and have been testing it out. Just recently I decided to use MultiMC to make it a proper pack, since before we were just playing on our forge profiles. But after inserting the mods which I already play-tested together in the mods folder of the instance, I tried to launch it, and got the following:

```
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
               at java.base/
```
I have no idea what this means. Could anyone help me?

System Information
-----------------------------
MultiMC version: 0.6.2-1222

Operating System: Win10

Summary of the issue or suggestion:
----------------------------------------------
 Failed to launch instance

What should happen:
------------------------------
 Instance should launch as normal. Minecraft forge should load and be ready to play.

Steps to reproduce the issue (Add more if needed): 
-------------------------------------------------------------
Unknown. All I did was create the instance, add the mods, and launch it.

Suspected cause:
---------------------------
Unknown

Logs/Screenshots:
----------------------------
https://paste.ee/p/HCi3t

Additional Info:
---------------------------

**Comment by tehbasshunter** [comment]
You need Java 8. 10 isn't supported with modded.

**Comment by Designation6of10** [comment]
I have java 8, but MultiMC can't find it. I've tried navigating to it manually, auto detecting, etc. No luck.

**Comment by tehbasshunter** [comment]
Unless you have a use for J10 uninstall it and try autodetecting again.

**Comment by Designation6of10** [comment]
Finally got it working. Thanks!
