### ISSUE TITLE
Authentication Operation Failed

### ISSUE THREAD

**Issue by abrodbeck** [MultiMC/MultiMC5#2348]
System Information
-----------------------------
MultiMC version:0.6.2

Operating System: Windows 64bit 

Summary of the issue or suggestion:
----------------------------------------------
I cannot add an account never used multimc before it says authentication operation failed and I have proxy set to none as per some suggestions

What should happen:
------------------------------
allow me to add my account

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.try to add account

**Comment by peterix** [comment]
Hmmm.... If you are still around, this is likely an issue with your network or firewall.

Check the MultiMC.0.log file and see what gets printed there when you try to add an account.
