### ISSUE TITLE
MultiMC Crash

### ISSUE THREAD

**Issue by julioplayz** [MultiMC/MultiMC5#2351]
System Information
-----------------------------
MultiMC version: 0.6.2-develop-1237

Operating System: Windows 10 Home 64x

Summary of the issue or suggestion:
----------------------------------------------
Custom Steves Mod causing game to crash when i look at myself in 3rd person

What should happen:
------------------------------
I see my model, the one loaded in

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Start the game

2. Enter a mode where you see your player model

3. The game will immediately crash

Suspected cause:
---------------------------

Bug in the program, or Hardware insufficiency
Logs/Screenshots:
----------------------------
https://paste.ee/p/7noET

Additional Info:
---------------------------

**Comment by Heufneutje** [comment]
Sounds like a bug in the customsteve mod you're using. It's doing something wrong with rendering. Make sure both Forge and the customsteve mod are on the latest version. If it still crashes after that, report it to the mod author.

**Comment by QuImUfu** [comment]
Have you unpacked the CustomSteve folder from the zip to your mods folder?  
Java seems to be unable to find this and other files:  
```
C:\Users\HP.LAPTOP-76LM2JKH\Documents\MultiMC\instances\1.10.2\.minecraft\mods\CustomSteve\shaders\uberShader.vert
```

**Comment by S10MC2015** [comment]
Time: 7/24/18 12:39 AM
Description: Rendering entity in world

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	_**at customsteve.ba.a(p:367)
	at customsteve.c.a(p:284)
	at customsteve.p.a(p:709)
	at customsteve.asm.ASMPointer.c(p:24)**_

Caused by customsteve. Not MMC. Requesting issue closure
