### ISSUE TITLE
MMC creates 'minecraft' folder as '.minecraft'

### ISSUE THREAD

**Issue by donls** [MultiMC/MultiMC5#2352]
System Information
-----------------------------
MultiMC version: 0.6.2-1163

Operating System: MacOS Sierra 10.12.6

Summary of the issue or suggestion:
----------------------------------------------
Using the 'Instance Folder' menu selection on right side of window shows the instance folder, but the 'minecraft' folder is invisible. Examination from command line reveals the 'minecraft' folder is instead named '.minecraft'. Renaming the folder to 'minecraft' makes it visible, and the instance still runs.

What should happen:
------------------------------
Selecting 'Instance Folder' from the right-hand menu should show 'instance.cfg', 'mmc-pack.json', and 'minecraft'

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a new instance, then create and start a new world; quit the game.

2. Click the 'Instance Folder' selection from the right-hand menu.

3. Observe that there are only two files, 'instance.cfg', 'mmc-pack.json'; the 'minecraft' folder is invisible. Get Info on the instance folder indicates much more space consumed than the two files present would explain. Examining with CLI shows the invisible folder.

Suspected cause:
---------------------------
MMC 0.6.2-1163 creates the 'minecraft' folder as '.minecraft', making it invisible.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

As created:
![screen shot 2018-07-26 at 3 26 42 pm folder as created](https://user-images.githubusercontent.com/957503/43286825-bfd865c6-90e8-11e8-9403-18e88764486f.png)

Renamed:
![screen shot 2018-07-26 at 3 27 29 pm renamed folder](https://user-images.githubusercontent.com/957503/43286824-bfb882a6-90e8-11e8-90ab-1160db48b3e6.png)

Second log entry shows the anomaly:

```
MultiMC version: 0.6.2-1163


Minecraft folder is:
/Users/donellis/Applications/MultiMC.app/Contents/MacOS/instances/Is minecraft folder visible-1.13/.minecraft

...
```

Additional Info:
---------------------------
So far, I have only tested this with MC 1.13. No modpacks are available as of the last time I checked (among the ones I'm interested in).

**Comment by Janrupf** [comment]
Thats intended AFAIK

**Comment by donls** [comment]
Curious why the sudden abrupt change. Were people complaining about seeing things after clicking the 'Instance Folder' menu item? I guess this makes it more interesting, so people have to learn more about how to access the important files. Also introduces a radical difference from the way MC works.

I know my wife doesn't like the new presentation. She does a lot with the 'Instance Folder'. Now, she'll get to learn how to make the folder visible.

**Comment by peterix** [comment]
It is necessary to not break some badly written mods.

**Comment by Heufneutje** [comment]
Could we make a symlink maybe? I know symlinks don't really work on Windows, but Windows also doesn't make folders that start with a period invisible so it's not an issue there anyway.

**Comment by jikuja** [comment]
Shortcut to reveal dotted files / setting to show all files: https://ianlunn.co.uk/articles/quickly-showhide-hidden-files-mac-os-x-mavericks/

Is there really something to learn?

**Comment by peterix** [comment]
Anyway, I am not going to change this.

**Comment by donls** [comment]
So, this breaks some badly written mods? Those would break in MC without
MMC, too, right? Bummer.

I tried making a symlink, and that looks like it will work, without having
to toggle "show invisible files" system-wide.

Another path to get to the minecraft folder is to go to the config folder,
then go upward to its parent (minecraft).

**Comment by peterix** [comment]
Hmm... Let's add a direct way to open the .minecraft folder (which is probably much more useful).

**Comment by donls** [comment]
Thanks! I think there are a lot of tips pages out there telling people to
go into the minecraft folder to add/modify things. Adding direct access to
the folder would be much appreciated by those who read/write those hints.

**Comment by Heufneutje** [comment]
That's actually an even nicer solution than what I came up with 👍

**Comment by peterix** [comment]
Done.
