### ISSUE TITLE
It is possible to launch MC/FORGE server or BukkitGUI from MultiMC?

### ISSUE THREAD

**Issue by hitman60** [MultiMC/MultiMC5#2354]
This is more feature request rather then issue. Since I love MultiMC, but I prefer to run my singleplayer worlds on dedicated server from different physical HDD, with different java arguments.

**Comment by S10MC2015** [comment]
This would be such a good future but it will take a very long time to implement

**Comment by peterix** [comment]
No, and this is a duplicate of #60.
