### ISSUE TITLE
Constant crashing

### ISSUE THREAD

**Issue by S10MC2015** [MultiMC/MultiMC5#2355]
System Information
AMD A10-8700P
Integrated graphics
jre1.8.0_171
-----------------------------
MultiMC version: 0.6.2-develop-1237

Operating System: Windows 10 64 bit Ver 1803

Summary of the issue or suggestion:
----------------------------------------------
Minecraft doesn't launch

What should happen:
------------------------------
Minecraft launching

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
I don't know

Suspected cause:
---------------------------
I don't know

Logs/Screenshots:
----------------------------
https://paste.ee/p/7sJZo

This only happens with this instance and this set of mods and configs

**Comment by jikuja** [comment]
How did you create instance? Did it ever work?

**Comment by S10MC2015** [comment]
I copied another instance to make it and it never worked. Now MMC just crashes itself when I try to launch it

**Comment by S10MC2015** [comment]
![image](https://user-images.githubusercontent.com/30575036/43358592-2fb85154-928c-11e8-9ba4-70d97871067f.png)
i found it but help?

**Comment by S10MC2015** [comment]
![image](https://user-images.githubusercontent.com/30575036/43358610-5a7d755e-928c-11e8-84cf-2919aa8ecfcf.png)
rip

**Comment by S10MC2015** [comment]
I can't fix the original so i made a new instance that works

**Comment by peterix** [comment]
How was that instance created?

**Comment by peterix** [comment]
Oh. Copied. I see.

**Comment by peterix** [comment]
Should be fixed in next dev build.
