### ISSUE TITLE
Ubuntu - MultiMC won't look in hidden folders for adding mods to an instance.

### ISSUE THREAD

**Issue by shelbykauth** [MultiMC/MultiMC5#2357]
System Information
-----------------------------
MultiMC version: 0.6.2

Operating System: Ubuntu 16.04

Summary of the issue or suggestion:
----------------------------------------------
Cannot view hidden folders when in the "Select Loader Mods" dialogue box.  I need to view hidden folders because all my multimc files are in "/home/<user>/.local/share/multimc", and ".local" is a hidden folder.

What should happen:
------------------------------
Hidden folders should either be visible or be made visible by pressing ctrl-H (the ubuntu file browser way of displaying hidden folders).  Or you should be able to type in a file path, which you also cannot do.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. As far as I know, this is only on the Linux version.  But maybe I just don't encounter hidden folders that much on Windows.
2. Edit Instance
3. Add Loader Mods
4. Try to navigate to a hidden folder.

Suspected cause:
---------------------------
Oversight when making UI for less popular OS.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![image](https://user-images.githubusercontent.com/10117276/43361048-403febac-9293-11e8-9c3d-b575c2dffcd2.png)

Additional Info:
---------------------------
All of my instances and MMC settings are located in /home/<user>/.local/share/multimc
When I first started adding mods to an instance, that is where it took me.  So I made a folder called 'modRepo' inside this folder to place all my downloaded mods into, so I could always find them.
At some point, I must have added mods from another place or something.  I'm not sure.  Now I am no longer automatically in that folder.

**Comment by QuImUfu** [comment]
Just press right click and check "Show hidden files":
![showhidden](https://user-images.githubusercontent.com/9885301/43363305-2d7626f2-9302-11e8-9808-3411370ea274.png)

**Comment by shelbykauth** [comment]
You're right.  Don't know why I didn't get that.  Thanks a bunch.
