### ISSUE TITLE
Build failed at zip.cpp

### ISSUE THREAD

**Issue by ppoozl** [MultiMC/MultiMC5#2358]
System Information
-----------------------------
MultiMC version:git develop

Operating System:Windows 10.0.17134.167
Build Env: Qt 5.11.1 MSYS2 64bit
Summary of the issue or suggestion:
----------------------------------------------
Build failed at ./libraries/pack200/src/zip.cpp:347:20

What should happen:
------------------------------
Build failed. Undefined functions

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Build with MSYS2 64bit with unchanged code directly from github.

Suspected cause:
---------------------------
Undefined gmtime_r function.

Suggestion:
---------------------------
define _POSIX_THREAD_SAFE_FUNCTIONS at zip.cpp
![image](https://user-images.githubusercontent.com/7188938/43365986-38b33882-9368-11e8-9a5d-1ea27d7a6b6c.png)
msys2's time.h header
![image](https://user-images.githubusercontent.com/7188938/43366001-6f8d1594-9368-11e8-8d66-bc70f93e09a9.png)

Logs/Screenshots:
----------------------------
![image](https://user-images.githubusercontent.com/7188938/43365972-bb9dad14-9367-11e8-8d74-2293a21a4537.png)

Additional Info:
---------------------------

**Comment by ppoozl** [comment]
you can do it more carefully using
#ifndef _POSIX_THREAD_SAFE_FUNCTIONS
#define _POSIX_THREAD_SAFE_FUNCTIONS
#endif

**Comment by peterix** [comment]
The only supported Qt version on Windows is 5.6, and the only compiler I care about on Windows is the one that came with the original 5.6 install. Sorry.
