### ISSUE TITLE
MultiMC crashes while starting Minecraft

### ISSUE THREAD

**Issue by ZockerGurke** [MultiMC/MultiMC5#2360]
MultiMC version: 0.6.2-develop-1242

Minecraft folder is:
D:/Downloads/Spiele/Minecraft/MultiMC/instances/1.12.2/.minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/javaw.exe

Java is version 9.0.4, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  D:/Downloads/Spiele/Minecraft/MultiMC/instances/1.12.2/natives

Libraries:
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.1.2555/forge-1.12.2-14.23.1.2555-universal.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/jline/jline/2.13/jline-2.13.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  D:/Downloads/Spiele/Minecraft/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  InventoryTweaks-1.63
  OptiFine_1.12.2_HD_U_C5

Params:
  --username  --version MultiMC5 --gameDir D:/Downloads/Spiele/Minecraft/MultiMC/instances/1.12.2/.minecraft --assetsDir D:/Downloads/Spiele/Minecraft/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2176m, -Xmx9088m, -Duser.language=en]

Minecraft process ID: 8480

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1.

**Comment by tehbasshunter** [comment]
Use Java 8. Nothing higher is supported.

**Comment by ZockerGurke** [comment]
Thanks, helped me alot :7
