### ISSUE TITLE
multimc failed to download 1.13 files

### ISSUE THREAD

**Issue by caborra** [MultiMC/MultiMC5#2361]
In older versions like 1.12, i can download files with deleting minimum launcher version but in 1.13 there is not a minimum launcher v.

MultiMC version: 5 Modify by hackphoenix.com

Minecraft folder is:
instances/1.131/minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/java.exe

Instance update failed because: Failed to download the following files:
http://s3.amazonaws.com/Minecraft.Download/versions/1.13/1.13.jar

Reason:Job 'Libraries for instance 1.13' failed 
Please try again..

MultiMC: Log upload triggered at: 03 Aug 2018 11:04:17 +0400
 

-----------------------------
MultiMC version:5

Operating System:windows 7

----------------------------------------------

**Comment by tehbasshunter** [comment]
Get the correct version of the launcher. We don't support hacked versions.

**Comment by peterix** [comment]
This is not my problem. Stop using illegal outdated garbage.

**Comment by peterix** [comment]
You can get real MultiMC on https://multimc.org
