### ISSUE TITLE
Perhaps some SSL Libs are missing, not sure which ones.

### ISSUE THREAD

**Issue by nodey420** [MultiMC/MultiMC5#2362]
System Information
-----------------------------
MultiMC version: 0.6.2-develop-1160

Operating System: Debian Stretch

Summary of the issue or suggestion:
----------------------------------------------
Cannot "Add Instance"

What should happen:
------------------------------
Add instance.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Click Add Instance
![image](https://user-images.githubusercontent.com/42081813/43671691-b9b9bac0-976c-11e8-8045-8826bd975c58.png)

Suspected cause:
---------------------------
Missing QT SSL Library

Logs/Screenshots:
----------------------------
[MultiMC-0.log](https://github.com/MultiMC/MultiMC5/files/2259157/MultiMC-0.log)

Additional Info:
---------------------------
This sucks.

**Comment by nodey420** [comment]
btw...I checked the above link in my browser and I got a proper response back.

**Comment by nodey420** [comment]
duplicate of #2265 perhaps.

**Comment by peterix** [comment]
Yes, install `openssl1.0`.

**Comment by peterix** [comment]
Yes, we need to stop bundling Qt.
