### ISSUE TITLE
help

### ISSUE THREAD

**Issue by gitipi** [MultiMC/MultiMC5#2363]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Janrupf** [comment]
Uhm, give us information, else this is going to be closed!

**Comment by gitipi** [comment]
https://imgur.com/a/8g272re

**Comment by jikuja** [comment]
Is upload log button somehow broken or?

**Comment by S10MC2015** [comment]
Reinstall Java 8? Not much info to go off of..

**Comment by Heufneutje** [comment]
Install 64-bit Java if you had not already done that. It's complaining about a bad max memory size which typically happens when you allocate too much RAM on 32-bit Java
