### ISSUE TITLE
Can't use instance with Forge if MultiMC is in a folder with a "+" in the name

### ISSUE THREAD

**Issue by SignumEternis** [MultiMC/MultiMC5#2365]
System Information
-----------------------------
MultiMC version: 0.6.2-1222

Operating System: Windows 10 64 bit

Summary of the issue or suggestion:
----------------------------------------------
When an instance of Minecraft is created and Forge is added to it it will not start if it is in a folder that has a "+" in its name, giving critical error messages, starting with "A critical error occurred trying to read the minecraft jar file java.io.FileNotFoundException". and ending with "Process exited with code 1."

I've only tested 1.11.2 and 1.12.2, but I imagine this would happen with nearly any version of Minecraft that has Forge support.

What should happen:
------------------------------
Minecraft should start with Forge installed.

Steps to reproduce the issue:
-------------------------------------------------------------
1. Move MultiMC to a folder that has a "+" in it's name, like "M+"

2. Create an instance of Minecraft and install Forge to it through the "Edit Instance" interface

3. Try to launch it and Minecraft will refuse to start.

Suspected cause:
---------------------------
I'm not quite tech savvy enough to understand exactly why, but it seems having "+" in the folder MultiMC is in makes it read the folder name wrong and think that the Minecraft jar file isn't there, or something like that. Whether it's an issue with MultiMC, Forge, Minecraft or Java itself, I'm not really sure, but I've only had the issue while trying to make a new MultiMC instance with Forge.

Logs/Screenshots:
----------------------------
Here's the log from my most recent test confirming the issue: https://paste.ee/p/pp1eO

Additional Info:
---------------------------
I also tested with "-" and "_" in the folder name and it opens fine, so maybe it's just "+" that causes it, but I'm not going to spend all day testing different characters to see.

For now I'm just going to have MultMC in a folder with only alphanumeric characters in order to use it, so it's an easy fix, but I felt I should report this in case anyone else is having the same issue and can't figure out what's wrong.

**Comment by Heufneutje** [comment]
Yeah Java doesn't like weird characters in its classpath. I think the best we might be able to do is filter those characters out of the folder name possibly?

**Comment by peterix** [comment]
Should be fixed in dev, I added it to the blacklist.
