### ISSUE TITLE
Cant record multiMC with obs studio

### ISSUE THREAD

**Issue by TurtleForGaming** [MultiMC/MultiMC5#2366]
Will this be fixed ? Btw obs is just running no record/stream

**Comment by peterix** [comment]
And what is the actual problem? I can record with obs just fine...

**Comment by Dushess** [comment]
Probably obs catching multimc itself? Because need to operate minecraft process instead.

**Comment by TurtleForGaming** [comment]
No I can record minecraft but not the multimc launcher since I have a 64bit obs install and it only catch 64bit apps

**Comment by Heufneutje** [comment]
I do this all the time and it works perfectly fine. You're definitely capturing the wrong source. Use a Game Capture source in OBS and select the Minecraft window. Make sure you're using the latest version of OBS Studio as well to be extra sure.

**Comment by TurtleForGaming** [comment]
I DO NOT WANT to capture minecraft i want to capture the multimc launcher

**Comment by tehbasshunter** [comment]
Why would you want to capture the launcher? It has no use for recordings honestly.

**Comment by Dushess** [comment]
Btw obs is just running no record/stream
i want to capture the multimc launcher

Good luck with streaming a thing, that is not containing stream source.

**Comment by peterix** [comment]
Stream the desktop.
