### ISSUE TITLE
Ftb Beyond ne veut pas se télécharger :-(

### ISSUE THREAD

**Issue by Celcraft** [MultiMC/MultiMC5#2367]
Français :
bonjour (ou bonsoir) quand j'essaye de télécharger le modpack FTB Beyond ça me m'ai :"Impossible de télécharger la description de la version. Essayer à nouveau." J'essaye à nouveau ça me m'ai le MÊME message !!!!! Donc si quelqu'un sais comment faire j'aimerai bien qu'il me le dise.
Merci de votre compréhension.
Celcraft

English:
Hello (or good evening) when I try to download the modpack FTB Beyond it has me: "I can not download the description of the version" I try again that I got the message of EVEN !!!!! So if anyone knows how to do it I'd like him to tell me. 
Thank you for your understanding.
Celcraft

**Comment by Janrupf** [comment]
Can't reproduce this here. Could you send a screenshot of the message?

**Comment by Janrupf** [comment]
No, thats not going to work AFAIK. There is no importer for FTB packs. Correct me if I'm wrong.

**Comment by Muda42** [comment]
Because at the end modpacks are just normal minecraft instances with some more files that someone compiled to an zip file and posted it on internet

**Comment by Janrupf** [comment]
Hmm
Indeed... it is working. Because if you download the pack that way it is a curse pack. Good to know...

**Comment by Muda42** [comment]
What do you mean with an "curse" pack ???

**Comment by Muda42** [comment]
Yeah i know they aren't normal instances but i meant that all the modpacks are compiled in the same way

**Comment by Janrupf** [comment]
Yes and no. The way MultiMC gets them they are legacy FTB packs. The API differs from the website.

**Comment by Muda42** [comment]
Ok good to know

**Comment by Muda42** [comment]
But the main thing is that Celcraft makes it to install FTB Beyond

**Comment by peterix** [comment]
Hmm... seems reolved to me? And yes, you can import curse packs.
