### ISSUE TITLE
Can not install forge and stuck on getting the library files from mojang.

### ISSUE THREAD

**Issue by GenJohnWilliam** [MultiMC/MultiMC5#2372]
System Information
-----------------------------
MultiMC version: MultiMC 5 Develop

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Im trying to make a 1.12.2 mod pack or i had one and it stopped working because of forge so I deleted everything and reinstalled MultiMC but now when forge is in the version list it doesn't launch and im stuck on the "getting the library files from mojang" loading bar it just repeats a few time then crashes and the log says 

"**Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance 1.12.2' failed to process:
http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.4.2749/forge-1.12.2-14.23.4.2749-universal.jar.**"

It does this with every version of forge but the game does in fact launch when forge is not installed but what good is that when close to every mod need forge.

What should happen:
------------------------------
What should happen is the game launching with forge installed and then running so i can play some mods.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Create a instance 

2.Add forge 

3.Launch= not working 

Suspected cause:
---------------------------
I guess Systemic Mechanic its the only thing I've installed in the past month. Also maybe java i updated yesterday. 

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)I have no idea how to upload a log this link does not send me to any sort of instruction.

Additional Info:
---------------------------
it happened out of the blue I just got on and it was broken. Also i cant even download the universal forge file from the main site manually it just always fails.

**Comment by GenJohnWilliam** [comment]
well the problem is fixed close this topic or whatever

**Comment by brodycas3** [comment]
you can do that on your own

**Comment by GenJohnWilliam** [comment]
how do you do that i dont know how.

**Comment by peterix** [comment]
By pressing the close button.
