### ISSUE TITLE
1.5 showing in wrong Fliter

### ISSUE THREAD

**Issue by somedudeonmc** [MultiMC/MultiMC5#2373]
System Information
-----------------------------
MultiMC version: 0.6.2-develop-1245

Operating System: Windows 10

Summary of the issue or suggestion:
1.5 Showing in the Snapshot Fliter and not the Release Fliter
----------------------------------------------

What should happen: 1.5 should show in the Release Fliter
------------------------------

Steps to reproduce the issue (Add more if needed):
1. Click on Add Instance

2. On the List uncheck Release and check Snapshot

3.Scroll down to the Bottom and you will see 1.5 in the wrong Fliter 
-------------------------------------------------------
Suspected cause:
Placed in the wrong Fliter by the Developer
---------------------------

**Comment by peterix** [comment]
1.5 was a snapshot. Mojang says so anyway. If you think it is wrong, report it on the Mojang jira.
