### ISSUE TITLE
[Feature Request] Unified display style within the interface

### ISSUE THREAD

**Issue by WitherZuo** [MultiMC/MultiMC5#2374]
Systeminfo and Application info:
------------------------------
**MultiMC Version:**    0.6.2-devlope 1245 and previous versions
**OS:**    Windows 10 Home 1803 Build 17134.191
**Summary of the issue or suggestion:**    Please unified display style within the interface (Like "Edit Instance>World" )

**What should happen:**
------------------------------
Some UI style are different with other, like "Edit Instance>Worlds" and "Edit Instance>Resource packs", and World info show less, Except for the name and last run time, it can also display game modes or other content (like version of world, search etc.). (Sorry for my poor English)

**Some Screenshots:**
------------------------------
![respack](https://user-images.githubusercontent.com/25317916/44071958-a4e3a020-9fbe-11e8-91ae-ddad77e7ce7a.png)
![world-ui](https://user-images.githubusercontent.com/25317916/44071960-a53b7034-9fbe-11e8-969b-de5f6f581827.png)

**Comment by WitherZuo** [comment]
@peterix 
perhaps unified interface display style is a good idea...maybe...

**Comment by WitherZuo** [comment]
like this:
![multimc-uidesign1](https://user-images.githubusercontent.com/25317916/44988273-b1699800-afbc-11e8-8dec-5c98c96e0920.png)

**Comment by WitherZuo** [comment]
There should be a little separation between the contents of the list I think......so the "Severs" ui should have the same layout...yep...

**Comment by WitherZuo** [comment]
**@peterix** sorry about that...

**Comment by peterix** [comment]
I like that game mode idea. Hmmm...

**Comment by peterix** [comment]
Done.
