### ISSUE TITLE
Optifine tweaker not working

### ISSUE THREAD

**Issue by S10MC2015** [MultiMC/MultiMC5#2376]
System Information
-----------------------------
MultiMC version:0.6.2-develop-1245

Operating System: Windows 10

Summary of the issue or suggestion: Optifine instructions in the Multimc wiki doesn't work
----------------------------------------------

What should happen:
------------------------------
Minecraft loading

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
Follow instructions on the wiki (https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine)

Suspected cause:
---------------------------
OptifineTweaker not installed

Logs/Screenshots: https://paste.ee/p/PNDDU

**Comment by Janrupf** [comment]
I heard that optifine moved classes to different packages. That might be causing the issue. May you are able to find out the new class?

**Comment by S10MC2015** [comment]
I will try

**Comment by S10MC2015** [comment]
![image](https://user-images.githubusercontent.com/30575036/44235303-edb98d80-a1a0-11e8-9355-8ac59bc0e71a.png)
What

**Comment by Janrupf** [comment]
Interesting

**Comment by peterix** [comment]
Actually add the file to the correct place.

**Comment by S10MC2015** [comment]
What do you mean? @peterix

**Comment by S10MC2015** [comment]
I just tried it with 1.12.2 instructions. Again same error

**Comment by SecurityGuy05** [comment]
That's what I did. Here is the folder.
![image](https://user-images.githubusercontent.com/42500332/44302663-67fa2700-a2f3-11e8-9d26-bcfbd71700ad.png)

**Comment by SecurityGuy05** [comment]
Here's the crash report. MultiMC version: 0.6.2-1222


Minecraft folder is:
C:/Users/mhome/AppData/Roaming/MultiMC/instances/Vinilla 1.13/.minecraft


Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe


Java is version 1.8.0_172, using 64-bit architecture.


Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/mhome/AppData/Roaming/MultiMC/instances/Vinilla 1.13/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/com/mojang/brigadier/0.1.27/brigadier-0.1.27.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/com/mojang/datafixerupper/1.0.16/datafixerupper-1.0.16.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/com/mojang/realms/1.13.4/realms-1.13.4.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/optifine/preview_OptiFine/1.13_HD_U_E3_alpha8/preview_OptiFine_1.13_HD_U_E3_alpha8.jar (missing)
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/com/mojang/minecraft/1.13/minecraft-1.13-client.jar

Native libraries:
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6-natives-windows.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6-natives-windows.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6-natives-windows.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6-natives-windows.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6-natives-windows.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6-natives-windows.jar
  C:/Users/mhome/AppData/Roaming/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  1.8.9_KeystrokesMod-4.1.1
  1.8.9_Wings_Mod-1.2
  FullscreenWindowed-1.10.2-1.3.0b
  OptiFine
  Orange's+1.7+Animations-6.7
  ProjectL-0.2
  Xaeros_Minimap_1.15.3_Forge_1.8.9

Params:
  --username  --version MultiMC5 --gameDir C:/Users/mhome/AppData/Roaming/MultiMC/instances/Vinilla 1.13/.minecraft --assetsDir C:/Users/mhome/AppData/Roaming/MultiMC/assets --assetIndex 1.13 --uuid  --accessToken  --userType  --versionType release --tweakClass optifine.OptiFineTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms4096m, -Xmx4224m, -Duser.language=en]


Minecraft process ID: 3788


Using onesix launcher.

[14:33:23] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[14:33:23] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: optifine.OptiFineTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_172]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_172]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_172]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_172]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Process exited with code 1.
Clipboard copy at: 18 Aug 2018 14:33:25 -0500

**Comment by S10MC2015** [comment]
https://paste.ee/p/ldGU3 This time I put it in the right folder. Same problem

**Comment by S10MC2015** [comment]
![image](https://user-images.githubusercontent.com/30575036/44302865-811dca80-a329-11e8-8472-248d1363492c.png)
@SecurityGuy05 your file is named wrong

**Comment by S10MC2015** [comment]
but anyway mine still doesn't work even though i fixed it for my end

**Comment by peterix** [comment]
It looks like you did a bunch of things that the instructions do not say. 
1. Why is there all this other garbage in the libraries folder? Remove it all.
2. Why did you rename the optifine jar?

**Comment by S10MC2015** [comment]
![image](https://user-images.githubusercontent.com/30575036/44303213-a9f68d80-a332-11e8-9334-8137e70a20ed.png)
![image](https://user-images.githubusercontent.com/30575036/44303218-d0b4c400-a332-11e8-8b90-ef103e5fd6fd.png)
![image](https://user-images.githubusercontent.com/30575036/44303220-df9b7680-a332-11e8-964f-bcf3a1ba273b.png)
https://paste.ee/p/l9jlm
just going to say it still doesn't work

**Comment by S10MC2015** [comment]
https://youtu.be/jAvngta43To

**Comment by SecurityGuy05** [comment]
I did everything you told me to do and same problem... I wonder what is wrong?

**Comment by jikuja** [comment]
Where does the guide mention <instance folder>/.minecraft/libraries directory?

**Comment by SecurityGuy05** [comment]
its not .minecraft its for multimc
and the guild mentions it on line #7

**Comment by xjbeta** [comment]
`  C:/Users/User/Desktop/PC things/Backup/New pc stuff/Other Stuff/MultiMC/libraries/optifine/preview_OptiFine/1.13_HD_U_E3_alpha8/preview_OptiFine_1.13_HD_U_E3_alpha8.jar (missing)`
Try copy your optifine jar file to this path.
It works on my macOS.

**Comment by SecurityGuy05** [comment]
Yeah, I've tried EVERYTHING! I guess ill wait for the other "30%" on OptiFine to be worked on, so the MMC Launcher will have support for it.

**Comment by jikuja** [comment]
Works for me by following the guide.

**Comment by SecurityGuy05** [comment]
Can you make a tourtial on YouTube

**Comment by peterix** [comment]
We just need forge and it will be easy/sensible again. Hopefully.
