### ISSUE TITLE
Vanilla instances crash, exit code 255

### ISSUE THREAD

**Issue by cephlapodhours** [MultiMC/MultiMC5#2377]
System Information
-----------------------------
MultiMC version: 0.6.2-1137

Operating System: Manjaro 17.1 64-bit, Intel i3-7100, Zotac Nvidia GTX-1050, java 8

Summary of the issue or suggestion:
----------------------------------------------
Vanilla instance crashes before loading screen.

What should happen:
------------------------------
Vanilla instance should have loading screen then progress to the menu.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Start MultiMC

2. Download a Vanilla instance (any version)

3. Run the instance

Suspected cause:
--------------------------
No idea

Logs/Screenshots:
----------------------------
https://paste.ee/p/DQMkN

Additional Info:
---------------------------
This is with a fresh install of MultiMC with fresh vanilla instances. This also the first time using MultiMC on this computer. The vanilla launcher will launch and run Minecraft with no issues, and the other fixes for the crashing have been tried.

**Comment by S10MC2015** [comment]
Wrong LWGJ or driver problem?

**Comment by cephlapodhours** [comment]
Turns out computer just needed to restart after I updated it. I will close this.
