### ISSUE TITLE
MultiMC fails to extract a native jar when opening a instance

### ISSUE THREAD

**Issue by TonyMestre** [MultiMC/MultiMC5#2378]
System Information
-----------------------------
MultiMC version: 0.6.2-1222

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
When i try to open a certain modded instance, it fails (before the game window appearing)(only happens in one instance).

What should happen:
------------------------------
The game starting

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1 .Opening the instance

Suspected cause:
---------------------------
MultiMC failing to extract a jar

Logs/Screenshots:
----------------------------
https://paste.ee/p/M1pTW

Additional Info:
---------------------------

**Comment by peterix** [comment]
Well, nobody got to this in time and that log timed out.
Reopen this or create a new issue if it is still relevant.
