### ISSUE TITLE
MultiMC doesn't respect Memory checkbox in instance settings

### ISSUE THREAD

**Issue by curiosity-a** [MultiMC/MultiMC5#2381]
System Information
-----------------------------
MultiMC version: 0.6.2

Operating System: Ubuntu 18.04.1 LTS

Summary of the issue or suggestion:
----------------------------------------------
MultiMC doesn't respect Memory checkbox in instance settings

What should happen:
------------------------------
When I uncheck the Memory checkbox, I expect memory not to be specified in JVM arguments.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Make sure instance is not running.

2. Edit instace, switch to the Settings tab.

3. In settings, switch to the Java tab. Uncheck the Memory checkbox.

4. Launch instance. Observe "-Xms" and "-Xmx" arguments in log.

Suspected cause:
---------------------------
api/logic/minecraft/MinecraftInstance.cpp:300:  No check is made for the state of the checkbox.

Logs/Screenshots:
----------------------------
```
Java Arguments:
[-Xms512m, -Xmx1024m, -Duser.language=en]
```

**Comment by Heufneutje** [comment]
I'm fairly certain default arguments are passed when you don't specify them yourself. I'm not really sure what the problem is here.

**Comment by curiosity-a** [comment]
How does it imply the "passes defaults" part? We are speaking about MultiMC defaults, not JVM defaults. The box is just called "Memory". If I uncheck it, I expect MultiMC not to regulate any of the included options. Nothing in the GUI suggests otherwise.

**Comment by Heufneutje** [comment]
I feel like adding more text is just gonna confuse people that don't care (most MultiMC users)...

**Comment by Heufneutje** [comment]
I feel like this is a change that only affects people who actively read what arguments are passed to the JVM. Most users aren't going to care about this.

**Comment by curiosity-a** [comment]
Then close the issue.

**Comment by jikuja** [comment]
Do you mean it is still using instance settings instead of global setting even you turn off the setting with checkbox?

**Comment by curiosity-a** [comment]
Oh. I wasn't aware there were global settings for all instances. And those for memory don't have any checkboxes. This makes sense now, thank you.

**Comment by Dushess** [comment]
An easy option for instance. "Reset memory flags" button, it will owerwrite instance flags by multimc's default.
