### ISSUE TITLE
1.12 instance gives 1.12.* forge installation candidate

### ISSUE THREAD

**Issue by wfjsw** [MultiMC/MultiMC5#2382]
System Information
-----------------------------
MultiMC version:
0.6.2-1222
Operating System:
Windows 10
Summary of the issue or suggestion:
----------------------------------------------
1.12 instance gives 1.12.* forge installation candidate, causing game to crash.

What should happen:
------------------------------
Only 1.12 Forge should be provided.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add a 1.12 instance

2. Install Forge from "Version" Tab

3. Found 14.23.4.2758 as latest candidate instead of 14.21.1.2443

Suspected cause:
---------------------------
1.12.* contains "1.12"

Logs/Screenshots:
----------------------------
![](https://lh3.googleusercontent.com/-LfiyMREZPnk/W36rArnGksI/AAAAAAAAMl8/qNy47Blk_7Etm7ZHE_Qr5eyLb9RevPlgACHMYCw/s0/MultiMC_2018-08-23_20-39-10.png)

Additional Info:
---------------------------

**Comment by peterix** [comment]
Should be fixed in next dev build.
