### ISSUE TITLE
Build fails on Funtoo Linux

### ISSUE THREAD

**Issue by therealfarfetchd** [MultiMC/MultiMC5#2383]
System Information
-----------------------------
MultiMC version: https://github.com/MultiMC/MultiMC5/commit/a279df8bdaee22ca04073a193294fd0e6dd2a31

Operating System: Funtoo Linux (x64)

Summary of the issue or suggestion:
----------------------------------------------

Trying to build with commit https://github.com/MultiMC/MultiMC5/commit/a279df8bdaee22ca04073a193294fd0e6dd2a31 (haven't tested earlier commits) fails with an `<command-line>:0:0: error: "_FORTIFY_SOURCE" redefined [-Werror]` error.

[This patch](https://gist.github.com/therealfarfetchd/38763e9ca50089d675dff7e7e2f0693e) fixes the issue, as suggested [here](http://bicosyes.com/2012/06/building-android-error-_fortify_source-redefined-werror/) (but I have no idea if this is the correct way to fix this =P).

Logs/Screenshots:
----------------------------

Full build log (cmake and make output):
https://gist.github.com/therealfarfetchd/9729286e08b677773c66a06f4d53eb55

Additional Info:
---------------------------

gcc -v:
```
Using built-in specs.
COLLECT_GCC=/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.1/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/7.3.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc-7.3.1/configure --disable-libssp --enable-multilib --enable-version-specific-runtime-libs --enable-libmudflap --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.1 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/7.3.1 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/7.3.1/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/7.3.1/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/include/g++-v7.3.1 --enable-libstdcxx-time --enable-__cxa_atexit --enable-clocale=gnu --host=x86_64-pc-linux-gnu --with-system-zlib --enable-obsolete --disable-werror --enable-secureplt --enable-lto --without-cloog --with-bugurl=http://bugs.funtoo.org --with-pkgversion='Funtoo 7.3.1' --enable-stage1-checking=yes --enable-checking=release --enable-bootstrap --enable-shared --enable-threads=posix --enable-libgomp --build=x86_64-pc-linux-gnu --enable-libgomp --enable-languages=c,c++,fortran --disable-libgcj --disable-esp --disable-libsanitizer --disable-default-pie --enable-default-ssp --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/7.3.1/python --enable-nls --without-included-gettext
Thread model: posix
gcc version 7.3.1 20180425 (Funtoo 7.3.1)
```

cmake version 3.10.1

GNU Make 4.2.1

**Comment by temp1011** [comment]
similar to https://github.com/MultiMC/MultiMC5/issues/2350 perhaps?

**Comment by therealfarfetchd** [comment]
Yup, that looks like the same issue. Guess I'll close this then

**Comment by GuntherDW** [comment]
Funtoo is based on Gentoo (well, kinda...) and yes, it is the same issue.
I kind of got it to work by building it on Debian and then moving over the completed build and "make"'ing it again after having removed the FORTIFIED_SOURCE flag.
It does recompile a good portion of the source but it works... for now...

**Comment by GuntherDW** [comment]
Just removing the FORTIFY_SOURCE (or adding  the U_FORTIFY_SOURCE flag as is recommended on several spots on the Gentoo forums) didn't fix it for me.
As shown in my original report it errors out with a bunch of linking errors. As if cmake isn't appending the right libraries to the linking stage. I haven't looked into it *too* deeply though.

**Comment by therealfarfetchd** [comment]
Huh, weird.

**Comment by GuntherDW** [comment]
Hmm, I diff'ed the CMakeCache.txt files between the 2 versions and the only real difference that I was able to see was that 2 variables were unset by the CMake version on my Gentoo install.

```diff
@@ -586,13 +599,13 @@
 //Test COMPILER_HAS_DEPRECATED_ATTR
 COMPILER_HAS_DEPRECATED_ATTR:INTERNAL=
 //Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-COMPILER_HAS_HIDDEN_INLINE_VISIBILITY:INTERNAL=
+COMPILER_HAS_HIDDEN_INLINE_VISIBILITY:INTERNAL=1
 //Test COMPILER_HAS_HIDDEN_VISIBILITY
-COMPILER_HAS_HIDDEN_VISIBILITY:INTERNAL=
+COMPILER_HAS_HIDDEN_VISIBILITY:INTERNAL=1
 //Details about finding Java
``` 

When I manually set those to be "1" it appears to build just fine. Odd.
