### ISSUE TITLE
Dragging a mod with the same filename into the Mods screen doesn't replace the existing copy

### ISSUE THREAD

**Issue by quat1024** [MultiMC/MultiMC5#2384]
System Information
-----------------------------
MultiMC version: 0.6.2-develop-1245 on win32

Operating System: Windows 7

Summary of the issue or suggestion:
----------------------------------------------
When clicking and dragging a mod file into the Loader Mods list, when a mod already exists with the same filename, nothing happens.  

What should happen:
------------------------------
I'd love it if the newly dragged-in copy would replace the old one!

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Procure some mod jar file, and click-drag it into the Loader Mods list.

2. Change the contents of it, but give it the same name.

3. Drag the new file into the Loader Mods list.

4. Nothing happens (the old file is still in your instance folder)

Suspected cause:
---------------------------
Fairy gremlins

Logs/Screenshots:
----------------------------
Nothing out of the ordinary.

Additional Info:
---------------------------
This would be great for mod development - I manage my (outside-dev environment) test instances with MultiMC, and it would be nice to update the copy of a mod in my instance without having to `View Folder` and fiddle with files manually. The version number doesn't always change, meaning the mod's filename isn't always different.

Just a little thing.

**Comment by peterix** [comment]
Sounds bug-like to me.

**Comment by peterix** [comment]
Fixed in develop.
