### ISSUE TITLE
Pass proxy argument to Minecraft

### ISSUE THREAD

**Issue by Glease** [MultiMC/MultiMC5#2385]
System Information
-----------------------------
MultiMC version:

Any

Operating System:

Any

Summary of the issue or suggestion:
----------------------------------------------
Add the functionality of passing proxy argument to Minecraft. They are `proxyHost`, `proxyPort`, `proxyUser` and `proxyPass`. Their functionality should be self explainatory.

What should happen:
------------------------------
Minecraft session service can be proxied.

Additional Info:
---------------------------
I'm not quite sure with vanilla, but at least with forge it's possible to pass an array of argument to `net.minecraft.client.main.Main`. At L38-L41 we can see 4 argument being accepted. They are used to construct a Proxy and passed to Minecraft, and then used in session service and resource pack download(?) and some realms related stuff. **However, AFAIK, actual game play, i.e. netty connections, will still NOT be affected.**

Currently, I use a make shift solution of hardcoding the proxy detail in OneSixLauncher, and it proved to be working with my 1.12.2 instance. I don't have older server in hand and I don't like the hassle of crack opening old MCPs, so I can't trace it back to when this command line argument is added. BUT, with this [https://minecraft.gamepedia.com/Minecraft_launcher#Minecraft_Launcher](changelog) I'm certain it's there at least since December 18, 2014. I optimistically believe this can trace back to the time multiplayer is invented. Perhaps adds "We try our best to pass proxy to Minecraft" line?

I'm not really familiar with how MultiMC work (quite amazing thing actually), so this is an issue not an PR...

**Comment by spannerman79** [comment]
To add those details in for proxy etc you add them into the instance java arguments

ie: `-Dhttp.proxyHost=proxy.com  -Dhttp.proxyPort=80`

**Comment by Glease** [comment]
# Please don't refute others' claim backed by their efforts, without your own research 

Generic tutorial doesn't always applies to minecraft. I've double checked the Minecraft.java source code and it shows it will EXPLICITLY tell `URL.openConnection` to use `Proxy.NO_PROXY` if no command line argument `--proxy` is passed in, which override any global settings set via -D. Setting `-D` up only proxy a imaginary connection that you claim to exist.
