### ISSUE TITLE
Optifine HD U E3 1.13 Alpha8 runs fine, but Beta2 crashes at the start.

### ISSUE THREAD

**Issue by Ulisse54** [MultiMC/MultiMC5#2389]
System Information
-----------------------------
MultiMC version:
0.62

Operating System:
Windows 10 Home x64

Summary of the issue or suggestion:
----------------------------------------------
I referred to this guide https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine to install optifine 1.13_HD_U_E3_alpha8 in my multiMC instance. I used the first example json.
Then, I was having https://github.com/sp614x/optifine/issues/1705#issuecomment-416180681 issue (which on a note, does not occur using optifine on the official minecraft launcher) and I was recommended to update optifine to the preview released yesterday. I try to edit the JSON file but I get this log:

I also tried re-adding it through "Add Empty" but the result was the same. Rolling back to Alpha8 works fine, except for that connected textures glitch.
As my system is set to italian, I added some comments in the log to make sure no mistakes are made.

Old JSON file:

```{
    "formatVersion": 1,
    "+libraries": [
        {
            "name": "net.minecraft:launchwrapper:1.12"
        },
        {
            "name": "optifine:preview_OptiFine:1.13_HD_U_E3_alpha8",
            "MMC-hint": "local",
            "MMC-filename": "preview_OptiFine_1.13_HD_U_E3_alpha8.jar"
        }
    ],
    "+tweakers": [ "optifine.OptiFineTweaker" ],
    "fileId": "optifine.OptiFine",
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "requires": [
        {
            "uid": "net.minecraft",
            "equals": "1.13"
        }
    ],
    "name": "OptiFine",
    "version": "1.13_HD_U_E3_alpha8"
}
```

New JSON file:
```
{
    "formatVersion": 1,
    "+libraries": [
        {
            "name": "net.minecraft:launchwrapper:1.12"
        },
        {
            "name": "optifine:preview_OptiFine_1.13_HD_U_E3_beta2",
            "MMC-hint": "local",
            "MMC-filename": "preview_OptiFine_1.13_HD_U_E3_beta2.jar"
        }
    ],
    "+tweakers": [ "optifine.OptiFineTweaker" ],
    "fileId": "optifine.OptiFine",
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "requires": [
        {
            "uid": "net.minecraft",
            "equals": "1.13"
        }
    ],
    "name": "OptiFine",
    "version": "1.13_HD_U_E3_beta2"
}
```

Rolling back to Alpha8 works fine. 

What should happen: 
------------------------------
Minecraft should start as usual, using the beta2 optifine version.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Follow the steps from the guide mentioned at the start.

2. Copy/Paste the JSON file and edit the filenames accordingly

3. Start the game and watch the crash happen.

Suspected cause: 
---------------------------
Wrong JSON systax, that's all I can think of, although I did check tons of times.

Logs/Screenshots:
----------------------------
https://paste.ee/p/K92SO

Additional Info:
---------------------------

**Comment by peterix** [comment]
` C:/MultiMC/libraries/INVALID (missing)`

Yep. Fix your library name.

**Comment by peterix** [comment]
Updated the wiki with the new json:
https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine

**Comment by peterix** [comment]
Well, both should be resolved with beta3.
