### ISSUE TITLE
Copy Mods to Central Mods Folder [enhancement]

### ISSUE THREAD

**Issue by Trainguyrom** [MultiMC/MultiMC5#239]
I love the idea of a central mods folder, and I would use a lot, but I don't. When I'm downloading mods, I have them go into the Downloads folder (I'm on a PC) and I then move them into the mods folder, since that's the most logical place to put them. I would love to see a feature added which would copy/paste the mods from the mods folders of instances into the Central Mods folder with the click of a button.

Why not just manually copy the mods over and/or move them there in the first place? Well, because I'm lazy. =P  I imagine this would be a pretty easy feature to add, and I could probably even do it myself if I really wanted to, but again, I'm too lazy.

**Comment by peterix** [comment]
Not going to do this, rejected the PR and should have closed this too.

The reasoning is that it's almost always better to have your own well-maintained library of mods. If we just dump files in a folder, it will just become a mess.
