### ISSUE TITLE
Multi-Mc crash après la pression du boutons parcourir.

### ISSUE THREAD

**Issue by JulienLQ** [MultiMC/MultiMC5#2390]
Bonjour,
Sur le site le téléchargement windows affiche 32/64-bits mais le problème est que mon pc étant en 64-bits multi-mc se lance en 32 bits ce qui cause pas mal de bug.
Cerais-ce possible de me communiquer comment lancer/télécharger la version 64-bits
Merci d' avance.

**Comment by peterix** [comment]
There is no 64bit version on Windows. It is not necessary, because the 32bit version can launch both 32bit and 64bit Java.

The only reason for adding a 64bit version on Windows would be if Microsoft released a consumer version of Windows that would not be compatible with 32bit software.

**Comment by JulienLQ** [comment]
Alors pourquoi le logiciel crash t’ il constamment ?

**Comment by peterix** [comment]
You tell me.

In any case, if you have a problem with it, describe the actual problem. It needs to be properly investigated. Trying to blame it on 32bit is premature.
