### ISSUE TITLE
Can't find core mods I think

### ISSUE THREAD

**Issue by Barenger** [MultiMC/MultiMC5#2392]
It doesn't have anything to do with my mods,they ere downloaded from curse
If I have a single mod on,except for forge,Id doesn't even open the main menu of minecraft
The minecraft with forge opens,then says I need to close it and look at the latest log,here it is:
Edit:Wrong log,here is the actual log https://paste.ee/p/JxPF0
Edit:I was wrong,I think this is the main log https://paste.ee/p/iXwur

**Comment by peterix** [comment]
Please post a full log using the `Upload` button in MultiMC.

See: https://github.com/MultiMC/MultiMC5/wiki/Minecraft-Logs

**Comment by Barenger** [comment]
I edited the post so it's the actual log now,and I'm pretty sure I used the upload button on MultiMc

**Comment by peterix** [comment]
That log is not useful. Please use the main log, always.

**Comment by peterix** [comment]
`MultiMCrack` ... really?

Anyway, your problem looks like some sort of GPU driver issue.
