### ISSUE TITLE
Failed to start Minecraft with mods

### ISSUE THREAD

**Issue by andersmmg** [MultiMC/MultiMC5#2396]
System Information
-----------------------------
MultiMC version: 0.6.2 development (same problem without development version)

Operating System: Ubuntu 18.04

Summary of the issue or suggestion:
----------------------------------------------
Minecraft crashes on start before even loading anything. I tried Java 8 and 11 but no luck.
https://paste.ee/p/QcqzR

What should happen:
------------------------------
It should open Minecraft ;)

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add mods

2. Install Forge with MultiMC

3. Click Launch

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
https://paste.ee/p/QcqzR

Additional Info:
---------------------------
I have also tried launching without Forge and it works just fine.

**Comment by andersmmg** [comment]
Okay, it turns out my java version somehow upgraded to 10.0.2 without my knowledge. I'm installing Java 8 and I'll run it using that. I had no idea Minecraft needed 8 before now, it usually just worked

**Comment by jikuja** [comment]
But how did you test with java 8 like you said in first message?

**Comment by Loetkolben** [comment]
Well, does it work with Java 8? Please close the issue if that is the case.
