### ISSUE TITLE
Feature request: add option to replace real user name with something else when uploading logs.

### ISSUE THREAD

**Issue by calloatti** [MultiMC/MultiMC5#2398]
System Information
-----------------------------
MultiMC version: 0.6.2 develop 1245

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------

Add an option in Settings - Log upload to replace actual user name in log to upload with something else to avoid privacy issues.

Since it seems that some users want the actual user name in the uploaded log, and others like me do not want the real MC user name exposed to the world, make it an option.

**Comment by Janrupf** [comment]
That was a thing for a long time... The problem is that some say its bad to obfuscate the name and some would like to see it obfuscated.

**Comment by calloatti** [comment]
I know. That is why I am asking for an option. I don't want the world to know my 12 y/o son's MC user name when reporting a problem.

**Comment by spannerman79** [comment]
Unless your son has a legacy account (pre email address login) and isn't playing on pre 1.7.10 servers there shouldn't be an issue with this.

If your son does have a legacy account change it for security reasons @calloatti 

Knowing your son he has already changed his MC name a couple times already as that is what kids their age tend to do lol

**Comment by peterix** [comment]
Sounds like a useful thing.

The user name should already be censored in logs. Do you mean the 'Other Logs' page?
