### ISSUE TITLE
Solved - Only most recent version of MC will launch

### ISSUE THREAD

**Issue by Apiek** [MultiMC/MultiMC5#2400]
System Information
-----------------------------
**MultiMC version**: MultiMC 0.6.2

**Operating System**: Ubuntu 18.04 running on a GT62VR 6RE (video drivers are third party (ie NVIDIA) and up to date. Running only Java 8 (version 1.8.0_181).

Summary of the issue:
----------------------------------------------
I can create and run and instance for 1.13 (.0, .1, and/or .2) without any issues. However, when I create an instance for 1.12 or 1.10 for example, it crashes on launch.

Additional Info:
---------------------------
upload of error log from MultiMC when trying to launch a vanilla 1.10 instance: https://paste.ee/p/yZooU

Many thanks in advance

**Comment by peterix** [comment]
Mak sure you have installed java correctly. You likely have the server version only.

**Comment by Janrupf** [comment]
Thats some stupdity on Ubuntu: https://askubuntu.com/questions/695560/assistive-technology-not-found-awterror

**Comment by Apiek** [comment]
Thank you - after completed wiping all elements of java from the system and then installing version 8 (not the headless version this time....thank you!) all vanilla versions work.
