### ISSUE TITLE
Minecraft crashes as soon as I launch it in multimc with mods

### ISSUE THREAD

**Issue by tommyboy3424** [MultiMC/MultiMC5#2405]
Ok so before this started to happened it worked fine with 5 mods, now that I added more it crashes. I checked and all of these are 1.7.10 mods so I know that can't be the problem. Heres the crash log: https://pastebin.com/b8HH4fxE

**Comment by tehbasshunter** [comment]
Install 64bit version of Java.

**Comment by tommyboy3424** [comment]
it is 64 bit
![image](https://user-images.githubusercontent.com/43102301/45260325-2ae0fc00-b3aa-11e8-99be-306da615c15a.png)

**Comment by jikuja** [comment]
Did you install all mod dependencies?

**Comment by tehbasshunter** [comment]
Not according to the logs

**Comment by tommyboy3424** [comment]
this might sound stupid but whats that.

**Comment by tommyboy3424** [comment]
Heres a new log with 64-bit version of java installed it stills crashes: https://pastebin.com/Qr2QM2j0

**Comment by peterix** [comment]
That means that when you install mods, you also need to install other things they need.

**Comment by tehbasshunter** [comment]
As jikuja asked about dependencies you have forgotten that.  
  
Install ChickenCodeCore and it SHOULD work.

**Comment by tommyboy3424** [comment]
Thank you so much this shouldn't have been an issue in the first place,
