### ISSUE TITLE
Crashing while loading Space Astronomy 2

### ISSUE THREAD

**Issue by julioplayz** [MultiMC/MultiMC5#2407]
System Information
-----------------------------
MultiMC version: 0.6.2-develop-1245

Operating System: Windows 10 Home

Summary of the issue or suggestion: 
----------------------------------------------
Crashing while trying to load a modpack Space Astronomy 2, crashing while loading

What should happen:
------------------------------
The modpack loads as normal

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Copy files from twitch

2. Run

3.

Suspected cause:
---------------------------
Modpack outdated or causing issues

Logs/Screenshots:
----------------------------
https://paste.ee/p/XNuYB

Additional Info:
---------------------------
It successfully ran once, then never again

**Comment by QuImUfu** [comment]
java.lang.OutOfMemoryError: GC overhead limit exceeded

=> give Minecraft more memory, try tweaking you GC settings and make sure you PC has enough free memory (eg. nothing is running in background).
```
-XX:+UseStringDeduplication -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions
```
as java arguments helps a bit reducing memory usage.
