### ISSUE TITLE
Feature request: Allow configuration of window position of Minecraft 

### ISSUE THREAD

**Issue by pinter-gabor-at** [MultiMC/MultiMC5#2409]
![image](https://user-images.githubusercontent.com/6544011/45412101-2d777600-b676-11e8-9f08-a36d4892ae00.png)
Can we have adjustible starting position for Minecraft window?
Other launchers have it, and I think it can be made in a very similar way to configuring initial window size.

**Comment by peterix** [comment]
What other launchers?

I see no way to do this sanely...

**Comment by pinter-gabor-at** [comment]
![image](https://user-images.githubusercontent.com/6544011/45417596-d7f59600-b682-11e8-9958-e08c840429ec.png)

**Comment by pinter-gabor-at** [comment]
You are right. I have found this feature only in FTB, and it does not work even there. I have definitely seen it in other launchers too, but I do not remember where, and it is not present in the latest versions. Apparently it become so difficult to implement that they have removed it.

**Comment by peterix** [comment]
I think there should be a way to do this... I just don't see it yet.
