### ISSUE TITLE
Minecraft 1.5.2 doesn't have sound

### ISSUE THREAD

**Issue by Teal1500** [MultiMC/MultiMC5#2410]
System Information
-----------------------------
MultiMC version: 0.6.2-1222

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Minecraft 1.5.2 doesn't have sound

What should happen: 
------------------------------
I should have sound

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch the instance

2.

3.

Suspected cause: 
---------------------------
No idea

Logs/Screenshots: 
[New Paste 1.txt](https://github.com/MultiMC/MultiMC5/files/2375628/New.Paste.1.txt)

----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info: 
---------------------------
1.13.1 has sound so i don't know why 1.5.2 doesn't.

**Comment by Teal1500** [comment]
Okay so you have to manually download the sound files because mojang doesn't include the, so i'm gonna close this now.

**Comment by peterix** [comment]
Yeah, you can grab one of those and put the contents in the resources folder(s) in the instance(s):
https://mega.nz/#F!U3owiTzK!QtYRYthO4i7Cyshf2MWmNg

**Comment by WolfyRed** [comment]
> Okay so you have to manually download the sound files because mojang doesn't include them, so i'm gonna close this now.

Okay but HOW though? HOW do you manually download the sound files?
