### ISSUE TITLE
Data pack management in instance management window

### ISSUE THREAD

**Issue by jochembroekhoff** [MultiMC/MultiMC5#2411]
It would be cool to have the option to enable and disable data packs in the instance management window, like you can do with resource packs.

However, data packs, compared to resource packs, are world-specific. I suggest that, if this were to be implemented, it is placed in the "Worlds" sub window, as a new button on the right side, like "Copy Seed".

**Comment by jochembroekhoff** [comment]
What's the reason for this issue to be closed suddenly? It does not appear that the feature has been implemented.

**Comment by phit** [comment]
all feature request issues were closed and moved to https://app.mindmup.com/map/_free/2020/01/7870d53031df11eaba96015fb85b0b73
