### ISSUE TITLE
Zombies (processes) left after closing minecraft

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [MultiMC/MultiMC5#2412]
System Information
-----------------------------

MultiMC version: 0.6.2-develop 1161 (though it has been longstanding though multiple versions)

Operating System: ubuntu 18.04

Summary of the issue or suggestion: MMC leaves zombie processes after launching and closing minecraft

What should happen: 
----------------------------------------------

Processes should be polled for their exit code after minecraft exits

Steps to reproduce the issue:
-------------------------------------------------------------
1. Start any version of minecraft
2. Wait for load to complete and close the version of MC

Suspected cause:
---------------------------

MMC either not keeping track of or not polling its children

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

![screenshot from 2018-09-20 13-40-23](https://user-images.githubusercontent.com/21071450/45816319-803ad880-bcdb-11e8-9da4-e82288425275.png)

**Comment by peterix** [comment]
Should be fixed in develop.
