### ISSUE TITLE
1.13 wont launch 

### ISSUE THREAD

**Issue by Jayjay2103** [MultiMC/MultiMC5#2413]
My MultiMC cant launch 1.13 for some reason and I don't understand the errors as I am an idiot. It has happened every time I try to launch 1.13 in a new instance or at all
![1 13 error](https://user-images.githubusercontent.com/43504721/45921708-07679680-befe-11e8-8114-b5e9cc70d280.PNG)
. And I have not played on 1.13 on this P.C yet.
I tried making a new instance a few times to no avail.

Here is the console window text. I will also attach a few screen shots.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Caused by: joptsimple.MissingRequiredOptionsException: Missing required option(s) [accessToken, version]
	at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:426)
	at joptsimple.OptionParser.parse(OptionParser.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:69)
	... 8 more
Exiting with -1
Process exited with code -1.

thank you for trying to help me.

**Comment by peterix** [comment]
Full log please. This is not useful for any sort of investigation.

**Comment by Jayjay2103** [comment]
MultiMC version: 0.5.0-945



Minecraft folder is:

C:/Games/Minecraft/instances/1.13.1/minecraft



Java path is:

C:/ProgramData/Oracle/Java/javapath/javaw.exe



Java is version 1.8.0_121, using 64-bit architecture.



Main Class:

net.minecraft.client.main.Main


Native path:

C:/Games/Minecraft/instances/1.13.1/natives


Libraries:

C:/Games/Minecraft/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar

C:/Games/Minecraft/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar

C:/Games/Minecraft/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar

C:/Games/Minecraft/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar

C:/Games/Minecraft/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar

C:/Games/Minecraft/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar

C:/Games/Minecraft/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar

C:/Games/Minecraft/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar

C:/Games/Minecraft/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar

C:/Games/Minecraft/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar

C:/Games/Minecraft/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar

C:/Games/Minecraft/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar

C:/Games/Minecraft/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar

C:/Games/Minecraft/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar

C:/Games/Minecraft/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar

C:/Games/Minecraft/MultiMC/libraries/com/mojang/brigadier/1.0.14/brigadier-1.0.14.jar

C:/Games/Minecraft/MultiMC/libraries/com/mojang/datafixerupper/1.0.16/datafixerupper-1.0.16.jar

C:/Games/Minecraft/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar

C:/Games/Minecraft/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

C:/Games/Minecraft/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar

C:/Games/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar

C:/Games/Minecraft/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar

C:/Games/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar

C:/Games/Minecraft/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar

C:/Games/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar

C:/Games/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar

C:/Games/Minecraft/MultiMC/libraries/com/mojang/realms/1.13.8/realms-1.13.8.jar

C:/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6.jar

C:/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6.jar

C:/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6.jar

C:/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6.jar

C:/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6.jar

C:/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6.jar

C:/Games/Minecraft/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar

C:/Games/Minecraft/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar

C:/Games/Minecraft/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar

C:/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar

C:/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar

C:/Games/Minecraft/MultiMC/versions/1.13.1/1.13.1.jar

C:/Games/Minecraft/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar

C:/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-windows.jar


Params:


Window size: 854 x 480


Java Arguments:

[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump,
-Xms2012m, -Xmx6024m, -Duser.language=en]



Minecraft process ID: 8520



Using onesix launcher.


Failed to start Minecraft:

java.lang.reflect.InvocationTargetException

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

at java.lang.reflect.Method.invoke(Unknown Source)

at
org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)

at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)

at org.multimc.EntryPoint.listen(EntryPoint.java:162)

at org.multimc.EntryPoint.main(EntryPoint.java:53)

Caused by: joptsimple.MissingRequiredOptionsException: Missing required
option(s) [accessToken, version]

at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:426)

at joptsimple.OptionParser.parse(OptionParser.java:400)

at net.minecraft.client.main.Main.main(SourceFile:69)

... 8 more

Exiting with -1

Process exited with code -1.




this good?

**Comment by peterix** [comment]
Yeah. You are using an obsolete version of MultiMC. Update.

**Comment by Jayjay2103** [comment]
Oh. Thanks!

**Comment by peterix** [comment]
Assuming that fixed it, because the current version does have support for 1.13 :)
