### ISSUE TITLE
More command line parameters

### ISSUE THREAD

**Issue by RandomOofer** [MultiMC/MultiMC5#2414]
System Information
-----------------------------
MultiMC version: 0.6.2-develop-1246

Operating System: Windows 10

Summary of the issue or suggestion:
Add more command line parameters, for example:
- -I import pack (for this you can move a instance folder into MultiMC/instances)

- -S Export/Import settings as json or something else

- -U Update

- --LaunchOffline (Instance ID) (Offline name) 

- --switch-account (Username)

- More?
----------------------------------------------

How to use:
------------------------------
open the command line and type in something like: MultiMC.exe -h

Additional Info:
---------------------------
https://en.wikipedia.org/wiki/Command-line_interface#Arguments

**Comment by TopicsLP** [comment]
More:
-account mail-address
If you have (like me) multiple accounts to switch/force them.
