### ISSUE TITLE
cant launch the game (linux)

### ISSUE THREAD

**Issue by dogasezerdotpy** [MultiMC/MultiMC5#2415]
System Information
-----------------------------
MultiMC version:
MMC 1.2-1

OpenSSL version:
OpenSSL 1.0.2g

Operating System: 
Linux Mint 18.3

Summary of the issue or suggestion:
it cant use ssl to download anything on https://v1.meta.multimc.org
----------------------------------------------

What should happen:
it should download the files with no problem
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.open MMC

2.launch the modpack

3.

Suspected cause:
it looks like an ssl issue 
---------------------------

Logs/Screenshots:
----------------------------
https://paste.ubuntu.com/p/yfZccvSVjt/

Additional Info: i repeated the fixing steps in #1784 they didnt work

**Comment by 133Seven** [comment]
Welp you fucked something up, install Gentoo, that'll fix it.

**Comment by peterix** [comment]
Wow. Gentoo? What?

You may have to re-generate the ssl cert store. At least it helped some people before.

See: http://manpages.ubuntu.com/manpages/xenial/man8/update-ca-certificates.8.html
