### ISSUE TITLE
Launching minecraft crashes on liblwjgl.so on all minecraft versions

### ISSUE THREAD

**Issue by gfokkema** [MultiMC/MultiMC5#2417]
Hello maintainers of MultiMC.
Thank you for your great work in creating MultiMC.
I've been using it to my full satisfaction for quite some time.

Unfortunately I suddenly can't launch any minecraft instance anymore.
Do you have suggestions?

System Information
-----------------------------
MultiMC version:
Version 0.6.2-custom
Git 2c03c67c36a4a093e0f28e814f0ba8ed3141875a

Operating System:
Arch Linux, 4.18.10-arch1-1-ARCH
nvidia 396.54-6

Summary of the issue or suggestion:
----------------------------------------------
All minecraft versions crash when loading liblwjgl.so or liblwjgl64.so.
Not sure why it even tries to load libljwgl.so, i'm on an amd64 install.

What should happen:
------------------------------
All minecraft versions should not crash.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install MultiMC
2. Create new minecraft instance, any version
3. Launch

Suspected cause:
---------------------------
Mismatched version of liblwjgl.so? 32 bit version instead of 64 bit version?
Unfortunately I'm not really able to pinpoint the cause :(

Logs/Screenshots:
----------------------------
https://paste.ee/p/7mv6G

Additional Info:
---------------------------
Attached logfiles of 1.13 as an example, but i've also tried 1.10 and 1.12, no mods installed.

**Comment by QuImUfu** [comment]
I think how /mnt/sda is mounted **may** be causing this issues. Could you try creating a instance folder somewhere on your main/home partition and see if the issue persists?

**Comment by gfokkema** [comment]
Hmmmm wow, that solved everything.

Turns out it was caused by the `user` mount option in /etc/fstab.
After changing the line from:
`UUID=bdc261e9-58c6-4e2e-93df-457aa3c28cd1       /mnt/sda        ext4    rw,relatime,data=ordered,user                   0 1`
To:
`UUID=bdc261e9-58c6-4e2e-93df-457aa3c28cd1       /mnt/sda        ext4    rw,relatime,data=ordered                        0 1`

After removing the flag it's working from /mnt/sda/curse as well as /mnt/curse.
Any ideas what could cause this behaviour?
