### ISSUE TITLE
MultiMC not letting me log in 

### ISSUE THREAD

**Issue by AcerArena** [MultiMC/MultiMC5#2419]
System Information
-----------------------------
MultiMC version: 5

Operating System: Windows 10

Summary of the issue or suggestion:
When trying to login with minecraft account, get message:
failed to parse authentication server response JSON response: illegal value at offset 1
----------------------------------------------

What should happen:
login works as normal
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. open accounts manager

2. attempt to login

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by spannerman79** [comment]
@AcerArena more then lilkey this was a auth issue with Mojang.
Please close/update this issue - don't leave it open and stale.
