### ISSUE TITLE
Multimc won't launch minecraft code -1. tried vanilla, same result

### ISSUE THREAD

**Issue by jackcookisfake** [MultiMC/MultiMC5#2422]
System Information
-----------------------------
OS Name	Microsoft Windows 10 Pro
Version	10.0.17134 Build 17134
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	WINDOWS-H6NLEAK
System Manufacturer	Hewlett-Packard
System Model	HP ProBook 6470b
System Type	x64-based PC
System SKU	C9E80UC#ABA
Processor	Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz, 2601 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	Hewlett-Packard 68ICE Ver. F.40, 1/31/2013
SMBIOS Version	2.7
Embedded Controller Version	66.50
BIOS Mode	Legacy
BaseBoard Manufacturer	Hewlett-Packard
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Mobile
Secure Boot State	Unsupported
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.17134.285"
User Name	WINDOWS-H6NLEAK\Alaric
Time Zone	Mountain Daylight Time
Installed Physical Memory (RAM)	8.00 GB
Total Physical Memory	7.88 GB
Available Physical Memory	192 MB
Total Virtual Memory	22.4 GB
Available Virtual Memory	11.6 GB
Page File Space	14.5 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Device Encryption Support	Reasons for failed automatic device encryption: PCR7 binding is not supported, Hardware Security Test Interface failed and device is not InstantGo, Un-allowed DMA capable bus/device(s) detected, TPM is not usable
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	No
Hyper-V - Data Execution Protection	Yes

MultiMC version: 0.6.2 

Operating System: Microsoft Windows 10 Pro

Summary of the issue or suggestion:
I downloaded MultiMC to play Sevtech ages, which would not launch. When i tried to launched, i noticed that it said my version of java did not align with my computer architecture and I might want to download 64-bit, which I did. Upon launching, that message is gone, but it still crashes. Tried launching vanilla, similar crash.

Logs/Screenshots:
Vanilla crash report
-----------------------
https://paste.ee/p/QfX3k
------------------------------
Sevtech ages Crash report
---------------------------------
https://paste.ee/p/YxrUo

**Comment by tehbasshunter** [comment]
Run the launcher again but hi the upload button in the top right corner of console when it crashes. Those logs mean nothing to us other than

**Comment by jackcookisfake** [comment]
Sorry, new user. 

Sevtech ages
https://paste.ee/p/YxrUo

Vanilla
https://paste.ee/p/QfX3k

**Comment by jackcookisfake** [comment]
I followed the outdated gpu idea, and the instructions on the lovely helpful page https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs
and everything launches fine now.

**Comment by peterix** [comment]
:+1:
