### ISSUE TITLE
Sevtech pack crashes while loading

### ISSUE THREAD

**Issue by jackcookisfake** [MultiMC/MultiMC5#2423]
System Information
-----------------------------
OS Name	Microsoft Windows 10 Pro
Version	10.0.17134 Build 17134
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	WINDOWS-H6NLEAK
System Manufacturer	Hewlett-Packard
System Model	HP ProBook 6470b
System Type	x64-based PC
System SKU	C9E80UC#ABA
Processor	Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz, 2601 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	Hewlett-Packard 68ICE Ver. F.40, 1/31/2013
SMBIOS Version	2.7
Embedded Controller Version	66.50
BIOS Mode	Legacy
BaseBoard Manufacturer	Hewlett-Packard
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Mobile
Secure Boot State	Unsupported
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.17134.285"
User Name	WINDOWS-H6NLEAK\Alaric
Time Zone	Mountain Daylight Time
Installed Physical Memory (RAM)	8.00 GB
Total Physical Memory	7.88 GB
Available Physical Memory	3.99 GB
Total Virtual Memory	22.4 GB
Available Virtual Memory	14.2 GB
Page File Space	14.5 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Device Encryption Support	Reasons for failed automatic device encryption: PCR7 binding is not supported, Hardware Security Test Interface failed and device is not InstantGo, Un-allowed DMA capable bus/device(s) detected, TPM is not usable
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	No
Hyper-V - Data Execution Protection	Yes

MultiMC version: 0.6.2

Operating System: Microsoft Windows 10 Pro

Summary of the issue or suggestion:
----------------------------------------------
trying to launch sevtech ages, loads and begins initializing mods, then crashes before loading finishes. 
I did have to download an older version of java to combat an outdated intel gpu.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. download multimc

2.add instance using https://minecraft.curseforge.com/projects/sevtech-ages/files/2570732/download (as directed by sevtech install page - https://sevtechages.gamepedia.com/How_to_install_Sevtech_with_Multimc)

3. download old version of java as directed from https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs

Logs/Screenshots:
----------------------------
https://paste.ee/p/9GXvP

**Comment by QuImUfu** [comment]
give minecraft more RAM, the sevtech wiki says 5GB are minimum.
