### ISSUE TITLE
Add mods by putting in URLs

### ISSUE THREAD

**Issue by superpowers04** [MultiMC/MultiMC5#2428]
Hello, Is it possible that you could make a way for a person to paste a download link for a mod and direct download the mod without having to mess around with files and stuff? thank you for your time :grinning:

**Comment by spannerman79** [comment]
Unless its hosted on curseforge CDN this will be an issue.

There are still mod devs that use their own jenkins (CI) and their own webspace (even *shudder* adfly) links and you cannot "direct download" those.

**Comment by peterix** [comment]
Sounds like an easy feature...

**Comment by peterix** [comment]
[ ] - Copy of text containing URLs into the mods list
[ ] - Drag and drop of text containing URLs into the mods list

This should likely ask what to download when there's more than one URL (URL list with checkboxes, OK, Cancel)
