### ISSUE TITLE
Crashing on Instance

### ISSUE THREAD

**Issue by ReallyGoodVibes** [MultiMC/MultiMC5#2429]
System Information
-----------------------------
MultiMC version: 0.6.2-1163

Operating System: Mac OS X Version 10.9.5

Summary of the issue or suggestion: Minecraft crashing before starting up aftering selecting mod
----------------------------------------------

What should happen: Open and run game with mods without issue
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause: Missing Files or MultiMC having issues creating them 
---------------------------

Logs/Screenshots: https://paste.ee/p/xifa4
MultiMC version: 0.6.2-1163

Minecraft folder is:
/Users/laurenjackson/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/FTB Presents Direwolf20/.minecraft

Java path is:
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java

Java is version 1.8.0_181, using 64-bit architecture.

Instance update failed because: Component metadata update task failed while downloading from remote server:
Job 'Download of meta file index.json' failed to process:
https://v1.meta.multimc.org/index.json
Job 'Download of meta file net.minecraft/1.7.10.json' failed to process:
https://v1.meta.multimc.org/net.minecraft/1.7.10.json
Job 'Download of meta file net.minecraftforge/10.13.4.1558.json' failed to process:
https://v1.meta.multimc.org/net.minecraftforge/10.13.4.1558.json.

MultiMC: Log upload triggered at: 11 Oct 2018 20:17:13 -0400
MultiMC: Log uploaded to: https://paste.ee/p/C6Vv1
Clipboard copy at: 11 Oct 2018 20:26:48 -0400

----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
You may have to update the OS.
