### ISSUE TITLE
Wrong language file!? "Deutsch" (German)

### ISSUE THREAD

**Issue by zISKo666** [MultiMC/MultiMC5#2430]
System Information
-----------------------------
MultiMC version: 5

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
I set the language of "User Interface" to my desired language "Deutsch" (German) but the UI is still in English. Other languages seamed to be working fine.

What should happen:
------------------------------
A User Interface in the language "Deutsch" German.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Just set the User Interface to the language "Deutsch".

Suspected cause:
---------------------------
The German translation file might be the English file.

Logs/Screenshots:
----------------------------
![grafik](https://user-images.githubusercontent.com/6992216/46886205-76c80a80-ce5a-11e8-9e45-f93775ab057a.png)

Additional Info:
---------------------------
If I look into the translation file with a hex editor it looks fully to English.

**Comment by Janrupf** [comment]
The translation for all languages is broken AFAIK. Thats a kind of temporary issue.

**Comment by peterix** [comment]
This was a problem in the German language file, and has been fixed.
