### ISSUE TITLE
Crashing with error 255 when using forge (Ubuntu)

### ISSUE THREAD

**Issue by TDderpy** [MultiMC/MultiMC5#2431]
Apologies for having to ask what I assume is a stupid/noobish question, but I've just spent around 2 hours searching for an answer to no avail. 
I've been trying to get modpacks working, yet every time I do it instantly crashes with error 255 (crashreport: https://paste.ee/p/HVrXo).

I've managed to narrow it down to Forge mod loader, causing the issue. And from looking around it seems to be because forge is incompatible with Java 8 but you can't get Java 7 any longer so I'm wondering what's the fix/workaround. 

Many thanks.

**Comment by Janrupf** [comment]
Its **not** incompatible with Java 8, its incompatible with **Java 10**. So you need to install Java 8 and select the version in the MultiMC settings. Or simply uninstall Java 10 and install Java 8.

**Comment by TDderpy** [comment]
> Its **not** incompatible with Java 8, its incompatible with **Java 10**. So you need to install Java 8 and select the version in the MultiMC settings. Or simply uninstall Java 10 and install Java 8.

Cheers, I'll give it a try. I only thought it was incompatible with 8 because that's what half the things I found were telling me. they might have simply been old though.

**Comment by 133Seven** [comment]
Btw, @TDderpy here's how you do this:
```
sudo apt purge jre*
sudo apt install openjdk-8-jre 
```

**Comment by TDderpy** [comment]
> Btw, @TDderpy here's how you do this:
> 
> ```
> sudo apt purge jre*
> sudo apt install openjdk-8-jre 
> ```

Thanks, man, I got it now, kinda new to Linux so still having those silly issues that normally I'd spot and fix within minutes.

**Comment by Heufneutje** [comment]
The sources that were telling you Java 8 was incompatible were probably very old cause that hasn't been the case for a long time. I'm fairly sure the last Minecraft version that was affected by that was 1.6.4.
