### ISSUE TITLE
can't log my account in my new installation

### ISSUE THREAD

**Issue by flapili** [MultiMC/MultiMC5#2434]
Hi, when i tried to add my account i have this message "Authentication server didn't specify a currently selected profile. The account exists, but likely isn't premium."
(on my old installation i was log, and i have bought minecraft in 2014 and i have skin :/ )

**Comment by peterix** [comment]
Did this get resolved?

It could just be an auth server issue.

**Comment by flapili** [comment]
no, and in the minecraft.net I would not have the game buyed ... I bought it with prepaid tickets in 2014.
The only proof I have is my skin (https://mcskinsearch.com/user/flapili), I search email or something that could help me but i thinks the email of the validation of my murchase was in the spam box...

I lost my premium account ...
Did you have idea ?

**Comment by flapili** [comment]
Hello, is not a problem with MultiMC but a problem with my account,
I sent an mail to mojang support with all my personnal information.. now I cross my fingers🤞 

Is possible to change personnal information of an account ? if not maybe I have a chance for recover my premium account

You can close my issue 😃
