### ISSUE TITLE
No .minecraft folder?

### ISSUE THREAD

**Issue by OctoPenguin** [MultiMC/MultiMC5#2435]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
What?

**Comment by OctoPenguin** [comment]
Sorry about this. I accidentally clicked 'Add Issue' then fixed the problem (which was due entirely to my own stupidity) and then forgot about me posting the issue. Sorry again 😬

**Comment by peterix** [comment]
Well, sometimes stuff happens :)

¯\\\_(ツ)\_/¯
