### ISSUE TITLE
Modded instances fail after using dev branch, loader error.

### ISSUE THREAD

**Issue by StripedMonkey** [MultiMC/MultiMC5#2441]
System Information
-----------------------------
MultiMC version:
0.6.2-1137
Operating System:
Linux (Ubuntu)
Summary of the issue or suggestion:
----------------------------------------------
I've been using the dev branch for a while, never noting any severe issues, I open it up today and see a single "NOISSUE" update and apply. After multimc restarts I hit launch on "FTB Presents Crackpack" and no dice. I get [this](https://paste.ee/p/BhpNb) as the resulting error. I tried stoneBlock 1.0.17 and still nada. Attempting a vanilla 1.12.2 works. Going to settings-> update channel and switching to stable didn't appear to solve the issue and get the same result (also trying the Stoneblock modpack instead). [here](https://paste.ee/p/547z0) Creating a new vanilla (1.13) instance worked. Creating a new 1.7.10 instance and installing forge results in an identical error as seen [here](https://paste.ee/p/2ssTz)

As I've played within the past two weeks and did not have any issues then I assume it was the recent e3ab393 that caused this one in particular, although I'm unsure as to why trying to revert to the stable version did nothing to fix the problem.

Lemme know if you need anything else from me. I'll try and figure out the exact issue if I have time.

**Comment by peterix** [comment]
You somehow installed and started using java 10:

```
Java is version 10.0.2, using 64-bit architecture.
```

This will not work. You need java 8.

**Comment by StripedMonkey** [comment]
Ok, now that has me genuinely confused, because I've done essentially nothing for the past few weeks to change the java version, especially since I didn't even realize Minecraft would run on anything other than java 8/maybe 7. Apologies, I'm not sure how it got changed.
