### ISSUE TITLE
OptiFine somehow installed as an old style jar mod crashes

### ISSUE THREAD

**Issue by Anosema** [MultiMC/MultiMC5#2444]
I've made an instance without mods in 1.13.2 and it crash with the code -1073741819 (https://paste.ee/p/ZqiEc), can you help me ?

**Comment by peterix** [comment]
This is modded. And you have installed optifine in some very weird and unsupported way.

See: https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine
