### ISSUE TITLE
MultiMC keeps crashing when trying to run SevTech

### ISSUE THREAD

**Issue by ksudavid216** [MultiMC/MultiMC5#2446]
System Information

MultiMC version:
MultiMC 5 - Version 0.6.2
Operating System:
Windows 10 64-bit
Summary of the issue or suggestion:
I am trying to switch from using the Twitch client to run Sevtech Ages on minecraft and launch it through MultiMC because I am having issues being able to run this modpack without running slowly.  Also trying to find a way for my brother to run Sevtech to play on a server with me but his computer is not as powerful as mine so it may have issues too.

What should happen:
Launch Sevtech to the select world screen

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
Unsure.  I am able to run it when I launch it through the Twitch app.

Logs/Screenshots:
https://pastebin.com/embed_js/xLrFva9e

Additional Info:
I also downloaded the FTB Presents Skyfactory 3 through the FTB Legacy screen and that didn't work as well.

**Comment by Janrupf** [comment]
Thats... interesting. There is pretty much no error that could cause the crash.

**Comment by YaourtGG** [comment]
I don't have any problem playing SevTech using MultiMC.
I'm on a Mac running latest MacOS and followed [this tutorial](https://sevtechages.gamepedia.com/How_to_install_Sevtech_with_Multimc) to install it.

**Comment by peterix** [comment]
Increase the amount of memory given to java. You will not be able to play sevtech with 1GB.
