### ISSUE TITLE
1.13 Keeps crashing

### ISSUE THREAD

**Issue by NCMS22** [MultiMC/MultiMC5#2448]
System Information
-----------------------------
MultiMC version: 0.6.2-1222

Operating System: Windows 10 pro

Summary of the issue or suggestion:
----------------------------------------------
I am able to play any version of minecraft pre 1.13, even modded, but for the past month i have frequently had the problem where i would launch an instance of 1.13 and 1.13+ and it would crash.
A friend helped me fix it 2 days ago. he had me uninstall my geforce drivers and reinstall them, which fixed the problem for the day. But now i have the issue again and i don't know why it keeps happening

What should happen:
------------------------------
Normally i didn't have a problem at all, i have more than enough ram allocated to java(12 Gb), but as mentioned above this is a recent problem.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

https://paste.ee/p/veo8C
Additional Info:
---------------------------

**Comment by Heufneutje** [comment]
It does indeed appear to be a driver issue since OpenGL doesn't seem to work.

**Comment by NCMS22** [comment]
But what i dont understand,is how its possible to have this issue every few
days? Since a friend told me the same as you,had me uninstall ,download,and
reinstall my geforce drivers. Which seemed to fix the issue for a day or
two.
And every day i check mc 1.13.1 on twitch,multimc and the default mc
launcher. Some days mc would launch on only one of them in that version.
Other days on neither.

**Comment by QuImUfu** [comment]
Maybe it has something to do with some third-party program interfering. See:  
https://bugs.mojang.com/browse/MC-134137?focusedCommentId=473457&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-473457  
List of known incompatible software:  
https://minecraftirc.net/support-articles/known-incompatible-software/

**Comment by NCMS22** [comment]
Thanks for the assist. I'll keep an eye on which programs i have open when
the crahses occur

**Comment by peterix** [comment]
Well, idk.
