### ISSUE TITLE
MultiMC gets stuck and fails when trying to download forge files

### ISSUE THREAD

**Issue by jefferyrlc** [MultiMC/MultiMC5#2449]
System Information
-----------------------------
MultiMC version: 0.6.2-1222

Operating System: Windows 7

Summary of the issue or suggestion:
----------------------------------------------
When trying to launch a new instance the launcher reports downloading librabries from mojang but then the instance crashes saying it cannot download the forge universal file

What should happen:
------------------------------
forge universal file should be downloaded and applied and the game launches

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create new 1.12.2 instance

2. Edit instance and select Version tab

3. Install forge via the button/menu

4. Attempt to start the instance

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/XE57x

Additional Info:
---------------------------

**Comment by Nicba1010** [comment]
@Janrupf I left the other issue, can I in any way add the file manually?

**Comment by Moshay08** [comment]
Same error here. Can't load up StoneBlock 1.0.26 because it can't fetch forge files.
![forge](https://user-images.githubusercontent.com/36089096/47953172-371faa80-df50-11e8-9afb-2f672155fb66.png)

**Comment by SevereOverfl0w** [comment]
I'm also having issues with 2759, I can't download manually using curl or Firefox.

**Comment by peterix** [comment]
Fixed on forge server side.
