### ISSUE TITLE
[Feature Request] Confirmation box for the Delete Group button

### ISSUE THREAD

**Issue by LO6AN** [MultiMC/MultiMC5#2452]
Upon right clicking inside of any group your confronted with two buttons very close to one another, Create instance and Delete group. Because of the fact that there is no confirm dialog for this delete group button, I've ended up deleting one of my groups while instead just trying to create a new instance.

I recommend either some kind of confirm dialog for the delete group button or to make the option only appear upon clicking a specific interface element, such as the group title or something.

**Comment by peterix** [comment]
Fixed in develop.
