### ISSUE TITLE
Libraries Problem

### ISSUE THREAD

**Issue by Vokuar** [MultiMC/MultiMC5#2453]
System Information
-----------------------------
MultiMC version: 0.6.2-1222

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Libraries wont update for forge

What should happen:
------------------------------
Minecraft should load

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch a Mod Pack Instance

Suspected cause:
---------------------------
Unknown

Logs/Screenshots:
----------------------------
https://pastebin.com/cDYmmtb5

Additional Info:
---------------------------

**Comment by makuyop** [comment]
This issue affects me too. I was trying to launch an instance with Direwolf20 1.12 and FTB Revelation on Linux. 

Here is the log : https://pastebin.com/W4e0wFMB

**Comment by NovaLynxie** [comment]
I have been getting the same error. It seems to be specifically trying to download an older/previous version of forge below the starred version for me. Yet the latest versions seem to download just fine.

**Comment by Vokuar** [comment]
ahh i had i feeling it was on forges end
