### ISSUE TITLE
Can not load instance

### ISSUE THREAD

**Issue by happytnt** [MultiMC/MultiMC5#2454]
MultiMC version: 0.6.2

Operating System: Windows 10

MultiMC version: 0.6.2-develop-1255

Logs:
Minecraft folder is:
C:/Users/ZZZ/Downloads/Games/MultiMC/instances/Space Astronomy/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_191, using 64-bit architecture.

Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance Space Astronomy' failed to process:
http://files.minecraftforge.net/maven/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar.pack.xz.

Any help?

**Comment by Janrupf** [comment]
I think thats an issue with the forge servers at the moment.

**Comment by Delwin9999** [comment]
I can directly download the files from the URL's provided but MultiMC can't.

**Comment by peterix** [comment]
Fixed on forge server side.
