### ISSUE TITLE
Minecraft 1.12.2 crashes with forge

### ISSUE THREAD

**Issue by Unusedfear** [MultiMC/MultiMC5#2457]
Used MultiMC Launcher 6.2 with forge 14.23.5.2768, crashed around 30 seconds in. Minecraft version was 1.12.2. Using Windows 10 home, version 1803
[https://pastebin.com/3aLHijZ0](url)

**Comment by tehbasshunter** [comment]
Not sure if you meant to close but use Java 8. 9 and 10 aren't support with modded.
