### ISSUE TITLE
StoneBlock Modpack Error (1.12.2)

### ISSUE THREAD

**Issue by RediGH** [MultiMC/MultiMC5#2460]
System Information
-----------------------------
MultiMC version: MultiMC 5 - Version 0.6.2-1163

Operating System: MacOS X Mojave

Summary of the issue or suggestion: It never opens/crashes.
----------------------------------------------

What should happen: The game launches and the mods load.
------------------------------

Steps to reproduce the issue (Add more if needed): 
-------------------------------------------------------------
1. Download the StoneBlock modpack on CurseForge.

2. Make the instance with the zip file. (Not the server)

3. Launch it.

Suspected cause: I do not know.
---------------------------

Logs/Screenshots: https://paste.ee/p/JiUoV

**Comment by RediGH** [comment]
It is in 1.

**Comment by tehbasshunter** [comment]
You need Java 8. Modded doesn't work with 9 or 10.

**Comment by tehbasshunter** [comment]
Also need to allocate WAY more than a gig of RAM to the pack.

**Comment by JulianWebb** [comment]
I would suggest 4-6 GB of ram for Stoneblock

**Comment by RediGH** [comment]
Okay, thanks.
