### ISSUE TITLE
Update button disables after clicking "Don't update now"

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [MultiMC/MultiMC5#2462]
System Information
-----------------------------
MultiMC version: 0.6.2

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Update button in menu bar disables after clicking don't update

What should happen:
------------------------------
It should be possible to open it again, and to update.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Change update channel to dev

2. Click the update button in menu bar

3. Click don't update now

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![screenshot-multimc-disabled-update-button](https://user-images.githubusercontent.com/18211838/48313316-b5b4c180-e5ba-11e8-8e30-1ea92406c4e8.PNG)

Additional Info:
---------------------------

**Comment by kaeptmblaubaer1000** [comment]
After restarting MultiMC I'm not able to reproduce this anymore, so there are probably more conditions than what I've written as steps to reproduce

**Comment by peterix** [comment]
Yeah... I haven't been able to reproduce this yet either.

**Comment by Heufneutje** [comment]
I've tried a number of times but it works for me too. Does this only happen when you upgrade from the stable version to the dev version?

**Comment by kaeptmblaubaer1000** [comment]
It happened only once, but that was what I tried. Restarted MultiMC and don't know how to reproduce.

**Comment by kaeptmblaubaer1000** [comment]
I had an instance running, you can see that in the screenshot above. It's not a bug.
