### ISSUE TITLE
Error code -1

### ISSUE THREAD

**Issue by zombital** [MultiMC/MultiMC5#2463]
System Information
-----------------------------
MultiMC version: 0.6.3-develop-1256

Operating System: Windows 10

Summary of the issue or suggestion: Always exits with error code -1
----------------------------------------------

What should happen: Minecraft should launch
------------------------------

Steps to reproduce the issue (Add more if needed): I dont know if its possible to reproduce this issue
----------------------------------------------------------

Suspected cause: unsure
---------------------------

Logs/Screenshots:
----------------------------
Log: https://paste.ee/p/OkEkx

Additional Info:
---------------------------

**Comment by QuImUfu** [comment]
use java 8, newer versions do not work with (modded) minecraft.
