### ISSUE TITLE
Instance does not load when Forge is running and version of MC is  lower than 1.7.10

### ISSUE THREAD

**Issue by TheGameTrain** [MultiMC/MultiMC5#2464]
System Information
-----------------------------
MultiMC version: 0.6.2-1222

Operating System: Windows 10 Home

Summary of the issue or suggestion: Minecraft 1.7.10 or lower does not load when forge is installed

----------------------------------------------

What should happen:
------------------------------
Minecraft should normally load with Forge and all my mods

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Make a new instance on 1.7.10 or lower version of MC.

2. Install ANY version of Forge onto that instance.

3. Launch instance and magic will happen in the console

Suspected cause:
---------------------------
Java 10 not cooperating with Forge

Logs/Screenshots:
----------------------------
https://pastebin.com/S9ea1Kva

Additional Info:
---------------------------
I tried the legacy java fixer. Still did not fix the issue

**Comment by peterix** [comment]
Works about as well as you could expect. That is, not at all.

Use java 8.

**Comment by peterix** [comment]
Where did you even get java 10? And why?

**Comment by TheGameTrain** [comment]
> Where did you even get java 10? And why?

Ill use Java 8, Java updated automatically
