### ISSUE TITLE
Unable to use checkbox exlude folder system when exporting pack

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MultiMC/MultiMC5#2465]
System Information
-----------------------------
MultiMC version: Dev-1260

Operating System: Windows 10 pro

Summary of the issue or suggestion:
----------------------------------------------
Unable to use checkbox folder exclusion system I fell in love with.

What should happen:
------------------------------
I should be able to prevent some files from being exported.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Use dev update branch

2. add a pack

3. try exporting and click a box

Suspected cause:
---------------------------
Unknown Been like this since 10/5/2018

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by P3rf3ctXZer0** [comment]
![2018-11-13 08_45_41-multimc 5 - version 0 6 2-develop-1260 on win32 - multimc 5](https://user-images.githubusercontent.com/10351221/48420906-0cd4a680-e721-11e8-90b3-625e7227537a.jpg)

**Comment by peterix** [comment]
I cannot replicate the issue. Can you somehow share the instance?

**Comment by P3rf3ctXZer0** [comment]
Yeah I will give you my Multi-Mc http://98.159.120.240:25590/HFS/MULTIMC.zip

**Comment by peterix** [comment]
I never managed to reproduce this problem...
