### ISSUE TITLE
Columns in Versions page seem to allow sorting while they shouldn't

### ISSUE THREAD

**Issue by africalinguist** [MultiMC/MultiMC5#2467]
System Information
-----------------------------
MultiMC version: 0.6.2-develop-1176

Operating System: Ubuntu 18.04

Summary of the issue or suggestion:
----------------------------------------------
When you click any of the buttons for sorting the list of items in the "Version" tab of the edit instance window nothing happens to the list.

What should happen:
------------------------------
It should sort the items based on name or version, depending on which button you clicked.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Select an instance

2. click "Edit Instance"

3. go to the "Version" tab

4. click either of the buttons that should sort the list

Suspected cause:
---------------------------
not sure

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![multimc sorted one way](https://user-images.githubusercontent.com/26539285/48773876-08972300-ecf7-11e8-809b-1a5aa74761a5.png)
![multimc sorted the other way](https://user-images.githubusercontent.com/26539285/48773878-08972300-ecf7-11e8-8c34-59501aaec494.png)

Additional Info:
---------------------------

**Comment by peterix** [comment]
The order is significant and affects how the game is launched. Sorting these is a potentionally destructive action if you don't remember the correct order.

Real issue is that the UI element appears to allow it.

**Comment by peterix** [comment]
Should be fixed in next dev build.
