### ISSUE TITLE
[Linux] Request: Implement a method to add terminal commands to the launch of a Minecraft instance

### ISSUE THREAD

**Issue by SteveHeist** [MultiMC/MultiMC5#2468]
System Information
-----------------------------
MultiMC version:  0.6.2-1137

Operating System: lin64 (Ubuntu 18.04 LTS)

Summary of the issue or suggestion:
----------------------------------------------
Steam, among other launchers, allows the injection of commands run from the terminal, such as GALLIUM_HUD, into the Launch Options, using syntax similar to "GALLIUM_HUD="fps" %command%". The request is that MultiMC 5's install on Linux should have the ability to call similar terminal commands for the launch of Minecraft instances.

What should happen:
------------------------------
Terminal commands should be able to be added into Launch Options somewhere. Currently even Pre-Launch options throws an error.

Additional Info:
-------------------------------------
GALLIUM_HUD is an OpenGL overlay implemented into the MESA drivers on Linux for AMD hardware, with similar options to Rivatuner Statistics Server (MSI Afterburner) on Windows, although options are selected via the command line for a single program.

**Comment by peterix** [comment]
MultiMC is not a shell, nor do I want to make it one.

Right now, you can do this by writing a wrapper script in bash (an actual shell) and make MultiMC run that. The script needs to use the first argument as the executable to run and translarently pass all remaining arguments, standard input and standard output. It should not attempt to print anything to standard output, error, or try to mess with standard input in any way.

Something like this should work:
``` bash
#/bin/bash
export GALLIUM_HUD="fps"
exec $1 "${@:2}"
```

Put it somewhere on the PATH and use it as a wrapper command.

Specifying environment variables is an interesting idea though, and having something specifically for that would make this more obvious.

**Comment by SteveHeist** [comment]
Not to sound like a total dunce, but I have copied-and-pasted that bash program as "gallium_bin.sh" into usr/local/bin, which is listed as a PATH option when I run "echo $PATH", however, MultiMC 5 doesn't find it when I give the program as a Wrapper command.

Am I misunderstanding something?

**Comment by peterix** [comment]
Is it executable?

**Comment by QuImUfu** [comment]
i use following script daily:
```
#!/bin/bash
env GALLIUM_HUD=.c120fps,cpu,VRAM-usage,GPU-load,.dframetime vblank_mode=0 $@
```
Just put it anywhere and make it executable, than add the script *with absolute path* as Wrapper command. @peterix script does not work, idk why, but this does.

**Comment by SteveHeist** [comment]
@QuImUfu That works with Vanilla, but now modpacks are throwing error 1 claiming "Error: Could not find or load main class Presents" [for FTB Hermitpack].

**Comment by QuImUfu** [comment]
FTB Hermitpack works with this script on my PCs.
Could you upload the whole minecraft log and post a link?

**Comment by QuImUfu** [comment]
remove all spaces from the instance folder name (you need to change the folder name, not the instance name) e.g. "/home/steveheist/.local/share/multimc/instances/FTB Presents HermitPack" -> "/home/steveheist/.local/share/multimc/instances/FTBPresentsHermitPack"

**Comment by SteveHeist** [comment]
That worked, thank you!

Also explains why TerraFirmaPunk worked but not Hermitpack :smiley:
