### ISSUE TITLE
Feature: NBTExplorer Support

### ISSUE THREAD

**Issue by TheTank18** [MultiMC/MultiMC5#2472]
If you could, like MCEdit, open a .dat file using NBTExplorer.

**Comment by TheTank18** [comment]
NBTExplorer is here: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac

**Comment by peterix** [comment]
Hmm... I'd probably sooner just build it right in, because MultiMC contains an NBT library. Adding some UI for it wouldn't be that hard...

**Comment by TheTank18** [comment]
Thank you.
