### ISSUE TITLE
No internet connection on anything.

### ISSUE THREAD

**Issue by lneux** [MultiMC/MultiMC5#2477]
I'm running MultiMC and it doesn't have internet connection at all, despite my laptop being connected. I'm running the Linux version (BunsenLabs/Debian), and even my terminal doesn't show logs, errors or anything... any help? 

![captura de tela_2018-11-25_21-50-31](https://user-images.githubusercontent.com/41797257/48986922-71203e80-f101-11e8-9dc7-9c1c6901bb2d.png)
![captura de tela_2018-11-25_22-25-55](https://user-images.githubusercontent.com/41797257/48986923-71203e80-f101-11e8-8429-6bea0fc55bd7.png)

**Comment by peterix** [comment]
Install the openssl 1.0 dev package.

**Comment by lneux** [comment]
> Install the openssl 1.0 dev package.

I've already installed all dependencies required to run both the oficial launcher (that also doesn't work) and MultiMC.

**Comment by peterix** [comment]
Check the `MultiMC.0.log` file for SSL errors. Ideally post it here as an attachment. MultiMC does log your e-mail when it authenticates, so make sure to censor that.

**Comment by lneux** [comment]
I would send the MMC.log for you if I had one, the launcher doesn't even generates a error log or connection error, nothing, and not even running straight from the terminal requesting an output.

**Comment by peterix** [comment]
Sorry for no response, I kinda lost track of this. Yes, you do need openssl 1.0. The dev package.

**Comment by peterix** [comment]
Resolving as fixed.
