### ISSUE TITLE
Creating new FTB Instances that use Minecraft 1.4.7 report missing libraries

### ISSUE THREAD

**Issue by ProjectSynchro** [MultiMC/MultiMC5#2478]
Fixed by creating a 'libraries' directory within the instance folder and copying the files within 'jarmods' into it.

I suggest fixing this as importing packs from the in launcher creates a broken instance by default

_Originally posted by @ProjectSynchro in https://github.com/MultiMC/MultiMC5/issue_comments#issuecomment-441506381_

**Comment by zomabies** [comment]
Can confirm.

`Version                    :  "0.6.2-develop-1268"`
`Git commit                 :  "9eb456336dc8bae2000f7d729d2d63c4a0906157"`

How to reproduce:

1. Add a jar mod via `Add to Minecraft.jar`.
2. Notice it does not read from `$instance/jarmod/`.

Note that `Replacing Minecraft.jar` is _not affected_ by it as it place the .jar on `libraries` folder.

**Comment by peterix** [comment]
Windows and 32bit linux builds will come later.

**Comment by peterix** [comment]
Fixed in develop.
