### ISSUE TITLE
mmc crashing with forge 2794

### ISSUE THREAD

**Issue by twoworlds** [MultiMC/MultiMC5#2480]
System Information
-----------------------------
MultiMC version: 0.6.2-1222

Operating System:

Windows 10 Pro 64bit

Summary of the issue or suggestion:
----------------------------------------------
With Forge 14.23.5.2794 i can't get mmc to run minecraft

What should happen:
------------------------------
minecraft should start 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. install Forge 2794

2. start profile

3. system crashes with error

Suspected cause:
---------------------------
Forge ?

Logs/Screenshots:
----------------------------
https://pastebin.com/8Fsi0TFN

Additional Info:
---------------------------
Switching back to older version (2780) minecraft startsjust fine.

**Comment by QuImUfu** [comment]
forwarded issue to https://github.com/sp614x/optifine/issues/2068 as it is an incompatibility between forge >=2794 and OptiFine.
