### ISSUE TITLE
Instance libraries are mistaken as jarmods

### ISSUE THREAD

**Issue by zomabies** [MultiMC/MultiMC5#2483]
MultiMC version: 0.6.2-develop-1269

Steps to reproduce
-----------------------
1. Follow the instructions : https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine
2. Hit `launch` on the instance menu or double click on the instance.
3. Fails to launch.

Logs
---------
With `libraries` folder

    Instance update failed because: Some artifacts marked as 'local' are missing their files:
    ./instances/$INSTANCE/jarmods/OptiFine_1.12.2_HD_U_E2.jar
    
Without `libraries` folder

    Instance update failed because: Some artifacts marked as 'local' are missing their files:
    ./instances/$INSTANCE/libraries/OptiFine_1.12.2_HD_U_E2.jar

------
`Launch Offline` does not trigger this issuse.

**Comment by peterix** [comment]
In both cases, you are missing the optifine jar.

**Comment by peterix** [comment]
It should be consistent about telling you what you are missing now... But still, you should just put it where it belongs.

**Comment by zomabies** [comment]
Thank you for fixing this issue.
