### ISSUE TITLE
German translations don't load

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [MultiMC/MultiMC5#2484]
System Information
-----------------------------
MultiMC version: latest develop

Operating System: Windows 10 1803

Summary of the issue or suggestion:
----------------------------------------------
German translations don't load, everything is still English

What should happen:
------------------------------
Some strings are German

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Update to develop

2. Change to German

3. Restart MultiMC

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
Fixed
