### ISSUE TITLE
The onesix lancher crashes while initializing.

### ISSUE THREAD

**Issue by CodeProgrammer0** [MultiMC/MultiMC5#2486]
I am just starting programming and I think your onesix launcher is bugged. I am new to GitHub so I hope I did this right. Here is the log (I do not know how to upload). https://paste.ee/p/k9Itq

**Comment by tehbasshunter** [comment]
It's not bugged. You're using Java 10 which isn't supported with MMC at the moment. Only 8 and below.

**Comment by CodeProgrammer0** [comment]
Oh sorry, thank you, I only work with Python at the moment.
