### ISSUE TITLE
[Feature Request] Option for making deleting harder

### ISSUE THREAD

**Issue by rpav** [MultiMC/MultiMC5#2487]
System Information
-----------------------------
MultiMC version: 0.6.2 (release)

Operating System: Windows

Summary of the issue or suggestion:
----------------------------------------------
It's rather unfortunately easy to delete instances.  Press delete and enter.  For instance, if one were to, say, accidentally upset a keyboard, flipping it over, and the numpad gets mashed, one could *surprisingly* easily delete an instance and lose many hours of play.

What should happen:
------------------------------
If nothing else, "Yes" should not be the default option for delete. Preferably, one should have to do something like type the instance name before deleting.  There could be a settings option to enable/disable easy deleting.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
NOT RECOMMENDED:
1. Highlight an instance
2. Mash the numpad such that you hit "delete" then "enter" in quick succession
3. Loss

## Additional Info

It's actually surprisingly easy to make backups using `xcopy` (and presumably just `cp` on linux) using pre/post commands.  If there were something like `INST_RUN_CYCLE` which provided a cycling `0, 1, 2, ... n`, it'd even be trivial to make proper rolling backups.  I think this is possible using `rsync`, but that would require a separate download.

*In any case*, it might be useful if there was an easy way to populate backup commands for the current OS as well.

**Comment by Lonami** [comment]
This can be closed now that it's fixed, right?

**Comment by peterix** [comment]
Sounds like it, yeah.
