### ISSUE TITLE
Relative URLs are not properly handled during redirection

### ISSUE THREAD

**Issue by AstralSorcerer** [MultiMC/MultiMC5#2488]
System Information
-----------------------------
MultiMC version: 0.6.2-1137

Operating System: Arch Linux on x86_64

Summary of the issue or suggestion:
----------------------------------------------
When following a redirect during library downloading, MultiMC will fail to download the library if the redirect is a relative URL.

What should happen:
------------------------------
MultiMC should follow the redirect and successfully download the library.

Steps to reproduce the issue:
-------------------------------------------------------------
1. Add a new patch to an instance. The patch must specify a library that will redirect during downloading, and the HTTP location header for this redirect must specify a relative URL. For instance,
```
"+libraries": [
    {
        "name": "com.github.Chocohead:Rift:jitpack-SNAPSHOT",
        "url": "https://www.jitpack.io/"
    },
]
```

2. Instruct MultiMC to download the instance's libraries by clicking the "Download All" button in the Edit Instance window.

Suspected cause:
---------------------------
[api/logic/net/Download.cpp](https://github.com/MultiMC/MultiMC5/blob/075e173fbd90292706d4033fcb965a4e48b2da6f/api/logic/net/Download.cpp) treats relative URLs as absolute URLs. See [Download::handleRedirect](https://github.com/MultiMC/MultiMC5/blob/075e173fbd90292706d4033fcb965a4e48b2da6f/api/logic/net/Download.cpp#L151-L201).

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/RCLx2 (Note: personally identifying information has been redacted to the best of my ability)

**Comment by peterix** [comment]
That's ... remarkable. Someone managed to convince people that they should use this convenient MITM proxy as part of their build chain?

The only question I have is: who is the target? Not whether this is malicious. The potential for malice is so high that it must be there even if unintended.

You are passing source code through a black box that is not under your control and under no supervision, and using the results of that. WOW

**Comment by peterix** [comment]
The redirect thing needs investigation tho.

**Comment by peterix** [comment]
See: https://bugreports.qt.io/browse/QTBUG-41061

This is yet more issues caused by this Qt bug.

**Comment by peterix** [comment]
Anyway, worked around in develop...
