### ISSUE TITLE
I hava issue #7220

### ISSUE THREAD

**Issue by Ducky1434** [MultiMC/MultiMC5#2489]
Hello i was trying to make my brother a modded minecraft world and then this appeared in the console pastebin.com/ZC2txLJp. Please help.

Sorry for my bad english.

**Comment by peterix** [comment]
Use 64bit Java.
You can get it here: https://javadl.oracle.com/webapps/download/AutoDL?BundleId=235727_2787e4a523244c269598db4e85c51e0c

**Comment by Ducky1434** [comment]
Hello! I deleted the old java and then installed the java from the link you gave me and then it crashed again.
Here is the console log:https://pastebin.com/qrF9KFWm

**Comment by Janrupf** [comment]
Techguns seems to be bugged, update the mod if possible or delete it.
