### ISSUE TITLE
Is it possible to assign an account to an instance?

### ISSUE THREAD

**Issue by NoVTeKa** [MultiMC/MultiMC5#2493]
I might be breaking rules here but I couldn't find anywhere how I could assign an account to an instance so I can have multiple accounts running on the same server. Sorry!

Edit : I found how to use different accounts but I'd still like to know if it's possible to assign a specific account ( I have 4 ) to a specific instance to make it easier to load them all

**Comment by tehbasshunter** [comment]
Not possible. You can add multiple accounts to MMC but not tie them to individual instances.

**Comment by NoVTeKa** [comment]
Alright! Thanks for responding!
