### ISSUE TITLE
Process exited with code -1?

### ISSUE THREAD

**Issue by NoVTeKa** [MultiMC/MultiMC5#2494]
System Information
-----------------------------
GTX 1060 6GB SC
Intel core i5 - 4440
random ram stick
MultiMC version: 0.6.2

Operating System: Windows 10 home

Summary of the issue or suggestion:
----------------------------------------------
I start up an instance using MultiMC, Join a server on my own solo map and games crashes giving code -1 and AL lib: (EE) alc_cleanup: 1 device not closed
What should happen:
------------------------------
Not crash I guess

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open up MultiMC

2. Make a 1.12.1 Instance

3. Start it up and join a server or world

4. Crash?

Suspected cause:
---------------------------
I have no idea 

Logs/Screenshots:
----------------------------
https://paste.ee/p/9bif7
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by tehbasshunter** [comment]
You need to install 64 bit java and give it a bit more allocated RAM if you want it to run.  
  
https://java.com/en/download/manual.jsp

**Comment by NoVTeKa** [comment]
This seems to have fixed the issue! Thanks!
