### ISSUE TITLE
Couldn't extract native jar

### ISSUE THREAD

**Issue by diamantico21** [MultiMC/MultiMC5#2495]
System Information
-----------------------------
MultiMC version: 0.6.2 - 12222

Operating System: Win10

Summary of the issue or suggestion:
----------------------------------------------
Opening any Enigmatica 2 modpack makes the log appear with the "Couldn't extract native jar..." error.

What should happen:
------------------------------
It should be booting the modpack

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Make something happen (?)
Just happened randomly after minecraft crashed

Suspected cause:
---------------------------
Minecraft crash (?)
Java (?)

Logs/Screenshots:
----------------------------
https://paste.ee/p/Xw3VU

Additional Info:
---------------------------
Happens to every Enigmatica 2 modpack - changing modpack versions doesn't help. But I can open other modpacks - even with the same minecraft version.

**Comment by peterix** [comment]
What happens when there isn't a `+` in the instance name/folder name?
