### ISSUE TITLE
Error: Could not find or load main class org.multimc.EntryPoint (Closed)

### ISSUE THREAD

**Issue by Ssmidge** [MultiMC/MultiMC5#2496]
System Information
-----------------------------
MultiMC version: 0.6.2

Operating System:Windows 10 pro 64 bit

Summary of the issue or suggestion:
----------------------------------------------

When I tried to start an Instance is keeps crashing with the following error:
Error: Could not find or load main class org.multimc.EntryPoint
Process exited with code 1.

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Try to start Minecraft

2.

3.

Suspected cause:
---------------------------
I have no idea

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

URL https://pastebin.com/Bquu6929 

Additional Info:
---------------------------

**Comment by adrian19734682** [comment]
Ok i will try it

**Comment by adrian19734682** [comment]
I tried it and it works thanks.

**Comment by jake21212** [comment]
I have tried everything doesn't work

**Comment by tehbasshunter** [comment]
Don't post a message on a 8 month old issue that's apparently been solved with no context.

Make your own new issue.
