### ISSUE TITLE
Minecraft doesn't open 

### ISSUE THREAD

**Issue by TonyMestre** [MultiMC/MultiMC5#2497]
System Information
-----------------------------
MultiMC version:
0.6.2
Operating System:
Windows 10
Summary of the issue or suggestion:
----------------------------------------------
When using the Forge version 14.23.5.2781(because latest Astral Sorcery version needs it) and clicking on Launch, the icon that indicates when the instance is been played appears, but Minecraft doesn't opens
What should happen:
------------------------------
Minecraft opening

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Launching the instance

2.

3.

Suspected cause:
---------------------------
Forge version 14.23.5.2781
Logs/Screenshots:
----------------------------
https://paste.ee/p/pmWhP
Additional Info:
---------------------------

**Comment by TonyMestre** [comment]
Ok, so which mod?

**Comment by TonyMestre** [comment]
So, which mod caused this?

**Comment by peterix** [comment]
No idea.
Try downgrading forge.

**Comment by peterix** [comment]
Or updating optifine.
