### ISSUE TITLE
Error Code -1073740791 Soon After Loading a World

### ISSUE THREAD

**Issue by Flarpyz** [MultiMC/MultiMC5#2502]
System Information
-----------------------------
MultiMC version:
0.6.3-develop-1286

Operating System:
Windows 10 Pro

Summary of the issue or suggestion
----------------------------------------------
Essentially, when I boot Minecraft 1.13.2, I will load up a world, and then 30 seconds later it will just crash with error code: -1073740791

What should happen:
------------------------------
The game should boot into the world with no problems. My PC usually maintains 60+ FPS even when loading into a world and loading chunks

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch Game

2. Go to Single player and select a world.

3. Wait for a little bit and the game will crash

Suspected cause:
---------------------------
Most likely a driver issue, although Nvidia says my GT 1030 has the latest drivers.

Logs/Screenshots:
----------------------------
https://paste.ee/p/twNxE

Additional Info:
---------------------------
Before this started happening my performance in-game was deteriorating. Also, this happens in every world I've tested, including brand new worlds.

**Comment by QuImUfu** [comment]
looks like https://bugs.mojang.com/browse/MC-112780

**Comment by peterix** [comment]
Maybe? It could be something else.
