### ISSUE TITLE
Minecraft Modded crash (1.7,10) on launch

### ISSUE THREAD

**Issue by Klurby** [MultiMC/MultiMC5#2504]
Please help.  I have asked and asked on forums with no answers or even replies.  I have zero idea what the log errors out on.  My best guesses and troubleshoots lead to no results.  I looked all over the internet for any fix but none that are presented work.
I installed forge/liteloader directly from the MultiMC client.
I have tried:
- Switching forge versions
- Switching install path
- Switching java path/updating java
- Checked all mod versions/compatibility
This is my first time using MultiMC, I have been playing minecraft for years and havent encountered any log that looks anything like this.
Log: https://paste.ee/p/lsasZ
Thank you for your time.

**Comment by peterix** [comment]
It is missing codechickencore.

**Comment by Klurby** [comment]
> It is missing codechickencore.

Must of deleted it troubleshooting.  I added that and it is still errors out on startup
Updated log - https://paste.ee/p/HnbIt

**Comment by peterix** [comment]
See: https://github.com/MultiMC/MultiMC5/issues/1377
