### ISSUE TITLE
Modpack suddenly isn't working anymore!

### ISSUE THREAD

**Issue by RishiAmador** [MultiMC/MultiMC5#2507]
System Information
-----------------------------
MultiMC version: Version 0.6.4-1291

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Two days ago, I was playing on the modpack just fine. Then, the next day, I tried to play it again, without making any changes or any updates, and it won't start anymore! I get to the forge screen, it builds the mod, but it doesn't even get past initializing phase 1! I have no idea what went wrong.
I even tried to run an older version of this modpack, a version I haven't touched or changed in months, and that one wasn't working either! With that in mind, I think it's a MultiMC issue.

What should happen:
------------------------------
The modpack normally opened and played like normal, but then for some reason it stopped running past the forge hammer-anvil screen.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Load all of the mods I have on to a 1.7.10 instance

2. Wait a few seconds

3.

Suspected cause:
---------------------------
I think this may be an issue with MultiMC, but I'm honestly not sure. I suspect it may be a Java issue, but I have no idea how to check.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

https://paste.ee/p/wGRmM

Additional Info:
---------------------------
You look lovely today.

**Comment by QuImUfu** [comment]
the peacefulpack mod update site is not working/available any more. Disable peacefulpack mod updates in the config.
