### ISSUE TITLE
I Can No Longer Open Any Modpacks

### ISSUE THREAD

**Issue by Dreamnoble** [MultiMC/MultiMC5#2509]
System Information
-----------------------------
MultiMC version: Version 0.6.4- 1291 on win32

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
I recently updated Java to what I believe is the newest version. Every time I try to open my modpack, an error appears saying:

Error: Could not create the Java Virtual Machine
Error: A fatal exception has occurred. Program will exit.

What should happen:
------------------------------
It should open the game.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Tried opening the modpack several times. Got the same result.

Suspected cause:
---------------------------
The java version I downloaded is definitely the issue, but I'm not sure how to fix it.

Logs/Screenshots:
The log isn't as long as some of the others I've seen on this site, I swear.

MultiMC version: 0.6.4-1291

Minecraft folder is:
C:/Users/EZ Pawn/Desktop/MultiMC/instances/1.12.21/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_191, using 32-bit architecture.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/EZ Pawn/Desktop/MultiMC/instances/1.12.21/natives

Libraries:
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2768/forge-1.12.2-14.23.5.2768-universal.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/EZ Pawn/Desktop/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  Age+of+Weapons+1.12.2++(v.0.13.5)
  animania-1.12.2-1.5.1.1
  Backpacks-Mod-by-Brad16840-1.11.2
  chiselsandbits-14.17
  CraftStudio-1.0.0.93-mc1.12-alpha (2)
  Decocraft-2.6.2_1.12.2
  DragonMounts-1.12.2-1.5.0
  DrZharks MoCreatures Mod-12.0.1
  Fairy-Lights-Mod-1.12
  iceandfire-1.5.2 (1)
  iChuns-Hats-Mod-1.12.2
  iChunUtil-1.12.2-7.1.4 (1)
  Improved-Backpacks-Mod-1.12.2
  jei_1.12.2-4.10.0.200 (1)
  justcoins_1.12.2-1.2.1
  llibrary-1.7.15-1.12.2
  LootBags-1.12.2-2.5.6
  Mantle-1.12-1.3.2.24 (1)
  MCA-1.12.x-5.3.1-universal (1)
  OptiFine_1.12.2_HD_U_D1
  PTRLib-1.0.3
  RadixCore-1.12.x-2.2.1-universal (1)
  RoguelikeDungeons-1.12.2-1.8.0 (1)
  rustic-1.0.6
  shetiphiancore-1.12.0-3.5.7 (1)
  Tails-1.12-1.10.0 (1)
  TConstruct-1.12.2-2.10.1.87 (1)
  terraqueous-1.12.0-1.4.12
  TreeChopper-1.12.2-1.2.4
  Waystones_1.12.2-4.0.67
  wearables-1.1.3
  worldedit-forge-mc1.12-6.1.8-dist

Params:
  --username  --version MultiMC5 --gameDir C:/Users/EZ Pawn/Desktop/MultiMC/instances/1.12.21/.minecraft --assetsDir C:/Users/EZ Pawn/Desktop/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2048m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 7228

Invalid maximum heap size: -Xmx4096m
The specified size exceeds the maximum representable size.
Process exited with code 1.

----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
I'm not at all educated in how Java works, so please bear with me.

**Comment by peterix** [comment]
telling 32bit Java to use 2-4GB of memory will not work.

Please use 64bit Java:
https://javadl.oracle.com/webapps/download/AutoDL?BundleId=235727_2787e4a523244c269598db4e85c51e0c

**Comment by Dreamnoble** [comment]
I just installed the wrong java version at first, sorry for wasting anyone's time! I've fixed the problem now!

**Comment by peterix** [comment]
Alright :)
