### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by NoCryTM** [MultiMC/MultiMC5#2510]
System Information
-----------------------------
MultiMC version: 0.6.2

Operating System: Windows 10 64Bits

Summary of the issue or suggestion: Esta dando erro ao tentar abrir/instalar o erro seria 
----------------------------------------------

What should happen: -x-
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. MultiMC couldn't create a log file - the multiMC data folder is not writable.

Make sure you have write permissions to the MultiMC data folder.

MultiMC cannot continue until you fix this problem.
----------------------------------------------

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots: https://imgur.com/EPl0EM8
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Heufneutje** [comment]
You probably either didn't extract the zip file or you dropped MultiMC somewhere it doesn't belong. Do not put it in Program Files for example.

**Comment by peterix** [comment]
![image](https://user-images.githubusercontent.com/203326/51124774-6d668980-181f-11e9-8a35-0488af8b849c.png)

**Comment by peterix** [comment]
Where did you place MultiMC?

**Comment by NoCryTM** [comment]
Na área de trabalho (On the desktop)

Em seg, 14 de jan de 2019 12:12, Petr Mrázek <notifications@github.com
escreveu:
