### ISSUE TITLE
Minecraft wont launch, process exited with code -1

### ISSUE THREAD

**Issue by StevenStoner69** [MultiMC/MultiMC5#2512]
System Information
-----------------------------
MultiMC version: 0.6.5

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
I need to use the world downloader mod to download my server.  I followed the steps on the mod site, clicked on the instance, but Minecraft won't launch.  I looked at other threads on here; I even tried downloading a different version of Java (the one recommended in the threads, jre-8u51), but no dice.

What should happen:
------------------------------
Minecraft should launch through MultiMC.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------
I have no idea.

Logs/Screenshots:
----------------------------
MultiMC version: 0.6.5-develop-1295

Minecraft folder is:
C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/instances/1.9_WDL/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_201/bin/javaw.exe

Java is version 1.8.0_201, using 64-bit architecture.

Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/instances/1.9_WDL/natives

Libraries:
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/1.5.22/authlib-1.5.22.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/com/mojang/realms/1.8.7/realms-1.8.7.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/instances/1.9_WDL/.minecraft/bin/minecraft.jar

Native libraries:
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Jar Mods:
  mod-worlddownloader-baseedit-4.0.4.0-mc1.13.2 (865db6fb-3160-484a-a2d0-df886fef7121.jar)

Params:
  --username  --version MultiMC5 --gameDir C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/instances/1.9_WDL/.minecraft --assetsDir C:/Users/Duane/Documents/mmc-stable-win32/MultiMC/assets --assetIndex 1.9 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 11252

Using onesix launcher.

[16:01:20] [Client thread/INFO]: Setting user: BasileGiroux
[16:01:20] [Client thread/INFO]: (Session ID is token:<ACCESS TOKEN>:<PROFILE ID>)
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at ado.t(SourceFile:888)
	at kn.c(SourceFile:509)
	at bcf.<init>(SourceFile:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	... 8 more
Exiting with -1
Process exited with code -1.
Clipboard copy at: 17 Jan 2019 16:01:23 -0500
Clipboard copy at: 17 Jan 2019 16:01:24 -0500

Additional Info:
---------------------------
Sorry if I'm doing this wrong!  I'm not used to using this site.

**Comment by QuImUfu** [comment]
To clarify what @BoomerangHunter said:  
You are (most likely) trying to use mod-worlddownloader-baseedit-4.0.4.0-mc1.13.2 which is for minecraft version 1.13.2 on minecraft version 1.9.  
This is not going to work.  
To fix it either download and install the 1.9 version from https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.0.4.0
or (probably what you want)  
change the minecraft version to 1.13.2 (click "Edit Instance" -> click  "Version" -> select the "Minecraft" entry -> click "Change Version" -> select "1.13.2")

**Comment by StevenStoner69** [comment]
Ohhh ok I'll try that!  Thank you!

**Comment by StevenStoner69** [comment]
It worked!
