### ISSUE TITLE
Marking last good mod setup, comparing to current

### ISSUE THREAD

**Issue by PikerZ** [MultiMC/MultiMC5#2514]
A log or textfile that remembers what mods were used/present in the mods folder last time the instance succesfully loaded.
This could be useful for creators of modpacks or people who just want to get their instance working by giving them a small headstart on what the problem could have been :3!

**Comment by andersmmg** [comment]
This would be awesome, and it would be nice to have a button to launch the last working config on the error log window as well

**Comment by peterix** [comment]
So, here's how you can do it right now

Use git

In the instance:
```
git init
git add *
git commit -a -m "Working state"
```

Then later, you can always return to the working state, and you can always compare the current with what worked.
