### ISSUE TITLE
OneSix launcher error, java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by RedstoneMaster256** [MultiMC/MultiMC5#2516]
System Information
-----------------------------
MultiMC version: 0.6.4-1291 on win32

Operating System: Windows 10 Home 64-bit

Summary of the issue or suggestion:
----------------------------------------------

The game does not start; it errors after a few seconds, exiting the OneSix launcher with -1 and giving a process code of 1. 

What should happen:
------------------------------
Minecraft loads, at least opening a window

Steps to reproduce the issue (Add more if needed):
------------------------------------------------------------
Unknown, I cannot reproduce this issue on my Windows 8.1 laptop

Suspected cause:
---------------------------
Unknown, perhaps related to something in Windows 10

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/wd83a

Additional Info:
---------------------------
Java versions I've had the issue on:
JRE 8u191
JDK 8u201
Forge versions I've had the issue on:
14.23.5.2764
14.23.5.2768
I am not using integrated graphics; My graphics card is a Radeon RX550 series

MultiMC is not on the same drive as Windows or Java. Windows and Java are on my SSD, whereas MultiMC is on my HDD

**Comment by RedstoneMaster256** [comment]
I tracked down the issue, it seems to be an incompatibility with the OneSix launcher and the mod Obfuscate, which is the coremod for MrCrayfish's Gun Mod. This conflict only exists on Windows 10.

**Comment by peterix** [comment]
Therefore it's a mod bug.
