### ISSUE TITLE
Minecraft closes (not crashes, closes) when i press 'esc'

### ISSUE THREAD

**Issue by Mysticalii** [MultiMC/MultiMC5#2517]
System Information
-----------------------------
MultiMC version: 0.6.2

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Basically I start up minecraft and it doesn't matter what I do, if i click 'esc' my game closes. Keyword being closes not crash.

What should happen:
------------------------------
It should just open up the menu instead of closing minecraft

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open minecraft

2. Press 'esc'

Suspected cause:
---------------------------
Mods?

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/rWmUN

Additional Info:
---------------------------
I have 24 mods and 1 shader pack. This has never happened before.

**Comment by tehbasshunter** [comment]
Try disabling blur. That appears to be the noticeable offender.

**Comment by Mysticalii** [comment]
ok i'll try that

**Comment by Mysticalii** [comment]
Thanks man, it worked problem solved.
