### ISSUE TITLE
Add Shaderpack Tab like Mods [Enhancement]

### ISSUE THREAD

**Issue by agowa338** [MultiMC/MultiMC5#252]
Please add a Tab for easily installing Shaderpacks
They use a Sub folder in the Minecraft Profile (.minecraft/shaderpacks) and ship as .zip files or folders.
http://www.minecraftforum.net/topic/940974-172sonic-ethers-unbelievable-shaders-and-glsl-shaders-mod/

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Wonko package management)](https://workflowy.com/s/2EyDMcp7CU)
