### ISSUE TITLE
multiMc shutsdown internal server instantly

### ISSUE THREAD

**Issue by LeftQuill4472** [MultiMC/MultiMC5#2520]
System Information
-----------------------------
MultiMC version:0.6.4

Operating System:

Summary of the issue or suggestion:
----------------------------------------------
instantly shutsdown internal server

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/LUTfG

Additional Info:
---------------------------

**Comment by Heufneutje** [comment]
Looks like Optifine is your problem. Try removing it or messing around with different Optifine versions.
