### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by martmists** [MultiMC/MultiMC5#2522]
System Information
-----------------------------
MultiMC version: latest

Operating System: Arch Linux x64

Summary of the issue or suggestion:
----------------------------------------------

I try to launch a pack I'm working on, but I get the following in console:
```
   ...
   72.052 D Resolving dependencies
   72.052 D "Req: net.minecraft == 1.12.2" already has different version that cannot be changed.
   72.052 D "Req: org.lwjgl" Is missing and should be added at 0
   72.052 C Task "ComponentUpdateTask(0x55c2a9bb4bd0)" failed:  "Instance has conflicting dependencies."
   72.052 D Component list update/resolve task failed for "TestPack" Reason: "Instance has conflicting dependencies."
   72.052 C Task "MinecraftUpdate(0x55c2a9388470)" failed:  "Instance has conflicting dependencies."
   72.052 C Task "Update(0x55c2a9279510)" failed:  "Instance update failed because: Instance has conflicting dependencies.\n\n"
   72.056 D Writing account list to "accounts.json"
   72.056 D Building JSON data structure.
   ...
```

In the console window:

```
MultiMC version: 0.6.3-custom


Minecraft folder is:
/home/mart/.local/share/multimc/instances/TestPack/minecraft


Java path is:
/usr/bin/java


Java is version 1.8.0_202, using 64-bit architecture.


Instance update failed because: Instance has conflicting dependencies.
```

What should happen:
------------------------------

It should launch just fine

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install pack <can add link if needed>

2. Try to launch

3. Error happens

**Comment by peterix** [comment]
Hmm?

**Comment by martmists** [comment]
Figured it out myself, my manifest.json generator set the version to 1.12 where it should have been 1.12.2

**Comment by mattiaperry95** [comment]
> Figured it out myself, my manifest.json generator set the version to 1.12 where it should have been 1.12.2

how do u fixed it?
