### ISSUE TITLE
code -1 exit 

### ISSUE THREAD

**Issue by SPACEFACE2394** [MultiMC/MultiMC5#2523]
I know what mod is causing the problem but is there any way to make it compatible?
https://paste.ee/p/X7fjl Minecraft log

**Comment by tehbasshunter** [comment]
Probably start by giving the pack more than 2GB of ram.

**Comment by SPACEFACE2394** [comment]
Then what?

**Comment by Heufneutje** [comment]
If you know which mod it is you'll have to play around with different versions of that mod or different versions of Forge until it works.
