### ISSUE TITLE
never mind, I fixed the problem myself

### ISSUE THREAD

**Issue by Dewieaha** [MultiMC/MultiMC5#2527]
System Information
-----------------------------
MultiMC version: 0.6.4-1291

Operating System: Windows 10

Summary of the issue or suggestion: Won't allow me to log in with any account even though the passwords and emails are correct
----------------------------------------------

What should happen: 
------------------------------
**It should sign me in and allow me to play Minecraft on this launcher**

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open launcher (MultiMC)

2. Add an account

3. Try to log in

Suspected cause:
---------------------------
I thought it was my password or email being typed in wrong, so I kept reentering them and it never worked so.. idk.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

I don't have any screenshots
Additional Info:
---------------------------
Got no additional info

**Comment by Heufneutje** [comment]
You should probably close the issue in that case.
