### ISSUE TITLE
Minecraft 1.12.2 not working in MultiMC for Linux

### ISSUE THREAD

**Issue by Sparkie2** [MultiMC/MultiMC5#2528]
System Information
-----------------------------
MultiMC version: 0.6.4-1206

Operating System: Ubuntu Linux (lin64)

Summary of the issue or suggestion: Minecraft 1.12.2 doesn't launch. 1.13 up works properly.
----------------------------------------------

What should happen: Minecraft 1.12.2 should launch normally
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Make an empty, Vanilla 1.12.2 profile in MultiMC for Linux

2. Launch it without modifying anything

Suspected cause: Missing libraries or bad filenames, maybe not enough RAM
---------------------------

Logs/Screenshots: https://paste.ee/p/1B2sF
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info: Previously, it happened also with 1.7.10. It works perfectly fine in Windows. 1.13 and 1.14 snapshots work without issue.
---------------------------

**Comment by QuImUfu** [comment]
see:  
https://www.minecraftforum.net/forums/support/java-edition-support/2931149-cant-launch-on-ubuntu-18-10  
You might want to use Java 8 anyway as it is the newest Java version that supports modding.

**Comment by Drecondius** [comment]
1.12.x requires Java 8. Cannot run on 9 up if modded.

**Comment by Josh74000** [comment]
forge for 1.13.2 is out, its still not available on multimc yet still
