### ISSUE TITLE
Shortcuts for Individual Profiles?

### ISSUE THREAD

**Issue by MC42** [MultiMC/MultiMC5#253]
If I recall correctly, there was a feature in older versions of MultiMC that allowed you to create shortcuts to launch the game without launching MultiMC and hitting play.  This feature seems to have been removed.

**Comment by peterix** [comment]
There is no reason for closing this.

**Comment by MC42** [comment]
Whoops, sorry... Wrong button...

**Comment by peterix** [comment]
Actually, this is now a lot closer to reality - I started refactoring the instance launch things. With any luck, it should end up in the version after 0.4.8

**Comment by MC42** [comment]
Much appreciated.

**Comment by osum4est** [comment]
+1

**Comment by peterix** [comment]
You can now make those manually.

If you run MultiMC like this:
```
MultiMC -l "instance_id"
```
It will launch MultiMC and just run the instance.

**Comment by peterix** [comment]
The important part of this is done. You can now launch instances directly.

Any fluff on top of this will be done later.

**Comment by MC42** [comment]
Thank you, much appreciated.

**Comment by p-schneider** [comment]
When launching my Minecraft Instance using the MultiMC -l parameter on Windows the MultiMC.exe process doesn't quit after I close the game. It's leaving no GUI behind, so I have to kill it using a task manager. (The logging window is set to close after the game quits.)

Game running:
![before (game running)](https://cloud.githubusercontent.com/assets/2636101/10649406/40f48808-7844-11e5-9c79-18949ad3440c.png)

Game quit, MultiMC still running in the background without a visible GUI (no tray bar icon either):
![after (game quit)](https://cloud.githubusercontent.com/assets/2636101/10649407/43c3a51e-7844-11e5-8eb6-c02260178f50.png)

**Comment by peterix** [comment]
I'm going to split this off to a new issue: #1300

**Comment by peterix** [comment]
@p-schneider should be fixed now

**Comment by peterix** [comment]
Alright. The hard part of this should be done already. I'm splitting off the UI integration and I'm going to track it on workflowy.

[The remaining work moved to workflowy as an idea (Ideas -> Add creation of system shortcuts to launch instances)](https://workflowy.com/s/2EyDMcp7CU)
