### ISSUE TITLE
Incorrect File Associations

### ISSUE THREAD

**Issue by Qwerty-Space** [MultiMC/MultiMC5#2530]
System Information
-----------------------------
MultiMC version:
Name            : multimc-git
Version         : 0.6.4.r8.ge4599ee2-1

Operating System:
Manjaro

Summary of the issue or suggestion:
----------------------------------------------
MultiMC opens directories in VSCode, and JSON in firefox

What should happen:
------------------------------
They should open with the correct program

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Click "Edit Instance"

2. VSCode opens

**Comment by peterix** [comment]
Well, I have no idea. MultiMC uses Qt's API calls to do that, and whatever those do depends on way too many factors.

Can you try running MultiMC in `strace` and get me some minimal set of `strace` logs? Just start the thing, do whatever is necessary to make it open the file(s) and close it, so minimize the amount of log spam.

Example:
`strace -f -e trace=execve multimc`

```
...
   34.690 D Opening directory "/home/peterix/.local/share/multimc/instances-experiment/a1.1.8/.minecraft"
strace: Process 27108 attached
strace: Process 27109 attached
strace: Process 27110 attached
[pid 27110] execve("/usr/bin/xdg-open", ["/usr/bin/xdg-open", "file:///home/peterix/.local/shar"...], 0x7ffd1a76aba8 /* 57 vars */ <unfinished ...>
[pid 27109] +++ exited with 1 +++
[pid 27108] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=27109, si_uid=1000, si_status=1, si_utime=0, si_stime=0} ---
[pid 27110] <... execve resumed> )      = 0
[pid 27108] +++ exited with 0 +++
[pid 27009] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=27108, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
strace: Process 27111 attached
[pid 27111] execve("/usr/bin/kde-open5", ["kde-open5", "file:///home/peterix/.local/shar"...], 0x5608f1b0ca30 /* 57 vars */) = 0
strace: Process 27112 attached
strace: Process 27113 attached
[pid 27112] +++ exited with 0 +++
[pid 27113] +++ exited with 0 +++
[pid 27111] +++ exited with 0 +++
[pid 27110] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=27111, si_uid=1000, si_status=0, si_utime=5, si_stime=2} ---
[pid 27110] +++ exited with 0 +++
///
```

**Comment by Qwerty-Space** [comment]
Looks like it tries to open it in ranger, then if I kill ranger it opens in VSCode now.
[multimc.txt](https://github.com/MultiMC/MultiMC5/files/2847369/multimc.txt)

So, if I don't kill ranger, ranger will appear in the logs
[multimcranger.txt](https://github.com/MultiMC/MultiMC5/files/2847370/multimcranger.txt)

**Comment by peterix** [comment]
I have no idea what that is, but it doesn't look like an strace log.

**Comment by Qwerty-Space** [comment]
@peterix Well, that's what the command gave me.
I think ranger tried to open in the strace log, and that's why it's a bit messed up

**Comment by peterix** [comment]
But what is ranger and where did it come from?

That can't be the whole log. It's not clear what processes are being spawned to handle the open request from it.

**Comment by Qwerty-Space** [comment]
ranger is a CLI file manager
