### ISSUE TITLE
MultiMC not opening crash landing

### ISSUE THREAD

**Issue by raggnoross** [MultiMC/MultiMC5#2533]
System Information
-----------------------------
MultiMC version: newest (0.6.4)

Operating System:

Summary of the issue or suggestion:
----------------------------------------------
Whenever i click launch on the instance i created for the modpack crash landing (i have created one through both downloads and the ftb legacy thing) it shows the green play button on the instance then stops, no crash report or anything, just stops (I only have a problem w/ crash landing everything else works). I have deleted crash landing a few times and tried to get it to work but i'm stumped. 

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by QuImUfu** [comment]
You need to update forge. The version of Forge packed with crash landing crashes with newer Java versions.

**Comment by brodycas3** [comment]
You can also use the java fixer mod.
https://forums.atlauncher.com/thread-4767.html
