### ISSUE TITLE
Project Ozone 3 keeps crashing while loading. 

### ISSUE THREAD

**Issue by SparJar** [MultiMC/MultiMC5#2535]
System Information
-----------------------------
MultiMC version:  0.6.4-1206

Operating System:  Ubuntu 18.04

Summary of the issue or suggestion:
----------------------------------------------
Project Ozone 3 instance crashing while loading. 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.  Re-launch and keeps crashing.

Suspected cause:
---------------------------
Voidcraft(?)  tried removing the mod but it didn't help. 

Logs/Screenshots:
----------------------------
https://paste.ee/p/nGmax

Additional Info:
---------------------------

**Comment by peterix** [comment]
It's crashing in your GPU driver (nouveau). I suggest using the real Nvidia driver.

**Comment by SparJar** [comment]
That did it! Thanks for looking into it.

**Comment by slainhydra77** [comment]
How do i use the real nvidia driver?

**Comment by QuImUfu** [comment]
google "your_distro_name nvidia driver" and follow the instructions that come up.

**Comment by Hellodogcheeseman** [comment]
How do you find that?

**Comment by Hellodogcheeseman** [comment]
And which one?

**Comment by zMarq28** [comment]
project ozone 3 does not open with optifine ,
it stops at the minecraft forge check, can someone please help me

**Comment by SiGz2630** [comment]
I can't open the Project Ozone 3.
please help..
i'm new here..
[crash-2019-10-13_17.32.08-server.txt](https://github.com/MultiMC/MultiMC5/files/3721597/crash-2019-10-13_17.32.08-server.txt)
