### ISSUE TITLE
Create a release with Qt 5.11 compatibility

### ISSUE THREAD

**Issue by leo60228** [MultiMC/MultiMC5#2536]
System Information
-----------------------------
MultiMC version: 0.6.2 / 19bb50b872da2702b8e0b65f3f7b6b54c1c5b071

Operating System: Linux (NixOS)

Summary of the issue or suggestion:
----------------------------------------------
[NixOS](https://nixos.org) has an official [package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/games/multimc/default.nix) for MultiMC, but it's currently built off the first commit with Qt 5.11 compatibilty, as NixOS does not package older versions of Qt. You could possibly backport 4d68c1b509cd289e9f02cbf258e69f2539349029 to v0.6.2 and put that in a v0.6.2-qt511 tag. This may have already been done with 0.6.3, but that does not appear to be an official release.

What should happen:
------------------------------
The latest official release can be built for Qt 5.11 without distribution-specific packages.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Build using Qt 5.11 on v0.6.2.

2. Build fails.

3. Update to unstable version 4d68c1b509cd289e9f02cbf258e69f2539349029.

4. Build succeeds.

Suspected cause:
---------------------------
4d68c1b509cd289e9f02cbf258e69f2539349029 is not available in an official release

Logs/Screenshots:
----------------------------
```
Unknown CMake command "qt5_use_modules"
```
From NixOS/nixpkgs#42387.

**Comment by peterix** [comment]
The current stable release is 0.6.4: https://github.com/MultiMC/MultiMC5/releases/tag/0.6.4

**Comment by leo60228** [comment]
Shouldn't this be available on the website? I thought that was a beta version, based on it only being documented in the Git repo.

**Comment by peterix** [comment]
The answer is: no.

I will not build with Qt 5.11 - I will continue to build with 5.4 and stop shipping Qt with linux builds.
