### ISSUE TITLE
Selfmade Modpack not starting

### ISSUE THREAD

**Issue by Meisterpopeister** [MultiMC/MultiMC5#2537]
MultiMC version: 064-1291

Operating System: Windows 10

Summary of the issue or suggestion:
I made a Modpack with about 80 mods, everything works completely fine on my server and on my Mac. Now i copied all of the mods and put em on Dropbox for my friends to download and play with me. (about 5 people all but me have the same error and all of them have Windows 10) I made him start it once without Ender io and once without Applied energistics 2 and AE2 Addons it crashed both times (I did that because Log row 1665 up tp 1670 told me to do so)

What should happen:
Game should start normally like for me

Steps to reproduce the issue:
1.Add the Mods to your Multi-mc

2.Start your Game

3.see it crashing in Forge phase 2

Suspected cause:
His Log row 1566 and row 1567
or
His Log row 1665 up to 1670

Logs/Screenshots:
His Log:  https://paste.ee/p/9uwq2

My Log:  https://paste.ee/p/tmydc
(i stopped mine in the main menu everything works and the texture bugs go away when i reload the textures once by adding and removing a texture pack)

Additional Info:
I would be happy to send you Guys more logs or Screenshots of our Multi Mc!

**Comment by janagyjr** [comment]
Looks like your friend only assigned a maximum of 2GB of RAM to the pack. Add moar RAM.

**Comment by peterix** [comment]
Assuming fixed, pastebins timed out.
