### ISSUE TITLE
Crash on Instance start

### ISSUE THREAD

**Issue by APimpNamedShane** [MultiMC/MultiMC5#2538]
System Information
-----------------------------
MultiMC version:
6.4-1204
Operating System:
Linux Mint
Summary of the issue or suggestion:
----------------------------------------------
Program Crashes when attempting to run any instance

What should happen:
------------------------------
Minecraft should run

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Unsure

2.

3.

Suspected cause:
---------------------------

No clue

Logs/Screenshots:
----------------------------
https://paste.ee/p/Ixmof

Additional Info:
---------------------------

**Comment by QuImUfu** [comment]
could you post the output of
```
glxinfo -B
```

**Comment by APimpNamedShane** [comment]
shane@laptop ~ $ glxinfo -B
name of display: :0
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  76
  Current serial number in output stream:  77

**Comment by QuImUfu** [comment]
Your graphics driver is not working.
Could you upload (e.g. to https://paste.ee) the contents of
`/var/log/Xorg.0.log`
and post a link?

**Comment by APimpNamedShane** [comment]
So I managed to get it working. I remembered that I had allowed Mint to
install updates and forgotten to restart. Sorry for the inconvenience.

Shane
