### ISSUE TITLE
´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´

### ISSUE THREAD

**Issue by gabriel2300** [MultiMC/MultiMC5#2539]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
minha conta nao entra

**Comment by peterix** [comment]
I'm sorry something with your account doesn't work, but please, try to at least communicate enough information to allow others to help you.
