### ISSUE TITLE
RAM problem

### ISSUE THREAD

**Issue by Omegasutoraiki** [MultiMC/MultiMC5#2540]
System Information
-----------------------------
MultiMC version: 5

Operating System: windows 7

Summary of the issue or suggestion: When I allocate more than 1488
![working](https://user-images.githubusercontent.com/47616823/52894605-c48ab180-3171-11e9-9222-3c6aaf0d9bbc.PNG)
 MB to my java RAM in MultiMc Minecraft won't launch. When I use the settings and hit test it says "The specified java binary didn't work with the arguments you provided"

----------------------------------------------

What should happen: I don't know if this is  because of my PC or because of a bug because I have tried it on other computers aswell and it does the same thing
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. open settings on the main MultiMC tab

2.go to java

3.raise Maximum memory allocation to over 1488mb

4. try to run an instance or hit test with any amount of memory above 1488mb

Suspected cause: I have no clue personally I just want to play modded Minecraft with some friends
---------------------------

Logs/Screenshots:
![not working](https://user-images.githubusercontent.com/47616823/52894607-d704eb00-3171-11e9-9ab2-76e7dfe9f982.PNG)
![working](https://user-images.githubusercontent.com/47616823/52894609-da987200-3171-11e9-8a15-d5fded1d9f5f.PNG)

----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Omegasutoraiki** [comment]
sorry about the double picture there my computer kinda copied it twice without me realizing.

**Comment by Heufneutje** [comment]
You're using 32-bit Java. You need 64-bit Java to allocate more RAM.

**Comment by Omegasutoraiki** [comment]
Well that sucks because I don't have a 64-bit PC thanks for the info though.
