### ISSUE TITLE
Modpack not loading fully

### ISSUE THREAD

**Issue by cathorpe21** [MultiMC/MultiMC5#2546]
System Information
-----------------------------
MultiMC version:0.6.5 - 1243

Operating System: macOSX 64-bit

Summary of the issue or suggestion:
----------------------------------------------
On trying to load a modpack, the icon comes up but quickly closes after and the error log pops up.

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: https://paste.ee/p/ubonm 

Additional Info:
---------------------------

**Comment by cathorpe21** [comment]
https://paste.ee/p/ubonm

**Comment by tehbasshunter** [comment]
Any reason you're using java 6?

**Comment by cathorpe21** [comment]
Didn't realise I was. Update it?

**Comment by tehbasshunter** [comment]
You need Java 8.

**Comment by cathorpe21** [comment]
Sorted - all good now! Thanks.
