### ISSUE TITLE
Build terminates on FreeBSD

### ISSUE THREAD

**Issue by soup6020** [MultiMC/MultiMC5#2547]
System Information
-----------------------------
MultiMC version: develop

Operating System: FreeBSD 13.0-CURRENT

Summary of the issue or suggestion:
----------------------------------------------
Compilation fails. I have the required dependencies installed. BSD make and GNU make provide the same output.

Suspected cause:
---------------------------
Either the Java FreeBSD provides is too old, or there is an issue with the project preventing proper compilation.

Logs/Screenshots:
----------------------------
https://hastebin.com/uyuhuvinoj.coffeescript

**Comment by peterix** [comment]
FreeBSD is not a supported operating system. You are on your own.

**Comment by peterix** [comment]
As for the problem itself, this is the global namespace being polluted with preprocessor macros.

This is on top of `JavaVersion.h`:
```
// NOTE: apparently the GNU C library pollutes the global namespace with these... undef them.
#ifdef major
    #undef major
#endif
#ifdef minor
    #undef minor
#endif
```

Guess on FreeBSD, this needs to be sprinkled over some other source files.

**Comment by soup6020** [comment]
Alright. I'll see if I can fix it at least locally then. A package exists already, but it's outdated so I'm trying to get it updated. Maybe I'll check what patches the maintainer used to get it working.
