### ISSUE TITLE
Versions using Alpha Save format stream saves from .minecraft, not the instance folder

### ISSUE THREAD

**Issue by JerryIsBored** [MultiMC/MultiMC5#2548]
System Information
-----------------------------
MultiMC version: 0.6.5-develop-1301

Operating System: Windows 10 version 16299.967

Summary of the issue or suggestion:
----------------------------------------------
When launching an instance of an old Infdev or Alpha version, (they are versions from an archive, not launcher versions), the game streams save from the .minecraft folder, not the instance folder. When creating a new world, the instance does not save the world to the instance folder, but the .minecraft folder instead. This applies to versions inf-20100327 to a1.0.9.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch MultiMC

2. Check instance folder of any version inf-20100327 to a1.0.9. See that there are no saves in the folder.

3. Check .minecraft folder, and see that the game is streaming saves from there instead of the instance folder.

---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.) 
Instance world select screen on Alpha 1.0.9.
![alpha 1 0 9 world select screen](https://user-images.githubusercontent.com/44452681/53293346-44cb9b00-37a0-11e9-96e4-1719d2ebccac.PNG)
Empty save folder in Alpha 1.0.9 instance folder.
![alpha 1 0 9 instance save folder](https://user-images.githubusercontent.com/44452681/53293347-4b5a1280-37a0-11e9-952e-1e2b2c8df9be.PNG)

Additional Info:
---------------------------
I also forgot to mention that most of my versions from inf-20100327 to a1.0.9 are from an archive, not the launcher. I do not know whether or not that affects this error or not.

**Comment by QuImUfu** [comment]
Old versions of minecraft (looked it up for inf-20100327) "hardcode" that location to:  
on Linux:
`System.getProperty("user.home", ".") + ".minecraft/"`
on Windows:  
`System.getenv("APPDATA") + ".minecraft/"`
on Mac:
`System.getProperty("user.home", ".") + "Library/Application Support/minecraft/"`


So to fix that on Linux you can simply pass:  
`-Duser.home="/path-to-mmc/instances/instance-folder-name"`
as Java argument.

On windows you'd need to change the environment variable APPDATA to:
`path-to-mmc\instances\instance-folder-name`
however i have absolutely no idea on how to do that on Windows :D 

On mac there is no way to fix that.
