### ISSUE TITLE
[Suggestion] Downgrade option

### ISSUE THREAD

**Issue by ReiDaTecnologia** [MultiMC/MultiMC5#2549]
_I deleted the issue template because this is a suggestion and i think it don't need it, if i'm wrong tell me and i will fix it._

This option could be useful.

**Comment by tehbasshunter** [comment]
If you mean downgrade MMC you can get that via the releases page [here](https://github.com/MultiMC/MultiMC5/releases).  
  
If you mean your minecraft version open the instance settings and switch the version in the versions tab.

**Comment by ReiDaTecnologia** [comment]
I mean an option in the app maybe even in the "update" gui, maybe select the version that you want to downgrade and stuff.

**Comment by QuImUfu** [comment]
The newer version should always be better.  
In what case do you think downgrading could be useful?

**Comment by peterix** [comment]
The answer is no.
