### ISSUE TITLE
Sort mods by being enabled/disabled

### ISSUE THREAD

**Issue by zomabies** [MultiMC/MultiMC5#2550]
MultiMC version: 0.6.5-develop-1301

What should happen:
----------------------------------------------
The mod entries should be sorted according to its status when the bar besides `Name` is clicked.

Steps to reproduce:
-------------------------------------------------------------
1. Select `Loader mods` from an instance
2. Click on the bar besides `Name` https://i.imgur.com/WLINOgL.png
3. The entries do not get sorted https://i.imgur.com/tJHsakh.png

The `Resource packs` menu has the same issue as above.

**Comment by peterix** [comment]
Sounds like an interesting thing to add.

**Comment by peterix** [comment]
Aaand done.
