### ISSUE TITLE
Make change version dialogue great again!

### ISSUE THREAD

**Issue by Zekken01** [MultiMC/MultiMC5#2552]
Change Minecraft version dialogue not unified with the create instance one with having the filter.

![image](https://user-images.githubusercontent.com/19770864/53594514-03a10580-3b69-11e9-9f2b-758266b04446.png)
![image](https://user-images.githubusercontent.com/19770864/53594546-19aec600-3b69-11e9-8a50-9cb960d0f859.png)

**Comment by peterix** [comment]
Can you explain what you mean? I don't understand that.

**Comment by Zekken01** [comment]
It doesn't have the same options for sorting by version, like the releases, snaps, betas, alphas, etc
