### ISSUE TITLE
The game crashes when I open the Minecraft with mods.

### ISSUE THREAD

**Issue by KentaroYuki** [MultiMC/MultiMC5#2554]
**I'm receiving a crash in my personal modpack, and I don't know how to fix it, please someone help me, the version of the Minecraft is 1.10.2.**

**The link containing the mods list, coremods list, Minecraft Log and Other Logs:**

https://paste.ee/p/ntPXC

**Please help me to fix it. All the mods are on their last version, except the OptiFine.** "428       * Optifine is installed. This is NOT supported." **I think some mod aren't compatible with OptiFine, and I can't play without OptiFine, because I have a low end computer, then I want to delete the mod that are incompatible with OptiFine.**

**Comment by tehbasshunter** [comment]
You'd need to upload the entire log when the instance crashes. Hit the upload button in the top right corner of console and paste the link here.

**Comment by QuImUfu** [comment]
```
Caught exception from Tinkers' Defense (tinkersdefense)
Caused by: slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Could not register Material "brass": It was already registered by Base Metals
```
seems to be quite an obvious error. 
fix it by disabling brass in BaseMetals.conf.
(set `B:EnableBrass=false` and `B:"Enabled Brass"=false`)

**Comment by KentaroYuki** [comment]
I am brazilian, then this isn't so obviously for me. And I don't know JavaScript, or whatever is it. I'm opening the Minecraft right now.

**Comment by KentaroYuki** [comment]
> ```
> Caught exception from Tinkers' Defense (tinkersdefense)
> Caused by: slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Could not register Material "brass": It was already registered by Base Metals
> ```
> seems to be quite an obvious error.
> fix it by disabling brass in BaseMetals.conf.
> (set `B:EnableBrass=false` and `B:"Enabled Brass"=false`)

QuImUfu, I get another crash. The link is here:
https://paste.ee/p/C6QlI

**Comment by QuImUfu** [comment]
Downgrade BaseMetals to 2.4.0.11 or remove NetherMetals.

**Comment by KentaroYuki** [comment]
> Downgrade BaseMetals to 2.4.0.11 or remove NetherMetals.

Ok, I'll try. Thanks for helping me.

**Comment by KentaroYuki** [comment]
> Downgrade BaseMetals to 2.4.0.11 or remove NetherMetals.

Another crash:
https://paste.ee/p/icroR

**Comment by QuImUfu** [comment]
That crash is hard to debug as there is no information what mod is at fault.  
You should first try updating optifine.

**Comment by KentaroYuki** [comment]
> That crash is hard to debug as there is no information what mod is at fault.
> You should first try updating optifine.

Ok.

**Comment by KentaroYuki** [comment]
> That crash is hard to debug as there is no information what mod is at fault.
> You should first try updating optifine.

I updated optifine to the last version of 1.10.2, and I get this crash:
https://paste.ee/p/7SCUD

**Comment by QuImUfu** [comment]
In that case you'll need to disable the mods strategically to find out with mod is causing it.  
(first deactivate one half, if it doesn't work, disable the other half...)  
If you upload the modpack and give me a link i would do that (and try to fix any other upcoming errors) for you.

**Comment by KentaroYuki** [comment]
> In that case you'll need to disable the mods strategically to find out with mod is causing it.
> (first deactivate one half, if it doesn't work, disable the other half...)
> If you upload the modpack and give me a link i would do that (and try to fix any other upcoming errors) for you.

Ok, give me 5 minutes and I'll upload for you.

**Comment by KentaroYuki** [comment]
> In that case you'll need to disable the mods strategically to find out with mod is causing it.
> (first deactivate one half, if it doesn't work, disable the other half...)
> If you upload the modpack and give me a link i would do that (and try to fix any other upcoming errors) for you.

The modpack link: 
https://www.dropbox.com/s/a8ny7ms0q9viter/mods.rar?dl=0

**Comment by KentaroYuki** [comment]
> In that case you'll need to disable the mods strategically to find out with mod is causing it.
> (first deactivate one half, if it doesn't work, disable the other half...)
> If you upload the modpack and give me a link i would do that (and try to fix any other upcoming errors) for you.

Are you online?

**Comment by QuImUfu** [comment]
Sorry this took me so long. These mods start and run just fine on one of my PC's (wtf) on the other i get the same crash.
Try setting `B:MilkBucket=false` in ./config/powercrystals/minefactoryreloaded/common.cfg.
I **think** that should fix the issue. I can not test it properly because the PC having the issue has not enough RAM to start the pack fully, but i think it got past the point were it cashed before.

**Comment by KentaroYuki** [comment]
> Sorry this took me so long. These mods start and run just fine on one of my PC's (wtf) on the other i get the same crash.
> Try setting `B:MilkBucket=false` in ./config/powercrystals/minefactoryreloaded/common.cfg.
> I **think** that should fix the issue. I can not test it properly because the PC having the issue has not enough RAM to start the pack fully, but i think it got past the point were it cashed before.

Yeees! It works! Thank you so much, and sorry for the inconvenience. Now I need to sleep, bye.
