### ISSUE TITLE
minecraft crash upon attempt to load optifine

### ISSUE THREAD

**Issue by titustitus98** [MultiMC/MultiMC5#2556]
System Information
-----------------------------
MultiMC version: 0.6.5-1302

Operating System: Windows

Summary of the issue or suggestion: So I tried installing optifine using the vanilla optifine installment tutorial provided on the github page and I keep getting a bigg error message in the logs and mc doesen't launch.
----------------------------------------------

What should happen: Mc should launch correctly with optifine
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
https://pastebin.com/1U00DdSn

Additional Info:
---------------------------

**Comment by tehbasshunter** [comment]
2 problems:  
You're using Java 10. You need 8 for modded.  
Why not add forge and drop in mods folder?

**Comment by titustitus98** [comment]
> 2 problems:
> You're using Java 10. You need 8 for modded.
> Why not add forge and drop in mods folder?

I have tried doing that but I get the same error

**Comment by tehbasshunter** [comment]
That's most likely due to you using Java 10. Install 8 and switch to that version.

**Comment by titustitus98** [comment]
hi thanks for your help but now I am crashing each time I try to load mc here is the error log: https://pastebin.com/sEwKWa10

**Comment by tehbasshunter** [comment]
Need the full log. Hit upload in the fop right corner of console after it crashes aand paste that link here.

**Comment by titustitus98** [comment]
https://paste.ee/p/YdKhI

**Comment by Heufneutje** [comment]
Have you tried assigning more RAM to the instance?

**Comment by QuImUfu** [comment]
upgrade BetterFoliage and install the new dependency Forgelin or downgrade Forge.
