### ISSUE TITLE
When I open the instance, it crashes

### ISSUE THREAD

**Issue by jing1456** [MultiMC/MultiMC5#2558]
System Information
-----------------------------
MultiMC version:MultiMC5 0.6.5-1302

Operating System:Windos10

Summary of the issue or suggestion:When I launch the instance, it will crashes, I don't know why.
----------------------------------------------

What should happen:It will crash and pop up a window
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open Multimc

2. Launch the instance

3. Then crash

Suspected cause:Forge error
---------------------------

Logs/Screenshots:
1.Online startup log
Java version 1.8.0_201, on 64-bit architecture

The instance update failed because: Game update error: Unable to get the required FML library.
the reason:
The task "Instance FTB Sky Adventures Dependent Library" failed to process:
Http://files.minecraftforge.net/maven/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar.pack.xz
Http://files.minecraftforge.net/maven/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar.pack.xz
Http://files.minecraftforge.net/maven/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar.pack.xz
Http://files.minecraftforge.net/maven/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar.pack.xz.

2.Offline startup log
[minecraft error.txt](https://github.com/MultiMC/MultiMC5/files/2945698/minecraft.error.txt)

There is a Chinese directory inside, but my friend can use the multimc to start the Minecraft
 normally in the Chinese directory.

----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by jing1456** [comment]
Ummm，I try to change the Forge,but it still crashes

**Comment by QuImUfu** [comment]
MultiMC seems to be unable to download e.g.:
http://files.minecraftforge.net/maven/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar.pack.xz
Can you manually download it?

**Comment by jing1456** [comment]
> MultiMC seems to be unable to download e.g.:
> http://files.minecraftforge.net/maven/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar.pack.xz
> Can you manually download it?

Yes,I can download it.But which folder should I move to?

**Comment by jing1456** [comment]
> MultiMC seems to be unable to download e.g.:
> http://files.minecraftforge.net/maven/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar.pack.xz
> Can you manually download it?

Yes,I can download it.But what should I do?

**Comment by QuImUfu** [comment]
can you post MultiMC-0.log? It may contain more info on why the download failed.

**Comment by jing1456** [comment]
[MultiMC-0.log](https://github.com/MultiMC/MultiMC5/files/2952948/MultiMC-0.log)

**Comment by Heufneutje** [comment]
You must have opened MultiMC without launching anything afterwards. You should try to launch your instance and then post MultiMC-0.log here.
