### ISSUE TITLE
Add debugger support and refactor launch-time tools features

### ISSUE THREAD

**Issue by SoniEx2** [MultiMC/MultiMC5#256]

**Comment by peterix** [comment]
Profilers are fixed on Windows now.

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Launching)](https://workflowy.com/s/2EyDMcp7CU).

**Comment by peterix** [comment]
`no description provided`

Hmm... Why did we keep this open in the first place?

**Comment by SoniEx2** [comment]
fixed
