### ISSUE TITLE
MultiMc5 will not allocate more then 3GB in 64bit at launch

### ISSUE THREAD

**Issue by DrakenFireen** [MultiMC/MultiMC5#2561]
System Information
-----------------------------
MultiMC version: 0.6.5-1302

Operating System: Windows 10

the issue: despite setting java in 64bit and launching the instance, the game will only allocate 3gb in 32bit mode.

The game should run in 64bit to allocate ram needed, not to be forced to run in 32bit mode on a 64bit system.

im running a brand new system and is fully updated including the .net framework, latest java 8 64bit, 64bit windows 10 os and all the libraries.

**Comment by QuImUfu** [comment]
could you post a game log?

**Comment by DrakenFireen** [comment]
i can't do that at all, the log will not load as it crashes too fast, i can only run multiMC if forge is removed and running only in vanilla.

it keeps trying to launch in 32bit mode and i only have Java 8 64bit latest version for march.

________________________________

**Comment by QuImUfu** [comment]
a vanilla log is fine.
