### ISSUE TITLE
Arch Linux | MultiMC won't install through yay.

### ISSUE THREAD

**Issue by RavenChan1023** [MultiMC/MultiMC5#2564]
System Information
-----------------------------
MultiMC version: 0.6.5

Operating System: Arch Linux (x64)

Summary of the issue or suggestion: Yay doesn't install MultiMC and instead aborts and tells me to check the log.
----------------------------------------------

What should happen: It should install and be ready to run right from the get-go.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open Konsole (or terminal of your choice)

2. Use the command: yay -S multimc5

3. When it asks if you want to remove make dependencies afterwards, hit y then hit enter

4. Enter password

5. Everything else will download and install just fine but MultiMC itself will not install.

Suspected cause:
---------------------------
My only guess is that it may be a possible issue with the aur package, as everything else I install with yay tend to work just fine. I'll poke at other angles and see if it's not a dependency problem, but I figured I'd make this post ahead of time in case I don't end up resolving it myself.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

[CMakeError.log](https://github.com/MultiMC/MultiMC5/files/2953447/CMakeError.log)

Additional Info:
---------------------------

**Comment by peterix** [comment]
I do not own the `multimc5` package... Contact its maintainer.

**Comment by peterix** [comment]
See: See: https://aur.archlinux.org/packages/multimc5

**Comment by Xiretza** [comment]
AUR package maintainer here, I can't reproduce it in a clean chroot. Since it fails inside a CMake check, it really is unlikely to be MultiMC's fault - much more likely a system misconfiguration.

@RavenChan1023 are you up to date (`pacman -Syu`)?

**Comment by RavenChan1023** [comment]
@Xiretza I wasn't up to date, I'll perform a full upgrade then clone the git, provided I don't come across any issues after the upgrade.

**Comment by RavenChan1023** [comment]
Same issue when trying to build it manually.

>   -> Found quazip-fix-build-with-qt-511.patch
==> Validating source files with sha512sums...
    0.6.5.tar.gz ... Passed
    multimc-0.6.1.tar.gz ... Passed
    multimc-3.tar.gz ... Passed
    quazip-fix-build-with-qt-511.patch ... Passed
==> Extracting sources...
  -> Extracting 0.6.5.tar.gz with bsdtar
  -> Extracting multimc-0.6.1.tar.gz with bsdtar
  -> Extracting multimc-3.tar.gz with bsdtar
==> Starting prepare()...
patching file CMakeLists.txt
==> Starting build()...
-- The C compiler identification is GNU 8.2.1
-- The CXX compiler identification is GNU 8.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Git commit: 805eff02b12c02b034a260746fed63be81dc04c3
-- Git refspec: refs/heads/master
-- Compiling for linux system with share/multimc and MULTIMC_LINUX_DATADIR
Using override nbt++ name: MultiMC_nbt++
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed
-- Performing Test COMPILER_HAS_DEPRECATED
-- Performing Test COMPILER_HAS_DEPRECATED - Failed
/home/mayravixx/multimc5/src/MultiMC5-0.6.5/cmake
CMake Error at libraries/launcher/CMakeLists.txt:2 (project):
  No CMAKE_Java_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "JAVA_COMPILER" or the CMake cache entry CMAKE_Java_COMPILER to
  the full path to the compiler, or to the compiler name if it is in the
  PATH.


-- Configuring incomplete, errors occurred!
See also "/home/mayravixx/multimc5/src/MultiMC5-0.6.5/build/CMakeFiles/CMakeOutput.log".
See also "/home/mayravixx/multimc5/src/MultiMC5-0.6.5/build/CMakeFiles/CMakeError.log".
==> ERROR: A failure occurred in build().
    Aborting...

>

**Comment by Draphar** [comment]
So were you able to resolve the issue?

**Comment by Janrupf** [comment]
Install `jdk8-openjdk`

**Comment by 143mailliw** [comment]
I have this error as well.
I have multiple versions of java, if that helps.
jdk8-openjdk is installed.

**Comment by Recidiviste** [comment]
I have the same issue, and installing other java versions doesn't works. The answer is to change java version thanks `archlinux-java`
Just type `sudo archlinux-java set java-11-openjdk` and then `yay -S multimc5`, and it'll works perfectly !

**Comment by Arzte** [comment]
Can confirm, if you're running a newer version of java, using ``archlinux-java`` to set a older version fixes the compile error. I had openJDK 12 set as my default, so changing it to 11 fixed it for me. (which I also had installed)

**Comment by AtomToast** [comment]
Same issue still persists but the provided fix via archlinux-java does fix it.
It does not seem to work with either 10 or 12

**Comment by strimmlarn** [comment]
`sudo archlinux-java set java-14-openjdk`

Solved it for me. 

So I guess openjdk version don't matter that much just that you point to the package or whatever with the ` archlinux-java` command

**Comment by Janrupf** [comment]
Java 14 sounds like a bad idea. It is possible that you won't be able to start Minecraft with older Java versions using MultiMC now
