### ISSUE TITLE
64-Bit Java running out of memory

### ISSUE THREAD

**Issue by dadijo2002** [MultiMC/MultiMC5#2567]
System Information
-----------------------------
MultiMC version: 0.6.5-1302

Operating System: Windows 10

Summary of the issue or suggestion: It will open MC for like 2 minutes then crash
----------------------------------------------

What should happen: I will open MC for like 2 minutes then it will crash. It won't let me increase the memory allocated past 1300MB but I have a 64-Bit Java
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download a bunch of mods into a pack

2. Join Multiplayer server

3. wait for it to crash or freeze

Suspected cause: it gives an out of memory error
---------------------------

Logs/Screenshots: https://paste.ee/p/W9iOe, https://paste.ee/p/43Ihb
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by tehbasshunter** [comment]
That's not 64bit java

**Comment by dadijo2002** [comment]
> That's not 64bit java

How do i upgrade?

**Comment by tehbasshunter** [comment]
That's 32bit Java￼

**Comment by tehbasshunter** [comment]
That's 32bit Java https://totally-not.a-sketchy.site/9fkXPoA.jpg

**Comment by dadijo2002** [comment]
> That's 32bit Java https://totally-not.a-sketchy.site/9fkXPoA.jpg

thank you but how do i get 64 bit?

**Comment by tehbasshunter** [comment]
https://java.com/en/download/manual.jsp

**Comment by dadijo2002** [comment]
> https://java.com/en/download/manual.jsp

Thank you! trying that rn

**Comment by peterix** [comment]
I'll guess it worked an you just forgot about this.
