### ISSUE TITLE
Multimc for beta 1.3_01 (with mods) crash upon loading world

### ISSUE THREAD

**Issue by municak** [MultiMC/MultiMC5#2568]
System Information
-----------------------------
MultiMC 5 version: 0.6.5.1302

Operating System: Win 8

Summary of the issue or suggestion:
----------------------------------------------
Multimc crashes during loading/startup of world

What should happen: 
------------------------------
World loads without crash

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Edit instance

2. Have required support mods/modloaders and correct version/update

3. Add Coral and/or Tree mod

4. Launch

5. Choose current or create new world

6. Multimc crashes mid-load

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
https://paste.ee/p/1DK16
https://paste.ee/p/ZPBqg

Additional Info:
---------------------------
All of the mods and required modloaders are for the correct update (beta 1.3_01) 
Multimc crashes when loading either the Tree Mod (log: 1DK16) and/or Coral Reef mod (log: ZPBqg)

**Comment by peterix** [comment]
The pastebin posts expired. In any case, this does not sound like a MultiMC problem, but a broken mods problem.
