### ISSUE TITLE
Newer versions of forge for 1.12.2 do not appear in install options...

### ISSUE THREAD

**Issue by ate0ate** [MultiMC/MultiMC5#2570]
System Information
-----------------------------
MultiMC version: 0.6.5 dev1304

Operating System: Win10

Summary of the issue or suggestion:
----------------------------------------------
More recent versions of forge for Minecraft 1.12.2 do not show up under install options for forge.

What should happen: 
------------------------------
When updating my instance and selecting to change the version of forge installed I should be able to select from several builds of forge after 14.23.5.2815 but they do not appear. (builds 2816 through 2821)

**Comment by peterix** [comment]
Fixed.
