### ISSUE TITLE
Multiple modloader support

### ISSUE THREAD

**Issue by Vokuar** [MultiMC/MultiMC5#2571]
System Information
-----------------------------
MultiMC version: 0.6.5-1302

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Other Modloaders that have been released added to the launcher
also a button to choose the modloader for future possible modloaders being added)
such as rift (yes i know its for 1.13.2 but it could be made so it only installs in in that version)

What should happen:
------------------------------
installation of other modloaders other than forge and liteloader

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. go to edit instance

2. go to loader mods

3. only liteloader and forge options

Suspected cause:
---------------------------
no support as of current

Logs/Screenshots:
----------------------------
https://i.imgur.com/vw5REET.png

**Comment by Vokuar** [comment]
Accidentally closed it

**Comment by peterix** [comment]
The answer to this would be: `maybe`.

**Comment by Prospector** [comment]
this seems resolved now that Fabric has been added

**Comment by asiekierka** [comment]
Well, the issue is about Rift; but Rift is generally unmaintained at this point, and its mod developers generally moved on to Fabric...

**Comment by muzikbike** [comment]
some way to install modloader (the super old one) for old versions would also be handy, as currently you're forced to modify the jar directly and can only run it in offline mode

**Comment by Scotsguy** [comment]
Resolved.
