### ISSUE TITLE
Add ability to edit Instance Folder Name

### ISSUE THREAD

**Issue by FeedTheChunk** [MultiMC/MultiMC5#2576]
System Information
-----------------------------
MultiMC version: 0.6.5-develop-1305

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Add the ability to edit the instance folder name.

What should happen:
------------------------------
Possible solution - Add an "instance path" under the "Edit Instance" window.  "Settings" section would be a logical place.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. I installed Stoneblock2 1.9.0 by using the Add Instance -> Import from Zip and pointed MultiMC to the http download on Curse.  It installed the instance just fine but the instance folder name ended up being "download."

I can change the name of the folder to something more descriptive but there doesn't appear to be a way of pointing the newly created instance to a different folder. 

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
This is something I've put off for quite a long time, and probably has a bunch of duplicates here.

The folder name is used for tracking the identity of the instance. When you change it, all sorts of things related to it will no longer be related to it. Solvable issue, but I never managed to convince myself that it is major enough for me to deal with it.

**Comment by pbanj** [comment]
an easy workaround for now is to rename the instance, export it, then import it.

**Comment by mastazi** [comment]
@pbanj thank you so much for pointing out the export/import workaround! This made my life so much easier

**Comment by phit** [comment]
This was scrapped due to the way the folder is the instance identity, just not feasible https://github.com/MultiMC/MultiMC5/pull/2707
Just use the above mentioned workaround.
