### ISSUE TITLE
Minecraft crashes on ubuntu while loading mods

### ISSUE THREAD

**Issue by Frogbeerr** [MultiMC/MultiMC5#2578]
System Information
-----------------------------
MultiMC version: 0.6.5-1217

Operating System: Ubuntu 18.04.2 LTS (Bionic Beaver) 64-bit

Summary of the issue or suggestion:
----------------------------------------------
Whenever I start an instance that has forge installed (I tried a few different versions of forge and minecraft) it either crashes, freezes or crashes my entire system.
For some reason it works if I run MultiMC as admin using sudo.

What should happen:
------------------------------
Minecraft should start up normally.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[PasteBin](https://pastebin.com/xe3F4Nm4)

Additional Info:
---------------------------

**Comment by peterix** [comment]
That log doesn't have useful information in it. If you've ever ran MultiMC as root, the whole thing is probably now broken, because any created files will be also owned by root. Fix your permissions.

**Comment by peterix** [comment]
You may be able to use `chown -R $(id -u -n):$(id -g -n) ~/.local/share/multimc/`  to restore proper file ownership.
