### ISSUE TITLE
Exiting MultiMC does not quit Java or clear memmory. 

### ISSUE THREAD

**Issue by GmanAtheist** [MultiMC/MultiMC5#2582]
System Information
-----------------------------
MultiMC version: 0.6.5.-.develop - 1305

Operating System: Windows 10.1
Msi Gaming motherboard.
16GB DDR3 
4GB MSI graphics card. 

Summary of the issue or suggestion:
----------------------------------------------
When exiting MultiMC 5 the Java instance does not exit. Even after closing MultiMC down. Java stays active and hogs memory.  Works fine with same mods in Windows 8.1. 

What should happen:
------------------------------
When exiting Minecraft Java should release memory and exit Java. 
![SNAG-0003](https://user-images.githubusercontent.com/5624207/55181553-c89feb00-5183-11e9-8fff-f68081942a85.jpg)
![SNAG-0004](https://user-images.githubusercontent.com/5624207/55181555-c89feb00-5183-11e9-947a-92e1f7fe9199.jpg)

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
Works as intended. When you close MultiMC, it only exits when there's nothing left - no MultiMC windows, no running game instances.

So, this works as intended.
