### ISSUE TITLE
Crash Report 1.7.10

### ISSUE THREAD

**Issue by yosifking93** [MultiMC/MultiMC5#2583]
i have problem with launching modded minecraft

and this is the crash report: https://pastebin.com/yXSJiAnv

**Comment by QuImUfu** [comment]
can you upload the complete log via the upload button?
It contains additional info.

**Comment by Galwet** [comment]
Update ForgeMicroblock

**Comment by DiamondOSDev** [comment]
Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
man, remove optifine or a mod which needs Mantle

**Comment by peterix** [comment]
Closing for lack of response from original poster.
