### ISSUE TITLE
missing java?

### ISSUE THREAD

**Issue by usereewrjrjeejr** [MultiMC/MultiMC5#2585]
![Capture](https://user-images.githubusercontent.com/36968617/55294694-18c0bc80-53d3-11e9-846f-6ad14d8b62f6.PNG)

How do I fix this?

**Comment by peterix** [comment]
Looks fine to me, as long as you are on a 32bit system.

Otherwise: https://javadl.oracle.com/webapps/download/AutoDL?BundleId=236888_42970487e3af4f5aa5bca3f542482c60
