### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by SirPrijter** [MultiMC/MultiMC5#2586]
System Information
-----------------------------
MultiMC version:
 0.6.5-1302

Operating System: 
Windows 10 64x

Summary of the issue or suggestion: 
----------------------------------------------
Error: "Failed to login: The authentication servers are currently down for maintenance.

What should happen: 
------------------------------
Connect to a multiplayer server.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. I have no clue

Suspected cause:
---------------------------
Authentication

Logs/Screenshots:
----------------------------
(https://user-images.githubusercontent.com/35633418/55511463-f47a0f80-5660-11e9-86a2-f4f6fac56cbc.png)

Additional Info:
---------------------------

**Comment by KayKayKo** [comment]
are you okay

**Comment by Zewia** [comment]
This has nothing to do with MultiMC.

**Comment by SirPrijter** [comment]
I'm only having this problem on MultiMC tho
