### ISSUE TITLE
game does not start

### ISSUE THREAD

**Issue by Ic1k** [MultiMC/MultiMC5#2588]
System Information
-----------------------------
MultiMC version: 0.6.5 1302

Operating System: windows 10

Summary of the issue or suggestion:
----------------------------------------------
game does not start

What should happen:
------------------------------
Start game.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download MultiMC

2. Login account

3. Create 1.7.10 note mods

4. Launch 

5. Getting the Library files from Mojang

6. wait wait wait

7. Crash:
 Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance 1.7.10' failed to process:
https://launcher.mojang.com/v1/objects/e80d9b3bf5085002218d4be59e668bac718abbc6/client.jar

8. Launch Offline 

This is how it works!

Suspected cause:
---------------------------
The problem is he lives 3 days. Everything else works.

Logs/Screenshots:
----------------------------
https://paste.ee/p/iNgXv

Additional Info:
---------------------------

**Comment by peterix** [comment]
Looks like a network problem. Check the `MultiMC-0.log` file for details.
