### ISSUE TITLE
Fails to launch with no internet connection.

### ISSUE THREAD

**Issue by darchitectlp** [MultiMC/MultiMC5#2589]
System Information
-----------------------------
MultiMC version:
0.6.5.1243

Operating System:
OSX 10.11.6 (El Capitan)

Summary of the issue or suggestion:
----------------------------------------------
MultiMC won't start when there is no internet, even if I've connected successfully once, then disconnect. It also fails if I choose "Launch Offline."

What should happen:
------------------------------
Minecraft starts.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Try to launch with no internet.

2.

3.

Suspected cause:
---------------------------
No idea.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
None, but thanks for making a great launcher!

**Comment by QuImUfu** [comment]
Have you launched the instance once with internet access? There are files downloaded the first time you start an instance.

**Comment by darchitectlp** [comment]
As I stated, yes.

**Comment by QuImUfu** [comment]
You stated you "connected" once. Wanted to be sure :D 
What error is MultiMC logging?

**Comment by peterix** [comment]
Well, I'll assume it fixed itself eventually. Reopen if necessary.
