### ISSUE TITLE
sign in problem

### ISSUE THREAD

**Issue by sonstud** [MultiMC/MultiMC5#2590]
when i try to play a version with a MCleaks acount it says put a pass in and when i do it says i didnt and that the token is expierd WHEN I JUST COPIED IT

**Comment by tehbasshunter** [comment]
Buy a legit copy.  We don't support cracked/stolen/hacked accounts.

**Comment by peterix** [comment]
Also: make sure to NEVER use your real account while MCLeaks is active. If you did, **GO CHANGE YOUR PASSWORD, NOW**!
