### ISSUE TITLE
Agricraft Automation?

### ISSUE THREAD

**Issue by KaiusWolf** [MultiMC/MultiMC5#2594]
Dont know if i'm doing something wrong, but i'm having real trouble automating harvesting of crops growing on agriculture crop sticks. I want to automate harvesting of diamond plants, but so far all I have found out is that the 'farmer' machine wont interact with agricraft crops at all, the Ender IO farming station removes the crop sticks and crops entirely before plancing plain seeds and the plant gatherer, while successfully harvesting a crop without breaking it, only does so to the one directly infront of it. Is there another machine I can try or will i have to use a complex system of plant harvesters, power cables and transfer nodes to automatically harvest nd transfer diamond essence?

**Comment by Heufneutje** [comment]
I feel like you'd be much better off asking the mod author of Agricraft.

**Comment by QuImUfu** [comment]
Don't know how how up to date these are but google shows.  https://www.reddit.com/r/feedthebeast/comments/46tiz2/ways_to_automate_agricraft/ and https://github.com/AgriCraft/AgriCraft/issues/92 as first result when searching "Agricraft Automation".
