### ISSUE TITLE
Newest forge version not detected

### ISSUE THREAD

**Issue by BlankLambda** [MultiMC/MultiMC5#2595]
On the Forge website, 1.13.2 versions of forge exists and is ready to be downloaded.
https://files.minecraftforge.net/
![image](https://user-images.githubusercontent.com/49465394/55847733-c24f3d00-5b8d-11e9-9d54-5ebb90c6e62c.png)

 
When trying to install forge through MultiMC on a 1.13.2 instance, it displays that there are no versions that exist.
![image](https://user-images.githubusercontent.com/49465394/55847704-aa77b900-5b8d-11e9-90b7-e51e3597fa52.png)

I am running the latest version of MultiMC and I have refreshed the MultiMC window multiple times.

**Comment by Janrupf** [comment]
This is currently normal, and it wont change until we found a way to install forge in MultiMC with its ~~stupid~~ installer

**Comment by peterix** [comment]
Yeah. Works as intended, sadly. No compatible versions exist.
