### ISSUE TITLE
Trying to change LWJGL to 3.2.1 or 3.1.2 on 1.13.2 results in it reverting to 3.1.6

### ISSUE THREAD

**Issue by ToastedToast128** [MultiMC/MultiMC5#2596]
System Information
-----------------------------
(Thinkpad w541)
Intel core i7-4810MQ
Intel HD graphics 4600
Nvidia Quadro k1100m
MultiMC version:
MultiMC 5 0.6.5-1302 on win32
Operating System:
Windows 10 1903 insider (also happens on 1809)
Summary of the issue or suggestion:
----------------------------------------------
Using the "change version" button to change LWJGL to 3.2.1 or 3.1.2 on minecraft 1.13 results in LWJGL showing the different version of LWJGL for 1 frame, then reverting to 3.1.6 (the JSON files still point to 3.1.6 binaries)

What should happen:
------------------------------
LWJGL should change versions

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create an 1.13.2 instance

2. Select LWJGL and press the change version button.

3. attempt to change LWJGL version on 1.13.2

Suspected cause:
---------------------------
There is some error with the configuration settings with 1.13.2

Logs/Screenshots:
----------------------------
![image](https://user-images.githubusercontent.com/21145223/55887798-d128f600-5b73-11e9-802b-96dd54ee4d9c.png)

![image](https://user-images.githubusercontent.com/21145223/55887747-b48cbe00-5b73-11e9-9266-25b9b62d9383.png)

**Comment by Josh74000** [comment]
I don't think 1.13.2 supports the latest LWJGL version

**Comment by ThexXTURBOXx** [comment]
Reproducable on all of my computers

**Comment by peterix** [comment]
This works as intended. Changing LWJGL 3 versions breaks the game.
