### ISSUE TITLE
Can't use securitycraft

### ISSUE THREAD

**Issue by SPACEFACE2394** [MultiMC/MultiMC5#2597]
games crashs every time i try to use something from security craft https://paste.ee/p/d6u0R log

**Comment by Heufneutje** [comment]
```Duplicate enchantment id! class electroblob.wizardry.enchantment.EnchantmentMagicSword and class am2.enchantments.EnchantMagicResist Enchantment ID:100```

You have two mods trying to register an enchantment with the same ID. Check if you can change that in the config file of either mod or tell the mod authors about it.

**Comment by SPACEFACE2394** [comment]
thanks that cleared it up a little but it still has some issues https://paste.ee/p/2rC7i log maybe its still the enchantment

**Comment by SPACEFACE2394** [comment]
sorry wrong log here's the right one https://paste.ee/p/W5lIJ log

**Comment by Heufneutje** [comment]
Not much of interest to see there other than a fatal error occurring in the connection and an error from the authentication server. You could retry or otherwise maybe try signing out and back into your Mojang account in MultiMC.

**Comment by SPACEFACE2394** [comment]
Okay thanks I’ll try that
