### ISSUE TITLE
Fails to download modpack due to cursemeta 404

### ISSUE THREAD

**Issue by martmists** [MultiMC/MultiMC5#2599]
System Information
-----------------------------
MultiMC version: 0.6.5-custom (from AUR)

Operating System: Arch Linux (up to date)

Summary of the issue or suggestion:
----------------------------------------------
MultiMC fails to install a pack when [CurseMeta fails](https://github.com/dries007/CurseMeta/issues/15) and returns a 404

What should happen:
------------------------------
Regardless of the 404, multimc should be able to install the pack (ModpackDownloader) works fine as it doesn't depend on cursemeta

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add mods that cursemeta returns a 404 for to your manifest.json

2. Install the pack

3. Error

Suspected cause:
---------------------------
CurseMeta fails to get the file which multimc depends on, but this shouldn't be required.

**Comment by peterix** [comment]
Depending on curse directly is not an option.

**Comment by peterix** [comment]
In any case, you limked a cursemeta issue. It should be fixed there, not here.

**Comment by peterix** [comment]
https://github.com/dries007/CurseMeta/issues/15
