### ISSUE TITLE
end with code -1

### ISSUE THREAD

**Issue by maxdostick** [MultiMC/MultiMC5#2601]
System Information
-----------------------------
MultiMC version:0.6.5-1302

Operating System:win32

Summary of the issue or suggestion:end with code -1
----------------------------------------------

What should happen:not crash
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.fix the bug

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Heufneutje** [comment]
Use the Upload log button and post the link here.
