### ISSUE TITLE
fresh install, all bottom icons a red "X". cant add account or instance

### ISSUE THREAD

**Issue by stuw2k** [MultiMC/MultiMC5#2604]
System Information
-----------------------------
MultiMC version: 0.6.5-1302

Operating System: win 10 x64

No other settings on MMC changed apart from boosting Max RAM (still had issue at base setting).

Using java x64 1.8.0_192

Summary of the issue or suggestion:
----------------------------------------------
Installed this fresh onto my laptop, used this before (years ago) and had no issues.
Upon installation completion, all 4 logins(?) at the bottom right corner have a red "X". Auth, skin etc.

i cannot add my minecraft account, nor will it find any versions to add, vanilla or otherwise.

its like im not connected to the internet and its blocked off.

there are no proxy settings used, as mentioned it is a fresh install with noprior versions existing beforehand.

What should happen:
------------------------------
all bottom right boxes display green "check" mark and login of minecraft account + vanilla versions available

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.download current version of multimc

2.install

3.open

Suspected cause: firewall maybe? ive looked but cant see anything. system conflict that im not aware of?
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
![multimc](https://user-images.githubusercontent.com/14862609/56125185-40d22300-5f70-11e9-89c3-bb379d4389d6.jpg)

**Comment by AlexTMjugador** [comment]
I think it'd be useful if you attach the MultiMC launch logs to your issue. They are in the MultiMC-0.log file of the MultiMC folder. That way we can know what's going wrong exactly when trying to communicate with Mojang servers.

**Comment by stuw2k** [comment]
[MultiMC-0.log](https://github.com/MultiMC/MultiMC5/files/3080643/MultiMC-0.log)
 here you go

**Comment by stuw2k** [comment]
ok, they have allgone green now. idk why

**Comment by stuw2k** [comment]
still if anyone can see a reason why.....

**Comment by Josh74000** [comment]
I've never had this issue, maybe try changing to the dev option to see if it fixes anything

**Comment by peterix** [comment]
Sounds like some sort of temporary networking error specific to your system? I don't see anything useful in the log, aside from the fact that some requests timed out.

Reopen if still relevant.
