### ISSUE TITLE
Game wont start exiting with error -1

### ISSUE THREAD

**Issue by YungGZ** [MultiMC/MultiMC5#2606]
System Information
-----------------------------
MultiMC version: 0.6.5-1302

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Game crashes, exiting with error -1

What should happen:
------------------------------
Should start

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Start game

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

https://paste.ee/p/EMOgt
Additional Info:
---------------------------

**Comment by tehbasshunter** [comment]
Update to Java 1.8. Fairly certain that's the issue https://java.com/en/download/manual.jsp

**Comment by YungGZ** [comment]
> Update to Java 1.8. Fairly certain that's the issue https://java.com/en/download/manual.jsp

I was there earlier, saw somewhere one of the mods said you should use a java version earlier than 1.8, so then i deleted it and installed the version above.

**Comment by YungGZ** [comment]
But i will try it.

**Comment by tehbasshunter** [comment]
Earlier java is need for some mods but that's for earlier versions than 1.12.2

**Comment by YungGZ** [comment]
Okay, updating back now.
