### ISSUE TITLE
Minecraft snapshots pre-release 3 & 4 are not available to be installed

### ISSUE THREAD

**Issue by sciguyryan** [MultiMC/MultiMC5#2608]
System Information
-----------------------------
MultiMC version: 0.6.5(dev)

Operating System: Windows 10, 64-bit

Summary of the issue or suggestion:
----------------------------------------------
Minecraft snapshots pre-release 3 & 4 are not available to be installed.

What should happen:
------------------------------
Minecraft snapshots pre-release 3 & 4 should be available to be installed.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a new instance (or edit an existing one)

2. Edit the instance to select a new Minecraft version

3. 1.14 pre-3 & pre-4 will not be available to be installed.

Suspected cause:
---------------------------
Unknown.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Janrupf** [comment]
# Cause:
http://ci.multimc.org/builders/meta-update builds are failing.
Thats because Mojang decided to add multiple LWJGL versions to their meta:
- https://github.com/MultiMC/meta-upstream/blob/master/mojang/versions/1.14%20Pre-Release%203.json contains multiple LWJGL versions, which the build script doesn't like

**Comment by peterix** [comment]
Cool. Should be fixed for the real release.

**Comment by bogger33** [comment]
they did it because of this bug, just in case anyone is interested:

https://bugs.mojang.com/browse/MC-144107

**Comment by peterix** [comment]
Well, I am forcing the version to 3.2.1 by default. If you have that particular problem, you should be able to switch to 3.1.6...

Hopefully this just goes away with some future nvidia/KDE update and we can forget it ever happened.

From my POV, this is now resolved.
