### ISSUE TITLE
Doesn't work on Linux...

### ISSUE THREAD

**Issue by SigmaRS** [MultiMC/MultiMC5#2609]
System Information
-----------------------------
MultiMC version: 0.6.5-1217 (stable, not a development version)

Operating System: MX Linux (debian-based)

Summary of the issue or suggestion: Can't load JSON files.
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download MultiMC .deb installer

2. Install MultiMC using dpkg or GDebi

3. Try to run it. (if you open it using the terminal you can get extra info)

4. You can't install MC version or login with your account since the launcher doesn't find the JSON files

Suspected cause:
---------------------------
Maybe the launcher is using an incorrect path? I don't know what happened.

Logs/Screenshots:
----------------------------
https://pastebin.com/iU1c043D
http://i.imgur.com/2GK5zeW.png

**Comment by geertjevandijk** [comment]
It doesn't work on Debian (or MX Linux) you mean. It's running fine on Arch.

Debian dropped the support for SSLv3: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=797926.
`sudo apt install libssl1.0-dev` should be a work-around.

**Comment by wizd3m** [comment]
It doesn't work on Debian (or MX Linux) you mean. It's running fine on Arch.

Debian dropped the support for SSLv3: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=797926.
sudo apt install libssl1.0-dev should be a work-around.

**Comment by SigmaRS** [comment]
Now it's working...
THANK YOU SO MUCH. I'M REALLY GRATEFUL.

**Comment by SigmaRS** [comment]
If you are a dev, please include in Build.MD that "libssl1.0-dev" is a dependency. I had no idea that I needed to install it.
