### ISSUE TITLE
Cannot start instances, MultiMC crashes

### ISSUE THREAD

**Issue by gatlinnewhouse** [MultiMC/MultiMC5#2612]
System Information
-----------------------------
MultiMC version: 0.6.5-custom

Operating System: Arch Linux (64 bit)

Java version: 1.8.0_212

Summary of the issue or suggestion: Bug launching instance
----------------------------------------------
Any time I try to start an instance, the instance does not load and MultiMC crashes.

What should happen:
------------------------------
I should be able to start the instance, vanilla latest version of stable Minecraft, with `jdk8-openjdk`.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch MultiMC

2. Create an instance for vanilla minecraft

3. Try launching it

4. Crash

Suspected cause:
---------------------------
Looks like an issue with "posting message" on Qt.

Logs/Screenshots:
----------------------------
[Log here](https://paste.ee/p/xzUwA)

Additional Info:
---------------------------
This looks like the key error:
```
  389.835 W QString::arg: Argument missing: Error posting message: %s, Connection refused
```

**Comment by peterix** [comment]
Use `multimc-git`
