### ISSUE TITLE
Can't add a new account in Ubuntu 19.04

### ISSUE THREAD

**Issue by canha** [MultiMC/MultiMC5#2614]
Greetings. First of all, thanks for all the hard work!

System Information
-----------------------------
MultiMC version: 0.6.5-1217 lin64 (Installed through the .deb)

Operating System: Ubuntu 19.04 / Kubuntu 19.04

Summary of the issue:
----------------------------------------------
Can't add the minecraft account due to:
`Authentication operation failed due to a network error: Unable to init SSL Context: (99)`

What should happen:
------------------------------
Should be able to configure the account and, afterwards, download a version of Minecraft.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Brand new Ubuntu 19.04 install, brand new install of MultiMC. Launch MultiMC

2. Go to settings, accounts, click add, fill out details.

3. Press OK, get the error: `Authentication operation failed due to a network error: Unable to init SSL Context: (99)`

Suspected cause:
---------------------------
Unsure. Could be some SSL library being used that's not compatible anymore?

**Comment by ThexXTURBOXx** [comment]
This issue appearently even affects the normal Minecraft Launcher and other launchers, as many users reported. I really hope, this will get fixed (although, across the internet, there doesn't seem to be a workaround for users yet :/ )

**Comment by Kastilo** [comment]
I had this issue happen, and from scrolling through previous issues I believe it's an incompatibility with the new dev OpenSSL library (it was updated from 1.0 to 1.1) and other issues #2477 & #2362 mainly support this seeing as 1.0 is required and the _only_ change I could figure out

**Comment by Orochikaku** [comment]
Does anyone know exactly what package can be installed on Ubuntu 19.04 to solve this issue?

**Comment by Kastilo** [comment]
My guess is https://www.howtoforge.com/tutorial/how-to-install-openssl-from-source-on-linux/ and try to find the last version of OpenSSL1.0 and try to follow the steps, but the method I am thinking is experimental, not sure it will work, but OpenSSL is the culprit from testing on my devices

**Comment by R2D2FISH** [comment]
I built MultiMC from source on Xubuntu 19.04 and was able to log in successfully.

**Comment by ThexXTURBOXx** [comment]
Interesting, that this works... Well, we can only hope, that peterix fixes this issue then

**Comment by ThexXTURBOXx** [comment]
Yes, I can confirm, that building MultiMC from source is working.
Am I allowed to upload my build for the people, that need it? I would link it here, if I am allowed to.

**Comment by masternetra** [comment]
Is there a repo with libssl1.0-dev  since it's not available in 19.04's repo?

**Comment by ThexXTURBOXx** [comment]
You could just add cosmic's repo for example.

**Comment by masternetra** [comment]
which one universe?

**Comment by stobbsm** [comment]
Fixed for me by rebuilding MultiMC using the newer libraries available in 19.04. libssl is the culprit, and had an ABI change from 1.0 series to 1.1, requiring a recompile.

After said compilation, working as expected. Flatpak may be good for this.

**Comment by ThexXTURBOXx** [comment]
As it seems like, peterix just needs to Upgrade his Qt to the newest 5.x Release. This Was an ongoing issue in 5.11 and 5.11.3 Fixed this Bug partially and 5.12 fully (Debian got fixed a little bit later).
That's why our recompilations fixed the issue appearently.

**Comment by Real-Gecko** [comment]
I use Arch and confirm that simple recompile solves the issue.

**Comment by stevenskeard** [comment]
I was able to get around this on Pop OS 19.04 by installing the following two packages together:
1. https://packages.debian.org/stretch/libssl1.0-dev
2. https://packages.debian.org/stretch/amd64/libssl1.0.2

**Comment by Janrupf** [comment]
duplicate of #1784, more specifically: https://github.com/MultiMC/MultiMC5/issues/1784#issuecomment-272712807

**Comment by canha** [comment]
Closing this in favour of #1784.
