### ISSUE TITLE
RAMDisking Instances for very fast loading

### ISSUE THREAD

**Issue by unknowntrojan** [MultiMC/MultiMC5#2616]
Summary of the issue or suggestion:
----------------------------------------------
Since RAMDisk programs are pretty widespread and seem to work in a simple manner, I thought MultiMC might profit from this. An Instance normally loads stuff from the disk, sometimes even multiple times. This could theoretically be avoided by either:

- RAMDisking the entire instance for the duration of the game.
- RAMDisking the instance up to the title screen, only speeding up the Forge loading screen.

I would suggest to either use symlinks to a RAMDisk in order to not screw up file versions, etc. or copying the game to the RAMDisk and just copying it back afterwards. This could however present various problems surrounding crashes, OOM scenarios and unexpected shutdowns not being able to recover savedata as it was stored in volatile memory.

What should happen:
------------------------------
The Instance should have far faster load times with an option to load the instance onto a RAMDisk.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Under the Instance's Java or Settings tab, check a box to load onto a RAMDisk.

2. Launch the Instance and watch the copying bar, then watch it launch.

3. Faster instance with almost no chunkloading lag.

**Comment by Orochikaku** [comment]
This is not an issue

**Comment by peterix** [comment]
Sounds fancy, but I don't think this fits into MultiMC. Sounds more like something you should set up yourself.

Symlinks are off limits because of limited (abysmal) support on Windows. Setting up custom filesystems too.
