### ISSUE TITLE
MultiMC crash error 255

### ISSUE THREAD

**Issue by WhateverNameIsAvailable** [MultiMC/MultiMC5#2617]
MultiMC version: 0.6.5-1217

Minecraft folder is:
/home/neo/.local/share/multimc/instances/Automaton-1.5.0-1.12.2/minecraft

Java path is:
/usr/lib/jvm/java-11-openjdk-amd64/bin/java

Java is version 11.0.2, using 64-bit architecture.

Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
Intel Corporation HD Graphics 5500 (rev 09)

Subsystem: ASUSTeK Computer Inc. HD Graphics 5500

Kernel driver in use: i915

OpenGL version string: 4.6.0 NVIDIA 390.116

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /home/neo/.local/share/multimc/instances/Automaton-1.5.0-1.12.2/natives

Libraries:
  /home/neo/.local/share/multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/neo/.local/share/multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/neo/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/neo/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/neo/.local/share/multimc/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  /home/neo/.local/share/multimc/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /home/neo/.local/share/multimc/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /home/neo/.local/share/multimc/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /home/neo/.local/share/multimc/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /home/neo/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /home/neo/.local/share/multimc/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/neo/.local/share/multimc/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/neo/.local/share/multimc/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/neo/.local/share/multimc/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /home/neo/.local/share/multimc/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/neo/.local/share/multimc/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  /home/neo/.local/share/multimc/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /home/neo/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /home/neo/.local/share/multimc/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /home/neo/.local/share/multimc/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /home/neo/.local/share/multimc/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /home/neo/.local/share/multimc/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  /home/neo/.local/share/multimc/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  /home/neo/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/neo/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/neo/.local/share/multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/neo/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/neo/.local/share/multimc/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  /home/neo/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  /home/neo/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  /home/neo/.local/share/multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  /home/neo/.local/share/multimc/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2772/forge-1.12.2-14.23.5.2772-universal.jar
  /home/neo/.local/share/multimc/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  /home/neo/.local/share/multimc/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  /home/neo/.local/share/multimc/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  /home/neo/.local/share/multimc/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  /home/neo/.local/share/multimc/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  /home/neo/.local/share/multimc/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  /home/neo/.local/share/multimc/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  /home/neo/.local/share/multimc/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  /home/neo/.local/share/multimc/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  /home/neo/.local/share/multimc/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  /home/neo/.local/share/multimc/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  /home/neo/.local/share/multimc/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  /home/neo/.local/share/multimc/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  /home/neo/.local/share/multimc/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  /home/neo/.local/share/multimc/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /home/neo/.local/share/multimc/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  /home/neo/.local/share/multimc/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /home/neo/.local/share/multimc/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  /home/neo/.local/share/multimc/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  /home/neo/.local/share/multimc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/neo/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar
  /home/neo/.local/share/multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar

Mods:
  [1.12]MoVillages-1.5.4
  ae2stuff-0.7.0.4-mc1.12.2
  appliedenergistics2-rv6-stable-3
  Aroma1997Core-1.12.2-2.0.0.0
  Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37
  AromaBackup-1.12.2-2.1.1.4
  AutoRegLib-1.3-20
  base-1.12.2-3.10.0
  bdlib-1.14.3.12-mc1.12.2
  BetterBedrockGenerator-1.12-6.1.1
  BetterBuildersWands-1.12-0.11.1.245+69d0d70
  BetterFps-1.4.8
  BetterQuesting-3.5.271
  BetterQuestingTriggerer-1.0
  blockcraftery-0.1.3
  bonsaitrees-1.1.1-b138
  Ceramics-1.12-1.3.4
  Chameleon-1.12-4.1.3
  Chisel-MC1.12.2-0.2.1.35
  chiselsandbits-14.26
  Clumps-3.1.1
  CodeChickenLib-1.12.2-3.2.2.353-universal
  colytra-1.12.2-1.1.0
  CraftTweaker2-1.12-4.1.11
  CTM-MC1.12.2-0.3.2.20
  CustomMainMenu-MC1.12.2-2.0.8
  diethopper-1.1
  elulib-0.1.12
  EnderStorage-1.12.2-2.4.5.135-universal
  engineers_doors-1.12.2-0.8.0
  EngineersWorkshopReborn-1.12.2-1.0.8.37
  environmentaltech-1.12.2-2.0.17.1
  Exchangers-1.12.2-2.8
  ExtraCells-1.12.2-2.6.1a
  FastFurnace-1.12.2-1.1.1
  FastWorkbench-1.12.2-1.5.3
  Faucets and Filters-1.0.2
  foamfix-0.10.2-1.12.2
  furnus-1.12.2-2.1.8
  Guide-API-1.12-2.1.6-61
  Harvest-1.12-1.2.6-18
  IGW-Mod-1.12.2-1.4.4-15-universal
  ImmersiveCables-1.12.2-1.3.2
  ImmersiveEngineering-0.12-86
  immersivepetroleum-1.12.2-1.1.9
  immersivetech-1.12-1.3.10
  InGameInfoXML-1.12.2-2.8.2.94-universal
  Inspirations-1.12.2-0.2.3
  InventoryTweaks-1.63
  ironchest-1.12.2-7.0.40.824
  IvToolkit-1.3.3-1.12
  jei_1.12.2-4.12.1.217
  journeymap-1.12.2-5.5.2
  JustEnoughResources-1.12.2-0.8.5.27
  knobcontrol-1.12-4.0.20
  limelib-1.12.2-1.7.12
  LootTweaker-1.12.2-0.0.8
  LunatriusCore-1.12.2-1.2.0.42-universal
  Mantle-1.12-1.3.3.39
  MCMultiPart-2.5.3
  Mekanism-1.12.2-9.4.13.349
  MekanismGenerators-1.12.2-9.4.13.349
  MekanismTools-1.12.2-9.4.13.349
  ModLister-1.12.2-3.2.4
  modtweaker-4.0.15
  moreoverlays-1.14-mc1.12.2
  Morpheus-1.12-3.3.2
  MouseTweaks-2.8-mc1.12.1
  MTLib-3.0.5
  NetherPortalFix_1.12.1-5.3.17
  OreExcavation-1.4.129
  p455w0rdslib-1.12-2.0.35
  platforms-1.12.0-1.4.6
  Quark-r1.5-130
  RebornCore-1.12.2-3.10.2.337-universal
  RecurrentComplex-1.4.7
  RedstoneFlux-1.12-2.1.0.6-universal
  ResourceLoader-MC1.12.1-1.5.3
  RoguelikeDungeons-1.12.2-1.8.0
  shetiphiancore-1.12.0-3.5.8
  SimpleCorn1.12-1.12-2.4.1
  SimpleOreGeneration-4.3.2 mc 1.12.2
  StandardExpansion-3.4.145
  stg-1.12.2-1.2.3
  StorageDrawers-1.12.2-5.3.7
  theoneprobe-1.12-1.4.25
  tinyprogressions-1.12.2-3.3.31-Release
  tombmanygraves2api-1.12.2-1.0.0
  usefulnullifiers-1.5.0
  valkyrielib-1.12.2-2.0.17.3
  ViesCraft-1.12.2-5.9.13
  Waystones_1.12.2-4.0.67
  WearableBackpacks-1.12.2-3.1.3
  weirdinggadget-1.12.2-2.0.5-universal
  WirelessCraftingTerminal-1.12.2-3.9.68
  woot-1.12.2-1.4.6
  Xtones-1.12-1.0.8-11

Params:
  --username  --version MultiMC5 --gameDir /home/neo/.local/share/multimc/instances/Automaton-1.5.0-1.12.2/minecraft --assetsDir /home/neo/.local/share/multimc/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Xms2048m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 32696

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code 255.
MultiMC: Log upload triggered at: 20 Apr 2019 19:56:39 +0200

**Comment by tehbasshunter** [comment]
You need Java 8. Modded doesn't work with anything higher than that.

**Comment by WhateverNameIsAvailable** [comment]
I have thought about that. I tried installing java 8 but I get "package oracle-java8-installer is not available but another package refers to it"

**Comment by tehbasshunter** [comment]
I'll have to leave the specific version you need to the Linux people. All I know is that's the problem.

**Comment by WhateverNameIsAvailable** [comment]
I'll try googling some more. Maybe I can find a solution.

**Comment by WhateverNameIsAvailable** [comment]
I managed to install j8 and it runs now.
