### ISSUE TITLE
Crashing 2 seconds after clicking Launch

### ISSUE THREAD

**Issue by MateiSR** [MultiMC/MultiMC5#2620]
System Information
-----------------------------
MultiMC version: 0.6.5-custom

Operating System: Manjaro

Summary of the issue or suggestion: I just click launch and after 2 seconds multimc will disappear(crash) and no minecraft/java instance will be started. Also no console log before crashing.
----------------------------------------------

What should happen:
------------------------------
Start the game

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. 

2.

3.

Suspected cause:
---------------------------
-

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/VYCmv

Additional Info:
---------------------------

**Comment by dawk42** [comment]
I have also been getting this same issue 

[https://pastebin.com/7g5jrRxu](url)

running Manjaro updated and freshly restarted
16G ram
AMD 1700X
MSI GTX 970

I can launch java edition without MultiMC and I can launch my modded games with ATLauncher, but both types of games crash MultiMC.  I have tried recompiling from the AUR and get the same results

**Comment by MateiSR** [comment]
Fix provided by **dawk42** worked, just follow the guide [https://github.com/MultiMC/MultiMC5/blob/develop/BUILD.md](here). Cheers!
