### ISSUE TITLE
Unable to use wrapper script

### ISSUE THREAD

**Issue by liketechnik** [MultiMC/MultiMC5#2621]
System Information
-----------------------------
MultiMC version:
0.6.5 (latest development, build from source)
Operating System:
Linux (Gentoo)
Summary of the issue or suggestion:
----------------------------------------------
When using a wrapper script MultiMC tries to launch MC via the wrapper script and fails with 'The process failed to start. Could not launch minecraft!'. To be sure it isn't my script's fault, I just made another one containing only `exec "$@"`, which resulted in the same error.

What should happen:
------------------------------
MultiMC should give the correct arguments to the wrapper script which then launches MC.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a script containing `exec "$@"`.

2. Set this script as wrapper in an instance's settings.

3. Launch the instance.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
https://gitlab.com/snippets/1850495

Additional Info:
---------------------------
The path to the script or the instance does not contain whitespace, the script itself is executable and MultiMC has the right path to the script.

**Comment by QuImUfu** [comment]
this script (for disabling vsync) works:
```
#!/bin/bash
env vblank_mode=0 $@
```
exec seems not to work. See:  
https://github.com/MultiMC/MultiMC5/issues/2468

**Comment by liketechnik** [comment]
Yes, I'm using bash. I'm not sure what exactly is causing this issue, because manually executing the script works flawlessly, only MultiMC reports an error back when using it.

**Comment by liketechnik** [comment]
So I just added `notify-send running` as the first line of the script. When executing the script manually I get the expected desktop notification. When running with MultiMC I don't get the notification but just the error, meaning that MultiMC fails to call the script, although the path is correct and it is executable (changing one letter in the path leads to MultiMC complaining about the fact the specified script does not exist, which is correct behaviour).

I think the interesting line from the log is Line [494](https://gitlab.com/snippets/1850495#L494) where it says 'Unexpected null receiver' right after executing the script, so my guess is something in the code calling the script is broken at the moment.

P.S.: I just saw that the link to the log was invisible (my bad), so here it is again: https://gitlab.com/snippets/1850495 (now also visible in the description).

**Comment by peterix** [comment]
Your script should be executable and contain this as the first line:
```
#!/bin/bash
```

Does it?

**Comment by liketechnik** [comment]
Yes, it does.
```
#!/bin/bash
notify-send running
$@
```
Running in terminal:
```
$ ./script.sh ls -l # just as an example
total 0
-rw-r--r-- 1 florian florian 0 Apr 24 19:25 file1
-rw-r--r-- 1 florian florian 0 Apr 24 19:25 file10
-rw-r--r-- 1 florian florian 0 Apr 24 19:25 file2
-rw-r--r-- 1 florian florian 0 Apr 24 19:25 file3
-rw-r--r-- 1 florian florian 0 Apr 24 19:25 file4
-rw-r--r-- 1 florian florian 0 Apr 24 19:25 file5
-rw-r--r-- 1 florian florian 0 Apr 24 19:25 file6
-rw-r--r-- 1 florian florian 0 Apr 24 19:25 file7
-rw-r--r-- 1 florian florian 0 Apr 24 19:25 file8
-rw-r--r-- 1 florian florian 0 Apr 24 19:25 file9
``` 
(Simultaneously desktop notification with text "running")

**Comment by QuImUfu** [comment]
1. Zusaetzlich-installierte-Programme - bester Ordnername :D
2. Was ist wenn du /bin/bash {dein scriptname} anstatt nur {dein scriptname} als wrapper-command benutzt?

**Comment by liketechnik** [comment]
Jap, das funktioniert. Ich vermute zsh als Standardshell macht da Probleme oder das Skript muss im PATH liegen. Wieso ich das nicht mal ausprobiert hab? :D Auf jeden Fall ein fettes Dankeschön.

English: Prepending /bin/bash before the script name fixes the problem. Because I have set zsh as my standard shell I believe this causes issues? Or does the script need to be in my PATH environment variable to be executed by MultiMC?

**Comment by QuImUfu** [comment]
Hab mich durch den Sourcecode gewühlt. [execve](https://linux.die.net/man/2/execve) wird im Endeffekt dazu genutzt das Script zu starten. Eigentlich sollte das immer funktionieren.  
Kannst du mal nachsehen was `file /bin/bash` dir ausgibt?

English: Looked through the code [execve](https://linux.die.net/man/2/execve) is used to execute the script in the end. That should always work. 
Can you post the output of `file /bin/bash`?

**Comment by liketechnik** [comment]
Okay, it's working now (even without /bin/bash prepended). It's possible I'm a big idiot and missed a '!' somewhere. I'm really sorry for wasting your time :/
