### ISSUE TITLE
MultiMC does not let you change the lwjgl version

### ISSUE THREAD

**Issue by bogger33** [MultiMC/MultiMC5#2623]
System Information
-----------------------------
MultiMC version: 0.6.5-develop-1223

Operating System:

debian testing

Summary of the issue or suggestion:
----------------------------------------------

you cannot change the lwjgl version for minecraft 1.14, which is annoying in my case because it means I'm going to experience this bug:

https://bugs.mojang.com/browse/MC-144107

What should happen:
------------------------------

version is changed

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Edit an instance (vanilla minecraft, mine is 1.14)

2. in the version tab, select "LWJGL 3"

3. click "change version"

4. select 3.1.6 (or any other one)

5. click OK

version is not changed. I closed and reopened multimc to make sure this isn't just a graphical error. 

Suspected cause:
---------------------------
I found #2596 which may be related. but in 1.14, multimc forces lwjgl 3.2.1 even though minecraft ships with 3.1.6 (see also #2608). This can cause problems because of this bug:

https://bugs.mojang.com/browse/MC-144107

**Comment by CGDoctor8** [comment]
Also trying to manual edit LWJGL to a config of 1.3.2 (3.1.6) will crash lutris
`./MultiMC-4.log:  134.443 D "Req: org.lwjgl3 == 3.2.1" already has different version that can be changed.
./MultiMC-4.log:  134.443 D Setting version of  "org.lwjgl3" to "3.2.1"
./MultiMC-4.log:  134.443 D "Req: org.lwjgl3 == 3.2.1" already has different version that can be changed.
./MultiMC-4.log:  134.443 D Setting version of  "org.lwjgl3" to "3.2.1"
./MultiMC-4.log:  134.443 D "Req: org.lwjgl3 == 3.2.1" already has different version that can be changed.
`

**Comment by peterix** [comment]
This is not a bug.

**Comment by gniftygnome** [comment]
> This is not a bug.

Mojang has "resolved" their bug by downgrading LWJGL.  If this is not a bug, please provide some work-around or persuade Mojang to pick a different fix.  I really like MultiMC but Minecraft 1.14 is not playable with LWJGL 3.2.1 for myself and others...

Attempts at pointer capture by the window manager or other program (like x2x) cause nearly random camera movement.  One moment you are mining happily Eastward in the Nether and the next moment you have broken the block below you and fallen to your death in lava.

**Comment by gniftygnome** [comment]
Just a note for any others here; it is possible to change the LWJGL version to 3.2.2 as described by Dinolek in https://bugs.mojang.com/browse/MC-144107 and that does resolve the problem.  Hopefully Minecraft will soon change to 3.2.2 and MultiMC will not override it with broken 3.2.1 but (for now) there is a work-around.

**Comment by peterix** [comment]
WAI

**Comment by DuendeInexistente** [comment]
It may be "Working as intended", but the intended working in this case causes a glitch to happen because it conflicts with the fix applied by the actual devs of the game, and makes the game unplayable.
just add an exception so we can pick a different LWJGL version in 1.14/.15, jeez. Or give us a checkbox  so we can force it on any version.
I tried manually adding a patch json that's just the 3.1.2 json copypasted and multimc crashed, is that "Working as intended" too?

**Comment by Zetabite** [comment]
IDK what you mean, i can choose version from 3.1.2 to 3.2.2

**Comment by DuendeInexistente** [comment]
> IDK what you mean, i can choose version from 3.1.2 to 3.2.2

![Peek 2020-01-20 19-48](https://user-images.githubusercontent.com/20157727/72762317-e7151e00-3bbd-11ea-88b1-e5dfcb953639.gif)

**Comment by Zetabite** [comment]
hm, why would you change the version? mine is on 3.2.2 and runs perfectly fine

**Comment by Blafy** [comment]
> hm, why would you change the version? mine is on 3.2.2 and runs perfectly fine

There is a camera bug related to the lwjgl version. See here : https://bugs.mojang.com/browse/MC-144107

It occurs with linux versions, and it is really annoying. It is almost unplayable, as the camera orientation resets itself randomly. I have it on my system too

**Comment by Zetabite** [comment]
Did you even try the workaround

**Comment by Blafy** [comment]
Disabling the raw input ? Yes, it doesn't work anymore, see the last comments in the link above.

**Comment by DuendeInexistente** [comment]
> Disabling the raw input ? Yes, it doesn't work anymore, see the last comments in the link above.

Killing unclutter ended up solving it, it's a program that hides the mouse pointer when it's not moving, and it must've been trying to wrestle control away from LWJGL for some reason.

Add 'pkill unclutter -e -i -9' to your pre-launch commands and see if that solves it.

**Comment by Blafy** [comment]
Actually, the problem occured only when I was using a non-native resolution in-game !
Changing it OS-side fixed it for me.

**Comment by DuendeInexistente** [comment]
To the pre-launch commands, I mean. Not arguments.

**Comment by DuendeInexistente** [comment]
Killing unclutter ended up solving it for me. Just add ʾpkill unclutter -i
-9ʾ to the pre-launch arguments. Maybe start it again when the game ends.
It's a program that hides the mouse pointer when you don't move it, it must
be trying to wrestle control away from lwjgl or something.
