### ISSUE TITLE
Segfault when launching instances

### ISSUE THREAD

**Issue by williewillus** [MultiMC/MultiMC5#2624]
System Information
-----------------------------
MultiMC version: 0.6.5 (AUR version)

Operating System: Arch Linux

Summary of the issue or suggestion:
----------------------------------------------
Segfault when launching a vanilla instance set to 1.14-pre5. Seems to happen for 1.14 and 1.13.2 release as well. I had just been prompted to log in again before launching the first instance, since I hadn't used multimc on this computer in a while. After I put my password in, the crashes began.

What should happen:
------------------------------
No crash

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create new instance and set it to 1.14.

2. Try to launch it

Suspected cause:
---------------------------
Appears to have to do with auth?

Logs/Screenshots:
----------------------------
Log + backtrace: https://gist.github.com/williewillus/d4ff982b11221765b7315a2eb4a959d9

Additional Info:
---------------------------

**Comment by Celivalg** [comment]
This exact same thing happened to me just after I installed the latest updates on manjaro. Was working fine hours before that.

**Comment by flcmc** [comment]
See the pinned commend on the [AUR package](https://aur.archlinux.org/packages/multimc5).

**Comment by peterix** [comment]
This seems to be fixed.
