### ISSUE TITLE
MultiMC launches Microsoft Minecraft Windows and not the desired instance

### ISSUE THREAD

**Issue by Sheldor5** [MultiMC/MultiMC5#2625]
When launching any instance (e.g. ATM3) in MultiMC, the selected Minecraft Version (Vanilla) from Microsoft Minecraft Installation is launched and not the selected MultiMC instance.

Selecting the proper Version in Microsoft Minecraft, closing it and launching the instance in MultiMC launches the desired Minecraft instance.

So the selection of Microsoft Minecraft somehow overwrites the instances in MultiMC?!?!

**Comment by nift4** [comment]
What is Microsoft Minecraft?? Vanilla Launcher?

**Comment by Sheldor5** [comment]
Yes the Vanilla Launcher (the new one from Microsoft)

**Comment by peterix** [comment]
No. You must be using something else.

**Comment by peterix** [comment]
Where did you get this 'MultiMC'?

**Comment by Sheldor5** [comment]
I downloaded it from here (this github repo) ...

**Comment by Janrupf** [comment]
Ok, something is going wrong here. Please download form https://multimc.org, unpack the archive and try again. What you are describing is impossible.
