### ISSUE TITLE
My save vanished

### ISSUE THREAD

**Issue by HunterWep** [MultiMC/MultiMC5#2626]
System Information
-----------------------------
MultiMC version: 5

Operating System: Windows 10

Summary of the issue or suggestion: issue: save vanished from minecraft, but it's still at save's folder
----------------------------------------------

What should happen: not sure
------------------------------

Suspected cause: probably bug
---------------------------

Logs/Screenshots: http://prntscr.com/nggyz1 (sorry, everything is in portuguese)
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
Well, that's a corrupted world.
You could probably try salvaging it, butr that depends on how bad the corruption is.
