### ISSUE TITLE
multimc forge bug

### ISSUE THREAD

**Issue by BiisLaaM** [MultiMC/MultiMC5#2627]
rying to add a new instance but after creating it and clickin on install forge it loads to 100%
and stays blank refreshing doesnt help neither uninstalling.
worked fine in the past but now i dont know what to do
![msc](https://user-images.githubusercontent.com/29259823/56728282-b8633780-6752-11e9-96ec-bfba5c3762f8.png)

**Comment by Distroyer2601** [comment]
This happens to me too. I dont know how can i fix it

**Comment by BiisLaaM** [comment]
@Distroyer2601  got a solution ? or not

**Comment by Distroyer2601** [comment]
no Im sorry

**Comment by Gregoryo7** [comment]
This happens to me too.

**Comment by peterix** [comment]
Is this still happening?

**Comment by Distroyer2601** [comment]
@peterix Yes. Still happening

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, please reproduce the issue and provide the logs. We cannot diagnose anything without them.
