### ISSUE TITLE
MultiMC Logging Me in Offline

### ISSUE THREAD

**Issue by janagyjr** [MultiMC/MultiMC5#2629]
System Information
-----------------------------
MultiMC version:
0.6.5-1217

Operating System:
Debian 9

Summary of the issue or suggestion:
----------------------------------------------
With proxy set to 'none' MultiMC only logs me in as 'offline'. I have an active connection to the Internet, no proxy setup. I cannot get MultiMC to see this.

What should happen:
------------------------------
Recognize my Internet connection and login as online.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install on Debian 9

2. Launch

3. Try to launch an MC instance.

Suspected cause:
---------------------------
Don't know

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

![image](https://user-images.githubusercontent.com/23646259/56778909-44e71780-679e-11e9-89a2-193d4c343299.png)

Additional Info:
---------------------------

**Comment by QuImUfu** [comment]
Please post MultiMC-0.log.

**Comment by janagyjr** [comment]
[MultiMC-0.log](https://github.com/MultiMC/MultiMC5/files/3119441/MultiMC-0.log)

**Comment by QuImUfu** [comment]
Duplicate of https://github.com/MultiMC/MultiMC5/issues/1816. Try the workarounds mentioned there.

**Comment by janagyjr** [comment]
That fixed it, specifically installing 

> libssl1.0-dev

and no symlinks.
