### ISSUE TITLE
MultiMC crashes with Forge or Liteloader

### ISSUE THREAD

**Issue by idkwasgoinon** [MultiMC/MultiMC5#2630]
System Information
-----------------------------
MultiMC version: 0.6.5-1234 

Operating System: mac osx64 version 10.14

Summary of the issue or suggestion:
----------------------------------------------
Minecraft launches fine without Forge or Liteloader, but if either of those are installed—no matter the Minecraft version—the game crashes. Exits with -1, code 255. Included is the log, attached below.

What should happen: 
------------------------------
It should launch with either Forge or Liteloader (although Forge matters more to me here).

Logs/Screenshots:
----------------------------
https://paste.ee/p/XNelg

[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by tehbasshunter** [comment]
Switch to Java 8. Anything higher is not designed for modded atm.

**Comment by idkwasgoinon** [comment]
@tehbasshunter I've tried downloading Java 8 (Java SE Runtime Environment 8u212) but it MultiMC still says I am using Java version 9.0.1

**Comment by idkwasgoinon** [comment]
NVM fixed!!! I installed the 201 update and was then able to find it among the other java versions, and then I just had to change the path in MultiMC settings to go through Java 8 instead of 9. Thanks!
