### ISSUE TITLE
Cant login to minecraft account.

### ISSUE THREAD

**Issue by Rokutiz** [MultiMC/MultiMC5#2631]
System Information
-----------------------------
Rtx 2080 windforce
I9-9900k
32 GB DDR4 3000 Mhz
and other shady things

MultiMC version:
0.6.5-1217 on lin64
Operating System:
Pop_os! 19.04

Summary of the issue or suggestion:
----------------------------------------------
cant logic i get Authentication operation failed due to a network error: Unable to init SSL Context (99)

What should happen:
------------------------------
I should be able to login.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Install MultiMC

2.Try to add an account

3.

Suspected cause:
---------------------------
Not sure. first time linux user.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by tehbasshunter** [comment]
https://github.com/MultiMC/MultiMC5/issues/1784#issuecomment-272712807

**Comment by dedilson995-sys** [comment]
Dhdjrhfbnfbb
