### ISSUE TITLE
Error 1 pls help

### ISSUE THREAD

**Issue by hackexblog** [MultiMC/MultiMC5#2632]
{Getting error 1!}

MultiMC version: 0.6.5-1302

Minecraft folder is:
C:/Users/FAMILY/Desktop/MultiMC/instances/1.2.5/.minecraft

Java path is:
C:/Program Files (x86)/Java/jre1.8.0_211/bin/javaw.exe

Java is version 1.8.0_211, using 32-bit architecture.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  

Native path:
  C:/Users/FAMILY/Desktop/MultiMC/instances/1.2.5/natives

Traits:
traits legacyLaunch
traits texturepacks

Libraries:
  C:/Users/FAMILY/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/FAMILY/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/FAMILY/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.3/lwjgl-2.9.3.jar
  C:/Users/FAMILY/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.3/lwjgl_util-2.9.3.jar
  C:/Users/FAMILY/Desktop/MultiMC/libraries/com/mojang/minecraft/1.2.5/minecraft-1.2.5-client.jar

Native libraries:
  C:/Users/FAMILY/Desktop/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/FAMILY/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.3/lwjgl-platform-2.9.3-natives-windows.jar

Params:
  

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx2048m, -Duser.language=en]

Minecraft process ID: 1312

Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Process exited with code 1.
Clipboard copy at: 26 Apr 2019 00:51:08 -0500

**Comment by Heufneutje** [comment]
> Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.
That is your issue.

**Comment by hackexblog** [comment]
thx
