### ISSUE TITLE
MultiMC5/OneSixLauncher does not work well with Eclipse OpenJ9 on macOS?

### ISSUE THREAD

**Issue by 3TUSK** [MultiMC/MultiMC5#2634]
System Information
-----------------------------
MultiMC version: 0.6.5-1243 on osx64

Operating System: macOS High Sierra 10.13.6

Summary of the issue or suggestion:
----------------------------------------------
If I use Eclipse OpenJ9 (from https://adoptopenjdk.net/) to launch a Minecraft 1.12.2 instance (with Forge 14.23.5.2811 and several mods installed), it will fail before the game window even appears, claiming that it cannot find `lwjgl` in system property `java.library.path`.

What should happen:
------------------------------
Game launches.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. `brew tap AdoptOpenJDK/openjdk && brew cask install adoptopenjdk8-openj9` or equivalent method to install the latest OpenJDK8-OpenJ9 to the machine.
2. Verify that OpenJ9 is correctly installed by `java -version`.
3. Tell MultiMC to use `/usr/bin/java`.
4. Launch the game. Game launching should stopped with non-zero exit code and `Caused by: java.lang.UnsatisfiedLinkError: lwjgl (Not found in java.library.path)` should be appeared in the log.

Suspected cause:
---------------------------
Unavailable. Personally I believe it falls into the OneSix launcher that MultiMC uses. No further researches are conducted due to time constraints.

Logs/Screenshots:
----------------------------
https://paste.ubuntu.com/p/k59JrmsG9x/

Additional Info:
---------------------------
1. Switching back to a regular HotSpot JDK (`brew cask install adoptopenjdk8`) makes it work.
2. Tried a Minecraft 1.14 instance (with [Fabric Loader 0.4.4-build138](http://fabricmc.net/use/)) with the same OpenJ9 JDK installed, and it somehow worked (i.e. game launched without error). One major observable difference is that the `natives` folder under the 1.14 instance has all required native libs extracted out.

**Comment by Ghalid** [comment]
This is not a MultiMC issue; it was an issue with OpenJ9. See https://github.com/AdoptOpenJDK/openjdk-build/issues/1056.

**Comment by 3TUSK** [comment]
Guess I can safely close this issue then…
