### ISSUE TITLE
Doesnt even start a minecraft instance

### ISSUE THREAD

**Issue by Rokutiz** [MultiMC/MultiMC5#2635]
System Information
-----------------------------
Rtx 2080 windforce
I9-9900k
32 GB DDR4 3000 Mhz
and other shady things

MultiMC version:
0.6.5-1217 on lin64

Operating System:
Pop_os! 19.04

Summary of the issue or suggestion:
----------------------------------------------
trying to launch Sky Factory 4 results in not starting up
Error:
https://hastebin.com/yorokanohi.sql

What should happen:
------------------------------
i should be able to launch minecraft

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Start multimc

2.Double click on modpack

3.

Suspected cause:
---------------------------
Java?

Logs/Screenshots:
----------------------------
https://paste.ee/p/F1Dq8

Additional Info:
---------------------------
javac version: 11.0.3
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu1, mixed mode, sharing)

**Comment by flcmc** [comment]
Use Java 8. Modded MineCraft doesn't work after Java 8.

**Comment by Rokutiz** [comment]
Do you know what package name it has bcs sudo apt install openjdk-8-jdk doesnt work

**Comment by Janrupf** [comment]
This should help: http://tipsonubuntu.com/2016/07/31/install-oracle-java-8-9-ubuntu-16-04-linux-mint-18/

**Comment by Rokutiz** [comment]
i tried following this but it gives me
Package oracle-java8-installer is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'oracle-java8-installer' has no installation candidate

**Comment by Janrupf** [comment]
weird, but google should also solve that issue for you

**Comment by flcmc** [comment]
Here's a [link](https://askubuntu.com/questions/1135045/how-to-install-the-openjdk-8-ubuntu-19-04) for Ubuntu 19.04

**Comment by QuImUfu** [comment]
in what way does `sudo apt install openjdk-8-jdk` not work?

**Comment by Rokutiz** [comment]
Aight the minecraft started for some reason ppa didnt work for me...
