### ISSUE TITLE
Unable to add OptiFine (edit button does nothing)

### ISSUE THREAD

**Issue by sangimed** [MultiMC/MultiMC5#2636]
System Information
-----------------------------
MultiMC version: `0.6.5 -1302 on win32 - MultiMC 5`

Operating System: `Windows 10 x64`

Summary of the issue or suggestion:
----------------------------------------------
Clicking on the `edit` button does nothing when trying to install optifine by following [the wiki page](https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine) (Minecraft versions that don't have Forge).

![Screenshot_2](https://user-images.githubusercontent.com/857405/56854800-a349fc80-693c-11e9-8842-62de5a5d14de.png)

What should happen:
------------------------------
Clicking `Edit` should open a json file in a text editor.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Make a new instance in MultiMC with the wanted version of Minecraft (`1.13.2`).

2. Click `Edit Instance`

3. Click `Add Empty`.

4. Set uid to `optifine.OptiFine` and name to `OptiFine`.

5. Select the newly created component and click `Edit` - this should open the file in a text editor.

**Comment by spannerman79** [comment]
> Clicking `Edit` should open a json file in a text editor.

Do you have a file association for `.json` files assigned? That is done outside of MultiMC and on the OS side.  I suggest [Atom](https://atom.io/) or [Notepad++](https://notepad-plus-plus.org/download/) to edit such files.

**Comment by spannerman79** [comment]
@sangimed did the above comment of mine resolve your issue?

**Comment by little-hophop** [comment]
If you want to install Optifine for Minecraft using MultiMC you could also do this:
1. Download the correct Optifine version
2. Open the normal Minecraft launcher once on the correct version (1.13.2 in this case) (you can close Minecraft again afterwards)
3. Open the downloaded Optifine .jar file
4. Once it is open click on 'Extract'
5. Once it is extracted you should have a new Optifine .jar file with the same name as the one you extracted except this one has _MOD added at the end
6. Open MultiMC
7. Create/Open an instance with the correct version (in this case 1.13.2)
8. Click on 'Edit Instance'
9. Click on 'Add to Minecraft.jar'
10. Select the Optifine file which you extracted (the one with _MOD at the end)
11. Launch the instance

**Comment by spannerman79** [comment]
> 9\. Click on 'Add to Minecraft.jar'

No @little-hophop read https://github.com/MultiMC/MultiMC5/wiki/Jar-Modding

**Comment by little-hophop** [comment]
It worked this way for me, and I already read that page and didn't really understand some stuff

**Comment by ScottoMotto** [comment]
@little-hophop is sharing a perfectly valid way to install Optifine in MMC when not using a mod loader. In fact, this is the preferred method of install for 1.14.3 (and up?)

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
