### ISSUE TITLE
Unable to launch 1.6.4 modpacks, gives double loading bar, then kills itself.

### ISSUE THREAD

**Issue by robocart9** [MultiMC/MultiMC5#2637]
**System Information**

_MultiMC version:_
0.6.5-develop-1308, MultiMC 5
_Operating System:_
Windows 64-bit Operating system.

**Summary of the issue or suggestion:**

Whenever I try to load 1.6.4 modpacks, it gives the loading bar that it normally shows when extracting extra data files and packages twice, then doesnt do anything for a few seconds, then kills itself. No log provided, just a few seconds of silence, and the Kill and greyed out Launch Online buttons return to Launch and Launch offline. I assume this mean sit kills itself in the process.

**What should happen:**

The bar should only appear once, extract the needed files and libraries, then show log window and attempt to load.

**Steps to reproduce the issue (Add more if needed):**

1. Try to initiate 1.6.4 modpacks [I have only tried Crash Landing and Tech World 2 so far, and gave up trying to load those two]

2. Watch
**Suspected cause:**

Unknown

**Logs/Screenshots:**

Log window does not open, so I cannot provide logs

Additional Info:
---------------------------
So far only 1.6.4 is doing this for me, And I have already refered to and tried solutions on Java 8u20 fix - Forge part #547 and Unable to launch java.util.ConcurrentModificationException #643 for another issue on this version, Unable to tell if past issue was fixed, as now it wont even attempt to extract or load the modpacks. I have also used the Beta title match thing, and found no other helping articles through it.
Running Java 8, and latest 1.6.4 forge version.

**Comment by QuImUfu** [comment]
does this happen with vanilla 1.6.4 as well?

**Comment by cheesehead544** [comment]
i've experienced trouble launching 1.6.4 pack(including crash landing) on java 8 as well. i'm not sure if it's the same problem but in my case selecting the newest supported version of LWJGL 2 and forge(forge 9.11.1.1345 for 1.6.4 i believe) fixed it. i think updating LWJGL wasn't necessary but i havent tested any further after updating them both.

**Comment by peterix** [comment]
This is an ancient forge bug. Update forge or use the legacyjavafixer mod.

**Comment by robocart9** [comment]
I have the latest forge, and i am attempting to run modpacks, in which i dont know how to add mods into.
