### ISSUE TITLE
Add "Install Fabric" Button

### ISSUE THREAD

**Issue by nift4** [MultiMC/MultiMC5#2639]
System Information
-----------------------------
MultiMC version: 0.6.5-stable

Operating System: Ubuntu GNU/Linux 19.04 Linux 5.0.0

Summary of the issue or suggestion:
----------------------------------------------
Please add a "Install Fabric" button like "Install Forge".

What should happen:
------------------------------
??

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC

2. Edit an instance.

3. No "Install Fabric" button available.

Suspected cause:
---------------------------
Feature not added.

Logs/Screenshots:
----------------------------

Additional Info:
---------------------------
Fabric has a MultiMC instance "generator" that generates URLs like this: `https://fabricmc.net/download/multimc?yarn=1.14+build.6&loader=0.4.6+build.141`

And if you add `&format=patchJson` you get a patch json. (No idea what this is ;))

**Comment by loper12** [comment]
You are using the BUG template. You do not need this template for a feature.

**Comment by asiekierka** [comment]
@peterix There are two routes that can be undertaken to support this, now that we have finally moved the "Yarn version issue" (with one mapping version per game version) greatly simplifying the user-side experience:

* Use the Fabric Meta API to both query versions and get the installer JSON data, with MultiMC building the resulting patch .JSON,
* Use the Fabric Meta API to query versions and the fabricmc.net API to download a prebuilt patch .JSON in MultiMC's format.

Which one would you side with?

**Comment by peterix** [comment]
Basically neither, but possibly either of them applied to https://github.com/MultiMC/meta instead.

**Comment by peterix** [comment]
In MultiMC, it should just be one more button that adds a `fabric` component to the instance.

**Comment by asiekierka** [comment]
The only problem I see in practice is that there are two components: one provides the mappings (Intermediary, there is only one version of it per Minecraft version), and one provides the mod loader (which is not dependent on a Minecraft version).

In effect, how MultiMC would have to act, to avoid an O(n^2) scalability for the data, is query the list of Intermediary mapping versions to figure out if a version of Minecraft is supported, then just list the compatible (for now - all) Loader versions.

**Comment by asiekierka** [comment]
Further progress depends on https://github.com/MultiMC/meta/pull/1

**Comment by peterix** [comment]
Aand this should land in develop soon :)
