### ISSUE TITLE
UPDATE THE VERSION

### ISSUE THREAD

**Issue by jaguar334** [MultiMC/MultiMC5#2642]
the version has been 1.12.1 for too long there is pandas now and we can't see them because you guys won't update it????? everyone wants an update right I mean RIGHT?

**Comment by peterix** [comment]
Update what?  It's right there...

![image](https://user-images.githubusercontent.com/203326/57027817-b95a0480-6c3d-11e9-8e0d-aaaf66fb9dd2.png)

**Comment by jaguar334** [comment]
how do I update it?

**Comment by jaguar334** [comment]
mine is in 1.12.1 and it won't update
