### ISSUE TITLE
MultiMC Keeps Crashing

### ISSUE THREAD

**Issue by ray27890** [MultiMC/MultiMC5#2645]
https://paste.ee/p/U9JM1
I don't know why it keeps crashing every time I launch it. Can someone help?

**Comment by P3rf3ctXZer0** [comment]
Use this https://javadl.oracle.com/webapps/download/AutoDL?BundleId=238729_478a62b7d4e34b78b671c754eaaf38ab

**Comment by P3rf3ctXZer0** [comment]
Its the x64 release - make sure you install it.

**Comment by ray27890** [comment]
Thanks!

**Comment by ray27890** [comment]
Update: This crash is still happening although I've downloaded what you linked @P3rf3ctXZer0 
Any other advice?

**Comment by P3rf3ctXZer0** [comment]
Can you launch vanilla Minecraft?

**Comment by P3rf3ctXZer0** [comment]
I also have far more experience with 1.12.2 I have not used 1.8.9 in legit forever.

**Comment by ray27890** [comment]
Sorry for the late reply, Vanilla minecraft does indeed launch up. @P3rf3ctXZer0

**Comment by ray27890** [comment]
Issue resolved! All my mods were duplicated in a folder, causing the crash.
