### ISSUE TITLE
[MMC-bug] Launcher can't use QT networking libraries

### ISSUE THREAD

**Issue by Synergyst** [MultiMC/MultiMC5#2647]
System Information
-----------------------------
MultiMC version: 0.6.5-1217-stable

Operating System: Linux 64-bit, Debian 10 Buster

Summary of the issue or suggestion:
----------------------------------------------
Launching MultiMC 5 no longer works with networking after upgrading to Debian 10 Buster.

What should happen:
------------------------------
MultiMC 5 should connect to the auth, session, skins, API, and news feed servers.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install fresh version of Multi-MC 5 (generic 64-bit)

2. Launch Multi-MC 5 via non-root user command-line

3. After configuration the launcher refuses to initialize any network connections

Suspected cause:
---------------------------
It is most likely a QT library dependency issue..
Perhaps this can be resolved by requiring the binary to use the system libraries instead? (refer to LDD output)

Logs/Screenshots:
----------------------------
Console log: https://pastebin.com/raw/jbeXWbaA

LDD output: https://pastebin.com/raw/ie20uYQP

Additional Info:
---------------------------
Please let me know if I need to add any information which may be relevant to this type of issue.

**Comment by Synergyst** [comment]
I can confirm that using the system's libraries compared to the redistributable ones packaged with MultiMC 5 are working fine!
Obviously this is only after manually cloning the repo, then building the launcher..

**Comment by nift4** [comment]
https://github.com/MultiMC/MultiMC5/issues/1816#issuecomment-487360771
