### ISSUE TITLE
Someone can help me with a crash?

### ISSUE THREAD

**Issue by KentaroYuki** [MultiMC/MultiMC5#2649]
Here is the log link: https://paste.ee/p/VLSac 
I don't understand about JavaScript and programming. I created this modpack like 10 minutes ago, and I can't open the minecraft screen without this crash.

**Comment by QuImUfu** [comment]
you have optifine for 1.10.2 installed but the mc version you use is 1.12.2.

**Comment by KentaroYuki** [comment]
Ok, I put the optifine for 1.12.2 in the mods folder, the minecraft openned now, but I received this crash:
https://paste.ee/p/8xd7y

The log is too large, then I just copy the middle to the end.

**Comment by KentaroYuki** [comment]
> you have optifine for 1.10.2 installed but the mc version you use is 1.12.2.

Ok, I put the optifine for 1.12.2 in the mods folder, the minecraft openned now, but I received this crash:
https://paste.ee/p/8xd7y

The log is too large, then I just copy the middle to the end.

**Comment by QuImUfu** [comment]
you used Applied Fluidics together which is "Not compatible with AE2 RV6!"  
together with appliedenergistics2 rv6-stable-6

**Comment by KentaroYuki** [comment]
> appliedenergistics2 rv6-stable-6

Then with appliedenergistics2 rv6-stable-6 it will work?

**Comment by KentaroYuki** [comment]
> you used Applied Fluidics together which is "Not compatible with AE2 RV6!"
> together with appliedenergistics2 rv6-stable-6

And another crash: https://paste.ee/p/NKESB
I deleted the Applied Fluidics.

**Comment by QuImUfu** [comment]
can you post the content of:
C:\Users\Kentaro\Downloads\Jogos\MultiMC\instances\Infinito\.minecraft\hs_err_pid3464.log

**Comment by KentaroYuki** [comment]
> can you post the content of:
> C:\Users\Kentaro\Downloads\Jogos\MultiMC\instances\Infinito.minecraft\hs_err_pid3464.log

This directory doesn't exist.

**Comment by QuImUfu** [comment]
Should be:
C:\Users\Kentaro\Downloads\Jogos\MultiMC\instances\Infinito\.minecraft\hs_err_pid3464.log
.minecraft might be hidden.

**Comment by KentaroYuki** [comment]
> Should be:
> C:\Users\Kentaro\Downloads\Jogos\MultiMC\instances\Infinito\.minecraft\hs_err_pid3464.log
> .minecraft might be hidden.

Eh... Wait. I'm not receiving the crash, I guess because I put just 6 GB RAM to the modpack, and then probably have occured a "bottleneck" with my RAM or something like this.

**Comment by KentaroYuki** [comment]
> Should be:
> C:\Users\Kentaro\Downloads\Jogos\MultiMC\instances\Infinito\.minecraft\hs_err_pid3464.log
> .minecraft might be hidden.

Here is the hs_err_pid3464.log: https://paste.ee/p/BmXdt
And which is the 10 mods that more use my RAM? Just to check something.

**Comment by QuImUfu** [comment]
That crash indicates java tries to allocate more memory than you have **free**.   
If you have 8GB of ram you OS and background processes use ~1GB. if another heavy program runs that uses another 4 GB that leaves only 3GB to java.  
If you tell java that it should grab more (i.e. 8GB), then it crashes with such a crash.  
Java is quite aggressive with memory and grabs as much as it can use without freeing anything if it doesn't need to.  
Reducing the amount of ram mincraft can use  to e.g. 5GB should fix it.   
This should not happen if you have swap space.

**Comment by KentaroYuki** [comment]
> That crash indicates java tries to allocate more memory than you have **free**.
> If you have 8GB of ram you OS and background processes use ~1GB. if another heavy program runs that uses another 4 GB that leaves only 3GB to java.
> If you tell java that it should grab more (i.e. 8GB), then it crashes with such a crash.
> Java is quite aggressive with memory and grabs as much as it can use without freeing anything if it doesn't need to.
> Reducing the amount of ram mincraft can use to e.g. 5GB should fix it.
> This should not happen if you have swap space.

Yes, but with 6 GB the minecraft can't load. That RAM bar stay red, and the loading screen don't make any progress.

**Comment by QuImUfu** [comment]
Have you tried closing chrome, rebooting and giving minecraft 7,5GB?  
I see no obvious memory eaters under your mods that i am aware of.   
If that doesn't work you could try watching the loading processes and see at what point it hangs and try to find the mod causing it that way.  
Apart from this you could upload the modpack and post a link so i can try to find the culprit.

**Comment by KentaroYuki** [comment]
> Have you tried closing chrome, rebooting and giving minecraft 7,5GB?
> I see no obvious memory eaters under your mods that i am aware of.
> If that doesn't work you could try watching the loading processes and see at what point it hangs and try to find the mod causing it that way.
> Apart from this you could upload the modpack and post a link so i can try to find the culprit.

Of sure, sorry, I was sleeping. But the problem is that the mod who eat my memory is the JEI (JustEnoughItems)... This is a little bit strange, because JEI is the lightest mod that I have. I guess because have a lot of item textures, or something like this. I don't really know.
But here's the instance link: http://www.mediafire.com/file/x1homuslqa6fcc2/Infinito.rar/file
I'll try to restart my computer, open the task manager and close all the useless processes, then open the Minecraft, but I don't know if this will work. Sorry for the inconvenience.

**Comment by KentaroYuki** [comment]
> Have you tried closing chrome, rebooting and giving minecraft 7,5GB?
> I see no obvious memory eaters under your mods that i am aware of.
> If that doesn't work you could try watching the loading processes and see at what point it hangs and try to find the mod causing it that way.
> Apart from this you could upload the modpack and post a link so i can try to find the culprit.

Are you alive?

**Comment by QuImUfu** [comment]
sorry, had a lot of things to do. I did not find a single mod at fault, it rather seems like mods on modern Minecraft versions just swallow **all** the RAM on start up. AFAIK the only possibility to get this to run on a PC with 8GB is tons of swap and **days** of patience. You'll have to remove some mods that add recepies and/or Blocks or upgrade your PC.

**Comment by KentaroYuki** [comment]
> sorry, had a lot of things to do. I did not find a single mod at fault, it rather seems like mods on modern Minecraft versions just swallow **all** the RAM on start up. AFAIK the only possibility to get this to run on a PC with 8GB is tons of swap and **days** of patience. You'll have to remove some mods that add recepies and/or Blocks or upgrade your PC.

Ok, I'll try.

**Comment by Evolution0** [comment]
Right-click your pack in MultiMC, select Edit Instance, go to Settings, check "Java Arguments" and paste this in the box below (Triple click the line to highlight the whole thing):
```
-d64 -server -XX:+AggressiveOpts -XX:ParallelGCThreads=3 -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:NewSize=84m -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3 -Dfml.readTimeout=90 -Ddeployment.trace=true -Ddeployment.log=true -Ddeployment.trace.level=all
```
Then set your ram allocation in the in the section above it, I give mine about 1024MB min and 4096MB max and these args are more aggressive with cleaning up so less chances of hitting a memory limit.

If you still have room to spare you can always allocate more for the maximum later.

**Comment by KentaroYuki** [comment]
> Right-click your pack in MultiMC, select Edit Instance, go to Settings, check "Java Arguments" and paste this in the box below (Triple click the line to highlight the whole thing):
> 
> ```
> -d64 -server -XX:+AggressiveOpts -XX:ParallelGCThreads=3 -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:NewSize=84m -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3 -Dfml.readTimeout=90 -Ddeployment.trace=true -Ddeployment.log=true -Ddeployment.trace.level=all
> ```
> 
> Then set your ram allocation in the section above it, I give mine about 1024MB min and 4096MB max and these args are more aggressive with cleaning up so less chances of hitting a memory limit.
> 
> If you still have room to spare you can always allocate more for the maximum later.

Oh, sorry, I forget to Close the issue, the modpack are working now. Sorry for the inconvenience.
