### ISSUE TITLE
Most versions of Minecraft seems to crash

### ISSUE THREAD

**Issue by TwistedPaper** [MultiMC/MultiMC5#2650]
System Information
-----------------------------
MultiMC version: 0.6.5

Operating System: 5.0.9-2-MANJARO

Summary of the issue or suggestion:
----------------------------------------------
Essentially trying to run any version of Minecraft, 1.12.2. 1.10, etc and it crashes at the onesix launcher. The log I am including here is for StoneBlock 2 on the latest version. According to the Version tab in MultiMC it is using Forge 14.23.5.2808, Minecraft 1.12.2 and the modpack 2.9.3. I also want to mention the only Minecraft I have successfully launched is 1.14, so it does work at all in some regard. Been trying to get this working for a couple of days on my own looking at other requests for help. I feel mine to be specific due to the operating system being used. The build of MultiMC is an Arch Linux Distro version. I have reinstalled both the pack and MultiMC and have restarted the computer.

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Forcing use of Java 8 and allocating up to 8G of ram.

2.

3.

Suspected cause:
---------------------------
OneSix Launcher?

Logs/Screenshots:
----------------------------
https://paste.ee/p/5hp0p

Additional Info:
---------------------------

**Comment by Jorval** [comment]
Had the same Problem a few days ago. i installed the multimc-git version from aur that worked for me

**Comment by ThexXTURBOXx** [comment]
This is not related to MultiMC, report here please: https://github.com/TheRandomLabs/RandomLib
