### ISSUE TITLE
ld: warning: ignoring file libsysteminfo.a, file was built for archive which is not the architecture being linked (x86_64): libsysteminfo.a

### ISSUE THREAD

**Issue by creepinson** [MultiMC/MultiMC5#2653]
Hey all. I was trying to build MultiMC on Mac OSX and it gave me this error when I ran the "make" command. 
`ld: warning: ignoring file libsysteminfo.a, file was built for archive which is not the architecture being linked (x86_64): libsysteminfo.a
Undefined symbols for architecture x86_64:
  "Sys::getKernelInfo()", referenced from:
      SysTest::test_kernelNotNull() in sys_test.cpp.o
ld: symbol(s) not found for architecture x86_64`

I've done some research and it sounds like I might be able to add compiler flags to the CMakeLists of the systeminfo library in the libraries folder, though I'm not sure it will fix it.

**Comment by peterix** [comment]
No idea, ideall come to the discord server and talk there.
