### ISSUE TITLE
multimc process crashed with exitcode -805306369

### ISSUE THREAD

**Issue by Shadow5tep73** [MultiMC/MultiMC5#2656]
System Information
-----------------------------
MultiMC version: 0.6.5

Operating System: Window 10 64 bit.

Summary of the issue or suggestion:
Multi MC will crash after trying to load a server with exit code -805306369.

What should happen:
Not crash since it worked for a whole week till now.

Steps to reproduce the issue (Add more if needed):

1. Use the mod pack my cousin made.

2. Run Multi MC.

3. Watch it crash if it crashes for you.

Suspected cause:
I have no clue to be honest.

Attached is the prompt I get I put it in a Zip Folder and posted it on Google Drive.
https://drive.google.com/drive/folders/1-O96X3Q-0PVK6tJkCQ-k2fM_VbS__skI?ths=true

Additional Info:
If it doesn't crash with this code it will crash with exit code -1., or 0., or just completely freeze at the model manager loading bar.

**Comment by peterix** [comment]
Please post an actually accessible log. This is behind some security nonsense. Repoen if still relevant.

**Comment by Shadow5tep73** [comment]
I made it accessible to anyone with a Link sorry that it didn't work when
you tried it I don't know what happened

**Comment by Shadow5tep73** [comment]
> Please post an actually accessible log. This is behind some security nonsense. Repoen if still relevant.

I made it accessible to anyone with a Link sorry that it didn't work when
you tried it I don't know what happened

**Comment by Shadow5tep73** [comment]
Also @peterix can you please re-open it since it is still an issue I'm facing
