### ISSUE TITLE
Error when installing zip for modpack - unable to resolve mod ids

### ISSUE THREAD

**Issue by FailToSurvive** [MultiMC/MultiMC5#2660]
System Information
-----------------------------
MultiMC version: 0.6.5-1302

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
When attempting to create a new instance of a pack, I used a zip file downloaded from curseforge to create the pack. After choosing the zip it gives me the error message below. I've tried this several times, yesterday and today. Based on prior issues it might be a delay issue on the curse API?

Doing the same process on the Twitch Launcher works. I'm not sure if they use a different API or something? I'd rather use MMC than the Twitch Launcher.

What should happen:
------------------------------
It should add a new instance of the pack to MMC.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download the zip file from https://minecraft.curseforge.com/projects/project-equivalence/files/2713377
2. Click Add Instance
3. Click Import from zip
4. Choose zip file downloaded from curseforge
5. Receive error message popup

Suspected cause:
---------------------------
Previous issues? #2655

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![6ctfJ4JcPJ](https://user-images.githubusercontent.com/50390524/58022841-580ab000-7adc-11e9-91da-b65f0b56cfe8.png)

Error - MultiMC 5
Unable to resolve mod IDs:
Some mod ID resolving tasks failed.

MultiMC Log: https://pastebin.com/d6JMs7zy

Additional Info:
---------------------------

**Comment by whygithubwhy** [comment]
Same issue here. Can't install Enigmatica 2: Expert through import anymore because mod ID fail.

**Comment by Nathgon** [comment]
Getting the same issue, at first I thought it was a per-modpack issue but I couldn't get anything to download off of curse. I didn't think it would fix it but I tried doing a fresh installation of MultiMC but the same thing.

**Comment by whygithubwhy** [comment]
This issue seems to have resolved itself. I am able to import and download no problem now.

**Comment by FailToSurvive** [comment]
Yeah, looks to be fixed now. Very strange. Thanks for the update @whygithubwhy
