### ISSUE TITLE
Forge version not compare

### ISSUE THREAD

**Issue by Gregoryo7** [MultiMC/MultiMC5#2661]
System Information
-----------------------------
MultiMC version:5

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
when i want install Forge , list of forge version is void.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Create an instance

2. Go to edit instance

3.Go to install Forge

Suspected cause:
---------------------------

Logs/Screenshots:
![image](https://user-images.githubusercontent.com/40891162/58048062-11539f00-7b4a-11e9-8fcf-fe31abad639b.png)

----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
If you want to install Forge for 1.13.2 or 1.14, MMC doesnt have those. For any other version it means that you dont use an official MMC build
