### ISSUE TITLE
Try to start minecraft with preview_OptiFine_1.14_HD_U_F1_pre2.jar

### ISSUE THREAD

**Issue by marvin1099** [MultiMC/MultiMC5#2662]
System Information
-----------------------------
MultiMC version: MultiMC 5 version 0.6.5

Operating System: Windows 10

Summary of the issue or suggestion: Optifine Version: preview_OptiFine_1.14_HD_U_F1_pre2.jar
----------------------------------------------

What should happen: Minecraft with Optifine 
should Start
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. i basically followed those institutions: https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine on the newest preview Version of Optifine and i dont i don't know what i did wrong

Suspected cause: that's the problem, i don't know
---------------------------

Logs/Screenshots: https://paste.ee/p/wakEf
![Log_and_Optifine_Screenshot](https://user-images.githubusercontent.com/40715852/58058304-ac5b7180-7b68-11e9-9940-24b57c15ff6e.PNG)
here the text form:
MultiMC version: 0.6.5-1302

Minecraft folder is:
D:/Program Files/MultiMC/instances/Optifine 1.14/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 10.0.2, using 64-bit architecture.

Instance update failed because: Some artifacts marked as 'local' are missing their files:
D:/Program Files/MultiMC/instances/Optifine 1.14/libraries/INVALID

You need to either add the files, or removed the packages that require them.
You'll have to correct this problem manually.

MultiMC: Log upload triggered at: 21 May 2019 01:25:45 +0200

----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:  i ges i don't know what i should add if you need anything else please let me know
---------------------------

**Comment by GreenLemon424** [comment]
https://gist.github.com/ScottoMotto/f5bb22e6ff5691e2465d8720ba648885

This json file should help in detecting where the file is, but it doesn't let me start the game

**Comment by ScottoMotto** [comment]
Installation instructions have been added to the gist https://gist.github.com/ScottoMotto/f5bb22e6ff5691e2465d8720ba648885

and a YouTube tutorial is online now: https://youtu.be/rVImKYcQIrg

**Comment by peterix** [comment]
The wiki should be updated for this.

**Comment by little-hophop** [comment]
If you want to install Optifine on 1.14 using MultiMC you could also just do this:

Download the correct Optifine version
Open the normal Minecraft launcher once on the correct version (1.14 in this case) (you can close Minecraft again afterwards)
Open the downloaded Optifine .jar file
Once it is open click on 'Extract'
Once it is extracted you should have a new Optifine .jar file with the same name as the one you extracted except this one has _MOD added at the end
Open MultiMC
Create/Open an instance with the correct version (in this case 1.14)
Click on 'Edit Instance'
Click on 'Add to Minecraft.jar'
Select the Optifine file which you extracted (the one with _MOD at the end)
Launch the instance

**Comment by marvin1099** [comment]
I Solved It by playing with optifabric so i can have mods to
