### ISSUE TITLE
Package dependency oversight

### ISSUE THREAD

**Issue by markonius** [MultiMC/MultiMC5#2665]
System Information
-----------------------------
MultiMC version:
0.6.5
Operating System:
Fedora 30
Summary of the issue or suggestion:
----------------------------------------------
Package dependencies seem to be satisfied by openJDK-headless, but a regular openJDK is required. The headless one is missing libjawt.so.

What should happen:
------------------------------
Probably, the correct JDK should get installed

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install Fedora 30

2. Have openJDK-headless installed by default

3. Fail to play Minecraft

Suspected cause:
---------------------------
See summary

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/tMHwA
```
java.lang.UnsatisfiedLinkError: /blah/blah/multimc/instances/FTB Ultimate Reloaded/natives/liblwjgl64.so: libjawt.so: cannot open shared object file: No such file or directory
```

Additional Info:
---------------------------

**Comment by phit** [comment]
multimc doesn't have a fedora package?

**Comment by peterix** [comment]
Indeed, it doesn't.
