### ISSUE TITLE
The instance crashes when i open it

### ISSUE THREAD

**Issue by jameswarman** [MultiMC/MultiMC5#2666]
MultiMC version:
MultiMC5 0.6.5-1243

Operating System:
MacOs Version 10.12.6

Summary of the issue or suggestion:
----------------------------------------------
When I open the instance it crashes, not sure why

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC

2. Open the instance

3. The game opens then crashes

Suspected cause:
---------------------------
no idea

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/qvFaw
https://paste.ee/p/hFWX4

Additional Info:
---------------------------

**Comment by QuImUfu** [comment]
try updating forge.
