### ISSUE TITLE
Cannot connect to mojang networks

### ISSUE THREAD

**Issue by asdfghjkl403622** [MultiMC/MultiMC5#2667]
System Information
-----------------------------
MultiMC version:0.6.5-1217

Operating System: ubuntu 19.04 disco dingo

Summary of the issue or suggestion:
I cannot connect to any Mojang networks, disabling multiplayer and many other features such as connectin to my account.

What should happen:
------------------------------
I log in normally and start playing Minecraft with friends.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.download multimc

2.try to log in

3.
![image](https://user-images.githubusercontent.com/44118606/58211387-6bbb3f80-7cb1-11e9-80e2-b3e3ab886128.png)

Suspected cause:
---------------------------
cannot connect to the networks.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![image](https://user-images.githubusercontent.com/44118606/58211411-783f9800-7cb1-11e9-9c6e-b7946bfd124b.png)

Additional Info:
---------------------------
I have qt5 installed already.
I am also connected to the internet.
I have already tried deleting and reinstalling java.

**Comment by drazisil** [comment]
This solved it for me

https://github.com/MultiMC/MultiMC5/issues/1784#issuecomment-272712807

**Comment by Josh74000** [comment]
Everything is ok for me, you need to have an internet connection that is why, it is all fine on Windows 10 v1903
![image](https://user-images.githubusercontent.com/32041132/58417509-e226bb80-807c-11e9-88d7-f880ee27bc78.png)

**Comment by Zetabite** [comment]
> Everything is ok for me, you need to have an internet connection that is why, it is all fine on Windows 10 v1903
Thats incorrect. The problem are the non MultiMC Libs. Ubuntu 19.04 and some other distros cant handle them.

**Comment by tjsd** [comment]
do you know of a fix for this @Zetabite ?

**Comment by Zetabite** [comment]
@tjsd the same fix @drazisil suggested

**Comment by tjsd** [comment]
I removed the QT5 libs and the plugins dir, but then multimc wont launch because they are missing

**Comment by Zetabite** [comment]
Install QT5 via `sudo apt-get install qt5-default `

**Comment by asdfghjkl403622** [comment]
I already have qt5 installed

**Comment by asdfghjkl403622** [comment]
I already have qt5 installed

**Comment by Janrupf** [comment]
Good, now delete everything without `multimc` in the name from `~/.local/share/multimc/bin` (or whereever your local multimc copy is)

**Comment by asdfghjkl403622** [comment]
THANK YOU! that fixed it and now I think it works pretty well!
