### ISSUE TITLE
Mac OS X version requesting Microphone Access

### ISSUE THREAD

**Issue by TemperedFool** [MultiMC/MultiMC5#2668]
System Information
-----------------------------
MultiMC version:0.6.5-1243

Operating System: osx64 (Mac OS X 10.14.4)

Summary of the issue or suggestion:
----------------------------------------------
While running MultiMC, I get frequent OS pop-ups indicating MultiMC is requesting permissions for microphone access. It's not clear why it should need the microphone, and there doesn't seem to be anyway to disable this.

I'm not clear on whether or not it's the MultiMC launcher or the Minecraft instance that's requesting the access. If it's Minecraft requesting the access I'd imagine there's nothing you can do about it.

What should happen:
------------------------------
I'm not sure it should be requesting microphone access at all; if there is a feature that wants to use it, it should be possible to disable it (thereby muting further requests).

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Run MultiMC (and I believe have an instance running, but I'm not sure on that point)

2. Wait.

Suspected cause:
---------------------------
I'm unsure; it's not clear there's a reason MultiMC should need the mic, but I'm also not clear why Minecraft would. This is pretty new (within the last couple weeks) behavior, but that could also be an OS update tightening access restrictions to the mic.

Logs/Screenshots:
----------------------------
N/A

Additional Info:
---------------------------

**Comment by dustinbrown** [comment]
+1

**Comment by peterix** [comment]
This is macOS going crazy and there's nothing I can do about it.

**Comment by leftyfl1p** [comment]
I get this whenever initially loading into a server.  It doesn't happen when launching through the twitch app but multimc shows it every time. 10.14.4, Java 1.8, multimc 0.6.5-1243, Project Orbit 3.

**Comment by Ghalid** [comment]
> I'm not clear on whether or not it's the MultiMC launcher or the Minecraft instance that's requesting the access. If it's Minecraft requesting the access I'd imagine there's nothing you can do about it.

Do you have the Mekanism mod installed? If so, this is caused by its voice server, and thus the game itself and is not a launcher problem. Set `B:VoiceServerEnabled=false` in its config. (Yes I realize I'm quite late, but maybe it'll help someone)

**Comment by TemperedFool** [comment]
> > I'm not clear on whether or not it's the MultiMC launcher or the Minecraft instance that's requesting the access. If it's Minecraft requesting the access I'd imagine there's nothing you can do about it.
> 
> Do you have the Mekanism mod installed? If so, this is caused by its voice server, and thus the game itself and is not a launcher problem. Set `B:VoiceServerEnabled=false` in its config. (Yes I realize I'm quite late, but maybe it'll help someone)

Thank you - I did have Mekanism installed, so I'm sure that was it.

**Comment by TheRubiksGamer** [comment]
> > I'm not clear on whether or not it's the MultiMC launcher or the Minecraft instance that's requesting the access. If it's Minecraft requesting the access I'd imagine there's nothing you can do about it.
> 
> Do you have the Mekanism mod installed? If so, this is caused by its voice server, and thus the game itself and is not a launcher problem. Set `B:VoiceServerEnabled=false` in its config. (Yes I realize I'm quite late, but maybe it'll help someone)

Thank you so much!
