### ISSUE TITLE
Minecraft version 2.0 (purple) not launching

### ISSUE THREAD

**Issue by torzod** [MultiMC/MultiMC5#2670]
System Information
-----------------------------
MultiMC version:
0.6.5
Operating System:
arch linux
Summary of the issue or suggestion:
----------------------------------------------
minecraft 2.0, that old april fools update, seems to not work. I have lost my blue version jar (which I am sad about), but i have downloaded the red and purple versions. However, when I try to launch them, it crashes with error -1.

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download JARfile of choice for minecraft 2.0

2. Go To Version > Minecraft > Customize and select your joke JAR

3. a

Suspected cause:
---------------------------
strange version issues?

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
```
Failed to find Minecraft main class:
Exiting with -1
	java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:171)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

Additional Info:
---------------------------

**Comment by peterix** [comment]
The version you customize must be close to the one you arer actually trying to use.

**Comment by torzod** [comment]
for some reason only blue and red were working when submitted, the json version files were correctly formatted. now all three work for some reason. thanks
