### ISSUE TITLE
Ubuntu 19.04 - version 0.6.5-develop-1223 - Stopped working

### ISSUE THREAD

**Issue by tjsd** [MultiMC/MultiMC5#2672]
System Information
-----------------------------
MultiMC version: 0.6.5-develop-1223

Operating System: Xubuntu 19.04

Summary of the issue or suggestion:
----------------------------------------------
It shows offline for all services and I am unable to launch packs, it only wants to run offline mode.

What should happen:
------------------------------
Should come online

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Start multimc
2. Try to launch a pack
3. fail

Suspected cause:
---------------------------
Seems something related to network. It worked fine a couple of weeks ago.

Logs/Screenshots:
----------------------------
https://pastebin.ubuntu.com/p/T3N7yCx7tt/

Additional Info:
---------------------------
Would love to get this fixed

**Comment by Zetabite** [comment]
Sounds like that: https://github.com/MultiMC/MultiMC5/issues/1784#issuecomment-272712807
Fix included

**Comment by tjsd** [comment]
That does hotfix the issue, but I think it still is a valid issue that the dev should get a permanent solution for.

**Comment by phit** [comment]
yes thats what that issue is for..
