### ISSUE TITLE
OptiFine manual install with 1.14 not working

### ISSUE THREAD

**Issue by Nximus** [MultiMC/MultiMC5#2673]
System Information
?
MultiMC version:
MMC 5 / 0.6.5
Operating System:
Windows 10
Summary of the issue or suggestion:
When following the steps of the manual optifine install, my game crashes on launch. I've done everything right. My .json file looks good and my file is in libraries.

What should happen:
My game should launch with optifine

Steps to reproduce the issue (Add more if needed):
Follow the provided guide for 1.14

Suspected cause:
Literally no clue

Logs/Screenshots:
https://prnt.sc/nu2zf7
https://prnt.sc/nu2zis
https://prnt.sc/nu2zxg

//LOGS
MultiMC version: 0.6.5-1302

Minecraft folder is:
C:/Users/jsa09/OneDrive/Desktop/MultiMC/instances/1.14/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_211, using 64-bit architecture.

Instance update failed because: Some artifacts marked as 'local' are missing their files:
C:/Users/jsa09/OneDrive/Desktop/MultiMC/instances/1.14/libraries/OptiFine_1.14_HD_U_F1_pre6

You need to either add the files, or removed the packages that require them.
You'll have to correct this problem manually.

**Comment by ScottoMotto** [comment]
Run the Optifine installer and Extract the Optfine jar, then use that in MultiMC.

**Comment by Nximus** [comment]
I tried that. Still doesn't work.

**Comment by ScottoMotto** [comment]
It works. https://youtu.be/rVImKYcQIrg

Note you must have installed 1.14 in the Vanilla launcher prior to extraction.
With the extracted file you could also use the Add to Minecraft.jar button in the Edit Instance window and embed the extracted OF jar:
https://youtu.be/bsXTLTNLaPs

Or you can install Fabric and use OptiFabric:
https://youtu.be/CRDRv7wLCP0

**Comment by Nximus** [comment]
The video fixed it. Thanks for the help!

**Comment by TheOfficialJosh** [comment]
The issue is with line 11 of your optifine.OptiFine.json. You do not have the ".jar" extension on the end of the file name.

**Comment by ScottoMotto** [comment]
There's no issue with that, please refer to https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine as the source for the json syntax.
