### ISSUE TITLE
process exited with code -1  

### ISSUE THREAD

**Issue by xag803** [MultiMC/MultiMC5#2674]
System Information
-----------------------------
MultiMC version:0.6.5dev

Operating System:win 10

Summary of the issue or suggestion: crash
---------
-------------------------------------
 
What should happen: 
------------------------------
Minecraft should load

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. get the mods in the image (https://imgur.com/a/wS9WgaK)

2. apply the mods

3. start Minecraft 1.9.4

Suspected cause: one of the mods
---------------------------

Logs/Screenshots: https://pastebin.com/zznce0km
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Heufneutje** [comment]
You didn't give your instance enough memory. Increase the memory in the instance settings.
