### ISSUE TITLE
Difference in JVM arguments compared to official launcher

### ISSUE THREAD

**Issue by e00E** [MultiMC/MultiMC5#2675]
When I check the jvm arguments in the official launcher with the current minecraft version `1.14.2` by going to `menu -> launch options -> enable advanced settings -> latest release -> jvm arguments` I see:

* -Xmx2G
* -XX:+UnlockExperimentalVMOptions
* -XX:+UseG1GC
* -XX:G1NewSizePercent=20
* -XX:G1ReservePercent=20
* -XX:MaxGCPauseMillis=50
* -XX:G1HeapRegionSize=32M

The first one is the maximum memory size which we can already set in MultiMC. Are the other arguments used in MultiMC or not? In either case, is this a conscious choice or were they just forgotten? Does it make sense to copy Mojang's default arguments?

I don't know enough about Java and Minecraft to answer these questions but you probably do.

Thank you a lot for this project.

**Comment by Zetabite** [comment]
these are java arguments. will be fine. i guess multimc will prefer the added jvm to the already self added once by multimc itself

**Comment by e00E** [comment]
There is documentation here https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/g1_gc_tuning.html .

**Comment by peterix** [comment]
I don't see why I should inject random magical things that won't be correct for modded or anything other than stock vanilla game anyway.

Not interested in copying vanilla in this either.
