### ISSUE TITLE
Crashing after a few minutes in a open to lan world

### ISSUE THREAD

**Issue by Moovewithminecraft** [MultiMC/MultiMC5#2676]
System Information:
-----------------------------
GPU: NVIDIA GeForce GTX 1080 3GB
CPU: AMD Ryzen 5 1400 Quad-Core Processor
Ram: 8 GB
MultiMC version: 0.6.5
Operating System: Windows 10
Summary of the issue or suggestion:
----------------------------------------------
I launch Minecraft, open a world, open to lan (play with my friends using hamachi) and after we play for a couple minutes the world crashes. 
What should happen:
------------------------------
It shouldn't crash while we are playing.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch a world

2. Open to lan, have friends connect

3. Play a while

Suspected cause:
---------------------------
Some mod / not enough ram?

Logs/Screenshots:
----------------------------
https://paste.ee/p/p6W2l

**Comment by Zetabite** [comment]
Seems like a network error because of the way its hosted. No mod seems to be directly involved. If you are playing on cracked mc it could be that this messes somehow with the game. You could try hosting a forge server in offline mode, so they can still connect via hamachi.
