### ISSUE TITLE
Crash on loading world?

### ISSUE THREAD

**Issue by halfging3r** [MultiMC/MultiMC5#2678]
System Information
-----------------------------
MultiMC version: MultiMC 5, version 0.6.5

Operating System: Windows

Summary of the issue or suggestion:
----------------------------------------------
Everytime I try to load a world, the game crashes.

What should happen:
------------------------------
The world should open.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Attempt to create or open a world. Any world.

2.

3.

Suspected cause:
---------------------------
I keep getting "Ticking Entity" errors. I thought it was Animania, but removing it did not fix the issue, so I really have no clue.

Logs/Screenshots:
----------------------------
One of the crash reports from before removing Animania:

https://paste.ee/p/fszBU

After removing it:

https://paste.ee/p/fySq4

And after attempting to fix via MCEdit:

https://paste.ee/p/BdHew

Additional Info:
---------------------------
I had Animania and its supporting mod, as well as OTG, and I though it was one of those causing the issue, so I removed both, but that did not solve the issue. I have tried deleting worlds and creating new ones after trying a new fix. I have tried removing the ticking entity on MCEdit, but that only caused the game to look like a strobe light.

Help? Minecraft version 1.12.2

**Comment by halfging3r** [comment]
Nevermind. I just decided to delete the instance and create a new one from scratch. Luckily I hadn't started building yet, so it's not a huge deal. It'll just be time consuming because I'm launching between each one to test and make sure it works.

**Comment by nift4** [comment]
Seems like OTG is buggy

**Comment by peterix** [comment]
It looks liek you didn't install the mod correctly... But, I guess you fixed that in the new instance...
