### ISSUE TITLE
How do I download OptiFine for MultiMC? 1.14.2

### ISSUE THREAD

**Issue by FantasticMenace** [MultiMC/MultiMC5#2679]
I simply don't know how to Install the latest version of OptiFine into MultiMC, If I could get some help here that would be Appreciated.

**Comment by ScottoMotto** [comment]
You have to install the version of Minecraft you want to target in the Vanilla launcher and then run it once. Download the Optfine Installer from optifine.net and run it to extract the Optfine jar.

Then follow one of these videos. The 2nd is the easiest.
JSON file patch: https://youtu.be/rVImKYcQIrg
Easier method with Add to Minecraft.jar: https://youtu.be/bsXTLTNLaPs
As a Fabric mod: https://youtu.be/CRDRv7wLCP0

**Comment by calloatti** [comment]
You can use https://minecraft.curseforge.com/projects/optifabric

You will need https://fabricmc.net/use/

And there is a tutorial for that here: https://fabricmc.net/wiki/tutorial:install_with_multimc

**Comment by FantasticMenace** [comment]
OptiFabric didn't work with 1.14.2, I tried it

**Comment by FantasticMenace** [comment]
The Problem I have is that Most if not All of my mods are for 1.14.2, yet I don't know how to Install OptiFine for 1.14.2.

**Comment by ScottoMotto** [comment]
Yeah, the Fabric one is not updated yet. The other methods work fine for 1.14.2. There is an updated json file in the first video description but again you won't need that for the second one.

**Comment by FantasticMenace** [comment]
I don't think that the Author for OptiFabric will Update it to 1.14.2 Today, but Thank you Regardless.

**Comment by ScottoMotto** [comment]
Actually it appears to be updated already: https://minecraft.curseforge.com/projects/optifabric/files/2717630

**Comment by FantasticMenace** [comment]
I tried that one, didn't work for 1.14.2.

**Comment by ScottoMotto** [comment]
![image](https://user-images.githubusercontent.com/40503051/58690041-3a481100-834e-11e9-8bd5-a838ac21c915.png)

It works fine.

**Comment by FantasticMenace** [comment]
How did you get to that point? I can't even launch Minecraft when I add OptiFine. Could you make a Video detailing how to do it or Something?

**Comment by ScottoMotto** [comment]
I did. Just translate the instructions to the newer versions. https://youtu.be/CRDRv7wLCP0

**Comment by FantasticMenace** [comment]
Gosh, I'm an idiot. Thanks again Scotto.

**Comment by FantasticMenace** [comment]
One or More of my mods are making it Crash.

**Comment by ScottoMotto** [comment]
I thought that might be the case. You probably want things to settle down a bit before introducing too many mods, or give them time to update.
Better yet. Test out which mod is crashing and report it to the developer.

**Comment by FantasticMenace** [comment]
I'm testing to see which mods crash and which don't right now. May attempt to report the crashes to the Mod Devs.

**Comment by FantasticMenace** [comment]
So far I'm figuring out that I need to download the Latest versions of Mods for them to work, since I downloaded the mods back in 1.14/1.14.1
