### ISSUE TITLE
error -1

### ISSUE THREAD

**Issue by NoVamaury** [MultiMC/MultiMC5#2680]
first thing first i am just here to find a answer to my problem
System Information
-----------------------------
MultiMC version: idk the last one 

Operating System: windows 10 64bits

Summary of the issue or suggestion:
----------------------------------------------
when i launch the game , (i am using FTB beyond in 1.10.2 it's the right version) it loads but when i should get to the "multiplayer singleplayer settings" menu it just closes

What should happen:
------------------------------
maybe let me play

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. use the latest version of MULTIMC

2. use the ftb beyond modpack without decocraft and forestery ( w/ all the mods that come with them)

3. launch online or offline it will be the same

Suspected cause:
---------------------------
maybe mods ?

Logs/Screenshots:
----------------------------
```
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.13.6.142
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 0
	Translocator Invalid Fingerprint Reports: 
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.64, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD Ryzen 3 2200G with Radeon Vega Graphics 
[00:48:27] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:560]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\amaury\Desktop\MultiMC\MultiMC\instances\FTBBeyond-1.9.0-1.10.2\minecraft\crash-reports\crash-2019-06-01_00.48.27-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.
```

Additional Info:
---------------------
i'm french excuse my crappy english

**Comment by NoVamaury** [comment]
my discord is NoVa_amaury#3256 if needed ( i think i'll nedd you more since idk how to code

**Comment by peterix** [comment]
Not sure what happened there, please post a full log (use the upload button).
