### ISSUE TITLE
Modpacks wont load.

### ISSUE THREAD

**Issue by AFancyCat** [MultiMC/MultiMC5#2681]
System Information
-----------------------------
MultiMC version: Version 0.6.5

Operating System: Windows

Summary of the issue or suggestion:
----------------------------------------------
When I try to open up a modpack it keeps on giving me an error

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open up the modpack instance

2.

3.

Suspected cause:
---------------------------
I really don't know, but when I try to install mods manually with forge before they just don't work for me. I think there's a similar problem between the two.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/oHW6G

Additional Info:
---------------------------
Again I can't load mods on forge normally so I tried multimc to play mods and modpacks. I think it may be some files missing but idk

**Comment by peterix** [comment]
That looks like either a forge bug, or a corrupted download.
Try deleting `C:/Users/Trever Cheung/Desktop/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar`.
