### ISSUE TITLE
MultiMC - Forge doesnt want to load

### ISSUE THREAD

**Issue by Jenda66** [MultiMC/MultiMC5#2682]
![mmc](https://user-images.githubusercontent.com/51330050/58811873-eb85ca00-8620-11e9-9e98-df8055a43757.png)
System Information
-----------------------------
MultiMC version: 5

Operating System:Win 10 - 64bit

Summary of the issue or suggestion:
----------------------------------------------
When i want instal forge  the menu is empty.

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Select instance

2. edit instance

3.install forge

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
And when i go to the game folder the folders are empty
![mmcc](https://user-images.githubusercontent.com/51330050/58812244-b75ed900-8621-11e9-9222-ffec74f390a0.png)

**Comment by peterix** [comment]
You are not using the official, supported build of MultiMC.
