### ISSUE TITLE
MMC says 'No Forge versions are currently available for Minecraft 1.14.2' but there is.

### ISSUE THREAD

**Issue by TetraTheta** [MultiMC/MultiMC5#2687]
System Information
-----------------------------
MultiMC version: Version 0.6.5 develop 1314
Operating System: Windows 10 19H1

Summary of the issue or suggestion:
----------------------------------------------
1.14.2 Forge has beed released but MMC says there aren't Forge version available.

What should happen:
------------------------------
Since Forge for 1.14.2 has been released, MMC should show me list of Forge versions but It just says 'No Forge versions are currently available for Minecraft 1.14.2'. [HERE](https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.14.2.html) is official Forge website that Forge for 1.14.2 can be downloaded.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Make new instance. Select Minecraft version to 1.14.2

2. Go to 'Version' tab, Click 'Install Forge' under 'Install' section

3. MultiMC says there aren't Forge version available.

Suspected cause:
---------------------------
It might be MMC's database(or something similar) hasn't been updated to apply recent Forge versions yet.
(When I tried to mimic 1.12.2 Forge ``mmc-pack.json`` MMC says failed to fetch meta blahblah from multimc server)

Logs/Screenshots:
----------------------------
![이미지 1](https://user-images.githubusercontent.com/37061801/59184658-9100e680-8ba9-11e9-81d6-55536182d737.png)

Additional Info:
---------------------------

**Comment by JTJSniperBee** [comment]
Forge 1.14.2 is unstable IIRC and will not be used until it's stable enough for integration into MMC.

**Comment by InsideBSI** [comment]
Yeah, that's right. I came here to say the exact same thing.
I'll just leave this comment here and walk away

**Comment by peterix** [comment]
And I'll just close this. There's a completely fine GitHub issue that covers this already.
