### ISSUE TITLE
No versions are currently available

### ISSUE THREAD

**Issue by steedvry** [MultiMC/MultiMC5#2691]
When i click Add Instance in vanilla it say "No versions are currently available" and " List update failed: Job 'Download of meta file net.minecraft/index.json' failes to process: htt ps://v1.meta.multimc.org/net.minecrfat/index.json" But i have the lastest version,please help me.
![image](https://user-images.githubusercontent.com/51857105/59552719-95f3da80-8f9b-11e9-9df7-5d04439d0bfc.png)

**Comment by peterix** [comment]
Sounds like a network issue to me. Make sure `v1.meta.multimc.org` is not blocked.

**Comment by fieryray** [comment]
i got the same issue and its not my network that is the issue. pls help

**Comment by Spongman** [comment]
i'm having the same issue. `v1.meta.multimc.org` doesn't resolve to anything.

**Comment by sorek777** [comment]
i currently have this issue too, im on win10
[MultiMC-2.log](https://github.com/MultiMC/MultiMC5/files/3500298/MultiMC-2.log)

how could i verify if v1.meta.multimc.org is not blocked?
 i would like to help get this issue solved

**Comment by Heufneutje** [comment]
Update MultiMC. Simple as that.

**Comment by sorek777** [comment]
my bad, yeah, didnt doublecheck and did not notice i was still opening the broken modded one, i just reinstalled with the legit one and works fine, thanks @Heufneutje

**Comment by peterix** [comment]
Well, I moved things to a cheaper to maintain domain, with a different SSL cert and everything.

If it still doesn't work after an update to latest, reopen this, or open a new issue.
