### ISSUE TITLE
Invalid or corrupt jarfile

### ISSUE THREAD

**Issue by ThePiGuy24** [MultiMC/MultiMC5#2696]
System Information
-----------------------------
MultiMC version: 0.6.5-1217

Operating System: Ubuntu 18.04 64bit

Summary of the issue or suggestion: 
----------------------------------------------
Attempts to run pre-launch command but fails stating "Invalid or corrupt jarfile"

What should happen:
------------------------------
Pre-launch command should execute successfully (does so on windows)

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. add instance (link listed in "Additional Info")

2. run instance

3. witness error

Suspected cause:
---------------------------
Unknown

Logs/Screenshots:
----------------------------
https://paste.ee/p/9GwOK

Additional Info:
---------------------------
Instance download: https://skyem.co.uk/minecraft/frozenhell/voodoo/multimc-sk/descentfrozenhell.zip
I am using openjdk 11 but also fails with openjdk 8

**Comment by peterix** [comment]
That really doesn't look like a MultiMC problem.

**Comment by peterix** [comment]
It will not work with java 11, so trying that is not going to do anything good.

**Comment by peterix** [comment]
As for this issue in general, this is not anything related to MultiMC. Contact the authors of this thing instead.
