### ISSUE TITLE
Process exited with code -1.

### ISSUE THREAD

**Issue by user-03** [MultiMC/MultiMC5#2697]
System Information
-----------------------------
MultiMC version: 0.6.5- 1302

Operating System: win 7

Summary of the issue or suggestion:
----------------------------------------------
Game save exits upon loading "Process exited with code -1."

What should happen:
------------------------------
Game should start normally.

Logs/Screenshots:
----------------------------
https://pastebin.com/prCAVSUz

Additional Info:
---------------------------
I already tried deleting the instance and making a new one with a new .zip mod pack. It seems the save itself or multimc is the issue? I also saw another thread that said to add more ram. I already have close to 15gb of ram assigned. I don't think I need more. Any suggestions are much appreciated.

This only started happening when my computer went to sleep while the game was up. Upon returning this issue started happening.

I put in a large part of the log as it was too big to upload in one go. I can include it if needed.

**Comment by Janrupf** [comment]
The issue here is actually Advanced Rocketry. It can't read this file `C:\Users\redacteduser\Desktop\MultiMC\instances\test\minecraft\saves\New Modded BoP World\advRocketry\planetDefs.xml` because it contains invalid data. You should try reporting that at https://github.com/zmaster587/AdvancedRocketry/issues. However, first check if LibVulpes and Advanced Rocketry are up-to-date.

**Comment by user-03** [comment]
> 
> 
> The issue here is actually Advanced Rocketry. It can't read this file `C:\Users\redacteduser\Desktop\MultiMC\instances\test\minecraft\saves\New Modded BoP World\advRocketry\planetDefs.xml` because it contains invalid data. You should try reporting that at https://github.com/zmaster587/AdvancedRocketry/issues. However, first check if LibVulpes and Advanced Rocketry are up-to-date.

Much appreciated! I updated those 2 mods (there were newer versions) and had to delete the advrocketry folder and have it remade by the game. Now my game runs! I didn't mind deleting it since I haven't done anything yet with advanced rocketry.
