### ISSUE TITLE
Launch stops at Getting library files from Mojang 

### ISSUE THREAD

**Issue by T2WIN** [MultiMC/MultiMC5#2702]
System Information
-----------------------------
MultiMC version: 0.6.5 develop 1319 win 32 MultiMC 5

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
I try to start the modpack Omnifactory for the first time and I get stuck at Getting the library files from Mojang

What should happen:
------------------------------
It should launch the pack without any problem

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Setup  Omnifactory 1.0.0 as an instance

2. Launch it

3.

Suspected cause:
---------------------------
I don't have any clue

Logs/Screenshots:
----------------------------
I don't get any

Additional Info:
---------------------------

**Comment by T2WIN** [comment]
https://paste.ee/p/Ry7Gv
I actually got logs

**Comment by peterix** [comment]
Look slike a network issue to me.

Are you ablke to access http://files.minecraftforge.net/maven/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar in a browser?

**Comment by T2WIN** [comment]
Yes I am

**Comment by T2WIN** [comment]
Sorry for the very late response

**Comment by peterix** [comment]
Well, all of the logs are gone... Closing. Sorry.
