### ISSUE TITLE
Chat Sent By Server Not showing up

### ISSUE THREAD

**Issue by KhanBhai-101** [MultiMC/MultiMC5#2710]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
Hmm... MultiMC does not include any chat functionality and you did not provide any details.

**Comment by KhanBhai-101** [comment]
I just updated with further info about the issue...
