### ISSUE TITLE
MultiMC Crashes before mod pack is fully loaded

### ISSUE THREAD

**Issue by Makoto60** [MultiMC/MultiMC5#2711]
System Information
-----------------------------
MultiMC version: 0.6.5-1302 on Win32 - MultiMC 5

Operating System: Windows 10

Summary of the issue or suggestion: I begin to start up Builders Paradise, It will get to phase 2 of laoding mods then exit abruptly with the message "process exited with code -1"
----------------------------------------------

What should happen: Builders paradise should load up normally.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Open MultiMC and begin FTBBuildersParadise - 1.3.0-1.12.2

2.Game begins loading mods

3. Game closes and log will open with code message

Suspected cause:
---------------------------
Ram issue? I've recently updated my java but that didn't cause issues last time i ran it.

Logs/Screenshots:
----------------------------
https://paste.ee/p/HXvGk

Additional Info:
---------------------------
None

**Comment by Janrupf** [comment]
Try to delet the code chicken lib configuration, it somehow is corrupt.

**Comment by Makoto60** [comment]
I removed CodeChickenLib then redownload the file back in and it still
result with the exit code -1

**Comment by Janrupf** [comment]
Don't delete codechickenlib, delete its config. (config/codechickenlib or something like this)

**Comment by Makoto60** [comment]
Ok, I got it working. Thank you so much!
