### ISSUE TITLE
Unable to start any instance in offline mode without internet connection.

### ISSUE THREAD

**Issue by Rencer** [MultiMC/MultiMC5#2712]
OS: Manjaro Linux
MultiMC version: 0.6.5-custom (build from AUR)

I tried to play an instance in offline, without internet connection, but it won't start because MultiMC want to "update" something. The instance is a modpack that I made for my personal singleplayer use only. That pack is runs on the 5 years old Minecraft version 1.7.10.

This is the errors that MultiMC drops:

Instance update failed because: Component metadata update task failed while downloading from remote server:
Job 'Download of meta file index.json' failed to process:
https://v1.meta.multimc.org/index.json
Job 'Download of meta file org.lwjgl/2.9.4-nightly-20150209.json' failed to process:
https://v1.meta.multimc.org/org.lwjgl/2.9.4-nightly-20150209.json
Job 'Download of meta file net.minecraft/1.7.10.json' failed to process:
https://v1.meta.multimc.org/net.minecraft/1.7.10.json
Job 'Download of meta file net.minecraftforge/10.13.4.1614.json' failed to process:
https://v1.meta.multimc.org/net.minecraftforge/10.13.4.1614.json

I thought offline means that I can play it offline, aka without internet connection.
Looking at those links, I think they are not assets or something from Mojang that are a must-have to start Minecraft. Every file that needed to run that instance are already must be somewhere in the folders of MultiMC, because, of course I run that instance several times in normal mode with internet connections while I putting it together.

It would be very nice, if we can play any instances in a real offline environment, when someone doesn't have internet connection at all.

**Comment by darchitectlp** [comment]
Having this same issue. On Mac, El Capitan. I really want MultiMC to be my go-to launcher, as I hate what Mojang has done to theirs, but not being able to launch without being online is a non-starter for me. Thanks for your work though!

**Comment by peterix** [comment]
Cool, I believe this still works as intended. Maybe you are running into some weird corner case, or your metadata only partially updated.

**Comment by peterix** [comment]
Needs closer investigation anyway.

**Comment by TipzTeam** [comment]
It didn't work for me too.

**Comment by UnknownTech** [comment]
I have a desktop system that does not have WiFi (had to take to a friends house to install MultiMC) and when I try to Launch Offline I get prompted for my username and password. It appears that Offline is not really Offline since there is no way to bypass the login.

**Comment by Zetabite** [comment]
you need to login once

**Comment by UnknownTech** [comment]
> you need to login once, too give and proof mmc an account to work with. mmc doesnt support piracy/cracked account/launcher.

I have 8d 7h 44m of playtime for the instance I am trying to play. After installing the 4 instances I have I spent about an hour on each while at my friends house. For the first couple of months after I installed MultiMC (using Version 0.6.7-1375) I had no problems with offline play.

**Comment by Zetabite** [comment]
might need to launch it offline twice, was a bug i had

**Comment by Rencer** [comment]
OS: Manjaro Linux
MultiMC version: 0.6.7-custom (build from AUR)

I didn't played MC for a long time. Now I playing again with exactly the same modpack that I mantoned when I posted this bugreprort, and I can confirm it, it is working perfectly. Now it is possible toplay without any internet connection.
