### ISSUE TITLE
Exception in thread main, process exited with code 1

### ISSUE THREAD

**Issue by swejehtsag** [MultiMC/MultiMC5#2714]
MultiMC version: 0.6.2

Operating System: Windows 7

Whenever I try to open an instance, the log outputs "Exception in thread "main"" and it exits with code 1. I am not sure how to reproduce the issue. This is the log:
MultiMC version: 0.6.2-1222

Minecraft folder is:
C:/Users/kevin/Desktop/Stuff/Games/MultiMC/instances/1.14.3/.minecraft

Java path is:
C:/Program Files/Java/jre7/bin/javaw.exe

Java is version 1.7.0_67, using 64-bit architecture.

Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/instances/1.14.3/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/com/mojang/realms/1.14.17/realms-1.14.17.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/com/mojang/minecraft/1.14.3/minecraft-1.14.3-client.jar

Native libraries:
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/kevin/Desktop/Stuff/Games/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/Users/kevin/Desktop/Stuff/Games/MultiMC/instances/1.14.3/.minecraft --assetsDir C:/Users/kevin/Desktop/Stuff/Games/MultiMC/assets --assetIndex 1.14 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -XX:PermSize=128m, -Duser.language=en]

Minecraft process ID: 11460

Using onesix launcher.

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:171)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Process exited with code 1.

**Comment by tehbasshunter** [comment]
Could be wrong but I think it might be because you're using 1.7 Java on 1.14.x which won't work.

**Comment by swejehtsag** [comment]
> Could be wrong but I think it might be because you're using 1.7 Java on 1.14.x which won't work.

Installed Java 8 and it worked! Thank you!
