### ISSUE TITLE
Unable to resolve mod IDs

### ISSUE THREAD

**Issue by stawz** [MultiMC/MultiMC5#2719]
System Information
-----------------------------
MultiMC version:

0.6.5-1217

Operating System:

Ubuntu 19.04

Summary of the issue or suggestion:
----------------------------------------------

When I try to import All the Mods 3 using "Import from zip", I receive the titular error or the entire program crashes. 

What should happen:
------------------------------

All the Mods 3 should be added to MultiMC.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download the All the Mods 3 zip from CurseForge.

2. Use "Import from zip" to add the pack.

3.

Suspected cause:
---------------------------

I don't know.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

The link just redirects to the main Wiki page.

Additional Info:
---------------------------

**Comment by peterix** [comment]
Cannot reproduce the issue.
