### ISSUE TITLE
mmc-meta.json can become empty, which causes confusing errors

### ISSUE THREAD

**Issue by Monkeyfume** [MultiMC/MultiMC5#2721]
System Information
-----------------------------
MultiMC version: 0.6.5-1302 on win32

Operating System: Win10 Pro x64

Summary of the issue or suggestion:
----------------------------------------------
Upon attempted launch of a modded 1.12.2 instance, the console just shows: `Instance update failed because: Null jar is specified in the metadata, aborting...` and the game doesn't start.

What should happen:
------------------------------
The game should launch normally.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open multimc

2. Launch the instance

Suspected cause:
---------------------------
Something wrong with how the version jar is found. I have no idea what metadata I can change to find a new jar.

Logs/Screenshots:
----------------------------
Screenshot: https://i.imgur.com/ekGVDZD.png
Log: https://pastebin.com/b2Ns04Fz

Additional Info:
---------------------------
By chance, I actually have some interesting info on this issue. Among my MultiMC instances on my PC, I have two different 1.12.2 instances that include Forge and some mods. I "exported" one of these instances to another computer (also running Windows) which had a fresh install of MultiMC. At this point I experienced the issue for the first time and couldn't find a solution, but oh well, I still could play on my main PC. Upon restart of my main PC, these two modded 1.12.2 instances both failed to start, and gave the same error as on the other computer. It's just these two instances that are affected. Vanilla 1.12.2 starts up just fine, and modded 1.13.2 and and 1.14.2 are also ok.

**Comment by Monkeyfume** [comment]
I noticed that in both affected instances, the file called `mmc-pack.json` in the root of the instance folder was, for some reason, blank. After replacing this file with the original file from the .zip I originally loaded the instance from, both instances were able to start normally.

**Comment by peterix** [comment]
If you see `Null jar is specified in the metadata, aborting...`, then you never ran the thing before.

**Comment by peterix** [comment]
And it will not run offline, because you don't have the files.

**Comment by peterix** [comment]
Hmm... mixed up replies with a different issue.

**Comment by peterix** [comment]
Did you leave out `mmc-pack.json` while exporting the instance?

**Comment by peterix** [comment]
Can you share the exported instance?

**Comment by Monkeyfume** [comment]
> Can you share the exported instance?

I've looked on my other computer and confirmed that the exported instance is identical to the original, except for the broken `mmc-pack.json` file. However, I don't think we should blame this on the export process; after all, the original instance AND a different instance broke upon closing MMC and rebooting my PC, as I wrote in "Additional Info".

One more thing to consider is that _I think_ I renamed the two instances prior to their `mmc-pack.json` files getting wiped.

Also, if you're so able, can you remove the `support: multimc` label and re-add `multimc: bug`?

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, please share the broken mmc-pack.json and I'll reopen this issue.

**Comment by zachbryant** [comment]
For the record, I solved this by creating a new profile and copying the mmc-pack.json contents into my empty mmc-pack.json

**Comment by TSGPL** [comment]
I came across this problem as well, the reason that it happened for me specifically was because I ran out of disk space.
