### ISSUE TITLE
[Suggestion] Ignore "the" when sorting mods

### ISSUE THREAD

**Issue by goreae** [MultiMC/MultiMC5#2722]
This is a really simple suggestion. All I'm asking is that in cases where a mod's name starts with "the" like "The Twilight Forest", "The Spice of Life", or "The Eight Fabled Blades", that multimc ignores the "the" at the beginning when sorting. So instead of putting "The Betweenlands" in with the T mods, it would be in the B mods where it belongs.

**Comment by peterix** [comment]
Related to: https://github.com/MultiMC/MultiMC5/issues/2762 because it's close in code.
