### ISSUE TITLE
MultiMC5 fails to build on archlinux

### ISSUE THREAD

**Issue by skwerlman** [MultiMC/MultiMC5#2723]
System Information
-----------------------------
MultiMC version: 0.6.5-2

Operating System: arch linux

Summary of the issue or suggestion:
----------------------------------------------
MultiMC5 fails to build because of deprecations

What should happen:
------------------------------
MultiMC5 should build

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Update arch to use QT 5.13 (now the default on arch!)

2. `yay -S multimc5` or `yay -S multimc5-git`

3. build fails

Suspected cause:
---------------------------
now deprecated in QT 5.13:
qSort (suggested to use std::sort)
trUtf8

Logs/Screenshots:
----------------------------
N/A (build logs are mostly unreadable b/c threading)

Additional Info:
---------------------------
it is possible there are additional deprecations. these are just the ones i ran into in the first ~20% of the build

**Comment by skwerlman** [comment]
additionally, even after editing the PKGBUILD to suppress all deprecations and dev errors, the build still fails with
```
warning: [options] bootstrap class path not set in conjunction with -source 6
error: Source option 6 is no longer supported. Use 7 or later.
error: Target option 6 is no longer supported. Use 7 or later.
warning: [options] bootstrap class path not set in conjunction with -source 6
error: Source option 6 is no longer supported. Use 7 or later.
error: Target option 6 is no longer supported. Use 7 or later.
make[2]: *** [libraries/launcher/CMakeFiles/NewLaunch.dir/build.make:78: jars/CMakeFiles/NewLaunch.dir/java_compiled_NewLaunch] Error 2
make[1]: *** [CMakeFiles/Makefile2:549: libraries/launcher/CMakeFiles/NewLaunch.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [libraries/javacheck/CMakeFiles/JavaCheck.dir/build.make:70: jars/CMakeFiles/JavaCheck.dir/java_compiled_JavaCheck] Error 2
make[1]: *** [CMakeFiles/Makefile2:604: libraries/javacheck/CMakeFiles/JavaCheck.dir/all] Error 2
```

**Comment by peterix** [comment]
Hopefully is fixed now in the current version?

**Comment by skwerlman** [comment]
yep, both the aur packages are updated to 0.6.6 and confirmed working. thanks!
