### ISSUE TITLE
Game crashes during loading screen when using OptiFine_1.14.3_HD_U_F1

### ISSUE THREAD

**Issue by pointlessturtlebutton** [MultiMC/MultiMC5#2728]
System Information
-----------------------------
MultiMC version: 0.6.5-1302

Operating System: Windows 10 x64

Summary of the issue or suggestion:
----------------------------------------------
The game crashes about halfway through the loading screen when running OptiFine_1.14.3_HD_U_F1

What should happen:
------------------------------
Game launches

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create instance of version 1.14.3

2. Install OptiFine_1.14.3_HD_U_F1 according to instruction at https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine

3. Launch game

Suspected cause:
---------------------------
Unknown

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/DEPA1

Additional Info:
---------------------------

**Comment by zipsy** [comment]
The current workaround found by **akoimeexx** in this post: https://www.reddit.com/r/MultiMC/comments/c79oah/optifine_1143_causing_a_crash_on_startup/

You need to install Optifine into a vanilla instalation, then grab the wrapper and the optifine jar and put it in the library folder in your instance.
![image](https://user-images.githubusercontent.com/7001072/60719512-d9e55a00-9f1f-11e9-9891-3944dfcfcdf3.png)

Then in the config make sure you have this:
`"libraries": [
        {
            "MMC-filename": "launchwrapper-2.0.jar",
            "MMC-hint": "local",
            "name": "net.minecraft:launchwrapper:2.0"
        },
        {
            "MMC-filename": "OptiFine-1.14.3_HD_U_F1.jar",
            "MMC-hint": "local",
            "name": "optifine:OptiFine:1.14.3_HD_U_F1"
        }
    ],`

There seems to be a problem with the current wrapper, so we use the 2.0 version from Optifine itself.
