### ISSUE TITLE
Can not use "DRI_PRIME=1" wrapper command on manjaro(archlinux)

### ISSUE THREAD

**Issue by Logic530** [MultiMC/MultiMC5#2729]
System Information
-----------------------------
MultiMC version:
0.6.5
Operating System:
manjaro(archlinux)

Summary of the issue or suggestion:
----------------------------------------------
Instance won't launch after applying wrapper command "DRI_PRIME=1", and this command is supposed to make minecraft running on delicated graphics card.

What should happen:
------------------------------
The game launches and is running on delicated graphics card.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.
Add "DRI_PRIME=1" as wrapper command

2.
Launch instance

Suspected cause:
---------------------------
Unknown

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![2019-07-02 16-59-34 的屏幕截图](https://user-images.githubusercontent.com/22793670/60475080-1a3aa300-9ca8-11e9-970b-476a3f5fb664.png)
This is how I setup the command
![2019-07-02 17-01-10 的屏幕截图](https://user-images.githubusercontent.com/22793670/60475110-3d655280-9ca8-11e9-9b83-1e809f568afa.png)
What happened when I launch an instance
![2019-07-02 16-59-46 的屏幕截图](https://user-images.githubusercontent.com/22793670/60475122-58d05d80-9ca8-11e9-8e3a-3fe9b52e71f2.png)
Proof of "DRI_PRIME=1" works on my system

Additional Info:
---------------------------
Game does launch without "DRI_PRIME=1" and of course running on integrated graphics card

**Comment by jikuja** [comment]
Try `bash -c "export DRI_PRIME=1;$INST_JAVA \"$@\""` as wrapper command

**Comment by Logic530** [comment]
Thanks! It worked!

**Comment by T3sT3ro** [comment]
for anyone who came here but `DRI_PRIME=1` is not working: 
This syntax is used for open source nvidia drivers (noveau). To use it for proprietary drivers, you have to use `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia`.

Just put `env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia` in the wrapper command.

To confirm that this works, try this in terminal:
```
> glxinfo | grep vendor
# should print strings with integrated graphics (mesa, intel, SGI etc.)

> env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia glxinfo | grep vendor
# should print strings with NVIDIA Corporation
```

sources: [[1]](https://askubuntu.com/questions/1409964/dri-prime-not-working), [[2]](https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/primerenderoffload.html), [[3]](https://askubuntu.com/questions/1201072/how-nvidia-on-demand-option-works-in-nvidia-x-server-settings)
