### ISSUE TITLE
No Versions Available After 1.12 

### ISSUE THREAD

**Issue by OliverLaVey** [MultiMC/MultiMC5#2730]
System Information
-----------------------------
MultiMC version: Version 0.6.5-1302

Operating System: Windows 32 Bit

Summary of the issue or suggestion:
----------------------------------------------
When I try to install forge for versions 1.13 or after, this message pops up saying that there are no forge versions, when on the forge website there clearly are.

What should happen:
------------------------------
I should be able to install the versions of forge for 1.13 and above, it makes no sense for it to say that there aren't any where there clearly are.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Click install forge for 1.13+, and there are no versions.

Suspected cause:
---------------------------
It might be something wrong with my laptop, but I'm unsure.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![image](https://user-images.githubusercontent.com/52472168/60550268-abc80600-9ce4-11e9-899a-30d29b1d29a0.png)

Additional Info:
---------------------------
I'm using the latest version of Windows, and this issue has been happening ever since the 1.13 updates came out, I've been unable to install forge on MultiMC.

**Comment by peterix** [comment]
There are no compatible versions above 1.12.2

**Comment by OliverLaVey** [comment]
exactly why is that? there is very obviously 1.13+ versions on the forge website. so why aren't they compatible?

**Comment by tehbasshunter** [comment]
Adding forge to MMC is like putting a round object in a square. Just doesn't fit right.

**Comment by OliverLaVey** [comment]
older versions of forge worked fine on MMC, so why doesn't 1.13?

**Comment by peterix** [comment]
they made it complicated.

**Comment by peterix** [comment]
for all the bad reasons that shouldn't be reasons at all.

**Comment by OliverLaVey** [comment]
man, that sucks. i was looking forward to playing with some mods. i guess thats how the world works sometimes. do you ever think there will be forge compatibility? or will it be stuck in the past forever?

**Comment by peterix** [comment]
Anyway, dupe of https://github.com/MultiMC/MultiMC5/issues/2544, locking this. You can read all about it there, I don't want to repeat myself.
