### ISSUE TITLE
MultiMC and OptiFine Wiki update for 1.14

### ISSUE THREAD

**Issue by mcfilmmakers** [MultiMC/MultiMC5#2731]
System Information
-----------------------------
MultiMC version: 5

Operating System: windows 10

Summary of the issue or suggestion:
----------------------------------------------
This wiki page needs to be updated to reflect 1.14. These instructions do not work with 1.14.3 and Optifine for 1.14.3 U F1.

What should happen:
------------------------------
{
    "formatVersion": 1,
    "+libraries": [
        {
            "name": "net.minecraft:launchwrapper:1.12"
        },
        {
            "name": "optifine:OptiFine:1.14.3_HD_U_F1",
            "MMC-hint": "local",
            "MMC-filename": "OptiFine_1.14.3_HD_U_F1.jar"
        }
    ],
    "+tweakers": [ "optifine.OptiFineTweaker" ],
    "fileId": "optifine.OptiFine",
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "requires": [
        {
            "uid": "net.minecraft",
            "equals": "1.14.3"
        }
    ],
    "name": "OptiFine",
    "version": "1.14.3_HD_U_F1"
}

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Follwoed the instructions on the wiki

2. Modified the entry to the correct 1.14.3 U F1 info

3. Ran Minecraft and got the below error

Suspected cause:
---------------------------
Out of date wiki instructions

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

https://paste.ee/p/YVfsB

Additional Info:
---------------------------

**Comment by little-hophop** [comment]
If you want to install Optifine on 1.14.3 using MultiMC all you have to do is:
1. Download the correct Optifine version
2. Open the normal Minecraft launcher once on the correct version (1.14.3 in this case) (you can close Minecraft again afterwards)
3. Open the downloaded Optifine .jar file
4. Once it is open click on 'Extract'
5. Once it is extracted you should have a new Optifine .jar file with the same name as the one you extracted except this one has _MOD added at the end
6. Open MultiMC
7. Create/Open an instance with the correct version (in this case 1.14.3)
8. Click on 'Edit Instance'
9. Click on 'Add to Minecraft.jar'
10. Select the Optifine file which you extracted (the one with _MOD at the end)
11. Launch the instance

**Comment by geniiii** [comment]
an updated JSON that actually works  
`{
    "formatVersion": 1,
    "+libraries": [
	    {
            "name": "optifine:OptiFine:1.14.3_HD_U_F1",
            "MMC-hint": "local",
            "MMC-filename": "OptiFine_1.14.3_HD_U_F1.jar"
        },
        {
            "name": "optifine:launchwrapper:2.0",
			"MMC-hint": "local",
			"MMC-filename": "launchwrapper-2.0.jar"
        }
    ],
    "+tweakers": [ "optifine.OptiFineTweaker" ],
    "fileId": "optifine.OptiFine",
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "requires": [
        {
            "uid": "net.minecraft",
            "equals": "1.14.3"
        }
    ],
    "name": "OptiFine",
    "version": "1.14.3_HD_U_F9"
}`

**Comment by mcfilmmakers** [comment]
> If you want to install Optifine on 1.14.3 using MultiMC all you have to do is:
> 
> 1. Download the correct Optifine version
> 2. Open the normal Minecraft launcher once on the correct version (1.14.3 in this case) (you can close Minecraft again afterwards)
> 3. Open the downloaded Optifine .jar file
> 4. Once it is open click on 'Extract'
> 5. Once it is extracted you should have a new Optifine .jar file with the same name as the one you extracted except this one has _MOD added at the end
> 6. Open MultiMC
> 7. Create/Open an instance with the correct version (in this case 1.14.3)
> 8. Click on 'Edit Instance'
> 9. Click on 'Add to Minecraft.jar'
> 10. Select the Optifine file which you extracted (the one with _MOD at the end)
> 11. Launch the instance

Doesn't work:

`Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    cvo.m()V @195: invokevirtual
  Reason:
    Type 'czk' (current frame, stack[1]) is not assignable to 'czx'
  Current Frame:
    bci: @195
    flags: { }
    locals: { 'cvo' }
    stack: { 'cvo', 'czk' }
  Bytecode:
    0x0000000: 2ab4 082d 9e00 0d2a 59b4 082d 0464 b508
    0x0000010: 2d2a b401 4513 085a b606 612a b406 8f9a
    0x0000020: 000a 2ab4 0455 b608 5b2a b401 45b6 0665
    0x0000030: 2ab4 0426 0cb6 085d 2ab4 022e 2ab4 043f
    0x0000040: 2ab4 07e7 b608 602a b401 4513 0862 b606
    0x0000050: 612a b406 8f9a 0011 2ab4 043f c600 0a2a
    0x0000060: b407 fbb6 0863 2ab4 0145 1303 e6b6 067b
    0x0000070: 2ab4 043f c600 0a2a b403 69b6 0864 2ab4
    0x0000080: 05de c700 472a b405 e5c6 0040 2ab4 05e5
    0x0000090: b605 eb0b 969d 0015 2ab4 05de c105 ed9a
    0x00000a0: 000b 2a01 b602 5aa7 0042 2ab4 05e5 b608
    0x00000b0: 6799 0038 2ab4 043f c600 312a bb08 6959
    0x00000c0: b708 6ab6 025a a700 232a b405 dec6 001c
    0x00000d0: 2ab4 05de c108 6999 0012 2ab4 05e5 b608
    0x00000e0: 679a 0008 2a01 b602 5a2a b405 dec6 000a
    0x00000f0: 2a11 2710 b507 e22a b405 dec6 0019 2aba
    0x0000100: 086e 0000 1308 702a b405 deb6 0874 b608
    0x0000110: 79b8 087d 2ab4 027c b405 fe9a 000a 2ab4
    0x0000120: 0455 b608 7e2a b405 5cc7 0036 2ab4 05de
    0x0000130: c600 0d2a b405 deb4 0881 9900 252a b401
    0x0000140: 4513 0883 b606 7bb8 0677 2ab7 0885 2ab4
    0x0000150: 07e2 9e00 0d2a 59b4 07e2 0464 b507 e22a
    0x0000160: b404 3fc6 0068 2ab4 0145 1306 8db6 067b
    0x0000170: 2ab4 068f 9a00 0a2a b404 26b6 0886 2ab4
    0x0000180: 0145 1308 88b6 067b 2ab4 068f 9a00 0a2a
    0x0000190: b404 35b6 0889 2ab4 0145 1308 8bb6 067b
    0x00001a0: 2ab4 068f 9a00 382a b404 3fb6 088d 9e00
    0x00001b0: 132a b404 3f2a b404 3fb6 088d 0464 b608
    0x00001c0: 8f2a b404 3fb6 0890 a700 142a b404 26b6
    0x00001d0: 0891 9900 0a2a b404 26b6 0892 2ab4 068f
    0x00001e0: 9a00 0a2a b403 99b6 0893 2ab4 038f 2ab4
    0x00001f0: 068f b608 942a b404 3fc6 00c9 2ab4 068f
    0x0000200: 9a00 6a2a b404 3f2a b404 3fb6 0897 b208
    0x0000210: 9ca5 0007 04a7 0004 0304 b608 9d2a b402
    0x0000220: 2eb6 089e 2ab4 043f ba08 a600 00b6 08a9
    0x0000230: a700 3a4c 2b13 08ab b802 3e4d 2ab4 043f
    0x0000240: c700 182c 1308 adb6 0243 4e2d 1308 af13
    0x0000250: 08b1 b608 b4a7 000c 2ab4 043f 2cb6 08b7
    0x0000260: 57bb 0236 592c b708 b9bf 2ab4 0145 1308
    0x0000270: bbb6 067b 2ab4 068f 9a00 2f2a b404 3fc6
    0x0000280: 0028 2ab4 043f 2ab4 05e5 b408 bdb8 079e
    0x0000290: 2ab4 05e5 b408 bfb8 079e 2ab4 05e5 b408
    0x00002a0: c1b8 079e b608 c42a b401 4513 08c6 b606
    0x00002b0: 7b2a b406 8f9a 0025 2ab4 0444 b608 c7a7
    0x00002c0: 001b 2ab4 08c9 c600 142a b401 4513 08cb
    0x00002d0: b606 7b2a b408 c9b6 08ce 2ab4 0145 1308
    0x00002e0: d0b6 067b 2ab4 02f9 b608 d12a b401 45b6
    0x00002f0: 0665 b1                                
  Exception Handler Table:
    bci [548, 560] => handler: 563
  Stackmap Table:
    same_frame(@17)
    same_frame(@41)
    same_frame(@102)
    same_frame(@126)
    same_frame(@170)
    same_frame(@201)
    same_frame(@233)
    same_frame(@247)
    same_frame(@276)
    same_frame(@293)
    same_frame(@317)
    same_frame(@351)
    same_frame(@382)
    same_frame(@406)
    same_frame(@449)
    same_frame(@459)
    same_frame(@476)
    same_frame(@490)
    same_locals_1_stack_item_frame(@536,Object[#1519])
    full_frame(@537,{Object[#2]},{Object[#1519],Integer})
    same_locals_1_stack_item_frame(@563,Object[#563])
    append_frame(@600,Top,Object[#571])
    full_frame(@609,{Top,Top,Object[#571]},{})
    full_frame(@618,{Object[#2]},{})
    same_frame(@679)
    same_frame(@706)
    same_frame(@730)

	at net.minecraft.client.main.Main.main(SourceFile:154)
	... 8 more
Exiting with -1
[12:28:19] [Client Shutdown Thread/ERROR]: Caught previously unhandled exception :
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    cvo.m()V @195: invokevirtual
  Reason:
    Type 'czk' (current frame, stack[1]) is not assignable to 'czx'
  Current Frame:
    bci: @195
    flags: { }
    locals: { 'cvo' }
    stack: { 'cvo', 'czk' }
  Bytecode:
    0x0000000: 2ab4 082d 9e00 0d2a 59b4 082d 0464 b508
    0x0000010: 2d2a b401 4513 085a b606 612a b406 8f9a
    0x0000020: 000a 2ab4 0455 b608 5b2a b401 45b6 0665
    0x0000030: 2ab4 0426 0cb6 085d 2ab4 022e 2ab4 043f
    0x0000040: 2ab4 07e7 b608 602a b401 4513 0862 b606
    0x0000050: 612a b406 8f9a 0011 2ab4 043f c600 0a2a
    0x0000060: b407 fbb6 0863 2ab4 0145 1303 e6b6 067b
    0x0000070: 2ab4 043f c600 0a2a b403 69b6 0864 2ab4
    0x0000080: 05de c700 472a b405 e5c6 0040 2ab4 05e5
    0x0000090: b605 eb0b 969d 0015 2ab4 05de c105 ed9a
    0x00000a0: 000b 2a01 b602 5aa7 0042 2ab4 05e5 b608
    0x00000b0: 6799 0038 2ab4 043f c600 312a bb08 6959
    0x00000c0: b708 6ab6 025a a700 232a b405 dec6 001c
    0x00000d0: 2ab4 05de c108 6999 0012 2ab4 05e5 b608
    0x00000e0: 679a 0008 2a01 b602 5a2a b405 dec6 000a
    0x00000f0: 2a11 2710 b507 e22a b405 dec6 0019 2aba
    0x0000100: 086e 0000 1308 702a b405 deb6 0874 b608
    0x0000110: 79b8 087d 2ab4 027c b405 fe9a 000a 2ab4
    0x0000120: 0455 b608 7e2a b405 5cc7 0036 2ab4 05de
    0x0000130: c600 0d2a b405 deb4 0881 9900 252a b401
    0x0000140: 4513 0883 b606 7bb8 0677 2ab7 0885 2ab4
    0x0000150: 07e2 9e00 0d2a 59b4 07e2 0464 b507 e22a
    0x0000160: b404 3fc6 0068 2ab4 0145 1306 8db6 067b
    0x0000170: 2ab4 068f 9a00 0a2a b404 26b6 0886 2ab4
    0x0000180: 0145 1308 88b6 067b 2ab4 068f 9a00 0a2a
    0x0000190: b404 35b6 0889 2ab4 0145 1308 8bb6 067b
    0x00001a0: 2ab4 068f 9a00 382a b404 3fb6 088d 9e00
    0x00001b0: 132a b404 3f2a b404 3fb6 088d 0464 b608
    0x00001c0: 8f2a b404 3fb6 0890 a700 142a b404 26b6
    0x00001d0: 0891 9900 0a2a b404 26b6 0892 2ab4 068f
    0x00001e0: 9a00 0a2a b403 99b6 0893 2ab4 038f 2ab4
    0x00001f0: 068f b608 942a b404 3fc6 00c9 2ab4 068f
    0x0000200: 9a00 6a2a b404 3f2a b404 3fb6 0897 b208
    0x0000210: 9ca5 0007 04a7 0004 0304 b608 9d2a b402
    0x0000220: 2eb6 089e 2ab4 043f ba08 a600 00b6 08a9
    0x0000230: a700 3a4c 2b13 08ab b802 3e4d 2ab4 043f
    0x0000240: c700 182c 1308 adb6 0243 4e2d 1308 af13
    0x0000250: 08b1 b608 b4a7 000c 2ab4 043f 2cb6 08b7
    0x0000260: 57bb 0236 592c b708 b9bf 2ab4 0145 1308
    0x0000270: bbb6 067b 2ab4 068f 9a00 2f2a b404 3fc6
    0x0000280: 0028 2ab4 043f 2ab4 05e5 b408 bdb8 079e
    0x0000290: 2ab4 05e5 b408 bfb8 079e 2ab4 05e5 b408
    0x00002a0: c1b8 079e b608 c42a b401 4513 08c6 b606
    0x00002b0: 7b2a b406 8f9a 0025 2ab4 0444 b608 c7a7
    0x00002c0: 001b 2ab4 08c9 c600 142a b401 4513 08cb
    0x00002d0: b606 7b2a b408 c9b6 08ce 2ab4 0145 1308
    0x00002e0: d0b6 067b 2ab4 02f9 b608 d12a b401 45b6
    0x00002f0: 0665 b1                                
  Exception Handler Table:
    bci [548, 560] => handler: 563
  Stackmap Table:
    same_frame(@17)
    same_frame(@41)
    same_frame(@102)
    same_frame(@126)
    same_frame(@170)
    same_frame(@201)
    same_frame(@233)
    same_frame(@247)
    same_frame(@276)
    same_frame(@293)
    same_frame(@317)
    same_frame(@351)
    same_frame(@382)
    same_frame(@406)
    same_frame(@449)
    same_frame(@459)
    same_frame(@476)
    same_frame(@490)
    same_locals_1_stack_item_frame(@536,Object[#1519])
    full_frame(@537,{Object[#2]},{Object[#1519],Integer})
    same_locals_1_stack_item_frame(@563,Object[#563])
    append_frame(@600,Top,Object[#571])
    full_frame(@609,{Top,Top,Object[#571]},{})
    full_frame(@618,{Object[#2]},{})
    same_frame(@679)
    same_frame(@706)
    same_frame(@730)

	at net.minecraft.client.main.Main$2.run(SourceFile:137) ~[minecraft.jar:?]
Process exited with code -1.
`

**Comment by TheDevFreak** [comment]
@geniiii Where did you get a launchwrapper-2.0jar ?

**Comment by geniiii** [comment]
> @geniiii Where did you get a launchwrapper-2.0.jar ?

extract from the OptiFine JAR

**Comment by TheDevFreak** [comment]
> 
> 
> > @geniiii Where did you get a launchwrapper-2.0.jar ?
> 
> extract from the OptiFine JAR

Perfect thanks. I can now confirm that this works for me on 1.14.4 with the latest optifine version at the time of writing of "OptiFine 1.14.4 HD U F2 pre1"

So my libraries folder contains:

- launchwrapper-of-2.1.jar
- OptiFine_1.14.4_HD_U_F2_pre1_MOD.jar

and the JSON I'm using is:
```
{
    "formatVersion": 1,
    "+libraries": [
	    {
            "name": "optifine:OptiFine:1.14.4_HD_U_F2_pre1",
            "MMC-hint": "local",
            "MMC-filename": "OptiFine_1.14.4_HD_U_F2_pre1_MOD.jar"
        },
        {
            "name": "optifine:launchwrapper:2.1",
			"MMC-hint": "local",
			"MMC-filename": "launchwrapper-of-2.1.jar"
        }
    ],
    "+tweakers": [ "optifine.OptiFineTweaker" ],
    "fileId": "optifine.OptiFine",
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "requires": [
        {
            "uid": "net.minecraft",
            "equals": "1.14.4"
        }
    ],
    "name": "OptiFine",
    "version": "1.14.4_HD_U_F2_pre1"
}
```

**Comment by VampireMonkey** [comment]
> > > @geniiii Where did you get a launchwrapper-2.0.jar ?
> > 
> > 
> > extract from the OptiFine JAR
> 
> Perfect thanks. I can now confirm that this works for me on 1.14.4 with the latest optifine version at the time of writing of "OptiFine 1.14.4 HD U F2 pre1"
> 
> So my libraries folder contains:
> 
> * launchwrapper-of-2.1.jar
> * OptiFine_1.14.4_HD_U_F2_pre1_MOD.jar
> 
> and the JSON I'm using is:
> 
> ```
> {
>     "formatVersion": 1,
>     "+libraries": [
> 	    {
>             "name": "optifine:OptiFine:1.14.4_HD_U_F2_pre1",
>             "MMC-hint": "local",
>             "MMC-filename": "OptiFine_1.14.4_HD_U_F2_pre1_MOD.jar"
>         },
>         {
>             "name": "optifine:launchwrapper:2.1",
> 			"MMC-hint": "local",
> 			"MMC-filename": "launchwrapper-of-2.1.jar"
>         }
>     ],
>     "+tweakers": [ "optifine.OptiFineTweaker" ],
>     "fileId": "optifine.OptiFine",
>     "mainClass": "net.minecraft.launchwrapper.Launch",
>     "requires": [
>         {
>             "uid": "net.minecraft",
>             "equals": "1.14.4"
>         }
>     ],
>     "name": "OptiFine",
>     "version": "1.14.4_HD_U_F2_pre1"
> }
> ```

Worked for me in the full "OptiFine 1.14.4 HD U F2" release.

**Comment by Josh74000** [comment]
I tried using it, but it crashed before it went to the main menu

**Comment by loverthehater** [comment]
```json
{
    "formatVersion": 1,
    "+libraries": [
	    {
            "name": "optifine:OptiFine:1.14.4_HD_U_F2",
            "MMC-hint": "local",
            "MMC-filename": "OptiFine_1.14.4_HD_U_F2_MOD.jar"
        },
        {
            "name": "optifine:launchwrapper:2.1",
			"MMC-hint": "local",
			"MMC-filename": "launchwrapper-of-2.1.jar"
        }
    ],
    "+tweakers": [ "optifine.OptiFineTweaker" ],
    "fileId": "optifine.OptiFine",
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "requires": [
        {
            "uid": "net.minecraft",
            "equals": "1.14.4"
        }
    ],
    "name": "OptiFine",
    "version": "1.14.4_HD_U_F2"
}
```
This worked with 1.14.4 and 1.14.4_HD_U_F2. (same as @geniiii just without `pre1`)

**Comment by nift4** [comment]
https://github.com/MMCInstances/OptifineInstances/releases/tag/v1.14.4-1.3 for premade instances.

**Comment by jamierocks** [comment]
Looks like this has been done.
