### ISSUE TITLE
Minecraft Crashes On Startup, language ~~error~~?

### ISSUE THREAD

**Issue by wtdm** [MultiMC/MultiMC5#2732]
System Information

Macbook Pro (2010) Intel core nvidia graphics
-----------------------------
MultiMC version:
0.6.5
Operating System:
lubuntu 19.04
Summary of the issue or suggestion:
minecraft crashes when the window pops up 
----------------------------------------------

What should happen:
------------------------------
it should continue loading when the minecraft window pops up

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. install ubuntu 19.04

2. install multimc

3. try running any minecraft version Or 1.13

Suspected cause:
---------------------------
i don't have language downloaded?

Logs/Screenshots:
----------------------------
MultiMC version: 0.6.5-1217

Minecraft folder is:
/home/commanding/.local/share/multimc/instances/1.13/.minecraft

Java path is:
/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

Checking Java version...
Java is version 1.8.0_212, using 64-bit architecture.

Intel(R) Core(TM)2 Duo CPU     P8800  @ 2.66GHz
NVIDIA Corporation MCP89 [GeForce 320M] (rev a2)

Subsystem: Apple Inc. MCP89 [GeForce 320M]

Kernel driver in use: nouveau

Main Class:
  net.minecraft.client.main.Main

Native path:
  /home/commanding/.local/share/multimc/instances/1.13/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  /home/commanding/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6.jar
  /home/commanding/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6.jar
  /home/commanding/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6.jar
  /home/commanding/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6.jar
  /home/commanding/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6.jar
  /home/commanding/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6.jar
  /home/commanding/.local/share/multimc/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  /home/commanding/.local/share/multimc/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /home/commanding/.local/share/multimc/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /home/commanding/.local/share/multimc/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /home/commanding/.local/share/multimc/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /home/commanding/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /home/commanding/.local/share/multimc/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/commanding/.local/share/multimc/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/commanding/.local/share/multimc/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/commanding/.local/share/multimc/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/commanding/.local/share/multimc/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  /home/commanding/.local/share/multimc/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /home/commanding/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /home/commanding/.local/share/multimc/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /home/commanding/.local/share/multimc/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /home/commanding/.local/share/multimc/libraries/com/mojang/brigadier/0.1.27/brigadier-0.1.27.jar
  /home/commanding/.local/share/multimc/libraries/com/mojang/datafixerupper/1.0.16/datafixerupper-1.0.16.jar
  /home/commanding/.local/share/multimc/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /home/commanding/.local/share/multimc/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  /home/commanding/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/commanding/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/commanding/.local/share/multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/commanding/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/commanding/.local/share/multimc/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  /home/commanding/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  /home/commanding/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  /home/commanding/.local/share/multimc/libraries/com/mojang/realms/1.13.4/realms-1.13.4.jar
  /home/commanding/.local/share/multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  /home/commanding/.local/share/multimc/libraries/com/mojang/minecraft/1.13/minecraft-1.13-client.jar

Native libraries:
  /home/commanding/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6-natives-linux.jar
  /home/commanding/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6-natives-linux.jar
  /home/commanding/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6-natives-linux.jar
  /home/commanding/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6-natives-linux.jar
  /home/commanding/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6-natives-linux.jar
  /home/commanding/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6-natives-linux.jar
  /home/commanding/.local/share/multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar

Params:
  --username  --version MultiMC5 --gameDir /home/commanding/.local/share/multimc/instances/1.13/.minecraft --assetsDir /home/commanding/.local/share/multimc/assets --assetIndex 1.13 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 5620

Using onesix launcher.

[09:19:35] [Client thread/INFO]: Setting user: aitherNight
[09:19:38] [Client thread/INFO]: LWJGL Version: 3.1.6 build 14
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 04/07/19 9:19 AM
Description: Initializing game

java.lang.RuntimeException: GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
	at cua.b(SourceFile:144)
	at cua.b(SourceFile:121)
	at cua.a(SourceFile:56)
	at cua.<init>(SourceFile:42)
	at cfi.am(SourceFile:443)
	at cfi.a(SourceFile:377)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cua.b(SourceFile:144)
	at cua.b(SourceFile:121)
	at cua.a(SourceFile:56)
	at cua.<init>(SourceFile:42)
	at cfi.am(SourceFile:443)

-- Initialization --
Details:
Stacktrace:
	at cfi.a(SourceFile:377)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.13
	Operating System: Linux (amd64) version 5.0.0-20-generic
	Java Version: 1.8.0_212, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 663785160 bytes (633 MB) / 762839040 bytes (727 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	Launched Version: MultiMC5
	LWJGL: 3.1.6 build 14
	OpenGL: NVAF GL version 3.3 (Compatibility Profile) Mesa 19.0.2, nouveau
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Core(TM)2 Duo CPU P8800 @ 2.66GHz
#@!@# Game crashed! Crash report saved to: #@!@# /home/commanding/.local/share/multimc/instances/1.13/.minecraft/crash-reports/crash-2019-07-04_09.19.40-client.txt
Process exited with code 255.
Clipboard copy at: 04 Jul 2019 09:33:21 -0700

Additional Info:
---------------------------
Please Help I just want to run minecraft on my laptop and play on my server

**Comment by wtdm** [comment]
If you know any threads of this exact issue please say so.

**Comment by wtdm** [comment]
also i'm not running any mods.

**Comment by wtdm** [comment]
i have dual boot, mac and lubuntu

**Comment by wtdm** [comment]
i also have a video of the problem.

https://youtu.be/tPbGxa4aHxc

**Comment by QuImUfu** [comment]
I'd recommend you to install the proprietary Nvidia drivers via Start -> Settings -> Additional Drivers. 
The open source ones have lots of issues with minecraft and bad performance, even if you get them to work.

**Comment by wtdm** [comment]
i tried but lubuntu crashes on startup.

**Comment by QuImUfu** [comment]
Sorry it took me so long.  
What do you mean with "lubuntu crashes on startup". 
Does the system not start any more after installing that driver?  
Does it throw you into a text console?  
What version of the driver did you install?

**Comment by peterix** [comment]
Assuming user gave up... :crying_cat_face:
