### ISSUE TITLE
Forge 1.14 Not Showing

### ISSUE THREAD

**Issue by Dory05** [MultiMC/MultiMC5#2733]
System Information
-----------------------------
MultiMC version: MultiMC5: 0.6.5-1302 on win32

Operating System: Windows 10 (64 bit)

Summary of the issue or suggestion:
----------------------------------
When attempting to load forge onto version 1.14.2, the message "No Forge Versions are Available for 1.14.2", despite the fact that these versions exist on the website for Minecraft Forge.

What should happen:
--------------------------------
Versions for Forge 1.14.2 should be shown.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a new instance of Minecraft of version 1.14.2

2. Try to Install Forge

3. No versions are available.

Suspected cause:
---------------------------
Unknown

Logs/Screenshots:
----------------------------
Screenshot below:
![Untitled](https://user-images.githubusercontent.com/47395472/60761066-4c813300-a00f-11e9-978d-99571821d3cb.png)

**Comment by TheBritishMidget** [comment]
It doesn't support it yet
