### ISSUE TITLE
Why is there no Forge version 1.13 or higher?

### ISSUE THREAD

**Issue by Spturate** [MultiMC/MultiMC5#2734]
Why is there no Forge version 1.13 or higher? ? ? I saw that forge has been updated!
[https://i.loli.net/2019/07/09/5d237ae8c25c827101.png](url)

[https://i.loli.net/2019/07/09/5d237ae9073e869823.png](url)

[https://i.loli.net/2019/07/09/5d237ae908df690902.png](url)

https://i.loli.net/2019/07/09/5d237ae92af8d49388.png

**Comment by tehbasshunter** [comment]
[Because there's no way to properly add it at the moment](https://github.com/MultiMC/MultiMC5/issues/2544)
