### ISSUE TITLE
Crash on launching Agrarian Skies 2 with MultiMC

### ISSUE THREAD

**Issue by Hidegamerr** [MultiMC/MultiMC5#2735]
System Information
-----------------------------
MultiMC version: Version 0.6.5-1302 on win32

Operating System: x64-based PC

Summary of the issue or suggestion:
----------------------------------------------
If I try to launch the Agrarian Skies 2 modpack in MultiMC, it gives the mojang startup-screen. That is all well and fine, but when it is done with the loading screen and it is about to open minecraft. It goes to the console and give the log down below.

What should happen:
------------------------------
The mojang startup-screen closes and it should start minecraft like normally

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.   Add instance with import from zip.

2.   Use the zip file of Agrarian Skies 2 from this link: https://www.curseforge.com/minecraft/modpacks/agrarian-skies-2/download/2736974

3.   Click OK and Agrarian Skies 2 is added to your MultiMC

4.   Run Agrarian Skies 2, it should launch the mojang startup-screen and load the instance.

5.   When it is done with the mojang startup-screen, it should be opening the console with the log down below.

Suspected cause:
---------------------------
I have no idea what could cause the problem.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

The console window log: https://paste.ee/p/0KtEh

Additional Info:
---------------------------
None!

**Comment by tehbasshunter** [comment]
You're using 32bit Java. You need 64.

https://java.com/en/download/manual.jsp

**Comment by Hidegamerr** [comment]
Thank you very much! It works now :)
