### ISSUE TITLE
Cannot launch versions 1.12.2 and below

### ISSUE THREAD

**Issue by ihax1234567890** [MultiMC/MultiMC5#2737]
System Information
-----------------------------
MultiMC version: 0.6.5-custom

Operating System: Debian GNU/Linux 10

Summary of the issue or suggestion: When I try to launch any version that is 1.12.2 or below, it gives an error. However, versions above 1.12.2 work fine.
----------------------------------------------

What should happen:
------------------------------
The game should launch without error.

Steps to reproduce the issue:
-------------------------------------------------------------
1. Open MultiMC.

2. Create an instance for a version that is 1.12.2 or lower.

3. Launch it, and it gives an error.

Suspected cause:
---------------------------
At first, I thought it could be that I was using Java 12. I installed Java 8, however it still gives the same error.

Logs/Screenshots:
----------------------------
https://paste.ee/p/jEGQJ

Additional Info:
---------------------------
I am using OpenJDK. I don't think this is the cause of the issue, as versions above 1.12.2 still work fine.

**Comment by QuImUfu** [comment]
looks like #2669

**Comment by ihax1234567890** [comment]
I installed the NVIDIA driver, and it worked! Thank you for linking that issue!
