### ISSUE TITLE
Unable to add account, Invalid User Credentials or password

### ISSUE THREAD

**Issue by jon-joy-1999** [MultiMC/MultiMC5#2739]
System Information
-----------------------------
MultiMC version:  0.6.6-1341

Operating System: Windows 10 v1803

Summary of the issue or suggestion:
----------------------------------------------
Trying to add my account to MultiMC says my username or password are invalid. 
I have tested my username credentials in the Minecraft launcher and they work there.

What should happen:
------------------------------
I should be able to add my credentials to MultiMC

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Attempt to login with a username that contains a + and password

Suspected cause:
---------------------------
I think it caused because my username contains a + (plus) sign in it (ab+cd@address.com).
For security purposes my address is unique to Minecraft and not public. If it is required for testing I can provide it privately.

Logs/Screenshots:
----------------------------
https://pastebin.com/ZzBaZAuD
https://imgur.com/5ctj2SX

Additional Info:
---------------------------

**Comment by Chew** [comment]
Tested this with a test email I made that contained a plus in it.
However I got this error (because I didn't buy the game), see "__account exists__"
![image](https://user-images.githubusercontent.com/8278263/61674315-f8d24300-acb8-11e9-8846-26d1e9553e42.png)
I was able to sign into the main launcher, but of course it said Demo.

**Comment by jon-joy-1999** [comment]
Yeah, pastebin expired about 4 days ago. I've retried logging in again and still have the same error. I've also created a test account and I get the Authentication server didn't specify a currently selected profile. error message from the test account as well. I've posted both logs https://paste.ee/p/bwvpl here

**Comment by verbal-kimt** [comment]
Same problem here with a regular email "first.name@zz.com"
MultiMC5 0.6.11-1430 win32 on W10 v2004

**Comment by spannerman79** [comment]
@verbal-kimt the login auth has nothing to do with MultiMC but with your account over at https://my.minecraft.net/login/

If its invalid then you have entered incorrect info.

**Comment by verbal-kimt** [comment]
I entered the same info I use there.

**Comment by verbal-kimt** [comment]
Can it be the reason, that I have the Windows 10 Edition from the MS Store and not the Java Version?

**Comment by kb-1000** [comment]
MultiMC only supports Java Edition.

**Comment by Janrupf** [comment]
Oh... yeah. The Java edition is a separate thing, you will have to buy it if you want to use it.

**Comment by verbal-kimt** [comment]
Ok. Thank you all.
