### ISSUE TITLE
error 1 multimc

### ISSUE THREAD

**Issue by Henrico326** [MultiMC/MultiMC5#2742]
I installed multimc recently ,when i try to start a version above java 7 it error, I already looked for all errors related to '' error 1 or -1 '' but I did not find anything, so I hope you help me

 this is the error

MultiMC version: 0.6.6-1341

Minecraft folder is:
C:/Users/User/Documents/Jogos/MultiMC/instances/1.14.3/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

O Java é da versão 1.8.0_211, usando arquitetura de 64-bits

Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/User/Documents/Jogos/MultiMC/instances/1.14.3/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/User/Documents/Jogos/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/com/mojang/realms/1.14.17/realms-1.14.17.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/com/mojang/minecraft/1.14.3/minecraft-1.14.3-client.jar

Native libraries:
  C:/Users/User/Documents/Jogos/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/User/Documents/Jogos/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/Users/User/Documents/Jogos/MultiMC/instances/1.14.3/.minecraft --assetsDir C:/Users/User/Documents/Jogos/MultiMC/assets --assetIndex 1.14 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx2048m, -Duser.language=en]

ID do Processo do Minecraft: 6824

Using onesix launcher.

[22:44:56] [Client thread/INFO]: Setting user: Henrico326
[22:45:13] [Client thread/INFO]: LWJGL Version: 3.2.2 build 10
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 7/12/19 10:45 PM
Description: Initializing game

java.lang.IllegalStateException: GLFW error 65542: WGL: The driver does not appear to support OpenGL
	at cuh.b(SourceFile:195)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
	at cuh.<init>(SourceFile:86)
	at dld.a(SourceFile:36)
	at cvo.au(SourceFile:465)
	at cvo.b(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cuh.b(SourceFile:195)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
	at cuh.<init>(SourceFile:86)
	at dld.a(SourceFile:36)
	at cvo.au(SourceFile:465)

-- Initialization --
Details:
Stacktrace:
	at cvo.b(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.14.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 766902912 bytes (731 MB) / 1090519040 bytes (1040 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2048m
	Launched Version: MultiMC5
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\User\Documents\Jogos\MultiMC\instances\1.14.3\.minecraft\crash-reports\crash-2019-07-12_22.45.14-client.txt
Minecraft foi fechado com o código de saída -1.
Clipboard copy at: 12 Jul 2019 22:45:28 -0300

the error is in portuguese language Brazil
I'm from there

**Comment by QuImUfu** [comment]
try installing/updating your graphic drivers.

**Comment by Henrico326** [comment]
> tente instalar / atualizar seus drivers gráficos.
I updated but did not change anything

**Comment by QuImUfu** [comment]
Could you upload the [dxdiag log](https://github.com/MultiMC/MultiMC5/wiki/Using-DxDiag) then?

**Comment by madokaorimura** [comment]
>https://bugs.mojang.com/browse/MC-128302
Problem maybe come from your card, try update/reinstall it from the legit source
Also, can you tell the name of that Card? (VGA/GPU)

**Comment by Henrico326** [comment]
when i I have with the computer I post

> [Bugs Mojang postar](https://bugs.mojang.com/browse/MC-128302)
> Problema talvez venha de seu cartão, tente atualizar / reinstalá-lo a partir da fonte legítima 
> Além disso, você pode dizer o nome desse cartão? (VGA / GPU)

**Comment by Henrico326** [comment]
> Você poderia fazer o upload do [log](https://github.com/MultiMC/MultiMC5/wiki/Using-DxDiag) do [dxdiag](https://github.com/MultiMC/MultiMC5/wiki/Using-DxDiag) então?

this is already the log I should have updated the board day 7 I think

**Comment by Henrico326** [comment]
these are the specs of my pc
![specs do meu pc](https://user-images.githubusercontent.com/52724493/61226416-c2188d80-a6f8-11e9-85df-dbd2468adef7.png)

**Comment by Henrico326** [comment]
is in portugues Brazil

**Comment by peterix** [comment]
Please post a dxdiag log, not vanilla crash logs. They are entirely useless in this case.

* Press the `[Windows]+[R]` keys on your keyboard to bring up the Run command.
* In the `Run` command box, type in `dxdiag` and press `<Enter>`. The DirectX Diagnostic Tool pop-up window should appear.
* Click on `Save all Information.`
* Save the information to your Desktop, keep the file name as is.
* Attach the file here.

Here is an example of what the DirectX Diagnostic Tool will look like:

![dxdiag example](https://user-images.githubusercontent.com/203326/34328124-4489aa8e-e8d6-11e7-9984-0f5e8561564b.png)

**Comment by Henrico326** [comment]
here

[DxDiag.txt](https://github.com/MultiMC/MultiMC5/files/3392889/DxDiag.txt)


> Por favor, poste um log do dxdiag, não os registros de falhas da baunilha. Eles são totalmente inúteis neste caso.
> 
> * Pressione as `[Windows]+[R]`teclas do seu teclado para ativar o comando Executar.
> * Na `Run`caixa de comando, digite `dxdiag`e pressione `<Enter>`. A janela pop-up da Ferramenta de diagnóstico do DirectX deve aparecer.
> * Clique em `Save all Information.`
> * Salve as informações na sua área de trabalho, mantenha o nome do arquivo como está.
> * Anexe o arquivo aqui.
> 
> Aqui está um exemplo de como será a ferramenta de diagnóstico do DirectX:
> 
> ![exemplo de dxdiag](https://user-images.githubusercontent.com/203326/34328124-4489aa8e-e8d6-11e7-9984-0f5e8561564b.png)

**Comment by QuImUfu** [comment]
Ok, this seems to be another case of:  
https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs

**Comment by Henrico326** [comment]
> Ok, this seems to be another case of:
> https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs

nesse caso eu tenho que desinstalar o outro Java ? (1.8.0_211)

**Comment by madokaorimura** [comment]
I dont know, just try it.

**Comment by Henrico326** [comment]
it worked, **thanks everyone**

**Comment by Henrico326** [comment]
It worked, **thanks everyone**
