### ISSUE TITLE
Update failed 0.6.6

### ISSUE THREAD

**Issue by Plinz** [MultiMC/MultiMC5#2744]
System Information
-----------------------------
MultiMC version: 0.6.5

Operating System: Linux

Summary of the issue or suggestion:
----------------------------------------------
When I update Multimc to 0.6.6 version, I got this error : 

Update Failed!
The new version didn't start or is too old and doesn't respond to startup checks.
Roll back to previous version ?

What should happen:
------------------------------
No error and make the update

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Get version 0.6.5 on linux

2. Update button or at startup accept update

**Comment by QuImUfu** [comment]
had the same errori ignored it, pressed no and everything worked.  
And make sure you have installed the package mentioned in the [Release Notes](https://github.com/MultiMC/MultiMC5/blob/develop/changelog.md)

**Comment by Plinz** [comment]
It was missing the package qt5-default which cause the error.
When I ignored the error, multiMC wasn't able to launch (and didn't show any error).
I think the popup error should indicate the package to install or directly ask to install them for a better user experience.
