### ISSUE TITLE
Process exited with code 1

### ISSUE THREAD

**Issue by MisterR2** [MultiMC/MultiMC5#2745]
System Information
-----------------------------
MultiMC version: 0.6

Operating System: Windows 10

Summary of the issue or suggestion: 
----------------------------------------------
Instances won't launch

What should happen: 
------------------------------
When i launch an instance Minecraft should open. 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Start MultiMC

2. Create an instance

3. Launch it

Suspected cause:
---------------------------
I honestly don't know

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

MultiMC version: 0.6.

Minecraft folder is:
C:/Users/arthu/Desktop/Arquivos/MultiMC/instances/1.12.2/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_191, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/arthu/Desktop/Arquivos/MultiMC/instances/1.12.2/natives

Libraries:
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2838/forge-1.12.2-14.23.5.2838-universal.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/arthu/Desktop/Arquivos/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  Baubles-1.12-1.5.2
  Bewitchment-1.12.2-0.0.19.47-indev
  jei_1.12.2-4.15.0.268
  journeymap-1.12.2-5.5.4
  llibrary-1.7.19-1.12.2
  OptiFine_1.12.2_HD_U_E3
  Patchouli-1.0-20

Window size: 854 x 480

Minecraft process ID: 116

2019-07-13 09:34:17,868 main ERROR Error processing element Queue ([Appenders: null]): CLASS_NOT_FOUND
2019-07-13 09:34:18,006 main ERROR Unable to locate appender "ServerGuiConsole" for logger config "root"
[09:34:18] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[09:34:18] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[09:34:18] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
Exception in thread "main" java.lang.NoClassDefFoundError: com/mojang/authlib/exceptions/AuthenticationException
	at net.minecraftforge.fml.common.launcher.FMLTweaker.acceptOptions(FMLTweaker.java:123)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.mojang.authlib.exceptions.AuthenticationException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 3 more
Process exited with code 1.
Clipboard copy at: 13 Jul 2019 09:35:37 -0300

Additional Info:
---------------------------
It happens even with instances that don't have Forge installed. Also, i was playing the instance normally yesterday, so i don't know what happened.

**Comment by loleq2105** [comment]
i have the same issue god dang it

**Comment by S10MC2015** [comment]
Maybe your antivirus is blocking Minecraft or MMC. Or you are using a cracked version of MMC which you shouldn't.
You can also reinstall multimc from https://multimc.org/#Download

**Comment by peterix** [comment]
Same as:
#2761
#2755
