### ISSUE TITLE
Annoying Error

### ISSUE THREAD

**Issue by AnimalLover567** [MultiMC/MultiMC5#2746]
System Information
-----------------------------
MultiMC version:
0.6.5

Operating System:
Windows Server 2019

Summary of the issue or suggestion:
----------------------------------------------
The issue i'm having is [here](https://pastebin.com/fWtPzUef), the launcher won't even launch as outlined in the error, it stops with java.lang.ClassNotFoundException: net.minecraftforge.fml.common.launcher.FMLTweaker if it's not you launcher i'm sorry but i'm at my wits end with this, if this isn't the launcher but rather something else could somebody point me in the right direction

What should happen:
------------------------------
Launcher Should go through the steps needed to launch

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Open Launcher

2.Click Launch

3.See error

Suspected cause:
---------------------------
not sure know nothing about error

Logs/Screenshots:
----------------------------
https://pastebin.com/fWtPzUef

Additional Info:
---------------------------

**Comment by peterix** [comment]
Make sure you are launching online and letting the instance update.

**Comment by AnimalLover567** [comment]
Tried that and it immediately stops with the above error

**Comment by AnimalLover567** [comment]
Can anybody help me with this or am i outta luck

**Comment by AnimalLover567** [comment]
I no longer need help with this as the original launcher i wanted to use started to work again, but you should really check out that problem incase somebody else runs into it.
