### ISSUE TITLE
MultiMC Version Window Buttons are wonky

### ISSUE THREAD

**Issue by LO6AN** [MultiMC/MultiMC5#2748]
System Information
-----------------------------
MultiMC version: Version 6.6.6-develop-1343 on win32

Operating System: Windows 10 1903

Summary of the issue or suggestion:
----------------------------------------------
The buttons in the version window have had their borders removed. https://i.imgur.com/dexQf2b.png

What should happen:
------------------------------
They should be standard buttons, or there should be something to differentiate the buttons from the text at the top that tells you what the buttons are. Overall, the interface looks uglier because of the change.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Installing the latest build of MultiMC

2. The issue just pops up

Suspected cause:
---------------------------
I believe something in commit GH-358 https://github.com/MultiMC/MultiMC5/commit/e4273d6a174ffb771728f32b5e2a8a36096c4e21 caused this graphical interface issue.

Logs/Screenshots:
----------------------------
New Version Window "Buttons" Issue: https://i.imgur.com/dexQf2b.png
Old Version Window Buttons: https://i.imgur.com/WPfbkfU.png

Additional Info:
---------------------------
The issue does not only happen in the "System" interface for colors. The same thing is also seen in the Dark and Light themes.
The issue is not specific to my version of Windows, as I was able to reproduce it by doing the same thing to Windows XP https://i.imgur.com/lcVRfmb.png

**Comment by kb-1000** [comment]
This is expected. It now uses the same component as MultiMC's main menu on the right side to save space, otherwise the instance window might be too hhigh for your screen.

**Comment by LO6AN** [comment]
Well that is the reason why I didn't specifically say that the solution was to return it back to how it was before. What I requested in my report was for some sort of differentiation between the buttons and the labels to be added back in. Something as simple as a couple more spacers and some bold font in the interface could accomplish that.
