### ISSUE TITLE
MultiMC won't open at all

### ISSUE THREAD

**Issue by Pinwigato** [MultiMC/MultiMC5#2749]
System Information
-----------------------------
**MultiMC version:** Latest Stable (Downloaded yesterday)

**Operating System:** Ubuntu 19.04 (Budgie)

**Summary of the issue or suggestion:**  
----------------------------------------------
When I try to start MultiMC, the icon shows for a few seconds in the taskbar, and then dissapears. The program doesn't open at all. I don't get any error message, and I don't know where the error logs are located since there's no ./MultiMC folder in /home

**What should happen:**
------------------------------
MultiMC should open and let me use it

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Press the Windows button in the keyboard

2. Type "MultiMC" and click the MultiMC icon

3. Wait for it to show in the taskbar, and then it will close

Suspected cause:
---------------------------
I have been messing a bit with Java because the technic launcher didn't work with the latest version. May be the cause

Logs/Screenshots:
----------------------------
As I said before, it doesn't seem like there are any logs... And I don't think a screenshot would help either

Additional Info:
---------------------------
-

**Comment by peterix** [comment]
How did you install MultiMC?

**Comment by Pinwigato** [comment]
> How did you install MultiMC?

I downloaded the Ubuntu .deb package, and installed using the default software manager

**Comment by Pinwigato** [comment]
**UPDATE:** Found a log --> https://pastebin.com/6CCMXhux
