### ISSUE TITLE
Large Modpack collections take a long time to group

### ISSUE THREAD

**Issue by unknowntrojan** [MultiMC/MultiMC5#2751]
Hi,

I have a feature idea I came across while trying to sort my pretty large instance collection into groups. Unless I missed something, the only way to set an instance's group is to right-click (or left-click on the right panel while it's selected) click on "Change Group" and select a group from the list or make a new one. This was gruesome.

So since this is basically torture, a new system for grouping might be useful. Maybe a central group manager, maybe with a drag&drop interface so you can easily group your packs.

I think this is a little (maybe not the drag&drop group manager, but some improvements to grouping as a whole) QoL feature that goes a long way.

Thanks for reading through :)

**Comment by peterix** [comment]
In MultiMC4, we had drag&drop for moving instances between groups. That was never reimplemented during the Qt rewrite.

So, technically, this is a regression.
