### ISSUE TITLE
I have Idea

### ISSUE THREAD

**Issue by iEpicGamerSVK** [MultiMC/MultiMC5#2754]
System Information
-----------------------------
MultiMC version: 5

Operating System: Windows 10 Home (64-Bit) - Java: 8 (64-bit)

Summary of the issue or suggestion:
----------------------------------------------
Its fine have central folder for resoucepacks, shaders and server list than central mods in main folder of multimc

**Comment by iEpicGamerSVK** [comment]
And sorry for bad english, I am from Slovakia :D

**Comment by ThexXTURBOXx** [comment]
You can achieve that via [Symlinks](https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/) yourself

**Comment by peterix** [comment]
There is no other solution.
