### ISSUE TITLE
MultiMC wont start and an error message is displayed

### ISSUE THREAD

**Issue by MRFluffyNBS** [MultiMC/MultiMC5#2757]
System Information
-----------------------------
MultiMC version: 0.6.5
Operating System: ubuntu linux 14.04
Summary of the issue or suggestion:
----------------------------------------------
MultiMC won'tstart when I launch it. The only thing that it does is that it downloads the tar.gz file. When I manually execute the executable in the tar file by doing ./MultiMC, it displays an error message that says there is a symbol lookup error. I used to be able to run MultiMC fine with the 0.6.4 version but after it prompted me to update it with a newer version it didn't start. 

this is the error message:
./MultiMC: symbol lookup error: ./MultiMC: undefined symbol: _ZN7QString13toUtf8_helperERKS_

Additional Info:
---------------------------
If this isn't fixable, does anyone know where to download previous versions of MultiMC as the previous version worked fine for me

**Comment by peterix** [comment]
You can grab previous versions right here on github.

You may be able to get it working by updating the deb package: https://files.multimc.org/downloads/multimc_1.3-1.deb

However, you may have to update to a newer Ubuntu release:
https://itsfoss.com/ubuntu-14-04-end-of-life/

**Comment by MRFluffyNBS** [comment]
sorry, but could you say where on GitHub the previous versions are? I'm pretty new to github sorry. Also, I have already updated the deb package.

**Comment by peterix** [comment]
https://github.com/MultiMC/MultiMC5/releases

**Comment by MRFluffyNBS** [comment]
ok thanks

**Comment by peterix** [comment]
Anyway, only distros that have Qt5 >= 5.4.2 are going to be supported going forward.
