### ISSUE TITLE
Loader mods sorting by version not using SemVer or sorting by the version order

### ISSUE THREAD

**Issue by maruohon** [MultiMC/MultiMC5#2762]
System Information
-----------------------------
MultiMC version: 0.6.6-1341
Operating System: Win 10

Summary of the suggestion:
----------------------------------------------
The Loader Mods mod list sorting should consider the mod versions as following semver, when possible, and sort them according to the version number, instead of considering the version to be a string. As far as I can tell, currently the versions are sorted alphabetically/lexicographically whatever the correct term is. Also it seems that certain long version numbers get cut out, perhaps for being too long?

Screenshots:
----------------------------
Here is an example where 0.9.x and 0.10.x versions get sorted in an undesired order, and the longer date and timestamp based dev build versions get truncated completely. I believe these are still following the SemVer standard, although they are a bit unconventional for version numbers...
![multimc_mod_sorting](https://user-images.githubusercontent.com/2331050/61646237-8316a900-acb1-11e9-87ad-ed9d0e6459b4.png)

**Comment by peterix** [comment]
Sounds reasonable :)

**Comment by Siphalor** [comment]
Still doesn't work for me:

![image](https://cdn.imgpaste.net/2019/07/30/g5gn3.jpg)

Version: 0.6.6-develop-1361

**Comment by peterix** [comment]
Looks sorted to me.

**Comment by Siphalor** [comment]
Sorry, you’re right. I was just used that the mods were sorted oldest to newest before and totally messed up 🙂

**Comment by peterix** [comment]
Like, it's probably not semver, but it's at least trying now :)

**Comment by Siphalor** [comment]
Seems like I uploaded the wrong image. It's still bugged:

![image](https://cdn.imgpaste.net/2019/07/31/g9t37.jpg)

**Comment by peterix** [comment]
Alright. Added more improvements along with #2550. Should be pretty good now, except for the lack of caching and slow refreshes.
