### ISSUE TITLE
My Multimc instance is crashing

### ISSUE THREAD

**Issue by Lebi72** [MultiMC/MultiMC5#2763]
https://paste.ee/p/Y1QMG

**Comment by Lebi72** [comment]
This is the log

**Comment by Chew** [comment]
This appears to be a problem with your Minecraft instance, not with MultiMC itself.

**Comment by ah-callie** [comment]
> This appears to be a problem with your Minecraft instance, not with MultiMC itself.

How do you go about trying to fix that?

**Comment by S10MC2015** [comment]
ProjRed problem. Maybe try to use the "stable" version of Project Red for 1.7.10 like https://www.curseforge.com/minecraft/mc-mods/project-red-base/files/2240246 and find its modules.

**Comment by peterix** [comment]
Looks broken, and like the author just closed issues that mentioned this error. Idk. Try a different version of the mod.
