### ISSUE TITLE
Invalid credentials. Invalid username or password.

### ISSUE THREAD

**Issue by MomeGnome** [MultiMC/MultiMC5#2766]
System Information
MultiMC version: 0.6.6-1341

Operating System: 64bit Windows 8

Summary of the issue or suggestion:
----------------------------------------------
When I try to add an account, I get this error message - Invalid credentials. Invalid username or password.

Suspected cause:
No idea
---------------------------

**Comment by peterix** [comment]
Can't help you, the server side is at fault.
I work at Mojang and I can't help you.

You can extrapolate what state the server side is in from that. Sorry.
