### ISSUE TITLE
minecraft crashes

### ISSUE THREAD

**Issue by xag803** [MultiMC/MultiMC5#2767]
System Information
-----------------------------
MultiMC version:0.6.6-dev

Operating System: Windows 10

Summary of the issue or suggestion:crash
----------------------------------------------

What should happen: Minecraft should boot up
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.get the mods  in an instance and disable them 

2.make a new instance

3.put the mods in and run them

Suspected cause: mods
---------------------------

Logs/Screenshots: https://textuploader.com/11jax
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info
---------------------------

**Comment by S10MC2015** [comment]
Update GPU drivers/Download correct GPU drivers. 
https://help.mojang.com/customer/en/portal/articles/928791-problematic-frame-or-pixel-format-not-accelerated

**Comment by xag803** [comment]
> Update GPU drivers/Download correct GPU drivers.
> https://help.mojang.com/customer/en/portal/articles/928791-problematic-frame-or-pixel-format-not-accelerated

Thank you I will try this

**Comment by xag803** [comment]
> Update GPU drivers/Download correct GPU drivers.
> https://help.mojang.com/customer/en/portal/articles/928791-problematic-frame-or-pixel-format-not-accelerated

i did this and i got this




https://textuploader.com/11j6d

**Comment by S10MC2015** [comment]
I don't really know what the problem is but can you check again if you are running latest drivers. Download center doesn't have win 10 drivers for your CPU/IGPU but does have win 8 ones.

**Comment by xag803** [comment]
> I don't really know what the problem is but can you check again if you are running latest drivers. Download center doesn't have win 10 drivers for your CPU/IGPU but does have win 8 ones.

Ok

**Comment by peterix** [comment]
Assuming fixed...
