### ISSUE TITLE
Is there any way to put forge into MultiMC for 1.14.2?

### ISSUE THREAD

**Issue by JustHmm** [MultiMC/MultiMC5#2768]
Hi, I'm currently playing [High Noon 5.0.3](https://www.curseforge.com/minecraft/modpacks/high-noon/files) modpack and MultiMC is my only option, Twitch launcher is not working properly and they're not even respond help requests, they marking it as "solved" . Every page on twitch launcher (even settings tabs) loading after 4-5 minutes.  Anyway i already deleted that, the real problem is i can't use forge for 1.14.2, when i drag 5.0.3 zip file on to MultiMC somehow its opening as a 1.12.2 modpack. with forge 14.23.5.2838 and LWJGL 2.9.4 nightly
Is there any way to manually add forge? like installing it somewhere than dragging files into instance folder or something like that?

Summary: Twitch Launcher not working, i want to try 1.14.2 and newer modpacks but i cant put forge into MultiMC.

**Comment by tehbasshunter** [comment]
I've got a feeling they accidentally marked it as 1.14.2 while it's actually 1.12.2.....

**Comment by JustHmm** [comment]
Thank you. I tried some newer 1.14.x modpacks and High Noon was the only one works. Thats normal than.
