### ISSUE TITLE
Maximized window size checkbox not operational

### ISSUE THREAD

**Issue by aeroeng15** [MultiMC/MultiMC5#2770]
System Information
-----------------------------
MultiMC version: 0.6.6-develop-1359

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Checking the "Start Minecraft maximized?" box does not result in maximized Minecraft.

What should happen:
------------------------------
Minecraft starts maximized regardless of custom window dimensions.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC Settings

2. Navigate to Minecraft tab

3. Select "Start Minecraft maximized?" checkbox

4. Minecraft starts at default size

Suspected cause:
---------------------------
Related to [#394](https://github.com/MultiMC/MultiMC5/issues/394)

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
If this is not planned to be fixed (per #394), this option should be removed/disabled.

**Comment by peterix** [comment]
It works with versions of the game that allow it to work. That is, up to 1.5.2.
