### ISSUE TITLE
Steam unable to draw overlay onto instance on Windows

### ISSUE THREAD

**Issue by Arudarin** [MultiMC/MultiMC5#2771]
System Information
-----------------------------
MultiMC version: 0.6.6-1341

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------

When I try to enable the Steam Overlay, the mouse cursor disappears and black bars are drawn. If I try clicking somewhere where there would be a button, I hear a noise indicating that it has been pressed.

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

I conclude that for some reason, [Steam is not drawing it's overlay over MultiMC correctly](https://streamable.com/294z0), whereas it does on the Vanilla Minecraft launcher.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

These are my settings in steam, selecting the MultiMC.exe and passing the command line arguments '-l "1.14.4"'.

https://i.imgur.com/gO5coK4.png
https://i.imgur.com/gU7SlVN.png

Additional Info:
---------------------------

**Comment by peterix** [comment]
Steam breaking their overlay is not my problem. Talk to Valve.
