### ISSUE TITLE
Minecraft crashing before the .exe opens

### ISSUE THREAD

**Issue by lamoyrl90** [MultiMC/MultiMC5#2773]
System Properties:

Processor: Intel(R) Xeon(R) CPU W3530 @ 2.80GHz
Installed memory (RAM): 12.0 GB
System type: 64-bit Windows 10

Pastebin to MultiMC log: https://paste.ee/p/NeM3R

Anyway, to the issue:
I've been getting this error since last night. I played with my java paths a couple times because I had to use AdoptOpenJDK for JDK 8 to decompile the Forge files for Eclipse. The first time I did it, I had no issue after switching back to JDK 12. However, since I did this a second time last night, I have been getting this issue. I uninstalled and reinstalled Java but it did not resolve the issue. I only start getting this error after I install Forge, tested it to make sure it wasn't my mods and it only happens with Forge installed. I tried downgrading my Forge version to no avail. I also had been procrastinating on the update to MultiMC, so I tried updating it to see if it would help. Nope.

Java is installed at 
C:\Program Files\Java\jdk-12.0.2
and
C:\Program Files\Java\jre1.8.0_221

JAVA_HOME is 
C:\Program Files\Java\jre1.8.0_221

Java path is
C:\Program Files\Java\jre1.8.0_221\bin

AdoptOpenJDK is located at
C:\Program Files\AdoptOpenJDK\jdk-8.0.222.10-hotspot

AdoptOpenJDK has no system path associated to it, I removed it in an attempt to fix this issue, again to no avail

My Eclipse version of Minecraft runs fine in Eclipse

Hopefully there's enough information for you to help me. I'll provide more if you need me to.

**Comment by peterix** [comment]
Switch order of liteloader and forge and try again.

**Comment by lamoyrl90** [comment]
Wow, such a simple thing cause that.

If the order matters, and those two are expected to be present, maybe in the future run a check to see if they're present and if they're not in the correct order force them to load in the correct order?

Anyway thanks, and I'm closing this. Keep up the good work!

**Comment by peterix** [comment]
It worked before.

The problem is that either forge or liteloader stopped treating the command line arguments correctly. Launchwrapper makes that a mistake too easy to make.
