### ISSUE TITLE
MCLeaks support

### ISSUE THREAD

**Issue by TheTank18** [MultiMC/MultiMC5#2774]
System Information
-----------------------------
MultiMC version: 0.6.6-develop-1361 on win32

Operating System: Windows 10 (64-bit)

Summary of the issue or suggestion: Addition of MCLeaks accounts
----------------------------------------------

What should happen:
------------------------------
On the Accounts tab of the Settings menu, there should be a MCLeaks option to insert your MCLeaks account.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Go to your profile picture.

2. Click "Manage Accounts".

Suspected cause:
---------------------------
Feature Request; No suspected cause.

Logs/Screenshots:
----------------------------
(https://user-images.githubusercontent.com/42577873/62170453-6bff3900-b2f9-11e9-9a3d-1b536e0b77cd.PNG)

Additional Info:
---------------------------
Feature Request

I do not support piracy in any way.

**Comment by peterix** [comment]
No. Never.
