### ISSUE TITLE
closed while loading

### ISSUE THREAD

**Issue by joekyu** [MultiMC/MultiMC5#2778]
System Information
-----------------------------
MultiMC version: 0.6.6-1341

Operating System: windows 10

Summary of the issue or suggestion:
----------------------------------------------
I downloaded optifine and did all the stuff necessary  to get it to work but when i open it it loads to about half way and then closes.

What should happen:
------------------------------
It should fully load and then open.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.make new instance 

2. goto version add empty and edit it

3. drop in the optifine file and open game

Suspected cause:
---------------------------
Maybe im missing something im not sure.

Logs/Screenshots:
----------------------------
https://paste.ee/p/VSk2m logs
https://gyazo.com/2aa453fb46528084118e65a69e5d403b json file

Additional Info:
---------------------------

**Comment by peterix** [comment]
Run the optifine jar, let it extract the actual jar, then add that into the Minecraft jar (there's a button for that on the Version page).

**Comment by joekyu** [comment]
that worked ty!
