### ISSUE TITLE
Resolution issues with dual monitors, instance edit window locked to main monitor resolution

### ISSUE THREAD

**Issue by Frontear** [MultiMC/MultiMC5#2779]
System Information
-----------------------------
MultiMC version: 0.6.6

Operating System: Manjaro

Summary of the issue or suggestion:
----------------------------------------------
The bottom part of the edit instance window, where the 'play', 'close' and others are all located, is below the monitor display. As a result, it is not possible to click. This only occurs on a non-primary display.

What should happen:
------------------------------
The 'edit instance' window buttons should line up with the bottom of my monitor

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Select an instance (or create a new one)

2. Open the edit instance menu on a secondary monitor (must not be the main display)

3. Bottom border will be below the monitor display

Suspected cause:
---------------------------
n/a

Logs/Screenshots:
----------------------------
https://streamable.com/m1ht0

Additional Info:
---------------------------
This became an issue after 0.6.4, before such this issue did not occur.

**Comment by peterix** [comment]
Try the dev builds.

**Comment by Frontear** [comment]
On a note, I think this issue is being caused by MultiMC choosing to use only the primary monitor resolution. As a result, it's not fitting in my second monitor (they are different resolutions). I suspect that may be the cause, but I'm not fully certain

**Comment by Heufneutje** [comment]
Did you try what @peterix suggested though. You didn't really make that clear.

**Comment by Frontear** [comment]
@Heufneutje apologies, the issue is definitely not present with the current latest git build.

**Comment by peterix** [comment]
Yeah, but the issue is more with display scaling misbehaving on linux.

Does setting the env variable `QT_AUTO_SCREEN_SCALE_FACTOR=1` help with the issue?

**Comment by Frontear** [comment]
@peterix sorry for being so late, but now I can no longer reproduce the issue. Using 0.6.7 from https://aur.archlinux.org/packages/multimc5, scaling issue seems to have been fixed. Not sure if that's intentional

**Comment by peterix** [comment]
I fully depend on Qt doing the right thing, and I guess it does the right thing now?
Nice :)
