### ISSUE TITLE
Instance update failed because: Game update failed: it was impossible to fetch the required libraries. Reason:

### ISSUE THREAD

**Issue by luqity** [MultiMC/MultiMC5#2780]
System Information:
-----------------------------
Windows 10 ver 1803
1 TB of Storage
8GB of RAM

MultiMC version:
-----------------------------
0.6.6-1341

Operating System:
-----------------------------
Windows 10 ver 1803
Summary of the issue or suggestion:
I created an instance of 1.12.2, installed, forge, pressed "Launch" and the console comes up with

Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance 1.12.2' failed to process:
http://files.minecraftforge.net/maven/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar.pack.xz
http://files.minecraftforge.net/maven/com/typesafe/config/1.2.1/config-1.2.1.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar.pack.xz
http://files.minecraftforge.net/maven/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar.pack.xz

What should happen:
------------------------------
Create instance, install forge, click launch, start minecraft

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a new instance (1.12.2)

2. Install the latest version of Forge

3. Click Launch

4. Console gives error

Suspected cause:
---------------------------
It may have been the regular launcher cause when I tried to launch it over there it was stuck on "Preparing", I had no idea how to fix that

Logs/Screenshots:
----------------------------

Additional Info:
---------------------------

Minecraft folder is:
C:/Users/Desktop/MultiMC/instances/1.12.2/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_211, using 64-bit architecture.

**Comment by peterix** [comment]
That sounds like a network problem, not a software problem.
Make sure the network you are using isn't blocking minecraft-related servers and services.

**Comment by clandorf** [comment]
Having the same issue. home network, able to access download other websites. Using the latest multi-mc, trying to run with RLcraft and Vivecraft

**Comment by seanawesome** [comment]
Having the same issue

**Comment by seanawesome** [comment]
Nevermind, it's only blocking "https://libraries.minecraft.net/com/mojang/minecraft/1.15.2-Impact_4.9.1/minecraft-1.15.2-Impact_4.9.1-client.jar"

**Comment by kb-1000** [comment]
This is not the support for Impact. This issue is closed.
And @seanawesome you're necromancing old threads.

**Comment by VanilloMC** [comment]
im having the same issue how do i fix it i really wanna play alpha 1.1.0

**Comment by thesentrygamer** [comment]
`MultiMC version: 0.7.0-3775


Launched instance in online mode

authserver.mojang.com resolves to:
    [18.154.101.93, 18.154.101.19, 18.154.101.51, 18.154.101.47]

session.minecraft.net resolves to:
    [2620:1ec:bdf::71, 2620:1ec:46::71, 13.107.213.71, 13.107.246.71]

textures.minecraft.net resolves to:
    [2620:1ec:bdf::71, 2620:1ec:46::71, 13.107.213.71, 13.107.246.71]

api.mojang.com resolves to:
    [2620:1ec:46::71, 2620:1ec:bdf::71, 13.107.246.71, 13.107.213.71]


Minecraft folder is:
E:/MultiMC/instances/RobinFilms SMP/.minecraft


Java path is:
C:/Program Files/Eclipse Adoptium/jdk-18.0.2.101-hotspot/bin/javaw.exe


Checking Java version...
Java is version 18.0.2.1, using 64-bit architecture, from Eclipse Adoptium.


Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance RobinFilms SMP' failed to process:
https://maven.minecraftforge.net/net/minecraftforge/fmlcore/1.20.1-47.0.14/fmlcore-1.20.1-47.0.14.jar
https://maven.minecraftforge.net/net/minecraftforge/fmlearlydisplay/1.20.1-47.0.14/fmlearlydisplay-1.20.1-47.0.14.jar
https://maven.minecraftforge.net/net/minecraftforge/fmlearlydisplay/1.20.1-47.0.14/fmlearlydisplay-1.20.1-47.0.14.jar
https://maven.minecraftforge.net/net/minecraftforge/fmlloader/1.20.1-47.0.14/fmlloader-1.20.1-47.0.14.jar
https://maven.minecraftforge.net/net/minecraftforge/fmlloader/1.20.1-47.0.14/fmlloader-1.20.1-47.0.14.jar
https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.1-47.0.14/forge-1.20.1-47.0.14-installer.jar
https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.1-47.0.14/forge-1.20.1-47.0.14-universal.jar
https://maven.minecraftforge.net/net/minecraftforge/javafmllanguage/1.20.1-47.0.14/javafmllanguage-1.20.1-47.0.14.jar
https://maven.minecraftforge.net/net/minecraftforge/lowcodelanguage/1.20.1-47.0.14/lowcodelanguage-1.20.1-47.0.14.jar
https://maven.minecraftforge.net/net/minecraftforge/mclanguage/1.20.1-47.0.14/mclanguage-1.20.1-47.0.14.jar


`



This is not a network issue as I was able to manually download the files from the listed links.

**Comment by AverageComet250** [comment]
Don't think that's a MultiMc issue... also you're necroing this thread _again_. Either open a new issue on the correct bug tracker or open a new issue on this tracker with more info.

**Comment by bekosun** [comment]
that was so useless...
its a software problem
I've disabled firewall
 I give the software all the necessary permission and still nothing.. I can manually download libraries but the software  can't
 I tried all the workarounds  that I can found and nothing works..

**Comment by phit** [comment]
post your multimc-0.log from the launcher folder, that should give you the reason

**Comment by novosta** [comment]
I'm having this issue, still can download it using chrome

```
 37184.958 C | [launcher.task.net.download]: "{2950bb07-4206-4771-88b2-bf50d702c503}" Failed "https://maven.fabricmc.net/org/ow2/asm/asm-util/9.7.1/asm-util-9.7.1.jar" with reason QNetworkReply::SslHandshakeFailedError
 37184.958 C | [launcher.task.net.download]: "{2950bb07-4206-4771-88b2-bf50d702c503}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37184.958 C | [launcher.task.net.download]: "{28fa493e-855d-43e0-ba6b-204cab85ef09}" Failed "https://maven.fabricmc.net/org/ow2/asm/asm-tree/9.7.1/asm-tree-9.7.1.jar" with reason QNetworkReply::SslHandshakeFailedError
 37184.958 C | [launcher.task.net.download]: "{28fa493e-855d-43e0-ba6b-204cab85ef09}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37184.958 C | [launcher.task.net.download]: "{3a6c248d-3cf6-42c1-a5a5-cb4ad647b807}" Failed "https://maven.fabricmc.net/org/ow2/asm/asm-commons/9.7.1/asm-commons-9.7.1.jar" with reason QNetworkReply::SslHandshakeFailedError
 37184.958 C | [launcher.task.net.download]: "{3a6c248d-3cf6-42c1-a5a5-cb4ad647b807}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37184.959 C | [launcher.task.net.download]: "{fff34c71-0dcf-4ec1-aa1e-a779e89a6768}" Failed "https://maven.fabricmc.net/org/ow2/asm/asm-analysis/9.7.1/asm-analysis-9.7.1.jar" with reason QNetworkReply::SslHandshakeFailedError
 37184.959 C | [launcher.task.net.download]: "{fff34c71-0dcf-4ec1-aa1e-a779e89a6768}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37184.959 C | [launcher.task.net.download]: "{8c8b5682-40f7-40f2-bba7-0a5b90b3e9c5}" Failed "https://maven.fabricmc.net/org/ow2/asm/asm/9.7.1/asm-9.7.1.jar" with reason QNetworkReply::SslHandshakeFailedError
 37184.959 C | [launcher.task.net.download]: "{8c8b5682-40f7-40f2-bba7-0a5b90b3e9c5}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37184.959 C | [launcher.task.net.download]: "{aed0f619-cc35-4422-9fc3-f0347067b56b}" Failed "https://maven.fabricmc.net/net/fabricmc/intermediary/1.21.1/intermediary-1.21.1.jar" with reason QNetworkReply::SslHandshakeFailedError
 37184.959 C | [launcher.task.net.download]: "{aed0f619-cc35-4422-9fc3-f0347067b56b}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37185.032 C | [launcher.task.net.download]: "{92318633-e28e-43e5-ab8e-b574f013d07c}" Failed "https://maven.fabricmc.net/net/fabricmc/fabric-loader/0.16.7/fabric-loader-0.16.7.jar" with reason QNetworkReply::SslHandshakeFailedError
 37185.032 C | [launcher.task.net.download]: "{92318633-e28e-43e5-ab8e-b574f013d07c}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37185.033 C | [launcher.task.net.download]: "{2ef8a20d-461b-464b-90b9-ddad32aa541a}" Failed "https://maven.fabricmc.net/net/fabricmc/sponge-mixin/0.15.3+mixin.0.8.7/sponge-mixin-0.15.3+mixin.0.8.7.jar" with reason QNetworkReply::SslHandshakeFailedError
 37185.033 C | [launcher.task.net.download]: "{2ef8a20d-461b-464b-90b9-ddad32aa541a}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37185.102 C | [launcher.task.net.download]: "{92318633-e28e-43e5-ab8e-b574f013d07c}" Failed "https://maven.fabricmc.net/net/fabricmc/fabric-loader/0.16.7/fabric-loader-0.16.7.jar" with reason QNetworkReply::SslHandshakeFailedError
 37185.102 C | [launcher.task.net.download]: "{92318633-e28e-43e5-ab8e-b574f013d07c}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37185.103 C | [launcher.task.net.download]: "{8c8b5682-40f7-40f2-bba7-0a5b90b3e9c5}" Failed "https://maven.fabricmc.net/org/ow2/asm/asm/9.7.1/asm-9.7.1.jar" with reason QNetworkReply::SslHandshakeFailedError
 37185.103 C | [launcher.task.net.download]: "{8c8b5682-40f7-40f2-bba7-0a5b90b3e9c5}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37185.175 C | [launcher.task.net.download]: "{aed0f619-cc35-4422-9fc3-f0347067b56b}" Failed "https://maven.fabricmc.net/net/fabricmc/intermediary/1.21.1/intermediary-1.21.1.jar" with reason QNetworkReply::SslHandshakeFailedError
 37185.175 C | [launcher.task.net.download]: "{aed0f619-cc35-4422-9fc3-f0347067b56b}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37185.176 C | [launcher.task.net.download]: "{2950bb07-4206-4771-88b2-bf50d702c503}" Failed "https://maven.fabricmc.net/org/ow2/asm/asm-util/9.7.1/asm-util-9.7.1.jar" with reason QNetworkReply::SslHandshakeFailedError
 37185.176 C | [launcher.task.net.download]: "{2950bb07-4206-4771-88b2-bf50d702c503}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37185.248 C | [launcher.task.net.download]: "{3a6c248d-3cf6-42c1-a5a5-cb4ad647b807}" Failed "https://maven.fabricmc.net/org/ow2/asm/asm-commons/9.7.1/asm-commons-9.7.1.jar" with reason QNetworkReply::SslHandshakeFailedError
 37185.248 C | [launcher.task.net.download]: "{3a6c248d-3cf6-42c1-a5a5-cb4ad647b807}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37185.248 C | [launcher.task.net.download]: "{28fa493e-855d-43e0-ba6b-204cab85ef09}" Failed "https://maven.fabricmc.net/org/ow2/asm/asm-tree/9.7.1/asm-tree-9.7.1.jar" with reason QNetworkReply::SslHandshakeFailedError
 37185.248 C | [launcher.task.net.download]: "{28fa493e-855d-43e0-ba6b-204cab85ef09}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37185.326 C | [launcher.task.net.download]: "{2ef8a20d-461b-464b-90b9-ddad32aa541a}" Failed "https://maven.fabricmc.net/net/fabricmc/sponge-mixin/0.15.3+mixin.0.8.7/sponge-mixin-0.15.3+mixin.0.8.7.jar" with reason QNetworkReply::SslHandshakeFailedError
 37185.326 C | [launcher.task.net.download]: "{2ef8a20d-461b-464b-90b9-ddad32aa541a}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37185.326 C | [launcher.task.net.download]: "{fff34c71-0dcf-4ec1-aa1e-a779e89a6768}" Failed "https://maven.fabricmc.net/org/ow2/asm/asm-analysis/9.7.1/asm-analysis-9.7.1.jar" with reason QNetworkReply::SslHandshakeFailedError
 37185.326 C | [launcher.task.net.download]: "{fff34c71-0dcf-4ec1-aa1e-a779e89a6768}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37185.406 C | [launcher.task.net.download]: "{92318633-e28e-43e5-ab8e-b574f013d07c}" Failed "https://maven.fabricmc.net/net/fabricmc/fabric-loader/0.16.7/fabric-loader-0.16.7.jar" with reason QNetworkReply::SslHandshakeFailedError
 37185.406 C | [launcher.task.net.download]: "{92318633-e28e-43e5-ab8e-b574f013d07c}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37185.407 C | [launcher.task.net.download]: "{8c8b5682-40f7-40f2-bba7-0a5b90b3e9c5}" Failed "https://maven.fabricmc.net/org/ow2/asm/asm/9.7.1/asm-9.7.1.jar" with reason QNetworkReply::SslHandshakeFailedError
 37185.407 C | [launcher.task.net.download]: "{8c8b5682-40f7-40f2-bba7-0a5b90b3e9c5}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37185.486 C | [launcher.task.net.download]: "{aed0f619-cc35-4422-9fc3-f0347067b56b}" Failed "https://maven.fabricmc.net/net/fabricmc/intermediary/1.21.1/intermediary-1.21.1.jar" with reason QNetworkReply::SslHandshakeFailedError
 37185.486 C | [launcher.task.net.download]: "{aed0f619-cc35-4422-9fc3-f0347067b56b}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37185.487 C | [launcher.task.net.download]: "{2950bb07-4206-4771-88b2-bf50d702c503}" Failed "https://maven.fabricmc.net/org/ow2/asm/asm-util/9.7.1/asm-util-9.7.1.jar" with reason QNetworkReply::SslHandshakeFailedError
 37185.487 C | [launcher.task.net.download]: "{2950bb07-4206-4771-88b2-bf50d702c503}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37185.552 C | [launcher.task.net.download]: "{3a6c248d-3cf6-42c1-a5a5-cb4ad647b807}" Failed "https://maven.fabricmc.net/org/ow2/asm/asm-commons/9.7.1/asm-commons-9.7.1.jar" with reason QNetworkReply::SslHandshakeFailedError
 37185.553 C | [launcher.task.net.download]: "{3a6c248d-3cf6-42c1-a5a5-cb4ad647b807}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37185.553 C | [launcher.task.net.download]: "{28fa493e-855d-43e0-ba6b-204cab85ef09}" Failed "https://maven.fabricmc.net/org/ow2/asm/asm-tree/9.7.1/asm-tree-9.7.1.jar" with reason QNetworkReply::SslHandshakeFailedError
 37185.553 C | [launcher.task.net.download]: "{28fa493e-855d-43e0-ba6b-204cab85ef09}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37185.689 C | [launcher.task.net.download]: "{2ef8a20d-461b-464b-90b9-ddad32aa541a}" Failed "https://maven.fabricmc.net/net/fabricmc/sponge-mixin/0.15.3+mixin.0.8.7/sponge-mixin-0.15.3+mixin.0.8.7.jar" with reason QNetworkReply::SslHandshakeFailedError
 37185.689 C | [launcher.task.net.download]: "{2ef8a20d-461b-464b-90b9-ddad32aa541a}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
 37185.689 C | [launcher.task.net.download]: "{fff34c71-0dcf-4ec1-aa1e-a779e89a6768}" Failed "https://maven.fabricmc.net/org/ow2/asm/asm-analysis/9.7.1/asm-analysis-9.7.1.jar" with reason QNetworkReply::SslHandshakeFailedError
 37185.690 C | [launcher.task.net.download]: "{fff34c71-0dcf-4ec1-aa1e-a779e89a6768}" HTTP Status 0 ;error "SSL handshake failed: Handshake failed: Unexpected or badly-formatted message received"
```

**Comment by phit** [comment]
that doesn't look like a multimc log, regardless something in your network or your pc is messing with the network connections
