### ISSUE TITLE
Unable to run MultiMc at all, as it says it is missing gui file even though the file is there

### ISSUE THREAD

**Issue by DragonAim0320** [MultiMC/MultiMC5#2781]
System Information
-----------------------------
MultiMC version: MultiMc 5

Operating System: Windows 8.1

Summary of the issue or suggestion:
----------------------------------------------
Does not allow program to run, stating the libMultiMc_gui.dll file is missing (when it isn't), and asks that the user reinstalls the program (which I have 5 or 6 times).

What should happen:
------------------------------
A pop-up stating the libMultiMc_gui.dll file is missing should appear. I can still access the zip and open the "missing" file. Inside the gui file, it says ".bss" is Uninitialized.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download MultiMc 5 onto Windows operating System.

2. Try to open MultiMc program.

3. See pop-up.

Suspected cause:
---------------------------
Inside the gui file, it says ".bss" is Uninitialized. I'm not sure if that has anything to do with it or if that is normal, but it is my best bet. Unfortunately, I'm not a coder.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![image](https://user-images.githubusercontent.com/53590101/62403355-8f74ee80-b55a-11e9-81c2-cbf4fe6f738b.png)
![image](https://user-images.githubusercontent.com/53590101/62403415-eed2fe80-b55a-11e9-844f-dbd6c7fa9b94.png)
![image](https://user-images.githubusercontent.com/53590101/62403424-feeade00-b55a-11e9-9fc4-3f90f2fa39fc.png)

Additional Info:
---------------------------

**Comment by tehbasshunter** [comment]
You need to extract all the files for it to work. You can't run the exe alone for it to work.
