### ISSUE TITLE
[Feature Request] Submit to Ubuntu for official package manager installation

### ISSUE THREAD

**Issue by PeashyScript** [MultiMC/MultiMC5#2783]
Right now what you have works, but I thought it would be cool if you hosted MultiMC on Ubuntu's official repos, plus it would save bandwidth. You already build deb packages, so I don't think it would be too hard.
https://wiki.ubuntu.com/UbuntuDevelopment/NewPackages

**Comment by peterix** [comment]
I'd say probably not.

MultiMC depends on numerous remote services to function. They can change at any time, which requires quick updates. Packaging things in the traditional linux way works, but only in rolling release distros. Something that locks down versions of software wouldn't work.

The deb package we have is basically an empty shell that downloads the rest and sets it up in `~/.local/multimc/` for you.

Having our own deb/rpm/whatever repositories and giving people packages that add those to their system would be a solution.

**Comment by PeashyScript** [comment]
@peterix I agree with this solution, maybe you could use a PPA instead.

**Comment by peterix** [comment]
Alright. I put this on the idea pile.
https://app.mindmup.com/map/_free/2020/01/7870d53031df11eaba96015fb85b0b73
