### ISSUE TITLE
Crashes while trying to add mods (via Add button)

### ISSUE THREAD

**Issue by Project579** [MultiMC/MultiMC5#2785]
System Information
-----------------------------
MultiMC version: 0.6.7-develop-1370

Operating System: Windows 7 SP1 x64

Summary of the issue or suggestion:
MultiMC crashes after the latest develop update if the Add button in Loader Mods is used (latest updated made significant changes to the mod windows improving performance drastically, I expected some bugs from it).

What should happen:
Mod should be added

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Edit any instance in MultiMC

2. Select the Loader Mods Tab

3. Click the Add button, select a file and click Open.

Suspected cause:
Commit: a3ffa3d6659e00e0762017cf64911db0183a250c

Logs/Screenshots:
----------------------------
https://gist.github.com/Project579/639a7eda4a133931af6fe6186c35bdb7

**Comment by peterix** [comment]
Fix incoming :)
