### ISSUE TITLE
ubuntu: can't update 0.6.5->0.6.7

### ISSUE THREAD

**Issue by Spongman** [MultiMC/MultiMC5#2786]
System Information
-----------------------------
MultiMC version: 0.6.5

Operating System: ubuntu 18.04

Summary of the issue or suggestion:
----------------------------------------------

after choosing 'update' in the 0.6.5 update dialog, it shows the following:

![image](https://user-images.githubusercontent.com/1088194/62440346-8e7fc080-b704-11e9-963a-659c4f82538f.png)

Suspected cause:
---------------------------

````
   21.338 D Task "NetJob(Update Files)" succeeded
   21.338 D Task "GoUpdate::DownloadTask(0x7ffef1312d40)" succeeded
   21.338 D Installing updates.
   21.594 W Couldn't find the "live.check" file!
   21.845 W Couldn't find the "live.check" file!
   22.095 W Couldn't find the "live.check" file!
   22.346 W Couldn't find the "live.check" file!
   22.596 W Couldn't find the "live.check" file!
   22.846 W Couldn't find the "live.check" file!
   23.097 W Couldn't find the "live.check" file!
   23.347 W Couldn't find the "live.check" file!
   23.598 W Couldn't find the "live.check" file!
   23.848 W Couldn't find the "live.check" file!
   23.849 W Update failed!
````

**Comment by Spongman** [comment]
not sure if it's related, but now i can't launch new instances:

````
Instance update failed because: Component metadata update task failed while downloading from remote server:
Job 'Download of meta file net.minecraft/1.8.9.json' failed to process:
https://v1.meta.multimc.org/net.minecraft/1.8.9.json
````

**Comment by Spongman** [comment]
so, i chose to install the new version regardless, and now it won't start at all :(

if i run it on the command-line, i get this:
````
MultiMC Dir: /home/user/.local/share/multimc
No missing dependencies found.
/home/user/.local/share/multimc/bin/MultiMC: error while loading shared libraries: libQt5Xml.so.5: cannot open shared object file: No such file or directory
````

**Comment by Heufneutje** [comment]
I actually got this message on Windows as well, but the update succeeded anyway for me.

**Comment by Heufneutje** [comment]
Though your problem of not being able to start anymore seems to be a different problem. You appear to missing the correct Qt libraries. Try running the command below:

`sudo apt-get install qt5-default`

**Comment by peterix** [comment]
Read the changelog for the versions you are installing:
https://github.com/MultiMC/MultiMC5/blob/develop/changelog.md

There's also a news thing for this:
https://multimc.org/posts/0-6-7-metadata-changes.html

1. You now need the system Qt libraries to be installed. If you update the deb package, you should get them
2. I shut down old metadata service. It was basically costing me extra $30 to have `v1.meta.multimc.org` instead of `meta.multimc.org/v1/`.

**Comment by eee12official** [comment]
> not sure if it's related, but now i can't launch new instances:
> 
> ```
> Instance update failed because: Component metadata update task failed while downloading from remote server:
> Job 'Download of meta file net.minecraft/1.8.9.json' failed to process:
> https://v1.meta.multimc.org/net.minecraft/1.8.9.json
> ```

I have the same problem... please help thanks

**Comment by Heufneutje** [comment]
You need to update. Simple as that.
