### ISSUE TITLE
"Download all" button in instance Version settings does not download

### ISSUE THREAD

**Issue by Fixer-007** [MultiMC/MultiMC5#2787]
System Information
-----------------------------
MultiMC version: 0.6.7

Operating System: Win 7

Summary of the issue or suggestion:
----------------------------------------------
"Download all" button in instance's Version settings does not download anything unlike in previous versions.

What should happen:
------------------------------
It should download all files needed to run the game

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Totally clean and fresh Multimc

2. Create an instance, go to settings -> version

3. Press "Download All"

4. Observe no download popup or anything

Suspected cause:
---------------------------
Recent update? It worked in 0.6.5 just fine

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://pastebin.com/raw/SLSZMQjw

Additional Info:
---------------------------

**Comment by QuImUfu** [comment]
It downloads only what is necessary (i.e. not already downloaded).  
If play offline works after clicking that button, everything works as it should. If it does not, that would AFAIK be a bug.

**Comment by Fixer-007** [comment]
> It downloads only what is necessary (i.e. not already downloaded).
> If play offline works after clicking that button, everything works as it should. If it does not, that would AFAIK be a bug.

No, it does not work on freshly installed multimc, nothing is downloading, offline button start will not work because of missing files. Download all worked in 0.6.5 just fine.

**Comment by QuImUfu** [comment]
Can confirm this bug after testing.

**Comment by QuImUfu** [comment]
i think this may be caused by using [on_actionDownload_triggered](https://github.com/MultiMC/MultiMC5/blob/a3ffa3d6659e00e0762017cf64911db0183a250c/application/pages/instance/VersionPage.cpp#L382),  
While the action is named [actionDownload_All](https://github.com/MultiMC/MultiMC5/blob/a0e45c5d1d55413e6b12334991ec41c6d9509bca/application/pages/instance/VersionPage.ui#L221).  
I could be completely wrong as I have not much knowledge about qt and c++ at all. :D

**Comment by Fixer-007** [comment]
Solved my issue, thank you!
