### ISSUE TITLE
Mc is white when i maximise

### ISSUE THREAD

**Issue by jesooswastaken** [MultiMC/MultiMC5#2789]
System Information
-----------------------------
MultiMC version:5

Operating System: idk

Summary of the issue or suggestion: Mc is white when i maximise
----------------------------------------------

What should happen: Launching the game then clicking the maximise button and it working
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create an instance of forge 1.8.9

2. Launch It

3. Press The Maximise Button on The Top Bar Of The Application

Suspected cause: I have no idea of why its happening
---------------------------

Logs/Screenshots: 

![image](https://user-images.githubusercontent.com/53817244/62529360-6b552e00-b836-11e9-9150-342502810003.png)

![image](https://user-images.githubusercontent.com/53817244/62529404-7b6d0d80-b836-11e9-81c8-22b334656384.png)

**Comment by peterix** [comment]
This has nothing to do with MultiMC.
