### ISSUE TITLE
AUR package out of date

### ISSUE THREAD

**Issue by CmdrNorthpaw** [MultiMC/MultiMC5#2790]
System Information
-----------------------------
MultiMC version: 0.6.6

Operating System: Manjaro Linux

Summary of the issue or suggestion: 
----------------------------------------------
The AUR package of MultiMC is still on 0.6.6

What should happen: 
------------------------------
I should have version 0.6.7 of MultiMC (I installed on Monday). My Mac has already received the update and it is showing up in the news feed. This is fairly urgent as my screen is quite miniscule and I can't close the Edit Instance window because of the UI bugs fixed in 0.6.4

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install MultiMC from the AUR package

2. Open About MultiMC

3. Observe v0.6.6 staring back at you

Suspected cause: 
---------------------------
Neglect of AUR by the devs (no offence).

Logs/Screenshots: 
----------------------------
https://i.imgur.com/eQlhydO.png
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
I don't control that AUR package.

**Comment by CmdrNorthpaw** [comment]
Oh really?

**Comment by peterix** [comment]
Yes.

`multimc-git` should be fine.

**Comment by Chronophylos** [comment]
This should be closed. Report out of date packages on the AUR: https://aur.archlinux.org/packages/multimc5. This has already been done.

**Comment by peterix** [comment]
Well, maybe I should go and ask the current maintainer to hand it over, and then automate the updating of both somehow.

**Comment by peterix** [comment]
Eh, maybe one day.
