### ISSUE TITLE
Feature Request: Create Instance from pre-existing folder

### ISSUE THREAD

**Issue by TrueCP6** [MultiMC/MultiMC5#2791]
Being able to create an instance from a custom modpack already installed would be a neat feature.

**Comment by tehbasshunter** [comment]
You already can. Right click the instance that you wanna dupe and choose copy instance.

**Comment by TrueCP6** [comment]
I meant from a modpack installed from something other than MultiMC. For example a Twitch modpack.

**Comment by QuImUfu** [comment]
you can import Twitch/Curse modpacks.

**Comment by TrueCP6** [comment]
I know you can but what if I put together my own modpack from jar files before installing MultiMC. There should be a way to easily import an instance pre-existing on your system by choosing a file when adding a new instance. There is a way to do it now but you have to do it jankily manually.

**Comment by peterix** [comment]
It's called copypasting the files into an instance and it's trivial.

**Comment by TrueCP6** [comment]
It's more complicated than it needs to be. Plus if it's simple it will be an easy addition.

**Comment by tehbasshunter** [comment]
The problem is MultiMC doesn't understand how other launchers handle their "instances/profiles". All it understands is the structure that it has internally for its instances.

**Comment by peterix** [comment]
s/problem/solution/
I have no intention of looking at that as a problem to solve.
