### ISSUE TITLE
Crash on edit instance, launch game, edit notes, etc.   MultiMC: Fatal IO error 0 (Success) on X server :0

### ISSUE THREAD

**Issue by md5i** [MultiMC/MultiMC5#2792]
System Information
-----------------------------
MultiMC version: 0.6.7-1290

Operating System: Linux maru2 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux

Summary of the issue or suggestion:
----------------------------------------------
After upgrading to this version, most actions in the menu on the right (whether selected from that menu or done from the context menu) cause MultiMC to crash.  It crashes with one of the following errors:

    MultiMC: Fatal IO error 0 (Success) on X server :0.
    MultiMC: Fatal IO error 2 (No such file or directory) on X server :0.

What should happen:
------------------------------
MultiMC should not crash.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Click Edit instance or Launch or Edit Notes or View Worlds or Manage Screenshots.

2. MultiMC crashes

Logs/Screenshots:
----------------------------
https://pastebin.com/a2iHYktM

In my syslog, I get, after this:

    MultiMC[29370]: MultiMC: Fatal IO error 0 (Success) on X server :0.

**Comment by md5i** [comment]
Moving away my instances folder, re-installing MultiMC, and then putting the instances folder back seems to have solved the problem.  I did get one crash:

**Comment by peterix** [comment]
The obvious thing to do would be to build from source with debug symbols and gather stack traces.

**Comment by md5i** [comment]
Closing this issue to open a new one.
