### ISSUE TITLE
Downloaded Skyfactory 3 off Curse and it won't run in MultiMC? It said it was correct and everything but it didn't work.

### ISSUE THREAD

**Issue by bhk696494** [MultiMC/MultiMC5#2793]
System Information
-----------------------------
MultiMC version: 0.6.7

Operating System: Windows 10

Summary of the issue or suggestion: Not able to load a modpack
----------------------------------------------

What should happen: Load mudpack successfully
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download SF3 from Curseforge

2. Open it with MultiMC (in the correct version)

3. Watch failure ensue by launching it. 

Suspected cause: Missing json
---------------------------

Logs/Screenshots: 
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
![stupid multimc](https://user-images.githubusercontent.com/53904030/62704125-0d088680-b9c1-11e9-8d5f-97b41f67723d.png)

MultiMC version: 0.6.7-1375

Minecraft folder is:
C:/Users/Owner/Downloads/MultiMC/instances/FTB Presents Skyfactory 3/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_221, using 32-bit architecture.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/Owner/Downloads/MultiMC/instances/FTB Presents Skyfactory 3/natives

Libraries:
  C:/Users/Owner/Downloads/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/com/mojang/authlib/1.5.22/authlib-1.5.22.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/com/mojang/realms/1.9.8/realms-1.9.8.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/it/unimi/dsi/fastutil/7.0.12_mojang/fastutil-7.0.12_mojang.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/net/minecraftforge/forge/1.10.2-12.18.3.2477/forge-1.10.2-12.18.3.2477-universal.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/jline/jline/2.13/jline-2.13.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/com/mojang/minecraft/1.10.2/minecraft-1.10.2-client.jar

Native libraries:
  C:/Users/Owner/Downloads/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/Owner/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Mods:
  [✔️] [1.10.x]FenceOverhaul-1.2.1
  [✔️] ActuallyAdditions-1.10.2-r105
  [✔️] actuallycomputers-1.0.0
  [✔️] angelRingToBauble-1.10.2-0.2.4.19+d71eb9e
  [✔️] AppleCore-mc1.10.2-2.2.2
  [✔️] AppleShields-0.1.7
  [✔️] AppleSkin-mc1.10.2-1.0.8
  [✔️] autopackager-1.6.4b
  [✔️] AutoRegLib-1.0-2
  [✔️] baconators-1.10.2-3.0.6
  [✔️] base-1.10.2-1.4.0
  [✔️] Baubles-1.10.2-1.3.11
  [✔️] bdlib-1.12.4.24-mc1.10.2
  [✔️] BedBugs-1.10.2-1.1.6
  [✔️] BetterBuildersWands-1.10.2-0.11.1.220+f8232fe
  [✔️] BetterFps-1.4.5-1.10
  [✔️] BetterThanBunnies-1.10.2-1.1.0
  [✔️] BiomeTweaker-1.10.2-2.3.239
  [✔️] BlockDispenser-1.0-1
  [✔️] BloodMagic-1.10.2-2.1.11-80
  [✔️] Bookshelf-1.10.2-1.4.4.347
  [✔️] Botania r1.9-341
  [✔️] BrandonsCore-1.10.2-2.1.12.130-universal
  [✔️] Ceramics-1.10.2-1.1.6b
  [✔️] Chameleon-1.10.2-2.3.0
  [✔️] ChanceCubes-1.10.2-3.0.1.207
  [✔️] Charset-mc1.10.2-0.3.5-fd38f2c944396214
  [✔️] ChestTransporter-1.10.2-2.5.18
  [✔️] ChickenChunks-1.10.2-2.2.0.52-universal
  [✔️] chickens-4.3.2
  [✔️] Chisel-MC1.10.2-0.0.14.33
  [✔️] chiselsandbits-12.15
  [✔️] ClientTweaks_1.10.2-1.1.16
  [✔️] Clipboard-1.10.2-1.1.1
  [✔️] Clumps-1.0.5
  [✔️] CodeChickenCore-1.10.2-2.4.1.102-universal
  [✔️] CodeChickenLib-1.10.2-2.5.9.283-universal
  [✔️] ColossalChests-1.10.2-1.6.0
  [✔️] CommonCapabilities-1.9.4-1.3.3
  [✔️] compatlayer-1.10-0.2.9
  [✔️] Controlling-1.0.5
  [✔️] CookingForBlockheads_1.10.2-4.2.45
  [✔️] CraftTweaker-1.10.2-3.0.26
  [✔️] CTM-MC1.10.2-0.2.2.24
  [✔️] CustomMainMenu-MC1.10.2-2.0.5
  [✔️] CyclopsCore-1.9.4-0.10.9
  [✔️] DarkUtilities-1.1.8.finalrc2
  [✔️] Decocraft-2.4.2_1.10.2
  [✔️] DefaultOptions_1.10.2-6.1.5
  [✔️] dimensionalcake-1.9.4-0.0.1
  [✔️] Draconic-Evolution-1.10.2-2.1.6.263-universal
  [✔️] DragonMounts-r46-1.10.2
  [✔️] DrawersBits-1.10.2-0.36
  [✔️] ElevatorMod[V.1.3.0][MC.1.10.2]
  [✔️] EnderCore-1.10.2-0.4.1.66-beta
  [✔️] EnderIO-1.10.2-3.1.193
  [✔️] EnderStorage-1.10.2-2.2.1.106-universal
  [✔️] energyconverters_1.10.2-1.0.0.26
  [✔️] EngineersWorkshop-1.3.6-1.10.2
  [✔️] environmentaltech-1.10.2-0.10.6b
  [✔️] etlunar-1.10.2-0.10.6a
  [✔️] ExCompressum_1.10.2-2.0.97
  [✔️] exnihiloadscensio-1.10.2-0.1.20
  [✔️] ExtraBitManipulation-1.10.2-2.5.1
  [✔️] extrautils2-1.10.2-1.6.3
  [✔️] ExtremeReactors-1.10.2-0.4.5.30
  [✔️] fairylights-2.1.2-1.10.2
  [✔️] FarmingForBlockheads_1.10.2-1.1.16
  [✔️] flatcoloredblocks-mc1.10-v4.4
  [✔️] FluxNetworks-1.10.2-1.2.8
  [✔️] foamfix-0.7.2-anarchy
  [✔️] Forgelin-1.5.1
  [✔️] FTBLib-1.1x-3.6.5
  [✔️] FTBUtilities-1.1x-3.6.5
  [✔️] FullscreenWindowed-1.10.2-1.5.1
  [✔️] Funnels-1.10.2-1.1.2
  [✔️] GardenOfGlass
  [✔️] generators-0.9.20.23-mc1.10.2
  [✔️] GooglyEyes-1.10.2-6.0.0
  [✔️] gravestone-1.5.13
  [✔️] Grue-1.9.4-1.3.5
  [✔️] Guide-API-1.10.2-2.0.3-46
  [✔️] Gyth-1.10.2-2.0.0.27
  [✔️] HammerCore-1.10.2-1.9.4.3
  [✔️] hatchery-1.10.2-0.3.21
  [✔️] Headcrumbs-2.0.3
  [✔️] hopperducts-mc1.9.4-1.4.8.1
  [✔️] Hwyla-1.8.17-B31_1.10.2
  [✔️] hydrogel-0.9
  [✔️] ImmersiveEngineering-0.10-61
  [✔️] InGameInfoXML-1.10.2-2.8.1.89-universal
  [✔️] InitialInventory-1.0.1
  [✔️] IntegratedDynamics-1.10.2-0.7.12
  [✔️] IntegratedTunnels-1.10.2-1.2.5
  [✔️] inventorysorter-1.10.2-0.11.0+47
  [✔️] IronBackpacks-1.10.2-2.2.31
  [✔️] ironchest-1.10.2-7.0.15.804
  [✔️] ItsBecauseUHasNoGoodSpawn-1.0.5
  [✔️] itsrainingfood-1.10.2-0.1.0
  [✔️] jei_1.10.2-3.14.7.420
  [✔️] journeymap-1.10.2-5.5.0b4
  [✔️] KleeSlabs_1.10.2-3.3.5
  [✔️] literalascension-1.10.2-1.0.2.2
  [✔️] llibrary-1.7.7-1.10.2
  [✔️] LongFallBoots - Hard Mode
  [✔️] LootBags-1.10.2-2.3.9
  [✔️] LunatriusCore-1.10.2-1.1.2.38-universal
  [✔️] Mantle-1.10.2-1.1.5
  [✔️] mcjtylib-1.1x-2.4.3
  [✔️] MCMultiPart-1.4.0-universal
  [✔️] Mercurius-1.10.2-1.0.6
  [✔️] MineMenu-1.10.2-1.4.5-universal
  [✔️] minicoal-1.1.0
  [✔️] missing_pieces-1.10.2-4.3.0
  [✔️] MoarSigns-1.10.2-4.2.3.9
  [✔️] MobGrindingUtils-0.1.8.22
  [✔️] ModTweaker2-2.0.13
  [✔️] MoreChickens-1.10.2-1.1.6
  [✔️] MoreShearables1.2.1-1.10.2
  [✔️] moreshears-1.10.2-1.0.5-release
  [✔️] Morpheus-1.10.2-3.1.13
  [✔️] MouseTweaks-2.8-mc1.10.2
  [✔️] mpbasic-1.10.2-1.1.5
  [✔️] mputils-1.10.2-1.2.9
  [✔️] MTLib-1.0.3
  [✔️] mysticalagriculture[1.10.2]-1.5.8
  [✔️] natura-1.10.2-4.1.0.80
  [✔️] Neat 1.3-12
  [✔️] nice-0.1.0
  [✔️] NotEnoughItems-1.10.2-2.1.3.220-universal
  [✔️] notenoughwands-1.1x-1.5.5
  [✔️] OpenComputers-MC1.10.2-1.6.2.7
  [✔️] OreExcavation-1.2.102
  [✔️] PackingTape-1.10.2-0.6.0
  [✔️] Pam's HarvestCraft 1.9.4-1.10.2h
  [✔️] platforms-1.10.0-1.2.10
  [✔️] Psi-r1.0-42
  [✔️] QuantumStorage-1.10.2-3.3.6
  [✔️] RandomThings-MC1.10.2-3.7.7.1
  [✔️] rangedpumps-0.3
  [✔️] RebornCore-1.10.2-2.13.6.142-universal
  [✔️] RebornStorage-1.10.2-1.0.3.30
  [✔️] redstonepaste-mc1.9.4-1.7.4
  [✔️] refinedstorage-1.2.26
  [✔️] Reliquia-[1.10.2]-0.0.7
  [✔️] ResourceLoader-MC1.9.4-1.5.1
  [✔️] rftools-1.1x-6.13
  [✔️] rftoolsctrl-1.1x-1.6.8
  [✔️] rftoolsdim-1.1x-5.05
  [✔️] roots-0.208
  [✔️] SBM-WoodenShears-1.10.2-0.0.1b2-universal
  [✔️] scanner-1.5.2
  [✔️] ShadowMC-1.10.2-3.6.1
  [✔️] shearmadness-1.10.2-1.7.0.4
  [✔️] shetiphiancore-1.10.0-3.3.11
  [✔️] SimpleAchievements-MC1.9.4-1.2.2-28
  [✔️] simplebarrels-1.26e
  [✔️] simpleCorn-1.10.2-2.2.0
  [✔️] simplegenerators-1.10.2-0.10.6a
  [✔️] simplelabels-1-10.2-0.0.3
  [✔️] SimplyJetpacks2-1.10.2-2.1.3.55
  [✔️] Snad-1.10.2-1.6.09.20a
  [✔️] SolarFluxReborn_1.10.2-2.17r
  [✔️] SonarCore-1.10.2-3.3.0
  [✔️] StevesCarts-1.10.2-2.2.0.86
  [✔️] StorageDrawers-1.10.2-3.7.10
  [✔️] SuperCircuitMaker-1.0.4
  [✔️] TConstruct-1.10.2-2.6.5
  [✔️] The Beneath-1.10.2-1.2.0
  [✔️] TinkerToolLeveling-1.10.2-1.0.1
  [✔️] tinyprogressions-1.10.2-1.1.0
  [✔️] torchmaster_1.10.2-1.4.1.34
  [✔️] Translocators-1.10.2-2.1.4.55-universal
  [✔️] TS2K16-1.0.3
  [✔️] Twitchcrumbs_1.10.2-2.0.4
  [✔️] UniDict-1.10.2-2.9b
  [✔️] valkyrielib-1.10.2-0.10.6
  [✔️] voidcup-1.10.2-0.0.1
  [✔️] Waddles-1.10.2-0.5.4
  [✔️] WanionLib-1.10.2-1.3
  [✔️] Wawla-1.10.2-2.3.2.215
  [✔️] witherCrumbs-1.10.2-0.9
  [✔️] xprings-1.10-1.3.0
  [✔️] YUNoMakeGoodMap-1.10.2-6.1.0.26
  [✔️] zerocore-1.10.2-0.1.0.6

Params:
  --username  --version MultiMC5 --gameDir C:/Users/Owner/Downloads/MultiMC/instances/FTB Presents Skyfactory 3/.minecraft --assetsDir C:/Users/Owner/Downloads/MultiMC/assets --assetIndex 1.10 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx2048m, -Duser.language=en]

Minecraft process ID: 13044

Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Process exited with code 1.
Clipboard copy at: 08 Aug 2019 09:38:15 -0300

**Comment by bhk696494** [comment]
Also tried downloading off of MultiMC itself.

**Comment by QuImUfu** [comment]
You are assigning Minecraft over 2GB of ram and are using a 32 bit installation of Java. Install/use a 64 bit Java version (Java 8).
