### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by xag803** [MultiMC/MultiMC5#2798]
System Information
-----------------------------
MultiMC version:0.6.7-1375

Operating System: windows 10

Summary of the issue or suggestion: crash
----------------------------------------------

What should happen: it should load
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. ???

2.

3.

Suspected cause: mods
---------------------------

Logs/Screenshots: https://paste.ee/p/QwXqO
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by QuImUfu** [comment]
You are missing MegaLoots dependency [Baubles](https://www.curseforge.com/minecraft/mc-mods/baubles). Install it.
