### ISSUE TITLE
Error downloading "net.minecraftforge/28.0.40.json"

### ISSUE THREAD

**Issue by Randomizzerr** [MultiMC/MultiMC5#2800]
System Information
-----------------------------
MultiMC version: 0.6.7-custom (from the AUR)

Operating System: Manjaro Linux (Linux 4.19.62-1)

Summary of the issue or suggestion:
----------------------------------------------
When attempting to launch modpacks, it fails to download the necessary files and crashes on launch. 

What should happen:
------------------------------
Everything should download and the game should launch.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add an instance from the modpack via the twitch URL option.

2. Launch.

3. Crash.

Suspected cause:
---------------------------
Based on the logs at least, I think it fails to download forge.

Logs/Screenshots:
----------------------------
MultiMC version: 0.6.7-custom

Minecraft folder is:
/home/randomizzerr/.local/share/multimc/instances/file/minecraft

Java path is:
/usr/bin/java

Java is version 1.8.0_222, using 64-bit architecture.

Instance update failed because: Component metadata update task failed while downloading from remote server:
Job 'Download of meta file net.minecraftforge/28.0.40.json' failed to process:
https://meta.multimc.org/v1/net.minecraftforge/28.0.40.json

Additional Info:
---------------------------
I've tested a few other modpacks, same result.

**Comment by peterix** [comment]
See #2544 

Complain to forge maintainers for making the installation process complex for no good reason.

**Comment by EmberFlash** [comment]
peterix, I believe you are the only one here making this a problem. As I have seen the Forge team try to work and help you solve this problem by giving you possible solutions. And telling Others to go complain to forge is bad sportsmanship. And only makes you look like a dick.

**Comment by peterix** [comment]
They try to infect MultiMC with the same problems vanilla has. I don't want this here. It's short sighted and crippling to the launcher.
