### ISSUE TITLE
i think it is dangerous

### ISSUE THREAD

**Issue by keeganthomas** [MultiMC/MultiMC5#2804]
I was trying to install and it was blocked. add a publisher for windows so windows defender does not block it!

**Comment by Zetabite** [comment]
Or Just Accept "unsafe" Install

**Comment by peterix** [comment]
These things aren't exactly cheap, and I don't like 'protection' rackets.

**Comment by peterix** [comment]
https://en.wikipedia.org/wiki/Protection_racket

**Comment by keeganthomas** [comment]
welp, I think publishers stop the warnings (windows defender verifies the publisher)

**Comment by keeganthomas** [comment]
@peterix plz open it again

**Comment by S10MC2015** [comment]
It isn't that bad of a problem. We would have to get ffork or peterix to go through alot of work and maybe money for little actual worth. The money part also goes with joining appledev program for validation too.

**Comment by gzusphish** [comment]
Well, how much does it cost? I'd be willing to put some money toward this. We already know (or hope) that MultiMC is trustworthy - I trust it, anyway.

Also, how is this related to a protection racket? According to the page you posted that sort of thing involves threats of violence. Depending on how much effort MS puts into validating publishers, it seems to me more like the concept of a surety bond.

https://www.sba.gov/funding-programs/surety-bonds

**Comment by Zetabite** [comment]
Meh. Not worth it. There are enough programs that have a certificate but are malicious. So paying for it doesnt really make sense, if it doesnt say anything about trustworthyness

**Comment by gzusphish** [comment]
True. Hadn't thought of that.
