### ISSUE TITLE
MC Crashes When I maximize

### ISSUE THREAD

**Issue by Hrishnugg** [MultiMC/MultiMC5#2805]
System Information
-----------------------------
MultiMC version: 0.6.7

Operating System: Windows =10

Summary of the issue or suggestion:
----------------------------------------------
**MC Crashes when I maximize**

What should happen:
------------------------------
MC should be stable when i hit maximize button.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create instance of vanilla 1.14.4

2. Run the instance

3. Hit the maximize button

Suspected cause:
---------------------------
**Absolutely unsure why it is happening**

Logs/Screenshots:
----------------------------
MultiMC version: 0.6.7-1375

Minecraft folder is:
C:/Users/hrish/Multi-MC/MultiMC/instances/Regular/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_221, using 32-bit architecture.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/hrish/Multi-MC/MultiMC/instances/Regular/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/hrish/Multi-MC/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/com/mojang/minecraft/1.14.4/minecraft-1.14.4-client.jar

Native libraries:
  C:/Users/hrish/Multi-MC/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/hrish/Multi-MC/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/Users/hrish/Multi-MC/MultiMC/instances/Regular/.minecraft --assetsDir C:/Users/hrish/Multi-MC/MultiMC/assets --assetIndex 1.14 --uuid  --accessToken  --userType  --versionType release

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1280m, -Xmx1280m, -Duser.language=en]

Minecraft process ID: 11136

Using onesix launcher.

[21:12:03] [Client thread/INFO]: Setting user: VeeviMasters
[21:12:07] [Client thread/INFO]: LWJGL Version: 3.2.2 build 10
[21:12:09] [Client thread/INFO]: Narrator library for x86 successfully loaded
[21:12:19] [Client thread/INFO]: OpenAL initialized.
[21:12:19] [Client thread/INFO]: Sound engine started
[21:12:20] [Client thread/INFO]: Created: 1024x512 textures-atlas
[21:12:20] [Client thread/INFO]: Created: 256x256 textures/particle-atlas
[21:12:20] [Client thread/INFO]: Created: 256x256 textures/painting-atlas
[21:12:20] [Client thread/INFO]: Created: 256x128 textures/mob_effect-atlas
[21:12:32] [Client thread/INFO]: OpenGL debug message, id=1285, source=API, type=ERROR, severity=HIGH, message=Error has been generated. GL error GL_OUT_OF_MEMORY in (null): (ID: 173538523) Generic error
Process crashed with exitcode -805306369.

Additional Info:
---------------------------

**Comment by S10MC2015** [comment]
Out of memory on either graphics or system ram. Probably system. Change java to 64 bit

**Comment by S10MC2015** [comment]
Also please use upload log feature

**Comment by Frontear** [comment]
What's your graphics card?

**Comment by Frontear** [comment]
> Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Update your Java, might not solve this issue, but it's definitely good for preventing further issues with allocations

> OpenGL debug message, id=1285, source=API, type=ERROR, severity=HIGH, message=Error has been generated. GL error GL_OUT_OF_MEMORY in (null): (ID: 173538523) Generic error

What is your GPU, VRAM, and system RAM?

**Comment by Hrishnugg** [comment]
My GPU is Intel HD Graphics 620. I have only 128 mb VRAM. I have 16 GB RAM.

**Comment by Frontear** [comment]
Which versions of MC work for you? Does anything below 1.12.2 work? What about in the default launcher?

Try updating your GPU drivers. `GL_OUT_OF_MEMORY` can be caused if VRAM or if normal RAM are exceeded in capacity. Considering the size of the VRAM, it's far more likely your low-end gpu is the culprit here.
