### ISSUE TITLE
Discord  link invalid

### ISSUE THREAD

**Issue by Johnibur** [MultiMC/MultiMC5#2806]
Discord link given in readme or other sites related to multimc (main website, patreon) is no longer valid.

**Comment by Heufneutje** [comment]
All of those links work fine. If they don't for you you're doing something wrong.

**Comment by peterix** [comment]
Maybe discord is failing, or maybe you were banned at some point.

**Comment by Johnibur** [comment]
I'd say something is wrong with Discord. Tried it again. From my browser (I'm am not authentificated), I recieved a "Invalid link  may have expired". But from the Discord client, it worked.
