### ISSUE TITLE
exitcode 6 with Ubuntu 18

### ISSUE THREAD

**Issue by truwizard19** [MultiMC/MultiMC5#2807]
System Information
-----------------------------
MultiMC version: 0.6.7

Operating System: Ubuntu 18

Summary of the issue or suggestion:
----------------------------------------------
game crash, error exitcode 6 when building program 

What should happen:
------------------------------
not to get error

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Launch any FTB modpack other than FTB lite

2. java-8-openjdk-amd64

3.

Suspected cause:
---------------------------
unsure

Logs/Screenshots:
----------------------------
[//]: # https://paste.ee/p/WYZFi

Additional Info:
---------------------------

**Comment by Frontear** [comment]
Future reference for anyone else, its a `JsonSyntaxException` when the SoundHandler tries to parse sounds.json: https://paste.ee/p/WYZFi#s=0&l=819

This looks to be an asset issue. Can you clear and re-download the assets?

**Comment by truwizard19** [comment]
Sadly, I have done so a few times. Even going as far as to do a full reformat of ubuntu 18, download multimc again, and open java 8 jdk only to get the same error. Thank you for reviewing my error log.

**Comment by Frontear** [comment]
Does the normal launcher work fine?

**Comment by truwizard19** [comment]
Yes, as well as the original minecraft and even ftb lite. Unfortunately anything beyond that crashes. Thank you!
