### ISSUE TITLE
Minecraft won't launch with exitcode 255

### ISSUE THREAD

**Issue by steirter** [MultiMC/MultiMC5#2809]
System Information
-----------------------------
MultiMC version: 06.7-1316

Operating System: osx64

Summary of the issue or suggestion:
----------------------------------------------
Minecraft can't be started

What should happen:
------------------------------
Minecraft should start up

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. add the instance of ftb presents stoneblock 2 in MultiMC

2. Launch offline

Suspected cause:
---------------------------
No idea I don't understand the log

Logs/Screenshots:
----------------------------
https://paste.ee/p/Uh9Tk

Additional Info:
---------------------------
I don't really know what's happening here so help is much appreciated

**Comment by tehbasshunter** [comment]
You're using Java 12. Switch to 8 as modded won't work beyond that.

**Comment by Frontear** [comment]
Java 12 breaks LWJGL2 (not sure about 3), as a result, you can't use it. Bump Java down to Java 8, or try playing with 1.13+

**Comment by steirter** [comment]
Yeah thats what im trying right now but java is kinda a b*tch to download you need an account and such

**Comment by steirter** [comment]
It worked! Thanks a lot!!
