### ISSUE TITLE
Crash when starting instances with Forge - Linux Mint 19.1 

### ISSUE THREAD

**Issue by krallendertoten** [MultiMC/MultiMC5#2810]
_**System Info**_

Intel(R) Core(TM) i3-5020U CPU @ 2.20GHz
Intel Corporation HD Graphics 5500 (rev 09)

Subsystem: Hewlett-Packard Company HD Graphics 5500

Kernel driver in use: i915

OpenGL version string: 3.0 Mesa 19.0.8

-----------------------------
**_MultiMC Version_**

0.6.7-1290

-----------------------------
_**Operating System**_

Linux Mint 19.1 Cinnamon

-----------------------------
**_Summary of Issue_**

When attempting to launch an instance of Minecraft with Forge, it immediately crashes. Forge is installed using the built-in installer (native to MultiMC). This occurs regardless of which version of Forge is used, and regardless of which version of Minecraft is used. I have tested with and without mods, and with different versions of both OpenJDK and Oracle's standard JRE; same results happen regardless. This issue does not occur with identical tests (same JRE and versions) on Windows 10.

EDIT: I also tested with and without JVM args; no changes.

-----------------------------
**_Suspected Cause_**

Incompatibility with Forge somewhere along the line with Linux

-----------------------------
**_Logs_**

https://paste.ee/p/GRGR0

https://paste.ee/p/XNGpM

**Comment by tehbasshunter** [comment]
You need Java 8 if you're gonna use modded. Anything higher won't work.

**Comment by krallendertoten** [comment]
Oh duh; you're absolutely correct. Is this an issue with Linux and forge compatibility specifically then?

**Comment by tehbasshunter** [comment]
No. It's with any OS. Only pure vanilla will work with higher Java versions.

**Comment by krallendertoten** [comment]
I see. Thank you for your help!
