### ISSUE TITLE
Crash w/Unexpected Error

### ISSUE THREAD

**Issue by Gameknight6916** [MultiMC/MultiMC5#2812]
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  HCASM (HammerCore-1.12.2-2.0.4.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.6-universal.jar)
  PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.2.0.3.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 8/20/19 6:58 PM
XRay version: 58
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraftxray.ci.tick(SourceFile:132)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3021954968 bytes (2881 MB) / 3943694336 bytes (3761 MB) up to 3943694336 bytes (3761 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4048m -Xmx4176m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 61 mods loaded, 61 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                        | Version           | Source                                            | Signature                                |
	|:------ |:------------------------- |:----------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                 | 1.12.2            | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp                       | 9.42              | minecraft.jar                                     | None                                     |
	| LCHIJA | FML                       | 8.0.99.99         | forge-1.12.2-14.23.5.2838-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                     | 14.23.5.2838      | forge-1.12.2-14.23.5.2838-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | passableleavescore        | 1.0.0             | minecraft.jar                                     | None                                     |
	| LCHIJA | techguns_core             | 1.12.2-1.0        | minecraft.jar                                     | None                                     |
	| LCHIJA | securitycraft             | v1.8.12           | [1.12.2]+SecurityCraft+v1.8.12.jar                | None                                     |
	| LCHIJA | buildcraftlib             | 7.99.21           | buildcraft-all-7.99.21.jar                        | None                                     |
	| LCHIJA | buildcraftcore            | 7.99.21           | buildcraft-all-7.99.21.jar                        | None                                     |
	| LCHIJA | buildcraftfactory         | 7.99.21           | buildcraft-all-7.99.21.jar                        | None                                     |
	| LCHIJA | buildcrafttransport       | 7.99.21           | buildcraft-all-7.99.21.jar                        | None                                     |
	| LCHIJA | buildcraftsilicon         | 7.99.21           | buildcraft-all-7.99.21.jar                        | None                                     |
	| LCHIJA | additionalpipes           | 6.0.0.8           | additionalpipes-6.0.0.8.jar                       | None                                     |
	| LCHIJA | csb_armorstand            | 1.0.4             | ArmorStandGUI-1.12-1.0.4.jar                      | None                                     |
	| LCHIJA | betterquesting            | 3.5.300           | BetterQuesting-3.5.300.jar                        | None                                     |
	| LCHIJA | biomesoplenty             | 7.0.1.2399        | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar     | None                                     |
	| LCHIJA | buildcraftbuilders        | 7.99.21           | buildcraft-all-7.99.21.jar                        | None                                     |
	| LCHIJA | buildcraftcompat          | 7.99.21           | buildcraft-all-7.99.21.jar                        | None                                     |
	| LCHIJA | buildcraftenergy          | 7.99.21           | buildcraft-all-7.99.21.jar                        | None                                     |
	| LCHIJA | buildcraftrobotics        | 7.99.21           | buildcraft-all-7.99.21.jar                        | None                                     |
	| LCHIJA | cavern                    | 2.2.0             | Cavern_1.12.2-v2.2.0.jar                          | b78e30ad27c82f3e348f76edf497058678207299 |
	| LCHIJA | charset                   | 0.5.5.6           | Charset-Lib-0.5.5.6.jar                           | None                                     |
	| LCHIJA | codechickenlib            | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | chickenchunks             | 2.4.1.73          | ChickenChunks-1.12.2-2.4.1.73-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux              | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore                  | 4.6.3             | CoFHCore-1.12.2-4.6.3.27-universal.jar            | None                                     |
	| LCHIJA | cofhworld                 | 1.3.1             | CoFHWorld-1.12.2-1.3.1.7-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | colytra                   | 1.2.0.3           | colytra-1.12.2-1.2.0.3.jar                        | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | doggytalents              | 1.14.2.396        | DoggyTalents-1.12.2-1.14.2.396-universal.jar      | None                                     |
	| LCHIJA | durabilityshow            | 5.0.0             | Durability+Show-1.12-5.0.0.jar                    | None                                     |
	| LCHIJA | hammercore                | 2.0.4.2           | HammerCore-1.12.2-2.0.4.2.jar                     | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | waila                     | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
	| LCHIJA | improvableskills          | 3.6.0r            | ImprovableSkills-1.12.2-3.6.0r.jar                | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | infinity                  | 0.13.2            | Infinity-0.13.2.jar                               | None                                     |
	| LCHIJA | invisiblights             | 3.0-8             | invisiblights-3.1-9.jar                           | None                                     |
	| LCHIJA | ironchest                 | 1.12.2-7.0.59.842 | ironchest-1.12.2-7.0.59.842.jar                   | None                                     |
	| LCHIJA | jei                       | 4.13.1.225        | jei_1.12.2-4.13.1.225.jar                         | None                                     |
	| LCHIJA | journeymap                | 1.12.2-5.5.5b7    | journeymap-1.12.2-5.5.5b7.jar                     | None                                     |
	| LCHIJA | lunatriuscore             | 1.2.0.42          | LunatriusCore-1.12.2-1.2.0.42-universal.jar       | None                                     |
	| LCHIJA | minemenu                  | 1.6.11            | MineMenu-1.12.2-1.6.11-universal.jar              | None                                     |
	| LCHIJA | neat                      | 1.4-17            | Neat+1.4-17.jar                                   | None                                     |
	| LCHIJA | oreexcavation             | 1.4.140           | OreExcavation-1.4.140.jar                         | None                                     |
	| LCHIJA | redstonearsenal           | 2.6.3             | RedstoneArsenal-1.12.2-2.6.3.18-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | scenter                   | 1.12-3.11.0       | scenter-1.12.2-3.12.0.jar                         | None                                     |
	| LCHIJA | schematica                | 1.8.0.169         | Schematica-1.12.2-1.8.0.169-universal.jar         | None                                     |
	| LCHIJA | sereneseasons             | 1.2.6             | SereneSeasons-1.12.2-1.2.6-universal.jar          | None                                     |
	| LCHIJA | simplecore                | 1.7.3.4           | simplecore-1.12.2-1.7.3.4.jar                     | None                                     |
	| LCHIJA | simpleores                | 1.11.2.0          | simpleores-1.12.2-1.11.2.0.jar                    | None                                     |
	| LCHIJA | bq_standard               | 3.4.159           | StandardExpansion-3.4.159.jar                     | None                                     |
	| LCHIJA | techguns                  | 2.0.2.0           | techguns-1.12.2-2.0.2.0_pre3.1.jar                | None                                     |
	| LCHIJA | thermalfoundation         | 2.6.3             | ThermalFoundation-1.12.2-2.6.3.27-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalcultivation        | 0.3.3             | ThermalCultivation-1.12.2-0.3.3.12-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermaldynamics           | 2.5.5             | ThermalDynamics-1.12.2-2.5.5.21-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | travellersbackpack        | 1.0.19.19         | TravellersBackpack-1.12.2-1.0.19.19.jar           | None                                     |
	| LCHIJA | treechopper               | 1.2.4             | TreeChopper-1.12.2-1.2.4.jar                      | None                                     |
	| LCHIJA | chunkbase_villageinfo_ssp | 2.1               | VillageInfoSSP-1.12.2-2.1.jar                     | None                                     |
	| LCHIJA | walljump                  | 1.12.2-1.2.3      | walljump-1.12.2-1.2.3.jar                         | None                                     |
	| LCHIJA | worldedit                 | 6.1.10-SNAPSHOT   | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
	| LCHIJA | zerocore                  | 1.12.2-0.1.2.8    | zerocore-1.12.2-0.1.2.8.jar                       | None                                     |
	| LCHIJA | llibrary                  | 1.7.19            | llibrary-1.7.19-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | passableleaves            | 2.0.0             | PassableLeaves-1.12.2-2.0.0.jar                   | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
HCASM (HammerCore-1.12.2-2.0.4.2.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.6-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  teamrtg.passableleaves.asm.PassableLeavesTransformer
ColytraLoadingPlugin (colytra-1.12.2-1.2.0.3.jar)
  c4.colytra.asm.ElytraTransformer
Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
  techguns.core.TechgunsASMTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13547 Compatibility Profile Context 25.20.15031.1000' Renderer: 'AMD Radeon(TM) R4 Graphics'
	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 524 names; 760 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KDQogICAgIyBSZXBsYWNlIHZhbmlsbGEgZnVybmFjZSBhbmQgYnJld2luZyBzdGFuZCBwcm9ncmVzcyBiYXJzIHRvIHVzZSBzbW9vdGggcmVuZGVyaW5nPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJTbW9vdGggVmFuaWxsYSBHdWlzIj10cnVlDQp9DQoNCg0KaXdyZW5jaCB7DQogICAgIyBXaGF0IGlzIHRoZSBjb2xvciB3aGVuIHRoZSBob3ZlcmVkIGJsb2NrIGlzIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6R3JlZW49MjJGRjIyDQoNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgTk9UIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6UmVkPUZGMjIyMg0KfQ0KDQoNCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGZvcmNlLXNwYXduIEVuZGVyIERyYWdvbiBFZ2cgb24gRW5kZXIgRHJhZ29uIGRlYXRoPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJBbHdheXMgU3Bhd24gRHJhZ29uIEVnZyI9dHJ1ZQ0KfQ0KDQoNCg==
Pastebin Connection: Okay.
Dependent Mods:
    -Improvable Skills (improvableskills) @3.6.0r

	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) R4 Graphics GL version 4.6.13547 Compatibility Profile Context 25.20.15031.1000, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A6-7310 APU with AMD Radeon R4 Graphics 
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13547 Compatibility Profile Context 25.20.15031.1000
	OpenGlRenderer: AMD Radeon(TM) R4 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4
[18:58:11] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Clan\Desktop\Max's Stuff\Minecraft\MultiMC\instances\Mechanical\.minecraft\crash-reports\crash-2019-08-20_18.58.10-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.
`

**Comment by Gameknight6916** [comment]
Crashes before even loading Main Menu.

**Comment by peterix** [comment]
This is not related to MultiMC.
