### ISSUE TITLE
Forge ClassNotFoundException: net.minecraftforge.fml.common.launcher.FMLTweaker

### ISSUE THREAD

**Issue by MarkCangila** [MultiMC/MultiMC5#2813]
System Information
-----------------------------
MultiMC version:
0.6.7-1375
Operating System:
Windows 10 Home 64 Bit
Summary of the issue or suggestion:
----------------------------------------------
When I attempt to open any modpack, it fails. I have tried it with FTB Academy and Breakout. There are 2 errors that occur. The FTB Academy has multiple errors as in the log, and Breakout can't find the FMLTweaker class.

What should happen:
------------------------------
The modpacks should boot correctly and load the mods. They do not.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add a modpack through zip or FTB legacy

2. Attempt to open a modpack

3. It fails (This is probably based on some computer config but I'm not sure what)

Suspected cause:
---------------------------
I have no idea

Logs/Screenshots:
----------------------------
FTB Academy Log: https://paste.ee/p/43hw1
Breakout log: https://paste.ee/p/NSPUu

Additional Info:
---------------------------
I am running forge version 14.23.5.2768

**Comment by MarkCangila** [comment]
It fixed for FTB Academy but does not work for Breakout after a reinstall

**Comment by peterix** [comment]
Logs are gone. Sorry. Closing.
