### ISSUE TITLE
minecraft not starting

### ISSUE THREAD

**Issue by MrWatermelaun** [MultiMC/MultiMC5#2820]
System Information
-----------------------------
MultiMC version: 0.6.7

Operating System: Windows 10 x64

Summary of the issue or suggestion:
 MultiMC doesn't start Minecraft
----------------------------------------------

What should happen: 
Minecraft should start loading
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause: 
these mods seem to have something to do with the problem. I tried reinstalling them but it didn't solve it
![e](https://user-images.githubusercontent.com/54384365/63632179-46fb9e80-c5f7-11e9-8f5a-15240d891e6a.png)

---------------------------

Logs/Screenshots:
 https://paste.ee/p/Vzi9k
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by MrWatermelaun** [comment]
can someone help with this?

**Comment by Zetabite** [comment]
Try installing Forgelin

**Comment by MrWatermelaun** [comment]
tried both, still have the same problem
