### ISSUE TITLE
Can't start any minecraft instance

### ISSUE THREAD

**Issue by CmdrClown** [MultiMC/MultiMC5#2824]
### System Information
MultiMC Version: 0.6.7
Operating System: Windows 10 

### Summary of problem-
MultiMC won't run any instances

### What Should Happen
Instances should run

### Steps to Replicate issue
1. Open MultiMC
2. Create instance
3. Attempt to run instance

### Suspected cause
No idea

### Crash reports
MultiMC version: 0.6.7-1375

Minecraft folder is:
C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/instances/Sky World/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_221/bin/javaw.exe

Java is version 1.8.0_221, using 64-bit architecture.

Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/instances/Sky World/natives

Libraries:
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.0/lwjgl-2.9.0.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.0/lwjgl_util-2.9.0.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.0/lwjgl-platform-2.9.0-natives-windows.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar
  C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Mods:
  [📁] 1.7 (folder)
  [✔️] AdvancedSolarPanel-1.7.10-3.5.1
  [✔️] AgriCraft-1.7.10-1.5.0
  [✔️] AOBD-2.9.2
  [✔️] appliedenergistics2-rv3-beta-6
  [✔️] Avaritia-1.11
  [✔️] bdlib-1.9.4.109-mc1.7.10
  [✔️] BiblioCraft[v1.11.7][MC1.7.10]
  [✔️] BiblioWoods[BiomesOPlenty][v1.9]
  [✔️] BiblioWoods[Forestry][v1.7]
  [✔️] BiblioWoods[Natura][v1.5]
  [✔️] BigReactors-0.4.3A
  [✔️] Binnie Patcher 1.8
  [✔️] binnie-mods-2.0-pre14
  [✔️] BiomeTweaker-1.7.10-2.0.182
  [✔️] BloodMagic-1.7.10-1.3.3-17
  [✔️] Botania r1.8-249
  [✔️] BrandonsCore-1.0.0.12
  [✔️] buildcraft-7.1.22
  [✔️] buildcraft-compat-7.1.5
  [✔️] Carpenter's Blocks v3.3.8.1 - MC 1.7.10
  [📁] carpentersblocks (folder)
  [✔️] Chisel-2.9.5.11
  [✔️] CodeChickenCore-1.7.10-1.0.7.47-universal
  [✔️] CoFHCore-[1.7.10]3.1.4-329
  [✔️] CoFHLib-[1.7.10]1.2.1-185
  [✔️] ComputerCraft1.75
  [✔️] cookingbook-mc1.7.10-1.0.140
  [✔️] CraftTweaker-1.7.10-3.0.13
  [✔️] creeperhost-1.7.10-1.1.0
  [✔️] CustomMainMenu-MC1.7.10-1.9.2
  [✔️] CustomThings-MC1.7.10-0.0.3-55
  [✔️] Decocraft-2.4.2_1.7.10
  [✔️] Draconic-Evolution-1.7.10-1.0.2h
  [✔️] EnderCore-1.7.10-0.2.0.39_beta
  [✔️] EnderIO-1.7.10-2.3.0.429_beta
  [✔️] EnderStorage-1.7.10-1.4.7.37-universal
  [✔️] EnderTech-1.7.10-0.3.2.405
  [✔️] Ex-Astris-MC1.7.10-1.16-36
  [✔️] excompressum-mc1.7.10-1.1.149
  [✔️] Ex-Nihilo-1.38-53
  [✔️] ExtraCells-1.7.10-2.3.14b197
  [✔️] extrautilities-1.2.12
  [✔️] fastcraft-1.23
  [✔️] FastLeafDecay-1.7.10-1.4
  [✔️] Forbidden Magic-1.7.10-0.575
  [✔️] forestry_1.7.10-4.2.16.64
  [✔️] ftbisland-1.3.3
  [✔️] FTBLib-1.7.10-1.0.18.3
  [✔️] FTBTrophies-1.0.8_1.7.10
  [✔️] FTBUtilities-1.7.10-1.0.18.3
  [✔️] funky-locomotion-1.7.10-beta-7
  [✔️] gendustry-1.6.3.132-mc1.7.10
  [✔️] GraviSuite-1.7.10-2.0.3
  [✔️] Guide-API-1.7.10-1.0.1-20
  [✔️] HQM-The Journey-4.4.4
  [📁] ic2 (folder)
  [✔️] IC2NuclearControl-2.4.2a
  [✔️] IguanaTinkerTweaks-1.7.10-2.1.6
  [✔️] ImmersiveEngineering-0.7.7
  [✔️] immersiveintegration-0.6.8
  [✔️] industrialcraft-2-2.2.827-experimental
  [✔️] INpureCore-[1.7.10]1.0.0B9-62
  [✔️] InventoryTweaks-1.59-dev-152
  [✔️] ironchest-1.7.10-6.0.62.742-universal
  [✔️] Jabba-1.2.2_1.7.10
  [✔️] kleeslabs-mc1.7.10-1.2.9
  [✔️] Lockdown-1.7.2-2.0.0-universal
  [✔️] logisticspipes-0.9.3.132
  [✔️] magicbees-1.7.10-2.4.3
  [✔️] Mantle-1.7.10-0.3.2b
  [✔️] mcjtylib-1.8.1
  [✔️] Mercurius-1.7.10-1.0.6
  [✔️] MineFactoryReloaded-[1.7.10]2.8.1-174
  [✔️] ModTweaker2-0.9.6
  [✔️] Morpheus-1.7.10-1.6.21
  [✔️] neiaddons-1.12.14.40-mc1.7.10
  [✔️] NEIIntegration-MC1.7.10-1.1.2
  [✔️] NotEnoughItems-1.7.10-1.0.5.120-universal
  [✔️] OpenBlocks-1.7.10-1.6
  [✔️] OpenModsLib-1.7.10-0.10
  [✔️] OpenPeripheralAddons-1.7.10-0.6
  [✔️] OpenPeripheralCore-1.7.10-1.4
  [✔️] OpenPeripheralIntegration-1.7.10-0.6
  [✔️] Pam's HarvestCraft 1.7.10Lb
  [✔️] Patcher
  [✔️] ProjectRed-1.7.10-4.7.0pre12.95-Base
  [✔️] ProjectRed-1.7.10-4.7.0pre12.95-Compat
  [✔️] ProjectRed-1.7.10-4.7.0pre12.95-Integration
  [✔️] ProjectRed-1.7.10-4.7.0pre12.95-Lighting
  [✔️] ProjectRed-1.7.10-4.7.0pre12.95-Mechanical
  [✔️] ProjectRed-1.7.10-4.7.0pre12.95-World
  [📁] railcraft (folder)
  [✔️] Railcraft_1.7.10-9.12.2.0
  [✔️] RedstoneArsenal-[1.7.10]1.1.2-92
  [✔️] ResourceLoader-MC1.7.10-1.3
  [✔️] rftools-4.23
  [✔️] SimplyJetpacks-MC1.7.10-1.5.3
  [✔️] SolarExpansion-Basic-1.6a
  [✔️] StevesCarts2.0.0.b18
  [✔️] StorageDrawers-1.7.10-1.10.8
  [✔️] StorageDrawers-BiomesOPlenty-1.7.10-1.1.1
  [✔️] StorageDrawers-Forestry-1.7.10-1.1.2
  [✔️] StorageDrawers-Misc-1.7.10-1.1.2
  [✔️] StorageDrawers-Natura-1.7.10-1.1.1
  [✔️] tcinventoryscan-mc1.7.10-1.0.11
  [✔️] TConstruct-1.7.10-1.8.8
  [✔️] Thaumcraft-1.7.10-4.2.3.5
  [✔️] thaumcraftneiplugin-1.7.10-1.7a
  [✔️] thaumicenergistics-1.0.0.5
  [✔️] ThaumicExploration-1.7.10-1.1-53
  [✔️] ThaumicTinkerer-2.5-1.7.10-512
  [✔️] ThermalDynamics-[1.7.10]1.2.1-172
  [✔️] ThermalExpansion-[1.7.10]4.1.5-248
  [✔️] ThermalFoundation-[1.7.10]1.2.6-118
  [✔️] TiCTooltips-mc1.7.10-1.2.5
  [✔️] TMechworks-1.7.10-0.2.15.106
  [✔️] Waila-1.5.10_1.7.10
  [✔️] WailaHarvestability-mc1.7.10-1.1.6
  [✔️] Wawla-1.0.5.120
  [✔️] witchery-1.7.10-0.24.1
  [✔️] WR-CBE-1.7.10-1.4.1.9-universal
  [✔️] YUNoMakeGoodMap-1.7.10-4.0.0.12-universal

Params:
  --username  --version MultiMC5 --gameDir C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/instances/Sky World/.minecraft --assetsDir C:/Users/kitch/Downloads/mmc-stable-win32/MultiMC/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType  --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 7920

Using onesix launcher.

[14:31:41] [main/INFO] [bao]: Setting user: CmdrClown
[14:31:41] [main/INFO] [bao]: (Session ID is token:<ACCESS TOKEN>:<PROFILE ID>)
Completely ignored arguments: [--tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]
[14:31:41] [Client thread/INFO] [bao]: LWJGL Version: 2.9.0
[14:31:41] [Client thread/ERROR] [bao]: Couldn't set pixel format
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.0.jar:?]
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.0.jar:?]
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:244) ~[lwjgl-2.9.0.jar:?]
	at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.0.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.0.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.0.jar:?]
	at bao.ag(SourceFile:327) [minecraft-1.7.10-client.jar:?]
	at bao.f(SourceFile:713) [minecraft-1.7.10-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [minecraft-1.7.10-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 8/25/19 2:31 PM
Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:244)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at bao.ag(SourceFile:340)
	at bao.f(SourceFile:713)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:244)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at bao.ag(SourceFile:340)

-- Initialization --
Details:
Stacktrace:
	at bao.f(SourceFile:713)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 422697664 bytes (403 MB) / 514850816 bytes (491 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: MultiMC5
	LWJGL: 2.9.0
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Kitch\Downloads\mmc-stable-win32\MultiMC\instances\Sky World\.minecraft\crash-reports\crash-2019-08-25_14.31.42-client.txt
Process exited with code -1.
MultiMC: Log upload triggered at: 25 Aug 2019 14:32:12 -0500
MultiMC: Log uploaded to: https://paste.ee/p/l9Dc7

### Walk through of Error 
Launch it, but it says there is a error everytime.

**Comment by peterix** [comment]
If you use an older integrated Intel GPU (HD2000, HD3000), you will have to use an older version of Java.

Either one of those should work:
* https://files.multimc.org/downloads/jre-8u51-windows-x64.zip (64-bit)
* https://files.multimc.org/downloads/jre-8u51-windows-i586.zip (32-bit)

Download it, extract it into the MultiMC folder so it shows up like this:
![image](https://cloud.githubusercontent.com/assets/203326/24775694/31ee8d8a-1b1e-11e7-81d5-eff24add7de2.png)

Then set it up in MultiMc like this:
![image](https://cloud.githubusercontent.com/assets/203326/24775746/5c45fb22-1b1e-11e7-8615-e9ba6d667d7f.png)

Obviously only on Windows 10 :)

If you want the full background about this issue, see:
<details>
https://github.com/LWJGL/lwjgl/issues/119
https://github.com/MultiMC/MultiMC5/issues/1276 (and many other)

I tried contacting Intel about it, they said they will not fix their drivers because the hardware is unsupported on Windows 10:
http://www.intel.com/content/www/us/en/support/graphics-drivers/000005526.html
And Microsoft got an another person to boost their Windows 10 numbers, even though the hardware is not supported properly there.
</details>

**Comment by CmdrClown** [comment]
Thank you, I'll try this

**Comment by CmdrClown** [comment]
I have Java version 1.8.0_221, isn't that older than the one you gave me the link too?

**Comment by Zetabite** [comment]
You are using Windows XP. OpenGL in the newer Java version doesnt work like it does on newer systems. So if you want to make it work properly, you need older version of Java or a new OS, which might end up you needing a new PC or at least some parts.

**Comment by peterix** [comment]
You need specifically 8u51

**Comment by Zetabite** [comment]
what he says

**Comment by peterix** [comment]
To be honest, it could be all kinds of other issues, but the intel problem is most likely.
If it doesn't help, we'll need to dig deeper.

**Comment by CmdrClown** [comment]
The instance I had loaded finally ran, but the mods from the modpack weren't on it.

**Comment by Zetabite** [comment]
Can you upload the error log

**Comment by CmdrClown** [comment]
There is no error log

**Comment by CmdrClown** [comment]
The modpack I am trying to load is FTB Infinity Evolved Skyblock, by it appears as normal 1.7.10.

**Comment by peterix** [comment]
You posted the log before. Do it again :)

Also, there's an upload button. It's much more readable if you use that and post a link here, instead of copypasting text.

**Comment by CmdrClown** [comment]
You mean post the log that worked without mods?

**Comment by CmdrClown** [comment]
https://paste.ee/p/6TCfI

**Comment by peterix** [comment]
![image](https://user-images.githubusercontent.com/203326/63656296-54995b80-c792-11e9-8f5a-ab6c995b2a03.png)

This one.

**Comment by CmdrClown** [comment]
I'm fairly sure that's what I posted above what you posted.

**Comment by CmdrClown** [comment]
Do you know what the problem is?

**Comment by peterix** [comment]
No, you haven't posted the log yet.

**Comment by CmdrClown** [comment]
I found the problem, and its loading the modpack, thanks for your help!

**Comment by Zetabite** [comment]
Can you elaborate your solution. It might help other people in future.

**Comment by peterix** [comment]
Probably disabled forge.
