### ISSUE TITLE
mmc doesnt launch at all windows 10

### ISSUE THREAD

**Issue by axelaxolotl** [MultiMC/MultiMC5#2825]
System Information
-----------------------------
MultiMC version: the newest windows stable and the newest windows dev (27.08.19)

Operating System: win 10 version 1903 build 18362.295

Summary of the issue or suggestion: when running the launcher (also with compatibility settings turned on) mmc refuses to open. for a few seconds i get the loading mouse icon but after that nothing seems to happen and mmc will not open but will be listed in the task manager. the task manager will say it uses 0% cpu and 0% of my storage devices and uses 8.5mb of ram (the number gets higher with some compatibility options turned on but not by much. with win 8 compatibility it goes up to 11mb). when i kill the launcher it doesnt create any kind of crash log. 

even when i download fresh instalations of mmc the same seems to happen. the last time i used the program i properly closed it and when i wanted to reopen it, it didnt work (i didnt restart the pc) at first i thought that maybe some windows update in the backround was the issue but i have not seen anyone else complain so i thought i might be the only one or one of few getting this issue.
i love this program and i know that these are probably not enough infos for you to find the issue but i realy dont know what else i can say. if i can do anything to give you more insight into the issue just tell me and i will gladly do it.

does mmc save files anywhere else so that i could delete them?

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.start the game

2.

3.

Suspected cause:
---------------------------
windows update

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by axelaxolotl** [comment]
i fixed it by removing my veikk tablet driver. i did not change anything about it but now everything works again

**Comment by DeltaNedas** [comment]
please close

**Comment by peterix** [comment]
Please do not report bugs with Windows 10 beta versions.
