### ISSUE TITLE
I'm receiving a crash on my customized modpack

### ISSUE THREAD

**Issue by KentaroYuki** [MultiMC/MultiMC5#2826]
I downloaded the 1.7.10 Infinity Evolved modpack, and added some mods, then I openned the modpack and it worked good, then I removed some mods to make smoother to host a server to play with my friends, and my modpack is crashing everytime I try to open it. Here's the crash report: https://paste.ee/p/HCawJ
Please help me, thank you.

**Comment by Zetabite** [comment]
Which mods did you remove. Seems like one of them either managed Biomes O Plenty stuff or at least removing them changed BOP config.

**Comment by DeltaNedas** [comment]
[Client thread/ERROR] [FML]: The mcmod.info file in magicalcropsarmoury-4.0.0_PUBLIC_BETA_4.jar cannot be parsed as valid JSON.
Please read the provided log, this is nothing to do with multimc.
