### ISSUE TITLE
Originally had Java Class issues, downloaded launchwrapper 2.0, but now I'm getting an error message about "instance failed to update"

### ISSUE THREAD

**Issue by ChaseH9499** [MultiMC/MultiMC5#2827]
System Information
-----------------------------
MultiMC version: 0.6.7

Operating System: Latest MacOS

Summary of the issue or suggestion:
----------------------------------------------
I have downloaded launchwrapper 2.0 and put it into the net/minecraft/2.0 folder, but now I get this error message:
"Instance update failed because: Component metadata update task failed while downloading from remote server:
Job 'Download of meta file net.minecraft/2.0.json' failed to process:
https://meta.multimc.org/v1/net.minecraft/2.0.json"

What should happen:
------------------------------
Minecraft should launch

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------
I know Forge is a problem, because launching one without forge has been no issue. However, I have no idea why it's a problem, because my friend's game with forge launches fine even with launchwrapper 1.12.2

Beyond that, I'm clueless.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by SHIuSH** [comment]
![image](https://user-images.githubusercontent.com/10953814/63908523-a1f32280-ca49-11e9-8807-d975cfd15ac5.png)
same issue when trying to launch ATM4(1.14)

**Comment by peterix** [comment]
It's not clear what you want to do, and I will not use the slow medium of github issue comments to teach you. Please come to the discord server and talk.
