### ISSUE TITLE
 Where is the default path for Java arguments?

### ISSUE THREAD

**Issue by huangsijun17** [MultiMC/MultiMC5#2828]
I want to add some  the Java arguments.But I can only use absolute paths for jar files.

`-javaagent:"E:/Program Files/MultiMC/instances/function测试_2019-5-22/.minecraft/nide8auth.jar"=65d8d29ff84511e89250525400b59b6a`

How do I modify to use a relative path?Where is the default path？Or is there any path variable that can be used?

**Comment by Heufneutje** [comment]
What are you trying to accomplish?

**Comment by huangsijun17** [comment]
Ues Minecraft Universal Login to Login.
https://www.mcbbs.net/thread-729821-1-1.html

**Comment by huangsijun17** [comment]
I succeeded. The default path for Java arguments is minecraft PATH.

**Comment by peterix** [comment]
The answer is no.
