### ISSUE TITLE
Can't use twitch url feature

### ISSUE THREAD

**Issue by SHIuSH** [MultiMC/MultiMC5#2829]
![image](https://user-images.githubusercontent.com/10953814/63883130-a85bad00-c9fd-11e9-88cf-20b11c4b2860.png)

Am I using the wrong link(https://www.curseforge.com/minecraft/modpacks/skyfactory-4/download)?

**Comment by peterix** [comment]
Just drag and drop the install button from curseforge into the main window. It will figure it out.

**Comment by SHIuSH** [comment]
It seemed to have worked, thanks!! it pasted practically the same link but figured it out? Maybe this drag'n'drop hint should be on that empty space. Or maybe in the wiki.

**Comment by peterix** [comment]
I threw that together the same day twitch changed the design, in a few hours. It just needs some polish.

**Comment by cluekitty** [comment]
There still appears to be an issue with Twitch URLs utilizing specific versions. Running MultiMC 0.6.7-develop-1380, I am able to add Project Ozone 3 utilizing the ["latest" install url](https://www.curseforge.com/minecraft/modpacks/project-ozone-3-a-new-way-forward/download?client=y), yet when following your instructions with drag and drop for the [older version](https://www.curseforge.com/minecraft/modpacks/project-ozone-3-a-new-way-forward/download/2700945?client=y), it simply fails to recognize it as a valid download URL. This was not the case in a previous version.

I am able to replicate this with any modpack by selecting an older version of the modpack to install.

**Comment by shinji257** [comment]
I checked here and that URL seems to be working fine.  Currently on Version 0.6.7-develop-1385 on Windows 10.
![image](https://user-images.githubusercontent.com/261005/65380818-c42b3980-dcb1-11e9-8b6f-a8cba5980d4b.png)

**Comment by bamvsgame** [comment]
Twitch URL seems to be broken for me too, I get the sadface whenever I try to install from curseforge. As shinji posted above, downloading & importing manually is still working.

**Comment by wusatosi** [comment]
> Twitch URL seems to be broken for me too, I get the sadface whenever I try to install from curseforge. As shinji posted above, downloading & importing manually is still working.

me too!

**Comment by darthvader45** [comment]
Worked once for me, then broke.  No idea why it won't work anymore.  Would be nice if this were fixed so it worked reliably.

**Comment by EmberQuill** [comment]
I skimmed through the logs and it looks like whenever I click the Check button, I get a `QNetworkReply::NetworkError(ContentOperationNotPermittedError)`

**Comment by darthvader45** [comment]
That's odd, perhaps that can be fixed?

**Comment by QuaternionsRock** [comment]
The problem appears to be this: https://minecraft.curseforge.com/mc-mods/224472

Ever since Curse integrated the "Twitch-ified" version of CurseForge with the original one, it doesn't appear that mods can be accessed via ID anymore (unless I'm missing something). Either the Twitch client is passing some kind of special token or there's another URL base that is needed in order to access mods by ID. I will run a Wireshark and report back later.

**Comment by peterix** [comment]
I updated the UI to make it clearer what should work. Again, I've yet to replicate the issue.

So, please test.

**Comment by peterix** [comment]
And no, this is not for mods. Only modpacks.

**Comment by QuaternionsRock** [comment]
![2019-10-15](https://user-images.githubusercontent.com/18317512/66846577-fe4dcb00-ef3f-11e9-8583-246b4de7fc30.png)
Perhaps I'm mistaken, but the updater says I'm on the latest version and I don't see any indicator?

**Comment by peterix** [comment]
Switch to develop branch in settings.

**Comment by QuaternionsRock** [comment]
![2019-10-15 (1)](https://user-images.githubusercontent.com/18317512/66857172-b2f1e780-ef54-11e9-9c8f-096c5ed5eb2f.png)
Still no dice. Check button doesn't do anything. Strange...

**Comment by darthvader45** [comment]
Same, though I switched to the dev branch in settings, closed and restarted multimc, though no change.  Do I have to not be running an instance?

**Comment by ItsiAdam** [comment]
Upon dag and drop/check button press: https://hastebin.com/anubenicuv.js

**Comment by Rafii2198** [comment]
I tried to install FTB Academy via Twitch URL and it didn't worked (I tried it on stable and developer version of mmc) but installing form .zip worked fine.

**Comment by cmcarey** [comment]
> 
> 
> Switch to develop branch in settings.

Still an issue on the develop branch.

**Comment by torndar** [comment]
I'm running into this as well. 0.6.7-develop-1398

**Comment by Cixxar** [comment]
> I'm running into this as well. 0.6.7-develop-1398

Ive just tested and the same problem with same build on a WIN10 build

**Comment by YigitGuzel** [comment]
Still not working...

**Comment by kb-1000** [comment]
It's not multimc's fault, it's cloudflare's fault for being extremely unpredictable, for some, like for me, it works. Just download the ZIP and import it, that should work.

**Comment by YigitGuzel** [comment]
I found this video: https://www.youtube.com/watch?v=7Yx7tl2IVWg
It works!

**Comment by darthvader45** [comment]
Huh, will try it.

**Comment by jmdev91** [comment]
You don't need to mess with urls, just click the name of the zip file and it'll take you to a slightly different page with a download button next to the install button.

**Comment by darthvader45** [comment]
Yeah, I'll use that as a workaround for now.  The Twitch feature could be fixed eventually, if it can be fixed at all.

**Comment by kb-1000** [comment]
As it works for some and not for others, it's a problem with curseforge. Maybe they should allow third-party launchers to easily access mod packs (but that's incredibly unlikely)... Others have even reported that they did the exact same as the browser did with `curl` and got an error, as such, I don't think MultiMC can do anything about this.

**Comment by cfanoulis** [comment]
We might be able to work around this by using [Gaz's Twitch-like API](https://gaz492.github.io/TwitchAPI/#/get~api~v2~addon~addonid~file~fileid~download-url), but I don't think Peter would approve of this since last time I checked he's not in favour of depending on 3rd parties

**Comment by kb-1000** [comment]
I'm not sure if that's similar to that, but MultiMC already uses https://cursemeta.dries007.net/

**Comment by cfanoulis** [comment]
@kb-1000 quoting the website:
> This service is deprecated

So I'm gonna go ahead and say it's not...

**Comment by Heufneutje** [comment]
Did you also read the note below that though?

**Comment by darthvader45** [comment]
Don't think they did, but that's just me.  It says the service is kept online because MultiMC relies on it.

**Comment by cfanoulis** [comment]
@Heufneutje @darthvader45 I'm... gonna be honest, I didn't read the whole thing.

And now that I've looked into this a bit more thoroughly, the issue is on twitch and the fact that they don't include the project ID in the URL anymore

**Comment by darthvader45** [comment]
Which is a big pita.  Why would Twitch do that, if it makes it literally impossible to use third parties which are more effective?

**Comment by Zetabite** [comment]
They dont want any third Party.

**Comment by peterix** [comment]
So, this is `not working, as intended`.

**Comment by darthvader45** [comment]
And they won't approve any third party, because why?

**Comment by Zetabite** [comment]
Money

**Comment by darthvader45** [comment]
It's always greed, what else?  So in a sense, this is unfixable.  Really sucks that they gotta be so stubborn.  Maybe someone can...persuade them?

**Comment by kb-1000** [comment]
well, let's look into replacing curse then

**Comment by darthvader45** [comment]
What do you mean by that, kb?

**Comment by peterix** [comment]
Well, it worked for some subset of users.

For better twitch support, we just need a slightly better API proxy that keeps a modpack index around and updates it as needed.

**Comment by peterix** [comment]
In any case, people had too many problems with this hack. It worked for me, it worked for some other people, it definitely wasn't reliable though.

So, it's gone. A replacement that doesn't have these problems would be nice.

For now, download the zip files from curseforge and import them. MultiMC can do that, and you don't need the install buttons.

**Comment by kb-1000** [comment]
Well, like creating a true and OSS alternative to it.I've created a
project, but it's in extremely early stage and isn't public yet...

>
