### ISSUE TITLE
I'm receiving a crash on my customized modpack (repost)

### ISSUE THREAD

**Issue by KentaroYuki** [MultiMC/MultiMC5#2831]
I downloaded the 1.7.10 Infinity Evolved modpack, and added some mods, then I openned the modpack and it worked good, then I removed some mods to make smoother to host a server to play with my friends, and my modpack is crashing everytime I try to open it. Here's the crash report: https://paste.ee/p/HCawJ
Please help me, thank you.

The mods that I removed:

Blood Magic
ComputerCraft
Creeperhost
CustomMainMenu
Forbidden Magic
GraviSuite
Resource Loader
Simply Jetpacks
Springboards
Steve's Addons
Steve's Factory Manager
Steve's Workshop
Storage Drawers - Biomes O plenty
Storage Drawers - Forestry
Storage Drawers - Misc
Storage Drawers - Natura
Tcinventoryscan
Thaumcraft
Thaumcraftneiplugin
Thaumic energistics
Thaumic Equivalence
Thaumic Exploration
Thaumic Tinkerer

**Comment by Heufneutje** [comment]
Do not repost issues. It will not get people to help you any faster. In fact it'll make people less willing to help you.

**Comment by Zetabite** [comment]
Remove Biomes O Plenty and try again.

**Comment by KentaroYuki** [comment]
> Do not repost issues. It will not get people to help you any faster. In fact it'll make people less willing to help you. This is also not a MultiMC issue. If you want help with a Minecraft issues, visit the #minecraft channel in our Discord.

Yes, I already asked for someone there, but nobody answered me.

**Comment by Heufneutje** [comment]
That is still no excuse to spam the issue tracker. Keep in mind that everyone here helping does so in their own spare time.
