### ISSUE TITLE
[Suggestion] Open instance folder button on instance>version page

### ISSUE THREAD

**Issue by JosephBarker123** [MultiMC/MultiMC5#2832]
Summary of the issue or suggestion:
----------------------------------------------
On the loader mods page you can open the mods folder but there is no equivalent button on the version/jar mods page. This would be useful for installing certain mods or libraries that aren't so simple as adding a zip to the jar.

**Comment by peterix** [comment]
Fair. I also see opening/creating the per-instance libraries folder as a quite viable option here.

**Comment by peterix** [comment]
Done in develop.
