### ISSUE TITLE
Missing JSON file for Modpack 1.14.4

### ISSUE THREAD

**Issue by danielimperial** [MultiMC/MultiMC5#2834]
System Information
-----------------------------
MultiMC version: 0.6.7

Operating System: Arch Linux 4.19.66-1-MANJARO

Summary of the issue or suggestion: 
----------------------------------------------
When trying to add a Modpack into the MultiMC client, the game cannot be opened due to a missing JSON file, pointed to an inexistent address.

What should happen: 
------------------------------
The game should download the file, supposedly to patch out the forge part of the game. 

Steps to reproduce the issue:
-------------------------------------------------------------
1. Download [The Adventures of Halk 1.14.4](https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk/files/2774004) modpack.

2. Drag-and-drop the modpack into the MultiMC client to create a new instance.

3. Wait for the content to be created.

4. Double-click the instance.

Suspected cause: 
---------------------------
The file was not found in the pointed address. Tests with wget, aria2c or querying through a browser will support this cause.

Logs/Screenshots:
----------------------------
Link for the [logs](https://paste.ee/p/ouiYS)

Edit:
----------------------------
I just got aware through [this news](https://multimc.org/posts/forge-114.html) that MultiMC cannot support installations for Minecraft 1.13 or higher with Forge. However, if I'm not incorrect, it should handle a manual installation of Forge and act as a Mod Manager.
If the answer to this thread is the news post about Forge, then you can close this thread and I'm sorry about the inconvenience.

**Comment by peterix** [comment]
WAI
