### ISSUE TITLE
FTB Error will not run

### ISSUE THREAD

**Issue by shegra** [MultiMC/MultiMC5#2838]
MultiMC version: 0.6.7-1316

Minecraft folder is:
/Applications/MultiMC.app/Contents/MacOS/instances/FTB Ultimate Reloaded/.minecraft

Java path is:
/usr/bin/java

Java is version 10.0.2, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /Applications/MultiMC.app/Contents/MacOS/instances/FTB Ultimate Reloaded/natives

Libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2838/forge-1.12.2-14.23.5.2838-universal.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-osx.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar

Mods:
  [📁] 1.12 (folder)
  [✔️] Advanced Machines-61.0.1
  [✔️] Advanced Solar Panels-4.3.0
  [✔️] ae2stuff-0.7.0.4-mc1.12.2
  [✔️] AppleSkin-mc1.12-1.0.9
  [✔️] appliedenergistics2-rv6-stable-6
  [✔️] Aroma1997Core-1.12.2-2.0.0.2
  [✔️] Aroma1997s-Dimensional-World-1.12.2-2.0.0.2
  [✔️] AutoRegLib-1.3-32
  [✔️] Baubles-1.12-1.5.2
  [✔️] bdlib-1.14.3.12-mc1.12.2
  [✔️] BetterAdvancements-1.12.2-0.1.0.77
  [✔️] BiblioCraft[v2.4.5][MC1.12.2]
  [✔️] binnie-mods-1.12.2-2.5.1.188
  [✔️] blockcraftery-1.12.2-1.3.1
  [✔️] buildcraft-all-7.99.24.1
  [✔️] cc-tweaked-1.12.2-1.83.1
  [✔️] Charset-Crafting-0.5.6.0
  [✔️] Charset-Lib-0.5.6.2
  [✔️] Chisel-MC1.12.2-0.2.1.35
  [✔️] chiselsandbits-14.33
  [✔️] CodeChickenLib-1.12.2-3.2.2.353-universal
  [✔️] CoFHCore-1.12.2-4.6.3.27-universal
  [✔️] CoFHWorld-1.12.2-1.3.1.7-universal
  [✔️] CompactSolars-1.12.2-5.0.18.341-universal
  [✔️] Computronics-1.12.2-1.6.6
  [✔️] Controlling-3.0.7
  [✔️] CraftingTweaks_1.12.2-8.1.9
  [✔️] CraftTweaker2-1.12-4.1.19
  [✔️] CTM-MC1.12.2-0.3.3.22
  [✔️] CustomMainMenu-MC1.12.2-2.0.9
  [✔️] DefaultOptions_1.12.2-9.2.8
  [✔️] diethopper-1.1
  [✔️] EnderStorage-1.12.2-2.4.5.135-universal
  [✔️] energyconverters_1.12.2-1.3.0.15
  [✔️] Fancy Fluid Storage-1.12.2-2.2.5
  [✔️] FastWorkbench-1.12.2-1.7.2
  [✔️] flatcoloredblocks-mc1.12-6.8
  [✔️] foamfix-0.10.5-1.12.2
  [✔️] forestry_1.12.2-5.8.2.387
  [✔️] Forgelin-1.8.3
  [✔️] ForgeMultipart-1.12.2-2.6.1.81-universal
  [✔️] FTBLib-5.4.3.129
  [✔️] FTBUtilities-5.4.0.100
  [✔️] FTBUtilitiesBackups-1.0.0.4
  [✔️] Gravitation Suite-3.1.1
  [✔️] GravityGun-1.12.2-7.0.1
  [✔️] Guide-API-1.12-2.1.8-63
  [✔️] Harvest-1.12-1.2.7-20
  [✔️] iChunUtil-1.12.2-7.2.1
  [✔️] ImmersiveCables-1.12.2-1.3.2
  [✔️] ImmersiveEngineering-0.12-89
  [✔️] industrialcraft-2-2.8.170-ex112
  [✔️] industrialforegoing-1.12.2-1.12.13-237
  [✔️] IntegrationForegoing-1.12.2-1.9
  [✔️] InventoryTweaks-1.63
  [✔️] ironchest-1.12.2-7.0.71.846
  [✔️] jei_1.12.2-4.15.0.268
  [✔️] jeibees-0.9.0.5-mc1.12.2
  [✔️] jeiintegration_1.12.2-1.5.1.36
  [✔️] JustEnoughEnergistics-1.12.2-1.0.7
  [✔️] longfallboots-1.2.1b
  [✔️] MagicBees-1.12.2-3.1.10
  [✔️] MCMultiPart-2.5.3
  [📁] memory_repo (folder)
  [✔️] MFFS-1.12.2-4.0.1.0_1.12_cc3a5aa
  [✔️] minetogether-1.10.2-2.1.3
  [✔️] modnametooltip_1.12.2-1.10.1
  [✔️] modtweaker-4.0.17
  [✔️] modular-routers-1.12.2-3.2.2
  [✔️] ModularPowersuits-1.12.2-1.0.46
  [✔️] moreoverlays-1.15.1-mc1.12.2
  [✔️] Morph-o-Tool-1.2-21
  [✔️] Morpheus-1.12.2-3.5.106
  [✔️] MouseTweaks-2.10-mc1.12.2
  [✔️] MrTJPCore-1.12.2-2.1.4.43-universal
  [✔️] MTLib-3.0.6
  [✔️] mysticallib-1.12.2-1.3.1
  [✔️] Netherending-Ores-1.12.2-1.3
  [✔️] Numina-1.12.2-1.0.38
  [✔️] PeripheralsPlusOne-1.12.2-1.1-build-T58
  [✔️] Placebo-1.12.2-1.6.0
  [✔️] playerplates-1.12.2-1.3.1.1
  [✔️] plethora-1.12.2-1.2.2
  [✔️] PortalGun-1.12.2-7.1.0
  [✔️] ProjectRed-1.12.2-4.9.4.120-Base
  [✔️] ProjectRed-1.12.2-4.9.4.120-compat
  [✔️] ProjectRed-1.12.2-4.9.4.120-fabrication
  [✔️] ProjectRed-1.12.2-4.9.4.120-integration
  [✔️] ProjectRed-1.12.2-4.9.4.120-lighting
  [✔️] ProjectRed-1.12.2-4.9.4.120-mechanical
  [✔️] ProjectRed-1.12.2-4.9.4.120-world
  [✔️] ProjectX-1.12.2-2.2.7-universal
  [📁] railcraft (folder)
  [✔️] railcraft-12.0.0
  [✔️] randompatches-1.12.2-1.17.2.1
  [✔️] reauth-3.6.0
  [✔️] RebornCore-1.12.2-3.14.1.457-universal
  [✔️] RedstoneFlux-1.12-2.1.0.6-universal
  [✔️] Reliquary-1.12.2-1.3.4.786
  [✔️] ResourceLoader-MC1.12.1-1.5.3
  [✔️] Retro-Exchange-1.12.2-1.0.7
  [✔️] Silverfish-1.12.2-0.0.19-universal
  [✔️] SimpleCorn1.12-1.12-2.5.10
  [✔️] SmoothFont-mc1.12.2-2.1
  [✔️] SoulShardsRespawn-1.12.2-1.1.1-13
  [✔️] SplashAnimation-0.2.1
  [✔️] StevesCarts-1.12.2-2.4.31.135
  [✔️] TechReborn-1.12.2-2.23.1.1003-universal
  [✔️] tesla-core-lib-1.12.2-1.0.15
  [✔️] Thaumcraft-1.12.2-6.1.BETA26
  [✔️] thaumicenergistics-2.2.2
  [✔️] ThaumicInventoryScanning_1.12.2-2.0.10
  [✔️] ThaumicJEI-1.12.2-1.6.0-27
  [✔️] thaumictinkerer-1.12.2-5.0-353c71c
  [✔️] TheFramework-1.12.2-1.0.1-build-T23
  [✔️] theoneprobe-1.12-1.4.28
  [✔️] ThermalDynamics-1.12.2-2.5.5.21-universal
  [✔️] ThermalExpansion-1.12.2-5.5.4.43-universal
  [✔️] ThermalFoundation-1.12.2-2.6.3.27-universal
  [✔️] TipTheScales-1.12.2-1.0.4
  [✔️] Toast Control-1.12.2-1.8.1
  [✔️] topaddons-1.12.2-1.11.0
  [✔️] torchmaster_1.12.2-1.7.1.74
  [✔️] Traverse-1.12.2-1.6.0-69
  [✔️] twilightforest-1.12.2-3.8.689-universal
  [✔️] UniDict-1.12.2-2.9.2
  [✔️] WanionLib-1.12.2-2.2
  [✔️] WorldControl-1.0.31
  [✔️] WR-CBE-1.12.2-2.3.1.30-universal
  [✔️] Xaeros_Minimap_1.17.4_Forge_1.12
  [✔️] XaerosWorldMap_1.4.3_Forge_1.12
  [✔️] YABBA-1.1.2.53

Params:
  --username  --version MultiMC5 --gameDir /Applications/MultiMC.app/Contents/MacOS/instances/FTB Ultimate Reloaded/.minecraft --assetsDir /Applications/MultiMC.app/Contents/MacOS/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: FTB Ultimate Reloaded", -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 31899

Using onesix launcher.

Failed to start Minecraft:
Exiting with -1
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Process exited with code 255.

---------------------------------------
I am trying to get FTB to work on a mac mini late 2012

**Comment by DeltaNedas** [comment]
minecraft uses java 8, download java 8u221 and use it instead

**Comment by DeltaNedas** [comment]
please close
