### ISSUE TITLE
Suggestion: Remove "Username" wording from "Add Account" dialog box due to Mojang account change

### ISSUE THREAD

**Issue by Carnaxus** [MultiMC/MultiMC5#2839]
**MultiMC version:** 0.6.7 - 1375

**Operating System:** Windows 10

**Summary of the issue or suggestion:** Mojang changed the Minecraft account system to only use email addresses, not usernames.  I can't login using "Carnaxus" anymore, even through MultiMC.  However, the "Add Account" dialog box still says "Username/Email."  That should probably be changed to just say "Email," since that's the only thing that works now.

**Comment by peterix** [comment]
Done.
