### ISSUE TITLE
FTB Interactions crashes while loading with exit code 9

### ISSUE THREAD

**Issue by Rolodophone** [MultiMC/MultiMC5#2840]
System Information
-----------------------------
MultiMC version:0.6.7-1290

Operating System:Manjaro Linux

Summary of the issue or suggestion:
----------------------------------------------
FTB Interactions crashes while loading with exit code 9

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
Launch a fresh FTB Interactions instance with 2GB min RAM and 4GB max RAM

Suspected cause:
---------------------------
Perhaps Java cannot allocate all the 4GB as other processes are using too much RAM. This was the error I got when I tried with the FTB Launcher. However the system monitor tells me I'm using 2.0GB without Minecraft, and I've got 7.8GB available RAM so allocating max 4GB to MC should be fine.

It seems to crash at varying stages of the loading process, so I don't think it's an issue with the pack.

However, it always ends with `Process crashed with exitcode 9`

Logs/Screenshots:
----------------------------
[https://paste.ee/p/duq9A](https://paste.ee/p/duq9A)

Additional Info:
---------------------------
Vanilla Minecraft using the normal launcher works fine.

**Comment by Janrupf** [comment]
Thats like super weird. But you are right, `9` = `SIGKILL`, so something is shooting down that process.
Maybe `dmesg` or something tells you whats wrong?

Try these commands to start of with:
`grep -i 'killed process' /var/log/messages`
`dmesg | egrep -i 'killed process'`

**Comment by Rolodophone** [comment]
I just tried it again today with 6GB max RAM, and it loaded this time, however I could see that it could only allocate up to 3GB, and it was really slow. I think I need more RAM.

**Comment by Rolodophone** [comment]
Yep, I just installed some more RAM and now it works fine

**Comment by jddicaro** [comment]
> Yep, I just installed some more RAM and now it works fine

Ouch my laptop is stuck with 8g
