### ISSUE TITLE
Cannot load modpack

### ISSUE THREAD

**Issue by aidensmartin** [MultiMC/MultiMC5#2841]
System Information
-----------------------------
MultiMC version: 0.6.7

Operating System: Win64x

Summary of the issue or suggestion:
----------------------------------------------
MultiMC version: 0.6.7-1375

Minecraft folder is:
C:/Users/aiden/Downloads/mmc-stable-win32/MultiMC/instances/The-Adventures-of-Halk-0.71/minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 1.8.0_221, using 64-bit architecture.

Instance update failed because: Component metadata update task failed while downloading from remote server:

Job 'Download of meta file net.minecraftforge/28.0.55.json' failed to process:
https://meta.multimc.org/v1/net.minecraftforge/28.0.55.json

MultiMC: Log upload triggered at: 06 Sep 2019 14:48:46 -0400

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by DeltaNedas** [comment]
you cannot use 1.13+ forge, see pinned issues.
for fabric, i dont know the modloader id in manifest.json to use.

**Comment by aidensmartin** [comment]
> you cannot use 1.13+ forge, see pinned issues.
> for fabric, i dont know the modloader id in manifest.json to use.

I'm very new to this so what do I need to do?

**Comment by DeltaNedas** [comment]
you use 1.12.2, get lexmanos to make forge not a wizard installer or use
fabric if possible
