### ISSUE TITLE
Missing JSON File

### ISSUE THREAD

**Issue by cosmokid** [MultiMC/MultiMC5#2842]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------
Component metadata update task failed while downloading from remote server

What should happen:
------------------------------
It should launch the game.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add the Twitch URL to download modpack

2. Select java version

3. Run game

Suspected cause:
---------------------------
Well, the JSON points to a URL that doesn't exist. ( https://meta.multimc.org/v1/net.minecraftforge/28.0.55.json )

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Screenshot: https://images2.imgbox.com/37/cd/ro6RCVjt_o.png

Additional Info:
---------------------------
```
Instance update failed because: Component metadata update task failed while downloading from remote server:
Job 'Download of meta file net.minecraftforge/28.0.55.json' failed to process:
https://meta.multimc.org/v1/net.minecraftforge/28.0.55.json
```

**Comment by Heufneutje** [comment]
MultiMC can't use Forge 1.13+ versions. 

For more details go [here](https://github.com/MultiMC/MultiMC5/issues/2544)

**Comment by cosmokid** [comment]
> MultiMC can't use Forge 1.13+ versions.
> 
> For more details go [here](https://github.com/MultiMC/MultiMC5/issues/2544)

Oh. How can I download and use that modpack then?

**Comment by peterix** [comment]
Probably with something else.

**Comment by CryoRenegade** [comment]
Twitch Launcher is another way

**Comment by peterix** [comment]
Never.
