### ISSUE TITLE
Keyboard key mapping wrong (English)

### ISSUE THREAD

**Issue by bigtimeweenfan** [MultiMC/MultiMC5#2847]
System Information
-----------------------------
MultiMC version: 0.6.7 (used most recent stable debian package)

Operating System: Ubuntu 16.04 (updated as of 9/14)

Summary of the issue or suggestion:
----------------------------------------------
The keyboard mapping is off. For example when I press the S key I get a B printed on the screen. It's like this for a lot of keys. This happens on any dialog box I enter text in. Everywhere else in the OS the keys are fine.

What should happen:
------------------------------
Press S and see S when I type anywhere within MultiMC5

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Press S (or any key) anywhere within a text field in MultiMC5

2.

3.

Suspected cause:
---------------------------
I selected English as the language, maybe it has to do with the english language package.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Janrupf** [comment]
Sounds like a Qt issue. Try deleting the files which don't start with `libMultiMC_` in `~/.local/share/multimc/bin`

**Comment by peterix** [comment]
What Jan said, also, current version isn't shipped with Qt anymore, so... yeah.
