### ISSUE TITLE
Modpacks wont work, keeps instantly crashing

### ISSUE THREAD

**Issue by TreeHead04** [MultiMC/MultiMC5#2850]
System Information

MacBook Pro (retina, 13-inch, Early 2015)
Processor 2.1 GHz Intel Core i5
Memory 8 GB 1867 MHz DDR3
Graphics Intel Iris Graphics 6100 1536 MB

MultiMC version:
MultiMC 5 - Version o.6.7 - develop - 1322 on osx64

Summary of the issue or suggestion:
When I try to play my modpacks they instantly crash. i've tried developer mode and updating but nothing.

What should happen:
I should be able to play my modpacks

Steps to reproduce the issue (Add more if needed):
1. Launch MultiMC
2. startup Modpack
3. Modpack Crashes

Suspected cause: RAM maybe im not sure

Logs/Screenshots:
MultiMC version: 0.6.7-develop-1322

Minecraft folder is:
/Applications/MultiMC.app/Contents/MacOS/instances/All-the-Mods-3-v5.12.3/minecraft

Java path is:
/usr/bin/java

Java is version 12.0.2, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /Applications/MultiMC.app/Contents/MacOS/instances/All-the-Mods-3-v5.12.3/natives

Libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2838/forge-1.12.2-14.23.5.2838-universal.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-osx.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar

Mods:
  [✔️] AbyssalCraft Integration-1.12.2-1.9.0
  [✔️] AbyssalCraft-1.12.2-1.9.10
  [✔️] ActuallyAdditions-1.12.2-r149
  [✔️] ActuallyBaubles-1.12-1.1
  [✔️] AdditionalBanners-1.12.2-1.1.76
  [✔️] AdvancedRocketry-1.12.2-1.6.0-160-universal
  [✔️] ae2stuff-0.7.0.4-mc1.12.2
  [✔️] AE2WTLib-1.12.2-1.0.30
  [✔️] AIImprovements-1.12.1-0.0.1b1
  [✔️] AkashicTome-1.2-12
  [✔️] angelRingToBauble-1.12-0.3.1.50+d4e654e
  [✔️] AppleCore-mc1.12.2-3.2.0
  [✔️] AppleSkin-mc1.12-1.0.9
  [✔️] appliedenergistics2-rv6-stable-7
  [✔️] armoryexpansion-1.3.1
  [✔️] Aroma1997Core-1.12.2-2.0.0.2.b165
  [✔️] Aroma1997s-Dimensional-World-1.12.2-2.0.0.2
  [✔️] astralsorcery-1.12.2-1.10.19
  [✔️] atmtweaks-1.2
  [✔️] AutoRegLib-1.3-32
  [✔️] badwithernocookiereloaded-1.12.2-3.3.16
  [✔️] Baubles-1.12-1.5.2
  [✔️] bdlib-1.14.3.12-mc1.12.2
  [✔️] bedpatch-2.2-1.12.2
  [✔️] BetterAdvancements-1.12.2-0.1.0.77
  [✔️] BetterBuildersWands-1.12-0.11.1.245+69d0d70
  [✔️] BetterFps-1.4.8
  [✔️] BiblioCraft[v2.4.5][MC1.12.2]
  [✔️] binnie-mods-1.12.2-2.5.1.188
  [✔️] BiomesOPlenty-1.12.2-7.0.1.2439-universal
  [✔️] blockcraftery-1.12.2-1.3.1
  [✔️] BloodMagic-1.12.2-2.4.1-103
  [✔️] Bookshelf-1.12.2-2.3.585
  [✔️] Botania r1.10-361
  [✔️] BrandonsCore-1.12.2-2.4.17.208-universal
  [✔️] careerbees-0.4.0
  [✔️] Ceramics-1.12-1.3.7
  [✔️] Chameleon-1.12-4.1.3
  [✔️] Chisel-MC1.12.2-0.2.1.35
  [✔️] chiselsandbits-14.33
  [✔️] CodeChickenLib-1.12.2-3.2.2.353-universal
  [✔️] CoFHCore-1.12.2-4.6.3.27-universal
  [✔️] CoFHWorld-1.12.2-1.3.1.7-universal
  [✔️] ColossalChests-1.12.2-1.7.3
  [✔️] CommonCapabilities-1.12.2-2.4.4
  [✔️] compactmachines3-1.12.2-3.0.18-b278
  [✔️] CompactSolars-1.12.2-5.0.18.341-universal
  [✔️] compatlayer-1.11.2-0.3.0
  [✔️] ComputerCraft1.80pr1
  [✔️] Computronics-1.12.2-1.6.6
  [✔️] conarm-1.12.2-1.2.4
  [✔️] Controlling-3.0.7
  [✔️] CookingForBlockheads_1.12.2-6.4.71
  [✔️] CosmeticArmorReworked-1.12.2-v4a
  [✔️] CraftingTweaks_1.12.2-8.1.9
  [✔️] CraftTweaker2-1.12-4.1.19
  [✔️] CTM-MC1.12.2-0.3.3.22
  [✔️] Cucumber-1.12.2-1.1.3
  [✔️] CustomBackgrounds-MC1.12-1.1.1
  [✔️] CustomMainMenu-MC1.12.2-2.0.9
  [✔️] Cyclic-1.12.2-1.19.13
  [✔️] CyclopsCore-1.12.2-1.4.0
  [✔️] DarkUtils-1.12.2-1.8.226
  [✔️] DefaultOptions_1.12.2-9.2.8
  [✔️] DefaultWorldGenerator-port-1.12-2.3
  [✔️] diethopper-1.1
  [✔️] Ding-1.12.1-1.0.1
  [✔️] DiscordSuite-2.2.4
  [✔️] dl_overrides
  [✔️] DoomlikeDungeons-1.12.5-MC1.12.2
  [✔️] Draconic-Evolution-1.12.2-2.3.23.345-universal
  [✔️] EmbersRekindled-1.13-hotfix2
  [✔️] EnderCore-1.12.2-0.5.59
  [✔️] EnderIO-1.12.2-5.0.46
  [✔️] EnderStorage-1.12.2-2.4.5.135-universal
  [✔️] environmentaltech-1.12.2-2.0.20.1
  [✔️] Exchangers-1.12.2-2.8
  [✔️] EXCore-2.0.0-beta19-1.12.2
  [✔️] ExtraCells-1.12.2-2.6.2a
  [✔️] ExtraRails-1.12-1.3.0
  [✔️] extrautils2-1.12-1.9.9
  [✔️] ExtremeReactors-1.12.2-0.4.5.67
  [✔️] fairylights-2.1.9-1.12.2
  [✔️] FastWorkbench-1.12.2-1.7.2
  [✔️] fencejumper-1.12-1.0.5
  [✔️] Flamingo-1.12-v1.11
  [✔️] flatcoloredblocks-mc1.12-6.8
  [✔️] foamfix-0.10.5-1.12.2
  [✔️] forestry_1.12.2-5.8.2.387
  [✔️] Forgelin-1.8.3
  [✔️] ForgeMultipart-1.12.2-2.6.1.81-universal
  [✔️] FTBLib-5.4.3.130
  [✔️] FTBUtilities-5.4.0.100
  [✔️] FTBUtilitiesBackups-1.0.0.5
  [✔️] funky-locomotion-1.12.2-1.1.2
  [✔️] gendustry-1.6.5.8-mc1.12.2
  [✔️] generators-0.9.20.12-mc1.12.2
  [✔️] Guide-API-1.12-2.1.8-63
  [✔️] Guidebook-1.12.2-2.9.2
  [✔️] HelpFixer-1.12.1-1.5.18
  [✔️] iChunUtil-1.12.2-7.2.1
  [✔️] ImmersiveEngineering-0.12-89
  [✔️] immersivepetroleum-1.12.2-1.1.9
  [✔️] immersivetech-1.12-1.3.10
  [✔️] industrialcraft-2-2.8.170-ex112
  [✔️] industrialforegoing-1.12.2-1.12.13-237
  [✔️] IndustrialWires-1.7-36
  [✔️] InitialInventory-3.0.0
  [✔️] IntegratedDynamics-1.12.2-1.0.17
  [✔️] IntegratedTunnels-1.12.2-1.6.10
  [✔️] IntegrationForegoing-1.12.2-1.9
  [✔️] inventorygenerators-1.2.2
  [✔️] InventoryTweaks-1.64+dev.146
  [✔️] IronBackpacks-1.12.2-3.0.8-12
  [✔️] ironchest-1.12.2-7.0.72.847
  [✔️] JAOPCA-1.12.2-2.2.8.103
  [✔️] JAOPCAAdditions-1.12.2-2.2.1.9
  [✔️] jei_1.12.2-4.15.0.287
  [✔️] jeibees-0.9.0.5-mc1.12.2
  [✔️] jeiintegration_1.12.2-1.5.1.36
  [✔️] journeymap-1.12.2-5.5.5b9
  [✔️] justenoughdimensions-1.12.2-1.6.0-dev.20190711.220109
  [✔️] JustEnoughResources-1.12.2-0.9.2.60
  [✔️] kjlib-1.0.4
  [✔️] KleeSlabs_1.12.2-5.4.12
  [✔️] librarianlib-1.12.2-4.19.2-release
  [✔️] LibVulpes-1.12.2-0.4.1-60-universal
  [✔️] lostcities-1.12-2.0.21
  [✔️] lostsouls-1.12-1.1.4
  [✔️] LunatriusCore-1.12.2-1.2.0.42-universal
  [✔️] MagicalPsi-1.3.2
  [✔️] MagicBees-1.12.2-3.1.10
  [✔️] malisiscore-1.12.2-6.5.1
  [✔️] malisisdoors-1.12.2-7.3.0
  [✔️] Mantle-1.12-1.3.3.55
  [✔️] mcjtylib-1.12-3.5.4
  [✔️] MCMultiPart-2.5.3
  [✔️] Mekanism-1.12.2-9.8.0.381
  [✔️] MekanismGenerators-1.12.2-9.8.0.381
  [✔️] MekanismTools-1.12.2-9.8.0.381
  [✔️] minecolonies-1.12.2-0.10.341-ALPHA-universal
  [✔️] mobtotems-1.12.1-0.3.0
  [✔️] modnametooltip_1.12.2-1.10.1
  [✔️] Modpack Configuration Checker-1.12.2-v1.8.1
  [✔️] modtweaker-4.0.17
  [✔️] moreoverlays-1.15.1-mc1.12.2
  [✔️] Morph-o-Tool-1.2-21
  [✔️] Morpheus-1.12.2-3.5.106
  [✔️] MouseTweaks-2.10-mc1.12.2
  [✔️] MrTJPCore-1.12.2-2.1.4.43-universal
  [✔️] MTLib-3.0.6
  [✔️] MysticalAgradditions-1.12.2-1.3.2
  [✔️] MysticalAgriculture-1.12.2-1.7.5
  [✔️] mysticallib-1.12.2-1.3.1
  [✔️] MysticWorld-1.12.2-1.3.2
  [✔️] natura-1.12.2-4.3.2.69
  [✔️] NaturesCompass-1.12.2-1.5.1
  [✔️] NoMobSpawningOnTrees-1.2.2-mc1.12.2
  [✔️] NoNVFlash-1.12.2-1.2.0.3-universal
  [✔️] NotEnoughIDs-1.5.4.4
  [✔️] notenoughwands-1.12-1.8.1
  [✔️] NuclearCraft-2.15-1.12.2
  [✔️] Nutrition-1.12.2-4.4.0
  [✔️] ocxnetdriver-1.0.3-b17
  [✔️] oeintegration-2.3.4
  [✔️] OpenBlocks-1.12.2-1.8.1
  [✔️] OpenComputers-MC1.12.2-1.7.4.153
  [✔️] OpenModsLib-1.12.2-0.12.2
  [✔️] OreExcavation-1.4.140
  [✔️] Overloaded-1.12.2-0.0.58
  [✔️] override_mods
  [✔️] p455w0rdslib-1.12.2-2.2.156
  [✔️] packcrashinfo-1.0.1
  [✔️] packmode-1.12.2-1.2.0
  [✔️] Pam's HarvestCraft 1.12.2zd Surprise for Yogcast
  [✔️] pamscookables-1.1
  [✔️] parry-1.0-hotfix
  [✔️] Patchouli-1.0-20
  [✔️] Placebo-1.12.2-1.6.0
  [✔️] Plants-1.12.2-2.10.7
  [✔️] platforms-1.12.0-1.4.6
  [✔️] plustic-7.1.0.0
  [✔️] pneumaticcraft-repressurized-1.12.2-0.11.4-368
  [✔️] PortalGun-1.12.2-7.1.0
  [✔️] portality-1.12.2-1.2.3-15
  [✔️] practicallogistics2-1.12.2-3.0.8-11
  [✔️] pressure-1.3.1.9-mc1.12.2
  [✔️] ProjectIntelligence-1.12.2-1.0.7.24-universal
  [✔️] ProjectRed-1.12.2-4.9.4.120-Base
  [✔️] ProjectRed-1.12.2-4.9.4.120-compat
  [✔️] ProjectRed-1.12.2-4.9.4.120-fabrication
  [✔️] ProjectRed-1.12.2-4.9.4.120-integration
  [✔️] ProjectRed-1.12.2-4.9.4.120-lighting
  [✔️] ProjectRed-1.12.2-4.9.4.120-mechanical
  [✔️] ProjectRed-1.12.2-4.9.4.120-world
  [✔️] Psi-r1.1-77
  [✔️] QuantumStorage-1.12-4.6.8
  [✔️] Quark-r1.5-168
  [✔️] QuickLeafDecay-MC1.12.1-1.2.4
  [✔️] randompatches-1.12.2-1.17.2.1
  [✔️] rangedpumps-0.5
  [✔️] realfilingcabinet-1.12-0.2.0.15
  [✔️] reauth-3.6.0
  [✔️] RebornCore-1.12.2-3.14.1.457-universal
  [✔️] RebornStorage-1.12.2-3.3.4.85
  [✔️] RedstoneArsenal-1.12.2-2.6.3.18-universal
  [✔️] RedstoneFlux-1.12-2.1.0.6-universal
  [✔️] refinedstorage-1.6.15
  [✔️] refinedstorageaddons-0.4.4
  [✔️] Reliquary-1.12.2-1.3.4.786
  [✔️] ResourceLoader-MC1.12.1-1.5.3
  [✔️] rftools-1.12-7.72
  [✔️] rftoolsctrl-1.12-2.0.2
  [✔️] rftoolsdim-1.12-5.71
  [✔️] rftoolspower-1.12-1.2.0
  [✔️] Roots-1.12.2-3.0.4
  [✔️] rustic-1.1.1
  [✔️] SBM-WoodenShears-1.12-0.0.1b8
  [✔️] ShadowMC-1.12-3.8.0
  [✔️] shetiphiancore-1.12.0-3.5.9
  [✔️] SimplyJetpacks2-1.12.2-2.2.12.65
  [✔️] SlimyBoyos-1.0.0
  [✔️] sonarcore-1.12.2-5.0.19-20
  [✔️] SoulShards-TOW-1.12-2.7.6-56
  [✔️] StevesCarts-1.12.2-2.4.31.135
  [✔️] StorageDrawers-1.12.2-5.3.8
  [✔️] StorageDrawersExtras-1.12-3.1.0
  [✔️] TConstruct-1.12.2-2.12.0.157
  [✔️] TechReborn-1.12.2-2.23.2.1007-universal
  [✔️] terraqueous-1.12.2-1.4.17b
  [✔️] tesla-core-lib-1.12.2-1.0.15
  [✔️] Thaumcraft-1.12.2-6.1.BETA26
  [✔️] ThaumicInventoryScanning_1.12.2-2.0.10
  [✔️] ThaumicJEI-1.12.2-1.6.0-27
  [✔️] TheBetweenlands-3.4.10-universal
  [✔️] theoneprobe-1.12-1.4.28
  [✔️] ThermalCultivation-1.12.2-0.3.3.12-universal
  [✔️] ThermalDynamics-1.12.2-2.5.5.21-universal
  [✔️] ThermalExpansion-1.12.2-5.5.4.43-universal
  [✔️] ThermalFoundation-1.12.2-2.6.3.27-universal
  [✔️] ThermalInnovation-1.12.2-0.3.3.12-universal
  [✔️] tinker_io-1.12.2-rw2.7.1
  [✔️] TinkerToolLeveling-1.12.2-1.1.0
  [✔️] Toast Control-1.12.2-1.8.1
  [✔️] TombManyGraves-1.12-4.2.0
  [✔️] tombmanygraves2api-1.12.2-1.0.0
  [✔️] topaddons-1.12.2-1.11.0
  [✔️] Traverse-1.12.2-1.6.0-69
  [✔️] twilightforest-1.12.2-3.8.689-universal
  [✔️] UniDict-1.12.2-2.9.2
  [✔️] unloader-1.2.0
  [✔️] usefulnullifiers-1.5.0
  [✔️] valkyrielib-1.12.2-2.0.20.1
  [✔️] WAIM-1.0.0
  [✔️] WanionLib-1.12.2-2.2
  [✔️] WaterStrainer-1.12-3.2.0
  [✔️] Waystones_1.12.2-4.0.72
  [✔️] WirelessCharger-1.12.2-1.0.6
  [✔️] WirelessCraftingTerminal-1.12.2-3.12.93
  [✔️] wizardry-0.10.8
  [✔️] woot-1.12.2-1.4.11
  [✔️] WrapUp-1.12-1.1.3
  [✔️] xnet-1.12-1.8.2
  [✔️] Xtones-1.12-1.0.8-11
  [✔️] YNot-0.2.4
  [✔️] zerocore-1.12.2-0.1.2.8

Params:
  --username  --version MultiMC5 --gameDir /Applications/MultiMC.app/Contents/MacOS/instances/All-the-Mods-3-v5.12.3/minecraft --assetsDir /Applications/MultiMC.app/Contents/MacOS/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: All+the+Mods+3-v5.12.3", -Xms4480m, -Xmx5760m, -Duser.language=en]

Minecraft process ID: 42867

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code 255.
Clipboard copy at: 15 Sep 2019 21:23:10 -0700

**Comment by wlhlm** [comment]
> Java is version 12.0.2, using 64-bit architecture.

You need Java 8 when playing mod packs.

See #2808 for some more information.

**Comment by TreeHead04** [comment]
Worked like a charm thanks!
