### ISSUE TITLE
MultiMC not working w/ OptiFine

### ISSUE THREAD

**Issue by ArcticFox3107** [MultiMC/MultiMC5#2851]
System Information
-----------------------------
MultiMC version: 0.6.7-1375

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Even with the correct compatibility fixes, Minecraft will not work with OptiFine as "files are missing"

What should happen:
------------------------------
Minecraft should launch with OptiFine

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
Can't think of any

Suspected cause:
---------------------------
Having MultiMC on an external disk

Logs/Screenshots:
----------------------------
https://paste.ee/p/YYC9G

Additional Info:
---------------------------
OptiFine version JSON: https://paste.ee/p/sxvyC

**Comment by tehbasshunter** [comment]
Optifine and anything newer than 1.12.2 is a handful. Not quite sure where you might've messed up but if it's strictly for optifine use fabric and optifabric.

**Comment by ChipWolf** [comment]
Can you screenshot your S:/Programy/MultiMC/instances/1.14.4/libraries/ folder?

**Comment by shinji257** [comment]
The JSON looks fine.  As ChipWolf already mentioned make sure that the OptiFine jar file is in the libraries folder for the instance in question.  Note the folder may not already be there.  The quickest way to the right spot is to right click the instance icon and click Minecraft folder.  If there isn't a libraries folder along with .minecraft and patches then create it.  Put the jar file in there.

I do know it works.  It was one of the first things I did before using OptiFabric instead.
