### ISSUE TITLE
MultiMC MAC OS X. Won't start FTB Interactions 1.12 and others

### ISSUE THREAD

**Issue by cirrussecure** [MultiMC/MultiMC5#2852]
System Information
-----------------------------
MultiMC version:
0.6.7-1316

Operating System:
mac OS Mojave 10.14.5
2.2 GHz i7, 8GB, SS drive, Intel graphics 6000

Summary of the issue or suggestion:
----------------------------------------------
I can successfully launch vanilla 1.12 and 1.14.

What should happen:
------------------------------
I should be able to launch an instance on MMC's supplied FTB list.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. New instance.

2. FTB Interactions

3. Launch

4. See additional info below.

5. After closing launch window, screen goes black til MultiMC in dock is clicked. This seems to happen even after a successful launch.

Suspected cause:
---------------------------
No ideas.

Logs/Screenshots:
----------------------------
See attachment and additional info.

[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------MultiMC version: 0.6.7-1316
![Screen Shot 2019-09-16 at 9 07 58 AM](https://user-images.githubusercontent.com/50553435/64960722-d9dbd180-d861-11e9-968d-75d8b28de937.png)
![Screen Shot 2019-09-16 at 9 09 14 AM](https://user-images.githubusercontent.com/50553435/64960727-dd6f5880-d861-11e9-9628-b8ce3763d8ff.png)

Minecraft folder is:
/Applications/MultiMC.app/Contents/MacOS/instances/FTB Interactions/.minecraft

Java path is:
/usr/bin/java

Java is version 12.0.2, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /Applications/MultiMC.app/Contents/MacOS/instances/FTB Interactions/natives

Libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar

...

Native libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-osx.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar

Mods:
  [📁] 1.12 (folder)
  [✔️] ActuallyAdditions-1.12.2-r148
  [✔️] ActuallyBaubles-1.12-1.1

...
  [✔️] Zen Triggers-1.12-1.0.9
  [✔️] zenstages-0.4.1-19

Params:
  --username  --version MultiMC5 --gameDir /Applications/MultiMC.app/Contents/MacOS/instances/FTB Interactions/.minecraft --assetsDir /Applications/MultiMC.app/Contents/MacOS/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: FTB Interactions", -Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 14934

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code 255.
MultiMC: Log upload triggered at: 16 Sep 2019 00:11:40 -0400
MultiMC: Log uploaded to: https://paste.ee/p/0XlVy

**Comment by tehbasshunter** [comment]
You need Java 8. Anything higher will not work with anything beyond vanilla.

**Comment by cirrussecure** [comment]
I happen to have Anaconda installed. I used it to install openjdk 1.8.0_152-release using 'conda install -c anaconda openjdk'. Things seem to working now although after closing the launch window, the screen still goes black til MultiMC icon in the dock is clicked. 

I don't remember seeing anything in my search results or in MultiMC or its site about this. I wasted a lot of time tracking it down. Wouldn't it be easier explaining to folks how to get it from https://openjdk.java.net or via brew? Would the Java included with Minecraft itself work? Or better yet include Java 8 with MultiMC.

**Comment by Janrupf** [comment]
The problem here is that MultiMC is not really responsible for what forge messes up.
And including Java in MultiMC leads to license issues and portability issues. You can however still extract a Java installation into your MultiMC folder and MultiMC wont touch it. (I know thats not what you asked for, but its a way of making sure that your system Java is not gonna do bad things)

**Comment by cirrussecure** [comment]
Let's not talk about Forge. They, like MS Studios(was Mojang), do what they want and will continue to. If  MS were committed to a non-subscription version of Minecraft, they would have come up with a better multi platform way to deploy and mod it long ago.

I'm talking about a Minecraft that:
-  moves beyond Java
- we pay for once,
- runs on our personal desktop or laptop
- provides a much improved, open, and free mod'ing API to developers. 
 
If and until that happens MultiMC will remain a much needed and well crafted tool for the MC community. As I mentioned above, the MultiMC team would do new users a big favor by making it clear that they need to install Java 8 (via openjdk) and how to do so.

**Comment by peterix** [comment]
Couldn't agree more.

**Comment by peterix** [comment]
Anyway, added https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java

And I'm taking this as an another vote for us to distribute a sensible version of Java (latest build of 8).
