### ISSUE TITLE
Category collapses when clicking on visible instance, after having collapsed other category

### ISSUE THREAD

**Issue by mstiller7** [MultiMC/MultiMC5#2853]
System Information
-----------------------------
MultiMC version: 0.6.7-develop-1381 on win32

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
After collapsing one category, when clicking on a visible instance, that instance's category also collapses.

What should happen:
------------------------------
The instance's category probably should not collapse when simply clicked on.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Click the "collapse" icon in a category title.

2. Click any other visible instance.

Suspected cause:
---------------------------
N/A

Logs/Screenshots:
----------------------------
![uAQVisyE1q](https://user-images.githubusercontent.com/44171274/64988344-3f978000-d899-11e9-8f62-6ecaeb41da20.gif)

Additional Info:
---------------------------
N/A

**Comment by peterix** [comment]
Fixed in develop.
