### ISSUE TITLE
Minecraft started with MultiMC on the F3 says its using my NVidia, but in task manager it uses integrated graphics

### ISSUE THREAD

**Issue by Runonstof** [MultiMC/MultiMC5#2854]
**What happens?**
This instance of MultiMC uses an java installation that is added viathe NVIDIA control panel.
Hence when I go in minecraft check the F3 screen it DOES say it uses my NVIDIA but checking GPU activity in Task Manager reveals that my integrated card it used. (Screenshots provided)

This happened after I updated when MultiMC prompted for that

**What I tried**
 - Checking the issue with Minecraft that is NOT started with MultiMC (but vanilla, technic and twitch), no problem there.
 - Adding the right javaw.exe path to the NVIDIA control panel
 - Playing with and Googled about various Minecraft video settings, with and without Optifine
 - Downgrading, but issue remained with MultiMC

So Minecraft says it uses my NVIDIA but task manager activity overview says integrated is used.
If I force minecraft on my integrated it actualle runs faster now

**Screenshots**

![Task Manager Window](https://user-images.githubusercontent.com/36049776/65080228-1530ea00-d9a1-11e9-9146-3cf9654426bf.png)
![F3 Screen](https://user-images.githubusercontent.com/36049776/65080324-4d382d00-d9a1-11e9-8bdb-a13a9fd80a4b.png)

**Comment by ChipWolf** [comment]
Disable the integrated GPU in your BIOS

**Comment by DarkenMoon97** [comment]
I've noticed this and it seems to be the way that Nvidia Optimus works on laptops. Unless you have a MUX switch on your laptop, which most do not, you can't disable the iGPU. Only way to bypass this issue would be using an external monitor that is typically routed to the dedicated graphics card; but that somewhat defeats the purpose of a laptop in the first place.

**Comment by shinji257** [comment]
Looks like you are running Windows 10.  Try checking in graphics settings and set Java to prefer High Performance.  This should hopefully get it to use the nVidia card instead of the iGPU on the laptop.
https://filestore.community.support.microsoft.com/api/images/2f24ffdf-1fd2-4111-aaa1-c7dbc6bfc69b

**Comment by peterix** [comment]
This has nothing to do with MultiMC, IMO.

A workaround is possible, but technically challenging.
