### ISSUE TITLE
MultiMC 5 Version 0.6.7-develop-1382 on win32 - SSL error in Auth flow

### ISSUE THREAD

**Issue by FPSobsession** [MultiMC/MultiMC5#2855]
System Information
-----------------------------
MultiMC version: MultiMC 5 Version 0.6.7-develop-1382

Operating System: Windows 8.1

Summary of the issue or suggestion:
----------------------------------------------
After the most recent update, I noticed that the section containing Auth/Session/Skins/API were all X'ed out. Attempted refreshing and the CTA was unresponsive. I removed my account and attempted to add it once more and received the following error:

Authentication operation failed due to a network error: Error creating SSL context () (99)

What should happen:
------------------------------
Authentication should be successful.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download the most recent update and install it.

2. Attempt to launch an instance or remove an account.

3. Attempt to add an account.

Suspected cause:
---------------------------
Missing dll files (add these in and it fixes the issue):
libeay32.dll
ssleay32.dll

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![multimc](https://user-images.githubusercontent.com/55470620/65101504-5911f800-d97d-11e9-9421-5d69e94dbe3f.PNG)

Additional Info:
---------------------------

**Comment by huuv888** [comment]
Reverted to previous dev version (1380) and the SSL errors are not present.
    
```
3.792 D Downloading  "https://status.mojang.com/check"
3.868 W QSslSocket: cannot call unresolved function SSLv23_client_method
3.868 W QSslSocket: cannot call unresolved function SSL_CTX_new
3.868 W QSslSocket: cannot call unresolved function SSL_library_init
3.868 W QSslSocket: cannot call unresolved function ERR_get_error
```

**Comment by ShadeTheCat** [comment]
Hello, no none dll files are missing for some reason this verison is the only version having a problem that the linux version is having, although not fixable by the same way.

**Comment by huuv888** [comment]
I updated the issue, those two files will fix the build.

**Comment by falizure** [comment]
I am having a similar issue on windows 10, i have not removed my account but it is forcing me to launch in offline mode because of this.

**Comment by FPSobsession** [comment]
Add the two indicated dll files in the description

**Comment by peterix** [comment]
the issue has been solved in the latest build. Add the two libs, or just grab the [latest build](https://files.multimc.org/downloads/mmc-develop-win32.zip) and overwrite MultiMC with it.
