### ISSUE TITLE
please help im trying to play skyfactory 2.5 and it wont work

### ISSUE THREAD

**Issue by JazzyXD** [MultiMC/MultiMC5#2857]
it just wont work can someone tell me the issue with this and how to fix this

Heres the log 
https://paste.ee/p/JRzTE

**Comment by JazzyXD** [comment]
help

**Comment by Janrupf** [comment]
Update your graphics driver

**Comment by JazzyXD** [comment]
> Update your graphics driver

my graphics card is up to date so idk the issue
