### ISSUE TITLE
Cannot open modpacks after crash/manually killing the task.

### ISSUE THREAD

**Issue by SpacewolfeCZ** [MultiMC/MultiMC5#2858]
System Information
-----------------------------
MultiMC version: 0.6.7-1375

Operating System: Win 10

Summary of the issue or suggestion: After a crash/killing the minecraft task due to ANR, one cannot launch the modpack.
----------------------------------------------

What should happen:Modpack should launch.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch modpack

2. Crash modpack

3. Obtain results.

Suspected cause: Some super ugly crash.
---------------------------

Logs/Screenshots:
----------------------------
[//]: # https://paste.ee/p/fTrvD

Additional Info: My guess is somewhere within how the files are handled, as a restart of the system fixes the issue. However, I doubt it's mostly on MultiMC's end, as I can launch other modpacks, and if I were to try and delete the instance folder, I couldn't, as apparently the folder was in use. Task manager showed neither a jawav.exe or a multimc process running.
---------------------------

**Comment by Janrupf** [comment]
Hmm, did a reboot fix this? It might also be your Antivirus

**Comment by SpacewolfeCZ** [comment]
>It might also be your Antivirus

I'm running Defender, and ran it on previous system and didn't have this kind of problem.

**Comment by peterix** [comment]
Oh my... well, I got nothing. This is Peak Windows Insanity at its finest.
