### ISSUE TITLE
[Feature request] Way to download modpacks with command lines

### ISSUE THREAD

**Issue by jinkhya** [MultiMC/MultiMC5#2860]
Hello,
could it be possible to add a way to download modpacks with command lines?
Something like "multimc -dl twitchurl"

Thanks in advance !

**Comment by Knogle** [comment]
Would be a nice feature, especially to set up minecraft modded servers on systemns without screen.

**Comment by akhyarrh** [comment]
<https://github.com/jaredallard/modpacker>

The problem is it using `nodejs` and `npm`

**Comment by peterix** [comment]
Not for twitch, because twitch urls are broken nonsense. But I like the idea and will keep it around for the eventual command line revamp.
