### ISSUE TITLE
Minecraft Crashes with code 255

### ISSUE THREAD

**Issue by CamcodOfficial** [MultiMC/MultiMC5#2861]
System Information
MacBook Air 2017
Processor: 1.8 GHz Intel Core i5
Memory: 8 GB 1600 MHz DDR3
Graphics: Intel HD Graphics 6000 1536 MB
-----------------------------
MultiMC version:
0.6.7-1316
Operating System:
macOS Mojave version 10.14.4
Summary of the issue or suggestion:
----------------------------------------------
I try to launch any modpack either through a zip downloaded from curse forge or FTB Legacy and it doesn't even launch the game.

What should happen:
------------------------------
Minecraft should launch and everything would be fine and dandy.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download MultiMC on macOS

2. Manually connect Java binary

3. Try and Launch a Pack

Suspected cause:
---------------------------
Perhaps it is a Java problem or something with a firewall of some sort.

Logs/Screenshots:
----------------------------
[//]: # https://paste.ee/p/6xSPD

Additional Info:
---------------------------
I am on a school computer and I'm desperately trying pass time in my boring classes.

**Comment by tehbasshunter** [comment]
You need java 8. Modded won't work with anything higher.
