### ISSUE TITLE
Process crashed with exitcode 6.

### ISSUE THREAD

**Issue by gagbe** [MultiMC/MultiMC5#2866]
System Information
-----------------------------
00:00.0 Host bridge: Intel Corporation 2nd Generation Core Processor Family DRAM Controller (rev 09)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port (rev 09)
00:16.0 Communication controller: Intel Corporation 6 Series/C200 Series Chipset Family MEI Controller #1 (rev 04)
00:1a.0 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #2 (rev 04)
00:1b.0 Audio device: Intel Corporation 6 Series/C200 Series Chipset Family High Definition Audio Controller (rev 04)
00:1c.0 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 1 (rev b4)
00:1c.3 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 4 (rev b4)
00:1c.4 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 5 (rev b4)
00:1c.5 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 6 (rev b4)
00:1c.6 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 7 (rev b4)
00:1d.0 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #1 (rev 04)
00:1f.0 ISA bridge: Intel Corporation HM65 Express Chipset LPC Controller (rev 04)
00:1f.2 SATA controller: Intel Corporation 6 Series/C200 Series Chipset Family 6 port Mobile SATA AHCI Controller (rev 04)
00:1f.3 SMBus: Intel Corporation 6 Series/C200 Series Chipset Family SMBus Controller (rev 04)
01:00.0 VGA compatible controller: NVIDIA Corporation GF106M [GeForce GTX 460M] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GF106 High Definition Audio Controller (rev a1)
08:00.0 FireWire (IEEE 1394): O2 Micro, Inc. 1394 OHCI Compliant Host Controller (rev 01)
08:00.1 SD Host controller: O2 Micro, Inc. Integrated MMC/SD Controller (rev 01)
08:00.2 Mass storage controller: O2 Micro, Inc. Integrated MS/MSPRO/xD Controller (rev 01)
0f:00.0 Network controller: Qualcomm Atheros AR9285 Wireless Network Adapter (PCI-Express) (rev 01)
10:00.0 Ethernet controller: Qualcomm Atheros AR8151 v2.0 Gigabit Ethernet (rev c0)
----------------------------------------------
MultiMC version:
MultiMC 5 - Version 0.6.7-1290 on lin64
Operating System:
Ubuntu 18.04.3
Summary of the issue or suggestion:
----------------------------------------------
When trying to run Roguelike Adventures and Dungeons, I get "Process crashed with exitcode 6." This only started happening when I reinstalled Ubuntu after messing something up with my video drivers. Before reinstalling Ubuntu it worked fine. I thought the issue was caused by my Java version, which was "java-8-openjdk-amd64", but when I upgraded to "java-11-openjdk-amd64" it just plain didn't start. It works fine with vanilla 1.14.4.

What should happen:
------------------------------
It should take a few minutes to load everything then allow me to play the game normally.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC.

2. Launch update-RAD-1.31

3. Wait for it to get to around 3/7 on the loading bar, and it crashes

Suspected cause:
---------------------------
I think it has something to do with my Java version, but I'm not positive.

Logs/Screenshots:
----------------------------
https://paste.ee/p/QhWY3

**Comment by Janrupf** [comment]
You are running the open source graphics driver:
```
Kernel driver in use: nouveau
```

You need to switch to the official nvidia drivers in order for this to work.

**Comment by gagbe** [comment]
> You need to switch to the official nvidia drivers in order for this to work.

Thanks, it works now.

**Comment by pip525** [comment]
Process crashed with exitcode 6.

**Comment by KTibow** [comment]
I'm getting this on a Microsoft Surface Pro 7, with these software specs:

- OS: Ubuntu 21.10
- Minecraft version: 1.8.9 with forge 11.15.1.2318
- MultiMC version: MultiMC 5 - Version 0.6.14-2998 on lin64
- Minecraft java version: `/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java`
- Minecraft memory allocation: 512-1024 MiB (as of crash)
- `inxi -Gxz` output:
```
Graphics:
  Device-1: Intel Iris Plus Graphics G4 vendor: Microsoft driver: i915 
  v: kernel bus-ID: 00:02.0 
  Device-2: Microsoft LifeCam HD-5000 type: USB 
  driver: snd-usb-audio,uvcvideo bus-ID: 3-4.3.2:28 
  Display: wayland server: X.Org 1.21.1.2 compositor: gnome-shell driver: 
  loaded: modesetting unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: Mesa Intel Iris Plus Graphics (ICL GT1.5) 
  v: 4.6 Mesa 21.2.2 direct render: Yes
```

**Comment by phit** [comment]
@KTibow make a new issue with logs, or better join our discord for support https://discord.gg/multimc

**Comment by KTibow** [comment]
Alright, I'll do that if I get it again.
