### ISSUE TITLE
error al actualizaar

### ISSUE THREAD

**Issue by neyster9999** [MultiMC/MultiMC5#2867]
al momento de querer descargar un pack de mods me sal el errror
Error al actualizar la lista:
El trabajo 'Descargando archivos de actualización de net.minecraft/index.json' no ha sido procesado:
https://v1.meta.multimc.org/net.minecraft/index.json
![Captura de pantalla (36)](https://user-images.githubusercontent.com/55932967/65824068-92712000-e227-11e9-8089-c68c31033414.png)

**Comment by Heufneutje** [comment]
You will not get any support for modified versions of MultiMC here. It broke because of changes made to MultiMC's servers so you're out of luck.
