### ISSUE TITLE
Unable to Launch Any Instances.

### ISSUE THREAD

**Issue by EaglePopes** [MultiMC/MultiMC5#2869]
System Information
-----------------------------
MultiMC version: MultiMC 5

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Im unable to launch any sort of instances,with forge and without forge i get the error "Process exited with code -1.".

What should happen:
------------------------------
Mc should open atleast.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Make new instances !.

2.Launch it !.

3.Nothing happens and i get "Process exited with code -1." at the end of logs.

Suspected cause:
---------------------------
im clueless tbh,only thing is i updated to windows 10 yesterday and idk if thats causing it?

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/rqxol

Additional Info:
---------------------------

**Comment by S10MC2015** [comment]
Something is wrong with your graphics driver

**Comment by EaglePopes** [comment]
> Something is wrong with your graphics driver

How many i fix that?sorry im not that good with fixing or updating things.

**Comment by Janrupf** [comment]
Depends on your graphics card:
- For NVIDIA see [here](https://www.nvidia.com/Download/index.aspx) (adjust the selection to match your system)
- For AMD see [here](https://www.amd.com/support)

**Comment by EaglePopes** [comment]
after 2 mins of googling it seems my graphics card doesnt support windows 10 ,should have done that sooner...i really apologize for wasting your guys time,i had to revert back to windows 8 now it works fine.
Take care and thanks again <3
