### ISSUE TITLE
[Linux] Crash when closing Edit Instance windows

### ISSUE THREAD

**Issue by FalsePattern** [MultiMC/MultiMC5#2873]
System Information
-----------------------------
MultiMC version: 0.6.7-develop-1307

Operating System: Linux x64 Debian Buster

Summary of the issue or suggestion:
----------------------------------------------
The launcher segfaults when closing the "Edit Instance" window.

What should happen:
------------------------------
The window should close and the launcher shouldn't segfault.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC

2. Select an instance

3. Click Edit instance

4. Close the edit instance window

Suspected cause:
---------------------------
QT5 socket system

Logs/Screenshots:
----------------------------
GDB backtrace: https://pastebin.com/fR6fASZ6

Additional Info:
---------------------------
Using KDE 5 Plasma desktop environment

**Comment by peterix** [comment]
This is most likely it:
https://bugreports.qt.io/browse/QTBUG-68393

Same bug, different strack trace, because the code has changed since.

**Comment by peterix** [comment]
In other words: upstream bug, should be fixed in Qt.

Possible patches:
https://codereview.qt-project.org/c/qt/qtbase/+/237817
https://codereview.qt-project.org/c/qt/qtbase/+/264529

**Comment by peterix** [comment]
Anyway, I will not do anything with this. Update your system.
