### ISSUE TITLE
My MultiMC Always clash

### ISSUE THREAD

**Issue by guiwosniak** [MultiMC/MultiMC5#2874]
always i try to open the minecraft with the multimc i receive a crash (bad card drivers) and this don't happens if i use the minecraft original laucher. (sorry for my bad english)

**Comment by Heufneutje** [comment]
Try this: https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs

Also, please fill out the template next time. It exists for a reason.
