### ISSUE TITLE
MultiMC task failed

### ISSUE THREAD

**Issue by crunchynut609** [MultiMC/MultiMC5#2878]
System Information
-----------------------------
MultiMC version: MultiMC 5 - Version 0.6.7 - 1316 on osx64

Operating System: MacOS 

Summary of the issue or suggestion: Component metadata update task failed while downloading from remote server
----------------------------------------------

What should happen: not sure, this is my first time loading this pack

**Comment by Zetabite** [comment]
What pack? Also, if you try to load a twtitch modpack, download the zip from curseforge and import it with MMC. In case you try to load 1.13 or 1.14 forge modpack that wont work either, cause MMC doesnt support those forge versions.
