### ISSUE TITLE
New health thing

### ISSUE THREAD

**Issue by ProfessorX234** [MultiMC/MultiMC5#2880]
The thing in the bottom right of multimc is showing an x on multiple spots because minecraft is moving it to minecraft.net I think.

**Comment by peterix** [comment]
Seems fine to me.

**Comment by ProfessorX234** [comment]
Well when you click on the things, they don't take you to the Minecraft API authentication and other health things anymore. I also had an issue starting up Minecraft in multimc but k don't know if it's related.

**Comment by ProfessorX234** [comment]
It says it can't get the updated assets or something like that. So maybe it is related?

**Comment by peterix** [comment]
Looks like the new site has no equivalent of the API status page. Yay.

Guess the clickable nature of it needs to be removed.

**Comment by peterix** [comment]
Created https://github.com/MultiMC/MultiMC5/wiki/Mojang-Services-Status to have something valid to point the status widget to.
