### ISSUE TITLE
unable to clone source

### ISSUE THREAD

**Issue by Vokuar** [MultiMC/MultiMC5#2881]
System Information
-----------------------------
MultiMC version: N/A

Operating System: Rasbian Buster

Summary of the issue or suggestion:
----------------------------------------------
unable to clone the git using command line

What should happen:
------------------------------
file should download to the correct folder

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. open terminal on linux

2. type ```git clone git@github.com:MultiMC/MultiMC5.git``` and press enter  

3. it should download

Suspected cause:
---------------------------
unsupported os?

Logs/Screenshots:
----------------------------
![image](https://user-images.githubusercontent.com/23405516/66699377-bb1a0f00-ed29-11e9-8620-41725c0d2346.png)

Additional Info:
---------------------------

**Comment by phit** [comment]
you need to configure git with your github keys or not use ssh to clone and instead do 
`git clone https://github.com/MultiMC/MultiMC5.git`

https://help.github.com/en/articles/error-permission-denied-publickey#verify-the-public-key-is-attached-to-your-account

**Comment by Vokuar** [comment]
thank you i was wondering what was wrong
