### ISSUE TITLE
Security requirements on MacOS Catalina

### ISSUE THREAD

**Issue by redpandamonium** [MultiMC/MultiMC5#2882]
System Information
-----------------------------
MultiMC version: 0.7.6-1316

Operating System: MacOS Catalina 10.15 (19A583)

Summary of the issue or suggestion: 
With MacOS Catalina there are new security requirements to run apps. You can get around this without changes to the app, but to users it looks like MultiMC poses a security risk. 

What should happen:
------------------------------

If there is a Developer ID then the app should be signed and notarized with Apple.

Steps to reproduce the issue
-------------------------------------------------------------
1. Install the new MacOS Version

2. Open MultiMC

Suspected cause:
---------------------------

See: https://developer.apple.com/news/?id=06032019i

**Comment by redpandamonium** [comment]
To get around this you go to `/Applications` right click on the app and click "open". A warning still pops up but you can open it anyway.

**Comment by peterix** [comment]
Yeah, I refuse to pay the apple tax and destroy the portable application nature of MultiMC for this.
