### ISSUE TITLE
i can't open Project Ozone 3

### ISSUE THREAD

**Issue by SiGz2630** [MultiMC/MultiMC5#2883]
i can only create the world but when it load it crashes..
can anyone help me..
here's the crash report
[crash-2019-10-13_17.32.08-server.txt](https://github.com/MultiMC/MultiMC5/files/3721599/crash-2019-10-13_17.32.08-server.txt)

**Comment by Frontear** [comment]
This is an OpenTerrainGenerator bug. Please file a report at [pg85/OpenTerrainGenerator](https://github.com/PG85/OpenTerrainGenerator/issues/210) instead
