### ISSUE TITLE
Can't load a NewWorld in fresh install for Minecraft 1.14.4

### ISSUE THREAD

**Issue by jbouchet** [MultiMC/MultiMC5#2884]
System Information
-----------------------------
MultiMC version: 0.6.7-1375

Operating System: Windows 10 (1903)

Summary of the issue or suggestion:
----------------------------------------------
I try to launch a NewWorld in SinglePlayer, and it's stuck at 0%. No crash ... but cannot load.
Same thing with a old save.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a instance in 1.14.4

2. Try to create a New World in SinglePlayer

Logs/Screenshots:
----------------------------
![image](https://user-images.githubusercontent.com/5328980/66715244-2367ff80-edc1-11e9-9a7f-fd7f9b399cb6.png)

**Comment by peterix** [comment]
Post the whole log. There s an upload button in the corner

**Comment by jbouchet** [comment]
The log : https://paste.ee/p/idXTa

**Comment by peterix** [comment]
Sorry for not getting back to you. I haven't looked at any of this in months, and now I'm cleaning stuff up.

Sadly, the log is gone. If you still want help withj this, please open a new issue.
