### ISSUE TITLE
Can't run a modded instance

### ISSUE THREAD

**Issue by Piress** [MultiMC/MultiMC5#2885]
MultiMC version: MultiMC5

Operating System: Windows 10

Summary of the issue or suggestion: Unable to launch a specific version

What should happen: Application should open

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. I don't know man 

Suspected cause:
---------------------------
Mods? Outdated software?

Logs/Screenshots:
----------------------------
https://paste.ee/p/KwM0F

Additional Info:
I have a vanilla version on MultiMC that can run just fine. I was using a version with the Fabric API and the Replay Mod a few months ago, and it worked fine. However, said version is not working anymore.

**Comment by peterix** [comment]
Log's gone and the usual people who hang around and help didn't, this time. Oh well.
