### ISSUE TITLE
MultiMC refuse to download same version libraries with suffix

### ISSUE THREAD

**Issue by ppoozl** [MultiMC/MultiMC5#2886]
Hello. I am using MMC to launch modded 1.13+ instances. And yes I am aware that you don't have official support for that. forge on 1.13+ need some libraries which have same version but different libraries. 
eg. net.minecraft:client:1.14.4:extra-stable and net.minecraft:client:1.14.4:slim-stable net.minecraftforge:forge:1.14.4-28.1.45,net.minecraftforge:forge:1.14.4-28.1.45:client,net.minecraftforge:forge:1.14.4-28.1.45:universal.
I am hosting these files so I can pack my instances and send it to my friends so that they can just import and play.But It seems MultiMC downloaded the first files and skip the second one.

**Comment by ppoozl** [comment]
My costom forge json:
{
    "formatVersion": 1,
    "name": "forge",
    "uid": "net.minecraftforge.forge",
    "version": "28.1.45",
    "mainClass": "cpw.mods.modlauncher.Launcher",
    "minecraftArguments": "--username ${auth_player_name} --version ${version_name} --gameDir ${game_directory} --assetsDir ${assets_root} --assetIndex ${assets_index_name} --uuid ${auth_uuid} --accessToken ${auth_access_token} --userType ${user_type} --versionType ${version_type} --launchTarget fmlclient --fml.forgeVersion 28.1.45 --fml.mcVersion 1.14.4 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20190829.143755",
    "libraries": [
        {
            "name": "net.minecraft:client:1.14.4:extra-stable",
            "url": "http://mcrepo-1253313747.cos.ap-shanghai.myqcloud.com/"
        },
        {
            "name": "net.minecraft:client:1.14.4:slim-stable",
            "url": "http://mcrepo-1253313747.cos.ap-shanghai.myqcloud.com/"
        },
        {
            "name": "net.minecraftforge:forge:1.14.4-28.1.45",
            "url": "http://mcrepo-1253313747.cos.ap-shanghai.myqcloud.com/"
        },
        {
            "name": "net.minecraftforge:forge:1.14.4-28.1.45:client",
            "url": "http://mcrepo-1253313747.cos.ap-shanghai.myqcloud.com/"
        },
        {
            "name": "net.minecraftforge:forge:1.14.4-28.1.45:universal",
            "url": "http://files.minecraftforge.net/maven/"
        },
        {
            "name": "org.ow2.asm:asm:6.2",
            "url": "https://files.minecraftforge.net/maven/"    
        },
        {
            "name": "org.ow2.asm:asm-commons:6.2",
            "url": "https://files.minecraftforge.net/maven/"
        },
        {
            "name": "org.ow2.asm:asm-tree:6.2",
            "url": "https://files.minecraftforge.net/maven/"
        },
        {
            "name": "cpw.mods:modlauncher:4.1.0",
            "url": "https://files.minecraftforge.net/maven/"
        },
        {
            "name": "cpw.mods:grossjava9hacks:1.1.0",
            "url": "https://files.minecraftforge.net/maven/"
        },
        {
            "name": "net.minecraftforge:accesstransformers:1.0.0-shadowed",
            "url": "https://files.minecraftforge.net/maven/"
        },
        {
            "name": "net.minecraftforge:eventbus:1.0.0-service",
            "url": "https://files.minecraftforge.net/maven/"
        },
        {
            "name": "net.minecraftforge:forgespi:1.4.0",
            "url": "https://files.minecraftforge.net/maven/"
        },
        {
            "name": "net.minecraftforge:coremods:1.0.0",
            "url": "https://files.minecraftforge.net/maven/"
        },
        {
            "name": "net.minecraftforge:unsafe:0.2.0",
            "url": "https://files.minecraftforge.net/maven/"
        },
        {
            "name": "com.electronwill.night-config:core:3.6.0",
            "url": "https://files.minecraftforge.net/maven/"
        },
        {
            "name": "com.electronwill.night-config:toml:3.6.0",
            "url": "https://files.minecraftforge.net/maven/"
        },
        {
            "name": "org.jline:jline:3.12.1",
            "url": "https://files.minecraftforge.net/maven/"
        },
        {
            "name": "org.apache.maven:maven-artifact:3.6.0",
            "url": "https://files.minecraftforge.net/maven/"
        },
        {
            "name": "net.jodah:typetools:0.6.0",
            "url": "https://files.minecraftforge.net/maven/"
        },
        {
            "name": "java3d:vecmath:1.5.2",
            "url": "https://libraries.minecraft.net/"
        },
        {
            "name": "org.apache.logging.log4j:log4j-api:2.11.2",
            "url": "https://files.minecraftforge.net/maven/"
        },
        {
            "name": "org.apache.logging.log4j:log4j-core:2.11.2",
            "url": "https://files.minecraftforge.net/maven/"
        },
        {
            "name": "net.minecrell:terminalconsoleappender:1.2.0",
            "url": "https://files.minecraftforge.net/maven/"
        },
        {
            "name": "net.sf.jopt-simple:jopt-simple:5.0.4",
            "url": "https://files.minecraftforge.net/maven/"
        }
    ]
}

**Comment by peterix** [comment]
No.
