### ISSUE TITLE
Impact Not Working

### ISSUE THREAD

**Issue by YurtCurcle** [MultiMC/MultiMC5#2891]
System Information
-----------------------------
MultiMC version: MultiMC 5 - Version 0.6.7 - 1375 on win 32

Operating System: Windows 10

Summary of the issue or suggestion: I followed the basic steps for installing Impact 4.8.1 via editing the json file. I then revieved the message bellow and it didn't run.

----------------------------------------------

What should happen: Open minecraft with the Impact Client
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Follow the normal steps listed for installing Impact with MultiMC

Logs/Screenshots:
MultiMC version: 0.6.7-1375

Minecraft folder is:
C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/instances/Impact 4.8.1/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 1.8.0_201, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/instances/Impact 4.8.1/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/com/github/ImpactDevelopment/Impact/4.8.1-1.14.4/Impact-4.8.1-1.14.4.jar (missing)
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/cabaletta/baritone-api/1.4.2/baritone-api-1.4.2.jar (missing)
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar (missing)
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/com/github/ImpactDevelopment/SimpleTweaker/1.2/SimpleTweaker-1.2.jar (missing)
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/com/github/ZeroMemes/Alpine/1.8/Alpine-1.8.jar (missing)
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/net/jodah/typetools/0.5.0/typetools-0.5.0.jar (missing)
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar (missing)
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/com/github/ImpactDevelopment/Installer/0.7.3/Installer-0.7.3.jar (missing)
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/club/minnced/java-discord-rpc/2.0.1/java-discord-rpc-2.0.1.jar (missing)
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar (missing)
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/club/minnced/discord-rpc-release/v3.3.0/discord-rpc-release-v3.3.0.jar (missing)
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/com/mojang/minecraft/1.14.4/minecraft-1.14.4-client.jar

Native libraries:
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/instances/Impact 4.8.1/.minecraft --assetsDir C:/Users/1777598/Downloads/MultiMC (Source Folder)/MultiMC (Source Folder)/assets --assetIndex 1.14 --uuid  --accessToken  --userType  --versionType release --tweakClass clientapi.load.ClientTweaker --tweakClass baritone.launch.BaritoneTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms204m, -Xmx2048m, -Duser.language=en]

Minecraft process ID: 1052

Using onesix launcher.

Failed to find Minecraft main class:
java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:171)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with code -1.
Clipboard copy at: 17 Oct 2019 13:19:59 -0400

**Comment by ile6695** [comment]
Try installation guide from Impact:
[https://github.com/ImpactDevelopment/ImpactIssues/wiki/Installing-with-MultiMC](https://github.com/ImpactDevelopment/ImpactIssues/wiki/Installing-with-MultiMC)

**Comment by peterix** [comment]
Yeah, I have no idea what any of this means. That's some wild stuff you have there :D
