### ISSUE TITLE
Minecraft Folder reverts to default when changing .jar files

### ISSUE THREAD

**Issue by bugmancx** [MultiMC/MultiMC5#2893]
(Note: I have been working on a project with the early alphas, so I have not tested this bug for later versions.)

System Information
-----------------------------
MultiMC version: 0.6.7-1375

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
MultiMC .minecraft directory doesn't use the correct instance location after changing server jars manually and instead uses the main one under C:\Users\someone\AppData\Roaming\.minecraft

What should happen:
------------------------------
The Instance directory's .minecraft folder should be used.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Set up a new instance based on something like Alpha 1.0.4.

2. Launch the game and create a new world.

3. Notice that it has created the world in the MultiMC instance .minecraft directory

4. Edit instance and "Replace Minecraft.jar" with something else, say the Alpha 1.0.6_03.jar file (Available here: https://archive.org/download/Minecraft-JE-Alpha/a1.0.6_03/a1.0.6_03.jar) 

5. Launch the game and createa  new world

6. Notice that it is now using your regular .minecraft directory for configuration and world saves, e.g. C:\Users\someone\AppData\Roaming\.minecraft

Suspected cause:
---------------------------
None

Logs/Screenshots:
----------------------------
None

Additional Info:
---------------------------

**Comment by Heufneutje** [comment]
The main problem that old versions of Minecraft have is that C:\Users\someone\AppData\Roaming\.minecraft is actually hardcoded into Minecraft itself.

**Comment by Heufneutje** [comment]
Replacing a jar file like that won't work because those jars actually have the .minecraft path hardcoded into them.

**Comment by peterix** [comment]
I don't see why this should work.
