### ISSUE TITLE
Getting QNetworkReply::NetworkError on twitch url install

### ISSUE THREAD

**Issue by skillrax** [MultiMC/MultiMC5#2894]
System Information
-----------------------------
MultiMC version: 0.6.7-develop-1398 on win32
MultiMC version 2: 0.6.7-1375 on win32

Operating System: windows 10 pro

Summary of the issue or suggestion:
----------------------------------------------

QNetworkReply::NetworkError(ContentOperationNotPermittedError)
Appears on every check for the twitch url. Regardless of what url I try. 

Has persisted across main install (settings and several other packs installed), and a fresh install. 

What should happen:
------------------------------

Check should pass I guess. Have no log files of a successful pack install. 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create instance

2. Twitch url

3. Any twitch install url

Suspected cause:
---------------------------

Possible firewall issue. But apon checking my firewall settings there are no issues.
API broken? My account black listed in API? Havent done anything deserved of this. 

Logs/Screenshots:
----------------------------
[MultiMC-1.log](https://github.com/MultiMC/MultiMC5/files/3744672/MultiMC-1.log)
[MultiMC-1.log](https://github.com/MultiMC/MultiMC5/files/3744683/MultiMC-1.log)

2nd upload is fresh install. Error is same across both

Additional Info:
---------------------------
```
94.485 D Task "Flame::UrlResolvingTask(0x864c618)" starting for the first time
   94.485 D Task "NetJob(URL resolver)" starting for the first time
   94.485 D Downloading  "https://www.curseforge.com/minecraft/modpacks/enigmatica2expert/download-client/2811246"
   94.826 C Failed  "https://www.curseforge.com/minecraft/modpacks/enigmatica2expert/download-client/2811246"  with reason  QNetworkReply::NetworkError(ContentOperationNotPermittedError)
```

**Comment by EmberQuill** [comment]
Probably the same issue as #2829 (although this issue has more info)

**Comment by darthvader45** [comment]
Yeah, no idea why it's doing this.

**Comment by skillrax** [comment]
Just tested on completely different computer. Same problem.

This leads me to believe its a problem with my ISP, router/modem, or accounts associated with twitch/mojang. 

I will investigate.

**Comment by Zetabite** [comment]
just download the zip from curseforge and install that. the twitch link install is totally unreliable due to twitch/curseforge itself

**Comment by darthvader45** [comment]
Yeah, apparently they're doing away with the twitch part someday.  Maybe soon, maybe not.  Honestly, I hope they get rid of it and just use some curse launcher link.  Would make installs simpler, as it seems Curse is a bit more reliable than Twitch.

**Comment by peterix** [comment]
This stuff is gone from dev builds.
