### ISSUE TITLE
Compilation fails on Raspbian Buster

### ISSUE THREAD

**Issue by niansa** [MultiMC/MultiMC5#2895]
System Information
-----------------------------
MultiMC version: branch master

Operating System: Raspbian Buster

Summary of the issue or suggestion:
----------------------------------------------
Exactly the same as #2426 but on very up-to-date packages

What should happen:
------------------------------
Compilation should succeed

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Go through the building manual

Suspected cause:
---------------------------
Outdated compiler (again?), version is `gcc (Raspbian 8.3.0-6+rpi1) 8.3.0`

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://hastebin.com/puloliboku.log

Additional Info:
---------------------------
Trying to run MC on the new Raspbian Buster (maybe it works?)

**Comment by Janrupf** [comment]
HOOOOOOOLY... I don't think an outdated compiler was ever the issue. This looks like the compiler works a bit different and somehow includes symbols multiple times.

I'm also gonna leave this disclaimer here, Minecraft does not run on arm! (MultiMC should, but there is no real use)

**Comment by niansa** [comment]
@Janrupf it does, as proven multiple times. ;-)

**Comment by kb-1000** [comment]
MultiMC does run there too. As I've already noted on Discord... well, @niansa just make cmake use clang instead of gcc (run `sudo apt install clang` then add `CMAKE_CXX_COMPILER=clang++ CMAKE_C_COMPILER=clang` to the cmake command line), and it should work just fine.

**Comment by Janrupf** [comment]
Well, you guys win then I guess :P

**Comment by kb-1000** [comment]
I'd guess this is some GCC issue that should be reported, probably they're doimg something wrong that LLVM correctly catches (as in, linkonce_odr global variable linkage)

**Comment by niansa** [comment]
thanks
