### ISSUE TITLE
MultiMC freezes and closes byitself when opening it

### ISSUE THREAD

**Issue by Hora-416** [MultiMC/MultiMC5#2896]
System Information
-----------------------------
MultiMC version: 0.6.7-1375

Operating System: Windows 10 64bit

Summary of the issue or suggestion:
----------------------------------------------
Multimc becomes unresponsive (can't click anywhere) about 1s after loading UI, and 3-5s later it closes by itself

What should happen:
------------------------------
Launcher working

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC.exe

2. It freezes and closes within 5s.

Suspected cause:
---------------------------
I thought it was cause of my proxy but closing it and running a new copy of multimc has same problem. I did uninstall java 8 and install an updated java 8 but that doesn't make much sense to me

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://pastebin.com/raw/HLSQn1cf (is there a log somewhere else? the link in the template redirects to main page so I don't know if this is all)

Additional Info:
---------------------------
I got this problem first on the dev version (0.6.7-develop-1394 (looks like this before it closes https://i.imgur.com/a7uD4ps.png). New stable install has same issue but the only thing it shows is the choose your language screen
Let me know if there is any more info I can provide

**Comment by Hora-416** [comment]
I noticed that I have the same problem with a launcher from another game so I had to restart my pc and multimc works now. Guess I'll never find out what was the cause.. hope it doesn't happen again

**Comment by Heufneutje** [comment]
If you ask me it sounds like there's something running on your computer that's messing with it in that case.

**Comment by spriteclad** [comment]
Can confim, have the same problem. Any idea what could be causing it?

**Comment by Heufneutje** [comment]
No idea. You haven't posted any logs. Create a new issue. Usually assumptions that your issue is the same as someone else's are incorrect.
