### ISSUE TITLE
Trying to run, but will not launch

### ISSUE THREAD

**Issue by Aubygreen** [MultiMC/MultiMC5#2897]
trying to run Multimc on Arch linux, pkg installed without a hitch, but i'm trying to launch a modpack and keep running into this: 

MultiMC version: 0.6.7-custom

Minecraft folder is:
/home/glameow/.local/share/multimc/instances/FVCraft_2.01/minecraft

Java path is:
/usr/lib/jvm/java-13-openjdk/bin/java

Java is version 13, using 64-bit architecture.

Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
Intel Corporation HD Graphics 530 (rev 06)

DeviceName:  Onboard IGD

Subsystem: Dell HD Graphics 530

OpenGL version string: 3.0 Mesa 19.2.1

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /home/glameow/.local/share/multimc/instances/FVCraft_2.01/natives

Libraries:
  /home/glameow/.local/share/multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/glameow/.local/share/multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/glameow/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  /home/glameow/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  /home/glameow/.local/share/multimc/libraries/com/mojang/netty/1.6/netty-1.6.jar
  /home/glameow/.local/share/multimc/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  /home/glameow/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/glameow/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/glameow/.local/share/multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/glameow/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/glameow/.local/share/multimc/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  /home/glameow/.local/share/multimc/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /home/glameow/.local/share/multimc/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /home/glameow/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  /home/glameow/.local/share/multimc/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/glameow/.local/share/multimc/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/glameow/.local/share/multimc/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/glameow/.local/share/multimc/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /home/glameow/.local/share/multimc/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/glameow/.local/share/multimc/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  /home/glameow/.local/share/multimc/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  /home/glameow/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  /home/glameow/.local/share/multimc/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  /home/glameow/.local/share/multimc/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  /home/glameow/.local/share/multimc/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  /home/glameow/.local/share/multimc/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  /home/glameow/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  /home/glameow/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  /home/glameow/.local/share/multimc/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  /home/glameow/.local/share/multimc/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
  /home/glameow/.local/share/multimc/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  /home/glameow/.local/share/multimc/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  /home/glameow/.local/share/multimc/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  /home/glameow/.local/share/multimc/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  /home/glameow/.local/share/multimc/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  /home/glameow/.local/share/multimc/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  /home/glameow/.local/share/multimc/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  /home/glameow/.local/share/multimc/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  /home/glameow/.local/share/multimc/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  /home/glameow/.local/share/multimc/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  /home/glameow/.local/share/multimc/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  /home/glameow/.local/share/multimc/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  /home/glameow/.local/share/multimc/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  /home/glameow/.local/share/multimc/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /home/glameow/.local/share/multimc/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  /home/glameow/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-linux.jar
  /home/glameow/.local/share/multimc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar

Mods:
  [📁] 1.7 (folder)
  [✔️] 1.7.10_AM2-1.4.0.009
  [✔️] ActuallyAdditions-1.7.10-r21
  [✔️] ae2stuff-rv3-0.5.1.9-mc1.7.10
  [✔️] AgriCraft-1.7.10-1.5.0
  [✔️] AnimationAPI-1.7.10-1.2.4
  [✔️] AOBD-2.9.2
  [✔️] AppleCore-mc1.7.10-3.1.1
  [✔️] appliedenergistics2-rv3-beta-6
  [✔️] Armourers-Workshop-1.7.10-0.48.3
  [✔️] Avaritia-1.13
  [✔️] bdlib-1.9.4.109-mc1.7.10
  [✔️] BiblioCraft[v1.11.7][MC1.7.10]
  [✔️] BiblioWoods[BiomesOPlenty][v1.9]
  [✔️] BiblioWoods[Forestry][v1.7]
  [✔️] BiblioWoods[Natura][v1.5]
  [✔️] BigReactors-0.4.3A
  [✔️] binnie-mods-1.7.10-2.0.22.7
  [✔️] BiomesOPlenty-1.7.10-2.1.0.1889-universal
  [✔️] BloodArsenal-1.7.10-1.2-5
  [✔️] BloodMagic-1.7.10-1.3.3-17
  [✔️] Botania r1.8-249
  [✔️] BrandonsCore-1.0.0.12
  [✔️] Carpenter's Blocks v3.3.8.2 - MC 1.7.10
  [📁] carpentersblocks (folder)
  [✔️] Chisel-2.9.5.11
  [✔️] CodeChickenCore-1.7.10-1.0.7.47-universal
  [✔️] CoFHCore-[1.7.10]3.1.4-329
  [✔️] CoFHLib-[1.7.10]1.2.1-185
  [✔️] ComputerCraft1.75
  [✔️] Controlling-1.7.10-1.0.0
  [✔️] cookingbook-mc1.7.10-1.0.140
  [✔️] CosmeticArmorReworked-1.7.10-v6b
  [✔️] CraftTweaker-1.7.10-3.0.13
  [✔️] CreativeCore v1.3.24 mc1.7.10
  [✔️] denseores-1.6.2
  [✔️] Ding-MC1.7.10v2
  [✔️] DoggyTalents-1.7.10-1.14.2.317-universal
  [✔️] Draconic-Evolution-1.7.10-1.0.2h
  [✔️] DynamicSurroundings-1.7.10-1.0.6.4
  [✔️] EnderCore-1.7.10-0.2.0.39_beta
  [✔️] EnderIO-1.7.10-2.3.0.429_beta
  [✔️] EnderStorage-1.7.10-1.4.7.37-universal
  [✔️] EnderTech-1.7.10-0.3.2.405
  [✔️] EnderZoo-1.7.10-1.0.15.32
  [✔️] ExtraCells-1.7.10-2.3.14b200
  [✔️] ExtraTiC-1.7.10-1.4.6
  [✔️] extrautilities-1.2.12
  [✔️] fastcraft-1.25
  [✔️] Forbidden Magic-1.7.10-0.575
  [✔️] forestry_1.7.10-4.2.16.64
  [✔️] FoxLib-1.7.10-0.7.0
  [✔️] Galacticraft-Planets-1.7-3.0.12.504
  [✔️] GalacticraftCore-1.7-3.0.12.504
  [✔️] Guide-API-1.7.10-1.0.1-20
  [✔️] Headcrumbs-1.7.4
  [✔️] ImmersiveEngineering-0.7.7
  [✔️] immersiveintegration-0.6.8
  [✔️] InventoryTweaks-1.59-dev-152
  [✔️] ironchest-1.7.10-6.0.62.742-universal
  [✔️] itlt-1.7.10-0.0.8
  [✔️] IvToolkit-1.2.1
  [✔️] Jabba-1.2.2_1.7.10
  [✔️] JadedNEI-1.7.10-1.0.1
  [✔️] journeymap-1.7.10-5.1.4p2-unlimited
  [✔️] LittleTiles v1.2.0 mc1.7.10
  [✔️] magicbees-1.7.10-2.4.4
  [✔️] Mantle-1.7.10-0.3.2b
  [✔️] Mekanism-1.7.10-9.1.1.1031
  [✔️] MekanismGenerators-1.7.10-9.1.1.1031
  [✔️] MekanismTools-1.7.10-9.1.1.1031
  [✔️] MicdoodleCore-1.7-3.0.12.504
  [✔️] MineFactoryReloaded-[1.7.10]2.8.1-174
  [✔️] MineTweakerRecipeMaker-1.7.10-1.1.1
  [✔️] ModTweaker2-0.9.6
  [✔️] Morpheus-1.7.10-1.6.21
  [✔️] MouseTweaks-2.4.4-mc1.7.10
  [✔️] natura-1.7.10-2.2.0.1
  [✔️] neiaddons-1.12.14.40-mc1.7.10
  [✔️] NEIIntegration-MC1.7.10-1.1.2
  [✔️] NetherOres-[1.7.10]2.3.1-22
  [✔️] NotEnoughItems-1.7.10-1.0.5.120-universal
  [✔️] NotEnoughResources-1.7.10-0.1.0-122
  [✔️] OpenBlocks-1.7.10-1.6
  [✔️] OpenModsLib-1.7.10-0.10
  [✔️] OpenModularTurrets-1.7.10-2.2.11-245
  [✔️] p455w0rdslib-1.7.10-1.0.4
  [✔️] Pam's HarvestCraft 1.7.10Lb
  [✔️] PlayerAPI-1.7.10-1.4
  [✔️] ProjectRed-1.7.10-4.7.0pre12.95-Base
  [✔️] ProjectRed-1.7.10-4.7.0pre12.95-Compat
  [✔️] ProjectRed-1.7.10-4.7.0pre12.95-Fabrication
  [✔️] ProjectRed-1.7.10-4.7.0pre12.95-Integration
  [✔️] ProjectRed-1.7.10-4.7.0pre12.95-Lighting
  [✔️] ProjectRed-1.7.10-4.7.0pre12.95-Mechanical
  [✔️] ProjectRed-1.7.10-4.7.0pre12.95-World
  [✔️] Quiet BossesV1.2
  [📁] railcraft (folder)
  [✔️] Railcraft_1.7.10-9.12.2.0
  [✔️] RandomThings-2.2.4
  [✔️] RecurrentComplex-0.9.7.1.1
  [✔️] Sanguimancy-1.7.10-1.1.9-35
  [✔️] SimplyJetpacks-MC1.7.10-1.5.3
  [✔️] SolarExpansion-Basic-1.6a
  [✔️] Tails-1.7.10-1.4.1a
  [✔️] Tainted-Magic-r7.82
  [✔️] tcinventoryscan-mc1.7.10-1.0.11
  [✔️] TConstruct-1.7.10-1.8.8
  [✔️] Thaumcraft-1.7.10-4.2.3.5
  [✔️] ThaumcraftMobAspects-1.7.2-2A
  [✔️] thaumcraftneiplugin-1.7.10-1.7a
  [✔️] Thaumic Fixer-1.2
  [✔️] thaumicenergistics-1.1.3.0
  [✔️] ThaumicExploration-1.7.10-1.1-53
  [✔️] ThaumicTinkerer-2.5-1.7.10-164
  [✔️] ThermalDynamics-[1.7.10]1.2.1-172
  [✔️] ThermalExpansion-[1.7.10]4.1.5-248
  [✔️] ThermalFoundation-[1.7.10]1.2.6-118
  [✔️] ThermalTinkering-1.7.10-1.2.1
  [✔️] TiCTooltips-mc1.7.10-1.2.5
  [✔️] tinker_io-1.7.10-release 1.5.0
  [✔️] TMechworks-1.7.10-0.2.15.106
  [✔️] VillageNames-1.7.10-3.2.1
  [✔️] Waila-1.5.10_1.7.10
  [✔️] WailaHarvestability-mc1.7.10-1.1.6
  [✔️] WAILAPlugins-MC1.7.10-0.2.0-25
  [✔️] Wawla-1.0.5.120
  [✔️] WirelessCraftingTerminal-1.7.10-rv3-1.8.7.4b
  [✔️] witchery-1.7.10-0.24.1

Params:
  --username  --version MultiMC5 --gameDir /home/glameow/.local/share/multimc/instances/FVCraft_2.01/minecraft --assetsDir /home/glameow/.local/share/multimc/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType  --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx9600m, -Duser.language=en]

Minecraft process ID: 18776

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code 255.

Now, I looked what code 255 typically results in, from the game trying to open at fullscreen. But I have made sure that the options.txt in the instance folder has fullscreen: false  
and et i still keep running into code 255

**Comment by Aubygreen** [comment]
https://paste.ee/p/o6f50
should be full log

**Comment by Zetabite** [comment]
Use java 8
