### ISSUE TITLE
Windows 10 - Minecraft does't fit game window

### ISSUE THREAD

**Issue by altDark** [MultiMC/MultiMC5#2899]
System Information
-----------------------------
MultiMC version:
0.6.7-develop-1398 and 0.6.7-1375

Operating System:
Windows 10 Enterprise 64-bit (10.0, Build 17763) (17763.rs5_release.180914-1434)

Summary of the issue or suggestion:
----------------------------------------------
Minecraft does't fit game window - sides are missing (top, left, bottom and right). I used default in MultiMC Settings/Game windows.

What should happen:
------------------------------
Minecraft should be displayed correctly and not cut.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add new instance of  vanilla Minecraft 1.14.4.

2. Run it.

Suspected cause:
---------------------------
No idea :(

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![image](https://user-images.githubusercontent.com/36827802/67408401-347ef080-f5b9-11e9-850d-54d9c8e57c5f.png)

![image](https://user-images.githubusercontent.com/36827802/67410667-bc1a2e80-f5bc-11e9-8e90-7c4fa90b5d97.png)

Additional Info:
---------------------------
Java: jdk1.8.0_221
DirectX Version: DirectX 12
Display Devices: Intel(R) HD Graphics 630

**Comment by peterix** [comment]
The launcher has nothing to do with this. You will need to fix your system configuration somehow.

**Comment by altDark** [comment]
Thanks for info!
Does anybody have any idea how to fix it?

**Comment by altDark** [comment]
Hi Petr,
you're right. I just tested standard Minecraft Launcher. The same issue there.
So, let's close this issue.
Thanks!

**Comment by peterix** [comment]
Ideally report a bug on https://bugs.mojang.com

**Comment by phit** [comment]
looks like https://bugs.mojang.com/browse/MC-120062
