### ISSUE TITLE
Cant launch FTB Ultimate Reloaded on Debian

### ISSUE THREAD

**Issue by Razer4Lyfe** [MultiMC/MultiMC5#2902]
System Information
(Laptop)
i7-4720HQ
16GB 
GTX 960M
500GB Samsung SSD
-----------------------------
MultiMC version: 0.6.7-1290 on lin64

Operating System: Debian GNU/Linux 10 (buster)

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------
FTB should launch without an issue.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Click Launch.

2.

3.

Suspected cause:
---------------------------
Java 11?

Logs/Screenshots:
----------------------------
https://paste.ee/p/mWB6Z

Additional Info:
---------------------------
Laptop is a Lenovo y50-70
Probably doesn't matter.

**Comment by Heufneutje** [comment]
Java 11 is indeed your problem. You need Java 8 to run modded 1.12.2.

**Comment by Razer4Lyfe** [comment]
Now I just need to find a tutorial on how to uninstall Java 11, and install 8.

**Comment by Heufneutje** [comment]
You don't need to uninstall Java 11. You can have both installed.

It seems Debian Buster doesn't ship OpenJDK 8 in their repos anymore but it seems to still be available in other repos https://stackoverflow.com/questions/57031649/how-to-install-openjdk-8-jdk-on-debian-10-buster.

**Comment by Razer4Lyfe** [comment]
https://superuser.com/questions/1460420/openjdk-8-for-debian-10

"openjdk is still available for Debian 10, but only in the supported openjdk-11 version. openjdk-8 is now unsupported and not officially available in Debian 10 anymore."

**Comment by peterix** [comment]
That means you need to get it from somewhere else. Or use a distro they doesn't remove essential packages.
