### ISSUE TITLE
Syncing the same instance on two pc's 

### ISSUE THREAD

**Issue by Ancient-Dragon** [MultiMC/MultiMC5#2903]
System Information
-----------------------------
MultiMC version: 0.6.7-develop-1338

Operating System: MacOS/Windows

Summary of the issue or suggestion:
----------------------------------------------
Use one instance across two pc's 

What should happen:
------------------------------
I want to be able to select an instance on both my pc and mac without having to export and import everytime.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by chicken3600** [comment]
Try putting your MultiMC installation on the cloud

**Comment by Heufneutje** [comment]
This is not something that MultiMC can accomplish for you.
