### ISSUE TITLE
Erro List update failed: Job 'Download of meta file net.minecraft/index.json' failed to process: https://v1.meta.multimc.org/net.minecraft/index.jso

### ISSUE THREAD

**Issue by crypto768** [MultiMC/MultiMC5#2904]
System Information
-----------------------------
MultiMC version: 1.14

Operating System: Windows

Summary of the issue or suggestion: Na hora de criar uma nova instancia aparece o erro: "List update failed:
Job 'Download of meta file net.minecraft/index.json' failed to process:
https://v1.meta.multimc.org/net.minecraft/index.jso"
----------------------------------------------

What should happen: Abrir sem mensagem, e escolher a versão do jogo
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Heufneutje** [comment]
Your MultiMC is outdated. Update.
