### ISSUE TITLE
MultiMC list update failed

### ISSUE THREAD

**Issue by KarmaTorte** [MultiMC/MultiMC5#2905]
System Information
-----------------------------
MultiMC version:
MultiMC 5.0 - Modified by Hackphoenix
Operating System:
Windows 10
Summary of the issue or suggestion:
----------------------------------------------
MultiMc can't connect to it's server. 

What should happen:
------------------------------
Instance should be created and then playable

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download MultiMC from Hackphoenix.com

2. Launch the Application

Suspected cause:
---------------------------
Wrong Path to the external Server

Logs/Screenshots:
----------------------------
Here the log https://paste.ee/p/sQRJA

![Screenshot_1](https://user-images.githubusercontent.com/57293769/68072993-29337e00-fd8c-11e9-9256-1119f33764d9.png)

Additional Info:
---------------------------
I now what the problem is. The Server is now located at "https://meta.multimc.org/v1/net.minecraft/index.json" instead of "https://v1.meta.multimc.org/index.json" but how do I change the path??

**Comment by Heufneutje** [comment]
You will not get support for any modified version of MultiMC here. You're on your own on that one.

**Comment by Zetabite** [comment]
To add its also a cracked client, yeah, you wont get any support here

**Comment by KarmaTorte** [comment]
Ok. Thanks anyways :D
