### ISSUE TITLE
resource packs not sticking when loading Fabric Instance via MultiMC

### ISSUE THREAD

**Issue by pjlasl** [MultiMC/MultiMC5#2906]
System Information
-----------------------------
MultiMC version: 0.6.7-1375

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
When I open an instance of Minecraft running FabricMC via MultiMC and select a resource pack, the selection is not remembered after I close and reopen the instance. I have to constantly keep selecting my resource pack.

What should happen:
------------------------------
With the normal minecraft launcher, I start an instance of the game select a resource pack from my world and it always remembers it.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a new fabric instance in MultiMC

2. Start a new world and select a resource pack other than the default one

3. Close the instance and start the instance again.

4. The game resets the resource pack back to the default

Suspected cause:
---------------------------
Not sure if it is MultiMC or Fabric. MultiMC and Vanilla don't seems to be a problem. Fabric with Default Minecraft Launcher also does not see this problem.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
Could you like, add info to work with? Elaborate the problem!

**Comment by pjlasl** [comment]
> Could you like, add info to work with? Elaborate the problem!

Sorry. I accidently clicked "Submit" when I created it...It has been updated with more information.

**Comment by Zetabite** [comment]
Might be a mod, or version changing. Could also be due to the texturepack being outdated for this mc version or that mc has trobules loading it due to some options.

**Comment by pjlasl** [comment]
Thank you for your attention. It definitely a mod....I started a new instance with only fabric and it worked. Now to load one by one and figure which one and contact the owner.

**Comment by NezzleGod** [comment]
what was the mod?

**Comment by diaphragm-workplace** [comment]
@peterix damn god mf say the mod name

**Comment by Tarknim** [comment]
Only thread i found about this problem and no solution written 💔🥀

**Comment by 320kg** [comment]
welcome to the internet @Tarknim

**Comment by Tarknim** [comment]
@320kg you didn't find a solution either in that  year did you ?

**Comment by 320kg** [comment]
@Tarknim the solution was to forget about my pile of mods and get a random modpack from modrinth instead once my minecraft version became too old
