### ISSUE TITLE
Cant add account

### ISSUE THREAD

**Issue by VirusRenamon** [MultiMC/MultiMC5#2908]
System Information
-----------------------------
MultiMC version: 0.6.7-1375

Operating System: Windows 10 Home

Summary of the issue or suggestion: 
----------------------------------------------
Cant add account.

What should happen:
------------------------------
Account should be added to client.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Login using Mojang credentials.

2.

3.

Suspected cause:
---------------------------
I have no clue, I have disabled my firewall entirely, even have a fresh from scratch hosts file. Mojang services are all green.

Logs/Screenshots:
----------------------------
Log 0: https://paste.ee/p/oqa3x
Log 1: https://paste.ee/p/rpSQR
Log 2: https://paste.ee/p/lU0S9
Log 3: https://paste.ee/p/mvs9d
Log 4: https://paste.ee/p/PA4D4

Screen of error 1: https://i.imgur.com/NE9NpVF.png
Screen of error 2: https://i.imgur.com/FY3xcLV.png

Additional Info:
---------------------------
I can log in to the regular launcher with my info just fine. I have no clue why this wont work.

**Comment by Zetabite** [comment]
Where did you download the launcher?

**Comment by VirusRenamon** [comment]
> Where did you download the launcher?

https://multimc.org/#Download

**Comment by Zetabite** [comment]
make a backup of mmc and download it again from the website

**Comment by VirusRenamon** [comment]
> make a backup of mmc and download it again from the website

I did as you said and no change.

**Comment by VirusRenamon** [comment]
Just for overkill, since my internet will be cut soon: 

- I am completely up to date (Win10 1903)
- My drivers are up to date.
- Safe mode w/ Networking didn't work.
- I am on the latest 1.8 java
- No AV installed (I use Virustotal before running anything)
- Host file is default.
- Compatibility mode doesn't work.
- No 3rd party firewalls. Adding the program to the firewall doesnt work. Turning firewall altogether doesn't work.

Maybe Windows latest update broke the program or something for newcomers such as myself?

**Comment by VirusRenamon** [comment]
I did something drastic and did a system restore, apparently SimpleWall (a FOSS, good firewall) didn't like it when it was uninstalled. Gave MultiMC perms, everything works.
