### ISSUE TITLE
Multimc crash when changing setting(Vanilla and Modded)

### ISSUE THREAD

**Issue by Whysoseriouslol97** [MultiMC/MultiMC5#2909]
System Information
-----------------------------
MultiMC version:Both Stable And Development

Operating System:Window 7

Summary of the issue or suggestion:
----------------------------------------------
The game freeze and crash when changing some of the settings like connected texture,mipmap or anything that will freeze the game for a moment like changing the resource pack.

Its crash even the vanilla and modded gameplay whenever i change the settings

Usually when i use the the main minecraft and change the setting its just
freeze for a moment and playable after that but with this laucher it crash 
and its annoy me so bad

What should happen:
------------------------------
1.I change the settings

2.its freeze for a moment

3.playable after that

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
https://paste.ee/p/9mYfN here the log file when changing connected texture
https://paste.ee/p/sFXVN here the log file when changing resource pack

Additional Info:
---------------------------
HELP ME

**Comment by Whysoseriouslol97** [comment]
already try to add more permgen and crash

**Comment by Whysoseriouslol97** [comment]
hello

**Comment by Whysoseriouslol97** [comment]
admin

**Comment by Whysoseriouslol97** [comment]
well its gonna be a long day

**Comment by Heufneutje** [comment]
Your problem is not related with MultiMC. Seems to be a crash of your graphics driver.

```
[14:04:04] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[14:04:04] [Client thread/ERROR] [minecraft/Minecraft]: @ Post render
[14:04:04] [Client thread/ERROR] [minecraft/Minecraft]: 1286: Invalid framebuffer operation
```

Also, do NOT spam your issue trying to get support. If anything it will makes people want to help you less.

**Comment by Whysoseriouslol97** [comment]
no that happen happen when i alt tab the game 

i do this with the vanilla launcher and still work normaly even after alt tab

**Comment by Whysoseriouslol97** [comment]
well i been ignore again

**Comment by Heufneutje** [comment]
MultiMC just launches the game. Anything that happens in Minecraft after that is unrelated to MultiMC. And other than these GL errors there is nothing to go off of.

**Comment by Frontear** [comment]
You only have logs with the modded version. Does vanilla work fine? If not, post those logs as well.

**Comment by Whysoseriouslol97** [comment]
yes vanilla works fine

**Comment by Frontear** [comment]
Can you also post your GPU information?

**Comment by Frontear** [comment]
Can you disable optifine and tell me if it works?

**Comment by Whysoseriouslol97** [comment]
already disable optifine and still it dont working,also can you tell me how to see gpu info:u

**Comment by Heufneutje** [comment]
Hold your Windows key and hit R, then type dxdiag in the run box. Then post a screenshot of the window that shows up here.
