### ISSUE TITLE
Modpack Crash

### ISSUE THREAD

**Issue by chicken3600** [MultiMC/MultiMC5#2910]
System Information
-----------------------------
MultiMC version: 0.6.7-1316

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
When I try to launch StoneBlock 2 or SkyFactory 4, the game crashes. I'm not sure if it's only with those two modpacks or with all modpacks that this happens

What should happen:
------------------------------
The game should launch without crashing lol

Suspected cause:
---------------------------
I'm pretty sure it's a problem with MultiMC because when I downloaded Twitch Desktop and tried using that StoneBlock 2 worked fine.

Logs/Screenshots:
----------------------------
https://paste.ee/p/Wojdm

Additional Info:
---------------------------
This also happens on my Mac.
I updated Java and it still didn't work.

**Comment by phit** [comment]
install java 8 and select it in the mmc settings, modded minecraft basically doesnt work on anything newer

**Comment by chicken3600** [comment]
Thx also it was a problem of mine not with multimc srry for wasting ur time
