### ISSUE TITLE
Can't extract native jar

### ISSUE THREAD

**Issue by devlow101** [MultiMC/MultiMC5#2912]
System Information
-----------------------------
MultiMC version: 0.6.7

Operating System: Windows 10

Summary of the issue or suggestion: Just tells me that it is unable to extract native jar for those files. 
----------------------------------------------

What should happen: It should open. 
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. No idea. My game crashed and then this happened.

Logs/Screenshots:
----------------------------
https://paste.ee/p/L7DVp

**Comment by Frontear** [comment]
Can you try deleting the libraries folder in multimc, then getting multimc to redownload them by running the instance?
