### ISSUE TITLE
MultiMC Out of memory HELP

### ISSUE THREAD

**Issue by ProcessTerminalF** [MultiMC/MultiMC5#2913]
System Information
-----------------------------
MultiMC version: Latest Windows

Operating System: Windows

Summary of the issue or suggestion: Crash when launch, it says out of memory but already allocated some memory!
----------------------------------------------

Logs/Screenshots: https://paste.ee/p/hW2Dw
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by ProcessTerminalF** [comment]
this is pissing me off can someone fucking tell me how to fix this fucking shit?

**Comment by Heufneutje** [comment]
1. Don't be a dick about it. Everyone answering questions does so in their own free time and isn't getting paid for it.
2. You're running a 32-bit OS which can't use more than 3.5 GB of RAM regardless of how much RAM you actually have. 1 GB of that is currently assigned to Minecraft which is way too little to run a modded instance.

**Comment by ProcessTerminalF** [comment]
> 1. Don't be a dick about it. Everyone answering questions does so in their own free time and isn't getting paid for it. We have no obligation to help you.
> 2. 1 GB of RAM is currently assigned to Minecraft which is way too little to run a modded instance. Whatever you did to increase the amount you likely did it wrong. I recommend following [this](https://github.com/MultiMC/MultiMC5/wiki/Increasing-Java%27s-memory-allocation) guide,

It still doesnt WORK!!!!!!

**Comment by ProcessTerminalF** [comment]
close this shit.
I fixed my issue by installing x64 java edition. useless fucks!

**Comment by Heufneutje** [comment]
You can close it yourself. It was never a hard issue to solve. You just decided to go about it in pretty much the worst way imaginable.

**Comment by peterix** [comment]
Hmmm... Not the most glorious moment in the history of this bug tracker.
