### ISSUE TITLE
[SUGGESTION] Save the collapsed state of groups

### ISSUE THREAD

**Issue by DarianLStephens** [MultiMC/MultiMC5#2915]
I'm someone who has way, way too many instances, numbering in the 100s.
I recently tried to tidy up my main window a bit by sorting things in to more groups, which I would then collapse and help reduce clutter (Without deleting anything).
However, it seems that the group bars are very sensitive, and will be toggled from any kind of mouse button being pressed while hovering over the bar, rather than having to left-click the plus/minus icon.
So, I went to restart MultiMC to see if things would calm down, but when it reopened, all the groups were expanded again.
I closed the relevant ones once more, and relaunched MultiMC, and they were opened yet again.
Unfortunately, this means that my groups can't be used for reducing clutter the way I was hoping. Organization is still nice, but I think MultiMC should remember if a group was expanded or collapsed between launches.

**Comment by phit** [comment]
this was already added, switch to the development version in the settings if you want it now
https://github.com/MultiMC/MultiMC5/commit/1747f413b9d9a515d8ba6f583bba5985bad5636d

**Comment by DarianLStephens** [comment]
Oh, nice. Would that also happen to have the ability to drag instances on to groups, rather than having to open the 'Change Group' dialog each time?

**Comment by phit** [comment]
no but theres an open issue for it https://github.com/MultiMC/MultiMC5/issues/2153
