### ISSUE TITLE
I'm getting AL lib: (EE) alc_cleanup: 1 device not closed help

### ISSUE THREAD

**Issue by Axodique** [MultiMC/MultiMC5#2916]
System Information
-----------------------------
MultiMC version:
0.6.7-1375
Operating System:
Windows
Summary of the issue or suggestion:
well i'm using the modpack stoneblock and it crashes at the end and gives me this.

What should happen:
------------------------------
Well the game should open normally but it doesn't

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
i don't know

Suspected cause:
---------------------------
unknown

Logs/Screenshots:
----------------------------
https://pastebin.com/S9WQYpht

Additional Info:
---------------------------

**Comment by Frontear** [comment]
Give Minecraft some more RAM. You can do this through MultiMC's settings, or per instance from within the instance settings. It's recommended to give Minecraft at least 1G

**Comment by Frontear** [comment]
Can you instead specify 3G instead of 3000m?

**Comment by Janrupf** [comment]
Not sure what @Frontear meant, but yeah, you need to assign more memory. The message you put into the title not a problem tho.

**Comment by Frontear** [comment]
What I mean is that, although OP has actually specified `-Xms500m -Xmx3000m` in the JVM args (this is visible in the logs), it clearly isn't applying, as java is running out of RAM far too quickly. I was simply wondering if perhaps it could be that `3000m` doesn't do the same thing.

Instead also, OP, please post your full JVM args, test a vanilla minecraft version, and specify your Java version via `java -version`. It's odd that the JVM is unable to work with 3000MB.

**Comment by Janrupf** [comment]
MultiMC itself is appending the `3000m`. It is quite possible that the jvm is running out of memory. Also, the JVM version can clearly be read from the log
```
Java Version: 1.8.0_221, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
```
Looking at the size of the pack, a requirement of at least 4GB is likely.

**Comment by Axodique** [comment]
Sorry i haven't been able to respond, i'm goign to try what you guys have been saying as soon as i get home.
