### ISSUE TITLE
Multi MC Crash Report

### ISSUE THREAD

**Issue by Danbo84** [MultiMC/MultiMC5#2919]
Hi ! When I launch Minecraft, my game crash ! How can I repair that ? Thanks !

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12.2-1.0.0.29.jar)
  ApotheosisCore (Apotheosis-1.12.2-1.11.8.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  LoadingPlugin (Reskillable-1.12.2-1.13.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63 (1).jar)
  AstralCore (astralsorcery-1.12.2-1.10.20.jar)
  CorePlugin (SmoothFont-mc1.12.2-2.1.1.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.8.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 11/18/19 5:37 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: lucraft/mods/heroesexpansion/potions/PotionKryptonitePoison
	at com.nic.tfw.items.ItemSafetyGoggles.onPotionApplicable(ItemSafetyGoggles.java:42)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_733_ItemSafetyGoggles_onPotionApplicable_PotionApplicableEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.entity.EntityLivingBase.func_70687_e(EntityLivingBase.java:764)
	at net.minecraft.entity.EntityLivingBase.func_70690_d(EntityLivingBase.java:743)
	at shadows.deadly.gen.BossItem.initBoss(BossItem.java:161)
	at shadows.deadly.gen.BossItem.place(BossItem.java:144)
	at shadows.deadly.gen.BossFeature.generate(BossFeature.java:39)
	at shadows.deadly.gen.WorldGenerator.terrainGen(WorldGenerator.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1755_WorldGenerator_terrainGen_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onChunkPopulate(ForgeEventFactory.java:769)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:395)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: lucraft.mods.heroesexpansion.potions.PotionKryptonitePoison
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 23 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2249215008 bytes (2145 MB) / 6074400768 bytes (5793 MB) up to 11002183680 bytes (10492 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms128m -Xmx11804m
	IntCache: cache: 0, tcache: 9, allocated: 20, tallocated: 86
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 93 mods loaded, 93 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                  | Source                                            | Signature                                |
	|:------ |:------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2                   | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp                 | 9.42                     | minecraft.jar                                     | None                                     |
	| LCHIJA | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2847-universal.jar           | None                                     |
	| LCHIJA | forge               | 14.23.5.2847             | forge-1.12.2-14.23.5.2847-universal.jar           | None                                     |
	| LCHIJA | ivtoolkit           | 1.3.3-1.12               | minecraft.jar                                     | None                                     |
	| LCHIJA | smoothfontcore      | mc1.12.2-2.1.1           | minecraft.jar                                     | None                                     |
	| LCHIJA | smoothfont          | mc1.12.2-2.1.1           | SmoothFont-mc1.12.2-2.1.1.jar                     | None                                     |
	| LCHIJA | abyssalcraft        | 1.9.13.1                 | AbyssalCraft-1.12.2-1.9.13.1.jar                  | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | aether_legacy       | 1.4.4                    | aether_legacy-1.12.2-v1.4.4.jar                   | None                                     |
	| LCHIJA | akashictome         | 1.2-12                   | AkashicTome-1.2-12.jar                            | None                                     |
	| LCHIJA | antiqueatlas        | 4.6.3                    | antiqueatlas-1.12.2-4.6.3.jar                     | None                                     |
	| LCHIJA | antiqueatlasoverlay | 1.2                      | antiqueatlas-1.12.2-4.6.3.jar                     | None                                     |
	| LCHIJA | placebo             | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                          | None                                     |
	| LCHIJA | apotheosis          | 1.11.8                   | Apotheosis-1.12.2-1.11.8.jar                      | None                                     |
	| LCHIJA | aquaculture         | 1.6.8                    | Aquaculture-1.12.2-1.6.8.jar                      | None                                     |
	| LCHIJA | baubles             | 1.5.2                    | Baubles-1.12-1.5.2 (1).jar                        | None                                     |
	| LCHIJA | astralsorcery       | 1.10.20                  | astralsorcery-1.12.2-1.10.20.jar                  | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | atum                | 2.0.15                   | Atum-1.12.2-2.0.15.jar                            | None                                     |
	| LCHIJA | quark               | r1.6-177                 | Quark-r1.6-177.jar                                | None                                     |
	| LCHIJA | autoreglib          | 1.3-32                   | AutoRegLib-1.3-32.jar                             | None                                     |
	| LCHIJA | betteradvancements  | 0.1.0.77                 | BetterAdvancements-1.12.2-0.1.0.77.jar            | None                                     |
	| LCHIJA | bettercombatmod     | 1.5.6                    | BetterCombat-1.12.2-1.5.6.jar                     | None                                     |
	| LCHIJA | bibliocraft         | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                 | None                                     |
	| LCHIJA | blockcraftery       | 1.12.2-1.3.1             | blockcraftery-1.12.2-1.3.1.jar                    | None                                     |
	| LCHIJA | guideapi            | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63 (1).jar                   | None                                     |
	| LCHIJA | bloodmagic          | 1.12.2-2.4.3-105         | BloodMagic-1.12.2-2.4.3-105.jar                   | None                                     |
	| LCHIJA | bonsaitrees         | 1.1.3                    | bonsaitrees-1.1.3-b156.jar                        | None                                     |
	| LCHIJA | bookshelf           | 2.3.585                  | Bookshelf-1.12.2-2.3.585.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | botania             | r1.10-362                | Botania+r1.10-362.jar                             | None                                     |
	| LCHIJA | chameleon           | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| LCHIJA | clumps              | 3.1.2                    | Clumps-3.1.2.jar                                  | None                                     |
	| LCHIJA | codechickenlib      | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal (1).jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | comforts            | 1.4.1.2                  | comforts-1.12.2-1.4.1.2.jar                       | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | reskillable         | 1.12.2-1.13.0            | Reskillable-1.12.2-1.13.0.jar                     | None                                     |
	| LCHIJA | compatskills        | 1.12.2-1.17.0            | CompatSkills-1.12.2-1.17.0.jar                    | None                                     |
	| LCHIJA | creeperconfetti     | 1.4.2                    | creeperconfetti-1.4.2.jar                         | None                                     |
	| LCHIJA | ctm                 | MC1.12.2-1.0.0.29        | CTM-MC1.12.2-1.0.0.29.jar                         | None                                     |
	| LCHIJA | darkutils           | 1.8.226                  | DarkUtils-1.12.2-1.8.226.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | ptrmodellib         | 1.0.4                    | PTRLib-1.0.4.jar                                  | None                                     |
	| LCHIJA | props               | 2.6.3                    | Decocraft-2.6.3_1.12.2.jar                        | None                                     |
	| LCHIJA | defiledlands        | 1.4.2                    | defiledlands-1.12.2-1.4.2.jar                     | None                                     |
	| LCHIJA | doggytalents        | 1.15.1.4                 | DoggyTalents-1.12.2-1.15.1.4-universal.jar        | None                                     |
	| LCHIJA | orelib              | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround           | 3.6.0.2                  | DynamicSurroundings-1.12.2-3.6.0.2.jar            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | ebwizardry          | 4.2.5                    | ElectroblobsWizardry-4.2.5-MC1.12.2.jar           | None                                     |
	| LCHIJA | enchdesc            | 1.1.15                   | EnchantmentDescriptions-1.12.2-1.1.15.jar         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | enderstorage        | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal (2).jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | tombstone           | 3.6.2                    | tombstone-3.6.2-1.12.2.jar                        | None                                     |
	| LCHIJA | erebus              | 1.0.30                   | Erebus-1.0.30.jar                                 | None                                     |
	| LCHIJA | minerva             | 1.0.13                   | minerva-library-1.0.13.jar                        | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
	| LCHIJA | extraalchemy        | 0.5.2                    | extraalchemy-0.5.2.jar                            | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
	| LCHIJA | forbidden_arcanus   | 1.12.2-1.1.4             | forbidden_arcanus-1.12.2-1.1.4.jar                | None                                     |
	| LCHIJA | forestry            | 5.8.2.387                | forestry_1.12.2-5.8.2.387.jar                     | None                                     |
	| LCHIJA | forgelin            | 1.8.4                    | Forgelin-1.8.4.jar                                | None                                     |
	| LCHIJA | ftblib              | 5.4.4.4                  | FTBLib-5.4.4.4.jar                                | None                                     |
	| LCHIJA | ftbutilities        | 5.4.0.122                | FTBUtilities-5.4.0.122.jar                        | None                                     |
	| LCHIJA | geneticsreborn      | 1.20                     | geneticsreborn-1.12-1.21.jar                      | None                                     |
	| LCHIJA | heroicarmory        | 1.1.3                    | heroicarmory-1.2.0.jar                            | None                                     |
	| LCHIJA | huntingdim          | 1.0.42                   | HuntingDimension-1.12.2-1.0.42.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | ichunutil           | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                        | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | infernalmobs        | 1.7.6                    | InfernalMobs-1.12.2.jar                           | None                                     |
	| LCHIJA | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63 (1).jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest           | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847 (1).jar               | None                                     |
	| LCHIJA | levelup2            | ${version}               | Level+Up!+2-1.1.23-1.12.jar                       | None                                     |
	| LCHIJA | lucraftcore         | 1.12.2-2.4.8             | LucraftCore-1.12.2-2.4.8.jar                      | None                                     |
	| LCHIJA | magicbees           | 1.0                      | MagicBees-1.12.2-3.1.10.jar                       | None                                     |
	| LCHIJA | malisiscore         | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                      | None                                     |
	| LCHIJA | malisisdoors        | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                     | None                                     |
	| LCHIJA | megaloot            | 0.2.40                   | megaloot-1.12.2-0.2.40.jar                        | None                                     |
	| LCHIJA | mobends             | 0.24                     | mobends-0.24_for_MC-1.12.jar                      | None                                     |
	| LCHIJA | morph               | 7.1.3                    | Morph-1.12.2-7.1.3.jar                            | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | mousetweaks         | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                     | None                                     |
	| LCHIJA | naturescompass      | 1.6.0                    | NaturesCompass-1.12.2-1.6.0.jar                   | None                                     |
	| LCHIJA | neat                | 1.4-17                   | Neat+1.4-17.jar                                   | None                                     |
	| LCHIJA | ordinarycoins       | 1.5                      | ordinarycoins-1.12.2-1.5.jar                      | None                                     |
	| LCHIJA | oreexcavation       | 1.4.143                  | OreExcavation-1.4.143.jar                         | None                                     |
	| LCHIJA | harvestcraft        | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zf.jar                   | None                                     |
	| LCHIJA | placeableitems      | 3.3                      | placeableitems-3.3.jar                            | None                                     |
	| LCHIJA | progressivebosses   | 1.5.4                    | ProgressiveBosses-1.5.4-mc1.12.x.jar              | None                                     |
	| LCHIJA | psi                 | r1.1-77                  | Psi-r1.1-77.jar                                   | None                                     |
	| LCHIJA | realdrops           | 1.2.14                   | RealisticItemDrops-1.2.14.jar                     | None                                     |
	| LCHIJA | reccomplex          | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                      | None                                     |
	| LCHIJA | rustic              | 1.1.1                    | rustic-1.1.1.jar                                  | None                                     |
	| LCHIJA | signpost            | 1.06.1                   | signpost-1.12-1.06.1.jar                          | None                                     |
	| LCHIJA | somanyenchantments  | 0.4.3                    | somanyenchantments+V0.4.31.jar                    | None                                     |
	| LCHIJA | storagedrawers      | 1.12.2-5.4.0             | StorageDrawers-1.12.2-5.4.0.jar                   | None                                     |
	| LCHIJA | the-fifth-world     | 0.5                      | the-fifth-world-0.5.1.jar                         | None                                     |
	| LCHIJA | tp                  | 3.2.34                   | tinyprogressions-1.12.2-3.3.34-Release.jar        | None                                     |
	| LCHIJA | twilightforest      | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar     | None                                     |
	| LCHIJA | walljump            | 1.12.2-1.2.3             | walljump-1.12.2-1.2.3 (1).jar                     | None                                     |
	| LCHIJA | waystones           | 4.0.72                   | Waystones_1.12.2-4.0.72.jar                       | None                                     |
	| LCHIJA | xpbook              | v1.1.4                   | xptome-1.12.2-v1.1.4.jar                          | None                                     |
	| LCHIJA | mysticallib         | 1.12.2-1.4.0             | mysticallib-1.12.2-1.4.0.jar                      | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12.2-1.0.0.29.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ApotheosisCore (Apotheosis-1.12.2-1.11.8.jar)
  shadows.ApotheosisTransformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
LoadingPlugin (Reskillable-1.12.2-1.13.0.jar)
  codersafterdark.reskillable.base.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63 (1).jar)
  invtweaks.forge.asm.ContainerTransformer
AstralCore (astralsorcery-1.12.2-1.10.20.jar)
  
CorePlugin (SmoothFont-mc1.12.2-2.1.1.jar)
  bre.smoothfont.asm.Transformer
LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.8.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	[Psi] Active spell: None
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Zetabite** [comment]
Could you please follow the issue template and for the love of god, send the link for the crash report after clicking on upload crash log in your MMC console
