### ISSUE TITLE
Error exitcode 1. Ram

### ISSUE THREAD

**Issue by DthYb** [MultiMC/MultiMC5#2921]
Error occurred during initialization of VM
Could not reserve enough space for 1536000KB

I'm 64 bits

I can't change my ram higher than 1024 max.

**Comment by Janrupf** [comment]
You need to install a 64bit Java version

**Comment by DthYb** [comment]
Thank you 👍 .

**Comment by L0rdLogan** [comment]
Please close this if solved.
