### ISSUE TITLE
I get this when I try to launch a modpack I installed for minecraft

### ISSUE THREAD

**Issue by DMartin-CG** [MultiMC/MultiMC5#2922]
MultiMC version: 0.6.7-1375

Minecraft folder is:
C:/Users/Dalton/Desktop/MultiMC/instances/Valhelsia/minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_231, using 64-bit architecture.

Instance update failed because: Component metadata update task failed while downloading from remote server:
Job 'Download of meta file net.minecraftforge/28.1.92.json' failed to process:
https://meta.multimc.org/v1/net.minecraftforge/28.1.92.json

MultiMC: Log upload triggered at: 27 Nov 2019 18:01:47 -0600

**Comment by peterix** [comment]
That version of Forge is not and will not be supported.
