### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NinoKlein** [MultiMC/MultiMC5#2923]
Help me, i was trying to play sky factory 3 and i got this error

Failed to download file, the file contents differ from what was expected.
Name: jopt-simple-4.6.jar
URL: https://libraries.minecraft.net/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
Filename on disk: jopt-simple-4.6.jar
Path: C:\Users\nkest\Twitch\Minecraft\Install\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar
Exists: File

**Comment by peterix** [comment]
This is not twitch or vanilla support. Your request is invalid.
