### ISSUE TITLE
JUST HELP ME 

### ISSUE THREAD

**Issue by NinoKlein** [MultiMC/MultiMC5#2925]
I was trying to play sky factory 3 on twitch and i got this error

Failed to download file, the file contents differ from what was expected.
Name: jopt-simple-4.6.jar
URL: https://libraries.minecraft.net/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
Filename on disk: jopt-simple-4.6.jar
Path: C:\Users\nkest\Twitch\Minecraft\Install\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar
Exists: File

**Comment by Janrupf** [comment]
Please stop opening issues. We only provide support for MultiMC. Opening further issues may result in a ban from this repository.

**Comment by peterix** [comment]
This is a vanilla launcher bug, btw.
