### ISSUE TITLE
Allow importing fabric modpacks

### ISSUE THREAD

**Issue by martmists** [MultiMC/MultiMC5#2927]
With Fabric becoming increasingly more popular, Fabric Modpacks with the same structure as curse modpacks should be able to be imported in MultiMC. As of right now many packs just distribute as instance, but having the launcher fetch from CurseForge would be the ideal way to create and import packs.

**Comment by peterix** [comment]
This is not something that can be done here.

**Comment by martmists** [comment]
May I ask why not? This seems like a pretty simple thing to do, just download fabric instead of forge.

**Comment by peterix** [comment]
Did twitch implement this? If not, there's nothing for me to do.
