### ISSUE TITLE
MultiMC wont stop crashing

### ISSUE THREAD

**Issue by ray27890** [MultiMC/MultiMC5#2928]
So I was playing 1.7.10 for like 2  minutes before my game crashes, and my system locks up for around a minute, then it unfreezes and MultiMC's launcher freezes and has to be killed by task manager for it to do anything.
Logs: https://paste.ee/p/SCnlE

**Comment by Frontear** [comment]
First, please update your java to the latest version of java 8 (1.8.0_232). Does the issue persist?

**Comment by ray27890** [comment]
Thanks, will try this now.

**Comment by ray27890** [comment]
Yeah, that's made it worse. https://paste.ee/p/u6qrc

**Comment by Janrupf** [comment]
You need to use 64bit Java

**Comment by ray27890** [comment]
I am using 64bit java

**Comment by Janrupf** [comment]
`Java is version 1.8.0_231, using 32-bit architecture.` - You are cleary not. Please check again

**Comment by ray27890** [comment]
I dont wknow where the 64bit java is then because i downloaded java from the main page :/

**Comment by ray27890** [comment]
downloaded 64bit jre and the first problem occurred again. https://paste.ee/p/FUfKb

**Comment by Janrupf** [comment]
Oh god... no idea what heppened there. However, you are loading multiple versions of optifine and such things. You need to clean the instances mod folder (the best would be to delete all mods and then reinstall them, look out for duplicates and version compatibility!)

**Comment by Heufneutje** [comment]
Since it's the Java VM crashing, I'd recommend checking if your drivers are up to date.

**Comment by ray27890** [comment]
will update drivers and reinstall all mods, I'll see if this works.

**Comment by ray27890** [comment]
deleted the repeat version of optifine, game still crashes, updating drivers

**Comment by ray27890** [comment]
updated drivers and deleted repeat optifine, game crashed and MultiMC completely crashed too. I couldn't get logs as MultiMC's launcher crashed

**Comment by Janrupf** [comment]
Does this also happen for now instances?

**Comment by ray27890** [comment]
No

**Comment by peterix** [comment]
Well, I have no idea. And the logs are gone now. Closing.
