### ISSUE TITLE
i can't download forge to 1.14.4 

### ISSUE THREAD

**Issue by Sad-Taco** [MultiMC/MultiMC5#2930]
System Information
-----------------------------
MultiMC version: 0.6.7

Operating System: windows

Summary of the issue or suggestion: i can't install forge to 1.14.4 it doesn't even give me the option to click on the button
----------------------------------------------

What should happen: it should bring up a list of different forge versions that i can install
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
You are not supposed to.
