### ISSUE TITLE
MultiMC does not launch instance.

### ISSUE THREAD

**Issue by Kommando-Droid** [MultiMC/MultiMC5#2931]
Sorry if I did this wrong as I'm kind of new here and not really much of a coding guy and I couldn't really find anything similar through Google.

As the Title says MMC doesn't launch an instance when I click the Launch Offline button, I have no idea what's going on but I think that I might be missing certain files. If that is the case, then how or where do I find them?

Here is the log:

MultiMC version: 0.6.7-1375

Minecraft folder is:
D:/MultiMC/instances/1.7.10/.minecraft

Java path is:
D:/Java64Bit/bin/javaw.exe

Java is version 1.8.0_231, using 64-bit architecture.

Main Class:
  net.minecraft.client.main.Main

Native path:
  D:/MultiMC/instances/1.7.10/natives

Libraries:
  D:/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar (missing)
  D:/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar (missing)
  D:/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.0/lwjgl-2.9.0.jar (missing)
  D:/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.0/lwjgl_util-2.9.0.jar (missing)
  D:/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar (missing)
  D:/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar (missing)
  D:/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar (missing)
  D:/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar (missing)
  D:/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar (missing)
  D:/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar (missing)
  D:/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar (missing)
  D:/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar (missing)
  D:/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar (missing)
  D:/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar (missing)
  D:/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar (missing)
  D:/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar (missing)
  D:/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar (missing)
  D:/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar (missing)
  D:/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar (missing)
  D:/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar (missing)
  D:/MultiMC/libraries/com/google/guava/guava/15.0/guava-15.0.jar (missing)
  D:/MultiMC/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar (missing)
  D:/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar (missing)
  D:/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar (missing)
  D:/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar (missing)
  D:/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar (missing)
  D:/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar (missing)
  D:/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar (missing)
  D:/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar (missing)
  D:/MultiMC/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar (missing)

Native libraries:
  D:/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar (missing)
  D:/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.0/lwjgl-platform-2.9.0-natives-windows.jar (missing)
  D:/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar (missing)
  D:/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar (missing)

Mods:
  [✔️] [1.7.10]+SecurityCraft+v1.8.10
  [✔️] [Minecraft-INSIDE.com] customnpcs_1.7.10d
  [✔️] Archimedes-Ships-Mod-1.7.10
  [✔️] Armourers-Workshop-1.7.10-0.48.3
  [✔️] Better-Storage-Mod-1.7.10
  [✔️] BiomesOPlenty-1.7.10-2.1.0.2308-universal
  [✔️] buildcraft-7.1.22
  [✔️] Carpenter's+Blocks+v3.3.8.1+-+MC+1.7.10
  [✔️] Chisel-2-Mod-1.7.10
  [✔️] CodeChickenCore-1.7.10-1.0.7.47-universal
  [✔️] CodeChickenLib-1.7.10
  [✔️] CoFHCore-[1.7.10]3.1.4-329
  [✔️] Flans Mod-1.7.10-4.10.0
  [✔️] millenaire-6.0.2

Params:
  --username  --version MultiMC5 --gameDir D:/MultiMC/instances/1.7.10/.minecraft --assetsDir D:/MultiMC/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType 

Window size: 1280 x 480

Couldn't extract native jar 'D:/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar' to destination 'D:/MultiMC/instances/1.7.10/natives'
Couldn't extract native jar 'D:/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.0/lwjgl-platform-2.9.0-natives-windows.jar' to destination 'D:/MultiMC/instances/1.7.10/natives'
Couldn't extract native jar 'D:/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar' to destination 'D:/MultiMC/instances/1.7.10/natives'
Couldn't extract native jar 'D:/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar' to destination 'D:/MultiMC/instances/1.7.10/natives'

**Comment by Janrupf** [comment]
Check for your Antivirus cuasing trouble and also that MultiMC can write to `D:\MultiMC`

**Comment by Zetabite** [comment]
Have you launched the instance once online at least?

**Comment by Kommando-Droid** [comment]
Running it online worked, thank you for your help. Everything is running fine now.
