### ISSUE TITLE
Project Ozone 3 has a download problem as well as a launching issue.

### ISSUE THREAD

**Issue by shutnote** [MultiMC/MultiMC5#2932]
System Information
-----------------------------
MultiMC version:

Operating System:
Windows 10 Home 64-bit(10.0, Build 18362)

Summary of the issue or suggestion:
----------------------------------------------
I had many issues with the pack not downloading from the project ozone 3 Zip file and upon downloading it fails to launch. Trying to have the pack reinstall still doesn't fix the issue.

What should happen:
------------------------------
The minecraft window should appear as it loads all the assets.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------
A compatibility issue with the newest version of forge for 1.12.2

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/bwOkR

Additional Info:
---------------------------
After trying different forge versions the pack launch's however I am unable to use this as a fix because mods need the newest version of java. I can get this version of forge running on minecraft's normal launcher however.

**Comment by peterix** [comment]
Log is gone, I can't help you.
