### ISSUE TITLE
Minecraft 1.8.9 crashes as loading up forge (Forge loading screen)

### ISSUE THREAD

**Issue by HyperLemons** [MultiMC/MultiMC5#2934]
System Information
-----------------------------
MultiMC version: 5 (Minecraft 1.8.9)

Operating System: Windows 10 (I can send device specs if needed)

Summary of the issue or suggestion:
Everytime I load up Minecraft very soon while forge is loading the game while crash instantly. Tried with and without mods. The log contained is without mods.
----------------------------------------------

What should happen:
Minecraft should open normally and let me play.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Click launch.

2. Wait like 10-15 sec.

3. Game crash.

Suspected cause: No idea honestly. Minecraft works fine with Badloin and Optifine on 1.8.9 and other versions.
---------------------------

Logs/Screenshots:
----------------------------
https://paste.ee/p/zyRT8

Additional Info:
---------------------------

Please help me out, as I just want to use 5zig. :(

**Comment by Zetabite** [comment]
install 64-Bit java https://www.java.com/download/ choose 64-Bit offline

**Comment by HyperLemons** [comment]
> install 64-Bit java https://www.java.com/download/ choose 64-Bit offline

TYSM! This did infact work. :)

**Comment by peterix** [comment]
@Zetabite now w have a nice wiki article to point people to: https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java
