### ISSUE TITLE
cant edit versions

### ISSUE THREAD

**Issue by NewCrazyLeon** [MultiMC/MultiMC5#2936]
i clicked on add empty made a file and tried to click edit but it doesnt work.

also the others arent working as they earlier did.
maybe its a multimc version issue.

**Comment by Heufneutje** [comment]
You deleted the issue template you're supposed to fill out and as such we can't help you now because you didn't provide enough info.

**Comment by peterix** [comment]
You probably have broken file associations. You need JSON files to open in a text editor.
