### ISSUE TITLE
Possible library file corruption

### ISSUE THREAD

**Issue by Panda-Trueno** [MultiMC/MultiMC5#2937]
System Information:
OS Name	Microsoft Windows 10 Home
Version	10.0.18362 Build 18362
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-59ETPQG
System Manufacturer	Dell Inc.
System Model	Inspiron 5577
System Type	x64-based PC
System SKU	07E1
Processor	Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz, 2801 Mhz, 4 Core(s), 8 Logical Processor(s)
 BIOS Version/Date	Dell Inc. 1.0.4, 6/7/2017
 SMBIOS Version	3.0
 Embedded Controller Version	255.255
 BIOS Mode	UEFI
 BaseBoard Manufacturer	Dell Inc.
 BaseBoard Product	0MVD5F
 BaseBoard Version	A00
 Platform Role	Mobile
 Secure Boot State	On
 PCR7 Configuration	Elevation Required to View
 Windows Directory	C:\WINDOWS
 System Directory	C:\WINDOWS\system32
 Boot Device	\Device\HarddiskVolume1
 Locale	United States
 Hardware Abstraction Layer	Version = "10.0.18362.1"
 User Name	DESKTOP-59ETPQG\natty
 Time Zone	Eastern Standard Time
 Installed Physical Memory (RAM)	8.00 GB
 Total Physical Memory	7.86 GB
 Available Physical Memory	3.26 GB
 Total Virtual Memory	17.9 GB
 Available Virtual Memory	10.2 GB
 Page File Space	10.0 GB
 Page File	D:\pagefile.sys
 Kernel DMA Protection	Off
 Virtualization-based security	Not enabled
 Device Encryption Support	Elevation Required to View
 Hyper-V - VM Monitor Mode Extensions	Yes
 Hyper-V - Second Level Address Translation Extensions	Yes
 Hyper-V - Virtualization Enabled in Firmware	Yes
 Hyper-V - Data Execution Protection	Yes

MultiMC version:
0.6.7-1375
Operating System:
Windows 10
Summary of the issue or suggestion:
Unable to run any instances - some instance will stop running within seconds of starting them, others will get as far as the FML loading window. Even if the instance gets to the FML window, the progress bar will stay at zero. I figured it was just taking a long time to load, so I let it sit for several minutes with no change.

What should happen:

I assume that FML should run and then open Minecraft, but instead some instances stop at the loading screen (the only way to close those is through Task Manager) and others will close on their own without visibly doing anything until the console opens.

Steps to reproduce the issue (Add more if needed):
1. Open MMC 

2. Attempt to run "FTB Direwolf20 1.12" or "FTB Crackpack."

3. Wait until console opens with errors.

Suspected cause:
I'm guessing this is some issue with Java, as I have similar issues with other launchers including ATLauncher and Technic Launcher - neither even start the launcher, MMC is the only one that gets as far as opening the launcher itself.

Logs/Screenshots:
[https://paste.ee/p/i9EB6] (https://paste.ee/p/i9EB6)

Additional Info:
I've monitored the processes in Task Manager, and Java Platform SE Binary opens whenever I try to start an instance. It uses between 55 and 70 MB of memory, and that does not change much while I let it load. Both CPU and disk usage spike then drop when I start, but returns to normal within a second or so.

**Comment by peterix** [comment]
Delete the libraries folder and try again.
