### ISSUE TITLE
[Request] Local Resource Folder

### ISSUE THREAD

**Issue by SomeKittyCat** [MultiMC/MultiMC5#2938]
Hello,

I was wondering if MultiMC could someday introduce something like a "local resource folder" or something where you can put in all the different Saves, Resource Packs, Server Infos, Mods, etc. so that you can just copy them to a new or different Minecraft instance.
For now I just use some Random Minecraft Instance but it would be more convenient and easier to use if it would be a dedicated Menu.

**Comment by peterix** [comment]
That's an interesting idea along the vein of 'shared resources between instances', but more practical.

I like this. It doesn't require a massive pile of tech or wonky automation.
