### ISSUE TITLE
Build failed at pack200

### ISSUE THREAD

**Issue by DariusSG** [MultiMC/MultiMC5#2941]
System Information
-----------------------------
MultiMC version: 0.6.7

Operating System: Windows 10 

Summary of the issue or suggestion:
----------------------------------------------
Build failed at pack200 Lib

What should happen:
------------------------------
It should build

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Build as per instruction from Build.md

Suspected cause:
---------------------------
???

Logs/Screenshots:
----------------------------
![image](https://user-images.githubusercontent.com/39219301/71240031-10365a80-2343-11ea-9b15-1cf8f0482516.png)

Additional Info:
---------------------------

**Comment by peterix** [comment]
If you are getting this error, you are not following the instructions. You have an incompatible compiler.

**Comment by DariusSG** [comment]
Ok so qt 5.6+ is my friend
i got another system running the correct specs but when running cmake, it gives me a error which says that it cannot find query_qmake what is wrong?

I cannot find the log for that though sorry
