### ISSUE TITLE
not sure new to mods basically can't get fun craft to load

### ISSUE THREAD

**Issue by donnymoonshine** [MultiMC/MultiMC5#2942]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------
 can't get instantce to run

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
https://paste.ee/p/yJ4ly

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
You need to install/use Java 8 (64Bit). you currently use Java 11.

**Comment by peterix** [comment]
https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java
