### ISSUE TITLE
Java not found

### ISSUE THREAD

**Issue by netopalis45** [MultiMC/MultiMC5#2944]
While going through the MultiMC Quick Setup on the Java page I get the error that "No versions are currently avaliable". I am able to browse to /usr/bin/java and select that but I still get the same error.

java -version gives me openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-0ubuntu1~18.04.1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

I am running Ubuntu 18.04

**Comment by Frontear** [comment]
Can you manually specify the `java` path?

**Comment by netopalis45** [comment]
I have tried just typing "java" in the box and using "/usr/bin/java" but neither work. I have also tried several different versions of java
