### ISSUE TITLE
MultiMC wont launch anymore even a fresh download

### ISSUE THREAD

**Issue by KevinDenys** [MultiMC/MultiMC5#2946]
System Information
-----------------------------
MultiMC version: 0.6.7

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Launched MultiMC wont open, I can see the process but I am unable to terminate the process

What should happen:
------------------------------
Open

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Double Click MultiMC

Suspected cause:
---------------------------
I have no idea, it worked yesterday

Logs/Screenshots:
----------------------------
https://paste.ee/p/XoIiC

Additional Info:
---------------------------
Logs are from a fresh download, still wont load

**Comment by Heufneutje** [comment]
Cannot reproduce. Likely a system issue and not a MultiMC issue.

**Comment by peterix** [comment]
Move it ou of that Downloads folder into something Windows 10 isn't messing up.

**Comment by tgstyle** [comment]
I am starting to have a similar issue. Mine crashes at downloading the notifications.json

    0.104 D <> Main window shown.
    0.105 D Downloading  "https://files.multimc.org/translations/index_v2.json"
    0.510 D Downloading  "https://status.mojang.com/check"
    0.510 D Downloading  "http://multimc.org/rss.xml"
    0.510 D Downloading  "http://files.multimc.org/update/win32/channels.json"
    0.510 D Downloading  "http://files.multimc.org/notifications.json"

Gets to this point and the window closes.

![image](https://user-images.githubusercontent.com/5832709/72208674-c97be200-3462-11ea-8ca4-e68e72de6b16.png)

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
