### ISSUE TITLE
Not enough allocation of my RAM

### ISSUE THREAD

**Issue by OmeagaBerry** [MultiMC/MultiMC5#2947]
System Information
-----------------------------
MultiMC version:   0.6.7-13752

Operating System:   Windows 10 64-bit

Summary of the issue or suggestion:  MultiMC is not allocating enough Ram that i have said to use, the logs then say that not reserve enough space for the object heap.
----------------------------------------------

What should happen:   run the damn modpack
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Changed the memory allocation in the Java settings in MultiMC application

2. Updated Java and MultiMC

Suspected cause: No clue
---------------------------

Logs/Screenshots:
MultiMC version: 0.6.7-1375

Minecraft folder is:
C:/Users/fredd/Downloads/MultiMC/instances/FTB Presents Skyfactory 2.5/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_231, using 32-bit architecture.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/fredd/Downloads/MultiMC/instances/FTB Presents Skyfactory 2.5/natives

Libraries:
  C:/Users/fredd/Downloads/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  C:/Users/fredd/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-windows.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-32.jar
  C:/Users/fredd/Downloads/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-32.jar

Mods:
  [✔️] [1.7.10]StartingInventory-universal-1.7.10.r03
  [📁] 1.7 (folder)
  [✔️] A Block of Charcoal-1.0
  [✔️] additionalresources-1.7.10_0.1.0.unknown
  [✔️] ae2stuff-rv3-0.5.1.9-mc1.7.10
  [✔️] AppleCore-mc1.7.10-1.3.2
  [✔️] appliedenergistics2-rv3-beta-6
  [✔️] audiodeath-0.6.0-1.7.10r25+e8c5987
  [✔️] Automagy-1.7.10-0.28.2
  [✔️] baconators-1.7.10-2.0.3
  [✔️] bdlib-1.9.4.109-mc1.7.10
  [✔️] BetterBuildersWands-0.6.1-1.7.10r80+358ee26
  [✔️] BiblioCraft[v1.11.5][MC1.7.10]
  [✔️] BiblioWoods[Natura][v1.5]
  [✔️] BigReactors-0.4.3A
  [✔️] Botania r1.8-249
  [✔️] BrandonsCore-1.0.0.12
  [✔️] Carpenter's Blocks v3.3.8.1 - MC 1.7.10
  [📁] carpentersblocks (folder)
  [✔️] ChanceCubes-1.7.10-2.3.2.126
  [✔️] ChatFlow-1.1
  [✔️] ChickenChunks-1.7.10-1.3.4.19-universal
  [✔️] Chisel-2.9.5.11
  [✔️] CodeChickenCore-1.7.10-1.0.7.47-universal
  [✔️] CoFHCore-[1.7.10]3.1.3-327
  [✔️] CoFHLib-[1.7.10]1.1.2-182
  [✔️] compacter-1.1.0.12-mc1.7.10
  [✔️] ComputerCraft1.75
  [✔️] cookingbook-mc1.7.10-1.0.140
  [✔️] CraftTweaker-1.7.10-3.0.13
  [✔️] CustomMainMenu-MC1.7.10-1.9.2
  [✔️] CustomThings-MC1.7.10-0.0.3-55
  [✔️] Decocraft-2.3.3_1.7.10
  [✔️] Ding-MC1.7.10v2
  [✔️] Draconic-Evolution-1.7.10-1.0.2h
  [✔️] DragonMounts-r41-1.7.10
  [❌] dualhotbar-1.7.10-1.6.jar (disabled)
  [✔️] Emotes 1.0.1
  [✔️] EnderCore-1.7.10-0.2.0.39_beta
  [✔️] EnderIO-1.7.10-2.3.0.429_beta
  [✔️] EnderStorage-1.7.10-1.4.7.37-universal
  [✔️] EnderTech-1.7.10-0.3.2.405
  [✔️] Ewy's Workshop-1.1.4
  [✔️] Ex-Astris-MC1.7.10-1.16-36
  [✔️] excompressum-mc1.7.10-1.1.143
  [✔️] Ex-Nihilo-1.38-53
  [✔️] ExtraCells-1.7.10-2.3.14b197
  [✔️] ExtraTiC-1.7.10-1.4.6
  [✔️] extrautilities-1.2.12
  [✔️] fastcraft-1.23
  [✔️] Forbidden Magic-1.7.10-0.575
  [✔️] ftbisland-1.3.1
  [✔️] FTBLib-1.7.10-1.0.18.3
  [✔️] FTBUtilities-1.7.10-1.0.18.3
  [✔️] GardenOfGlass
  [✔️] Hats-4.0.1
  [✔️] HatStand-4.0.0
  [✔️] Headcrumbs-1.7.4
  [✔️] iChunUtil-4.2.3
  [✔️] IguanaTinkerTweaks-1.7.10-2.1.6
  [✔️] ImmersiveEngineering-0.7.7
  [✔️] immersiveintegration-0.6.8
  [✔️] immibis-core-59.1.4
  [❌] InfiniteInvo-1.0.52.jar (disabled)
  [✔️] InGameInfoXML-1.7.10-2.8.1.82-universal
  [✔️] INpureCore-[1.7.10]1.0.0B9-62
  [✔️] InventoryTweaks-1.59-dev-152
  [✔️] ironchest-1.7.10-6.0.60.741-universal
  [✔️] itsrainingfood-1.7.10-1.0.4
  [✔️] Jabba-1.2.2_1.7.10
  [✔️] journeymap-1.7.10-5.1.4p1-unlimited
  [✔️] kleeslabs-mc1.7.10-1.2.9
  [✔️] Loot++-0.24_for_1.7
  [✔️] LootBags-1.7.10-2.0.16
  [✔️] LunatriusCore-1.7.10-1.1.2.21-universal
  [✔️] magicalcrops-4.0.0_PUBLIC_BETA_5
  [✔️] magicalcropsarmoury-4.0.0_PUBLIC_BETA_4
  [✔️] magicalcropsdeco-4.0.0_PUBLIC_BETA_4a
  [✔️] Mantle-1.7.10-0.3.2b
  [✔️] mcjtylib-1.8.1
  [✔️] Mercurius-1.7.10-1.0.1
  [✔️] minefactory-magicalcrops-compatibility-1.2
  [✔️] MineFactoryReloaded-[1.7.10]2.8.2B1-200
  [✔️] ModTweaker2-0.9.6
  [✔️] MooFluids-1.7.10-1.5.01.19a
  [✔️] Morpheus-1.7.10-1.6.21
  [✔️] MouseTweaks-2.4.4-mc1.7.10
  [✔️] mpbasic-1.7.10-1.0.0
  [✔️] mputils-1.7.10-1.0.8
  [✔️] natura-1.7.10-2.2.0.1
  [✔️] neiaddons-1.12.14.40-mc1.7.10
  [✔️] NEIIntegration-MC1.7.10-1.1.2
  [✔️] NEIlootbags-1.7.10-1.1.3
  [✔️] NotEnoughItems-1.7.10-1.0.5.120-universal
  [✔️] OpenBlocks-1.7.10-1.5.1
  [✔️] OpenModsLib-1.7.10-0.9.1
  [✔️] OpenPeripheralAddons-1.7.10-0.5.1
  [✔️] OpenPeripheralCore-1.7.10-1.3
  [✔️] OpenPeripheralIntegration-1.7.10-0.5
  [✔️] OreExcavation-1.1.31
  [✔️] Pam's HarvestCraft 1.7.10Lb
  [✔️] RanchableFluidCows-1.7.10-1.1.5
  [✔️] redlogic-59.1.11
  [✔️] RedstoneArsenal-[1.7.10]1.1.2-92
  [✔️] ResourceLoader-MC1.7.10-1.3
  [✔️] rftools-4.23
  [✔️] sampler-1.59
  [✔️] SimpleAchievements-MC1.7.10-1.1.0-21
  [✔️] SimpleLabels-1.7.10-1.0-9
  [✔️] SimplyJetpacks-MC1.7.10-1.5.3
  [✔️] Slabcraftmod 1.7 - 1.7.10 Forge
  [✔️] Snad-1.7.10-1.6.01.31a
  [✔️] SolarFlux-1.7.10-0.8b
  [✔️] spatialiocompat-build-9
  [✔️] Staircraftmod 1.7 - 1.7.10 Forge
  [✔️] StevesFactoryManagerA93
  [✔️] StorageDrawers-1.7.10-1.10.4
  [✔️] StorageDrawers-Natura-1.7.10-1.1.1
  [✔️] Sync-4.0.1
  [✔️] tcinventoryscan-mc1.7.10-1.0.11
  [✔️] tcnodetracker-1.7.10-1.1.2
  [✔️] TConstruct-1.7.10-1.8.8
  [✔️] Thaumcraft-1.7.10-4.2.3.5
  [✔️] thaumcraftneiplugin-1.7.10-1.7a
  [✔️] thaumicenergistics-1.0.0.5
  [✔️] thermalcasting-0.0.3
  [✔️] ThermalDynamics-[1.7.10]1.2.0-171
  [✔️] ThermalExpansion-[1.7.10]4.1.4-247
  [✔️] ThermalFoundation-[1.7.10]1.2.5-115
  [✔️] TiConAutoToolStation-1.7.10-1.1.2
  [✔️] TiCTooltips-mc1.7.10-1.2.5
  [✔️] Translocator-1.7.10-1.1.2.16-universal
  [✔️] treeGrowingSimulator-0.0.4
  [✔️] twitchcrumbs-mc1.7.10-1.0.10
  [✔️] Waila-1.5.10_1.7.10
  [✔️] WailaHarvestability-mc1.7.10-1.1.6
  [✔️] WAILAPlugins-MC1.7.10-0.2.0-23
  [✔️] Wawla-1.0.5.120
  [✔️] witchery-1.7.10-0.24.1
  [✔️] witherCrumbs-1.7.10-0.3
  [✔️] WR-CBE-1.7.10-1.4.1.9-universal
  [✔️] xprings-1.2.0
  [✔️] YUNoMakeGoodMap-1.7.10-4.0.0.12-universal

Params:
  --username  --version MultiMC5 --gameDir C:/Users/fredd/Downloads/MultiMC/instances/FTB Presents Skyfactory 2.5/.minecraft --assetsDir C:/Users/fredd/Downloads/MultiMC/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType  --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms128m, -Xmx2048m, -Duser.language=en]

Minecraft process ID: 9960

Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Process exited with code 1.

----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Heufneutje** [comment]
You need to install 64-bit Java

**Comment by TobiasSN** [comment]
MultiMC isn't the problem here. Instead, you're not allocating enough RAM. From what I can tell you're only giving in 2048 MB, but it needs at least 2098 MB.

I would recommend increasing it to 3072 MB, and then trying again.

**Comment by Heufneutje** [comment]
Which still won't work without installing 64 bit Java first.

**Comment by TobiasSN** [comment]
Explain?

**Comment by Zetabite** [comment]
You RAM allocation is limited by the kind of bit system you use. 32Bit System cant manage more than 4GB of RAM, 64Bit can

**Comment by Heufneutje** [comment]
While that is true it's not the reason that this is not working. This is a 64-bit system running a 32-bit version of Java. 32-bit Java can only use up to 1.5GB of RAM. This limitation does not exist for 64-bit Java. Therefore installing 64-bit Java is the solution.

**Comment by TobiasSN** [comment]
Okay yeah, but he still isn’t allocating enough RAM.

**Comment by peterix** [comment]
OP is gone.
