### ISSUE TITLE
Instances folder doesn't open

### ISSUE THREAD

**Issue by Killerqu00** [MultiMC/MultiMC5#2948]
System Information
-----------------------------
MultiMC version: latest stable, 0.6.7-1290

Operating System: Ubuntu 18.04

Summary of the issue or suggestion:
----------------------------------------------
I cannot open any instance folder. If I'm trying to launch MultiMC through /opt/multimc/run.sh command and trying to open any instance folder, it says "sudo: no tty present and no askpath program specified".

What should happen:
------------------------------
MultiMC should open folder normally

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch MultiMC

2. Try to open folder of any instance

Suspected cause:
---------------------------
Sudo command was not setuped correctly

Logs/Screenshots:
----------------------------
![gf](https://user-images.githubusercontent.com/47712032/71465138-ccbd6f80-27cc-11ea-8367-bbfaba7dbd19.gif)

**Comment by peterix** [comment]
You have broken MIME type / file association database. Make sure folders don't open with `sudo`, but with a real file manager.

**Comment by TheCynicalLiger** [comment]
run the following command if you have the package to do so 

`xdg-mime default exo-file-manager.desktop inode/directory`

**Comment by Killerqu00** [comment]
Thanks y'all! I solved the problem by giving read and write access to all users in instances folder.
