### ISSUE TITLE
Since Java 8 Is difficult to get Auto Download for the user

### ISSUE THREAD

**Issue by jredfox** [MultiMC/MultiMC5#2949]
Let's be honest most people are not computer people installing mods and using multi mc is even hard for them. So downloading java 8 which you need to download from oracles archive site with username/password is too difficult for them. Be like the minecraft launcher and install java x64/x86 for them.

**Comment by Heufneutje** [comment]
MultiMC doesn't install things. Not even itself. And neither does vanilla. It just bundles the contents of the JRE. If this is done by MultiMC at all that would probably be the way to go about it.

**Comment by jredfox** [comment]
yes it does install things. What do you call the libraries forge, lite loader? Java is just another library it needs to self install to it's own directory since java 8 is difficult to obtain

**Comment by Heufneutje** [comment]
You and I have a very different opinion on what installing things means in that case.

**Comment by jredfox** [comment]
well it's wrong. Look at the instance.json it downloads libraries from minecraft and mojang that are textural files and even forge. 

Java can be the same thing. Go ahead and try and download the JRE 8 you will find yourself wishing multi mc made this self install to

**Comment by Heufneutje** [comment]
I know how libraries work. But the term installing implies running an installer to me. Either way, not important.

I already have a perfectly fine working install of Java 8 on my computer and I do not need MultiMC to automatically download its own. All it is is a waste of space and a potential security risk. If this is going to be a thing at all it needs to be done deliberately with the click of a button like Forge.

**Comment by peterix** [comment]
I wrote https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java to address the issue of having to explain this over and over.

As for shipping some build of Java, yeah. That needs to happen. Closing, this was already in the internal feature tracker :)

**Comment by jredfox** [comment]
last time I checked java 8 wasn't downloadable from their website it must have happened very recently that it changed

**Comment by Zetabite** [comment]
it was never different since java 8

**Comment by jredfox** [comment]
yes it was about a week ago it had java 9 or java 13 I forget but, java 8 the only way was to go to the java oracle archives sign in and download it

**Comment by Zetabite** [comment]
its compatible with vanilla mc

**Comment by jredfox** [comment]
vanilla mc uses java 8 which it downloads automatically look in your minecraft.exe file location then locate runtime folder there it will say java 8
![Capture](https://user-images.githubusercontent.com/9736369/71991121-3fc9db80-31fa-11ea-8c77-0b49450149df.PNG)

**Comment by Zetabite** [comment]
cause you use java 8, but it will run when vanilla even on java 13, java 7 is a bigger problem

**Comment by Zetabite** [comment]
and mc installs its own java or something, its weird, but mmc could technically run it with any java 8+, i dont recommend it tho

**Comment by peterix** [comment]
Vanilla ships an outdated, garbage, potentially dangerous build of JRE 8. The only reason why it is that way is [Unsupported-Intel-GPUs](https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs), and Intel's complete disregard for the issue.

Therefore, Java 8 is the only supported version until further notice. No exceptions.

If someone wants to make things work with later versions, they are delusional.

**Comment by Zetabite** [comment]
can you maybe build in a check what java version is installed and if mmc uses anything than java 8 it wont launch or at least give a notice?

**Comment by peterix** [comment]
If I make any move, it will be to put in a default build of Java that gets automatically downloaded, and to put in better defaults for the heap and GC configuration.

It's the biggest stumbling block for users, and accounts for the vast majority of issues we get on discord and github.

**Comment by peterix** [comment]
The one corner case of crappy intel drivers on Windows 10 should be fairly easy to detect and compensate for...

**Comment by Zetabite** [comment]
hm, makes sense, since implementing that check now and removing it once mmc comes with a default java 8 sounds dumb

**Comment by HellishINC** [comment]
I hope that this will be something that is optional. Those of us who can run package managers will not want a local copy of java floating around.

Off topic slightly, since you brought it up @peterix what jvm arguements are you refering to specifically?
