### ISSUE TITLE
Nothing Launches

### ISSUE THREAD

**Issue by BranTuna** [MultiMC/MultiMC5#2951]
System Information
-----------------------------
MultiMC version: 067-1375

Operating System: Windows 64 bit

Summary of the issue or suggestion:
----------------------------------------------
Each time I try to launch minecraft in either 1.7.10 or 1.12.2 I get a crash with a log that for the heck of me I can't make sense of.

What should happen:
------------------------------
Should definately launch without crashing first-hand.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Tried with no mods installed. Failed.

2. Tried updating Java. Failed.

3. Tried spinning around three times and clapping my hands together. FAILED

Nothing worked. :(

Suspected cause:
---------------------------
Heck I don't know.

Logs/Screenshots:
----------------------------
[https://paste.ee/p/5hulB]

Additional Info:
---------------------------
Whaaaiii?

**Comment by QuImUfu** [comment]
Install and use Java 8.

**Comment by peterix** [comment]
https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java
