### ISSUE TITLE
FTB Horizons 3 code 225

### ISSUE THREAD

**Issue by Maligant2b** [MultiMC/MultiMC5#2952]
System Information
-----------------------------
MultiMC version: 0.6.7-1290

Operating System: Linux Mint 19.1 Cinnamon

Summary of the issue or suggestion:
----------------------------------------------
When I try to start the modpack, it crashes even before the game window opens with code 225. I have tried both Java 8 and 11.

What should happen:
------------------------------
Modpack should open and start normally

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install openjdk8

2. Start multimc 0.6.7 on lin64

3. Download and install FTB Horizons 3 through multimc

4. Attempt to start

Suspected cause:
---------------------------
Something with one of the mods or java maybe? I don't know.

Logs/Screenshots:
----------------------------
https://paste.ee/p/AcUhW

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
Use Java 8 64Bit

**Comment by peterix** [comment]
https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java
