### ISSUE TITLE
Whenever I run a mod from MultiMc, it returns an error and crashes

### ISSUE THREAD

**Issue by BlazingBeam** [MultiMC/MultiMC5#2958]
This problem doesn't occur when I start a vanilla version of the game, please help.

Log:
https://paste.link/p2/kpbcNkb8mDqSahFjNoTzuA.txt

**Comment by BlazingBeam** [comment]
I am using the FTB Academy Mod for this

**Comment by Zetabite** [comment]
pls post the pastee link next time. Also use java 8 64 bit

**Comment by BlazingBeam** [comment]
how do I check if I have java 8 64 bit

**Comment by Zetabite** [comment]
in the launcher auto detect java. but also as you can read in the first few lines, you use java 13

**Comment by BlazingBeam** [comment]
Ok

**Comment by BlazingBeam** [comment]
How will I download java 8 64 bit

**Comment by Zetabite** [comment]
https://java.com/en/download/manual.jsp 64Bit offline

**Comment by BlazingBeam** [comment]
Windows Online or Windows Offline (64 bit) ?

**Comment by Zetabite** [comment]
i literally wrote it. just read

**Comment by BlazingBeam** [comment]
Oh my lord, it workeD!!!! Thank you Zetabite so much!
