### ISSUE TITLE
 Minecraft with mods crashes

### ISSUE THREAD

**Issue by MisterioniX** [MultiMC/MultiMC5#2959]
I launch the world with a special generation of wasteland from the mod, the game crashes, in a super flat world I manage to sit for a short time and then also crash 
crash reports super flat and the world https://yadi.sk/d/-GiP0_ifHDHyZw 
crash reports from the wasteland world  HTTPS://yadi.sk/d/4nAo6xsGBCb6Aw 
mods https://yadi.sk/d/Aryfakow84mQhA

**Comment by Heufneutje** [comment]
English please.

**Comment by MisterioniX** [comment]
changed to English

**Comment by Janrupf** [comment]
Can you please use the integrated upload log function. The download links are not correctly working for me.

**Comment by MisterioniX** [comment]
I tried to download this archive, but it's too big

**Comment by MisterioniX** [comment]
Oh, more precisely .I tried to put this archive in this message, but it's too big
