### ISSUE TITLE
Launched Project Ozone 3 a new way forward and it crashes

### ISSUE THREAD

**Issue by TheHarrySmith** [MultiMC/MultiMC5#2961]
System Information
-----------------------------
MultiMC version: 0.6.7-1316 on OSX64

Operating System: Macbook Mojave V10.14.6 

Summary of the issue or suggestion:
----------------------------------------------
The game crashes 2 minutes in to loading

[https://paste.ee/p/iG1Sh](url)

**Comment by peterix** [comment]
/Applications/MultiMC.app/Contents/MacOS/instances/Project Ozone 3 - A new way forward/minecraft/hs_err_pid20521.log

Post this file

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
