### ISSUE TITLE
Crashing with Impact

### ISSUE THREAD

**Issue by TheDarkAndroid** [MultiMC/MultiMC5#2962]
System Information:
------------------------
16GB DDR4 Ram, Ryzen 5 2600, Radeon RX 580

MultiMC version:
------------------------
MultiMC 5 - Version 0.6.7-1375 on win32

Operating System:
------------------------
Windows 10

Summary of the issue or suggestion:
------------------------
When I try to start Minecraft with Impact on it crashes on startup. I also have OptiFine but it runs when I turn Impact off.

What should happen:
------------------------
The game should run.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add Impact (Jar mod or with custom version);

2. Start Minecraft.

Suspected cause:
---------------------------
Impact causing crash.

Logs/Screenshots:
----------------------------
https://paste.ee/p/WXNPM

Additional Info:
---------------------------

**Comment by peterix** [comment]
```
java.lang.IllegalArgumentException: Wrong mc path C:\Users\AndroidGamer\AppData\Roaming\.minecraft B:\Utility\Program Files\MultiMC\instances\Impacc\.minecraft
```

The mod is wrong. There is no such thing as a `Wrong mc path`. And you can take me as the authority on that, I work on the actual vanilla launcher.

**Comment by TheDarkAndroid** [comment]
How do I fix this?

**Comment by peterix** [comment]
Talk to the impact people. This is their stuff to fix.

**Comment by TheDarkAndroid** [comment]
I already tried to post this on the Impact GitHub and Discord but I got no reply

**Comment by peterix** [comment]
Did you follow their instructions for installing it?
https://github.com/ImpactDevelopment/ImpactIssues/wiki/Installing-with-MultiMC

**Comment by peterix** [comment]
If not, they may be confused about what they are looking at.

**Comment by TheDarkAndroid** [comment]
Yes, I did

**Comment by peterix** [comment]
Have you tried with a supported version of Java? Go grab Java 8.

See: https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java

**Comment by TheDarkAndroid** [comment]
I did

**Comment by peterix** [comment]
But yeah, I'm basically shooting blanks in the dark here, because this thing is just weird, and does things that should not be done.

**Comment by TheDarkAndroid** [comment]
I'm writing here because I tried every troubleshooting option

**Comment by peterix** [comment]
Come to discord. Let's mess with it in a more hands-on way.

**Comment by TheDarkAndroid** [comment]
The MultiMC Discord?

**Comment by peterix** [comment]
Yes.

**Comment by peterix** [comment]
It was due to Java - OpenJ9 should be avoided.
