### ISSUE TITLE
When using offline mode, the skin from the previous online user is fetched.

### ISSUE THREAD

**Issue by GreenBean4323** [MultiMC/MultiMC5#2963]
System Information
-----------------------------
MultiMC version: 0.6.7-1375

Operating System: Windows 10 Home 64 Bit

Summary of the issue or suggestion: 
----------------------------------------------
The first time I created an instance for my niece to play on, I signed in online because I was forced to, then swapped to an offline profile to use for her. I set the username to MHF_Alex in the hopes that it would change to Alex, but it used my slime skin instead.

What should happen: 
------------------------------
Her skin would either be the default offline mode skin or display as the skin fetched from the username I entered

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a new instance (I did 1.15.1)

2. Launch Online

3. Quit Game once loaded

4. Launch Offline

5. Open any world

Suspected cause: 
---------------------------
I believe it's fetching the skin previously saved from the skin servers instead of accessing the skin servers when launched in offline mode.

Logs/Screenshots:
----------------------------
[My main MultiMC screen](https://i.imgur.com/M3aijkN.png)
[My open Minecraft window with the chat open](https://i.imgur.com/mafBCNQ.png)
[My client logs](https://paste.ee/p/gFgo6)

Additional Info:
---------------------------
I remember, back in the olden days, if you used the method to break the official launcher and play any username offline, it would actually still load from the skin servers. I could pick the username Deadmau5 and have the attached ears that Notch gave to him, or pick the username Notch and have the brown and gold Mojang staff cape (plus for a short time you could do it and get the new red and white staff cape, but the cape is no longer associated with the username now). It *all* worked in offline mode, capes and all.

**Comment by peterix** [comment]
This is not how this works anymore. What you want is not possible.

**Comment by GreenBean4323** [comment]
Are you certain? I've done it before with the new version of the official launcher just within the past year (although I'm not telling how so people don't cheat the system again).

**Comment by GreenBean4323** [comment]
I'm 100% certain it's still possible now. I'm not gonna share proof since it'll leak info on how to crack the modern day launcher, but I signed in offline as Deadmau5 and got the ears, then signed in offline as jeb_ and got the Mojang cape, all with their skins fetched from the official servers.

**Comment by peterix** [comment]
This works as intended, as far as I'm concerned.

There is no such thing as an 'offline profile', and you are just breaking the software and complaining about the shards being sharp.
