### ISSUE TITLE
Fullscreen error (windows scaling)

### ISSUE THREAD

**Issue by OnnyCraft** [MultiMC/MultiMC5#2964]
System Information
-----------------------------
MultiMC version:   MultiMC 5 - Version0.6.7 - 1375

Operating System:   Windows 10 Pro

Summary of the issue or suggestion: 
----------------------------------------------
When I open a Vanilla instance (1.12.2 or older) it shows only the top left quarter of the game when in fullscreen mode.

What should happen:
------------------------------
Minecraft should work normal.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create new Instance 

2. Start Instance

3. Press f11

Suspected cause:
---------------------------
That Windows scaling isn't detected.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

 Log: https://paste.ee/p/N3FDA
screenshot: https://imgur.com/3XWwtTE

Additional Info:
---------------------------
When I launch it with 100% instead of 200% it works normal.

When I launch it, the game starts on the bottom right corner of the screen and shows only the top left corner of the game (i assume it starts where it thinks, where the middle of the screen is)

Re- downloading MultiMc hasn't helped.

**Comment by Heufneutje** [comment]
Does this happen with the vanilla launcher as well

**Comment by OnnyCraft** [comment]
@Heufneutje No it doesn't

**Comment by dacid44** [comment]
@OnnyCraft I was having the same problem and fixed it by following this solution: [https://gaming.stackexchange.com/a/346608](https://gaming.stackexchange.com/a/346608)

Just make sure to do it for whichever javaw.exe MultiMC is using. I believe the default is the one in "C:\Program Files (x86)\Common Files\Oracle\Java\javapath".

**Comment by peterix** [comment]
OK... Crazy heuristics and broken high DPI ... I have no idea how this could ever be fixed without the OS being fixed by MS.
