### ISSUE TITLE
Instance update failed because: Component metadata update task failed while downloading from remote server:

### ISSUE THREAD

**Issue by Wtfigohere** [MultiMC/MultiMC5#2966]
System Information
-----------------------------
MultiMC version: MultiMC version: 0.6.7-1290

Operating System: Linux Mint 19.3

Summary of the issue or suggestion:
----------------------------------------------
When attempting to launch modpacks, it fails to download the necessary files and crashes on launch.

What should happen:
------------------------------
Everything should download and the game should launch.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Click Game Icon in MultiMC

2. Crash

Suspected cause:
---------------------------
Guessing this file is not there..
Getting a 404 when i put it in browser.
https://meta.multimc.org/v1/net.minecraftforge/28.1.107.json

Logs/Screenshots:
----------------------------
MultiMC version: 0.6.7-1290

Minecraft folder is:
/home/wtfigohere/.local/share/multimc/instances/Limitless-1.09/minecraft

Java path is:
/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

Java is version 1.8.0_232, using 64-bit architecture.

Instance update failed because: Component metadata update task failed while downloading from remote server:
Job 'Download of meta file net.minecraftforge/28.1.107.json' failed to process:
https://meta.multimc.org/v1/net.minecraftforge/28.1.107.json

Additional Info:
---------------------------

**Comment by peterix** [comment]
Works as intended.

Forge above 1.12 is not supported.

**Comment by Jackc2021** [comment]
i got this and im using fabric
