### ISSUE TITLE
Wiki Features Fabric

### ISSUE THREAD

**Issue by IceCryptonym** [MultiMC/MultiMC5#2967]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------
The wiki home in the Features section has
`Forge and LiteLoader integration` it should be `Forge, Fabric and LiteLoader integration`

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------

Additional Info:
---------------------------

**Comment by peterix** [comment]
Fixed.
