### ISSUE TITLE
No Forge versions are currently available for Minecraft 1.12.2

### ISSUE THREAD

**Issue by spiwocoal** [MultiMC/MultiMC5#2968]
I'm trying to play Minecraft 1.12.2 with some mods using Forge, but when I click Install Forge, it says there are no versions of Forge currently available for Minecraft 1.12.2, what could be causing this?

Here is my [MultiMC-0.txt](https://pastebin.com/ezLu36Xn)

**Comment by Heufneutje** [comment]
Seems fine to me.
![image](https://user-images.githubusercontent.com/1357231/72559942-45808a80-38a6-11ea-9742-bc5832094a90.png)
