### ISSUE TITLE
java.lang.reflect.InvocationTargetException with Enigmatica 2: Expert

### ISSUE THREAD

**Issue by apozho** [MultiMC/MultiMC5#2969]
System Information
-----------------------------
MultiMC version: 0.6.7-1290

Operating System: 64-bit Debian GNU/Linux 10 (buster)

Summary of the issue or suggestion: 
----------------------------------------------
instantly getting "java.lang.reflect.InvocationTargetException" error when trying to launch modded pack that works properly on Windows and through the vanilla launcher.

What should happen: 
------------------------------
Pack should run normally

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install Enigmatica 2: Expert from [this zip file](https://www.curseforge.com/minecraft/modpacks/enigmatica2expert/files/2854637)

2. Attempt to launch pack

---------------------------

Logs/Screenshots:
----------------------------
[log](https://paste.ee/p/8KMYo)

**Comment by Heufneutje** [comment]
Get Java 8. You can't run modded MC 1.12 with Java 11.

**Comment by apozho** [comment]
Oh god how did I not notice that sorry
