### ISSUE TITLE
i am unable to install forge 

### ISSUE THREAD

**Issue by luckyluke7227** [MultiMC/MultiMC5#2970]
- [ ] #@

1. 

- 

> ### _`[](url)`_

System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by luckyluke7227** [comment]
![Uploading 2020-01-18.png…]()

**Comment by Heufneutje** [comment]
I'm not sure what you tried to do here but please fill out the issue template properly. We cannot help you otherwise.
