### ISSUE TITLE
Resource packs window hover descriptions need own strings

### ISSUE THREAD

**Issue by TechniKris** [MultiMC/MultiMC5#2971]
System Information
-----------------------------
MultiMC version: 0.6.7-1375

Operating System: Windows 10 Home 1903 (comp. 18362.592), 64-bit

Summary of the issue or suggestion:
----------------------------------------------
When you hover over a column header in the Resource packs menu, descriptions from the Loader mods menu appear, e.g. hovering over "Name" shows "The name of the mod.".

What should happen:
------------------------------
The text appearing should be appropriate to the Resource packs menu, e.g. hovering over "Name" should show "The name of the resource pack.".

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Select an instance

2. Hit "Edit Instance" button

3. Open "Resource packs" tab

4. Hover over the tickboxes column, "Name", "Version" or "Last changed" header

Suspected cause:
---------------------------
Hover boxes use same strings as ones in the "Loader mods" menu. They should use separate strings in the code (and in turn, in translations).

Logs/Screenshots:
----------------------------
![image](https://user-images.githubusercontent.com/30842158/72680827-a4b8e780-3abe-11ea-883a-40d15bbf2dd1.png)

Additional Info:
---------------------------
The "Version" column feels mislabeled in that menu. Because resource packs, unlike mods, don't have clearly stated versions, the column's only purpose is differentating .ZIPs from folders. I think it could be renamed or maybe even removed at some point.

**Comment by peterix** [comment]
Yeah, the same UI control is used.
