### ISSUE TITLE
Failed to Start Minecraft

### ISSUE THREAD

**Issue by AwesomeBros132** [MultiMC/MultiMC5#2973]
System Information
-----------------------------
MultiMC version:
0.6.7
Operating System:
osx64 (macOS Mojave)
Summary of the issue or suggestion:
----------------------------------------------
MultiMC failed to start/launch Minecraft.

What should happen:
------------------------------
Minecraft should launch.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add a modpack

2. Launch the modpack

Suspected cause:
---------------------------
Having Java (JDK) 8 or above. I have Java 13

Logs/Screenshots:
----------------------------
Access the log [here](https://paste.ee/p/ZUnTg)

Additional Info:
---------------------------
None.

**Comment by Zetabite** [comment]
You need to use Java 8, currently you use Java 12, anything over Java 8 doesnt work with modded mc

**Comment by AwesomeBros132** [comment]
> You need to use Java 8, currently you use Java 12, anything over Java 8 doesnt work with modded mc
I used Java 7 before, though I didn’t seem to work.
Should I try Java 8, I don’t think it’ll make a difference because I have been informed that the Java 8 update removed a feature that is needed for the modpack(s) to run.

**Comment by Zetabite** [comment]
yes try it. https://java.com/en/download/manual.jsp Select the Offline (64-bit) download

**Comment by ipatix** [comment]
Is this a problem with MultiMC, Forge or Minecraft?

**Comment by Zetabite** [comment]
> Is this a problem with MultiMC, Forge or Minecraft?
> 
> Because if it's an issue with MultiMC, I'd really appreciate getting this fixed.

what problem do you mean?

**Comment by ipatix** [comment]
@Zetabite The crash which @AwesomeBros132 mentioned.
Because I'm running into the same problem and would rather use a more recent OpenJDK.

**Comment by Zetabite** [comment]
What OpenJDK do you use?

**Comment by ipatix** [comment]
I've tried all from 9 to 13 without success.

**Comment by Zetabite** [comment]
The problem lies in forge, it only works with a java 8 based java release, it doesnt work with newer. MultiMC has nothing to do with it.

**Comment by Zetabite** [comment]
You can in fact run vanilla mc with newer java

**Comment by ipatix** [comment]
@Zetabite Okay, thanks. That's what I wanted to know :)
