### ISSUE TITLE
[Feature Request] Detect Twitch installed modpacks

### ISSUE THREAD

**Issue by jaideepheer** [MultiMC/MultiMC5#2974]
System Information
-----------------------------
MultiMC version: 0.6.7

Operating System: Windows 10 Pro

Summary of the issue or suggestion:
----------------------------------------------
Automatically detect installed Twitch modpacks to launch via MultiMC.

What should happen:
------------------------------
Installed modpacks on twitch should be detected by multimc and should be launchable.
A configuration can be provided to browse to the minecraft `Instances` folder created by the twitch launcher. This folder has subfolders for each installed modpack.

Each modpack's folder also has two files related to twitch, `manifest.json` and `minecraftinstance.json`. These files can be read to get information about the modpack required to use it as an multimc instance.

**Comment by jaideepheer** [comment]
This will allow using twitch to update/download modpacks while using multimc to launch them.

**Comment by peterix** [comment]
No.
