### ISSUE TITLE
Crashed minecraft launch

### ISSUE THREAD

**Issue by sodomon2** [MultiMC/MultiMC5#2975]
System Information
-----------------------------
MultiMC version:
0.6.7-custom
Operating System:
Alpine Linux
Summary of the issue or suggestion:
----------------------------------------------
MultiMC failed to start/launch Minecraft.

What should happen:
------------------------------
Minecraft should launch.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.launch minecraft

Suspected cause:
---------------------------
JDK 8 version as it is a core dump error at the end

Logs/Screenshots:
----------------------------
Access the log [here](https://paste.ee/p/uVDya)

Additional Info:
---------------------------
None

**Comment by spannerman79** [comment]
Log is incomplete/modified outside of MultiMC.

Missing hardware ID's and missing base info.

**Comment by sodomon2** [comment]
The record is not modified, I uploaded it as soon as I got the error

**Comment by QuImUfu** [comment]
This is a issue with your version/type of java install. Nothing MultiMC could fix.  
Report to whatever Java vendor/distribution you are using. (i.e. probably alpines packaging team) or build OpenJDK 8 Java yourself ([source](http://hg.openjdk.java.net/jdk8u/jdk8u-dev))
