### ISSUE TITLE
make install does not correctly install

### ISSUE THREAD

**Issue by ipatix** [MultiMC/MultiMC5#2981]
System Information
-----------------------------
MultiMC version:
bc98181ec274dfc933c5c0207943f9de1dbaf1d1

Operating System:
Linux, Debian Sid, 64 bit

Summary of the issue or suggestion:
----------------------------------------------
After compiling MultiMC and running `make install`, the Makefile installs the following files:
```
-- Install configuration: ""
-- Installing: /usr/local/./MultiMC
-- Installing: /usr/local/bin/libMultiMC_nbt++.so
-- Installing: /usr/local/bin/jars/NewLaunch.jar
-- Installing: /usr/local/bin/jars/JavaCheck.jar
-- Installing: /usr/local/bin/libMultiMC_quazip.so
-- Installing: /usr/local/bin/libMultiMC_unpack200.so
-- Installing: /usr/local/bin/libMultiMC_rainbow.so
-- Installing: /usr/local/bin/libMultiMC_iconfix.so
-- Installing: /usr/local/bin/libMultiMC_logic.so
-- Set runtime path of "/usr/local/bin/libMultiMC_logic.so" to ""
-- Installing: /usr/local/bin/libMultiMC_gui.so
-- Set runtime path of "/usr/local/bin/libMultiMC_gui.so" to ""
-- Installing: /usr/local/bin/MultiMC
-- Set runtime path of "/usr/local/bin/MultiMC" to "$ORIGIN/"
```
When looking carefully you can see the follwing line:
```
-- Installing: /usr/local/./MultiMC
```
Installting the launchscript to /usr/local/./MultiMC does not seem to make any sense as files usually go into bin, lib, share, etc.

Furthermore, the actual binary get's installed to `/usr/local/bin` which cannot be run directly due to the following error:
```
MultiMC: error while loading shared libraries: libMultiMC_unpack200.so: cannot open shared object file: No such file or directory
```

What should happen:
------------------------------
If the launch script is mandatory to run MultiMC, the launch script should go to `/usr/local/bin` and all the libraries should go to something like `/usr/local/lib/multimc/`. `*.so` and `*.jar` files do not belong into `*/bin/`

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. `git clone https://github.com/MultiMC/MultiMC5/`

2. `git submodule update --init --recursive`

3. `mkdir build && cd build`

4. `cmake ..`

5. `make`

6. `su -c "make install"`

Suspected cause:
---------------------------
Something in CMakeLists is not correct?

Logs/Screenshots:
----------------------------
N/A

Additional Info:
---------------------------
I don't quite understand the purpose of the MultiMC launch script. If all libraries get installed to the correct directories, there should be no need to mess with any environment variables.

**Comment by peterix** [comment]
You need to use a different install layout. By default, it makes a portable tarball layout

**Comment by ipatix** [comment]
Oh okay, that makes a lot more sense now.

Is there currently any way to use a non-portable layout? Personally, I don't desperately need the portable layout, but if it is possible already, I'd happily use it.

**Comment by spannerman79** [comment]
```
If the launch script is mandatory to run MultiMC, the launch script should go to /usr/local/bin and all the libraries should go to something like /usr/local/lib/multimc/. *.so and *.jar files do not belong into */bin/
```
 From https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html
> The /usr/local hierarchy is for use by the **system administrator** when installing software locally

99% of the time when a user that comes onto the discord server and that does use a deb based distro of some kind the _only_ time that su/sudo is reequired is for the initial setup (.desktop etc).  After that any further updates are handled within MultiMC.  The path that is used is the users own home directory which ensures correct permissions for both the files read/written and for the JVM.

Installing to `/usr` will require either a manual update (downloading the compressed file and extracing it into the location required) or running MultiMC with root level rights.  Both require root level read/write access which 99% of the time later on will cause issues especially if a user hasn't moved their instance directory to home.

Technically you are correct - but in practise it isn't exactly wise.

**Comment by ipatix** [comment]
Well yeah, now that I am aware of how things work, this is not a big issue for me and can be closed.
