### ISSUE TITLE
MultiMC process exited with code 255

### ISSUE THREAD

**Issue by Jeekie22** [MultiMC/MultiMC5#2982]
System Information
-----------------------------
MultiMC version:0.6.7-1290

Operating System:Ubuntu 18.04

Summary of the issue or suggestion:
----------------------------------------------
When i try to open minecraft, everything loads fine, but then crashes instantly when i try to join a server

What should happen:
------------------------------
It should just let me into the server, it was working around 5 minutes ago perfectly fine, and then i reloged and it broke

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
I dont really know how this issue came to be, ive reinstalled the instance, looked at other posts and cant find any answers

Suspected cause:
---------------------------
No idea

Logs/Screenshots:
----------------------------
https://paste.ee/p/d8dCq

Additional Info:
---------------------------
It was working perfectly fine before, but now it isnt. Im using fabric with optifabric and optifine.

**Comment by Jeekie22** [comment]
Normal minecraft on optifine works fine, using the normal minecraft launcher

**Comment by Zetabite** [comment]
you are not loading any kinds of mods in the instance, not even fabric. also check for updates.

**Comment by spannerman79** [comment]
The only two things I can think of is the following;

1. Ensure your user is part of the video group.  Not sure if that applies for *buntu but it does for both Fedora and Arch - so I'm going to assume its the same for *buntu.
2. This `Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build` specific the "Private Build" that bothers me.  Usually repos don't have "Private Builds" unless you are using some weird ppa.

Personally - just to test I'd grab https://adoptopenjdk.net/installation.html#linux-pkg just for the sake of testing. You can always remove both the repo and the deb later on.

If your wondering - Arch user with AdoptOpenJDK with OpenJ9 outputs;
```
java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
Eclipse OpenJ9 VM (build openj9-0.18.1, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200122_511 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - 8cf8a30581 based on jdk8u242-b08)
```

**Comment by Jeekie22** [comment]
Hey,
Thanks alot for the fast reply!
It works fine now, thank you so much!

**Comment by spannerman79** [comment]
@Jeekie22 if thats the case and your issue is resolved close this issue.
