### ISSUE TITLE
Ram keeps going above 8GB

### ISSUE THREAD

**Issue by HandThigh** [MultiMC/MultiMC5#2983]
System Information
-----------------------------
MultiMC version:
0.6.7-1375 win32
Operating System:
Windows 10
Summary of the issue or suggestion:
----------------------------------------------
Memory keeps going above 8GB even after i allocated max ram 8000MB

What should happen:
------------------------------
Ram shld be below 8G

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Download any mod pack (150 packs and above)

2.Run pack 

3.

Suspected cause:
---------------------------
Not sure 

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by spannerman79** [comment]
Not a MultiMC issue.  

Even if you use the vanilla launcher and used those mods and set ram to 8GB/8192MB you will have the same issue.
