### ISSUE TITLE
Unavailable required libraries download link

### ISSUE THREAD

**Issue by Loner-Knowledge** [MultiMC/MultiMC5#2984]
System Information
-----------------------------
MultiMC version:0.6.7-develop-1415

Operating System:Windows 7

Summary of the issue or suggestion:
----------------------------------------------
Unable to fetch the required libraries when starting Ultimate Alchemy Exam 0.1.0.

What should happen:
------------------------------
Cannot download forge-1.12.2-14.23.5.2796-universal.jar

Steps to reproduce the issue :
-------------------------------------------------------------
1.Open MultiMC5 and launch Ultimate Alchemy Exam 0.1.0

2.Get an error

Suspected cause:
---------------------------
The download link is `http://117.128.6.12/cache/files.minecraftforge.net/maven/...` instead of `http://files.minecraftforge.net/maven/...`
It looks like there is a problem with `117.128.6.12`, using another link can download `forge-1.12.2-14.23.5.2796-universal.jar` normally.

Logs/Screenshots:
----------------------------
```
Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance Ultimate+Alchemy+Exam-0.1.0' failed to process:
http://117.128.6.12/cache/files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2796/forge-1.12.2-14.23.5.2796-universal.jar?ich_args2=469-03150820018867_ee1644d3974667628121e6bcb5a40011_10001002_9c896c2cd0c2f2d6963d518939a83798_fad7b332a13377a2031afcdec69bf362
```

**Comment by Loner-Knowledge** [comment]
In fact the problem is in the download of `forge-1.12.2-14.23.5.2796-universal.jar`
Create a new normal 1.12.2 instance, and then install the 14.23.5.2796 version of Forge, the same error will still be reported.

**Comment by spannerman79** [comment]
As a quick test I did a fresh import of that pack

No issues from import, download and run https://paste.ee/p/5jyBz

Could of been an issue with forge CDN - or your internet.  Either way it (currently) isn't a MultiMC issue.
