### ISSUE TITLE
Crash while starting minecraft 1.14.4 instance ( World downloader Mod)

### ISSUE THREAD

**Issue by aaronwills** [MultiMC/MultiMC5#2985]
System Information
64bit
Intel core 2 quad Q6600
windows 7
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
Game crashes while launching
----------------------------------------------

What should happen:
------------------------------
well it should launch into minecraft with the worlddownloader mod installed, has worked on other peoples computers as i followed the download process for that specific mod.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Start minecraft 1.14.4 instance with the worlddownloader mod installed

2.

3.

Suspected cause:
I honestly wouldn't have a clue
---------------------------

Logs/Screenshots:
https://paste.ee/p/K91LX
----------------------------

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
World Downloader is a forge mod iirc and since there is no forge for 1.14 for MMC you will need vanilla launcher to use the mod

**Comment by aaronwills** [comment]
What did he do different to me in this video? https://youtu.be/1vvOP5PtFLw

**Comment by Heufneutje** [comment]
You downloaded the wrong version.
