### ISSUE TITLE
Crash when closing 'Edit Instance' window

### ISSUE THREAD

**Issue by dunekird** [MultiMC/MultiMC5#2986]
System Information
-----------------------------
MultiMC version: 0.6.7-1290

Operating System:  x86_64 GNU/Linux Debian Buster 10.2

Summary of the issue or suggestion:
----------------------------------------------
When pressing the 'Close' button under the 'Edit Instance' window, MultiMC crashes. The same happens using the X in the title bar.

What should happen:
------------------------------
The 'Edit Instance' window should close.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open 'Edit Instance'

2. Press 'Close' or 'X'.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/r/vEqFe/0

Additional Info:
---------------------------
Using KDE Plasma provided by Debian.
I have installed qt5-default package and dependencies

**Comment by dunekird** [comment]
Further tests show that the crash happens when under any subsection, but 'Settings' and 'Other Logs'

**Comment by spannerman79** [comment]
Buster might be supplying a buggy build of qt5.  I saw on discord someone else having this same issue and it pointed to a bugged qt build provided by debian.

**Comment by dunekird** [comment]
That's probably right. I found this bug [https://bugreports.qt.io/browse/QTBUG-68393](url) that seems related to the problem. Moreover, it is reported by Petr Mrazek, who mantains MultiMC.
The only solution is to update to a recent version. Thank you.
