### ISSUE TITLE
Minecraft Modpack won't complete the Launch on Manjaro then crashes 

### ISSUE THREAD

**Issue by Sasalu123** [MultiMC/MultiMC5#2987]
System Information
-----------------------------
MultiMC version: multimc5 0.6.7-2 
- also tried the multimc-git 

Operating System: Manjaro KDE Plasma

Summary of the issue or suggestion:
----------------------------------------------
-the Modpack client is crashing
-normal Minecraft is launching
-tried a different Modpack as a comparison also didn't work

What should happen:
------------------------------
-Minecraft Modpack should launch to completion 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. install in pamac any Multimc version

2. use jdk8 (open-jdk8)

3. launch a Modpack

4. Wait until it's 3/7 in the launcher at some point, maybe when transitioning to 4/7 

5. Crash

Suspected cause:
---------------------------
Something in Launching 3/7 or 4/7
at least not the java version since i only get 6 issues and in other version i get over 200 and it at least starts the launcher also because it worked on Linux Mint

Logs/Screenshots:
----------------------------
https://paste.ee/p/Q5Dz6
https://i.imgur.com/SYyIbGS.png [The 3/7 ; this is not right before the crash just the beginning of 3/7

Additional Info:
---------------------------
It worked with Linux Mint

**Comment by QuImUfu** [comment]
you are using the OpenSource NVIDIA driver (nouveau). That driver does not work with modded Minecraft without some tinkering.

**Comment by Sasalu123** [comment]
Thank you for noticing and a shame that it is not working with nouveau
