### ISSUE TITLE
Stuttering and Low GPU Usage in MultiMC (versions below 1.14)

### ISSUE THREAD

**Issue by Petrifyingz** [MultiMC/MultiMC5#2989]
System Information:
CPU: Intel Core i7-9700KF
GPU: Nvidia RTX 2060
RAM: 16GB DDR4

-----------------------------
MultiMC version: 0.6.7-1375

Operating System: Windows 10 64bit

Summary of the issue or suggestion: 
------------------------------
Games below version 1.14 using low gpu usage for shaders (haven't tested 1.13) and instances just generally stuttering (1.8.9 stutters the most). Issue came out of nowhere, everything was running fine but one day shaders on 1.8 used low gpu, then it started stuttering afterwards. 

The official launcher is working completely fine and has none of these issues. Even with mods and configs copied to it.

What should happen: 
------------------------------
Instances should be using full advantage of the GPU and there should be no stuttering

Steps to reproduce the issue (Add more if needed): 
------------------------------
unknown 

Suspected cause: 
---------------------------
unknown

Logs/Screenshots:
----------------------------
https://paste.ee/p/at2Db

not sure if that helps but yeah

Additional Info:
---------------------------
video (sorry for low quality my recording settings were messed up lol) https://www.youtube.com/watch?v=I69Zvi1LD7g&feature=youtu.be

**Comment by Zetabite** [comment]
do you have the "-Xmn2G" in your launch parameters in vanilla mc too?

**Comment by Petrifyingz** [comment]
> 
> 
> do you have the "-Xmn2G" in your launch parameters in vanilla mc too?

no, my parameters are -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
in the official launcher

**Comment by Zetabite** [comment]
could remove that parameter than

**Comment by Petrifyingz** [comment]
> 
> 
> could you remove the other parameters than. so that only RAM argument and the Locale argument remains.

in the official launcher? the official launcher works fine its just multimc causing issues

**Comment by Zetabite** [comment]
no i mean in mmc

**Comment by Zetabite** [comment]
like this: https://i.imgur.com/gIrQ91H.png https://i.imgur.com/v8l5gwM.png

**Comment by Petrifyingz** [comment]
> 
> 
> like this: https://i.imgur.com/gIrQ91H.png https://i.imgur.com/v8l5gwM.png

assuming you meant parameters for MMC then.

my MMC parameters are -Xmn2G -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=60 -XX:-UseAdaptiveSizePolicy

**Comment by Zetabite** [comment]
exactly. could you pls remove theme

**Comment by Petrifyingz** [comment]
> 
> 
> exactly. could you pls remove them and launch MC and report if it laggs less

Done and I think it's stuttering less, can't extensively test rn though. GPU usage is still a problem

**Comment by Zetabite** [comment]
you using same optifine + shader settings?

**Comment by Petrifyingz** [comment]
> 
> 
> you using same optifine + shader settings?

Yes. The same settings are used in 1.14.4 but there it uses all the gpu, as it should, anything below 1.14 caps around 50% - 70%

**Comment by QuImUfu** [comment]
hmm, possibly some Driver magic.  
Can you try whether renaming MultiMC.exe to Minecraft.exe changes anything?

**Comment by Petrifyingz** [comment]
> 
> 
> hmm, possibly some Driver magic.
> Can you try whether renaming MultiMC.exe to Minecraft.exe changes anything?

Did that and nothing changed

**Comment by Zetabite** [comment]
Well i dont really know whats goin on, since MMC only launches the game, the rest should be identical. Might need @peterix to narrow down the issue.

**Comment by Petrifyingz** [comment]
Stuttering is fixed now, also turned off threaded optimization in the nvidia control panel for javaw. GPU seems bugged where it uses less the higher the render distance (ex: tiny render distance uses 100% gpu, whereas render distance on 14 uses like 70% while using shaders). I don't think its an MMC specific issue since it happens with the official launcher too.
