### ISSUE TITLE
Error while loading a modpack. (failed to download 31.1.0.json)

### ISSUE THREAD

**Issue by SpidFightFR** [MultiMC/MultiMC5#2994]
Hello, i have a little problem.

i have downloaded a modpack (All The Mods 5 in 1.15.2 to be exact), and i get an error wich tells me that i don't have a "31.1.0.json" file and that the launcher can't download it.
Is there a way to manually download the file?

Can anyone help me please? Thank you by advance.

(PS sorry for my bad english)

**Comment by Zetabite** [comment]
Pretty sure ATM5 is forge based. Forge isnt supported by MMC from Version 1.13 and up. Either use vanilla launcher or use fabric based modpacks.

**Comment by SpidFightFR** [comment]
ok

**Comment by salomj** [comment]
What is the decision on not support forge after 1.13?

**Comment by Heufneutje** [comment]
https://multimc.org/posts/forge-114.html
