### ISSUE TITLE
Failed to upload skin

### ISSUE THREAD

**Issue by Frisk17** [MultiMC/MultiMC5#2995]
System Information
-----------------------------
MultiMC version: 0.6.7

Operating System: MacOSX Mojave

Summary of the issue or suggestion:
----------------------------------------------
When I upload my skin I get a message saying "Failed to upload skin!"

What should happen:
------------------------------
The skin should get uploaded and changed

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Meet the requirement above

Suspected cause:
---------------------------
Some OS directory problem perhaps

Logs/Screenshots:
----------------------------
Not required for a minor problem like this

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
Could you launch an instance and kill it once it is in the main menu and than click upload in the console and paste the link here?

**Comment by Heufneutje** [comment]
If you're not going to upload logs then how do you expect us to find the reason why it failed? The error message itself doesn't tell you anything.

**Comment by Heufneutje** [comment]
If you think it's a directory problem logs are most certainly required. If we don't know the reason why it failed it can't be fixed either.

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
