### ISSUE TITLE
Update to latest version wipes all instances

### ISSUE THREAD

**Issue by savedario** [MultiMC/MultiMC5#2999]
System Information
-----------------------------
MultiMC version: 0.6.8-1333

Operating System: OpenSUSE Linux

Summary of the issue or suggestion:
----------------------------------------------
Update to latest version wipes all istances and accounts

What should happen:
------------------------------
Update should keep previously defined instances and account, and probably settings.
At least, it should warn that the data will be lost, or could be lost, so one can make backups before-hand.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. After startup, get notification that a new update is available
2. Agree to proceed with the update
3. The initial setting configuration window appears
4. Before one can select the language, a new dialog appears warning that the version is slow to respond and asks to revert the update
5. Reply 'no' to keep the new version
6. Complete the setup and find an empty MultiMC window, as if it was the first installation ever

Suspected cause:
---------------------------
Not sure, perhaps if I had answered yes, I would have gotten my instances back.
In any case, the 'slow response' check is a bit too hasty.

Logs/Screenshots:
----------------------------
Too late now

Additional Info:
---------------------------
I was lucky that I did not copy ALL my worlds inside MultiMC instances...

**Comment by savedario** [comment]
Perhaps the previous version is saved somewhere ?

**Comment by Zetabite** [comment]
How did you install MMC?

**Comment by savedario** [comment]
I am pretty sure I extracted mmc-stable-lin64.tar.gz under ~/apps (On 15.12.19)

**Comment by HellishINC** [comment]
What old version were you running? I remember multimc changed the directories (could be an Arch thing) quite some time ago.

Look in your ~/.local/share ~/ and possibly your ~/.config

**Comment by savedario** [comment]
I mentioned the filename and the date above. How can I tell the version without installing it ?

**Comment by Zetabite** [comment]
just launch mmc and see what it says in the log

**Comment by savedario** [comment]
I unzipped into a new temp directory and launched bin/MultiMC.
The language selection windows shows, I close it.
What looked like the 0.6.8 readme / help appears briefly and then the main mmc window that says 0.6.7-1290 on lin64.
The log (shown in the terminal window) reports the same version number.
The file bin/MultiMC-0.log contains the same (including the long HTML text that has 0.6.8 at the top)

**Comment by Zetabite** [comment]
thr portable version will only save the instances if you move it correctly. if you delete it, you delete all the instances

**Comment by savedario** [comment]
Yesterday I unzipped the OLD file in a different directory to figure out which version it was, since HellishINC was asking.
My initial install was somewhere else and I did not move it. I just updated as suggested.

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
