### ISSUE TITLE
Closing the Console Window also closes the Main Window

### ISSUE THREAD

**Issue by BamaJoe411** [MultiMC/MultiMC5#3001]
System Information
-----------------------------
MultiMC version: 0.6.8-1333 on lin64

Operating System: Debian GNU/Linux 10 (buster)

Summary of the issue or suggestion:
----------------------------------------------
When closing the Console Window the Main Window also closes

What should happen:
------------------------------
Main Window should not close

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch MultiMC

2. Open Console Window

3. Close Console Window

Suspected cause:
---------------------------
No Clue

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
[https://youtu.be/I1xdqg9bsWA](https://youtu.be/I1xdqg9bsWA)

Additional Info:
---------------------------

**Comment by antcig** [comment]
Same issue, multimc crashing on instance window close.
Linux Debian 10 (KDE)
Crashlog attached.
[MultiMC-20200217-235323.kcrash.txt](https://github.com/MultiMC/MultiMC5/files/4218127/MultiMC-20200217-235323.kcrash.txt)

**Comment by peterix** [comment]
This is a bug in the version of Qt you are using.
The fix is in Qt 5.12, and would have to be backported.

See: https://bugreports.qt.io/browse/QTBUG-68393

**Comment by antcig** [comment]
Updated to qt 5.12.5 and issue fixed.
Thank you.
