### ISSUE TITLE
RAD 1.35 Keep Crashing With Exit Code 6 (Ubuntu 19.10)

### ISSUE THREAD

**Issue by pollen00** [MultiMC/MultiMC5#3003]
### System Information:
Multi Mc 5 Ver 0.6.8-1333 for Lin 64
Ubuntu 19.10

### Summary of the issue or suggestion
During the third stage of mod loading on the mipmap portion, it always crashes with exitcode 6 saying something about java: ../nouveau/pushbuf.c:723: nouveau_pushbuf_data: Assertion `kref' failed.

### What Should Happen
The modpack should load all of the mods without crashing

### Steps To Reproduce
(On Ubuntu with Nouveau graphics drivers with nVidia card)
1. Launch RAD, RLCraft,
2. Game crashes on stage 3/7: Mipmap loading

### Suspected Cause
Nouveau graphics drivers
WIth nVidia it works fine... but nVidia drivers aren't supported under Ubuntu, so it breaks the system if I try to use them

### Logs
Log files: https://paste.ee/p/ygqYO

**Comment by spannerman79** [comment]
Not a MultiMC issue as this issue would exist with the vanilla launcher.

>WIth nVidia it works fine... but nVidia drivers aren't supported under Ubuntu, so it breaks the system if I try to use them

Since when are nvidia drivers unsupported? https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa

**Comment by Zetabite** [comment]
i think it could be an issue that it uses the jdk instead of jre
