### ISSUE TITLE
Can't load an instance using FTB Ultimate Reloaded Modpack

### ISSUE THREAD

**Issue by sasquatch22** [MultiMC/MultiMC5#3004]
System Information
-----------------------------
MultiMC version: 0.6.7

Operating System: macOS Mojave - 10.14.6

Summary of the issue or suggestion:
----------------------------------------------
New to modding so not sure what the issue is - Using FTB Ultimate Reloaded Modpack - crashes with exit code 255

What should happen:
------------------------------
Launcher finishes loading mods

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create new instance using mudpack zip file downloaded from twitch/curse 

2. Initialises up to 6/7 then crashes - exited with code 255

Suspected cause:
---------------------------
Not sure

Logs/Screenshots:
----------------------------
https://paste.ee/p/K6Smo

Additional Info:
---------------------------

**Comment by spannerman79** [comment]
'java.lang.OutOfMemoryError: GC overhead limit exceeded'

Pretty simple to know what that means...

`[-Xdock:icon=icon.png, -Xdock:name="MultiMC: FTB Ultimate Reloaded", -Xms1024m, -Xmx2048m, -Duser.language=en]`

Add moar ram!
