### ISSUE TITLE
[SUGGESTION] Launcher Plugins

### ISSUE THREAD

**Issue by Shazuli** [MultiMC/MultiMC5#3007]
***Hi***

It would be neat with plugins support. You write a script you import into the launcher, bind it to events (game launched [instance name, instance title, instance mc version, instance allocated RAM, etc], game closed [close code, instance name, ...]), have it run when you open the launcher, add buttons to the menu, etc.

Example use: When creating a new instance you can have a script run from the event that fires when the instance has been created have it create additional files such as a default config file or something else. No mods required on the actual instance for this.
Another use (albeit more complicated): When closing an instance you can have it automatically sync your saves to a cloud stream and when launching it can check for an update and sync it locally from the same stream.
Custom windows can be used as pop-ups for showing a warning. Maybe have a config file with a window showing it as a nice options window for that particular plugin. Maybe have scripts bound to only check for events on certain instances, or on all except these two or in this group (blacklist). Plugins can have an enabled/disabled or loaded/unloaded option for convenience.

And scripts should all be open-source, preventing malicious scripts from doing bad things on the user's PC.

If this idea is stupid, just ignore and close this issue, I assume you guys are focusing on Forge. Otherwise, keep this issue open and have it in the back of your mind as a possible feature someday. I think it would be really nice to have in the launcher.

**Comment by Zetabite** [comment]
Yeah, no one is focusing on forge here. For what i know, we wanna rather see it burn.

**Comment by Heufneutje** [comment]
This idea has already been rejected many times.

**Comment by Shazuli** [comment]
@Heufneutje Ok, gotcha. Closing the issue.

**Comment by peterix** [comment]
What you would put in plugins, I'd rather see as pull requests first.
