### ISSUE TITLE
multimc wont start anymore

### ISSUE THREAD

**Issue by SevenChords** [MultiMC/MultiMC5#3010]
System Information
-----------------------------
MultiMC version: 
latest stable

Operating System: 
macos catalina (latest)

Summary of the issue or suggestion: 
the application multimc doesn't start anymore, it bounces in the dock as if it is starting, after that it just sits still in the dock without the dot below it indicating a running application (i normally don't have it in my dock), but it shows up in activity monitor as running, nothing happens anymore, can't click it, can't do anything but restarting my mac or force quitting multimc
----------------------------------------------

What should happen: 
multimc should start normally and open the main window
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. open multimc on macos catalina (latest)

2. try to import new instance from a local zip file

3. repeat step 2 until it freezes with rainbow spinny circle

4. force quit multimc after freeze in step 3

5. try to start multimc again

Suspected cause: 
issues/conflicts with the way macos catalina and multimc handle file/disk access and permissions for said access
---------------------------

**Comment by peterix** [comment]
Apple being Apple and soing stupid things with 'security'...

**Comment by phit** [comment]
this was presumably fixed with https://github.com/MultiMC/MultiMC5/pull/3081
if you are still having issues on the development version please let us know
