### ISSUE TITLE
Twitch URL VANISH - MultiMc 5 V0.6.8-1333

### ISSUE THREAD

**Issue by H2NsO** [MultiMC/MultiMC5#3014]
Twitch URL has vanish
![Twitch URL VANISH](https://user-images.githubusercontent.com/61457259/75240161-cf801500-57bb-11ea-9435-95ac3a9aa69c.png)

**Comment by cfanoulis** [comment]
intended https://github.com/MultiMC/MultiMC5/commit/af5120c828831dfe41482ebaff79608ba8531ede

**Comment by GeorgeWilson96** [comment]
If this is as intended shouldn't this be marked as closed ?

**Comment by Zetabite** [comment]
Either the issue creator or a project member can close it
