### ISSUE TITLE
World Files access

### ISSUE THREAD

**Issue by Macintosh-Fan** [MultiMC/MultiMC5#3015]
I am trying to access my world files in the MultiMC file system and I cannot seem to find the world files. If there is any way I can access them, can you please let me know @peterix?
That would be epic if it worked!

Thanks!

**Comment by kb-1000** [comment]
That's Apple's fault, they are stored in a subdirectory called .minecraft of each instance, and as it starts with a ".", Apple hides it. If you select the instance in MultiMC and click on "Minecraft Folder" on the right, you can find them in "saves". However, I'm only guessing from your username that you're using MacOS X, and you should mention which OS you're using when you have any issues. The issue template isn't there to be completely ignored.

**Comment by Macintosh-Fan** [comment]
macOS Catalina

**Comment by Macintosh-Fan** [comment]
> That's Apple's fault, they are stored in a subdirectory called .minecraft of each instance, and as it starts with a ".", Apple hides it. If you select the instance in MultiMC and click on "Minecraft Folder" on the right, you can find them in "saves". However, I'm only guessing from your username that you're using MacOS X, and you should mention which OS you're using when you have any issues. The issue template isn't there to be completely ignored.

What? I couldn't see the so-called "Minecraft" folder in the instances folder

**Comment by Heufneutje** [comment]
What? I couldn't see the so-called "Minecraft" folder in the instances folder
> That's Apple's fault, they are stored in a subdirectory called .minecraft of each instance, and as it starts with a ".", Apple hides it.

**Comment by Macintosh-Fan** [comment]
> What? I couldn't see the so-called "Minecraft" folder in the instances folder
> 
> > That's Apple's fault, they are stored in a subdirectory called .minecraft of each instance, and as it starts with a ".", Apple hides it.
> 
> This is why you can't see that folder. Another way to access your saves is to go the instance window in MultiMC itself and then click on the Worlds tab. In the bottom right there's a View Folder button which will take you right to the saves folder for that instance.

App crashes then.

**Comment by Heufneutje** [comment]
Probably Apple blocking access to something as per usual.

**Comment by kb-1000** [comment]
"Minecraft Folder" is a button in MultiMC, by the way, I didn't refer to a folder called "Minecraft"

**Comment by IsmayilMirzali** [comment]
> "Minecraft Folder" is a button in MultiMC, by the way, I didn't refer to a folder called "Minecraft"

Minecraft worlds are usually stored in ~/.minecraft/ unless MultiMC changes this.
Try opening the terminal application and running ```ls -lh ~/.minecraft/``` and post the result here.

**Comment by Macintosh-Fan** [comment]
> > "Minecraft Folder" is a button in MultiMC, by the way, I didn't refer to a folder called "Minecraft"
> 
> Minecraft worlds are usually stored in ~/.minecraft/ unless MultiMC changes this.
> Try opening the terminal application and running `ls -lh ~/.minecraft/` and post the result here.

No such file or directory. I wonder if MultiMC has done something weird to my files.

Extra notes:
@peterix The "Minecraft Folder" button in MultiMC just crashes the app

**Comment by Macintosh-Fan** [comment]
I also opened Minecraft and tapped edit and tapped Open Folder and nothing happens.

**Comment by Macintosh-Fan** [comment]
Hang on! Never mind, things work now. The loading was slow though. I had to click in Minecraft in order for it to load and it worked. Some bugs are still needed to be fixed but that solves my problem.

**Comment by kb-1000** [comment]
@IsmayilMirzali
> Minecraft worlds are usually stored in ~/.minecraft/ unless MultiMC changes this.
> Try opening the terminal application and running `ls -lh ~/.minecraft/` and post the result here.
Changing this is exactly the main feature of MultiMC. They are separated in instances. Also, "Minecraft" and ".minecraft" isn't the same name.
@Macintosh-Fan please don't close this, if the app crashes when clicking on "Minecraft folder" then it definitely is a bug.

**Comment by Macintosh-Fan** [comment]
> @IsmayilMirzali
> 
> > Minecraft worlds are usually stored in ~/.minecraft/ unless MultiMC changes this.
> > Try opening the terminal application and running `ls -lh ~/.minecraft/` and post the result here.
> 
> Changing this is exactly the main feature of MultiMC. They are separated in instances. Also, "Minecraft" and ".minecraft" isn't the same name.
> @Macintosh-Fan please don't close this, if the app crashes when clicking on "Minecraft folder" then it definitely is a bug.

That is for a separate issue

**Comment by Macintosh-Fan** [comment]
New issue for the bug:
https://github.com/MultiMC/MultiMC5/issues/3026
