### ISSUE TITLE
Unable to start 1.8.9 on virtual machine (Microsoft Azure)

### ISSUE THREAD

**Issue by HyperLemons** [MultiMC/MultiMC5#3016]
System Information
-----------------------------
MultiMC version:
0.6.8-1419

Operating System:
Windows 10

Summary of the issue or suggestion:
----------------------------------------------
I have been using Multimc on Micorsoft Azure here and there for awhile. Worked even this morning.

What should happen:
1. I start game (with all mods working and texture packs on)
2. Game starts after a few seconds
3. Play game (lmao)

------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Start game (Launch)

2. Almost instantly get crash log

3.

Suspected cause:
---------------------------
No idea, I installed Java and Offline so I honestly need some help here.

Logs/Screenshots:
----------------------------
![image](https://user-images.githubusercontent.com/36387099/75366292-62c85180-5873-11ea-9fdc-bc30352c872b.png)

https://paste.ee/p/FU5LT

Additional Info:
---------------------------
Hope I can get some help with this, thanks all in advance.

**Comment by Heufneutje** [comment]
This appears to be a graphics driver issue (which wouldn't surprise me on a VM). Could you try the Java version [here](https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs)? Can't say for sure it'll help but sometimes it does.

**Comment by HyperLemons** [comment]
> This appears to be a graphics driver issue (which wouldn't surprise me on a VM). Could you try the Java version [here](https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs)? Can't say for sure it'll help but sometimes it does.

TYSM! Worked like a charm.
