### ISSUE TITLE
Process exited with code -1

### ISSUE THREAD

**Issue by pierrehicks** [MultiMC/MultiMC5#3018]
System Information
-----------------------------
MultiMC version: 0.6.8-1419

Operating System: windows 10

Summary of the issue or suggestion:
----------------------------------------------
Tried to launch instance and crashed with error code -1

What should happen:
------------------------------
instance launches successfully

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. launch instance 

2. wait for it to load

3. CRASH!!!!

Suspected cause:
---------------------------
????

Logs/Screenshots:
----------------------------
https://paste.ee/p/Md7vM

Additional Info:
---------------------------
I was playing it earlier in the day and it worked fine. I closed it and tried adding some mods and this happened. I have since disabled those mods and it continues to crash. I have tried updating Java to no success and I have plenty of RAM(16gb). I have seen others with this issue but so far nothing has worked.

**Comment by Heufneutje** [comment]
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from AsmodeusCore (asmodeuscore)
Caused by: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/api/galaxies/CelestialBody

This mod is causing a crash.

Also, assigning that much RAM is not recommended. You're assigning 18 GB which is way too much. 8 GB is more than enough.

**Comment by pierrehicks** [comment]
@Heufneutje Thank you for your help I disabled it and it launched fine. Could allocating that much RAM cause an issue, I had seen others that had this error and claimed that increasing RAM helped so I put it at something that I knew would be enough. It didn't help but I figured i'd leave it anyway unless it causes problems. Again thank you for your help

**Comment by Heufneutje** [comment]
Increasing RAM does indeed help but increasing it too much can cause significant lag spikes due to the way Java works.

**Comment by pierrehicks** [comment]
Good to know. Thank you once again for your help.
