### ISSUE TITLE
Inconsistency detected by ld.so: dl-lookup.c: 111

### ISSUE THREAD

**Issue by EliCodes9** [MultiMC/MultiMC5#3019]
https://github.com/MultiMC/MultiMC5/wiki/Report-a-Bug
-->

System Information TS147
-----------------------------
MultiMC version: 5

Operating System: Ubuntu Mate, Linux

Summary of the issue or suggestion: Log issue:

 MultiMC version: 0.6.8-1333

Minecraft folder is:
/home/eli/.local/share/multimc/instances/Mod-/.minecraft

Java path is:
/usr/bin/java

Java is version 11.0.6, using 64-bit architecture.

Intel(R) Xeon(R) CPU E3-1225 v3 @ 3.20GHz
Intel Corporation Xeon E3-1200 v3 Processor Integrated Graphics Controller (rev 06)

Subsystem: Lenovo Xeon E3-1200 v3 Processor Integrated Graphics Controller

Kernel driver in use: i915

OpenGL version string: 3.0 Mesa 19.2.8

Main Class:
  net.minecraft.client.main.Main

Native path:
  /home/eli/.local/share/multimc/instances/Mod-/natives

Libraries:
  /home/eli/.local/share/multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/eli/.local/share/multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/eli/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/eli/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/eli/.local/share/multimc/libraries/net/minecraft/launchwrapper/1.9/launchwrapper-1.9.jar
  /home/eli/.local/share/multimc/libraries/org/ow2/asm/asm-all/4.1/asm-all-4.1.jar
  /home/eli/.local/share/multimc/libraries/com/mumfrey/liteloader/1.7.2_05/liteloader-1.7.2_05.jar
  /home/eli/.local/share/multimc/libraries/com/mojang/netty/1.6/netty-1.6.jar
  /home/eli/.local/share/multimc/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  /home/eli/.local/share/multimc/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /home/eli/.local/share/multimc/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /home/eli/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  /home/eli/.local/share/multimc/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/eli/.local/share/multimc/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/eli/.local/share/multimc/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/eli/.local/share/multimc/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /home/eli/.local/share/multimc/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/eli/.local/share/multimc/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  /home/eli/.local/share/multimc/libraries/com/google/guava/guava/15.0/guava-15.0.jar
  /home/eli/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
  /home/eli/.local/share/multimc/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  /home/eli/.local/share/multimc/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  /home/eli/.local/share/multimc/libraries/com/mojang/authlib/1.3/authlib-1.3.jar
  /home/eli/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  /home/eli/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  /home/eli/.local/share/multimc/libraries/com/mojang/minecraft/1.7.2/minecraft-1.7.2-client.jar

Native libraries:
  /home/eli/.local/share/multimc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/eli/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar

Mods:
  [✔️] crazycraft+2,0-2.0
  [✔️] hopperfilter-e561 (1)
  [✔️] lots-o-mod-1-0-e340
  [✔️] Lucky-Block-Mod-1.7.10
  [✔️] magicmod172zip8185459
  [✔️] ModernArch Mod (v1.0.0)
  [✔️] MoreEmeraldUses_v.1.1_1.12.2
  [✔️] orespawn-1.7.10-20.0
  [✔️] simcraft-1-0-1509656777
  [✔️] the-steves-mod-1-12-2-1-0-4-1563291980

Params:
  --username  --version MultiMC5 --gameDir /home/eli/.local/share/multimc/instances/Mod-/.minecraft --assetsDir /home/eli/.local/share/multimc/assets/virtual/legacy --uuid  --accessToken 

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 5825

Using onesix launcher.

[07:33:29] [main/INFO]: Setting user: moongoggles929
[07:33:29] [main/INFO]: (Session ID is token:<ACCESS TOKEN>:<PROFILE ID>)
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
Process exited with code 127.
Clipboard copy at: 28 Feb 2020 07:34:26 -0500

**Comment by QuImUfu** [comment]
use Java 8 for (modded) Minecraft.

**Comment by Mepz939-officialz** [comment]
oh, thank you for the help, i wish you the best of luck!

**Comment by JW6677** [comment]
Getting the same issue

**Comment by kb-1000** [comment]
Use the same solution
Java 8

**Comment by Scotsguy** [comment]
This is not a MultiMC issue, closing.

**Comment by KajeArch** [comment]
This still happens to me. I use vanilla Minecraft.
