### ISSUE TITLE
i cant run game

### ISSUE THREAD

**Issue by Cr1PT0Z** [MultiMC/MultiMC5#3021]
Instance update failed because: Component metadata update task failed while downloading from remote server:

Job 'Download of meta file net.minecraftforge/31.1.17.json' failed to process:
https://meta.multimc.org/v1/net.minecraftforge/31.1.17.json

**Comment by HellishINC** [comment]
Also seeing this issue (though now it's not finding the json for 31.1.18).

Can't launch any forge instances that are =>1.15.

**Comment by phit** [comment]
any version newer than 1.12.2 is not supported with Forge, use Fabric or a different launcher
https://multimc.org/posts/forge-114.html

**Comment by HellishINC** [comment]
While I understand why, it's a shame to hear. Perhaps that information should be noted in the launcher itself. Currently when adding a new instance, it appears to the end user that the forge download is simply failing. Guess I'll migrate to the official launcher until either party changes thier stance.
