### ISSUE TITLE
can't resize columns in 'loader mods' 

### ISSUE THREAD

**Issue by Spongman** [MultiMC/MultiMC5#3022]
System Information
-----------------------------
MultiMC version: 0.6.9-develop-1422 on win32

Operating System: win10 x64

Summary of the issue or suggestion:
----------------------------------------------

columns in the instance settings dialog aren't resizeable. for example, can't see full versions of mods.

**Comment by peterix** [comment]
The version column should auto expand to the size of content.

The only way to make these not fit is to have the window so small that it can't fit anything...
