### ISSUE TITLE
world crashes at 0% load, back up still works

### ISSUE THREAD

**Issue by AshEcho** [MultiMC/MultiMC5#3024]
System Information
-----------------------------
MultiMC version: 0.6.8

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
opened revaltions, went to play my world and the text comes up saying its generating, but when it gets to where it displays a percent it says 0% for a few seconds before crashing, my old back up of the world works

What should happen:
------------------------------
should hit play
load world
play as normal

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
made no changes to game since i last play a few days ago, game closed normally then, unsure why the world no longer works

Suspected cause:
---------------------------
possible corrupt world somehow? im not sure

Logs/Screenshots:
----------------------------
https://paste.ee/p/HeBqi

Additional Info:
---------------------------

**Comment by Heufneutje** [comment]
According to the log it's caused by Refined Storage. Try updating it and/or Forge.

**Comment by AshEcho** [comment]
tried both, they are both current, and i can load a back up same world and it works, just that one world doesnt, so does that mean some how it got corrupt?

**Comment by AshEcho** [comment]
i vaguely remember messing with rs right before i logged off, was trying to set up a new drawer controller system and attached an external storage to it, however i remember it wasnt working and my other drawer system did so i couldnt figure out why and logged off.

**Comment by QuImUfu** [comment]
Known rs bug:  
https://github.com/raoulvdberge/refinedstorage/issues/2241 
You could try turning on Forges option to remove erroring tile entities, and see if that works around the issue.

**Comment by AshEcho** [comment]
tried both forge options for tile entities and just plain entities, also saw a comment on another post to resolve the tick loop error and changed my maximum chunks per tick to 50 instead of 25 in the forgeChunkLoading.cfg and that didnt do anything either.

**Comment by QuImUfu** [comment]
Then you are out of luck. If you don't mind loosing everything rs related, remove that mod and re-add it. Otherwise you could use mcedit to remove the offending entity. It's probably a EnderIO conduit and a Refined Storage machine next to each other... or something like that.

**Comment by Zetabite** [comment]
Backup your world before doing anything
