### ISSUE TITLE
Clicking on “Minecraft Folder” freezes the app

### ISSUE THREAD

**Issue by Macintosh-Fan** [MultiMC/MultiMC5#3026]
There is a bug in when I look at the Minecraft worlds section and when I click the button that opens the files, the app freezes. When I do this in Minecraft, the app does not freeze.

**Comment by Zetabite** [comment]
pls follow the issue reporting guidelines and post your log https://github.com/MultiMC/MultiMC5/wiki/Minecraft-Logs

**Comment by Chew** [comment]
Already reported: #2579
