### ISSUE TITLE
Crash error Vanilla 1.12.2

### ISSUE THREAD

**Issue by JustB3nny** [MultiMC/MultiMC5#3027]
So i installed a fresh new version of MultiMC 5 (deleted the other one due to file size and mod issues) and whenever i try to run 1.12.2 it instantly crahses and spews out this log: https://paste.ee/p/SI9sN

THIS ONLY HAPPENS WITH 1.12.2 (or atleast it does for me)

**Comment by Zetabite** [comment]
do you have enough disk space left?

**Comment by Zetabite** [comment]
are you trying to make a hacked client work with mmc?

**Comment by JustB3nny** [comment]
Yeah I was trying to get a hacked client to work with mmc lol. But i did a fresh install when I crashed with the hacked client as i thought it was some config issue but it was still crashing the vanilla game itself or the launcher. 
To resolve it I had to reinstall the base game files (.minecraft) and set it up again from there.. so i guess it corrupted the base game files or something..?

**Comment by Zetabite** [comment]
you are pretty much on your own. if you have luck somebody might help you on the discord

**Comment by Scotsguy** [comment]
This is not a MultiMC issue, closing.
