### ISSUE TITLE
Process exited with code -1.

### ISSUE THREAD

**Issue by dablade11577** [MultiMC/MultiMC5#3028]
https://paste.ee/p/3AyLH#s=0&l=1

**Comment by Zetabite** [comment]
please follow the report guidelines and add paste the link of the log instead of the log

**Comment by QuImUfu** [comment]
you seem to have installed multiple forgelin versions. Remove all except Forgelin-1.8.4.

**Comment by dablade11577** [comment]
Thanks @QuImUfu.
