### ISSUE TITLE
[1.6.4] Game runs fine, but a few mods don't show up.

### ISSUE THREAD

**Issue by mazdafan1** [MultiMC/MultiMC5#303]
So I have created my own mod-pack with 140+ mods, I fixed all the ID conflicts and it now runs fine. In fact almost perfect. But a couple of mods aren't showing in my game. Firstly my TF2 Dispensers mod is in the listings in the Mods tab (In Game and Launcher), however it doesn't show up in the crafting recipes or creative. Next is my flans modern warfare gun pack, the main flans mod shows up but the guns don't. So I can't even craft the gun making block, this mod however doesn't show up in the mods tab (In game).

I am not yet aware if this is the case with any other mods, but these are what I have encountered so far. Please help! Thanks

(Please tell me which files you need to diagnose the problem!)

**Comment by peterix** [comment]
We should've asked for the actual Minecraft log. Not MultiMC log. And then the issue got completely ignored.

Sorry for not resolving this half a year ago.
