### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by MsDebbie616** [MultiMC/MultiMC5#3030]
I'm trying to play Minecraft with MultiMC...It cant load the world and it says this: 

[12:27:54] [Client thread/INFO]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Owner\Downloads\mmc-develop-win32\MultiMC\instances\Mystical Forest Renewed 15-11-2016\minecraft\crash-reports\crash-2020-03-13_12.27.48-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.
Clipboard copy at: 13 Mar 2020 12:28:27 -0400

**Comment by Janrupf** [comment]
![image](https://user-images.githubusercontent.com/25827180/76653994-3c403100-656a-11ea-909c-17211b2caab2.png)

**Comment by MsDebbie616** [comment]
https://paste.ee/p/eRF0N

**Comment by Janrupf** [comment]
Please follow the image and don't just upload the crash report. Run minecraft and then click on upload.

**Comment by MsDebbie616** [comment]
https://paste.ee/p/eQ3OJ

**Comment by QuImUfu** [comment]
`java.lang.OutOfMemoryError: Java heap space`  
=> not enough memory allocated to minecraft.  
Solution:
Allocate more memory, remove mods, install memory footprint reducing mods or fiddle with java options to better utilize the memory.

**Comment by Scotsguy** [comment]
This is not a MultiMC issue, closing.
