### ISSUE TITLE
Windows release `0.6.8` on Github is actually version `0.6.7`

### ISSUE THREAD

**Issue by r15ch13** [MultiMC/MultiMC5#3034]
Summary of the issue or suggestion:
----------------------------------------------
The Windows release `0.6.8` on Github is actually version `0.6.7`.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
- Goto https://github.com/MultiMC/MultiMC5/releases/tag/0.6.8
- Download windows release and start it
- The title bar shows version `0.6.7-1375`
- It will prompt to update version 0.6.8

Related:
https://github.com/Calinou/scoop-games/issues/100

**Comment by Scotsguy** [comment]
0.6.8 is old now, this probably isn't a relevant issue anymore.
