### ISSUE TITLE
Comparison method violates its general contract! (no hope, something about Timsort)

### ISSUE THREAD

**Issue by SteleCat** [MultiMC/MultiMC5#3035]
System Information
-----------------------------
MultiMC version: 0.6.8-1419

Operating System: Windows 10 64-bit

Summary of the issue or suggestion: Crash upon attempting to load any world
----------------------------------------------

What should happen: Game should work
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Attempt to generate new world

2. Watch in horror as a bug you've never heard and has never been solved in any of the hours worth of forums you've searched once again rears its ugly head and steals all hope from your heart.

3. cry

Suspected cause: unknown
---------------------------

Logs/Screenshots:

MultiMC version: 0.6.8-1419

Minecraft folder is:
D:/YT_Resources/Minecraft Misc/MultiMC/instances/inf-20100618/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_51/bin/javaw.exe

Java is version 1.8.0_51, using 64-bit architecture.

Main Class:
  net.minecraft.client.d

Native path:
  D:/YT_Resources/Minecraft Misc/MultiMC/instances/inf-20100618/natives

Traits:
traits no-texturepacks
traits legacyLaunch

Libraries:
  D:/YT_Resources/Minecraft Misc/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  D:/YT_Resources/Minecraft Misc/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  D:/YT_Resources/Minecraft Misc/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  D:/YT_Resources/Minecraft Misc/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  D:/YT_Resources/Minecraft Misc/MultiMC/instances/inf-20100618/libraries/customjar-1.jar

Native libraries:
  D:/YT_Resources/Minecraft Misc/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  D:/YT_Resources/Minecraft Misc/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Params:
  

Window size: 854 x 480

Java Arguments:
[-Dhttp.proxyHost=classic.retrocraft.net, -Dhttp.proxyPort=80, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 19552

Using onesix launcher.

Could not find Minecraft path field.
Launching with applet wrapper...
43
LWJGL version: 2.9.4
GL RENDERER: Intel(R) UHD Graphics 630
GL VENDOR: Intel
GL VERSION: 4.6.0 - Build 26.20.100.7063
OpenGL 3.0: true
OpenGL 3.1: true
OpenGL 3.2: true
ARB_compatibility: true
PROFILE MASK: 10
CORE PROFILE: false
COMPATIBILITY PROFILE: true
Mar 16, 2020 5:34:49 PM net.java.games.input.DefaultControllerEnvironment getControllers
WARNING: Found unknown Windows version: Windows 8.1
Mar 16, 2020 5:34:49 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Attempting to use default windows plug-in.
Mar 16, 2020 5:34:49 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.DirectAndRawInputEnvironmentPlugin
Mar 16, 2020 5:34:49 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to initialize device HIDI2C Device because of: java.io.IOException: Failed to acquire device (8007001e)

Starting up SoundSystem...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
OpenAL initialized.

java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeLo(Unknown Source)
	at java.util.TimSort.mergeAt(Unknown Source)
	at java.util.TimSort.mergeCollapse(Unknown Source)
	at java.util.TimSort.sort(Unknown Source)
	at java.util.Arrays.sort(Unknown Source)
	at net.minecraft.client.a.b.e(Unknown Source)
	at net.minecraft.client.a.b.a(Unknown Source)
	at net.minecraft.client.d.a(Unknown Source)
	at net.minecraft.client.d.a(Unknown Source)
	at net.minecraft.client.c.n.a(Unknown Source)
	at net.minecraft.client.c.i.a(Unknown Source)
	at net.minecraft.client.c.i.f(Unknown Source)
	at net.minecraft.client.d.f(Unknown Source)
	at net.minecraft.client.d.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

SoundSystem shutting down...
    Author: Paul Lamb, www.paulscode.com

Process exited with code 0.

----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
What pack are you trying to launch

**Comment by QuImUfu** [comment]
that is (likely) a vanilla bug. Java <7 did not (ever) check whether Comparisons make sense. Java 7+ does that and (likely) uncovers this bug.  
Use Java 6 for really old minecaft versions.

**Comment by Forkk** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's discord, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
