### ISSUE TITLE
Multi MC crash when laoding world .... 90% of the time only.

### ISSUE THREAD

**Issue by TomGareth** [MultiMC/MultiMC5#3041]
Hi everyone, 

Like some, I'm having crashed with my Multi MC almost every time I load a world.
I've tried the multiple solutions I found online but I'm unable to understand properly the log so it's hard which kind of error I have. I play an FTB revelation instance.
I tried so far: 
- simple reboot
- updating Multi MC Java and GC drivers, no changes
- increasing RAM avail for Java up to 12go, nothing.
- using specific Java argument I found (
- creating a new instance of FTB revelation AND a new world. It worked a couple time but start crashing too now.

Interesting fact, every I re-install java or lunch a new world, it works. It seems that when I turn off/reboot my computer, then it keeps crashing.

I'm a bit desperate now, so if someone understand the log and can help ... That would be great :)

Thanks

System Information
-----------------------------
MultiMC version: 0.6.8-1419
Operating System: Windows 10, up to date.

Log
[MC Crash.txt](https://github.com/MultiMC/MultiMC5/files/4358554/MC.Crash.txt)

**Comment by Zetabite** [comment]
could you upload the log as this picture suggest :D
https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by TomGareth** [comment]
Sure :)

**Comment by TomGareth** [comment]
No idea ? :s

**Comment by TomGareth** [comment]
New crash today. Won't even go to the Minecraft menu now ...
https://paste.ee/p/UFNQy

Tried a new instance but all the same.

**Comment by Zetabite** [comment]
`[12:27:53] [Client thread/INFO] [FML]: FML has found a non-mod file bedpatch-2.2-1.12.2.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[12:27:53] [Client thread/INFO] [FML]: FML has found a non-mod file AutoSave-1.12.2-1.0.11.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[12:27:53] [Client thread/INFO] [FML]: FML has found a non-mod file AutoConfig-1.12.2-1.0.2.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.`

**Comment by TomGareth** [comment]
Yes ... but that looks like chinese for me... :(
Knowing that I didn't touch the modpack, it's FTB Revelation out of the box.
What should I do?

**Comment by Scotsguy** [comment]
This is not a MultiMC issue, closing.
