### ISSUE TITLE
multimc not opening

### ISSUE THREAD

**Issue by stumpgod** [MultiMC/MultiMC5#3047]
System Information
-----------------------------
MultiMC version: latest

Operating System: windows 8

Summary of the issue or suggestion: just installed multimc and when i try to open "multimc.exe" it doesnt open. it displays the error message "the program cant start because libmultimc_gui.dll is missing from your computer. try reinstalling the program to fix this problem"
----------------------------------------------

What should happen: it should open multi mc
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. install the latest version of multi mc

2. extract the zip into a folder

3. open "multimc.exe"

Suspected cause: not sure. i have had this problem with other installers where it says that a .dll file is missing
---------------------------

Logs/Screenshots:
----------------------------
https://imgur.com/a/CF7eNMs
https://imgur.com/a/iDJLj20

Additional Info:
---------------------------

**Comment by kb-1000** [comment]
Extract the ZIP file, MultiMC won't launch from inside the ZIP file.

**Comment by stumpgod** [comment]
> Extract the ZIP file, MultiMC won't launch from inside the ZIP file.

i have. as you can see in the screenshot it is in its extracted folder

**Comment by kb-1000** [comment]
You didn't. You extracted a single file, and the file needs the remaining files from the ZIP file to function properly.
