### ISSUE TITLE
Add LWJGL 3.2.3

### ISSUE THREAD

**Issue by Freso** [MultiMC/MultiMC5#3050]
System Information
-----------------------------
MultiMC version: 5/0.6.8

Operating System: Linux

Summary of the issue or suggestion:
----------------------------------------------

I’m trying to change the used LWJGL version to version 3.2.3, but it isn’t showing in the "Change version" dialog.

What should happen:
------------------------------

LWJGL 3.2.3 should be available in the "Change version" dialog.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open a Minecraft instance

2. Go to "Version"

3. Select "LWJGL"

4. Click "Change version"

5. No 3.2.3 :frowning_face: 

Suspected cause:
---------------------------

There is no `org.lwjgl3/3.2.3.json` in the [`meta-multimc` repository](https://github.com/MultiMC/meta-multimc).

Logs/Screenshots:
----------------------------
![Screenshot of "Change version" dialog](https://user-images.githubusercontent.com/177659/77582677-055e0980-6ee0-11ea-9e86-a9e003dd25ee.png)

Additional Info:
---------------------------

[LWJGL 3.2.3](https://github.com/LWJGL/lwjgl3/releases/tag/3.2.3) was released in September of 2019, [`org.lwjgl3`](https://github.com/MultiMC/meta-multimc/tree/master/org.lwjgl3) was last updated in June of last year.

**Comment by Heufneutje** [comment]
Is there any specific reason why you need 3.2.3?

**Comment by phit** [comment]
This issue is being closed for inactivity. If you still need this please explain your reasoning and we will consider reopening this.
