### ISSUE TITLE
Mouse Jumping to Side of Screen in Inventory

### ISSUE THREAD

**Issue by SpacePuppeh** [MultiMC/MultiMC5#3058]
System Information
-----------------------------
MultiMC version: 0.6.11 

Operating System: macOS Catalina 10.15.4

Summary of the issue or suggestion:
----------------------------------------------
When I am playing Minecraft beta 1.7.3 in fullscreen using the fn+f11 key, every time I go to an inventory screen, the mouse leaps up slightly to the left of my helmet, away from my items, making it more difficult to access inventory items. The mouse is leaped away from the center of the screen each time I try to access my inventory.

What should happen:
------------------------------
The mouse should stay exactly in the center. This issue did not happen on the release version.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open beta 1.7.3 and load world

2. Press fn +f11 (or just f11 depending on system) for full screen

3. Open inventory

4. Observe mouse in wrong position

Suspected cause:
---------------------------
Something to do with my fullscreen in macOS and this version of Minecraft.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
I can post these if necessary.

Additional Info:
---------------------------
Note: This issue *only* started happening consistently after updating MultiMC today.

**Comment by nyaNezt** [comment]
well a similiar thing happens on windows, but even in fullscreen mode, when opening the inventory, for a split second you can see my character looking at the top left corner, and snap to the middle when the cursor actually appears. so i think its a ingame bug and multimc has probably nothing to do with it

**Comment by Heufneutje** [comment]
MultiMC just launches the game. It does not do anything with the game itself. What you could try is changing the LWJGL on the instance window's version tab and see if that makes a difference.

**Comment by Forkk** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's discord, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
