### ISSUE TITLE
mc15.2 crashes after installing forge

### ISSUE THREAD

**Issue by sky96111** [MultiMC/MultiMC5#3059]
System Information
-----------------------------
MultiMC version:0.6.11

Operating System:windows10 2004

Summary of the issue or suggestion:
----------------------------------------------
Minecraft 1.15.2 crashes after installing forge(31.1.0-31.1.30).Just install forge,no any other mod.

What should happen:
------------------------------
install forge in multimc

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/Uvtp1

Additional Info:
---------------------------

**Comment by ZekerZhayard** [comment]
Forge can't run under Java 14.
Forge 不支持 Java 14， Forge 1.15.2 只支持 Java 8~11

**Comment by sky96111** [comment]
> Forge can't run under Java 14, please use Java8 ~ 11.
> Forge 不支持 Java 14， Forge 1.15.2 只支持 Java 8 ~ 11。

谢谢，已经解决。（奇怪的知识增加了.jpg）
