### ISSUE TITLE
MultiMC Upgrade Fails on MacOS

### ISSUE THREAD

**Issue by mdedmon** [MultiMC/MultiMC5#3061]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: MacOS 10.15.4 (19E266)

Summary of the issue or suggestion:
----------------------------------------------
When trying to auto update, I'm getting an error version of "The new version didn't start or is too old and doesn't respond to startup checks. Roll back to previous version?" This has happened since the 0.6.8 version. I previously backed up my saves, deleted multimc and installed the new version. But, now it's still doing it. 

What should happen:
------------------------------
The update should work?

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Prompted to install new update

2. It fails

3.

Suspected cause:
---------------------------
???

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![Screenshot 2020-03-29 21 30 52](https://user-images.githubusercontent.com/459278/77867535-a9f48a00-7205-11ea-8c37-163f963f226e.png)

Additional Info:
---------------------------

**Comment by 71vl17** [comment]
Same thing
