### ISSUE TITLE
Failed to find Minecraft main class

### ISSUE THREAD

**Issue by meowmeoe** [MultiMC/MultiMC5#3064]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
After downloading Forge to 1.15.2, I attempt to launch offline.  I'm sent to the console with the error message "Failed to find Minecraft main class".  I get the same message for all other mods (except OptiFine for some reason), although the error description messages below are slightly different.

What should happen:
------------------------------
Minecraft should launch showing Forge.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.  Upload Forge (or any other mod) to new 1.15.2 instance

2.  Click Launch Offline

3.  Get sent to console with error message

Suspected cause:
---------------------------
Literally no idea.  The Forge mod is installed by MultiMC, so I have no clue to as how I could screw it up.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
Full logs:  https://paste.ee/p/D1F43
Just the error logs:

Using onesix launcher.

Failed to find Minecraft main class:
java.lang.ClassNotFoundException: io.github.zekerzhayard.forgewrapper.installer.Main
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:171)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with code -1.

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
You need to launch online once

**Comment by kingofsponges** [comment]
should work for me too (tho without any mod loader)

**Comment by shawnjbragdon-0** [comment]
not working for me either? lol and i just got the mod from the mod browser, didn't modify it

**Comment by obamamen** [comment]
same

**Comment by BigTunaKahuna** [comment]
For anyone running into this issue, what fixed it for me was to log in on Microsoft with the account.
