### ISSUE TITLE
Very Important!- After opening MultiMC, if clicking 'Launch' or 'Launch Offline', box pops up asking for login creds

### ISSUE THREAD

**Issue by bloxanne123** [MultiMC/MultiMC5#3067]
System Information
-----------------------------
MultiMC version:
0.6.7
Operating System:
Win 10 Pro, Intel 5500 + GeForce 830m, Intel i5-5300U, 16GB DDR3 1600 Mhz w/ Samsung 860 EVO SATA 500GB capacity, currently using ~250GB. (Dell Latitude E5450)
Summary of the issue or suggestion:
----------------------------------------------
When I opened MultiMC, I don't know why, but when I clicked on 'Launch', or 'Launch Offline', I am asked for login credentials. I clicked on 'Launch' first, and it asked me for creds. If I click 'Launch Offline' first, it works

What should happen:
------------------------------
It should ask for a username to use. Then it opens up Minecraft. (If anyone knows how to get all the Minecraft 1.14.4 files, and not have to open up MultiMC at the same time, that would be nice as I usually don't need the additional features. I do occasionally, but usually not.

Steps to reproduce the issue (Add more if needed): It may be a problem w/ my system.
-------------------------------------------------------------
1. Open Normal Launcher.bat

2. Click 'launch offline' button. It will not ask for login creds

3. Click cancel and click 'Launch'. It should ask for login creds

4. Close everything, and open Normal launcher.bat again.

5. Click 'Launch'. It should start to open the smaller dialog box for player name, but it closes that and should go straight to login creds.

6. Repeat above, but with 'Launch Offline'. It should only open the login creds dialog box.

7. Repeat all steps but with cracked launcher.bat

8. IMPORTANT NOTE: You MUST close Normal launcher.bat, open up cracked launcher.bat, let it go to the user interface, and then close it before doing step 6. But, try doing random combos of Launch and Launch offline from both cracked launcher.bat and normal launcher.bat. And make sure to alternate if you do the random combos.

Suspected cause: 
---------------------------
Either my system or I somehow need an account. If so, please let me know how to get one! Second suspected cause: Unknown.

Logs/Screenshots:
----------------------------
For some reason, I cannot take screenshots w/ MultiMC open.

Additional Info:
---------------------------

**Comment by peterix** [comment]
You get an account by creating it on minecraft.net and buying a Minecraft license.

**Comment by peterix** [comment]
Cracked anything is not supported here ... unless the world falls apart and Mojang/Microsoft fails to maintain the required services.

**Comment by bloxanne123** [comment]
So multiplayer is off the table? Do you know a way to get Minecraft Java
Edition for free with whatever I'd get if I bought the full thing from
minecraft.net? Also, there is a cracked.launcher.bat file.

**Comment by peterix** [comment]
There is no such thing as a cracked.launcher.bat and never will be. Whatever you are using is NOT MultiMC, and you will not get any support here.
