### ISSUE TITLE
launcher said process exited with code -1 when i try to open the saves of the modpack volcanoblock

### ISSUE THREAD

**Issue by MaxTsuirbt** [MultiMC/MultiMC5#3069]
System Information
-----------------------------
MultiMC version:0.6.11

Operating System:windows10

Summary of the issue or suggestion:
----------------------------------------------
Process exited with code -1

What should happen:
------------------------------
open the saves

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.download the modpack on the curseforge

2.install the instance

3.open the game and creat a save

Suspected cause:
---------------------------
I don't know

Logs/Screenshots:
----------------------------
https://paste.ee/p/aADuT
https://paste.ee/p/EcHEZ
Additional Info:
---------------------------

**Comment by Tunacan427** [comment]
looks like a corrupted world (not sure). and this isnt really a multimc issue.

**Comment by phit** [comment]
lwjgl doesn't seem to be happy with your keyboard layout and something you've bound, try deleting your options.txt to reset all keybinds

this was fixed in vanilla by not letting you bind these keys, maybe the mod controlling is ignoring this?
https://bugs.mojang.com/browse/MC-102867

**Comment by MaxTsuirbt** [comment]
The issue has already been solved.Thanks a lot!
