### ISSUE TITLE
Crash when starting any modpack

### ISSUE THREAD

**Issue by DasVoelkel** [MultiMC/MultiMC5#3072]
System Information
-----------------------------
MultiMC version: V0.6.7

Operating System: Archlinux

Summary of the issue or suggestion:
----------------------------------------------

Starting a modpack causes a crash,  have no idea how java works though, so reading this log gets me nowhere as I don't understand the javas structure.

What should happen:
------------------------------
Start the modpacks

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
I tried this with these modpacks:
https://www.curseforge.com/minecraft/modpacks/enigmatica2light
https://www.curseforge.com/minecraft/modpacks/rlcraft
I created the instances via the link that twitch spits out  if you download the files. Which has worked perfectly well for me in the past.

I stopped trying after 2 because the error logs seems to say the same thing:
https://paste.ee/p/Vw1M6
https://paste.ee/p/nt5C4

and I hope someone can decipher this.

Suspected cause:
---------------------------
No Idea.

Logs/Screenshots:
----------------------------
https://paste.ee/p/Vw1M6
https://paste.ee/p/nt5C4

Additional Info:
---------------------------

**Comment by peterix** [comment]
You need Java 8. See: https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java

**Comment by DasVoelkel** [comment]
and obviously i missed something obvious, thanks !

**Comment by Zetabite** [comment]
Cause it says java 11
