### ISSUE TITLE
NVidia GeForce Experience detects MultiMC as Badlion Client

### ISSUE THREAD

**Issue by EberHure** [MultiMC/MultiMC5#3074]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 10 x64

Summary of the issue or suggestion:
----------------------------------------------
When I save a screenshot or recording of my MultiMC Minecraft instance using GeForce experience, it saves into a folder named Badlion Client. I had Badlion Client installed on my machine as well for only an hour at most before uninstalling it. I can't find any leftover traces of Badlion Client so I'm not sure why it still does this.

What should happen:
------------------------------
Screenshots of my MultiMC instances before installing Badlion would save into a folder called Base Profile.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install Badlion Client on same machine

2. Launch Badlion Client at least once

3. Open any MultiMC instance

4. Save a screenshot or screen recording using Nvidia GeForce Experience

Suspected cause:
---------------------------
I'm unsure, as I've removed all traces of Badlion Client

Logs/Screenshots:
----------------------------
![Capture](https://user-images.githubusercontent.com/34819855/78410133-7fc21400-75d9-11ea-9b37-986cf28ba4a1.PNG)

**Comment by peterix** [comment]
Report this bug to NVidia. This is not a MultiMC feature and I will not spend time on investigating it.
