### ISSUE TITLE
Account skin preview (top right of the interface) not showing the "Hat" layer

### ISSUE THREAD

**Issue by MsWolphie** [MultiMC/MultiMC5#3075]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Win10 64bits

Summary of the issue or suggestion:
----------------------------------------------

If the skin have a hat layer, the said layer is not shown, only the "base" one

What should happen:
------------------------------

Both layers should be shown (like in the Tab list in game)

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Have a skin with a "hat" layer

2. Boom, preview not showing it

Suspected cause:
---------------------------

Maybe the preview only takes the base layer?

Logs/Screenshots:
----------------------------
The skin preview in MultiMC interface, missing the "snout" part, which should be on the "hat" layer:
![image](https://user-images.githubusercontent.com/49898596/78412634-583c6d00-7614-11ea-9914-bc55e83e6139.png)

The skin preview in mcname.com, with both layers visible:
![image](https://user-images.githubusercontent.com/49898596/78412658-773aff00-7614-11ea-98e6-0f51ed4567cc.png)

Additional Info:
---------------------------
Seems like the preview doesn't like to refresh itself instantly either, but I can't "force" a refresh, so I couldn't test this a bit more unfortunately

I know it's not something really crucial, I can live with it x) But since I couldn't really find any issue mentionning it, here it is? '^'

**Comment by Scotsguy** [comment]
It does now. I'm not sure since when, presumably crafatar changed something.

**Comment by phit** [comment]
was fixed with https://github.com/MultiMC/MultiMC5/pull/3241
