### ISSUE TITLE
MultiMc with Forge 1.8.9 not starting

### ISSUE THREAD

**Issue by Braincoke24** [MultiMC/MultiMC5#3077]
System Information
-----------------------------
MultiMC version: 0.6.11-1430 on win32

Operating System: Windows 10 Home

Summary of the issue or suggestion:
----------------------------------------------
1.8.9 Instance with Forge doesn't start/crashes on start
"Failded to start Minecraft"

What should happen:
------------------------------
Minecraft window opens and shows loading screen

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a new instance

2. Select Version 1.8.9

3. Click "Install Forge"

4. Install recommended version [11.15.1.1722] (Same issue with newest version [11.15.1.2318])

5. Click Launch

Suspected cause:
---------------------------
¯\_(ツ)_/¯

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/yimZt

Additional Info:
---------------------------
Starting the same instance with forge disabled works as expected.
Forge Version 11.15.1.2318 works with Vanilla Launcher.

**Comment by peterix** [comment]
Use java 8.
https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java

**Comment by Braincoke24** [comment]
Thanks, it worked!
