### ISSUE TITLE
MultiMc will not open Minecraft. 

### ISSUE THREAD

**Issue by Lilmo0305** [MultiMC/MultiMC5#3078]
System Information
-----------------------------
MultiMC version:
0.6.7
Operating System:
64-bit operating system
Summary of the issue or suggestion:
---------------------------------------------- 
MultiMc gets stuck on what seems to be the last file for the library files from Mojang. 

What should happen:
------------------------------
The game should load the bar completely and launch Minecraft. 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. update a computer from windows 7 to windows 10. 

2. Use the link in the additional info for the update. 

3. Try and launch the game with any instance afterward. 

Suspected cause:
---------------------------
Updating my old computer from Windows 7 to Windows 10. 

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Logs:
https://paste.ee/p/m6YR0

Additional Info:
---------------------------
Before updating my computer, I was able to run MultiMc with ease. However after the update, I tried it and the game either 1. Crashed or 2. Did not load whatsoever. I tried to delete then re-install, go into the folder and delete un-needed material, and even delete the library file with no luck. For the website I used for the update (if it has any use) is: https://www.microsoft.com/en-us/software-download/windows10?ranMID=24542&ranEAID=0JlRymcP1YU&ranSiteID=0JlRymcP1YU-ZJ6IuYaJnHczPoAswS6WBg&epi=0JlRymcP1YU-ZJ6IuYaJnHczPoAswS6WBg&irgwc=1&OCID=AID2000142_aff_7593_1243925&tduid=(ir__uzfdfpa3jgkfrz9bkk0sohzn0u2xlgveerxzqfe100)(7593)(1243925)(0JlRymcP1YU-ZJ6IuYaJnHczPoAswS6WBg)()&irclickid=_uzfdfpa3jgkfrz9bkk0sohzn0u2xlgveerxzqfe100&irgwc=1&OCID=AID2000142_aff_7593_1238941&tduid=(ir__osm3rwbtbgkftj93kk0sohzg2u2xnzgp92vzobff00)(7593)(1238941)()()&irclickid=_osm3rwbtbgkftj93kk0sohzg2u2xnzgp92vzobff00

**Comment by SquirrelKiev** [comment]
Basic troubleshooting ideas here - 
1. Create a blank instance and see if it happens 
2. Reinstall MultiMC and see if that fixes it. 
Might work. Idk.

**Comment by IceCryptonym** [comment]
Do you have the graphics card drivers installed?
