### ISSUE TITLE
Can't launch any instances, "Failed to download the assets index"

### ISSUE THREAD

**Issue by Tunacan427** [MultiMC/MultiMC5#3079]
System Information
-----------------------------
MultiMC version:
0.6.11-1344
Operating System:
Arch Linux (x64)
Summary of the issue or suggestion:
----------------------------------------------
This issue started after the update and every time I try it gets worse. When I try to start a instance it gets stuck at "Updating assets index...". After some time it closes and the error in the log appears. When I first launch a instance it works and the game works properly, but on the next launch sometimes it stops working. I have to restart my computer or be lucky for it to work again. This happens on all instances. It works when you launch the instance offline. 

What should happen:
------------------------------
The updating assets index window should go away and the instance should start.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Be unlucky

2. Try to start an instance

Suspected cause:
---------------------------
No idea.

Logs/Screenshots:
----------------------------
https://paste.ee/p/2VbsA

Additional Info:
---------------------------
Can't reproduce on Windows 10.

**Comment by Zetabite** [comment]
Did you launch it online once?

**Comment by Tunacan427** [comment]
I can launch online it the first few times. After that the updating assets index thing just stops working.

**Comment by Tunacan427** [comment]
Closing because the issue seems to have resolved itself. It was probably caused by something in my system that has been resolved now.

**Comment by Kyllingene** [comment]
I have the same issue, and it comes and goes. I'm on a wayyy later version, 0.7.0.

**Comment by Aurumaker72** [comment]
Same here, it persists on 0.7.0-3714

**Comment by dgubz** [comment]
fix for me:
disable any vpn, run offline, then online
