### ISSUE TITLE
Instances from 1.15 and up fail to launch

### ISSUE THREAD

**Issue by bloxanne123** [MultiMC/MultiMC5#3080]
System Information
-----------------------------
MultiMC version: 0.6.7

Operating System:
Win 10 Pro
Summary of the issue or suggestion:
----------------------------------------------
When opening any instance from 1.15 and up, I receive a 'Failed to find minecraft assests'

What should happen:
------------------------------
It should open the console window and display an 'X' in the upper left corner of the instance.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open cracked launcher.bat

2. Add any instance from 1.15 and up

3. Launch any one of them offline.

Suspected cause:
---------------------------
Uknown

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/5TJlZ

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
Update MulitMC. 0.6.7 doenst work cause the old meta servers went down
