### ISSUE TITLE
"Let's Talk About Forge" is still prominent depsite 0.6.11

### ISSUE THREAD

**Issue by LeafHacker** [MultiMC/MultiMC5#3082]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: Arch Linux

Summary of the issue or suggestion:
----------------------------------------------
Despite multimc now supporting forge for 1.13+, [Let's Talk About Forge](https://multimc.org/posts/forge-114.html) is still present on the main window. This can give the impression that forge is still not supported even though it is.

What should happen:
------------------------------
Perhaps a brief follow up article should be posted, announcing that forge 1.13+ is now supported by MultiMC 0.6.11+. Assuming the latest blog post is what is shown on the main page.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC

2. Look at the bottom left of the main GUI window

3. Observe that "Let's Talk About Forge" is still present

Suspected cause:
---------------------------
The latest blog post always being shown on the main window and "Let's Talk About Forge" _being_ the latest blog post.

Logs/Screenshots:
----------------------------
![image](https://user-images.githubusercontent.com/23565638/78604672-17319c00-7852-11ea-91a7-e7bdf81978b8.png)

Additional Info:
---------------------------
N/A

**Comment by Janrupf** [comment]
This in fact is know, at some point, the blog post will be updated (or a new post will be published)

**Comment by Scythern** [comment]
Looks like this still needs to happen - I've been assuming I can't use forge on new versions for the last month so haven't bothered checking. Was a welcome surprise when I did, haha.
