### ISSUE TITLE
1.12.2 Modpack Crashes with Error Code 1 On Launch

### ISSUE THREAD

**Issue by Casey110405** [MultiMC/MultiMC5#3083]
System Information
-----------------------------
MultiMC version: 0.6.12-develop-1434

Operating System: Windows 10 (64-bit)

Summary of the issue or suggestion:
----------------------------------------------
My modpack crashes with error code 1 every time I load it.

What should happen:
------------------------------
The modpack should load like normal.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Loaded my modpack on MultiMC.

2. It starts launching the game.

3. It crashes.

Suspected cause:
---------------------------
Either a Forge issue or mod issue.

Logs/Screenshots:
https://paste.ee/p/1lgOx
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
you have two versions of MJRLegendsLib enabled. disable/delete one

**Comment by Casey110405** [comment]
I tried that, and thanks for reminding me, but it still crashes the same way it did before.
https://paste.ee/p/uEzt4

**Comment by Casey110405** [comment]
Alright, I spent a bit looking at the log and determined vanilla fix was the problem. Removed the mod and now the game works like a charm. Thanks for the help!
