### ISSUE TITLE
I was going to the menu, it crashed, and when I tried to restart it didn't work

### ISSUE THREAD

**Issue by Isucc1** [MultiMC/MultiMC5#3085]
System Information
-----------------------------
MultiMC version: 5 / 0.6.11-1430

Operating System: Windows 10 

Summary of the issue or suggestion: Game doesn't load up
----------------------------------------------

What should happen: It loads up
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download pixelmon

2. Accidentally do /struc in your house

3. Go to menu and let it crash

4. reload game

Suspected cause: No idea
---------------------------

Logs/Screenshots:  https://paste.ee/p/y2pgX
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info: I tried to uninstall forge, no luck, and I tried to fix it manually, and as you can guess, no luck
---------------------------

**Comment by Zetabite** [comment]
Upload log like this: https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by Isucc1** [comment]
I have a link to the upload log here: https://paste.ee/p/y2pgX
Sorry for forgetting, and I can't find any way to edit the actual thing

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
