### ISSUE TITLE
Build error on Windows

### ISSUE THREAD

**Issue by Pannoniae** [MultiMC/MultiMC5#3086]
System Information
-----------------------------
MultiMC version: 296ff6d (latest commit)

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
When trying to compile MultiMC using Qt Creator, the following compile error happens (along with countless warnings about "class needs to have dll-interface to be used by clients of class": 
```
D:\dev\cpp\MultiMC5\libraries\libnbtplusplus\include\tag_list.h:217: error: C2668: 'nbt::make_unique': ambiguous call to overloaded function
D:\dev\cpp\MultiMC5\libraries\libnbtplusplus\include\make_unique.h:30: could be 'std::unique_ptr<Sub,std::default_delete<Sub>> nbt::make_unique<T,const Arg&>(const Arg &)'
with
[
    Sub=nbt::tag_string,
    T=nbt::tag_string,
    Arg=std::string
]
D:\dev\vs\VC\Tools\MSVC\14.25.28610\include\memory:2063: or       'std::unique_ptr<Sub,std::default_delete<Sub>> std::make_unique<T,const Arg&,0>(const Arg &)' [found using argument-dependent lookup]
with
[
    Sub=nbt::tag_string,
    T=nbt::tag_string,
    Arg=std::string
]
D:\dev\cpp\MultiMC5\libraries\libnbtplusplus\src\tag_list.cpp:35: see reference to function template instantiation 'void nbt::tag_list::init<nbt::tag_string,std::string>(std::initializer_list<std::string>)' being compiled
D:\dev\cpp\MultiMC5\libraries\libnbtplusplus\include\tag_list.h:217: error: C2672: 'std::vector<nbt::value,std::allocator<nbt::value>>::emplace_back': no matching overloaded function found
```

What should happen:
------------------------------
It should compile.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Clone project

2. Open in Qt Creator

3. Set compiler, environment variables, etc.

4. Run CMake

5. Hit Build all

Suspected cause:
---------------------------
None.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
Building with visual studio is not and will not be supported.

**Comment by peterix** [comment]
That said, the Qt installer should have a decent GCC-based toolchain available.

**Comment by Pannoniae** [comment]
No, I was not building with Visual Studio. I was using QT Creator. (Although yes, it was with MSVC)
I'll look into building with GCC on Windows.

**Comment by Janrupf** [comment]
In this context Visual Studio means MSVC.
