### ISSUE TITLE
Minecraft Alpha Versions stuck on blank screen

### ISSUE THREAD

**Issue by Jaayyyy** [MultiMC/MultiMC5#3089]
System Information
-----------------------------
MultiMC version:
Version 0.6.11-1370
Operating System:
Mac OS X Catalina 10.53.3 64-Bit
Summary of the issue or suggestion:
Minecraft alpha versions 1.0 to 1.3 will not load and get stuck on a blank screen.

What should happen:
Minecraft loads. successfully alpha versions, showing menu screen.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download MultiMC 0.6.11-1370 on osx64

2. Create an instance for an old alpha version of Minecraft (I used 1.2.6)

3. Run Minecraft

Suspected cause:
Unsure

Logs/Screenshots:

MultiMC version: 0.6.11-1370

Minecraft folder is:
/Applications/MultiMC.app/Contents/MacOS/instances/a1.2.3/.minecraft

Java path is:
/Library/Java/JavaVirtualMachines/jdk-13.0.2.jdk/Contents/Home/bin/java

Java is version 13.0.2, using 64-bit architecture.

Main Class:
  

Native path:
  /Applications/MultiMC.app/Contents/MacOS/instances/a1.2.3/natives

Traits:
traits legacyLaunch
traits texturepacks

Libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/minecraft/a1.2.3/minecraft-a1.2.3-client.jar

Native libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-osx.jar

Params:
  

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: a1.2.3", -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 5815

Using onesix launcher.

Launching with applet wrapper...
28
Setting user: Jaayyyy1, token:<ACCESS TOKEN>:<PROFILE ID>
org.lwjgl.LWJGLException: Native cursors not supported
	at org.lwjgl.input.Cursor.<init>(Cursor.java:88)
	at og.<init>(SourceFile:32)
	at net.minecraft.client.Minecraft.a(SourceFile:224)
	at net.minecraft.client.Minecraft.run(SourceFile:563)
	at java.base/java.lang.Thread.run(Thread.java:830)
Apr 11, 2020 1:26:50 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.OSXEnvironmentPlugin
Apr 11, 2020 1:26:50 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to enumerate device: Device open failed: -536870174

Apr 11, 2020 1:26:50 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to enumerate device: Device open failed: -536870174

Apr 11, 2020 1:26:50 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to enumerate device: Device open failed: -536870174

Starting up SoundSystem...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
OpenAL initialized.

Additional Info:
https://paste.ee/p/8g6iF

**Comment by Zetabite** [comment]
please upload the log as followed: https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by Jaayyyy** [comment]
Will do once I get home in about an hour.

**Comment by IceCryptonym** [comment]
The alpha versions do not work on Java 13. You need Java 8 to play the alpha versions.

**Comment by salthepal128** [comment]
same problem, but I have java 8

**Comment by TehcJS** [comment]
same problem, i have tried java 8 with openjdk and openj9

**Comment by Zetabite** [comment]
OpenJ9 is not recommened, use hotspot

**Comment by QuImUfu** [comment]
It seems like alpha versions don't work on Mac OS X (any more?), as this crash happens because lwjgl thinks that transparent cursors are not supported.  
On Linux this version of the alpha works fine with java 8.

**Comment by TehcJS** [comment]
it works fine in the official launcher. this is definitely a multimc issue

**Comment by TehcJS** [comment]
> OpenJ9 is not recommened, use hotspot

I am able to use OpenJ9 with versions 1.12 and below. I've also tried OpenJDK and Hotspot, both of which don't work.

**Comment by Zetabite** [comment]
Whatever issue you are having, should be investigated, as OpenJ9 is not recommended, nor supported as far as i remember

**Comment by peterix** [comment]
Use Orcale Java 8.

**Comment by peterix** [comment]
That is all.

**Comment by TehcJS** [comment]
I've tried that. It's still doing this.
