### ISSUE TITLE
MultiMC fails to launch forge/inconsistant

### ISSUE THREAD

**Issue by TaintedMeat** [MultiMC/MultiMC5#3090]
System Information
-----------------------------
MultiMC version: 
0.6.11-1344

Operating System:
Linux Mint

Summary of the issue or suggestion:
----------------------------------------------
MultiMC sometimes stops running Forge before it launches.

What should happen:
------------------------------
Forge should run.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
I don't know. It usually runs forge successfully and I've been able to get my mods in a stable configuration, but sometimes it just refuses to start up. It's not consistent, as I have disabled a random mod, ran minecraft successfully, then re-enabled the same mod and it continues to run (where it previously had not.)

Suspected cause:
---------------------------
No clue.

Logs/Screenshots:
----------------------------
https://paste.ee/p/0wIQJ

Additional Info:
---------------------------
(Forge has also been crashing when loading sounds, but I don't expect that to be related.)

**Comment by TaintedMeat** [comment]
**It seems that Better Portals was the issue.** **BUT** I had it turned on and running smoothly previously, so I'm still not certain it was the problem.

**Comment by Janrupf** [comment]
Well, it probably was a race condition, see here for instructions on how to fix it: https://kbdeveloper.qoppa.com/removing-a-signature-from-a-signed-jar-file/

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
