### ISSUE TITLE
Crashes when loading forge.

### ISSUE THREAD

**Issue by H4rl00** [MultiMC/MultiMC5#3091]
System Information
-----------------------------
MultiMC version: LATEST

Operating System: Windows 10 Pro Latest 64bit

Summary of the issue or suggestion:
----------------------------------------------
The Launcher Crashes in a Nullpointer Exception

What should happen:
------------------------------
Launching the Game Normally

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add atleast the 106 mods i used

2. Launch the game

3. Get the crash

Suspected cause:
---------------------------
Crash

Logs/Screenshots:
----------------------------
https://paste.dimdev.org/ayujumatuk.md
Additional Info:
---------------------------

**Comment by Zetabite** [comment]
you are adding 1.15 mods and 1.12 mods. You are on 1.12, kick out all non 1.12 mods. and next time use mmc upload log button

**Comment by 0H4rl3qu1n0** [comment]
i noticed that it works now lol

Den mån 13 apr. 2020 kl 02:54 skrev Adrian <notifications@github.com>:
