### ISSUE TITLE
Support new FTB API

### ISSUE THREAD

**Issue by jamierocks** [MultiMC/MultiMC5#3095]
## Introduction

Creeperhost have just [released the new Feed The Beast pack installer](https://forum.feed-the-beast.com/threads/ftb-update-new-launcher-ftb-omnia-released.302085/#post-2020272) (they call FTB App). It uses a totally revamped system than the older FTB Launcher, involving a mostly nicely designed API - documented [here](https://modpacksch.docs.apiary.io/).

## Potential Obstacles

There are many ways you could go about implementing support, however note the following:
1. There is currently no way to list all packs
2. There is currently no pagination for any routes
3. All routes are seemingly limited to 50 results

The last 2 points don't currently bear much weight as there aren't 50 packs in the system, so no pagination is required - though the 1st point holds.

## Potential Solutions

I see a few potential solutions here, but I'll list 2 that I think would be the most practical:

1. Only display promoted/latest/popular packs as per the routes available from the API, similar to CreeperHost's FTB App.
2. Crawl their API for packs and add such data to meta (I have done a [similar solution](https://github.com/jamierocks/neptune-ftb-meta) for my own tooling).
    - Alternatively, crawling of their API could be done in MultiMC.

**Comment by RecurringRaccoon** [comment]
Yes please! Lots of FTB packs on CurseForge are already outdated since they've been pushing updates exclusively to FTB App. Seems like they're about to take them down, too. Supporting this API is necessary for Feed The Beast players, even if it's only search and install.

**Comment by peterix** [comment]
Merged into develop
