### ISSUE TITLE
Crash running 1.14.4 instances

### ISSUE THREAD

**Issue by belathus** [MultiMC/MultiMC5#3096]
System Information
-----------------------------
MultiMC version: 0.6.12-1349 (though, I tried 0.6.11-1344 first)

Operating System: Linux Mint

Summary of the issue or suggestion:
----------------------------------------------
Minecraft crashes after installing Forge 1.14.4.

What should happen:
------------------------------
Not Crash

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add new instance of Minecraft 1.14.4

2. Add Forge (I tried 28.2.0 and 28.2.4)

3. Start Forge

Suspected cause:
---------------------------
I was wondering if this crash is specific to Linux, but I see others were able to run MC+Forge with a similar setup. As it is now, I have no idea why this is crashing like this.

Logs/Screenshots:
----------------------------
https://paste.ee/p/ahLaC

Additional Info:
---------------------------
I'm able to run 1.12.2 and 1.15.2 instances just fine.
I have no mods installed. It crashes with them, too, but I removed them to test.

**Comment by Zetabite** [comment]
You're using Java 11. Versions other than Java 8 are not designed to be used with Minecraft and may cause issues. See here for help installing the correct version.

**Comment by belathus** [comment]
Yeah, forcing it to use Java 8 works fine. I wonder how I got Java 11 installed. Alas, thanks.
