### ISSUE TITLE
Skins are Default 

### ISSUE THREAD

**Issue by UltriaPrime101** [MultiMC/MultiMC5#3099]
System Information
-----------------------------
MultiMC version:0.6.12

Operating System:

Summary of the issue or suggestion: 
All the skins show up on default despite the fact we have custom skins, problem is only on my screen.
----------------------------------------------

What should happen:
------------------------------
Everyones skins should show up but it just plain default for me

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------
Unknown

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![image](https://user-images.githubusercontent.com/63894628/79628960-095dff80-810b-11ea-8c4b-d891ac36d1a0.png)
![image](https://user-images.githubusercontent.com/63894628/79628975-24c90a80-810b-11ea-8865-bc21fec6627b.png)

Additional Info:
---------------------------
As seen in the images my screen isn't showing everyones skins, but everyone else can see it just fine. Just want a suggestion on how to fix it, if it is fixable

**Comment by Zetabite** [comment]
trying adding this to multicmc java arguments: `-Djava.net.preferIPv4Stack=true`

**Comment by UltriaPrime101** [comment]
That fixed it, Thank you so much!
