### ISSUE TITLE
When i try to log in in multi mc it says Invalid credentials

### ISSUE THREAD

**Issue by Tomas0402** [MultiMC/MultiMC5#3100]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 10 Home 64-bit

Summary of the issue or suggestion: I just can't sign in so I can't play
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause: I think that it may be because of the pressure put on servers of raytracing version of minecraft
---------------------------

Logs/Screenshots:
![image](https://user-images.githubusercontent.com/63920173/79644106-0dd7f600-81a7-11ea-9197-432eeca38c52.png)
![image](https://user-images.githubusercontent.com/63920173/79644115-1c261200-81a7-11ea-98e1-c3f4807f9d27.png)

----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
After totally playing for like 30 hours without problem, I once started multi mc and was signed out so i logged in but it didn't accept my password/name/e-mail

**Comment by Janrupf** [comment]
Please fill out the template

**Comment by Tomas0402** [comment]
I hope this is all you need

**Comment by Janrupf** [comment]
Did you buy the game?

**Comment by Tomas0402** [comment]
Yes

**Comment by Tomas0402** [comment]
Or exactly it's my brothers account but he gave it to me

**Comment by Janrupf** [comment]
The last screenshot basically says that the account exists (you always need to use the email) but that it is just a demo one.

**Comment by Tomas0402** [comment]
That's weird, but when it was working I was signed with account name

**Comment by Tomas0402** [comment]
Ok, i just got idea to log in on technic launcher and it still says that i have invalid credentials so i guess that somebody stole my account so i'll try to check it when i have time to be with my brother

**Comment by Tomas0402** [comment]
Yeah, I can't sign in minecraft launcher so i really think that my account is stolen
