### ISSUE TITLE
Can't install Forge for 1.14.4+

### ISSUE THREAD

**Issue by Matoca** [MultiMC/MultiMC5#3104]
System Information
-----------------------------
MultiMC version: 5 0.6.11-1430

Operating System: Windows 10 Pro

Summary of the issue or suggestion:
----------------------------------------------
When I create a new fresh instance on 1.14.4+ and run the game in online mode, my Minecraft downloads normally. Then, I exit Minecraft, go to the version tab and install the recommended Forge. And then, when I execute the game again it doesn't work and the game doesn't open anymore (this issue only stops if I disable Forge in version tab).

What should happen:
------------------------------
Minecraft should launch with Forge installed.

Logs/Screenshots:
----------------------------
https://pastebin.com/we7cMVh4

**Comment by Zetabite** [comment]
you are using an unofficial build of mmc. Get an official version and comeback.
