### ISSUE TITLE
QWERTY and AZERTY keyboard

### ISSUE THREAD

**Issue by louis-1268** [MultiMC/MultiMC5#3105]
Minecraft detects a QWERTY keyboard but I've a AZERTY keyboard. I'm on MacOS X 10.15.4.
All my applications are in azerty excepted Minecraft
Multi Mc version: 0.6.11

**Comment by Heufneutje** [comment]
I'm not sure how that is a MultiMC issue. MultiMC just launches the game. It doesn't do anything to the game itself.

**Comment by louis-1268** [comment]
But when I use the vanilla launcher, my keyboard is normally detected in AZERTY.

**Comment by Heufneutje** [comment]
Might be an LWJGL issue. You could try hitting Edit Instance and changing the LWJGL version to see if that fixes it.

**Comment by louis-1268** [comment]
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/37590019/79853421-54586b00-83c8-11ea-95d4-ab7a0d830fdb.png">

I had the 2.9.4, the last version and I tried the 2.9.3 but nothing changed. Maybe an older version of LWJGL?

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to reply and I'll be happy to reopen this.
