### ISSUE TITLE
Feature: server instance

### ISSUE THREAD

**Issue by A2va** [MultiMC/MultiMC5#3106]
System Information
-----------------------------
MultiMC version: MultiMC 5 version 0.6.11-1430

Operating System: Windows 10 64 bits 18363

Summary of the issue or suggestion:
----------------------------------------------

MultiMC allows you to have client instances but it would be nice if it were possible to have a server instance. And to install Vanilla servers but also Paper,Spigot. 
This would be very useful for example for terraforming which requires plugins.

**Comment by phit** [comment]
please use the search before making new issues/feature requests
https://github.com/MultiMC/MultiMC5/issues/60

**Comment by A2va** [comment]
I'm really sorry I didn't think to do a search before posting my suggestion.
