### ISSUE TITLE
MultiMC issue with session

### ISSUE THREAD

**Issue by jj136975** [MultiMC/MultiMC5#3107]
Hi, since 3 days, I can't connect to my server and get the error "invalid session" when I try to connect. The problem is that on MultiMC launcher, the session check at the bottom still red always. I'm using a premium minecraft account, I've tried to restart my pc, change my password, disconnect reconnect my account, same on Minecraft launcher. But it still red and I can't acces my own server.
![image](https://user-images.githubusercontent.com/57088933/79968529-82a17d80-8490-11ea-8457-6e19f479f068.png)
If anyone know why and can help me, it will be very helpfull for me

**Comment by Zetabite** [comment]
Thats a mojang issue. If you were already logged in you could use mc normally, but people who didnt connect to a session server in time now need to wait for mojang to fix that connection

**Comment by jj136975** [comment]
d'you mean that mojang session servers are dead at the moment ?

**Comment by Zetabite** [comment]
yes

**Comment by jj136975** [comment]
ok thank you very much.

**Comment by jj136975** [comment]
![image](https://user-images.githubusercontent.com/57088933/79977140-0b72e600-849e-11ea-8d74-41037d0a5af5.png)

but it look that session server is okay

**Comment by jj136975** [comment]
oh no, mb, it's down (the website I looked was not up to date

**Comment by LukasAppleFan** [comment]
In MultiMC session is red for me at the moment

**Comment by Heufneutje** [comment]
That;s cause it's down according to Mojang. The issue is on their side.

**Comment by LukasAppleFan** [comment]
Do you know what it does, since it does not seem to affect anything.

**Comment by jj136975** [comment]
Because a lot of servers are using custom UUIDs and not Minecraft sessions

**Comment by Saber664** [comment]
My session is red? When does it go back to green?

**Comment by Zetabite** [comment]
When Mojang fixes it

**Comment by kb-1000** [comment]
@Saber664 it means nothing anymore sadly, the status thing is broken on mojang's side

**Comment by Chew** [comment]
Can confirm, check out [WEB-2303](https://bugs.mojang.com/browse/WEB-2303)
