### ISSUE TITLE
Central Mod Folder alteration does not alter Instances?

### ISSUE THREAD

**Issue by Areolata7** [MultiMC/MultiMC5#3108]
Running Java 1.14.4 with 0.6.11.1430

I have been creating my own texture pack and am constantly tweaking it. But editing the texture file in the central mods folder does not update that same exact texture file used by my instances - even though the file was added into each instance via the central mods folder. So every time I  make any alteration to the file in the central mods folder I have to go into each instance, remove the texture pack, and then add it back in. This is the only way to refresh the texture pack so the changes appear in the worlds for each instance. This has become incredibly tedious. The name of my texture pack never changes, I simply update something within it whenever I make a change. 

Shouldn't the instances be relying on the central mods folder so that any changes made will trickle down to all associated instances? I thought choosing the mod or texture pack from the central folder was simply directing the instance to use that file in that folder. However it appears that each instance is just copying it from the central folder into its own independent folder. I also thought that deleting a mod from the central folder would then remove that same mod from any instances that were using it. If not; what is the point of having a central folder if you still have to manage completely separate mod/texture folders for each instance? 

Am I misunderstanding something or is there a setting I can change so that any updates I apply in the central folder will trickle down to all instances that use the specific file I update?

Please advise.

**Comment by Zetabite** [comment]
The instances dont use the central mods folder. You can see this mods folder more like a folder to keep all your mod files, where you can easily find and add them to the modpack

**Comment by peterix** [comment]
It's just a default location for browse dialogs.
