### ISSUE TITLE
minecraft dungeons dragons and space shuttles 1.12.2 (Game Crash)

### ISSUE THREAD

**Issue by AncientWho** [MultiMC/MultiMC5#3110]
System Information
-----------------------------
MultiMC version: 5 - Version 0.6.11-1430

Operating System: Windows 10 64

Summary of the issue or suggestion:
----------------------------------------------
When playing, just out of nowhere my game crashes. Sometimes it happens right after playing for 10 mins, sometimes it happens after 1 or 2 hours of playing.

What should happen:
------------------------------
Not crashing? Maybe a fix?

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Start Minecraft.

2. Log in the server.

3. Play for a few minutes.

Suspected cause:
---------------------------
I think it's the mods or my PC. I don't know anything about codes.

Logs/Screenshots:
----------------------------
https://paste.ee/p/w4IkS

Additional Info:
---------------------------
Mods are on 1.12.2

**Comment by QuImUfu** [comment]
The only reference to that error i found on the web is that it indicates heap corruption. That would mean that either you memory is faulty/unstable or there is a hidden issue somewhere in your driver stack or jvm. It is typical for heap corruption to be detected at seemingly random times.  
Try running memtest to rule out memory corruption.  
If you find no memory corruption, update your GPU driver. If that doesn't work try a different build of Java (e.g. https://aws.amazon.com/corretto/).

**Comment by AncientWho** [comment]
> The only reference to that error i found on the web is that it indicates heap corruption. That would mean that either you memory is faulty/unstable or there is a hidden issue somewhere in your driver stack or jvm. It is typical for heap corruption to be detected at seemingly random times.
> Try running memtest to rule out memory corruption.
> If you find no memory corruption, update your GPU driver. If that doesn't work try a different build of Java (e.g. https://aws.amazon.com/corretto/).

It's not the memory. I'm gonna try a different Java later today and see if it solves the problem.

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
