### ISSUE TITLE
Launching Minecraft 1.14.4 returns error. First time it has ever happened.

### ISSUE THREAD

**Issue by bloxanne123** [MultiMC/MultiMC5#3111]
If you believe your issue to be a bug, please make sure you check the wiki page: https://github.com/MultiMC/MultiMC5/wiki/Report-a-Bug
-->

System Information
-----------------------------
MultiMC version:
0.6.7-1375
Operating System:
win 10 pro
Summary of the issue or suggestion:
----------------------------------------------
when i open 1.14.4, it opens up a console window saying it failed to extract something.
What should happen:
------------------------------
It should normally launch minecraft!

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC using cracked.bat file

2. Launch 1.14.4 offline.

3. Error should pop up-see screenshot below.

Suspected cause:
---------------------------
No idea.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

https://paste.ee/p/Wqpyp-Log
![image](https://user-images.githubusercontent.com/63023773/80136232-6fb1aa80-856f-11ea-8b55-c3e038d4443e.png)

Additional Info:
---------------------------
The issue may or may not reproduce properly using steps given. I believe it is specific to me.

**Comment by Zetabite** [comment]
You are missing fabric api

**Comment by bloxanne123** [comment]
But how? I saved the game, quit to title, and quit minecraft. An hour or so later, I opened MultiMC to launch 1.14.4, launched 1.14.4, and got hit with the error. I didn't touch any files.

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
