### ISSUE TITLE
Hello, I don't know why but when I click on the MultiMC.exe in the .zip folder, I install MultiMC but there is no icon on my desktop and when i double click on MultiMC.exe, it reinstall MultiMC and i lost my instances. Can someone help me please?

### ISSUE THREAD

**Issue by Guironium** [MultiMC/MultiMC5#3113]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Janrupf** [comment]
Please fill out the issue template, and use the title for what it is for: a title!

**Comment by Heufneutje** [comment]
https://github.com/MultiMC/MultiMC5/wiki/Getting-Started

**Comment by AzsaZazsa** [comment]
Extract the zip

**Comment by Scotsguy** [comment]
Closing, not actionable.
