### ISSUE TITLE
the error about  first defined here when I compile the tag_*.cpp

### ISSUE THREAD

**Issue by physics1024** [MultiMC/MultiMC5#3115]
System Information
-----------------------------
MultiMC version:5

Operating System:Raspbian

Summary of the issue or suggestion:(unknown)Incorrect conversion changes or header file,maybe because I use raspberry pi?
----------------------------------------------

What should happen:
-----------------------------

/usr/bin/ld: CMakeFiles/MultiMC_nbt++.dir/src/tag_array.cpp.o:(.data.rel.ro+0xc): multiple definition of `typeinfo for nbt::tag_array<int>'; CMakeFiles/MultiMC_nbt++.dir/src/tag.cpp.o:(.data.rel.ro+0x54): first defined here
and this just one of the 74 errors

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.git the code

2.use cmake to compile

3.make install and found this problem

Suspected cause:
---------------------------
Value conversion issue:  'int32_t'  (aka  'int'  ) to   'std::vector::size_type'  (aka  'unsigned int' )

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
It includes some of Chinese,but it doesn't matter
"错误“ means 'error'
"正在等待未完成的任务" means 'waiting for the rest tasks'
[log.txt](https://github.com/MultiMC/MultiMC5/files/4532234/log.txt)

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
MMC isnt supported to run on Raspberry Pi. You are on your own. Everybody trying it so far didnt get LWJGL running

**Comment by physics1024** [comment]
> MMC isnt supported to run on Raspberry Pi. You are on your own. Everybody trying it so far didnt get LWJGL running

I have already run LWJGL on rpi,and I have already run mc1.12 on my raspberry pi.But I just want to play the newest version!Could anyone help me with the newest version?

**Comment by peterix** [comment]
Sounds like you are using a compiler that MultiMC isn't tested/made with.

Well, C++ sucks. The code is correct.

**Comment by kb-1000** [comment]
It's because gcc has a bug on ARM. Use clang instead, and it will compile just fine.

**Comment by physics1024** [comment]
Thank you very much!I'll try it in the summer vacation.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kb1000"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月17日(星期天) 晚上8:00
收件人:&nbsp;"MultiMC/MultiMC5"<MultiMC5@noreply.github.com&gt;;
抄送:&nbsp;"Tony"<1738822365@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MultiMC/MultiMC5] the error about  first defined here when I compile the tag_*.cpp (#3115)





 
It's because gcc has a bug on ARM. Use clang instead, and it will compile just fine.

**Comment by physics1024** [comment]
Thanks for your help!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Petr Mrázek"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月17日(星期天) 晚上7:56
收件人:&nbsp;"MultiMC/MultiMC5"<MultiMC5@noreply.github.com&gt;;
抄送:&nbsp;"Tony"<1738822365@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MultiMC/MultiMC5] the error about  first defined here when I compile the tag_*.cpp (#3115)





 
Sounds like you are using a compiler that MultiMC isn't tested/made with.
 
Well, C++ sucks. The code is correct.
