### ISSUE TITLE
MultiMC Soulbound to cmd.exe

### ISSUE THREAD

**Issue by naqaden** [MultiMC/MultiMC5#3119]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 8.1

Summary of the issue:
----------------------------------------------
If MultiMC is not already running, starting it via CMD or BAT forces cmd.exe to stay open with output from MultiMC. This happens even if I use EXIT or EXIT /B. I'm not using START with /WAIT or /B. The worst part is: closing that cmd.exe causes MultiMC to close too.

It seems the only way to start MultiMC without a cmd window full of output is to start it manually. 

What should happen:
------------------------------
cmd.exe should ~~close~~ be released after MultiMC is started

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open cmd.exe

2. Run MultiMC.exe

Suspected cause:
---------------------------
The commits referenced in #1586 ?

Logs/Screenshots:
----------------------------
[//]: #
```
0.007 D <> Log initialized.
0.008 D MultiMC 5, (c) 2013-2019 MultiMC Contributors
0.008 D Version                    :  "0.6.11-1430"
```
etc...

**Comment by peterix** [comment]
I'd say this works as intended.

**Comment by Janrupf** [comment]
Using `start MultiMC.exe` should be enough

**Comment by naqaden** [comment]
> Using `start MultiMC.exe` should be enough

It is enough if alone, good point. I have PAUSE later in my .BAT. That makes MMC act like it does without START, and it suppresses input required to continue.

**Comment by naqaden** [comment]
Calling TASKKILL after MMC also causes this behavior. Instead of figuring out what can and can't be called after MMC to keep cmd.exe free, I'll just rewrite the script to call MMC with START on the last line. I had it earlier in the script (with an instance param) to get a head start on loading MC.
