### ISSUE TITLE
Modded Profile not launching

### ISSUE THREAD

**Issue by Isucc1** [MultiMC/MultiMC5#3123]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 10 64-bit

Summary of the issue or suggestion: I got a profile, it has mods, and it won't launch
----------------------------------------------

What should happen: Profile Launches
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download the mods I got

2. Load into 1.12.2 newest forge

3. Watch as it doesn't work

Suspected cause: Cubic Chunks mod
---------------------------

Logs/Screenshots:
----------------------------
https://paste.ee/p/mdHGC

Additional Info: I don't exactly know if this is the right place to ask for help but if it is, and I do get help... thanks
---------------------------

**Comment by Janrupf** [comment]
You are correct with your suspected cause, indeed it is cubic chunks, but I'm not sure why. Might be a compatibility issue, but it looks really weird. It might be the best to contact the author (Barteks), if you join the CubicChunks or MultiMC discord, you will find him there. But first try to update the Mod if it is not the latest version already.

See [CubicChunks discord(https://discord.gg/kMfWg9m)] or [MultiMC discord](https://discordapp.com/invite/0k2zsXGNHs0fE4Wm).

**Comment by Forkk** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's discord, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
