### ISSUE TITLE
Worlds Missing in Vanilla Snapshot Version 20w14infinite

### ISSUE THREAD

**Issue by aeroeng15** [MultiMC/MultiMC5#3124]
System Information
-----------------------------
MultiMC version: 0.6.12-develop-1438

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
When looking at the "Worlds" view of the 20w14infinite snapshot, it is empty despite having at least one world. Looking at other 20wXX snapshots, there is not a similar issue.

What should happen:
------------------------------
When looking at "Worlds" of the snapshot, created worlds show up.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add Vanilla instance of the snapshot version

2. Boot up instance and create world

3. Exit MC instance

4. Open up "Worlds" tab of instance, see that it is blank

Suspected cause:
---------------------------
Possible change in folder structure?

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by aeroeng15** [comment]
I seem to have not tested as thoroughly as I should have; it appears to only be an issue with 20w14infinite.

**Comment by Zetabite** [comment]
Worlds are not shared throught instances. Please make sure the world exists inside the instance folder. If you want to make an instance with the same world, clone the instance with world and change the clones version to the one you want

**Comment by aeroeng15** [comment]
I understand worlds are not shared. I am attempting to move worlds from one instance to another (via drag-and-drop) rather than going to the filesystem.

Looking into it a bit more this morning, it appears that 20w14infinite uses "special_level.dat" in place of "level.dat", which is probably breaking things.

**Comment by Janrupf** [comment]
They probably did that in order to not break other installations. This is not a MultiMC bug.

**Comment by aeroeng15** [comment]
Looking at and interacting with Worlds (or saves) via dialogs _is_ a MultiMC feature that does not work if "level.dat" does not exist. 20w14infinte shows that this filename can be changed at will.

**Comment by Zetabite** [comment]
It can be changed, but its not mmc fault, if mojang decides to change the .dat name

**Comment by CDAGaming** [comment]
This was actually an intended feature on Mojang's end and this issue can be closed as intentional.

![image](https://user-images.githubusercontent.com/16328918/80871117-6b247a80-8c70-11ea-8864-4cf4aa519bcb.png)

Reference: https://bugs.mojang.com/browse/MC-177051

**Comment by JCode-JCode** [comment]
Regardless, this version is one of the best.
