### ISSUE TITLE
Whenever I try to connect to a server, it kicks me about a minute later with the message "an existing connection was forcibly closed by the remote host"

### ISSUE THREAD

**Issue by ProfessorGlaceon** [MultiMC/MultiMC5#3129]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: win 32

Summary of the issue or suggestion:
----------------------------------------------
Essentially what the title says. Whenever I try to connect to this modded server, everything freezes and I disconnect about a minute later with the message "an existing connection was forcibly closed by the remote host". I don't have this problem when I try the vanilla minecraft launcher, but since I don't know how to install mods on that, and don't really want to either, I'm stuck with multiMC. I've noticed that the "session" box has been marked with a red X on every instance of minecraft I make. if that's the issue, how do I fix it?

What should happen:
------------------------------
I should connect to the server and be able to do stuff without a hitch, like I am able to in single player or the normal launcher.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------
whatever is causing the "sessions" box to be marked with a red X

**Comment by phit** [comment]
Your PC is too slow, so the server kicks you eventually when your client fails to respond. Make sure you assigned enough memory, and you can ask the server you are joining to raise the login timeout.
Other than that find a lighter modpack your PC is capable of running at a decent enough speed, so it doesn't freeze for 60 seconds when joining a server.

The session box is completely cosmetic and has been wrong as Mojang Status is broken https://status.mojang.com/check

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
