### ISSUE TITLE
Failed to upload skin (works on one account, not other)

### ISSUE THREAD

**Issue by RedFern104** [MultiMC/MultiMC5#3130]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: Windows 10

Summary of the issue or suggestion: 
----------------------------------------------
When I upload a skin on my new Minecraft account (purchased it April 2020), it works perfectly. However, when I try the same thing on my old Minecraft account (purchased around 2010/2011), I get the error "Failed to upload skin!"
The old Minecraft account has not been migrated into a Mojang account. I can't log in to the account on minecraft.net because I don't know the answers to the security questions and I don't have access to the email account.

What should happen:
------------------------------
The skin should upload successfully with the old account.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Go to Manage Accounts.

2. Click on the desired account (non-migrated?).

3. Click Upload Skin.

4. Select a skin file.

5. Hit Okay.

Suspected cause:
---------------------------
I'm not sure if I'm getting the error because it's a non-migrated Minecraft account, but that's the only difference I see between the old and new accounts.

Logs/Screenshots:
----------------------------
![Untitled](https://user-images.githubusercontent.com/64855439/81089068-7d492780-8ec1-11ea-8381-48ca03963e1b.png)

Additional Info:
---------------------------

**Comment by sambhavsaggi** [comment]
Are you able to upload skins via the official Minecraft website?

**Comment by kb-1000** [comment]
It simply depends on whether Mojang wants further verification for the request (I think it was a captcha or the security questions or something). Then, this error happens, and you HAVE TO go to the website... and if you have no access to the account, then that's not a MultiMC issue.

**Comment by sambhavsaggi** [comment]
@kb-1000 My apologies! I read your question too fast. It does not appear to be a MultiMC issue as I was able to upload a skin just fine. If you are locked out of your account, then I cannot help you :)

**Comment by kb-1000** [comment]
It is NOT my question.

**Comment by sambhavsaggi** [comment]
@kb-1000 Do you have any logs you can upload?

**Comment by kb-1000** [comment]
I don't have this issue. For me, the skin upload works just fine. So, no.

**Comment by sambhavsaggi** [comment]
@kb-1000 I'm sorry. I went through a mental dissonance there for a few minutes: I mixed up your and RedFern104's usernames in my head. @RedFern104 if you are reading this, please upload some logs of the issue.

**Comment by RedFern104** [comment]
Hi, thank you for your help. I actually was able to access the account from the original computer and change the skin that way, so I guess I don't technically need help anymore; however, I left this issue open so that if someone found a solution, it might help someone else who had the same problem.
@sambhavsaggi I actually have no idea how to find the logs. Is there a keyboard command or something?

**Comment by kb-1000** [comment]
You don't need to upload logs. The issue and its reason are known. A possible solution could be implementing a way to enter the solution in the UI when Mojang wants extra verification.

**Comment by UltraBlackLinux** [comment]
So If MMC fails do Upload a skin cause of security questions, then you have to log in to minecraft.net with the security questions, then they got ur ip (if it even goes via that, cause it changes with almost every reboot), and it will be set as trusted and u can upload skins later w/o problems via MMC

**Comment by kb-1000** [comment]
It doesn't change with a reboot of your PC, it changes with a reboot of your router.
It also most likely changes every day when the router reconnects

**Comment by UltraBlackLinux** [comment]
It changes no matter what. That doesnt require a Router restart.

> It also most likely changes every day when the router reconnects
Propably

**Comment by sambhavsaggi** [comment]
You get a new IP when the DHCP lease expires or is renewed. Usually the time for it to expire is pretty high on the WAN side (weeks or months) but when your router reboots it needs a new IP.

When you sign in to Minecraft, their website has many mechanisms for verifying the users: cookies, passwords, security questions, IP address. A combination of these decide whether or not they ask for the security questions again. Once they verify your computer, everything is going to be allowed (with just a password) for some time until your Minecraft session expires and they ask for login or security questions again to change skin.

I think.

**Comment by peterix** [comment]
This should now be fixed.

**Comment by TatiestEwe2200** [comment]
it doesent

**Comment by TatiestEwe2200** [comment]
i tried to upload this skin
![dev0](https://user-images.githubusercontent.com/88336781/197392306-39f135b0-0913-423d-81ec-5a43f07ae024.png)

**Comment by GTHB-plyr7510** [comment]
This same issue happens to me, but I don't have a Mojang account, instead I have an Ely.by account. Can anybody help me out with this issue?
