### ISSUE TITLE
Running MMC in returns an "undefined symbol" error

### ISSUE THREAD

**Issue by ClapClop** [MultiMC/MultiMC5#3132]
System Information
-----------------------------
MultiMC version: 1.4-1

Operating System: Ubuntu 14.04lts

Summary of the issue or suggestion: 
----------------------------------------------
 When I run MultiMC it returns : `undefined symbol: _ZN7QString13toUtf8_helperERKS_`.

What should happen:
------------------------------
Open as normal.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install Ubuntu 14.04lts.

2. Install MultiMC `.deb` binary.

3. Run it using gdebi or dpkg.

4. Run MultiMC

Suspected cause:
---------------------------
A missing compiler flag `-DQT_COMPILING_QSTRING_COMPAT_CPP`.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

MultiMC doesn't even open so i cannot get the log.

Additional Info:
---------------------------
I found the compiler flag [here](https://stackoverflow.com/questions/27714446/undefined-symbol-zn7qstring13toutf8-helpererks-at-runtime)
The first time running MultiMC created a small window that i didn't pay to much atention

**Comment by Zetabite** [comment]
Have you installed Qt as described on the page?

**Comment by ClapClop** [comment]
Yes and i even tryed using `sudo apt-get install --reinstall qt5-default` and still give me the same error

**Comment by Zetabite** [comment]
Could be that you need to install cmake, not sure.

Btw, you should update your distro if possible, this LTS version is only supported security wise now, general support has ended. This

**Comment by Zetabite** [comment]
Also, you could try installing it via generic install

**Comment by ClapClop** [comment]
> Could be that you need to install cmake, not sure.

It was installed already, tried cmake3 but didin't work
> Btw, you should update your distro if possible, ...

I have some problems with the repositories but i can try something i think

> Also, you could try installing it via generic install

Sorry but i dont know

**Comment by Zetabite** [comment]
You download the generic mmc linux install, extract the archive and just start the multicmc executable in MultiMC directory

**Comment by ClapClop** [comment]
Oh I already tried that gives and the same error

**Comment by ClapClop** [comment]
> I have some problems with the repositories but i can try something i think
It didn't work but surelly its the reason im just gonna close this and use original launcher
but thanks

**Comment by peterix** [comment]
The oldest supported version on both sides is 16.04.
