### ISSUE TITLE
Identical launch conditions failing on one PC and working on another?

### ISSUE THREAD

**Issue by RainXS** [MultiMC/MultiMC5#3133]
Specs are slightly different, but when I try to launch Minecraft with a modpack on my second computer it crashes. I'm almost certain Java is the exact same version, both allowed the same amount of RAM and permgen. Seems like a Java issue though? The crash log is uploaded below.

https://paste.ee/p/L3hTb

**Comment by WhyDoWeWonder** [comment]
This is probably happening because your running the OpenJ9, forge does a lot of hacky stuff that usually only works on Hotspot. Did you download or build OpenJDK with OpenJ9 as the JVM? If so either get the Oracle JRE and/or JDK or OpenJDK with Hotspot as the VM.

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
