### ISSUE TITLE
MacOS Infinite Bouncing App Launch Bug

### ISSUE THREAD

**Issue by norahqueen** [MultiMC/MultiMC5#3134]
System Information
-----------------------------
MultiMC version: 0.6.11 (1370)

Operating System: MacOS Catalina (10.15.4)

Summary of the issue or suggestion: When trying to launch MultiMC, the app icon will bounce indefinitely and never actually launch.
----------------------------------------------

What should happen:
------------------------------
The app launches as normal.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. I'm unsure what causes the bug. If I play regularly, it doesn't seem to occur. If I don't play MC for a few days and come back to it, that's when it does occur.

2. To fix the issue, I've found that launching the application using the 'open' terminal command forces it to launch, though after a short period of the app doing the bounce. After doing this, closing and relaunching the app normally does work for a period of time.

3. This only started occurring in the last 30 days or so.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by sambhavsaggi** [comment]
Could you upload some debug information? Here is how:

1. Open the Terminal
1. Type in the following: `/Applications/MultiMC.app/Contents/MacOS/MultiMC`
1. Copy and paste the output from that into your question

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
