### ISSUE TITLE
MultiMC5\libraries\pack200\src\zip.cpp:347: error: use of undeclared identifier 'gmtime_r'

### ISSUE THREAD

**Issue by graytoowolf** [MultiMC/MultiMC5#3135]
Compilation environment windows 10 QT5.14 prompt error: use of undeclared identifier 'gmtime_r'

**Comment by peterix** [comment]
Sounds like you are using an unsupported version of Qt, and an unsupported compiler.

**Comment by graytoowolf** [comment]
> 听起来您正在使用不受支持的Qt版本和不受支持的编译器。

Could you please recommend the Qt version?
