### ISSUE TITLE
Pack crashes on Mac OS X

### ISSUE THREAD

**Issue by sidnoway** [MultiMC/MultiMC5#3136]
System Information
-----------------------------
MultiMC version: 0.6.11-1370

Operating System: Mac OS X 10.15.4

Summary of the issue or suggestion: Modpack crashes on Mac OS X, when it would run fine on Windows or Linux
----------------------------------------------

What should happen: The pack would run
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install Pack (https://mega.nz/file/MdQFlQzQ#XkBy-pxajwh1dqTrIMNvrhBp1OnYSpcNp_sZ3P6fS0E)

2. Run pack

3. Crash

Suspected cause: Catalina at it again?
---------------------------

Logs/Screenshots: https://paste.ee/p/HAhUO
----------------------------

Additional Info: My Mac is very old. (Mid-2012 MBP Non-Retina)
---------------------------

**Comment by kb-1000** [comment]
not a multimc issue

**Comment by Janrupf** [comment]
Might be an OptiFine issue.

**Comment by sidnoway** [comment]
It was because I was using OpenJDK, I switched to Oracle JRE, and it works fine.
