### ISSUE TITLE
Instance crashes with specific logo

### ISSUE THREAD

**Issue by CommandMC** [MultiMC/MultiMC5#3137]
System Information
-----------------------------
MultiMC version: 0.6.11-custom

Operating System: Manjaro Linux

Summary of the issue ~~or suggestion~~:
----------------------------------------------
When setting a specific image as the logo for an instance, upon clicking "Edit Instance" or similar, MultiMC crashes. Clicking "Minecraft Folder" still works fine and opens. Selecting another icon makes everything work again.

What should happen:
------------------------------
Well, it shouldn't crash

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a new instance

2. Copy the linked image and export it using GIMP (or download my exported one) 

3. Import the image into MultiMC and set it as the instance icon

3. Try to launch the instance, edit instance or similar

Suspected cause:
---------------------------
Well something is up with that image, as it's not happening with any other image. My best guess is that GIMP does *something* to exported images that MultiMC doesn't like.

Logs/Screenshots:
----------------------------
Log of MultiMC: https://paste.ee/p/OEiOw
The picture: https://vignette.wikia.nocookie.net/minecraft/images/f/fd/VillageAndPillageLogo.png/revision/latest/scale-to-width-down/1000?cb=20191219014954
A video of me demonstrating the crash: https://www.youtube.com/watch?v=Dt2aE7SqvNM

Additional Info:
---------------------------
As you can see, the original image is a .webp file. Because of that, I copied it ("Copy Image" in FF) and pasted it into GIMP, from where I exported it as a .PNG.
Download link for my exported image: https://imgur.com/a/ubDbaRU

**Comment by phit** [comment]
Duplicate of https://github.com/MultiMC/MultiMC5/issues/2811

**Comment by CommandMC** [comment]
Oops, sorry!
I'll go ahead and close this then
