### ISSUE TITLE
Instance Failing to Load

### ISSUE THREAD

**Issue by Arasarhood** [MultiMC/MultiMC5#3138]
System Information
-----------------------------
MultiMC version: MultiMC5 Version 0.6.11 - 1430 on win32

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Instance crashed at launch.  Error log below. 

What should happen:
------------------------------
Minecraft instance loads.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create new 1.12.2 instance

2. Load mods below.

3. Click launch button.

Suspected cause:
---------------------------
Wrong jar file somewhere?

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
https://paste.ee/p/tHFSG
MultiMC version: 0.6.11-1430

Minecraft folder is:
C:/Users/Rob Whitaker/Documents/MultiMC/instances/New Advent/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_221, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/Rob Whitaker/Documents/MultiMC/instances/New Advent/natives

Libraries:
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2768/forge-1.12.2-14.23.5.2768-universal.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/Rob Whitaker/Documents/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [✔️] animania-1.12.2-1.4.8
  [✔️] AppleCore-mc1.12.2-3.2.0
  [✔️] armoryexpansion-1.1.10
  [✔️] base-1.12.2-3.12.0
  [✔️] Baubles-1.12-1.5.2
  [✔️] BedrockBGone-1.12.2-5.0-b8
  [✔️] BetterBuildersWands-1.12-0.11.1.245+69d0d70
  [✔️] BetterCombat-1.12.2-1.5.6
  [✔️] BetterFoliage-MC1.12-2.2.0
  [✔️] BiblioCraft[v2.4.5][MC1.12.2]
  [✔️] bibliotheca-1.3.6-1.12.2
  [✔️] BiomesOPlenty-1.12.2-7.0.1.2422-universal
  [✔️] BloodMagic-1.12.2-2.3.3-101
  [✔️] Botania+r1.10-361
  [✔️] ccm-1.0
  [✔️] ceanimals-1.12.2-1.4.1
  [✔️] CodeChickenLib-1.12.2-3.2.2.353-universal
  [✔️] conarm-1.12.2-1.2.3
  [✔️] ContentTweaker-1.12.2-4.9.1
  [✔️] CookingForBlockheads_1.12.2-6.4.70
  [✔️] CraftStudio-1.0.0.93-mc1.12-alpha
  [✔️] CraftTweaker2-1.12-4.1.17
  [✔️] crafttweakerutils-0.4
  [✔️] creeperconfetti-1.4.2
  [✔️] CustomStartingGear-1.12-1.2.0.9-universal
  [✔️] DrZharks MoCreatures Mod-12.0.4
  [✔️] DynamicTrees-1.12.2-0.9.4
  [✔️] DynamicTreesBOP-1.12.2-1.4.1e
  [✔️] EnderStorage-1.12.2-2.4.5.135-universal
  [✔️] EngineersWorkshop-1.4.0-1.12.2
  [✔️] Exotic+Birds+1.12.2-1.4.1
  [✔️] FastLeafDecay-v14
  [✔️] Forgelin-1.8.2
  [✔️] ForgeMultipart-1.12.2-2.6.1.81-universal
  [✔️] Guide-API-1.12-2.1.8-63
  [✔️] hopperducts-mc1.12-1.5
  [✔️] HungerOverhaul-1.12.2-1.3.3.jenkins148
  [✔️] iceandfire-1.7.1-1.12.2
  [✔️] iChunUtil-1.12.2-7.1.4
  [✔️] InventoryTweaks-1.63
  [✔️] IronBackpacks-1.12.2-3.0.8-12
  [✔️] ironchest-1.12.2-7.0.59.842
  [✔️] IvToolkit-1.3.3-1.12
  [✔️] journeymap-1.12.2-5.5.2
  [✔️] LibEx-1.12.2-1.0.8
  [✔️] llibrary-1.7.15-1.12.2
  [✔️] LLOverlayReloaded-1.1.6-mc1.12.2
  [✔️] Mantle-1.12-1.3.3.49
  [✔️] MineTweakerRecipeMaker-1.12.2-1.2.2.30
  [✔️] natura-1.12.2-4.3.2.66
  [✔️] Neat+1.4-17
  [✔️] NetherEx-1.12.2-2.0.8
  [✔️] NetherPortalFix_1.12.1-5.3.17
  [✔️] OpenBlocks-1.12.2-1.8
  [✔️] OpenModsLib-1.12.2-0.12.1
  [✔️] OreExcavation-1.4.137
  [✔️] Pam's+HarvestCraft+1.12.2zb
  [✔️] Patchouli-1.0-18
  [✔️] plustic-7.0.5.2
  [✔️] PortalGun-1.12.2-7.0.2
  [✔️] RecurrentComplex-1.4.7
  [✔️] redstonepaste-mc1.12-1.7.5
  [✔️] reptilemod-1.12.2-3.8.4-86
  [✔️] SpawnCommands-2.7.0-mc1.12to1.12.2-forge
  [✔️] taiga-1.12.2-1.3.4
  [✔️] TConstruct-1.12.2-2.12.0.135
  [✔️] Thaumcraft-1.12.2-6.1.BETA26
  [✔️] ThaumicInventoryScanning_1.12.2-2.0.10
  [✔️] TinkersComplement-1.12.2-0.3.2
  [✔️] TinkerToolLeveling-1.12.2-1.1.0
  [✔️] TombManyGraves-1.12-4.2.0
  [✔️] Translocators-1.12.2-2.5.1.77-universal
  [✔️] twilightforest-1.12.2-3.8.689-universal
  [✔️] ultimate_unicorn_mod-1.12.2-1.5.16
  [✔️] Waddles-1.12.2-0.6.0
  [✔️] Waystones_1.12.2-4.0.43

Params:
  --username  --version MultiMC5 --gameDir C:/Users/Rob Whitaker/Documents/MultiMC/instances/New Advent/.minecraft --assetsDir C:/Users/Rob Whitaker/Documents/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2048m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 6928

Using onesix launcher.

[10:29:22] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[10:29:22] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraftforge.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_221]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Process exited with code 1.
MultiMC: Log upload triggered at: 09 May 2020 10:30:12 -0500
MultiMC: Log uploaded to: https://paste.ee/p/tHFSG
Clipboard copy at: 09 May 2020 10:36:31 -0500

**Comment by Zetabite** [comment]
If you havent installed Forge to this instance do it now. If it isnt possible, switch to the dev branch and try to install forge with it

**Comment by Arasarhood** [comment]
MultiMC says Forge 14.23.5.2768 is installed.  Do you think I should remove and re-install?

Also, I now see how the log link should have worked, my apologies.

**Comment by Zetabite** [comment]
RecurrentComplex try installing the pre java 10 version

**Comment by Zetabite** [comment]
Try a newer version of forge

**Comment by Arasarhood** [comment]
Forge version 14.23.5.2846 gives this error: https://paste.ee/p/heBMQ

Forge version 14.23.5.2769 gives this error: https://paste.ee/p/qee5M

Forge version 14.23.5.2770 gives this error: https://paste.ee/p/d5LPH

What's weirder is this same modpack/forge version is running on 2 other computers here.

**Comment by Arasarhood** [comment]
The DEV branch appears to be working.  No idea why, but thanks.
