### ISSUE TITLE
how to install WWE client on multimc?

### ISSUE THREAD

**Issue by woochan456** [MultiMC/MultiMC5#3139]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by QuImUfu** [comment]
download the manual install, open the zip, in there the mods folder and copy the wwe mod into the mod folder of instance you installed fabric on.

**Comment by sambhavsaggi** [comment]
WWE Client (at least version 1.15.2) does not use Forge, but Fabric. Here is how to use Fabric:
1. Download the WWE zip file from [here](https://wweclient.com/NewAdDownload.php?MinecraftVersion=1.15.2%20fabric)
1. Unzip the folder, move the `.jar` file somewhere you can find it.
1. Follow this video (mine): [Imgur Link](https://imgur.com/a/yEgNjOT)

**Comment by UltraBlackLinux** [comment]
Some other Clients require to get installed via Jar Mod In the versions tab.

**Comment by sambhavsaggi** [comment]
In this case, it needed fabric to be installed, and the jar should be in the “loader mod” section

**Comment by Forkk** [comment]
This is a forum for reporting bugs, not asking for help. If you want help with things like this try asking in the mod's discord, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by TehcJS** [comment]
stop

**Comment by TehcJS** [comment]
piracy abd

**Comment by Forkk** [comment]
This is not the place for this nonsense @TehcJS
