### ISSUE TITLE
1.8.9 window is blurry

### ISSUE THREAD

**Issue by MelonSkuppy** [MultiMC/MultiMC5#3140]
System Information
-----------------------------
MultiMC version: 0.6.7

Operating System: Windows 10 (64-bit)

Summary of the issue or suggestion:
----------------------------------------------
Minecraft 1.8.9 (with and without forge)’s window is blurry. I tested out several versions and it only happens in 1.8.9 (It looks normal when I launch it in the default launcher)

What should happen:
-----------------------------
The window shouldn’t be blurry

Steps to reproduce the issue (Add more if needed)
-------------------------------------------------------------
1. Open MultiMC

2. Create a new instance

3. Set the instance version to 1.8.9

4. Launch

Suspected cause:
---------------------------
It’s probably a setting in MultiMC causing it

Logs/Screenshots:
----------------------------
https://imgur.com/a/SnHD3Yl
Logs: https://pastebin.com/BrCaGjdF

Additional Info:
---------------------------
I tried the dev build but nothing changed

**Comment by josh-65** [comment]
try updating multimc to 6.11

**Comment by MelonSkuppy** [comment]
> Try updating multimc to 0.6.11. Also if you have a nvidia GPU some 3D settings can cause blurry windows you will have to look up what ones as i don't remember.

**Comment by MelonSkuppy** [comment]
accidentally closed, but i will try what you said.

**Comment by MelonSkuppy** [comment]
*can I stop accidentally pressing close and comment*

**Comment by MelonSkuppy** [comment]
> Try updating multimc to 0.6.11. Also if you have a nvidia GPU some 3D settings can cause blurry windows you will have to look up what ones as i don't remember.

Updating didn’t work but idk about the 3D thing

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
