### ISSUE TITLE
Keep seeing exitcode 255 error when loading instance with modpack

### ISSUE THREAD

**Issue by justtryingtoplaythecraft** [MultiMC/MultiMC5#3141]
System Information
-----------------------------
MultiMC version: 0.6.11-1370

Operating System:MacOS

Summary of the issue or suggestion:
----------------------------------------------
keep getting the exit code 225 whenever i try and run the Rougelike Adventures and Dungeons in multimc

What should happen: 
------------------------------
i should be able to play modded minecraft

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Downloaded Multimc and properly installed it

2.downloaded zip file from cursedforage and moved it to my desktop

3.created new instance and imported zip from desktop

4. created another instance and ran vanilla  12.2

5.tried to run modpack on the first instance and error code apeared

Suspected cause: 
---------------------------
no idea (im not good with computers)

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
MultiMC version: 0.6.11-1370

Minecraft folder is:
/Applications/MultiMC.app/Contents/MacOS/instances/HERRO ITS RLD/minecraft

Java path is:
/usr/bin/java

Java is version 14.0.1, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /Applications/MultiMC.app/Contents/MacOS/instances/HERRO ITS RLD/natives

Libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2838/forge-1.12.2-14.23.5.2838-universal.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-osx.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar

Mods:
  [✔️] aether_continuation-1.12.2-v1.2.3
  [✔️] aether_legacy-1.12.2-v1.4.4
  [✔️] AIImprovements-1.12-0.0.1b3
  [✔️] AkashicTome-1.2-12
  [✔️] AppleCore-mc1.12.2-3.2.0
  [✔️] AppleSkin-mc1.12-1.0.9
  [✔️] Aquaculture-1.12.2-1.6.8
  [✔️] Aroma1997Core-1.12.2-2.0.0.2
  [✔️] Aroma1997s-Dimensional-World-1.12.2-2.0.0.2
  [✔️] Atum-1.12.2-2.0.17
  [✔️] AutoRegLib-1.3-32
  [✔️] Baubles-1.12-1.5.2
  [✔️] BetterAdvancements-1.12.2-0.1.0.77
  [✔️] BetterDiving-1.12.2-1.5.1
  [✔️] BetterFps-1.4.8
  [✔️] BiblioCraft[v2.4.5][MC1.12.2]
  [✔️] biggerpacketsplz-since1.8-1.2
  [✔️] Biome_Bundle-1.12.2-v6.1
  [✔️] Bloodmoon-MC1.12.2-1.5.3
  [✔️] bonsaitrees-1.1.4-b170
  [✔️] Bountiful-2.2.1
  [✔️] BuildingGadgets-2.8.3
  [✔️] Cavern_1.12.2-v2.2.0
  [✔️] Chameleon-1.12-4.1.3
  [✔️] ChanceCubes-1.12.2-5.0.2.345
  [✔️] Charm-1.12.2-1.3.7
  [✔️] ChestTransporter-1.12.2-2.8.8
  [✔️] ChickenChunks-1.12.2-2.4.2.74-universal
  [✔️] Chisel-MC1.12.2-1.0.2.45
  [✔️] Clumps-3.1.2
  [✔️] CodeChickenLib-1.12.2-3.2.3.358-universal
  [✔️] ColossalChests-1.12.2-1.7.3
  [✔️] comforts-1.12.2-1.4.1.3
  [✔️] Controlling-3.0.9
  [✔️] CookingForBlockheads_1.12.2-6.5.0
  [✔️] CosmeticArmorReworked-1.12.2-v5a
  [✔️] CraftTweaker2-1.12-4.1.20.562
  [✔️] creeperconfetti-1.4.2
  [✔️] crimsonrevelations-0.8
  [✔️] CTM-MC1.12.2-1.0.2.31
  [✔️] Cucumber-1.12.2-1.1.3
  [✔️] Customized-Dungeon-Loot-1.12 -(v.1.0.3)
  [✔️] CustomMainMenu-MC1.12.2-2.0.9.1
  [✔️] Cyclic-1.12.2-1.20.2
  [✔️] CyclopsCore-1.12.2-1.6.3
  [✔️] DefaultSettings-1.8.x-1.12.x-2.1.10
  [✔️] DimensionalDoors-3.0.9-287
  [✔️] DiscordSuite-2.2.4
  [✔️] disenchanter-[1.12]1.6
  [✔️] DoggyTalents-1.12.2-1.15.1.5
  [✔️] DoomlikeDungeons-1.13.2-MC1.12.2
  [✔️] DungeonTactics-1.12.2-0.16.6
  [✔️] DynamicSurroundings-1.12.2-3.6.0.2
  [✔️] Electroblob's Wizardry - 4.1.4 - MC 1.12.2
  [✔️] Embersified-1.12.2-1.0.3
  [✔️] EmbersRekindled-1.13-hotfix2
  [✔️] EnchantmentDescriptions-1.12.2-1.1.15
  [✔️] EngineersWorkshopReborn-1.12.2-1.0.9.40
  [✔️] extraalchemy-forge-1.12-build11-0.5.4
  [✔️] ExtraSpells-1.12.2-1.0.7
  [✔️] extrautils2-1.12-1.9.9
  [✔️] FastFurnace-1.12.2-1.3.1
  [✔️] FastWorkbench-1.12.2-1.7.3
  [✔️] foamfix-0.10.10-1.12.2
  [✔️] ForgeEndertech-1.12.2-4.5.2.0-build.0459
  [✔️] Forgelin-1.8.4
  [✔️] FTBBackups-1.1.0.1
  [✔️] FTBGuides-2.0.0.52
  [✔️] FTBLib-5.4.7.0
  [✔️] FTBMoney-1.1.0.42
  [✔️] FTBQuests-1.8.0.237
  [✔️] FTBUtilities-5.4.0.124
  [✔️] heroicarmory-1.2.0
  [✔️] hooked-1.0.3
  [✔️] Hwyla-1.8.26-B41_1.12.2
  [✔️] iceandfire-1.9.1-1.12.2
  [✔️] ImprovedBackpacks-1.12.2-1.5.0.0
  [✔️] InfernalMobs-1.12.2
  [✔️] inventorypets-1.12-2.0.4
  [✔️] InventoryTweaks-1.63
  [✔️] ItemFilters-1.0.3.12
  [✔️] ItemPhysic Lite 1.3.7 mc1.12.2
  [✔️] IvToolkit-1.3.3-1.12
  [✔️] Jack-O'-Launcher-1.12.2-1.7.0
  [✔️] jei_1.12.2-4.15.0.291
  [✔️] journeymap-1.12.2-5.7.1
  [✔️] JustEnoughIDs-1.0.3-48
  [✔️] letsencryptcraft-1.10.2-1.2.0
  [✔️] levelup2-1.2.4
  [✔️] librarianlib-1.12.2-4.20-release
  [✔️] LibraryEx-1.12.2-1.1.2
  [✔️] limelib-1.12.2-1.7.12
  [✔️] living_enchantment-3.2.1
  [✔️] llibrary-1.7.19-1.12.2
  [✔️] Login_Shield-1.12.2-3-g7c6e7ac
  [✔️] lost_aether-content-1.12.2-0.1.3
  [✔️] LunatriusCore-1.12.2-1.2.0.42-universal
  [✔️] megaloot-1.12.2-0.2.40
  [✔️] minerva-library-1.0.13
  [✔️] MouseTweaks-2.10-mc1.12.2
  [✔️] mowziesmobs-1.5.4
  [✔️] Mystical Mechanics-0.12
  [✔️] MysticalAgriculture-1.12.2-1.7.5
  [✔️] NaturesCompass-1.12.2-1.8.5
  [✔️] Neat 1.4-17
  [✔️] NetherEx-1.12.2-2.1.5
  [✔️] NetherPortalFix_1.12.1-5.3.17
  [✔️] NomadicTents-1.12.2-9.5.2
  [✔️] NoMoreRecipeConflict-0.13(1.12.2)
  [✔️] noRecipeBook_v1.2.2formc1.12.2
  [✔️] OpenBlocks-1.12.2-1.8.1
  [✔️] OpenModsLib-1.12.2-0.12.2
  [📁] OpenTerrainGenerator (folder)
  [✔️] OpenTerrainGenerator-1.12.2 - v6
  [✔️] ordinarycoins-1.12.2-1.5
  [✔️] OreExcavation-1.4.150
  [✔️] OreLib-1.12.2-3.6.0.1
  [✔️] Pam's HarvestCraft 1.12.2zg
  [✔️] Patchouli-1.0-20
  [✔️] phosphor-1.12.2-0.2.6+build50-universal
  [✔️] PiTweaks-1.12-1.1.1
  [✔️] placeableitems-3.3
  [✔️] Placebo-1.12.2-1.6.0
  [✔️] PortableCrafting-1.12.2-1.0.2
  [✔️] PotionCore-1.9_for_1.12.2
  [✔️] prefab-1.3.0.26
  [✔️] ProgressiveBosses-1.5.4-mc1.12.x
  [✔️] ProjectVibrantJourneys-1.12.2-1.6.4
  [✔️] PyramidPlunder-1.12.2-1.4
  [✔️] QualityTools-1.0.7_for_1.12.2
  [✔️] Quark-r1.6-179
  [✔️] QuarkOddities-1.12.2
  [✔️] randomloot 1.7.4
  [✔️] randompatches-1.12.2-1.21.0.3
  [✔️] RandomThings-MC1.12.2-4.2.7.4
  [✔️] randomtweaks-1.12.2-2.8.0.1
  [✔️] reauth-3.6.0
  [✔️] RebornCore-1.12.2-3.19.3.524-universal
  [✔️] RecurrentComplex-1.4.8.2
  [✔️] Reliquary-1.12.2-1.3.4.796
  [✔️] ResourceLoader-MC1.12.1-1.5.3
  [✔️] RoguelikeDungeons-1.12.2-1.8.0
  [✔️] ropebridge-1.12-2.0.7
  [✔️] roughTweaks0.2.4-1.12.2
  [✔️] rustic-1.1.3
  [✔️] ScalingHealth-1.12.2-1.3.42+147
  [✔️] signpost-1.12.2-1.08.3
  [✔️] SilentLib-1.12.2-3.0.14+168
  [✔️] SimpleStorageNetwork-1.12.2-1.7.10
  [✔️] Skewers-1.1
  [✔️] solcarrot-1.12.2-1.8.3
  [✔️] SoundFilters-0.12_for_1.12
  [✔️] spartanfire-0.08
  [✔️] SpartanShields-1.12.2-1.5.4
  [✔️] SpartanWeaponry-1.12.2-beta-1.3.8
  [✔️] SpawnTemple-v.2.1-mc1.12
  [✔️] Stackie-1.12.2-1.6.0.48-universal
  [✔️] stg-1.12.2-1.2.3
  [✔️] StorageDrawers-1.12.2-5.4.1
  [✔️] strawgolem-1.4.1
  [✔️] StuffASockInIt-1.12.2-1.1.30
  [✔️] SubSwitch1.1.0
  [✔️] terracartreloaded-1.12.2-1.2.3
  [✔️] Thaumcraft-1.12.2-6.1.BETA26
  [✔️] ThaumicAugmentation-1.12.2-1.1.17
  [✔️] ThaumicInventoryScanning_1.12.2-2.0.10
  [✔️] The Beneath-1.12.2-1.7.0
  [✔️] TheBetweenlands-3.5.10-universal
  [✔️] tombstone-3.7.3-1.12.2
  [✔️] tropicraft-MC1.12.2-7.1.9.115
  [✔️] twilightforest-1.12.2-3.10.1013-universal
  [✔️] Unique Enchantments V1.12.2-1.8
  [✔️] uniquecrops-1.12.2-0.2.1
  [✔️] VanillaFix-1.0.10-99
  [✔️] VanillaTweaks-1.12.2-1.5.6
  [✔️] ViesCraft-1.12.2-5.9.16
  [✔️] VTweaks-1.12.2-2.0.8
  [✔️] Waystones_1.12.2-4.1.0
  [✔️] xptome-1.12.2-v1.1.4

Params:
  --username  --version MultiMC5 --gameDir /Applications/MultiMC.app/Contents/MacOS/instances/HERRO ITS RLD/minecraft --assetsDir /Applications/MultiMC.app/Contents/MacOS/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: HERRO ITS RLD", -Xms1024m, -Xmx3072m, -Duser.language=en]

Minecraft process ID: 2536

Using onesix launcher.

Failed to start Minecraft:
Exiting with -1
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Process exited with code 255.

Additional Info: 
---------------------------
regular/vanilla versions of minecraft run perfect

**Comment by Zetabite** [comment]
Install Java8 https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java
And, if possible, pls use this to upload logs next time: https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by floki70** [comment]
I don't know if this is the same issue but I also get the same error code. I have tried it with Java 8 installed. I even did a clean install of my OS (Pop_Os 20.04). but I still get this error https://paste.ee/p/F2Xuy#s=0   
I can run vanilla MC just fine but when launching any mod pack i get this error. I don't know what to do any more. I'm using MultiMC because the FTB launcher just gave the error that my Game had crashed. and fora where saying to use MultiMC. but still no joy.
thanks for the help any way ;)

**Comment by Heufneutje** [comment]
Are you trying to launch it offline? Cause there don't appear to be any libraries. You need to launch the game in online mode at least once.

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
