### ISSUE TITLE
Crash on Startup referrring to TextToSpeech?

### ISSUE THREAD

**Issue by ArtOfCombat** [MultiMC/MultiMC5#3142]
System Information
-----------------------------
MultiMC version: 0.6.11-1430 on win32

Operating System: Windows 10, latest update

Summary of the issue or suggestion:
----------------------------------------------
The pack, MC Eternal, which ran fine last night, crashes before startup with an error.

What should happen:
------------------------------
It should just run.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
Not reproducable

Suspected cause:
---------------------------
Unknown

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
Couldn't extract native jar 'C:/Users/music/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar' to destination 'C:/Users/music/Desktop/MultiMC/instances/Eternal-1.3.5.3/natives'
Couldn't extract native jar 'C:/Users/music/Desktop/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar' to destination 'C:/Users/music/Desktop/MultiMC/instances/Eternal-1.3.5.3/natives'

I'd attach more but pastebin is down. This happened immediately after mod check.

Additional Info:
---------------------------

**Comment by ArtOfCombat** [comment]
Got through to Pastebin, so here's the full log: https://pastebin.com/MbMtnBf9 It's worth mentioning that it did NOT crash before this, I shut it down normally last night.

**Comment by phit** [comment]
try disabling your antivirus software temporarily

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
