### ISSUE TITLE
What do i do i am desperate for help

### ISSUE THREAD

**Issue by Zazi-creator** [MultiMC/MultiMC5#3143]
System Information
-----------------------------
MultiMC version:10.7+

Operating System:

Summary of the issue or suggestion:
----------------------------------------------
When i launch MultiMc launcher its just black screen if i click on the black screen i can hear the sounds of opening singelplayer but i don't see it when i try joining a world (by memory) my screen just starts blinking black white black white... that happens when i play alpha versions if i play the newer versions such as 1.15.2 it works normal. So basically i cannot play alpha versions with my friends because of this bug.

I hope you will replay soon!

I am playing on MacOS.

What should happen:
------------------------------
it should open the launcher properly and the screen shouldn't be black.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.i open the MultiMc launcher

2.the screen turns black

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------

[61082763058__465C059E-A6CA-437F-A1EF-8638ED83B508 2.mov.zip](https://github.com/MultiMC/MultiMC5/files/4606463/61082763058__465C059E-A6CA-437F-A1EF-8638ED83B508.2.mov.zip)

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
could you provide the log: https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by Zazi-creator** [comment]
So i cannot find this Minecraft Log above my launcher but i did go to minecraft logs on the bottom and i clicked launch and the screen was blank again when i checked what it said there were a lot of WARNINGS
![8A98D8A7-76CE-40E8-95DA-A259BBE4C50E](https://user-images.githubusercontent.com/61931908/81845583-0b23b300-9551-11ea-8e78-efa54ed3e094.jpeg)

**Comment by Zetabite** [comment]
we need that minecraft log in Other Logs

**Comment by Zazi-creator** [comment]
MultiMC version: 0.6.11-1370


Minecraft folder is:
/Applications/MultiMC.app/Contents/MacOS/instances/a1.2.6/.minecraft


Java path is:
/usr/bin/java


Java is version 13.0.2, using 64-bit architecture.


Main Class:
  

Native path:
  /Applications/MultiMC.app/Contents/MacOS/instances/a1.2.6/natives

Traits:
traits texturepacks
traits legacyLaunch

Libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/minecraft/a1.2.6/minecraft-a1.2.6-client.jar

Native libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-osx.jar

Params:
  

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: a1.2.6", -Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 71550


Using onesix launcher.

Launching with applet wrapper...
28
Setting user: hexa_PUP, token:<ACCESS TOKEN>:<PROFILE ID>
Failed to load options
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at gq.a(SourceFile:150)
	at gq.<init>(SourceFile:52)
	at net.minecraft.client.Minecraft.a(SourceFile:210)
	at net.minecraft.client.Minecraft.run(SourceFile:559)
	at java.base/java.lang.Thread.run(Thread.java:830)
org.lwjgl.LWJGLException: Native cursors not supported
	at org.lwjgl.input.Cursor.<init>(Cursor.java:88)
	at oi.<init>(SourceFile:32)
	at net.minecraft.client.Minecraft.a(SourceFile:220)
	at net.minecraft.client.Minecraft.run(SourceFile:559)
	at java.base/java.lang.Thread.run(Thread.java:830)
May 13, 2020 7:46:44 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.OSXEnvironmentPlugin
May 13, 2020 7:46:44 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to enumerate device: Device open failed: -536870174

May 13, 2020 7:46:44 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to enumerate device: Device open failed: -536870174

May 13, 2020 7:46:44 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to enumerate device: Device open failed: -536870174

May 13, 2020 7:46:44 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to enumerate device: Device open failed: -536870174

May 13, 2020 7:46:45 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to enumerate device: Device open failed: -536870174


Starting up SoundSystem...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
OpenAL initialized.

AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 0.




This is what it says when i launch it in minecraft log

**Comment by Zetabite** [comment]
Use Java 8 https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java then comeback if the error persists, also use pastebin or so to upload the log next time

**Comment by Zazi-creator** [comment]
i freaking love you tysm!!!!!!! it works thank you thank you thank you!
