### ISSUE TITLE
Request to let all log append to a single log file.

### ISSUE THREAD

**Issue by stevenleeS0ht** [MultiMC/MultiMC5#3144]
System Information
-----------------------------
MultiMC version: 0.6.11-1344

Operating System: Linux

Summary of the issue or suggestion:
----------------------------------------------

Every time, `MultiMC` launch, the a new log file will be created. There will be too many log file in the filesystem.

The users expect that only single log file will be created, and every time when `MultiMC` launches, it will append the log to this file.

**Comment by Heufneutje** [comment]
It will only keep 5 log files at most. I wouldn't call that many... 

Besides in many cases only the latest log file is relevant for the current problem. Especially with large modpacks these log files can get pretty cluttered. The last thing you need is even more clutter from a previous launch. Therefore I'd argue this is a horrible idea that will only make it harder for the people who try to help users.

**Comment by jikuja** [comment]
> Every time, MultiMC launch, the a new log file will be created. There will be too many log file in the filesystem.

How many is too many?

Are you talking Multimc logs only or also about MC logs?

**Comment by stevenleeS0ht** [comment]
@Heufneutje , OK, thanks, I didn't know it will keep at most 5 logs.
