### ISSUE TITLE
Since latest update, no audio. Pop OS 20.04

### ISSUE THREAD

**Issue by sudoWiz** [MultiMC/MultiMC5#3145]
System Information
-----------------------------
MultiMC version: 0.6.11-1344

Operating System: Pop!_OS 20.04

Summary of the issue or suggestion:
----------------------------------------------
Since the latest update, I am not getting any sound from my game at all. It is not even showing up in my PulseAudio volume controls, like other applications (Firefox, Spotify). I have updated, I have rebooted, no change.

What should happen:
------------------------------
Game should have audio.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Start MultiMC

2. Launch Modpack, wait for it to load

3. Game is running, but no sound.

Suspected cause:
---------------------------
Latest update. Everything worked before this.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/IneOu

Additional Info:
---------------------------

**Comment by QuImUfu** [comment]
Do button presses in the menu have sound? I see nothing in the logs that indicates problems.

**Comment by Zetabite** [comment]
@QuImUfu they are talking about ingame sounds, not MMC

**Comment by Zetabite** [comment]
@sudoWiz did you add any mods to the modpack?

**Comment by sudoWiz** [comment]
No, it’s stock Enigmatica 2

**Comment by Zetabite** [comment]
Try updating forge. After you installed the latest forge, launch the instance in online mode once, so it can download the new forge

**Comment by Zetabite** [comment]
this should even fix if sounds werent downloaded properly

**Comment by jikuja** [comment]
> Since the latest update

What did you update?

**Comment by sudoWiz** [comment]
How do I update just forge? I’ve only ever installed a mod pack all at once from the zip file

**Comment by sudoWiz** [comment]
Just MultiMC

**Comment by Zetabite** [comment]
https://cdn.discordapp.com/attachments/531598137790562305/575385471207866388/Install_Forge_in_MultiMC.gif instead of install, you click change version for forge and set it to newest

**Comment by sudoWiz** [comment]
I have now updated to the latest forge, but there is still no audio

**Comment by Zetabite** [comment]
I am pretty sure you checked, but please verify your volume isnt down ingame and you havent muted it anywhere in the system

**Comment by sudoWiz** [comment]
I have checked in-game, system volume is up (I watched a movie while testing and it was still muted) and I have checked my pulseaudio settings and minecraft never even shows up on the application list.

**Comment by Zetabite** [comment]
Hm, i can barely imagine it, but maybe a sound service isnt running, might be that minecraft doesnt directly run over pulseaudio for some reason and needs a bridge, alsa or so, which might be either disabled or not even installed due to some update

**Comment by QuImUfu** [comment]
I wanted to ask if in-game button presses make sounds, because contrary to other in-game sounds they are not influenced by e.g. sound-mufflers or most possible sound-bugs introduced by mods.

**Comment by Zetabite** [comment]
maybe the pack is broken, its possible

**Comment by sudoWiz** [comment]
I have friends successfully playing the pack, with sound. And in-game buttons do not make sound either, I have heard absolutely no audio from minecraft. I have also tried unplugging all audio devices from my PC except one, and trying my speakers and headphones one by one, just in case. No luck.

**Comment by sudoWiz** [comment]
Just tried vanilla minecraft, and also another launcher program, no sound from anything. I don't understand.

**Comment by Zetabite** [comment]
That honestly sounds like what i made assumptions of in https://github.com/MultiMC/MultiMC5/issues/3145#issuecomment-627642116
So maybe try installing some sound plugins and enable sound services

**Comment by QuImUfu** [comment]
does sound in vanilla 1.15.2 work? It uses a (slightly) different sound system.

**Comment by sudoWiz** [comment]
If it's what Zetabite suggested I don't know how to fix it. no, sound does not work in 1.15.2

**Comment by QuImUfu** [comment]
could you upload and link the contents of `/etc/openal/alsoft.conf` and, if existing `$HOME/.alsoftrc`?

**Comment by sudoWiz** [comment]
I got it.

I had to have PulseAudio Volume open at the same time as minecraft, and when I clicked buttons or made sound in-game it would briefly show up as an entry in PulseAudio Volume and then vanish. It was muted. I cannot explain why or how, as I only downloaded PulseAudio Volume to fix this issue, but I unmuted it, and now it's back.

**Comment by Zetabite** [comment]
i had similar weird issues to, pulseaudio can be weird. hope it works now. close the topic if its fixed

**Comment by sudoWiz** [comment]
Thanks very much for the help all!
