### ISSUE TITLE
Request to add Authlib 

### ISSUE THREAD

**Issue by UOYZAL** [MultiMC/MultiMC5#3148]
System Information
-----------------------------
MultiMC version:0.6.12-develop-1438

Operating System:Windows 10 Professional 1909

Summary of the issue or suggestion:
----------------------------------------------
In China,many people don't have a Minecraft Accont,so they use other way to login, it's called"Authlib",or "外置登陆" in Chinese. It's very usefu both in China and abroad, it support third-part to auth a game nickname like Mojang do,and then provide skins and game server auth info.but MultiMC does not support it. If it's possible,please  add a function to supports it.

Here are some popular Authlib API links:
https://github.com/yushijinhun/authlib-injector
https://blessing.netlify.app/en/

**Comment by kb-1000** [comment]
To be honest, this sounds like a request for converting MultiMC into a cracked launcher. And that won't happen.

**Comment by Heufneutje** [comment]
And even if legit Mojang account data is being used, that data should still not be sent anywhere but Mojang's offical auth servers.

**Comment by graytoowolf** [comment]
大兄弟 官方是不可能出这种功能的 .
你可以自己编译 修改掉Mojang 的验证服务地址.

**Comment by Zetabite** [comment]
Just be aware that nobody will support a version of MMC where the auth method has been tempered with

**Comment by kakolisgay** [comment]
Since MultiMC [may not support microsoft accounts](https://github.com/MultiMC/MultiMC5/issues/3392) going forward, supporting authlib should be reconsidered.

**Comment by Janrupf** [comment]
You might have gotten something wrong there... MultiMC will support microsoft accounts, it just requires an official solution from Microsoft

**Comment by kb-1000** [comment]
Also, that we have absolutely no plans for making MMC a cracked launcher has not (and will not) changed.

**Comment by kakolisgay** [comment]
> it just requires an official solution from Microsoft

I wouldn't hold my breath

> we have absolutely no plans for making MMC a cracked launcher has not (and will not be) changed.

I dont think supporting microsoft's very clearly anti-consumer move is a good idea. If Mojang thought this was for the better they wouldn't have tried to bribe their userbase

**Comment by peterix** [comment]
This issue and its discussion has no or negative value.
