### ISSUE TITLE
I dont know what happen, I only use one mod

### ISSUE THREAD

**Issue by Xiang990293** [MultiMC/MultiMC5#3150]
System Information
-----------------------------
MultiMC version: MultiMC5 0.6.12 develop-1438

Operating System: Windows 10

Summary of the issue or suggestion: game crash
----------------------------------------------

What should happen: game will open
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. I create a instance that the version is 1.12.2.

2. I put the mod "Up And Down And All Around" in the mod folder.

3. when I try to execute the instance, the game crash.

Suspected cause: nothing comes my mind.
---------------------------

Logs/Screenshots:
----------------------------
[//]: 
MultiMC version: 0.6.12-develop-1438

Minecraft folder is:
E:/APPDATA/MultiMC/instances/1.12.2模組測試無OF/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_51/bin/javaw.exe

Java 版本為 1.8.0_51，使用64位元架構.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  E:/APPDATA/MultiMC/instances/1.12.2模組測試無OF/natives

Libraries:
  E:/APPDATA/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  E:/APPDATA/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  E:/APPDATA/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  E:/APPDATA/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  E:/APPDATA/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  E:/APPDATA/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  E:/APPDATA/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  E:/APPDATA/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  E:/APPDATA/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  E:/APPDATA/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  E:/APPDATA/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  E:/APPDATA/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  E:/APPDATA/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  E:/APPDATA/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  E:/APPDATA/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  E:/APPDATA/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  E:/APPDATA/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  E:/APPDATA/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  E:/APPDATA/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  E:/APPDATA/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  E:/APPDATA/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  E:/APPDATA/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  E:/APPDATA/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  E:/APPDATA/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  E:/APPDATA/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar
  E:/APPDATA/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.11.2/log4j-core-2.11.2.jar
  E:/APPDATA/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  E:/APPDATA/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/1.4.1/ForgeWrapper-1.4.1.jar
  E:/APPDATA/MultiMC/libraries/net/minecraftforge/forge/1.15.2-31.1.0/forge-1.15.2-31.1.0-launcher.jar
  E:/APPDATA/MultiMC/libraries/org/ow2/asm/asm/7.2/asm-7.2.jar
  E:/APPDATA/MultiMC/libraries/org/ow2/asm/asm-commons/7.2/asm-commons-7.2.jar
  E:/APPDATA/MultiMC/libraries/org/ow2/asm/asm-tree/7.2/asm-tree-7.2.jar
  E:/APPDATA/MultiMC/libraries/cpw/mods/modlauncher/5.0.0-milestone.4/modlauncher-5.0.0-milestone.4.jar
  E:/APPDATA/MultiMC/libraries/cpw/mods/grossjava9hacks/1.1.0/grossjava9hacks-1.1.0.jar
  E:/APPDATA/MultiMC/libraries/net/minecraftforge/accesstransformers/2.0.0-milestone.1-shadowed/accesstransformers-2.0.0-milestone.1-shadowed.jar
  E:/APPDATA/MultiMC/libraries/net/minecraftforge/eventbus/2.0.0-milestone.1-service/eventbus-2.0.0-milestone.1-service.jar
  E:/APPDATA/MultiMC/libraries/net/minecraftforge/forgespi/2.0.0-milestone.1/forgespi-2.0.0-milestone.1.jar
  E:/APPDATA/MultiMC/libraries/net/minecraftforge/coremods/2.0.0-milestone.1/coremods-2.0.0-milestone.1.jar
  E:/APPDATA/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  E:/APPDATA/MultiMC/libraries/com/electronwill/night-config/core/3.6.2/core-3.6.2.jar
  E:/APPDATA/MultiMC/libraries/com/electronwill/night-config/toml/3.6.2/toml-3.6.2.jar
  E:/APPDATA/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  E:/APPDATA/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.0/maven-artifact-3.6.0.jar
  E:/APPDATA/MultiMC/libraries/net/jodah/typetools/0.6.1/typetools-0.6.1.jar
  E:/APPDATA/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  E:/APPDATA/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  E:/APPDATA/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  E:/APPDATA/MultiMC/libraries/com/mumfrey/liteloader/1.12.2-SNAPSHOT/liteloader-1.12.2-SNAPSHOT.jar
  E:/APPDATA/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  E:/APPDATA/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [✔️] UpAndDownAndAllAround-1.12.2-2.8.0

Params:
  --username  --version MultiMC5 --gameDir E:/APPDATA/MultiMC/instances/1.12.2模組測試無OF/.minecraft --assetsDir E:/APPDATA/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 31.1.0 --fml.mcVersion 1.15.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20200122.131323 --tweakClass com.mumfrey.liteloader.launch.LiteLoaderTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx7888m, -Duser.language=en]

Minecraft 處理序 ID: 2428

Using onesix launcher.

2020-05-15 22:12:30,227 main WARN Advanced terminal features are not available in this environment
[32m[22:12:30] [main/INFO] [LaunchWrapper/]: Loading tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[m[32m[22:12:30] [main/INFO] [LaunchWrapper/]: Using primary tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[m[32m[22:12:30] [main/INFO] [LaunchWrapper/]: Calling tweak class com.mumfrey.liteloader.launch.LiteLoaderTweaker
[m[32m[22:12:30] [main/INFO] [LiteLoader/]: Bootstrapping LiteLoader 1.12.2
[m[32m[22:12:30] [main/INFO] [LiteLoader/]: Registering API provider class com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient
[m[32m[22:12:30] [main/INFO] [LiteLoader/]: Spawning API provider class 'com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient' ...
[m[32m[22:12:30] [main/INFO] [LiteLoader/]: API provider class 'com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient' provides API 'liteloader'
[m[32m[22:12:30] [main/INFO] [LiteLoader/]: Initialising API 'liteloader' ...
[m[32m[22:12:30] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.7.5 Source=file:/E:/APPDATA/MultiMC/libraries/com/mumfrey/liteloader/1.12.2-SNAPSHOT/liteloader-1.12.2-SNAPSHOT.jar Service=LaunchWrapper Env=CLIENT
[m[32m[22:12:31] [main/INFO] [mixin/]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: LiteLoader begin PREINIT...
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Initialising Loader properties...
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Setting up logger...
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: LiteLoader 1.12.2 starting up...
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Active Pack: 1.12.2-SNAPSHOT-r4CC2BB0-b4-4
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Java reports OS="windows 8.1"
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Adding supported mod class prefix 'LiteMod'
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Enumerating class path...
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Class path separator=";"
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Class path entries=(
   classpathEntry=E:/APPDATA/MultiMC/jars/NewLaunch.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.11.2/log4j-core-2.11.2.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/1.4.1/ForgeWrapper-1.4.1.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/net/minecraftforge/forge/1.15.2-31.1.0/forge-1.15.2-31.1.0-launcher.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/org/ow2/asm/asm/7.2/asm-7.2.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/org/ow2/asm/asm-commons/7.2/asm-commons-7.2.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/org/ow2/asm/asm-tree/7.2/asm-tree-7.2.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/cpw/mods/modlauncher/5.0.0-milestone.4/modlauncher-5.0.0-milestone.4.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/cpw/mods/grossjava9hacks/1.1.0/grossjava9hacks-1.1.0.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/net/minecraftforge/accesstransformers/2.0.0-milestone.1-shadowed/accesstransformers-2.0.0-milestone.1-shadowed.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/net/minecraftforge/eventbus/2.0.0-milestone.1-service/eventbus-2.0.0-milestone.1-service.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/net/minecraftforge/forgespi/2.0.0-milestone.1/forgespi-2.0.0-milestone.1.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/net/minecraftforge/coremods/2.0.0-milestone.1/coremods-2.0.0-milestone.1.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/com/electronwill/night-config/core/3.6.2/core-3.6.2.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/com/electronwill/night-config/toml/3.6.2/toml-3.6.2.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.0/maven-artifact-3.6.0.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/net/jodah/typetools/0.6.1/typetools-0.6.1.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/com/mumfrey/liteloader/1.12.2-SNAPSHOT/liteloader-1.12.2-SNAPSHOT.jar
   classpathEntry=E:/APPDATA/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar
)
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Registering discovery module EnumeratorModuleClassPath: [<Java Class Path>]
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Registering discovery module EnumeratorModuleFolder: [E:\APPDATA\MultiMC\instances\1.12.2模組測試無OF\.minecraft\mods]
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Registering discovery module EnumeratorModuleFolder: [E:\APPDATA\MultiMC\instances\1.12.2模組測試無OF\.minecraft\mods\1.12.2]
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Registering enumerator plugin DefaultEnumeratorPlugin: [com.mumfrey.liteloader.core.api.DefaultEnumeratorPlugin@67f639d3]
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Discovering valid mod files in folder E:\APPDATA\MultiMC\instances\1.12.2模組測試無OF\.minecraft\mods
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Inspecting jar metadata in 'UpAndDownAndAllAround-1.12.2-2.8.0.jar'
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Ignoring E:\APPDATA\MultiMC\instances\1.12.2模組測試無OF\.minecraft\mods\UpAndDownAndAllAround-1.12.2-2.8.0.jar
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Discovering valid mod files in folder E:\APPDATA\MultiMC\instances\1.12.2模組測試無OF\.minecraft\mods\1.12.2
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Discovering tweaks on class path...
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Baking listener list for EnumerationObserver with 1 listeners
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Registering discovered mod files in folder E:\APPDATA\MultiMC\instances\1.12.2模組測試無OF\.minecraft\mods
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Registering discovered mod files in folder E:\APPDATA\MultiMC\instances\1.12.2模組測試無OF\.minecraft\mods\1.12.2
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Initialising LiteLoader Mixins
[m[32m[22:12:31] [main/INFO] [mixin/]: Compatibility level set to JAVA_8
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: LiteLoader PREINIT complete
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Injecting required class transformer 'com.mumfrey.liteloader.transformers.event.EventProxyTransformer'
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Injecting required class transformer 'com.mumfrey.liteloader.launch.LiteLoaderTransformer'
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Injecting required class transformer 'com.mumfrey.liteloader.client.transformers.CrashReportTransformer'
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Queuing required class transformer 'com.mumfrey.liteloader.transformers.event.EventTransformer'
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Queuing required class transformer 'com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer'
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Queuing required class transformer 'com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer'
[m[32m[22:12:31] [main/INFO] [LaunchWrapper/]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[m[32m[22:12:31] [main/INFO] [LaunchWrapper/]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[m[32m[22:12:31] [main/INFO] [LaunchWrapper/]: Loading tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker$PreInitTweaker
[m[32m[22:12:31] [main/INFO] [LaunchWrapper/]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[m[32m[22:12:31] [main/INFO] [LaunchWrapper/]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[m[32m[22:12:31] [main/INFO] [LaunchWrapper/]: Calling tweak class com.mumfrey.liteloader.launch.LiteLoaderTweaker$PreInitTweaker
[m[33m[22:12:31] [main/WARN] [LaunchWrapper/]: Tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker has already been visited -- skipping
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Injecting downstream transformers
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Injecting additional class transformer class 'com.mumfrey.liteloader.transformers.event.EventTransformer'
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Injecting additional class transformer class 'com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer'
[m[32m[22:12:31] [main/INFO] [LiteLoader/]: Injecting additional class transformer class 'com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer'
[m[32m[22:12:31] [main/INFO] [LaunchWrapper/]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[m[1;31m[22:12:32] [main/ERROR] [LaunchWrapper/]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?] {}
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
Caused by: java.lang.NoClassDefFoundError: org/lwjgl/LWJGLException
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?] {}
	... 14 more
Caused by: java.lang.ClassNotFoundException: org.lwjgl.LWJGLException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?] {}
	... 14 more

The program has exited, code: 1

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
Use only ascii letters in the path. Any other letters make the path not recognized by java

**Comment by Xiang990293** [comment]
I see

**Comment by Xiang990293** [comment]
the error has not been solved

**Comment by Zetabite** [comment]
log: https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by Xiang990293** [comment]
I think I found the problem, I forget to say that when I created the instance, I use the wrong version in 1.15, but I just change the Minecraft version to 1.12.2.

But, the problem hasn't been solved, although the game can be opened, it will be closed in the next moment.

**Comment by Xiang990293** [comment]
https://paste.ee/p/z6R8A

**Comment by Zetabite** [comment]
https://www.curseforge.com/minecraft/mc-mods/up-and-down-and-all-around/relations/dependencies

**Comment by Xiang990293** [comment]
I solved it! Just don't download the version 2.8.0, you must download the latest version 2.9.1.

**Comment by Forkk** [comment]
###
