### ISSUE TITLE
Can not install only Optifine

### ISSUE THREAD

**Issue by BBloom81** [MultiMC/MultiMC5#3151]
I didn't fill out the all the fields as this is a very well know issue, there is no friendly way to install just Optifine.  Sometimes I want to play on a non-fabric or forge server and then have to go back to the vanilla launcher.
It's been years from what I can see that you have not put any way to run optifine only, in fact, it appears you've made it harder.

**Comment by Zetabite** [comment]
nothing was made harder. If anything the mod creators made it harder. also fill out the fields if you want help. we cannot help you without you stating for which version you want to install it

**Comment by phit** [comment]
https://github.com/MultiMC/MultiMC5/issues/1540

**Comment by Zetabite** [comment]
What an ancient issue

**Comment by BBloom81** [comment]
> nothing was made harder. If anything the mod creators made it harder. also fill out the fields if you want help. we cannot help you without you stating for which version you want to install it

You misunderstand, and that's on me.  I'm not looking for help, I'm pointing out that this "uber launcher" doesn't support the most important mod to most players and there seems to no care to do so.
It's no skin off my teeth.  I blew a couple hours today when I had nothing else to do, setting up MultiMC for Fabric and Forge, and messing with Optifine only to find none of the methods out there work.  I found this to be insane.  Coupled with the fact the MultiMC devs can take the time to code a cat button, but ignore Optifine installation, says quite a bit.

Anyway, again, just pointing out the BS from this dev.  I have no intention of using MultiMC purely on the fact I can not have an instance for just Optifine.  Couple that with the way the devs have "supported" this app, and now rather than not use until they support it, I will just write them off, as they clearly never will support it.

On to the next launcher.  I'm sure there's much better and caring devs out there that I'd love to make a purchase from or donate to.

**Comment by BBloom81** [comment]
> #1540

2016 and no movement, proof the devs simply don't care and there's no reason any user should care about them or this program. 

I'm not into investing in an app that has poor support.  Poor support leads to worse support and eventually no support.

**Comment by kb-1000** [comment]
Complain to OptiFine if it doesn't like being launched as a tweaker. That is what that issue is about.

**Comment by Zetabite** [comment]
Optifine still works, you just may have to do some tweaks. This has nothing to do with MMC not supporting it (cause MMC supports optifine) its just the way Optifine works nowadays doesnt play well with the way MMC works.

**Comment by BBloom81** [comment]
> Optifine still works, you just may have to do some tweaks. This has nothing to do with MMC not supporting it (cause MMC supports optifine) its just the way Optifine works nowadays doesnt play well with the way MMC works.

Right, because the mod author needs to make sure his mod works with all launchers, not the launcher author.  Optifine installs super easy with vanilla, so seems to me they've done their job.  It's MMC that doesn't wanna add support to install easily.  Again, no skin off my teeth, I've moved on and am trying a different launcher right now.
Keep the comments/replies coming if you'd like, I won't be responding further.  Maybe your blind love for laziness will be rewarded in some BS internet way.  Best of luck to you on that bud.

**Comment by Zetabite** [comment]
Ight. Have a great life.

**Comment by UltraBlackLinux** [comment]
https://github.com/UltraBlackLinux/MultiMC-Patch-Gen
This propably solves your Problems.

**Comment by kb-1000** [comment]
In the description of that project you confuse MultiMC and the Minecraft client. Please correct that. And please make clear that _you_ are responsible for support with errors caused by it, not MultiMC.

**Comment by BBloom81** [comment]
> https://github.com/UltraBlackLinux/MultiMC-Patch-Gen
> This propably solves your Problems.

Thanks, but as I've said, I've moved on.  This client is trash and it really seems as the devs have straight given up.  There hasn't even been a "news" post since August last year, no updates, nothing.  It's a joke.

In testing something else the other day though, I found I can't even go through a Nether portal without the game crashing on my Fabric server using MultiMC with all the same config for the instance as the official launcher.  Copy/pasting the instance from MultiMC and using the data in other launchers did not produce the bug.

Again, crap software that's been left behind by crap devs.   I've moved on, so should everyone else.

**Comment by Zetabite** [comment]
The fact that you are considering MMC being the fault for Optifine not working clearly shows that you have no idea what you are talking about.

**Comment by kb-1000** [comment]
First this isn't a client, it's a launcher. Second, there HAVE been quite a few updates, they were just not put on the stable branch yet. Third, if you don't report bugs such as that nether portal one, you will never receice a fix, and actively contribute to "crap software" being "crap software". Don't blame that on the devs then, though.

**Comment by Zetabite** [comment]
Just because something doesnt work how you want it to work, doesnt make it crap software. Maybe start taking advices and follow steps to fix stuff. If you continue like this, nobody will consider you credible for any issue report.
