### ISSUE TITLE
Weird modpack loading crashes?

### ISSUE THREAD

**Issue by mouroz** [MultiMC/MultiMC5#3152]
**System Information**
Windows

**MultiMC version:**
MultiMC 5: downloaded it today from the official site

**Operating System:**
Windows 10

**Summary of the issue**
I was looking forward to playing new minecraft modpacks. I found this open source very light and free modpack instance creator. But sadly im having constant crashes since then. Couldn't play one single mod. I tried SkyFactory 4, Farming Valey but all of them keeps crashing. I looked a little onto this community, found out abbout the update channel needing to be set as development but still nothing.

**What should happen:**
The modpack was supposed to load

**Steps to reproduce the issue (Add more if needed):**
-------------------------------------------------------------
1. Download MultiMC 5

2. Indicate javaw.exe location to the app

3. Log in with email and password

4. Create an instance with a zip url

5. Open the modpack instance (download from: https://www.curseforge.com/minecraft/modpacks/farming-valley, https://www.curseforge.com/minecraft/modpacks/skyfactory-4 as a zip file)

6. (Seriously i have no ideia why it just crashes after the 3rd step)

**Suspected cause:**
---------------------------
I know its mandatory but i no idea. The log just points out multiple errors that ive never heard

**Logs/Screenshots:**
----------------------------
I cant get acess to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach the logs (you guys should also check that out its being redirected to Home). So ill send a drive share link with the logs as txt
[https://drive.google.com/open?id=10yzeICUH_KCmpCiW31WM-SKC385KC9-c](url)

**Additional Info:**
---------------------------
If the txt files there really cant help you guys please tell me what are the instructions for the log sharing or atleast a usable link that wont redirect me to the home page
I actually noticed that this wasnt just the modpack after the 1st try, so i dont currently have the Farming Valley crash log (i deleted the instance), but if needed i can send it as well

Please contact me with whatever info you can tell, either from above or from the crashes themselves

**Comment by peterix** [comment]
You have to give modded minecraft more memory. Big modpacks will never run with 1GB.

**Comment by peterix** [comment]
```
// My bad.

Time: 5/16/20 10:07 PM
Description: Initializing game

java.lang.OutOfMemoryError: Java heap space
	at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_147962_a(TextureAtlasSprite.java:364)
	at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_188539_a(TextureAtlasSprite.java:288)
```

**Comment by FormalTrasier36** [comment]
How do you give modded minecraft more memory?

**Comment by UltraBlackLinux** [comment]
Settings -> Java

**Comment by Heufneutje** [comment]
https://github.com/MultiMC/MultiMC5/wiki/Increasing-Java%27s-memory-allocation
