### ISSUE TITLE
index_v2.json file missing multiMC

### ISSUE THREAD

**Issue by Amrien** [MultiMC/MultiMC5#3153]
System Information
-----------------------------
MultiMC version: Various Versions. 0.6.11 and latest versions (both stable and developmental)

Operating System: Windows 7

Summary of the issue or suggestion:
----------------------------------------------
MultiMC starts, but crashes near immediately. 

What should happen:
------------------------------
MultiMC shouldn't crash.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Downloaded MultiMC

2. Extracted to desktop or any driver folder

3. Clicked to run MultiMC

4. Crash "MultiMC Launcher has stopped working."

Suspected cause:
---------------------------
Ran it in command prompt, here's the screenshot of the log.

Logs/Screenshots:
----------------------------
![MultiMC problem](https://user-images.githubusercontent.com/65141078/82156056-e0c24600-982d-11ea-9c3c-0ed98e473112.png)

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
have you just extracted the multimc.exe?

**Comment by liorsl** [comment]
It seems like I am facing the same issue, Windows 10, Java 8, fresh install
https://pastebin.com/eACAd9Zf

**Comment by Zetabite** [comment]
Try disabling antivirus

**Comment by Amrien** [comment]
@Zetabite as you can see in my steps, yes it's been fully extracted onto the desktop. I also tried putting it in program files.

@liorsl I don't know what would be causing it. It worked literally a month ago for me.

@Zetabite I don't have any antivirus and the only and I had Windows firewall disabled. No dice.

**Comment by Zetabite** [comment]
No idea then

**Comment by kb-1000** [comment]
When I delete the `translations` directory and then start multimc, this appears in its log:
```
    0.024 C Exception: "Unable to open /home/kb1000/MultiMC-Install/translations/index_v2.json for reading: No such file or directory"
    0.025 C Translations Download Failed: index file not readable
```
Exactly what you're facing. However, for me it doesn't crash, and the directory is automatically created and populated after startup. That means your issue is caused by something else.

**Comment by Janrupf** [comment]
> When I delete the `translations` directory and then start multimc, this appears in its log:
> 
> ```
>     0.024 C Exception: "Unable to open /home/kb1000/MultiMC-Install/translations/index_v2.json for reading: No such file or directory"
>     0.025 C Translations Download Failed: index file not readable
> ```
> 
> Exactly what you're facing. However, for me it doesn't crash, and the directory is automatically created and populated after startup. That means your issue is caused by something else.

Yeah, that is the correct behaviour, it automatically downloads the missing files. It is possible, that the last log messages are completely unrelated and something else is blowing up.

**Comment by kb-1000** [comment]
> Yeah, that is the correct behaviour, it automatically downloads the missing files. It is possible, that the last log messages are completely unrelated and something else is blowing up.
That's what I mean. And it's not just possible, it's very likely.

**Comment by Amrien** [comment]
I'll keep attempting new things. I'll need to investigate further and do testing, but it's just so odd that it's not working.

**Comment by kb-1000** [comment]
You will most likely need a debug build of Qt for more detailed error logging.
But unfortunately I think that you can't get one working with MMC

**Comment by Amrien** [comment]
Does anyone else have a recommendation of what to do? I've been trying to figure this out. how can I tell what's blowing up? I don't know how to start making progress on this.

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
