### ISSUE TITLE
My mods are not being accepted by MultiMC5!

### ISSUE THREAD

**Issue by TheNerdyFunnyComedian** [MultiMC/MultiMC5#3155]
System Information
-----------------------------
MultiMC version:
MultiMC5
Operating System:
Lenovo IdeaPad (Win10)
Summary of the issue or suggestion:
----------------------------------------------
Whenever I try to import mods into through MultiMC, it says that the file is not a recognized modpack type. I have tried all sports of mods, but I get the same issue. I have scoured different websites if I am doing something wrong, but it seems that I'm not. For now, I am reporting this as a bug but if there is something I am doing wrong please tell me. I should also mention that if I try to put it in to the MultiMC mods folder myself (Yes, I am using the right version of forge) I play the game and it doesn't recognize my mod as a mod. 

What should happen:
------------------------------
I should be able to drag and drop my mods into my folder/put the mods in the mods folder and it should accept them as mods

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Try to use a Lenovo IdeaPad with Win10

2. Download MultiMC5 (Doesn't matter if you are running experimental or non-experimental as I get the same issue)
3. Try to drag and drop the mods/put mods in the mods folder

Suspected cause:
---------------------------
A possible compatibility issue with my specific pc.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by kb-1000** [comment]
You don't import mods as modpacks, that just doesn't work (dragging files into the main window is importing modpacks.). You add mods to a single instance.

**Comment by TheNerdyFunnyComedian** [comment]
Oh I am so sorry for the misinterpretation, I am not doing that.

**Comment by sambhavsaggi** [comment]
Would you be able to upload screenshots of what exactly you are doing? Could you also update your question with Windows build and MultiMC version?

[How to find Windows build](https://www.howtogeek.com/236195/how-to-find-out-which-build-and-version-of-windows-10-you-have/)

To find the MultiMC version, press "Update" and report back the version (if you are on the latest build)

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
