### ISSUE TITLE
MultiMC

### ISSUE THREAD

**Issue by FormalTrasier36** [MultiMC/MultiMC5#3158]
Hi I have a problem with joining servers in minecraft using MultiMC. It says that I am out of memory. Do you know how to fix that?

**Comment by devomaa** [comment]
allocate more memory from Settings -> Java

**Comment by Forkk** [comment]
Please fill out the issue form correctly next time.

This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
