### ISSUE TITLE
AdoptOpenJDK 14

### ISSUE THREAD

**Issue by reddvilzz** [MultiMC/MultiMC5#3161]
System Information
-----------------------------
MultiMC version: 0.6.12 develop 1438

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Running instances using AdoptOpenJDK 14, would crash.

What should happen:
------------------------------
The game would start

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Using AdoptOpenJDK 14 with HotSpot VM (https://adoptopenjdk.net/?variant=openjdk14&jvmVariant=hotspot)

2. Launch the game

3. Crash

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
https://paste.ee/p/touwg

Additional Info:
---------------------------

**Comment by kb-1000** [comment]
Known issue, not MultiMC's fault nor fixable in MultiMC

**Comment by reddvilzz** [comment]
Ah okay, I'll close it. Thank you.
