### ISSUE TITLE
Add mod updater

### ISSUE THREAD

**Issue by Suyashtnt** [MultiMC/MultiMC5#3162]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 10

Summary of the issue or suggestion: Add a mod updater
----------------------------------------------

What should happen: When you open the mods menu, if the mod is on Curseforge it will see if there is a new version. If there is, there will be a little icon you can click kinda like twitch.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.N/A
Suspected cause: N/A
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
N/A

Additional Info: Modloader I'm using: Fabric
---------------------------

**Comment by kb-1000** [comment]
That would require mods to contain metadata about them being on curseforge. And they don't have such metadata. So, it is not possible.

**Comment by Suyashtnt** [comment]
oh, ok then, but maybe could you do it so you can put in the twitch URL?

**Comment by Heufneutje** [comment]
That is unrelated. There is no possible way to do this unless MultiMC had its own mod repository that is not CurseForge.

**Comment by Suyashtnt** [comment]
> That is unrelated. There is no possible way to do this unless MultiMC had its own mod repository that is not CurseForge.

Could you explain why you can't do that?

**Comment by Zetabite** [comment]
This would need the access to meta data of twitch, which would require access to the api, which doesnt exist, else you wont be able to tell if a mod has been updated

**Comment by peterix** [comment]
it's not `can't`. It's `won't`. I am not making a 'twitch client' here.
