### ISSUE TITLE
Add API for opening MultiMC Instances.

### ISSUE THREAD

**Issue by devomaa** [MultiMC/MultiMC5#3163]
# Type of issue
This is a suggestion
# Summary of the issue or suggestion:
It would be nice if we could open instances using an API, instead of copying the incredibly long command, so why not use MultiMC Instances?
# How I would want it to work
Either in Java, Lua, or bash whatever, I would want to open my instances using an command or API, It would look something like this in Lua:
```lua
local multimc = require("multimc")
somejsonserializer(multimc.listInstances):
```
```json
{
	"name": "1.12.2",
	"version": {
		"vanilla": "1.12.2",
		"optifine": "E7"
	},
	"group": "Vanilla Minecraft",
	"identifier": 1
}
...
```
```lua
local multimc = require("multimc")
multimc.openInstance("1.12.2", --[[Identifier if there is multiple instances named the same]] 1):
Opens the selected instance
```
etc.

**Comment by kb-1000** [comment]
Run `multimc --launch <instance name>`
could be --instance too, idk

**Comment by devomaa** [comment]
@kb-1000 Tried that, just opened MultiMC, even `multimc --help` didn't work

**Comment by Janrupf** [comment]
![image](https://user-images.githubusercontent.com/25827180/82925497-0d890280-9f7e-11ea-859f-c9ecdf50fa38.png)

**Comment by Zetabite** [comment]
> @kb-1000 Tried that, just opened MultiMC, even `multimc --help` didn't work

you need to launch it with commands in terminal, not mmc

**Comment by peterix** [comment]
It's already there.

**Comment by peterix** [comment]
And it's `multimc --launch Instance ID`, which is the name of the folder.

The folder names are more suited to be identifiers, because the OS enforces uniqueness there.

**Comment by kb-1000** [comment]
```
u0_a104 in MultiMC5/build on  develop [$?]
➜ ./MultiMC --help
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to
'/data/data/com.termux/files/usr/tmp/runtime-u0_a104'
Usage: ./MultiMC [-h] [-V] [-d <dir>] [-l <launch>] [--alive]

Options & Switches:
  -h, --help            Display this help and exit.
  -V, --version         Display program version and exit.
  -d, --dir <dir>       Use the supplied folder as MultiMC root instead of
the binary location (use '.' for current)
  -l, --launch <launch> Launch the specified instance (by instance ID)
  --alive               Write a small 'live.check' file after MultiMC starts
```

`--launch` is definitely there.
This is a develop version from approximately when 0.6.7 was up to date (it
has been a while since I last started MultiMC on my phone 😁), and the
feature has not been removed since then. Your package's multimc wrapper
script might be broken. Which package are you using?
Anyways, what do you need that for at all?

>
