### ISSUE TITLE
modpack not working "Failed to start minecraft"

### ISSUE THREAD

**Issue by devauntea** [MultiMC/MultiMC5#3166]
System Information
-----------------------------
MultiMC version: 0.6.11-1370

Operating System:macOS Mojave

Summary of the issue or suggestion:
----------------------------------------------
When I try to start any modpacks it says failed "Failed to start Minecraft". I've tried this with the modpacks RLCraft and Valhelsia 1, which have given me two different errors. 

What should happen:
------------------------------
profiles should start minecraft

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.download RLCraft/Valhelsia 1

2.install latest forge

3.install latest JAVA

Suspected cause:
---------------------------
Incompatible versions of mods

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

https://paste.ee/p/QiVAM 

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
1. https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java
2. https://cdn.discordapp.com/attachments/531598137790562305/575378380573114378/unknown.png

**Comment by devauntea** [comment]
That didn't work Im already on 1.8.0_251

**Comment by phit** [comment]
no you aren't your log shows you are using java 12

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
