### ISSUE TITLE
Mods not loading correctly: "0 child mods"

### ISSUE THREAD

**Issue by jonleeyz** [MultiMC/MultiMC5#3168]
First time reporting a bug (both for Minecraft, as well as on GitHub), so just 2 quick things:
1. My apologies if if there is anything lacking in this report; please do let me know if I need to rectify anything or provide more information and I will be happy to do so!
2. My sincere thanks to the MultiMC team for making such a great launcher; it's great work y'all have done! :)

---

System Information
-----------------------------
**MultiMC**: 5, 0.6.11-1430
**Operating System**: Windows 10 Pro 10.0.18363
**Java**: 64 bit, Version 8 Update 251 (build 1.8.0_251-b08)
**Modpacks**: Enigmatica 2 Expert 1.78, FTB Revelation 3.2.1-1.1.12.2,  

Summary of the issue or suggestion:
----------------------------------------------
Modpacks appear to be installed and enabled in MultiMC instance windows (Figure 1) but are not actually working in-game.

Two main manifestations of the problem:
1. Modpack's "mod list" window (Figure 2): Each mod appears to have 0 child mods. Before this issue cropped up, almost every, if not all, mod had at least 1 child mod.
2. In-game: Some mods have their mod-specific items missing (eg. Immersive Engineering), while others that are more UI specific are not working (eg. Better Questing). This was observed in my Enigmatica 2 Expert world, as I only checked for the "mod list" observation in FTB Revelation. As Enigmatica 2 Expert is a big kitchen-sink modpack, it was unfeasible to check everything for what was working and was not.

What should happen:
------------------------------
1. Most, if not all mods, should have some child mods.
2. Mods should be working correctly in-game.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install MultiMC 5. I set RAM allocated to min 6144 MB and max 8192 MB.
2. Download the zip file for Enigmatica 2 Expert and FTB Revelation.
3. Create an instance for Enigmatica 2 Expert and FTB Revelation.
4. Open the Enigmatica 2 Expert instance and launch. 
5. Check "mod list"  for "0 child mods" issue.
6. Create a new world and load in to observe the dysfunctionality of certain mods in-game.
7, Perform steps 4 - 6, but for FTB Revelation.

Suspected cause:
---------------------------
To preface this section, I am not an experienced developer, but I have attempted the following as solutions (in no particular order), to no avail:
1. Close the affected instance and relaunch.
2. Kill the affected running instance and relaunch.
3. Reinstall the modpack and launch (both Enigmatica 2 Expert & FTB Revelation).
4. Delete MultiMC folder and reinstall from downloaded zip.
5. Reinstall Java Runtime Environment.
6.  Restart computer and then rerun just step 3.

My suspicion is that this might be a problem with the installation of Forge by MultiMC, as having "0 child mods" for almost every mod is one thing, but considering that it persists when restarting or reinstalling MultiMC, Java and modpacks, or even between two modpacks, informs me that it is probably not a Minecraft or a modpack-specific issue.

I am in the midst of trying other launchers to see if this problem is exclusive to MultiMC, but this will take time, as I have not used anything else before.

I have also read [Let's Talk About Forge](https://multimc.org/posts/forge-114.html), which applies to Forge for versions of Minecraft that are not 1.13 or above, and hence does not apply.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your log
I have a screenshot, but I am trying to figure out how to host the image before I can link to it here.

Additional Info:
---------------------------

**Comment by Janrupf** [comment]
That sounds pretty weird, but mods having 0 child mods is totally normal. Child mods are rarely used, those numbers were probably always 0.

> [//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your log

The screenshot is not that important, a log file would help much more. (Btw, you can host screenshots by simply copying them to your clipboard and then just pasting them :smile:).

Upload a log the following way:
![image](https://user-images.githubusercontent.com/25827180/83555277-586ec100-a50e-11ea-8f80-67fb8304bc19.png)

**Comment by jonleeyz** [comment]
Thanks for replying!

I see about the child mods, but I do remember some mods distinctly having some numbers there, could be mistaken though.

And sorry I didn't realize it was so easy to upload the log (or screenshots for that matter), here it is: https://paste.ee/p/fLVn7

Let me know what other information might help!

**Comment by phit** [comment]
> Create a new world and load in to observe the dysfunctionality of certain mods in-game

can you explain what doesn't work? the log seems normal

**Comment by jonleeyz** [comment]
Sorry that I did not follow up earlier; work has been crazy and I have not had the chance to test out specifically what went wrong.

As I previously assumed the problem was related to the loading of the game but not a specific save, the previously uploaded log only documented the state of the game instance when I started loading the instance, all the way till I was at main menu.

This new [log](https://paste.ee/p/V6T6w) documents the state of the game instance (Enigmatica 2 Expert 1.78) from when I start loading the instance, all the way I loaded into 2 saves. The first was a newly created world, the second was my previous save (copy pasted the save folder, not sure if that is the correct way to backup and restore saves). So maybe this log might indicate some anomalies.

Some empirical problems I noticed when I loaded up my previous save:
1. **Immersive Engineering**: All LV wire coils that were connected in-world are just gone.
2. **Tinkers' Construct**: Tools that had the Global Traveler (allows the user to teleport to a set location in-world) attribute were unlinked.
3. **Hotbar switching mod (not sure which mod)**: This mod allowed me to store 4 separate hotbar configurations of items and switch them in and out. When I loaded up the save, all saved hotbar configurations were lost and most of the items appeared back in my main inventory, but some items were lost.
4. **JourneyMap**: All saved bookmarks were lost.

Please let me know what other information I can provide.

**Comment by QuImUfu** [comment]
Your save game got corrupted. Likely the whole [worldname]/data folder went missing. It is used by mods and minecraft to store global data.  
This explains all issues.  
However without the log that was created when all the data got lost it is impossible to pinpoint a problem, as seemingly everything is fine in that log (it loads and saves the global state just fine).  
Should you have older logs in your logs folder, upload and link those (the whole folder), that might give some clue as of why this happened.

**Comment by jonleeyz** [comment]
Thank you for explaining, looks like my save is unsalvagable then :(

Even more unfortunately, I've since reinstalled MultiMC a total of 4 times so I won't be able to provide the original logs for y'all :( should a similar issue crop up, I will be sure to report it again here with the appropriate logs.

Might there be anything else I could do to shed light on the issue? I'm not a very experienced developer, just out of school but would love to contribute if there is anything that needs helping and is within my capacity! If not, thank you all for your time and making such a good product!

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
