### ISSUE TITLE
upgrade instance failure

### ISSUE THREAD

**Issue by Orneno** [MultiMC/MultiMC5#3170]
System Information
-----------------------------
MultiMC version:
0.6.11-1370
Operating System:
macOS Catalina 10.15.3
Summary of the issue or suggestion:
----------------------------------------------
When I opened MultiMC recently, I got the message that my main instance, which used MC 1.7.10, needed to be upgraded to a new format.  Seems well and good, but when I click the button to do so I get a pop-up error box that says Instance folder copy failed.
If I close the dialogue all together and try and make a new instance instead, MultiMC crashes instantly when I hit create after selecting with MC version to use.

What should happen:
------------------------------
instance is copied and upgraded, or a new one can be made

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
<img width="815" alt="Screen Shot 2020-05-30 at 3 58 03 PM" src="https://user-images.githubusercontent.com/64508750/83338904-5f879c00-a28e-11ea-8254-775da4127d79.png">

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
I think that feature broke a long time ago, and only works on older versions after this was implemented. Solution is atm, just to make a new instance and copy over the files

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
