### ISSUE TITLE
Minecraft refuses to launch on versions 1.12.2 and below

### ISSUE THREAD

**Issue by jbmagination** [MultiMC/MultiMC5#3171]
EDIT: Whoops. Somehow managed to include what was supposed to be commented out and didn't see it in preview.

System Information
-----------------------------
EDIT: Added Java version. 

MultiMC version: 0.6.11-1370 on osx64

Operating System: macOS Catalina 10.15.4 (19E287)

Java version: 13.0.2

Summary of the issue or suggestion:
----------------------------------------------
Starting from the oldest version (rd-132211) to Minecraft version 1.12.2, the game refuses to launch, and crashes.

What should happen:
------------------------------
EDIT: Reworded and simplified.

The game should launch as expected.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add any instance using any Minecraft version from rd-132211 to 1.12.2

2. Start said instance

3. See the game crash

Suspected cause:
---------------------------
EDIT: Change cause and add notice for Java 8.

 It is a problem with the Java version.

In MultiMC, 1.13+ and above utilize LWJGL version `3.1.6`, while 1.12.2 and below use version `2.9.4-nightly-20150209`. In the official Minecraft launcher, 1.13+ and above utilize version `3.2.1`, while 1.12.2 and below use version `2.9.2-nightly-20140822`. Likely, the instruction set changed for LWJGL inbetween these versions, and Java understands these new changes.

You can see there is a `SIGILL` error in the logs, which means the CPU didn't understand an instruction. This is further proven when in that same log, it states "The crash happened outside the Java Virtual Machine in native code." This does not occur in the official Minecraft launcher, which uses Java 8.

Even more mind boggling, even downgrading to 2.9.2 for version 1.12.2 in MultiMC won't launch, so it's not a problem with LWJGL.

After running this in Java 8 it works as expected. However, plenty of people do not have Java 8 (I'm pretty sure Catalina comes with 13.0.2), so this should still be fixed if possible to prevent this from occurring in the future.

Logs/Screenshots:
----------------------------
I recommend viewing Additional Info before looking at the logs unless you like redundancy.

[MultiMC Minecraft Log](https://paste.ee/p/WZBFY)
[MultiMC Crash Report](https://paste.ee/p/rGkGX)

Additional Info:
---------------------------
EDIT: Took something out to rewrite it and forgot to finish it. Removed the part entirely.
EDIT 2: Added exit code.
EDIT 3: Added important notice for Java 8.
EDIT 4: Add potential solution.
EDIT 5: Removed notice for Java 8.
EDIT 6: Man, 6 edits already? Add location for Minecraft’s bundled runtime.

If needed, the problematic frame is:
> \# Problematic frame:
> \# C  [AppKit+0x3e565c]  -[NSOpenGLContext setView:]+0xe5

And the process crashes with exit code 6.

However, a better solution would be to automatically try to download Java 8 if it’s not found, and allow a change from the bundled Java runtime in Settings. Even better, use the official launcher’s runtime if available.

For reference, Minecraft’s bundled runtime is available at the following locations:

macOS: `<.minecraft location>/runtime/jre-x64/jre.bundle/Contents/Home/bin/java`
Windows (x86): `<Minecraft launcher location>\runtime\jre-x86\bin\java.exe`
Windows (x64): `<Minecraft launcher location>\runtime\jre-x64\bin\java.exe`
Linux: No fun :(

**Comment by jbmagination** [comment]
After running this in Java 8 it works as expected. However, plenty of people do not have Java 8 (I'm pretty sure Catalina comes with 13.0.2), so this should still be fixed if possible to prevent this from occurring in the future.

**Comment by jbmagination** [comment]
Man, when I first posted this issue, I was just wondering why Beta 1.7.3 didn’t run but 1.15.2 did. Now I’m actually learning somewhat about Minecraft.

**Comment by kb-1000** [comment]
> After running this in Java 8 it works as expected. However, plenty of people do not have Java 8 (I'm pretty sure Catalina comes with 13.0.2), so this should still be fixed if possible to prevent this from occurring in the future.

Most people do not have MultiMC either, so they have to install it if they want to use it. Sounds logical, right?
Although this seems to be unrelated to that, Java 8 is the only version that will work with many mods.
> Even more mind boggling, even downgrading to 2.9.2 for version 1.12.2 in MultiMC won't launch, so it's not a problem with LWJGL.

Do you really think this proofs that it's unrelated to LWJGL? After all, since 1.13 LWJGL 3 is used, which is fundamentally different and a complete rewrite.

**Comment by jbmagination** [comment]
> Although this seems to be unrelated to that, Java 9 is also the only version that will work with many mods.

Exactly- and it's also the version that the Minecraft launcher downloads, so it would make plenty sense to at least check for it and try to use it.

> Do you really think this proofs that it's unrelated to LWJGL? After all, since 1.13 LWJGL 3 is used, which is fundamentally different and a complete rewrite.

Good point.

This refers to LWJGL 2, not 3-- what I mean is since Minecraft was running 2.9.2 and MultiMC was running 2.9.4, I showed that even a downgrade to 2.9.2 didn't work, and as such the LWJGL version used isn't the issue.

**Comment by kb-1000** [comment]
> and as such the LWJGL version used isn't the issue.

That's not a proof. A proof would be if you somehow patched 1.12 to run with lwjgl 3 and it would still not work. you cant just test a version and then say it's unrelated.

**Comment by jbmagination** [comment]
So would there be no proof in that case? Because as far as I know that’s not possible.

**Comment by UltraBlackLinux** [comment]
Is it a java Problem? I thought the best MC java version was Java 8...
