### ISSUE TITLE
Error occurred during initialization of VM Could not reserve enough space for 3145728KB object heap Process exited with code 1.

### ISSUE THREAD

**Issue by WickedsickGGS** [MultiMC/MultiMC5#3172]
System Information
-----------------------------
MultiMC version:MultiMC 0.6.11-1430

Operating System:Windows 10

Summary of the issue or suggestion:idk
----------------------------------------------

What should happen:idk
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.when i try to launch any instances modded or not

2.

3.

Suspected cause: idk
---------------------------

Logs/Screenshots:
----------------------------
[MultiMC version: 0.6.11-1430

Minecraft folder is:
D:/1MULTIMC/MultiMC/instances/Etho's LP Pack/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_251, using 32-bit architecture.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  D:/1MULTIMC/MultiMC/instances/Etho's LP Pack/natives

Libraries:
  D:/1MULTIMC/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  D:/1MULTIMC/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  D:/1MULTIMC/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  D:/1MULTIMC/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  D:/1MULTIMC/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  D:/1MULTIMC/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  D:/1MULTIMC/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  D:/1MULTIMC/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  D:/1MULTIMC/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  D:/1MULTIMC/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  D:/1MULTIMC/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  D:/1MULTIMC/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  D:/1MULTIMC/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  D:/1MULTIMC/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  D:/1MULTIMC/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  D:/1MULTIMC/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  D:/1MULTIMC/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  D:/1MULTIMC/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  D:/1MULTIMC/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  D:/1MULTIMC/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  D:/1MULTIMC/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  D:/1MULTIMC/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  D:/1MULTIMC/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  D:/1MULTIMC/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  D:/1MULTIMC/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  D:/1MULTIMC/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  D:/1MULTIMC/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  D:/1MULTIMC/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  D:/1MULTIMC/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  D:/1MULTIMC/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1566-1.7.10/forge-1.7.10-10.13.4.1566-1.7.10-universal.jar
  D:/1MULTIMC/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  D:/1MULTIMC/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  D:/1MULTIMC/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  D:/1MULTIMC/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  D:/1MULTIMC/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  D:/1MULTIMC/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  D:/1MULTIMC/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  D:/1MULTIMC/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  D:/1MULTIMC/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  D:/1MULTIMC/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  D:/1MULTIMC/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  D:/1MULTIMC/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  D:/1MULTIMC/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  D:/1MULTIMC/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  D:/1MULTIMC/MultiMC/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  D:/1MULTIMC/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  D:/1MULTIMC/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  D:/1MULTIMC/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-32.jar
  D:/1MULTIMC/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-32.jar

Mods:
  [📁] 1.7 (folder)
  [✔️] 1.7.10-Pistronics2-v0.6.4
  [✔️] AppleCore-mc1.7.10-1.0.2
  [✔️] appliedenergistics2-rv2-stable-10
  [✔️] ArchimedesShips-1.7.1
  [✔️] BiblioCraft[v1.9.2][MC1.7.10]
  [✔️] BiomesOPlentyMod
  [✔️] buildcraft-7.1.16
  [✔️] Carpenter's Blocks v3.3.4.2 - MC 1.7.10
  [📁] carpentersblocks (folder)
  [✔️] Chisel2-2.5.1.44
  [✔️] CodeChickenCore-1.7.10-1.0.4.29-universal
  [✔️] CoFHCore-[1.7.10]3.1.2-325
  [✔️] compactmachines-1.7.10-1.17
  [📁] ComputerCraft (folder)
  [✔️] ComputerCraft1.75
  [✔️] CustomNPCs_1.7.10d
  [✔️] DeadlyWorld-1.7.10-1.0.2
  [✔️] Decocraft-2.2.1_1.7.10
  [✔️] DragonAPI 1.7.10 V13b
  [✔️] Enchiridion-1.7.X-1.2b
  [✔️] EnderIO-1.7.10-2.2.8.381
  [✔️] ExtraCells-1.7.10-2.3.9b188
  [✔️] extrautilities-1.2.1
  [✔️] fastcraft-1.21
  [✔️] forestry_1.7.10-4.2.9.57
  [✔️] FPSPlus-1.7.10
  [✔️] funky-locomotion-1.7.10-beta-4
  [✔️] GalacticraftCore-1.7-3.0.11.320
  [✔️] Galacticraft-Planets-1.7-3.0.11.320
  [✔️] gases-1.5.2-1.7.10
  [✔️] gasesCore-1.5.2-1.7.10
  [✔️] gasesFramework-1.0.6-1.7.10
  [✔️] gasesFrameworkCore-1.0.6-1.7.10
  [✔️] growthcraft-bamboo-1.7.10-2.1.0
  [✔️] growthcraft-bees-1.7.10-2.1.0
  [✔️] growthcraft-cellar-1.7.10-2.1.0a
  [✔️] growthcraft-core-1.7.10-2.1.0a
  [✔️] growthcraft-grapes-1.7.10-2.1.0
  [✔️] growthcraft-hops-1.7.10-2.1.0
  [✔️] growthcraft-rice-1.7.10-2.1.0a
  [✔️] HardcoreEnderExpansion  MC-1.7.10  v1.8.4
  [📁] ic2 (folder)
  [✔️] IC2NuclearControl-2.1.2a
  [✔️] ImmersiveEngineering-0.7.5
  [✔️] industrialcraft-2-2.2.810-experimental
  [✔️] InventoryTweaks-1.58-147
  [✔️] ironchest-1.7.10-6.0.62.742-universal
  [✔️] JourneyMap5.0.1_Unlimited_MC1.7.10
  [✔️] LunatriusCore-1.7.10-1.1.2.21-universal
  [✔️] Mantle-1.7.10-0.3.2
  [✔️] Mariculture-Deluxe-1.7.10-1.2.4.2a
  [✔️] Mekanism-1.7.10-8.1.9.265
  [✔️] MicdoodleCore-1.7-3.0.11.320
  [✔️] Minechem-1.7.10-5.0.5.406
  [✔️] mystcraft-1.7.10-0.12.3.02
  [✔️] natura-1.7.10-2.2.0.1
  [✔️] neiaddons-1.12.14.40-mc1.7.10
  [✔️] NEIIntegration-MC1.7.10-1.1.2
  [✔️] NotEnoughItems-1.7.10-1.0.3.74-universal
  [✔️] OpenBlocks-1.7.10-1.3
  [✔️] OpenComputers-MC1.7.10-1.5.22.46-universal
  [✔️] OpenModsLib-1.7.10-0.6
  [✔️] OpenPeripheral-1.7.10-AIO-1
  [✔️] Pam's HarvestCraft 1.7.10f
  [✔️] Peripherals++-1.2.9
  [✔️] PneumaticCraft-1.7.10-1.6.7-69-universal
  [📁] PPP (folder)
  [📁] ppp_mount (folder)
  [✔️] ProjectRed-1.7.10-4.5.15.75-Base
  [✔️] ProjectRed-1.7.10-4.5.15.75-Compat
  [✔️] ProjectRed-1.7.10-4.5.15.75-Integration
  [✔️] ProjectRed-1.7.10-4.5.15.75-Lighting
  [✔️] ProjectRed-1.7.10-4.5.15.75-Mechanical_beta
  [✔️] qCraft-1.2
  [📁] railcraft (folder)
  [✔️] Railcraft_1.7.10-9.8.0.0
  [✔️] RandomThings-2.2.2
  [✔️] RotaryCraft 1.7.10 V13a
  [✔️] Schematica-1.7.10-1.7.6.131-universal
  [✔️] SimplyJetpacks-MC1.7.10-1.3.2
  [✔️] SpiceOfLife-mc1.7.10-1.2.3
  [✔️] StevesCarts2.0.0.b18
  [✔️] StevesFactoryManagerA92
  [✔️] TConstruct-1.7.10-1.8.7
  [📁] temp (folder)
  [✔️] Thaumcraft-1.7.10-4.2.3.0
  [✔️] ThaumicInfusion-1.7.10-3.83
  [✔️] ThaumicTinkerer-2.5-1.7.10-162
  [✔️] ThermalDynamics-[1.7.10]1.1.0-161
  [✔️] ThermalExpansion-[1.7.10]4.1.2-240
  [✔️] ThermalFoundation-[1.7.10]1.2.3-112
  [✔️] TMechworks_mc1.7.10_0.2.8
  [✔️] twilightforest-1.7.10-2.3.5
  [✔️] Waila-1.5.5_1.7.10
  [✔️] WailaHarvestability-mc1.7.x-1.1.0
  [✔️] WR-CBE-1.7.10-1.4.1.9-universal
  [✔️] Ztones-1.7.10-2.2.1

Params:
  --username  --version MultiMC5 --gameDir D:/1MULTIMC/MultiMC/instances/Etho's LP Pack/.minecraft --assetsDir D:/1MULTIMC/MultiMC/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType  --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx3072m, -Duser.language=en]

Minecraft process ID: 7692

Error occurred during initialization of VM
Could not reserve enough space for 3145728KB object heap
Process exited with code 1.
MultiMC: Log upload triggered at: 31 May 2020 14:59:45 +0300
MultiMC: Log upload failed!
MultiMC: Log upload triggered at: 31 May 2020 14:59:49 +0300
MultiMC: Log upload failed!
Clipboard copy at: 31 May 2020 14:59:53 +0300
Clipboard copy at: 31 May 2020 14:59:55 +0300

Additional Info:nothing
---------------------------

**Comment by kb-1000** [comment]
Using 3GB RAM requires a 64-bit Java. Install one.

**Comment by WickedsickGGS** [comment]
> Using 3GB RAM requires a 64-bit Java. Install one.

thanks

**Comment by idk-br0** [comment]
> 
I have the same problem, the official launcher works fine but multimc doesn't, why?
