### ISSUE TITLE
"Minecraft has run out of memory" errors in log and "Can't connect to server" Error on Multiplayer

### ISSUE THREAD

**Issue by Bunistalri** [MultiMC/MultiMC5#3174]
System Information
-----------------------------
MultiMC version: 0.6.11-1430 on win32

Operating System: Windows 10, 64bit

Summary of the issue or suggestion:
----------------------------------------------
This is a 3-part rabbit hole of things that screwed up in Minecraft and MultiMC. 
1) I wanted to make space in my laptop's C: SSD drive, so I deleted the Minecraft launcher and most of my MultiMC instances. I reinstalled the Minecraft Launcher. I deleted and re-downloaded Java.
2) Minecraft gives me a "Minecraft has run out of memory" error
3) Multiplayer lists all Minecraft servers as grayed-out and "Can't connect to server"

What should happen:
------------------------------
Minecraft should start up as normal when double-clicking a MultiMC instance. Minecraft should not give any "Minecraft has run out of memory" errors. The multiplayer servers should have their own colorful icons and should be available to connect to them.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Attempt to free up space on my C: SSD drive by deleting the Minecraft Launcher. Also delete an old-looking version of Java in my Downloads folder that has the number 8 on it, which I assumed meant "Windows 8".

1a. Attempt to move the Minecraft Launcher to D: drive, which has more space. 

1b. Realize that MultiMC stops functioning without the Minecraft Launcher and that I have no idea how to make MultiMC check for the Minecraft Launcher in the D: drive without making things worse.

1c. Re-download the Minecraft Launcher to C:

1d. MultiMC can't find Java. Redownload Java to both C: and D:.

1e. Minecraft now gives me a "Minecraft has run out of memory" screen whenever I try to start it.

1f. Delete some extra MultiMC instances.

1g. Realize I accidentally deleted my main 1.15.2 instance (RIP 2019-2020), can't find it in the Recycle Bin, download Recuva, realize I can't find it in Recuva either.

2. Give up and create a new 1.15.2 instance

3. Click "Install Fabric". From Forge, download Fabric, Fabric API, Fabric installer, Optifabric, Optifine, and Voxelmap and move them to the instance's Mods folder.

4. Double click on the instance to run Minecraft.

5. Click Multiplayer

6. Add some servers by clicking Add server > Enter server IP > Enable server resource packs > Done

7. I now have a list of multipayer servers that all say "Can't connect to server" despite those servers being online. No wifi bars are shown and no player count is shown.

Suspected cause:
---------------------------
Something crucial somehow got deleted when I went on a drive cleaning rampage and deleted most of my MultiMC instances. Though it makes no sense how deleting instances can affect all future instances.

Logs/Screenshots:
----------------------------
[//]: # https://paste.ee/p/etqbJ

Additional Info:
---------------------------
This is a Dell G15 gaming laptop. I have restarted multiple times and that is not helping.
On the plus side: If I have to move the Minecraft Launcher to D: and uninstall MultiMC and then reinstall MultiMC to D: to free up space on C:, I won't have anything else left to lose. :3c

**Comment by Heufneutje** [comment]
You're using 32-bit Java and also only 1 GB of RAM. You should install 64-bit Java and assign more RAM in MultiMC's settings.

https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java

**Comment by Bunistalri** [comment]
I also have "Java Test Failure: The specified java binary didn't work with the arguments you provided:" when trying to test it under Java Runtime, is that related?

**Comment by Bunistalri** [comment]
Ah nvm the Java test succeeded after the 64 bit Java finished downloading!

**Comment by phit** [comment]
> Realize that MultiMC stops functioning without the Minecraft Launcher and that I have no idea how to make MultiMC check for the Minecraft Launcher in the D: drive without making things worse.

also just to clarify, you do not need the normal launcher installed at all for multimc to work

**Comment by Bunistalri** [comment]
Huh, that's strange. Right after I deleted the launcher MultiMC said it couldn't find Minecraft or something.

**Comment by kb-1000** [comment]
then you got a strange setup.

**Comment by UltraBlackLinux** [comment]
(Download now: Mac OS, and get a free ugly OS*. Edit: Cant download that, huh?)
(Download now: Linux, and get a free, open source OS*)
*: May contains CIA/FBI, no warranty on working components
**: May contains Bugs, we dont need warranty

**Comment by Zetabite** [comment]
You are the kind of person that make other people dislike linux.

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
