### ISSUE TITLE
Shared Folders

### ISSUE THREAD

**Issue by UltraBlackLinux** [MultiMC/MultiMC5#3175]
This allows Instances to all take RPs/Worlds from the same folder (as it is currently not possible via Folder-Shortcuts).
I have quite a few Instances, but almost all of them use the same resourcepack, thats why I had this Idea.
This could be done with
either a Shared/File folder (any kind, so it would be possible to share mod settings/OF Shaderpacks/...)
or a Settings entry, where you can drop Zip files and Folders with Zips in them (to keep it organized)
Id love to see such a Feature, since "shared" Folders are already a Thing in the default MC launcher, what eases Mod configuration & stuff.

**Comment by kb-1000** [comment]
That would require a virtual file system, which is really difficult to implement properly cross-platform. Just use symlinks.
The vanilla launcher has it because it doesn't separate versions from each other at all, which MultiMC does and which is its main feature.

**Comment by UltraBlackLinux** [comment]
Symlimks? I think Ive never used that technique - how do I do that on linux?

**Comment by Heufneutje** [comment]
https://stackoverflow.com/questions/1951742/how-can-i-symlink-a-file-in-linux

**Comment by UltraBlackLinux** [comment]
Thank you!
