### ISSUE TITLE
Twitch Modpack Creation Support / Mod Download client

### ISSUE THREAD

**Issue by UltraBlackLinux** [MultiMC/MultiMC5#3176]
So since Im on linux, I think there is no Twitch launcher available for my OS. Also I cant create Twitch Modpacks, but that would be kinda Important for me.
(For Context: Twitch modpacks have a File, where every mods download Link is listed.) Then I thought of This: 
What about a primitive Curse Client, where you can search Mods Read its Text (I think we dont need pics here, just dont add a browser, that displays the curse page, cause some people, like me, wouldnt like to get tracked by javascript & cookies) and being able to download Mods directly into the Mods Folder or import them from a custom Link. All Those Links will be listed in the Link-File.
So then you could export instances with this file as Twitch Modpack.
Optionally you could create an Option to auto search all Mods in Curse (And save the corresponding Mod link to Cache to make later searching faster by skipping known Mods. Also Mod List 404-Testing would be good.), to create a Pack from an Instance w/o the mods File.
Thats also a thing that Id love to see added, keep developing MMC, its a great Launcher!

**Comment by Zetabite** [comment]
I doubt Peterix will support this, he already said that he wont implement mod download afaik

**Comment by Heufneutje** [comment]
This is almost certainly going to be rejected.

**Comment by UltraBlackLinux** [comment]
oh ok, in that case....
(Want to create twitch modpacks though)
