### ISSUE TITLE
Adding/Removing Resourcepacks not possible when Instance Running

### ISSUE THREAD

**Issue by UltraBlackLinux** [MultiMC/MultiMC5#3177]
System Information
-----------------------------
MultiMC version: 0.6.11.r13 (the git version - newest beta)

Operating System: Linux

Summary of the issue or suggestion: 
----------------------------------------------
I think its not a Bug of some kind, I think its just sth coded wrong (?)
In MC changing Resourcepacks while the game is running is even Intended - why would you be able to open the RP folder from running mc, if not to being able to quickly change RPs. Deleting RPs from a running instance also isnt that Bad, cause the textures a stored In cache - the game doesnt break in any possible way (unlike with mods - i think).
So please change it, I always have to manually open the folder and drop the files there, its quite uncomfortable to change RPs when there is an option to do it with ease.

**Comment by kb-1000** [comment]
No, it's not coded wrong. It's working as intended. The mods and resource pack pages are read-only on purpose while the game is running.

**Comment by UltraBlackLinux** [comment]
Minecraft doesnt crash - try it yourself!
