### ISSUE TITLE
[Feature Request] Minecraft Icon = Multimc Instance Icon

### ISSUE THREAD

**Issue by UltraBlackLinux** [MultiMC/MultiMC5#3178]
It just would be a cool addition, if the Minecraft Task Bar Icon was the icon of the Instance In multimc.
(And Id also get rid of the blurry default MC icon)

**Comment by kb-1000** [comment]
Not possible, sorry. I think it's the case pre-1.6 when it still had a Java Applet, but now, it's impossible to do so.

**Comment by UltraBlackLinux** [comment]
Hm Ok.. Is it possible via some kinda Injector maybe? (you may know the client, that injects itself to mc at any time, and so provides a hack interface.)

**Comment by kb-1000** [comment]
Just no. And I don't think peterix wants to force users to use only modded MC.

**Comment by UltraBlackLinux** [comment]
That makes sense, ok. maybe could be toggled via Instance settings?

**Comment by UltraBlackLinux** [comment]
I just saw: It isnt a Modded client automatically:
![Screenshot_20200602_153520](https://user-images.githubusercontent.com/62404294/83526500-cd2e0500-a4e6-11ea-9274-bad0b2664343.png)

**Comment by kb-1000** [comment]
And that's just the legacy assets folder, for 1.5 and below.
Most likely it would get overwritten by MMC.
