### ISSUE TITLE
[Feature Request] Icon themes

### ISSUE THREAD

**Issue by UltraBlackLinux** [MultiMC/MultiMC5#3179]
So I dont like most of Multimc's (Edit: Instance) icons, cause they have this 3d effect, and I dont like 3d icons, so what about a 3d and flat icon theme? I could try to edit some (Eder pearl, MMC Logo, Herobrine, creeper,...) flat.

**Comment by kb-1000** [comment]
Already existing. Do you even check if features are already there?

**Comment by UltraBlackLinux** [comment]
I dont mean the MMC Button Icons, I mean the Instance Icons

**Comment by kb-1000** [comment]
I know what you meant.

**Comment by UltraBlackLinux** [comment]
you cant change those symbols via Icon themes.

**Comment by kb-1000** [comment]
![image](https://user-images.githubusercontent.com/18211838/83526021-16318980-a4e6-11ea-8295-9fe48c0fc492.png)

**Comment by UltraBlackLinux** [comment]
oof. cant find that folder in Arch :/

**Comment by kb-1000** [comment]
It's inside the executable. But you can override it using themes.
