### ISSUE TITLE
MultiMC not launching MineCraft at all.

### ISSUE THREAD

**Issue by BeadyEyesNoSoul** [MultiMC/MultiMC5#3180]
When I attempt to launch MineCraft through MultiMC, nothing happens, and a few error messages show in the logs.  I have absolutely **0** experience with MultiMC, and have been trying to get it to work all day.  I have no mods.

Here's the logs:
https://paste.ee/p/vwJ3O

**Comment by Zetabite** [comment]
https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java
