### ISSUE TITLE
Minecraft 1.8 with optifine exits with error code -1

### ISSUE THREAD

**Issue by blueslime32** [MultiMC/MultiMC5#3182]
System Information
-----------------------------
MultiMC version:
MultiMC5
Operating System:
Windows 10
Summary of the issue or suggestion:
----------------------------------------------
Minecraft should start correctly, but it only crashes and gives error code -1. It has never worked properly.

What should happen:
------------------------------
Well, Minecraft should at least open, or give more information. I read the crash report and I didn't find anything, probably because I'm not an expert on this

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create new instance of Minecraft 1.8

2. Add Optifine

3. The game doesn't start

Suspected cause:
---------------------------
I don't really know what's causing this

Logs/Screenshots:
----------------------------
https://paste.ee/p/yKzp7

Additional Info:
---------------------------
When opening the game with the original launcher, it works properly but then it crashes after a short while (0/0 fps), and the only way to exit the game is Alt+F4-ing. This has been an issue for a while and I don't know if it's the game of my machine. Should I send this to Mojang's Bug Tracker? Thanks :)

**Comment by QuImUfu** [comment]
You may be running an [Unsupported Intel GPU](https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs) and need to downgrade java.

**Comment by kb-1000** [comment]
Would you like to help with testing of a fix for that issue? I have an experimental Java build that might fix it without needing to downgrade it.
