### ISSUE TITLE
Flatpak packaging

### ISSUE THREAD

**Issue by stobbsm** [MultiMC/MultiMC5#3183]
Inquiry
-----------
Would you be interested in a community member creating a flatpak package out of this for Linux? Use it often with my son, and having an easier way to install in supported distributions (the majority can use it) is appealing.

I've already ported 2 things to flatpak on flathub:
- QOwnNotes
- The original PHP language extension for the SDK bundles (it's since been taken over, and that's fine by me)

Let me know, and I'll get started on it.

**Comment by phit** [comment]
https://github.com/MultiMC/MultiMC5/issues?q=is%3Aissue+flatpak+is%3Aclosed

**Comment by peterix** [comment]
Not again.

**Comment by stobbsm** [comment]
Ever consider it's getting asked for because people want it?

**Comment by stobbsm** [comment]
Btw, all those library issues you were having, as well as needing people to build it on there own whenever a library is changed, is the reason flatpaks, snaps, and a lesser extent appomage, were created.

Why no discussion and just a no? Not asking you to do the work or maintain it.

**Comment by Janrupf** [comment]
Let's say it this way. If you create a flatpack image, I guess nobody is going to complain about you doing so, as long as it doesn't mess with MultiMC internals (I might be wrong here though). I personally also have something against flatpack and all those packaging systems shipping half a linux system every installation, especially since they destroy portability of applications. So as said, you can create a package, but don't expect support from our side

**Comment by kb-1000** [comment]
Someone else is already making a flatpak, I wouldn't recommend you to create yet another one.

**Comment by peterix** [comment]
Personally, I consider flatpak, appimage, snap (and possibly other similar systems I'm not aware of) as a really bad idea.

The only official source of MultiMC binaries is multimc.org and the packages available from it.

As you can see, there is no flatpak. That is intentional.

**Comment by peterix** [comment]
In other words: not this. not again. not interested. and not interested in the discussion around it.

**Comment by stobbsm** [comment]
Wow. You don't like it, so no? Also, what do you call portable? Rebuilding a binary on a system that doesn't support it out of the box? Or being able to install a package on any Linux system and have it work?

**Comment by peterix** [comment]
It already does that.

**Comment by peterix** [comment]
And yes, `no` is a valid answer.

**Comment by peterix** [comment]
And the **final** answer, unless someone comes up with a system that is actually good.

**Comment by stobbsm** [comment]
> It already does that.



> And the **final** answer, unless someone comes up with a system that is actually good.

Definition of that is? Honestly, you're just coming off as "I don't like it, and neither should you, but all I'm going to do is be mad at it". I'll see who else is making a flatpak, and see if they need assistance. To bad you don't see the benefit, and decided that's enough to say no.

**Comment by peterix** [comment]
I'm not mad. I'm just saying 'no'.

**Comment by peterix** [comment]
And I wish github didn't have these emoji things.

**Comment by stobbsm** [comment]
> And I wish github didn't have these emoji things.

That's something we can agree on.

**Comment by ojoeth** [comment]
I generally don't run minecraft stuff outside of flatpak, as it acts as a sandbox  which prevents apps from accessing my home folder, /proc, etc. Considering quite a few RATs have been developed in the form of minecraft mods.

**Comment by peterix** [comment]
There will be no flatpak packaging.

**Comment by peterix** [comment]
I would sooner implement sandboxing in MultiMC than put MultiMC into any sort of sandbox.

**Comment by AverageComet250** [comment]
Multimc is supposed to be portable.

Making it a snap or flatpack will mean that it isn't portable whatsoever, as it has to store all its settings with settings for other apps and the binaries have to be in another place with the binaries for other apps.

**Comment by nonetrix** [comment]
I understand and respect your decision but it would be nice if Multimc could be packaged more places outside of Snaps and Flatpaks like RPM and etc

**Comment by spannerman79** [comment]
> I understand and respect your decision but it would be nice if Multimc could be packaged more places outside of Snaps and Flatpaks like **RPM** and etc

https://github.com/MultiMC/MultiMC5/blob/develop/application/package/rpm/MultiMC5.spec

Did you even **bother** to look @nonetrix ?

**Comment by nonetrix** [comment]
This isn't in the releases or website or in the Fedora repo

**Comment by nonetrix** [comment]
This is more of a band-aid than a fix imo

**Comment by spannerman79** [comment]
> This isn't in the releases or website or in the Fedora repo

...and neither is it in Ubuntu repos, what is your point exactly?

**Comment by nonetrix** [comment]
> > This isn't in the releases or website or in the Fedora repo
> 
> ...and neither is it in Ubuntu repos, what is your point exactly?
> 
> Edit: and neither in Arch, or Debian, etc

Would be nice if it was

**Comment by spannerman79** [comment]
> Would be nice if it was

Then complain to Fedora to change their [packaging](https://docs.fedoraproject.org/en-US/packaging-guidelines/what-can-be-packaged/#prebuilt-binaries-or-libraries) rules - not here.

You know for someone that uses linux you sure don't do your own homework and just bitch and whine without warrant nor reason to back up your "complaint"

**Comment by kb-1000** [comment]
As that would mean to allow "binary" packages due to peterix' wishes, that would go against its spirit.
RPMFusion might work though, they package a Steam "downloader" as well

**Comment by ojoeth** [comment]
The flatpak file which i used didn't even download the binary, it built multimc from source.

**Comment by peterix** [comment]
Then that's basically illegal.

**Comment by peterix** [comment]
Anyway, flatpak is not supported, will not be supported, and I'm not interested in discussing this any further.
