### ISSUE TITLE
when trying to launch any instance, minecraft crashes and the exit code is -1

### ISSUE THREAD

**Issue by Frostspark1** [MultiMC/MultiMC5#3184]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
When I try to load Compact Claustrophobia (modpack) or Vanilla Minecraft 1.12.2, the game crashes without even loading up Minecraft and the process exits with code -1

What should happen:
------------------------------
Load up Minecraft without any issues (hopefully)

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. I am not sure how to reproduce this issue.

2.

3.

Suspected cause:
---------------------------
I am using Java 32 bit, my system is 64 bit
Lots of libraries are missing (not native libraries)

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

I don't know how to upload them at the moment (they won't upload (says 'host requires authentication' error))
Additional Info:
---------------------------
I am using an MCleaks account because other alt accounts are not working at the time I am writing this.

**Comment by kb-1000** [comment]
-1 means nothing. Upload logs.

**Comment by Frostspark1** [comment]
like i said, it doesn't want to upload

**Comment by kb-1000** [comment]
You use MCleaks. That is illegal, and you won't receive ANY support here.

**Comment by Frostspark1** [comment]
I can't get a real account

**Comment by kb-1000** [comment]
Doesn't matter.

**Comment by Frostspark1** [comment]
also for some reason I can't use other alt accounts
for me the session indicator is always red
even if I wanted to use other accounts I can't

**Comment by Janrupf** [comment]
The above statement still applies. MultiMC is a Minecraft Launcher which requires a paid account. We don't support illegal activities in any way, shape or form, including, but not limited to MCLeaks. If you want to use this Launcher, buy the Game, its just 25 bucks. If you don't have that money, then accep that, but don't use illegal sources and then even try to get support with them.

From our side no further support will be provided.

**Comment by Frostspark1** [comment]
fine

**Comment by Frostspark1** [comment]
but like i said nothing else besides a paid account works

**Comment by Frostspark1** [comment]
and i can't pay 25 bucks because of personal reasons

**Comment by kb-1000** [comment]
> but like i said nothing else besides a paid account works
Works as intended. Stop now.

**Comment by Frostspark1** [comment]
ok ill find another solution

**Comment by Frostspark1** [comment]
> for me the session indicator is always red

but how about this?
