### ISSUE TITLE
Game keeps freezing indefinitely

### ISSUE THREAD

**Issue by ChikoritaTrainer** [MultiMC/MultiMC5#3186]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows

Summary of the issue or suggestion: My game, after anywhere from 5 minutes to several hours of play, freezes and doesn't unfreeze. The game does not close itself, I have to smite it using task manager.
----------------------------------------------

What should happen: 
------------------------------
Game SHOULD run fine.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Have my computer

2. Play minecraft

3. Keep playing until it freezes

Suspected cause:
---------------------------
Not clean computer? 
Not enough/too much Ram?
Honestly I have no clue

Logs/Screenshots:
----------------------------
https://github.com/MultiMC/MultiMC5/wiki/Log-Upload
https://paste.ee/p/hlHtG

Additional Info:
---------------------------
I've been playing on a server. 
My Ram is set from the range of 6-8.5 gigs. 
permgen is 136 megabytes
I have a computer with 12 gigs of ram.
There seems to be no consistency in when the game crashes

**Comment by Janrupf** [comment]
Can you please upload your log:
![image](https://user-images.githubusercontent.com/25827180/83912714-9bc76a80-a76e-11ea-9a4f-661757190de2.png)

**Comment by ChikoritaTrainer** [comment]
Log uploaded.

**Comment by Janrupf** [comment]
Proably its `themidnight-0.3.5.jar `. The crash is really weird, the game crashes without actually killing itself, someone is doing really nasty stuff in their mod.

**Comment by ChikoritaTrainer** [comment]
Do you mean that mod should be removed?

**Comment by phit** [comment]
no

its the thaumcraft aspect scanning, its slow af but almost done in your log, you can turn it off in the mods config

**Comment by ChikoritaTrainer** [comment]
This is a server. Does that mean other people scanning aspects is freezing my game? I haven't touched thaumcraft yet

**Comment by phit** [comment]
no, its your client doing it

**Comment by ChikoritaTrainer** [comment]
Why would my client be scanning thaumcraft things? I don't even have a thaumometer

**Comment by phit** [comment]
it has nothing to do with playing, its the mod that shows you aspects in JEI, it has to scan all items once to display that data, it runs in the background no matter if you use the mod or not

**Comment by ChikoritaTrainer** [comment]
I see. I'll turn off that config and see if it fixes it. Thank you!

**Comment by phit** [comment]
see the mods issue tracker for more info, but realistically this should fix your issue if you let it finish once after changing the config, you can see the progress in the console

https://github.com/Buuz135/Thaumic-JEI/issues/51
https://github.com/Buuz135/Thaumic-JEI/issues/38

**Comment by ChikoritaTrainer** [comment]
Where do I go to change the config?

**Comment by phit** [comment]
open `config/thaumicjei.cfg` with some text editor
change `B:alwaysRecreateAspectFromItemStackFile=true`
to `B:alwaysRecreateAspectFromItemStackFile=false`

**Comment by ChikoritaTrainer** [comment]
thank you very much! I'll be back if there's still an issue.

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
