### ISSUE TITLE
MultiMC forge issues

### ISSUE THREAD

**Issue by ccbrown20** [MultiMC/MultiMC5#3188]
System Information
-----------------------------
MultiMC version: 0.4.11-703

Operating System: Linux Mint 64

Summary of the issue or suggestion:
----------------------------------------------
When i want to create a new modpack and install a new forge no forge's come up for me to download into my minecraft modpack

What should happen:
------------------------------
When i create a modpack you need a forge to load the mods and you click on install forge and usually a bunch of forge's should show up but for me they do not.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Simply an issue that is here and won't go away

2.

3.

Suspected cause:
---------------------------
No idea

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![Screenshot at 2020-06-05 18:23:50](https://user-images.githubusercontent.com/66497641/83927068-b9d6a000-a759-11ea-901a-9b934948fcec.png)

Additional Info:
---------------------------

**Comment by QuImUfu** [comment]
0.4.11 is **very** outdated. Update.
