### ISSUE TITLE
View Worlds not showing worlds with Minecraft 1.16-pre releases

### ISSUE THREAD

**Issue by hfab** [MultiMC/MultiMC5#3189]
System Information
-----------------------------
MultiMC version: 0.6.12-develop-1453

Operating System: Windows 10 Home 1903

Summary of the issue or suggestion:
----------------------------------------------
With the Minecraft 1.16-pre2 instance selected, pressing menu item "View Worlds" opens the console window with the Worlds tab opened. The list of worlds is empty even though worlds exist and are shown in the world selection screen in Minecraft.

What should happen:
------------------------------
The existing worlds are listed.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add instance for Minecraft snapshot 1.16-pre2

2. Start the instance and create a new single player world

3. Exit Minecraft

4. In MultiMC with the, instance still selected, click "View Worlds". The world is not present in the list.

Suspected cause:
---------------------------
Change by Mojang in level.dat with the pre-release.

Logs/Screenshots:
----------------------------
Relevant line in Multi-MC-0.log (world name is E):
 W Unable to load "E" : Invalid tag type: 12

Additional Info:
---------------------------
World list is working for snapshot 20w22a. World list does not work for 1.16-pre1 and 1.16-pre2.

**Comment by peterix** [comment]
This should now be fixed.

**Comment by LDVSOFT** [comment]
Still present for me on 1.16.1 / 0.6.11.

**Comment by peterix** [comment]
Yet it is fixed.

**Comment by LDVSOFT** [comment]
Oh, it's not included in any stable release just yet? I'm sorry.
