### ISSUE TITLE
instance failing when installing forge because of inotify instances

### ISSUE THREAD

**Issue by silverhikari** [MultiMC/MultiMC5#3192]
System Information
-----------------------------
MultiMC version: 0.6.11-1344

Operating System: kubuntu 20.04

Summary of the issue or suggestion: 
----------------------------------------------
after selecting forge on version 1.3+, and doing first launch for installation, it starts doing the patching and crashes with the error in the log. which seems to be caused by too many inotify instances.

What should happen: forge should be installed and minecraft launches
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. launching minecraft after adding forge

2.

3.

Suspected cause: seems to be caused by too many inotify instances
---------------------------

Logs/Screenshots:
----------------------------
https://paste.ee/p/EJsZu

Additional Info:
---------------------------

**Comment by peterix** [comment]
Interesting.

MultiMC quite heavily uses inotify, so I think this needs some investigation

**Comment by QuImUfu** [comment]
I think something else uses up your inotify cap. Forge issues ~4 inotify_add_watch calls during installation/startup and holds 2 watches on my system. The default limit on inotify watches (ubuntu) is 8192, so its not minecrafts/forges fault. MultiMC only holds ~40 inotify watches on my system.
Could you post the output of: 
```
find /proc/*/fd -lname anon_inode:inotify 2>/dev/null | cut -d/ -f3 | xargs -I '{}' -- ps --no-headers -o '%p %U %c' -p '{}' | uniq -c | sort -nr
```
That command will list the 10 progresses with most active watches, and the amount of watches each of those holds.

**Comment by silverhikari** [comment]
here is the output of the command, and the problem seems to be fixed
