### ISSUE TITLE
Copying seeds from worlds 20w21a and newer does not work

### ISSUE THREAD

**Issue by hfab** [MultiMC/MultiMC5#3194]
Thank you for fixing the bug from my previous bug report so quickly. Unfortunately I have found another one that is similar.

System Information
-----------------------------
MultiMC version: 0.6.12-develop-1455

Operating System: Win 10 Home 1903

Summary of the issue or suggestion:
----------------------------------------------
When copying the seed from a world in the View Worlds window, the copied seed is always 0.

What should happen:
------------------------------
The actual world seed is copied.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a world in Minecraft 20w21a or newer

2. Open the View World window

3. Select a world and click "Copy Seed"

4. Past the copied seed into a text editor. This will show 0 instead of the actual seed.

Suspected cause:
---------------------------
Mojang changed seed code for solving bug https://bugs.mojang.com/browse/MC-183786

Logs/Screenshots:
----------------------------
Relevant line in the log file:
W Long NBT tag RandomSeed could not be found. Defaulting to 0

Additional Info:
---------------------------
The world was not created with a random seed.

**Comment by hfab** [comment]
Seems to be fixed in 0.16.12-develop-1502 in fix for duplicate issue GH-3229

**Comment by Forkk** [comment]
Duplicate of #3229, which is resolved.
