### ISSUE TITLE
Issue Loading Modpack

### ISSUE THREAD

**Issue by ThyZrench** [MultiMC/MultiMC5#3196]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Trying to load up a modpack I created and it is throwing errors when loading

What should happen:
------------------------------
It should load up without a problem

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Press Launch With The Modpack

2. Wait For It to Mostly Load, then sends crash report

3.

Suspected cause:
---------------------------
Unknown

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://pastebin.com/CYrPWCwP

Additional Info:
---------------------------

**Comment by Heufneutje** [comment]
You didn't upload the full log but it seems like a certain mod is missing.

**Comment by ThyZrench** [comment]
I was missing animationapi, it works now, thank you
