### ISSUE TITLE
Dropdown menu displayed on wrong monitor

### ISSUE THREAD

**Issue by MeindertKempe** [MultiMC/MultiMC5#3197]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: Arch linux (kernel 5.6.15)

window manager: bspwm 0.9.9, i3 4.18.1, fluxbox 1.3.7, sway 1.4

Qt version: 5.15.0

Summary of the issue or suggestion:
----------------------------------------------
As can be seen in the attached image, the drop down menu appears on the wrong monitor, this only happens when MultiMC is opened on my second monitor (which is set as my primary monitor).

I was able to reproduce this in bspwm, i3wm, fluxbox and sway (bspwm and i3 are tiling window managers for X11 and fluxbox is a floating window manager for X11, whereas sway is a tiling compositor for wayland).

What should happen:
------------------------------
The drop down menu should appear on the same monitor that MultiMC is opened on.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC

2. Open drop down menu

Suspected cause:
---------------------------
I have no idea, perhaps is an issue with Qt, however I have not seen this issue in the few other Qt applications that I use.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![screenshot20200610_021503-e](https://user-images.githubusercontent.com/34239778/84216080-f555cf00-aab7-11ea-98af-ca707ac3d1a1.png)

Additional Info:
---------------------------
If there is any other info I can provide I am happy to do so.

**Comment by peterix** [comment]
It's entirely up to Qt what happens here. And on linux, MultiMC doesn't contain Qt.

Can't reproduce it in my environment either (Arch, X11, KWin)

So, I have no idea what to do about it...

**Comment by Janrupf** [comment]
I had this issue on i3 with other programs before. I highly suspect i3 to have a bug causing popups to align wrongly.

**Comment by MeindertKempe** [comment]
I just noticed that this issue was still opened, however it seems that this is no longer happening for me, perhaps is was solved by a Qt update.
