### ISSUE TITLE
Session status API is broken (https://sessionserver.mojang.com  is 404)

### ISSUE THREAD

**Issue by hacker1024** [MultiMC/MultiMC5#3199]
System Information
-----------------------------
MultiMC version: 0.6.12-develop-1455

Operating System: Windows 10 (Insider build 19645)

Summary of the issue or suggestion:
----------------------------------------------
The session status in the bottom right has been red for at least a couple of days now. The session service is not actually down, though - I can connect to online servers.

On further inspection, it [seems](https://github.com/MultiMC/MultiMC5/blob/3581f5384f1270b7cc31d2cc8b610c37cd3a794e/application/widgets/ServerStatus.cpp#L68) that the session status is retrieved from https://sessionserver.mojang.com. This URL, however, now gives a 404 error.

What should happen:
------------------------------
The session status should report correctly. Hopefully, this change on Mojang's end is a bug, but if it's not, the session status indicator may have to look somewhere else for session status, or be removed.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC

2. Note that the session status is red

3. Connect to an online server and confirm that it works anyway

Suspected cause:
---------------------------
Described above.

Logs/Screenshots:
----------------------------
![image](https://user-images.githubusercontent.com/20849728/84452223-98fdd580-ac98-11ea-990e-17897669d904.png)

![image](https://user-images.githubusercontent.com/20849728/84452253-adda6900-ac98-11ea-9c0a-31629b21c5c4.png)

(Ignore the clipped text, that's just Windows being Windows when I switch monitors.)

**Comment by Zetabite** [comment]
Known for weeks. For all I know Peterix waits for Mojang to fix it. What he will do I dont know

**Comment by ThexXTURBOXx** [comment]
Why doesn't it use this API? https://status.mojang.com/check

**Comment by Janrupf** [comment]
In fact MultiMC is using https://status.mojang.com/check

This check is simply broken... it randomly shows red and green

**Comment by ThexXTURBOXx** [comment]
Oh okay, then sorry... I didn't look far enough into the code, I thought it may just look at the status code returned by https://sessionserver.mojang.com itself. Then just ignore my comment, sorry :)

**Comment by Sandalette42** [comment]
If you are done with this, you should close the issue :D

**Comment by hacker1024** [comment]
The issue hasn't been resolved yet; if the fault's Mojang's, it doesn't really matter anymore - I think we need to find a different way of checking the status if possible (or disable the broken indicator entirely).

I think it would also be fair to assume that the reason https://status.mojang.com/check is broken is due to https://sessionserver.mojang.com being down.

**Comment by kb-1000** [comment]
it is NOT down. 404 just means not found, and for a simple API there doesn't need to be any page on the server root. We could indeed try switching to looking at status codes... but that requires calling the api itself, not just the root of the server that it is running on.

**Comment by peterix** [comment]
I poked the Mojang Services team about it. They are busy with other stuff, so this will be the case for the foreseeable future.

Closing, because there's nothing I can do about this without wasting time.
