### ISSUE TITLE
Multi MC Error Code 1

### ISSUE THREAD

**Issue by ComradeRick** [MultiMC/MultiMC5#3200]
Hi, 

I am attempting to run a 1.12.2 instance on my mac. I've just gotten past the old 'liteloader libraries' error but I keep getting a code 1.

Logs are right here: https://paste.ee/p/zsbaP

Here are my mods: https://imgur.com/a/Xwlw2fE

Running mac OS yosemite, with jre 1.8.0 e251. 

Thanks in advance.

**Comment by codingJWilliams** [comment]
Thanks for sending the log but I think it expired, could you send it again without an expiry?
