### ISSUE TITLE
everything works until i enable orespawn and/or not enough items

### ISSUE THREAD

**Issue by cillian-murphy** [MultiMC/MultiMC5#3201]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: windows

Summary of the issue or suggestion:
----------------------------------------------
all mods work exept when not enough items or orespan mod is enabled. minecraft closes when loading up the game and mods with orespawn. with not enough items it doesnt open at all. orespawn works on its own. not enough items doesn't.

What should happen:
------------------------------
minecraft should run with all mods enabled

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------
i dont know

Logs/Screenshots:
----------------------------
https://paste.ee/p/XcazL

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
https://www.curseforge.com/minecraft/mc-mods/codechickencore
always make sure that you have all dependencies

**Comment by cillian-murphy** [comment]
> https://www.curseforge.com/minecraft/mc-mods/codechickencore
> always make sure that you have all dependencies

I dont understand if I was missing a dependency mod it would tell me in game. And the link is for chicken bones mod which I dont have.

**Comment by cillian-murphy** [comment]
@Zetabite ok i got codechickencore however it still crashes when loading up the game. thanks i didnt know i needed codechickencore.

https://paste.ee/p/sz2dd.

**Comment by Zetabite** [comment]
You either have not enough IDs left or were just unlucky with IDs. You need to give the item with the ID 186 of Battle Towers a new ID. try out this mod: https://www.curseforge.com/minecraft/mc-mods/notenoughids/files

**Comment by cillian-murphy** [comment]
@Zetabite ok cool how exactly do i use it. can you tell me or point me towards a guide. it didnt really explain on hte website or at least i dont understand

**Comment by Zetabite** [comment]
its just a mod. But IDs conflicts you need to resolve yourself

**Comment by Forkk** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's discord, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
