### ISSUE TITLE
When logging in it says my account isnt premium MultiMC 5

### ISSUE THREAD

**Issue by DOCNOX1** [MultiMC/MultiMC5#3202]
System Information
-----------------------------
MultiMC version: 5 

Operating System:

Summary of the issue or suggestion: tried loggin into my minecraft account i got today and it says the account isnt premium 
----------------------------------------------

What should happen: Allows me to log into and then use the mods to access servers 
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. open the multimc application 

2.launch pixelmon 

3. Try sign into my minecraft account 

4. game launches 

Suspected cause: I'm not sure 
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by kb-1000** [comment]
If the account isn't premium, that means you haven't bought minecraft.
MultiMC is not a cracked launcher.
Buy the game and it will work.

**Comment by peterix** [comment]
Well, there could be a bug or some sort of weirdness.

**Comment by cfanoulis** [comment]
If you just bought it, give it like 24hrs for it to propagate. Else try using the vanilla launcher. if it breaks there too, email mojang about this including your receipt ID / cleverbridge txid
