### ISSUE TITLE
Server resource packs

### ISSUE THREAD

**Issue by KermiDeLagyFrog** [MultiMC/MultiMC5#3203]
I went on a server and it wants me to download its texture pack (server texture pack) and I am on multi it doesn't let me but when I switch over to normal mc launcher it lets me how do I fix it so it works on multi mc too?

**Comment by codingJWilliams** [comment]
Are there any errors in your game log? Can you send them via https://pastebin.com ?

Definitely sounds like a game/mod issue rather than a MultiMC issue

**Comment by Zetabite** [comment]
MMC has a build in log upload. Just need to copy the link it gives you and paste it here

**Comment by Zetabite** [comment]
@KermiDeLagyFrog ive seen that before. From my expirience, the server did something weird in the way they install the pack and this made it now work correctly. If it would be MMC, i wouldnt be able to use Wynncraft without problems

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
