### ISSUE TITLE
[QUESTION] Is there a reason so much of the instance data is in hidden folders?

### ISSUE THREAD

**Issue by scribbler957** [MultiMC/MultiMC5#3204]
I expect it has something to do with the awful way MC itself is coded, but it took me a while to realize all the folders I needed were being hidden because they start with a period. Is this a necessary thing?
It's not game-breaking. I can use command-shift-. to toggle the hidden files, but I'm curious why it's a thing. I don't think any of the other launchers do this.

**Comment by phit** [comment]
for compatibility with mods expecting the game to be in a folder called `.minecraft`, if you dont like it you can remove the dot manually. multimc will continue to work and use the folder without the dot in the name

**Comment by scribbler957** [comment]
Hmm. That's interesting. I didn't even know mods hardcoding the directory like that was a thing. Well, asked an answered. Thanks. Do you happen to know any mods that do that, off hand?

**Comment by peterix** [comment]
Some very old ones do it... And MultiMC is for all Minecraft versions, not just the latest ones.
