### ISSUE TITLE
Closing instance window closes MultiMC main window as well

### ISSUE THREAD

**Issue by JakeMoe** [MultiMC/MultiMC5#3205]
System Information
-----------------------------
MultiMC version:
* MultiMC 5 - Version 0.6.11-1344 on lin64 - MultiMC 5

Operating System:
* Debian 10

Summary of the issue or suggestion:
----------------------------------------------
If I right-click an instance and select "Edit Instance", once I finish and click "Close" on the bottom right or the close button in the titlebar, not only does the instance window close, but MultiMC itself closes as well and needs to be reopened.

What should happen:
------------------------------
The instance window should close, leaving the main MultiMC window behind.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC
2. Right-click instance, select "Edit Instance"
3. Click "Close" button on bottom-right or close button in titlebar

Suspected cause:
---------------------------
I've used MultiMC on Linux previously, but on Gentoo and Ubuntu, and prior to MultiMC 5. Not sure if it's something Debian related, or something in the new versions, or something else, but can't find any information in the MultiMC log to tell me what's going on, so it doesn't look like it's a crash?

Logs/Screenshots:
----------------------------
https://gist.github.com/JakeMoe/25ae862d77bdbdcaf74668e754a2701e

Additional Info:
---------------------------

**Comment by comp500** [comment]
What happens if you run MultiMC from the console? Does it print anything?

**Comment by comp500** [comment]
Seems to be the same issue as https://github.com/MultiMC/MultiMC5/issues/2797 and https://github.com/JJTech0130/MultiMC5/issues/25

**Comment by JakeMoe** [comment]
For the record, looking at the other issues made me realize "Debian 10" possibly wasn't quite enough info:

    Linux MyComputerName 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

And I always forget to try running from console.  Yes, it appears to be the same issue mentioned in the Raspian support request:

    ./MultiMC: line 93:  1938 Segmentation fault      "${MMC_DIR}/bin/MultiMC" -d "${MMC_DIR}" "$@"

If I'm reading that right, they fixed it by switching from Oracle Java to OpenJDK?  I know OpenJDK is the reference implementation of Java for newer versions; is it for v8 as well?  Last I heard, Minecraft explicitly said to use Oracle's Java, as no other was supported?  Or has that changed?

If you need any more info or testing, please let me know.

**Comment by QuImUfu** [comment]
This Segmentation fault has nothing to do with Java. It is a bug in Qt, the framework MultiMC uses. Qt tries to access memory it isn't allowed to. The OS then shuts down the program.  
In many distros afterwards a GUI opens, saying something along the lines of "program xyz crashed, send a bug report, collecting data..."  
You can fix this bug by updating Qt in one way or another.

**Comment by JakeMoe** [comment]
Oh awesome, Qt again.  I don't think I've had a pleasant interaction with Qt since KDE 3.  *sigh*

Alright, so I used the Qt Online Installer to download and install Qt 5.15.0, then modified the default.conf for Qt to use that as the system default rather than the Debian-installed 5.11.3.  Qmake seems to bear out that this is happening:

    jmoe@MySystemName:~/.local/share/multimc$ qtchooser -print-env
    QT_SELECT="default"
    QTTOOLDIR="/home/jmoe/Qt/5.15.0/gcc_64/bin"
    QTLIBDIR="/home/jmoe/Qt/5.15.0/gcc_64/lib"
    jmoe@MySystemName:~/.local/share/multimc$ qmake -version
    QMake version 3.1
    Using Qt version 5.15.0 in /home/jmoe/Qt/5.15.0/gcc_64/lib

I can't see anything in the MultiMC logs to confirm it's using that Qt, so I hope it is.  However, I get the same result:

    ./MultiMC: line 93:  4355 Segmentation fault      "${MMC_DIR}/bin/MultiMC" -d "${MMC_DIR}" "$@"

**Comment by QuImUfu** [comment]
Try running `ldd bin/MultiMC` in the MultiMC directory and than use file on the path that is printed for libQt5Gui.so.5. That should give you the currently used version.  
example:
```
~/MultiMC$ ldd bin/MultiMC
	linux-vdso.so.1 (0x00007ffe371bf000)
	libMultiMC_gui.so => /home/koala/MultiMC/bin/libMultiMC_gui.so (0x00007fa303799000)
...
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007fa301e27000)
...
~/MultiMC$ file /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: symbolic link to libQt5Gui.so.5.12.4
```  
so i am using qt 5.12.4.  
To use a different version, append its location to the `LD_LIBRARY_PATH` environment variable

**Comment by JakeMoe** [comment]
Added a line to my .bashrc to export LD_LIBRARY_PATH (didn't work at first with just the Qt root folder; should have guessed the LIBRARY variable needed the lib path :-S) and relogged.  The variable has a value, and ldd on MultiMC seems to be pointing in the right direction now.  However, I still crash after right-clicking a pack, choosing "Edit Instance", then click the "Close" button.

```
jmoe@VIT-604-EIS-009:~/.local/share/multimc$ echo $LD_LIBRARY_PATH 
/home/jmoe/Qt/5.15.0/gcc_64:/home/jmoe/Qt/5.15.0/gcc_64/lib
jmoe@VIT-604-EIS-009:~/.local/share/multimc$ ldd bin/MultiMC | grep Qt5Core
	libQt5Core.so.5 => /home/jmoe/Qt/5.15.0/gcc_64/lib/libQt5Core.so.5 (0x00007f0701a88000)
jmoe@VIT-604-EIS-009:~/.local/share/multimc$ file /home/jmoe/Qt/5.15.0/gcc_64/lib/libQt5Core.so.5
/home/jmoe/Qt/5.15.0/gcc_64/lib/libQt5Core.so.5: symbolic link to libQt5Core.so.5.15.0
jmoe@VIT-604-EIS-009:~/.local/share/multimc$ file /home/jmoe/Qt/5.15.0/gcc_64/lib/libQt5Core.so.5.15.0
/home/jmoe/Qt/5.15.0/gcc_64/lib/libQt5Core.so.5.15.0: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=e361cc13d47b56e958fe55fbd0df169367cd4367, for GNU/Linux 2.6.28, not stripped
jmoe@VIT-604-EIS-009:~/.local/share/multimc$ /opt/multimc/run.sh 
MultiMC Dir: /home/jmoe/.local/share/multimc
No missing dependencies found.
    0.001 D <> Log initialized.
    0.001 D MultiMC 5, (c) 2013-2019 MultiMC Contributors
    0.001 D Version                    :  "0.6.11-1344"
    0.001 D Git commit                 :  "3ad9ea507e945709b01a5fcc51a60f7c45ad4c38"
    0.001 D Git refspec                :  "refs/heads/stable"
    0.001 D Work dir before adjustment :  "/home/jmoe/.local/share/multimc"
    0.001 D Work dir after adjustment  :  "/home/jmoe/.local/share/multimc"
    0.001 D Adjusted by                :  "Command line /home/jmoe/.local/share/multimc"
    0.001 D Binary path                :  "/home/jmoe/.local/share/multimc/bin"
    0.001 D Application root path      :  "/home/jmoe/.local/share/multimc"
...
    9.029 D Resolving dependencies
    9.029 D "Req: net.minecraft == 1.15.2" Is met.
    9.029 D "Req: org.lwjgl3 == 3.2.2" Is met.
    9.030 D Task "ComponentUpdateTask(0x1963290)" succeeded
    9.030 D Component list update/resolve task succeeded for "Primitus-0.3"
./MultiMC: line 93:  3674 Segmentation fault      "${MMC_DIR}/bin/MultiMC" -d "${MMC_DIR}" "$@"

```

**Comment by QuImUfu** [comment]
MultiMC's start script seems to replace LD_LIBRARY_PATH ... O.o
Try in terminal:  
```
$ MMC_LIBRARY_PATH=$LD_LIBRARY_PATH ./MultiMC
```

**Comment by JakeMoe** [comment]
That's worked fine, now. Hopefully Debian updates Qt sometime soon and I'll be able to revert this.  :-)  Cheers for your assistance.
