### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by MajorIceKid** [MultiMC/MultiMC5#3206]
when i try to join a server it crashes with this report 
https://paste.ee/p/oJVpl

**Comment by Worive** [comment]
Look more like an issue caused by NuclearCraft than MultiMC @MajorIceKid 

Are you sure to have the correct version?

**Comment by Forkk** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's discord, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
