### ISSUE TITLE
Offline problem

### ISSUE THREAD

**Issue by dablade11577** [MultiMC/MultiMC5#3207]
Whenever i chose a randome username on offline mode i had armor and some a tconstruct pick and whenever i got off and got on and used my actual username on offline mode i had nothing but an axe with soulbound axe on me and whenever i decided to try out if the problem was the name changing it was and if i use a random username and have a sword it pick on me whenever i change to another random username offline i no longer have anything and when i switch back i have nothing in that even though i had something before and want to know if there is a way to recober my things?

**Comment by dablade11577** [comment]
The game suddenly started to save my things again but want to know if there is a way to recover my things because in players theres only my username

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
