### ISSUE TITLE
Issues with offline play on 1.13. and up

### ISSUE THREAD

**Issue by t4st3r** [MultiMC/MultiMC5#3210]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Win10

Summary of the issue or suggestion:
----------------------------------------------
So, when i go ahead and try to create a new world or start an old one, the game freezes on 0% and does nothing. Works on original launcher. 

What should happen: 
------------------------------
A singleplayer world should be started/at least created

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. start MutiMC

2. start an instance on version 1.13 and up

3. create a new world or join an old one

Suspected cause:
---------------------------
i dont know what could cause this

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload
 for instructions on how to attach your logs.)

[latest.log](https://github.com/MultiMC/MultiMC5/files/4819345/latest.log)

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
refer to https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png for uploading logs

**Comment by Zetabite** [comment]
Cant reproduce

**Comment by t4st3r** [comment]
Sorry for the log, I didn't quite understood the instructions. For the reproduction, I also use Java SDK, not just JRE. It could also be a machine or system specific issue, but I do not know why it should happen.

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
