### ISSUE TITLE
Can't launch any modpack

### ISSUE THREAD

**Issue by BurAndBY** [MultiMC/MultiMC5#3211]
System Information
-----------------------------
MultiMC version: MultiMC5 0.6.11-1430

Operating System: Windows10

Summary of the issue or suggestion:
----------------------------------------------
Can't launch any modpack

What should happen:
------------------------------
Minecraft should open

Logs/Screenshots:
----------------------------
https://paste.ee/p/9LY7u

**Comment by Zetabite** [comment]
You're using 32-bit Java. See here for help installing the correct version.

**Comment by BurAndBY** [comment]
still Minecraft crashes (Glacial Awakening) https://paste.ee/p/gyKly

**Comment by Zetabite** [comment]
try updating Patchouli

**Comment by BurAndBY** [comment]
All works just forgot to apply it :)
![Снимок экрана (41)](https://user-images.githubusercontent.com/48630651/85835910-7c849180-b79e-11ea-9924-923633f810d2.png)
