### ISSUE TITLE
LWJGL version not changable mc 1.13+

### ISSUE THREAD

**Issue by UltraBlackLinux** [MultiMC/MultiMC5#3212]
System Information
-----------------------------
MultiMC version: 0.6.12-custom

Operating System: Linux - Manjaro

Summary of the issue or suggestion:
----------------------------------------------
I want to change the LWJGL version but its flickering back (I changed it at some Point to the newest - but not recommended)

What should happen:
------------------------------
It should change my mc 1.13+ LWJGL version

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. create mc 1.13+ instance

2. change LWJGL version to newest

3. Change it back, it'll flicker back to the newest

Suspected cause:
---------------------------
 It should change the version

Logs/Screenshots:
----------------------------
My MMC Log while changing the LWJGL version 
[log.txt](https://github.com/MultiMC/MultiMC5/files/4821211/log.txt)
: 

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
Intended afaik

**Comment by UltraBlackLinux** [comment]
works for other versions though

**Comment by Zetabite** [comment]
Ok we talked about this yesterday in the discord. For 1.13+ its hardcoded as it seems, there is a reason, but we didnt talk about it.

**Comment by UltraBlackLinux** [comment]
Geez make it downgradeable again... Super annoying. It seems to cause the random mouse jumps bug, where my mouse just jumps up.

**Comment by Zetabite** [comment]
Pretty sure it wouldnt have been downgradedable thats why its locked

**Comment by jamierocks** [comment]
> there is a reason,

Please elaborate?

**Comment by peterix** [comment]
LWJGL 3 is not ABI compatible between versions, and other versions than the one coming with the game generally didn't work. So I locked it down in order to keep people from shooting themselves in the foot.

If you still want to do this, you can. Customize the Minecraft version and make the requirement not a forced one.

That is, turn this:
```
    "requires": [
        {
            "equals": "3.2.2",
            "suggests": "3.2.2",
            "uid": "org.lwjgl3"
        }
    ],
```
Into this:
```
    "requires": [
        {
            "suggests": "3.2.2",
            "uid": "org.lwjgl3"
        }
    ],
```

**Comment by Zetabite** [comment]
IDK the reason

**Comment by peterix** [comment]
And because this is already something you can do, the request is invalid.

**Comment by peterix** [comment]
Don't expect it to work tho.

**Comment by UltraBlackLinux** [comment]
@peterix Hey, there, thanks for answering, and sorry that I am so late, the issue disappeared from my recents. 
I tried this, but the files just get changed back to their original state after trying to change the version. What is this now?
