### ISSUE TITLE
Unable to launch fabric with 1.16 - remappedJars not created correctly

### ISSUE THREAD

**Issue by 1oglop1** [MultiMC/MultiMC5#3213]
System Information
-----------------------------
MultiMC version: MultiMC 0.6.11 -1430

Operating System: Win 10 - 1909

Summary of the issue or suggestion:
----------------------------------------------
There is a problem with creating remappedJars or launching the game 1.16 with Fabric (0.8.8+build.202) mod installed.
I tried the Fabric mod with the official launcher and it worked as expected.

What should happen:
------------------------------
After installing fabric the game should launch.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC

2. Create new instance 1.6

3. Edit instance -> version -> Install Fabric 0.8.8+build.202

4. Launch the game

5. Observe the error

Suspected cause:
---------------------------
No idea

Logs/Screenshots:
----------------------------
log: https://paste.ee/p/AOoKL

Additional Info:
---------------------------
I also tried to the same steps with 1.16-rc1 and that has worked as well.
Next I took `\instances\1.16-rc1\.minecraft\.fabric\remappedJars\minecraft-1.16-rc.9\intermediary-minecraft-1.16-rc1-client.jar` and placed and renamed it into `\instances\1.16\.minecraft\.fabric\remappedJars\minecraft-1.16\intermediary-minecraft-1.16-client.jar` which has resolved the issue.

**Comment by QuImUfu** [comment]
Can not reproduce.
(lubuntu 19.10, OpenJDK 1.8.0_252, 0.6.11-1344 and 0.6.12-develop-1363)

**Comment by kosma** [comment]
I think this happens if you ran the "original" 1.16 release (with botched Realms) and you get the cached 1.16.json etc. Mojang did a silent re-release of 1.16, see here:

https://github.com/gnembon/fabric-carpet/releases

> "Since Mojang released 2 versions of 1.16 the same day due to crashing Realms (What's Realms?) Carpet 1.4.0 comes with two versions as well.
> 1.4.0 would probably work better for you, but if you have downloaded and play the initial 1.16 version, the 1.3.99 could be used."

In any case, the issue is fixed for my friends by grabbing a fresh MultiMC install. I suspect you can also remove the meta/cache/assets directories from your existing MultiMC install but I don't have a "broken" installation myself to test.

**Comment by 1oglop1** [comment]
Thanks @kosma I tried the 1.16.1 and it worked straight forward! It had to been released shortly after I logged this issue.
