### ISSUE TITLE
No sound in java minecraft 1.16

### ISSUE THREAD

**Issue by Wisdom1533** [MultiMC/MultiMC5#3216]
After I installed the 1.16 Nether update, I started playing but had no sound, I did some sleuthing to find that only the 1.16.1 instance had no sound, all other instances were fine. If anyone knows what the issue is and/or how to fix that would be great

**Comment by Drison64** [comment]
@Wisdom1533 Sound in my 1.16 instance works. Could you please attach a log?

**Comment by Zetabite** [comment]
@Wisdom1533 like this: https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
