### ISSUE TITLE
minecraft cannot start

### ISSUE THREAD

**Issue by greentea3064** [MultiMC/MultiMC5#3217]
System Information
-----------------------------
MultiMC version:5-0.6.11-1430

Operating System:win 32

Summary of the issue or suggestion:the world is inaccessible
----------------------------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
MultiMC version: 0.6.11-1430

Minecraft folder is:
C:/Users/user/Desktop/MultiMC/instances/SkyFactory4-4.1.0/minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java 版本為 1.8.0_241，使用64位元架構.

Main Class:
  

Native path:
  C:/Users/user/Desktop/MultiMC/instances/SkyFactory4-4.1.0/natives

Libraries:

Native libraries:

Mods:
  [📁] 1.12 (folder)
  [✔️] Advancement_Book-1.12-1.0.3
  [✔️] ae2stuff-0.7.0.4-mc1.12.2
  [✔️] AnimalCrops-1.12.2-0.2.0
  [✔️] Apotheosis-1.12.2-1.10.5
  [✔️] AppleCore-mc1.12.2-3.2.0
  [✔️] AppleSkin-mc1.12-1.0.9
  [✔️] appliedenergistics2-rv6-stable-7
  [✔️] Aroma1997Core-1.12.2-2.0.0.2.b165
  [✔️] AromaBackup-1.12.2-3.0.0.0.b125
  [✔️] astralsorcery-1.12.2-1.10.19
  [✔️] BarrelsDrumsStorageAndMore-0.0.24
  [✔️] base-1.12.2-3.11.0
  [✔️] Baubles-1.12-1.5.2
  [✔️] bdlib-1.14.3.12-mc1.12.2
  [✔️] bedpatch-2.2-1.12.2
  [✔️] BetterAdvancements-1.12.2-0.1.0.77
  [✔️] BiblioCraft[v2.4.5][MC1.12.2]
  [✔️] BNBGamingCore-1.12.2-0.11.0
  [✔️] BNBGamingLib-1.12.2-2.17.6
  [✔️] bonsaitrees-1.1.3-b156
  [✔️] Bookshelf-1.12.2-2.3.581
  [✔️] BouncyCreepers-0.0.4
  [✔️] BuildingGadgets-2.6.8
  [✔️] Caliper-1.12.2-1.1.45
  [✔️] CalmDownZombieGuy-1.12.2-1.0.0
  [✔️] CarryOn MC1.12.2 v1.12.2
  [✔️] Ceramics-1.12-1.3.7
  [✔️] Chargers-1.12.2-1.2.0.4
  [✔️] ChineseWorkshop-1.12.2_1.2.6
  [✔️] Chisel-MC1.12.2-0.2.1.35
  [✔️] chiselsandbits-14.32
  [✔️] ClickMachine-1.12.2-1.2.0
  [✔️] ClientTweaks_1.12.2-3.1.11
  [✔️] Clumps-3.1.2
  [✔️] CodeChickenLib-1.12.2-3.2.3.357-universal
  [✔️] CoFHCore-1.12.2-4.6.3.27-universal
  [✔️] CoFHWorld-1.12.2-1.3.1.7-universal
  [✔️] ColouredTooltips-1.12.2-1.0.7
  [✔️] CommonCapabilities-1.12.2-2.1.0
  [✔️] compactmachines3-1.12.2-3.0.18-b278
  [✔️] CompactStorage-3.1-12
  [✔️] ComPatchedStorage-1.12.2-1.6.0
  [✔️] conarm-1.12.2-1.2.4
  [✔️] ContentTweaker-1.12.2-4.9.1
  [✔️] Controlling-3.0.6
  [✔️] CookingForBlockheads_1.12.2-6.4.71
  [✔️] CraftTweaker2-1.12-4.1.18
  [✔️] CTM-MC1.12.2-0.3.3.22
  [✔️] Cucumber-1.12.2-1.1.3
  [✔️] culinaryconstruct-1.3.3
  [✔️] CustomMainMenu-MC1.12.2-2.0.9
  [✔️] Cyclic-1.12.2-1.19.14
  [✔️] CyclopsCore-1.12.2-1.0.6
  [✔️] DarkUtils-1.12.2-1.8.226
  [✔️] deepmoblearning-1.12.2-2.5.2-universal
  [✔️] DefaultOptions_1.12.2-9.2.8
  [✔️] DimensionStages-1.12.2-2.0.23
  [✔️] DragonMurder-1.12.2-1.0.1
  [✔️] ElevatorMod-1.12.2-1.4.2
  [✔️] EnchantmentDescriptions-1.12.2-1.1.15
  [✔️] EnderCore-1.12.2-0.5.57
  [✔️] endercrop-1.12.2-1.6.0
  [✔️] EnderStorage-1.12.2-2.4.6.137-universal
  [✔️] enderutilities-1.12.2-0.7.12
  [✔️] ExtendedCrafting-1.12.2-1.5.4
  [✔️] ExtraCells-1.12.2-2.6.2a
  [✔️] FancyBlockParticles-1.12.x-2.4.1
  [✔️] FarmingForBlockheads_1.12.2-3.1.26
  [✔️] FastFurnace-1.12.2-1.3.1
  [✔️] FastWorkbench-1.12.2-1.7.2
  [✔️] FenceOverhaul-1.3.4
  [✔️] findme-1.12.2-1.1.0-8
  [✔️] fluxnetworks-1.12.2-3.0.19-21
  [✔️] foamfix-0.10.5-1.12.2
  [✔️] Forgelin-1.8.2
  [✔️] ForgeMultipart-1.12.2-2.6.1.81-universal
  [✔️] ForgivingVoid_1.12.2-1.0.23
  [✔️] GameStages-1.12.2-2.0.115
  [✔️] Guide-API-1.12-2.1.8-63
  [✔️] Headcrumbs-1.12.2-2.0.5.17
  [✔️] HorsePower-1.12.2-2.6.4.74
  [✔️] HuntingDimension-1.12.2-1.0.38
  [✔️] HurtAnimationRemover-1.12.2-1.0.0
  [✔️] Hwyla-1.8.26-B41_1.12.2
  [✔️] HydroGel-1.12.2-1.1.0
  [✔️] iChunUtil-1.12.2-7.1.4
  [✔️] incontrol-1.12-3.9.10
  [✔️] industrialforegoing-1.12.2-1.12.12-236
  [✔️] Inspirations-1.12.2-0.2.6
  [✔️] IntegratedDynamics-1.12.2-1.0.8
  [✔️] IntegratedTunnels-1.12.2-1.6.7
  [✔️] inventorysorter-1.12.2-1.13.3+57
  [✔️] IronJetpacks-1.12-2-1.1.0
  [✔️] ItemStages-1.12.2-2.0.50
  [✔️] jei_1.12.2-4.15.0.289
  [✔️] journeymap-1.12.2-5.5.5
  [✔️] KleeSlabs_1.12.2-5.4.11
  [✔️] LimitlessStructureBlocks-1.12.2-1.1.0
  [✔️] LoadingScreens-1.12.2-0.3.1
  [✔️] lostcities-1.12-2.0.17
  [✔️] malisiscore-1.12.2-6.5.1
  [✔️] malisisdoors-1.12.2-7.3.0
  [✔️] Mantle-1.12-1.3.3.55
  [✔️] MatterOverdrive-1.12.2-0.7.1.0-universal
  [✔️] mcjtylib-1.12-3.1.1
  [✔️] MCMultiPart-2.5.3
  [✔️] Mekanism-1.12.2-9.8.0.381
  [✔️] MekanismGenerators-1.12.2-9.8.0.381
  [📁] memory_repo (folder)
  [✔️] Mercurius-1.12.2
  [✔️] MobGrindingUtils-0.3.13
  [✔️] MobStages-1.12.2-2.0.13
  [✔️] modtweaker-4.0.17
  [✔️] MoreBuckets-1.12.2-1.0.4
  [✔️] More-Cauldrons-1.4.5
  [✔️] moreoverlays-1.14-mc1.12.2
  [✔️] Morpheus-1.12.2-3.5.106
  [✔️] MouseTweaks-2.10-mc1.12.2
  [✔️] mpbasic-1.12.2-1.4.11
  [✔️] MPUtils-1.12.2-1.5.7
  [✔️] MTLib-3.0.6
  [✔️] mystcraft-1.12.2-0.13.7.04
  [✔️] MysticalAgradditions-1.12.2-1.3.2
  [✔️] MysticalAgriculture-1.12.2-1.7.5
  [✔️] Neat 1.4-17
  [✔️] NuclearCraft-2.17c-1.12.2
  [✔️] ocxnetdriver-1.0.3-b17
  [✔️] ogdragon-1.12.2-0.1.4
  [✔️] OpenComputers-MC1.12.2-1.7.4.153
  [✔️] OreExcavation-1.4.137
  [✔️] Parabox-1.12.2-2.0.0
  [✔️] Patchouli-1.0-19
  [✔️] PickleTweaks-1.12.2-2.1.3
  [✔️] PipeMaster-1.0.2-b8
  [✔️] Placebo-1.12.2-1.6.0
  [✔️] PlaneFix-1.12.2-1.0.0
  [✔️] PortalGun-1.12.2-7.1.0
  [✔️] practicallogistics2-1.12.2-3.0.8-11
  [✔️] Prestige-1.12.2-1.1.58
  [✔️] PrimitiveCrafting MC1.12.2 v1.3.5
  [✔️] ProjectE-1.12.2-PE1.4.1
  [✔️] ProportionalDestructionParticles-1.12.2-1.2.4
  [✔️] rangedpumps-0.5
  [✔️] realfilingcabinet-1.12-0.2.0.19
  [✔️] reauth-3.6.0
  [✔️] RecipeStages-1.1.3
  [✔️] RedstoneFlux-1.12-2.1.0.6-universal
  [✔️] ResourceHogs-1.12.2-1.0.12
  [✔️] ResourceLoader-MC1.12.1-1.5.3
  [✔️] rftoolspower-1.12-1.1.2
  [✔️] rustic-1.0.15
  [✔️] simplegenerators-1.12.2-2.0.20.2
  [✔️] SimpleStorageNetwork-1.12.2-1.7.8
  [✔️] SkyBonsais-1.0.1
  [✔️] SkyGrid-1.1.7
  [✔️] SkyOrchards-0.0.12
  [✔️] Slab_Machines-1.0.6
  [✔️] SlimyBoyos-1.0.0
  [✔️] SmoothFont-mc1.12.2-2.1
  [✔️] Snad-1.12.1-1.7.09.16a
  [✔️] sonarcore-1.12.2-5.0.19-20
  [✔️] SqueezerPatch-1.12.2-1.0.0
  [✔️] statues-1.12.X-0.8.9
  [✔️] stg-1.12.2-1.2.3
  [✔️] StuffASockInIt-1.12.2-1.1.30
  [✔️] supersoundmuffler-1.12.2-1.0.2.10
  [✔️] Surge-1.12.2-2.0.77
  [✔️] Sync-1.12.2-7.1.0
  [✔️] TallGates-1.12.2-1.0.0.1
  [✔️] TConstruct-1.12.2-2.12.0.157
  [✔️] TelePastries-0.3.4
  [✔️] tesla-core-lib-1.12.2-1.0.15
  [✔️] ThermalDynamics-1.12.2-2.5.5.21-universal
  [✔️] ThermalFoundation-1.12.2-2.6.3.27-universal
  [✔️] ThermalInnovation-1.12.2-0.3.3.12-universal
  [✔️] TinkersComplement-1.12.2-0.4.2
  [✔️] TinkerToolLeveling-1.12.2-1.1.0
  [✔️] tinyprogressions-1.12.2-3.3.34-Release
  [✔️] TipTheScales-1.12.2-1.0.4
  [✔️] Toast Control-1.12.2-1.8.1
  [✔️] togetherforever-1.12.2-1.0.12-22
  [✔️] tombstone-3.5.2-1.12
  [✔️] Topography-1.12.2-1.10.1
  [✔️] torchmaster_1.12.2-1.7.1.74
  [✔️] Translocators-1.12.2-2.5.2.81-universal
  [✔️] TreeGrowingSimulator2017-1.0.1
  [✔️] Triumph-1.12.2-3.17.0
  [✔️] twilightforest-1.12.2-3.8.689-universal
  [✔️] Twitchcrumbs_1.12.2-3.0.4
  [✔️] Uppers-0.0.6
  [✔️] valkyrielib-1.12.2-2.0.20.1
  [✔️] ViesCraft-1.12.2-5.9.13
  [✔️] Waddles-1.12.2-0.6.0
  [✔️] WailaStages-1.12.2-2.0.24
  [✔️] walljump-1.12.2-1.2.3
  [✔️] Wawla-1.12.2-2.5.273
  [✔️] weirdinggadget-1.12.2-2.1.16-universal
  [✔️] witherCrumbs-1.12.2-0.11
  [✔️] WorldBook-1.0.0
  [✔️] worldutils-1.12.2-0.4.2
  [✔️] XCPatch-1.12.2-1.0.1
  [✔️] XL-Food-Mod-1.12.2-1.9.1
  [✔️] xnet-1.12-1.7.6
  [✔️] YNot-0.2.3
  [✔️] yoyos_1.12.2-1.3.3.25
  [✔️] zenstages-0.4.1-19

Params:
  

Window size: 854 x 480

Failed to reconstruct Minecraft assets.
Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx7096m, -Duser.language=en]

Minecraft 處理序 ID: 8616

Using onesix launcher.

Not enough arguments.
org.multimc.NotFoundException
	at org.multimc.ParamBucket.all(ParamBucket.java:43)
	at org.multimc.onesix.OneSixLauncher.processParams(OneSixLauncher.java:55)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:212)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
程序已退出，代碼:-1。

實例更新失敗，因為:metadata中指定了空白的.jar檔，中斷執行。

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
Either your instance is corrupt or you never ran it in online mode

**Comment by greentea3064** [comment]
> 您的實例已損壞，或者您從未在在線模式下運行它

what should I do?

**Comment by Zetabite** [comment]
Run it in online mode once

**Comment by greentea3064** [comment]
> 一次以在線模式運行

I tried it,still can not

**Comment by Zetabite** [comment]
try making an new instance with the same modpack

**Comment by greentea3064** [comment]
> 嘗試使用相同的modpack製作新實例

Can I still have the original map file?

**Comment by Zetabite** [comment]
If you dont delete the broken instance you should be able by copying it over

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
