### ISSUE TITLE
[Feature Request] Toggleable Narrator In Settings

### ISSUE THREAD

**Issue by UltraBlackLinux** [MultiMC/MultiMC5#3218]
Summary of the issue or suggestion:
----------------------------------------------
So this adds a little checkbox in the local Instance settings and the Global settings that allows the user to enable/disable the narrator (or even change the bind without mods?)
Why? Cause Its quite annoying if the Instance starts up and I get a Giant warning that A voice synthesizer isnt found, but its also damn annoying to hit b accidently when sprint jumping.
Id love to see this!
Thanks for Multimc :)

**Comment by Forkk** [comment]
This is not possible to implement without modding the game. MultiMC does not and will not install any mods "by default", so this unfortunately can't be implemented.
