### ISSUE TITLE
Windows continuously wanting to install a app from the Microsoft Store

### ISSUE THREAD

**Issue by ChaoticDucc** [MultiMC/MultiMC5#3219]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: Windows 10 Pro Version 1909

Summary of the issue or suggestion:
----------------------------------------------
Whenever I launch the .exe file, Windows puts up a message saying that "This action requires an app from the (Microsoft) Store. Would you like to open the store?". Clicking "Yes" or "No" does nothing and simply opens MultiMC. No store, no wedsite no nothing. It dosn't make the program unusable, its just really annoying, especially because I wanted to switch to MultiMC as my main launcher. 

What should happen:
------------------------------
The window above shouldnt be there

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
Explained above. May only affect me.

Suspected cause:
---------------------------
Probably Windows being weird

Logs/Screenshots:
----------------------------
![Anmerkung 2020-06-27 215225](https://user-images.githubusercontent.com/63168091/85930948-a8983380-b8c0-11ea-8fb9-f2bec559af2a.png)
(Sorry about it being in German)

Additional Info:
---------------------------
N/A

**Comment by Zetabite** [comment]
Yeah probably windows. Cause it doesnt make sense

**Comment by peterix** [comment]
MultiMC does nothing with any store of any description. Can't really help you with this.
