### ISSUE TITLE
Liteloader library url "org.ow2.asm:asm-all:5.0.3" needs https

### ISSUE THREAD

**Issue by Drison64** [MultiMC/MultiMC5#3221]
System Information
-----------------------------
MultiMC version:
0.6.11-1430

Operating System:
Windows 10

Summary of the issue or suggestion:
----------------------------------------------
When getting libraries for Liteloader, one of the URLs needs HTTPS.

What should happen:
------------------------------
Liteloader should install.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create 1.8.9 instance

2. Add Liteloader

3. Launch

Suspected cause:
---------------------------
The website requires HTTPS

Logs/Screenshots:
----------------------------
https://pastebin.com/jsAGRTqg

Additional Info:
---------------------------

**Comment by Drison64** [comment]
Think noone noticed the mention. I have created a pull request in MultiMC/meta fixing this problem (hopefully).

**Comment by peterix** [comment]
Fixed!
