### ISSUE TITLE
LiteLoader 1.12.2: ClassCastException

### ISSUE THREAD

**Issue by WesJD** [MultiMC/MultiMC5#3222]
System Information
-----------------------------
MultiMC version: 0.6.11-1370

Operating System: osx64

Summary of the issue or suggestion: 
----------------------------------------------
Launching the game causes a ClassCastException when using LiteLoader on 1.12.2

What should happen: 
------------------------------
The game should launch

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a new 1.12.2 instance
2. Edit Instance > Install LiteLoader
3. Attempt to start the game

Suspected cause: 
---------------------------
Recently switched to Java 11

Logs/Screenshots:
----------------------------
https://paste.ee/p/TFD8u

**Comment by Zetabite** [comment]
Could it be that you no longer have java 8 installed? You need java 8 for modded mc, so install it again and select it in MMC
