### ISSUE TITLE
Game crashes when going through second nether portal on 1.14.4

### ISSUE THREAD

**Issue by bloxanne123** [MultiMC/MultiMC5#3228]
System Information
-----------------------------
MultiMC version:0.6.7-1375

Operating System: Windows 10 Pro

Summary of the issue or suggestion:
----------------------------------------------
When I go through my nether portal to a village, the game crashes. My first nether portal is fine, but the one that is a couple hundred blocks away in the Nether, or a thousand blocks away in the Overworld, that one causes the game to crash.

What should happen:
------------------------------
It should crash during the Loading Terrain screen when transitioning to Overworld from Nether.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
Not possible.

Suspected cause:
---------------------------
Transition from Nether to Overworld chunk loading fails.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/0Fe0Q

Additional Info:
---------------------------
I run 1.14.4 with Optifine and Forge.

**Comment by Zetabite** [comment]
1. What are those weird folders in your modlist
2. Your MMC is long outdated. Update it (we are at 0.6.11 or so already)

**Comment by Chew** [comment]
1 looks like they tried to put the Minecraft code or whatever in the mods folder, not sure why

**Comment by bloxanne123** [comment]
Zetabite, which folders? Also, how do I update it? I dont have admin access on my PC so I can't install Java, which I think is the reason I can't run minecraft above 1.14.4 and the latest MultiMC version. 

> 1 looks like they tried to put the Minecraft code or whatever in the mods folder, not sure why

What do you mean?

**Comment by Zetabite** [comment]
those: https://i.imgur.com/qhwI1QQ.png
just remake the modpack and make sure you have updated mmc.
There is a way to get java without admin, but not sure how that would work, so someone else answer that one for me

**Comment by bloxanne123** [comment]
How do I remake the modpack and update mmc? When i install for the official build, I get? I also dont know what the folder name is. I am a noob at this, and I dont have admin access. My dad just installed Eclipse and whatever else is needed to run it. That might work, right?

**Comment by kb-1000** [comment]
Eclipse? What?

**Comment by bloxanne123** [comment]
Idk my dad installed JDK for Eclipse, would it work at all? I installed the latest one, but when I try to launch minecraft, https://paste.ee/p/qFSpD happens. It didnt happen with the version of MMC that I put in my issue box.

**Comment by kb-1000** [comment]
you didnt actually setup java then. "" means not configured

**Comment by AverageComet250** [comment]
Download the exe file for windows and point multimc to the java.exe in the java folder after running it once. That is the java that the official launcher uses and will work with multimc.
