### ISSUE TITLE
Copy Seed button doesn't work

### ISSUE THREAD

**Issue by bestsoft100** [MultiMC/MultiMC5#3229]
Since Minecraft 1.16 seeds are now saved in WorldGenSettings.seed,
previously at randomSeed in the level.dat file.
Pressing the button in a newer world copies 0 instead of the seed.

MultiMC version: MultiMC 0.6.12-develop-1457

**Comment by BrisingrAerowing** [comment]
I was just about to report this myself. As a workaround, I'm using [NBT Explorer](https://github.com/jaquadro/NBTExplorer/releases) to yoink the seed out of the save data. A bit more manual work, but whatever.
