### ISSUE TITLE
MultiMC crashes in Fabric 1.14.4 (Mods: Optifine+OptiFabric, Fabric, FabricAPI)

### ISSUE THREAD

**Issue by HatHelo** [MultiMC/MultiMC5#3230]
Hey!
I tried to start Minecraft up with replay mod, and I found a cool way on YouTube using MultiMC. The issue is that it crashes after I try to launch it with any mod (I didn't even get to try out if it works with the Replay Mod). So starting it up with only fabric works, but nothing else.
Mods I'm using: OptiFine_1.14.4_HD_U_F5, optifabric-0.7.1, fabric-api-0.14.0+build.258-1.14, fabric-installer-0.6.1.45.
MultiMC Fabric version: 0.6.1+build.165
Java version:  jre1.8.0_251
Error log: https://paste.ubuntu.com/p/m6y88jZHjD/
In theory, everything is in the right version.
Thank you for the answers in advance!

**Comment by Drison64** [comment]
@HatHelo Hello,
Please try removing `fabric-installer-0.6.1.45` from your instance and install fabric through `Install fabric` button in Version tab.

https://puu.sh/G4FbG/772863d49b.png
https://puu.sh/G4Fc8/beaa549177.png

**Comment by Zetabite** [comment]
that should fix it yeah

**Comment by Drison64** [comment]
@HatHelo 
Hello, is the issue solved?
If so, please close this issue.

**Comment by HatHelo** [comment]
It did. Thank you!
