### ISSUE TITLE
MultiMC crashing whenever I load up Salhack as one of the mods

### ISSUE THREAD

**Issue by Lockelyy** [MultiMC/MultiMC5#3231]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------

Whenever I load up MultiMC with Salhack as one of the mods, MultiMC crashes. The thing is it was working fine up until now and I made 0 changes to any of the mods and it decides to act up. The issue is only with Salhack, whenever I disable Salhack MultiMC launches perfectly with no problems. 

What should happen:
------------------------------

It should work properly and run Salhack.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Run MultiMC 

2. Run the 1.12.2 instance with Salhack

3. MultiMC crashes and the console shows the error

Suspected cause:
---------------------------

I have no idea

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

https://paste.ee/p/09JQr

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
Idk, could be discord rich presence missing

**Comment by Drison64** [comment]
Oh, yeah. It might be.
@Lockelyy Do you have Discord installed on your PC?

**Comment by Lockelyy** [comment]
Yeah I do, I just created a new instance and it worked fine. I'm pretty sure it just had something to do with DRP because I was screwing around with it.
