### ISSUE TITLE
Another process exited with code 1

### ISSUE THREAD

**Issue by Booglay** [MultiMC/MultiMC5#3232]
when launching an instance it loads for a few seconds then crashes

System Information
-----------------------------
MultiMC version: 5

Operating System: windows 7

Logs/Screenshots:
----------------------------
https://paste.ee/p/Pm9KA

**Comment by Zetabite** [comment]
submit the crashreport like this: https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by Drison64** [comment]
@Booglay 

`(Line 1270) [13:18:13] [Client thread/INFO] [Pulsar-tconstruct]: Skipping Pulse theoneprobeIntegration; missing dependency: theoneprobe`
It seems you are missing a dependency `The One Probe`.

`(Line 1145) [13:17:43] [Client thread/WARN] [FML]: Zip file ._BetterFps-1.4.8.jar failed to read properly, it will be ignored`
The .jar file name looks wrong, the `.` might cause some problems shrug. (This appears many times in the log)

**Comment by Booglay** [comment]
> @Booglay
> 
> `(Line 1270) [13:18:13] [Client thread/INFO] [Pulsar-tconstruct]: Skipping Pulse theoneprobeIntegration; missing dependency: theoneprobe`
> It seems you are missing a dependency `The One Probe`.
> 
> `(Line 1145) [13:17:43] [Client thread/WARN] [FML]: Zip file ._BetterFps-1.4.8.jar failed to read properly, it will be ignored`
> The .jar file name looks wrong, the `.` might cause some problems shrug. (This appears many times in the log)

i already reinstalled the client and tried everything, whats the fix?

**Comment by Drison64** [comment]
@Booglay 
Can you send me the modpack so i can try to find a solution to this problem?

**Comment by Booglay** [comment]
> @Booglay
> Can you send me the modpack so i can try to find a solution to this problem?

The issue isn't modpack specific it happens on every modpack but the modpack is mc eternal

**Comment by Zetabite** [comment]
I would argue that BetterFPS seems broken, for whatever reason forge is trying to extract it and fails dramaticly

**Comment by Janrupf** [comment]
I guess that there is some OpenGL abusage going on. Try updating your graphics driver if possible, and/or remove graphics related mods one by one to identify which mod is blowing it up. You might also want to make sure that minecraft is running on the dedicated GPU

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, you may re-open it.
