### ISSUE TITLE
Session icon in the status bar reports false information

### ISSUE THREAD

**Issue by danielnaaman** [MultiMC/MultiMC5#3233]
### Technical Information
MultiMC Version: MultiMC 5 (0.6.11)
Operating System: Manjaro Stable (Latest)

### Summary of Issue
The status section shows the session servers as offline even though everything works smoothly for the past weeks and Mojang reported that all servers are back to normal ages ago, no substantial downtime reported since..

### What Should Happen
The icon should either be positive, or at least provide any information for why is it appearing as offline. Since it's clearly online.

### Steps to Reproduce
1. Enter MultiMC launcher
2. Look at the status icons in the bottom part of the screen
3. Verify that the session servers icon appears offline

### Suspected Cause
No clue, perhaps it's static and not live.

### Screenshots
![image](https://user-images.githubusercontent.com/16944217/86916150-d173c080-c12b-11ea-9d90-a09ca27f0b6e.png)

### Additional Information
I tried refreshing using the refresh button, and it's like this for the past months, even when I was still using Windows. I'm pretty sure it's like this for everyone.

**Comment by phit** [comment]
please use the search before making new issues https://github.com/MultiMC/MultiMC5/issues?q=is%3Aissue+is%3Aopen+session
https://github.com/MultiMC/MultiMC5/issues/3199

**Comment by danielnaaman** [comment]
> please use the search before making new issues https://github.com/MultiMC/MultiMC5/issues?q=is%3Aissue+is%3Aopen+session
> #3199

Already did, just went through it too briefly I guess. Thanks for pointing that out.

Closed.
