### ISSUE TITLE
(1.16.1) Disabling a dimension mod in Multimc will break other dimension mods

### ISSUE THREAD

**Issue by TelepathicGrunt** [MultiMC/MultiMC5#3238]
To recreate the issue, download The Bumblezone, Astromine, and Terrestia into Multimc
https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-fabric
https://www.curseforge.com/minecraft/mc-mods/astromine-fabric
https://www.curseforge.com/minecraft/mc-mods/terrestria

Create a world and throw an Enderpearl at a Bee Nest to enter Bumblezone's dimension. The dimension should look normal and full of beehive like blocks.

Now disable Astromine in Multimc and restart the game. Create a new world and try entering The Bumblezone. The dimension should be completely screwed up with random biomes being used that shouldn't be in the dimension.

It seem like Minecraft will still read the datapack of disabled mods which causes massive issues with dimensions probably due to the registry now pointing to a mod's content that doesn't exist. 1.16.1 really made this hectic lmao

The dimension when it is working properly:
![image](https://user-images.githubusercontent.com/40846040/86984979-0b5dba80-c15e-11ea-941f-169eeb65890f.png)

The dimension when disabling a different dimension mod:
![image](https://user-images.githubusercontent.com/40846040/86985002-1ca6c700-c15e-11ea-888d-694942b32113.png)
![image](https://user-images.githubusercontent.com/40846040/86985031-292b1f80-c15e-11ea-86fc-b4c7ff49c75d.png)

Hopefully this can be fixed soon! The issue and pics were given to me by a user of my mod. We narrowed down the issue to multimc so hopefully it is easily reproducible

**Comment by phit** [comment]
MultiMC is a game launcher and has nothing to do with what happens in game, the "disable" in MultiMC just renames the mod so it's no longer loaded. If those mods don't handle removal well, that's a mod issue and has nothing to do with MultiMC

**Comment by TelepathicGrunt** [comment]
Well, it's not the mods' issue as they are making their dimension the way that Minecraft specifies them to (by json files now in 1.16) so it is Minecraft that takes the json files from the mod's jars and makes the dimensions. 

So either Minecraft is being too aggressive with finding Json files for dimensions or Fabric is still loading in the mod's json files despite the mod extension being changed. I'll kick this issue down the road to Fabric and see if they can figure out where the issue lies
