### ISSUE TITLE
SS111's ID Resolver integration

### ISSUE THREAD

**Issue by DeathHammer000** [MultiMC/MultiMC5#324]
I originally posted issue #322 where I requested a multi-log viewer and a world-loading stopper. I added an idea concerning the integration of SS111's ID Resolver (for 1.6.X clients only), but was asked to move to a new issue.

Link: https://github.com/SS111/Minecraft-ID-Resolver

This would include the automatic location of config directories and NEI item ID dumps (which are used to fix ID conflicts); MultiMC5 would use the program to print all conflicts that occur in the config directory and a configurable number of subdirectories.

There should also be a manual process of selecting config files to omit from the ID conflict resolution process (some mods use "base block IDs", making it almost impossible to change IDs for these mods in an effective fashion). A NEI dump contains ALL IDs, so that mods with no configs or "abnormal" configs can still be used.

**Comment by peterix** [comment]
I think ID resolvers are obsolete now -- and that's a good thing.  Sorry for not acting upon this issue, but I'm just going to close it now.
