### ISSUE TITLE
Custom command won't work on Linux

### ISSUE THREAD

**Issue by uiytt** [MultiMC/MultiMC5#3242]
System Information
-----------------------------
MultiMC version: 0.6.11-1344

Operating System: Ubuntu 20.4

Summary of the issue: 
----------------------------------------------
When adding a linux custom command in pre-launch, the command is never run.
Ex : echo TEST > /home/test.txt 

What should happen:
------------------------------
 TEST should appear in a file test.txt in /home/

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Enable custom command

2. Add a linux command

3. See the problem

**Comment by QuImUfu** [comment]
You are not trying to execute a executable but a bash command.  
Try `sh -c "echo TEST > /home/test.txt"`.  
Easiest is writing a simple bash script.

**Comment by peterix** [comment]
MultiMC is not a shell. A command is a single executable or script.

No parameters.

And it has to transparently pass through standard input and output if it's a wrapper command.

**Comment by QuImUfu** [comment]
> No parameters for pre and post.  

I tested `sh -c "echo TEST > /home/test.txt"` and it works. Parameters (if you don't mean something different by parameters) do work.  
Quoting however is kinda wired and qt-specific. Single quotes (') do nothing. Double quotes (") work for creating arguments with spaces. Triple double quotes (""") become the double quote character. ([source1](https://code.woboq.org/qt5/qtbase/src/corelib/io/qprocess.cpp.html#_ZL22parseCombinedArgStringRK7QString), [source2](https://code.woboq.org/qt5/qtbase/src/corelib/io/qprocess.cpp.html#2327))
