### ISSUE TITLE
optifine for 1.15.2

### ISSUE THREAD

**Issue by andsim** [MultiMC/MultiMC5#3243]
try to install newest optifine for mc 1.15.2 useally i put in mod for this but it crash it
**System Information**
_MultiMC version_: 5

_Operating System_: windows 10

log: 
---
https://paste.ee/p/fcOv9

**Comment by Drison64** [comment]
@andsim 
Hello, you imported a .jar file you installed.
You need to export mod .jar file from that downloaded file then import it.

Recently i found a way that suits me well.
Create a new folder anywhere on your computer (for example Desktop, lets refer to this folder as root).
Go to `https://mcversions.net`, find version you want to use (in this case 1.15.2) and download the client.jar file.
Go to `https://optifine.net/downloads`, find latest version of OF for the MC version you want to use (in this case 1.15.2).
Create a new folder called `versions` in the "root" folder.
In that folder `versions` create another folder named by the version you want to use (in this case 1.15.2).
Move the file you downloaded from mcversions.net to the 1.15.2 folder and rename it to 1.15.2.jar
Move the file you downloaded from optifne.net to "root" folder.
Open the optifine.jar file and change the path to the "root" folder.
Click extract.
Import that exported .jar file to your instance.
Enjoy the game!

**Comment by Zetabite** [comment]
Thats not a good way to do it.
Make 1.15.2 instance and install fabric. Download Optifine, OptiFabric and FabricAPI. Install those as mods in that instance. Done

**Comment by andsim** [comment]
have to be forge 1.15.2

**Comment by Zetabite** [comment]
If you want forge (though i would recommend switiching to fabric for vanilla instances as sodium etc have greater performance improvements than optifine) you will need OptiForge to make Optifine work.

**Comment by andsim** [comment]
still not accept by that reason, i was hoping with other mod on forge. had to be easier way

**Comment by andsim** [comment]
like other version,  i just put in mod folder. not this one it had to be harder

**Comment by andsim** [comment]
ok get addon mods.. it working ty

**Comment by Zetabite** [comment]
This no longer works due to how OptiFine changes, you need a loader mod if you want that work
