### ISSUE TITLE
screen is off set when full screen on versions 1.12.2 & earlier

### ISSUE THREAD

**Issue by Le-Kat** [MultiMC/MultiMC5#3244]
System Information
-----------------------------
MultiMC version: tested both 0.6.11-1430 and 0.6.12.-develop-1457

Operating System: Windows 10 home 1903

Summary of the issue or suggestion:
----------------------------------------------
When playing minecraft 1.12.2 (vanilla or modded) the window will start half-way on the right side of the screen, and when turning on full screen, the screen is incredibly zoomed in (to the point of not being able to see many of the options) and when setting the GUI scale to small, everything appears to be centered on the right edge of the screen. This applies to gameplay as well, in which the crossbar is centered on the bottom-right of the screen, & the hot bar isn't visible.

What should happen:
------------------------------
The game should be centered on the actual center of the screen, instead of the bottom righ.

Steps to reproduce the issue:
-------------------------------------------------------------
1. run a 1.12.2 minecraft instance (using vanilla in my case)

2. when game loads, go into options -> video settings menu

3. turn full screen on

Suspected cause:
---------------------------
game is probably assuming I have a bigger screen than I actually do?

Logs/Screenshots:
----------------------------
game appears half-way off screen when booting up
![1](https://user-images.githubusercontent.com/37410281/87632730-7f352f80-c729-11ea-8aa9-be905e237188.png)

GUI scale auto & turning on fullscreen
![2](https://user-images.githubusercontent.com/37410281/87632733-80665c80-c729-11ea-9229-ca3453f1b3f9.png)

gameplay with GUI scale auto
![3](https://user-images.githubusercontent.com/37410281/87632735-80fef300-c729-11ea-8b28-9cbbccfa355e.png)

switching to GUI scale small
![4](https://user-images.githubusercontent.com/37410281/87632736-81978980-c729-11ea-8c9f-498c88fa304e.png)

cursur is centered in the bottom right
![5](https://user-images.githubusercontent.com/37410281/87632740-81978980-c729-11ea-8ecd-14c9c771ac63.png)

so is the inventory
![6](https://user-images.githubusercontent.com/37410281/87632746-82c8b680-c729-11ea-90c2-58a86781de91.png)

Additional Info:
---------------------------
I did not get this to occur in minecraft 1.13.2, 1.14.4, 1.15.2, 1.16.1. This bug happened in minecraft 1.12.2, 1.11.2, 1.10.2, 1.9.4, 1.8.9, & 1.7.10. I stopped testing after 1.17.10, I also only ever tested the last release of each major version.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you still need help with this try the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc). This is some known scaling issue related to your DPI, Google "minecraft display scaling off center" and you can probably find a guide how to fix it.

**Comment by nvrsbr** [comment]
This an issue with MultiMC, this only happens to me using 1.12.2 through MultiMC.

**Comment by HVATK** [comment]
Did you ever solve this? Having the same issue (as you were - only in MultiMC).

**Comment by HarmlessTurtle1** [comment]
Go to the javaw.exe in file explorer -> right-click -> "Properties" -> "Compatibility" tab -> "Change high DPI settings" -> set the checkbox for "Override high DPI scaling behaviour"
