### ISSUE TITLE
Could not reserve enough space for 4188160KB object heap

### ISSUE THREAD

**Issue by GeneralStorm101** [MultiMC/MultiMC5#3246]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------
unable to play because of so called 4188160KB object heap

What should happen:
------------------------------
modpack should at least open

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. I don't know I was just fiddling around with the memory settings

2.

3.

Suspected cause:
---------------------------
?

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Drison64** [comment]
@GeneralStorm101 
Hello, please attach logs.
https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by GeneralStorm101** [comment]
https://paste.ee/p/Wpf3S

**Comment by GeneralStorm101** [comment]
I just figured out the solution. I just needed to download java again. simple. https://www.java.com/en/download/manual.jsp

**Comment by Drison64** [comment]
@GeneralStorm101 
Since this issue is resolved, please close this issue.
