### ISSUE TITLE
Whilst attempting to load a modpack, Minecraft exits with code 255

### ISSUE THREAD

**Issue by QuintBrit** [MultiMC/MultiMC5#3248]
System Information
-----------------------------
MultiMC version: 0.6.11 - 1370

Operating System: OSX 10.11 (El Capitan)

Summary of the issue or suggestion:
----------------------------------------------
I have repeatedly launched the modpack (PO3), and it loads until about 6 minutes in, when Minecraft exits with code 255. I have tested the java before and after launching, and it works. I have restarted my computer and tried again, and the same problem occurs. I have successfully launched an FTB pack from FTB Legacy as well as another imported Curse pack.

What should happen:
------------------------------
Minecraft should finish launching.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download Java 8 and configure correctly.

2. Download PO3 from Curse.

2. Import as instance.

3. Launch.

Suspected cause:
---------------------------
Unknown.

Logs/Screenshots:
----------------------------
https://paste.ee/p/cvyFZ 
Additional Info:
---------------------------

**Comment by QuintBrit** [comment]
After downloading a bunch more packs, most of which loaded correctly, I tried the FTB pack again and it didn't work (exact same error), and tried the pack in question again, with the same result. Conclusion: ???

**Comment by Janrupf** [comment]
Looks like EnderIO tries to load textures of a size minecraft can't handle, maybe you are running out of GPU memory? Try installing OptiFine

**Comment by QuintBrit** [comment]
IT LOADED, I owe you my firstborn. Thank you so much!
