### ISSUE TITLE
1.7.10 keeps crashing

### ISSUE THREAD

**Issue by Useydess** [MultiMC/MultiMC5#3249]
[New Paste 1.txt](https://github.com/MultiMC/MultiMC5/files/4951209/New.Paste.1.txt)

System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by QuImUfu** [comment]
This *seems* to be an issue with lwjgl 2 and Mac OS Catalina.  
(If that's the case, the simplest solution would be to use a sane OS that does not break user space.^^)  
Does vanilla minecraft 1.7.10  (i.e. without any mods) work?

**Comment by Useydess** [comment]
okay so this is not the problem i made this without placing the crash log

here's a new one that does have the crash 
https://github.com/MultiMC/MultiMC5/issues/3250 this is whats really happening
