### ISSUE TITLE
Graphical symlink helpers

### ISSUE THREAD

**Issue by Artoria2e5** [MultiMC/MultiMC5#3252]
System Information
-----------------------------
* MultiMC version: 0.6.11
* Operating System: Windows 10.0.19041.388

Summary of the issue or suggestion:
----------------------------------------------
A lot of people end up wanting to use symlinks for stuff like sharing saves, assets, and libraries. For saves this allow for testing different clients, while for assets/libraries this reduces duplicate data.

It makes sense to have an option when importing a version to links these stuff to another location, for example a central store.

What should happen:
------------------------------
Symlinks should be used on Unix-like systems. It's literally the `symlink()` sys call.

Since Windows requires either admin privs or developer mode for symlinks, junctions (mount points) should be used instead. Restrictions include:
* No crossing file systems. This shouldn't be an issue in a usual configuration.
* Directories only. We are only proposing this for directories anyways.
* Obsecure API. Use reparselib.

Symlinks can be handled transparently after they are created.

**Comment by peterix** [comment]
Not gonna haoppen.
