### ISSUE TITLE
cant launch any modpack

### ISSUE THREAD

**Issue by Hethos20** [MultiMC/MultiMC5#3254]
System Information
-----------------------------
MultiMC version: 0.6.11-1344

Operating System: Linux mint 20

Summary of the issue or suggestion:
----------------------------------------------
Crash before game starts

What should happen:
------------------------------
It crashes before the game starts

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. install any modpack

2. launch the modpack

Logs/Screenshots:
----------------------------
https://paste.ee/p/dNjRi

**Comment by minecraft8997** [comment]
Look at this line (419) Caused by: java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper.
https://askubuntu.com/questions/695560/assistive-technology-not-found-awterror

**Comment by Hethos20** [comment]
Ok I actually fixed it by downloading the jre from oracle's website and removing the jre from linux mint's repository
