### ISSUE TITLE
Allowing symlinked mods to be displayed / disabled?

### ISSUE THREAD

**Issue by Sturmlilie** [MultiMC/MultiMC5#3256]
System Information
-----------------------------
MultiMC version:
0.6.12 (ref e7f373496ed51d30d87eb1b75410d4f02f0412ec)

Operating System:
Linux

Summary of the issue or suggestion:
----------------------------------------------
I would like to be able to see, and enable / disable fabric mods that I have symbolically linked into the mods folder from my dev environment, just as any other entries.

What should happen:
------------------------------
See above.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Symlink mods into mod/ folder with `ln -s`

2. They don't show up (fabric loader still picks them up correctly though)

3.

Suspected cause:
---------------------------
Symlinks get ignored when the file tree is walked.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
I compiled MultiMC with this one-liner:
```
diff --git a/api/logic/minecraft/mod/ModFolderModel.cpp b/api/logic/minecraft/mod/ModFolderModel.cpp
index 59ccaaba..fbe81fb9 100644
--- a/api/logic/minecraft/mod/ModFolderModel.cpp
+++ b/api/logic/minecraft/mod/ModFolderModel.cpp
@@ -29,7 +29,7 @@
 ModFolderModel::ModFolderModel(const QString &dir) : QAbstractListModel(), m_dir(dir)
 {
     FS::ensureFolderPathExists(m_dir.absolutePath());
-    m_dir.setFilter(QDir::Readable | QDir::NoDotAndDotDot | QDir::Files | QDir::Dirs | QDir::NoSymLinks);
+    m_dir.setFilter(QDir::Readable | QDir::NoDotAndDotDot | QDir::Files | QDir::Dirs);
     m_dir.setSorting(QDir::Name | QDir::IgnoreCase | QDir::LocaleAware);
     m_watcher = new QFileSystemWatcher(this);
     connect(m_watcher, SIGNAL(directoryChanged(QString)), this, SLOT(directoryChanged(QString)));

```

And so far it works exactly as I would like. However I suspect there's a good reason why symlinks were being filtered out in the first place. Would it maybe be possible to allow symlinks under a special config option or cmdline parameter? This really helps **a lot** in my dev workflow.

**Comment by peterix** [comment]
Symlinks make instances not shareable and in general, this will not be allowed.

**Comment by redcreeper14385** [comment]
I mean, the point of this addition is to help devs, it's not really related to making shareable instances.

**Comment by Minenash** [comment]
For me symlinked mods are loaded, but don't show up in the `Mods:` list. I get that it's not a great thing that symlinks are used, but rn that list displays incorrect information.

**Comment by Sturmlilie** [comment]
@Minenash you need to apply the diff I posted above in order for them to show up.
