### ISSUE TITLE
multimc -d folder deletes all files in the folder

### ISSUE THREAD

**Issue by josephtheengineer** [MultiMC/MultiMC5#3257]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: Linux 5.7.8 (NixOS)

Summary of the issue or suggestion:
----------------------------------------------
`multimc -d folder` is listed as --dir but actually means --delete.

What should happen:
------------------------------
```` > multimc -d folder
0.000 D <> Log initialized.
0.002 D <> Error: folder 'folder' contains misc files.
< Multimc exit >
````

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. `mkdir folder`

2. `touch folder/file.txt`

3. `multimc -d folder`

4. `ls folder # file.txt is deleted`

**Comment by Janrupf** [comment]
Eh? You know... it changes the installation home of MultiMC, which MultiMC then cleans up to get it ready for working. No `--delete` at all, it is `--dir`. There could maybe be a notice that it cleans the folder, but its 100% intended.

**Comment by peterix** [comment]
There is no such functionality anywhere in the codebase.

Where did you get this version of MultiMC, who made it, and how can I contact them?

**Comment by peterix** [comment]
This is most likely also a license violation.

**Comment by Zetabite** [comment]
https://github.com/jD91mZM2/nixpkgs/blob/master/pkgs/games/multimc/default.nix its not a licsense violation, they redistribute mmc, but they add some stuff on nix site

**Comment by peterix** [comment]
Looks like a build from source to me... Maybe the wrapper messes things up?

**Comment by Zetabite** [comment]
I dont think it messes up, it does stuff intentionally, but then again, i am not a nix user

**Comment by josephtheengineer** [comment]
Oh wops, I should have checked that first. Thought it was a builtin option. Seems it's added with a wrapper.
`wrapProgram $out/bin/multimc --add-flags "-d \$HOME/.multimc/" --set GAME_LIBRARY_PATH /run/opengl-driver/lib:${libpath} --prefix PATH : ${jdk}/bin/:${xorg.xrandr}/bin/`
