### ISSUE TITLE
My skin doesnt work

### ISSUE THREAD

**Issue by DerangedMZ** [MultiMC/MultiMC5#3259]
Before I started using MultiMC, my original Minecraft java launcher didn't work for 3 years and I had no idea why. I've tried everything until my friend told me about MultiMC. Suddenly I'm able to play but my skin nor anyone else's skins load. Everyone just looks like Steve or Alex. It's not the biggest deal to me to have skin but I just want to have a good design on my look. All of the servers on the MultiMC launcher are check-marked except session. The session server has been marked with an X ever since I installed the launcher. Would that have anything to do with it?

**Comment by Zetabite** [comment]
The session has nothing to do with that, as it works, its just Mojangs status server for that is offline, so it appears offline. What i think is the issue, is that MC has problems with downloading skins with IPv6. Add this to your Java launch options: `-Djava.net.preferIPv4Stack=true`

**Comment by DerangedMZ** [comment]
Holy shit! It worked 👍 Thanks so much, dude!
