### ISSUE TITLE
Fails to launch after installing Forge (1.14.4)

### ISSUE THREAD

**Issue by meowmeoe** [MultiMC/MultiMC5#3261]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
After installing Forge to 1.14.4, Minecraft fails to launch with the error message below.

What should happen:
------------------------------
Minecraft should launch with Forge installed (for minimap/schematic/inventory mods, though none are installed yet)

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.  Get 1.14.4 instance

2.  Click install Forge (Either the starred version or the latest version, neither work)

3.  Run 1.14.4

Suspected cause:
---------------------------
Unknown

Logs/Screenshots:
----------------------------
https://paste.ee/p/qV2QX

Additional Info:
---------------------------
I've tried with/without OptiFine, since that was already installed (using the "add to minecraft.jar" method)

**Comment by Zetabite** [comment]
If you use forge, you need to put optifine in the "Loader Mods" tab
