### ISSUE TITLE
Modded 1.15.2 Crashing Upon Launch

### ISSUE THREAD

**Issue by Lkbrunson1** [MultiMC/MultiMC5#3262]
System Information
-----------------------------
MultiMC version: 5

Operating System: Windows

Summary of the issue or suggestion:
----------------------------------------------
I keep trying to launch Minecraft, and once it nearly finishes, it crashes.  I am trying to play with mods installed on my buddy's server but can't figure out how to stop it from crashing.  I had it working relatively smoothly all of yesterday, but after restarting my PC it can no longer run it without crashing at launch.

What should happen:
------------------------------
Hopefully should not crash.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Install MultiMC 5

2.install mods for 1.15.2 and forge 31.2.31

3.attempt launch

Suspected cause:
---------------------------
I've tried removing individual mods and allocating more RAM, but am pretty inexperienced, so I'm not sure what more I could try.

Logs/Screenshots:
----------------------------
https://paste.ee/p/ss9JO

Additional Info:
---------------------------
Thank you in advance to whomever can help.

**Comment by Janrupf** [comment]
Try deleting the ``config`` folder from the instance.

**Comment by Lkbrunson1** [comment]
WOW that was fast.  It worked.  Thanks a lot for the help so soon.
