### ISSUE TITLE
Minecraft 1.6.4 doesn't launch

### ISSUE THREAD

**Issue by yu767485** [MultiMC/MultiMC5#3263]
System Information
MultiMC version: 0.6.11-1430

Operating System: windows 10

Summary of the issue or suggestion:
When I try to launch the game, it crashes a few seconds after starting, even without any mods.

What should happen:
Minecraft should launch successfully, with mods as well

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
?

Logs/Screenshots:
----------------------------
https://paste.ee/p/5gj4G

Additional Info:
I tried reinstalling, but it didn't work

**Comment by Janrupf** [comment]
Try running it without the jarmods, as in remove them one-by-one and see which one is causing the issue. The log doesn't tell anything about the actual cause.

**Comment by yu767485** [comment]
I took out all of the mods, and it still didn't work. By the way, what do you mean the crash doesn't mean anything regarding the issue?

**Comment by Janrupf** [comment]
> By the way, what do you mean the crash doesn't mean anything regarding the issue?
Well, the log does indicate the crash, it just doesn't tell why. Please upload a log without the jar mods enabled so we can investigate further

**Comment by yu767485** [comment]
I think I fixed it. I think the problem was that the system did not have permission to access one of the folder for some reason and after I moved the folder and replaced it with a new one, it worked.

**Comment by Zetabite** [comment]
NTFS corruption, lovely.
