### ISSUE TITLE
[Feature request] Support the install button on CurseForge (twitch: URLs)

### ISSUE THREAD

**Issue by laurinneff** [MultiMC/MultiMC5#3265]
The install button on CurseForge opens a URL like this: twitch://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons/download-client/3017933  
MultiMC should support converting that into a format it can understand and add a protocol handler for twitch: URLs. This would make modpack installation even easier than it already is

**Comment by kb-1000** [comment]
MultiMC used to support such URLs if you replace the twitch:// with https://.
But that didn't work for everyone and was thus removed.

**Comment by peterix** [comment]
Yeah. It was a constant source of problems because people trying to use it got blocked by cloudflare all the time.
