### ISSUE TITLE
MC fails to launch (1.10.2) Exit code -1

### ISSUE THREAD

**Issue by peterodavies27atgmailcom** [MultiMC/MultiMC5#3266]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
MC does not launch and the log says: "Exiting with -1
Process exited with code -1."

What should happen:
------------------------------
MC should launch.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create New Instance

2. Install Forge

3. Add Mods

4. Press Launch

Suspected cause:
---------------------------
Maybe my Java?

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://pastebin.com/gp7TnbZe

Additional Info:
---------------------------
I don't know much about technical stuff.

**Comment by TehcJS** [comment]
# Simple Answer
---
This looks like a launcher bug.
# Long Answer
---
It appears that launchwrapper failed to load due to an invalid cast (AppClassLoader -> URLClassLoader).

**Comment by TehcJS** [comment]
It could be your version of Java. I recommend using Java 8 instead of Java 11 since it runs better and has a lower chance of weird errors like this one.

**Comment by Janrupf** [comment]
It is indeed Java 11 causing the issue

**Comment by peterix** [comment]
Yep. Use Java 8.

**Comment by BeansBeefBroccoli** [comment]
thank you
