### ISSUE TITLE
1.12.2 Modpacks keep crashing when i try to load up a world

### ISSUE THREAD

**Issue by BananaLord12** [MultiMC/MultiMC5#3267]
System Information
-----------------------------
MultiMC version:0.6.11-1430 on win32

Operating System:WIndows 10 64-bit

Summary of the issue or suggestion: On most of the 1.12 modpacks, my world keeps freezing and crashing
----------------------------------------------

What should happen:
------------------------------
it should load up the world

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Open MultiMC

2.Launch instance (for example Madpack 4)

3.load world

Suspected cause:
---------------------------
Primarily Java

Logs/Screenshots:
----------------------------
https://pastebin.com/UjHRVW4b

Additional Info:
---------------------------
These crashes have been happening when a new Java update got released and since then i am forced to use the official minecraft launcher to play with any mods, Multi MC will only allow me to play with 1.13 and beyond

**Comment by peterix** [comment]
Then don't use this broken version of Java.

See:
https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs
