### ISSUE TITLE
MultiMc Instances issue, can anyone help?

### ISSUE THREAD

**Issue by Justinhedrick1** [MultiMC/MultiMC5#3269]
MultiMC version: 0.6.11-1430

Operating System: win32

So lately i have been trying to play with different modpacks on multi MC one's I've made and not made, but it's been closing
and i don't know the issue
What should happen:
------------------------------
It should start normally, but instead it exits with code 1.

I don't know what the cause is, but this has been happening a lot lately.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

MultiMC version: 0.6.11-1430

Minecraft folder is:
C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/instances/Giny Boruto/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_241/bin/javaw.exe

Java is version 1.8.0_241, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/instances/Giny Boruto/natives

Libraries:
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar
  C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Mods:
  [✔️] [1.7.10]DamageIndicatorsMod-3.2.0
  [✔️] 1.7.10-MB_Battlegear2-Bullseye-1.0.8.3
  [✔️] Armourers-Workshop-1.7.10-0.48.2
  [✔️] Baubles-1.7.10-1.0.1.10
  [✔️] BetterBuildersWands-0.8.1-1.7.10r92+aec06c3
  [✔️] BetterFps-1.0.1
  [✔️] Better-Furnaces-Mod-1.7.10
  [✔️] BiblioCraft[v1.11.5][MC1.7.10]
  [✔️] Carpenter's Blocks v3.3.8.1 - MC 1.7.10
  [✔️] Chisel-2.9.5.11
  [✔️] ChunkAnimator-MC1.7.10-1.0.1
  [✔️] CodeChickenCore-1.7.10-1.0.7.47-universal - Copy
  [✔️] CodeChickenLib-1.7.10-1.1.3.138-universal
  [✔️] CustomNPCs_1.7.10d
  [✔️] extrautilities-1.2.12
  [✔️] fairylights-1.4.0-1.7.10
  [✔️] FreezeCam-Mod-1.7.10
  [✔️] GraveStone+Mod+0.7.10.3
  [✔️] Hide Names-1.7.10-1.1.8
  [✔️] immibis-core-59.1.1
  [✔️] immibis-microblocks-59.1.0
  [✔️] ironchest-1.7.10-6.0.62.742-universal
  [✔️] IvToolkit-1.2.1
  [✔️] journeymap-1.7.10-5.1.4p1-unlimited
  [✔️] Morpheus-1.7.10-1.6.21
  [✔️] MrCrayfishFurnitureModv3.4.7(1.7.10)
  [✔️] Naruto-Anime-Mod_V0.9.17_Beta_1.7.10-1.0(10)
  [✔️] NarutoDojutsuMod2
  [✔️] NBTEdit_1.7.10
  [✔️] netherportalfix-mc1.7.10-1.1.0
  [✔️] NoFog-1.7.10b1-1.0
  [✔️] NotEnoughItems-1.7.10-1.0.5.120-universal
  [✔️] OptiFine_1.7.10_HD_D1
  [✔️] Pam's+HarvestCraft+1.7.10Lb
  [✔️] placeableitems-2.0.1
  [✔️] secretroomsmod-1.7.10-4.7.1.413
  [✔️] Waila-1.5.10_1.7.10
  [✔️] WailaHarvestability-mc1.7.10-1.1.6
  [✔️] worldedit-forge-mc1.7.10-6.1.1-dist

Params:
  --username  --version MultiMC5 --gameDir C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/instances/Giny Boruto/.minecraft --assetsDir C:/Users/justi/Downloads/mmc-stable-win32/MultiMC/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType  --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms4608m, -Xmx16316m, -Duser.language=en]

Minecraft process ID: 16336

Error: Could not find or load main class org.multimc.EntryPoint
Process exited with code 1.
Clipboard copy at: 04 Aug 2020 14:28:29 -0700

Additional Info:
---------------------------

**Comment by peterix** [comment]
Grab the current release of MultiMC and copy it over your existing copy. Looks like you are missing one of the files.

**Comment by kb-1000** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
