### ISSUE TITLE
MultiMC lets me play on a server for 10 seconds to 2 minutes and then it crashes entirely.

### ISSUE THREAD

**Issue by Lingay6969** [MultiMC/MultiMC5#3272]
System Information
-----------------------------
MultiMC version: 0.6.11 

Operating System: MacOS Catalina 10.15.5

Summary of the issue or suggestion:
----------------------------------------------
 
MultiMC is working fine except after 10 seconds to 2 minutes of me playing on my friends server, the application crashes and i get the error code 255. This issue just started out of nowhere. I played for 4 hours without a crash before this started happening.
I know that to is not an issue with the modpack (Valhelsia 3) and i have checked that my Java is up to date at version 8.

What should happen: I should be able to play for longer
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. press launch

2. boot up

3. attempt to play for any length of time

Suspected cause:
---------------------------
 i have no idea. the only other thing is that "Session" has a red X, but that hasn't affected playability before.
Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

https://paste.ee/p/TF8gB

Additional Info:
---------------------------
The server is 3rd party and not LAN, so I know its not a wifi issue. Hope someone can help! Thanks! <3

**Comment by phit** [comment]
update Immersive Engineering

**Comment by Lingay6969** [comment]
> update Immersive Engineering

I did this, but then it told me i needed to update forge to 32.0.99 and after i did that, it says that Toast Control has failed to load correctly.. am i about to fall down a rabbit hole?

**Comment by Zetabite** [comment]
Welcome to forge mod development 1.16. In the few newer releases of forge for 1.16, much stuff has changed so that developers now need to change stuff too. that could take time

**Comment by phit** [comment]
yup, there's no stable for Forge on 1.16 yet, so lots of breaking changes

**Comment by Lingay6969** [comment]
okay.. this is all very confusing because we made this server barely over 24 hours ago and now its suddenly not working even though everything matches... server side and user side.

I guess my noob is showing

**Comment by Zetabite** [comment]
making a modpack on it currently is just a waste of time

**Comment by Lingay6969** [comment]
I didn't make one, we are using the new Valhelsia edition.

**Comment by Zetabite** [comment]
who knows what can break on runtime
