### ISSUE TITLE
MultiMC possibly incorrectly loading files from Curseforge packs

### ISSUE THREAD

**Issue by Razorfin8** [MultiMC/MultiMC5#3273]
System Information
-----------------------------
MultiMC version:0.6.11-1344

Operating System:PopOS 20.04 LTS 64-bit

Summary of the issue or suggestion:
----------------------------------------------
When loading MC Eternal 1.3.7.1 (also happened on 1.3.7) the FTB Quest book is missing textures. I've posted this to MCEternal's Github however, it seems another user is also having this issue when using MultiMC on a Linux distro.  However, when they used the Twitch launcher on windows, they did not have this issue.  It seems as this issue is related to how MultiMC loads packs downloaded from curse forge. I am also running Optifine, but other users on the Modded Minecraft discord said they had no issues with Optifine running.  I am not running shaders and all settings except dynamic lights are default. 

On a side note, I really don't know if this is a bug, an oversight or just a problem with running multimc on linux.  Posting it here but I can make a new post in the bug tracker if needed.

What should happen:
------------------------------
All textures load appropriately 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Have Linux (another user used Arch, I'm using PopOS) 

2. Have MultiMC

3. Run MC Eternal on MultiMC on Linux

4. Open Quest book

5. Having missing textures

Suspected cause:
---------------------------
Somehow MultiMC is loading textures incorrectly

Logs/Screenshots:
----------------------------
I attached one screenshot of one page of the quest book, but there are missing textures on every page. Let me know if you need more.
[//]: https://paste.ee/p/S67vZ
![asdf](https://user-images.githubusercontent.com/2932987/89516191-fbe98580-d78c-11ea-8862-2b115685746f.png)

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
what method did you use to install the pack?

**Comment by Razorfin8** [comment]
Download from curse forge then install from zip

**Comment by peterix** [comment]
MultiMC is not loading textures.
