### ISSUE TITLE
[Feature Request] use a template .minecraft folder

### ISSUE THREAD

**Issue by AverageComet250** [MultiMC/MultiMC5#3274]
I usually change quite a few of default settings whenever I create a new instance in multimc. These settings are always the same, so why I can't I just use a .minecraft folder with no worlds and no servers, but with all my usual settings for fov, controls and graphics and other things, if there was a way to specify a default template or a way to specify one at instance creation, it would save me running the instance once and then swapping the created one with my template.

**Comment by peterix** [comment]
You can have a template instance and copy it.

**Comment by peterix** [comment]
Aside from that, noted, like 4 years ago. It's on the pile.

**Comment by AverageComet250** [comment]
Reason I put this out is because not everyone wants to do that every single time they create a new instance
