### ISSUE TITLE
Unable to use update button, when info bar for windows reads I do not have latest version.

### ISSUE THREAD

**Issue by zediious** [MultiMC/MultiMC5#3278]

**Comment by WhiteSammy** [comment]
lol, the update notification is from almost a year ago and is in regards to version 6.7. The build is now on 6.11, they just never removed it. I was gonna make a comment about updating the notification but it's not important.

**Comment by zediious** [comment]
Okay, that explains it ahaha. I was having a different issue an I wanted to make sure it was updated fully. Thanks!

**Comment by Zetabite** [comment]
> lol, the update notification is from almost a year ago and is in regards to version 6.7. The build is now on 6.11, they just never removed it. I was gonna make a comment about updating the notification but it's not important.

Its not an update notification, its a blog entry that recommended to for older version users, there was just not another entry after that, as the forge one has been deleted
