### ISSUE TITLE
Crash when trying to run last combat test with Fabric Loader

### ISSUE THREAD

**Issue by mondis1337** [MultiMC/MultiMC5#3279]
-----------------------------
MultiMC version: 0.6.12-develop-1459

Operating system: Windows 10 v2004 Build: 19041.388

I can't run last Minecraft Combat test (1.16_combat-0) with Fabric Loader
----------------------------------------------
The game should be playable.
------------------------------
Screenshots:
![crash](https://user-images.githubusercontent.com/55624582/89718171-5de8fb80-d9d6-11ea-9533-5d62036b89b5.png)
![crash2](https://user-images.githubusercontent.com/55624582/89718178-6f320800-d9d6-11ea-93db-f0de21db6507.png)
![crash3](https://user-images.githubusercontent.com/55624582/89718185-7c4ef700-d9d6-11ea-9793-305f31f2d6ff.png)

**Comment by peterix** [comment]
Well, duh. That's not supposed to work.
