### ISSUE TITLE
Rendering issue in Edit Instance window

### ISSUE THREAD

**Issue by Tanath** [MultiMC/MultiMC5#3282]
System Information
-----------------------------
MultiMC version: `multimc-git 0.6.11.r1.g21ac860e-1`

Operating System: Manjaro Linux

Summary of the issue or suggestion:
----------------------------------------------
The Edit Instance window renders as shown in the screenshot. 

What should happen:
------------------------------
Normal rendering, of course.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. MMC -> Edit Instance for any instance.

2. Make sure the Edit Instance window is 819 pixels tall or more. If less, it goes away.

Suspected cause:
---------------------------
Not sure. 

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![image](https://user-images.githubusercontent.com/3394708/89753059-d0281180-daa4-11ea-979a-e3e66afa9cdc.png)

Additional Info:
---------------------------
It's not the window manager. I've tried reloading and switching window managers, which has no effect. I've tried rebooting, no change. Everything's up to date.

If I mouse over a button, the button's rendering goes back to normal until mouse out, then it goes back to glitchy.

`inxi -Gx`:
```
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] 
           vendor: Micro-Star MSI driver: amdgpu v: kernel bus ID: 09:00.0 
           Display: x11 server: X.Org 1.20.8 driver: amdgpu resolution: 1: 1680x1050~60Hz 2: 1920x1080~60Hz 
           OpenGL: renderer: Radeon RX 570 Series (POLARIS10 DRM 3.38.0 5.8.0-2-MANJARO LLVM 10.0.1) v: 4.6 Mesa 20.1.5 
           direct render: Yes 
```

**Comment by peterix** [comment]
Hmm... That is most likely a broken theme and I can't really do anything about it. Everything in that panel is just stock Qt controls.

**Comment by Tanath** [comment]
I forgot to mention, it doesn't happen in any other qt (or other) program. Changing my themes has no effect.

**Comment by OpenDeveloper16** [comment]
I ran into this before... its a GPU issue with Linux... do you have the open source or propriety drivers installed?

**Comment by Tanath** [comment]
It's in Additional Info (open source):

`inxi -Gxz`:
```
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] 
           vendor: Micro-Star MSI driver: amdgpu v: kernel bus ID: 09:00.0 
           Display: x11 server: X.Org 1.20.8 driver: amdgpu resolution: 1: 1680x1050~60Hz 2: 1920x1080~60Hz 
           OpenGL: renderer: Radeon RX 570 Series (POLARIS10 DRM 3.38.0 5.8.0-2-MANJARO LLVM 10.0.1) v: 4.6 Mesa 20.1.5 
           direct render: Yes ```

**Comment by OpenDeveloper16** [comment]
Sorry, can't read lol... I am going to look into this.

**Comment by Tanath** [comment]
I heard kernel 5.8 had bugs with amdgpu so I tested the latest LTS, `5.4.58-1-MANJARO` but no change, except some of the green lines are blue.

**Comment by Tanath** [comment]
My nvme drive with my OS died, I had to reinstall on another drive, and I'm not able to reproduce it now so I'm closing this.
