### ISSUE TITLE
Minecraft is a gray screen

### ISSUE THREAD

**Issue by hyperak** [MultiMC/MultiMC5#3285]
System Information
-----------------------------
MultiMC version: 0.6.11-custom

Operating System: Void Linux glibc x86_64

Summary of the issue or suggestion: 
----------------------------------------------
I found `dwm`, my window manager, had issues with Java applications (see the issue title), which [could be fixed](https://wiki.archlinux.org/index.php/Dwm#Fixing_misbehaving_Java_applications) by setting `_JAVA_AWT_WM_NONREPARENTING=1` and `AWT_TOOLKIT=MToolkit` in your environment, or by running `wmname compiz` to make Java think it was running a window manager in its list requiring the same fix needed by dwm. Needless to say, I did that, logging in and out and all.

I also tried:
* running wmname and not,
* different versions from the first Minecraft version ever to relatively recent ones such as 1.12.2
* self compiled versions, the official Void repository version and the generic binaries
* deleting the entire MultiMC local data folder (~/.multimc) several times
* maybe something else I don't remember

But *none of it* worked... well, except Minecraft 4K.

Later on, I found out the issue isn't with dwm, because I tried running Minecraft under fluxbox, also to no avail...

Nobody, not even other Void users, have had the issue persist after setting up their environment.

What should happen:
------------------------------
 With those environment variables, Minecraft should work just fine.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Have a Linux system with OpenJDK 8.

2. Run MultiMC.

3. Minecraft is a gray screen!

Suspected cause:
---------------------------
Nobody knows. It's all a mystery.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

I set `env` as a prelaunch command so you can see for yourself that my environment is indeed setup properly for would-be success.

https://paste.ee/p/lV57D

Also some images of things in action.

![1.5.2 effectively gray screening :(](https://u.dieg.io/5697c1d7-cf70-4827-8755-e5c0f686d6f0/1.5.2.png)

![Minecraft 4K, not gray screening...](https://u.dieg.io/1c1bc3b0-9ba2-4ccd-8468-73a2f2b38463/4k.png)

Additional Info:
---------------------------
Once again, I'm running OpenJDK 8.

**Comment by peterix** [comment]
Make sure you have `xrandr` installed.

**Comment by hyperak** [comment]
Yay! That fixed it. Thanks @peterix

I guess it should be a included as a dependency in repositories... maybe even put it in the documentation?
