### ISSUE TITLE
Error code 255 on launch

### ISSUE THREAD

**Issue by bakingpanckae** [MultiMC/MultiMC5#3288]
System Information
-----------------------------
MultiMC version:  0.6.11-1344

Operating System: Linux

Summary of the issue or suggestion:
----------------------------------------------
I followed this guide https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine to install optifine for 1.16.1, I made sure to follow it exactly to install OptiFine. Upon launching I'm getting an error code 255

https://pastebin.com/6zuNBr3N

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Here's my optifine.Optifine.json text file https://pastebin.com/kmJprkim

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
https://youtu.be/CRDRv7wLCP0 do the same just for 1.16

**Comment by Janrupf** [comment]
You are using Java 11, install and select Java 8.

**Comment by OpenDeveloper16** [comment]
To install java 8 use the following;
Ubuntu / Debian: sudo apt-get install openjdk-8-jre
Arch / Manjaro: sudo pacman -Syu jre8-openjdk
Fedora: sudo dnf install java-1.8.0-openjdk.x86_64
If you need a different distro tell me!
