### ISSUE TITLE
1.16.2 Will not launch not even in vanilla

### ISSUE THREAD

**Issue by RubberDuckyDJ** [MultiMC/MultiMC5#3289]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System:
Windows 10
Summary of the issue or suggestion:
----------------------------------------------
Minecraft 1.16.2 does launch

What should happen:
------------------------------
The game should launch

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a 1.16.2 instance

2. Run It

Suspected cause:
---------------------------
I have no clue what could have caused this

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
Log File was not created
MultiMC version: 0.6.11-1430

Minecraft folder is:
C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/instances/1.16.21/.minecraft

Java path is:
C:/Program Files/AdoptOpenJDK/jdk-8.0.232.09-openj9/bin/javaw.exe

Java is version 1.8.0_232, using 64-bit architecture.

Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/instances/1.16.21/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/com/mojang/authlib/1.6.25/authlib-1.6.25.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/com/mojang/minecraft/1.16.2/minecraft-1.16.2-client.jar

Native libraries:
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/instances/1.16.21/.minecraft --assetsDir C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: max (if available)

Java Arguments:
[-XX:+UseG1GC, -XX:+UnlockExperimentalVMOptions, -XX:MaxGCPauseMillis=100, -XX:+DisableExplicitGC, -XX:TargetSurvivorRatio=90, -XX:G1NewSizePercent=50, -XX:G1MaxNewSizePercent=80, -XX:InitiatingHeapOccupancyPercent=10, -XX:G1MixedGCLiveThresholdPercent=50, -XX:+AggressiveOpts, -XX:+AlwaysPreTouch, -d64, -XX:+UseCompressedOops, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms6016m, -Xmx12032m, -Duser.language=en]

Minecraft process ID: 10432

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.BootstrapMethodError: java.lang.ExceptionInInitializerError
	at hk.<clinit>(SourceFile:50)
	at gm.<clinit>(SourceFile:237)
	at vm.a(SourceFile:42)
	at net.minecraft.client.main.Main.main(SourceFile:137)
	... 8 more
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:148)
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:137)
	at java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method)
	at java.lang.invoke.MethodHandle.getAdditionalBsmArg(MethodHandle.java:869)
	at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:948)
	... 12 more
Caused by: java.lang.NullPointerException
	at hk.a(SourceFile:88)
	at kk.a(SourceFile:20)
	at kk.<clinit>(SourceFile:13)
	... 15 more
Exiting with -1
Process exited with code -1.

Additional Info:
---------------------------
When 1.16.2 is attempted to be launched a window is never opened

**Comment by Janrupf** [comment]
Looks like OpenJ9 bugging out. Use a JVM built from the OpenJDK or OracleJDK.

**Comment by RubberDuckyDJ** [comment]
@Janrupf i downloaded JDK 14.0.2 and it still doesn't open (just so you know 1.16.1 opens fine its just 1.16.2 that doesn't work.)

**Comment by Zetabite** [comment]
download openjdk8 with jvm, not openjdk 14 with who knows. minecraft is designed for java 8

**Comment by RubberDuckyDJ** [comment]
@Janrupf openjdk 14 runs on java 8 and all versions of java have jvm included

**Comment by Zetabite** [comment]
no openjdk 14 doesnt run on java 8, its literally java 14

**Comment by RubberDuckyDJ** [comment]
java 8 is the latest version of java openjdk just has a different naming scheme since it isn't official

**Comment by Zetabite** [comment]
no its not. openj9 is for java 8, openjdk 14 is java 14 https://openjdk.java.net/projects/jdk/14/

**Comment by RubberDuckyDJ** [comment]
openjdk 14 is an open source version of oraclejdk 14 which is the latest jdk. the jdk contains jre8 along with extra development features and within jre8 is jvm.

**Comment by Zetabite** [comment]
it has that for dev stuff, yes, but it isnt used for launching stuff. if you launch with openjdk 14, it launches with java 14

**Comment by peterix** [comment]
Looks weird. I'm not sure about OpenJ9, nevber used it... but there's a lot of weird Java forks out there, and they are definitely not guaranteed to work.

If you want something that does work, conside using one of the Java versions here:
https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs

These are identical to the versions shipped with the Mojang launcher, and are being used by millions of people.

**Comment by peterix** [comment]
Also note:
https://stackoverflow.com/a/31976060

While it doesn't mention `#`, it might (or might not) be causing problems. It is commonly used as a character that denotes the start of a comment in common shell/command line implementations, and could have special meaning in OpenJ9.

**Comment by RubberDuckyDJ** [comment]
i don't have an intel gpu i have a nvidia gtx1060

**Comment by peterix** [comment]
That doesn't matter.

**Comment by RubberDuckyDJ** [comment]
also if java was the problem i wouldn't be able to run any version of minecraft but 1.16.1 works fine

**Comment by peterix** [comment]
What matter is that you should try something that definitely works instead of a weird for of Java that nobody at Mojang tests the game with.

**Comment by peterix** [comment]
MultiMC doesn't serve you an installation of Java on a silver platter like the vanilla launcher does, it assumes you can get a working one from Oracle, or your linux distribution repositories (most have decent OpenJDK build in them).

You can get current Java 8 from here:
https://java.com/en/download/manual.jsp

**Comment by peterix** [comment]
Prefer the offline installers, they don't try to sneak a 32bit build of Java in, when 64bit is generally required these days.

**Comment by RubberDuckyDJ** [comment]
i only use the offline installer

**Comment by RubberDuckyDJ** [comment]
im downloading it rn

**Comment by RubberDuckyDJ** [comment]
i installed the latest version of java 64x and it still doesn't work

**Comment by RubberDuckyDJ** [comment]
MultiMC version: 0.6.11-1430


Minecraft folder is:
C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/instances/1.16.2/.minecraft


Java path is:
C:/Program Files/AdoptOpenJDK/jdk-8.0.232.09-openj9/bin/javaw.exe


Java is version 1.8.0_232, using 64-bit architecture.


Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/instances/1.16.2/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/com/mojang/authlib/1.6.25/authlib-1.6.25.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/com/mojang/minecraft/1.16.2/minecraft-1.16.2-client.jar

Native libraries:
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/instances/1.16.2/.minecraft --assetsDir C:/Users/Ethan/Desktop/Games/#Game Launchers/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: max (if available)

Java Arguments:
[-XX:+UseG1GC, -XX:+UnlockExperimentalVMOptions, -XX:MaxGCPauseMillis=100, -XX:+DisableExplicitGC, -XX:TargetSurvivorRatio=90, -XX:G1NewSizePercent=50, -XX:G1MaxNewSizePercent=80, -XX:InitiatingHeapOccupancyPercent=10, -XX:G1MixedGCLiveThresholdPercent=50, -XX:+AggressiveOpts, -XX:+AlwaysPreTouch, -d64, -XX:+UseCompressedOops, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms6016m, -Xmx12032m, -Duser.language=en]


Minecraft process ID: 16296


Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.BootstrapMethodError: java.lang.ExceptionInInitializerError
	at hk.<clinit>(SourceFile:50)
	at gm.<clinit>(SourceFile:237)
	at vm.a(SourceFile:42)
	at net.minecraft.client.main.Main.main(SourceFile:137)
	... 8 more
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:148)
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:137)
	at java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method)
	at java.lang.invoke.MethodHandle.getAdditionalBsmArg(MethodHandle.java:869)
	at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:948)
	... 12 more
Caused by: java.lang.NullPointerException
	at hk.a(SourceFile:88)
	at kk.a(SourceFile:20)
	at kk.<clinit>(SourceFile:13)
	... 15 more
Exiting with -1
Process exited with code -1.

**Comment by peterix** [comment]
Still using OpenJ9 there. Make sure you actually set the installed java up to be used.

Go in the Java settings, auto-detect and select the isntalled Java 8.

**Comment by RubberDuckyDJ** [comment]
do you even know what openj9 is

**Comment by peterix** [comment]
AFAIK, one of the many build of Java that sprang up when Oracle decided to drop the ball and change its license. Or at least became relevant at that point.

**Comment by Zetabite** [comment]
From what i know openj9 is java 8 jvm with a lot of tweaks, which does sometimes help running java 8 stuff, but also brings many incompatibilies with closer to original java 8 codebase projcets

**Comment by peterix** [comment]
From my point of view, if you use that and it breaks, that's your problem. I can point you to things that have worked for years and are being used by most people.

**Comment by RubberDuckyDJ** [comment]
no its the latest JVM (Java Virtual Machine) which is part of the JRE (Java Runtime Enviroment(the base version of java you get off of the java website)) and the JVM is what allows java programs to run.

**Comment by peterix** [comment]
It's an unofficial fork, and not shipped with Minecraft in any way, shape or form.

**Comment by RubberDuckyDJ** [comment]
openj9 is official

**Comment by RubberDuckyDJ** [comment]
its literally a part of base java

**Comment by peterix** [comment]
And does it work for you?

**Comment by Zetabite** [comment]
no: https://en.wikipedia.org/wiki/OpenJ9

**Comment by RubberDuckyDJ** [comment]
ok though you were talking about something else for a second there

**Comment by Zetabite** [comment]
> ok though you were talking about something else for a second there

mistakes were made. anyway, openj9 doesnt work all that dandy with mc in general. it does sometimes, but not always. with openjdk8 + jvm its almost guaranteed to work. thats everything we are saying

**Comment by peterix** [comment]
If you want the thing that definitely works, it's 8u52 from Oracle.
That is what is shipped with the game, and what it is tested with.

Compatible versions *should* work. Doesn't mean they do. There are some really bad interactions with newer versions of even Java 8 on Windows 10 and specific GPU drivers. There are similar limitations with Java 9 and newer when it comes to mods.

I'm not going to pretend it's not a mess, but that's how things are.

**Comment by peterix** [comment]
Third party patched versions are ... well outside of anything I could recommend.

**Comment by RubberDuckyDJ** [comment]
found the error it was auto detecting my old jdk version of java i used for developing mods a while back but the problem is fixed now
