### ISSUE TITLE
Import Versions from vanilla launcher/vanilla to MMC json convert

### ISSUE THREAD

**Issue by UltraBlackLinux** [MultiMC/MultiMC5#3290]
System Information
-----------------------------
MultiMC version: 0.6.12

Operating System: Linux
Summary of the issue or suggestion: Would be nice, if I could Import versions from the vanilla launcher
----------------------------------------------

What should happen:
------------------------------
The Wiki says, the feature will be added in the future - but its quite outdated; you can already install modpacks from ftb and technic support got cancelled - thats why Im curious.

Why Im suggesting this: In most cases its just pretty difficult, to port the versions json from the vanilla launcher

**Comment by peterix** [comment]
Not interested in doing this. Vanilla supports junk that should not receive any support here.

**Comment by UltraBlackLinux** [comment]
Hm, ok. 
Thanks!
