### ISSUE TITLE
Vanilla 1.16.2 in OSX Fails to Launch

### ISSUE THREAD

**Issue by drinkdecaf** [MultiMC/MultiMC5#3292]
System Information
-----------------------------
MultiMC version: 0.6.11-1370

Operating System: OSX 10.15.6 Catalina

Summary of the issue or suggestion:
----------------------------------------------
Vanilla 1.16.2 Fails to Launch

What should happen:
------------------------------
Should Launch

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add Instance > 1.16.2 > Ok

2. Launch Instance > Crashes with attached log.

Note that this workflow works fine if 1.16.1 is chosen.

Suspected cause:
---------------------------
Minecraft 1.16.2

Highly speculative, but from reading another thread, I checked and am seeing:
```
Traits:
traits FirstThreadOnMacOS
```
in the log. I've hit the refresh button on the versions panel before choosing 1.16.2, but to no avail. If these lines aren't supposed to be there and aren't on the server side, it would seem they're being cached somewhere.

Logs/Screenshots:
----------------------------
https://paste.ee/p/4zIsO

Additional Info:
---------------------------

Java is /usr/bin/java version 1.8.0_252, using 64-bit architecture, and works fine for other instances within MultiMC.

**Comment by 7coil** [comment]
Same issue with _MultiMC 5 - 0.6.11-1430 on win32_

https://gist.github.com/7coil/bfbac02c221f282933976ffdc7bff5d1

**Comment by peterix** [comment]
Do not use OpenJ9.
