### ISSUE TITLE
My mod pack won’t work and I don’t know how to fix it.

### ISSUE THREAD

**Issue by BlossomPeach65** [MultiMC/MultiMC5#3293]
(https://paste.ee/p/5YXBJ) paste.ee/p/5YXBJ
^^my crash log.^

**Comment by Zetabite** [comment]
give more memory, start with about 6000MB max, if that doesnt suffice, 8000MB

**Comment by BlossomPeach65** [comment]
Thank you! I’ll try it with 8000 because I’ve already tried with 6144 and it still won’t work. Also can I use future mc and future versions together? Because I’m the last I felt like future mc wouldn’t work with my pack at all.
