### ISSUE TITLE
How will my world with my mod pack show up in the Minecraft Launcher?

### ISSUE THREAD

**Issue by BlossomPeach65** [MultiMC/MultiMC5#3294]
I’ve clicked the launch button and I want to start my world but I don’t want to have to open the MultiMc app again to play my world. I rather just have it in the Minecraft Launcher. Am I being dumb or am I doing something wrong?

**Comment by Zetabite** [comment]
1. yeah you kinda being dumb, i mean, there is no point of using the vanilla launcher if you use MMC, 2. MMC doesnt use the normal mc folder, cause of the whole instance stuff, which is the reason MMC exists in the first place. If you want your world in vanilla mc launcher: copy world folder of your mmc instance and paste it into the vanilla launchers world folder

**Comment by BlossomPeach65** [comment]
I just thought the vanilla launcher would be easier to play my world. I just don’t know how to play the world after I close out of it the first time I launch it

**Comment by Zetabite** [comment]
?

**Comment by peterix** [comment]
MultiMC has nothing to do with any other launcher. And never will.
