### ISSUE TITLE
Is my laptop crappy or is it a problem with the mods?

### ISSUE THREAD

**Issue by BlossomPeach65** [MultiMC/MultiMC5#3295]
So. Whenever I click on a waystone. It crashes. Whenever I go to /gameruleKeepInventory true. It doesn't work. And whenever I click a shader's to put on. It crashes. Is it the laptop or something wrong with the mods or MultiMC or me? :(

**Comment by Zetabite** [comment]
please provide log

**Comment by BlossomPeach65** [comment]
There’s not crashlog it just tells me to close the program and also my Bibliocraft labels aren’t working and I’ve right clicked with an empty hand

**Comment by Janrupf** [comment]
![image](https://user-images.githubusercontent.com/25827180/90331397-35ec3000-dfb4-11ea-8ab1-53e35bb56b32.png)

**Comment by BlossomPeach65** [comment]
ok I'll do that next time it crashes. I just don't think my computer can handle it because there's just so many things going wrong. Like there's not even a ring of flight from PattysMoreStuff not even in the config file
