### ISSUE TITLE
MultiMC crashing on startup with multiple modpacks

### ISSUE THREAD

**Issue by Lassley** [MultiMC/MultiMC5#3297]
System Information
-----------------------------
MultiMC version: MultiMC 5 - Version 0.6.11-1430 on win32

Operating System: x64 Windows 10

Summary of the issue or suggestion:
----------------------------------------------
It seems like any modpack I try to play with MultiMC (or the twitch app, for that matter) crash on startup. The startup error varies but sometimes is about java running out of memory, a failed core dump, or it doesnt crash at all and just freezes. Issues usually happen during part 2/7 or 3/7 of the startup.

What should happen:
------------------------------
Minecraft starts up.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Start up a modpack with multiMC

2. Wait

3. Cry

Suspected cause:
---------------------------
My suspected cause is something to do with memory, since I have gotten "ran out of memory" errors. However, my laptop has 8gb of ram.

Logs/Screenshots:
----------------------------
https://paste.ee/p/BHyuf
Error  log starting up Enigmatica 2 Light with no ram min or max. Startup crashed on part 2/7.

https://paste.ee/p/N1T13
Error log starting up PO3 with 1024 mb ram min and 2048 mb ram max. Startup froze on part 2/7.

https://paste.ee/p/9DrI7
Error log starting up PO3 with 1024 mb ram min and 4096 mb ram max. Startup froze on part 3/7 during ModelLoader: Blocks - rftools:powercell_creative with 2167mb/3641mb used.

Additional Info:
---------------------------
-I am running the latest x64 version of java. However, my multiMC version says running on win32. Is this a problem?
- Also I know in the past I used to run big modpacks like FTB and PO2 off this laptop. They were slow but definitely still launched.

Thanks for any help you can give.

**Comment by Janrupf** [comment]
It is probably your graphics driver. See here https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs for more information

**Comment by Lassley** [comment]
I tried your suggestion and still got crashes.

Enigmatica 2 Light crashes much earlier with log 
https://paste.ee/p/xpuOL

On the first test of PO3 it caused my screen to go completely black and I had to hard reset the computer.

On the second test, PO3 did not crash but got hung up on part 3/7 with something to do with the model manager. The used ram kept hovering around and returning to 2298 mb. When I clicked on the app it stopped responding. Here is the log
https://paste.ee/p/XSiJP

For java, I am currently allowing a min ram of 1024 and a max of 4096. Is this a good setting for an 8gb ram laptop?

Thanks again.

**Comment by Janrupf** [comment]
```
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 1234256 bytes for Chunk::new
```
So,
``is 4096MB a good idea for a 8G laptop?`` - Generally speaking, yes
``is it enough for those modpacks?`` - For ``Enigmatic 2 Light`` apparently not, try using 6G or 7G, for ``PO3``, no idea.

So, the reason ``PO3`` crashed can't be determined from the log (and will probably stay a mystery), I suggest you try to increase the memory there as well.

**Comment by Lassley** [comment]
Upping the ram still causes out of ram errors. Maybe I need to try a lighter pack or just get more ram...

Either way, I think this thread is done. Thanks for trying to help.
