### ISSUE TITLE
MultiMC Requires Update?

### ISSUE THREAD

**Issue by pholab41** [MultiMC/MultiMC5#3298]
I installed MultiMC and it said i needed java. I installed java, and Qt5, and when i went back in it says Update Required, and no session connection but when I click update it says that i have the latest version. I have logged into my MC account, but message still shows.

![image](https://user-images.githubusercontent.com/69826486/90455249-7928ca80-e0aa-11ea-97b3-fb57aeed0e87.png)
![image](https://user-images.githubusercontent.com/69826486/90455269-8645b980-e0aa-11ea-9d56-41e4967efb33.png)

**Comment by Zetabite** [comment]
Thats an old blog post, you can savely ignore it

**Comment by SqueaksAnon** [comment]
I am having the same issue. have you solved it yet?

**Comment by Janrupf** [comment]
> Thats an old blog post, you can savely ignore it
How about this?

**Comment by seattleda** [comment]
My MultiMC 5 Version 0.6.11-1430 also says "0.6.7 - UI fixes and important metadata news - update required!"  Seems like a bug.

**Comment by Zetabite** [comment]
no. its just a "news" bar, that links to the blog, which hasnt been updated since then (well it was, but the newer entries were intentionally removed)
