### ISSUE TITLE
Update MultiMC to use the next Skins API

### ISSUE THREAD

**Issue by UltraBlackLinux** [MultiMC/MultiMC5#3301]
Summary of the issue or suggestion:
----------------------------------------------
It would be cool, If you could upload your skin to minecraft.net, even with security questions.
I recently found out that most of the minecraft alt accounts are brute forced. That means you really cant protect against that. So I set up my security questions to have some kinda security, but now the skin upload fails.

Maybe add an option to save them In an encrypted file by multimc, so you get promted to enter the password for the file containing the security questions and so proceed to upload the skin?
Thanks for any response.

**Comment by Zetabite** [comment]
MMC just uses the system Minecraft provides, they cannot do more than they allow to.

**Comment by UltraBlackLinux** [comment]
hmm

**Comment by peterix** [comment]
Ehh. I'd say we need to document some of the incoming changes. They will make this obsolete. But I'll keep it around as a reminder.

**Comment by phit** [comment]
fixed in https://github.com/MultiMC/MultiMC5/commit/6b3b7ded2d9f30388219b97fb656313ef648e08e

**Comment by peterix** [comment]
This is nowhere near done.

**Comment by peterix** [comment]
Hmmm... or maybe I could just not conflate skin upload with correctly handling skins in general :)
