### ISSUE TITLE
Unused Required Parameters In OneSix

### ISSUE THREAD

**Issue by TheBrokenRail** [MultiMC/MultiMC5#3306]
System Information
-----------------------------
MultiMC version: 0.6.1-1344

Operating System: Ubuntu 20.04

Summary of the issue or suggestion:
----------------------------------------------
The MultiMC OneSix launcher requires multiple parameters. However the parameters ``cp``, and ``natives`` are never used after definition in the entire file, yet they are still required. Also the parameters ``userName`` and ``sessionId`` are also required, yet only used in a a legacy launch.

Relevant File:
------------------
https://github.com/MultiMC/MultiMC5/blob/develop/libraries/launcher/org/multimc/onesix/OneSixLauncher.java

**Comment by peterix** [comment]
I don't see how this internal detail is relevant to anyone but me.

If you depend on this in any way, please reconsider your choices.
