### ISSUE TITLE
A block crashed my world so I removed the mod and now I can’t load my world.

### ISSUE THREAD

**Issue by BlossomPeach65** [MultiMC/MultiMC5#3309]
[Crash log](https://paste.ee/p/xoxKq) 
Please help me! I really don’t want my world to be lost forever. The mod was blockcraftery.

**Comment by Janrupf** [comment]
Waila or Doubleslabs is causing the crash, or maybe a combination of both.

**Comment by QuImUfu** [comment]
duplicate of #3312
