### ISSUE TITLE
My world keeps crashing and I don’t want it to be lost forever.

### ISSUE THREAD

**Issue by BlossomPeach65** [MultiMC/MultiMC5#3312]
[Here’s my Crash Log](https://paste.ee/p/xoxKq) 

I placed a blockcraftery slab and I broke it. It instantly crashed my world and I can’t open it back up. I worked so hard on that world and I don’t want it to be lost forever. Even after I deleted the mod from the mod folder it still crashes.

My world keeps crashing and I don’t want it to be lost forever.

**Comment by QuImUfu** [comment]
I think this is an issue with https://github.com/CJMinecraft01/DoubleSlabs and waila.  
Ping @CJMinecraft01

**Comment by BlossomPeach65** [comment]
How do I fix it with that information tho?

**Comment by QuImUfu** [comment]
First back up the world.  

Then either:  
Try removing waila. If that doesn't work, remove DoubleSlabs (this might destroy a lot of your buildings).  
Or:  
Try replacing `Optional.of` with `Optional.ofNullable` in line: https://github.com/CJMinecraft01/DoubleSlabs/blob/6441ba3df344327cecfdc08bc94cd65c731c739d/src/main/java/cjminecraft/doubleslabs/blocks/BlockVerticalSlab.java#L91 and recompile DoubleSlabs. And replace the mod with the pached version. If you trust me sufficiently (keep in mind, mods are executables and can, even without administrative privileges, do a lot of harm), here is a build with that done: https://dl.dropbox.com/s/oia9ghnwvt5an14/DoubleSlabs-1.12-0.10.0.jar  

If you choose to use the patched DoubleSlabs version and it still crashes, please post a new log.

**Comment by BlossomPeach65** [comment]
I deleted the double slabs mod but can I add it back since it fixed my world and the blocks are gone?

**Comment by CJMinecraft01** [comment]
Hi, sorry for the delay in responding to this. This is an issue which I am aware of and intend to patch as soon as possible for you and release an new official version. I have been working on a complete rewrite of the mod to improve stability which will also fix a lot of errors like the one you are experiencing but unfortunately it has taken longer than anticipated. I will try to get this fixed as soon as I can. Sorry for the inconvenience

**Comment by QuImUfu** [comment]
@BlossomPeach65 I am not sure why exactly that crash happens, so if you re-add the double slabs mod it might happen again, some time later. Add it if you think that's worth it. :)  
Otherwise i think you could use chisels and bits to replace it.
