### ISSUE TITLE
Issue with installing and launching instances

### ISSUE THREAD

**Issue by AlphaMike19** [MultiMC/MultiMC5#3317]
System Information
-----------------------------
MultiMC version: MultiMC 5 - Version 0.6.11-1430

Operating System: Windows 10 64 Bit

Summary of the issue or suggestion: 
----------------------------------------------
I have installed MultiMC, signed into my account, and have added an instance. The instance I chose is vanilla 1.7.10. Everything else is set exactly as how it was when MultiMC was installed. I then click on Launch instance, and I receive the below crash log.

What should happen:
------------------------------
The instance should launch as vanilla 1.7.10

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Click launch Instance

2.

3.

Suspected cause:
---------------------------
No idea.

Logs/Screenshots:
----------------------------
MultiMC version: 0.6.11-1430

Minecraft folder is:
E:/MultiMC/instances/1.7.10 Vanilla/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_261/bin/javaw.exe

Java is version 1.8.0_261, using 64-bit architecture.

Main Class:
  net.minecraft.client.main.Main

Native path:
  E:/MultiMC/instances/1.7.10 Vanilla/natives

Libraries:
  E:/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  E:/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  E:/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  E:/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  E:/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  E:/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  E:/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  E:/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  E:/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  E:/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  E:/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  E:/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  E:/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  E:/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  E:/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  E:/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  E:/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  E:/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  E:/MultiMC/libraries/com/google/guava/guava/15.0/guava-15.0.jar
  E:/MultiMC/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
  E:/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  E:/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  E:/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  E:/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  E:/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  E:/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  E:/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  E:/MultiMC/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  E:/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  E:/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar
  E:/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Params:
  --username  --version MultiMC5 --gameDir E:/MultiMC/instances/1.7.10 Vanilla/.minecraft --assetsDir E:/MultiMC/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType 

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 9392

Using onesix launcher.

[14:56:27] [main/INFO]: Setting user: AlphaMike19
[14:56:27] [main/INFO]: (Session ID is token:<ACCESS TOKEN>:<PROFILE ID>)
[14:56:27] [Client thread/INFO]: LWJGL Version: 2.9.4
[14:56:28] [Client thread/INFO]: Reloading ResourceManager: Default

Starting up SoundSystem...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffa898d2d77, pid=9392, tid=0x0000000000002b50
#
# JRE version: Java(TM) SE Runtime Environment (8.0_261-b12) (build 1.8.0_261-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.261-b12 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ig7icd64.dll+0x22d77]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# E:\MultiMC\instances\1.7.10 Vanilla\.minecraft\hs_err_pid9392.log
OpenAL initialized.
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 1.

Clipboard copy at: 27 Aug 2020 15:14:46 -0400

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs

Next time you upload the log do this: https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by AlphaMike19** [comment]
Thank you for both suggestions. I will try and let you know if it works.

**Comment by AlphaMike19** [comment]
Thanks for your help! That allowed me to launch the vanilla 1.7.10. Let's hope I don't run into issues with mods. Thanks again!

**Comment by Scotsguy** [comment]
Resolved.
