### ISSUE TITLE
Worlds are missing

### ISSUE THREAD

**Issue by end-user** [MultiMC/MultiMC5#3318]
System Information
-----------------------------
MultiMC version: 0.6.1430

Operating System: Win10

Summary of the issue or suggestion:
----------------------------------------------
Saved games no longer show up in "Worlds"

What should happen:
------------------------------
New worlds that have local saves should show up in Worlds

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.  Create new world

2. Open it; save and quit

3. Look in "Worlds"

Suspected cause:
---------------------------
Something in 1.16x release causes it not to be found.  A world created from an old snapshot was there; when opened and updated, it's now missing.

**Comment by Zetabite** [comment]
thats intentional

**Comment by end-user** [comment]
Could you be more specific?  What is "worlds" if it's intentionally empty?

**Comment by Zetabite** [comment]
well if its the releases i think you mean, mojang did it as they didnt want the worlds from snapshots to work on releases, compatibility and stuff. though if you havent installed mmc properly, that might be the issue why there are no saves. so its either mojang, uncorrect install, or antivirus or onedrive acting up

**Comment by end-user** [comment]
Not sure what happened, but I created a new instance and worlds began working as expected.
