### ISSUE TITLE
My shaders crashes my world.

### ISSUE THREAD

**Issue by BlossomPeach65** [MultiMC/MultiMC5#3319]
I don’t know why but whenever I try to put on a shaders pack it crashes everything including optifine my forge the game version and shaders pack is 1.12.2 and I looked it up and it said it might be a hard drive issue but I don’t know how to fix it.

**Comment by UltraBlackLinux** [comment]
Your Hardware may be bad. Cant fix that software wise

**Comment by QuImUfu** [comment]
Please post a game log. (upload button in the launcher (log window) and paste the link.)

**Comment by BlossomPeach65** [comment]
[https://paste.ee/p/QMVV7](url)
I don't think it's my software because it worked on less heavily modded worlds.

**Comment by BlossomPeach65** [comment]
I don’t think it’s my software because shaders has worked on less heavily modded worlds.
https://paste.ee/p/QMVV7

**Comment by Zetabite** [comment]
you have optifine twice in this instance, disable one

**Comment by Zetabite** [comment]
also, shaders on such a heavily modded modpack is insanity, no wonder it would crash

**Comment by BlossomPeach65** [comment]
Yeah it’s just too modded to handle it

**Comment by QuImUfu** [comment]
Does this error not happen without shaders?  
It looks like a normal crash inside ValkyrieLib. I have no (simple) way to debug further, as that mod is not open source.

**Comment by BlossomPeach65** [comment]
I dunno i dont want to touch the files rn because I'm kinda rusty... should I dedicate more ram to it?

**Comment by BlossomPeach65** [comment]
https://paste.ee/p/pO5pA

**Comment by QuImUfu** [comment]
that crash was caused by insufficient memory.
