### ISSUE TITLE
OptiFine 1.8.9 w/ Forge Crashes when launching on MultiMC

### ISSUE THREAD

**Issue by 69420XD** [MultiMC/MultiMC5#3320]
System Information
-----------------------------
MultiMC version: **0.6.11**

Operating System: **macOS Catalina 10.15.6**

Summary of the issue or suggestion: **1.8.9 OptiFine crashes with Forge version 11.15.1.2318 (latest version)**
----------------------------------------------

What should happen: **Instance should launch normally with OptiFine and Forge installed.**
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install latest version of Forge

2. Install OptiFine 1.8.9 in Loader mods

3. Launch the instance

4. Crash

Suspected cause:

---------------------------

Logs/Screenshots: https://paste.ee/p/MCQI9
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by 69420XD** [comment]
Bump?

**Comment by QuImUfu** [comment]
This seems to be similar to #3250. Please try the workaround suggested by @Janrupf and report back whether it worked.  
Related issues:
#3173 #3270 #3253  
In some of those, changing the java version seemingly helped. Also try `reload` and `download all` in the version page.

**Comment by 69420XD** [comment]
> In some of those, changing the java version seemingly helped.

It says on the website that downloading older Java versions are not safe though…?

**Comment by jamierocks** [comment]
> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'

This may only be applicable to LWJGL 3, but try using `-XstartOnFirstThread`.

**Comment by 69420XD** [comment]
So, I used -XstartOnFirstThread and also tried ### reload and ### download all in the versions page, but it still crashes.

https://paste.ee/p/wIbIS
<img width="2160" alt="Screenshot 2020-09-03 at 19 02 53" src="https://user-images.githubusercontent.com/64201549/92150930-1eb49b80-ee18-11ea-91a5-aae22f2d171f.png">
<img width="455" alt="Screenshot 2020-09-03 at 19 03 04" src="https://user-images.githubusercontent.com/64201549/92150946-22e0b900-ee18-11ea-807f-66c5023a3b8d.png">

I am using the latest version of Java and I have yet to try and downgrade the version of it

**Comment by Janrupf** [comment]
You need to keep the checkbox ``Java Arguments`` checked. Please also upload a log _with the checkbox enabled and the arguments in the text field_!

**Comment by jamierocks** [comment]
I'm assuming the flag was set globally, as it was definitely enabled in the log.

> [-XstartOnFirstThread, -Xdock:icon=icon.png, -Xdock:name="MultiMC: 1.8.9", -Xms512m, -Xmx1024m, -Duser.language=en]

**Comment by 69420XD** [comment]
> ~You need to keep the checkbox `Java Arguments` checked. Please also upload a log _with the checkbox enabled and the arguments in the text field_!~
> 
> Didn't see the log link, sorry

https://paste.ee/p/SPqKP
I kept the checkbox 'Java Arguments' checked but it still crashed.

**Comment by Janrupf** [comment]
Well, that is at least another error, so some progress. I have seen this error before, but I don't know where. You could try downgrading your Java version to 8.61 (or something like that).

For reference, the error now causing the crash is ``glGenLists returned an ID of 0 for a count of 1, GL error (0): No error code reported``

**Comment by 69420XD** [comment]
> Well, that is at least another error, so some progress. I have seen this error before, but I don't know where. You could try downgrading your Java version to 8.61 (or something like that).
> 
> For reference, the error now causing the crash is `glGenLists returned an ID of 0 for a count of 1, GL error (0): No error code reported`

Do I have to uninstall my latest Java version or could I just keep both versions and use the older version for only 1.8.9?

**Comment by Janrupf** [comment]
> Do I have to uninstall my latest Java version or could I just keep both versions and use the older version for only 1.8.9?

If you configure MultiMC correctly, you can keep the old version. When you launch with it, upload a new log please.

**Comment by 69420XD** [comment]
> > Do I have to uninstall my latest Java version or could I just keep both versions and use the older version for only 1.8.9?
> 
> If you configure MultiMC correctly, you can keep the old version. When you launch with it, upload a new log please.

Ok, where do I download the older Java version?

**Comment by 69420XD** [comment]
I also tested out if installing OptiFine 1.8.9 + Forge on the normal launcher would crash, it launched normally with no issues, with the latest java version.

**Comment by Janrupf** [comment]
Can you try to find out which launch arguments the official launcher uses? Maybe something differs there. Another possibility would be that the official launcher runs Minecraft on the GPU, and somehow MultiMC manages to run it on the CPU? (Not sure if this is even possible on a MAC)

**Comment by 69420XD** [comment]
> Can you try to find out which launch arguments the official launcher uses? Maybe something differs there. Another possibility would be that the official launcher runs Minecraft on the GPU, and somehow MultiMC manages to run it on the CPU? (Not sure if this is even possible on a MAC)

-Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

**Comment by 69420XD** [comment]
This is what happens when I try to run 1.8.9 Optifine + Forge with the Java Arguments as 
~~-Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M~~ 
https://paste.ee/p/XA4Pj

**Comment by Janrupf** [comment]
You now need to add back the ``-XstartOnFirstThread``

**Comment by SoCuul** [comment]
I have the same issue.

**Comment by 69420XD** [comment]
> You now need to add back the `-XstartOnFirstThread`

Do I add the `-XstartOnFirstThread` with `-Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`?

**Comment by Janrupf** [comment]
Yes

**Comment by darchitectlp** [comment]
Just adding my experience in :
Using a Mac on 10.15.6, Minecraft 1.12.2, forge-1.12.2-14.23.5.2854, OptiFine_1.12.2_HD_U_F5.jar

Using MultiMC with Optifine: Crash
Using Mojang's Launcher with Optifine: Works

I also tried adding the -XstartOnFirstThread in MultiMC, which it allowed it to keep working up until the Sound Manager was loaded, then it crashed.

**Comment by adamthedog** [comment]
Hey I found a solution (at least for me)!!

Use the [Zulu build of OpenJDK](https://www.azul.com/downloads/zulu-community/?version=java-8-lts&os=macos&architecture=x86-64-bit&package=jdk) and set the Java path to `/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/bin/java` after install.

At least for me, the `-XstartOnFirstThread` was not necessary, but you may need to try for yourself.

**Comment by 69420XD** [comment]
> Hey I found a solution (at least for me)!!
> 
> Use the [Zulu build of OpenJDK](https://www.azul.com/downloads/zulu-community/?version=java-8-lts&os=macos&architecture=x86-64-bit&package=jdk) and set the Java path to `/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/bin/java` after install.
> 
> At least for me, the `-XstartOnFirstThread` was not necessary, but you may need to try for yourself.

Still doesn't work :/

**Comment by 69420XD** [comment]
Which older version of Java fixes this?

**Comment by 69420XD** [comment]
Update: Downloading an older version of Java, specifically Java8u242 fixes the issue.
I downloaded the older version of Java from here[https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=hotspot](url).
