### ISSUE TITLE
Mixin Errors?

### ISSUE THREAD

**Issue by mindblaster0076** [MultiMC/MultiMC5#3324]
System Information
-----------------------------
MultiMC version: Version 0.6.11-1430

Operating System: Windows 10

Summary of the issue or suggestion:  When attempting to join any server, the game crashes.
----------------------------------------------

What should happen: I should be able to join the server.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add Forge 1.12.2 (Version 14.23.5.2854) to a 1.12.2 instance.

2. Add the following mods to the instance:
- 5zig-Reborn 1.12.2 (Version 3.14.0) https://5zigreborn.eu/downloads/
- Real Time Chat Translation Mod 1.12.2 (Version 5.1) https://www.curseforge.com/minecraft/mc-mods/real-time-chat-translation-mod/download/3040853
- OptiFine 1.12.2 (Version HD U F5) https://optifine.net/adloadx?f=OptiFine_1.12.2_HD_U_F5.jar&x=1448

3. Run the instance and try to join any server of your liking.

Suspected cause: Honestly, no clue. There are a few Mixin errors, no clue what those are.
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/4denb

Additional Info: Everything worked 100% fine when I used the vanilla Minecraft Launcher.
---------------------------

**Comment by QuImUfu** [comment]
This error has nothing to do with mixins. This crash happened inside the Intel GPU driver. Try updating it. Or removing Optifine. It seems quite unlikely this happens with MultiMC but not the vanilla launcher. Do they use different Java versions?

**Comment by mindblaster0076** [comment]
> This error has nothing to do with mixins. This crash happened inside the Intel GPU driver. Try updating it. Or removing Optifine. It seems quite unlikely this happens with MultiMC but not the vanilla launcher. Do they use different Java versions?

I just triple checked and it worked perfectly fine with the normal Launcher. I copied the exact .jars from the instance to the vanilla launcher and I made sure both had the same version of forge installed.

**Comment by QuImUfu** [comment]
Do they use different Java versions?

**Comment by kb-1000** [comment]
Of course they do. 8u51 vs. whatever is installed on your system
try my patched java build at https://ci.appveyor.com/project/kb1000/jdk8u/build/artifacts
Also do you have a hybrid GPU system? The GPU driver might not detect Minecraft when ran through MultiMC if so, and might give you the integrated GPU

**Comment by Scotsguy** [comment]
This is not a MultiMC issue, closing.
