### ISSUE TITLE
Unable to launch forge instances

### ISSUE THREAD

**Issue by Logic530** [MultiMC/MultiMC5#3325]
System Information
-----------------------------
MultiMC version:
0.6.12-develop-1371

Operating System:
```
logic@logic-ThinkPad-E550 ~> uname -a
Linux logic-ThinkPad-E550 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Summary of the issue or suggestion:
----------------------------------------------
Fail to launch 1.12.2 forge loader instances

Logs/Screenshots:
----------------------------
https://paste.ee/p/8fAE1

Additional Info:
---------------------------
This is a blank instance without any mod.
Forge version is 2854.

**Comment by QuImUfu** [comment]
Have you installed openjdk-8-jre, not just openjdk-8-jre-headless?  
If you have, but the problem persists, try adding `-Djavax.accessibility.assistive_technologies=" "` to the Java arguments.

**Comment by Logic530** [comment]
> Have you installed openjdk-8-jre, not just openjdk-8-jre-headless?
> If you have, but the problem persists, try adding `-Djavax.accessibility.assistive_technologies=" "` to the Java arguments.

openjdk-8-jre-headless caused the problem, thanks XD
