### ISSUE TITLE
MultiMC Crashes launching fabric for the first time with 1.16

### ISSUE THREAD

**Issue by Adrakaris** [MultiMC/MultiMC5#3328]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 10

Summary of the issue or suggestion: Fabric 1.16 crashes on startup, doesnt even start the game
----------------------------------------------

What should happen: The game should start
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a new instance

2. Install fabric

3. Launch

Suspected cause: I have no idea
---------------------------

Logs/Screenshots: https://pastebin.pl/view/ff8c24d2

**Comment by jamierocks** [comment]
> java.lang.J9VMInternals

Perhaps this is an issue with using OpenJ9 because I can't reproduce this with Hotspot.

**Comment by peterix** [comment]
Yes. Avoid OpenJ9.

**Comment by QuImUfu** [comment]
OpenJ9 Java 8 version works fine for me on Lubuntu (Linux). With and without Fabric. And it even performs better with extreme rendering distances where Minecraft uses lots of memory, as the Metronome garbage collector actually manages to achieve sub 5ms pause times, allowing for no noticeable gc lag with 60 fps, something AFAIK impossible with Hotspot.  
However, as metronome only works on Linux, OpenJ9 java versions >8 crash when loading a world and it performs worse in most other aspects, I can't see a reason to use it on windows.
