### ISSUE TITLE
MultiMC 5 crashing anytime that I use mods

### ISSUE THREAD

**Issue by Kermit-The-Froog** [MultiMC/MultiMC5#3329]
System Information
-----------------------------
MultiMC version: MultiMC 5 0.6.11-1430

Operating System: Windows x64

Summary of the issue or suggestion:
----------------------------------------------
I have a relatively small 1.12.2 modpack that I have used in the past, and one day all of a sudden, it no longer worked and all other vanilla instances worked but no other modded.

What should happen:
------------------------------
I would like a solution to this problem because I would like to continue working on my projects.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Run a modded forge instance and wait for all the assets to be downloaded.

2.

3.

Suspected cause:
---------------------------
I am an amateur java developer, and I suspect it is an issue with the version of the JDK that I use.

Logs/Screenshots:
----------------------------
[//]: # https://paste.ee/p/wJySx (Log)

Additional Info:
---------------------------

**Comment by Janrupf** [comment]
You are using Java 14, Minecraft/Forge wont work with it. Use Java 8

**Comment by Kermit-The-Froog** [comment]
That's what I thought, and I have tried that, but I can't find any way to download Java 8 without a Java account, which requires a lot of stuff that I don't have. Any idea of how to get around this?

**Comment by Janrupf** [comment]
2 Ways:
1. If you really want an Oracle Java (the other one works as fine, and maybe even better), use something like http://bugmenot.com/
2. You can use an OpenJDK build, specifically [OpenJDK-JRE 8b265b01](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u265-b01/OpenJDK8U-jre_x64_windows_hotspot_8u265b01.msi) from https://adoptopenjdk.net/

**Comment by Kermit-The-Froog** [comment]
Thank you that solved my problem.
