### ISSUE TITLE
Launcher always offline even with wifi

### ISSUE THREAD

**Issue by WolfGuy264** [MultiMC/MultiMC5#3330]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
provide log https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by Scotsguy** [comment]
Please fill out the issue template.
