### ISSUE TITLE
Minecraft crashes whenever I create or load a world from multimc

### ISSUE THREAD

**Issue by Jarsef** [MultiMC/MultiMC5#3331]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 10

Summary of the issue or suggestion: Minecraft crashes whenever I create or load a world from Multimc
----------------------------------------------

What should happen: My world should load
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch Minecraft 1.14 from MultiMc

2. Create a new world or join an existing world.

3.

Suspected cause: No idea
---------------------------

Logs/Screenshots: https://paste.ee/p/83o3R
![image](https://user-images.githubusercontent.com/70814774/92309907-03a86f80-ef6f-11ea-808b-36c5e36a0c36.png)

----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Janrupf** [comment]
![image](https://user-images.githubusercontent.com/25827180/92310190-2311bd80-efac-11ea-98b7-b54d6c39b287.png)

**Comment by Jarsef** [comment]
https://paste.ee/p/83o3R

**Comment by Janrupf** [comment]
See https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs for more info

**Comment by Jarsef** [comment]
It Works! Thanks so much!!!
