### ISSUE TITLE
MultiMC keeps Crashing on startup

### ISSUE THREAD

**Issue by WolfGuy264** [MultiMC/MultiMC5#3333]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by WolfGuy264** [comment]
So everytime i load an instance (such as b1.7.3) the game crashes. heres the log: "MultiMC version: 0.6.11-1430


Minecraft folder is:
C:/Users/User/Downloads/mmc-stable-win32/MultiMC/instances/b1.7.3/.minecraft


Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe


Java is version 1.8.0_261, using 64-bit architecture.


Main Class:
  

Native path:
  C:/Users/User/Downloads/mmc-stable-win32/MultiMC/instances/b1.7.3/natives

Traits:
traits legacyLaunch
traits texturepacks

Libraries:
  C:/Users/User/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/User/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/User/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/User/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/User/Downloads/mmc-stable-win32/MultiMC/instances/b1.7.3/.minecraft/bin/minecraft.jar

Native libraries:
  C:/Users/User/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/User/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Jar Mods:
  BetaEvolutionsFull (1) (bea98300-d553-42ed-96e7-e0b96f2e4a96.jar)

Params:
  

Window size: 854 x 480

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 9908


Using onesix launcher.

Launching with applet wrapper...
16 achievements
151 recipes
Setting user: CIANSTARZ, -
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fff2553526c, pid=9908, tid=0x0000000000002ac0
#
# JRE version: Java(TM) SE Runtime Environment (8.0_261-b12) (build 1.8.0_261-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.261-b12 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ig7icd64.dll+0x4b526c]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\User\Downloads\mmc-stable-win32\MultiMC\instances\b1.7.3\.minecraft\hs_err_pid9908.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Process exited with code 1.
MultiMC: Log upload triggered at: 06 Sep 2020 23:23:33 +0100" does anyone know a fix?

**Comment by WolfGuy264** [comment]
does anyone know a fix?

**Comment by Janrupf** [comment]
https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs

**Comment by WolfGuy264** [comment]
ok so it did work but i cant see any of the text on the buttons in the game

**Comment by WolfGuy264** [comment]
ok now the crashes are back

**Comment by WolfGuy264** [comment]
what do i do?

**Comment by WolfGuy264** [comment]
should i match the bit version of multimc?

**Comment by kb-1000** [comment]
No, instead the one of your windows

**Comment by WolfGuy264** [comment]
guess ill just close it because of no answer

**Comment by WolfGuy264** [comment]
oh wait i didnt read ur answer
