### ISSUE TITLE
Missing British English

### ISSUE THREAD

**Issue by MrMelon54** [MultiMC/MultiMC5#3334]
~~This was meant as a joke please don't hate me~~

**Comment by MrMelon54** [comment]
~~This was meant as a joke~~

**Comment by jamierocks** [comment]
I'm not sure there are any changes that need be made -though I'm all for this!

**Comment by MrMelon54** [comment]
I looked on translate.multimc.org and it lists English as "English, United Kingdom" but in multimc its listed as "American English"

**Comment by phit** [comment]
closing in favor of https://github.com/MultiMC/MultiMC5/issues/3605

**Comment by jamierocks** [comment]
This is a bug, and distinct from GH-3605. There are translations for en_GB, its a client bug preventing them from being visible (and also reporting the stats for en_GB for en_US).

**Comment by jamierocks** [comment]
Fixed by https://github.com/MultiMC/MultiMC5/commit/64617201b029c0df72974e91d3314b5ee0e80971.
