### ISSUE TITLE
Feature Request: Import FTB Packs via Link

### ISSUE THREAD

**Issue by UnicorNora** [MultiMC/MultiMC5#3336]
System Information
-----------------------------
MultiMC version: git
Operating System: arch

Request
-----------------------------
I am request a way to add  FTB (Modpacks.ch) modpacks via a direct link instead of the current way of Searching. Searching for packs isnt bad but me and a few others are making projects like [FTBMeta](https://ftbmeta.crankysupertoon.live/
) that allow you to browse FTB Packs. FTBMeta is good but Modpacks.ch the API that powers it and the FTB App doesnt have a ZIP file like Curse. Instead it skipps it all togeather and gives a manifest like this https://api.modpacks.ch/public/modpack/6/91. I am asking for a way probally on Import from Zip where the launcher can read these links like CurseForge Links and import them. Sure its kinda useless but Isnt importing Curse packs via a link equally as useless.

**Comment by peterix** [comment]
You can host curse packs anywhere, so it makes sense for those.

**Comment by CrankySupertoon** [comment]
Fair enough. it kinda defeats the point of my website tho if you cant import the link anywhere.

**Comment by CrankySupertoon** [comment]
this is the offical link FTB provides as well

**Comment by jamierocks** [comment]
It doesn't represent a zip, would be odd to support this from "Import from zip". A better place, if implemented, would be straight in the FTB search.

**Comment by jamierocks** [comment]
This doesn't really serve any practical benefit, closing.
