### ISSUE TITLE
URLs for assets in the new FTB modpacks aren't always "url decoded" properly by MultiMC.

### ISSUE THREAD

**Issue by credomane** [MultiMC/MultiMC5#3337]
System Information
-----------------------------
MultiMC version:  0.6.11.r39.g8a0027c7-1 (From Manjaro AUR) 
having looked at the AUR build script it is compiled from git commit https://github.com/MultiMC/MultiMC5/commit/8a0027c73a755849bf5b58c1509c71a543ddb982

Operating System: Manjaro Linux

Summary of the issue or suggestion:
----------------------------------------------
Downloading assets for some modpacks fail unexpectedly resulting in the modpack not installing.

What should happen:
------------------------------
Modpack downloads and installs correctly.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open up MultiMC
2. Click "add instance"
3. Click "FTB"
4. Search for and click StoneBlock 2.
5. Install SB2 version 1.20.0

Suspected cause:
---------------------------
None or Improper URL decoding. Manually performing a url decode on one of the urls below and visiting that resulting url works.

Logs/Screenshots:
----------------------------
![image](https://user-images.githubusercontent.com/1283031/92539599-88adb600-f207-11ea-8b71-1e5d381f3739.png)

> https://dist.modpacks.ch/modpacks/0/2/config/brandon3055/ResourceCache/Cache%2523-1135820533.png
https://dist.modpacks.ch/modpacks/0/2/config/brandon3055/ResourceCache/Cache%2523-1176369040.png
https://dist.modpacks.ch/modpacks/0/2/config/brandon3055/ResourceCache/Cache%2523-1177856129.png
https://dist.modpacks.ch/modpacks/0/2/config/brandon3055/ResourceCache/Cache%2523-1181428365.png
https://dist.modpacks.ch/modpacks/0/2/config/brandon3055/ResourceCache/Cache%2523-1183039813.png
https://dist.modpacks.ch/modpacks/0/2/config/brandon3055/ResourceCache/Cache%2523-2144074589.png
https://dist.modpacks.ch/modpacks/0/2/config/brandon3055/ResourceCache/Cache%25232134442667.png
https://dist.modpacks.ch/modpacks/0/3/config/Tiny Progressions/Food %2526 Drinks.cfg

**Comment by credomane** [comment]
After ensuring proper URL decoding the previously failing downloads succeed but now different ones fail instead. They fail because apparently they *aren't* supposed to get decoded. What are you supposed to do then? Try once with the url as is then if it fails with 404 try again after decoding it? Then if you get another 404 fail the download for real?

Curious how the FTBApp handles this as it downloads the SB2 V1.20.0 modpack without issue

**Comment by credomane** [comment]
....And the FTBApp just completely ignores the failures and completes the pack install as if nothing is wrong. Investigating the SB2 1.20.0 install folder indeed reveals that the files shown above are missing completely. Guess I need to talk with the SB2 pack dev.

**Comment by Janrupf** [comment]
Well... good catch I guess

**Comment by jamierocks** [comment]
Duplicate of GH-3304.

**Comment by credomane** [comment]
Dang it I searched before I opened this ticket. Seems I didn't search well enough. Closing in favor of the original.
