### ISSUE TITLE
Game freezes my whole pc after 20 mins

### ISSUE THREAD

**Issue by af2111** [MultiMC/MultiMC5#3339]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: Manjaro XFCE 

Summary of the issue or suggestion: The game freezes my whole pc after 20 minutes or so
-----
-----------------------------------------

What should happen:
------------------------------
It shouldn't freeze everything

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install Manjaro XFCE

2. Install Forge for 1.8.9 (newest version)

3. Use this mod folder: http://www.mediafire.com/file/w97eu2hfpz2ftac/mods.zip/file

Suspected cause: The OS

---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Janrupf** [comment]
Can you upload a log after you have entered a world? This would help looking at the setup

**Comment by af2111** [comment]
Yeah I can do that

**Comment by af2111** [comment]
[latest.log](https://github.com/MultiMC/MultiMC5/files/5202994/latest.log)
Do you mean this?

**Comment by Janrupf** [comment]
![image](https://user-images.githubusercontent.com/25827180/92757222-d48a6780-f38d-11ea-8b2e-c5cb7a7ebdc9.png)

**Comment by af2111** [comment]
Oh ok https://paste.ee/p/hpx83

**Comment by Janrupf** [comment]
Uhm... I'm kind of impressed Minecraft is running at all. Running Intel Graphics on Linux is... well, as you see not a good idea. So either you don't have a dedicated GPU, or Linux has not detected it.

**Comment by Janrupf** [comment]
Idk, whatever fits your needs.

**Comment by af2111** [comment]
Okay, thank you

**Comment by QuImUfu** [comment]
Intel and Linux pair just fine, normally, and even performance wise it is quite OK. (the Intel driver is the second most conformant mesa OpenGL driver) That being said there was a Intel driver bug in the kernel recently that caused freezes. Look at `dmesg` during such a freeze or at the kernel log afterwards and see it anything related to "i915" hanging (and recovering) is logged. If that's the case, you might wanna upgrade your system and see if the problem persists. If it does look for an upstream bug report and if there is none, create one.
