### ISSUE TITLE
Fabric Loader-LWJGL Downgrade issue

### ISSUE THREAD

**Issue by DrakeVanLyon** [MultiMC/MultiMC5#3340]
System Information
-----------------------------
MultiMC version: 0.6.12-develop-1468

Operating System: Windows 10: Pro (20H2) x64

Summary of the issue or suggestion: When changing LWJGL 3 to the recommended version (3.1.2.) under any instance with the Fabric Loader installed it will not change from 3.2.2. to anything else, including the other two available versions. I have noticed this bug/issue in both 1.16.3 and 1.16.2 versions of Minecraft.
----------------------------------------------

What should happen: It should obviously change the version after selecting it and clicking "Ok". Or, if it really isn't recommended, LWJGL 3.1.2 shouldn't have the star next to it.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Edit Instance with Fabric Loader installed

2.Click "Change Version" after selecting LWJGL 3

3.Try to select and change the version of LWGJL to anything else

Suspected cause: ??
---------------------------

Logs/Screenshots: 

----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info: After updating to Forge 34.0.0. in the instances where I have it installed, it automatically updated LWJGL to 3.2.2. and I can no longer downgrade to the recommended LWJGL version on those instances either.
---------------------------

**Comment by Zetabite** [comment]
You arent supposed to set it to something else. AFAIK, the menu is just a list of the versions that MMC uses, to display them, but cannot be changed as they are version specific.
