### ISSUE TITLE
Hanges after updating to lates DEV update

### ISSUE THREAD

**Issue by FeedTheChunk** [MultiMC/MultiMC5#3341]
System Information
-----------------------------
MultiMC version:  Current 0.6.12-dv-1467

Operating System: Win10

Summary of the issue or suggestion:
----------------------------------------------
Programs hangs after downloading latest update, "add a way to use native system versions of OpenAL and GLFW"  Downloads 2 files but hangs and doesn't seem to be installing the updated files(??) just hangs and have to force close.

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. From update screen: "Update Now"

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
i cannot recall MMC using that version scheme in dev. Where did you get MMC?

**Comment by FeedTheChunk** [comment]
It's from right here.  I've been signed up to the development channel for quite some time now. 

I got the version number from the title bar use shows  **MultiMC 5 - Version 0.6.12-develop-1467 on win32 - MultiMC 5**

I still can't update to the latest development version.

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
