### ISSUE TITLE
Launching two instances on the command-line

### ISSUE THREAD

**Issue by pierrep** [MultiMC/MultiMC5#3343]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: Linux

Summary of the issue or suggestion:
----------------------------------------------
I'm playing local co-op Minecraft, i.e.t. split screen via two different instances using controllers.
Currently I can launch one of them via the command line using `multimc -l "instance name"`
It would be amazing to be able to launch a second instance as a second command line option in order to fully automate my game launching process.
Am I right in assuming this isn't possible?

**Comment by NanoTrasen-Inc** [comment]
This should be possible, just not in one command on it's own.

Try executing MultiMC a second time shortly after the first instance has finished starting.
For example:
> $ **`multimc -l "instance 1"; sleep 5; multimc -l "instance 2"`**

However, if the instances share a similar name, you may encounter bug #3440, assuming it's affecting Linux too.
Keep this in mind.

**Comment by pierrep** [comment]
Ok thanks, I will give this a try

**Comment by pierrep** [comment]
Just putting this here for future reference, the shell script to do this is actually:
`multimc -l "instance 1" & multimc -l "instance 2"`
Otherwise the second instance is only launched after the first has ended (which is what you'd expect)
