### ISSUE TITLE
Minecraft resource version not found error code -1

### ISSUE THREAD

**Issue by gav1tron** [MultiMC/MultiMC5#3344]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: windows 10

Summary of the issue or suggestion: 
----------------------------------------------
trying to run vivecraft 1.16.X and the instance crashes and reads out Failed to find Minecraft resource version 1.16.3-20200911.084530 at E:\minecraft for vr stuff\mmc-stable win32\MultiMC\libraries\net\minecraftforge\forge\1.16.3-34.0.1\forge-1.16.3-34.0.1-client.jar
exited with code -1

What should happen:
------------------------------
the game should boot up in my VR and run minecraft

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. the exact instructions can be found here http://www.vivecraft.org/multimc/

Suspected cause:
---------------------------
unknown

Logs/Screenshots:
----------------------------
 https://paste.ee/p/FHf6i

Additional Info:
---------------------------
 no mods have been downloaded yet

**Comment by QuImUfu** [comment]
The instructions are faulty. You need to run the instance once before installing vivecraft, not only crate it. Alternatively create another instance with the same forge version and run it once. That should fix your current instance.

**Comment by QuImUfu** [comment]
@jrbudda you might wanna add a third step, something like "start that instance once" to http://www.vivecraft.org/multimc/, as forge-***-client.jar gets generated at first launch and the vivecraft instance seems (from this log) to rely on that file being there.

**Comment by jrbudda** [comment]
we have this fixed on our end for the next release already. also there is no vivecraft for 1.16.3 yet so idk what you're trying to run there....

**Comment by QuImUfu** [comment]
Thanks. Sorry, i didn't check that first. So @gav1tron use a older 1.13 release (e.g. 1.13.2) and run the instance once before installing vivecraft. Or wait for the next release.

**Comment by gav1tron** [comment]
i switched over to minecraft version 1.16.2 and it works without mods but as soon as i add mods it brings back the same error code

**Comment by QuImUfu** [comment]
you have installed a lot of mods for 1.16.1, but you are using minecraft 1.16.2 remove or update them. Or install vivecraft for 1.16.1 if the mods you want aren't available for 1.16.2

**Comment by gav1tron** [comment]
ok thankyou
