### ISSUE TITLE
"Failed to start Minecraft" -1

### ISSUE THREAD

**Issue by peterodavies27atgmailcom** [MultiMC/MultiMC5#3345]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 10 64-bit

Summary of the issue or suggestion: MC doesn't launch
----------------------------------------------

What should happen: MC should launch
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC

2. Click on Launch

3. Wait

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
https://pastebin.com/UKpqX33n
https://snipboard.io/2ircPA.jpg

Additional Info: None
---------------------------

**Comment by QuImUfu** [comment]
iceandfire requires LLibrary. Install it (https://www.curseforge.com/minecraft/mc-mods/llibrary)

**Comment by peterodavies27atgmailcom** [comment]
ok thanks
