### ISSUE TITLE
Crashing when toggle fullscreen is turned off in settings (exitcode 6)

### ISSUE THREAD

**Issue by Sour-Grape** [MultiMC/MultiMC5#3350]
System Information
-----------------------------
MultiMC version: 0.6.11-1370

Operating System: MacOS Mojave

Summary of the issue or suggestion: 
When I toggle fullscreen in the options of minecraft, it crashes with the following : libc++abi.dylib: terminating with uncaught exception of type NSException
Process crashed with exitcode 6.
----------------------------------------------

What should happen: The game should not crash
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch a modpack

2. Toggle fullscreen on 

3. Toggle fullscreen off

Suspected cause: I have no idea
---------------------------

Logs/Screenshots:
----------------------------
https://paste.ee/p/m7gTX

![Screen Shot 2020-09-22 at 7 54 45 pm](https://user-images.githubusercontent.com/71589508/93964629-b14eb780-fd92-11ea-9384-d606627dcad1.png)

Additional Info:
-----------------------------
Not sure it will help, but before I toggled fullscreen on, when i used the green button in the top right, not the game settings, it showed only the bottom left of the minecraft screen. I have tried with another modpack as well (Seablock: Rustic Waters), and the same issue occurs.

**Comment by Zetabite** [comment]
Check if the modpacks have similar mods and if they do, look what mod is causing this. Alterntively, see if changing the forge version does trick, in case of a buggy forge release

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
