### ISSUE TITLE
I tried installing All the Mods 5 (and some other packs too) and always got an issue like this

### ISSUE THREAD

**Issue by Sz4rv4s** [MultiMC/MultiMC5#3351]
Here is the log:
https://paste.ee/p/oC48h
If you could help me I would really appreciate it.
Thanks!

**Comment by 46620** [comment]
The log shows it's not finding forge, if you click "edit instance" and go to version you should be able to add forge from there.

**Comment by Sz4rv4s** [comment]
Thank you, I'll give it a try!

**Comment by Sz4rv4s** [comment]
It detects the correct forge (31.2.36) and still crashes.

**Comment by Sz4rv4s** [comment]
I tried to use latest forge, another crash

**Comment by HelveticaToast** [comment]
is it the same error?

**Comment by Sz4rv4s** [comment]
Yes

**Comment by Sz4rv4s** [comment]
I tried installing Stoneblock 2 now, the log is different.
https://paste.ee/p/pnNR5

**Comment by Janrupf** [comment]
Minetogether crashed the game, not sure why, but removing it should fix the crash.

**Comment by Sz4rv4s** [comment]
> Minetogether crashed the game, not sure why, but removing it should fix the crash.

You mean in SB2 or ATM5?
I'll give it a try.

**Comment by Janrupf** [comment]
Stoneblock 2

**Comment by Sz4rv4s** [comment]
I removed it, and it works! Thanks mate!

**Comment by Sz4rv4s** [comment]
The problem with ATM5 happens in every 1.15 and 1.16 pack, and not with 1.12 packs.
I hope somehow we find a soliution for that.

**Comment by peterix** [comment]
Use the official buyild of MultiMC from multimc.org
