### ISSUE TITLE
Could not Reserve enough space

### ISSUE THREAD

**Issue by HiBla** [MultiMC/MultiMC5#3352]
System Information
-----------------------------
MultiMC version: 5

Operating System: Linux

Summary of the issue or suggestion: Could not reserve enough space for object heap
----------------------------------------------

What should happen:
------------------------------
Minecraft should launch

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. I'm not sure

2.

3.

Suspected cause: I don't know
---------------------------

Logs/Screenshots:
----------------------------
https://paste.ee/p/0rhAq

Additional Info:
---------------------------

**Comment by QuImUfu** [comment]
how much RAM does your system have? (`sudo lshw -c memory` should give that information.

**Comment by HiBla** [comment]
3gb i think

**Comment by QuImUfu** [comment]
try reducing the maximum ram to 2GB, as you are using a 32bit java you won't be able to use more then 2-2,5 GB.  
Your CPU should support 64 bit, so using a 64 bit version of your OS and java might be a good alternative.

**Comment by HiBla** [comment]
This is what's happening when I do that.
https://paste.ee/p/5CeaV

**Comment by QuImUfu** [comment]
@peterix does Minecraft still support 32 bit systems with lwjgl3? 32bit versions of lwjgl3 do not seem to be included in the natives.

**Comment by phit** [comment]
it does not https://bugs.mojang.com/browse/MC-121388

**Comment by QuImUfu** [comment]
In that case @HiBla , either stick to minecraft versions below 1.13 or install the 64 bit version of whatever distribution you are currently using.
