### ISSUE TITLE
MultiMC crash when delete a instance

### ISSUE THREAD

**Issue by SciUnivMoring** [MultiMC/MultiMC5#3355]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: Windows 10 x64

Summary of the issue or suggestion:
----------------------------------------------
When I deleted an instance, MultiMC crashed. I checked the instance folder, the files on the hard disk of the corresponding instance was been deleted. When I restarted MultiMC, the instance is not in the instance list. 
So... It seemed that there was no problem when deleting the instance, but somehow MultiMC crashed.

What should happen:
------------------------------
When deleting an instance, MultiMC does not crash.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. start MultiMC and choose an instance

2. delete the instance

3. you will see MultiMC crash

Suspected cause:
---------------------------
Sorry, I don't know :(

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
If that happens again, provide the MultiMC.0.log here

**Comment by SciUnivMoring** [comment]
> If that happens again, provide the MultiMC.0.log here

Well... A magical thing happened. When I wanted to reproduce this problem, I deleted an instance, the instance have a custom package (when deleting this instance, the crash problem still exists), and then deleted another instance, the crash problem no longer exists.
