### ISSUE TITLE
How does one update a modpack in MultiMC?

### ISSUE THREAD

**Issue by oliverjanik** [MultiMC/MultiMC5#3356]
I appreciate there's some competition to the horrible Twitch app, but it seems MultiMC is missing a crucial feature. Updating a pack in Twitch is 1 click.

Ideally there would be:
1. Backup
2. Update
3. Easy rollback if necessary

**Comment by Zetabite** [comment]
The problem is that there is no twitch api that MMC could use to make it work in a good way. As long as their is no proper support from twitch side, there wont be any here

**Comment by oliverjanik** [comment]
Why is Twich API required? 

If I'm running Fabric loader what steps would be necessary to have modpack update functionality?

**Comment by Zetabite** [comment]
It isnt relevant if fabric or forge. You would need some kind of api to get the mods that need to be updated + where to get it from. This is stuff the mod hoster needs to provide so it can be fetched, which twitch doesnt. So besides asking them to make one (which efforts were made previously), or you get someone to make a new platform that does it, which is in the making but still takes time + in need of getting popular. Addtionaly, just updating a pack isnt always a good idea, cause updating mods can make them incompatible with others, due to changes made in the version.

**Comment by Zetabite** [comment]
So best you can do is make a new instance with the updated mods and then copy over the save files and stuff

**Comment by jamierocks** [comment]
> The problem is that there is no twitch api that MMC could use to make it work in a good way. As long as their is no proper support from twitch side, there wont be any here

The problem is that MMC doesn't track information about what pack an instance is running - once that is done, updating is something that can be looked at.

**Comment by Zetabite** [comment]
> > The problem is that there is no twitch api that MMC could use to make it work in a good way. As long as their is no proper support from twitch side, there wont be any here
> 
> The problem is that MMC doesn't track information about what pack an instance is running - once that is done, updating is something that can be looked at.

That too, but no efforts was made since there is not database to work with to make this happen in the first place, so you would track info you couldnt do anything with

**Comment by jamierocks** [comment]
I'm not entirely sure what your on about? Peterix has begun working on this (see https://github.com/MultiMC/MultiMC5/tree/feature/modpack_metadata).

**Comment by Zetabite** [comment]
I am not sure what you are on about

**Comment by oliverjanik** [comment]
How about this? Update instance from a zip file.

1. Take backup
2. replace all mods
3. keep save data

Done.

It's not auto update, but would help with managing the files and directories, which is a daunting task for non-technical users/players.

**Comment by mkaito** [comment]
There's usually more that you would want to keep, such as map data and prestige and so on. Depends on the pack. But if all you want from this is "install pack, copy folders", isn't that far easier to just do by hand anyway?

**Comment by DeathOfTime** [comment]
i would appreciate this too. from what i have seen of modpacks for the most part it would just work to delete whatever subfolders it creates and copy over the new ones. so if i downloaded a zip file to update atm6 say and it downloaded a mods folder, kubejs folder, and config folder then the old folders and there contents would be deleted. then the new ones added in

might need some minor changes to that. like blocking any changes to the saves folder or erroring out if there are any. maybe a blacklisting or asking for input if user selected files are copied over. like a user could lock the botania config file and that wouldn't be deleted and would merge with the update or they would be asked if they wanted it replaced

no it isn't easier to do it by hand. it is much easier to do it in the app. from what i have seen only certain stuff changes. a difference isn't needed just a blanket delete folder contents and copy in new contents. maybe a warning everyone can ignore about how it is a very simplistic implimentation and issues leading to the loss of save data or world corruption can result

**Comment by Zetabite** [comment]
i mean, i can see it being easier, but it would be so rarely used, since many modpacks just break saves when updating, or dont need necessarly updating

**Comment by Spongman** [comment]
> isn't that far easier to just do by hand anyway?
so is weaving.

**Comment by TheCultLeader666** [comment]
How do launchers like GDLauncher accomplish this?

**Comment by peterix** [comment]
Mostly by narrowing their focus to the point where they can ignore the million other issues.

**Comment by peterix** [comment]
Anyway, to answer the question: just import a new version of the pack and move over saves.

**Comment by TheCultLeader666** [comment]
Why can’t a feature at least be implemented to do it automatically?

Check the version against the latest twitch version, download the pack, create it as a new instance, move the saves over, and keep the copy until the next update?

You say in another thread that the only reason this was even implemented was to bring curseforge to Linux, but you’re implementation can’t hold a torch to GDLauncher’s, even if it has a million other issues. If I was a Linux user and needed to use cf modpacks, GDLauncher would be a much better option, even if it’s really buggy, as this is a crucial feature. If I have to do all that work to update, why give the option to import a pack as an instance at all.

**Comment by peterix** [comment]
The original question has been answered and anything GDLauncher does is entirely irrelevant to MultiMC.
