### ISSUE TITLE
Symlinks flattened when copying instance

### ISSUE THREAD

**Issue by ChloeDawn** [MultiMC/MultiMC5#3357]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 10.0.19041

Summary of the issue or suggestion:
----------------------------------------------
Symlinks are flattened when copying an instance, resulting in all the contents of symlinked directories being copied to the new root.

What should happen:
------------------------------
Symlinks should be copied as they are, without flatenning.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a file or directory symlink within an instance folder.

2. Copy the instance to a new name.

3. Symlinked files and directories are flattening in the new location.

**Comment by Zetabite** [comment]
Symlinks arent support by MMC, additionaly, on Windows they are barely working. You are on your own.

**Comment by ChloeDawn** [comment]
Could you provide some sources for this? They work perfectly fine for me and have done for quite some time.

**Comment by MarkusG** [comment]
Seems to be Windows-specific. I'm unable to reproduce on Linux.
MultiMC version:
```
Version 0.6.11-custom
Git 0f1eb839ce69b5977e9db4ed88b5ca4a871451b7
```

**Comment by peterix** [comment]
This is intended.
