### ISSUE TITLE
MultiMC Won't Install Any Mods (not modpacks)

### ISSUE THREAD

**Issue by WiggleyOtter** [MultiMC/MultiMC5#3358]
When I copy the file location from Cursedforge and paste it into MultiMC and click "OK" it'll show a progress bar then pop up an error message, I have no clue what is going on. My computer refused to let me attach video and picture to this website, sorry.

**Comment by Zetabite** [comment]
You cannot just copy the file location from cursedforge. You either download the zip from curseforge and import that, or you use the release of MMC that has the Twitch Modpack downloader

**Comment by jcotton42** [comment]
> or you use the release of MMC that has the Twitch Modpack downloader

@Zetabite is that just modpacks or individual mods as well? If the latter which release is that, the current dev?

**Comment by QuImUfu** [comment]
Download the mod and add it to an instance. That's how you install a mod from CurseForge.
