### ISSUE TITLE
Whenever i try to install forge to minecraft through MultiMC (Any Version,i tried on 1.16.3) it just crashes

### ISSUE THREAD

**Issue by max123123124** [MultiMC/MultiMC5#3359]
System Information
-----------------------------
MultiMC version:MultiMC 5

Operating System: Windows 64-bit

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.just install forge on 1.16.3 through instance settings

Logs/Screenshots:
----------------------------

MultiMC version: 0.6.

Minecraft folder is:
D:/Gry/MultiMC/instances/1.16.3/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_261, using 64-bit architecture.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  D:/Gry/MultiMC/instances/1.16.3/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  D:/Gry/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  D:/Gry/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  D:/Gry/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  D:/Gry/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  D:/Gry/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  D:/Gry/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  D:/Gry/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  D:/Gry/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  D:/Gry/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  D:/Gry/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  D:/Gry/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  D:/Gry/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  D:/Gry/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  D:/Gry/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  D:/Gry/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  D:/Gry/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  D:/Gry/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  D:/Gry/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  D:/Gry/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  D:/Gry/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  D:/Gry/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  D:/Gry/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  D:/Gry/MultiMC/libraries/com/mojang/authlib/1.6.25/authlib-1.6.25.jar
  D:/Gry/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  D:/Gry/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  D:/Gry/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  D:/Gry/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  D:/Gry/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  D:/Gry/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar
  D:/Gry/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.11.2/log4j-core-2.11.2.jar
  D:/Gry/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  D:/Gry/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/1.4.2/ForgeWrapper-1.4.2.jar
  D:/Gry/MultiMC/libraries/net/minecraftforge/forge/1.16.3-34.1.0/forge-1.16.3-34.1.0-launcher.jar
  D:/Gry/MultiMC/libraries/org/ow2/asm/asm/7.2/asm-7.2.jar
  D:/Gry/MultiMC/libraries/org/ow2/asm/asm-commons/7.2/asm-commons-7.2.jar
  D:/Gry/MultiMC/libraries/org/ow2/asm/asm-tree/7.2/asm-tree-7.2.jar
  D:/Gry/MultiMC/libraries/org/ow2/asm/asm-util/7.2/asm-util-7.2.jar
  D:/Gry/MultiMC/libraries/org/ow2/asm/asm-analysis/7.2/asm-analysis-7.2.jar
  D:/Gry/MultiMC/libraries/cpw/mods/modlauncher/7.0.1/modlauncher-7.0.1.jar
  D:/Gry/MultiMC/libraries/cpw/mods/grossjava9hacks/1.3.0/grossjava9hacks-1.3.0.jar
  D:/Gry/MultiMC/libraries/net/minecraftforge/accesstransformers/2.2.0-shadowed/accesstransformers-2.2.0-shadowed.jar
  D:/Gry/MultiMC/libraries/net/minecraftforge/eventbus/3.0.3-service/eventbus-3.0.3-service.jar
  D:/Gry/MultiMC/libraries/net/minecraftforge/forgespi/3.1.1/forgespi-3.1.1.jar
  D:/Gry/MultiMC/libraries/net/minecraftforge/coremods/3.0.0/coremods-3.0.0.jar
  D:/Gry/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  D:/Gry/MultiMC/libraries/com/electronwill/night-config/core/3.6.2/core-3.6.2.jar
  D:/Gry/MultiMC/libraries/com/electronwill/night-config/toml/3.6.2/toml-3.6.2.jar
  D:/Gry/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  D:/Gry/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.0/maven-artifact-3.6.0.jar
  D:/Gry/MultiMC/libraries/net/jodah/typetools/0.8.1/typetools-0.8.1.jar
  D:/Gry/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  D:/Gry/MultiMC/libraries/org/spongepowered/mixin/0.8.1/mixin-0.8.1.jar
  D:/Gry/MultiMC/libraries/com/mojang/minecraft/1.16.3/minecraft-1.16.3-client.jar

Native libraries:
  D:/Gry/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  D:/Gry/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  D:/Gry/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  D:/Gry/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  D:/Gry/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  D:/Gry/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  D:/Gry/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  D:/Gry/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2060m, -Xmx14000m, -Duser.language=en, -Djava.library.path=D:/Gry/MultiMC/instances/1.16.3/natives, -cp, D:/Gry/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar;D:/Gry/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar;D:/Gry/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar;D:/Gry/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar;D:/Gry/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar;D:/Gry/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar;D:/Gry/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar;D:/Gry/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar;D:/Gry/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar;D:/Gry/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar;D:/Gry/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar;D:/Gry/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar;D:/Gry/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar;D:/Gry/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar;D:/Gry/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar;D:/Gry/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar;D:/Gry/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar;D:/Gry/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar;D:/Gry/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar;D:/Gry/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar;D:/Gry/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar;D:/Gry/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar;D:/Gry/MultiMC/libraries/com/mojang/authlib/1.6.25/authlib-1.6.25.jar;D:/Gry/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar;D:/Gry/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar;D:/Gry/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar;D:/Gry/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar;D:/Gry/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar;D:/Gry/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar;D:/Gry/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.11.2/log4j-core-2.11.2.jar;D:/Gry/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar;D:/Gry/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/1.4.2/ForgeWrapper-1.4.2.jar;D:/Gry/MultiMC/libraries/net/minecraftforge/forge/1.16.3-34.1.0/forge-1.16.3-34.1.0-launcher.jar;D:/Gry/MultiMC/libraries/org/ow2/asm/asm/7.2/asm-7.2.jar;D:/Gry/MultiMC/libraries/org/ow2/asm/asm-commons/7.2/asm-commons-7.2.jar;D:/Gry/MultiMC/libraries/org/ow2/asm/asm-tree/7.2/asm-tree-7.2.jar;D:/Gry/MultiMC/libraries/org/ow2/asm/asm-util/7.2/asm-util-7.2.jar;D:/Gry/MultiMC/libraries/org/ow2/asm/asm-analysis/7.2/asm-analysis-7.2.jar;D:/Gry/MultiMC/libraries/cpw/mods/modlauncher/7.0.1/modlauncher-7.0.1.jar;D:/Gry/MultiMC/libraries/cpw/mods/grossjava9hacks/1.3.0/grossjava9hacks-1.3.0.jar;D:/Gry/MultiMC/libraries/net/minecraftforge/accesstransformers/2.2.0-shadowed/accesstransformers-2.2.0-shadowed.jar;D:/Gry/MultiMC/libraries/net/minecraftforge/eventbus/3.0.3-service/eventbus-3.0.3-service.jar;D:/Gry/MultiMC/libraries/net/minecraftforge/forgespi/3.1.1/forgespi-3.1.1.jar;D:/Gry/MultiMC/libraries/net/minecraftforge/coremods/3.0.0/coremods-3.0.0.jar;D:/Gry/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar;D:/Gry/MultiMC/libraries/com/electronwill/night-config/core/3.6.2/core-3.6.2.jar;D:/Gry/MultiMC/libraries/com/electronwill/night-config/toml/3.6.2/toml-3.6.2.jar;D:/Gry/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar;D:/Gry/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.0/maven-artifact-3.6.0.jar;D:/Gry/MultiMC/libraries/net/jodah/typetools/0.8.1/typetools-0.8.1.jar;D:/Gry/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar;D:/Gry/MultiMC/libraries/org/spongepowered/mixin/0.8.1/mixin-0.8.1.jar;D:/Gry/MultiMC/libraries/com/mojang/minecraft/1.16.3/minecraft-1.16.3-client.jar, io.github.zekerzhayard.forgewrapper.installer.Main]

Minecraft process ID: 3872

Exception in thread "main" java.lang.RuntimeException: Can't detect the forge installer!
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:109)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:120)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:23)
Process exited with code 1.

**Comment by Zetabite** [comment]
You are using an unofficial built that isnt from any reputable source. Find official repos and downloads here: https://multimc.org/

**Comment by Scotsguy** [comment]
Closing, unofficial MultiMC build.
