### ISSUE TITLE
Rename the instance folder when renaming instances

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#336]
What the title says.

**Comment by nicowaves** [comment]
This has been bugging me for a very long time now. I hope I don't sound ungrateful or pushy - you are doing a great job with this - but could you guys please fix this soon? It has the 'confirmed' tag for quite some time now and I don't know how hard this is to implement, but it would be awesome if it could be done.

**Comment by peterix** [comment]
Not too hard. Definitely possible to do, at least for instances that are inside the instances folder.

**Comment by nicowaves** [comment]
Thanks a lot!

**Comment by peterix** [comment]
Actually, let's do this. It's *should* be small and simple.

**Comment by peterix** [comment]
duplicate of #176
