### ISSUE TITLE
 Automatic search Java is not friendly to LibericaJDK

### ISSUE THREAD

**Issue by huangsijun17** [MultiMC/MultiMC5#3363]
System Information
-----------------------------
MultiMC version:
0.6.12
Operating System:
Windows 10
Summary of the issue or suggestion:
----------------------------------------------

I installed LibericaJDK automatically with Winget. But MMC does not recognize this Java.

What should happen:
------------------------------

MMC automatically recognizes the Java installed by Winget.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install [Winget](https://github.com/microsoft/winget-cli)

2. Install JDK by Winget:
`winget install BellSoft.LibericaJDK8`

3. Take MultiMC to find Java automatically.

Suspected cause:
---------------------------

Not compatible with this Java installation method.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

![image](https://user-images.githubusercontent.com/31504595/94998130-22d40480-05e2-11eb-911d-1f1861ddb130.png)
![image](https://user-images.githubusercontent.com/31504595/94998137-2e273000-05e2-11eb-86d8-ce5ef4e07ee5.png)

Additional Info:
---------------------------

**Comment by LordMZTE** [comment]
well multimc cant be compatible with all JDKs so if you are gonna use this one, youll have to select the path manually

**Comment by huangsijun17** [comment]
> well multimc cant be compatible with all JDKs so if you are gonna use this one, youll have to select the path manually

This JDK is provided in the [Winget](Winget) tool developed by Microsoft. 
In the future, more and more people will automatically install java8 using Winget.

**Comment by LordMZTE** [comment]
this has nothing to do with winget. the issue is that you are not using oracle jdk, open jdk or any jdk that multimc knows about. multimc, to my knowledge, just searches for java, accounting for the paths of the jdks it know. it doesnt know LibericaJDK apparently
