### ISSUE TITLE
Windows 10 Scale and Layout Problems

### ISSUE THREAD

**Issue by Natroid-5** [MultiMC/MultiMC5#3365]
MultiMC version:
---------------------------------------------
MultiMC 5 -  Version 0.6.11 - 1430 on win32

Operating System:
--------------------------------------------
Windows 10 64 bit

Summary of the issue or suggestion:
---------------------------------------------------------------------------------------------
When "Scale and Layout" under "Display" settings is set higher than 100%, all instances launched from MultiMC are set off screen and when maximized (through F11 or otherwise) all UI buttons are off screen.

What should happen:
The game should launch in the center of the screen and when maximized, all UI options should be visible.

Steps to reproduce the issue (Add more if needed):
--------------------------------------------------------------
1. In the display setting of Windows 10, set the scale to a higher percentage.

2. Launch any instance from MultiMC. Instance will be off screen, most likely far lower right.

3. From Task Manager, right click the pack process and click maximize.

4. Press F11 to full screen the application to show misplace UI.

Suspected cause:
----------------------------------------
MultiMC doesn't respond to changes in scale well

**Comment by phit** [comment]
does this not happen with the vanilla Minecraft launcher aswell?

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.

**Comment by jumble** [comment]
@Natroid-5 I have found a solution to this problem. It will allow you to run on displays with scaling.

Unfortunately this solution is not ideal as it involves editing the Windows properties of a Java runtime- this will cause any Java applications which run on that Java runtime to ignore display settings, not just Minecraft. If you have other such applications, it may pay to download and use a separate Java executable just for the Minecraft instance/s in question before completing the following steps.

- In the MultiMC settings for your instance, find out the path to the Java executable being used. (Settings > Java > Java Runtime > Java Path)
- In Windows Explorer, navigate to the folder which contains that Java executable.
- Right-click the Java executable itself and select Properties.
- In the Properties dialog, under the Compatibility tab, under the Settings subheading, you will see a button labeled "Change High DPI Settings". Click that.
- Ensure the "Use this setting to fix scaling problems....." and "Override high DPI scaling behavior. ..." checkboxes are checked.
- Ensure that the "Scaling performed by:" dropdown reads "Application".
- Press OK to close all Properties dialogs.

Good luck! :)

**Comment by EvanOfTheAces** [comment]
jumble your solution doesn't work for me. I don't know why. The only thing that's managed to fix this is to set my windows scaling to 100%.

**Comment by phit** [comment]
@EvanOfTheAces try this https://files.multimc.org/downloads/mmc-stable-win32-5.15.2.zip

**Comment by EvanOfTheAces** [comment]
Thanks. The file you sent fixed the scaling issue, but added issues with java. For anyone with the same issue, you need to download java 17 specifically and manually set the correct java version for your instances. Not a bad compromise in my opinion. Thanks again.

**Comment by jumble** [comment]
Nice- glad you found a solution!

**Comment by yikaii** [comment]
I'm having the same issue as well but both jumble's and phit's solutions do not work for me
