### ISSUE TITLE
ig7icd64.dll+0x22ee7 issue 

### ISSUE THREAD

**Issue by luckidyck** [MultiMC/MultiMC5#3367]
System Information
-----------------------------
MultiMC version: 0.6.11-1430 on win32

Operating System: windows 10 pro

Summary of the issue or suggestion:
----------------------------------------------
so after i launched 1.12.2 minecraft with labys mod, it keep crashes (more info below) even if i launch vanilla minecraft 1.12.2 it still crashes, i tried to find the solution by reinstalling multimc and 1.12.2 but its not working.

What should happen:
------------------------------
it should run smoothly without crashing 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. launch minecraft

Suspected cause:
---------------------------
not sure, either java, gpu or idk i tried to reinstall java too still not working

Logs/Screenshots:
----------------------------
labys mod log https://paste.ee/p/S4yhf#s=1
vanilla 1.12.2 log https://paste.ee/p/C5WuV

**Comment by Zetabite** [comment]
https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs

**Comment by luckidyck** [comment]
> https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs

okay i will try tmr and update
