### ISSUE TITLE
all my skins will not load

### ISSUE THREAD

**Issue by slothlover3** [MultiMC/MultiMC5#3369]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
Provide log when this happens: https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by Shyraptors** [comment]
https://paste.ee/p/M7j5W
@Zetabite 
I give you my logl, I have the same problems, I can't see any skins and same for player's head

**Comment by phit** [comment]
Add this to your Java arguments to make Minecraft prefer IPv4 over IPv6:
`-Djava.net.preferIPv4Stack=true`

**Comment by Shyraptors** [comment]
OK It's good!!!! Thank you very much :)
