### ISSUE TITLE
Session server always down

### ISSUE THREAD

**Issue by UltraBlackLinux** [MultiMC/MultiMC5#3370]
System Information
-----------------------------
MultiMC version: doesn't matter

Operating System: doesn't matter

Summary of the issue or suggestion: Multimc shows the session server as always down
----------------------------------------------

Suspected cause:
---------------------------
Microsoft Propably Changed some data request stuff or moved the server. So either remove that Indicator or update it
You seem to retrieve your infos from https://status.mojang.com/check - those seem outdated, since the session servers are up.

Logs/Screenshots:
----------------------------
![Screenshot_20201010_230745](https://user-images.githubusercontent.com/62404294/95665102-6a601080-0b4d-11eb-9e5b-62874c8df25f.png)

**Comment by Zetabite** [comment]
we know.

**Comment by Janrupf** [comment]
Duplicate of #3199

**Comment by UltraBlackLinux** [comment]
oh well xD
