### ISSUE TITLE
Cannot import modpack from zip.

### ISSUE THREAD

**Issue by Colonizor48** [MultiMC/MultiMC5#3371]
System Information
-----------------------------
MultiMC version:

Operating System: windows 10

Summary of the issue or suggestion: The download bar freezes right a tthe end of downloading. making it basicly impossible to install modpacks.
----------------------------------------------

What should happen:I download the modpack normaly
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Try to import a modpack

2. Wait for 5 hours as it tries to install but just doesnt

3.cry

Suspected cause:
---------------------------
idk

Logs/Screenshots:
----------------------------
[
[MultiMC-1.log](https://github.com/MultiMC/MultiMC5/files/5360235/MultiMC-1.log)

Additional Info:
---------------------------
This has a been a critical bug for a year at this point. It should really be fixed

**Comment by Colonizor48** [comment]
How do u install a modpack from a zip in the meantime while this is fixed?

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
