### ISSUE TITLE
I am using a fabric mod and I cant join servers. I know the issue is on multimc because I can join that server with the same fabric mod on normal mc. Can anyone help me please???

### ISSUE THREAD

**Issue by Alprolol** [MultiMC/MultiMC5#3374]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Alprolol** [comment]
ok it somehow magically got fixed...

**Comment by recursivetree** [comment]
then please close it
