### ISSUE TITLE
I modified the Assets; Libraries download address to Chinese mirror

### ISSUE THREAD

**Issue by graytoowolf** [MultiMC/MultiMC5#3375]
我修改Assets; Libraries下载地址为中国镜像，能发布在中国吗? 我保证只修改下载地址,其他所有信息都不做任何修改，保证作者权益.

I modified the Assets; Libraries download address to be a Chinese mirror, can it be published in China? I guarantee that only the download address will be modified, and all other information will not be modified in any way. The rights of the author are guaranteed

**Comment by baka-gourd** [comment]
我们使 MultiMC 保持开源，因为我们认为能够看到像这样的项目的源代码很重要，并且我们使用 Apache 许可证。
使用 Apache 许可证的原因之一是我们不希望其他人在重新分配项目时使用 "MultiMC" 的名称。这意味着其他人必须在项目源代码中移除所有提及 "MultiMC" 的部分，这包括但不仅限于项目图标及窗口标题（标题中不应有 MultiMC-fork）。
Apache 许可证说明了该名称的合理用途 - 在“关于”对话框中提及了项目的来源，并且该许可证是可以接受的。尽管如此，非常清楚的是，该项目是一个分支，而不是意味着您拥有我们的权利。

**Comment by phit** [comment]
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3164
