### ISSUE TITLE
Update and rollback failed when updating from really old MultiMC version

### ISSUE THREAD

**Issue by Novocastrian** [MultiMC/MultiMC5#3379]
System Information
-----------------------------
MultiMC version: 0.5.0-945

Operating System: Windows 10 home (latest)

Summary of the issue or suggestion:
----------------------------------------------
Launched MultiMC from my dropbox folder and started the update process, but I forgot to stop the dropbox process beforehand. Naturally, the client failed to update, as dropbox hadn't released control of the files. This is the error I got in the client: 
![image](https://user-images.githubusercontent.com/4601813/95930450-336e5100-0e12-11eb-824b-64bf452e5754.png)

Now, whenever I try to launch the .exe file (dropbox process isn't running), i get these errors: 
![image](https://user-images.githubusercontent.com/4601813/95930471-42ed9a00-0e12-11eb-8a57-149d49976d13.png)
![image](https://user-images.githubusercontent.com/4601813/95930579-86e09f00-0e12-11eb-8401-71b5cf982cce.png)
![image](https://user-images.githubusercontent.com/4601813/95930596-8e07ad00-0e12-11eb-9be5-8c814d3b18e1.png)

What should happen:
------------------------------
MultiMC launches and updates as per normal. 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Store MultiMC in dropbox directory (local file mode)

2. with all files stored locally, and dropbox running in the background, launch MultiMC.exe

3. When prompted to update, start the update process.

Suspected cause:
---------------------------
MultiMC trying to update when another process (dropbox.exe) has a hold of the files.

Logs/Screenshots:
----------------------------
[MultiMC-0.log](https://paste.ee/p/9JFUP)

Additional Info:
---------------------------
I assume there isn't a fix to this except for manually downloading the latest version then moving some folders into the new directory, correct? Which folders do I need to move to keep my settings, backups and instances?

**Comment by kb-1000** [comment]
First, make a backup of the whole MultiMC folder, then replace the binaries in the old folder with a new version from the ZIP. (Just extract the files into there and let replace existing ones)

**Comment by Novocastrian** [comment]
Yep, that did the trick! Thanks for the quick response :)
