### ISSUE TITLE
An option to keep the launcher open whilst playing?

### ISSUE THREAD

**Issue by DeathHammer000** [MultiMC/MultiMC5#338]
I was playing around with the Forge prerelease, when I decided to update some of my instances - when I realised that I had already opened another instance. The launcher closed and the console popped up.

I had to open another window, but I felt that if I used all of the features, I'd get an error.

What I would like to see is an option that keeps the original window open, as well as saying which instances are open and storing changes made to them for next time (i.e. when an instance closes, any changes made are saved).

Thanks.

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Running multiple instances)](https://workflowy.com/s/2EyDMcp7CU)

This is a big one... and also needed if we want to add server support.

**Comment by peterix** [comment]
Done.
