### ISSUE TITLE
Burps in MULTIMC Minecraft 1.8.9

### ISSUE THREAD

**Issue by AggamR** [MultiMC/MultiMC5#3381]
System Information
-----------------------------
MultiMC version: 0.6.7

Operating System: Ubuntu

Summary of the issue or suggestion: 
----------------------------------------------
Minecraft burps a lot. Massive freeses for like half-a-second each time. using 1.8.9 forge.

What should happen:
------------------------------
Minecraft will run normaly.

Suspected cause:
---------------------------
IDK

Logs/Screenshots:
----------------------------
Java settings:
![image](https://user-images.githubusercontent.com/50958945/96011168-43eeed80-0e4b-11eb-9c56-62272440dcd8.png)
Versions of things:
![image](https://user-images.githubusercontent.com/50958945/96011332-7862a980-0e4b-11eb-9d21-312904d1f8ff.png)

Logs: https://pastebin.com/nUvyb3wq

**Comment by QuImUfu** [comment]
enable OptiFines lagometer (options->Video Settings->other) and look what color the lag-spike frames have.

**Comment by Scotsguy** [comment]
This is not a MultiMC issue, closing.
