### ISSUE TITLE
Pewter problem with tinker's evolution osmium cfg

### ISSUE THREAD

**Issue by peterodavies27atgmailcom** [MultiMC/MultiMC5#3382]
System Information
-----------------------------
MultiMC version: 0.6.11-1430 on win32

Operating System: Win 10

Summary of the issue or suggestion: MC launches but then crashes after a few moments
----------------------------------------------

What should happen: There should be no error and MC should start
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Start MC

2. Wait

Suspected cause: DeepResonance
---------------------------

Logs/Screenshots: https://pastebin.com/nFt8c4GV   https://pasteboard.co/JvOvc4V.png
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info: None
---------------------------

**Comment by QuImUfu** [comment]
probably an incompatibility with you ancient version of DeepResonance and your new version of mcjtylib. Update DeepResonance.

**Comment by peterodavies27atgmailcom** [comment]
that seems to have worked, and i needed to change my eleccore to a more updated version but now i'm getting another error now with mystical world. here's the log: https://pastebin.com/AeFy3U7t

**Comment by QuImUfu** [comment]
update mysticallib.

**Comment by peterodavies27atgmailcom** [comment]
That was weird, it didn't show i had one in my mods, but it was in the mods folder. anyways, I updated it but now I have this:  https://ctxt.io/2/AAAgOadJFA
do i need to update asmodeuscore?

**Comment by QuImUfu** [comment]
update GalaxySpace.

**Comment by peterodavies27atgmailcom** [comment]
oh ok

**Comment by peterodavies27atgmailcom** [comment]
so I did that, but now a problem with integrated dynamics: https://ctxt.io/2/AAAgC7BiFw  something about a guide book

**Comment by peterodavies27atgmailcom** [comment]
https://justpaste.me/U9Ir
it expired

**Comment by kb-1000** [comment]
That looks like an impcompatible library mod version. Look up what version of Cyclops Core your version of Integrated Dynamics requires.

**Comment by peterodavies27atgmailcom** [comment]
hmm, still happening

**Comment by peterodavies27atgmailcom** [comment]
so I got _that_ to work, but now___ with nuclearcraft, it says nc/item/armor/ItemHazmatSuit. https://write.as/vze0aby7xhu18.md

**Comment by peterodavies27atgmailcom** [comment]
nevermind all I had to do was update ic2

**Comment by Janrupf** [comment]
Please close the issue if all the problems are resolved now

**Comment by peterodavies27atgmailcom** [comment]
no, now theres a problem with more planets

**Comment by peterodavies27atgmailcom** [comment]
https://write.as/1jp1uflxgtwm5.md cant tell if its with more planets or galacticraft core

**Comment by Janrupf** [comment]
Please upload the log to paste.ee, it is unreadable (and incomplete?) on the site you linked.

**Comment by peterodavies27atgmailcom** [comment]
https://paste.ee/p/YfNy6

**Comment by QuImUfu** [comment]
probably MorePlanets beeing to old for the version of galacticraft.  
At this point you might wanna think about "simply" updating all the mods...

**Comment by peterodavies27atgmailcom** [comment]
so i updated more planets but now pewter is having a problem with tinker's evolution: https://paste.ee/p/49K5g

**Comment by QuImUfu** [comment]
Look into the config files. A lot of mods add the same materials to tcon, conflicting. You can disable materials in the configs of most of these mods. Disable all duplicates. Some mods do not generate their config file before they crash, to make them generate it, temporarily disable all conflicting mods.

**Comment by peterodavies27atgmailcom** [comment]
ok thanks i will

**Comment by peterodavies27atgmailcom** [comment]
which mod's osmium should I keep?

**Comment by peterodavies27atgmailcom** [comment]
how do I edit this (I've never done it from the actual file)
https://paste.ee/p/PrdXo

**Comment by LordMZTE** [comment]
this is really funny :P youll probably end up updating your whole pack

**Comment by QuImUfu** [comment]
probably like this:  
```
    S:disabledMaterials <
        osmium
     >
```

**Comment by peterodavies27atgmailcom** [comment]
I have totally wrecked my MultiMC, so I will reopen this or make a new issue when I've fixed it. (Also I will probably update all the mods in the pack cause I have to remake it anyways)
