### ISSUE TITLE
Can't install Forge 34.1.21 - not on the list

### ISSUE THREAD

**Issue by BaccarWozat** [MultiMC/MultiMC5#3383]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Win10

Summary of the issue or suggestion:
----------------------------------------------
A 1.16.3 mod updated and required the new Forge 34.1.21, but the list of Forges to choose from only went to 34.1.19, so the mod won't run.

What should happen:
------------------------------
Newest Forge should be on the list, or at least a reason it is not should be available somewhere.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add a mod that requires 34.1.21 (Oh The Biomes You'll Go 1.0.8)

2. Attempt to change Forge version.

Suspected cause:
---------------------------
Perhaps the new Forge versions are being distributed differently? That's been the reason with previous unavailable Forges.

**Comment by phit** [comment]
1.16.4-pre1 release broke the metadata updater so nothing is getting refreshed right now, give it a bit I'm sure it will be fixed sometime this weekend

**Comment by BaccarWozat** [comment]
Works now. Thanks!
