### ISSUE TITLE
i cant login it says authenication canceled for some reason when i try to login i treid multiple times and it dosent let me can u please fix it

### ISSUE THREAD

**Issue by haddow2030** [MultiMC/MultiMC5#3384]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by haddow2030** [comment]
i dont know what to do if u can help me id really apprecaite it thank u

**Comment by SomethingGeneric** [comment]
We're gonna need more info my friend

**Comment by Virusnest** [comment]
Hi is your minecraft account linked to a microsoft account or have you crated yourr account after december 1st

**Comment by wb1016** [comment]
info needed. read wiki.

**Comment by SomethingGeneric** [comment]
But why would you necro-bump

**Comment by Forkk** [comment]
Please fill out the issue form correctly next time. There is not enough information provided here for anyone to help you.
