### ISSUE TITLE
Minecraft Beta 1.7.3 Refuses To Launch

### ISSUE THREAD

**Issue by alco2024** [MultiMC/MultiMC5#3386]
System Information
-----------------------------
MultiMC version: MultiMC 0.6.11-1370

Operating System: macOS Catalina

Summary of the issue or suggestion: Whenever an attempt to launch Minecraft Beta 1.7.3, a black screen is the only thing that appears.
----------------------------------------------
What should happen: Minecraft Beta 1.7.3 should launch
------------------------------
Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create an instance of Beta 1.7.3

2. Attempt to launch said instance

3. Whenever the accessibility prompt comes up, accept it, and restart MultiMC

4. Launch the instance again

Suspected cause:
---------------------------
No idea, to be honest. Most likely something to do with net.java.games.input.ControllerEnvironment

Logs/Screenshots:
----------------------------
Log Upload: [paste.ee](https://paste.ee/p/csFk6)

Screenshot Upload 1: [prnt.sc](https://prnt.sc/v0xvdi)

Additional Info:
----------------------------
1. The instance of Beta 1.7.3 is in vanilla, so no mods that could be causing the issue.

2. While the logs are technically incomplete, that is the only thing that happens, at least for the 5 minutes I left it open.

(This is my first time filling out an issue, so please don't hurt me if I did anything wrong.)

**Comment by 69420XD** [comment]
Download an older Java Version here (jdk8u232-b09): https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=hotspot

You will need to uninstall Java first before installing the older version listed above: https://explainjava.com/uninstall-java-macos/

**Comment by alco2024** [comment]
> Download an older Java Version here (jdk8u232-b09): https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=hotspot
> 
> You will need to uninstall Java first before installing the older version listed above: https://explainjava.com/uninstall-java-macos/

Will this older version work with more modern versions of Minecraft? I would like to retain that compatibility.

**Comment by 69420XD** [comment]
> > Download an older Java Version here (jdk8u232-b09): https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=hotspot
> > You will need to uninstall Java first before installing the older version listed above: https://explainjava.com/uninstall-java-macos/
> 
> Will this older version work with more modern versions of Minecraft? I would like to retain that compatibility.

Yup.

**Comment by alco2024** [comment]
> > > Download an older Java Version here (jdk8u232-b09): https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=hotspot
> > > You will need to uninstall Java first before installing the older version listed above: https://explainjava.com/uninstall-java-macos/
> > 
> > 
> > Will this older version work with more modern versions of Minecraft? I would like to retain that compatibility.
> 
> Yup.

Ok, I'll try this later. Motel wifi won't let me download it easily.

**Comment by alco2024** [comment]
> > > Download an older Java Version here (jdk8u232-b09): https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=hotspot
> > > You will need to uninstall Java first before installing the older version listed above: https://explainjava.com/uninstall-java-macos/
> > 
> > 
> > Will this older version work with more modern versions of Minecraft? I would like to retain that compatibility.
> 
> Yup.

Okay, this solution has worked! I will close this issue. Thank you!
