### ISSUE TITLE
Clicking on an icon automatically opens an instance

### ISSUE THREAD

**Issue by DoctorBang** [MultiMC/MultiMC5#3391]
System Information
-----------------------------
MultiMC version:
*MultiMC 5 - 0.6.11*

Operating System:
*EndeavourOS*
 
Summary of the issue or suggestion:
----------------------------------------------
When clicking on an icon for an instance, it automatically launches the instance. 

What should happen:
------------------------------
I should be able to click on it and be able to select the instance in order to either edit mods, or any other options. I have confirmed that this does not happen on Windows (I have tested it there too).

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install MultiMC on EndeavourOS

2. Select an instance and click on it.

3. In order to change settings, it is necessary to hit abort in order to prevent the instance from running.

Suspected cause:
---------------------------
It's either a bug in the code, or something to do with my mouse. I doubt the latter because I have had no issues with any other program.

Logs/Screenshots:
----------------------------
Logs don't seem relevant here, but let me know if you some kind of log.

Additional Info:
---------------------------

**Comment by QuImUfu** [comment]
What desktop environment are you using?

**Comment by QazCetelic** [comment]
I am also experiencing this behavior, I didn't think this was unintentional. 
I'm using the KDE Plasma DE, which can be used on EndeavourOS so OP could also be using it.

**Comment by QuImUfu** [comment]
It is an KDE Plasma setting (Workspace behavior-> click behavior).  
But as multimc doesn't support/have selection markers, it would IMO be better if MultiMC ignored that setting.

**Comment by DoctorBang** [comment]
Yes, I am using KDE Plasma. Sorry for not keeping track of this, been busy with college stuff. It did turn out to be a result of the click behavior. Changing it to open files on double clicking fixed it.

**Comment by Forkk** [comment]
This seems resolved, so I'm closing it.
