### ISSUE TITLE
Microsoft Accounts are not supported

### ISSUE THREAD

**Issue by l1ving** [MultiMC/MultiMC5#3392]
Official post: https://www.minecraft.net/en-us/article/java-edition-moving-house

They have **not** announced a replacement for Yggdrasil. 

I can only assume this spells the end for multimc, unless someone reverse engineers the new system, which I doubt will happen due to risk of DMCA takedowns. 

How does the multimc team plan to handle this?

**Comment by SViN24** [comment]
https://old.reddit.com/r/Minecraft/comments/jfgrhh/java_edition_is_moving_house_now_requires_a/g9kbh56/

"No specific announcement has been made yet, but it is very likely that they need to be at least updated to work in the future."

**Comment by l1ving** [comment]
Of course they need to be updated to work. That's not very helpful, it's just reiterating the concerns I already voiced.

**Comment by GreffMASTER** [comment]
I would suggest not to migrate to Microsoft account until MultiMC will support it. Even tho the cape is quite a cool reward, it would not be that special to have one. I can't go back to the official launcher.

**Comment by l1ving** [comment]
I'm fully aware, which is why I made this issue.

**Comment by GreffMASTER** [comment]
Maybe they can use the Microsoft's Authentication libraries. (I'm not an expert in coding and licensing so I might not know what i'm saying) [(https://developer.microsoft.com/en-us/identity/add-sign-in-with-microsoft)]

**Comment by peterix** [comment]
Mojang will release a solution.
I will integrate the solution.

... I am actually one of the people working on the solution.

If you want to use MultiMC, do not migrate to a Microsoft account intil a solution is in place.

**Comment by peterix** [comment]
Ok. Given how everything went internally, this will have to be done from scratch.

**Comment by peterix** [comment]
OK. A very rough implementation is now merged in develop and ready for testing/breaking/fixing.

Please report issues separately.

**Comment by l1ving** [comment]
thanks for the hard work :tada: :smile:

**Comment by MrMelon54** [comment]
After these commits were merged into my download of multimc is has stopped showing skins except for ones attached to microsoft accounts. I tried deleting the files in "accounts/skins/" (this only contained the skins of mojang accounts) after deleting them the files haven't been downloaded again to this location.

**Comment by l1ving** [comment]
... make a new issue then

**Comment by Andreas711** [comment]
A bunch of people's accounts are being migrated rapidly so I'm really not sure what's gonna happen but this should 100% be top priority.

**Comment by Zetabite** [comment]
No worries, dev has already MSA in testing

**Comment by Zetabite** [comment]
Why do you think it was closed
