### ISSUE TITLE
Unable to access because of buffer

### ISSUE THREAD

**Issue by TimothyPlays57** [MultiMC/MultiMC5#3393]
I was trying to play on 1.8.9 the normal launcher didnt work with the same issue I looked it up it said multi mc worked and it didnt I play on debian linux beta pls help me.

**Comment by Janrupf** [comment]
Please upload a log and fill out the issue template.

**Comment by TimothyPlays57** [comment]
wdym Janrupf

**Comment by Janrupf** [comment]
![image](https://user-images.githubusercontent.com/25827180/96800698-3bc41e80-1406-11eb-8b26-918a22817fc9.png)

**Comment by TimothyPlays57** [comment]
kk thx ill try that

**Comment by TimothyPlays57** [comment]
erm did our comments get deleted?

**Comment by TimothyPlays57** [comment]
nvm they reapeared for me

**Comment by TimothyPlays57** [comment]
I dont have that 
![Uploading Screenshot 2020-10-21 at 6.36.41 PM.png…]()

**Comment by Janrupf** [comment]
Whatever you posted there does not work, you need to wait for your image to upload before you press comment....

**Comment by TimothyPlays57** [comment]
oh ok

**Comment by TimothyPlays57** [comment]
![Screenshot 2020-10-21 at 6 36 41 PM](https://user-images.githubusercontent.com/73261054/96801184-aa848600-13cc-11eb-9b6c-c0f47aa3b97f.png)

**Comment by Janrupf** [comment]
You need to click Launch, then you can follow the screenshot

**Comment by TimothyPlays57** [comment]
k I did the screenshot

**Comment by TimothyPlays57** [comment]
https://paste.ee/p/Q3Zry

**Comment by Janrupf** [comment]
The game did launch though? Whats the problem?

**Comment by TimothyPlays57** [comment]
I cant go into server

**Comment by TimothyPlays57** [comment]
![Screenshot 2020-10-21 at 6 41 56 PM](https://user-images.githubusercontent.com/73261054/96801393-1e269300-13cd-11eb-939b-8f03512f2cf3.png)

**Comment by TimothyPlays57** [comment]
I cant play 1.11 or below

**Comment by Janrupf** [comment]
Please upload the log again now, as you have encountered the error now. (As in, **immediately** after getting that screen, upload the log)

**Comment by TimothyPlays57** [comment]
ok

**Comment by TimothyPlays57** [comment]
![Screenshot 2020-10-21 at 6 45 52 PM](https://user-images.githubusercontent.com/73261054/96801631-aa38ba80-13cd-11eb-8208-7cd5afe44026.png)

**Comment by TimothyPlays57** [comment]
![Screenshot 2020-10-21 at 6 46 39 PM](https://user-images.githubusercontent.com/73261054/96801672-c5a3c580-13cd-11eb-8344-81608ffbc2d9.png)
then this over and over again

**Comment by Janrupf** [comment]
You are using Java 11, please install and use Java 8. Search instructions for your system online.

**Comment by TimothyPlays57** [comment]
how do I do that

**Comment by TimothyPlays57** [comment]
I tried to do that before

**Comment by TimothyPlays57** [comment]
but you need debian 8

**Comment by TimothyPlays57** [comment]
which is now imposible to get im pretty sure

**Comment by TimothyPlays57** [comment]
are you still there?

**Comment by Janrupf** [comment]
Yeah, please have a bit of patience

**Comment by TimothyPlays57** [comment]
oh ok

**Comment by TimothyPlays57** [comment]
tysm for trying to help me

**Comment by Janrupf** [comment]
Run the following commands:
```bash
wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
sudo apt-get install -y software-properties-common
sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
sudo apt-get install adoptopenjdk-8-hotspot
```

Then, in MultiMC select Java 8:
![image](https://user-images.githubusercontent.com/25827180/96802203-a460ca80-1409-11eb-9467-e6de764f4693.png)

**Comment by TimothyPlays57** [comment]
im sorry but do I run these commands in my terminal?

**Comment by Janrupf** [comment]
Yes

**Comment by TimothyPlays57** [comment]
If I put in wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public it does nothing

**Comment by TimothyPlays57** [comment]
oh its a download?

**Comment by TimothyPlays57** [comment]
eait is this a terminal itself

**Comment by TimothyPlays57** [comment]
do I put the commands into the download or the linux terminal

**Comment by TimothyPlays57** [comment]
do u know?

**Comment by Janrupf** [comment]
I recommend you to get familiar with the operating system before you really start using it. Anyway, those commands belong into th e linux terminal (I have no idea what a download terminal is supposed to be though)

**Comment by Zetabite** [comment]
Some distros have their own software center and i can remember one calling itself similar

**Comment by TimothyPlays57** [comment]
none of those commands work in the linux beta terminal for me

**Comment by Zetabite** [comment]
linux beta?

**Comment by Zetabite** [comment]
could you give a link to the actual distro site, cause i have no idea what you are talkin about

**Comment by TimothyPlays57** [comment]
its not a site

**Comment by TimothyPlays57** [comment]
its an addon to chrome os ill show u

**Comment by TimothyPlays57** [comment]
![Screenshot 2020-10-21 at 7 14 00 PM](https://user-images.githubusercontent.com/73261054/96803301-998a4380-13d1-11eb-8170-02ac80ca13f4.png)

**Comment by TimothyPlays57** [comment]
see it says linux beta

**Comment by Zetabite** [comment]
thats not a version. That a feature which is in beta stage

**Comment by TimothyPlays57** [comment]
no the version of the jpk is the problem

**Comment by TimothyPlays57** [comment]
not the linux itself

**Comment by Zetabite** [comment]
i didnt said anything about the version being wrong.

**Comment by TimothyPlays57** [comment]
like I said its not linux itself it is the jpk being version 11 and not 8 not linux inself something inside coded for minecraft

**Comment by Janrupf** [comment]
You have gotten instructions on how to fix it, there is nothing we can really do anymore. Please use these commands, and if you get stuck, use google. Apply common sense when searching, and learn how to use the Linux terminal. Once you get the hang, its quite easy. Have fun experimenting.

**Comment by peterix** [comment]
Oh boy.

What happened here?

Github issues are not chat. If you want immediate responses, go to the Discord server and talk there. Probably in the #minecraft channel.
