### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Peter-Crawley** [MultiMC/MultiMC5#3395]
I'm banned, not sure why.
Please unban PeterCrawley#8651

**Comment by Luke18033** [comment]
I don't think GitHub issues are the best place to ask to be unbanned from a Discord server. If anything, it might just get you banned here as well. This is an issue tracker, not a forum.

**Comment by REALERvolker1** [comment]
The discord server rules are:

1. Keep it civil.
2. Don't ping random people with questions and tech support issues.
3. Don't post the same thing in multiple channels. While it might get you attention, it's annoying and it's not necessarily the attention you want.
4a. If you have issues with or questions about MultiMC, use the #multimc channel.
4b. If you have issues with or questions about Minecraft mods, use the #minecraft channel.
5. Wait for responses. There are usually plenty of people around willing to help, but not everyone is awake at the same time.
6. Please don't ask for help with other launchers here.

they don't just ban people randomly

**Comment by Peter-Crawley** [comment]
I don't know why I was banned, and I have nowhere else to ask for an unban.

**Comment by Forkk** [comment]
This is not the place for this, and the answer is no.

**Comment by peterix** [comment]
Well, we don't know either. It's not in the audit log.
