### ISSUE TITLE
Issue: Process exited with code 255.

### ISSUE THREAD

**Issue by FendrZwag** [MultiMC/MultiMC5#3396]
System Information
-----------------------------
MultiMC version: 5

Operating System: MacOS

Summary of the issue or suggestion: 
----------------------------------------------
- This issue occurs when I try to launch the modpack: All of Fabric 3 - Minecraft version 1.6.2

What should happen: 
------------------------------
- Open the modpack so that I can play the modpack either offline and online

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC

2. Drag je the compressed minecraft modpack file into MultiMC

3. Double click the modpack Icon

4. The issue occurs

Suspected cause:
---------------------------
- I don't know

Logs/Screenshots:
----------------------------
- https://paste.ee/p/PisJC

Additional Info:
---------------------------
I have disabled the mods: Jumploader and Megane, because these mods were causing issues

**Comment by LordMZTE** [comment]
you are using forge instead of fabric

**Comment by FendrZwag** [comment]
Oh wow. Thanks for the help :)

**Comment by TheGayInThewather** [comment]
i have the problem too but i installed forge, have java 8 and fix the bug with the fullscreen and also it´s chrashing with error code 255

**Comment by LordMZTE** [comment]
> 
> 
> i have the problem too but i installed forge, have java 8 and fix the bug with the fullscreen and also it´s chrashing with error code 255

you are not having the same issue. the error code is pretty much meaningless

also someone should close this issue

**Comment by wb1016** [comment]
solved issue. should be closed.

**Comment by FendrZwag** [comment]
> solved issue. should be closed.

Idk how lol
