### ISSUE TITLE
When launching Minecraft 1.16 : crashes and says "process exited with code 255"

### ISSUE THREAD

**Issue by Jowelle** [MultiMC/MultiMC5#3397]
System Information
-----------------------------
MultiMC version: MultiMC 5

Operating System: Linux Mint 19.2 Cinnamon (32 bits)

Summary of the issue or suggestion:
----------------------------------------------
When I try launching my instance of Minecraft (version 1.16.3), the game crashes and indicates a code : 255
My instance is not modded.

What should happen:
------------------------------
My instance of Minecraft should start.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC 5

2. Right-click on the instance and select "launch"

3. The console opens

4. The process is interrupted and the game crashes.

Suspected cause:
---------------------------
It might have something to do with Java, because the log indicates at some point "[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath."

But I am not sure of this at all (I don't know much about computers).

Logs/Screenshots:
----------------------------
[/https://paste.ee/p/ucGbq/]

Additional Info:
---------------------------
I am using Java 8 and increased the allocated memory, as suggested in the MultiMC Help section.

Sorry if my english is not correct (I use the French version of MultiMC). And thank you very much for your attention.

**Comment by phit** [comment]
32 bit linux is no longer supported by Minecraft, see this comment by Mojang https://bugs.mojang.com/browse/MC-121388?focusedCommentId=419156&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-419156

install a 64bit OS or use a version older than 1.13

**Comment by Jowelle** [comment]
Oh, I see now, thank you very much for your explanation !
