### ISSUE TITLE
MultiMC Issue Minecraft 1.8.9 Not working properly.

### ISSUE THREAD

**Issue by Qxx11** [MultiMC/MultiMC5#3398]
System Information
-----------------------------
MultiMC version:
0.6.12-develop-1481
Operating System:
Windows 10 Home 64-bit (10.0, Build 18362)
Summary of the issue or suggestion:
----------------------------------------------
I try to launch minecraft 1.8.9, it starts loading and shows the loading screen, but then after it seems like it's gonna load, it closes and then, in the console, I get information about what happened

What should happen:
------------------------------
Minecraft 1.8.9 turns on normally like it should.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.There is no way I can explain how to reproduce the issue, I'm sorry

Suspected cause:
---------------------------
I cannot give a suspected cause for this. There is nothing that can come up in my mind that would be the cause.

Logs/Screenshots:
----------------------------
[//]: #
#A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffbc2032bfa, pid=8944, tid=0x00000000000027a4
#
# JRE version: Java(TM) SE Runtime Environment (8.0_271-b09) (build 1.8.0_271-b09)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.271-b09 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ig7icd64.dll+0x22bfa]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\DarkNess\Desktop\MultiMC\instances\1.8.9\.minecraft\hs_err_pid8944.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
AL lib: (EE) alc_cleanup: 1 device not closed

C:\Users\DarkNess\Desktop\MultiMC\instances\1.8.9\.minecraft\hs_err_pid8944.log Log:
https://paste.ubuntu.com/p/zd9ZcJ2wSK/

Additional Info:
---------------------------
When I try starting up 1.8.9 on the original MC launcher, it works, yet when I try on MultiMC, it gives me what you can see above, in the "Summary of the issue or suggestion" section. I have tried reinstalling MultiMC, Updating Java, updating my drivers, downgrading Jaa, downgrading my drivers. Nothing worked.

Also, if needed because I wasn't sure, DxDiag:
https://paste.ubuntu.com/p/4hr976H82q/

**Comment by Qxx11** [comment]
I've also tried changing my launcher to the stable one, it didt work aswell

**Comment by yellows111** [comment]
[ig7icd64]
User problem: yes (Type: bad driver?)
Driver known to be problematic: yes (Multiple sources with same error.)

Is this a MultiMC Problem (Required to be vaild if an issue): no.

**Comment by QuImUfu** [comment]
@Qxx11 this is probably the "normal" win10+Intel driver bug.  
see:  
https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs

**Comment by Qxx11** [comment]
thanks a lot
