### ISSUE TITLE
Error code 1

### ISSUE THREAD

**Issue by kasycz** [MultiMC/MultiMC5#3403]
Hello i wanna create my own modpack but i don't know how to read from logs. At end it says process exited with code 1.

Mods:
AbyssalCraft-1.7.10-1.9.1.3-FINAL
aether-1.7.10-v1.1.1
Baubles-1.7.10-1.0.1.10
BloodMagic-1.7.10-1.3.3-17
Damage-Indicators-Mod-1.7.10
DimensionalDoors-2.2.4-353
Draconic-Evolution-1.7.10-1.0.2h
DrZharks+MoCreatures+Mod+v6.3.1
DurabilityShow-1.7.10-1.2.0
journeymap-1.7.10-5.1.4p2-unlimited
mystcraft-1.7.10-0.12.3.04
NotEnoughItems-1.7.10-1.0.5.120-universal
QuiverBow_1.7.10_b101d
SoulShards-TOW-1.7.10-0.1-RC9-7
Thaumcraft-1.7.10-4.2.3.5
TheBetweenlands-1.0.6-alpha-universal
TheErebus-0.4.7
Too-Much-TNT-Mod-1.7.10
twilightforest-1.7.10-2.3.8

My system:
Ubuntu 20.04.1 LTS x86_64

Gpu:
Intel hd graphic 620

Cpu:
Intel core i5-7200u

Java:
OpenJDK java 8 Runtime

**Comment by Zetabite** [comment]
The error code is meaning less. We need the log to work. https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png
