### ISSUE TITLE
i need help to change the memory settings

### ISSUE THREAD

**Issue by jptc667** [MultiMC/MultiMC5#3405]
How can I change the hard drive that will allocate memory for minecraft.

**Comment by QuImUfu** [comment]
Hard drive is not RAM, and while swap is a thing, it is **slow**, you do not want to use it if you do not have a week to spare for starting minecraft.  
If you just want to change the amount of RAM minecraft is allowed to use, see https://github.com/MultiMC/MultiMC5/wiki/Increasing-Java%27s-memory-allocation.

**Comment by Scotsguy** [comment]
This is not a MultiMC issue, closing.
