### ISSUE TITLE
Minecraft crashes when trying to load mod through MultiMC

### ISSUE THREAD

**Issue by Navi2912** [MultiMC/MultiMC5#3407]
System Information
-----------------------------
MultiMC version: 5

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
I am trying to load the modpack Dimension Zero through multimc, when I click launch it crashes

What should happen:
------------------------------
Minecraft should open and allow me to play with the mod.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download dimension zero .zip

2. Make instance of minecraft with that zip

3. Try to launch

Suspected cause:
---------------------------
From looking at the logs I think it may be a Java error but Im not sure

Logs/Screenshots:
----------------------------
https://paste.ee/p/TIMBm
Additional Info:
---------------------------

**Comment by LordMZTE** [comment]
you are using java 15 but you have to use java 8

**Comment by peterix** [comment]
See: https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java
