### ISSUE TITLE
[Feature Request] Change between Mojang and Microsoft authentication

### ISSUE THREAD

**Issue by Chaoschaot232** [MultiMC/MultiMC5#3408]
It is out, that our beloved Mojang Accounts must be merged into your own MS Account. For now only one MC Account can be linked with only one MS Account (which is stupied btw.).

So I please you to watch at this and and hopefully add the possibility for a login later with the MS Account. I assume that you then only need your Credentials from your MS Account and the corresponding API from MS itself.

Maybe you can include it in the future version besides the still available Mojang Login so that all MultiMC Users have a smooth
way to switch over, after there account was ported to MS, thanks :)

**Comment by peterix** [comment]
I'm involved with the process on Mojang side. It's not clear how it will be handled in launchers like MultiMC yet. I will do something once there's a clear path ahead.
