### ISSUE TITLE
.deb not working on Ubuntu 20.10

### ISSUE THREAD

**Issue by ergpopler** [MultiMC/MultiMC5#3410]
When i install it, it will succeed and when i run multimc it shows a downloading pop up for a second then it disappears and never loads

**Comment by peterix** [comment]
Cannot reproduce the problem.

The default interface Ubuntu ships now with is kinda buggy and I had to click the icon like 30 times for it to respond, but that's not a MultiMC problem.

**Comment by RainbowAsteroids** [comment]
When in doubt, just use the terminal.
```
sudo dpkg -i path/to/deb/file
sudo apt install -f
```

**Comment by ergpopler** [comment]
Yeah, that isn't the issue.
I can install the .deb, and it shows up in my application menu.
But when i run mutltimc a popup shows up and says something about downloading updates or something then it closes and nothing happens.

**Comment by ergpopler** [comment]
Can confirm the deb DOES work on 20.04

**Comment by mylesbartlett72** [comment]
I'm pretty sure this is libraries MultiMC depending on not being available any more.  This is an issue I have seen elsewhere.

**Comment by Zetabite** [comment]
If you have seen it elsewhere, might wanna reference? But from all I know, you should still be able to install that package, if not, move to another distro, since this distro seems to have some serious package problems.
