### ISSUE TITLE
Red Session

### ISSUE THREAD

**Issue by LethalRedEvent** [MultiMC/MultiMC5#3412]
System Information
-----------------------------
MultiMC version: Version 0.6.11 - 1370 on osx64

Operating System:macOS Catalina

Summary of the issue or suggestion: Session stays red no matter what I do
----------------------------------------------

What should happen: It should be green and allow me to launch I believe. 
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Not sure

Suspected cause: I researched into this and some sources say it's because Minecraft sessions are down, which don't make sense as of right now. 
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![image](https://user-images.githubusercontent.com/73813467/97835611-68422b00-1c8f-11eb-9324-cef432b7ef83.png)

Additional Info:
---------------------------

**Comment by Janrupf** [comment]
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3199

**Comment by LethalRedEvent** [comment]
Ah right, sorry. I'll close this then
