### ISSUE TITLE
Mouse keybinds are erratic

### ISSUE THREAD

**Issue by halloweenhunt** [MultiMC/MultiMC5#3416]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
On (at least) 1.8.9 forge mouse keybinds are erratic and don't always go to the correct slot. i.e. pushing button 4 goes to the slot mapped for button 5 about 80% of the time.

What should happen:
------------------------------
Mouse keybinds should go to the slot they are mapped to

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Load 1.8.9 forge instance

2. Remap mouse keybinds to hotbar slots

3. Press mouse buttons

Suspected cause:
---------------------------
Keyboard binds work perfectly, only the mouse does not (yes my mouse is not broken, tested on other minecraft, other games, etc.). Perhaps multimc has issues with razer mice (if not mouse keybinds in general)? I don't have any other ideas as to what could be wrong.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![image](https://user-images.githubusercontent.com/73437941/98269022-282bc280-1f85-11eb-8a83-2b18ef2d4769.png)
![image](https://user-images.githubusercontent.com/73437941/98272197-ba819580-1f88-11eb-9893-00ac3600a5f2.png)

Additional Info:
---------------------------
I am using the Razer Viper mouse

**Comment by LordMZTE** [comment]
almost certainly not multimc related

**Comment by xcfrg** [comment]
Can confirm, not related to multimc. It's something with your mouse or mouse software.

**Comment by Forkk** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's discord, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by Chicken337** [comment]
I have the saem issue but they work fine in 1.21 so i think its somehow an issue with 1.8.9. using optifine doesnt fix it for me
