### ISSUE TITLE
The multiMC 5 is crash

### ISSUE THREAD

**Issue by caroquinha13** [MultiMC/MultiMC5#3417]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at sun.security.util.SignatureFileVerifier.processImpl(Unknown Source)
	at sun.security.util.SignatureFileVerifier.process(Unknown Source)
	at java.util.jar.JarVerifier.processEntry(Unknown Source)
	at java.util.jar.JarVerifier.update(Unknown Source)
	at java.util.jar.JarFile.initializeVerifier(Unknown Source)
	at java.util.jar.JarFile.getInputStream(Unknown Source)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at java.util.ServiceLoader.parse(Unknown Source)
	at java.util.ServiceLoader.access$200(Unknown Source)
	at java.util.ServiceLoader$LazyIterator.hasNextService(Unknown Source)
	at java.util.ServiceLoader$LazyIterator.hasNext(Unknown Source)
	at java.util.ServiceLoader$1.hasNext(Unknown Source)
	at cpw.mods.modlauncher.ServiceLoaderStreamUtils.errorHandlingServiceLoader(ServiceLoaderStreamUtils.java:65)
	at cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:141)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:74)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50)
	... 8 more

**Comment by Janrupf** [comment]
Please fill  out the issue template and upload a log:
https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by caroquinha13** [comment]
MultiMC version: 0.6.11-1430


Minecraft folder is:
C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/instances/1.16.3/.minecraft


Java path is:
C:/Program Files/Java/jre1.8.0_271/bin/javaw.exe


Java versão 1.8.0_271, usando arquitetura de 64 bits.


Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/instances/1.16.3/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/1.6.25/authlib-1.6.25.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.11.2/log4j-core-2.11.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/1.4.2/ForgeWrapper-1.4.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forge/1.16.3-34.1.0/forge-1.16.3-34.1.0-launcher.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm/7.2/asm-7.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-commons/7.2/asm-commons-7.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-tree/7.2/asm-tree-7.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-util/7.2/asm-util-7.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-analysis/7.2/asm-analysis-7.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/cpw/mods/modlauncher/7.0.1/modlauncher-7.0.1.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/cpw/mods/grossjava9hacks/1.3.0/grossjava9hacks-1.3.0.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/accesstransformers/2.2.0-shadowed/accesstransformers-2.2.0-shadowed.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/eventbus/3.0.3-service/eventbus-3.0.3-service.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forgespi/3.1.1/forgespi-3.1.1.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/coremods/3.0.0/coremods-3.0.0.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/electronwill/night-config/core/3.6.2/core-3.6.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/electronwill/night-config/toml/3.6.2/toml-3.6.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.0/maven-artifact-3.6.0.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/net/jodah/typetools/0.8.1/typetools-0.8.1.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/spongepowered/mixin/0.8.1/mixin-0.8.1.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/instances/1.16.3/.minecraft/bin/minecraft.jar

Native libraries:
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] additional_lights-1.16.3-2.1.2
  [✔️] AmbientSounds_v3.0.21_mc1.16.2
  [✔️] BackTools-1.16.3-10.0.0
  [✔️] bambooeverything-1.16.3-forge-1.0.0
  [✔️] BiomesOPlenty-1.16.3-12.0.0.409-universal
  [✔️] Bookshelf-1.16.3-8.5.17
  [✔️] BotanyPots-1.16.3-5.1.9
  [✔️] branders-lampblock-1.16.3-1.1.3
  [✔️] buildersaddition-1.16.3-20200930a
  [✔️] caelus-forge-1.16.3-2.0.0.3
  [✔️] ceilingtorch-1.16.2-v1.8
  [✔️] ChineseWorkshop-1.16.3-3.2.0
  [✔️] craftingstation-4.1.0
  [✔️] Cucumber-1.16.3-4.1.2
  [✔️] curios-forge-1.16.3-4.0.2.0
  [✔️] curiouselytra-forge-1.16.3-4.0.0.1
  [✔️] decorative_blocks-1.16.2-1.1
  [✔️] DoubleSlabs-1.16-3.4.10
  [✔️] DramaticDoors-1.16.3-1.1.0
  [✔️] elevatorid-1.16.3-1.7.6
  [✔️] EnchantmentDescriptions-1.16.3-5.0.1
  [✔️] EnderMail-1.16.3-1.1.5
  [✔️] engineerstools-1.16.3-1.1.0
  [✔️] extratags-2.2
  [✔️] FruitTrees-1.16.3-2.1.0
  [✔️] gravestone-1.16.3-1.0.2
  [✔️] iChunUtil-1.16.3-10.0.0
  [✔️] InfinityMending-1.16.3-0.1.0
  [✔️] InventoryHud_1.16.x.forge-3.1.3
  [✔️] ironchest-1.16.3-11.2.6
  [✔️] jei-1.16.3-7.6.0.49
  [✔️] jumbofurnace-1.16.3-2.1.0.0
  [✔️] Kiwi-1.16.3-3.4.0
  [✔️] LightingWand-1.16.2-1.7.0
  [✔️] MagicMirror-1.16.3-0.0.7.435
  [✔️] masonry-1.16.3-0.3.6
  [✔️] mcw-bridges-1.0.4-mc1.16.3
  [✔️] mcw-doors-1.0.1fix-mc1.16.3-1.16.2
  [✔️] mcws-roofs-1.16.3-v2.0.0
  [✔️] mcw-windows-1.0.2-mc1.16.3
  [✔️] mining-helmet-1.16.3-1.0.9
  [✔️] MmmMmmMmmMmm-1.16-1.0.1
  [✔️] morevanillalib-1.16.2-1.2.14
  [✔️] movingelevators-1.2.23-mc1.16.3
  [✔️] NaturesCompass-1.16.3-1.8.5
  [✔️] OptiFine_1.16.3_HD_U_G3
  [✔️] pathundergates-1.16.3-1.0.1-release
  [✔️] PickleTweaks-1.16.3-5.1.2
  [✔️] pitg-1.16.3-1.4.0
  [✔️] ShulkerTooltip-1.9.3
  [✔️] SignButton-1.16.3-2.1.3
  [✔️] simplechunkloaders-1.16.3-1.0.3.2
  [✔️] SimpleStorageNetwork-1.16.3-1.1.2
  [✔️] simpleworldtimer-1.16.3-1.1.2-beta
  [✔️] simplylight-1.16.3-1.0.2
  [✔️] sit-1.16.2-v1.3
  [✔️] speedyhoppers-1.16.3-1
  [✔️] StorageDrawers-1.16.2-8.1.0
  [✔️] sweetconcrete-1.16.3-1.7.1
  [✔️] sworddisplay-1.16.2-1.0.3.
  [✔️] torchmaster-2.3.3-alpha
  [✔️] torchslabmod-1.16.3_v1.6.18
  [✔️] TrampleStopper-2.2.0+build.1.mcVersion.1.16.3
  [✔️] TravelersBackpack-1.16.2-5.1.1
  [✔️] u_team_core-1.16.3-3.1.10.183
  [✔️] useful_backpacks-1.16.3-1.11.6.83
  [✔️] useful_railroads-1.16.3-1.4.5.32
  [✔️] valhelsia_structures-16.0.3
  [✔️] valkyrielib-1.16.3-3.0.3.2
  [✔️] vanillaexcavators-1.16.2-2.1.3
  [✔️] vanillahammers-1.16.2-2.1.3
  [✔️] walljump-forge-1.16.3-1.3.6
  [✔️] Waystones_1.16.3-7.3.0

Jar Mods:
  additional_lights-1.16.3-2.1.2 (715e1a8c-58f8-4252-b62f-3754ff65a77e.jar)
  AmbientSounds_v3.0.21_mc1.16.2 (ed00dd2b-672d-4958-ac55-1da8ea60c01e.jar)
  BackTools-1.16.3-10.0.0 (aee1001f-de22-4045-85b1-f8a2eb5ba514.jar)
  bambooeverything-1.16.3-forge-1.0.0 (a191472b-0382-4e35-9d65-4358cab6df12.jar)
  BiomesOPlenty-1.16.3-12.0.0.409-universal (3a0d25b5-a8e7-4fbf-8685-a0fab8605d6c.jar)
  Bookshelf-1.16.3-8.5.17 (187e1493-d713-4048-8be8-ce0bbe24b9f4.jar)
  BotanyPots-1.16.3-5.1.9 (f03d68ce-7ff1-4190-a3c3-1dd66334ccfb.jar)
  branders-lampblock-1.16.3-1.1.3 (f748ddaf-f28f-4b90-8bf9-e4cdfbe3852c.jar)
  buildersaddition-1.16.3-20200930a (cd706f46-b4c6-4398-9705-375d86b8ce7b.jar)
  caelus-forge-1.16.3-2.0.0.3 (880ea6ca-5629-46c3-8325-1c80f40949e8.jar)
  ceilingtorch-1.16.2-v1.8 (7009d639-236e-46b1-bd7c-c2f270fa9a38.jar)
  ChineseWorkshop-1.16.3-3.2.0 (344de645-7f6d-48a4-b076-a944754c084d.jar)
  craftingstation-4.1.0 (f2876a13-b3e7-43ac-97b3-461778b92f0b.jar)
  Cucumber-1.16.3-4.1.2 (41175745-90c6-4071-a468-b369402a257b.jar)
  curios-forge-1.16.3-4.0.2.0 (2c73ec42-bb31-4de3-a1ed-5a9f7e5bc20b.jar)
  curiouselytra-forge-1.16.3-4.0.0.1 (da09dc22-22b8-4b8d-af9c-36512edce22e.jar)
  decorative_blocks-1.16.2-1.1 (c6d517db-2286-405f-b2d7-aaabe3d47539.jar)
  DoubleSlabs-1.16-3.4.10 (4dd7c296-60a5-4420-8237-e7ef0736e69d.jar)
  DramaticDoors-1.16.3-1.1.0 (c17e1354-c6bb-46d9-94a3-553b9b0b4861.jar)
  elevatorid-1.16.3-1.7.6 (ed43d924-611c-4b0c-ad75-af520fbe9e23.jar)
  EnchantmentDescriptions-1.16.3-5.0.1 (d9f0e35b-01ea-40ec-9519-511e91c88a5e.jar)
  EnderMail-1.16.3-1.1.5 (03bc3c0d-eb3c-46aa-8c55-744a301a4a06.jar)
  engineerstools-1.16.3-1.1.0 (2226ba39-744e-49b0-9bce-a654c532b383.jar)
  extratags-2.2 (aa6c845a-4842-42ba-a96b-178a782011dc.jar)
  FruitTrees-1.16.3-2.1.0 (db868b2f-7078-4c32-977e-89ba19d0f26d.jar)
  gravestone-1.16.3-1.0.2 (9706eada-1e1f-4d18-99e3-1301361e9315.jar)
  iChunUtil-1.16.3-10.0.0 (8c8da373-7138-47a3-a538-234c2d355a5c.jar)
  InfinityMending-1.16.3-0.1.0 (cd4aa709-f916-4c44-835b-939afd09a23c.jar)
  InventoryHud_1.16.x.forge-3.1.3 (e5c744da-9899-4fad-a20d-d00123e14ac6.jar)
  ironchest-1.16.3-11.2.6 (ca90921c-210f-4ae7-8894-a4e1d98ddd23.jar)
  jei-1.16.3-7.6.0.49 (6b000542-a373-4953-9a79-4de709afa3a1.jar)
  jumbofurnace-1.16.3-2.1.0.0 (3757ce72-fc12-4e01-ba7a-7110c0d30edd.jar)
  Kiwi-1.16.3-3.4.0 (cae6b388-6580-413f-a1fb-988365fb864a.jar)
  LightingWand-1.16.2-1.7.0 (8ebbd88a-3266-4dfc-b981-3d87627e7ed3.jar)
  MagicMirror-1.16.3-0.0.7.435 (ecea802d-2aca-4eab-940d-14d0ee710d33.jar)
  masonry-1.16.3-0.3.6 (adcb9645-c99b-49bf-81fa-ce3ec4e7df97.jar)
  mcw-bridges-1.0.4-mc1.16.3 (429e18b9-aa04-4750-9ecb-5c710fd803c5.jar)
  mcw-doors-1.0.1fix-mc1.16.3-1.16.2 (271429b5-6dec-4db0-95b0-7f30cdad4b8a.jar)
  mcws-roofs-1.16.3-v2.0.0 (01f21f80-6e7e-446c-926c-e6bb23c17625.jar)
  mcw-windows-1.0.2-mc1.16.3 (d4c020d9-1eea-4752-b6b8-28bc493ccf22.jar)
  mining-helmet-1.16.3-1.0.9 (4b2811f3-6633-4a3f-8560-88b200eb2aac.jar)
  MmmMmmMmmMmm-1.16-1.0.1 (10c80d1b-5d91-4a1a-8006-beee7d00638d.jar)
  morevanillalib-1.16.2-1.2.14 (0a77f382-a7ea-4b54-97a5-fe6cc4d0ea33.jar)
  movingelevators-1.2.23-mc1.16.3 (afff54ea-ea44-43e1-81ed-adb67a1946e1.jar)
  NaturesCompass-1.16.3-1.8.5 (b9c759b5-9567-40d9-9450-cd29f0453cf8.jar)
  OptiFine_1.16.3_HD_U_G3 (ca2b94f4-0e31-46e0-82ed-68fc794dcc29.jar)
  pathundergates-1.16.3-1.0.1-release (f1d41320-2bd7-4870-9860-f43f7b6a329c.jar)
  PickleTweaks-1.16.3-5.1.2 (f6035cde-1857-4a8e-ac13-0064ee145ff3.jar)
  pitg-1.16.3-1.4.0 (fd284a8e-8ea8-4ff0-bd01-004d9ea38894.jar)
  ShulkerTooltip-1.9.3 (d839fa09-e5c1-4181-b289-5425929b0c96.jar)
  SignButton-1.16.3-2.1.3 (7f138afe-799f-4850-a604-8e000c151ef4.jar)
  simplechunkloaders-1.16.3-1.0.3.2 (2984b457-447f-48b2-b998-509997c941f2.jar)
  SimpleStorageNetwork-1.16.3-1.1.2 (463bc68d-c931-442a-97e2-a0e6cac0880e.jar)
  simpleworldtimer-1.16.3-1.1.2-beta (ad273a84-e217-4d3f-8027-4a2a062092b7.jar)
  simplylight-1.16.3-1.0.2 (239d560d-1470-4743-b473-3cd73f275842.jar)
  sit-1.16.2-v1.3 (965e2f94-c036-4a1f-8f9c-1a9162f6fa76.jar)
  speedyhoppers-1.16.3-1 (c9ae1c31-2039-4fc3-beda-0e0d31d30887.jar)
  StorageDrawers-1.16.2-8.1.0 (ff2c086e-701a-4e85-9c3a-d004bd5228f6.jar)
  sweetconcrete-1.16.3-1.7.1 (c912c58b-0c5a-412d-983f-066a3f8e6e99.jar)
  sworddisplay-1.16.2-1.0.3. (47e29e02-083d-410e-99f9-1a54f1aa19b9.jar)
  torchmaster-2.3.3-alpha (887654ce-72aa-4433-a40a-66eb269f4602.jar)
  torchslabmod-1.16.3_v1.6.18 (cb657787-1d30-4264-8aa2-ea8a31ea4a30.jar)
  TrampleStopper-2.2.0+build.1.mcVersion.1.16.3 (b331d702-2320-4835-bdda-5ebaa583bb4b.jar)
  TravelersBackpack-1.16.2-5.1.1 (d4de83b4-e617-40a3-bb19-2eff66902f90.jar)
  u_team_core-1.16.3-3.1.10.183 (dd64e262-1c94-46a9-978b-980c39efc6d4.jar)
  useful_backpacks-1.16.3-1.11.6.83 (b4a38dd0-fda0-4f2e-bcaf-546b86bda880.jar)
  useful_railroads-1.16.3-1.4.5.32 (42d3bd9f-5d1e-4a8c-9f51-4229c036e7f2.jar)
  valhelsia_structures-16.0.3 (fe0de0f6-920f-46ad-a991-1bb4a4552d29.jar)
  valkyrielib-1.16.3-3.0.3.2 (4e89f5e4-9051-4afb-a38b-7887c9cdfbc9.jar)
  vanillaexcavators-1.16.2-2.1.3 (37460359-1f30-49f5-9d99-0b643ba3887c.jar)
  vanillahammers-1.16.2-2.1.3 (ec28fdf1-8097-4e53-a7f9-f765fc0bb834.jar)
  walljump-forge-1.16.3-1.3.6 (80ab0f8a-39e8-439d-addd-c2b0b296bc12.jar)
  Waystones_1.16.3-7.3.0 (e5f67aca-730b-429f-8cf1-cdab7d9b737d.jar)

Params:
  --username  --version MultiMC5 --gameDir C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/instances/1.16.3/.minecraft --assetsDir C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 34.1.0 --fml.mcVersion 1.16.3 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20200911.084530

Window size: 854 x 480

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2048m, -Xmx3000m, -Duser.language=en]


ID do processo do Minecraft: 9280


Using onesix launcher.

2020-11-05 16:20:24,325 main WARN Advanced terminal features are not available in this environment
[32m[16:20:24] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Caroquinha13, --version, MultiMC5, --gameDir, C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/instances/1.16.3/.minecraft, --assetsDir, C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/assets, --assetIndex, 1.16, --uuid, <ID DO PERFIL>, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 34.1.0, --fml.mcVersion, 1.16.3, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200911.084530, --width, 854, --height, 480]
[m[32m[16:20:24] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 7.0.1+78+master.e9771d8 starting: java version 1.8.0_271 by Oracle Corporation
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at sun.security.util.SignatureFileVerifier.processImpl(Unknown Source)
	at sun.security.util.SignatureFileVerifier.process(Unknown Source)
	at java.util.jar.JarVerifier.processEntry(Unknown Source)
	at java.util.jar.JarVerifier.update(Unknown Source)
	at java.util.jar.JarFile.initializeVerifier(Unknown Source)
	at java.util.jar.JarFile.getInputStream(Unknown Source)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at java.util.ServiceLoader.parse(Unknown Source)
	at java.util.ServiceLoader.access$200(Unknown Source)
	at java.util.ServiceLoader$LazyIterator.hasNextService(Unknown Source)
	at java.util.ServiceLoader$LazyIterator.hasNext(Unknown Source)
	at java.util.ServiceLoader$1.hasNext(Unknown Source)
	at cpw.mods.modlauncher.ServiceLoaderStreamUtils.errorHandlingServiceLoader(ServiceLoaderStreamUtils.java:65)
	at cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:141)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:74)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50)
	... 8 more
[mExiting with -1
O processo foi encerrado com o código -1.

**Comment by Janrupf** [comment]
Remove all Jar Mods, they don't belong there.

**Comment by caroquinha13** [comment]
okay

**Comment by caroquinha13** [comment]
But,  i have 4gb RAM in my pc,  how many i use in multimc?

**Comment by caroquinha13** [comment]
But, i have 4gb RAM in my pc, how many i use in multimc?

**Comment by LordMZTE** [comment]
with 4 gb of ram i doubt youll ever get this many mods to run at reasonable performance

**Comment by caroquinha13** [comment]
okay

**Comment by caroquinha13** [comment]
okay,
but if you consider that it works, what is the minimum and maximum that I should allocate
