### ISSUE TITLE
Launch and starting worlds will crash

### ISSUE THREAD

**Issue by dablade11577** [MultiMC/MultiMC5#3419]
System Information
-----------------------------
MultiMC version:0.6.11-1430

Operating System:
windows 10

Summary of the issue or suggestion:
----------------------------------------------
Something with java runtime, maybe

What should happen:
------------------------------
start

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.start game

2.

3.

Suspected cause:
---------------------------
Java runtime environment

Logs/Screenshots:
----------------------------
[hs_err_pid11460.log](https://github.com/MultiMC/MultiMC5/files/5542925/hs_err_pid11460.log)

Additional Info:
---------------------------
i have reinstalled java and on a different drive and restarted to make sure it works fine but problem proveils

**Comment by phit** [comment]
please post this file `C:\Users\aaron\Desktop\game launchers\MultiMC\instances\1.12.2\.minecraft\hs_err_pid11460.log`

**Comment by dablade11577** [comment]
> please post this file `C:\Users\aaron\Desktop\game launchers\MultiMC\instances\1.12.2\.minecraft\hs_err_pid11460.log`

done

**Comment by dablade11577** [comment]
the game started working again but its back to the problem

**Comment by phit** [comment]
Looks like bad memory from my untrained eye, I'd start with something like MemTest86 to make sure it isn't faulty hardware. Java is very good at finding bad RAM.

**Comment by dablade11577** [comment]
> Looks like bad memory from my untrained eye, I'd start with something like MemTest86 to make sure it isn't faulty hardware. Java is very good at finding bad RAM.

Ill have to try when i get home but this happened just recently, last month i had no problems and just when i transferred these files onto an ssd

**Comment by dablade11577** [comment]
Pretty sure you misinterpreted what i said but i dont mean my pc crashes, just the game crashes, pretty sire i worded it wrong @phit
