### ISSUE TITLE
error multimc5

### ISSUE THREAD

**Issue by caroquinha13** [MultiMC/MultiMC5#3421]
MultiMC version: 0.6.11-1430

Minecraft folder is:
C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/instances/1.16.3/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_271/bin/javaw.exe

Java versão 1.8.0_271, usando arquitetura de 64 bits.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/instances/1.16.3/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/1.6.25/authlib-1.6.25.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.11.2/log4j-core-2.11.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/1.4.2/ForgeWrapper-1.4.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forge/1.16.3-34.1.19/forge-1.16.3-34.1.19-launcher.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm/7.2/asm-7.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-commons/7.2/asm-commons-7.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-tree/7.2/asm-tree-7.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-util/7.2/asm-util-7.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-analysis/7.2/asm-analysis-7.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/cpw/mods/modlauncher/7.0.1/modlauncher-7.0.1.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/cpw/mods/grossjava9hacks/1.3.0/grossjava9hacks-1.3.0.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/accesstransformers/2.2.0-shadowed/accesstransformers-2.2.0-shadowed.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/eventbus/3.0.3-service/eventbus-3.0.3-service.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forgespi/3.1.1/forgespi-3.1.1.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/coremods/3.0.0/coremods-3.0.0.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/electronwill/night-config/core/3.6.2/core-3.6.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/electronwill/night-config/toml/3.6.2/toml-3.6.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.0/maven-artifact-3.6.0.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/net/jodah/typetools/0.8.1/typetools-0.8.1.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/instances/1.16.3/.minecraft/bin/minecraft.jar

Native libraries:
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] additional_lights-1.16.3-2.1.2
  [✔️] AmbientSounds_v3.0.21_mc1.16.2
  [✔️] BackTools-1.16.3-10.0.0
  [✔️] bambooeverything-1.16.3-forge-1.0.0
  [✔️] BiomesOPlenty-1.16.3-12.0.0.409-universal
  [✔️] Bookshelf-1.16.3-8.5.17
  [✔️] BotanyPots-1.16.3-5.1.9
  [✔️] branders-lampblock-1.16.3-1.1.3
  [✔️] buildersaddition-1.16.3-20200930a
  [✔️] caelus-forge-1.16.3-2.0.0.3
  [✔️] ceilingtorch-1.16.2-v1.8
  [✔️] ChineseWorkshop-1.16.3-3.2.0
  [✔️] craftingstation-4.1.0
  [✔️] Cucumber-1.16.3-4.1.2
  [✔️] curios-forge-1.16.3-4.0.2.0
  [✔️] curiouselytra-forge-1.16.3-4.0.0.1
  [✔️] decorative_blocks-1.16.2-1.1
  [✔️] DoubleSlabs-1.16-3.4.10
  [✔️] DramaticDoors-1.16.3-1.1.0
  [✔️] elevatorid-1.16.3-1.7.6
  [✔️] EnchantmentDescriptions-1.16.3-5.0.1
  [✔️] EnderMail-1.16.3-1.1.5
  [✔️] engineerstools-1.16.3-1.1.0
  [✔️] extratags-2.2
  [✔️] FruitTrees-1.16.3-2.1.0
  [✔️] gravestone-1.16.3-1.0.2
  [✔️] iChunUtil-1.16.3-10.0.0
  [✔️] InfinityMending-1.16.3-0.1.0
  [✔️] InventoryHud_1.16.x.forge-3.1.3
  [✔️] ironchest-1.16.3-11.2.6
  [✔️] jei-1.16.3-7.6.0.49
  [✔️] jumbofurnace-1.16.3-2.1.0.0
  [✔️] Kiwi-1.16.3-3.4.0
  [✔️] LightingWand-1.16.2-1.7.0
  [✔️] MagicMirror-1.16.3-0.0.7.435
  [✔️] masonry-1.16.3-0.3.6
  [✔️] mcw-bridges-1.0.4-mc1.16.3
  [✔️] mcw-doors-1.0.1fix-mc1.16.3-1.16.2
  [✔️] mcws-roofs-1.16.3-v2.0.0
  [✔️] mcw-windows-1.0.2-mc1.16.3
  [✔️] mining-helmet-1.16.3-1.0.9
  [✔️] MmmMmmMmmMmm-1.16-1.0.1
  [✔️] morevanillalib-1.16.2-1.2.14
  [✔️] movingelevators-1.2.23-mc1.16.3
  [✔️] NaturesCompass-1.16.3-1.8.5
  [✔️] OptiFine_1.16.3_HD_U_G3
  [✔️] pathundergates-1.16.3-1.0.1-release
  [✔️] PickleTweaks-1.16.3-5.1.2
  [✔️] pitg-1.16.3-1.4.0
  [✔️] ShulkerTooltip-1.9.3
  [✔️] SignButton-1.16.3-2.1.3
  [✔️] simplechunkloaders-1.16.3-1.0.3.2
  [✔️] SimpleStorageNetwork-1.16.3-1.1.2
  [✔️] simpleworldtimer-1.16.3-1.1.2-beta
  [✔️] simplylight-1.16.3-1.0.2
  [✔️] sit-1.16.2-v1.3
  [✔️] speedyhoppers-1.16.3-1
  [✔️] StorageDrawers-1.16.2-8.1.0
  [✔️] sweetconcrete-1.16.3-1.7.1
  [✔️] sworddisplay-1.16.2-1.0.3.
  [✔️] torchmaster-2.3.3-alpha
  [✔️] torchslabmod-1.16.3_v1.6.18
  [✔️] TrampleStopper-2.2.0+build.1.mcVersion.1.16.3
  [✔️] TravelersBackpack-1.16.2-5.1.1
  [✔️] u_team_core-1.16.3-3.1.10.183
  [✔️] useful_backpacks-1.16.3-1.11.6.83
  [✔️] useful_railroads-1.16.3-1.4.5.32
  [✔️] valhelsia_structures-16.0.3
  [✔️] valkyrielib-1.16.3-3.0.3.2
  [✔️] vanillaexcavators-1.16.2-2.1.3
  [✔️] vanillahammers-1.16.2-2.1.3
  [✔️] walljump-forge-1.16.3-1.3.6
  [✔️] Waystones_1.16.3-7.3.0

Jar Mods:
  OptiFine_1.16.3_HD_U_G3 (be2c0a2f-f55f-4a10-b510-69f8466be5ac.jar)

Params:
  --username  --version MultiMC5 --gameDir C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/instances/1.16.3/.minecraft --assetsDir C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 34.1.19 --fml.mcVersion 1.16.3 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20200911.084530

Window size: 854 x 480

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx2056m, -Duser.language=en]

ID do processo do Minecraft: 10852

Using onesix launcher.

2020-11-06 15:14:49,465 main WARN Advanced terminal features are not available in this environment
[32m[15:14:49] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Caroquinha13, --version, MultiMC5, --gameDir, C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/instances/1.16.3/.minecraft, --assetsDir, C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/assets, --assetIndex, 1.16, --uuid, <ID DO PERFIL>, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 34.1.19, --fml.mcVersion, 1.16.3, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200911.084530, --width, 854, --height, 480]
[m[32m[15:14:49] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 7.0.1+78+master.e9771d8 starting: java version 1.8.0_271 by Oracle Corporation
[m[32m[15:14:50] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[m[32m[15:14:50] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file: C:\Users\carol\Downloads\mmc-stable-win32\MultiMC\instances\1.16.3\.minecraft\bin\minecraft.jar
[m[32m[15:14:52] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[m[32m[15:14:52] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/carol/Downloads/mmc-stable-win32/MultiMC/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[m[32m[15:14:53] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: java.lang.RuntimeException: Failed to load FML config from C:\Users\carol\Downloads\mmc-stable-win32\MultiMC\instances\1.16.3\.minecraft\config\fml.toml
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.loading.FMLConfig.loadFrom(FMLConfig.java:64)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.loading.FMLConfig.load(FMLConfig.java:77)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:81)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.util.HashMap$Values.forEach(Unknown Source)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[m[32m[15:14:53] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
[m[32m[15:14:53] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at com.electronwill.nightconfig.core.io.AbstractInput.readCharsUntil(AbstractInput.java:123)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:166)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at com.electronwill.nightconfig.core.file.AutoreloadFileConfig.load(AutoreloadFileConfig.java:41)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraftforge.fml.loading.FMLConfig.loadFrom(FMLConfig.java:60)
[m[32m[15:14:53] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 18 more
[m[32m[15:14:53] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1

**Comment by LordMZTE** [comment]
delete the file `C:\Users\carol\Downloads\mmc-stable-win32\MultiMC\instances\1.16.3\.minecraft\config\fml.toml` it appears to be invalid

**Comment by caroquinha13** [comment]
ok
