### ISSUE TITLE
[Request] Using curseforge api to install mods.

### ISSUE THREAD

**Issue by nathan130200** [MultiMC/MultiMC5#3422]
Currently we have curse forge public api (extracted from twitch app launcher) to install mods and it's dependencies, can be implemented into MultiMC to install mods (and its dependencies) from curse api?

Search mods endpoint: `https://addons-ecs.forgesvc.net/api/v2/addon/search?gameId=432&sectionId=6&categoryId=0&pageSize=${pageSize}&sort=Popularity&isSortDescending=true&index=0&searchFilter=${query}`
  When `${query}` is an optional string, if provided will search an mod, if not provided, will grab most trending mods.

Get specific mod: `https://addons-ecs.forgesvc.net/api/v2/addon/${id}`
  When `${id}` id of mod (grab from search endpoint).

Get addon file by id: `https://addons-ecs.forgesvc.net/api/v2/addon/${modId}/file/${fileId}`
  When `${modId}` is addon id, `${fileId}` is file id grabbed from "Get specific mod", endpoint.

Have an NodeJS implementation on github you can use for example: [GitHub: lupont/curse-cli](https://github.com/lupont/curse-cli)

I made an prototype in .net framework/winforms: [GitHub: nathan130200/CurseForgeApp](https://github.com/nathan130200/CurseForgeApp)

Additional information about Curse API: https://gist.github.com/crapStone/9a423f7e97e64a301e88a2f6a0f3e4d9

**Comment by peterix** [comment]
No.

**Comment by peterix** [comment]
At no point do I want this to be the base for a feature this important.

Giving these guys any, even indirect control over MultiMC would be disastrous.
