### ISSUE TITLE
1.16 and other versions won't generate or load worlds (stuck at 0%) 

### ISSUE THREAD

**Issue by AlNexus** [MultiMC/MultiMC5#3423]
System Information
-----------------------------
MultiMC version:
0.6.11-1430 on win32 (MultiMC 5)
Operating System:
Microsoft Windows 10 Enterprise

Summary of the issue or suggestion:

Whenever I play on recent versions (tested on 1.16, 1.16.3 and 1.16.4) I can't generate nor load worlds. The loading screen is stuck at 0%, with one gray "pixel" in the loading screen thingy. Same happens on 1.17 snapshot (20w45a). I don't know why this happens... Be it OptiFine or Vanilla I can't do anything... On my modpack (1.12.2) everything works fine, version 1.12.2 works but 1.16 does not. Also, I can always join servers, but just can't do anything in singleplayer, if I download a world, I can't load it. If I try to create a world, I also can't do it. I haven't tested it for a long period, I only waited 10 minutes and nothing happened, but I doubt it will make any difference to wait 1 hour, it's probably stuck indefinitely. I tested this on different instances (for the different versions)

What should happen:

The world should load or generate, but nothing happens, just stuck on 0% forever.

Steps to reproduce the issue (Add more if needed):

1. Open Minecraft on versions 1.16.3, 1.16.4 or snapshot 20w45a

2. Click on "Singleplayer" and create a new world or import a world (move a save to the "saves" folder in .minecraft)

3. Try to generate/load world

Suspected cause:
None. Doubt it's my system, probably some issue with Java? I dunno, but Minecraft's official launcher works fine, so MultiMC is probably the issue here. Also, MultiMC shows as "win32", but allocated RAM is 8gb and 32-bit limit is 4gb, but that's probably not the issue here since Forge 1.12.2 works just fine.

Logs/Screenshots:
https://paste.ee/p/D6Bjo (I killed the process because it was stuck on the generating screen and I wanted the log)
![image](https://user-images.githubusercontent.com/44513942/98468652-37e01c80-21ba-11eb-9517-32bbba812a1f.png)

Additional Info:
The instance I'm using has "2 versions installed on it", because I want to share resource packs and shaderpacks between versions, but that's probably not the problem since normal instances and even fresh instances had the same problem.
![image](https://user-images.githubusercontent.com/44513942/98468982-b6898980-21bb-11eb-8449-c1a48e71797e.png)
When I want to play 1.16.4, I just change the version from 1.16.3 to 1.16.4 and disable the 1.16.3 OF jar mod and enable the 1.16.4 OF jar mod, the process is the same for 1.16.3.

**Comment by phit** [comment]
try updating java
https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java#windows

**Comment by AlNexus** [comment]
> try updating java
> https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java#windows

it worked! Thank you so much! :D

**Comment by RGFTheCoder** [comment]
Make sure to close the issue
