### ISSUE TITLE
Minecraft 1.8.9 crash when using Forge

### ISSUE THREAD

**Issue by stepcity** [MultiMC/MultiMC5#3425]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
When I install 1.8.9 and Forge, Minecraft does not launch and displays errors regarding the OneSix launcher. 

What should happen:
------------------------------
Minecraft should launch without any errors.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a new instance of Minecraft 1.8.9

2. Install Forge 11.15.1.1722 (recommended version)

3. Launch Minecraft

Suspected cause:
---------------------------
Forge is broken and causes Minecraft to fail.

Logs/Screenshots:
----------------------------
https://paste.ee/p/uG1QP

Additional Info:
---------------------------
This issue works with any version of Forge, not just the recommended one. I have only tested it on 1.8.9, though.

**Comment by phit** [comment]
install Java 8 
https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java#windows
