### ISSUE TITLE
Crashed with exit code -1

### ISSUE THREAD

**Issue by miki3390** [MultiMC/MultiMC5#3428]
System Information
-----------------------------
MultiMC version:
0.6.11-1430 on win32

Operating System:
Windows 10 Home

Summary of the issue or suggestion:
----------------------------------------------
MultiMC crashes with exit code -1 when trying to launch Volcano Block

What should happen:
------------------------------
MultiMC should finish loading minecraft and launch the game

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download Volcano Block modpack

2. Add it to the instances

3. Launch the modpack

Suspected cause:
---------------------------
Mod issue (?)

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://pastebin.com/vcjg9J0X

Additional Info:
---------------------------
Volcano Block modpack is not loading properly; it stops during the second phase

**Comment by Zetabite** [comment]
discord rich presence seems to crash the game, try disabling it

**Comment by miki3390** [comment]
Where do I disable mods? Never done that before.

**Comment by Zetabite** [comment]
in the instance setting go to loader mods and disable it there

**Comment by miki3390** [comment]
Thanks! It worked!
