### ISSUE TITLE
Cannot create account when starting instance from CLI

### ISSUE THREAD

**Issue by jamierocks** [MultiMC/MultiMC5#3429]
System Information
-----------------------------
MultiMC version: 0.6.11-1344

Operating System: Fedora 32

Summary of the issue or suggestion:
----------------------------------------------

Cannot create account when starting instance from CLI

What should happen:
------------------------------

Allowed to create an account, and continue to play game.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC for first time, create "1.16.4" instance

2. Run `./MultiMC --launch "1.16.4"`

3. Create account in account manager

4. Not able to proceed to launch

**Comment by peterix** [comment]
It walks you through adding an account and then you can run the command again.
