### ISSUE TITLE
On macOS, Java builds after 8u241 break Minecraft

### ISSUE THREAD

**Issue by TonyBurritoNico** [MultiMC/MultiMC5#3431]
So i tried to use multimc on mac and [this](https://pastebin.com/BGW9rkEr) happend i dowloaded java 8 and i worked for some other versions but not this? whats the problem.

**Comment by peterix** [comment]
You need Java 1.8.0_241, not 1.8.0_271.

Uninstall the existing version:
https://explainjava.com/uninstall-java-macos/

Install 241:
https://files.multimc.org/downloads/jre-8u241-macosx-x64.dmg

**Comment by peterix** [comment]
TBD: add this to wiki

**Comment by kthchew** [comment]
For MC 1.8.9, this is currently fixed as of OptiFine M6 pre1. A similar fix also exists for other versions of OptiFine for other MC versions as well, including 1.12.2. To use the latest version of Java, update OptiFine to the latest **preview** version.

**Comment by phit** [comment]
![](https://cdn.discordapp.com/attachments/134843027553255425/829312427769987092/Screenshot_2021-04-07_at_12.11.06.png)

there was also an issue with forge at some point that caused the same crash, which has also been fixed at this point with https://github.com/MinecraftForge/MinecraftForge/pull/7549
