### ISSUE TITLE
Make the Mod List for modpacks exportable to CSV, etc etc...

### ISSUE THREAD

**Issue by Tomodachi94** [MultiMC/MultiMC5#3433]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: Windows 10

Summary of the suggestion: Make the Mod List for modpacks exportable to CSV, etc etc...
----------------------------------------------

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
what do you mean by etc etc?

**Comment by Tomodachi94** [comment]
just some other formats that I might be forgetting

**Comment by Zetabite** [comment]
I dont see the usefullnes tho

**Comment by Tomodachi94** [comment]
For modpack makers who don't want to manually type out their mod lists, or people who want to share their mod list with others.

**Comment by Zetabite** [comment]
Export exists

**Comment by peterix** [comment]
This has been asked for numerous times in the past. It's on the idea pile. I'll just add a +1 to it.

**Comment by LordMZTE** [comment]
This seeme really pointless. One could just ls the mod directory
