### ISSUE TITLE
Minecraft 1.12.2 not fully loading Appears in task bar but no game window other versions of Minecraft work

### ISSUE THREAD

**Issue by Ancientarcher** [MultiMC/MultiMC5#3434]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------
1.12.2 not fully loading Appears in task bar but no game window

What should happen:
------------------------------
Game should launch and open game window

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Using 8 GB of ram for large mod packs

2.Install instance of 1.12.2

3.Run the instance

Suspected cause:
---------------------------
Incompatibility

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/D07rm

Additional Info:
---------------------------
Attempted to use forge to resolve issue not resolved

**Comment by peterix** [comment]
Check if it's not appearing outside the screen space.

But in any case, this is not a launcher bug.
