### ISSUE TITLE
Unable to launch second instance through command line if the instance ID is similar but contains spaced text

### ISSUE THREAD

**Issue by NanoTrasen-Inc** [MultiMC/MultiMC5#3440]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 10

Summary of the issue or suggestion: 
----------------------------------------------
Attempting to launch a second instance via command line -l parameter will instead open the log window of the first instance.
This only occurs when the second instance shares the name of the first one, but with text preceded by a space at the end.

The issue does not occur if the second instance is started first.

**Example**
> \> **`MultiMC.exe -l "1.16.4"`** Functions as expected.
> -_wait for instance to start_-
> \> **`MultiMC.exe -l "1.16.4 2"`** Functions as if I had attempted to start the first instance. (Opens the logging window)

**After renaming "1.16.4 2" to "1.16.4-2":**
> \> **`MultiMC.exe -l "1.16.4"`** Functions as expected.
> -_wait for instance to start_-
> \> **`MultiMC.exe -l "1.16.4-2"`** Functions as expected.

What should happen:
------------------------------
> \> **`MultiMC.exe -l "1.16.4 2"`**

 Should start the instance named 1.16.4 2 regardless of 1.16.4's status.

Steps to reproduce the issue:
-------------------------------------------------------------
1. Create an instance named `test`

2. Create an instance named `test 2`

3. Start instance 1 via `MultiMC.exe -l "test"`

4. Start instance 2 via `MultiMC.exe -l "test 2"`

Suspected cause:
---------------------------
Improper instance collision handling. (Rogue wildcard?) (Failure to parse quoted string?)

Logs/Screenshots:
----------------------------
**Log:** [MultiMC-0.log](https://github.com/MultiMC/MultiMC5/files/5540112/MultiMC-0.log)
**Video:** https://www.youtube.com/watch?v=ZKzKEr7jGoA

**Comment by peterix** [comment]
This is fully intended and will not change.

**Comment by peterix** [comment]
Hmmm. Too fast :)

**Comment by peterix** [comment]
This has been fixed in dev builds and should be in the next release.
