### ISSUE TITLE
MultiMC does not utilize standard command line behavior

### ISSUE THREAD

**Issue by NanoTrasen-Inc** [MultiMC/MultiMC5#3441]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 10

Summary of the issue or suggestion: 
----------------------------------------------
Running MultiMC from the command line does not utilize standard practice regarding command line execution and output handling. This results in _highly_ unexpected behavior for those utilizing MultiMC inside of scripts and other kinds of automation. This also causes significant confusion even during general command line usage.

When MultiMC is executed, the main process immediately forks off itself and continues running in the background.

There are a couple reasons why this is considered bad practice.
1. MultiMC dodges file descriptor redirection, preventing the user from '> /dev/null'-ing the output.
2. MultiMC returns immediately, misleading the shell into thinking that MultiMC has ended when it hasn't.
3. MultiMC overwrites the output from any commands executed along side it.
Ex: `MultiMC.exe -h && echo Success!` Output from 'echo' is overritten by the first line of MultiMC's help text.

![2020-11-13 22_02_34-Command Prompt](https://user-images.githubusercontent.com/1747249/99139969-1ee4ca80-2603-11eb-89da-7a2df62c5eff.png)

Expected behavior:
------------------------------
- MultiMC.exe should stay in the foreground and not fork off of itself.
- Output should come from the main process so it can be redirected using [command redirection](https://ss64.com/nt/syntax-redirection.html).

Video:
----------------------------
**Video:** https://www.youtube.com/watch?v=5GfZ7WOn54I

**Comment by peterix** [comment]
You should not be using MultiMC inside scripts. Automation will not be catered to.

**Comment by peterix** [comment]
Especially on Windows. Windows is not worth doing anything reliable on.

**Comment by peterix** [comment]
I can also tell you that MultiMC is definitely not doing this. It's most likely some other broken thing on your system.

**Comment by peterix** [comment]
Looking at it, the system itself.

**Comment by kb-1000** [comment]
I would expect this to be caused by multimc reattaching to console, while being a GUI application and also marked as such in the EXE and thus not being waited on by command line. I don't see how that's an issue. Any hacky attempts to "fix" this would cause even more problems, it's not worth it.

**Comment by peterix** [comment]
Yeah, MultiMC is not a terminal application on Windows, and Windows discriminates between windowed and terminal applications -- for no good reason.

You get some output only because I am doing this attaching nonsense.

**Comment by LordMZTE** [comment]
i can't seem to reproduce this on windows and git bash

**Comment by kb-1000** [comment]
MSYS (I think that's what this is based on? or was it MinGW?) bash does always wait for command completion and print output, that's to emulate Linux GUI application behavior

**Comment by peterix** [comment]
It may be a `cmd.exe` bug, tbh.

MultiMC calls `AttachConsole` and `FreeConsole` as part of its own code. So it definitely starts, attaches, prints, detaches and exits.

I guess `cmd.exe` does some weird buffering stuff on top of everything.

**Comment by kb-1000** [comment]
Git bash also uses MinTTY, not the classic Windows Console Host, that may cause some differences there
