### ISSUE TITLE
[Suggestion] Link mods to global mods folder

### ISSUE THREAD

**Issue by RGFTheCoder** [MultiMC/MultiMC5#3445]
System Information
-----------------------------
MultiMC version: 0.6.11-1344

Operating System: Kubuntu 20.10

Summary of the issue or suggestion:
----------------------------------------------
When importing modpacks from websites like curseforge, the mods could be downloaded into the already present global mods folder, and then soft-linked into the directory to preserve space on disks, and it shouldn't have any impacts.

**Comment by kb-1000** [comment]
Short version:
That wouldn't work.

Slightly longer version:
While that does sound like a nice idea, softlinks are supported badly by modloaders, and Windows doesn't have proper support for them at all.
You'd run into many, many problems.
Not all file system support them either.

**Comment by phit** [comment]
> While that does sound like a nice idea, softlinks are supported badly by modloaders, and Windows doesn't have proper support for them at all

They work fine on any OS I've ever used, symbolic on Linux and junction on Windows, can't speak for Mac.
Modloaders don't need to anything to support them, Java handles that just fine and it's transparent to the modloaders and mods.

A good reason for this to never be supported in MultiMC is the lack of standardization which would be a hassle to support in MultiMC, but don't blame this on the mod loaders or OS's.

**Comment by kb-1000** [comment]
Junction is for directories, not for files. Windows has no good way to do it for files (that either requires admin or developer mode)

**Comment by RGFTheCoder** [comment]
Maybe it could be an optional feature for Mac/Linux (both unix so I assume `ln` exists) and Windows on admin mode (Although that may be too much)

**Comment by Zetabite** [comment]
OS specific features and optional features based on OS are ugly. It may make a program better for a certain group of users, but the expirience is a totally different one. Additionaly, you would need to maintain OS specific features, while not having them, you can focus fixing them to make the program work the same on all devices

**Comment by kb-1000** [comment]
I'm sorry but if you play Minecraft on admin mode you're stupid.
Especially if you play wirh mods.

**Comment by Zetabite** [comment]
nah, no need to insult. Yes, its unwise, as it makes malicious mods able to execute with admin priviliges

**Comment by peterix** [comment]
I have no plans to solve any problems by using symlinks. Other approaches, maybe. But symlinks are not uniformly supported across systems.
