### ISSUE TITLE
MultiMC segfaults when exiting an edit instance window on Debian 10

### ISSUE THREAD

**Issue by arthomnix** [MultiMC/MultiMC5#3448]
System Information
-----------------------------
MultiMC version: 0.6.12-develop-1393 (bug also occurs on stable)

Operating System: Linux (Debian 10 'buster' KDE) amd64

PC specs: i7-4600u, Intel integrated graphics, 8gb RAM (Lenovo ThinkPad X240)

Summary of the issue or suggestion:
----------------------------------------------
When I exit an 'edit instance' window, MultiMC crashes and I get a popup saying 'MultiMC closed unexpectedly'. When I click the popup I can find this error:
`Executable: MultiMC PID: 27532 Signal: Segmentation fault (11) Time: 18/11/2020 17:52:52`

What should happen:
------------------------------
The edit instance window should close without a crash, leaving the main window open

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC

2. Right click any instance and press Edit Instance

3. Close the edit instance window (either through the title bar or pressing Close in the bottom right)

Suspected cause:
---------------------------
Honestly I have no idea

Logs/Screenshots:
----------------------------

https://hastebin.com/ifumahuxil (MultiMC log file)
https://hastebin.com/guqovoqero (Backtrace from KDE error reporter)
https://github.com/arthomnix/random/tree/master/multimc-bug-screenshots (Some screenshots)

Additional Info:
---------------------------
The log does not appear to contain any errors.

**Comment by peterix** [comment]
This is a bug in Qt that Debian should backport.

**Comment by peterix** [comment]
See: https://bugreports.qt.io/browse/QTBUG-68393

**Comment by peterix** [comment]
In other words: I can't help you, your distro package maintainers should.
