### ISSUE TITLE
Make playtime display/recording optional

### ISSUE THREAD

**Issue by Fidgetcetera** [MultiMC/MultiMC5#3450]
System Information
-----------------------------
MultiMC version: 0.611-1344

Operating System: Linux (Xubuntu 20.04)

Summary of the issue or suggestion: 
----------------------------------------------
Suggestion to disable displaying and recording playtime for instances of Minecraft.

What should happen: 
------------------------------
A setting, could be either global or per-instance, would disable the display and/or recording of the amount of time you've used that instance. 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
Not an issue.

Suspected cause:
---------------------------
Again, not a bug.

Logs/Screenshots:
----------------------------
Doesn't seem necessary here.

Additional Info:
---------------------------
I know several people who actively dislike seeing how much time they play a game for. It can act as a mark of shame, or just feel inaccurate if you've left a game open a lot. It's the sort of thing that isn't a stat that always needs tracked, and would be nice to be able to turn off.

**Comment by jamierocks** [comment]
Fixed by https://github.com/MultiMC/MultiMC5/commit/de089195cdb79c7f5cf46dd78782d6da5401d8da.
