### ISSUE TITLE
[FEATURE REQUEST] Ability to import zip file from windows file explorer context menu

### ISSUE THREAD

**Issue by mylesbartlett72** [MultiMC/MultiMC5#3453]
System Information
-----------------------------
MultiMC version:0.6.11-1430

Operating System:MS Windows 10 Enterprise v10.0.17134 Build 17134

Summary of the issue or suggestion:
----------------------------------------------
I would like the option to import a modpack directly from Windows file explorer, in the context menu.

What should happen:
------------------------------
1.Find a zip archive (e.g. one used by a modpack)

2.Right click it

3.Click the context menu icon to import with MultiMC

4.MultiMC checks whether it is a modpack and if so, opens the add instance dialog with location pre-filled.

5.Add Instance dialog is then used as normal.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Find a zip archive (e.g. one used by a modpack)

2.Right click it

3.There is no context menu option to import with MultiMC (or do similar)

Suspected cause:
---------------------------
Not yet implemented

Logs/Screenshots:
[https://raw.githubusercontent.com/mylesbartlett72/bugreports-images-logs-mylesbartlett72/main/multimc/multimc-fileexplorer-integration.PNG](https://raw.githubusercontent.com/mylesbartlett72/bugreports-images-logs-mylesbartlett72/main/multimc/multimc-fileexplorer-integration.PNG)

Also attached directly here:
![multimc-fileexplorer-integration](https://user-images.githubusercontent.com/44680463/99898580-5bb36000-2c9a-11eb-93de-e15092eaeeb5.PNG)

----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
My MultiMC architecture is 32-bit - as 32-bit programs cannot interface with 64-bit ones(file explorer) a plugin/new build for 64-bit windows may be neccesarry.

**Comment by peterix** [comment]
Not going to happen.

**Comment by peterix** [comment]
Main reason is that this doesn't fit into how MultiMC is distributed and that it does not mess with the system it's on.
This needs deep integration into Windows, and it's way out of scope of what MultiMC 5 is supposed to be.
