### ISSUE TITLE
[Doubt] Update Channels

### ISSUE THREAD

**Issue by Werner1201** [MultiMC/MultiMC5#3455]
Does the .deb version of MultiMC has a update channel selection just like in the Windows Version? Independent of Which version on the website we download ? Because I downloaded the stable version and I can go to the development channel, If Install MultiMC on Ubuntu via .deb will I be able to do the same and receive updates ?

**Comment by peterix** [comment]
Yeah. The deb is just an icon and a small script that fetches the normal version of the launcher and/or starts it when it's present.

**Comment by Werner1201** [comment]
Thank for the fast and precise answer! Have a good day!
