### ISSUE TITLE
Forge not working with MultiMC(mac)

### ISSUE THREAD

**Issue by itisputin** [MultiMC/MultiMC5#3457]
I have tried to open forge but it keeps crash before it launches. Whats strange is when I use vanilla it works perfectly.

Here is the crash info:

MultiMC version: 0.6.11-1370

Minecraft folder is:
/Applications/MultiMC.app/Contents/MacOS/instances/modded 1(1.7.10)/.minecraft

Java path is:
/usr/bin/java

Java is version 15, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /Applications/MultiMC.app/Contents/MacOS/instances/modded 1(1.7.10)/natives

Libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/netty/1.6/netty-1.6.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1566-1.7.10/forge-1.7.10-10.13.4.1566-1.7.10-universal.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-osx.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-osx.jar

Mods:
  [✔️] OptiFine_1.7.10_HD_U_E7
  [✔️] TerraFirmaPunk-2.1.0-1.7.10

Params:
  --username  --version MultiMC5 --gameDir /Applications/MultiMC.app/Contents/MacOS/instances/modded 1(1.7.10)/.minecraft --assetsDir /Applications/MultiMC.app/Contents/MacOS/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType  --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: modded 1(1.7.10)", -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 1049

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code 255.
Clipboard copy at: 24 Nov 2020 18:54:56 -0500

I am not very tech savvy and I am new to MultiMC so if someone could help that would be great.

**Comment by Zetabite** [comment]
You are using java 15, which isnt supported by anything tbh. Install java 8: https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java
