### ISSUE TITLE
MultiMC won't let me launch anything below 1.15?             

### ISSUE THREAD

**Issue by dunnoauser** [MultiMC/MultiMC5#3459]
I've been trying to launch 1.8.8 and 1.12.2 for Minecraft servers with a lower version and PVP. I have no clue what's happening, I'm pretty sure I the latest version of Java, can anyone help me out? Sorry if I give a late response. I'm on the latest version of MultiMC.
https://paste.ee/p/KnoBR
Thank you for helping.
edit: I'm not using any modpacks, its pure vanilla I'm using linux

**Comment by spannerman79** [comment]
https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java#linux

**Comment by dunnoauser** [comment]
> https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java#linux

I did it, didn't work, thanks though. </3

**Comment by spannerman79** [comment]
For archive purpose;

Duplicate of https://github.com/MultiMC/MultiMC5/issues/3254 and https://github.com/MultiMC/MultiMC5/issues/2862.

**Comment by xsun2001** [comment]
https://askubuntu.com/questions/695560/assistive-technology-not-found-awterror

You may need to comment out the following line in `accessibility.properties` file of your jdk\jre. And check twice if you are using a headless jdk.

```
# assistive_technologies=org.GNOME.Accessibility.AtkWrapper
```

**Comment by dunnoauser** [comment]
Thanks, it works now!
