### ISSUE TITLE
Ability for patches to specify Java agents

### ISSUE THREAD

**Issue by unascribed** [MultiMC/MultiMC5#3461]
I'm working on something that needs to specify -javaagent in the JVM arguments for a premain handler. I see this was previously discussed in #764, but was rejected due to the fact MultiMC was performing weird hacks to get around Windows being busted as usual. However, as of the fix for #1997, these hacks have been removed, meaning premain handlers via simply using -javaagent should be acceptable now.

Currently, I'm doing this by just overriding the "Java arguments" setting for the instance, but it'd be preferable if this could be done "correctly" and with dependency resolution/download via the patches system, instead of having to drop a jar into the .minecraft directory and possibly clobber a user's preferred Java arguments.

I can make an attempt at implementing this and PR'ing it, but I want to know if there'd be interest in merging such a PR before I go to the trouble of implementing it. This is kind of niche, to be fair.

The way I see this syntax working is a `"javaagent": true` option on a library entry. A more generic way to add JVM arguments would also be a good solution, as long as there were a way to get a path to a downloaded dependency via some kind of placeholder.

**Comment by peterix** [comment]
What do you want to use this for?

Why not just plain old mod loaders?

This is some seriously weird tech that I would prefer to not have to deal with at all.

**Comment by unascribed** [comment]
I'm attempting to automatically sync the game directory before launch to facilitate updating in a launcher-agnostic fashion. I'm not using Instrumentation. A mod loads far too late to accomplish this, and agents exist anywhere Java 7+ does.

This could also be used to inject more complex Instrumentation-based agents like LWJGLX-Debug, which is useful for debugging various kinds of native crashes that have become more common in LWJGL3-based versions of Minecraft. Though I admit that's flimsy justification, a debug tool is fine to just hardcode in your own Java arguments temporarily.

Java agents are easily less weird than most of the trickery done by mod loaders. I'd also be happy with mainClass chaining similar to what Fabric does internally by defining the mainClass chain in a system property; that's a lot more work than just allowing premain handlers via agents though.

**Comment by peterix** [comment]
OK. Then this is a no. This is something only the launcher or user should do, not something that does things behind their backs during launch.

**Comment by kb-1000** [comment]
> Why not just use plain old mod loaders?

Please be aware that some older mod loaders indeed do use Java agents, to be able to specify them as patches, this would be a requirement (I think)
Of course, for _new_ stuff, I would recommend not using them (IIRC they have some performance impact)

**Comment by unascribed** [comment]
> OK. Then this is a no. This is something only the launcher or user should do, not something that does things behind their backs during launch.

Why would you assume this happens "behind the [user's] back?" Yes, it has a GUI, and it asks permission. If MultiMC had an updater other than importing ZIPs (which is *not* an updater) then I probably wouldn't even be doing this.

> Of course, for new stuff, I would recommend not using them (IIRC they have some performance impact)

Premain agents do not have a performance impact. Instrumentation is no heavier than the ASM tricks all loaders do.
