### ISSUE TITLE
Can't find Java compiler even though OpenJDK8 JDK is installed (and javac is available)

### ISSUE THREAD

**Issue by PureTryOut** [MultiMC/MultiMC5#3465]
System Information
-----------------------------
MultiMC version: git master, as of this writing f4d58e17eeb5bd608766acfebe425925d40d5825

Operating System: Alpine Linux

Summary of the issue or suggestion:
----------------------------------------------
I'm trying to compile MultiMC5 for myself, but it fails to find a Java compiler even though javac is present on my system and OpenJDK8 is installed.

```
> apk info -L openjdk8
openjdk8-8.272.10-r2 contains:
usr/lib/jvm/java-1.8-openjdk/ASSEMBLY_EXCEPTION
usr/lib/jvm/java-1.8-openjdk/LICENSE
usr/lib/jvm/java-1.8-openjdk/THIRD_PARTY_README
usr/lib/jvm/java-1.8-openjdk/release
usr/lib/jvm/java-1.8-openjdk/bin/clhsdb
usr/lib/jvm/java-1.8-openjdk/bin/extcheck
usr/lib/jvm/java-1.8-openjdk/bin/hsdb
usr/lib/jvm/java-1.8-openjdk/bin/idlj
usr/lib/jvm/java-1.8-openjdk/bin/jar
usr/lib/jvm/java-1.8-openjdk/bin/jarsigner
usr/lib/jvm/java-1.8-openjdk/bin/java-rmi.cgi
usr/lib/jvm/java-1.8-openjdk/bin/javac
...
```

What should happen:
------------------------------
It should pick up the OpenJDK8 compiler.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Get an Alpine Linux system, a Docker container should do the trick

2. `# apk add openjdk8`

3. Try to compile MultiMC5

Suspected cause:
---------------------------
I see on Alpine Linux OpenJDK8 gets installed under `/usr/lib/jvm/java-1.8-openjdk` where on for example Arch Linux it gets installed under `/usr/lib/jvm/java-8-openjdk`. I guess this confuses CMake? 1.8 is however a valid Java version number.

Logs/Screenshots:
----------------------------
```
> cmake -B build -DMultiMC_LAYOUT_REAL=lin-system
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Git commit: f4d58e17eeb5bd608766acfebe425925d40d5825
-- Git refspec: refs/heads/develop
Using override nbt++ name: MultiMC_nbt++
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
/home/bart/Documents/Git/MultiMC5/cmake
CMake Error at libraries/launcher/CMakeLists.txt:2 (project):
  No CMAKE_Java_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "JAVA_COMPILER" or the CMake cache entry CMAKE_Java_COMPILER to
  the full path to the compiler, or to the compiler name if it is in the
  PATH.


-- Configuring incomplete, errors occurred!
```

**Comment by peterix** [comment]
Java versioning has changed multiple times, and it's super confusing.

But Java 1.8 definitely does NOT exist. 1.4 is the last one with the `1.` prefix.

So in this case, the distro package maintainers are making things up.

**Comment by peterix** [comment]
Also: https://www.oracle.com/java/technologies/javase/naming-and-versions.html

**Comment by PureTryOut** [comment]
Sorry but I have to correct you, 1.8 _does_ exist and is what most people call Java 8.

Check https://www.oracle.com/java/technologies/javase/8u51-relnotes.html for example:

> The full version string for this update release is 1.8.0_51-b16 (where "b" means "build"). The version number is 8u51.

**Comment by Zetabite** [comment]
The versioning of java is just garbage, hence the confusion. If you use OpenJDK 8/11 in IntelliJ for example, it will show Java 1.8 as option for legacy mode.

**Comment by PureTryOut** [comment]
Well [we changed the paths (and kept the old location for compatibility)](https://gitlab.alpinelinux.org/alpine/aports/-/commit/b2b2034019c875043d0175383d67f8d0aea0bf12), but I still have the same problem. It seems I can get a bit further by using the `JAVA_COMPILER` environment variable when running CMake, but I'm not entirely sure what path to pass to it.

**Comment by mjevans** [comment]
You need the **java** binary; the javac binary just compiles source code to byte code, it does not execute the bytecode.

https://www.tutorialspoint.com/what-is-the-difference-between-javac-java-commands

On ArchLinux my java binary is located in /usr/lib/jvm/java-8-openjdk/bin/java

On AlpineLinux openjdk8 depends on openjdk8-jre-lib which contains the binary...

https://pkgs.alpinelinux.org/contents?branch=edge&name=openjdk8-jre-base&arch=x86_64&repo=community

/usr/lib/jvm/java-1.8-openjdk/bin/java

Generally /usr/lib/jvm/*/bin/java is one of the globs that should be checked for possible versions of Java to try.

**Comment by phit** [comment]
@PureTryOut do you have a log with `JAVA_COMPILER` set? where does it fail then? or is this resolved and can be closed?

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to let us know and we'll reopen this issue.
