### ISSUE TITLE
Huge performance loss on MultiMC 5 0.6.11-1370 on osx64 vs Vanilla Launcher

### ISSUE THREAD

**Issue by BeanieBen9990** [MultiMC/MultiMC5#3466]
System Information
-----------------------------

MultiMC version: MultiMC 5 0.6.11-1370 on osx64

Operating System: OSX Big Sur Beta Build 20A5395g (Beta 11 I think)

Summary of the issue or suggestion:
----------------------------------------------

Using 1..16.4 and haven't tested any other version other than adding Optifine, which didn't help. Huge performance loss. Talking 20 less fps (50-60 on Vanilla Launcher and 30-40 on MultiMC) no other processes running, same bundled java and command line options, for testing purposes, same texture pack, settings, world files, everything. As far as I can tell, literally everything is the same other than how it's launched. 

What should happen:
------------------------------

Should be getting around 60 fps, with some regular dips, but over 40 fps always. Playable. Getting 30-40 consistent, with dips as low as 5. 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open 1.16.4 instance in Vanilla Launcher. Note fps

2. Open 1.16.4 instance in MultiMC Launcher. Note fps

3. Compare FPS

Suspected cause:
---------------------------

Not totally sure... maybe some random memory bug or cpu utilization setting not present in MultiMC or Vanilla Launcher

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Couldn't take video of FPS, as it made the FPS much less stable and much less in general. I tried to get just about the same exact screenshot of running toward trees to get the FPS about what it usually is while looking around and generally playing the game. Although standing still or looking at one thing has much less of a difference between versions, as it'll most likely hit the cap of 60, normal gameplay is looking around and moving, and that has a huge difference. 

![Screen Shot 2020-12-01 at 12 59 50 PM](https://user-images.githubusercontent.com/29309688/100778651-44c8e800-33d5-11eb-9d43-78ee8a951589.png)

![Screen Shot 2020-12-01 at 12 55 27 PM](https://user-images.githubusercontent.com/29309688/100778661-485c6f00-33d5-11eb-952a-58c9d3d25b7f.png)

Additional Info:
---------------------------

I do not have a dGPU. Using integrated Intel 620 graphics on an i58250U

**Comment by kb-1000** [comment]
Possibly some stupid heuristics check for the vanilla launcher and enable some "high performance mode"... who knows. Anyways, that's beyond MultiMC's control, most likely

**Comment by peterix** [comment]
Sounds like macOS being broken to me, tbh. There should be no difference.

**Comment by peterix** [comment]
If you're running a beta of the OS, I'd say try updating that to the current version.

Other than that, no idea.

**Comment by switch64** [comment]
I've tried this on catalina, and <img width="1920" alt="Screen Shot 2020-12-20 at 1 35 38 PM" src="https://user-images.githubusercontent.com/42489380/102724995-5c0a3f80-42c8-11eb-83c8-0283e4b8e137.png">
<img width="1920" alt="Screen Shot 2020-12-20 at 1 40 15 PM" src="https://user-images.githubusercontent.com/42489380/102725076-f2d6fc00-42c8-11eb-8f7f-b29c50faa957.png">

**Comment by spannerman79** [comment]
Look at the two java versions used in those screenshots.


Find a java version that is the same that is bundled with the Vanilla launcher if indeed you wish to correctly replicate between Vanilla launcher and MultiMC @switch64

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, please reproduce this with matching Java versions. Realistically if this is even an issue, it probably won't be fixable by MultiMC and is out of our control.

**Comment by mhossein1384** [comment]
I Tried that with my m1 (maybe the problem is solved but) It Is the java version after changing to the latest it's working as good
