### ISSUE TITLE
Minecraft crashes every time I start it up

### ISSUE THREAD

**Issue by Shaneinei** [MultiMC/MultiMC5#3468]
I've tried everything at this point, this is out of my expertise. I've tried updating my Java, allocating more ram, reinstalling MultiMC.

I specifically found this interesting:
"Failed to write core dump. Minidumps are not enabled by default on client versions of Windows"
I later went to search it up but nothing really helped, that's when I ended my search and now I'm here.

Here's the Pastebin of the crash report.
https://paste.ee/p/WaTKB

**Comment by jotoho** [comment]
```
# An error report file with more information is saved as:
# C:\Users\Michael\Desktop\MulitMC\MultiMC\instances\1.8.9\.minecraft\hs_err_pid43192.log
```

The crash report you linked refers to this other logfile for more information. Perhaps it would help debug the issue if you upload that aswell?

Also while your version is the newest Java 8 Runtime Environment available on oracle.com, [there seems to be a slightly newer version available from AdoptOpenJDK.](https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=hotspot) (build 271 -> 275)

As an end user you probably only need the JRE and not the full JDK. Don't know if this upgrade would help but it might be worth a try...

**Comment by jotoho** [comment]
Also I don't think the core dump is what caused the problem. From my limited understanding those are snapshots of a programs memory that can be saved to disk to help diagnose issues with software but they are normally only written AFTER the error occured.
And the minidumps are probably disabled for a normal user to prevent them from flooding their disks when most people don't know how to use them. (At least that's my guess)

**Comment by spannerman79** [comment]
You are wrong on both counts @jotoho 

@Shaneinei the issue is your Intel GPU driver - from the crash log;

```
Problematic frame:
# C  [ig7icd64.dll+0x22bfa]
```

`ig7icd64.dll` is Intels Intergrated graphics stack driver.

I suggest following https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs

**Comment by Shaneinei** [comment]
> You are wrong on both counts @jotoho
> 
> @Shaneinei the issue is your Intel GPU driver - from the crash log;
> 
> ```
> Problematic frame:
> # C  [ig7icd64.dll+0x22bfa]
> ```
> 
> `ig7icd64.dll` is Intels Intergrated graphics stack driver.
> 
> I suggest following https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs

I got this message: https://i.imgur.com/S9dsEbW.png

**Comment by spannerman79** [comment]
Follow the instructions on that wiki link **exactly**.

**Comment by Shaneinei** [comment]
> Follow the instructions on that wiki link **exactly**.

I extracted the file to my MultiMC folder and the same thing just happens. Tried both x64 and x32 bit.
Here the's crash report: https://paste.ee/p/ge6VI

**Comment by spannerman79** [comment]
No you didn't.  The wiki link I gave uses Java 8u51.

From the log;

`Java is version 1.8.0_271, using 32-bit architecture.`  That is Java 8u271

**Comment by Shaneinei** [comment]
> No you didn't. The wiki link I gave uses Java 8u51.
> 
> From the log;
> 
> `Java is version 1.8.0_271, using 32-bit architecture.` That is Java 8u271
> 
> Also the path of the java version you installed;
> 
> ```
> Java path is:
> C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe
> ```
> 
> If you followed the wiki that path would be different.
> 
> Once again - follow the wiki link I gave previously and will **again** provide - https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs

Oh my god, thank you so much. I got so confused and didn't realize I had to redirect the Java Path to "jre1.8.0_51/bin/javaw.exe"
Again, thank you. I really appreciate it.
