### ISSUE TITLE
Doesn't seem to allocate the set amount of ram

### ISSUE THREAD

**Issue by amatuerspice** [MultiMC/MultiMC5#3469]
System Information
-----------------------------
MultiMC version: 0.6011-1430

Operating System: Windows 10 (amd64) version 10.0

Summary of the issue or suggestion:
----------------------------------------------
I'm helping a friend set up FTB Revelation, and we have set them RAM to 8GBs, and every time they launch the game, it'll load for a while and then crash. On the crash report it says it due to Caused by: java.lang.OutOfMemoryError: Java heap space
Here is the paste.ee file for more info
https://paste.ee/p/BtjdT

**Comment by spannerman79** [comment]
From the log (line 283)

```
Java Arguments:
[-Xmx8G, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx2500m, -Duser.language=en]
```

You don't set the amount of ram allocated within JVM arguments - you actually set it in max memory allocation - see https://github.com/MultiMC/MultiMC5/wiki/Java-settings

**Comment by Scotsguy** [comment]
This is not a MultiMC issue, closing.
