### ISSUE TITLE
Date added list? (from issue #338)

### ISSUE THREAD

**Issue by ReceivedChunky** [MultiMC/MultiMC5#347]
This is an issue relating to an idea on a separate issue (#338; I was asked to split it into parts).

I added a second idea to the issue:

"I'd also like to see a "date added" list for mods - this is because when I add a mod and I don't know which one is causing the crash (like with a Packet24MobSpawn crash), I can't tell which one it is if I have downloaded it ages ago (there is no "date added" option in Windows Explorer)."

**Comment by peterix** [comment]
Moved to workflowy

**Comment by brodycas3** [comment]
mmmm nice

**Comment by peterix** [comment]
Yep.

Why haven't I done this earlier? It was so easy! :smile: 

It's not exactly 'date added' - it's 'date changed'. But in most cases, that should be the same. Plus knowing that something changed without you doing it is good too.

**Comment by peterix** [comment]
Had to change one more thing - adding a mod through MultiMC forces a change to the 'changed' timestamp of the mod.
