### ISSUE TITLE
Fully updated system alwasys exits process with error code -1

### ISSUE THREAD

**Issue by NorielSylvire** [MultiMC/MultiMC5#3471]
System Information
-------------------------------------------------------------
MultiMC version:
-------------------------------------------------------------
MultiMC 5 Version 0.6.11-1430. Says to be the latest stable version, freshly downloaded before re-trying to use the app.

Operating System:
-------------------------------------------------------------
Windows 10 Professional Edition 64 Bits updated half an hour ago.

System Specifications:
-------------------------------------------------------------
ASUS Tufgaming FX DT505 model (laptop) with
- AMD Rysen 7 3750H CPU (with integrated AMD Radeon Vega 10 GPU)
- NVidia GeForce GTX 1650 with freshly updated drivers
- 10240 mebibytes of max ram allocated to MultiMC
- A stable internet connection
- Lots of disk space
- Bought copy of both java and bedrock editions of the game

Summary of the issue or suggestion:
-------------------------------------------------------------
All Modpacks, official FTB modpacks installed using the app, 3rd party FTB modpacks installed using the app, and modpacks installed using zip files that previously (one month ago) all worked, both online and offline, now don't work either online or offline, before and after restarting, same error message always with everything.
Vanilla minecraft installations installed two minutes ago work just fine.
This is the error log for the modded installations.
I just deleted one legacy ftb instance and reinstalled it using the app and got the same error log.
https://paste.ee/p/aSf1R and this is a copy of the error log I get with all installations.

-------------------------------------------------------------

What should happen:
-------------------------------------------------------------
I should click either laingh or offline launch and the game should start correctly

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open the app

2. Select one already installed instance or install an instance and select it

3. Click launch upon selecting an instance

Suspected cause:
-------------------------------------------------------------
Maybe java is not updated? If so why is vanilla minecraft both with the official launcher and with MultiMC working, modded minecraft with official launcher working and modded minecraft with MultiMC not working? Edit: Updated java and still doesn't work.

Logs/Screenshots:
https://paste.ee/p/aSf1R
-------------------------------------------------------------

**Comment by NorielSylvire** [comment]
Fixed this issue myself by:
-------------------------------------------------------------
instead of pasting the zipped files provided by MultiMC and overwriting the files in your current installation of the app, backup your modpack instances from the app's files, and delete that folder, then unzip the files provided by MultiMC, open the app with no installations, choose youre language and such, then close it, and paste the instances folder inside the newly created MultiMC folder and tadah! Works again. Also, you'll need to re-assign icons to all instances.

**Comment by spannerman79** [comment]
For archive and search purposes;

From the paste.ee log two sections need attention.

> **Java is version 15**, using 64-bit architecture.

and also

```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
```

Using Java > 8 is the actual issue here. https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java
