### ISSUE TITLE
Roguelike adventure and dungeons doesn't start

### ISSUE THREAD

**Issue by skusku1601** [MultiMC/MultiMC5#3474]
to be honest, i don't have much knowledge about these problemes. but i try to start Roguelike adventure and dungeons mincraft mod but it doesn't work. my first try was with curseforge but because that didn't work and i saw a thread that said to try multimc i tried it. but it still didn't work i manage to copy the logg so i will link that.

Hope somebody can help me and thank you in advance 
---------------------------

Logs/Screenshots:https:https://paste.ee/p/8M7gS
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
i do have a red cross by session in multimc but i don't know if that has anything to do with this problem

**Comment by kb-1000** [comment]
```
Process was killed by user.
```
If you abort it, it dies. Yes.

**Comment by skusku1601** [comment]
> ```
> Process was killed by user.
> ```
> 
> If you abort it, it dies. Yes.


yea i killed the game because it didn't work, the application was on the windows bar but when i klicked on it the game didn't come forward.

**Comment by skusku1601** [comment]
> ```
> Process was killed by user.
> ```
> 
> If you abort it, it dies. Yes.

https://paste.ee/p/8M7gS

sorry i posted the wrong log i think this is what happens when i don't kill it

**Comment by phit** [comment]
update llibrary to https://www.curseforge.com/minecraft/mc-mods/llibrary/files/3116493

**Comment by skusku1601** [comment]
> update llibrary to https://www.curseforge.com/minecraft/mc-mods/llibrary/files/3116493

thank you for your reply but how do i update this i downloaded the file and now?

**Comment by phit** [comment]
put it in the mods folder of the instance and delete the old version

**Comment by Scotsguy** [comment]
This is not a MultiMC issue, closing.
