### ISSUE TITLE
Add Support For Microsoft Accounts

### ISSUE THREAD

**Issue by MiniDigger** [MultiMC/MultiMC5#3475]
Hey, 

just letting you know that I just published a draft documentation of the new authentication scheme for the new microsoft accounts: https://wiki.vg/Microsoft_Authentication_Scheme

All new accounts created now have to use this scheme, over the old scheme.

My sample impl is here: https://github.com/MiniDigger/MiniLauncher/blob/master/launcher/src/main/java/me/minidigger/minecraftlauncher/launcher/gui/MsaFragmentController.java

I would look into PRing this, but, C++ is scarry, I have no idea how QT works, and this is better fit for somebody who actually knows the codebase.

**Comment by sp1ritCS** [comment]
> My sample impl is here: https://github.com/MiniDigger/MiniLauncher/blob/master/launcher/src/main/java/me/minidigger/minecraftlauncher/launcher/gui/MsaFragmentController.java

If I see this correct, your sample impl is still executing non-free javascript directly from M$ Servers. I'd wish to avoid this.

I'm required to use a web-app that uses m$ oauth for sign-in. I've created a [cli app that I can avoid executing non-free js](https://github.com/sp1ritCS/libschulmanager/tree/master/src/o365). I don't know if this helps in this case, as that "Microsoft Authentication Scheme" seems a bit more complex. But it might help as a reference (even tho the code-quality is shit 🙃)

**Comment by MiniDigger** [comment]
I am not sure if microsoft would (or should) allow this in this case. This endpoint is meant to be used interactively for security purposes. It's not meant to be used with custom UI (like the app flows are for example)

worth noting that my impl is outdated, as it used the mojang app id for communicating with MSA/Azure AD, refer to the since updated docs to see how to generate your own azure application.

**Comment by peterix** [comment]
Having a github issue for this has no value.
