### ISSUE TITLE
Older Versions of MC not functioning after Java Updates

### ISSUE THREAD

**Issue by Saffron-uni-Canux** [MultiMC/MultiMC5#3477]
System Information:
-----------------------------
MultiMC version: 0.6.12

Operating System: Linux Manjaro KDE

Summary of the issue or suggestion: 
----------------------------------------------
Older Versions of MC (e.g; 1.12.2) crash upon launch, even with Java-8-openjdk being the only version of Java installed which from my understanding means that older versions should function

What should happen:
------------------------------
Older versions such as 1.12.2 should launch as normal, as they did before the java / MC update

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install Manjaro KDE using the .iso from the official website

2. Update OS and build MultiMC from the AUR package provided by the "Add/Remove Software" pkg manager GUI

3. Select Java-8-openjdk and launch an older version of Minecraft which will then crash with error 255

Suspected cause:
---------------------------
Improper Java Installation

To be honest i suspect this may be some idiocy on my part and i simply misunderstand how Java should be properly installed but I'm not sure and I've tried and searched for solutions that i could think of and had seen but I've been unable to troubleshoot the issue. 

Logs/Screenshots:
----------------------------
https://paste.ee/p/BZisM 

Additional Info:
---------------------------
N/A

**Comment by phit** [comment]
install xrandr

**Comment by Saffron-uni-Canux** [comment]
I currently have "libxrandr" and "xorg-xrandr" installed... is that what your referring too?

**Comment by phit** [comment]
so there's two common reasons for this bug to usually happen, either you don't have xrandr installed or you have some weird display setups lwjgl 2 doesn't like
if xrandr is installed, what is the output of `xrandr -q`

**Comment by Saffron-uni-Canux** [comment]
Here is the ouptut:

Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 16384 x 16384
HDMI-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x1080     74.97 +  60.00*   50.00    59.94  
   1920x1080i    60.00    50.00    59.94  
   1680x1050     59.88  
   1280x1024     60.02  
   1440x900      59.90  
   1280x800      59.91  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      70.07    60.00  
   800x600       60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       66.67    60.00    59.94  
   720x400       70.08  
DVI-D-1-0 disconnected
HDMI-1-0 connected
   1920x1080     60.00 +  60.00    59.94    50.00    23.98  
   4096x2160     23.98  
   3840x2160     30.00    29.97    25.00    23.98    23.98  
   2560x1600     59.97  
   2560x1440     59.95    30.00  
   1920x2160     59.99  
   1920x1200     59.88  
   1680x1050     59.95  
   1600x900      60.00  
   1440x900      59.89  
   1280x1024     75.02    61.00  
   1280x800      59.81  
   1280x720      59.94    50.00  
   1152x864      60.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    72.81    59.93    59.94  
DP-1-0 disconnected
DP-1-1 disconnected
  1920x1080 (0x45) 148.500MHz +HSync +VSync
        h: width  1920 start 2008 end 2052 total 2200 skew    0 clock  67.50KHz
        v: height 1080 start 1084 end 1089 total 1125           clock  60.00Hz
  1920x1080 (0x46) 148.500MHz +HSync +VSync
        h: width  1920 start 2448 end 2492 total 2640 skew    0 clock  56.25KHz
        v: height 1080 start 1084 end 1089 total 1125           clock  50.00Hz
  1280x720 (0x51) 74.250MHz +HSync +VSync
        h: width  1280 start 1720 end 1760 total 1980 skew    0 clock  37.50KHz
        v: height  720 start  725 end  730 total  750           clock  50.00Hz
  1024x768 (0x53) 75.000MHz -HSync -VSync
        h: width  1024 start 1048 end 1184 total 1328 skew    0 clock  56.48KHz
        v: height  768 start  771 end  777 total  806           clock  70.07Hz
  1024x768 (0x54) 65.000MHz -HSync -VSync
        h: width  1024 start 1048 end 1184 total 1344 skew    0 clock  48.36KHz
        v: height  768 start  771 end  777 total  806           clock  60.00Hz
  800x600 (0x55) 40.000MHz +HSync +VSync
        h: width   800 start  840 end  968 total 1056 skew    0 clock  37.88KHz
        v: height  600 start  601 end  605 total  628           clock  60.32Hz
  800x600 (0x56) 36.000MHz +HSync +VSync
        h: width   800 start  824 end  896 total 1024 skew    0 clock  35.16KHz
        v: height  600 start  601 end  603 total  625           clock  56.25Hz
  720x576 (0x57) 27.000MHz -HSync -VSync
        h: width   720 start  732 end  796 total  864 skew    0 clock  31.25KHz
        v: height  576 start  581 end  586 total  625           clock  50.00Hz
  720x480 (0x59) 27.000MHz -HSync -VSync
        h: width   720 start  736 end  798 total  858 skew    0 clock  31.47KHz
        v: height  480 start  489 end  495 total  525           clock  59.94Hz
  640x480 (0x5c) 25.175MHz -HSync -VSync
        h: width   640 start  656 end  752 total  800 skew    0 clock  31.47KHz
        v: height  480 start  490 end  492 total  525           clock  59.94Hz

**Comment by Saffron-uni-Canux** [comment]
Ohh, ok well i just removed my dummy display that i use for VMs and it seems to work fine now, strange

**Comment by phit** [comment]
looks like https://github.com/LWJGL/lwjgl/issues/129
`HDMI-1-0 connected` this screen is connected but disabled

**Comment by Saffron-uni-Canux** [comment]
Yeah, dummy plug in, MC crashes out, dummy plug out MC works fine
Well I'll see if i can work around that later but thanks for the help, never would have guessed it was a display issue!

**Comment by Saffron-uni-Canux** [comment]
Aaaaand i just got around it, had to make the main display a replica of the dummy, again thank you, this issue has been bugging me for awhile

**Comment by RudiAusBuddeln** [comment]
@phit I love you bro
