### ISSUE TITLE
i put mods into the folder and launch but it loads vanilla 1.12.2

### ISSUE THREAD

**Issue by pr0ff** [MultiMC/MultiMC5#3482]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by pr0ff** [comment]
i put the mods into loader mod folder

**Comment by 69420XD** [comment]
did you install forge?

**Comment by Scotsguy** [comment]
Please fill out the issue template.
