### ISSUE TITLE
My skin is not appearing even though I have uploaded it.

### ISSUE THREAD

**Issue by KGXSparks** [MultiMC/MultiMC5#3483]
Is their something I am missing? I upload the skin  but it still does not work. Any ideas?
![image](https://user-images.githubusercontent.com/74122236/102012484-06bfb280-3d4b-11eb-9fbf-60df013d0366.png)

**Comment by Zetabite** [comment]
Upload via minecraft website. This feature doesnt work properly due to mojangs side
