### ISSUE TITLE
New FTB is Missing from Linux version (MultiMC 5)

### ISSUE THREAD

**Issue by Flare183** [MultiMC/MultiMC5#3485]
When creating a new instance of Minecraft, I am unable to download the new versions of FTB. This CAN be done on windows, however I am using Linux.
Here is a screenshot proving the point:
![Screenshot_2020-12-15_12-11-18](https://user-images.githubusercontent.com/4323/102249174-11f01b00-3ed0-11eb-90c8-899fa0640f3d.png)

**Comment by kb-1000** [comment]
This can be done everywhere, as long as you're on the `develop` update channel, and not on the `stable` channel.
Most likely you switched the channel on Windows.

**Comment by Flare183** [comment]
Sadly, after changing the channel to development, there is still no change. The FTB selection on the left is still missing, and I am unable to go any higher than FTB Revelation 3.2.0 on the legacy menu.

**Comment by Flare183** [comment]
Ah, after updating to the developmental launcher version, I am now able to see the FTB menu selection.
