### ISSUE TITLE
Need help in packaging MultiMC for Guix

### ISSUE THREAD

**Issue by VictorAlbertsson** [MultiMC/MultiMC5#3486]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: Linux/Guix

Problem
-----------
I'm packaging/building MultiMC for/on Guix and the compilation fails at `make -j 16`, while this likely isn't an issue of MultiMC maybe someone more familiar with the compilation process of MultiMC could help me?

Log
-----
[error log](https://paste.ee/p/xmeL8)

Code
-------
```scheme
(use-modules (guix packages)
	     (guix git-download)
	     (guix build-system cmake)
	     (gnu packages compression) ; zlib
	     (gnu packages qt)
	     (gnu packages java))

(define-public multimc
  (let ((the-name    "multimc")
	(the-version "0.6.11")
	(the-commit  "3ad9ea507e945709b01a5fcc51a60f7c45ad4c38")
	(the-hash    "1jkbmb4sgfk8d93f5l1vd9pkpvhq9sxacc61w0rvf5xmz0wnszmz"))
    (package (name    the-name)
	     (version the-version)
	     (source
	      (origin
	       (method git-fetch)
	       (uri (git-reference
		     (url        "https://github.com/MultiMC/MultiMC5/")
		     (commit     the-commit)
		     (recursive? #t)))
	       (file-name (git-file-name the-name the-version))
	       (sha256 (base32 the-hash))))
	     (build-system cmake-build-system)
	     (arguments
	      '(#:configure-flags
		'("-DJava_JAR_EXECUTABLE=/gnu/store/4fm6rmx0vsp1lghnbd6nf746l7wzazix-openjdk-14.0-jdk/bin/jar"
		  "-DJava_JAVADOC_EXECUTABLE=/gnu/store/4fm6rmx0vsp1lghnbd6nf746l7wzazix-openjdk-14.0-jdk/bin/javadoc")))
	     (inputs `(("zlib" ,zlib)
		       ("qt"   ,qtbase)
		       ("java" ,openjdk14)))
	     (synopsis    #f)
	     (description #f)
	     (license     #f)
	     (home-page   #f))))

multimc
```

**Comment by wlhlm** [comment]
> packaging MultiMC for Guix

Cool!

The error seems to be here:
```
make[2]: *** [libraries/javacheck/CMakeFiles/JavaCheck.dir/build.make:73: jars/CMake
Files/JavaCheck.dir/java_compiled_JavaCheck] Error 2
make[2]: Leaving directory '/tmp/guix-build-multimc-0.6.11.drv-0/build'
make[1]: *** [CMakeFiles/Makefile2:826: libraries/javacheck/CMakeFiles/JavaCheck.dir
/all] Error 2
make[1]: *** Waiting for unfinished jobs....
warning: [options] bootstrap class path not set in conjunction with -source 6
error: Source option 6 is no longer supported. Use 7 or later.
error: Target option 6 is no longer supported. Use 7 or later.
```
(order of lines is shuffled due to parallel build)

Looks like your JDK version is too new. NixOS builds using JDK8. On Arch Linux, the [multimc-git](https://aur.archlinux.org/packages/multimc-git/) AUR package also [builds](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=multimc-git#n11) with JDK8. The stable [multimc](https://aur.archlinux.org/packages/multimc5/) AUR packages depends on the virtual "java-runtime" package which by default means the latest JDK, but the [comments](https://aur.archlinux.org/packages/multimc5/#pinned-700404) indicate that an older JDK version has to be set on the system before building the package.

Not exactly sure where the cutoff is, but it looks like it's JDK11. I'd recommend building with JDK8.

**Comment by VictorAlbertsson** [comment]
Thanks for the quick response! It turns out the latest version of JDK on Guix is 14, using an older version of JDK shouldn't be problem however it seems like JDK 9 might be the oldest version available. The Icetea java distribution might have an even older version of the JDK (I think they used it for bootstrapping OpenJDK 9). If that doesn't work I will try and get in touch with the OpenJDK packagers and see if they have any recommendations/tips on maybe bootstrapping JDK 8.

**Comment by wlhlm** [comment]
JDK9 and 11 should be fine for building MultiMC and running Vanilla, thought JDK8 is still the go to for modded MC.

**Comment by Zetabite** [comment]
If you cant get OpenJDK 8 on your system, just download the binaries from AdoptOpenJDK with Hotspot JVM and point MMC java settings tehre

**Comment by jamierocks** [comment]
You won't be able to run some older Minecraft Forge versions with anything newer than Java 8, well anything that uses LaunchWrapper.

**Comment by Kloenk** [comment]
Only know about Guix that it uses the nix daemon (at least an old version). Maybe the nix packaging can help you here? https://github.com/NixOS/nixpkgs/blob/nixos-20.09/pkgs/games/multimc/default.nix#L32

**Comment by VictorAlbertsson** [comment]
According to [this](https://www.draketo.de/software/guix-work.html#org07ebedd) blog post it looks like IcedteaJDK 3.7 corresponds to OpenJDK 8, I will try this when I have time.

**Comment by VictorAlbertsson** [comment]
Some progress, the build now succeeds however a test fails. Specifically `DownloadTask` , I initially thought this might be a hardware issue so I disabled RDRAND in the kernel yet it still complains with the same error. Any help is appreciated!

Code
-------
```scheme
(use-modules (guix packages)
	     (guix git-download)
	     (guix build-system cmake)
	     (gnu packages compression) ; zlib
	     (gnu packages qt)
	     (gnu packages java)) ; icedtea@3.7 = JDK 8

(define-public multimc
  (let ((the-name    "multimc")
	(the-version "0.6.11")
	(the-commit  "3ad9ea507e945709b01a5fcc51a60f7c45ad4c38")
	(the-hash    "1jkbmb4sgfk8d93f5l1vd9pkpvhq9sxacc61w0rvf5xmz0wnszmz"))
    (package (name    the-name)
	     (version the-version)
	     (source
	      (origin
	       (method git-fetch)
	       (uri (git-reference
		     (url        "https://github.com/MultiMC/MultiMC5/")
		     (commit     the-commit)
		     (recursive? #t)))
	       (file-name (git-file-name the-name the-version))
	       (sha256 (base32 the-hash))))
	     (build-system cmake-build-system)
	     (inputs `(("zlib" ,zlib)
		       ("qt5"  ,qtbase)
		       ("java" ,icedtea-8 "jdk")))
	     (synopsis    #f)
	     (description #f)
	     (license     #f)
	     (home-page   #f))))

multimc
```

Log
-----
[error log](https://paste.ee/p/TyEDP)
Note: Only `test` phase included due to file size limits on paste.ee

**Comment by Kloenk** [comment]
Does guix have network in testPhase?

**Comment by peterix** [comment]
Please use the official build. You do not have the right to call your own build MultiMC.

**Comment by VictorAlbertsson** [comment]
Sorry for the late reply, but what do you mean by 'the official build' as far as I know there is no build for Guix which is why I am doing this, now if there is an official build for Guix then it would be appreciated if that was documented in the 'Download & Install' section of the MultiMC website.

**Comment by spannerman79** [comment]
If your intent is to make a package @VictorAlbertsson then I suggest you make a PR similar to https://github.com/MultiMC/MultiMC5/pull/3460.

**Comment by AverageComet250** [comment]
If people were to make `.deb`, `.rpm` and other Linux builds and attach them to issues for people to use, I think that would be fine as they are helping the multimc community. And if people do that, then it might be worth someone adding them to website to help make multimc easier to use.

I am thinking of the right thing or something completely different to what this thread is about.

**Comment by spannerman79** [comment]
@AverageComet250 the PR that I referenced showed that support for other distos are supported - but the required files/etc **must** reside in this repo.  The build server for the `.rpm` pulls what it needs from the official source - being `https://github.com/MultiMC/MultiMC5`.  

As there has been no PR's issued by the OP, the stance that peterix has is correct - you cannot create a fork of MultiMC and still call it MultiMC due to https://github.com/MultiMC/MultiMC5#license and distribute it at the same time as "MultiMC"

**Comment by AverageComet250** [comment]
So if you were to fork it and make a valid `.rpm` or `.deb` file, it wouldn't work as it takes from the original and not the fork, when the fork contains the required code.

Note that this example is basically what would happen without that pr.

**Comment by AverageComet250** [comment]
Also I can't find a license for multimc in the repo.

**Comment by Zetabite** [comment]
https://github.com/MultiMC/MultiMC5/blob/develop/COPYING.md

**Comment by Zetabite** [comment]
Also, .deb already exist. If you want a proper .rpm, you should contribute to this repo.

**Comment by AverageComet250** [comment]
I think it might be worth making a copy of COPYING.md and naming LICENSE.md, as it would make finding those license agreements easier.

Thanks,
Shravan Mandava

________________________________

**Comment by Zetabite** [comment]
Uh, its literally linked as "View Lisence"

**Comment by VictorAlbertsson** [comment]
I think I understand now, however my intention was never to fork MultiMC or make a custom build only to port it to a new Linux distribution in whatever way would be most appropriate for the project hence the code shown earlier is not part of a fork or any repository. Recently however I discovered that someone has already made a [build script for MultiMC](https://gitlab.com/guix-gaming-channels/games/-/blob/master/games/packages/minecraft.scm) in the Guix Gaming channel and hence my work is mostly rendered obsolete. If the licensing continues to be a problem it should be discussed with the maintainers of the [Guix Gaming](https://gitlab.com/guix-gaming-channels/games) channel, however it should be noted that if MultiMC requires that all build scripts be part of the official MultiMC repository then you will have to manage your own Guix channel. 

Just as a side note, regarding the naming clause of the license how far does it go? Would `multimc-guix` be enough or would it have to have a completely different name?

**Comment by phit** [comment]
No, that is not enough. Closing this as it seems resolved, if you need to discuss this further come by the MultiMC discord.
