### ISSUE TITLE
Is it possible to send Java mod output to MultiMC console?

### ISSUE THREAD

**Issue by JSpencer000** [MultiMC/MultiMC5#3488]
System Information
-----------------------------
MultiMC version: 0.6.11-1430 on Win32

Operating System: Windows 10 (1909)

Summary of the issue or suggestion:
----------------------------------------------

I am working on improving a mod (LiteMatica). My first experience with Java and Mod development (I have years of C++ experience). And I'd like real time logging from my changes. I'm wondering if MultiMC has a mechanism for a mod to write to its console Window. 

What should happen:
------------------------------
Someone point me to a resource on how a Java mod can send lines to the MultiMC console window.
Or
Develop a new interface or mod to allow mods to send to the MultiMC console window.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install a Mod (I'll call it ModA) in the mod directory

2.Launch that Instance

3. ModA calls SuperFantasticMultiMCConsole.WriteLine("Hello World")

Suspected cause:
---------------------------
A newb mod developer

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
Feel free to point me to a different resource, or forum to ask this question.

**Comment by phit** [comment]
MultiMC is a launcher, not really the place to take about mod dev. When you are developing a mod use an IDE and launch the game through that. For logging, Minecraft uses Log4J, I'm sure litematica already uses it in places, just search the existing codebase.
Not sure what version of litematica you are targeting, so here's both
Forge https://forums.minecraftforge.net/ https://mcforge.readthedocs.io/en/latest/
Fabric https://fabricmc.net/discuss/ https://fabricmc.net/wiki/start#mod_developers

**Comment by JSpencer000** [comment]
Thanks for the help.
