### ISSUE TITLE
Need Help 

### ISSUE THREAD

**Issue by StarfireSky** [MultiMC/MultiMC5#3491]
When I try to load Minecraft 1.12.2 in the single player in the MultiMC it crashes but when I loaded the single player in version 1.16.4 it did not what is going on why can't I play version 1.12.2.

Thanks

**Comment by QuImUfu** [comment]
please post the Minecraft log of the crashing instance (https://github.com/MultiMC/MultiMC5/wiki/Minecraft-Logs#uploading-logs)

**Comment by StarfireSky** [comment]
Here is the log from version 1.12.2. [2020-11-23-2.log.gz](https://github.com/MultiMC/MultiMC5/files/5719192/2020-11-23-2.log.gz)

**Comment by jotoho** [comment]
After unpacking, the log file only contains this line and is otherwise empty:
```java
[22:26:16] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
```
Seems to me like it is incomplete or the game crashed directly after that line.

**Comment by jotoho** [comment]
@StarfireSky Please use the button for log uploading as described in the wiki article @QuImUfu linked instead of trying to manually upload.

**Comment by StarfireSky** [comment]
I try to reupload the log but I am unable I get a message that says SSL handshake failed.

**Comment by spannerman79** [comment]
If you have SSL issues its no longer a MultiMC issue but an issue on your end.  Something is playing around with SSL connections which only you can resolve.


No longer a MultiMC issue.
