### ISSUE TITLE
Account problems

### ISSUE THREAD

**Issue by wannabemoddedplayer** [MultiMC/MultiMC5#3493]
System Information
-----------------------------
MultiMC version:
0.6.11-1430 on win 32 - multi mc 5
Operating System:
Windows 10
Summary of the issue or suggestion:
----------------------------------------------
I'm new to multi mc, when I try to add an account, I enter in the correct details and it says invalid password and/or email.

What should happen:
------------------------------
It should create my account.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Go to profiles- manage profiles

2. Add account

3.

Suspected cause:
---------------------------
I read somewhere that it may be because mojang is moving from mojang to microsoft accounts

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
Thanks a lot if you fix this, I've always wanted to do mods and it would mean a lot to me. :D

**Comment by spannerman79** [comment]
Did you purchase Minecraft in the last month (December) or so?

If so - https://multimc.org/posts/microsoft-accounts.html

**Comment by Dragonlord1005** [comment]
Basically, like me, I bought Minecraft in December with my Microsoft account because you have to, as of currently, MultMC does not support microsoft accounts yet, don’t worry you aren’t alone

**Comment by 69420XD** [comment]
Use normal mc launcher until multimc supports Microsoft accounts

**Comment by AverageComet250** [comment]
To use mods in the normal MC launcher, install forge through the official installer and place your mods in either `.minecraft/mods` or  `.minecraft/mods/<MC version>`

**Comment by Dragonlord1005** [comment]
You can also use atlauncher, which recently gained support, but I wouldn’t recommend it, it can be pretty slow and have lame warnings that no one cares about

**Comment by wb1016** [comment]
needs more info

**Comment by Scotsguy** [comment]
Support for Microsoft accounts is planned.
