### ISSUE TITLE
Crashing with exitcode -805306369

### ISSUE THREAD

**Issue by HeisenMgh** [MultiMC/MultiMC5#3495]
System Information
-----------------------------
MultiMC version: 0.6.12-devolp

Operating System: windows 10

Summary of the issue or suggestion: I keep crashing while playing FTB: revelation with exitcode -805306369
----------------------------------------------

What should happen: someone to help me with this issue
------------------------------

Steps to reproduce the issue (Add more if needed): I have no idea that is the problem I keep crashing for days
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by spannerman79** [comment]
Log or it never happened

https://github.com/MultiMC/MultiMC5/wiki/Minecraft-Logs

**Comment by HeisenMgh** [comment]
> Log or it never happened
> 
> https://github.com/MultiMC/MultiMC5/wiki/Minecraft-Logs


https://paste.ee/p/kN71Q

**Comment by Zetabite** [comment]
please upload according to the instructions. Restart the instance if you need to to get the "Minecraft Log"

**Comment by HeisenMgh** [comment]
> please upload according to the instructions. Restart the instance if you need to to get the "Minecraft Log"

https://paste.ee/p/Yi6kY

**Comment by spannerman79** [comment]
You've got errors like `[02:20:06] [Client thread/ERROR] [FML]: There was a problem reading the entry module-info.class in the jar C:\Users\Heise\Downloads\mmc-develop-win32\MultiMC\instances\FTB Revelation\minecraft\mods\MineTogether-1.12.2-2.4.1.jar - probably a corrupt zip` amongst others.

Currput instance, anti virus or some other system task screwing around with I/O.

Not a MultiMC issue.

**Comment by Scotsguy** [comment]
This is not a MultiMC issue, closing.
