### ISSUE TITLE
Can't sign in due to supposed invalid credentials

### ISSUE THREAD

**Issue by Oracidrep** [MultiMC/MultiMC5#3496]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: windows 10

Summary of the issue or suggestion:
----------------------------------------------
I can't sign in with the correct information when adding an account to multimc

What should happen:
------------------------------
It should sign in. Don't know what else because I cant sign in.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Attempt to sign in

2. Fail and get told that my login info is incorrect despite it being correct.

Suspected cause:
---------------------------
bad programming

Logs/Screenshots:
----------------------------
none

Additional Info:
---------------------------
Yes I have the java edition and have even played with other users on java

**Comment by Oracidrep** [comment]
> Have you already migrated your minecraft account to your microsoft account?
> If yes, take a look at #3392 and [this official blog post](https://multimc.org/posts/microsoft-accounts.html) about how MultiMC plans to deal with that.

I bought minecraft for the first time ever yesterday

**Comment by jotoho** [comment]
The transition to microsoft accounts was announced but I am not certain if it has already begun for new users.

If you did not link your minecraft license to your microsoft account, can only advise checking if your credentials are correct by trying to log into minecraft.net and making sure the authentication servers aren't down when you try to log in.

Perhaps the others will have more ideas you could try.

**Comment by phit** [comment]
MultiMC currently does not support new users, as they are already using the new Microsoft login. Until that changes you will have to use a different launcher.

**Comment by jshdfg** [comment]
every sing time i try to add my account on multimc it says invalid credentials.invalid username or password but eveything is correct please help

**Comment by spannerman79** [comment]
@jshdfg you were **already told** what your issue was https://github.com/MultiMC/MultiMC5/issues/3734#issuecomment-821100118

**Comment by spannerman79** [comment]
@jshdfg when you went to issues ( https://github.com/MultiMC/MultiMC5/issues ) did you happen to see an issue that was already pinned up at the top?
