### ISSUE TITLE
When i press add instance it freezez and when i try to click anywhere it makes that error sound thing

### ISSUE THREAD

**Issue by Pezocan** [MultiMC/MultiMC5#3499]
System Information
-----------------------------
MultiMC version: 5 

Operating System: Windows 10 Pro

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by jotoho** [comment]
Please provide the complete version number. You can find it from the main window under "Help" -> "About MultiMC" -> "About" or in the window title of the application.

Here's a screenshot of it on my system:

![Screenshot_20201226_155406](https://user-images.githubusercontent.com/12120743/103153743-f4a23300-4792-11eb-8ca2-0cf2b92f3d99.png)

**Comment by Zetabite** [comment]
Please fill out the issue like the template proposes.

**Comment by Zetabite** [comment]
Regarding the log, follow these instruction https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by Pezocan** [comment]
> Please provide the complete version number. You can find it from the main window under "Help" -> "About MultiMC" -> "About" or in the window title of the application.
> 
> Here's a screenshot of it on my system:
> 
> ![Screenshot_20201226_155406](https://user-images.githubusercontent.com/12120743/103153743-f4a23300-4792-11eb-8ca2-0cf2b92f3d99.png)

my main page is like that i couldnt find what yousaid
![image](https://user-images.githubusercontent.com/76609377/103166917-d6dad980-4837-11eb-8a9b-f91e78d0ef76.png)

**Comment by Pezocan** [comment]
and its like it opens the adding instance window but i cant see it

**Comment by spannerman79** [comment]
Where **exactly** did you obtain that copy of MultiMC from @Pezocan ?

**Comment by Pezocan** [comment]
> Where **exactly** did you obtain that copy of MultiMC from @Pezocan ?

i dont remeber

**Comment by spannerman79** [comment]
I suspect you do...

Either way;

That copy is not a legimate copy of MultiMC.  It has been modified.

The **only** legimate location for windows users to obtain MultiMC from is https://multimc.org/

I'd change your minecraft account password and use MultiMC downloaded from the link I gave above.

If you refuse to do that then don't expect any support here and go and get support from the place you downloaded that _questionable_ copy of MultiMC.

**Comment by Pezocan** [comment]
> I suspect you do...
> 
> Either way;
> 
> That copy is not a legimate copy of MultiMC. It has been modified.
> 
> The **only** legimate location for windows users to obtain MultiMC from is https://multimc.org/
> 
> I'd change your minecraft account password and use MultiMC downloaded from the link I gave above.
> 
> If you refuse to do that then don't expect any support here and go and get support from the place you downloaded that _questionable_ copy of MultiMC.

okay but will it save my instances and worlds

**Comment by Pezocan** [comment]
okay but can i save my worlds

**Comment by spannerman79** [comment]
If you have a legitimate copy of Minecraft - yes.

**Comment by Pezocan** [comment]
okay than you very much

**Comment by AverageComet250** [comment]
You'll need to port them across to your offical download by basically copying the instances folder into your new multimc folder from your old one.

I'd also recommend scanning your old multimc folder with an antivirus program **BEFORE** you move your instances folder to check it for viruses as it doesn't seem very legit. Also, did it download as a zip or as an installer as the way you ask if your worlds will be automatically ported across makes it seem like you used an installer to install it

**Comment by Pezocan** [comment]
> You'll need to port them across to your offical download by basically copying the instances folder into your new multimc folder from your old one.
> 
> I'd also recommend scanning your old multimc folder with an antivirus program **BEFORE** you move your instances folder to check it for viruses as it doesn't seem very legit. Also, did it download as a zip or as an installer as the way you ask if your worlds will be automatically ported across makes it seem like you used an installer to install it

okay good idea
