### ISSUE TITLE
What's going on?

### ISSUE THREAD

**Issue by PhoenixGre** [MultiMC/MultiMC5#3501]
https://paste.ee/p/HoQvT

**Comment by spannerman79** [comment]
https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java

**Comment by PhoenixGre** [comment]
> https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java
jdk doesnt work???

**Comment by spannerman79** [comment]
Line 12 from your log;

`Java is version 15.0.1, using 64-bit architecture.`

Enough said.

**Comment by PhoenixGre** [comment]
> Line 12 from your log;
> 
> `Java is version 15.0.1, using 64-bit architecture.`
> 
> Enough said.

Ah  thank you <3
