### ISSUE TITLE
Executable at `~/.local/share/multimc/bin/MultiMC` launches a different install of MultiMC than the one at `~/.local/share/multimc/MultiMC`

### ISSUE THREAD

**Issue by VoxelTek** [MultiMC/MultiMC5#3502]
System Information
-----------------------------
MultiMC version:
0.6.11-1344

Operating System:
Kubuntu 20.10

Summary of the issue or suggestion:
Executable at `~/.local/share/multimc/bin/MultiMC` launches a different install of MultiMC than the one at `~/.local/share/multimc/MultiMC`
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Execute `~/.local/share/multimc/MultiMC` and set up a dummy MultiMC install (just enough to distinguish it from a clean install).

2. Close MultiMC, and execute `~/.local/share/multimc/bin/MultiMC` without using the executable at `~/.local/share/multimc/MultiMC`.

3. You will be greeted with an install that is different to the one experienced when executing `~/.local/share/multimc/MultiMC`

Suspected cause:
---------------------------
Not sure how to explain it, but I think that, because it is launched without the `~/.local/share/multimc/MultiMC` executable, it takes the directory it is in (./bin) as the MultiMC working directory.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Not applicable or useful in this case.

Additional Info:
---------------------------
Given that the MultiMC shortcut is set by default to launch the `~/.local/share/multimc/MultiMC` executable before the one in `./bin`, this would not normally be an issue. But, given that the executable itself is being run in both cases, just with different working directories, if I was to pin MultiMC to the taskbar, it would always launch the `./bin` instance, instead of the main one.

A solution I would recommend is to set the working directory of the executable itself to `~/.local/share/multimc/` instead of `~/.local/share/multimc/bin`. That way, the same install would be launched, regardless of which file was executed.

EDIT: A working, temporary fix is to create symbolic links for all files and folders in `~/.local/share/multimc/` in `~/.local/share/multimc/bin`, except for the `~/.local/share/multimc/MultiMC` executable.

**Comment by kb-1000** [comment]
You aren't supposed to launch `~/.local/share/multimc/bin/MultiMC` at all.
The launcher script (`~/.local/share/multimc/MultiMC`) does that for you, and sets the `-d` parameter specifying the install directory properly.

**Comment by kb-1000** [comment]
Also, since you are on Kubuntu, I would suggest using [the Ubuntu package](https://files.multimc.org/downloads/multimc_1.4-1.deb) instead, that one already contains a .desktop file, and puts the data in `~/.local/share/multimc`.
`/opt/multimc/run.sh` is the launcher script there.

**Comment by VoxelTek** [comment]
> You aren't supposed to launch `~/.local/share/multimc/bin/MultiMC` at all.
> The launcher script (`~/.local/share/multimc/MultiMC`) does that for you, and sets the `-d` parameter specifying the install directory properly.

I know that the startup script executes the file the correct way. However, as I stated before, if I was to pin MultiMC to the taskbar while it is running, it will pin the MultiMC executable in /bin instead of the startup script. If I was to pin the startup script to the taskbar, then clicking on that would launch a seperate window, which is not pinned to the taskbar. This is a minor issue, however, it is an issue nonetheless. Since I have discovered a temporary fix, it is not of the utmost priority, but I do recommend that this be fixed or patched, to allow the executable to work out of the correct directory.

**Comment by VoxelTek** [comment]
> Also, since you are on Kubuntu, I would suggest using [the Ubuntu package](https://files.multimc.org/downloads/multimc_1.4-1.deb) instead, that one already contains a .desktop file, and puts the data in `~/.local/share/multimc`.
> `/opt/multimc/run.sh` is the launcher script there.

I...am.... I never said I wasn't. I downloaded the .Deb package from the official MultiMC website, and installed it correctly. My issue is that launching the /bin executable doesn't set the directory correcly. I suggest that either the executable be modified to properly point to the correct directory, or symlinks be put in place automatically.

**Comment by phit** [comment]
superseded by https://github.com/MultiMC/MultiMC5/issues/3974#issuecomment-887785255
