### ISSUE TITLE
Java Auto-detection feature does not seem to detect AdoptOpenJDK versions besides those in PATH

### ISSUE THREAD

**Issue by Xalaxis** [MultiMC/MultiMC5#3503]
System Information
-----------------------------
MultiMC version: 0.6.12-develop-1493

Operating System: Windows 10 Version 20H2

Summary of the issue or suggestion: 
----------------------------------------------
Java Auto-detection feature does not seem to detect AdoptOpenJDK versions besides the one in PATH

What should happen:
------------------------------
MultiMC should correctly detect the alternative versions available.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install two different AdoptOpenJDK versions from https://adoptopenjdk.net/

2. Run the Java auto-detection feature in MultiMC

3. Observe only one version is found, and it is the version currently present in the PATH

Suspected cause:
---------------------------
MultiMC seems only to check a list of predefined locations for Java installations. AdoptOpenJDK installs (default location "C:\Program Files\AdoptOpenJDK" on Windows systems) should be added to this list.

Logs/Screenshots:
----------------------------
[MultiMC-0.log](https://github.com/MultiMC/MultiMC5/files/5747748/MultiMC-0.log)

Additional Info:
---------------------------
N/A

**Comment by kb-1000** [comment]
You need to instruct the installer to register the java in the registry

**Comment by Xalaxis** [comment]
@kb-1000 This option here?
![image](https://user-images.githubusercontent.com/12937964/103224097-25af6e80-491f-11eb-9166-35109bfc46cd.png)

**Comment by kb-1000** [comment]
Yes

**Comment by AverageComet250** [comment]
I'm pretty sure it uses path to find java installs

Otherwise you could use the java bundled with the official mc launcher

**Comment by Xalaxis** [comment]
That does seem to fix the detection, so I'll close this issue. Do you think it would be useful to raise a suggestion about the auto-detection dialog having some warning to the effect that "Only the official Java registry keys are checked"?

**Comment by Xalaxis** [comment]
> I'm pretty sure it uses path to find java installs
> 
> Otherwise you could use the java bundled with the official mc launcher

As far as I'm aware, MultiMC only checks the PATH for "javaw". It seems to check the Oracle Java registry keys for everything else as per what @kb-1000 just told me.

**Comment by AverageComet250** [comment]
I would create a separate issue as a suggestion saying to make that clear in the docs or on that screen or to make it scan your whole pc for `javaw.exe` files

**Comment by Xalaxis** [comment]
I'll raise a suggestion to improve the https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java and https://github.com/MultiMC/MultiMC5/wiki/Java-settings pages when I'm free.

Thanks for your help all ❤️
