### ISSUE TITLE
always launchs in offline mode

### ISSUE THREAD

**Issue by DJGull7** [MultiMC/MultiMC5#3504]
System Information
-----------------------------
MultiMC version:
latest
Operating System:
windows 10 64bit
Summary of the issue or suggestion:
----------------------------------------------
when launching any modpack, multimc will launch it in offline mode

What should happen:
------------------------------
it should launch in online mode

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.install windows 10

2.install java 8 64bit

3.install (and setup) multimc latest 64bit

4.launch any minecraft version/modpack

Suspected cause:
---------------------------
not verifying login credentials? (only lead i have based on the 4 frames the "verifying login credentials" was on screen)

Logs/Screenshots:
----------------------------
this was happoning to my friend and he was streaming over discord, and as im writing this report he is at work so no logs can be attached (i use an ubuntu multimc and can run mmc fine)

Additional Info:
---------------------------

**Comment by DJGull7** [comment]
a reinstall of multi mc fixed it

**Comment by gabuz52** [comment]
If anyone still having this problem, clicking "manage accounts", right click your account and click refresh, that worked for me
