### ISSUE TITLE
Can not load into servers.

### ISSUE THREAD

**Issue by tricao7** [MultiMC/MultiMC5#3506]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows

Summary of the issue or suggestion: 
----------------------------------------------
I can load into the game but when I try to connect to a server with my friends the game crashes. I was playing in the server for multiple hours and it crashed while I was in the server. I have deleted MultiMc and redownloaded it, but this did not fix the issue. I was using the Valhesia 3 Modpack. 

What should happen:
------------------------------
I should be able to log into the server and play. I have been doing this for a week prior to the issue and none of the server's settings were changed.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch MultiMc

2. Join a valhesia 3 minecraft server

3. the game loads then crashes immediately. The world never renders on my screen.

Suspected cause:
---------------------------
I don't know how to fix the issue.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

https://paste.ee/p/RGTZh

Additional Info:
---------------------------

**Comment by jotoho** [comment]
The mods in that pack are spewing warnings and Exception stack traces like there's no tomorrow. Makes me wonder how its stable.

That said, the information in the crash report itself references a `ItemArchitectWand` from astral sorcery and the storage drawers mod. Did you try something involving those two items when you crashed the first time?

If the code that is causing this NullPointerException is something that runs without the user actively clicking anything - like for example looking at a drawer with a buggy item from astral sorcery - then it would make sense for you to crash immediately after joining.

I am reasonably certain that this crash has nothing to do with MultiMC. Have you tried researching if other users of the modpack are having this issue? Did you and your friends change the modpack in any way?

In the worst case, if you cannot fix the problem on your side, you could always request the server admins to move your player using a world editing tool like MCEdit or delete your player file in the world save folder - though deleting your file would mean losing everything in your inventory and potentially some other player-specific progress/data.

**Comment by Scotsguy** [comment]
This is not a MultiMC issue, closing.
