### ISSUE TITLE
Unknown Error, can't get ingame. Error code: -1

### ISSUE THREAD

**Issue by Ozzysyn** [MultiMC/MultiMC5#3509]
https://paste.ee/p/vRsNi

**Comment by Janrupf** [comment]
Looks like an issue with `Slient Games`. Next time please reach out on the discored, this tracker is for bugs with MultiMC and not for game crashes.

**Comment by dablade11577** [comment]
@Janrupf  what discord

**Comment by dablade11577** [comment]
@Janrupf i cant seem to find it

**Comment by spannerman79** [comment]
@dablade11577 https://github.com/MultiMC/MultiMC5/blob/develop/README.md#L16

Also main multimc website.

Not hard to miss.

**Comment by Scotsguy** [comment]
This is not a MultiMC issue, closing.
