### ISSUE TITLE
You should add support for custom intermediaries for Fabric Loader to MultiMC

### ISSUE THREAD

**Issue by Tytanium13** [MultiMC/MultiMC5#3513]
System Information
-----------------------------
MultiMC version: 0.6.11-1430 on win32

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
I'm attempting to add fabric to the 1.16 combat test 6 so I can use optifine with it, however the intermediaries for that fabric version, despite fabric itself being supported, is not. [On github there is a supported version for the 1.16 combat test 6 version](https://github.com/rizecookey/intermediary/tree/2ae717f67b41fb035c2e72d3bffc64f1ceb293d8), but it is unusable as MultiMC does not support usage of custom intermediaries. [I have found a post on how someone got fabric working on the 1.16 combat test 6 version](https://www.reddit.com/r/fabricmc/comments/j92l6p/how_i_unofficially_installed_fabric_and_mods_on/), but it was a tedious and annoying process that could be significantly improved with the simple addition of allowing custom intermediaries for use with fabric in MultiMC

What should be implemented:
------------------------------
The user should have the option to use locally downloaded/developed/forked intermediary files or modify the link to allow the user to directly apply a github fork of the original as the intermediary for the Fabric loader, rather that just automatically attempting to find/download a file from github that is outdated/unsupported/non-existent.

Additional Info:
---------------------------

**Comment by jamierocks** [comment]
Just modify the intermediary component and use whatever fork you like.

**Comment by Scotsguy** [comment]
As jamie said, this is what components are for.
