### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005) Error     Exit code 1  (Not Exit Code -1)

### ISSUE THREAD

**Issue by peterodavies27atgmailcom** [MultiMC/MultiMC5#3514]
System Information
-----------------------------
MultiMC version: 
0.6.11-1430 on win 32 - MultiMC 5

Operating System: 
Windows 10

Summary of the issue or suggestion:
----------------------------------------------
MC Launches, Loads, and then right before the title screen fully shows it crashes

What should happen:
------------------------------
Obviously MC shouldn't crash

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch Minecraft

Suspected cause:
---------------------------
Iris or Sodium, but IDK

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/RnIkf

Additional Info:
---------------------------
This is probably not MultiMC, but IDK and if you can help please do

**Comment by spannerman79** [comment]
```
# Problematic frame:
# C  [atio6axx.dll+0x1b0f894]
```

`atio6axx.dll` is AMD.  Not a MultiMC issue. Sort out your gfx drivers.
