### ISSUE TITLE
can't join servers is says "Failed to login: The authentication servers are currently down for maintenance

### ISSUE THREAD

**Issue by benny20022004** [MultiMC/MultiMC5#3515]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 7 ultimate 64 bit

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------
i should be able to join servers

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------
i think the x symbol at session at bottom right causes this          IDK

Logs/Screenshots: https://paste.ee/p/Z0SjS
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
I can join servers in vanilla.

**Comment by Zetabite** [comment]
upload log: https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by benny20022004** [comment]
> upload log: https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

ok wait a min

**Comment by benny20022004** [comment]
> upload log: https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

Here is th log plzzzz help me
https://paste.ee/p/Z0SjS

**Comment by Zetabite** [comment]
if you drop that annoying begging, yes

**Comment by Zetabite** [comment]
where did you got mmc from?

**Comment by benny20022004** [comment]
> where did you got mmc from?

from Mysticat youtuber

**Comment by benny20022004** [comment]
> if you drop that annoying begging, yes
