### ISSUE TITLE
Server bug

### ISSUE THREAD

**Issue by SpaceStatus** [MultiMC/MultiMC5#3518]
Hey! I have noticed a weird bug about this, when I try joining a server my Minecraft is instantly crashing. I don't have a recording because I have some technical problems with my recorder.
So when I try entering a server Cubecraft for example, it's  entering like regular but then it's showing, from Connecting to Server, Joining world.... and the cancel button, but after some seconds it's not showing it anymore, freezes a bit then crashing, does anyone have a solution to that?

**Comment by AverageComet250** [comment]
Probably bad packets.

Can you do it once more and then post an error log.

**Comment by Zetabite** [comment]
please provide the full log: https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by Forkk** [comment]
Please fill out the issue form and provide the full log.
