### ISSUE TITLE
MultiMC doesn' t start

### ISSUE THREAD

**Issue by Nefixen** [MultiMC/MultiMC5#3520]
System Information
-----------------------------
MultiMC version:

Operating System: Windows 10 Pro 64bit

Summary of the issue or suggestion:
----------------------------------------------

MultiMC can't start

What should happen:
------------------------------

MultiMC should start 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Try to launch MultiMC

Suspected cause:
---------------------------

MultiMC can't find info about viewport and RAM. Maybe that's the problem

Logs/Screenshots:
----------------------------

    0.000 D <> Log initialized.
    0.000 D MultiMC 5, (c) 2013-2019 MultiMC Contributors
    0.000 D Version                    :  "0.6.11-1430"
    0.000 D Git commit                 :  "3ad9ea507e945709b01a5fcc51a60f7c45ad4c38"
    0.000 D Git refspec                :  "refs/heads/stable"
    0.000 D Work dir before adjustment :  "G:/mmc-stable-win32/MultiMC"
    0.000 D Work dir after adjustment  :  "G:/mmc-stable-win32/MultiMC"
    0.000 D Adjusted by                :  "Fallback to binary path G:/mmc-stable-win32/MultiMC"
    0.000 D Binary path                :  "G:/mmc-stable-win32/MultiMC"
    0.000 D Application root path      :  "G:/mmc-stable-win32/MultiMC"
    0.000 D <> Paths set.
    0.000 D Detected default console font: "Courier" , substitutions: ""
    0.000 D <> Settings loaded.
    0.000 D Your language is "en"
    0.000 D <> Translations loaded.
    0.000 D <> Updater started.
    0.016 D Started watching  "G:/mmc-stable-win32/MultiMC/icons"
    0.016 D Adding  "icons/636574428512291945.png"
    0.016 D <> Instance icons intialized.
    0.016 D <> Icon themes initialized.
    0.016 D ""
    0.016 D Loading theme "custom"
    0.016 D <> Widget themes initialized.
    0.016 D Instance path              :  "instances"
    0.016 D Loading Instances...
    0.016 D Discovering instances in "G:/mmc-stable-win32/MultiMC/instances"
    0.016 D Found instance ID "SevTech-Ages_3.1.7"
    0.016 D Will load group list now.
    0.016 D Group list loaded.
    0.016 D Loaded instance  "SevTech-Ages_3.1.7"  from  "G:/mmc-stable-win32/MultiMC/instances/SevTech-Ages_3.1.7"
    0.016 D <> Instances loaded.
    0.016 D Loading accounts...
    0.016 D <> Accounts loaded.
    0.016 D <> Cache initialized.
    0.016 D Detecting proxy settings...
    0.016 D Using no proxy is an option!
    0.016 D <> Proxy settings done.
    0.016 D Downloading Translations Index...
    0.016 D Task "NetJob(Translations Index)" starting for the first time
    0.031 D <> Icon theme set.
    0.031 D <> Application theme set.
    0.031 D <> Initialized analytics with tid "UA-87731965-2"
    0.047 W QMetaObject::connectSlotsByName: No matching signal for on_actionInstanceSettings_triggered()
    0.047 D Task "NetJob(Status JSON)" starting for the first time
    0.062 D Task "NetJob(Startup player skins download)" starting for the first time
    0.062 D Reloading news.
    0.062 D Task "NetJob(News RSS Feed)" starting for the first time
    0.062 D Task "NetJob(Checking for notifications)" starting for the first time

And it stays here, whtiout futher progress

**Comment by Forkk** [comment]
Is this still an issue? Looks like something is blocking MultiMC's access to the internet.

**Comment by Nefixen** [comment]
Turned out it wasn't problem with multi mc, but with my power supply not
handeling enough power for 3rd hard drive.... Yea... Thread can be closed.

wt., 9 mar 2021, 16:25 użytkownik Andrew Okin <notifications@github.com>
napisał:
