### ISSUE TITLE
MultiMc with forge doesn't work (Tried on 1.8.9 and 1.12.2

### ISSUE THREAD

**Issue by hasjdhaksdhakjdh** [MultiMC/MultiMC5#3522]
System Information
1.6 GHz Intel Core i5
8 GB 1600 MHz DDR3
Intel HD Graphics 6000 1536 MB

MultiMC version:
0.6.11.1370

Operating System:
macOS High Sierra

Summary of the issue or suggestion:
Whenever I try to load an instance that I'd installed forge on it doesn't load. Vanilla loads perfectly fine though.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download forge using "Install Forge"

2. Attempt to load it

Logs/Screenshots:
https://paste.ee/p/YEgIX (Thats the log according to MultiMc)

Additional Info:
At the end it said something exit code 255

**Comment by AverageComet250** [comment]
Can you run Minecraft without forge?

**Comment by phit** [comment]
you need to use Java 8

**Comment by hasjdhaksdhakjdh** [comment]
how do i change to java 8?

**Comment by phit** [comment]
https://www.java.com/en/download/

**Comment by hasjdhaksdhakjdh** [comment]
this didnt work

**Comment by phit** [comment]
this does work, please elaborate what didn't work for you otherwise nobody can help you

**Comment by AverageComet250** [comment]
Click other downloads and use the x64 offline if required. Then change your java path in multimc to the one you just installed.

If you don't change your java path in MMC it will still use the other java.

If you have the official mc launcher, you can use the java bundled with it, but this isn't recommended.

**Comment by hasjdhaksdhakjdh** [comment]
do I have to install a different version of java then change the thing in multimc?

**Comment by AverageComet250** [comment]
Yes. Select the correct javaw binary in multimc after installing it. The install location is something like `C:\Program Files\Java\jre-<version>`.

**Comment by sigma-1402** [comment]
.
