### ISSUE TITLE
I can't activate my account

### ISSUE THREAD

**Issue by MattixGaming** [MultiMC/MultiMC5#3523]
I'm registered in minecraft with a microsoft account when I put the password and the email on MultiMc it tells me: invalid credentials. invalid username or password. What can I Do?

**Comment by jamierocks** [comment]
MultiMC doesn't support Microsoft authentication yet.

**Comment by MattixGaming** [comment]
and how do i login on MultiMC?

**Comment by Veradra** [comment]
You don't. You either wait until MultiMC supports Microsoft accounts (which itself is waiting on Mojang to make an official system to do that), or you use the vanilla launcher until then, which is the only officially sanctioned method of using Microsoft accounts with Minecraft as of right now.

**Comment by MattixGaming** [comment]
Thank you :)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno mar 12 gen 2021 alle ore 08:49 Veradra <notifications@github.com>
ha scritto:
