### ISSUE TITLE
exit with code 255 during game loading

### ISSUE THREAD

**Issue by SveetPickle** [MultiMC/MultiMC5#3525]
System Information
-----------------------------
MultiMC version: 0.6.12-develop-1404

Operating System: linux mint 20

Summary of the issue or suggestion:
----------------------------------------------
game crashes while loading, All The Mods 6 specifically. loaded fine last Time i played

What should happen:
----------------------------

Logs/Screenshots:
----------------------------
https://paste.ee/p/0K9gz

**Comment by phit** [comment]
`java.lang.IllegalStateException: GLFW error before init: [0x10004]Invalid axis in gamepad mapping 030000005e0400001907000000010000 (X360 Wireless Controller)`

try unplugging your controller?

**Comment by SveetPickle** [comment]
I unplugged the wireless adapter, same error.

**Comment by phit** [comment]
not sure what else to try, the issue points at a broken gamepad driver, if you google the snippet from my last message you can find lots of people with the same issue, maybe try some of those solutions

**Comment by SveetPickle** [comment]
that's what I'll do, thanks for your time.

**Comment by Zetabite** [comment]
You are using java 11, use java 8
