### ISSUE TITLE
Can't get MultiMC to detect Java.

### ISSUE THREAD

**Issue by tenere84** [MultiMC/MultiMC5#3526]
System Information
-----------------------------
MultiMC version: MultiMC 5 - Version 0.6.11-1430 on win32

Operating System: Windows 10 Pro, 64-bit

Summary of the issue or suggestion:
----------------------------------------------
When I run MultiMC.exe, it cannot detect any version of Java. It says, "You do not have a working Java set up yet or it went missing. Please select one of the following or browse for a java executable." And "No versions are currently available. Even though I installed the latest version of java on java.com (jre-8u271).

What should happen:
------------------------------
It should detect the version of java that I have.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Go to java.com. Download and install the latest version of java (as of 1/13/2021).

2. Download MultiMC, extract the download and run MultiMC.exe.

3. It will give the error I explained above.

Suspected cause:
---------------------------
Zero clue.

Logs/Screenshots:
----------------------------
The Wiki didn't show me anything about uploading a log, but I hope pastebin works for you.

https://pastebin.com/LghgaJV1

**Comment by spannerman79** [comment]
https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java

> The Wiki didn't show me anything about uploading a log

https://github.com/MultiMC/MultiMC5/wiki/Minecraft-Logs
