### ISSUE TITLE
Modpack does not launch when trying to launch through MultiMC

### ISSUE THREAD

**Issue by AluminumTarkus** [MultiMC/MultiMC5#3530]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 7

Summary of the issue or suggestion: Valhelsia 2 not launching
----------------------------------------------

What should happen: Hit launch on Valhelsia 2 modpack and it launches
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. I am not sure

Suspected cause:
---------------------------
I do not know

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

https://paste.ee/p/HAEvg

Additional Info:
---------------------------
I recently started using MultiMC since Curseforge is not the best, vanilla seems to work fine but when I imported Valhelsia 2 and tried to launch it, MultiMC states it is running and the log is going, but no window opens, even when I try to open java manually.

**Comment by spannerman79** [comment]
Not a MultiMC issue as more then likley this would happen even on the vanilla launcher.

Join the discord server for non specific MultiMC issues like this.

**Comment by QuImUfu** [comment]
@AluminumTarkus seems like you need a bit more patience. The log AFAIK just displays normal forge installing behavior.

**Comment by Forkk** [comment]
Not a MultiMC issue.
