### ISSUE TITLE
MultiMc

### ISSUE THREAD

**Issue by MotherOfFan** [MultiMC/MultiMC5#3531]
hi

when I try to add a new Minecraft user (an existing one obviously( it doesn't recognize the email or password....

Help!!!
please!!

**Comment by spannerman79** [comment]
The user must have a paid java minecraft account.

Also if you purchased java minecraft since december 2020 read https://multimc.org/posts/microsoft-accounts.html

**Comment by MotherOfFan** [comment]
They do.

**Comment by spannerman79** [comment]
Then show the actual error that is displayed.

**Comment by Forkk** [comment]
In the future, please fill out the issue form correctly.

**Comment by MotherOfFan** [comment]
You did not help!!! Instead of teaching me how to fill a gorm do your job in helping clients.

**Comment by spannerman79** [comment]
@MotherOfFan I asked you to show the actual error ( https://github.com/MultiMC/MultiMC5/issues/3531#issuecomment-761024138 ) but you never did.

Secondly when you create an issue a temple is used for which you need to fill out for which **you did not do**.

>  how to fill a gorm do your job in helping clients.

If it is my "job" then where is my pay check for helping here? lol

No - it isn't a "job".  You are not a "client".
