### ISSUE TITLE
Feature Request: Ability to use the vanilla launcher as a account authenticator

### ISSUE THREAD

**Issue by Dragonlord1005** [MultiMC/MultiMC5#3532]
System Information
-----------------------------
MultiMC version: Dev version

Operating System:
Windows
Summary of the issue or suggestion:
----------------------------------------------
Basically, just allow for multimc to check the vanilla launcher for accounts in order for some form of temporary microsoft authentication

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by spannerman79** [comment]
This won't work as if there is any form of token stored in the vanilla launcher it will become invalid.

**Comment by Dragonlord1005** [comment]
I see
