### ISSUE TITLE
Process exited with code 255 Minecraft Forge Crash

### ISSUE THREAD

**Issue by zombiemans** [MultiMC/MultiMC5#3533]
System Information:

MultiMC version: 0.6.12-develop-1432
Operating System: macOS Catalina 10.15.7

Minecraft Forge instantly crashes whenever I try to launch it.

I am using the latest version of Forge 1.12.2 with no mods installed, I also tried installing the latest version of Java 8 but it didn't change the error message.

Logs: 
- https://paste.ee/p/qBChd

**Comment by AverageComet250** [comment]
1. Did you change the version of java that multimc uses to the one you installed and 

2. There seems to be an awful lot of issues regarding multimc on Mac, but they all seem to be different versions of MacOS.

**Comment by AverageComet250** [comment]
You're using jdk 15, which means you didn't change the version in f java that multimc uses after installing java 8.

If you find java options in settings, select the option to change java path and select the `javaw.exe` file for java 8. Multimc might also detect it automatically when you click on the option to change java path.

**Comment by zombiemans** [comment]
it worked!!!! thank you so much
