### ISSUE TITLE
MultiMC doesn't check for name changes on logged in accounts

### ISSUE THREAD

**Issue by TechniKris** [MultiMC/MultiMC5#3535]
System Information
-----------------------------
MultiMC version: 0.6.12-develop-1496

Operating System: Windows 10 20H2 64-bit

Summary of the issue:
----------------------------------------------
After changing a username of an account MultiMC doesn't detect the name change.
That makes it launch properly, however when joining multiplayer servers:

- Online Mode servers - fails authentication

- Offline Mode servers - joins with the old username

As for singleplayer or servers, I didn't test it and I'm unable to, because I already fixed the issue on my end.

What should happen:
------------------------------
MultiMC should detect the username change on its own e.g. , after launcher restart.

Steps to reproduce the issue:
-------------------------------------------------------------
(Note: difficult to reproduce, experienced by me only once)

1. Set up MMC

2. Change the username

3. Try joining (online/offline mode) multiplayer servers

3.1. (Assumption, didn't test) Join singleplayer and try sending a chat message

Suspected cause:
---------------------------
- MultiMC doesn't recheck an account's username when authenticating the already logged in account

Logs/Screenshots:
----------------------------

- Example: Trying to connect to connect to an online mode server (Hypixel in this case) a couple days after performing the name change ends up failing the authentication. I don't know when the issue started occuring as I haven't used MMC since performing the name change and until the day of taking that screenshot.
[Log](https://paste.ee/p/5fiYZ) shows in the first line the game uses the correct UUID, but also the old username `[16Jan2021 18:03:33.748]`(...)`--username, TechniKris`(...)`--uuid, a79cd206559b445188e043bec1d0132c`
[NameMC](https://namemc.com/profile/TechniKris.1) proves that at the time it's already been past the name change and that the username used by MMC was outdated

![MMC_namechange_issue](https://user-images.githubusercontent.com/30842158/104847362-d508b100-58df-11eb-9f5f-553d42b9225a.png)

Workarounds:
---------------------------
Log out of the launcher and log back in

**Comment by Lolbit723** [comment]
It also doesn't use microsoft accounts which need to be added soon as most of us already use microsoft account

**Comment by Zetabite** [comment]
MS accounts will happen, as soon as their is a proper way to do it

**Comment by Xenapte** [comment]
> I don't know when the issue started occuring as I haven't used MMC since performing the name change and until the day of taking that screenshot.

I reproduced this issue too some months ago. For me it starts immediately after the name change; I changed my username some months ago while MMC is running, and launched Minecraft, which when joining online servers gave me the same error (restarting MMC won't help either since it doesn't check username changes; only after I logged out and in again did that become fixed).

**Comment by pofdzm** [comment]
Yeah, same issue happened to me on linux.

**Comment by peterix** [comment]
Irrelevant with the changes in dev.

**Comment by lavendertea05** [comment]
i changed my xbox/microsoft username a few months ago, but it is not updating in multimc. i've uninstalled and reinstalled mmc twice now. my friends and I are trying to start a server and I don't know if they will be able to whitelist me with my old username, which is what is visible in multimc, but isn't the correct username. help??

**Comment by TechniKris** [comment]
@lavendertea05 This is unrelated.
Minecraft Java profile name is separate from Xbox Gamertag. Change your Java profile name instead.
https://help.minecraft.net/hc/en-us/articles/4408950195341-How-To-Change-Your-In-Game-Profile-Name-in-Minecraft
