### ISSUE TITLE
Minecraft crashes when launching indev versions with exit code 1. (https://paste.ee/p/tYrOK)

### ISSUE THREAD

**Issue by 4A8** [MultiMC/MultiMC5#3539]
System Information

Intel HD 4000
i3 2.2ghz
-----------------------------
MultiMC version: 5 I think

Operating System: Windows 10 Pro
Summary of the issue or suggestion: Crashing
----------------------------------------------

What should happen: Not crash lol
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. buy a shit pc

2. isntall multimc on it

3. launch an alpha version of mc on it

Suspected cause: i have a shit pc
---------------------------

Additional Info: help
---------------------------

**Comment by Zetabite** [comment]
https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs

**Comment by 4A8** [comment]
I have HD4000. Also, I tried that.

**Comment by spannerman79** [comment]
Supply the log **after** you have followed the wiki link that Zerabite supplied above @4A8

**Comment by 4A8** [comment]
https://paste.ee/p/ksO0Z

**Comment by 4A8** [comment]
@spannerman79 https://paste.ee/p/8DpCp

**Comment by spannerman79** [comment]
```
Checking Java version...
Java is version 1.8.0_281, using 64-bit architecture.
```

Nope - you need to follow the wiki **exactly**.  You are not using the java version given in the wiki link that Zetabite supplied before.

**Comment by 4A8** [comment]
Ok, I'll check it out.

**Comment by 4A8** [comment]
It doesn't detect the Java version

**Comment by 4A8** [comment]
I tried manually selecting it. Now it worked. Thanks

**Comment by Zetabite** [comment]
please close the issue then
