### ISSUE TITLE
MultiMC newer develop update doesn't work on Kubuntu 20.04

### ISSUE THREAD

**Issue by Werner1201** [MultiMC/MultiMC5#3541]
System Information
-----------------------------
MultiMC version: 0.6.12-develop-14.04 on lin64

Operating System: Kubuntu 20.04

Summary of the issue or suggestion:
----------------------------------------------
The launcher wants to update but when I update it says the new version failed to start and asks to rollback (The new version opens but does not maintain the version when I close and open again) (A strange thing is that when it updates it installs the folders inside the bin folder. 

What should happen:
------------------------------
Close the Old version and Open the new one in the correct folders inside ``` /home/werner/.local/share/multimc/``` not inside 
```/home/werner/.local/share/multimc/bin ```

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Click to Update to new Version

2. 

3.

Suspected cause:
---------------------------
Wrong execution of installation of newer version 

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![image](https://user-images.githubusercontent.com/8631657/104931301-f8d20280-5984-11eb-913a-102b9a5b67b2.png)

Additional Info:
---------------------------

**Comment by Werner1201** [comment]
In the time of both running I've got a output of the snapshot of the processes:

``` ps -uax | grep 'MultiMC\|multimc' ```:

``` 
werner    605077  0.0  0.0   9500  3400 ?        S    12:01   0:00 /bin/bash /opt/multimc/run.sh
werner    605079  0.2  0.4 1177632 107372 ?      Sl   12:01   0:03 ./MultiMC
werner    605242  0.0  0.0   9500  3452 ?        S    12:01   0:00 /bin/bash /home/werner/.local/share/MultiMC --alive
werner    605251  2.9  0.4 1129880 119176 ?      Sl   12:01   0:36 /home/werner/.local/share/bin/MultiMC -d /home/werner/.local/share --alive
werner    608730  0.0  0.0   9060  2576 pts/1    S+   12:22   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox MultiMC\|multimc


```

**Comment by Werner1201** [comment]
I tried using the new version and installed a new instance and it "installed" the multimc version inside the .local/share/

**Comment by Werner1201** [comment]
I tried using the new version and installed a new instance and it "installed" the multimc version inside the ```.local/share/```

**Comment by Werner1201** [comment]
Fixed by Deleting the MultiMc executable inside the correct .local/share/multimc folder and executing the program again via the run.sh which forces to download the executable again and from a very previous version. Clicking to update works and closes the previous version window and opens the new one

**Comment by Zetabite** [comment]
please close the issue then

**Comment by Werner1201** [comment]
Sorry for the waiting.
