### ISSUE TITLE
Fails to start Minecraft 1.16.4 with exit code -1

### ISSUE THREAD

**Issue by TheNanoMachi** [MultiMC/MultiMC5#3542]
System Information
-----------------------------
MultiMC version: MultiMC 5 - Version 0.6.11-1430

Operating System: Windows

Summary of the issue or suggestion:
----------------------------------------------
When attempting to launch Minecraft 1.16.4, the launch fails with java.lang.reflect.InvocationTargetException. A full crash report below:
https://pastebin.com/VbbPFAzF

What should happen:
------------------------------
Minecraft successfully launches.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create new instance of Minecraft 1.16.4 with Fabric 0.11.1 and Fabric API 0.29.1 installed.

2. Launch Minecraft instance.

3. Launch stops with exit code -1.

Suspected cause:
---------------------------
Fabric API.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/F0aK7 - Log
![image](https://user-images.githubusercontent.com/34221391/105119475-6756b380-5a9e-11eb-8df8-ab4d3d5ea169.png) - All loaded mods.

Additional Info:
---------------------------

**Comment by ChloeDawn** [comment]
You need to update OptiFabric
