### ISSUE TITLE
Account issues

### ISSUE THREAD

**Issue by Serenaxo** [MultiMC/MultiMC5#3544]
When i try to add my Microsoft account, it says my email or password is wrong, i know i typed them correctly as i had just logged in on the minecraft website.

**Comment by jotoho** [comment]
See #3493, #3523 or #3496. All of these (and maybe others I've missed) will tell you what you need to know. There's also [a blog post by the maintainer about this topic.](https://multimc.org/posts/microsoft-accounts.html)

Please take a look at the existing issues before making a new one, next time.

**Comment by HeyBanditoz** [comment]
They are going to start migration pretty soon I think. Hopefully this any those many other issues will be resolved by then.

**Comment by walker5live** [comment]
I prefer this launcher to the original one, but with the upcoming plans Microsoft has to migrate things this launcher will need to be able to support Microsoft accounts.

**Comment by Zetabite** [comment]
Its all just a question of Microsoft to release approved method for this

**Comment by HeyBanditoz** [comment]
> Its all just a question of Microsoft to release approved method for this

There's this: [https://wiki.vg/Microsoft_Authentication_Scheme](https://wiki.vg/Microsoft_Authentication_Scheme)

**Comment by Zetabite** [comment]
Whatever this is, it isnt official nor approved.

**Comment by rom4ster** [comment]
Who cares if its approved do it anyways. Why wait on microcrap to do anything.
