### ISSUE TITLE
MultiMC instances with Forge installed simply won't start.

### ISSUE THREAD

**Issue by Labyrinthia** [MultiMC/MultiMC5#3545]
System Information
-----------------------------
MultiMC version:
MultiMC 5 - Version 0.6.11-1430

Operating System:
Windows 7 64bits

Summary of the issue or suggestion:
----------------------------------------------
Adding Forge to any version of the game simply won't let the game start. Even if it has no mods loaded.
This also goes for modpack instances gotten via the "FTB Legacy" tab.

"Vanilla" instances results in the game starting normally.

What should happen:
------------------------------
Game start normally.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Select any instance of the game that has Forge in it.

2. Launch said instance.

3. Process exits with code -1.

Suspected cause:
---------------------------
I'm clueless, really.

Logs/Screenshots:
----------------------------
https://paste.ee/p/IrLp5

Additional Info:
---------------------------
Up until some time ago MultiMC was working normally. I don't recall making any changes to the game directy or java version so I'm not sure what's the problem.

**Comment by jotoho** [comment]
You are using Java 11 instead of Java 8. Vanilla can use newer versions too, but modded minecraft is more picky. you can change the version multimc uses in the settings.

**Comment by jotoho** [comment]
If this helped you, please don't forget to close the issue. Otherwise you need to give us the new log.

**Comment by spinkleboi** [comment]
Bruh 11 I used 14 lol well next time join the discord server and in the multimc channel past the link.
