### ISSUE TITLE
Dont work 1.12.2 on new version MultiMC

### ISSUE THREAD

**Issue by superuser127** [MultiMC/MultiMC5#3546]
MultiMC version: everything after 0.6.7
Operating System: GNU/Linux Mint 20.1(64bit)
Summary of the issue or suggestion:
Dont work minecraft 1.12.2(Other versions may not work either). Tried with and without forge. All package dependencies are met. Installed MultiMC using deb-packages and sources. I did not install another mods. Version 1.12.2 is work on my system on MultiMC version 0.6.7-1290 and earlier
Logs:
https://paste.ee/p/Efyss
-----------
Sorry if I made a mistake in writing the text. I do not speak English well
Thanks in advance for your help)

**Comment by phit** [comment]
you need to use java 8 https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java

**Comment by superuser127** [comment]
> you need to use java 8 https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java

Спасибо огромное. От всей Русской души)

**Comment by AverageComet250** [comment]
I've seen so many issues regarding incorrect java versions that I think a fix is required. Maybe a small java script that just checks the version of java that the JVM is using. If it gives out a version that isn't 8 it can say that you have an incorrect version of java.

**Comment by spannerman79** [comment]
@AverageComet250 that implies that every single user **only** will play modded mc with multimc.

You cannot state that as you don't know that for a fact.  No one does.

Yes by default the vanilla launcher ships with Java 8u51 ( re: https://help.minecraft.net/hc/en-us/articles/360029643932-Problematic-frame-or-pixel-format-not-accelerated & https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs ) for windows users.  But that doesn't mean that, for example, vanilla 1.16.4 doesn't work with say Java 11 doesn't work.

See the issue now?

Besides in the works there is a system being put in place once peterix gets to it in the _very_ long to do list.

**Comment by AverageComet250** [comment]
@spannerman79 instead of forcing a pop up that appears if you're running a forge or fabric instance with a java version that isn't 8. The pop up would show a warning and say to switch to java 8 before filing an issue.

That is 1 alternative.

**Comment by Forkk** [comment]
Closed for inactivity.
