### ISSUE TITLE
1.8.9 Sound bug

### ISSUE THREAD

**Issue by SteamF4lk** [MultiMC/MultiMC5#3547]
System Information
-----------------------------
MultiMC version:

Operating System: Windows 7 64 bit

Summary of the issue or suggestion:
----------------------------------------------
When i launch Minecraft 1.8.9 on forge the sound does not work at all. on vanilla it does though, any fixes?

What should happen:
------------------------------
sound should be working but is not

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. launch 1.8.9 on forge

2.

3.

Suspected cause:
---------------------------
forge, minecraft version, or pc?

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://gyazo.com/da463ea96e59fefa10e77160aad5b46b

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
please provide the full log: https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png
