### ISSUE TITLE
Code 255. Mac OSX. Game keeps crashing upon start.

### ISSUE THREAD

**Issue by bluemonkey96** [MultiMC/MultiMC5#3549]
System Information
-----------------------------
MultiMC version:0.6.11-1370

Operating System: Mac OS BigSur 11.1

Summary of the issue or suggestion:
----------------------------------------------
Keep crashing when trying to start the modpack Valhelsia 3.

What should happen:
------------------------------
I should be playing.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Start MultiMC

2.Download Valhelsia 3.

3.Start Valhelsia 3/Minecraft

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[old crash report](https://paste.ee/p/6YkbD#)

[Instance Java Setting](https://paste.ee/p/0S9lC)

**[New crash report with Java 241](https://paste.ee/p/0S9lC)**

Additional Info:
---------------------------
Vanilla works fine.
Tried without the mod Performant.
Tried using Java 1.8.0_241 *See New crash report*

**Comment by spannerman79** [comment]
Try https://github.com/MultiMC/MultiMC5/wiki/Java-on-macOS

**Comment by bluemonkey96** [comment]
> Try https://github.com/MultiMC/MultiMC5/wiki/Java-on-macOS

Tried it not changing much. will edit the issue with new crash report..

**Comment by bluemonkey96** [comment]
Seems like Forge is the problem because Fabric works really well.
