### ISSUE TITLE
MultiMc Mac Quitting when opening forge  1.15 above

### ISSUE THREAD

**Issue by TonyBurritoNico** [MultiMC/MultiMC5#3550]
System Information
-----------------------------
MultiMC version: 0.6.11 - 1370 on osx64

Operating System: Macos Big Sur

Summary of the issue or suggestion:
----------------------------------------------
when i open multimc forge it says this: https://pastebin.com/XPD19M4J
i have tried this with 2 versions and they both quit when i do
What should happen:
------------------------------
open minecraft 1.16 forge

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
https://pastebin.com/XPD19M4J

Additional Info:
---------------------------

**Comment by AverageComet250** [comment]
Try creating a new instance, reinstalling forge/fabric and readding mods.

Also redownload the mods don't copy paste them, in case you have any faulty jars.

**Comment by AverageComet250** [comment]
Also what cpu do you have.

**Comment by TonyBurritoNico** [comment]
i did redownload and i did make new instance even without mods it still happens

**Comment by TonyBurritoNico** [comment]
and also im on mac if this makes a differance

**Comment by TonyBurritoNico** [comment]
s

> Also what cpu do you have.

im on mac and dont know how to check

**Comment by phit** [comment]
this is Apple's fault, wait for Mojang/Apple to fix it, see the discussion here https://forums.minecraftforge.net/topic/94803-javalangillegalstateexception-glfw-error-before-init-0x10008cocoa-failed-to-find-service-port-for-display/
