### ISSUE TITLE
All Vanilla Versions Below 1.13 Fail To Launch (Ubuntu Linux)

### ISSUE THREAD

**Issue by BJTMastermind** [MultiMC/MultiMC5#3551]
System Information
-----------------------------
MultiMC version: 0.6.11-1344

Operating System: Kubuntu Linux

Summary of the issue or suggestion:
----------------------------------------------
When ever i try to launch a version of minecraft from 1.12.2 and below
they will start to launch but then fail with a process exit code 255
What should happen:
------------------------------
Minecraft should open in the versions below 1.13

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Make a Instance of Vanilla Minecraft 1.12.2 or below.

2. Select the Instance you created.

3. Click Launch

Suspected cause:
---------------------------
OpenGL drivers or LWJGL

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/dpj0h

Additional Info:
---------------------------
I have Java 8 Select in the MultiMC Settings

**Comment by phit** [comment]
install the non headless version of openjdk8

**Comment by AverageComet250** [comment]
Also are you running this off a raspberry pi 4 or a similar arm device? If no, you have the wrong version of java, as you have the arm64 version not the x86_64 version

**Comment by phit** [comment]
amd64 not arm, they have the right java, just the headless version

**Comment by BJTMastermind** [comment]
I will try getting the openjdk8 headless version,

**Comment by BJTMastermind** [comment]
Doing 
```sudo apt install openjdk-8-jdk``` 
To install the non headless version fixed the problem thanks!
