### ISSUE TITLE
MultiMC is my only mod hope for linux

### ISSUE THREAD

**Issue by Stevenzocker** [MultiMC/MultiMC5#3552]
System Information
-----------------------------
MultiMC version: 0.6.11-1344

Operating System: Pop!_OS

Summary of the issue or suggestion: doesn't remember my settings and starts all in light mode and with some packs missing as well as my account data no being saved
----------------------------------------------

What should happen: just start with all my settings and packs loaded
------------------------------

Steps to reproduce the issue (Add more if needed): 
-------------------------------------------------------------
1.
  you do anything in the settings
2.
  you close the window
3.
  open MultiMC again
Suspected cause: i've got no idea
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
Are you running a live usb?

**Comment by Forkk** [comment]
Please fill out the issue form correctly.
