### ISSUE TITLE
无法添加最新的curse forge整合包

### ISSUE THREAD

**Issue by jsdjaj** [MultiMC/MultiMC5#3553]
我试了很多最新的curse forge整合包都不行

**Comment by AverageComet250** [comment]
Please use English when reporting issues.

**Comment by peterix** [comment]
Anything to do with 'curse forge' will be denied.

**Comment by peterix** [comment]
Regardless of what it is.

**Comment by AverageComet250** [comment]
@jsdjaj use the comments section on the curseforge page
