### ISSUE TITLE
can't sign in

### ISSUE THREAD

**Issue by kwensel** [MultiMC/MultiMC5#3554]
i created a microsoft account with minecraft a week ago, now i try to sign in to multimMC but i get an error and that said: invalid credits pls help me because i want mods

**Comment by Zetabite** [comment]
MS accounts dont work on MMC yet, since the implementation isnt there yet, due to no approved solution by Microsoft. This shouldnt stop you from playing modded mc tho

**Comment by kwensel** [comment]
ok is there another way to play with mods?

**Comment by Zetabite** [comment]
the usual way? installing forge and putting mods in a folder?

**Comment by kwensel** [comment]
do you know a tutorial video?

**Comment by kwensel** [comment]
i don't know how it works

**Comment by Zetabite** [comment]
there are enough tutorials online

**Comment by kwensel** [comment]
ok thanks for helping me
