### ISSUE TITLE
A MC 1.2.3 Technic Launcher modpack (YogBox) crashes when attempting to launch in MultiMC

### ISSUE THREAD

**Issue by Lufvave** [MultiMC/MultiMC5#3560]
System Information
-----------------------------
MultiMC version:
0.6.11-1430

Operating System:
Windows 10 Pro N

Summary of the issue or suggestion:
----------------------------------------------
I have been trying to get the old YogBox from Technic running on MultiMC, however whenever I attempt to launch it, it crashes

What should happen:
------------------------------
Start the modpack without crashing

Steps to reproduce the issue:
-------------------------------------------------------------
I have followed[ these ](https://www.reddit.com/r/FeedTheBeastCrashes/comments/5hau73/how_do_i_transfer_a_modpack_from_technic/) instructions to convert a Technic modpack to MultiMC, I just added modloader to it
the modpack I used is YogBox and can be downloaded on the [Technic Platform here](https://www.technicpack.net/modpack/yogbox.552680) _(version 1.2.1)_ 

>  1. Create MultiMC instance
> 
>  2. Target the same Minecraft version
> 
>  3. Edit Instance
> 
>  4. Add Forge, target the version the modpack needs

5. I added mod loader as suggested [on my previous Issue](https://github.com/MultiMC/MultiMC5/issues/3557), in order to prevent the game from crashing when loading a world

> 6. Launch the instance without doing anything else - confirm it you can get to the Minecraft main menu, then close
> 
> 7. Open the Instance's minecraft folder, delete everything
> 
> 8. Open your modpack's minecraft folder, copy all contents, paste in the MultiMC's minecraft folder you just cleared

9. Launch game

Suspected cause:
---------------------------
I suspect the process of converting a Technic modpack does not apply to older versions of minecraft, like this one (1.2.3)
I have used MultiMC a lot in the past, but this new version seems to work completely differently than what I remember, so this issue is also most likely due to my _newbieness_

The issue is also propably somehow linked to modloader

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
[MultiMC console log pastebin link](https://pastebin.com/hXNqyW2k)

Minecraft crashes and displays the blue crash screen, however it doesn't react, sort of starts blinking and then shuts itself down
I can't view the whole thing, the most I've been able to do is take this screenshot before it shut down
![YogBox crash](https://user-images.githubusercontent.com/78086980/106098321-1ba8a780-6139-11eb-9601-b57c1c2e18b4.png)

Additional Info:
---------------------------
The modpack launches _'perfectly'_ on Technic Launcher, I just want to get it running on MultiMC

The modpack initially booted _**seemingly**_ fine, it started crashing after I installed modloader to prevent different kind of crashing

**Comment by AverageComet250** [comment]
Like I said in your previous issue, I would recommend switching to the 1.7 version of the mod pack, but if you're intent on using 1.2.3, then it might be worth manually adding all the mods, instead of using the modpack.

**Comment by Lufvave** [comment]
In _.minecraft > bin_ Technic Launcher modpacks have modpack.jar, so go into _MultiMC > Edit Instance > add to .jar_ and add modpack.jar, this fixes... basically all of my modpacks

**Comment by kb-1000** [comment]
No. Use the Technic platform import support, it automatically does that.

**Comment by Lufvave** [comment]
> No. Use the Technic platform import support, it automatically does that.

How/where do I access this?

**Comment by browsky300** [comment]
Use the dev version by going to Settings > MultiMC > Features, setting the update channel to Development, and clicking the update button on the main menu.
