### ISSUE TITLE
Game fails to load when starting it out of MultiMC.

### ISSUE THREAD

**Issue by carlos-miller-466** [MultiMC/MultiMC5#3565]
System Information
-----------------------------
MultiMC version: 0.6.11-1344 (lin64)

Operating System: Pop_OS 20.10 on AMD64

Summary of the issue or suggestion:
----------------------------------------------
Game fails to load when starting it out of MultiMC. I've reinstalled OpenJDK 8 and the internal MultiMC Java test didn't show any errors yet I keep getting the same error log.

What should happen:
------------------------------
Game window should start without error.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch Instance with latest version of All Of Fabric.

2. Wait for asset index to update.

3. Crash occurs.

Suspected cause:
---------------------------
Bad Java Install/Failure to find and load Java.

Logs/Screenshots:
----------------------------
https://paste.ee/p/z2fNP

Additional Info:
---------------------------

**Comment by AverageComet250** [comment]
What do you mean by 'launching outside of multimc'
