### ISSUE TITLE
Forge not working on 1.8.9

### ISSUE THREAD

**Issue by H0qpp** [MultiMC/MultiMC5#3566]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: Windows 10 home

Summary of the issue or suggestion: Forge is not loading on 1.8.9 (only 1.8.9) when i launch it, vanilla just opens up (with optifine). 
----------------------------------------------

What should happen: Self explanatory
------------------------------

Logs/Screenshots:

Under "Edit Instance"
https://user-images.githubusercontent.com/78278973/106368504-3d2cad80-634a-11eb-9a32-1254e3c1098b.png

Just shows Minecraft vanilla
https://user-images.githubusercontent.com/78278973/106368500-2e45fb00-634a-11eb-86b0-60e648011b20.png

----------------------------

**Comment by AverageComet250** [comment]
How did you install optifine and do you have any other mods?

Thanks,
Shravan Mandava

________________________________

**Comment by QuImUfu** [comment]
move Forge below Minecraft in the Version tab of the Edit Instance window. That should be the default when installing forge.
