### ISSUE TITLE
Feedback/Suggestion: "Set Default" appears to only change the "Active" account. This is confusing.

### ISSUE THREAD

**Issue by Xastabus** [MultiMC/MultiMC5#3567]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
"Set Default", "No Default", and "Use as default?" UI elements imply a per-instance setting in the context of their usage. These UI elements only change or clear the "Active?" account under the launcher's main Settings > Accounts. This is inconsistent, not clearly communicated, and confusing.

I was trying to figure out how to set specific instances to use specific accounts. Wording like "Set Default", "No Default", and "Use as default?" in various places implies that this would be possible. Searching for help, I found from very old tickets #209 & #529 that support for instance-level default accounts was scrapped because it would somehow cause added inconvenience to users.

Personally, I find it more inconvenient there isn't an option to set default accounts on a per-instance level. This is most inconvenient as modded instances tend to have very long initial load times. Launching an instance with the wrong account requires the instance to be closed and re-launched. It may require other running instances to be closed and relaunched to re-authenticate.

What should happen:
------------------------------
The current implementation of a "Default" account applies globally to all instances. Similar functionality could be achieved by having instance-level default account settings that may be unspecified (and should be unspecified by default) and a launcher-level default account setting applied when an instance-level default is unspecified.

There could even be an instance-level account option of "Ask Me" to force the account selection dialog for specific instances regardless of the launcher-level default account setting.

This would give users with multiple accounts greater convenience and control over instance-specific preferences without inconveniencing other users.

Perhaps this could be done with just the addition of an optional instance-level setting that (if defined by the user) would automatically change the active account in the launcher when an instance is selected?

I realize this is a matter of convenience that only affects users with multiple accounts and is not a high priority due to the upcoming migration of Mojang accounts to Microsoft accounts, but it would be greatly appreciated if at least an instance-level account default setting could be given more consideration.

Thank you.

**Comment by peterix** [comment]
Works as intended.
There is no concept of 'active' account. This is something we don't do here.

**Comment by peterix** [comment]
I've considered this many times (stopped counting) and the answer is still 'no'.
