### ISSUE TITLE
mod load crash

### ISSUE THREAD

**Issue by jwarrior319** [MultiMC/MultiMC5#3568]
System Information
-----------------------------
MultiMC version: 0.6.11-1344 MultiMC 5

Operating System: Ubuntu 20.10

Summary of the issue or suggestion:
----------------------------------------------
crashes during initial mod loading

What should happen:
------------------------------
successfully launch 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch with or without optifine and all mods installed

Suspected cause:
---------------------------
mixin

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/xIrvO

Additional Info:
---------------------------

**Comment by spannerman79** [comment]
This issue tracker is for actual issues with MultiMC.  Not for modpack nor mod issues.

**Comment by AverageComet250** [comment]
Try disabling all the mods that effect world generation, but @spannerman79 is right, this is for multimc issues not mod/modpack issues. If you got the pack off curse forge, then use the comments section on the mod pack for help, or the modpack's issue tracker if it has one.

**Comment by jwarrior319** [comment]
it was anviltweaks apparently
