### ISSUE TITLE
Libraries Folder Not In MultiMC Folder

### ISSUE THREAD

**Issue by beexubee** [MultiMC/MultiMC5#3569]
System Information
-----------------------------
MultiMC version:
0.6.11-1430
Operating System:
Windows 10

Summary of the issue or suggestion:
----------------------------------------------
The mod pack I am trying to create won't launch. I don't understand what the log is saying about a libraries folder that my MultiMc folder is supposed to have in it. It doesn't have one. I've looked it up but all I'm getting is ARMS something and the other and but even downloading that hasn't fixed anything. I still get the same error.

What should happen:
------------------------------
The game should launch. I've tested the mod pack before by just putting the mods into my .minecraft mods folder straight up and it worked, but since then I think I've added mods and it won't work now. 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Copy over mods in mod pack folder to the instance in MultiMC's mod folder.
(please see additional notes for questions)
2.Launch offline to test.

Suspected cause:
---------------------------
No libraries folder. The exact wording that is given is:

Couldn't extract native jar 'C:/Users/Gabba/OneDrive/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar' to destination 'C:/Users/Gabba/OneDrive/Desktop/MultiMC/instances/Magical Senses/natives'
Couldn't extract native jar 'C:/Users/Gabba/OneDrive/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar' to destination 'C:/Users/Gabba/OneDrive/Desktop/MultiMC/instances/Magical Senses/natives'
Couldn't extract native jar 'C:/Users/Gabba/OneDrive/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar' to destination 'C:/Users/Gabba/OneDrive/Desktop/MultiMC/instances/Magical Senses/natives'
Couldn't extract native jar 'C:/Users/Gabba/OneDrive/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar' to destination 'C:/Users/Gabba/OneDrive/Desktop/MultiMC/instances/Magical Senses/natives'
Couldn't extract native jar 'C:/Users/Gabba/OneDrive/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar' to destination 'C:/Users/Gabba/OneDrive/Desktop/MultiMC/instances/Magical Senses/natives'
Couldn't extract native jar 'C:/Users/Gabba/OneDrive/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar' to destination 'C:/Users/Gabba/OneDrive/Desktop/MultiMC/instances/Magical Senses/natives'
Couldn't extract native jar 'C:/Users/Gabba/OneDrive/Desktop/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar' to destination 'C:/Users/Gabba/OneDrive/Desktop/MultiMC/instances/Magical Senses/natives'

Logs/Screenshots:
----------------------------
https://paste.ee/p/WeU6a
Screenshot of MultiMC Folder:
![image](https://user-images.githubusercontent.com/78312530/106390622-3c7e3080-63b7-11eb-86da-abd24ef8c0d0.png)

Additional Info:
---------------------------
Also, any advice on what mod is a core mod so they can properly be sorted would be greatly appreciated because the mod pages don't say if a mod has to go into the coremods folder or not.

**Comment by phit** [comment]
move multimc out of onedrive

**Comment by beexubee** [comment]
I have done so and I still get the same errors just without the OneDrive in the pathing. I don't know where to find/get the libraries folder it is asking for.

**Comment by phit** [comment]
new log please

**Comment by beexubee** [comment]
I think I have figured it out. I might have been launching offline like a moron so it wasn't making the libraries folder in the first place. I will try this then send the log fo the launching offline version if need be.

**Comment by beexubee** [comment]
Ok after finding more brain cells to launch normally to create the libraries folder, the game launch but didn't make it back the mod loading screen before crashing with error -1 which I have seen a post about on here so I'm going to check out that post for a solution.
Log for reference if you want it still:
https://paste.ee/p/cdJKV

 Also in my post, I asked about advice on the core mods situation. Do you have any to spare?

**Comment by AverageComet250** [comment]
If you look in your log, it should say if it's found a coremod. It'll also give the name there. For your info, things like impact and optifine are core mods, and pretty much any forge mod that allows you to install it straight into the launcher as well as add it to your mods folder is a core mod.

**Comment by beexubee** [comment]
aaaaah thank you so much!

**Comment by beexubee** [comment]
It's running now! Thank you to all who helped!
