### ISSUE TITLE
Error install mod packs.

### ISSUE THREAD

**Issue by wgaylord** [MultiMC/MultiMC5#3571]
System Information
-----------------------------
MultiMC version:  0.6.11-1430

Operating System: Windows 10 

Summary of the issue or suggestion:
----------------------------------------------
When trying to install a mod pack zip the install errors after downloading all the mods then pops up a window with  "Job 'Mod download' failed to process:".

What should happen:
------------------------------
The mod pack should install.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download a mod pack zip from Curseforge / Twitch.

2. Add instance from zip

3. Error after downloading everything.

Suspected cause:
---------------------------
I am thinking something with the weird looking path its trying to use.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/qNDsE

Additional Info:
---------------------------
I can make new instances just fine so I know its not a permission issue.

**Comment by wgaylord** [comment]
This issue also exists on 0.6.12-develop-1498 with both loading from Zip and also from the twitch menu.
Zip Log - https://paste.ee/p/FTzEU
Twitch Menu log - https://paste.ee/p/y9IcL

**Comment by spannerman79** [comment]
Error is that http error 502 is unknown to `QNetworkReply`

Example line;

```
C Failed  "https://cursemeta.dries007.net/430513/3153298.json"  with reason QNetworkReply::NetworkError(UnknownServerError)
```

When opening said URL in web browser Cloudflare reports it as http error 502 with their usual custom landing page.

**Comment by UpcraftLP** [comment]
yes, [cursemeta](https://cursemeta.dries007.net) is down at the moment.

**Comment by wgaylord** [comment]
Should probably open a new issue about how a gracefully failure with a useful error message for the user should be displayed, but as this is technically not a MultiMC issue I will be closing this.

**Comment by peterix** [comment]
Please keep this open until this is resolved.

**Comment by UpcraftLP** [comment]
Update: All back up and running again.

According to @dries007 the root cause was a failed server update.
