### ISSUE TITLE
CurseMeta deprecation

### ISSUE THREAD

**Issue by ExecuteOrd66** [MultiMC/MultiMC5#3572]
System Information
-----------------------------
MultiMC version: 0.6.12-develop-1498

Operating System: Windows x64

Summary of the issue or suggestion:
----------------------------------------------
Unable to locate certain modpacks via Twitch, when adding a new instance. In my case, I am unable to locate "All of Fabric 3 - 1.16.5". 

What should happen:
------------------------------
"All of Fabric 3 - 1.16.5" should be displayed after query.

Steps to reproduce the issue:
-------------------------------------------------------------
1. Add new instance

2. Go to Twitch tab

3. Search "All of Fabric 3 - 1.16.5"

Suspected cause:
---------------------------
CurseMeta is now deprecated, according to Dries007 (found here: https://cursemeta.dries007.net/), which I suspect MultiMC still relies on, according to issue #3571 posted earlier. The API can now be directly accessed via "Twitch App API".

**Comment by spannerman79** [comment]
> CurseMeta is now deprecated, according to Dries007 (found here: cursemeta.dries007.net), which I suspect MultiMC still relies on, according to issue #3571 posted earlier. The API can now be directly accessed via "Twitch App API".

Nope - doesn't apply.

Also;

![Capture](https://user-images.githubusercontent.com/7542384/106574666-4bb7d680-658f-11eb-881e-647440e72b8b.PNG)

PEBKAC

**Comment by ExecuteOrd66** [comment]
Ok. I have reinstalled MultiMC and now everything is working. Sorry for false issue.

**Comment by spannerman79** [comment]
Then close the issue.
