### ISSUE TITLE
Multi MC Foolcraft 4 crashed

### ISSUE THREAD

**Issue by BlossomPeach65** [MultiMC/MultiMC5#3573]
[https://paste.ee/p/RkDKf](url) -->https://paste.ee/p/RkDKf

all I did was add optifine and shaders onto it

**Comment by jotoho** [comment]
Not a MultiMC issue. Do your own research or contact the modpack authors for help. People on the MultiMC Discord might also be able to help you. Line 3492 indicates that you ran out of memory, so you probably need to increase the limit in the instance settings.

Also: You broke the URL. Here's a working one: https://paste.ee/p/RkDKf

**Comment by BlossomPeach65** [comment]
so this is a world i based off of enigmatica 2 is it just a memory thing too because I wanna play with shaders but I don't think my laptop can handle it. https://paste.ee/p/WU2wi

**Comment by BlossomPeach65** [comment]
and now it says this :( https://paste.ee/p/cr8OZ
