### ISSUE TITLE
How much memory for a world?

### ISSUE THREAD

**Issue by BlossomPeach65** [MultiMC/MultiMC5#3576]
I added more mods to the Enigmatica 2 modpack and it has like 330 ish mods and I want to have shaders. I have 8000-12000 mb dedicated to it and when I click on a shader it crashes... how much more should I add about I only have like 20 gb on my laptop.￼

**Comment by jotoho** [comment]
This is NOT a general minecraft forum. The Discord is a better place to ask these questions than a **bugtracker** for the minecraft **launcher.**

Here's the Discord invitation link from multimc.org: https://discord.gg/0k2zsXGNHs0fE4Wm

You currently have ***9 open issues, all of which don't seem to have anything to do with MultiMC***, the oldest of which is from August. Please close them and go somewhere else for general minecraft support.
