### ISSUE TITLE
GDLauncher Modpack Error with Fabric

### ISSUE THREAD

**Issue by Jefaxe** [MultiMC/MultiMC5#3578]
System Information
-----------------------------
MultiMC version: 0.6.12-develop-1500

Operating System: Windows 10, 64-bit

Summary of the issue or suggestion:
Currently, exporting a modpack from gdlauncher then importing to multimc works (didn't expect that, thanks!), but it ends with Unkown Modloader: fabric. It does not install fabric on that instance.

What should happen:
It should install fabric.

Steps to reproduce the issue (Add more if needed):
1. Create a pack on GDLauncher.

2. Export it.

3. Create a new instance, and click "import from zip", and import your pack

4. It downloads all mods, but not fabric.

Suspected cause:
Some formatting issue in manifest.json

Logs/Screenshots:
![image](https://user-images.githubusercontent.com/73656286/107032178-4c2cb900-67ab-11eb-92ba-3371d8e34bb8.png)

![image](https://user-images.githubusercontent.com/73656286/107032214-5949a800-67ab-11eb-8ba5-1f39815ae6b4.png)

![image](https://user-images.githubusercontent.com/73656286/107032234-623a7980-67ab-11eb-8f61-b3142680b8cc.png)

Additional Info:
Last screenshot shows the upload does infact work.

**Comment by peterix** [comment]
I don't see any reason why this should work?

**Comment by kb-1000** [comment]
Does CurseForge properly import it?
This import option in MultiMC is for CurseForge's ZIP format.

**Comment by peterix** [comment]
Indeed. Curseforge should implement it first. It's their format, and they should define how it works, and what the acceptable values are.

Taking a proprietary format and expanding it is ... somewhere between irresponsible, aggressive and unethical.
In the industry, it's called [Embrace, extend, and extinguish].(https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish)

**Comment by peterix** [comment]
So, this is only a correct thing to do IF this imports cleanly in the curse client.

**Comment by extremMiSt** [comment]
hi,

How about if it's a modpack from curseforge found via the multimc search?
Like I am having the same problem with https://www.curseforge.com/minecraft/modpacks/fabric-simple-origins

**Comment by phit** [comment]
this was added with https://github.com/MultiMC/MultiMC5/commit/3390367d931cc47a8c9980d456546326d5c5e2cd since CurseForge now officially supports Fabric, can you please share your MultiMC log, can be found in the main MultiMC folder

**Comment by extremMiSt** [comment]
[MultiMC-0.log](https://github.com/MultiMC/MultiMC5/files/6686202/MultiMC-0.log)
The error message is in line 502

**Comment by phit** [comment]
the pack doesn't install in the Curseforge launcher either, it's using some non standard format. We only support the Curseforge standard, if some other launcher creates some incompatible files that's their issue.
![image](https://user-images.githubusercontent.com/2097483/122754058-6fa45c00-d293-11eb-95fa-1e9295c060e2.png)

**Comment by extremMiSt** [comment]
Thank you for clearing that up.

**Comment by coldReactive** [comment]
Here's my log:
[MultiMC-0.log](https://github.com/MultiMC/MultiMC5/files/7070106/MultiMC-0.log)

I have a microsoft account due to migration, so I wouldn't be able to test any fixes anyway, as your login system will return 207: Gone using migrated account credentials.
