### ISSUE TITLE
Direwolf20 1.16 pack won't install off of FTB on the developer branch

### ISSUE THREAD

**Issue by JustANormalHooman** [MultiMC/MultiMC5#3581]
System Information
-----------------------------
MultiMC version: 0.6.12-develop-1503

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
The Direwolf 20 pack isn't installing through Multimc, but I can get it through FTB just fine.

What should happen:
------------------------------
Direwolf 20 pack should be able to be installed through Multimc using the "Add Instance > FTB" tab

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add the Direwolf 20 pack through the Add Instance tab

2. Try to launch it

3. Get an error, despite having all green checks for auth and session, etc.

Suspected cause:
---------------------------
The launcher is likely having some form of difficulty contacting the forge servers for some reason. I am able to download the library zip from the URL in the log manually in a web browser, so I know that my network . I don't know if there is a way to manually add said files to the instance, but that would certainly be nice.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/Xap8U

Additional Info:
---------------------------

**Comment by phit** [comment]
problem with forge, not related to multimc https://twitter.com/ForgeDevTeam/status/1356456863684943872
