### ISSUE TITLE
Game not launching: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by madguy123456788** [MultiMC/MultiMC5#3584]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows

Summary of the issue or suggestion:
----------------------------------------------
Unable to start Minecraft

What should happen:
------------------------------
For the game to run normally

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.  Download and import my "broken" instance (https://mega.nz/file/aOZxTYLZ#kmKQgzm9oG0zrrB91d2vILvV9BkBrx1zIBer9Fi1-Yw)

2. Attempt to launch the instance

Suspected cause:
---------------------------
I had multiple power outages while the game was running through MultiMC, after about 2 or 3 outages the game crashes upon launch. I suspect the non-graceful shutdowns are the root cause of this problem.

Logs/Screenshots:
----------------------------
https://paste.ee/p/jqNbU

Additional Info:
---------------------------
Other issues on this repo regarding this problem have the resolution of using java 8, The problem remains even after reinstalling/installing a later build of Java 8

**Comment by ImperatorStorm** [comment]
you may be using an older java version than was used to compile some of the mods you used.

Try using [Java 15](https://adoptopenjdk.net/releases.html?variant=openjdk15&jvmVariant=hotspot)

**Comment by ImperatorStorm** [comment]
> [00:49:31] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: java.lang.RuntimeException: Failed to load FML config from C:\Users\madgu\Downloads\mmc-stable-win32\MultiMC\instances\Mekanism pack\.minecraft\config\fml.toml

looks like a config file corrupted, i'd try deleting it and seeing if it solves the problem

**Comment by peterix** [comment]
Never use Java 15 with any of the existing versions of Minecraft.

**Comment by madguy123456788** [comment]
Thanks for the responses. After clearing all of my mod configs, I'm able to get it running as normal!
