### ISSUE TITLE
(Suggestion): Specify Java Version for Individual Instances

### ISSUE THREAD

**Issue by masternetra** [MultiMC/MultiMC5#3585]
System Information
-----------------------------
MultiMC version: 5 (0.6.11-1344)

Operating System: Linux (64bit) - (Linux Mint 20 - Cinnamon)

Summary of the issue or suggestion:
----------------------------------------------
Just a suggestion, would like to see the ability to assign specific java version usage to specific instances. I ask this because while Minecraft 1.13 and up is fine with you using the latest versions of Java (Like Java 15), 1.12 isn't and will crash (With Oracle Java 15 at bear minimal). Allowing us to be able to assign specific java versions to a instance would allows us to continue to play both latest MC pack or vanilla game versions on the latest version of java, while being able play older MC pack favorites on like Java 8 without having to go into setting every single time you want to switch between them.

This shouldn't of course replace the what is current but simply serve as a override applied to instances that specify it.

What should happen:
------------------------------
Go into Instance settings, have Java section, with java setup like in settings but they just apply for that instance only.

Steps to reproduce the issue (Add more if needed): N/A

Suspected cause: N/A
---------------------------

Logs/Screenshots: N/A
----------------------------

Additional Info: N/A
---------------------------

**Comment by Zetabite** [comment]
already exists

**Comment by peterix** [comment]
Yep.

**Comment by peterix** [comment]
![image](https://user-images.githubusercontent.com/203326/107155994-01ae6680-697c-11eb-9522-da20c7e0c9f4.png)

**Comment by masternetra** [comment]
Oops my bad missed that.
