### ISSUE TITLE
Can't use a lightly modded 1.16 instance

### ISSUE THREAD

**Issue by ComradeRick** [MultiMC/MultiMC5#3586]
I tried to set up a 1.16 instance today as I had to reinstall windows, and I used it once, had to go out for a while (and as such shut down my computer), and when I came back later and tried to use it, whenever I joined a server it inexplicably crashed. Any help? Thanks.

https://pastebin.pl/view/c9318e62

**Comment by AverageComet250** [comment]
What is the folder named `mamiyaotaru`?

Also, did you try connecting without optifine? It looks like an issue loading the resource pack.

**Comment by ComradeRick** [comment]
I would, however I get less than 30 frames usually without optifine. Should I turn off the resource pack before connecting?

**Comment by AverageComet250** [comment]
Yeah that sounds reasonable. I'd recommend asking if anyone else has the issue, and try connecting to a server like hypixel that doesn't have a resource pack.

**Comment by spannerman79** [comment]
That is an invalid paste.

Use the built in upload log feature within MultiMC - see both https://github.com/MultiMC/MultiMC5/wiki/Minecraft-Logs & https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png
