### ISSUE TITLE
Compiling MultiMC

### ISSUE THREAD

**Issue by Sebastian-byte** [MultiMC/MultiMC5#3587]
System Information
-----------------------------
MultiMC version: 0.6.12

Operating System: Windows Server 2019

Summary of the issue or suggestion:
----------------------------------------------
I can't compile MultiMC in Windows by using the help in the build.md file

The build isn't working probably due to linker issues, I followed the guide in the build.md in an fork with GitHub actions.

What should happen:
------------------------------
Successful Compilation

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Follow the guide to compile given in build.md file for Windows

Suspected cause:
---------------------------
MinGW Linker 

Logs/Screenshots:
----------------------------
![image](https://user-images.githubusercontent.com/62727185/107275818-383dbd00-6a20-11eb-8bca-65c4ef74582e.png)

Additional Info:
---------------------------
The GNU/Linux compilation it's actually working, but not in Windows.

**Comment by peterix** [comment]
I'm not going to support forks.

**Comment by Sebastian-byte** [comment]
Ok, I respect that, But can you at least give me the code you use to compile MultiMC in Teamcity? (teamcity.multimc.org)

**Comment by peterix** [comment]
No, I won't. If you are making forks, you are on your own.

**Comment by peterix** [comment]
Make sure you aren't calling it MultiMC, btw.

**Comment by Sebastian-byte** [comment]
I will try to compile the Original and Pure MultiMC to test if the same thing happens.
