### ISSUE TITLE
Mac OS X build guide outdated

### ISSUE THREAD

**Issue by Dakkaron** [MultiMC/MultiMC5#3589]
System Information
-----------------------------
MultiMC version: current develop branch

Operating System: Mac OS X

Summary of the issue or suggestion:
----------------------------------------------
I tried building MultiMC according to the OS X build guide on Big Sur, but it seems outdated. First, it wants me to install gcc48 from brew, but they only have gcc49.
When using gcc49 cmake fails with this message:

error: unknown value '11.0' of --macos-version-min

What should happen:
------------------------------
It should compile successfully.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Follow the Mac OS X build guide

2. Install gcc49 instead of gcc48

Suspected cause:
---------------------------
Outdated documentation.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
Fixed in https://github.com/MultiMC/MultiMC5/commit/e8b9176736c8ab32731c4f01fe886de0c6377c57
