### ISSUE TITLE
Make updates that apply on close download when closing

### ISSUE THREAD

**Issue by oeed** [MultiMC/MultiMC5#359]
At the moment if there is an update available MultiMC will tell you when you open it and ask  if you want to update now or when you close MultiMC. However, if you choose to update when you close it still downloads them immediately anyway, although it does install it when closing. It would be useful if it were to download the files when I was finished and didn't have to wait a few minutes before being able to play.

**Comment by peterix** [comment]
I am removing this 'update on exit'. You can click the update button whenever it is convenient.
