### ISSUE TITLE
Enhancement: Add support for Modrinth

### ISSUE THREAD

**Issue by pjlasl** [MultiMC/MultiMC5#3591]
Add support for Modringth Modpacks. Documentation can be found here: https://github.com/modrinth/labrinth/wiki

**Comment by ThexXTURBOXx** [comment]
Maybe not only Modpacks, but Mods also :)
This mod support could also include importing/downloading/updating/managing mods within MultiMC from CurseForge, MCArchive, Modrinth etc.

**Comment by peterix** [comment]
Absolutely not.

**Comment by peterix** [comment]
1. There's nothing there in terms of modpacks
2. I will not integrate with any single mod 'blob store', only with something that indexes them all

**Comment by peterix** [comment]
Specifically, just shifting all the mod download sites into a slightly different window is not an improvement, and integrating with them individually would not accomplish anything better.

This needs to be in a component that is OUTSIDE MultiMC. It does not belong here.

As for modpacks, that might become reasonable if/when Modrinth hosts modpacks.
