### ISSUE TITLE
Log in issues Msoft account used to buy Minecraft

### ISSUE THREAD

**Issue by tomparonett** [MultiMC/MultiMC5#3598]
System Information
-----------------------------
MultiMC version: 0.6.11-11370 on osx64

Operating System: Mac OS Bigger on M1 MacBook Air 2020

Summary of the issue or suggestion:
----------------------------------------------
I appear to be unable to log into Mutlimc to use this as a launcher. I intended to utilize this launcher as there is a workaround available that allows users to configure a java version that is optimized for ARM based chips (the M1). I configured everything for that properly. I went ahead and bought Minecraft java edition, in doing so it of course makes me purchase Minecraft under a Microsoft account which I already had one, so I used that of course. I am not able to log into Multimc for some reason despite my Minecraft account being my Microsoft account.

What should happen:
------------------------------
I should be able to log into multimc without issue with my log in credentials I use for Minecraft which are my Microsoft account log in credentials.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. pretty self explanatory 

2.

3.

Suspected cause:
---------------------------
I suspect the cause is that when you have a Minecraft account purchased under a Microsoft account it doesn't also create a Minecraft/mojang account using your Microsoft account information. The workaround should be as simple as, "don't have a mojang/mincraft account click here" which will page you to another screen to log in using another account method... idk though

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
Microsoft accounts are not supported yet.

**Comment by CryoRenegade** [comment]
Yeah more like a Soon`tm`
