### ISSUE TITLE
Crash on launch in multimc

### ISSUE THREAD

**Issue by SmileyFaces** [MultiMC/MultiMC5#3599]
Game crashes when launching. It's weird because it started today and I haven't changed any settings.

console log: https://pastebin.com/Q8TntmW2

**Comment by AverageComet250** [comment]
Could you paste the end of the log here maybe the last fifty lines or so cause pastebin keeps crashing my phone.

**Comment by phit** [comment]
custom fog is crashing probably due to optifine

**Comment by wb1016** [comment]
you cant use multiple graphics mods at the same time in most cases. delete custom fog mod.

this issue should be closed.
