### ISSUE TITLE
No modpack icons

### ISSUE THREAD

**Issue by TheCultLeader666** [MultiMC/MultiMC5#3600]
Whenever I create a new instance and import a modpack from any of the integrated modpack providers, instead of importing the packs icon, the instance uses the default icon

**Comment by Zetabite** [comment]
please follow the template

**Comment by TheCultLeader666** [comment]
I didn't get a template

**Comment by Zetabite** [comment]
yes you did, you deleted it

**Comment by Zetabite** [comment]
> I didn't get a template, which I admit I thought was weird, but it's probably because I submitted this through GitHub mobile

hm

**Comment by TheCultLeader666** [comment]
I'll close this and submit a new issue on desktop

**Comment by Zetabite** [comment]
just reopen it on desktop and add template
