### ISSUE TITLE
No Modpack Icons

### ISSUE THREAD

**Issue by TheCultLeader666** [MultiMC/MultiMC5#3601]
System Information
-----------------------------
MultiMC version:
0.6.12-develop-1456
Operating System:
macOS 10.15.7
Summary of the issue or suggestion:
----------------------------------------------
Whenever I create a new instance and import a modpack from any of the providers, the instances uses the default icon

What should happen:
------------------------------
The instance should import the modpack's icon from the modpack provider

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a new instance and select any modpack from any provider

2. The instance will use the default "infinity" icon

3.

Suspected cause:
---------------------------
No idea, worked up until recently

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![Screen Shot 2021-02-11 at 13 39 18](https://user-images.githubusercontent.com/65368815/107682898-d9cf4380-6c98-11eb-988a-7ca4523f2249.png)
![Screen Shot 2021-02-11 at 13 40 44](https://user-images.githubusercontent.com/65368815/107682916-dfc52480-6c98-11eb-9cd0-c50d8c9f776d.png)

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
hm, thats weird, i have no issues. could you provide the MultiMC.0.log?

**Comment by TheCultLeader666** [comment]
> hm, thats weird, i have no issues. could you provide the MultiMC.0.log?

Where might I find that?

**Comment by kb-1000** [comment]
You can find it in the MultiMC.app directory, at `Content/MacOS`

**Comment by TheCultLeader666** [comment]
https://paste.ee/p/N7n56

**Comment by TheCultLeader666** [comment]
This seems like the culprit
`29.964 D Task "NetJob(Twitch Icon Download )" starting for the first time
   29.966 C "Could not open /Applications/MultiMC.app/Contents/MacOS/cache/TwitchPacks/logos for writing"
   29.966 C "Could not open /Applications/MultiMC.app/Contents/MacOS/cache/TwitchPacks/logos for writing"
   29.966 C "Could not open /Applications/MultiMC.app/Contents/MacOS/cache/TwitchPacks/logos for writing"
   29.966 C "Could not open /Applications/MultiMC.app/Contents/MacOS/cache/TwitchPacks/logos for writing"
   29.967 C Task "NetJob(Twitch Icon Download )" failed:  "Job 'Twitch Icon Download ' failed to process:\n"`

**Comment by TheCultLeader666** [comment]
But I have no idea what it means

**Comment by jotoho** [comment]
My somewhat-uneducated guess would be permission problems. Maybe the MultiMC process doesn't have the required permissions to write to that folder/file.

**Comment by TheCultLeader666** [comment]
Just gave it full disk access, same problem

**Comment by AverageComet250** [comment]
Does the folder `cache/TwitchPacks/logos` exist inside `Contents/MacOS` directory. If no, try grabbing a brand new version of multimc and copy across the instances folder.

**Comment by TheCultLeader666** [comment]
yeah its there

**Comment by TheCultLeader666** [comment]
Should I empty it so that it regenerates the files? It is in the `cache` folder

**Comment by TheCultLeader666** [comment]
Didn't work, ill try reinstalling

**Comment by TheCultLeader666** [comment]
Still doesn't work

**Comment by TheCultLeader666** [comment]
This is somewhat of a nuisance ._.

**Comment by Forkk** [comment]
phit on discord says this has been reproduced, so marked as bug.

Please don't spam the issue tracker.

**Comment by phit** [comment]
i think this was fixed, at least I haven't seen this in a while.
