### ISSUE TITLE
Can't load up modpacks,  Instance update failed

### ISSUE THREAD

**Issue by Endetrix** [MultiMC/MultiMC5#3603]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 10

Summary of the issue or suggestion: 
----------------------------------------------
Was able to use MultiMC alright a few days ago. Now I can't play any modpack.

What should happen:
------------------------------
Modpack should load and I should be able to play Minecraft.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC

2. Select a modpack (i.e GregBlock 1.10.2)

3. Launch (Online or Offline, both yield same result)

4. Game launcher errors

Suspected cause:
---------------------------
No idea, any help would be greatly appreciated.

Logs/Screenshots:
----------------------------
[https://paste.ee/p/r5C8Z](https://paste.ee/p/r5C8Z)

Additional Info:
---------------------------
Worked fine for me a few days ago.

**Comment by AverageComet250** [comment]
Looks like an issue with your WiFi.

I can access the file fine from my phone.

Try again later or disconnect and reconnect to your WiFi.
