### ISSUE TITLE
Minecraft Forge crashing on boot (1.16.5/36.0.22)

### ISSUE THREAD

**Issue by Alandiethebest** [MultiMC/MultiMC5#3604]
System Information
-----------------------------
MultiMC version: MultiMC5 Version 0.6.11-1430

Operating System: Windows 10 Pro, Version 2004 (OS Build 19041.508)

Summary of the issue or suggestion:
----------------------------------------------
When clicking the launch button, Minecraft Forge opens up and after approximately a minute of loading, it abruptly crashes with exit code -1.

What should happen:
------------------------------
Minecraft Forge loads the mods completely and runs like normal.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add all the mods listed in my log

2. Launch Minecraft on any Forge version available for 1.16.5

3. Wait approximately a minute

Suspected cause:
---------------------------
Could be an issue with Mixin or FML based on what I can see from the log, but I am no expert whatsoever.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
Crash log: https://paste.ee/p/IPEbm

Additional Info:
---------------------------
I have tried removing some mods that have some errors in the log, such as Apotheosis, Better Controls, Charm, but it gives no difference. Also, the crash seems to be time-based, as it takes the same time to reach the crash whatever mods I remove.

**Comment by DalenW** [comment]
Just played for a couple hours on the exact same config as you, with my only mods being optifine and voxel map. Probably a mod issue with the forge version.

**Comment by spannerman79** [comment]
This issue tracker is for **actual** issues with MultiMC.  Not a tracker/help desk for general modded help.  There are plenty of other alternatives for that. Such as the #minecraft channel on the MultiMC discord, r/feedthebeastcrashes, etc.

Invalid issue.
