### ISSUE TITLE
Linker Issues Again (in the original code!)

### ISSUE THREAD

**Issue by Sebastian-byte** [MultiMC/MultiMC5#3607]
System Information
-----------------------------
MultiMC version: develop branch

Operating System: Windows

Summary of the issue or suggestion:
----------------------------------------------
I tried to build MultiMC, but it fails with **lots** of linker errors, I already have Zlib, OpenSSL, JDK and QT in the PATH.

What should happen:
------------------------------
Successful Build.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
Follow the Windows build guide.

Suspected cause:
---------------------------
The Linker, Or maybe i'm doing something wrong?

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
nah, the build guide is just outdated afaik

**Comment by Sebastian-byte** [comment]
Was me, was using an wrong compiler (64-bit MinGW) after that the build runned successfully, but you also need to add Qt MinGW to Path and run "mingw32-make install" (if you used Qt Creator to build it) on the build folder.

**Comment by peterix** [comment]
This is definitely a WONTFIX.

Don't do development on Windows, it's bad for you.

**Comment by Sebastian-byte** [comment]
Yes, Windows isn't Made for development (soon I will migrate to GNU/Linux), also the Windows build guide needs to be updated.

**Comment by AverageComet250** [comment]
@Sebastian-byte if you're planning on switching to Linux, then I'd recommend looking into WSL rather than installing linux alongside windows or overwriting it.

**Comment by kb-1000** [comment]
TBH... don't use WSL. It's Microsoft showing again that they think of Linux as a GUI-less server-only OS.
Besides, MultiMC does not run in WSL, and will not. Use real Linux, not some Microsoft extension of it running in a VM. ref: they've added a proprietary DirectX 12 API already, see [EEE](https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish) and [DirectX on "Linux"](https://devblogs.microsoft.com/directx/directx-heart-linux/)

**Comment by peterix** [comment]
No.
