### ISSUE TITLE
Allow to install beta releases on Twitch

### ISSUE THREAD

**Issue by Seegras** [MultiMC/MultiMC5#3611]
It would be helpful if MultiMC also allowed to install beta releases of modpacks from twitch.

Not quite sure whether Twitch even allows that; pretty sure it's not allowed with alpha, but beta might.

**Comment by spannerman79** [comment]
Give a direct URL of one such modpack that is in "beta" @Seegras

**Comment by Seegras** [comment]
Right now https://www.curseforge.com/minecraft/modpacks/all-of-fabric-3 
has 2 releases out; 2.6.3 and 2.6.6 the latter marked beta. If I install, I always get 2.6.3. 
On Vanilla I can choose to also download betas.

**Comment by spannerman79** [comment]
You still can - just download the zip and import it as a new instance.

> On Vanilla I can choose to also download betas.

Vanilla launcher **by default** has no modding capability - unless you add in forge/fabric manually.

**Comment by Forkk** [comment]
This looks like it's resolved.

**Comment by kb-1000** [comment]
It's not really, you can't tell the twitch page to import the latest beta version

**Comment by Forkk** [comment]
Clearly I misread this. My apologies. Marked as a feature request.
