### ISSUE TITLE
my game crashes every time i load a world in minecraft and it keeps happening and it says exit code -1 failed to create a child loop

### ISSUE THREAD

**Issue by idonthaveaname123** [MultiMC/MultiMC5#3612]
[crash-2021-02-17_11.26.54-client.txt](https://github.com/MultiMC/MultiMC5/files/5995365/crash-2021-02-17_11.26.54-client.txt)

**Comment by spannerman79** [comment]
Upload the log directly from within MultiMC

https://github.com/MultiMC/MultiMC5/wiki/Minecraft-Logs

Like this - https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by wb1016** [comment]
invalid issue. should be closed.
