### ISSUE TITLE
Skin is gone?

### ISSUE THREAD

**Issue by lopus65466** [MultiMC/MultiMC5#3613]
System Information
-----------------------------
MultiMC version: 0.6.12 devolper (Ive also tried fixing it by going to the regular it doesnt work)

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Every time i launch a modpack doesnt matter which one it just doesnt load my skin

What should happen:
------------------------------
I should have my skin

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
Nothing pretty sure it just happens to me

Suspected cause:
---------------------------
I honestly dont know

Logs/Screenshots:
----------------------------
![WHAT](https://user-images.githubusercontent.com/65353615/108286829-070f6c00-7147-11eb-9345-37c141775333.png)
![SKin](https://user-images.githubusercontent.com/65353615/108286876-1bebff80-7147-11eb-96b3-d02c964eec54.png)

Additional Info:
---------------------------
Those 2 pictures i attached are my multimc launcher and what happens when i launch a modpack in this instance its the 1.16.4 modpack skybee's but it happens on any modpack

**Comment by spannerman79** [comment]
This isn't a MultiMC issue.

As by the looks of it you are playing either as Offline, or SSP.  There are mods that can fix the visual look of a missing skin.

https://www.curseforge.com/minecraft/mc-mods/lumy-skin-patch is one such mod.  There are **many** others.

**Comment by lopus64655** [comment]
hey this is me the post owner i forgot my password to that account but i dont want to reset it (im still logged in on my pc on my phone atm) do you know a mod for 1.16.4 like that or how i find mods like that also what is ssp

**Comment by Zetabite** [comment]
there is the possibility its because of MC using ipv6, try this as java argument `-Djava.net.preferIPv4Stack=true`

**Comment by lopus65466** [comment]
> there is the possibility its because of MC using ipv6, try this as java argument `-Djava.net.preferIPv4Stack=true`

Where would I put this?

**Comment by jiggak** [comment]
@lopus65466 Edit Instance -> Settings -> Java Arguments

**Comment by lopus65466** [comment]
thanks
