### ISSUE TITLE
Game crashes immediately upon loading the main menu

### ISSUE THREAD

**Issue by TheNanoMachi** [MultiMC/MultiMC5#3616]
System Information
-----------------------------
MultiMC version:0.6.11-1430

Operating System:Windows

Summary of the issue or suggestion:
----------------------------------------------
The game crashes once loading has completed (after the red loading screen but before any buttons). This happens with both my custom modset and only optifine, optifabric, the fabric API, and the Fabric Loader.

What should happen:
------------------------------
The game should complete loading.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a new instance with the newest version of Fabric, and the following mods: 
![image](https://user-images.githubusercontent.com/34221391/108560884-65655780-72cb-11eb-9b60-8c0ddaa0f013.png)

2. Load the game

3. The game crashes.

Suspected cause:
---------------------------
Optifine, as it is still the 1.16.4 version and could be outdated.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
https://paste.ee/p/OWhfe

Additional Info:
---------------------------

**Comment by AverageComet250** [comment]
Is the optifine jar the one that is downloaded from the website or the one that you get when you use the extract button in the installer jar file. It looks to me like you put the installer and not the forge mod in the mods folder.

**Comment by wb1016** [comment]
seems you are not using extracted optifine. check out optifabric's guide.

unrelated issue.
should be closed.

**Comment by Forkk** [comment]
This is not an issue with MultiMC.
