### ISSUE TITLE
An example of Microsoft Login implementation in Java (GeyserMC)

### ISSUE THREAD

**Issue by CactiChameleon9** [MultiMC/MultiMC5#3617]
Summary of the issue or suggestion:
I am unsure about what has already been done and what has been planned to help with Microsoft logins in MultiMC, but I thought it would be helpful to mention that this has been done before, in case you want to copy the code or find a native (e.g. non-browser) solution. Specifcally its in another open-source Minecraft java project called Geyser (you may or may not be familiar with it) - with the pull request with the feature being [here](https://github.com/GeyserMC/Geyser/pull/1808)

Sorry if you knew about this already or you have other plans... I am just trying to be helpful

Finally,
Thank you so much for providing such an amazing piece of open source software!

**Comment by spannerman79** [comment]
Did you even do a [search](https://github.com/MultiMC/MultiMC5/search?q=microsoft+is%3Aissue&type=issues) beforehand?  Doubt it.  I'm not going to list the individual issues listed in that search as there is over 10 pages of results.

Invalid issue.

**Comment by CactiChameleon9** [comment]
Sorry... I will close the issue. I did search beforehand and read the article about the ms account changes and multiMC. There was nothing on geyser and their implementation, so I assumed this would be helpful. Sorry again
