### ISSUE TITLE
Couldn't extract native jar error when booting instance after crash

### ISSUE THREAD

**Issue by Rodnock** [MultiMC/MultiMC5#3618]
System Information
-----------------------------
MultiMC version: 0.6.12-develop-1520

Operating System: Windows 10 Pro 64 bit

Summary of the issue or suggestion:
----------------------------------------------
I experienced a game crash, and now when I try to launch the instance again I get the following:

Couldn't extract native jar 'F:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar' to destination 'F:/MultiMC/instances/Enigmatica 6 0.3.11/natives'
Couldn't extract native jar 'F:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar' to destination 'F:/MultiMC/instances/Enigmatica 6 0.3.11/natives'
Couldn't extract native jar 'F:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar' to destination 'F:/MultiMC/instances/Enigmatica 6 0.3.11/natives'
Couldn't extract native jar 'F:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar' to destination 'F:/MultiMC/instances/Enigmatica 6 0.3.11/natives'
Couldn't extract native jar 'F:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar' to destination 'F:/MultiMC/instances/Enigmatica 6 0.3.11/natives'
Couldn't extract native jar 'F:/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar' to destination 'F:/MultiMC/instances/Enigmatica 6 0.3.11/natives'
Couldn't extract native jar 'F:/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar' to destination 'F:/MultiMC/instances/Enigmatica 6 0.3.11/natives'

What should happen:
------------------------------
Instance should launch

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Attempted to launch instance after crash

2. Restarted MultiMC

3.

Suspected cause:
---------------------------
Unknown

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Cannot upload entire log using Upload button. Antivirus blocks for a trojan.

MultiMC version: 0.6.12-develop-1520

Minecraft folder is:
F:/MultiMC/instances/Enigmatica 6 0.3.11/minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 1.8.0_271, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  F:/MultiMC/instances/Enigmatica 6 0.3.11/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  F:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  F:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  F:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  F:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  F:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  F:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  F:/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  F:/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  F:/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  F:/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  F:/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  F:/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  F:/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  F:/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  F:/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  F:/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  F:/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  F:/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  F:/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  F:/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  F:/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  F:/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  F:/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  F:/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  F:/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  F:/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  F:/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  F:/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  F:/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar
  F:/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.11.2/log4j-core-2.11.2.jar
  F:/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  F:/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/1.4.2/ForgeWrapper-1.4.2.jar
  F:/MultiMC/libraries/net/minecraftforge/forge/1.16.5-36.0.10/forge-1.16.5-36.0.10-launcher.jar
  F:/MultiMC/libraries/org/ow2/asm/asm/9.0/asm-9.0.jar
  F:/MultiMC/libraries/org/ow2/asm/asm-commons/9.0/asm-commons-9.0.jar
  F:/MultiMC/libraries/org/ow2/asm/asm-tree/9.0/asm-tree-9.0.jar
  F:/MultiMC/libraries/org/ow2/asm/asm-util/9.0/asm-util-9.0.jar
  F:/MultiMC/libraries/org/ow2/asm/asm-analysis/9.0/asm-analysis-9.0.jar
  F:/MultiMC/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar
  F:/MultiMC/libraries/cpw/mods/grossjava9hacks/1.3.0/grossjava9hacks-1.3.0.jar
  F:/MultiMC/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  F:/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  F:/MultiMC/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  F:/MultiMC/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  F:/MultiMC/libraries/net/minecraftforge/coremods/4.0.3/coremods-4.0.3.jar
  F:/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  F:/MultiMC/libraries/com/electronwill/night-config/core/3.6.2/core-3.6.2.jar
  F:/MultiMC/libraries/com/electronwill/night-config/toml/3.6.2/toml-3.6.2.jar
  F:/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  F:/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.0/maven-artifact-3.6.0.jar
  F:/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  F:/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  F:/MultiMC/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar
  F:/MultiMC/libraries/net/minecraftforge/nashorn-core-compat/15.1.1/nashorn-core-compat-15.1.1.jar
  F:/MultiMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  F:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  F:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  F:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  F:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  F:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  F:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  F:/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  F:/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] [1.16.4]-additionalbars-1.6.0
  [✔️] additional_lights-1.16.4-2.1.3
  [✔️] AdHooks-1.16.4-6.1.3.0-build.0038
  [✔️] AI-Improvements-1.16.2-0.3.0
  [✔️] aiotbotania-1.16.4-1.7.0
  [✔️] AkashicTome-1.4-15
  [✔️] alexsmobs-1.4.1
  [✔️] AmbientSounds_v3.1.4_mc1.16.4
  [✔️] angelring-1.16.3-1.3.3
  [✔️] Apotheosis-1.16.3-4.4.1
  [✔️] AppleSkin-mc1.16.2-forge-1.0.14
  [✔️] Aquaculture-1.16.4-2.1.12
  [✔️] archers_paradox-1.16.3-1.1.1
  [✔️] architectury-1.5.104-forge
  [✔️] ars_nouveau-1.16.4-1.11.2
  [✔️] Artifacts-1.16.4-2.7.5
  [✔️] astralsorcery-1.16.4-1.13.9
  [✔️] AttributeFix-1.16.5-10.0.1
  [✔️] AutoRegLib-1.6-47
  [✔️] BackTools-1.16.3-10.0.0
  [✔️] bambooeverything-1.16.3-forge-1.0.0
  [✔️] BedBenefits-1.16.5-5.0.3
  [✔️] bedspreads-forge-1.16.4-5.1.0.1
  [✔️] BetterAdvancements-1.16.4-0.1.0.104
  [✔️] BetterBurning-1.16.5-6.0.2
  [✔️] BetterCaves-Forge-1.16.4-1.1.1
  [✔️] BetterMineshafts-Forge-1.16.4-2.0.1
  [✔️] BiomesOPlenty-1.16.4-13.0.0.430-universal
  [✔️] blockcarpentry-1.16-0.3.5a
  [✔️] BloodMagic-1.16.4-3.1.0-15
  [✔️] Bookshelf-1.16.5-10.0.1
  [✔️] Botania-1.16.4-411
  [✔️] BotaniaAdditionsMC1.16.4-1.0.4
  [✔️] BotanyPots-1.16.5-7.0.2
  [✔️] BotanyTrees-1.16.5-3.0.1
  [✔️] Bountiful Baubles FORGE-1.16.3-0.0.2
  [✔️] buildersaddition-1.16.4-20210127a
  [✔️] buildinggadgets-1.16.4-3.7.3
  [✔️] bwncr-1.16.4-3.9.16
  [✔️] byg-1.1.9
  [✔️] caelus-forge-1.16.5-2.1.2.2
  [✔️] cakechomps-forge-1.16.4-5.0.0.2
  [✔️] campfiretorches-1.16.3-1.0.3
  [✔️] catjammies-1.0.0
  [✔️] cc-tweaked-1.16.4-1.95.2
  [✔️] cherishedworlds-forge-1.16.4-5.1.0.0
  [✔️] chiselsandbits-0.2.10-RELEASE
  [✔️] citadel-1.5.3
  [✔️] clockout-1.16.4-2.0.0.1
  [✔️] Clumps-6.0.0.13
  [✔️] cobblegenrandomizer-1.16-5.1.2
  [✔️] CodeChickenLib-1.16.4-3.5.1.408-universal
  [✔️] cofh_core-1.16.3-1.1.6
  [✔️] comforts-forge-1.16.4-4.0.1.0
  [✔️] configswapper-1.1
  [✔️] connectedglass-1.0.6-mc1.16.4
  [✔️] Controlling-7.0.0.12
  [✔️] cookiecore-1.16.2-3.0.2-9389769
  [✔️] CookingForBlockheads_1.16.3-9.2.2
  [✔️] CosmeticArmorReworked-1.16.5-v1
  [✔️] craftingstation-4.1.1
  [✔️] CraftingTweaks_1.16.3-12.2.0
  [✔️] create-mc1.16.3_v0.3e
  [✔️] CreativeCore_v2.0.10_mc1.16.4
  [✔️] CTM-MC1.16.1-1.1.2.6
  [✔️] curioofundying-forge-1.16.4-5.1.0.0
  [✔️] curios-forge-1.16.4-4.0.3.5
  [✔️] Curious Armor Stands-1.16.3-2.0.2
  [✔️] curiouselytra-forge-1.16.5-4.0.2.0
  [✔️] DangerousStoneCutter-1.16.2-1.4
  [✔️] dankstorage-3.14
  [✔️] DarkUtilities-1.16.5-8.0.2
  [✔️] decorative_blocks-1.16.4-1.7.2
  [✔️] DefaultOptions_1.16.3-12.2.0
  [✔️] demagnetize-forge-1.16.2-1.2.2
  [✔️] Ding-1.16.3-1.2.0
  [✔️] DrawersTooltip-1.16.2-2.1.0
  [✔️] DungeonCrawl-1.16.3-2.2.4
  [✔️] dungeons_plus-1.16.4-1.1.2
  [✔️] DustrialDecor-1.1.5
  [✔️] eidolon-0.2.7
  [✔️] elevatorid-1.16.5-1.7.12
  [✔️] embellishcraft-1.16.4-3.3.0.0
  [✔️] EmendatusEnigmatica-1.16.4-1.1.5
  [✔️] emojiful-1.16.4-2.1.4
  [✔️] EnchantmentDescriptions-1.16.5-7.0.1
  [✔️] EnderMail-1.16.4-1.2.0
  [✔️] EnderStorage-1.16.4-2.7.1.166-universal
  [✔️] engineersdecor-1.16.4-1.1.7
  [✔️] enigmatica-1.16.3-0.1.1
  [✔️] ensorcellation-1.16.3-1.1.2
  [✔️] ensorcelled-0.1a
  [✔️] extradisks-1.16.4-1.5.0
  [✔️] ExtraStorage-1.16.4-1.3.1
  [✔️] extremeSoundMuffler-3.6_Forge-1.16.4
  [✔️] FarmersDelight-1.16.3-0.3.1
  [✔️] FarmingForBlockheads_1.16.3-7.2.1
  [✔️] FastFurnace-1.16.4-4.4.0
  [✔️] FastLeafDecay-v25
  [✔️] FastWorkbench-1.16.4-4.5.0
  [✔️] ferritecore-1.1.1
  [✔️] findme-1.16.3-2.1.0.0
  [✔️] forge-1.16.5-geckolib-3.0.6
  [✔️] ForgeEndertech-1.16.4-7.0.10.0-build.0037
  [✔️] FpsReducer-mc1.16.4-1.18
  [✔️] framedcompactdrawers-1.16-2.2.0
  [✔️] ftb-backups-2.1.1.6
  [✔️] ftb-chunks-1604.2.2.61
  [✔️] ftb-essentials-1604.1.0.13
  [✔️] ftb-gui-library-1605.2.1.37-forge
  [✔️] ftb-quests-1604.1.1.21
  [✔️] ftb-ranks-1604.1.1.10
  [✔️] ftb-teams-1604.1.0.15-forge
  [✔️] ftb-ultimine-1603.1.1.13
  [✔️] GameStages-1.16.5-6.0.1
  [✔️] glassential-forge-1.16.4-1.1.5
  [✔️] gunswithoutroses-1.16.4-1.0.6
  [✔️] iChunUtil-1.16.3-10.0.0
  [✔️] ImmersiveEngineering-1.16.4-4.1.2-129
  [✔️] ImmersivePetroleum-1.16.4-3.1.0-2
  [✔️] immersiveposts-1.16.3-3.0.0
  [✔️] industrial-foregoing-1.16.5-3.2.9-2215ef4
  [✔️] Interactio-1.16.4-3.1.1
  [✔️] InventoryEssentials_1.16.3-2.3.0
  [✔️] invtweaks-1.16.4-1.0.1
  [✔️] ironchest-1.16.4-11.2.10
  [✔️] item-filters-1605.2.3.27-forge
  [✔️] JAOPCA-1.16.4-3.4.0.3
  [✔️] jei-1.16.4-7.6.1.65
  [✔️] justenoughbeacons-3.1-1.16.3
  [✔️] JustEnoughProfessions-1.16.3-1.1
  [✔️] KleeSlabs_1.16.3-9.2.0
  [✔️] kubejs-1605.3.5-build.156-forge
  [✔️] kubejs-blood-magic-1604.1.0.4
  [✔️] kubejs-create-1604.1.0.4
  [✔️] kubejs-immersive-engineering-1604.1.0.12
  [✔️] kubejs-mekanism-1604.1.1.6
  [✔️] kubejs-thermal-1604.1.0.5
  [✔️] LibX-1.16.3-1.0.10
  [✔️] Lollipop-1.16.4-3.2.4
  [✔️] lootr-1.16.4-0.0.4.13
  [✔️] LostTrinkets-1.16.4-0.1.18
  [✔️] magicfeather-1.16.2-3.1.0
  [✔️] Mantle-1.16.5-1.6.79
  [✔️] mapperbase-1.16.4-2.3.0.0
  [✔️] masonry-1.16.3-0.3.6
  [✔️] mcjtylib-1.16-5.0.15
  [✔️] mcw-bridges-1.0.5-mc1.16.5-4
  [✔️] mcw-doors-1.0.2-mc1.16.5
  [✔️] mcw-roofs-2.0.1-mc1.16.5-4
  [✔️] mcw-trapdors-1.0.1-mc1.16.5
  [✔️] mcw-windows-1.0.2-mc1.16.4
  [✔️] meetyourfight-1.16.4-1.1.0
  [✔️] Mekanism-1.16.4-10.0.19.446
  [✔️] MekanismGenerators-1.16.4-10.0.19.446
  [✔️] MekanismTools-1.16.4-10.0.19.446
  [✔️] mgui-1.16.4-3.1.3
  [✔️] mightyarchitect-mc1.16.3_v0.5
  [✔️] mininggadgets-1.7.1
  [✔️] mining-helmet-1.16.4-2.0.0
  [✔️] modnametooltip_1.16.2-1.15.0
  [✔️] modular-routers-1.16.4-7.3.1-50
  [✔️] moredragoneggs-1.4
  [✔️] MoreMobGriefingOptions-1.16.5-1.0.0
  [✔️] moreoverlays-1.18.13-mc1.16.5
  [✔️] morevanillalib-1.16.4-1.3.9
  [✔️] Morpheus-1.16.4-4.2.68
  [✔️] Morph-o-Tool-1.4-26
  [✔️] MouseTweaks-2.13-mc1.16.2
  [✔️] MythicBotany-1.16.3-1.2.0
  [✔️] NaturesAura-33.4
  [✔️] NaturesCompass-1.16.4-1.8.6
  [✔️] Neat 1.7-27
  [✔️] NetherPortalFix_1.16.3-7.2.1
  [✔️] observerlib-1.16.4-1.5.1
  [✔️] occultism-1.0.8
  [✔️] OldJavaWarning-1.16.5-7.0.1
  [✔️] overloadedarmorbar-5.1.0
  [✔️] PackMenu-1.16.4-2.3.1
  [✔️] Paraglider-1.16.2-1.3.1.0
  [✔️] PassthroughSigns-1.16.4-2.3.7
  [✔️] Patchouli-1.16.4-48
  [✔️] pedestals-0.8r_hotfix_4
  [✔️] Ping-1.16.4-1.6.9
  [✔️] pitg-1.16.3-1.4.1
  [✔️] Placebo-1.16.4-4.4.1
  [✔️] plonk-1.16.5-9.0.7
  [✔️] pneumaticcraft-repressurized-1.16.5-2.9.5-128
  [✔️] polymorph-forge-1.16.4-0.23
  [✔️] portable_stonecutter-1.16.4-1.3.2
  [✔️] Powah-1.16.4-2.3.9
  [✔️] PrettyPipes-1.9.1
  [✔️] QuantumStorage-1.16.4-5.3.0
  [✔️] QuarkOddities-1.16.3
  [✔️] Quark-r2.4-299
  [✔️] randompatches-2.2.1-forge
  [✔️] rangedpumps-0.8.2
  [✔️] rare-ice-0.2.2
  [✔️] ReAuth-1.16-Forge-3.9.3
  [✔️] recipebuffers-2.1
  [✔️] refinedstorage-1.9.11
  [✔️] refinedstorageaddons-0.7.2
  [✔️] ResourcefulBees1.16.3-1.16.4-0.5.8b
  [✔️] restriction-1.16.4-0.0.3
  [✔️] rftoolsbase-1.16-2.0.9
  [✔️] rftoolsbuilder-1.16-3.0.13
  [✔️] rftoolscontrol-1.16-4.0.6
  [✔️] rftoolspower-1.16-3.0.8
  [✔️] rftoolsstorage-1.16-2.0.8
  [✔️] rftoolsutility-1.16-3.0.20
  [✔️] rhino-1.7.13-build.12
  [✔️] rsgauges-1.16.4-1.2.8
  [✔️] rsrequestify-1.16.3-2.0.1
  [✔️] Runelic-1.16.5-7.0.1
  [✔️] SaveYourPets-1.16.2-1.0.0.5
  [✔️] scaffoldingpower-1.16.3-1.2.1
  [✔️] seals-1.16.3-2.0.0
  [✔️] serverconfigupdater-1.3
  [✔️] ServerTabInfo-1.16.4-1.3.3
  [✔️] Shrink-1.16.4-1.0.7
  [✔️] SimpleDiscordRichPresence-1.16.4-1.3.5
  [✔️] simplefarming-1.16.4-1.3.5
  [✔️] simplylight-1.16.4-1.1.1
  [✔️] snowundertrees-1.16.4-v1.1.3
  [✔️] solcarrot-1.16.3-1.9.9
  [✔️] sophisticatedbackpacks-1.16.4-1.3.4.136
  [✔️] spark-forge
  [✔️] SpawnerFix-1.16.2-1.0.0.2
  [✔️] Storage4ComputerCraft-1.16.4-1.2.1
  [✔️] StorageDrawers-1.16.3-8.2.2
  [✔️] structure_gel-1.16.4-1.7.5
  [✔️] supplementaries-1.16.5-0.9.23c
  [✔️] swingthroughgrass-1.16.4-1.5.3
  [✔️] tamedsummon-1.0.0
  [✔️] tetra-1.16.4-3.5.3
  [✔️] The_Undergarden-1.16.5-0.4.5
  [✔️] theoneprobe-1.16-3.0.7
  [✔️] thermal_expansion-1.16.3-1.1.6
  [✔️] thermal_foundation-1.16.3-1.1.6
  [✔️] thermal_innovation-1.16.3-1.1.7
  [✔️] thermal_locomotion-1.16.3-1.1.6
  [✔️] Tips-1.16.5-4.0.2
  [✔️] TipTheScales-1.16.4-3.0.0.10
  [✔️] titanium-1.16.5-3.2.6
  [✔️] TMechworks-1.16.3+-2.2.3
  [✔️] Toast-Control-1.16.4-4.3.1
  [✔️] tomeofblood-1.16.4-1.0.5
  [✔️] ToolStats-1.16.5-6.0.1
  [✔️] torchmaster-2.3.6
  [✔️] toughnessbar-6.1
  [✔️] towers_of_the_wild-1.16.4-2.0.1
  [✔️] Transport-1.16.4-3.4.1
  [✔️] trashcans-1.0.6a-mc1.16.4
  [✔️] TrashSlot_1.16.3-12.2.1
  [✔️] TravelAnchors-2.1
  [✔️] u_team_core-1.16.4-3.1.17.192
  [✔️] Undergarden-Tetra Patch-1.1.1
  [✔️] useful_backpacks-1.16.4-1.11.6.87
  [✔️] useful_railroads-1.16.4-1.4.6.35
  [✔️] valhelsia_structures-16.0.5
  [✔️] vanillaexcavators-1.16.4-2.2.0
  [✔️] vanillahammers-1.16.4-2.2.0
  [✔️] Waystones_1.16.3-7.3.1
  [✔️] Wither-Skeleton-Tweaks-1.16.4-5.3.0
  [✔️] World Stripper-1.16.4-2.0.1
  [✔️] xnet-1.16-3.0.11
  [✔️] XNetGases-1.16.4-2.2.3
  [✔️] YungsApi-1.16.4-Forge-3

Params:
  --username  --version MultiMC5 --gameDir F:/MultiMC/instances/Enigmatica 6 0.3.11/minecraft --assetsDir F:/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 36.0.10 --fml.mcVersion 1.16.5 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20210115.111550

Window size: max (if available)

Couldn't extract native jar 'F:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar' to destination 'F:/MultiMC/instances/Enigmatica 6 0.3.11/natives'
Couldn't extract native jar 'F:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar' to destination 'F:/MultiMC/instances/Enigmatica 6 0.3.11/natives'
Couldn't extract native jar 'F:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar' to destination 'F:/MultiMC/instances/Enigmatica 6 0.3.11/natives'
Couldn't extract native jar 'F:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar' to destination 'F:/MultiMC/instances/Enigmatica 6 0.3.11/natives'
Couldn't extract native jar 'F:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar' to destination 'F:/MultiMC/instances/Enigmatica 6 0.3.11/natives'
Couldn't extract native jar 'F:/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar' to destination 'F:/MultiMC/instances/Enigmatica 6 0.3.11/natives'
Couldn't extract native jar 'F:/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar' to destination 'F:/MultiMC/instances/Enigmatica 6 0.3.11/natives'

Additional Info:
---------------------------

**Comment by Rodnock** [comment]
Instance launches successfully after computer restart.

**Comment by mpavkovic** [comment]
In case someone else stumbles upon this problem, you can resolve it without restarting your PC. Open Task Manager, go to Details tab and search for javaw.exe process, it should have status Suspended, select it and click End task.

As far as I understand it, java process is still holding a file lock on some DLLs in instance's natives folder which prevents MultiMC to overwrite them when launching. Maybe a more detailed error message in that case would be helpful like "Couldn't extract native jar ... because another java process is still running". Or even better if MultiMC could terminate the process before extracting native libraries.

**Comment by James103** [comment]
> In case someone else stumbles upon this problem, you can resolve it without restarting your PC. Open Task Manager, go to Details tab and search for javaw.exe process, it should have status Suspended, select it and click End task.

It is not guaranteed that javaw.exe or java.exe is present in Task Manager in Processes or Details.
In this case, a player may need to do the following instead:
1. Open a terminal window as administrator.
2. In the admin-level terminal, run the following command: `taskkill /im javaw.exe /f`

**Comment by TheGrandJaggard** [comment]
Finding javaw.exe in the details tab of task manager and ending the task worked for me. Thanks!

**Comment by Gabo-98-alt** [comment]
I've done everything you recommend, but nothing solves the problem.
When I type the command: taskkill /im javaw.exe /f in CMD, it tells me that the process "java.exe" was not found.
The task manager also doesn't work because the file "java.exe" isn't there.
And restarting my PC doesn't work either.
I've had this error for several days, and I don't know how to fix it. I don't know if it's something else.
