### ISSUE TITLE
I cant login

### ISSUE THREAD

**Issue by BeaniBoy** [MultiMC/MultiMC5#3619]
So to make this short in sweat, I'm tiring to add a new profile because I have never used this before to create a modpack, but my issue is that MultiMC wont let me sign in. I don't have a java account because you cant make them anymore. I have a Microsoft account that allows me to play MC Java edition. For whatever reason when I enter the account email and password it doesn't work. Does my Minecraft account have a different email from Microsoft? I really wish they had a log in through Microsoft option.

**Comment by Zetabite** [comment]
you cant use MMC with MSA, support is planned, but depending on the time peterix has to implement it

**Comment by BeaniBoy** [comment]
> you cant use MMC with MSA, support is planned, but depending on the time peterix has to implement it

Thank you, do you know any other sites I can use to create mod packs similarity to MultiMC

**Comment by Zetabite** [comment]
What do you mean? There is nothing special about the way mmc makes modpacks. its just more convenient

**Comment by BeaniBoy** [comment]
> What do you mean? There is nothing special about the way mmc makes modpacks. its just more convenient
Yes, that's why I'm asking if there is any other convenient sites like this one. I'll just do some research but thanks for your help.

**Comment by JustPassingBy06** [comment]
Most (if not all) launchers don't have MSA support because Mojang/Microsoft hasn't allowed it from 3th party programs yet and because Mojang accounts haven't started migrating.

**Comment by ZYLHL** [comment]
You can try Plain Craft Launcher 2, this is a launcher made by @LTcat (a Chinese developer). It can authenticate you by both Mojang Account and Microsoft Account. Although it is still under beta progression, we can use know. Here is the link to his [donate page](http://afdian.net/@LTcat) (You need to donate ￥12.34, then you can join in inner-beta channel), here is also a free way, everyone can join in public-beta channel for free!
I uploaded the newest public-beta edition of PCL 2 here.:)
[Beta 1.5.3.zip](https://github.com/MultiMC/MultiMC5/files/6051089/Beta.1.5.3.zip)

**Comment by ZYLHL** [comment]
There is something I forget to tell. PCL 2 have no multi-languages options for now, so when open PCL 2, there is only Chinese for GUI's text. But don't be sad, there is another launcher also made by a Chinese developer, it's called **HiMinecraft!Launcher**(HMCL). HMCL support multi-languages options, and it was programmed by Java. You can learn more in HMCL's GitHub repository:https://github.com/huanghongxun/HMCL

**Comment by peterix** [comment]
And that's enough. We got people advertising other launchers here now.
