### ISSUE TITLE
Cannot log into MultiMC

### ISSUE THREAD

**Issue by cahziah** [MultiMC/MultiMC5#3621]
System Information
-----------------------------
MultiMC version: 5

Operating System: Windows

Summary of the issue or suggestion: I cannot log into my new minecraft account on MultiMC, despite being able to log onto it on the official Minecraft broweser
----------------------------------------------

What should happen: I should be able to log on 
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC

2. Open accounts and go to add new account

3. Type in account details, press enter and error message appears

Suspected cause: I think it may be because Microsoft now makes you buy MC accounts and connect them only to you Microsoft account. because my account is not a Mojang account, I suspect that it may affect me being able to log in.
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
![image](https://user-images.githubusercontent.com/79529616/108869672-83281900-764b-11eb-8604-0c6febd320ce.png)

Additional Info:
---------------------------
I have double and triple checked my password and account match my Microsoft account exactly (which is the only way I can log into the MC account)

**Comment by TheCultLeader666** [comment]
Microsoft accounts are not yet supported in multimc

**Comment by cahziah** [comment]
Thank you, all good

**Comment by nixinator** [comment]
I just got into mine craft and unfortunately if you purchase the game , your automatically have to link your microsoft account. This means MultMC5 won't log in as stated on the issue tracker.... looks like i'm doomed! :-) . What a chore!

**Comment by jamierocks** [comment]
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3392.
