### ISSUE TITLE
Using custom forge version

### ISSUE THREAD

**Issue by ubscal** [MultiMC/MultiMC5#3622]
System Information
-----------------------------
MultiMC version:
MultiMc 5 - Version 0.6.11 - 1430

Operating System:
Windows 10 Home

Summary of the issue or suggestion:
----------------------------------------------
There is no clear way to use a custom forge version, and I am unable to load a local one from local by modifying the json file.

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
I am unable to edit the forge json file to use a modified forge jar file, i have tried pointing it to a local file by following other guides, and I have tried uploading the jar to a server and downloading it on launch, but none of those work. Im using a very old version of minecraft and optifine didnt exist as a forge mod yet.

**Comment by phit** [comment]
what Minecraft version? you can use the add to Minecraft.jar button in the versions tab for most things

**Comment by ubscal** [comment]
> what Minecraft version? you can use the add to Minecraft.jar button in the versions tab for most things

1.4.7, You can add it to the jar, but trying to use forge alongside it crashes, the only way to use forge and optifine together on this version is to put the optifine files into the forge jar file and delete the META-INF. I have done that, but i cant seem to point forge to use my custom jar.

**Comment by phit** [comment]
I just tried it, works fine?
Make 1.4.7 instance, install Forge with the button in the versions tab of the instance, click add to Minecraft.jar and add the Optifine ZIP file
![image](https://user-images.githubusercontent.com/2097483/108896417-31fd3280-7615-11eb-9bae-0b0d890971b3.png)

**Comment by ubscal** [comment]
I crash with a white screen when I do that.
![image](https://user-images.githubusercontent.com/21148758/108903613-1c6f1500-75e3-11eb-8fda-26f9ddb3a7ab.png)

It also happens when no mods are installed, here is my log. https://paste.ee/p/dNTSa

**Comment by ubscal** [comment]
Figured it out, apparently you **have** to have optifine on the bottom. Thank you for your help.
