### ISSUE TITLE
Why is it crashing

### ISSUE THREAD

**Issue by LucaForever** [MultiMC/MultiMC5#3625]
I was using MultiMC a while ago, and at some point, it stopped working suddenly.

Here are the mods and logs: https://paste.ee/p/mtTTG
Note that all the mods with X I don't use, the only thing that I tried is to disable LabyMod, but it still crashes.

**Comment by Veradra** [comment]
Use java 8.

Java 15 will have issues with forge.

**Comment by LucaForever** [comment]
> Use java 8.
> 
> Java 15 will have issues with forge.

and how exactly do I do that? can I change that in the MultiMC settings?

**Comment by LucaForever** [comment]
i even reinstalled but to no avail

**Comment by phit** [comment]
https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java

**Comment by LucaForever** [comment]
> https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java

did it, but now I'm getting errors from Minecraft it's self. I already removed labymod as it seems as it interferes, but what do I do now?              https://paste.ee/p/Sg5dv

**Comment by AverageComet250** [comment]
I'm seeing errors to do with sponge, which doesn't make that much sense since sponge is a server side plugin api like bukkit. Can you disable all your mods and try connecting? Then slowly add mods one by one until it starts crashing. I also notice that is says process killed by user. Does it just get stuck loading?

**Comment by phit** [comment]
ReplayMod is clashing with something else messing with some keybind class.

@AverageComet250 Spongepowered is the organization publishing stuff like https://github.com/SpongePowered/Mixin
which is used by a lot of mods for coremodding, completely unrelated to their server software in this case

**Comment by AverageComet250** [comment]
Oh thanks @phit. I didn't realise mixin is by sponge. I thought sponge's main product is their server software.

**Comment by LucaForever** [comment]
> I'm seeing errors to do with sponge, which doesn't make that much sense since sponge is a server-side plugin api like bukkit. Can you disable all your mods and try connecting? Then slowly add mods one by one until it starts crashing. I also notice that is says process killed by user. Does it just get stuck loading?
> 
> I'm also guessing that this is your mod pack for hypixel skyblock.

well first, yes i was killing the process because it was getting stuck, and it's my hypixel mod pack.



> ReplayMod is clashing with something else messing with some keybind class.
> 
> @AverageComet250 Spongepowered is the organization publishing stuff like https://github.com/SpongePowered/Mixin
> which is used by a lot of mods for core modding, completely unrelated to their server software in this case

and i don't think it is because of replay mod, even if it has caused me some issues some time, it doesn't anymore, but ill try and see whats happening. and if it is because of replay mod, then what do i do to use it? cause that the only thing why i wanted to use forge instead of clients

**Comment by phit** [comment]
it is not because of the replay mod, as I said something else is messing with the same classes before it does, figure out which mod that is and replay mod should work

**Comment by LucaForever** [comment]
so i fixed it, idk what mod was causing the crash tho. I downgraded my replay mod to 2.1.4 and replaced some of my mods with fresh downloads and now it works

thanks @phit and @AverageComet250 

log: https://paste.ee/p/FNZ4f
