### ISSUE TITLE
Not successfully logging in. "Authentication operation cancelled."

### ISSUE THREAD

**Issue by AtkinsonStar2006** [MultiMC/MultiMC5#3627]
MultiMC version:
0.6.11-1430

Operating System:
Windows 10

Summary of the issue or suggestion:
----------------------------------------------
I've been using MultiMC for a while now, but about a week ago, I opened the program, and every service in the bottom-right corner was down, (servers weren't, and still aren't down,) I couldn't play online, and from what I remember, there was a message saying something along the lines of "Authentication error." I re-entered my account info, and it timed out a few times. I removed and tried to add it again as the FAQ tells because I had changed my username a couple of days prior, but when I tried to add an account, it said: "Authentication operation canceled." I gave it a break for a few days, and I came back to the same error when trying to log in. I am using a Mojang account, not a Microsoft account, I've had Minecraft for a few years, and I've had MultiMC work for me flawlessly in the past. 

What should happen:
------------------------------
The account should add itself.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Try to add an account in the "Accounts" tab of settings.

Suspected cause:
I did change my username, however, I tried to re-add my account, and it failed, as explained above.

Logs/Screenshots:
----------------------------
https://pastebin.com/QxPUwZ6K
I would like to point out that the Baritone/Impact Instances are always used in single-player worlds/offline mode.

**Comment by peterix** [comment]
None of the network request go through at all.

So, it's either your firewall, or everything is getting blocked somewhere down the line from you. School and work networks sometimes filter out game-related internet sites. Could be your ISP pretending to protect you.

In any case, look at the network, look at your local settings. If you have a second machine on the same network, try there and see if there is a difference. Restart your router. That sort of thing.

**Comment by AtkinsonStar2006** [comment]
MultiMC was suddenly blocked on my firewall for some reason. Allowed it through and everything works as intended. Thanks!
