### ISSUE TITLE
New instance of All of Fabric from a zip file automatically installs the Forge loader

### ISSUE THREAD

**Issue by duncanwebb** [MultiMC/MultiMC5#3628]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 7

Summary of the issue or suggestion:
----------------------------------------------
Installing a new instance of "All of Fabric" from a zip file automatically installs the Forge loader

What should happen:
------------------------------
It should install the Fabric loader.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download the zip file from https://www.curseforge.com/minecraft/modpacks/all-of-fabric-3

2. Click the Add Instance button, Select import from zip, Click the Browse button, select the downloaded zip file and Click open.

3. Play the mod pack

Suspected cause:
---------------------------
MultiMC cannot detect that the pack is for Fabric.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
What is strange is that the pack plays the first time and fails on subsequent runs with messages like:
`Caused by: java.lang.IllegalArgumentException: The specified resource 'fabric-screen-handler-api-v1.mixins.json' was invalid or could not be read`
After the Forge loader is removed and the Fabric loader is installed the game still fails as above.
I think something has been cached and not removed until MultiMC is restarted.
I rebooted my machine and the pack played again.

**Comment by whitebeartigtig** [comment]
you'll need to provide a full log. also this is not a MultiMC issue.

**Comment by jamierocks** [comment]
Well that pack does specify a Forge modloader 🤷‍♂️

```json
  "minecraft": {
    "version": "1.16.5",
    "modLoaders": [
      {
        "id": "forge-36.0.13",
        "primary": true
      }
    ]
  },
```

**Comment by whitebeartigtig** [comment]
> 
> 
> Well that pack does specify a Forge modloader man_shrugging
> 
> ```json
>   "minecraft": {
>     "version": "1.16.5",
>     "modLoaders": [
>       {
>         "id": "forge-36.0.13",
>         "primary": true
>       }
>     ]
>   },
> ```

actually yeh it'll use Jumploader to load fabric. I don't see why MultiMC wouldn't be able to use that though.

**Comment by peterix** [comment]
Works here without issues...

Provide a full log

**Comment by peterix** [comment]
Just to be clear, this is NOT a MultiMC bug and will not be addressed here in any way.

**Comment by duncanwebb** [comment]
The MultiMC log file is here https://pastebin.com/TwJMY5Jc 

That's a bit off that the pack developers would specify a forge mod loader.

What is the Jumploader?

The Minecraft crashes are annoying as they change every time and I can't seem to find a pattern when it happens.

I very much like MultiMC it is quick and easy to use, many thanks for your help and development efforts, they are much appreciated.

**Comment by jamierocks** [comment]
> The MultiMC log file is here https://pastebin.com/TwJMY5Jc

That link is broken, you can upload the log from MultiMC :)

**Comment by duncanwebb** [comment]
That's strange, the post is unlisted, and it worked for me :-D

The Minecraft log is https://paste.ee/p/tfgJr
The MultiMC log is https://paste.ee/p/2deHb

Not sure how to post the MultiMC log from the application.

**Comment by AverageComet250** [comment]
Jumploader is a mod that basically turns the fabric modloader into a forge mod. It allows fabric modpacks to be played on the curseforge app since it only supports forge. Note that it doesn't let any forge mods be loaded. It cannot be used to play fabric and forge mods at the same time. I think there was some other fabric mod that allowed forge mods to be used at the same time.

**Comment by duncanwebb** [comment]
Thank you very much. I removed forge, disabled jumploader and installed fabric and since then, the game is starting without any problems.

The jumploader seems to be a workaround for another launcher that can only load forge modpacks.

**Comment by Zetabite** [comment]
yup, twitch launcher needs it

**Comment by duncanwebb** [comment]
One more observation, when the pack is started after running other applications like brave browser, thunderbird, etc it fails to load. If MultiMC and the pack is started first thing after a boot it works.

**Comment by Scotsguy** [comment]
This is not a MultiMC issue, closing.
