### ISSUE TITLE
Getting the server Hoster IP

### ISSUE THREAD

**Issue by RomeDome** [MultiMC/MultiMC5#3629]
With MultiMC I was able to get the hosters of a servers IP I am not going to detail how but if you can prove you help with MultiMC
in anyways I will detail how it is possible to get the IP. Thank you for reading and to contact me add me on discord. 
Roman_#0518

**Comment by AverageComet250** [comment]
Incorrect issue format.

USE THE TEMPLATE.

And I don't see how this is an issue with multimc. It is a privacy concern for server hosters, but as long this stays private, eg no one makes an issue on it, it's probably never gonna get be found.

And being a server hoster myself, I don't really have an issue with my server IP being found out and getting ddosed cause they just ddos me using the domain name.

**Comment by kb-1000** [comment]
so what
of course you're going to need the IP to connect to a server, whether you enter it directly or it gets resolved via DNS
I can't see how this is a big thing

**Comment by AverageComet250** [comment]
And to be honest there are loads of websites out there where you input a domain name and it tells you the IP it resolves.

**Comment by LucaForever** [comment]
> And to be honest there are loads of websites out there where you input a domain name and it tells you the IP it resolves.

well, you can even connect to a server and if its badly set up you can see the IP with a server address mod like on lunar client

**Comment by wb1016** [comment]
unrelated issue.
should be closed.
