### ISSUE TITLE
Nao consigo adiocionar uma conta!!!!! ):

### ISSUE THREAD

**Issue by Tigrao123** [MultiMC/MultiMC5#3630]
MultiMc 5
Windows 10

When I go to add an account, I put my data, but the error. He asks for mojang account, but I have minecraft recently and I signed up with a microsoft account I tried everything):

**Comment by kb-1000** [comment]
Please use English on this issue tracker.

**Comment by Tigrao123** [comment]
ok

**Comment by wb1016** [comment]
duplicate issue about microsoft account. should be closed.

**Comment by Forkk** [comment]
Microsoft accounts are not supported yet. [Please see this post on the website for more info.](https://multimc.org/posts/microsoft-accounts.html)
