### ISSUE TITLE
Twitch/Curse Modpack search not working properly

### ISSUE THREAD

**Issue by andry08** [MultiMC/MultiMC5#3633]
System Information
-----------------------------
MultiMC version: 0.6.12-develop-1521

Operating System: Windows 10 20H2

Summary of the issue or suggestion:
----------------------------------------------
Searching for "Better Minecraft Modpack" in the twitch section leads to the wrong modpack being shown. Just for reference, this should be the correct one: https://www.curseforge.com/minecraft/modpacks/better-minecraft-modpack.
Note that this issue seems to be related to MultiMC, because searching with the api manually reports the correct modpack: 
https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=Better%20Minecraft&sectionId=4471&sort=0

What should happen:
------------------------------
The correct modpack should be listed

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC and click  "Add Instance"

2. Go to the twitch section

3. Search for "Better Minecraft Modpack"

Suspected cause:
---------------------------
I suspect the issue to be something related to the url construction [here](https://github.com/MultiMC/MultiMC5/blob/4c62776044f3a7ad9efa3150ebec6150070502ed/application/pages/modplatform/twitch/TwitchModel.cpp#L162)

Logs/Screenshots:
----------------------------
[MultiMC.log](https://paste.ee/p/IkFnP#5GKkKXfn8vwfpneZHqGQkrsccZLIXUsB) doesn't seem to contain any useful info, but I'm including it just in case
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

**Comment by kb-1000** [comment]
From the code:
```cpp
"https://addons-ecs.forgesvc.net/api/v2/addon/search?"
        "categoryId=0&"
        "gameId=432&"
        //"gameVersion=1.12.2&"
        "index=%1&"
        "pageSize=25&"
        "searchFilter=%2&"
        "sectionId=4471&"
        "sort=0"
```
`%1` is the start index (initially 0), `%2` is the search term.
MultiMC does not apply any sorting on top.
Note that the URL you provided searches for "Better Minecraft", not "Better Minecraft Modpack".

**Comment by andry08** [comment]
You're right, idk why, I meant to write "Better Minecraft".
Still, the problem is that searching for "Better Minecraft" on MultiMC yields different results from the api.
I have to agree with the fact that the api returns a wrong result searching for "Better Minecraft Modpack" which should be the modpack's full name.
These screenshot shows the difference between the search in MultiMC and the direct API.
![a1](https://user-images.githubusercontent.com/10282315/109433420-85ee8980-7a10-11eb-9ebd-cd9380510691.PNG)
![a2](https://user-images.githubusercontent.com/10282315/109433422-86872000-7a10-11eb-8e4b-d3e7882c1063.PNG)

If this you don't consider this to be an MMC issue, could you please tell me how I'm supposed to find the modpack in that screen, without having to manually download the modpack's zip and importing it manually afterwards.

**Comment by phit** [comment]
This almost looks like the MultiMC search only sends the last word from the box. There's definitely a bug here!
The results seem to match e.g. when you search "better minecraft" the results seem to match https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=Minecraft&sectionId=4471&sort=0

if I search "better minecraft modpack" the results match https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=modpack&sectionId=4471&sort=0

**Comment by phit** [comment]
the pack is being skipped because its only version is set to be compatible with multiple Minecraft versions, the pack author should fix this and set it to only be one version that is actually being used https://github.com/MultiMC/MultiMC5/blob/4c62776044f3a7ad9efa3150ebec6150070502ed/application/pages/modplatform/twitch/TwitchModel.cpp#L266

**Comment by andry08** [comment]
Oh ok, I didn't see that line, sorry about that. So, this is partially MMC fault for not handling multiple version modpacks. On that line, a version selector should be added to the twitch modpacks page.

**Comment by phit** [comment]
to select what? that pack only has one version in the actual modpack zip, the selection the pack author chose for the metadata is simply wrong, curseforge only supports one minecraft version and loader in its manifest.json

**Comment by andry08** [comment]
I mean, there is an array containing the various versions returned from the api, idk about older versions, but still, that's a starting point I guess
![aa](https://user-images.githubusercontent.com/10282315/109480558-f5e62980-7a7b-11eb-8cf3-748119dfe838.PNG)

**Comment by phit** [comment]
those are different pack versions or files, the issue here is that a single file/release is marked as supporting multiple game versions

**Comment by peterix** [comment]
Well, that's some weirdly broken data. Will take a look if we can handle it slightly better.
