### ISSUE TITLE
Homepage must communicate that only Mojang accounts work

### ISSUE THREAD

**Issue by purple512** [MultiMC/MultiMC5#3634]
I only bought Minecraft last month and I do not have a Mojang account and am unable to use MultiMC. This is not a choice I made, they made it impossible to buy the game without a Microsoft account starting 3 months ago.

It was rather frustrating going through the steps of installing and trying to add an account without it working. You could have saved a lot of time and frustration if you'd mentioned this prominently. "**_Hey, if you've bought the game since December 1, 2020 you cannot use MultiMC_**" seems like a pretty important little detail that ought to be on your home page. It's mentioned in the FAQ but only if you know to search for it, which I of course did not. This is not some small little detail.

**Comment by jamierocks** [comment]
The latest blog article is https://multimc.org/posts/microsoft-accounts.html.

**Comment by Zetabite** [comment]
I mean, besides the launcher having it in the news feed. but yeah, there are several places where you could have gotten that info from

**Comment by Forkk** [comment]
The website already communicates that Microsoft accounts are not supported yet, and this tracker is for MultiMC issues, not website issues.
