### ISSUE TITLE
Linux : Error 255 on forge modpack (SkyFactory4)

### ISSUE THREAD

**Issue by Firokat** [MultiMC/MultiMC5#3637]
The game is crashing before any window appears

System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: Manjaro (Linux) 

Summary of the issue or suggestion:
----------------------------------------------
Game crashes while starting

What should happen:
------------------------------
Game should start normaly and let me play

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Install the modpack

2. Try to start the game

Suspected cause:
---------------------------
I have no idea

Logs/Screenshots:
----------------------------
https://paste.ee/p/5gW0a

Additional Info:
---------------------------
The only version of Java running on my PC is 1.8.0_282

**Comment by jotoho** [comment]
Please upload your log [like described here](https://github.com/MultiMC/MultiMC5/wiki/Minecraft-Logs#uploading-logs) and give us the link to that upload. Normal minecraft crash reports may not give enough information

**Comment by Firokat** [comment]
Sorry, here it is : https://paste.ee/p/ujk5n

**Comment by Firokat** [comment]
SOLVED :  I had to install xrandr using :
pamac install xorg-xrandr
