### ISSUE TITLE
Minecraft bedrock/Microsoft Account

### ISSUE THREAD

**Issue by Finoway** [MultiMC/MultiMC5#3639]
I'm wondering and I haven't seen an answer for but would it be possible one day to launch minecraft windows 10 edition when you're on windows 10 and/or why not minecraft pocket edition for linux users ? because given that microsoft accounts will soon be linked it would allow us not to look at ten thousand places to play minecraft whatever the version. (to see for the obtaining of the apk in the case of pocket edition either to link the google account, or to ask for the apk and for windows 10 take the version already installed if install or ask to install it or see to install it thanks to multimc and the microsoft account) 

I don't know if my idea is possible but I prefer to propose it anyway ^^ 

System Information
-----------------------------
MultiMC version: 0.6.12-develop

Operating System:
   - Kernel 5.9
   - OS Manjaro Linux
   - Desktop KDE

**Comment by spannerman79** [comment]
Minecraft for Windows 10 is commonly known as Bedrock edition.  It was never inteded to be ran on any other OS other then... wait for it... Windows 10.

There are **severe** limitations to bedrock edition compared to java edition.

https://help.minecraft.net/hc/en-us/articles/360034753992-Different-Minecraft-Editions

The Merge from Mojang accounts to MS accounts has no bearing on the ability to play other then Java edition.

If you wish to use Bedrock on linux there are several ways to do it - just not with MultiMC as it involves obtaining the apk.  One such "example" is https://github.com/ChristopherHX/linux-packaging-scripts/releases/tag/appimage

All in all this is not a MultiMC issue and a literal 5 second google search would have answered your issue.

Invalid issue.

**Comment by AverageComet250** [comment]
To play bedrock on Linux you could also just use blue stacks and play pocket edition.

PS4, Xbox 1, switch, Mobile and windows 10 are the bedrock games. These have cross platform play and don't require servers for multiplayer.

PS3, Xbox 360, Wii U and 3ds all have legacy edition Minecraft. This version stopped being updated after 1.13 in favour of bedrock edition. It doesn't have cross platform play and doesn't require servers for multiplayer either.

Finally, you have the java edition of Minecraft. The OG version that was originally called cave game. This version is kinda cross-platform and servers are the only way to play with friends on this version. It's pc only, coded in java and runs on Linux, windows and MacOS (sorry SteamOS, you aren't destined for greatness). THIS IS THE VERSION THAT MULTIMC SUPPORTS. All the other Minecraft versions don't use launchers and don't have proper mod capabilities, however java edition does use a launcher, meaning that you can play on any version (not just the latest) and use mods, as it openly supports them.

That took me ages to type.

**Comment by kb-1000** [comment]
> To play bedrock on Linux you could also just use blue stacks and play pocket edition.

No. BlueStacks is a Windows/Mac program, while the above mentioned program is for Linux. Please validate your information before posting.
However: I see no reason why MultiMC would be needed for Bedrock edition, so that doesn't change that this issue is invalid.

**Comment by Forkk** [comment]
MultiMC is a launcher for Java Edition only, and will not support bedrock. Support for Microsoft accounts is planned.

**Comment by AureliusGemini** [comment]
> MultiMC is a launcher for Java Edition only, and will not support bedrock. Support for Microsoft accounts is planned.

why cant MultiMC also launch bedrock? 
i saw FoxyNoTail's MCBE Version Switcher. he said it was downloading from the Mojang servers? if i remember correctly (i may have the wrong quote, cuz based on memory)
