### ISSUE TITLE
我的帳號登不進去multiMC

### ISSUE THREAD

**Issue by SOS121HAHA** [MultiMC/MultiMC5#3640]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by ifurther** [comment]
可能需要再寫詳細一點，只有寫標題可能沒人可以幫你

**Comment by jotoho** [comment]
This issuetracker is english-only.

Invalid

**Comment by Forkk** [comment]
As stated above, please use english when reporting issues on here.
