### ISSUE TITLE
False reporting of session crashing when closing instance normally.

### ISSUE THREAD

**Issue by DragonMeme** [MultiMC/MultiMC5#3643]
System Information
-----------------------------
MultiMC version: 0.6.11-1344

Operating System: Ubuntu 20.04

Summary of the issue or suggestion:
----------------------------------------------
Reports as crashed when I click `Quit Game` or the close button on the window.

What should happen:
------------------------------
Should not report session as crashed under these 2 conditions.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch any minecraft instance (normal or offline).

2. Press `Quit Game` or close the window.

3. See selected instance with the [X] on sessions.

Suspected cause:
---------------------------
While unsure, I suspect that the MultiMC reads only the exitcode to determine if session has crashed or not.

Logs/Screenshots:
----------------------------
```
pure virtual method called
terminate called without an active exception
Process crashed with exitcode 6.
```
^ Common end of logs when performing the actions of closing the window.

Additional Info:
---------------------------
Tested with following instances:
* 1.8.9 Forge
* 1.12.2 Forge
* 1.16.5 Fabric
* 1.16.5 Vanilla

**Comment by peterix** [comment]
Well, guess what? It crashed. It's true. And fixing it is not our problem.

**Comment by peterix** [comment]
I suspect you are using some Java build that's simply broken

**Comment by spannerman79** [comment]
@DragonMeme when you filled out the issue report there was a section to include a paste.ee link not a snippet of an exit code that actually means nothing as its a Java exit code and those are just as useful as tits are on a bull.

https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by DragonMeme** [comment]
Updated to include the logs of me just starting instances and then closing them via `Quit Game` just in case.
