### ISSUE TITLE
Able to install Modpacks straight from the browser

### ISSUE THREAD

**Issue by ianwijma** [MultiMC/MultiMC5#3647]
System Information
-----------------------------
**MultiMC version:**
Does not apply

**Operating System:**
Any

Summary of the issue or suggestion:
----------------------------------------------
I think it would be really cool to have a browser extension for either Chrome or Firefox, which adds a button to quickly install a modpack into your MultiMC client.

What should happen:
------------------------------
Several things need to be in place before this can be done:
- Support from MultiMC's client to open and install modpacks using a url or something: `multimc://curseforge/<modpackid>/<version>
- A browser extension which adds the button with the link

In the end the browser extension should also be published to the different extension stores (Chrome, Firefox and Edge)

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
Does not apply

Suspected cause:
---------------------------
Does not apply

Logs/Screenshots:
----------------------------
![image](https://user-images.githubusercontent.com/17692119/110388332-04a19180-80b7-11eb-8881-387970164170.png)

Additional Info:
---------------------------
I don't know any C / C++, so I can not help out there.
I do have some knowledge of working with Browser Extensions, so I can help out there.

Let me know if there is any interest into this feature and if there is any help needed with anything.

**Comment by peterix** [comment]
Not with the current design of MultiMC and with how limited this is in all three operating systems.

**Comment by peterix** [comment]
And to be clear: I'm not dismissing the idea.

It's just not technically feasible to do with how things work right now. URL handlers require more system integration than a portable application should ever do. MultiMC 5 is a portable application.

**Comment by ianwijma** [comment]
> And to be clear: I'm not dismissing the idea.
> 
> It's just not technically feasible to do with how things work right now. URL handlers require more system integration than a portable application should ever do. MultiMC 5 is a portable application.

Alrighty, I was unaware that MultiMC was portable. Then having URL handlers makes no sense indeed.

Thanks for your time.
