### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by kakakakuts** [MultiMC/MultiMC5#3654]
System Information
-----------------------------
MultiMC version: Multimc 5

Operating System: Windows 10 20H2

Summary of the issue or suggestion:
----------------------------------------------
game crashes at any random point + lag spikes Error Code: 

What should happen:
------------------------------
Game should run normaly

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Close discord

2. Restart minecraft

3.

Suspected cause:
---------------------------
https://paste.ee/p/8wN4R

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
I refractions mod folder v4 maybe that causes the problem?

**Comment by kb-1000** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's discord.
