### ISSUE TITLE
Will MultiMC support Microsoft accounts ?

### ISSUE THREAD

**Issue by chris000000** [MultiMC/MultiMC5#3656]
Just bought another copy of MC but can't use with MultiMC as it has a Microsoft account ; your pinned issue title was recently changed to "Microsoft Accounts are not supported", are there still plans to support login with MS accounts ?

**Comment by phit** [comment]
please read the actual issue https://github.com/MultiMC/MultiMC5/issues/3392#issuecomment-713796443 or the blog post on the website https://multimc.org/posts/microsoft-accounts.html
