### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by kakakakuts** [MultiMC/MultiMC5#3658]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System:
Windows 10 20H2
Summary of the issue or suggestion:
----------------------------------------------
Game crashes about 4h of gaming. error code -805306369

What should happen:
------------------------------
Game should run correctly without any crashes.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. None

2. None

3. None

Suspected cause:
---------------------------
I don't know

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

https://paste.ee/p/8wN4R

Additional Info:
---------------------------

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
