### ISSUE TITLE
MultiMc instantly crashes, without even opening Minecraft, idk if it's mod incompatibilities or MultiMc itself.

### ISSUE THREAD

**Issue by ZeGamingCuber** [MultiMC/MultiMC5#3660]
System Information
-----------------------------
MultiMC version: 

Operating System: Windows 10

Summary of the issue or suggestion: 
----------------------------------------------
MultiMc instantly crashes when starting game

What should happen: 
------------------------------
Minecraft launching

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Make a modpack

2. Attempt to launch it

Suspected cause:
---------------------------
Not enough ram? Incompatible mods?

Logs/Screenshots:
----------------------------
https://paste.ee/p/Ymncf

**Comment by jamierocks** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by Janrupf** [comment]
You are using Java 11. You'll need to use Java 8 in order to be able to use forge.

**Comment by ZeGamingCuber** [comment]
> You are using Java 11. You'll need to use Java 8 in order to be able to use forge.

how do I download java 8 again?

**Comment by AverageComet250** [comment]
[](java.com) @ZeGamingCuber

**Comment by spannerman79** [comment]
> how do I download java 8 again?

Please follow https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java @ZeGamingCuber
