### ISSUE TITLE
MultiMC crashes when closing "Edit Instance" dialog

### ISSUE THREAD

**Issue by schaerfo** [MultiMC/MultiMC5#3661]
System Information
-----------------------------
MultiMC version: develop (commit af5b1beb), 0.6.11

Operating System: Debian 10, GCC 8.3, Qt 5.11.3

Summary of the issue or suggestion:
----------------------------------------------
When closing the "Edit Instance" dialog, MultiMC crashes with a segmentation fault.

What should happen:
------------------------------
The dialog should be closed and focus should return to the main window.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Start MultiMC
2. Add new instance
3. Click "Edit Instance"
4. Close dialog by clicking the X button in the window decoration or the "Close" button

Suspected cause:
---------------------------
Something goes wrong with memory management

Logs/Screenshots:
----------------------------
GDB log (including launcher log and stack trace): https://gist.github.com/schaerfo/6bfef3167a39f0b63c8fb65defc41863

**Comment by peterix** [comment]
This is a Qt bug and will not be fixed in MultiMC.

**Comment by peterix** [comment]
See: https://bugreports.qt.io/browse/QTBUG-68393
It's fixed in 5.12

Either update Qt (which likely means updating your system), or try to get the patch/fix backported to Debian's packages.
