### ISSUE TITLE
Snapshot 21w11a is missing from the version list

### ISSUE THREAD

**Issue by ThePotatoKing55** [MultiMC/MultiMC5#3662]
System Information
-----------------------------
MultiMC version: 0.6.12-develop 1459

Operating System: macOS Big Sur 11.3 (running on M1 through Rosetta)

Summary of the issue:
----------------------------------------------
Yesterday's snapshot 21w11a is missing from the list of available Minecraft versions for download.

What should happen:
------------------------------
Snapshots normally appear a few minutes after release.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Edit Minecraft instance

2. Select "Change Version" for Minecraft

3. Notice the lack of "21w11a"s

Suspected cause:
---------------------------
Based on the logs alone, it seems like MultiMC gets the Minecraft version list from its own servers (at least, I saw it accessing the URL `https://meta.multimc.org/v1/net.minecraft/index.json`). I assume the process is automated to some degree, but desynced from Minecraft's actual updates for one reason or another.

Logs/Screenshots:
----------------------------
[MultiMC-0.log](https://pastebin.com/raw/4xYKdpYW)

<img width="748" alt="Screenshot" src="https://user-images.githubusercontent.com/18623872/111691228-1c39f200-87fc-11eb-870b-0a214281ded4.png">

Additional Info:
---------------------------
I think it would make more sense to use Mojang's own APIs so as to not fall behind. The default launcher gets its information from `https://launchermeta.mojang.com/mc/game/version_manifest.json`. This file could, in theory, be downloaded and interpreted by MultiMC automatically. Or maybe you're already doing that on the server side at multimc.org and the cause is something else entirely. I'm not too familiar with the inner workings of it.

In the meantime I just switched out Minecraft for a custom .jar file.

**Comment by peterix** [comment]
Fixed.

**Comment by phit** [comment]
To add, MultiMC uses its own metadata as a "shock absorber" so stuff doesn't randomly break when vanilla or other meta like Forge changes something. In this case with 21w11a the addition of specific Java versions for a game version. Using our own meta guarantees a certain degree of stability so this will never be removed. And yes it's fully automated, here is the fix in question https://github.com/MultiMC/meta/commit/97d3da8a2514993bf18755d8bc48c1e54c40cb3e for now MultiMC will ignore the new data.
