### ISSUE TITLE
Deobfuscates stracktrace when game crashed

### ISSUE THREAD

**Issue by XakepSDK** [MultiMC/MultiMC5#3663]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: Arch Linux

Summary of the issue or suggestion:
----------------------------------------------
Deobfuscate stacktrace when game crashes

What should happen:
------------------------------
Log viewer deobfuscates stracktrace automatically when game crashes

**Comment by kb-1000** [comment]
There are mods for this, and that cannot be reliably done on text files (as subclass relations are not known).
In addition to that, it would not be clear what mappings to use.
I personally do not think this is a good idea, either.

**Comment by Janrupf** [comment]
More or less impossible to implement. MultiMC would have to parse mappings and know about the game - which it does not.
No way this is going to be implemented.

**Comment by XakepSDK** [comment]
Minecraft includes proguard mappings since 1.14.4 and proguard has a tool to remap stacktraces with given mappings

**Comment by spannerman79** [comment]
> Minecraft includes proguard mappings since 1.14.4 and proguard has a tool to remap stacktraces with given mappings
> Maybe it's possible to use it as an optional feature?

@XakepSDK those mappings are still a possible legal poison pill.

One (of **many**) such write up's on this - http://cpw.github.io/MinecraftMappingData.html#update-august-2020

Until those mappings are released under some form of better licence other then All rights Reserved (eg GPL or CC-BY-SA) then no, poison pill.

**Comment by phit** [comment]
@spannerman79 that is super outdated, Forge actually offers those mappings now to be used when modding https://forums.minecraftforge.net/topic/98980-forge-361-minecraft-1165/

**Comment by spannerman79** [comment]
> (c) 2020 Microsoft Corporation. These mappings are provided "as-is" and you bear the risk of using them. You may copy and use the mappings for development purposes, **but you may not redistribute the mappings complete and unmodified**. Microsoft makes no warranties, express or implied, with respect to the mappings provided here. Use and modification of this document or the source code (in any form) of Minecraft: Java Edition is governed by the Minecraft End User License

Looks like a legal poison pill to me.

**Comment by kb-1000** [comment]
It does. You're not allowed to put names even only inspired from them in Yarn or even MCP. (same applies to MCP)
This does not feel like an option at all.

**Comment by peterix** [comment]
`you may not redistribute the mappings complete and unmodified` ... So what if you change one letter?

**Comment by peterix** [comment]
Because by basic logic, they can be complete and modified.
