### ISSUE TITLE
Modded games become vanilla

### ISSUE THREAD

**Issue by Mycario** [MultiMC/MultiMC5#3664]
### Description of bug

When I launch a modded launcher it is not modded but vanilla (fabric mods and yes i have fabric api) I have dragged the mods into mod's folder in the instance and it still does not work.

### Steps to reproduce

i drag the mods in the mod folder i launch no mods

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ImperatorStorm** [comment]
did you install the fabric loader?

**Comment by issac4892** [comment]
![image](https://user-images.githubusercontent.com/56223465/111734968-77341d80-88be-11eb-9a6c-39812a0efc66.png)
it's korean, but it'll be at the same place (Install Fabric Loader)/(패브릭 설치)

**Comment by Mycario** [comment]
i do try but as it is origins mod it does not work no matter what version
and i have fabric api

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
