### ISSUE TITLE
Synchronize settings/worlds/etc. between instances

### ISSUE THREAD

**Issue by sartamo** [MultiMC/MultiMC5#3665]
### Role

I have multiple instances.

### Suggestion

I want that I can have the same settings/worlds/servers/etc in every instance.

### Benefit

If you change settings or play worlds, you would be able to see the changes in an other instance.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by spannerman79** [comment]
Duplicate of https://github.com/MultiMC/MultiMC5/issues/42, https://github.com/MultiMC/MultiMC5/issues/3093,https://github.com/MultiMC/MultiMC5/issues/3256 ... god the list is endless.


What you are suggesting is in fact **breaking** core function of MultiMC - **to keep instances apart from each other**.
