### ISSUE TITLE
1.16.1 crash

### ISSUE THREAD

**Issue by a-a3458** [MultiMC/MultiMC5#3671]
### Operating System

Windows

### Description of bug

1.16.1 crashes even if you have optifine but 1.16.5 runs fine here is my multimc log link https://paste.ee/p/L21bs

### Steps to reproduce

just add an instance of 1.16.1 and it crashes

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by AverageComet250** [comment]
Are you launching in offline mod without launching normally first?

It says missing library so it's probably just a mistype somewhere in the run instructions.

**Comment by spannerman79** [comment]
Unable to reproduce - https://paste.ee/p/whrui

Runs without an issue.  Have no idea what you are doing @a-a3458

**Comment by Skiuileuf** [comment]
Getting the same error here, running Windows 10 20H2. Made an instance containing fabric version 0.11.3 on minecraft 1.16.4. 
Log with "-Dorg.lwjgl.util.Debug=true -Dorg.lwjgl.util.DebugLoader=true" added to the java arguments : https://paste.ee/p/6yae1

**Comment by spannerman79** [comment]
Create a new issue @Skiuileuf as you are running a different mod loader then the OP.

**Comment by phit** [comment]
they are both on lwjgl-glfw 3.2.2

**Comment by phit** [comment]
try deleting MultiMCFolder\libraries\org\lwjgl\lwjgl-glfw\3.2.2

**Comment by spannerman79** [comment]
@a-a3458 & @Skiuileuf : How **exactly** did you add Optifine? Exact steps to reproduce please.

Because I cannot reproduce - https://paste.ee/p/K2SiH

**Comment by Skiuileuf** [comment]
@spannerman79 My instance does not contain optifine. The only mods in it are Fabric API, Meteor Client and Multiconnect, but all those are disabled, so the game should load normally. Judging by your file paths, you seem to be using a distribution of linux. I think this issue is windows-only, considering that it seems the problem is a missing DLL.

@phit deleted that folder, it appeared back when I tried launching again. Game crashed for the same reason (glfw.dll not found)

Tried launching some of my other instances. The only ones that crash seem to be the ones on 1.16 that also contain fabric.

**Comment by phit** [comment]
it should reappear, thats fine. I still can't reproduce this on Windows 10 myself and I completely matched your setup in terms of Minecraft, libraries and Java version

**Comment by spannerman79** [comment]
@Skiuileuf for the sake of reproduction ability I suggest the following;

To exclude a borked Java install - Follow and use https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs as you would be using the same java version as the Vanilla launcher and also rule out a borked Java install.

If MultiMC still fails after that I suggest trying to reproduce the same issue with the Vanilla Launcher.  

If it still fails after using the Vanilla Launcher - then its system related and outside the scope of this issue tracker (ie borked gpu drivers, hardware about to fail, etc)

**Comment by Skiuileuf** [comment]
Did the first thing, getting the same error.

Tried reproducing in the vanilla launcher - it launched successfully (both with and without mods)

**Comment by phit** [comment]
do you have any third party antivirus software? try disabling that

**Comment by Skiuileuf** [comment]
No. I do not have any antivirus software (other than Windows Defender)

I managed to fix the problem by going to MultiMC Settings > Java and unchecking "Use system installation of GLFW"

**Comment by spannerman79** [comment]
> I managed to fix the problem by going to MultiMC Settings > Java and unchecking "Use system installation of GLFW"

That option is default **unchecked**.

Unless you are one of those rare edge cases (which I've only seen about three cases for) you don't enable that.


------

TODO:

Update wiki re: native work arounds
Suggested UI Change: BIG RED WARNING - DO NOT USE UNLESS YOU KNOW WHAT YOU ARE DOING

**Comment by spannerman79** [comment]
@a-a3458 - do you have either/both options enabled under Settings -> Minecraft -> Native library workarounds?

**Comment by peterix** [comment]
Maybe the better option would be to load the native library and see if it exists.

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help. Some logging to spot this issue was added with https://github.com/MultiMC/MultiMC5/pull/3680
