### ISSUE TITLE
Can not launch mod packs through MultiMC.

### ISSUE THREAD

**Issue by idioticbanana27** [MultiMC/MultiMC5#3673]
This is my log when launching a Hevens of Sorcery instance. I also get a similar error when I launch any other mod pack but not vanilla.

MultiMC version: 0.6.12-develop-1525

Minecraft folder is:
C:/Users/Josh/Desktop/MultiMC/instances/Hevens of Sorcery/minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 11.0.9, using 64-bit architecture, from Oracle Corporation.

Main Class:
net.minecraft.launchwrapper.Launch

Native path:
C:/Users/Josh/Desktop/MultiMC/instances/Hevens of Sorcery/natives

Libraries:
C:/Users/Josh/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
C:/Users/Josh/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
C:/Users/Josh/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
C:/Users/Josh/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
C:/Users/Josh/Desktop/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
C:/Users/Josh/Desktop/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
C:/Users/Josh/Desktop/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
C:/Users/Josh/Desktop/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
C:/Users/Josh/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
C:/Users/Josh/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
C:/Users/Josh/Desktop/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
C:/Users/Josh/Desktop/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
C:/Users/Josh/Desktop/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
C:/Users/Josh/Desktop/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
C:/Users/Josh/Desktop/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
C:/Users/Josh/Desktop/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
C:/Users/Josh/Desktop/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
C:/Users/Josh/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
C:/Users/Josh/Desktop/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
C:/Users/Josh/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
C:/Users/Josh/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
C:/Users/Josh/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
C:/Users/Josh/Desktop/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
C:/Users/Josh/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
C:/Users/Josh/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
C:/Users/Josh/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
C:/Users/Josh/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
C:/Users/Josh/Desktop/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
C:/Users/Josh/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
C:/Users/Josh/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
C:/Users/Josh/Desktop/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
C:/Users/Josh/Desktop/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854-universal.jar
C:/Users/Josh/Desktop/MultiMC/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
C:/Users/Josh/Desktop/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
C:/Users/Josh/Desktop/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
C:/Users/Josh/Desktop/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
C:/Users/Josh/Desktop/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
C:/Users/Josh/Desktop/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
C:/Users/Josh/Desktop/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
C:/Users/Josh/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
C:/Users/Josh/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
C:/Users/Josh/Desktop/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
C:/Users/Josh/Desktop/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
C:/Users/Josh/Desktop/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
C:/Users/Josh/Desktop/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
C:/Users/Josh/Desktop/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
C:/Users/Josh/Desktop/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
C:/Users/Josh/Desktop/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
C:/Users/Josh/Desktop/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
C:/Users/Josh/Desktop/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
C:/Users/Josh/Desktop/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
C:/Users/Josh/Desktop/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
C:/Users/Josh/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
C:/Users/Josh/Desktop/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
[📁] 1.12 (folder)
[✔️] aether-1.12.2-v1.5.2
[✔️] AkashicTome-1.2-12
[✔️] Animus-1.12-2.1.7
[✔️] AoV-1.12-0.11.7
[✔️] AppleSkin-mc1.12-1.0.14
[✔️] Arcane Essentials-1.0.0-alpha-6
[✔️] arcanearchives-0.2.0.25-mixins8
[✔️] arcaneworld-1.12.2-0.0.11
[✔️] architecturecraft-1.12-3.98
[✔️] ArtemisLib-1.12.2-v1.0.6
[✔️] Artifacts-1.12.2-1.2.2
[✔️] astralsorcery-1.12.2-1.10.27
[✔️] athenaeum-1.12.2-1.19.2
[✔️] AttributeFix-1.12.2-1.0.10
[✔️] AuraControl-1.12.2-1.0.2
[✔️] autonetworklib-1.12.2-1.0.38
[✔️] AutoRegLib-1.3-32
[✔️] base-1.12.2-3.13.0
[✔️] Baubles-1.12-1.5.2
[✔️] BetterAdvancements-1.12.2-0.1.0.77
[✔️] BetterBuildersWands-1.12.2-0.13.2.271+5997513
[✔️] BetterFps-1.4.8
[✔️] bewitchment-1.12.2-0.0.22.41
[✔️] BiomeTweaker-1.12.2-3.2.368
[✔️] blockcraftery-1.12.2-1.3.1
[✔️] BloodMagic-1.12.2-2.4.3-105
[✔️] blue_skies-1.12.2-v1.1.3
[✔️] BNBGamingCore-1.12.2-0.12.0
[✔️] BNBGamingLib-1.12.2-2.17.6
[✔️] Bookshelf-1.12.2-2.3.590
[✔️] Botania r1.10-363
[✔️] botaniatweaks-1.9.0
[✔️] buildersbag-1.12.2-1.3.0.22
[✔️] BuildingGadgets-2.8.4
[✔️] Cathedral-1.12.2-1.9.9
[✔️] ChestTransporter-1.12.2-2.8.8
[✔️] Chisel-MC1.12.2-1.0.2.45
[✔️] chiselsandbits-14.33
[✔️] colytra-1.12.2-1.2.0.4
[✔️] comforts-1.12.2-1.4.1.3
[✔️] ContentTweaker-1.12.2-4.9.1
[✔️] Controlling-3.0.10
[✔️] CosmeticArmorReworked-1.12.2-v5a
[✔️] craftingstation-0.1.7c
[✔️] CraftingTweaks_1.12.2-8.1.9
[✔️] CraftTweaker2-1.12-4.1.20.586
[✔️] CreativeCore_v1.10.28_mc1.12.2
[✔️] CTM-MC1.12.2-1.0.2.31
[✔️] Cuisine-0.5.22-build929
[✔️] CustomMainMenu-MC1.12.2-2.0.9.1
[✔️] diethopper-1.1
[✔️] DimensionalDoors-3.0.9-287
[✔️] divinefavor-1.0.754
[✔️] dropt-1.12.2-1.18.0
[✔️] DynamicTrees-1.12.2-0.9.15
[✔️] DynamicTreesNaturesAura-1.12.2-1.0.2
[✔️] dynamictreesQuark-1.12.2-1.0.4
[✔️] dynamicTreesRoots-0.2.1
[✔️] DynamicTreesTC-1.12.2-1.4.2
[✔️] dynamictreesTheAether-1.12.2-1.0.9
[✔️] Earthworks-1.12-1.3.6
[✔️] ElectroblobsWizardry-4.2.11-MC1.12.2
[✔️] EmbersRekindled-1.14-hotfix
[✔️] EnchantmentDescriptions-1.12.2-1.1.15
[✔️] EquipmentTooltips-1.12.2-1.0.3-4
[✔️] extraalchemy-forge-1.12-build11-0.5.4
[✔️] ExtraBitManipulation-1.12.2-3.4.1
[✔️] ExtraSpells-1.12.2-1.1.4
[✔️] FancySpawnEggs MC1.12.2 v1.0
[✔️] FastWorkbench-1.12.2-1.7.3
[✔️] foamfix-0.10.10-1.12.2
[✔️] Forgelin-1.8.4
[✔️] ForgivingVoid_1.12.2-1.1.0
[✔️] FTBBackups-1.1.0.1
[✔️] FTBLib-5.4.7.2
[✔️] FTBUtilities-5.4.1.130
[✔️] GameStages-1.12.2-2.0.123
[✔️] Guide-API-1.12-2.1.8-63
[✔️] Hwyla-1.8.26-B41_1.12.2
[✔️] incontrol-1.12-3.9.17
[✔️] incorporeal-1.2.5
[✔️] Inspirations-1.12.2-0.2.9
[✔️] inventorysorter-1.12.2-1.13.3+57
[✔️] itemzoom_1.12.2-1.11
[✔️] jei_1.12.2-4.16.1.301
[✔️] journeymap-1.12.2-5.7.1
[✔️] JustEnoughIDs-1.0.3-55
[✔️] JustEnoughResources-1.12.2-0.9.2.60
[✔️] Kathairis-1.12.2-1.6.0-beta
[✔️] Kiwi-1.12.2-0.5.3.32
[✔️] KleeSlabs_1.12.2-5.4.12
[✔️] lemonlib-1.12.2-1.3.0
[✔️] librarianlib-1.12.2-4.22
[✔️] librikka-1.0.0
[✔️] LittleTiles_v1.5.0-pre199_64_mc1.12.2
[✔️] llibrary-1.7.19-1.12.2
[✔️] Login_Shield-1.12.2-6-g5654706
[✔️] LootTweaker-0.2.0+MC1.12.2
[✔️] lost-aether-content-1.12.2-1.0.2
[✔️] LunatriusCore-1.12.2-1.2.0.42-universal
[✔️] magicalsculpture-1.0.0
[✔️] Mantle-1.12-1.3.3.55
[✔️] maxpotidext-1.0.3
[✔️] mcjtylib-1.12-3.5.4
[✔️] MCMultiPart-2.5.3
[✔️] meecreeps-1.12-1.3.1
[📁] memory_repo (folder)
[✔️] MetalChests-v6.1.0+mc1.12.2
[✔️] minerva-library-1.0.13
[✔️] MistyWorld-1.12.2-1.2.4.15
[✔️] MobStages-1.12.2-2.0.8
[✔️] modtweaker-4.0.18
[✔️] moreoverlays-1.15.1-mc1.12.2
[✔️] MoreTweaker-1.0.16
[✔️] MouseTweaks-2.10-mc1.12.2
[✔️] MTLib-3.0.6
[✔️] mystgears-1.1.5
[✔️] Mystical Mechanics-0.18
[✔️] mysticallib-1.12.2-1.9.0
[✔️] mysticalworld-1.12.2-1.9.2
[✔️] NaturalPledge-r3.1.2
[✔️] NaturesAura-18.1
[✔️] Neat 1.4-17
[✔️] Patchouli-1.0-20
[✔️] phosphor-forge-mc1.12.2-0.2.7-universal
[✔️] Placebo-1.12.2-1.6.0
[✔️] platforms-1.12.0-1.4.6
[✔️] PotionCore-1.9_for_1.12.2
[✔️] QualityTools-1.0.7_for_1.12.2
[✔️] Quark-r1.6-179
[✔️] randompatches-1.12.2-1.22.1.7
[✔️] randomportals-1.12.2-1.8.2.3
[✔️] rats-3.2.14-1.12.2
[✔️] RealisticItemDrops-1.2.14
[✔️] reauth-3.6.0
[✔️] ResourceReloader-1.0.2.5
[✔️] Roots-1.12.2-3.0.32
[✔️] Rustic Thaumaturgy-4.4a
[✔️] rustic-1.1.6
[✔️] rusticwitcraft-1.0.2
[✔️] Scavenge V1.12-1.8.3.2
[✔️] shetiphiancore-1.12.0-3.5.9
[✔️] SimilsaxTranstructors-1.12-1.0.22
[✔️] Sledgehammer-1.12.2-2.0.8
[✔️] Soot-1.10-hotfix
[✔️] SoundFilters-0.12.1_for_1.12
[✔️] spawntabletweaker-1.0
[✔️] StackUp-0.2.5
[✔️] SuperiorShields-1.12.2-1.0.2
[✔️] supersoundmuffler-revived_1.12.2_1.0.2.10
[✔️] TamModized-1.12.2-0.15.6
[✔️] TBone-v1.6.8+mc1.12.2
[✔️] tellme-1.12.2-0.7.0-dev.20200919.184303
[✔️] TexFix V-1.12-4.0
[✔️] Thaumcraft-1.12.2-6.1.BETA26
[✔️] ThaumicAugmentation-1.12.2-2.0.8
[✔️] ThaumicInventoryScanning_1.12.2-2.0.10
[✔️] ThaumicJEI-1.12.2-1.6.0-27
[✔️] thaumicperiphery-0.3.1
[✔️] TheBetweenlands-3.6.2-universal
[✔️] Tips-1.12.2-1.0.9
[✔️] TipTheScales-1.12.2-1.0.4
[✔️] Toast Control-1.12.2-1.8.1
[✔️] togetherforever-1.12.2-1.0.12-22
[✔️] tombstone-4.0.0-1.12.2
[✔️] Triumph-1.12.2-3.19.2
[✔️] vaultopic-2.2
[✔️] voidislandcontrol-1.5.3
[✔️] WailaHarvestability-mc1.12-1.1.12
[✔️] wings-1.1.6-1.12.2
[✔️] wizardry-0.11.1

Params:
--username  --version MultiMC5 --gameDir C:/Users/Josh/Desktop/MultiMC/instances/Hevens of Sorcery/minecraft --assetsDir C:/Users/Josh/Desktop/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx4736m, -Duser.language=en]

Minecraft process ID: 5872

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke([NativeMethodAccessorImpl.java:62](https://NativeMethodAccessorImpl.java:62))

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke([DelegatingMethodAccessorImpl.java:43](https://DelegatingMethodAccessorImpl.java:43))

at java.base/java.lang.reflect.Method.invoke([Method.java:566](https://Method.java:566))

at org.multimc.onesix.OneSixLauncher.launchWithMainClass([OneSixLauncher.java:196](https://OneSixLauncher.java:196))

at org.multimc.onesix.OneSixLauncher.launch([OneSixLauncher.java:231](https://OneSixLauncher.java:231))

at org.multimc.EntryPoint.listen([EntryPoint.java:143](https://EntryPoint.java:143))

at org.multimc.EntryPoint.main([EntryPoint.java:34](https://EntryPoint.java:34))
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
at net.minecraft.launchwrapper.Launch.<init>([Launch.java:34](https://Launch.java:34))

at net.minecraft.launchwrapper.Launch.main([Launch.java:28](https://Launch.java:28))

... 8 more
Exiting with -1
Process exited with code -1.

**Comment by phit** [comment]
https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java

next time use the issue template
