### ISSUE TITLE
[1.12.2 Forge] InvocationTargetException on start.

### ISSUE THREAD

**Issue by andrew121410** [MultiMC/MultiMC5#3674]
### Operating System

Windows

### Description of bug

When starting 1.12.2 latest or recommended forge version it immediately crashes here's the log https://paste.ee/p/KzytS

### Steps to reproduce

1. Create a new instance of 1.12.2
2. Install forge by going to edit instance then version and hit the install forge button
3. then try to run the game and it just crashes

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
maybe follow what the template says and what you checked off, and use the search https://github.com/MultiMC/MultiMC5/issues?q=is%3Aissue+InvocationTargetException

https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java

**Comment by andrew121410** [comment]
My bad
