### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by PhantomFran** [MultiMC/MultiMC5#3675]
### Operating System

Windows

### Description of bug

I think it is a bug because it started when i updated multimc. when i start an instance, everything is normal but after a few minutes everything starts lagging alot while freezing and then unfreezing constantly, it has happened every time i open an instance please help!

### Steps to reproduce

I just started an instance and after a few minutes the game started lagging and freezing constantly.

### Suspected cause

I think it might have to do with the multimc update.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
