### ISSUE TITLE
Modded Crash 

### ISSUE THREAD

**Issue by itssofia13** [MultiMC/MultiMC5#3676]
Everytime I run this pack, Minecraft plays good for a couple minutes and then crash. 
heres the report: https://paste.ee/p/52ECW

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by AverageComet250** [comment]
@phit is that a reply that you've saved
