### ISSUE TITLE
Any 1.12 modpack crashes on launch, before opening the Minecraft window

### ISSUE THREAD

**Issue by OmegaX123** [MultiMC/MultiMC5#3679]
What: Any 1.12.2 modpack, whether newly installed or previously used, crashes when I try to launch the pack, crashes when I launch it, without even opening the Minecraft window.

Example crash log from the MultiMC console:
---------------------
MultiMC version: 0.6.12-1530

Minecraft folder is:
C:/Games/Minecraft/MultiMC/instances/Craft Die Repeat - Curse of Israphel/minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 15.0.2, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Games/Minecraft/MultiMC/instances/Craft Die Repeat - Curse of Israphel/natives

Libraries:
  C:/Games/Minecraft/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Games/Minecraft/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Games/Minecraft/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Games/Minecraft/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Games/Minecraft/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Games/Minecraft/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Games/Minecraft/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Games/Minecraft/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Games/Minecraft/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Games/Minecraft/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Games/Minecraft/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Games/Minecraft/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Games/Minecraft/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Games/Minecraft/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Games/Minecraft/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Games/Minecraft/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Games/Minecraft/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Games/Minecraft/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Games/Minecraft/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Games/Minecraft/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Games/Minecraft/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Games/Minecraft/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Games/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Games/Minecraft/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Games/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Games/Minecraft/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Games/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Games/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Games/Minecraft/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Games/Minecraft/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2855/forge-1.12.2-14.23.5.2855-universal.jar
  C:/Games/Minecraft/MultiMC/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
  C:/Games/Minecraft/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Games/Minecraft/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/Games/Minecraft/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Games/Minecraft/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Games/Minecraft/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Games/Minecraft/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Games/Minecraft/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  C:/Games/Minecraft/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  C:/Games/Minecraft/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Games/Minecraft/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Games/Minecraft/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Games/Minecraft/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Games/Minecraft/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Games/Minecraft/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Games/Minecraft/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Games/Minecraft/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Games/Minecraft/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Games/Minecraft/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Games/Minecraft/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Games/Minecraft/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [✔️] [___MixinCompat-0.8___]
  [✔️] 1.12.2-DynamicSwordSkills-6.0.1
  [✔️] 1.12.2-SwordSkillsApi-1.1.0
  [✔️] 1.3dgcd
  [✔️] 1.5dgpamp
  [✔️] absentbydesign-1.12.2-1.0.4
  [✔️] additional_lights-1.12.2-1.2.1.2-optional
  [✔️] AIReducer-1.12.2-0.2.1
  [✔️] anvilpatch-1.0.1
  [✔️] Apotheosis-1.12.2-1.12.5
  [✔️] AppleCore-mc1.12.2-3.4.0
  [✔️] AppleSkin-mc1.12-1.0.14
  [✔️] AquaAcrobatics-v1.3.5-1.12.2
  [✔️] Aquaculture-1.12.2-1.6.8
  [✔️] Attributes-1.0.1
  [✔️] AutoRegLib-1.3-32
  [✔️] bettercaves-1.12.2-2.0.4
  [✔️] BetterCombat-1.12.2-1.5.6
  [✔️] BetterFoliage-MC1.12-2.3.1
  [✔️] BetterMineshaftsForge-1.12.2-2.2
  [✔️] BetterPlacement-1.0.0-1
  [✔️] Biome_Bundle_O_Plenty-1.12.2_v1.0
  [✔️] BiomesOPlenty-1.12.2-7.0.1.2444-universal
  [✔️] Bountiful-2.2.2
  [✔️] Camels-1.12.2-1.0.1
  [✔️] carryon-1.12.2-1.12.3.15
  [✔️] Chameleon-1.12-4.1.3
  [✔️] Chisel-MC1.12.2-1.0.2.45
  [✔️] chococraft_1.12.2-0.9.9.0
  [✔️] Chocolate_Quest_Repoured-1.12.2-2.2.4B
  [✔️] Chunk Pregenerator-V1.12-2.4.1
  [✔️] ChunkAnimator-MC1.12-1.2
  [✔️] Clumps-3.1.2
  [✔️] collective-1.12.2-1.66
  [✔️] CompatSkills-1.12.2-1.17.0
  [✔️] Controlling-3.0.10
  [✔️] coroutil-1.12.1-1.2.37
  [✔️] CosmeticArmorReworked-1.12.2-v5a
  [✔️] Costumemes_1.12.2_2020-12-10
  [✔️] CraftableHorseArmour-1.3.0-1.12
  [✔️] CreativeCore_v1.10.45_mc1.12.2
  [✔️] creature_whisperer_1.0.2
  [✔️] CTM-MC1.12.2-1.0.2.31
  [✔️] CustomMainMenu-MC1.12.2-2.0.9.1
  [✔️] CustomMobSpawner-3.11.5
  [✔️] dailies-1.12.2-6
  [✔️] DamageTilt-1.12.2-0.1.0
  [✔️] davincisvessels-1.12-6.340-full
  [✔️] DeathQuotes-1.2.0-mc1.12-forge
  [✔️] DefaultOptions_1.12.2-9.2.8
  [✔️] disenchanter[1.12]1.7
  [✔️] DoomlikeDungeons-1.13.2-MC1.12.2
  [✔️] DrZharks MoCreatures Mod-12.0.5
  [✔️] DungeonsMod-1.12.2-1.0.6
  [✔️] dwmh-1.1.0
  [✔️] DynamicSurroundings-1.12.2-3.6.1.0
  [✔️] DynamicTrees-1.12.2-0.9.22
  [✔️] DynamicTreesBOP-1.12.2-1.4.4
  [✔️] DynamicTreesMysticalWorld-1.12.2-1.0.1
  [✔️] DynamicTreesQuark-1.12.2-1.0.6
  [✔️] easiercrafting-1.12-forge14.21.1.2387-1.2
  [✔️] elenaidodge-1.12.2-2.0.2
  [✔️] EnderZoo-1.12.1-1.4.0.49
  [✔️] Exotic Birds 1.12.2-3.2.0
  [✔️] fairylights-2.2.0-1.12.2
  [✔️] FamiliarFauna-1.12.2-1.0.11
  [✔️] FancyBlockParticles-1.12.x-2.4.1
  [✔️] Farseek-1.12-2.5.1
  [✔️] FastFurnace-1.12.2-1.3.1
  [✔️] FastLeafDecay-v14
  [✔️] FastWorkbench-1.12.2-1.7.3
  [✔️] Fish's Undead Rising-1.2.3
  [✔️] foamfix-0.10.11-1.12.2
  [✔️] Forgelin-1.8.4
  [✔️] FreeLook-1.2.2
  [✔️] FullscreenWindowed-1.12-1.6.0
  [✔️] future-mc-1.12.2-0.2.6.1
  [✔️] grapplemod-v11.1-1.12.2
  [✔️] handoveryouritems_1.12.2-1.0
  [✔️] healthhungertweaks-1.12-2.1.1
  [✔️] Hwyla-1.8.26-B41_1.12.2
  [✔️] iceandfire-1.9.1-1.12.2
  [✔️] iChunUtil-1.12.2-7.2.2
  [✔️] InventoryTweaks-1.63
  [✔️] ironchest-1.12.2-7.0.72.847
  [✔️] itlt-1.12.2-1.0.3
  [✔️] IvToolkit-1.3.3-1.12
  [✔️] jei_1.12.2-4.16.1.301
  [✔️] JustEnoughResources-1.12.2-0.9.2.60
  [✔️] KeepingInventory-1.12.2-2.4
  [✔️] lightorbs-Alpha 0.3.1
  [✔️] lilliputian-1.0
  [✔️] llibrary-1.7.20-1.12.2
  [✔️] MagmaMonsters-0.3.0
  [✔️] mcw-bridges-1.0.4-mc1.12.2
  [✔️] MedievalCraft-1.12.2-1.5.4
  [✔️] middletorch-6.0.1
  [✔️] MinecraftEarthModOldEdition-1.1.6.2
  [✔️] MineMenu-1.12.2-1.6.11-universal
  [✔️] MixinBootstrap-1.0.5
  [✔️] MobDismemberment-1.12.2-7.0.0
  [✔️] MoBends_1.12.2-1.0.0-beta-20.06.20
  [✔️] mobsunscreen-1.12.2-2.1.3
  [✔️] morepaintings-paintings-1.12.2-5.0.1.2
  [✔️] Morpheus-1.12.2-3.5.106
  [✔️] MouseTweaks-2.10-mc1.12.2
  [✔️] movingworld-1.12-6.353-full
  [✔️] mowziesmobs-1.5.8
  [✔️] MultiMine-1.12.2
  [✔️] multimob-1.0.5
  [✔️] MutantBeasts-1.12.2-1.0.1
  [✔️] mysticallib-1.12.2-1.9.0
  [✔️] mysticalworld-1.12.2-1.9.2
  [✔️] NamePain-1.3.1 Forge-1.12.x
  [✔️] Neat 1.4-17
  [✔️] NewWalls-1.12.2-1.0.0
  [✔️] NoCubes-1.12.2-0.4.0-pre2
  [✔️] NotEnoughScaffold-1.12.2-1.10
  [✔️] OpenGlider-1.12.1-1.1.0
  [✔️] OpenTerrainGenerator-1.12.2-v9.3
  [✔️] OreLib-1.12.2-3.6.0.1
  [✔️] overloadedarmorbar-1.0.4g
  [✔️] OverpoweredMending-1.12.2-1.0.1+8
  [✔️] PassableLeaves-1.12.2-2.0.0
  [✔️] Patchouli-1.0-23.6
  [✔️] pathundergates-1.12.2-2.2.0-release
  [✔️] phosphor-forge-mc1.12.2-0.2.7-universal
  [✔️] placeableitems-3.3
  [✔️] Placebo-1.12.2-1.6.0
  [✔️] PlayerRevive_v1.2.40_mc1.12.2
  [✔️] primitivemobs-1.2.3a
  [✔️] ProjectE-1.12.2-PE1.4.1
  [✔️] ProjectVibrantJourneys-1.12.2-1.6.4
  [✔️] Quark-r1.6-179
  [✔️] RealisticItemDrops-1.2.14
  [✔️] RealisticItemDropsAddon-0.1.1
  [✔️] RecurrentComplex-1.4.8.2
  [✔️] Reskillable-1.12.2-1.13.0
  [✔️] ResourceLoader-MC1.12.1-1.5.3
  [✔️] Rex's-Additional-Structures-1.12.x-(v.2.3.1)
  [✔️] RoguelikeDungeons-1.12.2-1.8.0
  [✔️] roost-1.12.2-2.0.10
  [✔️] Ruins-1.12.2
  [✔️] ScalingHealth-1.12.2-1.3.42+147
  [✔️] ShoulderSurfing-1.12.2-1.15.1
  [✔️] SilentLib-1.12.2-3.0.14+168
  [✔️] sit-1.12.2-v1.3
  [✔️] SlimyBoyos-1.0.0
  [✔️] SnowRealMagic-0.3.3
  [✔️] spartanfire-0.08
  [✔️] SpartanShields-1.12.2-1.5.4
  [✔️] SpartanWeaponry-1.12.2-beta-1.3.8
  [✔️] starterkit_1.12.2-2.2
  [✔️] StepUp-1.0.2-mc1.10-1.12
  [✔️] StorageDrawers-1.12.2-5.4.2
  [✔️] Surge-1.12.2-2.0.77
  [✔️] TexFix V-1.12-4.0
  [✔️] TheCurseOfIsraphel-1.12.2-1.0
  [✔️] ToolBelt-1.12.2-1.9.13
  [✔️] toughnessbar-2.4
  [✔️] TravelersBackpack-1.12.2-1.0.35
  [✔️] tumbleweed-1.12-0.4.7
  [✔️] VanillaFix-1.0.10-150
  [✔️] VeinMiner-1.12-0.38.2.647+b31535a
  [✔️] villagespawnpoint_1.12.2-1.4
  [✔️] Voice Chat Reloaded-1.2.4
  [✔️] walljump-1.12.2-1.3.2
  [✔️] Waystones_1.12.2-4.1.0
  [✔️] wolfarmor-1.12.2-3.7.5-universal-signed
  [✔️] Xaeros_Minimap_21.4.0.1_Forge_1.12
  [✔️] XaerosWorldMap_1.12.0.2_Forge_1.12
  [✔️] zombieawareness-1.12.1-1.11.16

Params:
  --username  --version MultiMC5 --gameDir C:/Games/Minecraft/MultiMC/instances/Craft Die Repeat - Curse of Israphel/minecraft --assetsDir C:/Games/Minecraft/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx12884m, -Duser.language=en]

Minecraft process ID: 7644

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1.
Clipboard copy at: 23 Mar 2021 22:57:48 -0300

**Comment by Janrupf** [comment]
You need to use Java 8. See here: https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java

**Comment by OmegaX123** [comment]
I haven't changed the Java version I use. I've been using the same settings for as long as I've been using MultiMC.

**Comment by Janrupf** [comment]
Well, you are certainly using Java 15 right now. You need java 8, regardless of whether you manually changed something or not.

**Comment by OmegaX123** [comment]
Java 8 is what I've been using all along, which means that MultiMC changed something, or my computer decided to uninstall my Java 8 install (which was separate from my main install, so it's not just that it updated) in the last day or two.

**Comment by OmegaX123** [comment]
Your advice worked, though I'm still in the dark about how my Java settings in MultiMC got changed, because the previous Java 8 install was definitely still installed, and as I said, I never changed my settings, which means that MultiMC updating wiped my Java settings, as that was the only thing that has changed (aside from installing more modpacks) since the last time it worked before this.
