### ISSUE TITLE
Modpacks crash on Startup

### ISSUE THREAD

**Issue by DeathDreamZz** [MultiMC/MultiMC5#3683]
### Operating System

Linux

### Description of bug

Modpacks Crash on Startup (Stage 3)
Heres my log https://paste.ee/p/eYPX4

### Steps to reproduce

Start Stoneblock 2
Observe

### Suspected cause

i thought it may be the Nvidia Driver Arch uses but idk

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
