### ISSUE TITLE
ошибка при входе в MultiMC 5 

### ISSUE THREAD

**Issue by Gomehg** [MultiMC/MultiMC5#3689]
### Operating System

Windows

### Description of bug

здравствуй выдаёт ошибку Invalid credentials. Invalid username or password. что делать лицензия майнкрафт есть .
версия 0.6.12-1530

### Steps to reproduce

1. Захожу в профили.
2. Нажимаю кнопку добавить аккаунт.
3. Завожу данные и высвечивается ошибка.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
Hi. Thanks for reporting a potential bug. Unfortunately we can't process reports unless they're written in English.
