### ISSUE TITLE
Removing forge causes an error; reinstalling it hides versions temporary

### ISSUE THREAD

**Issue by pojx** [MultiMC/MultiMC5#369]
I tried to remove forge to install a newer version and got this error.
The instance used was a instance created before 0.4.
![multimc1](https://cloud.githubusercontent.com/assets/6299175/3574345/163f6dd8-0b7d-11e4-9071-f76746777f2e.PNG)

After letting MutliMC crash i tried to reinstall forge. Installing worked but after selecting the actual version and letting MultiMC do its thing all "jar-mods / versions / however it is called" disappeared.
![multimc2](https://cloud.githubusercontent.com/assets/6299175/3574373/5ea2fc70-0b7d-11e4-9d4b-342c247e1f3d.PNG)

**Comment by peterix** [comment]
Whatever this was, I seriously doubt it's still there. The code in question has been overhauled a few times since.
