### ISSUE TITLE
External Tools can't use command to open tool

### ISSUE THREAD

**Issue by jopejoe1** [MultiMC/MultiMC5#3692]
### Operating System

Linux

### Description of bug

Using the command for opening in External Tools is not opening the tool. When Pressing check it gives me the error `Error while checking JProfiler install: Path does not exist` 

### Steps to reproduce

Open settings -> External Tools -> Set JProfiler to `jprofiler` -> try Check or using the tool in MultiMC

### Suspected cause

Only checks for paths and not commands

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
The path points to the installation folder of jprofiler, not the binary this is working as intended.
Specifially it takes that path and then executes `bin/jpenable`

https://github.com/MultiMC/MultiMC5/blob/0946c7c138d73a6e11835dc95da764ff1c0db5ad/api/logic/tools/JProfiler.cpp#L65
