### ISSUE TITLE
Windows 64 bit support

### ISSUE THREAD

**Issue by CryoRenegade** [MultiMC/MultiMC5#3693]
### Role

I usually play modded mc using MultiMC.

### Suggestion

I would like the ability to both build and/or download a 64 bit version of MultiMC .

### Benefit

Honestly? To future proof MultiMC when Windows drops 32 bit support like Apple did in MacOS Catalina.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by peterix** [comment]
The answer to that is a No.

**Comment by peterix** [comment]
It's not necessary until MS actually does this.

**Comment by CryoRenegade** [comment]
Fair enough

**Comment by AverageComet250** [comment]
Also, ms probs won't do this for a while.

And anyway, having a single exe for everyone rather than two exes and a community split between them, is way easier.

Also, it causes ram usage limits for MMC, so MMC itself will never end up taking up too much ram
