### ISSUE TITLE
Job 'Modpack download' failed to process

### ISSUE THREAD

**Issue by FeedTheChunk** [MultiMC/MultiMC5#3695]
MultMC:  Version 0.6.12-develop-1538
OS: Windows 10

I added a new instance and searched CurseForge sky of ages.  Found the pack, downloaded and installed the pack.  Then tried to add a second pack.  When I went to the CurseForge section and searched it through the error **Job 'Modpack download' failed to process**

I noticed that you had just made a change due to the search featuring not working as intended.

**Comment by kb-1000** [comment]
Please fill out the issue form correctly. There is not enough information provided here for anyone to help you.

**Comment by kb-1000** [comment]
Please provide `MultiMC-0.log` from your MultiMC directory.

**Comment by FeedTheChunk** [comment]
[MultiMC-0.log](https://github.com/MultiMC/MultiMC5/files/6216141/MultiMC-0.log)

**Comment by FeedTheChunk** [comment]
When I posted the bug report there wasn't the typical template to follow / fill out.  I found it odd but tried to include as much as I could.  Let me know what else you need.

**Comment by kb-1000** [comment]
Please reproduce the issue and upload the log _after_ that.
This log seems to have been uploaded directly after startup.

**Comment by FeedTheChunk** [comment]
[MultiMC-1.log](https://github.com/MultiMC/MultiMC5/files/6216404/MultiMC-1.log)
[MultiMC-0.log](https://github.com/MultiMC/MultiMC5/files/6216405/MultiMC-0.log)

-1.log was from the this morning.  the -0.log file is where I just duplicated the error.

**Comment by phit** [comment]
snippet of the important part

```
  686.654 D Task "NetJob(Modpack download)" starting for the first time
  686.662 C "Could not open E:/Games/MultiMC/cache for writing"
  686.662 C "Could not open E:/Games/MultiMC/cache for writing"
  686.662 C "Could not open E:/Games/MultiMC/cache for writing"
  686.663 C "Could not open E:/Games/MultiMC/cache for writing"
```

**Comment by phit** [comment]
@FeedTheChunk any idea what could be blocking that on your end? Are you using any third party antivirus software? If yes, try disabling that temporarily and try again.

**Comment by phit** [comment]
any updates?

**Comment by FeedTheChunk** [comment]
Sorry I thought that I answered.  I was typing my search string into the Name: field and pressing Enter / Return.  So I was essentially searching for a null / empty string in the Search and filter ... field.
