### ISSUE TITLE
Add the ability to download mods directly from curseforge

### ISSUE THREAD

**Issue by J-E-Mc** [MultiMC/MultiMC5#3696]
### Role

I often switch between different sets of mods and don't usually use pre-made modpacks

### Suggestion

I want the "Loader Mods" screen to have an option to search curseforge for mods

### Benefit

To make it easier to download certain mods to quickly build an instance

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by spannerman79** [comment]
When Curse has a _decent_ API.  Until then, personally, I doubt it.

**Comment by jamierocks** [comment]
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3696.
