### ISSUE TITLE
MultiMC interface on HDPI

### ISSUE THREAD

**Issue by ThexXTURBOXx** [MultiMC/MultiMC5#3697]
### Operating System

Windows

### Description of bug

Interface is too small, as seen on the screenshot. It is important to notice, that I have set the native scaling in Windows to 150%, which doesn't seem to influence MultiMC.

https://prnt.sc/10x820b

### Steps to reproduce

Open MultiMC on a HDPI display

### Suspected cause

The new update with the HDPI scaling is causing this. Before that update, everything was scaling correctly.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Janrupf** [comment]
Regression: https://github.com/MultiMC/MultiMC5/pull/3684

**Comment by phit** [comment]
what happens if you explicitly go into the MultiMC.exe properties and set the scaling there?

**Comment by ThexXTURBOXx** [comment]
If I set it to override with system, then it is blurry (like e.g. Minecraft in fullscreen with custom fullscreen resolution). This is, of course, expected and only a workaround. This needs further investigation, I believe.

Is there any way in MultiMC itself to set a scaling or is Qt able to read Windows's native scaling setting?

![grafik](https://user-images.githubusercontent.com/12763829/112729635-7b4ee380-8f2d-11eb-81b3-afc600640677.png)

**Comment by ThexXTURBOXx** [comment]
I forgot to mention: I have 3 monitors and my main one is on 4k resolution:
![grafik](https://user-images.githubusercontent.com/12763829/112751337-b0127780-8fcd-11eb-8869-676fe364873a.png)

**Comment by AverageComet250** [comment]
Should be fixed on latest develop build

**Comment by phit** [comment]
@AverageComet250 thats the commit that introduced the issue in the first place..

**Comment by AverageComet250** [comment]
Wait so that fixed the UI scaling, but because of this the text isn't being scaled properly.

I have a slight blur when I move MMC between my monitor and my laptop screen, which are different sizes, but the same resolution. However I've always had that blur, before and before the commit.

**Comment by ThexXTURBOXx** [comment]
Yes, that is basically the same behavior that I also have. I would personally opt for reverting the mentioned commit as it only breaks stuff and I can't see any positive changes. Before that commit, MultiMC did size "correctly" (I don't know how "correctly" should be defined in this case, but everything was readable and no boxes overflowed like now)

**Comment by ThexXTURBOXx** [comment]
The new update (revert) fixed this. Thank you very much :)

![grafik](https://user-images.githubusercontent.com/12763829/112762255-fb914980-8ffe-11eb-80a0-10502038103a.png)

**Comment by peterix** [comment]
Yeah, but what was https://github.com/MultiMC/MultiMC5/issues/3666 about?

**Comment by ThexXTURBOXx** [comment]
That issue was fixed by the PR, but it broke the normal case, when MultiMC is being used on the main monitor. So, #3666 needs more investigation

**Comment by Janrupf** [comment]
Why is this closed then?! I marked https://github.com/MultiMC/MultiMC5/pull/3684 as a regression and **NOT** a fix for this? As far as I can tell, this is **CAUSED** not **FIXED** by this PR?

**Comment by ThexXTURBOXx** [comment]
Since the PR got reverted, **this** issue is fixed. The **other** one is **not**. If peterix wants this issue to stay open, then he may reopen it himself, but for me, this is fixed.
