### ISSUE TITLE
multiMC 5 on chrome OS linux can't launch modpacks on my chromebook

### ISSUE THREAD

**Issue by JMBrands** [MultiMC/MultiMC5#3701]
I am trying to launch a modpack but with all the modpacks i have tried i got the same error, it launches single mods just fine but I get a error with modpacks
here is the log:
[https://paste.ee/p/EYuGn](https://paste.ee/p/EYuGn)

**Comment by peterix** [comment]
Read https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java - you need Java 8
