### ISSUE TITLE
Snapshot 12w17a runs as a demo

### ISSUE THREAD

**Issue by Schnyarf** [MultiMC/MultiMC5#3703]
The 1.3 snapshot 12w17a (maybe some others, I haven't tested) when run in MultiMC runs as a demo. In my experience, 12w17a also runs as a demo in the old launcher used before 1.6.1 but runs correctly in the launcher used after 1.6.1.

**Comment by jamierocks** [comment]
MultiMC doesn't have any metadata to run Minecraft 12w17a, since it looks like it isn't available from Mojang's launcher.

Its possible that you can resolve this in your modified Minecraft component.
