### ISSUE TITLE
Abort button don't work when downloading 

### ISSUE THREAD

**Issue by mrcorpz** [MultiMC/MultiMC5#3704]
### Operating System

Windows

### Description of bug

Abort button don't work when downloading 

### Steps to reproduce

Download a modpack and then press abort

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kb-1000** [comment]
Duplicate of #1949.

**Comment by mrcorpz** [comment]
THIS HAVE BEEN ON A LOOOOONG TIME AND YOUGYS HAVEN'T FREAKING FIXED COME ON
