### ISSUE TITLE
Forge Crashing

### ISSUE THREAD

**Issue by Kristoth** [MultiMC/MultiMC5#3705]
Since two days ago I cannot launch any instance before 1.15 with forge. At first, it looks like it loads then just crashes, even without any mods. I tried 1.14.4 and 1.12.2. 
If I turn off the forge, it loads normally.
[Example Log no mods, 1.14.4](https://paste.ee/p/T5kYT)
[Example Log 2, 13 mods, 1.14.4](https://paste.ee/p/VzOyd)
[Example Log 3, ~80 mods, 1.12.2](https://paste.ee/p/lzoIk)
I am using Linux Mint 19

**Comment by jamierocks** [comment]
Hi, thanks for reporting. This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the MultiMC Discord.

With that said, in future please follow our issue template - its their for a reason :)
