### ISSUE TITLE
[Feature Suggestion] Shared instances

### ISSUE THREAD

**Issue by MineAndDine96** [MultiMC/MultiMC5#3706]
I would suggest a instance sync function for MultiMC. So for example that you can select an instance and share it (if possible) with any other computer which has MultiMC and this Mojang/Microsoft account registered. Or if its not possible over Mojang/Microsoft accounts a seperate account system. So everytime you for example add a mod on one computer it also gets added in the synced instance in another computer. Or if you play in a singleplayer world after saving it, the changes made would also be made in the synced instamce on the other computer.
That would be very useful especially for people who play on several PC. I know its a ton of work, but I just thought suggestiobs dont harm anyone.

**Comment by Zetabite** [comment]
Sync is a mess, especially since this would need its own cloud setup to work properly, i dont see that in near future if even ever

**Comment by kb-1000** [comment]
That doesn't sound like a doable or a viable thing to do.

**Comment by jamierocks** [comment]
This can already be achieved by instance commands, with say rsync.

**Comment by peterix** [comment]
Yeah, implementing the details of this is generally out of scope for MultiMC and the desired effect can be achieved using existing tools/features.

For example running some sort of synchronization tool as a post-exit command.

Not super polished, but doable.

**Comment by AverageComet250** [comment]
If I wanted I would happily make a tool + mod for syncing MMC instances.

Just note that even if you want it, I wouldn't start development for a while since I'm already working on a project.

**Comment by MineAndDine96** [comment]
Aight. I get the point, thanks for reading. :)

**Comment by spannerman79** [comment]
@MineAndDine96 I actually already do this with SyncThing.  I just use a pre and post command to pause and resume the sync process.

To be fair to be able to include something like this to be able to be done across all three OS's is a tall order for MultiMC.

Use already tools that exist for functionality like this - like I have :smile:
