### ISSUE TITLE
Can Not Add Instance for GreedyCraft Modpack

### ISSUE THREAD

**Issue by CorsonForge** [MultiMC/MultiMC5#3708]
### Operating System

Windows

### Description of bug

When trying to add instance for GreedyCraft modpack I receive the error "Could not understand pack manifest: Document is not an object"

### Steps to reproduce

Drag GreedyCraft zip file in to MultiMC

or

1. Click Add Instance
2. Click Import from Zip
3. Click Browse
4. Find GreedyCraft Zip File and click Open
5. Click OK

### This issue is unique

I have searched the issue tracker and did not find an issue describing my bug.

**Comment by CorsonForge** [comment]
![Capture](https://user-images.githubusercontent.com/64653583/113462962-48e33180-93d8-11eb-9148-6b2b5146a0f5.PNG)

Here is a screen shot of the error I receive

**Comment by jamierocks** [comment]
Could you supply a link to the modpack?

**Comment by CorsonForge** [comment]
> Could you supply a link to the modpack?

I tried with both the file from github and from curseforge and received the same error. 

I should also mention this is my first time using MultiMC. So could very well be user error in some way.

https://github.com/TCreopargh/GreedyCraft
https://www.curseforge.com/minecraft/modpacks/greedycraft/files

**Comment by spannerman79** [comment]
Unable to replicate.

1. Downloaded https://www.curseforge.com/minecraft/modpacks/greedycraft/files/3259813
2. Add Instance -> Import from Zip -> Browse -> selected `GreedyCraft-1.34.1.115.1.zip`
3. Wait for other mods to download
4. Finished/Done

**Comment by CorsonForge** [comment]
> Unable to replicate.
> 
> 1. Downloaded https://www.curseforge.com/minecraft/modpacks/greedycraft/files/3259813
> 2. Add Instance -> Import from Zip -> Browse -> selected `GreedyCraft-1.34.1.115.1.zip` -> Clicked OK
> 3. Wait for other mods to download
> 4. Finished/Done

**Comment by CorsonForge** [comment]
> Unable to replicate.
> 
> 1. Downloaded https://www.curseforge.com/minecraft/modpacks/greedycraft/files/3259813
> 2. Add Instance -> Import from Zip -> Browse -> selected `GreedyCraft-1.34.1.115.1.zip` -> Clicked OK
> 3. Wait for other mods to download
> 4. Finished/Done

Hahaha I think my computer heard you and got scared because when I tried it from your link it seems to be working!
