### ISSUE TITLE
Windows "Vista" Theme broken with Qt 5.15

### ISSUE THREAD

**Issue by phit** [MultiMC/MultiMC5#3711]
### Operating System

Windows

### Description of bug

The default theme on Windows looks like Windows 95

### Steps to reproduce

* run the Qt 5.15 build on Windows
* select the default theme

### Suspected cause

https://bugreports.qt.io/browse/QTBUG-80732
https://forum.qt.io/topic/109704/qt-5-14-0-qapplication-setstyle-broken/3
packaging needs to be updated for Qt 5.15

### This issue is unique

I have searched the issue tracker and did not find an issue describing my bug.

**Comment by peterix** [comment]
Adding the 'windowsvista' plugin DLL to `plugins/styles/` seems to help.

**Comment by AverageComet250** [comment]
Isn't MMC built against Qt 6?

**Comment by kb-1000** [comment]
No, and it never has been.

**Comment by phit** [comment]
test, sorry for the email

**Comment by phit** [comment]
fixed with https://github.com/MultiMC/MultiMC5/commit/cd87029e6fc0c8d8b25c9162812ae066066ad11a
