### ISSUE TITLE
Instance doesn't start at the second start

### ISSUE THREAD

**Issue by theitalianweeb** [MultiMC/MultiMC5#3712]
### Operating System

macOS

### Description of bug

The instance should have started normally, but it crushed when I tried to open it a second time, after creation. Right after having created it, it started and functioned normally, then when I closed it and reopened it, it doesn't start at all. I tried removing the mods I added between the two starts, to reproduce the conditions of the first start, then when I looked at the log it showed an issue with the launcher itself, OneSix launcher. The game is in 1.16.5, There's only one world, generated with chunk pregenerator, with a radius of 200 chunks (like, very big).

### Steps to reproduce

Generate a world with chunk pregenerator of at least 200 chunk radius, then close the instance and try to open it again, to see if the launcher can handle.

### Suspected cause

The launcher doesn't start, probably because of the size of the world and how much is generated (200 chunks radius, for short, 160000 chunks).

### This issue is unique

I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
