### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by githut256** [MultiMC/MultiMC5#3716]
### Description of bug

Invalid account or username

### Steps to reproduce

maybe fix

### Suspected cause

i dont know

### This issue is unique

I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
MultiMC currently does not support Microsoft accounts yet. If you purchased Minecraft after December 1st, 2020, you will not be able to use your account in MultiMC until support for Microsoft accounts is added. [You can read more on the website here.](https://multimc.org/posts/microsoft-accounts.html)
