### ISSUE TITLE
UI inconsistancies when changing instance type

### ISSUE THREAD

**Issue by NinjaPhenix** [MultiMC/MultiMC5#3720]
### Operating System

Windows

### Description of bug
MultiMC Version: `0.6.12-devlop-2055`
I've noticed a few inconsistencies when changing instance type in the new instance screen. ( vanilla, import from zip, ... )
When switching to (ATLauncher / FTB / Technic) pack selection after previously selecting a pack I've observed the following:
1. The OK button state is not updated
2. The pack icon fails to update properly, defaults to multimc icon or stays same if switching from Curseforge / FTB Legacy, also stays the same when switching from FTB to ATLauncher.

### Steps to reproduce

1. Add Instance.
2. Select FTB and select any pack, so that OK button is enabled.
3. Change to any other install type, e.g. FTB Legacy. (2)
4. Change back to FTB.
5. OK button is disabled. (1) Icon is now MultiMC icon. (2)
6. Select a different pack such that the instance icon updates.
7. Switch to ATLauncher.
8. Instance Icon is still the FTB pack icon. (2)

### Suspected cause

Not sure however these issues don't seem to affect Curseforge or FTB Legacy so I would refer to them.

### This issue is unique

I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
The lingering Legacy FTB icons is covered by GH-3118. Interesting about the OK button state not being updated though, will test that.
