### ISSUE TITLE
MalisisCore and Optifine makes the Game crashing

### ISSUE THREAD

**Issue by Blocky10** [MultiMC/MultiMC5#3722]
### Description of bug

Help!!

My Minecraft crashes because of MalisisCore and Optifine

### Steps to reproduce

1.12.2

### Suspected cause

The Mods
MalisisCore
Optifine

### This issue is unique

I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kb-1000** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's discord.
