### ISSUE TITLE
Multiple Skin Support

### ISSUE THREAD

**Issue by PlatFormPlayZ** [MultiMC/MultiMC5#3723]
### Role

I play on multiple roleplaying SMP servers.

### Suggestion

I want there to be multiple skin support similar to the native Minecraft Launcher

### Benefit

I want multimc to be able to do this so i can more quickly and easily be able to switch which skin im using

### This suggestion is unique

I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by jamierocks** [comment]
Thanks for taking the time to make this suggestion! I agree this would be very nice to have 🙂

Though this suggestion is already being tracked by https://github.com/MultiMC/MultiMC5/issues/3399.
