### ISSUE TITLE
Wiki: Arch jre8-openjdk install instructions tells reader to break their arch install

### ISSUE THREAD

**Issue by ImperatorStorm** [MultiMC/MultiMC5#3724]
### Role

Arch user

### Suggestion

[Arch jre8-openjdk install instructions](https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java#linux) tells reader to break their arch install by telling them to use `pacman -Sy`, [which is unsuppported and can break your system](https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported). This should be corrected to `pacman -Syu`.

### Benefit

This will help prevent broken systems as a result of partial upgrades.

### This suggestion is unique

I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by spannerman79** [comment]
Yes, I do agree with you, although to be fair if you look at the official PKGBUILD https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=multimc-git#n11 `jdk8-openjdk` is a required depend for the make process.

-----
Scope:  Someone with the correct perms to edit the wiki needs to resolve this.

**Comment by solarshado** [comment]
Pretty sure the correct command should be `pacman -S jre8-openjdk`. `-Syu` would do a full system upgrade before installing the new package, which is probably massive overkill, and may have unintended consequences.

**Comment by peterix** [comment]
It is `-S` that has unintended consequences, because it can lead to a partially updated system that stops working.

**Comment by jotoho** [comment]
`pacman -Syu && pacman -S jre8-openjdk` should work as a one-liner, shouldn't it? That way the system is updated correctly and the Java runtime installed immediately afterward.

**Comment by peterix** [comment]
you can shorten that to `pacman -Syu jre8-openjdk`

**Comment by jotoho** [comment]
> you can shorten that to `pacman -Syu jre8-openjdk`

Interesting, I'm going to remember that trick.

**Comment by peterix** [comment]
I've updated the wiki page.
