### ISSUE TITLE
a bug playing with 1.12.2 forge mods... pls make compatibility with the mods.

### ISSUE THREAD

**Issue by coopersteve14** [MultiMC/MultiMC5#3725]
### Description of bug

i wanted to play some 1.12.2 but when i make/load into a world and this this critical error shown up "[14:44:00] [Client thread/FATAL] [minecraft/Minecraft]: Reported exception thrown!" and the mods are "creativecoredummy  | 1.0.0               | minecraft.jar                                       | None                                     |
	| LCHIJA | micdoodlecore      |                     | minecraft.jar                                       | None                                     |
	| LCHIJA | obfuscate          | 0.4.2               | minecraft.jar                                       | None                                     |
	| LCHIJA | ichunutil          | 7.2.2               | iChunUtil-1.12.2-7.2.2.jar                          | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | backtools          | 7.0.0               | BackTools-1.12.2-7.0.0.jar                          | None                                     |
	| LCHIJA | better_diving      | 1.5.8               | BetterDiving-1.12.2-1.5.8.jar                       | None                                     |
	| LCHIJA | bookshelf          | 2.3.590             | Bookshelf-1.12.2-2.3.590.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | catwalks           | 1.12.2-4.0.45       | catwalks-1.12.2-4.0.45.jar                          | None                                     |
	| LCHIJA | chunkpregenerator  | 2.5.0               | Chunk+Pregenerator-V1.12-2.5.0.jar                  | None                                     |
	| LCHIJA | clumps             | 3.1.2               | Clumps-3.1.2.jar                                    | None                                     |
	| LCHIJA | colytra            | 1.2.0.4             | colytra-1.12.2-1.2.0.4.jar                          | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | creativecore       | 1.10.0              | CreativeCore_v1.10.47_mc1.12.2.jar                  | None                                     |
	| LCHIJA | effortlessbuilding | 1.12.2-2.12         | effortlessbuilding-1.12.2-2.12.jar                  | None                                     |
	| LCHIJA | exhaustedstamina   | 1.2                 | exhaustedstamina-1.2.jar                            | None                                     |
	| LCHIJA | googlyeyes         | 7.1.1               | GooglyEyes-1.12.2-7.1.1.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | hexlands           | 1.9.0               | hexlands-1.9.0.jar                                  | None                                     |
	| LCHIJA | waila              | 1.8.26              | Hwyla-1.8.26-B41_1.12.2.jar                         | None                                     |
	| LCHIJA | ido                | 2.0.0-B             | ido-1.12.2-2.0.0-B (2).jar                          | None                                     |
	| LCHIJA | journeymap         | 1.12.2-5.7.0        | journeymap-1.12.2-5.7.0.jar                         | None                                     |
	| LCHIJA | mclib              | 2.2.2               | mclib-2.2.2-1.12.2.jar                              | None                                     |
	| LCHIJA | metamorph          | 1.2.6               | metamorph-1.2.6-1.12.2 (1).jar                      | None                                     |
	| LCHIJA | mobdismemberment   | 7.0.0               | MobDismemberment-1.12.2-7.0.0.jar                   | None                                     |
	| LCHIJA | mobends            | 1.0.0-beta-20.06.20 | MoBends_1.12.2-1.0.0-beta-20.06.20.jar              | None                                     |
	| LCHIJA | multimine          | 1.6.2               | MultiMine-1.12.2.jar                                | None                                     |
	| LCHIJA | opframe            | 1.4.0               | OnlinePicFrame_v1.5.0-pre1_mc1.12.2.jar             | None                                     |
	| LCHIJA | portalgun          | 7.1.0               | PortalGun-1.12.2-7.1.0 (2).jar                      | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | quick_cheat_mod    | Beta                | Quick_Cheat_MOD_Beta_1.5.3_for_Minecraft_1.12.2.jar | None                                     |
	| LCHIJA | realdrops          | 1.2.14              | RealisticItemDrops-1.2.14.jar                       | None                                     |
	| LCHIJA | ropebridge         | 2.0.5               | ropebridge-1.12-2.0.7.jar                           | None                                     |
	| LCHIJA | screenbrowser      | 2r                  | ScreenshotBrowser-1.12.2-2r.jar                     | None                                     |
	| LCHIJA | sekcphysics        | 0.1.0               | sekcphysics-0.1.0.jar                               | None                                     |
	| LCHIJA | shouldersurfing    | 1.12                | ShoulderSurfing-1.12.2-1.12.jar                     | d6261bb645f41db84c74f98e512c2bb43f188af2 |
	| LCHIJA | treechopper        | 1.2.4               | TreeChopper-1.12.2-1.2.4.jar                        | None                                     |
	| LCHIJA | mysttmtgravitymod  | 2.9.1               | UpAndDownAndAllAround-1.12.2-2.9.1.jar              | None                                     |
	| LCHIJA | wearablebackpacks  | 3.1.4               | WearableBackpacks-1.12.2-3.1.4.jar                  | None                                     |
	| UD     | mclib_core         | 2.2.2               | minecraft.jar                                       | None                                     |" pls fix bug

### Steps to reproduce

idk

### Suspected cause

all the disabled mods was trying to load in but it crashed

### This issue is unique

I have searched the issue tracker and did not find an issue describing my bug.

**Comment by spannerman79** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
