### ISSUE TITLE
missing files after running offline mode

### ISSUE THREAD

**Issue by SpaceTurtle75** [MultiMC/MultiMC5#3727]
### Operating System

Linux

### Description of bug

after running the launcher on all of fabric 3 for an hour and thirty minutes, it kept staying pretty laggy. i tried switching to offline mode to see if it would help the lag but instead it crashed for the first time. i couldnt start the normal version without a bunch of yellow and reds reports being seen in the console, then as minecraft gets | | close to starting it says it has no optifine in the main text. after 8 seconds it says it is stopping without me doing anything, and the crash code is "Process exited with code 255".. i have no clue what that means in need to fix in what i did. i believe its the fact im running ubuntu 20.10, it doesnt say muiltimc is supported in my software installer and i had to download it in the terminal.

### Steps to reproduce

launch minecraft in multimc

### Suspected cause

me running offline mode already not being supported by software.

### This issue is unique

I have searched the issue tracker and did not find an issue describing my bug.

**Comment by spannerman79** [comment]
> and the crash code is "Process exited with code 255

This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by phit** [comment]
> i believe its the fact im running ubuntu 20.10, it doesnt say muiltimc is supported in my software installer and i had to download it in the terminal.

just to clarify here, multimc works fine on ubuntu, there was only some packaging changes recently see https://github.com/MultiMC/MultiMC5/issues/3413#issuecomment-805294349

but that has nothong to do with the game issues you are having
