### ISSUE TITLE
clearing the log results in 100% cpu usage

### ISSUE THREAD

**Issue by kuzetsa** [MultiMC/MultiMC5#373]
#### Steps to reproduce:

0. click on an instance and launch it
0. click "clear" on the log thinger
0. *optional???* -- clear the log thinger a second time
0. click on one of the other panes (*the one I chose was "other logs"*)
0. now try going back to the main log pane, and nothing works right (*see:* "**result**" *below*)

**Result:** 100% cpu usage on one thread / core & the windows message pump event loop thinger isn't getting any CPU cycles

---

**Edited to add:**

This is on windows 7 64-bit (*hence my use of the term "message pump / event loop" <br>... not sure how it's handled on other OSes or if it's just called something else*)

When this sort of glitch happens, the OS says it is "not responding" and offers the option to wait or close.

**Comment by peterix** [comment]
Unable to reproduce.
