### ISSUE TITLE
Error 127 in under 1.13

### ISSUE THREAD

**Issue by Huso112** [MultiMC/MultiMC5#3733]
Hello. I am using MultiMC in Manjaro KDE. I take error 127 in under 1.13 and i do not know what is happened. Little help ?
[new 2.txt](https://github.com/MultiMC/MultiMC5/files/6323515/new.2.txt)
[new 3.txt](https://github.com/MultiMC/MultiMC5/files/6323517/new.3.txt)
[new 4.txt](https://github.com/MultiMC/MultiMC5/files/6323518/new.4.txt)
[new 5.txt](https://github.com/MultiMC/MultiMC5/files/6323519/new.5.txt)
[new 6.txt](https://github.com/MultiMC/MultiMC5/files/6323520/new.6.txt)
[new 7.txt](https://github.com/MultiMC/MultiMC5/files/6323521/new.7.txt)
[new 8.txt](https://github.com/MultiMC/MultiMC5/files/6323522/new.8.txt)
[new 9.txt](https://github.com/MultiMC/MultiMC5/files/6323523/new.9.txt)
[new 10.txt](https://github.com/MultiMC/MultiMC5/files/6323524/new.10.txt)
[new 11.txt](https://github.com/MultiMC/MultiMC5/files/6323525/new.11.txt)
[new 12.txt](https://github.com/MultiMC/MultiMC5/files/6323526/new.12.txt)
[new 13.txt](https://github.com/MultiMC/MultiMC5/files/6323527/new.13.txt)
[new 14.txt](https://github.com/MultiMC/MultiMC5/files/6323528/new.14.txt)

You can see version 1.12.2 to 1.0

**Comment by jotoho** [comment]
You're using Java 15 but (most) modded minecraft versions require Java 8.

Here's some more information: https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java

Either way, this seems like a problem with the game and not MultiMC, so this issue tracker isn't the right place to report this.
Maybe someone on [the MultiMC Discord Server](https://discord.gg/multimc) will help you?

**Comment by Huso112** [comment]
> You're using Java 15 but (most) modded minecraft versions require Java 8.
> 
> Here's some more information: https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java
> 
> This seems like a problem with the game and not MultiMC, so this issue tracker isn't the right place to report this.
> Maybe someone on [the MultiMC Discord Server](https://discord.gg/multimc) will help you?

Okay. I'll sak here :) Thanks for help.

**Comment by jotoho** [comment]
@Huso112 Please close this issue, if you're done here.

**Comment by Huso112** [comment]
> @Huso112 Please close this issue, if you're done here.

You solved my issue. Thanks a lot!

Btw I am sorry to open ask in wrong place :(
