### ISSUE TITLE
i can't play because because it tells me that my account or that my password is incorrect

### ISSUE THREAD

**Issue by gabrytech** [MultiMC/MultiMC5#3734]
### Operating System

Windows

### Description of bug

i go to add one account on multimc and it tells me that my account or that my password is incorrect i have a microsoft account not mojang

### Steps to reproduce

add an account

### Suspected cause

microsoft account are not supported at the moment

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Janrupf** [comment]
>  I have searched the issue tracker and did not find an issue describing my bug.

Have you though? https://github.com/MultiMC/MultiMC5/issues/3392

**Comment by VirusHD791** [comment]
I have a microsoft account and it won't let me in

**Comment by Zetabite** [comment]
read the linked issue + the news link in mmc
