### ISSUE TITLE
Unable to import instance on Raspberry pi

### ISSUE THREAD

**Issue by skyper-cz** [MultiMC/MultiMC5#3739]
### Operating System

Linux

### Description of bug

I´m unable to add instance into multiMC launcher

### Steps to reproduce

Idk

### Suspected cause

Missing feature

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kb-1000** [comment]
Please fill out the issue form correctly. There is not enough information provided here for anyone to help you.
