### ISSUE TITLE
Can't select newest snaphost (21w16a)

### ISSUE THREAD

**Issue by Bixilon** [MultiMC/MultiMC5#3741]
Today minecraft released a new snapshot: `21w16a`.

It is not possible to select in in multi mc, 21w15a is the latest version. 

It is listed as snapshot in the version manifest: https://launchermeta.mojang.com/mc/game/version_manifest.json

Using linux btw (no clue, what else to write here)

**Comment by kb-1000** [comment]
As I can see 21w16a in MultiMC, closing.

**Comment by Bixilon** [comment]
I can also see and select it now, but the question is: Why that late? (Do you use own servers for querying the minecraft versions, etc?)

**Comment by phit** [comment]
small explanation here: https://github.com/MultiMC/MultiMC5/issues/3662#issuecomment-802290369
Forge has been redoing their download servers, which broke the updates and has been temporarily disabled https://github.com/MultiMC/meta/commit/70971cd3c614e3a469b9a1aeb9d5aa28348ff183

**Comment by Bixilon** [comment]
Ah, that explains it. Thanks.
