### ISSUE TITLE
Minecraft crashed with exit code 255

### ISSUE THREAD

**Issue by Emcat737** [MultiMC/MultiMC5#3743]
My Minecraft doesn't wanna open with my Forge launcher, it opens, but before it is loaded it closes and send you to the Game crashed screen with exit code 255.

This is my crash report:
[crash-2021-04-22_23.07.09-client.txt](https://github.com/MultiMC/MultiMC5/files/6361310/crash-2021-04-22_23.07.09-client.txt)

Please help me!

**Comment by Zetabite** [comment]
Short answer: exit code useless, need correct log, follow issue template guidelines, https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by Emcat737** [comment]
I don't have MultiMC installed, does the link not work?

**Comment by Zetabite** [comment]
If you dont have MMC installed, you dont belong here.

**Comment by jamierocks** [comment]
Please fill out our issue template in future, with that said though - this isn't a bug with MultiMC, and as such this isn't an appropriate place for this.

You may go to our Discord guild (the #minecraft channel to be specific) to seek help with the game if you wish.
