### ISSUE TITLE
[macOS][1.16.5][10.7 x64] Forge Version List Not Updating

### ISSUE THREAD

**Issue by GittyUpMyHorsey** [MultiMC/MultiMC5#3744]
I can't get any newer versions of Forge past (36.1.4) to show up in the list when Minecraft 1.16.5 release is selected. There are 6 newer versions all the way up to (36.1.12)?

**Comment by RDKRACZ** [comment]
Same on Linux so it’s not os specific.

**Comment by phit** [comment]
Forge updates are currently frozen https://github.com/MultiMC/meta/commit/70971cd3c614e3a469b9a1aeb9d5aa28348ff183
They have been moving their infrastructure around which broke a couple of things, once that's all cleared up they will be added.

**Comment by peterix** [comment]
Fixed.
