### ISSUE TITLE
Will Not Allow Memory Allocation

### ISSUE THREAD

**Issue by amoddev** [MultiMC/MultiMC5#3750]
Wont let me allocate more memory then the defalts set. It just crashes.

heres the log.

https://pastebin.com/iuaZkTNs

**Comment by Zetabite** [comment]
also, please use mmc built in log uploader and paste the link it gives you

**Comment by amoddev** [comment]
Oh ok thanks for your time :)

**Comment by jamierocks** [comment]
In future use our issue template - though this being game support, this is a bug tracker. Please use the Discord for this in future :)
