### ISSUE TITLE
Microsoft Accounts again. Seriously please read!!!!!

### ISSUE THREAD

**Issue by krennerite** [MultiMC/MultiMC5#3751]
Microsoft ONLY allows new accounts to be created as Microsoft accounts. I know that they still support old Mojang accounts, but new users CANNOT create Mojang accounts. **_ALL NEW ACCOUNTS ARE MICROSOFT ACCOUNTS._**

I don't know how else to say it.

Also, if mineflayer already supports microsoft accounts, what exactly is the difficulty???

**Comment by ImperatorStorm** [comment]
#3392, waiting for official solution.
