### ISSUE TITLE
[macOS] Instance modifying window doesn't close properly

### ISSUE THREAD

**Issue by whitebear60** [MultiMC/MultiMC5#3752]
Steps To Reproduce:

1. Open MultiMC
2. Maximize the MultiMC window, it should be in fullscreen and the system menu bar should not be visible unless you move the mouse pointer to the top of the screen.
3. Choose any instance
4. Click "Edit instance"
5. Close this window by clicking the "Close" button in the bottom right corner, NOT the system close button in the system menu bar.

System: macOS 10.10
MultiMC 5 v.0.6.12-develop-2061

**Comment by whitebear60** [comment]
Maybe same as #955

**Comment by phit** [comment]
appears to be fixed with 0.6.13-develop-2490 QT 5.15.2 on macOS 11.5.2
