### ISSUE TITLE
[macOS] Rename `.minecraft` folder to `minecraft` for easier instance manage

### ISSUE THREAD

**Issue by whitebear60** [MultiMC/MultiMC5#3753]
By default, all files and folders which names start with a dot is hidden in macOS, which makes MultiMC instance managing pretty harder. Why not to rename `.minecraft` folder to `minecraft`, as Mojang did it in their launcher?

**Comment by AverageComet250** [comment]
The same behaviour happens in Linux and the `.minecraft` folder is supposed to be a hidden folder. It contains import files that, can cause errors if modified or replaced like the games dependencies. All the folders where you actually have to put stuff are openable from the game itself.

**Comment by whitebear60** [comment]
> The same behaviour happens in Linux and the `.minecraft` folder is supposed to be a hidden folder. It contains import files that, can cause errors if modified or replaced like the games dependencies. All the folders where you actually have to put stuff are openable from the game itself.

MultiMC does not store libraries in .minecraft folder, there are only configs, resourcepacks, logs, screenshots, mods (if applicable) and saves in instance's .minecraft folder.

**Comment by RDKRACZ** [comment]
>as Mojang did 

wait they did? TIL.

>MultiMC does not store libraries in .minecraft folder

Then where are libraries? I only have .minecraft folder

**Comment by whitebear60** [comment]
> wait they did? TIL.
https://minecraft.fandom.com/wiki/.minecraft
> Then where are libraries? I only have .minecraft folder
Libraries and assets are in MultiMC.app/Contents/MacOS

**Comment by RDKRACZ** [comment]
>https://minecraft.fandom.com/wiki/.minecraft

Ah so it's only changed on MacOS... why...

>I don't know how it works on Linux.

I found the button "Open libraries" but the folder is empty 
/home/username/.local/share/multimc/instances/1.16.5/libraries

**Comment by AverageComet250** [comment]
Changing something _just_ for Mac users is wrong. MultiMC is a portable app, with a single codebase for all 3 apps. This can be closed now, as it will **_not_** be implemented.

**Comment by jamierocks** [comment]
This is to handle badly written mods, though I believe that MultiMC will accept a minecraft directory with or without the prefix.

**Comment by phit** [comment]
Indeed, you can already rename them to `minecraft` and MultiMC will be fine with it! May be worthwhile considering changing the default.

**Comment by MrMelon54** [comment]
Why not just use the "open .minecraft" button?

**Comment by MaxALEau** [comment]
This will cause conflicts with the different versions.

**Comment by peterix** [comment]
Yes, it will cause problems. No, we won't do this.
