### ISSUE TITLE
[MacOS] SkyBees: Process exited with code 255.

### ISSUE THREAD

**Issue by AOTincan24** [MultiMC/MultiMC5#3756]
### Operating System

macOS

### Description of bug

Trying to load minecraft modpack SkyBees but the game crashes as during the FML process

### Steps to reproduce

No clue

### Suspected cause

https://paste.ee/p/g7inF

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc). You also may wanna read https://github.com/MinecraftForge/MinecraftForge/issues/7558
