### ISSUE TITLE
Add a way to directly install optifine via the version menu

### ISSUE THREAD

**Issue by leElvyn** [MultiMC/MultiMC5#3757]
### Role

Vanilla minecraft

### Suggestion

Have a button bellow the "install liteloader" option in the versions menu of an instance that would directly install forge, download the latest version of optifine for the current instance version, and add optifine to the mod folder 

### Benefit

it would be very useful to have an easy way of installing optifine, as it is the base minecraft mod, that the large majority of minecraft players uses for vanilla. It would be a cool QOL improvement to automate the process of installing optifine, instead of having to do it manually for every new vanilla instances

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Janrupf** [comment]
> I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

AAAAND you lied. Will not be implemented

**Comment by leElvyn** [comment]
> AAAAND you lied. Will not be implemented

i searched it. there isn't any suggestion mentioning optifine related to that.

then, there is #1989, that is basically exactly what i'm asking, and it seemed promising

https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine
isn't what i would call a one click install

we have #1506, #1605, #1777 and #2289, that are all referring to each other, and have all been closed, along with #1989 in early 2020, and i can't find any reasons why. i may be missing it entirely, but it all just seems closed.

also, you don't really have the space needed to put all of that in the suggestion

**Comment by peterix** [comment]
In general, I think MultiMC could *assist* with installing things like optifine, where it makes sense... But it would be a bit hacky.
Basically, it would have to have the ability to ask you to provide missing files and you would put in the OptiFine jar yourself. But the rest of the setup would be automated.

**Comment by leElvyn** [comment]
That totally makes sense, thanks
