### ISSUE TITLE
Add Luxemburgish translation (i can translate it)

### ISSUE THREAD

**Issue by MakeItGame** [MultiMC/MultiMC5#3759]
### Role

Just normal Multi MC

### Suggestion

Translation for Luxemburgish

### Benefit

So Luxemburgish players can use multimc in their language

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by AverageComet250** [comment]
Feel free to go on crowdin and contribute. If it isn't there already, I'm sure @peterix can add it

**Comment by phit** [comment]
Please get in touch on Discord in the translations channel, https://discord.com/invite/multimc
