### ISSUE TITLE
Add support to download mods from the internet

### ISSUE THREAD

**Issue by PibePlayer** [MultiMC/MultiMC5#3761]
### Role

It needs this feature to make the app even better

### Suggestion

I want to be able to download mods without having to deal with my mess of Downloads folder

### Benefit

Would make easier to manage/update the mods

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by PibePlayer** [comment]
I know there were some suggestions about using CurseForge or Modrinth that got rejected, but I hope we can find a Mod provider that the dev is happy about including it :)

**Comment by phit** [comment]
If there's ever any platform with sufficient pull and officially supported API, I'm sure this will be looked at. As this issue without a path forward is just noise I'm closing it.

**Comment by BenjaminHoegh** [comment]
Could you use modrinth API to do this?
