### ISSUE TITLE
Pixelmon Reforgeged from ATLauncher will download both server and client version

### ISSUE THREAD

**Issue by Malachiel87** [MultiMC/MultiMC5#3764]
### Operating System

Windows

### Description of bug

Downloading Pixelmon Reforget from ATLauncher integration of MULTIMC it will download both server version mod and client mod

### Steps to reproduce

download Pixemon Reforget from ATlauncher

### Suspected cause

I have to delete server version mod from be able to launch Pixelmon Reforged

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by spannerman79** [comment]
Looking at `https://download.nodecdn.net/containers/atl/packs/PixelmonMod/versions/Pixelmon-8.1.2/Configs.json` in specific;

```json
        {
            "name": "Pixelmon Server",
            "version": "8.1.2",
            "url": "https://download.nodecdn.net/containers/reforged/server/release/8.1.2/Pixelmon-1.12.2-8.1.2-server.jar",
            "file": "Pixelmon-1.12.2-8.1.2-server.jar",
            "download": "direct",
            "md5": "8c78b855f4958544dec483af4b49cc32",
            "force": false,
            "colour": "Green",
            "type": "mods",
            "client": false,
            "optional": false,
            "server": true,
            "selected": false,
            "recommended": true,
            "hidden": false,
            "library": false,
            "description": "Pokemon in Minecraft.",
            "website": "https://www.pixelmonmod.com/",
            "authors": [
                "PixelmonMod"
            ]
        },
```

The issue here by the looks of it the server jar is being classed as a mod - which if this is the way that the ATLauncher system works its well... stupid.

**Comment by jamierocks** [comment]
The important part is really:
```json
            "client": false,
            "optional": false,
            "server": true,
```
I already ignore optional mods, but forgot to ignore non-client mods. I've got a patch locally that resolves this, I just wasn't able to get the Pixelmon pack to finish installing.

Will return to it shortly.

**Comment by jamierocks** [comment]
Also @spannerman79 I suspect that's just a server-specifc build of Pixelmon, since it's still installed into mods. I can only assume it has the (perhaps large) client assets removed.

**Comment by jamierocks** [comment]
Fixed by https://github.com/MultiMC/MultiMC5/commit/df7873eb9a44c70710d86ccdf9975597e941351e.
