### ISSUE TITLE
Set a default account per instance

### ISSUE THREAD

**Issue by bramceulemans** [MultiMC/MultiMC5#3765]
### Role

I run a lot of alt accounts.

### Suggestion

I want to be able to set a default account per instance.

### Benefit

It will prevent me from launching instances with the wrong account. It saves extra clicks and mistakes.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Zetabite** [comment]
oh really? https://github.com/MultiMC/MultiMC5/issues/3411

**Comment by Zetabite** [comment]
anyway, last time i checked it was denied, since it was very low prio for mmc development and nobody was able to come up with a non confusing implementation

**Comment by naqaden** [comment]
@Zetabite In #3116 the first suggested implementation is to do this via command line. If that was the only implementation, would it solve the confusion?

The second suggestion is to implement it the way others have asked, as a profile setting that overrides the global default. Would it be confusing to stick it in Edit Instance > Settings > Default Account (next to the other global default overrides)?

Where can I follow the discussion you saw on this feature? Of the listed issues, one was closed with code that doesn't seem to be implemented, one was merely a yes/no question, one was closed as a dupe of a future issue, and one was closed over some bounty offers.
