### ISSUE TITLE
I just keep crashing and dont know what to do with it

### ISSUE THREAD

**Issue by dreadfullmoe** [MultiMC/MultiMC5#3773]
heres ya crash report dont know what else i can give to help ya out
https://paste.ee/p/6BIZm

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
And in the future use the issue template.
