### ISSUE TITLE
Curse/Twitch modpack don't show up in search when pack marked as "Supported Modloader Versions: Forge"

### ISSUE THREAD

**Issue by Sajeyson** [MultiMC/MultiMC5#3774]
### Operating System

Windows

### Description of bug

If modpack has 
![git](https://user-images.githubusercontent.com/42738314/117571294-a6a12280-b0d6-11eb-892b-74c27593f0a5.png)
they don't show up in search.
Maybe with Fabric and Rift they don't show up too.

### Steps to reproduce

1. Mark your modpack file to Forge.
2. Search it in Twitch packs.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
can't reproduce, do you have an example?
![image](https://user-images.githubusercontent.com/2097483/117572261-5e800100-b0d2-11eb-8e59-0590b19023bb.png)

**Comment by Sajeyson** [comment]
https://user-images.githubusercontent.com/42738314/117573287-b3764400-b0df-11eb-87bb-db72a025752f.mp4

**Comment by phit** [comment]
please try the development branch, this is probably fixed already
Settings > Update Channel

**Comment by Sajeyson** [comment]
Yes! It's worked in dev version. Thanks!
