### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by Sajeyson** [MultiMC/MultiMC5#3776]
### Operating System

Windows

### Description of bug

Error when trying Run CMake.
`CMake Deprecation Warning at CMakeLists.txt:18 (cmake_policy):
  The OLD behavior for policy CMP0020 will be removed from a future version
  of CMake.
  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.`

[CMake output log.](https://pastebin.com/a61prNZP)

### Steps to reproduce

Follow [Build instruction for Windows](https://github.com/MultiMC/MultiMC5/blob/develop/BUILD.md#windows).

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sebastian-byte** [comment]
That isn't a error, is just a warning and shouldn't interfere with build process, maybe another error is occuring and you don't see it?

**Comment by Sajeyson** [comment]
This is all errors from CMake Wizard.
```
CMake Error at CMakeLists.txt:254 (add_subdirectory):
  The source directory

    S:/MultiMC5-develop/libraries/libnbtplusplus

  does not contain a CMakeLists.txt file.


S:/MultiMC5-develop/cmake
CMake Error at CMakeLists.txt:262 (add_subdirectory):
  The source directory

    S:/MultiMC5-develop/libraries/quazip

  does not contain a CMakeLists.txt file.


S:/MultiMC5-develop/cmake
From S:/MultiMC5-develop/api/logic/testdata to S:/build-MultiMC5-develop-Desktop_Qt_5_6_0_MinGW_32bit-Default/api/logic/data
From S:/MultiMC5-develop/api/logic/updater/testdata to S:/build-MultiMC5-develop-Desktop_Qt_5_6_0_MinGW_32bit-Default/api/logic/data
From S:/MultiMC5-develop/api/logic/updater/testdata to S:/build-MultiMC5-develop-Desktop_Qt_5_6_0_MinGW_32bit-Default/api/logic/data
From S:/MultiMC5-develop/api/logic/minecraft/testdata to S:/build-MultiMC5-develop-Desktop_Qt_5_6_0_MinGW_32bit-Default/api/logic/data
From S:/MultiMC5-develop/api/logic/testdata to S:/build-MultiMC5-develop-Desktop_Qt_5_6_0_MinGW_32bit-Default/api/logic/data
-- Configuring incomplete, errors occurred!
See also "S:/build-MultiMC5-develop-Desktop_Qt_5_6_0_MinGW_32bit-Default/CMakeFiles/CMakeOutput.log".
```
And i can't press finish, only open project with errors.

**Comment by Sebastian-byte** [comment]
You forgot to grab the submodules, remove the MultiMC source code folder and clone it again with "--recursive" option.

**Comment by Sajeyson** [comment]
It's works. Thanks!
