### ISSUE TITLE
microsoft account

### ISSUE THREAD

**Issue by issac4892** [MultiMC/MultiMC5#3777]
### Role

logging in

### Suggestion

make that api

### Benefit

make new users able to log in

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by issac4892** [comment]
https://wiki.vg/Microsoft_Authentication_Scheme

**Comment by jotoho** [comment]
> - [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

You lied. This issue is pinned on the issue tracker:

Duplicate of #3392 and **many** others

**Comment by jotoho** [comment]
> https://wiki.vg/Microsoft_Authentication_Scheme

FYI: This was already proposed in #3475

**Comment by issac4892** [comment]
oh
