### ISSUE TITLE
Themes?

### ISSUE THREAD

**Issue by ReceivedChunky** [MultiMC/MultiMC5#378]
One last thing for now...

...will there be themes (like with browsers)? I'd love to personalise my launcher and console (this came into my head when I was creating new themes for my desktop and browser).

There should be a theme creator that allows the images and colours of the main toolbars (instances, news and settings), the background, the console text, the console background and toolbar to be edited and changed (using file "uploads"); the alignment and scaling ("resizing") of the images should also possible.

Let me know what you think of this idea.

**Comment by peterix** [comment]
I'm sorry for never taking you up on the offer.

Theming is one of those ideas that get repeated over often. I'm moving all ideas to a different site, so:

[Moved to worflowy (Ideas -> Theming)](https://workflowy.com/s/2EyDMcp7CU)

**Comment by ReceivedChunky** [comment]
wew this is old

**Comment by peterix** [comment]
Well, themes are in now. Took a while for me to do it and it wasn't even that much work to do it.

Let's call it the 'first prototype'. I'll definitely improve upon it later - when I get some feedback :)
