### ISSUE TITLE
Add MCP support

### ISSUE THREAD

**Issue by StereoMadnessss** [MultiMC/MultiMC5#3780]
### Role

I play minecraft with mods and I would like to see this added to the launcher.

### Suggestion

I want multimc to add support for mcp mods.

### Benefit

so that anyone can play mcp mods with no issue. There are a variety of them and usually they change vanilla but, they would be nice to see.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by kb-1000** [comment]
MCP mods are just jarmods, which is an outdated (as of approximately MC 1.5) way of making Minecraft mods.
