### ISSUE TITLE
Minecraft 1.16.5 fails to launch when forge is installed

### ISSUE THREAD

**Issue by Dimness** [MultiMC/MultiMC5#3784]
### Operating System

Windows

### Description of bug

When launching with forge installed the instance stops during the step where it fetches libraries and displays the following error:

Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance one' failed to process:
https://maven.minecraftforge.net/de/oceanlabs/mcp/mcp_config/1.16.5-20210115.111550/mcp_config-1.16.5-20210115.111550.zip

### Steps to reproduce

Create new instance of 1.16.5, add forge, launch

### Suspected cause

Multimc itself is unable to reach and download the file. I know it is not my connection itself as I am able to download the file(although I am not sure what to do with it)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
your antivirus is most likely blocking it, what AV are you using?

**Comment by Dimness** [comment]
> your antivirus is most likely blocking it, what AV are you using?

I have both Avast and malwarebytes. installed I have added the folder containing multimc to avasts whitelist to no avail.

**Comment by phit** [comment]
In the past we had players that had to uninstall Avast and then reboot for things to work, we can't really do anything about AV's messing with normal software behavior.

**Comment by Dimness** [comment]
> In the past we had players that had to uninstall Avast and then reboot for things to work, we can't really do anything about AV's messing with normal software behavior.

If the antivirus is blocking it from downloading but i can download is there a way i can manually put the library zip where it needs to go?

**Comment by AverageComet250** [comment]
I guess, but you'll need to know where the libraries are on the mojang system, and know what they have to be extracted to

Thanks,
Shravan Mandava

________________________________

**Comment by kb-1000** [comment]
> If the antivirus is blocking it from downloading but i can download is there a way i can manually put the library zip where it needs to go?

No.
MultiMC detects if you are messing with the library folder, and redownloads any changed files or files it does not know it downloaded before.
