### ISSUE TITLE
21w19a Won't launch

### ISSUE THREAD

**Issue by Rafii2198** [MultiMC/MultiMC5#3785]
### Operating System

Linux

### Description of bug

Launching the game gives [this](https://paste.ee/p/twjEN) error message. (the instance folder is called 21w07a because I just updated old snapshot version).
I tried default java settings which was java 8 and then I manually changed it to java 16 but nothing changed. MultiMC wasn't detecting Java 16 which is questionable too.

### Steps to reproduce

Just launching 21w19a

### Suspected cause

21w19a changed Java version from 8 to 16. I watched [Slicedlime video](https://www.youtube.com/watch?v=oUEDh_K74p4) and long story short he said that there is new field in version manifest and custom launchers would need to update it. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
looks like your Java 16 installation is broken, what distro are you using?

**Comment by Rafii2198** [comment]
I use Manjaro and for java I use aur package called `jre` which is in version 16.0.1-1

**Comment by ImperatorStorm** [comment]
yeah, i ran into the same issue while using `java-openjdk-bin`, for whatever reason, using an [adoptopenjdk](https://adoptopenjdk.net/) binary worked

**Comment by phit** [comment]
The Java 16 packages are still pretty new, may wanna track down those package issue trackers and report the problem(s).

**Comment by ImperatorStorm** [comment]
I'm gonna guess its an upstream issue, rather than a packaging, as `java-openjdk-bin` used binaries from oracle

**Comment by AverageComet250** [comment]
Also, as far as I'm aware, you're still supposed to use java 8 for vanilla and forge, with fabric being the only modloader to support newer java versions, since the mod for that platform which patched it, was merged into the loader

Thanks,
Shravan Mandava

________________________________

**Comment by ImperatorStorm** [comment]
@AverageComet250 re-read 21w19a's patchnotes, mojang updated to java 16

**Comment by AverageComet250** [comment]
I thought I missed something as @phit and a few other people normally close all the issues to do with not using java 8 quite quickly after they're created.
