### ISSUE TITLE
Instance crashes when launched from a mounted device

### ISSUE THREAD

**Issue by gutyina70** [MultiMC/MultiMC5#3788]
### Operating System

Linux

### Description of bug

When I start any instance (for example a clean 1.16.5 vanilla) it [crashes](https://paste.ee/p/R6tjt).
MultiMC installation is on my main drive, and the instances folder is on a mounted drive.

### Steps to reproduce

* install MultiMC for Ubuntu on the main drive
* mount an (external) partition
  * open `/etc/fstab/`
  * append that file with the following line (replace UUID with your one):
  * `UUID=f85d7a58-6f32-4af5-a2d8-97d1abd732b1 /mnt/Data ext4 defaults,auto,users,rw,nofail,noatime 0 0`
  * run `mount -a`
* Change MultiMC instances folder to:
* `/mnt/Data/MultiMC Instances`
* create a new 1.16.5 instance and run it

### Suspected cause

**NOTE**: if I don't change the instances folder, this bug doesn't happen

I have 3 ideas why this bug happens:
* MultiMC doesn't like if instances folder is not in MultiMC folder
* MultiMC doesn't have permissions to do stuff on the mounted drive
  * I tried sudo-ing it, but it exits with errors
* I messed up the mounting

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by spannerman79** [comment]
Before blaming MultiMC can you in fact create a directory under `/mnt/Data` under your current user without using sudo/su/etc?

**Comment by phit** [comment]
the mount is broken and Multimc can't extract the natives in the instance folder, try adding `exec` to the mount options

**Comment by gutyina70** [comment]
> Before blaming MultiMC can you in fact create a directory under `/mnt/Data` under your current user without using sudo/su/etc?

Yes, creating a directory works without sudo.

**Comment by gutyina70** [comment]
> the mount is broken and Multimc can't extract the natives in the instance folder, try adding `exec` to the mount options
> in theory that should be added by defaults, but eh

It fixed my issue, thanks!
