### ISSUE TITLE
MultiMC Setup Not Running

### ISSUE THREAD

**Issue by MythicDev** [MultiMC/MultiMC5#3790]
### Description of bug

I tried to open the MultiMC setup and it would not open. When first trying to open, it came up with Windows Prevented this app from opening. I clicked more options and run anyways, but nothing happened. I tried to move the folder and it said cannot be edited because is open, but I searched task manager and found nothing.

### Steps to reproduce

- Download MultiMC for Windows
- Extract Zip
- Click on MultiMC setup application
- If windows stopped it from running, click view more and then run anyways.
- It doesn't open

### Suspected cause

I don't really know what could be causing it sorry.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kb-1000** [comment]
That .exe is not a setup application, it's MultiMC itself.
There is no installer.

**Comment by MythicDev** [comment]
> That .exe is not a setup application, it's MultiMC itself.
> There is no installer.

oh thanks, but its still not opening

**Comment by phit** [comment]
where did you extract multimc to?

**Comment by MythicDev** [comment]
> where did you extract multimc to?

just into downloads and then i opened the folder.

**Comment by MythicDev** [comment]
Thank you i ran it as an administrator and it works. Thanks for helping :D

**Comment by kb-1000** [comment]
congrats for breaking perms on mmc files

**Comment by spannerman79** [comment]
> Thank you i ran it as an administrator and it works. Thanks for helping :D

MultiMC does **not** need to be ran as admin. Don't do it. There will be unintended consequences if you do.

You will need to now reset user permissions on the entire directory and contents of the directory that holds MultiMC and all if its files - including and not limited to your instances.

I won't go into details on how to do that as managing your files is outside the scope of this issue tracker.(google is your friend).

Alternatively you can redownload multimc, and extract it to _sane_ location.  I would avoid Downloads directory just in case you decide to clean out your downloads. One such location could be C:\Users\ _your user name_ \MultiMC
