### ISSUE TITLE
Optifine version read as "1.0.0", not actual version

### ISSUE THREAD

**Issue by helpimnotdrowning** [MultiMC/MultiMC5#3791]
### Operating System

Windows

### Description of bug

In the Loader Mods menu of an instance, the Optifine version shows as 1.0.0 instead of the correct version.

### Steps to reproduce

1. Add Optifine jar with a `mods.toml` file to instance
2. 
![image](https://user-images.githubusercontent.com/35247379/118519581-debfeb00-b6fe-11eb-8db8-d2167e3e7380.png)

### Suspected cause

MultiMC added `mods.toml` parsing a little bit ago, so instead of it showing the Optifine jar filename and no version, it shows the mod name as "OptiFine" instead of "OptiFine_1.16.5_HD_U_G8" with no version.
![image](https://user-images.githubusercontent.com/35247379/118520060-4f670780-b6ff-11eb-8c52-94a99db5b81f.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Janrupf** [comment]
Sounds like this should be reported to OptiFine honestly.

**Comment by helpimnotdrowning** [comment]
I think the best way to fix for now would be to either:
* check if the jar name has the word "optifine" in it, and if it does, just shown the raw jar name
* check the first line in the `OptiFine.jar/changelog.txt` file, it should almost always be the optifine version. latest changelog file for example: [changelog.txt](https://github.com/MultiMC/MultiMC5/files/6495217/changelog.txt)

**Comment by Janrupf** [comment]
I don't think there is any action needed on the MultiMC side. This is clearly a problem with OptiFine itself, so it should also be fixed by them. Given that it is only a cosmetic issue, I don't think its worth the effort to add in (possibly unstable) checks for OptiFine.
