### ISSUE TITLE
Exiting with -1

### ISSUE THREAD

**Issue by AvacadoWizard120** [MultiMC/MultiMC5#3792]
### Operating System

Windows

### Description of bug

I expected to launch Minecraft 1.16.5 modded, but it said "Process exiting with code -1"

### Steps to reproduce

* Launch MultiMC on Windows 10
* Install latest version of forge.
* Download Alchemist mod
* launch with optifine stable 1.16.5

### Suspected cause

Hardware / software on PC? Maybe drivers need to be updated?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Janrupf** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by AvacadoWizard120** [comment]
I would like to know what code -1 is

**Comment by Zetabite** [comment]
Could mean everything, there are is no common standard for it. Important is the actual crash log, cause that is the only thing with possible information.

**Comment by kb-1000** [comment]
There is a common standard... 0 means success, unless you got an `Error: Success` style thing (which usually marks a bug, but not in MultiMC).
But other than that, you're right.

**Comment by AvacadoWizard120** [comment]
Okay! Thanks for the info!
