### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Itzkk2115** [MultiMC/MultiMC5#3796]
### Description of bug

When I use muttimc5 it uses 32 bit and it uses 900 mb for ram i have a 64 bit pc and 8 gb of ram
![Capture](https://user-images.githubusercontent.com/84423359/118736309-1d38d100-b7f7-11eb-9164-af21957b59f4.PNG)

### Steps to reproduce

idk

### Suspected cause

idk

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
I believe that MultiMC is only shipped as a 32 bit binary for Windows. Now it shouldn't be using 900MB of memory though - I'm assuming you mean that's what you've configured the game to use?

In any case, this isn't a bug with MultiMC.

**Comment by Zetabite** [comment]
This is entirely unrelated and bad recommendation based on the actual issue
