### ISSUE TITLE
Can't built MultiMC on ARM Mac

### ISSUE THREAD

**Issue by mlindner** [MultiMC/MultiMC5#3797]
### Operating System

macOS

### Description of bug

I'm trying to build MultiMC on an ARM mac and I get this error.

[  8%] Building Java objects for NewLaunch.jar
warning: [options] bootstrap class path not set in conjunction with -source 6
error: Source option 6 is no longer supported. Use 7 or later.
error: Target option 6 is no longer supported. Use 7 or later.
make[2]: *** [jars/CMakeFiles/NewLaunch.dir/java_compiled_NewLaunch] Error 2
make[1]: *** [libraries/launcher/CMakeFiles/NewLaunch.dir/all] Error 2
make: *** [all] Error 2

### Steps to reproduce

Build on Arm Mac on Mac OS 11.3.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ImperatorStorm** [comment]
If I'm correct, ARM is unsupported.

**Comment by Janrupf** [comment]
That issue doesn't seem to be a problem with ARM mac at all though. Its an issue with a too new Java cversion. Java 7 or 8 are required for building (maybe some later versions too).

Minecraft might actually run on the ARM Mac because it can emulate x86_64 - so MultiMC can even be a native ARM executable, as long as the JVM is run through Rosetta (or you hack together the ARM libraries for LWJGL for M1)

**Comment by jamierocks** [comment]
You can build on AArch64. You're just building with an incompatible version of Java.

**Comment by mlindner** [comment]
@jamierocks I built it using Java "1.8" so it should be fine.

**Comment by jamierocks** [comment]
That's not an error that would occur with Java 8.

**Comment by mlindner** [comment]
javac -version
javac 1.8.0_292

So yes it's Java 8.

**Comment by mlindner** [comment]
Is the make file somehow ignoring what is set in JAVA_HOME?

**Comment by jamierocks** [comment]
As per [JDK-8206877](https://bugs.openjdk.java.net/browse/JDK-8206877) support for building to an SE 1.6 target was dropped with Java 12 - so Java 8 isn't being used.

**Comment by mlindner** [comment]
Ok then how do you get cmake to use the correct JAVA version if it ignores my Java 8? Java 8 is installed and the local environment is configured for it. So the build is somehow bypassing that. How do I prevent that?

**Comment by mlindner** [comment]
The bug was apparently cmake not overwriting previous files when you run it. So it kept hardcoding a specific java version. Please fix the cmake files so it calls "javac" and doesn't hardcode the path to javac like "/Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home/bin/javac"
