### ISSUE TITLE
[Suggestion] Support folders within Mods folder

### ISSUE THREAD

**Issue by helpimnotdrowning** [MultiMC/MultiMC5#3798]
### Role

When I play newer verisons of Minecraft, mainly 1.16, I like switching between Optifine and Sodium for shaders/framerates, but whenever I have to switch between them, I have to flip on and off 9 different mods, and I will almost always forget one or two and have to tick them on and off.

### Suggestion

Support subfolders with mods within the .minecraft/mods folder. I think a good way of doing this would be by being able to check and uncheck folders in the mods pane, but instead of adding ".disabled" to the end of folders (would mess with a lot of mods), it would add something to the end of enabled folders. Before the game starts up, MultiMC checks for enabled folders, and extracts those mods to the mods folder and lets Minecraft take care of the rest. After the game shuts down, it moves the extracted mods back to the folder.

### Benefit

So that I dont have to remember 9~10 mods to tick and untick when I want to switch between Optifine and Sodium & friends

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by AverageComet250** [comment]
You can just create two different instances and symlink a world between them

**Comment by peterix** [comment]
Just use multiple instances.
