### ISSUE TITLE
microsoft account

### ISSUE THREAD

**Issue by Emayeah** [MultiMC/MultiMC5#3802]
### Role

i play old versions

### Suggestion

add microsoft registration

### Benefit

because i do not have a mojang account

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Janrupf** [comment]
See #3392, indirect duplicate

**Comment by kb-1000** [comment]
Duplicate of #3392
