### ISSUE TITLE
How do I run a modded copy?

### ISSUE THREAD

**Issue by RealHypnoticOcelot** [MultiMC/MultiMC5#3809]
I've tried everything, but it won't load any mods. Whenever I run, it's just a vanilla copy!!!!
![Snip20210524_66](https://user-images.githubusercontent.com/57046530/119400682-83669d80-bca8-11eb-98b6-adc7e1173309.png)
![Snip20210524_67](https://user-images.githubusercontent.com/57046530/119400687-83ff3400-bca8-11eb-9a84-f3213c8d2353.png)

**Comment by ImperatorStorm** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by jamierocks** [comment]
We're unable to provide support in lack of information. Please fill out our issue template.
