### ISSUE TITLE
Deleting Logs from Instance Folder causes MultiMC Crash

### ISSUE THREAD

**Issue by dottiekh** [MultiMC/MultiMC5#3811]
### Operating System

Windows

### Description of bug

Title, if the console of an instance is opened and has been navigated to the "Other logs" menu, then the logs in the logs folder (crash-reports folder included) for that instance are deleted, MultiMC will freeze and need to be force restarted. This occurs even if the console has been closed and reopened before and after deletion respectively. Unfortunately, it does not seem to happen every time (I've only had the crash happen twice total, each on separate days).

### Steps to reproduce

1. Navigate to an instance's Other logs (there should be at least one log to view).
2. Delete the log files from that instance's logs folder.
3. MultiMC should crash.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
I'm unable to reproduce this on the latest development version, please provide your `MultiMC-0.log` from the main MultiMC folder.

**Comment by dottiekh** [comment]
[Pastebin](https://pastebin.com/r0eVgTbZ) here. Experienced similar hanging but without log deletion (instead I clicked Edit instance and it froze indefinitely).

**Comment by phit** [comment]
are you using any third party anti virus? try disabling that, rebooting and then try it again

**Comment by AverageComet250** [comment]
It might be that tried writing to something to the log and crashed cause it cause it couldn't find the log file since you deleted it. 

And before anyone says that MMC would just make a new one, it only creates a new log file at startup.

**Comment by dottiekh** [comment]
> 
> 
> are you using any third party anti virus? try disabling that, rebooting and then try it again

Nope, Windows Defender only. However I have figured out why it actually hangs indefinitely, strangely enough my system keeps suspending MultiMC's process whenever its not responding and I hit a key (which makes the "X is not responding" message pop up). I'm able to resume the process in Resource Monitor and it begins working again. If you can't reproduce it, I'd probably just write it off as something strange my computer does that I'm able to mitigate on my end. Either way the response was appreciated.

**Comment by spannerman79** [comment]
> strangely enough my system keeps suspending MultiMC's process

then it is a system/user sided issue.

I cannot replicate this issue - even within a VM created on purpose with limited resources (throttled I/O, reduced RAM I/O, etc).

If MultiMC "doesn't respond" when its footprint is ~20/30MB RAM you have bigger issues.

**Comment by dottiekh** [comment]
Yeah, I've sort of come to the same conclusion. I appreciate you going the extra mile to try and replicate it, though! I'll go ahead and close this issue then.
