### ISSUE TITLE
How do I run forge?

### ISSUE THREAD

**Issue by RealHypnoticOcelot** [MultiMC/MultiMC5#3812]
Whenever I run Forge, it gets an error saying it can't get the library files.
![Snip20210525_68](https://user-images.githubusercontent.com/57046530/119501224-a8095680-bd36-11eb-86cf-d39bc86f39cf.png)
So I manually added all of the files. But it still refuses to load because it keeps trying to get the library files from Mojang even though it doesn't check if the files are already there... Help???

**Comment by phit** [comment]
Please use the [MultiMC Discord](https://discord.gg/multimc) for general support, this Github is mainly to aid the development of MultiMC.
