### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by ChonkiestxPanda** [MultiMC/MultiMC5#3814]
### Operating System

Windows

### Description of bug

So I was launching the game as normal, I pressed launch and then pressed single player and press the only world I have. It would then just stay there on the red loading screen and then pop up with a not responding notice.

### Steps to reproduce

just launching into my world causes my game to not load and crash.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kb-1000** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's discord, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
