### ISSUE TITLE
Add option to input gigabytes into memory allocation instead of megabytes

### ISSUE THREAD

**Issue by helpimnotdrowning** [MultiMC/MultiMC5#3815]
### Role

When entering my min/max RAM for instances, I like setting the memory to align to the gigabyte, but I have to use a calculator when changing it.

### Suggestion

Instead of inputting something like 5120 into the memory allocation box, input 5G to allocate 5 gigs (java accepts stuff like -Xmx5G instead of -Xmx5120M in launch args)

### Benefit

Easier to input memory allocation.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by AverageComet250** [comment]
I think this a great idea too, cause I end up using a calculator too

**Comment by peterix** [comment]
Why do you need a calculator? Just put in a number, Java doesn't care that much.

**Comment by peterix** [comment]
And what Java accepts is irrelevant in this case., This is what MultiMC accepts. One number, no units.

**Comment by AverageComet250** [comment]
But what if you have a massive modpack and you want to give it 6gb ram, you have to whip out a calculator and do 1024 X 6 and it would be way easier if you could just type 6G or 6GB or 6GiB and it would convert that to 6144 (I had to use a calculator to get that)

**Comment by Zetabite** [comment]
You dont need a calculator. as peterix said, it doesnt really matter on how exact. 6000 is close enough. no need for such nonsense

**Comment by AverageComet250** [comment]
But then my ram counter doesn't show that minecraft's using 6gb and says 5 point something GB instead. 

If someone was to pr it, would you accept?

**Comment by Zetabite** [comment]
i dont know if you fail to understand, it doesnt change much, besides the little cute number, which matter minimally if its 6GB or a little bit less.

**Comment by RDKRACZ** [comment]
Can this be reconsidered? If this is supported by the official launcher then then MultiMC as a better alternative should have that option too, even if there is little reason to add it.

>it doesnt change much

It can. If you are playing a big modpack those ~200 MB, when using 6GiB vs 6GB, can prevent a few pauses caused by garbage collector.

**Comment by spannerman79** [comment]
> It can. If you are playing a big modpack those 144 MB, when using 6GiB vs 6GB, can prevent a few pauses caused by the garbage collector.

If you are needing to be **that** exact then use a calculator if you cannot work out `X * 1024` as you would be using -gc to check when in fact when gc pauses happen.

Splitting hairs much?

**Comment by peterix** [comment]
1. Adding UI elements for entering units would compliecate the UI
2. There is very little need for this, if any

That said, redoing how java heap settings are handled by MultiMC is definitely something to consider, but this change would simply make future changes more complex for no reason.
