### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Rob3rt005** [MultiMC/MultiMC5#3816]
### Operating System

Windows

### Description of bug

the 1.17 pre 1 crashes when i try to open

### Steps to reproduce

launch the 1.17 pre 1 version

### Suspected cause

idk

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Zetabite** [comment]
please fill out the template properly, we need a log

**Comment by Zetabite** [comment]
https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by ImperatorStorm** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's discord, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by kb-1000** [comment]
Use Java 16 for 21w19a and newer.
