### ISSUE TITLE
Use Java 16 for 21w19a and newer.

### ISSUE THREAD

**Issue by Rob3rt005** [MultiMC/MultiMC5#3817]
Use Java 16 for 21w19a and newer.

_Originally posted by @kb-1000 in https://github.com/MultiMC/MultiMC5/issues/3816#issuecomment-849829092_

I don't know how to do it

**Comment by kb-1000** [comment]
This is not a support ticket system.

**Comment by AverageComet250** [comment]
@Rob3rt005 I'm not supposed to help you but here's the fix:

Go into the settings tab on the edit instance window, tick the box next to java, click browse and select a javaw that came with java 16.

Make sure to install java 16 from adopt open jdk or normal openjdk or use the one in the launcher

**Comment by RDKRACZ** [comment]
Shouldn't MultiMC inform the user when they try to launch 21w19a and newer without Java >=16? Maybe a tooltip on the launch button or a box after clicking it?

**Comment by AverageComet250** [comment]
That's does sound like a good idea. 

It would be useful to bring up a warning if the user has their java version set to something that isn't 16 and link to a wiki page.

At the least, it'll mean less people making issues here unnecessarily.

It'd also be great if the same thing could be done for other Minecraft versions if someone isn't using java 8
