### ISSUE TITLE
The id of the instance is case sensitive when launching an instance using the cmd line parameter

### ISSUE THREAD

**Issue by calloatti** [MultiMC/MultiMC5#3818]
### Operating System

Windows

### Description of bug

Launching and instance using the command line parameter -l in Windows should probably ignore the case of the instance id.

Since the instance id is based on the folder name, and in Windows folder names are not case sensitive, it would be logical for the instance id to not be case sensitive on Windows

Note: Since Windows users are used to case insensitive folder names, when encountering this problem its not easy for them to understand what is going on and why the instance does not start. (It took me a few months to finally realize why sometimes it worked and some other times it did not)

### Steps to reproduce

Use Windows

Name an instance folder "ACME"

type multimc -l "acme" in a cmd window

multimc starts but the instance is not launched

### Suspected cause

MultiMC is probably following the convention that directory names are case sensitive in Linux systems, and applying the same criteria to instances ids when running under Windows

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by peterix** [comment]
Because the IDs are case sensitive and this is not a bug.
