### ISSUE TITLE
Unsupported mod loader in manifest: fabric

### ISSUE THREAD

**Issue by whitebear60** [MultiMC/MultiMC5#3822]
### Operating System

Linux (Fedora Workstation 34)

### Description of bug

When I trying to import [this](https://www.dropbox.com/s/0w34ebc5hvew7d7/Minecraft%20Quiz%20Reloaded-1.0.zip?dl=1) modpack, which is created in GDLauncher and uses Fabric mod loader, it starts importing, downloading all mods, but don't load Fabric and showing an error message: Unsupported mod loader in manifest: fabric.

MultiMC5 version: 0.6.12-develop-2084

### Steps to reproduce

- Import an instance with Fabric mod loader (I'm used one I linked above)
- See error message

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/MultiMC5/issues/3578#issuecomment-774007710
