### ISSUE TITLE
Installation via WinGet

### ISSUE THREAD

**Issue by jmigual** [MultiMC/MultiMC5#3823]
### Role

I play modded minecraft

### Suggestion

It would be really nice if MultiMC could be downloaded/installed via WinGet

### Benefit

This would nicely integrate with the new way Microsoft intends for binaries to be distributted

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
winget does not support ZIP files, ignoring that, the only supported way to get MultiMC will stay the official website, any other way will not get any support from this project

**Comment by peterix** [comment]
Absolutely not.

**Comment by jmigual** [comment]
Hey @peterix no need to be rude. Another contributor already gave an explanation of why this doesn't fit with the project.
