### ISSUE TITLE
My world Is not loading.

### ISSUE THREAD

**Issue by ChonkiestxPanda** [MultiMC/MultiMC5#3824]
### Operating System

Windows

### Description of bug

When I click my single player world It just stops working and then the page pops up with a not responding sign

### Steps to reproduce

When I click my single player world It just stops working and then the page pops up with a not responding sign, it still happens
[Minecraft log.txt](https://github.com/MultiMC/MultiMC5/files/6566558/Minecraft.log.txt)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by ChonkiestxPanda** [comment]
Ok thanks for the help
