### ISSUE TITLE
Use the same icons as shown in the screenshots on the website

### ISSUE THREAD

**Issue by NewoIsTaken** [MultiMC/MultiMC5#3826]
Hi everyone!

On the website, the top bar icons look like this: 
![Screenshot_2021-05-30_22-37-20](https://user-images.githubusercontent.com/18237567/120132225-f20b9580-c197-11eb-9e8a-47032ec54995.png)

However, in my MultiMC, they look like this:
![Screenshot_2021-05-30_22-36-54](https://user-images.githubusercontent.com/18237567/120132246-0354a200-c198-11eb-80c7-48f4d9c0ff9a.png)

A similar thing is happening with the Mojang status icons on the bottom.

**Comment by phit** [comment]
you can change the icon set and theme in the settings, the one in the screenshot should be "Simple (Colored Icons)"
