### ISSUE TITLE
Instance update failed because: Game update failed: it was impossible to fetch the required libraries.

### ISSUE THREAD

**Issue by In1th** [MultiMC/MultiMC5#3827]
### Operating System

Windows

### Description of bug

When I'm trying to launch new 1.16.5 instance with forge, an error:

Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance 1.16.5' failed to process:
https://maven.minecraftforge.net/de/oceanlabs/mcp/mcp_config/1.16.5-20210115.111550/mcp_config-1.16.5-20210115.111550.zip

appears

### Steps to reproduce

- create new 1.16.5 instance
- add forge (from what I have seen the version doesn't matter)
- try to launch the game

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
disable your antivirus, it is blocking the zip file
