### ISSUE TITLE
Java Bug

### ISSUE THREAD

**Issue by Romski10** [MultiMC/MultiMC5#3828]
### Operating System

Windows

### Description of bug

After I installed the correct version of java it tell me the "No versions are available" when I hit the auto detect feature.  Any suggestions on what I should do?

### Steps to reproduce

I dont know how to reproduce this because I don't know what caused it.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
what Java version did you install and where from? what is your MultiMC version?

**Comment by Romski10** [comment]
I fixed it I had a blocker that was suspending java
