### ISSUE TITLE
Snapshots 1.17-pre1 and 1.17-pre2

### ISSUE THREAD

**Issue by SlightlyPeckish** [MultiMC/MultiMC5#3829]
### Operating System

Windows

### Description of bug

Trying to run 1.17-pre1 or pre2 the game gives an error about the wrong version of java even though java is up to date and the snapshot runs fine in the normal Minecraft launcher
I have jre1.8.0_291 which is the latest version on the java website
I don't have any other versions of Java installed and the settings show that multiMC is using the correct java location 
The game works fine on other versions of Minecraft just not these snapshots

![image](https://user-images.githubusercontent.com/21175434/120243325-31e98000-c25f-11eb-927d-d394bb6feb8a.png)
![image](https://user-images.githubusercontent.com/21175434/120243342-3e6dd880-c25f-11eb-905b-ff72d84faea9.png)

Error log here: https://paste.ee/p/T3y6s

### Steps to reproduce

Create a new profile and select either the 1.17-pre1 or 1.17-pre2 snapshot and attempt to run it

### Suspected cause

Something to do with the way MultiMC uses Java

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
at least read the changelogs when trying out snapshots, you need Java 16 for them

**Comment by SlightlyPeckish** [comment]
But the normal Minecraft launcher boots the game perfectly fine and the only Java 16 I'm able to find is a dev kit

**Comment by kb-1000** [comment]
Mojang launcher bundles its own Java 16
for JREs see [AdoptOpenJDK](https://adoptopenjdk.net/releases.html?variant=openjdk16&jvmVariant=hotspot)
