### ISSUE TITLE
i can't add my mojang account and minecraft account!

### ISSUE THREAD

**Issue by Hasanohemid7** [MultiMC/MultiMC5#3830]
### Operating System

_Windows_

### Description of bug

i installed the program and i did everything right but when i'm going to add my mojang account do every thing and click (Ok)
it says ( **_### Authentication server didn't specify a currently selected profile. The account exists, but likely isn't premium._**)
like what does Premium means??? if its mean i have to own the game i Already owned it i searched everywhere and i didn't see any answer Please if you know the answer help if you can

### Steps to reproduce

i don't know what is this?

### Suspected cause

_none_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Janrupf** [comment]
Well, a few thigs:
1. Please fill out the issue template completely (including Operating System, MultiMC version)
2. "Premium" means you must have bought the game
3. You must have bought the game before december 2020 AND NOT yet have migrated your account to a Microsoft account

**Comment by Hasanohemid7** [comment]
i bought it yet december 2020 so i can't ?

**Comment by jamierocks** [comment]
Microsoft authentication isn't supported, so no.

**Comment by Hasanohemid7** [comment]
i have a mojang account not microsoft account

**Comment by Zetabite** [comment]
> i have a mojang account not microsoft account
If you bought it in december, no

**Comment by Hasanohemid7** [comment]
so is there any other way to do it?

**Comment by Zetabite** [comment]
No. Microsoft Accounts arent supported

**Comment by jotoho** [comment]
Take a look at the PINNED issue #3392 for new developments. That's the issue used
to track the microsoft authentication task and will probably get any new info first
or at least you'll know that it has been implemented if they close it.
