### ISSUE TITLE
Mods from central mods folder to be able to install for certain groups only and not for others

### ISSUE THREAD

**Issue by SlimyPython** [MultiMC/MultiMC5#3837]
### Role

I play modded minecraft via preset modpacks

### Suggestion

I want the central mods folder to be able to split into groups

### Benefit

That way fabric mods that I personally like dont try and go into forge modpacks or modpacks that shouldnt have those mods within it (i.e: If the server finds a certain mod that I placed there to be cheaty)

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by spannerman79** [comment]
You misunderstand how MultiMC works.

**Each** instance is isolated and separate from each other.

There is no need to worry about keeping forge and fabric mods separate - unless you **on purpose** attempt to do so.

There is no "central mods" folder to be concerned about as it just doesn't apply to MultiMC.
