### ISSUE TITLE
not adding account 

### ISSUE THREAD

**Issue by mrchaosss** [MultiMC/MultiMC5#3838]
### Operating System

Windows

### Description of bug

i put in email and password but it said sever did not specify and is not leting me add account 

### Steps to reproduce

add account 

### Suspected cause

i think the servers are just bad 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/MultiMC5/issues/3392
