### ISSUE TITLE
Forge Issue

### ISSUE THREAD

**Issue by diagnosey** [MultiMC/MultiMC5#3839]
### Operating System

Windows

### Description of bug

I seem to be running in to an issue with Forge not allowing my instance to run at all, it instantly crashes. Starting a completely vanilla instance from MultiMC (No forge) works without issue. Log posted here:
https://paste.ee/p/bM9SG

Any suggestions would be greatly appreciated!

### Steps to reproduce

Minecraft v. 1.16.5
LWJGL 3 v. 3.2.2
Forge v. 36.1.25
Loader mods
Economyinc 1.6.9.4-1.16.5
JEI 1.16.5 - 7.7.0.104
u-team_core 1.16.5 - 3.2.1.195
useful_backpacks 1.16.5 - 1.12.0.89

### Suspected cause

Forge issue where forge will not create modded instance due to improper forge installation?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
