### ISSUE TITLE
Export and import changes instance name

### ISSUE THREAD

**Issue by Delivator** [MultiMC/MultiMC5#3840]
### Operating System

Windows

### Description of bug

I have an instance called `Vanilla+`. But when exporting the file is called `Vanilla-.zip`.

A bit different when importing. I renamed the ZIP to `Vanilla+.zip`, imported it and the Instance is called also `Vanilla+` but the MMC instance path is `MultiMC\instances\Vanilla-`.

### Steps to reproduce

Create an instance with a `+` in its name and export it.

### Suspected cause

I would guess that some function makes sure that the exported ZIP filenames and imported instance paths are safe with the filesystem, but the `+` character is a valid character for filenames and paths.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
It looks as if a bunch of characters are excluded from being in the exported files names, including `+` - they are replaced by `-`.

Not sure why certain characters are excluded though, seems odd to me :s 

https://github.com/MultiMC/MultiMC5/blob/8b926d29d7aef9c7bbcb25ec9bfbf0ad314a8d72/api/logic/FileSystem.cpp#L302

**Comment by peterix** [comment]
This is intentional.

**Comment by peterix** [comment]
Just to give you a bit of background on this... Various operating systems and file systems have different reserved or forbidden charadters or names.

`+` is reserved on FAT32 and similar
