### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by fr20L** [MultiMC/MultiMC5#3842]
### Operating System

Windows

### Description of bug

when i try to open 1.17 it crashes

### Steps to reproduce

select version 1.17 
press start the game
and crashes

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedbackFox** [comment]
Log file, please. Your java is likely outdated. Download java 16's JDK or openJDK. 

https://www.oracle.com/java/technologies/javase-jdk16-downloads.html

**Comment by phit** [comment]
You need Java 16 download the JRE from https://adoptopenjdk.net/releases.html?variant=openjdk16&jvmVariant=hotspot

**Comment by fr20L** [comment]
thanks i will try

**Comment by MrBlueCat135** [comment]
I'm having the same issue, I'll attach the terminal output in case I'm doing something stupid

`MultiMC version: 0.6.12-1530


Minecraft folder is:
C:/Users/tobyb/OneDrive/Documents/MultiMC/instances/1.17/.minecraft


Java path is:
C:/Program Files/Java/jre1.8.0_271/bin/javaw.exe


Checking Java version...
Java is version 1.8.0_271, using 64-bit architecture, from Oracle Corporation.


Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/tobyb/OneDrive/Documents/MultiMC/instances/1.17/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/com/mojang/blocklist/1.0.5/blocklist-1.0.5.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/com/github/oshi/oshi-core/5.7.4/oshi-core-5.7.4.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/net/java/dev/jna/jna/5.8.0/jna-5.8.0.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/net/java/dev/jna/jna-platform/5.8.0/jna-platform-5.8.0.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.14.1/log4j-slf4j18-impl-2.14.1.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/com/mojang/javabridge/1.1.23/javabridge-1.1.23.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/com/mojang/authlib/2.3.31/authlib-2.3.31.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.14.1/log4j-api-2.14.1.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.14.1/log4j-core-2.14.1.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/com/mojang/minecraft/1.17/minecraft-1.17-client.jar

Native libraries:
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/tobyb/OneDrive/Documents/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/Users/tobyb/OneDrive/Documents/MultiMC/instances/1.17/.minecraft --assetsDir C:/Users/tobyb/OneDrive/Documents/MultiMC/assets --assetIndex 1.17 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 18768


Using onesix launcher.

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:171)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Process exited with code 1.
`

**Comment by FeedbackFox** [comment]
"Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0"

Update to java 16. 
https://www.oracle.com/java/technologies/javase-jdk16-downloads.html or
https://adoptopenjdk.net/releases.html?variant=openjdk16&jvmVariant=hotspot
