### ISSUE TITLE
Instance update failed because: Conflicting requirements detected during dependency checking!

### ISSUE THREAD

**Issue by NotGalacticFire** [MultiMC/MultiMC5#3846]
When loading up Minecraft 1.17 I get this error, I'm not sure what the issue is.

**Comment by kb-1000** [comment]
Please fill out the issue form correctly. There is not enough information provided here for anyone to help you.

Though:
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's discord.
