### ISSUE TITLE
Instance update failed because: Conflicting requirements detected during dependency checking!

### ISSUE THREAD

**Issue by NotGalacticFire** [MultiMC/MultiMC5#3848]
### Operating System

Windows

### Description of bug

What happened is when I started up Minecraft 1.17 (even if I uncheck all mods and use vanilla) It will an error in the logs and not start up, this error is "Conflicting requirements detected during dependency checking!" What is supposed to happen is that Minecraft starts up and I don't get any errors.

### Steps to reproduce

1. Make a MultiMC Instance on Minecraft 1.17 with java 16 (I'm using adopt OpenJDK)
2. Try launching the instance

### Suspected cause

Maybe the new version or java 16.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
![Screenshot_20210609_170344](https://user-images.githubusercontent.com/5103549/121389791-a8b00880-c944-11eb-8d5a-7d4103efdda4.png)


Unable to reproduce with provided steps.

**Comment by NotGalacticFire** [comment]
There is one thing to note, If I turn off 'keep updating' then Minecraft launches. The issue is that every time I launch Minecraft I have to turn that off because it doesn't save when I close MultiMC.

**Comment by jamierocks** [comment]
What we need is reproduction steps :)

**Comment by NotGalacticFire** [comment]
So, I think the reason your not getting it is because I have a thing called 'intermediary mappings' So I think you have to do all the steps I listed but then get the thing called 'intermediary mappings'. (I don't know if this is part of fabric I unchecked fabric but I have that thing still there and it's not uncheckable)

**Comment by NotGalacticFire** [comment]
Oh wait, it's because I had other things in the minecraft jar, fixed the issue.
