### ISSUE TITLE
Component metadata update task failed while downloading from remote server

### ISSUE THREAD

**Issue by dom11990** [MultiMC/MultiMC5#3849]
Hello,

I've been using multimc for a long time and recently went back to play some Enigmatica 2 Expert. I installed it via the CurseForge search. Strangely, when I try to launch I get the following error (only once after installing the modpack):

```
Instance update failed because: Component metadata update task failed while downloading from remote server:


Job 'Download of meta file net.minecraftforge/14.23.5.2847.json' failed to process:
https://meta.multimc.org/v1/net.minecraftforge/14.23.5.2847.json
```

If I click launch again, I get a new error:
```
Instance update failed because: Failed to download the assets index:
Job 'Asset index for Enigmatica 2: Expert - E2E' failed to process:
https://launchermeta.mojang.com/v1/packages/1584b57c1a0b5e593fad1f5b8f78536ca640547b/1.12.json
```

I'm on the develop version "MultiMC version: 0.6.12-develop-2085" but stable has the same issue. Any idea what is causing this or how I am to fix it? Is it an issue with the modpack?

```
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)
```

If I launch offline it works..

Best regards,
Dominik

**Comment by phit** [comment]
looks like you dont have internet access or MultiMC is being blocked from accessing the internet

can you open those links in your browser?

**Comment by dom11990** [comment]
I can open the link yes, looks like a json file.

**Comment by phit** [comment]
then something is blocking MultiMC from the internet, can't really help you with what that might be on your end, try disabling your antivirus

**Comment by dom11990** [comment]
Maybe as a features request to handle this issue, could MultiMC provide a nicer error message? Try a ping on google or something and let the user know there is a problem with the internet? I had though these links were deprecated or something and that there was an issue either with MultiMC or the modpack itself. I had the windows firewall disabled as well as antivirus. Not sure what could be causing this issue. I'll investigate further. At least I know the problem now. Thanks!

**Comment by phit** [comment]
yeah there's an open pull request for that https://github.com/MultiMC/MultiMC5/pull/3835
