### ISSUE TITLE
[integration] Cauldron support?

### ISSUE THREAD

**Issue by DeathHammer000** [MultiMC/MultiMC5#385]
I was trying to use WorldEdit without Single Player Commands for 1.6.4 whilst running a small, 45-strong modpack, but the Forge version crashed. Currently, there is no way for me to send the crash report to the mod devs. I am, therefore, forced to use Cauldron (it includes Bukkit, which WE fully supports), but I cannot use it with MultiMC5; this is annoying as MMC5 is a great tool and for me, MC without it is very limited.

When I installed Cauldron, it referred to the default MC directory (under %appdata%), but MultiMC5 handles Forge differently than the normal configuration (I know this because in my .minecraft directory there is an edited version of the 1.6.4 JAR - this is due to the addition of Cauldron - but there is no such thing in any of the MMC5 directories), so some things may have to be tweaked. Other than that, it's just like Forge and LiteLoader integration.

(It's strange yet interesting... ...one thing always leads to another...

...the only reason why I wanted WE was to experiment with long "runways" made from lava foam from OreSpawn... ...though I could use it for a massive building project...)

**Comment by peterix** [comment]
I do not think this is relevant anymore.
