### ISSUE TITLE
Restoration of deleted packs.

### ISSUE THREAD

**Issue by CaptianBoo** [MultiMC/MultiMC5#3850]
### Operating System

Windows

### Description of bug

At some points, when I open the launcher, previous packs that I have deleted (lets say Skyfactory 4 for example) will at some point return fully - with all the resourcepacks I downloaded and worlds still there. This can get rather annoying as I have played quite a few packs and having around 10 modpacks that I have to constantly delete rather annoying.

### Steps to reproduce

I am unsure how to reproduce this as I simply open the app.

### Suspected cause

It might be because I have it on development, but it doesn't always happen and sometimes (like a few moments ago) they just pop up.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kb-1000** [comment]
Do you have any third-party Antivirus?
Is MultiMC located in any cloud syncing tool's directory? (i.e., can you please post the full path to your MultiMC)
Also... a log would be helpful (MultiMC-0.log after trying to delete the instance)

**Comment by Xetaxheb** [comment]
Unless i'm mistaken, all packs should be contained in ..\MultiMC\instances\* (or wherever you've chosen to store them) and should only appear if they exist.... so either multimc isn't deleting the files properly (permissions issue?) or you're restoring them somehow (imaged pc that resets on boot, cloud directory, etc). 
Try deleting a pack in multimc and seeing if the folder for it in instances still exists? MultiMC should have no way to bring it back if it's gone from there.

**Comment by CaptianBoo** [comment]
@Xetaxheb I've already checked before making the report and yes they are gone from the instance folder

@kb-1000 I have CCleaner, I also have cloud syncing disabled. As for the log, I do not know how to grab it and by the time I saw your reply the launcher went through an update.

**Comment by CaptianBoo** [comment]
![image](https://user-images.githubusercontent.com/39862135/122433606-3eeabc80-cf4b-11eb-930a-647a1dfdf6b7.png)
How do I grab the log for this?

**Comment by CaptianBoo** [comment]
Also [Sorry it wont let me update previous comment with this]
![image](https://user-images.githubusercontent.com/39862135/122434224-c20c1280-cf4b-11eb-94b4-947f93676be2.png)

**Comment by AverageComet250** [comment]
Take it out of your OneDrive

**Comment by phit** [comment]
Running MultiMC in stuff like OneDrive is not supported, if it restores stuff because syncing we can't do anything about that.
