### ISSUE TITLE
Minecraft release 1.17 crashes on launch?

### ISSUE THREAD

**Issue by SteamF4lk** [MultiMC/MultiMC5#3852]
![image](https://user-images.githubusercontent.com/77806803/121432358-8f10c000-c948-11eb-9955-ef2a22053248.png)

This happens on vanilla, fabric, etc. So it does not let me launch minecraft, i have java version 8.

How do i fix this issue? happens regardless of restarting and reinstalling

**Comment by Zetabite** [comment]
use java 16

**Comment by GalaxyLinus** [comment]
where to install java 16?

**Comment by phit** [comment]
To download Java 16 go to <https://adoptopenjdk.net/releases.html?variant=openjdk16&jvmVariant=hotspot>
Select your operating system in the dropdown and change architecture to x64, if that doesn't apply to you, you do not need this guide to begin with.
Then download the JRE zip file <https://i.imgur.com/h7oosNp.png>
After the file is downloaded, extract it to some permanent location. Then open MultiMC, go to your 1.17 instance and open its settings.
<https://i.imgur.com/OKdzvgk.png>
Here go to the settings tab, enable Java Installation then click browse and navigate to the folder to which you extracted the previously downloaded ZIP file.
Then open the "bin" folder, select the "javaw(.exe)" executable and confirm, you can now launch your game.

**Comment by GalaxyLinus** [comment]
> Then download the JRE zip file https://i.imgur.com/h7oosNp.png

If I also want to compile java stuff I need JDK right?

**Comment by AverageComet250** [comment]
Yes.

You can add it to path and make java_home point to it if you want to use it for java programming.
