### ISSUE TITLE
"Cannot open MultiMC.app" on mac (solution included)

### ISSUE THREAD

**Issue by barrowsys** [MultiMC/MultiMC5#3853]
### Operating System

macOS

### Description of bug

attempting to open MultiMC.app gives error "cannot open MultiMC.app". caused by MultiMC.app/Contents/MacOS/MultiMC not having executable bit set. can be fixed by chmod +x.

im a linux person and macs confuse me. im extremely surprised that my remote debugging did any good here lol.

### Steps to reproduce

* download https://files.multimc.org/downloads/mmc-stable-osx64.tar.gz
* unzip gz
* unzip tar
* move MultiMC.app to ~/Applications
* right click MultiMC.app -> open, gives error "cannot open MultiMC.app"

### Suspected cause

MultiMC.app/Contents/MacOS/MultiMC does not have executable bit set.

* open terminal
* cd Applications/MultiMC.app/Contents/MacOS
* ls -l MultiMC, indicates read write noexecute permissions
* chmod +x MultiMC
* right click MultiMC.app -> open, works

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by hdfsyu** [comment]
or just do some stuff with compiling to make it have a bit-set pre-built

**Comment by phit** [comment]
I can't reproduce this at all with a fresh download on 11.5, I assume something happened when you extracted the tar.gz

![Screenshot 2021-07-28 at 12 40 17](https://user-images.githubusercontent.com/2097483/127309228-7fb8462e-5475-4149-822c-0fce7b12523d.png)
