### ISSUE TITLE
Add support for linux arm32

### ISSUE THREAD

**Issue by Painadath** [MultiMC/MultiMC5#3855]
### Role

I never played it becuase it didn't work

### Suggestion

Give a build for arm in every release

### Benefit

It will cause many raspberry pi users to use multimc

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by ImperatorStorm** [comment]
Won't happen unless Mojang ships arm32 builds of lwjgl and other libraries required to run minecraft

**Comment by Painadath** [comment]
Please reopen it we have lwgl libraries for arm32 @ImperatorStorm

**Comment by phit** [comment]
no "we" don't, there's no official ARM libraries from Mojang

**Comment by Painadath** [comment]
But there is unofficial lwgl libraries I play minecraft on my pi 4 using them @phit

**Comment by spannerman79** [comment]
Until there is **official** support from Mojang it won't happen @Painadath

**Comment by Painadath** [comment]
> Until there is **official** support from Mojang it won't happen @Painadath

IDK but there is lwgl2 and lwgl3 libraries compiled for arm32 @spannerman79

**Comment by Painadath** [comment]
Here it is  https://github.com/mikehooper/Minecraft

**Comment by spannerman79** [comment]
**Again** it seems you miss the entire point.

**Until there is official support from Mojang providing those libraries this won't happen**.

How much more clear does this need to be?!

**Comment by kb-1000** [comment]
Okay @Painadath, please show me where these ARM libraries are referenced in this file then:
https://launchermeta.mojang.com/v1/packages/44fa141917df947ed5a138f5cfe667a34f7bbaca/1.17.json
Third-party libraries like what you referenced are _not_ accepted.

**Comment by Painadath** [comment]
@kb-1000 sry if multimc won't accept third party libraies it's ok .I just wanted to use multimc on pi so it won't happen,😔

**Comment by Painadath** [comment]
And also when using minecraft java on pi it needs a extra jvm argument to show where is lwgl lib located

**Comment by AverageComet250** [comment]
@Painadath if you really want arm support then fork multimc, add it yourself and use your own fork

**Comment by Painadath** [comment]
> @Painadath if you really want arm support then fork multimc, add it yourself and use your own fork

I don't know either cpp or c so it remains as a distant dream but I can play minecraft on my pi without multimc @AverageComet250

**Comment by AverageComet250** [comment]
It's always worth learning a programming language even if you think you're only going to use it once

**Comment by JJTech0130** [comment]
It doesn't even require modifying the source code. You just have to specify a modified meta repo. I haven't had time to update it, so it is several versions behind, but you could use this: https://github.com/JJTech0130/MultiMC5/releases/tag/0.6.11d
As a side note, I don't recommend ARM32 minecraft on the raspberry pi b/c it is slower, use the arm64 one (beta [here](https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2021-05-28/)) and [this release](https://github.com/JJTech0130/MultiMC5/releases/tag/0.6.11-buildtest). If you want an updated version, fork my meta repo and build it yourself.

**Comment by Painadath** [comment]
> It's always worth learning a programming language even if you think you're only going to use it once

I know python html/css

**Comment by Painadath** [comment]
> It doesn't even require modifying the source code. You just have to specify a modified meta repo. I haven't had time to update it, so it is several versions behind, but you could use this: https://github.com/JJTech0130/MultiMC5/releases/tag/0.6.11d
> As a side note, I don't recommend ARM32 minecraft on the raspberry pi b/c it is slower, use the arm64 one (beta [here](https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2021-05-28/)) and [this release](https://github.com/JJTech0130/MultiMC5/releases/tag/0.6.11-buildtest). If you want an updated version, fork my meta repo and build it yourself.

Playing minecraft java 1.16.5 will get about 15-30 on single player and 50-60 on multiplayer which is engough for me

**Comment by peterix** [comment]
Everything has been said here, locking the issue.
