### ISSUE TITLE
Can't install MultiMC without installing Java 8.

### ISSUE THREAD

**Issue by RDKRACZ** [MultiMC/MultiMC5#3857]
### Operating System

Linux

### Description of bug

MultiMC requires installing openjdk-8 even though I have openjdk-16 installed (on my main PC MC my 1.16 modpack runs fine with Java 16 and I don't see a reason to force this Java version especially when somebody would be playing only with MC 1.17).

### Steps to reproduce

Download the official package for Ubuntu and try to install it without `openjdk-8-jre` `openjdk-8-jre-headless`.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
It doesn't appear to be a hard dependency of the package -> https://github.com/MultiMC/MultiMC5/blob/9fafe3ffe6fd970b5096c31db8687e4c62c0cfa6/application/package/ubuntu/multimc/DEBIAN/control#L9

**Comment by RDKRACZ** [comment]
By hard dependency, you mean that the installation can be avoided by using the --no-install-recommends flag for apt?
What if someone uses a GUI package installer like Gdebi? Wouldn't it be better to instead use the "Suggest" option (seems more valid now, after MC switched to Java 16)?

**Comment by spannerman79** [comment]
_If_ it can be assumed that everyone will _only_ play MC 1.17+ then yes.

But that cannot be assumed for obvious reasons.

**Comment by AverageComet250** [comment]
Or, 8 and 16 can both be set as the same type of dependency. Whether these are set as hard or soft dependencies is up to you, but I would say to set them _both_ as hard dependencies.

**Comment by RDKRACZ** [comment]
Java 16 is the only version that can run versions prior to 1.17 and 1.17+. Also, MultiMC on Windows and Linux Generic does not install any Java so why it does with the deb package?

Or maybe set it like that: 16 as recommended and 8 as suggested.

**Comment by Zetabite** [comment]
No. 16 can run some older versions, but as soon as your get mods into it, you will need java 8. and java 8 is what is recommend to use pre 1.17 for almost everything.

**Comment by RDKRACZ** [comment]
Maybe I was lucky but I was able to run ~60 mods on Java 16 with MC 1.16.5. You also need at least Java 11 to run the C2ME mod.

**Comment by jamierocks** [comment]
The rpm package didn't specify any, so perhaps just remove the recommendation?

**Comment by kb-1000** [comment]
I probably just forgot that

**Comment by rehashedsalt** [comment]
`.deb` packages provide a means of "OR"ing several dependencies together. We could use something like this to specify a good default Java (say, 8) while allowing the dependency to be met by any installed version of Java. Thus, a user with 11 installed won't be nagged to install 8, but a user with no JRE will:

```
Recommends: openjdk-8-jre | openjdk-11-jre | openjdk-16-jre | default-jre | java-runtime
```

The last package is a virtual with no installation candidate, but is provided by several other Java packages. The choice of 8 > 11 > 16 is completely arbitrary based on my own personal experience with compatibility.

Hard-depending on any one particular version of Java is absolutely the wrong approach given the tools we have available and the diversity of MC versions users may wish to run.

I imagine RPM has similar capabilities.

**Comment by theofficialgman** [comment]
I think you will find that java 16 will not work with multimc5 as I detailed here when trying to build using java 16
https://github.com/MultiMC/MultiMC5/issues/3949

**Comment by peterix** [comment]
None of this will be done - definitely not this way. The dependencies will be simply removed when I get to it. Replaced with using Mojang JREs.

And right now, you need Java 8 AND 16 to properly play all versions of the game.

**Comment by peterix** [comment]
Also, Java 11 is entirely unusable and requiring it is insane.

**Comment by theofficialgman** [comment]
???? never had any issues with java 11 and I've only used that with fabric mods though

**Comment by peterix** [comment]
Las I checked, pretty much all builds of it on linux were buggy and couldn't even load libraries properly... It's been a while tho.,

In any case, everything older than Minecraft 1.17 requires Java 8.
Minecraft 1.17 requires Java 16.

Using anything else is in the 'you are free to shoot yourself in the foot, I guess, if you really want to' territory.

**Comment by theofficialgman** [comment]
interesting. have had 0 issues with it on linux with the arm64 and x86_64 java builds from here: openjdk-r/ppa
been using java 11 for months on everything 1.12-1.16 and java 16 on 1.17
of course I also have java 8 incase thats needed but just haven't needed it

**Comment by peterix** [comment]
Some random ppa is not something shipped with a distro.

**Comment by peterix** [comment]
And 'works on my machine' is not a solution applicable to anyone except you.

**Comment by theofficialgman** [comment]
well of course thats only for java 16 on bionic
java 11 and java 8 from ubuntu works fine as well
