### ISSUE TITLE
Problems with saving downloaded files

### ISSUE THREAD

**Issue by Gamer153** [MultiMC/MultiMC5#3859]
MultiMC version: 0.6.12-custom
OS: Linux

When I opened MultiMC for the first time, it only showed "American English" as an available translation, and there were some errors in the log (Failed to download language json).

I didn't run it as root, and I even did `chmod 777 -Rv .` in the installation directory.

My full log: https://paste.ee/p/p7uGd

First real errors from downloading are in line 27, language json download errors start at line 56.

**Comment by spannerman79** [comment]
How **exactly** did you compile and install MultiMC?

From the log;

`Error while committing data to multimc.cfg: Operation not permitted`

Also

```
    2.393 D Downloading  "https://files.multimc.org/translations/index_v2.json"
    2.487 C Failed to commit changes to  "/home/.../MultiMC/install/translations/index_v2.json"
```

You have r/w permission issues.

**Comment by Gamer153** [comment]
I built it following the instructions from https://jjtech0130.github.io/MultiMC5/build (I built it on arm64):
```bash
mkdir ~/MultiMC && cd ~/MultiMC
mkdir build
mkdir install
git clone --recursive https://github.com/MultiMC/MultiMC5.git src
cd build
cmake -DCMAKE_INSTALL_PREFIX=../install -DMultiMC_META_URL:STRING="https://franck-nein.github.io/meta-multimc/" ../src
make -j2 install
```

And I just ran `bash ~/MultiMC/install/MultiMC` to start it.

**Comment by jamierocks** [comment]
That information is from a fork, please follow the build instructions from this repository :)
