### ISSUE TITLE
 Add login Microsoft account

### ISSUE THREAD

**Issue by RedCzech** [MultiMC/MultiMC5#3863]
### Role

 Add login Microsoft account

### Suggestion

 Add login Microsoft account

### Benefit

Can be used without Mojang

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by spannerman79** [comment]
> * I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

Well that is **utter bullshit**.

Literally pinned right at the top of https://github.com/MultiMC/MultiMC5/issues
