### ISSUE TITLE
Minecraft 1.17 on multimc crashes on Chromebook when started

### ISSUE THREAD

**Issue by Buffalokid28** [MultiMC/MultiMC5#3865]
### Operating System

Linux

### Description of bug

That minecraft started and i could play Minecraft 1.17. When i want to start my minecraft 1.17 on multimc it crash
Idk what happend to make it crash.
![Screenshot 2021-06-16 at 15 35 31](https://user-images.githubusercontent.com/86004158/122229004-ac99d880-ceb8-11eb-9c15-40782490ed4c.png)

### Steps to reproduce

/

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
We would need a full log to help - though this isn't a bug with MultiMC, but rather game support.

This is a bug tracker for MultiMC, and therefor not the appropriate place for game support. There are many communities which may be able to provide game support for you - the MultiMC Discord being one, but also the Minecraft subreddit, Minecraft Forums, the #minecrafthelp IRC channel, and potentially many more
