### ISSUE TITLE
Allow MultiMC to parse nested folders in the mods folder

### ISSUE THREAD

**Issue by EndTEmpire** [MultiMC/MultiMC5#3866]
### Role

I believe it would be beneficial for people who like to organize their mods in nested folders to not need to have a separate folder of disorganized mods.

### Suggestion

I would appreciate if the developers could add an option for MultiMC to parse folders after choosing a main folder for mods.

### Benefit

I'd rather not have too many instances of the exact same mod. (It saves space)

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by EndTEmpire** [comment]
Apologies in advance if I somehow failed to find an identical suggestion. I looked for one by searching "nested" and "parse" but it's completely possible I missed it. Thanks.

**Comment by kb-1000** [comment]
Mods aren't loaded by MultiMC, that's on your respective modloader (most likely Forge or Fabric)
Since MultiMC cannot influence that, closing

**Comment by EndTEmpire** [comment]
> Mods aren't loaded by MultiMC, that's on your respective modloader (most likely Forge or Fabric)
> Since MultiMC cannot influence that, closing

Was unaware of that. Sorry
