### ISSUE TITLE
Minecraft with forge freezes the pc after about 30, 40 minutes 

### ISSUE THREAD

**Issue by Kair0st** [MultiMC/MultiMC5#3867]
### Operating System

Windows

### Description of bug

basically, whenever I start any instance with mods installed, it runs normally for a while, but all of a sudden the game freezes and not only the game, but the pc, forcing me to turn off the pc by force that unfortunately prevents me from seeing the log , I've updated all kinds of drivers, the operating system itself and even formatted my pc, allocated more and less RAM, but this always happens, I thought it would be mine, but if you start with minecraft's official launcher, it works normally, it only happens through multimc, please, I have this problem for about 2 weeks and I couldn't solve it, does anyone have any tips on what I can do to fix this? 

### Steps to reproduce

There is no specific order to reproduce the bug, just start any instance with forge and mods installed

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
This isn't a bug with MultiMC, but rather game support.

This is a bug tracker for MultiMC, and therefor not the appropriate place for game support. There are many communities which may be able to provide game support for you - the MultiMC Discord being one, but also the Minecraft subreddit, Minecraft Forums, the #minecrafthelp IRC channel, and potentially many more.
