### ISSUE TITLE
Failed to build on Windows with either command-line or QtCreator

### ISSUE THREAD

**Issue by lockieluke** [MultiMC/MultiMC5#3868]
### Operating System

Windows

### Description of bug

I was trying to build MultiMC with the guide [here](https://github.com/MultiMC/MultiMC5/blob/develop/BUILD.md) but it failed

### Steps to reproduce

Run `make -jX` to build MultiMC

### Suspected cause

It appears that there's something wrong with `test.rc`
![image](https://user-images.githubusercontent.com/25424409/122536972-b0179600-d057-11eb-9d6b-d8d021958ab1.png)
The error says syntax error

When building in command-line...
![image](https://user-images.githubusercontent.com/25424409/122537172-e35a2500-d057-11eb-98a4-8b66251070ba.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
solved via discord, for reference use the mingw binaries qt supplies and not whatever choco happens to have at the time
