### ISSUE TITLE
MultiMC won't launch minecraft 1.17

### ISSUE THREAD

**Issue by HamzaGaming400** [MultiMC/MultiMC5#3871]
https://paste.ee/p/aGvnH

Minecraft just would't launch on MultiMC. Runs perfectly fine in the official launcher

OS: Arch linux (kernel 5.12)
GPU: 1660 super
CPU: i5-10400f

**Comment by phit** [comment]
This isn't a bug with MultiMC, but rather game support.

This is a bug tracker for MultiMC, and therefor not the appropriate place for game support. There are many communities which may be able to provide game support for you - the MultiMC Discord being one, but also the Minecraft subreddit, Minecraft Forums, the #minecrafthelp IRC channel, and potentially many more.

**Comment by RDKRACZ** [comment]
@HamzaGaming400 https://github.com/MultiMC/MultiMC5/issues/3869#issuecomment-863976708
