### ISSUE TITLE
Failed to start Minecraft: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by z1haze** [MultiMC/MultiMC5#3876]
### Operating System

Windows

### Description of bug

Failed to start Minecraft: java.lang.reflect.InvocationTargetException

I expect the game to not crash, but the game crashed. I found an earlier issue with this exact same issue, but your yelled at someone for making a necro post, so here is a new one. I DO have java 8 installed.

link to crash report: https://paste.ee/p/7yzCl

### Steps to reproduce

1. Download MultiMC
1. Extract Contents
1. Open MultiMC, configure javaw, ram, etc.
1. Import modpack from zip
1. Sign in to minecraft account
1. Launch game.

### Suspected cause

No idea.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

there _are_ other issues, but they are old, and I dont want to get yelled at for a necro post.

**Comment by phit** [comment]
Move your game out of whatever that drive that is, Java does not like it.

Anyway this doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by z1haze** [comment]
I can't just move it. That is where my desktop maps to and that is the only place I can put the game. What is the issue with the \\?? that is a perfectly valid directory path

**Comment by jamierocks** [comment]
> a perfectly valid directory path

In Windows, or what-have-you, perhaps - but Java would disagree. https://github.com/openjdk/jdk/blob/b7d78a5b661e2b00f271298db3b6cc873cf754e7/src/java.base/share/classes/java/io/File.java#L424-L425
