### ISSUE TITLE
Why Can't I Play Any Other Version On MultiMC?

### ISSUE THREAD

**Issue by TheGamingMaster1-0** [MultiMC/MultiMC5#3878]
### Description of bug

I was supposed to play normally but it wouldn't let me into the world. Only 1.16.5 will work for me.
[latest.log](https://github.com/MultiMC/MultiMC5/files/6679971/latest.log)

### Steps to reproduce

1.12.2

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ImperatorStorm** [comment]
This is a bug tracker for MultiMC, and therefor not the appropriate place for game support. There are many communities which may be able to provide game support for you - the MultiMC Discord being one, but also the Minecraft subreddit, Minecraft Forums, the #minecrafthelp IRC channel, and potentially many more.

**Comment by TheGamingMaster1-0** [comment]
okay
