### ISSUE TITLE
New console window minimum size is bigger than before and doesn't fit on small screens well

### ISSUE THREAD

**Issue by ornithologistnightmare** [MultiMC/MultiMC5#388]
I use the Aerosnap function on my computer to show the console side-by-side with other windows for different things concerning MC; for crash reports I use it alongside my browser and when fixing small numbers of item ID conflicts, my text editor. Before the 0.4 update, I could snap it so that the screen was perfectly split. That, for me, was one of the best things about the console.

However, with MMC5 0.4 (and 0.4.1), this happens:

![image](https://cloud.githubusercontent.com/assets/7671948/3643450/88daa56e-10d3-11e4-9ae8-d6ecbad3e12d.png)

This leaves me with less space to do other things in, which could lead to all sorts of skewed webpages and config files. Also, Chrome does the same, so I can't see what I'm doing very well.

To fix this, there should be a way to hide the console toolbar (reducing the window's size) and a lowered minimum size limit should also apply (thus reducing the window's size even further.

Thanks.

**Comment by peterix** [comment]
I think #358 is the same issue as this, closing.
