### ISSUE TITLE
Suggestion for implementing other repos source code for microsoft accounts

### ISSUE THREAD

**Issue by flleeppyy** [MultiMC/MultiMC5#3883]
### Role

Owning a microsoft account

### Suggestion

Look over and possibly integrate/recode the following source code from PojavLauncher: https://github.com/PojavLauncherTeam/PojavLauncher/tree/v3_openjdk/app_pojavlauncher/src/main/java/net/kdt/pojavlaunch/authenticator/microsoft

### Benefit

So people with Microsoft account's can login and play. I do realize that there are multiple issues asking for Micorosft account support, but I'm hoping that providing the source code to PojavLauncher's authentication java files, it could be some use to MultiMC

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by flleeppyy** [comment]
Are you for real right now?

**Comment by kb-1000** [comment]
Duplicate of #3392

**Comment by peterix** [comment]
Not interested.
GPL code is not allowed here.

**Comment by binex-dsk** [comment]
> Not interested. GPL licensed code is not allowed here.

What you're saying is that you're not interested in anything to do with FOSS. Understood. I remember when this launcher was actually good.
