### ISSUE TITLE
Can't launch any forge or liteloader version on multimc

### ISSUE THREAD

**Issue by juliocoliveira** [MultiMC/MultiMC5#3884]
### Operating System

Windows

### Description of bug

Can't run any forge instances, but fabric and vanilla works fine, tried liteloader too does not work, tried a lot of versions 1.16.5, 1.11.2, 1.12, 1.14.3.
Tried a lot of forge versions but usually i use the one with the star.

Log: ``
MultiMC version: 0.6.12-develop-2135

Launched instance in online mode
Authentication server is online

authserver.mojang.com resolves to:
    [13.33.109.69]

session.minecraft.net resolves to:
    [52.44.210.220, 3.234.0.54, 34.192.50.106]

textures.minecraft.net resolves to:
    [13.32.86.4, 13.32.86.81, 13.32.86.97, 13.32.86.47]

api.mojang.com resolves to:
    [13.33.132.94]

Minecraft folder is:
D:/Games/MultiMC/instances/Forge [1.16.5]/.minecraft

Java path is:
C:/Program Files/Java/jdk-16.0.1/bin/javaw.exe

Checking Java version...
Java is version 16.0.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  D:/Games/MultiMC/instances/Forge [1.16.5]/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  D:/Games/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  D:/Games/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  D:/Games/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  D:/Games/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  D:/Games/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  D:/Games/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  D:/Games/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  D:/Games/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  D:/Games/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  D:/Games/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  D:/Games/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  D:/Games/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  D:/Games/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  D:/Games/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  D:/Games/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  D:/Games/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  D:/Games/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  D:/Games/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  D:/Games/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  D:/Games/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  D:/Games/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  D:/Games/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar
  D:/Games/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.11.2/log4j-core-2.11.2.jar
  D:/Games/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  D:/Games/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  D:/Games/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  D:/Games/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  D:/Games/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  D:/Games/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  D:/Games/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  D:/Games/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  D:/Games/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/1.4.2/ForgeWrapper-1.4.2.jar
  D:/Games/MultiMC/libraries/net/minecraftforge/forge/1.16.5-36.1.0/forge-1.16.5-36.1.0-launcher.jar
  D:/Games/MultiMC/libraries/org/ow2/asm/asm/9.0/asm-9.0.jar
  D:/Games/MultiMC/libraries/org/ow2/asm/asm-commons/9.0/asm-commons-9.0.jar
  D:/Games/MultiMC/libraries/org/ow2/asm/asm-tree/9.0/asm-tree-9.0.jar
  D:/Games/MultiMC/libraries/org/ow2/asm/asm-util/9.0/asm-util-9.0.jar
  D:/Games/MultiMC/libraries/org/ow2/asm/asm-analysis/9.0/asm-analysis-9.0.jar
  D:/Games/MultiMC/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar
  D:/Games/MultiMC/libraries/cpw/mods/grossjava9hacks/1.3.0/grossjava9hacks-1.3.0.jar
  D:/Games/MultiMC/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  D:/Games/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  D:/Games/MultiMC/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  D:/Games/MultiMC/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  D:/Games/MultiMC/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar
  D:/Games/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  D:/Games/MultiMC/libraries/com/electronwill/night-config/core/3.6.3/core-3.6.3.jar
  D:/Games/MultiMC/libraries/com/electronwill/night-config/toml/3.6.3/toml-3.6.3.jar
  D:/Games/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  D:/Games/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  D:/Games/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  D:/Games/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  D:/Games/MultiMC/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar
  D:/Games/MultiMC/libraries/net/minecraftforge/nashorn-core-compat/15.1.1.1/nashorn-core-compat-15.1.1.1.jar
  D:/Games/MultiMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  D:/Games/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar
  D:/Games/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  D:/Games/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  D:/Games/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  D:/Games/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  D:/Games/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  D:/Games/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  D:/Games/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar

Mods:
  [✔️] OptiFine_1.16.5_HD_U_G7

Params:
  --username  --version MultiMC5 --gameDir D:/Games/MultiMC/instances/Forge [1.16.5]/.minecraft --assetsDir D:/Games/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 36.1.0 --fml.mcVersion 1.16.5 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20210115.111550

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx2048m, -Duser.language=en]

Minecraft process ID: 19316

Using onesix launcher.

2021-06-20 00:09:58,499 main WARN Advanced terminal features are not available in this environment
[00:09:58] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, DathusBR, --version, MultiMC5, --gameDir, D:/Games/MultiMC/instances/Forge [1.16.5]/.minecraft, --assetsDir, D:/Games/MultiMC/assets, --assetIndex, 1.16, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.1.0, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[00:09:58] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 16.0.1 by Oracle Corporation
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x6ab7a896) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x6ab7a896
	at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:41)
	at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
	at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:41)
	at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
	at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
	at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
	at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50)
	... 8 more
Exiting with -1
Process exited with code -1.
Clipboard copy at: 20 Jun 2021 00:10:14 -0300
Clipboard copy at: 20 Jun 2021 00:13:27 -0300
``

### Steps to reproduce

Create new instance.
Add forge loader.
Launch

### Suspected cause

Don't know

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ZekerZhayard** [comment]
forge does not support Java 16 for now, you should use 8 ~ 15 or add several jvm args on Java 16

**Comment by jamierocks** [comment]
This isn't a bug with MultiMC, but rather game support.

This is a bug tracker for MultiMC, and therefor not the appropriate place for game support. There are many communities which may be able to provide game support for you - the MultiMC Discord being one, but also the Minecraft subreddit, Minecraft Forums, the #minecrafthelp IRC channel, and potentially many more.

**Comment by juliocoliveira** [comment]
I didn't know that, I installed java 15 for forge and java 8 for lite loader, and is all working fine, even forge+lite loader.
Thanks so much!
