### ISSUE TITLE
Resource packs to not display if symlinked

### ISSUE THREAD

**Issue by seasnail8169** [MultiMC/MultiMC5#3890]
### Operating System

macOS, Linux

### Description of bug

Resource packs aren't displayed in an instance's resource packs tab if the resource pack is symlinked to the instances resource pack folder. 

### Steps to reproduce

1. Download a resource pack (this affects both zips and folders).
2. Create a symbolic link from the dir of the resource pack to any MMC instance's resource packs folder.
3. Open the instance's resource pack manager tab.
4. See that the pack does not show up. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
https://github.com/MultiMC/MultiMC5/blob/8179a89103833805d5374399d80a4305be1b8355/api/logic/minecraft/mod/ModFolderModel.cpp#L32 symlinked files are currently specifically ignored.

**Comment by seasnail8169** [comment]
Is there an explanation for that?

**Comment by jamierocks** [comment]
Not that I'm aware of, seems to always have been that way.

**Comment by seasnail8169** [comment]
🤔 It seems to me like a useful addition *if* there is no known issues with it, butt given that it is there i assume there was some issue with symlinked folders.

**Comment by Zetabite** [comment]
Issue is mostly due to systems that have janky symlinks like windows, where allowing symlinks would end up in a support hassle, due to users using it incorrectly and co. Making it OS dependent on the other hand, is just bad coding style.

**Comment by seasnail8169** [comment]
That's understandable, thanks for the help.

**Comment by phit** [comment]
this was now changed with https://github.com/MultiMC/MultiMC5/commit/e2355eb276bf355ca4acf526a0f3cc390aa88f8b

**Comment by seasnail8169** [comment]
> this was now changed with https://github.com/MultiMC/MultiMC5/commit/e2355eb276bf355ca4acf526a0f3cc390aa88f8b

Yeah I noticed in the changelog, thanks for letting me know!
