### ISSUE TITLE
MultiMC downloads amd64 LWJGL on aarch64

### ISSUE THREAD

**Issue by grepwood** [MultiMC/MultiMC5#3891]
### Operating System

Linux

### Description of bug

Minecraft cannot start because the supplied version of LWJGL is for amd64

### Steps to reproduce

```
sudo emerge -qv multimc::gentoo
[ start multimc ]
[ select minecraft 1.16.5 and start the game ]
```

### Suspected cause

Incorrect assumption that we're all running on amd64.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kb-1000** [comment]
Complain to Mojang. They don't provide any binaries (and ARM is therefor unsupported).

**Comment by peterix** [comment]
Yep. ARM (of any kind) is not (yet) a supported architecture.

**Comment by grepwood** [comment]
That's not exactly true that ARM is entirely unsupported. I have written down the incantation for Minecraft in a text file and did this:
```
for x in $(sed 's/:/\n/g' y | sed 's/^.*\/usr/\/usr/' | grep -o ^.*\\.jar$); do unzip -l $x; done | grep \\.so | awk '{print $4}'
```

to receive this:
```
libglfw.so.sha1
libglfw_wayland.so.sha1
libjemalloc.so.sha1
libopenal.so.sha1
liblwjgl_opengl.so.sha1
liblwjgl_stb.so.sha1
liblwjgl_tinyfd.so.sha1
liblwjgl.so.sha1
com/sun/jna/linux-x86/libjnidispatch.so
com/sun/jna/linux-x86-64/libjnidispatch.so
com/sun/jna/linux-arm/libjnidispatch.so
com/sun/jna/linux-armel/libjnidispatch.so
com/sun/jna/linux-aarch64/libjnidispatch.so
com/sun/jna/linux-ppc/libjnidispatch.so
com/sun/jna/linux-ppc64le/libjnidispatch.so
com/sun/jna/sunos-x86-64/libjnidispatch.so
META-INF/native/libnetty_transport_native_epoll_x86_64.so
```

Some parts of Minecraft's software stack support various architectures. FWIW, the only missing parts are glfw, jemalloc, OpenAL (all three can be provided by OS) and LWJGL - the missing link apparently.

**Comment by Janrupf** [comment]
ARM not being supported means it is not supported by Mojang officially. JNA always ships all native libraries, but Mojang doesn't have anything to do with it. This doesn't change the fact that they (and thus MultiMC) don't support ARM.

**Comment by kb-1000** [comment]
As far as I know, JNA isn't even used on Linux but just shipped anyways (correct me if I'm wrong).
All other parts do not support ARM.
Not on Linux, not on macOS, not on Windows.
