### ISSUE TITLE
MultiMC incorrectly reports Java bitness on aarch64

### ISSUE THREAD

**Issue by grepwood** [MultiMC/MultiMC5#3892]
### Operating System

Linux

### Description of bug

During first run, it says that Java is 32bit despite `java -version` command saying it's 64bit.

### Steps to reproduce

1. Install Java
2. Install MultiMC
3. Run MultiMC for the first time
4. Set up Java

### Suspected cause

aarch64 is incorrectly handled

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kb-1000** [comment]
ARM is not supported. It checks for `x86_64` or `amd64`.
