### ISSUE TITLE
MultiMC Wont Work

### ISSUE THREAD

**Issue by Toxicide** [MultiMC/MultiMC5#3898]
### Operating System

Windows

### Description of bug

Whenever I install forge on any of the minecraft versions it just doesn't work at all

### Steps to reproduce

Installing Forge
Wait For it to load
Says Exit Code -1

### Suspected cause

I have no idea why but it could be my java version

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
