### ISSUE TITLE
Forge will not launch in multiMC

### ISSUE THREAD

**Issue by nschwa115** [MultiMC/MultiMC5#3900]
### Operating System

Windows

### Description of bug

When I try to launch an instance with forge installed it crashes and won't launch even with no mods active or added. I can use forge just fine in the official launcher.

### Steps to reproduce

[modded server-forge.zip](https://github.com/MultiMC/MultiMC5/files/6704862/modded.server-forge.zip)

Whenever I try to launch this instance it gives me this in the log

[Crash report.txt](https://github.com/MultiMC/MultiMC5/files/6704890/Crash.report.txt)

### Suspected cause

Unsure

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
use Java 8

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by nschwa115** [comment]
Thank you. I had to go and change the directory for the java installation sense there are multiple on my PC the one it was using was the one for the JDK, not the java 8 installation.
