### ISSUE TITLE
Process exited with code 255

### ISSUE THREAD

**Issue by Goboosh** [MultiMC/MultiMC5#3901]
### Description of bug

I use pop!_OS linux, and I installed multimc 5. I have several java installations, namely java 8, 11, and 16. I installed a modpack (valhelsia 3 1.16.5) using a .zip file from curseforge. It gave me the following output:

https://paste.ee/p/bCLM8

I tried with a different launcher, GDLauncher as well. It gave me an error related to opengl, so it might be that. 

I know this has been addressed before, but not with the new 1.16.5 opengl support. 

### Steps to reproduce

as far as I know, just install java 8/11 (openjdk), install multimc using the official multimc.deb, download the valhelsia 3 modpack (version 3.3.3) from curseforge, and try and import it into multimc.

### Suspected cause

I tried with a different launcher, GDLauncher as well. It gave me an error related to opengl, so it might be that. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by spannerman79** [comment]
Reboot your system.

I've only seen this happen when there has been a dkms update/kernel update and the user never restarted their system.

**Comment by Goboosh** [comment]
That worked! thanks, I wasn't sure what the problem was. Good to know what caused it as well, never would have thought of that.
