### ISSUE TITLE
Modpacks not updating to newest version via instal from twitch/

### ISSUE THREAD

**Issue by Sarelth** [MultiMC/MultiMC5#3902]
### Description of bug

The Enigmatica 6 modpack as well as 1 or two others I have used recently have had updates but there is no option to instal that version via MultiMC unless I download the zip and install that way. 

### Steps to reproduce

Install Enigmatica 6 via twitch instal option.
It installs wrong version.
Which leads to being unable to join the server I play on.

### Suspected cause

Not sure what might be the cause.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sarelth** [comment]
Expected version was 0.4.14 got 0.4.10.

**Comment by spannerman79** [comment]
Fixed in dev.

Switch to dev channel - https://github.com/MultiMC/MultiMC5/wiki/MultiMC-settings#update-settings
