### ISSUE TITLE
Write to me that the code is 1- What do you do?

### ISSUE THREAD

**Issue by orianbrener** [MultiMC/MultiMC5#3904]
### Description of bug

I wanted to download a mod to Minecraft and suddenly the code said -1 what to do I have no idea why it happened!

### Steps to reproduce

Recovery steps:
Do not make the user ChihoSuisyou -1 in the code!

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by orianbrener** [comment]
ok
