### ISSUE TITLE
I DEMAND MICROSOFT SUPPORT

### ISSUE THREAD

**Issue by killme990** [MultiMC/MultiMC5#3906]
### Role

MY ACC IS MICROSCOPICPENISSOFT

### Suggestion

I DEMAND MICROSOFT SUPPORT

### Benefit

MICROSOFT NEW ACCOUNTS ARE ALWAYS MICROSOFT

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by peterix** [comment]
Seriously. Take a chill pill and find something more substantial to be mad about.

**Comment by AverageComet250** [comment]
Microsoft support will arrive as soon as @peterix decides on a suitable alternative for the now scrapped api we were waiting for

**Comment by AverageComet250** [comment]
Is #3475 a viable option now that the official api is scrapped @peterix
