### ISSUE TITLE
Forge install not processing for 1.16.5

### ISSUE THREAD

**Issue by Cronje99** [MultiMC/MultiMC5#3907]
### Operating System
Windows 10 Home

### Description of bug
Once any version of Forge is installed using a 1.16.5 instance, the game will fail to load and the log will show the following:

Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance mymodpack' failed to process:
https://maven.minecraftforge.net/de/oceanlabs/mcp/mcp_config/1.16.5-20210115.111550/mcp_config-1.16.5-20210115.111550.zip

### Steps to reproduce
1. Create a Vanilla 1.16.5 release instance.
2. Click on 'Edit Instance'.
3. Click 'Install Forge' and install any version of Forge. Really, any single version.
4. Click 'Launch'.

**Comment by elias116** [comment]
this happens to me too

**Comment by phit** [comment]
disable your antivirus or exclude the multimc folder
