### ISSUE TITLE
Add support for CurseForge Fabric modpacks

### ISSUE THREAD

**Issue by L33Tech** [MultiMC/MultiMC5#3908]
### Role

I develop and play Fabric modpacks.

### Suggestion

I would like the new CurseForge fabric modpack format to be supported and importable from zip like CurseForge Forge modpacks.

### Benefit

This would allow for new packs developed with Fabric to be more easily used on MultiMC.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

###Additional info:

This was closed before as it wasn't a Twitch/CurseForge feature: https://github.com/MultiMC/MultiMC5/issues/2927
However, this feature now exists and should be implemented.

**Comment by phit** [comment]
update to the development version of multimc, this was already added

**Comment by jamierocks** [comment]
It has been implemented, I did it a few weeks back.

**Comment by L33Tech** [comment]
Oh awesome. Any idea when it'll be released to stable?

**Comment by phit** [comment]
no, there's no set timeline
