### ISSUE TITLE
Find Java Versions on OS X using /usr/libexec/java_home

### ISSUE THREAD

**Issue by max96at** [MultiMC/MultiMC5#391]
/usr/libexec/java_home (Available on 10.5 and higher), when passed the argument -V shows a verbose list of all installed java versions. The current JAVA_HOME is written to stdout while the full list is written to stderr in this format:
https://gist.github.com/max96at/38bb0994682d9f3ed5cb

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Java -> More java detection).](https://workflowy.com/s/2EyDMcp7CU)

**Comment by max96at** [comment]
henlo

**Comment by peterix** [comment]
Long time no see. I hope I haven't spammed your inbox too much.
