### ISSUE TITLE
aarch64 support??

### ISSUE THREAD

**Issue by hdfsyu** [MultiMC/MultiMC5#3910]
### Role

I play vanilla minecraft.

### Suggestion

I want MultiMC to support aarch64

### Benefit

So I can play MultiMC on my arm chromebook

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
use the search, that checkbox isnt there for fun

https://github.com/MultiMC/MultiMC5/issues/2133
and countless others, https://github.com/MultiMC/MultiMC5/issues?q=is%3Aissue+arm+is%3Aclosed
