### ISSUE TITLE
Microsoft Accounts

### ISSUE THREAD

**Issue by Denisbg2011game** [MultiMC/MultiMC5#3911]
I was wanting to buy minecraft i bought it but i had to use a microsoft account how do i use multimc if i was required to buy it with a microsoft account

**Comment by jamierocks** [comment]
Give the bug tracker a search, you'll find plenty of issues related to Microsoft authentication.

**Comment by non-bin** [comment]
it would be good to get an update on #3392 I would post this there but it's locked.

The badlion client has some fix for this problem, have you guys got any ideas? (I'd love to help if I can but I'm not sure I'd be much use)
