### ISSUE TITLE
Forge Files not to current

### ISSUE THREAD

**Issue by TobiDoes** [MultiMC/MultiMC5#3921]
### Operating System

Windows

### Description of bug

i was trying to start a 1.16.5 version of my "The Magic of Ice and Fire Pack" (made by me) and the game gives me a "ImmersivePetroleum-1.16.5-3.3.0-4.jar needs language provider javafml:36 or above to load We have found 34.1" Errori looked at the launcher only to find it only goes to Forge version 34.1.42 but the most resent one is Forge version 36.1.32 for Minecraft Version 1.16.5

### Steps to reproduce

download the Latest version of forge in MultiMC and install Immersive Engineering and Immersive Petroleum 

### Suspected cause

an error in the catch forge version code making it not catch the update to version 36

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TobiDoes** [comment]
[https://ibb.co/K0mcFWy
https://ibb.co/WnWRnFr
https://ibb.co/HGM1f1f](url)

**Comment by jamierocks** [comment]
This isn't a bug with MultiMC, but rather game support.

This is a bug tracker for MultiMC, and therefor not the appropriate place for game support. There are many communities which may be able to provide game support for you - the MultiMC Discord being one, but also the Minecraft subreddit, Minecraft Forums, the #minecrafthelp IRC channel, and potentially many more.

**Comment by TobiDoes** [comment]
you cant download the version 36 for forge in MultiMC

**Comment by jotoho** [comment]
I have to say that the issue description does not sound like a game support issue to me. If the launcher fails to show the newer versions for installation then that is a problem with MultiMC and not the game.

At the same time, I am unable to reproduce this issue as MultiMC shows the up-to-date forge versions for me on current development version 417994735a4823782f0f2304695347a13eed9a1d.

@TobiDoes Does this issue still exist after switching to the development channel of MultiMC?

https://github.com/MultiMC/MultiMC5/wiki/Switching-update-channels

**Comment by kb-1000** [comment]
Rather, it sounds like someone is just using an unofficial, modifidd MultiMC build.
Which is not supported here
