### ISSUE TITLE
Add Alpha 1.1.1 to the version selection menu

### ISSUE THREAD

**Issue by Derpitron** [MultiMC/MultiMC5#3922]
### Role

I use old versions of Minecraft.

### Suggestion

I want the version Alpha 1.1.1 to be added to the Java Version selection screen. The .jar file has been found by the OmniArchive team and it has been shown to work properly.

### Benefit

This will allow people to experience a Minecraft version that has been lost for years.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

After 11 years, version Alpha 1.1.1 has been found, thanks to a Twitter user who managed to find it on her old USB drive. This file has been confirmed to be the real 1.1.1 version, and not just 1.1.2. The user collaborated with the OmniArchive team to archive this version of Minecraft and preserve it.

https://archive.org/download/Minecraft-JE-Alpha This version has been added to the Alpha archive,
https://archive.org/download/Minecraft-JE-Classic And some more classic versions have been found as well.

**Comment by phit** [comment]
see https://github.com/MultiMC/MultiMC5/issues/3472

**Comment by Derpitron** [comment]
like I said in my post, this version has been found, verified and successfully archived https://twitter.com/lunasorcery/status/1408785025492000770

**Comment by Janrupf** [comment]
This is not about availability but copyright problems

**Comment by Derpitron** [comment]
Oh I see. Thank you for the clarification
