### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by BenyBoy124555** [MultiMC/MultiMC5#3923]
### Operating System

Windows

### Description of bug

I tried loading the replay mod and i just had to abort

error: https://paste.ee/p/SzThI

someone pls help

### Steps to reproduce

im sorry i forgot how i did it :/

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
