### ISSUE TITLE
Issue with bcprov-jdk15on-147.jar

### ISSUE THREAD

**Issue by josof** [MultiMC/MultiMC5#3926]
### Operating System

Windows

### Description of bug

When attempting to launch a version of Minecraft with forge, 1.4.7, the following error continues to occur https://paste.ee/p/FlLdi

I have downloaded the proper file from java and placed it in the bin folder yet the issue persists. I have tried different versions of the same software, placing the file in the direct MCMulti mods/bin folder, as well as of course the instance bin folder. I have tried about everything I can think of and yet this continues to persist. I attempted to read the thread to stop relying on Minecraft forge's outdated links, but that just pointed me to what I already knew, which was that I'd have to find the javascripts from their original producers. I believe I have done that and again, the problem persists.javascript

### Steps to reproduce

Attempt to launch Minecraft 1.4.7 after clicking the install forge button.

When the error comes up for four missing files, install all of the missing files into the bin folder.

It should still say that the bcprov-jdk15on-147.jar was failed to be acquired, despite the fact that it is already where it is supposed to be.

### Suspected cause

I genuinely have no clue. I fear the file itself that I am downloading is broken in some way? I have tried downloading the file from multiple sources, including the original producer, and still no dice.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Zetabite** [comment]
This is not suprising. Versions below 1.17 need java 8, everything beyond java 16. Java 15 isnt ideal on either

**Comment by phit** [comment]
they are using Java 8 that file name has no connection to JDK15, but instead is a reference to Java 1.5 and newer `bcprov-jdk15on` is the name of the library

**Comment by Zetabite** [comment]
Jesus, i hate the naming schemes. Well, time to look in the log again

**Comment by Zetabite** [comment]
I would guess its maybe the FML server issue? That would require moving to develop to have the fix for that

**Comment by jamierocks** [comment]
This was fixed on the development update channel :)

**Comment by wufe8** [comment]
Written for those who came here through a search engine:
I had the same problem, but I solved it by downloading an existing modpack and extracting the lib files from it, specifically FTB's Direwolf20 1.4.7 modpack. After downloading it, find the jar in the lib folder and copy it to your game directory.


argo-2.25.jar
asm-all-4.0.jar
bcprov-jdk15on-147.jar
guava-12.0.1.jar
![image](https://github.com/user-attachments/assets/8e58976a-e54b-41a7-b23b-d8dd319a9812)
