### ISSUE TITLE
Can't run most installations.

### ISSUE THREAD

**Issue by kevinlejc21** [MultiMC/MultiMC5#3927]
### Operating System

macOS

### Description of bug

They start in a small window and then either turn black(alphas) flicker and break my eyes(beta 1.0) or turn white (other betas). Some mod pack installations close out with this error(or similar). 
https://paste.ee/p/bDnuE 
I have not tried all mod packs so I don't know, but the alphas and betas are definitely not working. Version 1.0 works so it is likely that 1.0 and above works.

### Steps to reproduce

Be on a MacBook Air with Big Sur and install Java(latest version) then download MultiMC and run any alpha or beta version of Minecraft with it. 

### Suspected cause

Might be because these versions require 32-bit computer, operating system or java. I am 100% 64-bit.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Zetabite** [comment]
Your are using java 16, everything under 1.17 needs java 8. For further questions get in touch with a minecraft supporting community, like MMC discord (linked on website)
