### ISSUE TITLE
Instance Session playtime

### ISSUE THREAD

**Issue by LividJava** [MultiMC/MultiMC5#3930]
### Role

N/A this is really a minor suggestion and I like seeing stats.

### Suggestion

With the understanding that the current Playtime indicator has Total time played. The Session would tell you how long your last session was. It would ideally read something like "Version, last session played for 3h 5m, total played for 5d 12h 4m"

### Benefit

So I know how much time I'm wasting playing this game.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by jamierocks** [comment]
![Screenshot_20210713_165504](https://user-images.githubusercontent.com/5103549/125484769-15f432ac-e012-42c5-bef0-a167d6d13361.png)

something like that?

**Comment by LividJava** [comment]
yes exactly like that

**Comment by FeedTheChunk** [comment]
With the addition of the play time added to the info bar at the bottom, now the window width grows as the text get longer.

![image](https://user-images.githubusercontent.com/35508630/127245819-24061603-3825-4637-b5b9-7e0a0b0f31cf.png)

vs.

![image](https://user-images.githubusercontent.com/35508630/127245849-96428666-8637-4b8c-8894-f8193548aec0.png)

I would personally prefer that the bar grow vertically (multi line) and not grow horizontally.

**Comment by Zetabite** [comment]
I would prefer the total time being an option. For me for example, the time isnt even right, since i copy a lot of instances to temper with different stuff. Also i have no need for the times

**Comment by jamierocks** [comment]
This was merged :)

**Comment by Zetabite** [comment]
Doesnt mean we cant discuss on the matter.
