### ISSUE TITLE
Add an experimental 1.18 snapshot to the "Experiments" list in the instance creation menu

### ISSUE THREAD

**Issue by whitebear60** [MultiMC/MultiMC5#3934]
### Role

I want to play with new experimental generation that Mojang released yesterday

### Suggestion

I want the snapshot 1.18-experimental-1 to appear in the Experiments section of MultiMC instance creation menu, as Combat Tests does.

### Benefit

so MultiMC users can play with this if they want to and don't need to download vanilla launcher if they don't want to.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by whitebear60** [comment]
[Minecraft.net article about this snapshot](https://www.minecraft.net/ru-ru/article/new-world-generation-java-available-testing) and [link to download this snapshot from official Minecraft resources](https://launcher.mojang.com/v1/objects/231bba2a21e18b8c60976e1f6110c053b7b93226/1_18_experimental-snapshot-1.zip).

**Comment by heftymouse** [comment]
In the meantime, until it's added to the launcher, you could do this to play it (credit kb1000 from the MultiMC Discord)
> make new instance > Edit instance > Version > Click on "Minecraft" > Customise > Edit > replace everything in the .json that opens with the contents from https://kb1000.de/multimc-meta/net.minecraft/1.18_experimental-snapshot-1.json > Save > Launch

**Comment by whitebear60** [comment]
@heftymouse Thank you!

**Comment by kb-1000** [comment]
MultiMC/meta-upstream#1 should do it.

**Comment by whitebear60** [comment]
This is resolved now, experimental snapshot 1 is now present in MultiMC version list under Experiments section.
