### ISSUE TITLE
 https://paste.ee/p/1zqCI

### ISSUE THREAD

**Issue by Bootstrap21** [MultiMC/MultiMC5#3940]
### Operating System

Windows

### Description of bug

adwadawda https://paste.ee/p/1zqCI

### Steps to reproduce

dawd https://paste.ee/p/1zqCI

### Suspected cause

 https://paste.ee/p/1zqCI

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by RDKRACZ** [comment]
You are using java 8 with Minecraft 1.17.
Java 16 is required.

**Comment by jamierocks** [comment]
Unclear on what the issue is, how to reproduce, and likely to be game support rather than an MultiMC issue.

Please fill our bug report template in properly next time.
