### ISSUE TITLE
打不開模組包 求大神幫助

### ISSUE THREAD

**Issue by hi23392** [MultiMC/MultiMC5#3941]
### Operating System

Windows

### Description of bug

我的模組跑到一半就卡了,點它就變成下面面圖片那樣

### Steps to reproduce

![螢幕擷取畫面 2021-07-18 164522](https://user-images.githubusercontent.com/87599137/126061389-39951f69-a9bd-4cfa-a2d5-7617d3105162.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
Unfortunately we're unable to unable to help with bug reports written in languages other than English.
