### ISSUE TITLE
Unable to play the mod pack, please help

### ISSUE THREAD

**Issue by hi23392** [MultiMC/MultiMC5#3942]
### Description of bug

As long as the program runs to 3, it will be stuck. Click it and it will become the following

### Steps to reproduce

![螢幕擷取畫面 2021-07-18 164522](https://user-images.githubusercontent.com/87599137/126061719-f63ed54c-c0cc-48c2-aea1-ca891f43095f.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by hi23392** [comment]
plese help me

**Comment by phit** [comment]
give your game more memory https://github.com/MultiMC/MultiMC5/wiki/Java-settings

**Comment by Janrupf** [comment]
In case you need further assistance you can come talk to use on the [MultiMC discord](https://discord.gg/multimc)

**Comment by hi23392** [comment]
> 如果您需要進一步的幫助，您可以在[MultiMC Discord](https://discord.gg/multimc)上使用[](https://discord.gg/multimc)

**Comment by hi23392** [comment]
thanks
