### ISSUE TITLE
wierd gui issues

### ISSUE THREAD

**Issue by notahumanthatisimportant** [MultiMC/MultiMC5#3944]
### Operating System

Linux

### Description of bug

when clicking in any gui there is a weird bug that makes some lag or something so when i click on it i have to drag click on it so that it registers i clicked

### Steps to reproduce

launch mc 1.8.9
go to hypixel.net
click on a gui

### Suspected cause

something wrong with the linux build

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by notahumanthatisimportant** [comment]
works normally on offical launcher

**Comment by notahumanthatisimportant** [comment]
here is log 
https://paste.ee/p/8D8bF

**Comment by kb-1000** [comment]
Not a MultiMC bug.
Most likely caused by your mods.

**Comment by kryptochaos** [comment]
@kb1000 they are using only 1gb of ram could that cause issues
