### ISSUE TITLE
CurseForge pack browser missing from stable but are mentioned in the changelog

### ISSUE THREAD

**Issue by KirinFuji** [MultiMC/MultiMC5#3945]
### Operating System

Windows

### Description of bug

Hi just wanted to let you know that the 0.6.12 changelog is misleading. It mentions that CurseForge pack browser has been added. But in the current windows build from the website (0.6.12-1530) it still has Twitch and no CurseForge.

Additionally it says I have no updates available.

I downloaded the Develop version and it does have the CurseForge pack browser.

![image](https://user-images.githubusercontent.com/40347158/126091363-ef881fbe-5d5d-4fcd-a4bd-bc320563539c.png)

### Steps to reproduce

Download the Windows MultiMC version from the main website and check the new instance section.

### Suspected cause

The release version containing the CurseForge pack browser was not uploaded to the website or included in the updater or was mistakenly added to the changelog.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kb-1000** [comment]
After all, it's the same thing, with a different name.
closing.

**Comment by KirinFuji** [comment]
Except It does not work though :/ You can click twitch and nothing loads or shows up.

**Comment by kb-1000** [comment]
Enter a search term...
