### ISSUE TITLE
minecraft freezes while loading older versions

### ISSUE THREAD

**Issue by umjammerlammy1** [MultiMC/MultiMC5#3946]
### Description of bug

I try to load minecraft beta 1.7.3. I have tried multiple different java versions. Nothing works. It always freezes at the same point while loading the game, and I always have to go over to kill the instance.

https://paste.ee/p/rwFxN

### Steps to reproduce

1. create an instance of minecraft b 1.7.3
2. attempt to load it and watch as this miserable bug happens again

### Suspected cause

![image](https://user-images.githubusercontent.com/87675188/126230492-cb3fb851-c6d0-47de-8873-4c5c5e566892.png)
The log always ends with this. I'm pretty sure it has something to do with an issue with controllers? I installed this thing to get Nintendo Switch Pro Controllers working on my computer, and I'm pretty sure it's what's causing everything to fuck up. This wasn't an issue until I installed HIDGuardian and now nothing loads on my god forsaken minecraft game. The thing is, I've tried uninstalling it, and it STILL doesn't work. I'm beginning to wonder if my computer is irreparably damaged in such a way to prevent old minecraft from running, specifically to make me suffer. I'm losing hope.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
This isn't a bug with MultiMC, but rather game support.

This is a bug tracker for MultiMC, and therefor not the appropriate place for game support. There are many communities which may be able to provide game support for you - the MultiMC Discord being one, but also the Minecraft subreddit, Minecraft Forums, the #minecrafthelp IRC channel, and potentially many more.

**Comment by jamierocks** [comment]
Having said that, I did try to reproduce this myself and was unable to.
