### ISSUE TITLE
who can teach me

### ISSUE THREAD

**Issue by hi23392** [MultiMC/MultiMC5#3947]
### Operating System

Windows

### Description of bug

who can teach me

### Steps to reproduce

![螢幕擷取畫面 2021-07-19 230221](https://user-images.githubusercontent.com/87599137/126256265-1a96e459-96d6-4636-9cef-0e72206aca25.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by hi23392** [comment]
plese help

**Comment by phit** [comment]
read the error message and fix it
