### ISSUE TITLE
Add button label is truncuated

### ISSUE THREAD

**Issue by Leo40Git** [MultiMC/MultiMC5#3957]
### Operating System

Windows

### Description of bug

![image](https://user-images.githubusercontent.com/7997354/126703584-fc4c2842-cf7d-4763-9df2-058a8e15483e.png)

A.

### Steps to reproduce

* Open MultiMC.
* That's it.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
Will write up a fix now, thanks for making an issue :)

**Comment by jamierocks** [comment]
Fix merged :)
