### ISSUE TITLE
MultiMC can't run Forge 36.1.66 or 36.2.0 for some reason

### ISSUE THREAD

**Issue by maxsize213** [MultiMC/MultiMC5#3959]
### Operating System

Windows

### Description of bug

When running anything after 36.1.65, it causes this error:
[36.1.66](https://paste.ubuntu.com/p/g2xjhRJ4J7/)
[36.2.0](https://paste.ubuntu.com/p/QNbNWTjw73/)

### Steps to reproduce

1. Create a 1.16.5 profile.
2. Add Forge 36.2.0 or 36.1.66.
3. (optional) Add a compatible mod and it's library, if it has one.
4. It will exit with code -1.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3953
