### ISSUE TITLE
Need to drag items into another open inventory slot to count as a click

### ISSUE THREAD

**Issue by notahumanthatisimportant** [MultiMC/MultiMC5#3962]
### Operating System

Linux

### Description of bug

I should click on an item on a server and it should do the thing that its supposed to but before it does that now i have to drag it into an open slot

### Steps to reproduce

launch minecraft on ubuntu 20.04
luanch multimc
launch minecraft in multimc
join a server (hypixel.net or mineplex.com tried both)

### Suspected cause

i have no freakin clue dude

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your game, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by notahumanthatisimportant** [comment]
not using a modpack and the vanilla launcher works fine

**Comment by Zetabite** [comment]
please refer to the discord link for further help
