### ISSUE TITLE
Need to drag items into another open inventory slot to count as a click

### ISSUE THREAD

**Issue by notahumanthatisimportant** [MultiMC/MultiMC5#3963]
### Operating System

Linux

### Description of bug

I should click on an item on a server and it should do the thing that its supposed to but before it does that now i have to drag it into an open slot

### Steps to reproduce

launch minecraft on ubuntu 20.04
luanch multimc vanilla
launch minecraft in multimc
join a server (hypixel.net or mineplex.com tried both)

### Suspected cause

something to do with the multimc package

ps the vanilla launcher works like normal

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
please refrain from opening more issues, you were already told where to get game support
