### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by StarfireSky** [MultiMC/MultiMC5#3968]
I try to go Multimc Discord but it want to test my phone but my phone does not accept text message what do I do.

**Comment by jamierocks** [comment]
There are other communities that may be able to help, such as the #minecrafthelp IRC channel or one of the many subreddits.

With that said, please stop opening issues here that aren't bugs with MultiMC. It is not the place, we have the discord server for that.

**Comment by jotoho** [comment]
1. I was under the impression that phone verification is not normally mandatory on Discord unless specifically demanded by the server
1. Any phone with a SIM card in it should be able to receive SMS though it may be delayed. If you have difficulties creating a Discord account this isn't the right place for guidance. Check the Discord FAQ or use a search engine to investigate your problem. You'll have to figure this out on your own or get help with Discord from somewhere else. If you cannot get Discord running at all, then you'll have to ask somewhere else. There are many other places on the internet where people would attempt to help you with Minecraft problems like forums or subreddits.
1. Please stop creating new issues or abusing the issue tracker for this. You're only creating spam and causing extra work for the volunteers that help out here in their free time.
