### ISSUE TITLE
.appimage version?

### ISSUE THREAD

**Issue by AlexKari** [MultiMC/MultiMC5#3975]
Why not have a .appimage version for linux? Qt5 is fairly easy to make an .appimage, and it'd make it more portable for systems lacking Qt5.

**Comment by jamierocks** [comment]
Please follow our suggestion template.

**Comment by phit** [comment]
also no, use the search

https://github.com/MultiMC/MultiMC5/issues/3183#issuecomment-638822464
https://github.com/MultiMC/MultiMC5/issues/3149#issuecomment-628671958
