### ISSUE TITLE
Job 'Asset index for 1.17.1' failed to process

### ISSUE THREAD

**Issue by TheChilliPL** [MultiMC/MultiMC5#3976]
### Operating System

Windows

### Description of bug

A couple of days after reinstalling Windows, I decided to start MultiMC and try running 1.17.1. I installed Java (OpenJDK 16.0.2 x64) and tried running it. Logged in, created a new instance, and selected 1.17.1.

<details>
<summary>
Trying to start it, I got an error in the Minecraft log (click here to expand):
</summary>

```
MultiMC version: 0.6.12-1530


Minecraft folder is:
G:/MultiMC/instances/1.17.1/.minecraft


Java path is:
P:/Java/jdk-16.0.2/bin/java.exe


Checking Java version...
Java is version 16.0.2, using 64-bit architecture, from Oracle Corporation.


Instance update failed because: Failed to download the assets index:
Job 'Asset index for 1.17.1' failed to process:
https://launchermeta.mojang.com/v1/packages/e5af543d9b3ce1c063a97842c38e50e29f961f00/1.17.json


```

</details>

Version: 0.6.12-1530
Platform: win32
Built Number: 1530
Channel: stable

Found similar closed issues but they're closed due to inability to reproduce.

### Steps to reproduce

Not sure if it can be reproduced, for me it'd be
- Start MultiMC
- Add a new instance with vanilla 1.17.1
- Try starting it

### Suspected cause

I have no idea what could be the cause. I have no problems with my internet in general and it seems like MultiMC is unable to download the file.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheChilliPL** [comment]
Seems like I get similar errors with all the other instances I have

**Comment by ppoozl** [comment]
Seems like a network error?

**Comment by phit** [comment]
Looks like your PC is unable to reach the Mojang servers, could be firewall, DNS, antivirus, etc., not much we can do about this here. If you need further help with this try the #technology channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by TheChilliPL** [comment]
Let me just say here in case someone encounters a similar issue:
My problem was with Windows NTFS permissions. MultiMC didn't have permission to write in its folder. Had to open its properties and add my user a write permission in the security tab.
