### ISSUE TITLE
No Forge for 1.17.1

### ISSUE THREAD

**Issue by Bloodlex** [MultiMC/MultiMC5#3977]
### Operating System

Windows

### Description of bug

No Forge for 1.17.1 available, although it's been already released

### Steps to reproduce

No Forge for 1.17.1 available, although it's been already released

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Zetabite** [comment]
Duplicate of #3953
Duplicate of #3960

**Comment by spannerman79** [comment]
Duplicate of https://github.com/MultiMC/MultiMC5/issues/3936
