### ISSUE TITLE
Can't seem to craft Enhanced Superconductor

### ISSUE THREAD

**Issue by MirranM** [MultiMC/MultiMC5#3978]
### Description of bug

Recipe shows 4 regular conductors and a Efficiency V enchanted Book. 

When I add the items by the recipe button it adds 1 conductor and 1 book but it shows no recipe.

Adding in the 4 conductors and the book also does not start the Fusion Control Computer.  [https://imgur.com/a/8wSWhc6](url)

### Steps to reproduce

Insert items?

### Suspected cause

Wrong ID for the book maybe?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by heftymouse** [comment]
This isn't a problem with MultiMC so this isn't the right place to report such a thing.
