### ISSUE TITLE
Sync / Symboliclink folders

### ISSUE THREAD

**Issue by Redostrike** [MultiMC/MultiMC5#3980]
### Role

I use schematics a lot.

### Suggestion

There should be a way to be able to sync specific folders or make them a symbolic link so they appear on every instances

### Benefit

You don't need to manually copy over schematics from litematica anymore (currently i made my own setup but no techy people might not be able to do this)

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
You can symlink folders manually. MultiMC is a portable application, symlinks are not, especially cross OS. So this will not become an integrated feature, especially for something mod specifc like schematics.

Some related issues: https://github.com/MultiMC/MultiMC5/issues/3445#issuecomment-733224473 https://github.com/MultiMC/MultiMC5/issues/3861
