### ISSUE TITLE
JAVA

### ISSUE THREAD

**Issue by Ghosthack89** [MultiMC/MultiMC5#3984]
### Operating System

Windows

### Description of bug

when trying to load an instance the java file path is not allowing a connection even though i have java8u301

### Steps to reproduce

installed multimmc twice and uninstalled java8u301 and installed again twice

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jotoho** [comment]
You failed to provide any log. See this wiki article on how to upload it (the method is mandatory): https://github.com/MultiMC/MultiMC5/wiki/Minecraft-Logs#uploading-logs

**Comment by Ghosthack89** [comment]
MultiMC version: 0.6.12-1530


Minecraft folder is:
C:/Users/ghost/Desktop/MultiMC/MultiMC/instances/FTB Presents Direwolf20 1.16/minecraft


Java path is:
C:/Users/ghost/Desktop/Java/bin/javaws.exe


Checking Java version...
Java checker returned some invalid data MultiMC doesn't understand:


Minecraft might not start properly.
Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/ghost/Desktop/MultiMC/MultiMC/instances/FTB Presents Direwolf20 1.16/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/1.5.1/ForgeWrapper-1.5.1.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/net/minecraftforge/forge/1.16.5-36.1.23/forge-1.16.5-36.1.23-launcher.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/ow2/asm/asm/9.0/asm-9.0.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/ow2/asm/asm-commons/9.0/asm-commons-9.0.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/ow2/asm/asm-tree/9.0/asm-tree-9.0.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/ow2/asm/asm-util/9.0/asm-util-9.0.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/ow2/asm/asm-analysis/9.0/asm-analysis-9.0.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/cpw/mods/grossjava9hacks/1.3.3/grossjava9hacks-1.3.3.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/com/electronwill/night-config/core/3.6.3/core-3.6.3.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/com/electronwill/night-config/toml/3.6.3/toml-3.6.3.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.11.2/log4j-core-2.11.2.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/net/minecraftforge/nashorn-core-compat/15.1.1.1/nashorn-core-compat-15.1.1.1.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/com/mojang/patchy/1.2.3/patchy-1.2.3.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/ghost/Desktop/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar

Mods:
  [✔️] absentbydesign-1.16.5-1.4.1
  [✔️] AppleSkin-mc1.16.2-forge-1.0.14
  [✔️] appliedenergistics2-8.3.1
  [✔️] archers_paradox-1.16.4-1.2.0
  [✔️] architectury-1.14.157-forge
  [✔️] ars_nouveau-1.16.4-1.16.2
  [✔️] astralsorcery-1.16.4-1.13.9
  [✔️] BetterAdvancements-1.16.5-0.1.0.105
  [✔️] BloodMagic-1.16.4-3.1.0-15
  [✔️] Bookshelf-1.16.5-10.0.7
  [✔️] Botania-1.16.5-416
  [✔️] BotanyPots-1.16.5-7.0.17
  [✔️] BotanyTrees-1.16.5-3.0.5
  [✔️] buildinggadgets-1.16.5-3.8.0
  [✔️] bwncr-1.16.4-3.9.16
  [✔️] cc-tweaked-1.16.4-1.95.3
  [✔️] charginggadgets-1.3.0
  [✔️] chiselsandbits-0.3.4-RELEASE
  [✔️] chocolate-1.3.0-1.16.4
  [✔️] ChunkNoGoByeBye-1.16.5-1.3.0
  [✔️] citadel-1.6.3
  [✔️] cloth-config-4.11.26-forge
  [✔️] Clumps-6.0.0.22
  [✔️] CodeChickenLib-1.16.4-3.5.1.408-universal
  [✔️] cofh_core-1.16.4-1.2.1
  [✔️] comforts-forge-1.16.5-4.0.0.4
  [✔️] CommonCapabilities-1.16.5-2.7.0
  [✔️] compactmachines-4.0.0-beta.2
  [✔️] Controlling-7.0.0.16
  [✔️] CookingForBlockheads_1.16.5-9.3.1
  [✔️] create-mc1.16.5_v0.3.1c
  [✔️] culinaryconstruct-forge-1.16.5-4.0.0.6
  [✔️] curios-forge-1.16.5-4.0.5.1
  [✔️] Cyclic-1.16.5-1.2.7
  [✔️] CyclopsCore-1.16.5-1.11.6
  [✔️] DarkUtilities-1.16.5-8.0.9
  [✔️] DefaultOptions_1.16.3-12.2.0
  [✔️] DeLogger-1.16.5-1.0.9+mc-1.16.5
  [✔️] doomangelring-1.16.4-1.0.0
  [✔️] DungeonCrawl-1.16.3-2.2.4
  [✔️] elevatorid-1.16.5-1.7.13
  [✔️] emojiful-1.16.4-2.1.4
  [✔️] EnchantmentDescriptions-1.16.5-7.0.8
  [✔️] EnderStorage-1.16.4-2.7.1.166-universal
  [✔️] ensorcellation-1.16.4-1.2.0
  [✔️] entangled-1.3.2-mc1.16.5
  [✔️] entitydetectors-1.16.4-1.1.0.1
  [✔️] envirocore-1.16.5-3.0.8.0
  [✔️] envirotech-1.16.5-3.0.8.0
  [✔️] extcaves-2.4
  [✔️] ExtraStorage-1.16.4-1.3.1
  [✔️] ExtremeReactors2-1.16.4-2.0.23
  [✔️] extremeSoundMuffler-3.11_Forge-1.16.5
  [✔️] FastFurnace-1.16.4-4.4.0
  [✔️] FastLeafDecay-v25
  [✔️] FastWorkbench-1.16.4-4.5.1
  [✔️] ferritecore-2.0.4-forge
  [✔️] findme-1.16.3-2.2.0.0
  [✔️] flatbedrock-1.16.4-1.1.6
  [✔️] FluxNetworks-1.16.5-6.1.7.12
  [✔️] ftbauxilium-forge-1605.1.1-build.14-forge
  [✔️] ftb-backups-2.1.1.6
  [✔️] ftb-chunks-1605.2.3-build.75
  [✔️] ftb-essentials-1604.1.0.13
  [✔️] ftb-gui-library-1605.2.1.41-forge
  [✔️] ftb-janitor-1604.1.1-build.20
  [✔️] ftb-ranks-1604.1.1.11
  [✔️] ftb-teams-1604.1.0.16-forge
  [✔️] geckolib-forge-1.16.5-3.0.35
  [✔️] glassential-forge-1.16.5-1.1.6
  [✔️] gravestone-1.16.5-1.0.4
  [✔️] harvest-1.16.3-1.0.3
  [✔️] ice_ice_baby-1.16.4-3.0.1
  [✔️] ImmersiveEngineering-1.16.5-4.2.4-134
  [✔️] immersiveposts-1.16.5-4.0.0
  [✔️] industrial-foregoing-1.16.5-3.2.11-55cb112
  [✔️] IntegratedCrafting-1.16.5-1.0.15
  [✔️] IntegratedDynamics-1.16.5-1.8.2
  [✔️] integratednbt-1.16.4-1.4.2
  [✔️] IntegratedTerminals-1.16.5-1.2.3
  [✔️] IntegratedTunnels-1.16.5-1.8.1
  [✔️] inventorysorter-1.16.1-18.1.0
  [✔️] ironchest-1.16.4-11.2.10
  [✔️] itemcollectors-1.0.11-mc1.16.5
  [✔️] JAMD-1.1.9-beta+mc-1.16.5
  [✔️] JAVD-2.5.45+mc-1.16.5
  [✔️] jei-1.16.5-7.7.0.98
  [✔️] jeiintegration_1.16.5-7.0.1.15
  [✔️] JustEnoughProfessions-1.16.5-1.2.1
  [✔️] JustEnoughResources-1.16.4-0.12.0.109
  [✔️] Krate-1.16.5-0.1.4
  [✔️] kubejs-1605.3.8-build.198-forge
  [✔️] kubejs-blood-magic-1604.1.0.4
  [✔️] kubejs-create-1604.1.0.4
  [✔️] kubejs-immersive-engineering-1604.1.0.12
  [✔️] kubejs-mekanism-1604.1.1.6
  [✔️] kubejs-thermal-1605.1.1.6
  [✔️] kubejs-ui-1605.1.3-build.4-forge
  [✔️] lanterncolors-1.16.3-2.1.1
  [✔️] LibX-1.16.3-1.0.63
  [✔️] light-overlay-5.8.1
  [✔️] Lollipop-1.16.5-3.2.9
  [✔️] mana-and-artifice-1.3.0.6
  [✔️] Mantle-1.16.5-1.6.97
  [✔️] mcjtylib-1.16-5.0.19
  [✔️] mcw-bridges-1.0.5-mc1.16.5-4
  [✔️] mcw-doors-1.0.2-mc1.16.5
  [✔️] mcw-roofs-2.0.1-mc1.16.5-4
  [✔️] mcw-trapdoors-1.0.2-mc1.16.5
  [✔️] mcw-windows-1.0.3-mc1.16.5
  [✔️] Mekanism-1.16.5-10.0.21.448
  [✔️] MekanismGenerators-1.16.5-10.0.21.448
  [✔️] MekanismTools-1.16.5-10.0.21.448
  [✔️] mgui-1.16.5-3.2.0
  [✔️] minecolonies-0.14.169-ALPHA-universal
  [✔️] MiniCoal2-1.16.1-0.0.2-universal
  [✔️] mininggadgets-1.7.5
  [✔️] modnametooltip_1.16.2-1.15.0
  [✔️] modular-routers-1.16.5-7.4.0-55
  [✔️] moredragoneggs-1.4
  [✔️] Morpheus-1.16.5-4.2.70
  [✔️] MouseTweaks-2.14-mc1.16.2
  [✔️] movingelevators-1.2.34-mc1.16.5
  [✔️] MythicBotany-1.16.4-1.3.10
  [✔️] NaturesAura-34.2
  [✔️] NaturesCompass-1.16.5-1.8.6
  [✔️] observerlib-1.16.4-1.5.1
  [✔️] Patchouli-1.16.4-51
  [✔️] Placebo-1.16.4-4.4.5
  [✔️] pneumaticcraft-repressurized-1.16.5-2.12.4-188
  [✔️] pocketstorage-1.16.3-0.7.6
  [✔️] portality-1.16.4-3.2.2
  [✔️] Powah-1.16.5-2.3.16
  [✔️] PrettyPipes-1.9.3
  [✔️] Psi 1.16-94
  [✔️] QuantumStorage-1.16.4-5.3.0
  [✔️] quartz-chests-1603.1.0.8
  [✔️] rangedpumps-0.8.2
  [✔️] ratlantis-1.0.0-1.16.3
  [✔️] rats-7.1.1-1.16.5
  [✔️] recipebuffers-2.1
  [✔️] refinedpipes-0.5
  [✔️] refinedstorage-1.9.12
  [✔️] refinedstorageaddons-0.7.2
  [✔️] reliquary-1.16.5-1.3.5.1098
  [✔️] restrictions-1.16-3.0.3
  [✔️] rftoolsbase-1.16-2.0.10
  [✔️] rftoolsbuilder-1.16-3.0.17
  [✔️] rftoolscontrol-1.16-4.0.10
  [✔️] rftoolsdim-1.16-7.0.9-beta
  [✔️] rftoolspower-1.16-3.0.8
  [✔️] rftoolsstorage-1.16-2.0.12
  [✔️] rftoolsutility-1.16-3.0.26
  [✔️] rhino-1.7.13-build.24
  [✔️] rsgauges-1.16.4-1.2.10
  [✔️] rsrequestify-1.16.3-2.0.1
  [✔️] Runelic-1.16.5-7.0.1
  [✔️] serverconfigupdater-1.3
  [✔️] Shrink-1.16.4-1.0.7
  [✔️] shutupexperimentalsettings-1.0.3
  [✔️] simplemagnets-1.1.2-mc1.16.5
  [✔️] simplybackpacks-1.16.3-1.4.13
  [✔️] SimplyJetpacks2-1.16.5-2.6.7.1
  [✔️] snad-1.0.5-1.16.5
  [✔️] SpawnerFix-1.16.2-1.0.0.2
  [✔️] Statues-1.16.5-0.1.6.8
  [✔️] StorageDrawers-1.16.3-8.2.2
  [✔️] structurize-0.13.173-ALPHA-universal
  [✔️] supermartijn642configlib-1.0.6-mc1.16
  [✔️] supermartijn642corelib-1.0.3-mc1.16.5
  [✔️] TConstruct-1.16.5-3.0.3.152
  [✔️] tetra-1.16.5-3.10.0
  [✔️] The_Undergarden-1.16.5-0.5.1
  [✔️] theoneprobe-1.16-3.1.3
  [✔️] thermal_cultivation-1.16.4-1.2.0
  [✔️] thermal_expansion-1.16.4-1.2.0
  [✔️] thermal_foundation-1.16.4-1.2.0
  [✔️] thermal_innovation-1.16.4-1.2.0
  [✔️] thermal_locomotion-1.16.4-1.2.0
  [✔️] TipTheScales-1.16.5-3.0.0.11
  [✔️] titanium-1.16.5-3.2.8.2
  [✔️] Toast-Control-1.16.4-4.3.1
  [✔️] torchmaster-2.3.7
  [✔️] trashcans-1.0.10-mc1.16.5
  [✔️] twilightforest-1.16.5-4.0.435-universal
  [✔️] valkyrielib-1.16.5-3.0.8.0
  [✔️] Waystones_1.16.5-7.5.1
  [✔️] woot-1.16.5-1.0.7.0
  [✔️] wormhole-1.1.8-mc1.16.5
  [✔️] xnet-1.16-3.0.13
  [✔️] XNetGases-1.16.5-2.2.6
  [✔️] ZeroCore2-1.16.4-2.0.21

Params:
  --username  --version MultiMC5 --gameDir C:/Users/ghost/Desktop/MultiMC/MultiMC/instances/FTB Presents Direwolf20 1.16/minecraft --assetsDir C:/Users/ghost/Desktop/MultiMC/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4736m, -Duser.language=en]


Minecraft process ID: 25256


Process exited with code -1.
MultiMC: Log upload triggered at: 03 Aug 2021 00:19:26 +0100

**Comment by Zetabite** [comment]
seems like you havent read through the linked sites. Please upload the log as shown.

**Comment by spannerman79** [comment]
> Checking Java version...
> Java checker returned some invalid data MultiMC doesn't understand:

Invalid Java install.  Or self built (and borked it up).

Either way - follow https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java
