### ISSUE TITLE
Cant login with my microsoft minecraft account

### ISSUE THREAD

**Issue by BrakoGrimly** [MultiMC/MultiMC5#3985]
### Operating System

Windows

### Description of bug

i entered my microsoft minecraft account and password to login but its showing inalid credentials

### Steps to reproduce

idk

### Suspected cause

i guess its becuz of java or somethin but i have java installed already

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by BrakoGrimly** [comment]
pls help somebody

**Comment by BrakoGrimly** [comment]
if not microsoft what are the other options to log in

**Comment by Zetabite** [comment]
Only mojang account, which can be no longer legally obtained. MSA implementation is in the works. The issue will be unpinned once its ready.
