### ISSUE TITLE
When I launch I get exit code -1 without any minecraft window appearing 

### ISSUE THREAD

**Issue by Gh0stChaos** [MultiMC/MultiMC5#3988]
### Operating System

Windows

### Description of bug

Every time I launch it tries to run but then opens the error log without a minecraft window appearing

### Steps to reproduce

Not too sure

### Suspected cause

My integrated graphics and Java version 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Gh0stChaos** [comment]
By the way I saw another post with the same issues but that fix didn’t work for me

**Comment by phit** [comment]
post your log https://github.com/MultiMC/MultiMC5/wiki/Minecraft-Logs#usage

**Comment by Gh0stChaos** [comment]
> 
> 
> post your log https://github.com/MultiMC/MultiMC5/wiki/Minecraft-Logs#usage

https://paste.ee/p/wi3q3

**Comment by jotoho** [comment]
There's a slightly newer Forge version for 1.12.2 -> (`14.23.5.2854` (yours) vs `14.23.5.2855` (latest & recommended version)) but I find it unlikely for that to be the cause. Likely doesn't hurt to update anyway.

My best **guess** would be some kind of incompatibility between those mods you have installed. Maybe try disabling all mods and then launching MC without it? If that works then you can re-enable them one-by-one and attempt running MC after each time to see when launching the game fails. That way you may be able to learn which mod is causing your problems.

Your issue could also be something else entirely though. :man_shrugging:
I'm not an expert on this topic.

**Comment by jamierocks** [comment]
This isn't a bug with MultiMC, but rather game support.

This is a bug tracker for MultiMC, and therefore not the appropriate place for game support. There are many communities which may be able to provide game support for you - the MultiMC Discord being one, but also the Minecraft subreddit, Minecraft Forums, the #minecrafthelp IRC channel, and potentially many more.
