### ISSUE TITLE
When I run normal minecraft it exits with code -1

### ISSUE THREAD

**Issue by Gh0stChaos** [MultiMC/MultiMC5#3989]
### Operating System

Windows

### Description of bug

I ran a standard version on minecraft and just got an error log without seeing any minecraft window 

Log: https://paste.ee/p/4C8WQ

btw was another issue the same that fix didn’t work for me

### Steps to reproduce

Not sure

### Suspected cause

Java/my graphics

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Janrupf** [comment]
This isn't a bug with MultiMC, but rather game support.

This is a bug tracker for MultiMC, and therefore not the appropriate place for game support. There are many communities which may be able to provide game support for you - the MultiMC Discord being one, but also the Minecraft subreddit, Minecraft Forums, the #minecrafthelp IRC channel, and potentially many more.
