### ISSUE TITLE
MultiMC is not supporting forge 1.17.1

### ISSUE THREAD

**Issue by myoun** [MultiMC/MultiMC5#3990]
### Operating System

Windows

### Description of bug

MultiMC is not supporting forge 1.17.1
https://files.minecraftforge.net/net/minecraftforge/forge/

### Steps to reproduce

* Create Minecraft 1.17.1 instance
* click install forge

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kb-1000** [comment]
Duplicate of #3936
