### ISSUE TITLE
Multimc cannot log in to Microsoft account

### ISSUE THREAD

**Issue by LiuShu2694** [MultiMC/MultiMC5#3991]
### Description of bug

Multimc cannot log in to Microsoft account，I hope you can add a Microsoft account

### Steps to reproduce

Multimc cannot log in to Microsoft account，I hope you can add a Microsoft account

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Janrupf** [comment]
>  I have searched the issue tracker and did not find an issue describing my bug.
I don't think so.

Duplicate of #3392
