### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by FeedTheChunk** [MultiMC/MultiMC5#3993]
### Role

Trying to build on Ubuntu.

### Suggestion

The Build Instructions seem to be out of date.  Qt 5.6. no longer seems to be available.  The insaller only goes back to v 5.9.

### Benefit

Make a Linux from he git.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

.

**Comment by ImperatorStorm** [comment]
> The Build Instructions seem to be out of date. Qt 5.6. no longer seems to be available. The insaller only goes back to v 5.9.

MultiMC should build perfectly fine with newer versions of Qt5, I've been building MultiMC with Qt 5.15, and it builds perfectly fine.

**Comment by phit** [comment]
use the qt available for your distro like the docs say

**Comment by peterix** [comment]
5.6 is required to build for all the target platforms.

**Comment by peterix** [comment]
And 5.4 is the version MultiMC is built on Linux, actually.
