### ISSUE TITLE
Adoptium JDK's are not auto-detected

### ISSUE THREAD

**Issue by ruifung** [MultiMC/MultiMC5#3996]
### Operating System

Windows

### Description of bug

Eclipse Adoptium (Formerly AdoptOpenJDK) java installations are not autodetected.

https://adoptium.net/

### Steps to reproduce

- Install JDK from Adoptium
- JDK installation not auto detected

Installation paths look something like
C:/Program Files/Eclipse Foundation/jdk-16.0.2.7-hotspot/bin/javaw.exe

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Zetabite** [comment]
switch to dev branch

**Comment by phit** [comment]
added in develop
