### ISSUE TITLE
Account MultiMC

### ISSUE THREAD

**Issue by Fortblox172010045** [MultiMC/MultiMC5#3998]
### Operating System

Windows

### Description of bug

When I add an account it tells me "The authentication server didn't specify a profile. The account exists, but it's probably not premium", even though I'm premium

### Steps to reproduce

When I click the ok button on add account

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
When did you buy the game?

**Comment by insomnia-creator** [comment]
Won't work with Microsoft accounts.

**Comment by phit** [comment]
When exactly? I suspect you have an old non premium Mojang account and then used the same details to buy the game from Microsoft. If you bought the game after the 30th of November 2020, you can not use MultiMC right now.

**Comment by Fortblox172010045** [comment]
> Quando esattamente? Sospetto che tu abbia un vecchio account Mojang non premium e che abbia utilizzato gli stessi dettagli per acquistare il gioco da Microsoft. Se hai acquistato il gioco dopo il 30 novembre 2020, non puoi utilizzare MultiMC in questo momento.

I downloaded it in January. I had a non-premium account where I used the same details to purchase the game, just like you said. What should I do in this case?

**Comment by phit** [comment]
Wait for MultiMC to support Microsoft accounts and use the official launcher until then.

**Comment by Fortblox172010045** [comment]
> Attendi che MultiMC supporti gli account Microsoft e utilizza il launcher ufficiale fino a quel momento.

Ok
