### ISSUE TITLE
Microsoft accounts unusable

### ISSUE THREAD

**Issue by redvoltron** [MultiMC/MultiMC5#3999]
### Description of bug

I can't log in with my migrated minecraft account

### Steps to reproduce

Migrate account to microsoft, then attempt to add said account

### Suspected cause

not the same database?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
> I have searched the issue tracker and did not find an issue describing my bug.

no you didn't
