### ISSUE TITLE
não consigo logar na minha conta da mojang com menos de 16 caracteres

### ISSUE THREAD

**Issue by enzogamerbc2** [MultiMC/MultiMC5#4001]
### Operating System

Other

### Description of bug

não consigo logar na minha conta da mojang

### Steps to reproduce

jjjjjj

### Suspected cause

causa da senha

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
We're unable to provide support in languages other than English.

**Comment by enzogamerbc2** [comment]
I can't log into my mojang account with less than 16 characters

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Jamie ***@***.***>
Enviado:quinta-feira, 12 de agosto de 2021 17:39
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [MultiMC/MultiMC5] não consigo logar na minha conta da mojang com menos de 16 caracteres (#4001)


We're unable to provide support in languages other than English.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMultiMC%2FMultiMC5%2Fissues%2F4001%23issuecomment-897951966&data=04%7C01%7C%7C09ccbc6c38844c01558808d95dd138ac%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637643975445941722%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NkDPAeQRH9Z8TDq5mhFTu5ToXKf5wwNLzIVfYAgUWK0%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVF5WU3KN34IIZD4ZDWJXX3T4QWONANCNFSM5CCDMR4Q&data=04%7C01%7C%7C09ccbc6c38844c01558808d95dd138ac%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637643975445941722%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=m0M53lihTbxxb2oiJP12u0kRcrEg5EhPvRFP4fFSsEU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C09ccbc6c38844c01558808d95dd138ac%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637643975445951717%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0r1MjXUcoSbepKci7BxwOTEd07qhLSpik11bS6pn1kQ%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7C%7C09ccbc6c38844c01558808d95dd138ac%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637643975445961713%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8b47alZr10TRom9dX64jX8dOeEkT5MOBIAs9c5vMwak%3D&reserved=0>.
