### ISSUE TITLE
Support for environment variables within java path

### ISSUE THREAD

**Issue by Carterpersall** [MultiMC/MultiMC5#4005]
### Role

I play vanilla and modded minecraft

### Suggestion

Add support for environment variables within java path

### Benefit

so that I don't have to change the java path every time I open multimc portable on another device

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I often swap between my personal pc and my laptop as I go to school or swap my parent's houses. Due to this, I try to make as many programs I use as possible portable to allow me to upload them to onedrive and pick up where I left off on my other computer. But due to the different locations of onedrive on both of my computers, I have to change the java path every time I change devices. To fix this I would like to be able to use the environment variable %onedrive% within the java path to prevent this issue. Example here of what I would like to do:
![image](https://user-images.githubusercontent.com/60557606/129453095-8b145601-1603-48d2-9a9f-acddb9ad3a59.png)

**Comment by peterix** [comment]
You can put the java in a subfolder of MultiMC. It should work without any extra features.

**Comment by Carterpersall** [comment]
I tried that and it works now. Thanks! Hopefully now that this is here people won't have to waste as much time googling as I did.
