### ISSUE TITLE
Launch crash on Linux (OpenSUSE) with FTB Continuum 1.6.0

### ISSUE THREAD

**Issue by kisachi5** [MultiMC/MultiMC5#4006]
I am using MultiMC to launch Vanilla Minecraft on my OpenSUSE Leap 15.2 laptop  ever since Mojang managed to make their launcher not work anymore.

Now a friend invited me to play FTB Continuum 1.6.0 with me on a server, but the launch crashes.

Error report: https://paste.ee/p/jhAol

**Comment by phit** [comment]
https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java

For future game support please use the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
