### ISSUE TITLE
Account skins aren't loaded by the launcher unless they are Microsoft accounts.

### ISSUE THREAD

**Issue by MrMelon54** [MultiMC/MultiMC5#4009]
### Operating System

Linux

### Description of bug

Skins for mojang accounts don't load in the launcher.

### Steps to reproduce

Open MultiMC on the latest dev version.

### Suspected cause

One of the commits for microsoft account login probably causes this but not sure why?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
Skins have disappeared for me too :(

**Comment by phit** [comment]
> [11:09 AM] peterix: skins get updated on login/refresh
[11:09 AM] peterix: currently
[11:10 AM] peterix: so start the game and it should be updated

**Comment by MrMelon54** [comment]
Ok that resolved my issue but I'll leave this open as it would be useful to load skins when MultiMC is opened if they can't be loaded from cache files.

**Comment by bryiewes** [comment]
**there was a recent commit that appears to have fixed this**

**Comment by MrMelon54** [comment]
If this was fixed then just reply with the commit hash and I can close this issue

**Comment by peterix** [comment]
The issue as described does not exist.
