### ISSUE TITLE
Some Curseforge modpacks are missing from the Twitch modpack search

### ISSUE THREAD

**Issue by bbb651** [MultiMC/MultiMC5#4010]
### Operating System

Linux

### Description of bug

Some Curseforge modpacks don't show up in the Twitch modpack search when creating a new instance, such as `Ultimate Origins Modpack`.

### Steps to reproduce

- Click on create instance
- Click on Twitch in the sidebar
- Search for an affected modpack such as `Ultimate Origins Modpack` (or search it's Curseforge page url)
    - All modpacks that were made somewhat recently seem to be affected, a good way to find them is to look at all [modpacks sorted by creation date](https://www.curseforge.com/minecraft/modpacks?filter-game-version=&filter-sort=1)
- The modpack doesn't show up

### Suspected cause

I noticed that a while ago Curseforge stopped offering zip downloads for modpacks, instead forcing people to use their launcher, it seems that all the affected modpacks are relatively recent ones, I suspect it effects all modpacks created after this change. I haven't found examples but I also suspect that modpacks that are updated after zip downloads were removed are not getting those updates in MultiMC.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by bbb651** [comment]
Also worth mentioning that the same modpacks appear to be missing from [GDLauncher](https://github.com/gorilla-devs/GDLauncher) as well, so it's probably something related to Curseforge changes.

**Comment by phit** [comment]
update to the MultiMC dev version
