### ISSUE TITLE
Microsoft login fails: client_id input parameter missing

### ISSUE THREAD

**Issue by just-dev-creator** [MultiMC/MultiMC5#4012]
### Operating System

Linux

### Description of bug

When logging in using a microsoft account, an error is displayed that states that the parameter "client_id" isn't included in the request. 
![German error message](https://user-images.githubusercontent.com/67005012/129572117-5a0a6715-6e29-4012-bcff-d06c324ab8c2.png)
***translated:** Microsoft | Account
Your request couldn't be fullfilled*

### Steps to reproduce

- Open the account menu
- Click the "Add Microsoft" button

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
where did you download MultiMC from?

**Comment by TheFrenchGhosty** [comment]
@phit Same problem, using the AUR package multimc-git

**Comment by kb-1000** [comment]
Switch to multimc-bin

**Comment by TheFrenchGhosty** [comment]
@kb-1000 -bin doesn't support microsoft accounts.

**Comment by kb-1000** [comment]
Change your update channel in settings to develop then.

**Comment by TheFrenchGhosty** [comment]
@kb-1000 It worked this way (thanks!), though this is still an issue.

**Comment by kb-1000** [comment]
It's not... multimc-bin is recommended over multimc-git now.
multimc-bin uses the binary packages available from https://multimc.org.

**Comment by TheFrenchGhosty** [comment]
@kb-1000 I understand, but if users can't build a working package themselves something is wrong.

**Comment by Janrupf** [comment]
The git package is deprecated basically now. It should be removed

**Comment by kb-1000** [comment]
> I understand, but if users can't build a working package themselves something is wrong.

They can, but it requires doing stuff that you really can't expect an end user to do (I won't give further details about that here)

**Comment by peterix** [comment]
I cannot be personally responsible for builds made by users.

**Comment by jamierocks** [comment]
While this is a packaging issue, GH-4017 will help the situation by disabling the button in builds without a client ID.

**Comment by just-dev-creator** [comment]
As this specific issue is caused from the aur package and therefore not an bug in MultiMC, closing this issue makes sense. Personally, the solution of @kb-1000 worked for me. GH-4017 is a nice addition, but does not solve the problem specified in this bug report as this - as said earlier - is a packaging problem. 

Thanks to all of you for your quick help.
