### ISSUE TITLE
MultiMC downloading old versions of Twitch/Curseforge modpacks.

### ISSUE THREAD

**Issue by yablock0** [MultiMC/MultiMC5#4016]
### Operating System

Windows

### Description of bug

The version of a modpack you download is one or several versions older than the recent version. But only on some modpacks.

### Steps to reproduce

1. Start downloading a Twitch/Curseforge modpack (Valhelsia 3 in my case)
2. See that version downloading is not recent in the loading window.
![image](https://user-images.githubusercontent.com/67269084/129672552-b089d0de-f13e-4111-93a7-a6356597720f.png)
3. The instance is playable, but the mods are outdated.
![image](https://user-images.githubusercontent.com/67269084/129672836-8492e27a-8356-4cb2-bf11-ce4a83f870cd.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
update to the development version this has been fixed already
