### ISSUE TITLE
Infinite loading if MSA has 2FA enabled

### ISSUE THREAD

**Issue by Aeroshide** [MultiMC/MultiMC5#4018]
### Operating System

Windows

### Description of bug

When trying to launch the game if the MSA account has 2FA enabled it would just infinitely displaying "Logging in as Microsoft User", and MultiMC becomes unresponsive. It works fine if 2FA is disabled though.

### Steps to reproduce

1.  Sign in with a Microsoft Account (that is linked you your MC java account) to MultiMC
2. Go to https://aka.ms/account
3. Click on security
4. Click advanced security options
5. Look for additional security, there should be something like "Turn on 2FA" or something like that and turn that on
6. Now restart MultiMC and try to launch any instance

### Suspected cause

MultiMC apparently doesn't know what to do if Microsoft challenged 2FA, I'm guessing the method of getting access token for MSA is still very primitive, I have no idea if its actually a limitation or just an unfinished feature.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Aeroshide** [comment]
Just giving an update, this is still an issue, (develop-2402)
and maybe to make it clearer, ill provide a screenshot
![Screenshot_139](https://user-images.githubusercontent.com/78432778/130372460-bdc5a6f7-e5f0-4755-9b87-7a15619d0a30.png)

If any additional information is needed, I'm happy to provide more.

**Comment by peterix** [comment]
That is totally nonsensical...

**Comment by peterix** [comment]
Right... log in again by adding the account once you activate 2fa

I did some testing and the MS 2fa seems really weak though... it has so many exceptions that the 2fa check never triggered after I enabled it.

**Comment by Aeroshide** [comment]
Nice, re-adding the account works!, thanks for the help.
