### ISSUE TITLE
Adding a Microsoft Account stops at a specific place in the Progress Bar.

### ISSUE THREAD

**Issue by LogIsparK5** [MultiMC/MultiMC5#4021]
### Operating System

Windows

### Description of bug

When I click Add Microsoft, it prompts me to log in. After I log in, the progress bar stops at a specific place without moving, been sitting at the progress bar for a few hours and it still hadn't moved.
![multimc microsoft bug](https://user-images.githubusercontent.com/89096228/129769596-0390f730-68ec-4042-8ac6-1a5282df495e.png)

### Steps to reproduce

Not sure, been trying to log in for a while and it has always done this.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by NooneAllAlone** [comment]
i have the same problem
if you find any solutions please also tell me

**Comment by LogIsparK5** [comment]
So, try logging in with Microsoft Edge as your default Browser, seemed to work for me, on Windows 10.
