### ISSUE TITLE
XBox User Authentication Failed - Macos

### ISSUE THREAD

**Issue by CaptainMaximus5** [MultiMC/MultiMC5#4022]
Microsoft account sign in pops up and you can enter credentials but after submitting there is popup with the message XBox User Authentication Failed, from what I can tell, this is a Mac exclusive problem. Hopefully fixed in the next version?

**Comment by jamierocks** [comment]
Please resubmit with our template.

**Comment by CaptainMaximus5** [comment]
Sorry
