### ISSUE TITLE
"Account is missing a profile" when logging in with microsoft account

### ISSUE THREAD

**Issue by antonvlasov** [MultiMC/MultiMC5#4024]
### Operating System

Windows

### Description of bug

Logging in with microsoft account leads to getting "Account is missing a profile" message. 

![image](https://user-images.githubusercontent.com/51422193/129791658-3f5ab2c9-b52a-41ea-a210-b07877557f93.png)

### Steps to reproduce

1. In mmc ```manage accounts->Add Microsoft```
2. In browser log in to a microsoft account with minecraft.
3. Agree to give access (prompt go give access only appeared first time, next times there is a blank page after logging in)
4. Open mmc and see the error on screenshot

### Suspected cause

Maybe there are some issues with microsoft account and there is a way to create profile but I did not find information on this. Here are logs 

https://pastebin.com/8rWPBPJg

### This issue is unique 

- [x]  I have searched the issue tracker and did not find an issue describing my bug.

**Comment by antonvlasov** [comment]
This is a bug and "bug" label should be added

**Comment by peterix** [comment]
If your account doesn't have a profile, it will not be added. It means you don't own the game.
