### ISSUE TITLE
Browser redirects to "http://localhost:28562/" when trying to add the Microsoft Account, and it it stuck right there

### ISSUE THREAD

**Issue by NooneAllAlone** [MultiMC/MultiMC5#4026]
### Operating System

Windows

### Description of bug

When I try to add my Microsoft account, and when I select it, it redirects me to the http://localhost:28562/ after that, and after some time, the launcher crashes, please fix this issue as soon as possible!
![Capturejk](https://user-images.githubusercontent.com/88819016/129842377-2f31149e-eb2a-434a-9b73-cb0aef1f67b8.PNG)
![image_2021-08-18_105823](https://user-images.githubusercontent.com/88819016/129842382-dd03d7e8-d4f8-4726-961e-92a405d5e1c4.png)

### Steps to reproduce

This issue shows similarities with this one too https://github.com/MultiMC/MultiMC5/issues/4021#issue-972895371

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by drshapeless** [comment]
Same thing happened to me, but it directed me to a browser page with this link, https://login.live.com/oauth20_authorize.srf?response_type=code&client_id=&redirect_uri=http://localhost:28562&scope=XboxLive.signin+offline_access&state=37e72fe975bf4a38a85aebae649edaf6&prompt=select_account.

And the page looks like this.
![2021-08-18_161945](https://user-images.githubusercontent.com/66210497/129863776-2c1b085a-2496-4153-b399-87920b68757f.png)

**Comment by yupa42** [comment]
same thing on ubuntu 20.04.2 LTS

**Comment by theofficialgman** [comment]
can confirm this happens just like drshapeless on my linux bionic install with chromium and firefox as default browsers

however, it is working for me on windows 11 with chrome, firefox, and microsoft edge (the only browsers I tested)

**Comment by ImperatorStorm** [comment]
> Same thing happened to me, but it directed me to a browser page with this link, https://login.live.com/oauth20_authorize.srf?response_type=code&client_id=&redirect_uri=http://localhost:28562&scope=XboxLive.signin+offline_access&state=37e72fe975bf4a38a85aebae649edaf6&prompt=select_account.
> 
> And the page looks like this.
> ![2021-08-18_161945](https://user-images.githubusercontent.com/66210497/129863776-2c1b085a-2496-4153-b399-87920b68757f.png)
> 
> I am using the latest build and Arch Linux.

did you build from [`multimc-git`](https://aur.archlinux.org/packages/multimc-git)? If so, switch to [`multimc-bin`](https://aur.archlinux.org/packages/multimc-bin). `multimc-git` is likely going to be deprecated soon, and it lacks a `client-id` build parameter, which is required to use MSA. `multimc-bin`, however, _does_ have that `client-id` build parameter.

**Comment by theofficialgman** [comment]
@ImperatorStorm could you clarify the client-id build parameter? I am building multimc5 from source myself since its necessary on arm64

**Comment by peterix** [comment]
@drshapeless I'm sorry, but there is no 'same, but'. It is either the same or it isn't. And you are using a weird build. Get MultiMC from https://multimc.org or as @ImperatorStorm said, `multimv-bin` if you are on Arch.

**Comment by theofficialgman** [comment]
no worries @ImperatorStorm .. I figured it out, the client ID is not given but is a cmake variable
well no worries, I will figure out what it is. already got the other variables
I don't maintain a fork but still need to build myself so I will find the variables and set them properly in the cmake

**Comment by peterix** [comment]
Custom builds are not supported here.

**Comment by drshapeless** [comment]
I just want to clarify one thing. Does the multimc-bin on Arch support Microsoft account? I installed multimc-git because I could not find the add microsoft button. There is only one "Add" button in the corner, and if I enter my microsoft account, it does not work. And I thought the multimc-git version would be more up-to-date.

If multimc-bin currently does not support microsoft account, I can wait for a newer release. But if it is my problem, please let me know if there is a way to fix.

**Comment by ImperatorStorm** [comment]
@drshapeless `multimc-git` is dead, deprecated, and flagged for deletion on the AUR. switch to `multimc-bin` and [move to the development channel](https://github.com/MultiMC/MultiMC5/wiki/Switching-update-channels) for MSA support.

**Comment by drshapeless** [comment]
@ImperatorStorm Thank you so much! Everything is working now.
