### ISSUE TITLE
Multimc library

### ISSUE THREAD

**Issue by Kloenk** [MultiMC/MultiMC5#4028]
### Role

Different clients, like better Mac support

### Suggestion

Provide a so/dylib/dll which does the multimc work, without the multimc gui

### Benefit

more native macOS feeling, QT seems to be missing some bindings for macOS features

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I known this is a huge thing to ask, so I accept closing without comments :-)

**Comment by phit** [comment]
the logic is usually connected in some way to Qt apis, it kinda went the opposite of what you are asking [just recently](https://github.com/MultiMC/MultiMC5/commit/20b9f2b42a3b58b6081af271774fbcc34025dccb) removing that whole multimc "api" concept, so I don't think this is happening

**Comment by Kloenk** [comment]
That's what I feared and though wrote that this is just a wish. Thanks for consideration.

**Comment by peterix** [comment]
Absolutely not.
