### ISSUE TITLE
Tray Icon on Linux

### ISSUE THREAD

**Issue by robotbrain** [MultiMC/MultiMC5#403]
the tray icon on linux seems to be broken
for me, the Tay contains a space for the icon, but the space is blank and clicking on it does nothing. i use arch linux, lxpanel and openbox. i have no actual desktop environment, opting for a custom setup. issue persists on latest dev versions.

also, the window title bar icon is not set to the mmc icon for me.

**Comment by Gotolei** [comment]
Problem still exists in 0.4.5
Xubuntu 14.04 64bit, Xfce 4.12

https://i.imgur.com/se4s1tJ.png

**Comment by RX14** [comment]
Works on arch linux i3 with the window manager ![](http://i.imgur.com/H72QszL.png) version 0.4.7

**Comment by Kilobyte22** [comment]
I am running Plasma 5 and i cannot remember ever setting a tray icon.

**Comment by peterix** [comment]
The fix for this is in Qt 5.5, apparently:
https://bugs.launchpad.net/ubuntu/+source/sni-qt/+bug/1330444

Once 5.5.1 is out, I will update Qt on all platforms and this problem should be gone.

**Comment by peterix** [comment]
See:
https://bugreports.qt.io/browse/QTBUG-31762

**Comment by Gotolei** [comment]
Bumping since 5.1.1 seems to be behaving as expected:

![screenshot_2016-07-26_21-37-25](https://cloud.githubusercontent.com/assets/7553595/17164028/4d7f62b2-5379-11e6-96f2-87d0e19557a9.png)
(xubuntu 16.04, xfce 4.12)

**Comment by peterix** [comment]
Yeah... and then 5.5.x had a fatal flaw that made it cause massive network latency when you're on wifi... and I skipped 5.6, because I simply didn't want to deal with that and other bugs... plus some of MultiMC depends on stuff removed in 5.6.

The current version is 5.7. I can no longer get binary builds for the version of Ubuntu I build on.

So I might just have to start building my own Qt on all platforms, not just Windows.

**Comment by peterix** [comment]
The comment on that bug:
```
Kubuntu 16.04, Qt 5.5.1. Tray icon doesn't work.
```
Does not inspire any confidence.

**Comment by peterix** [comment]
So, some hypothesis about what's going on:
The tray icons only work when you use a system patched version of Qt that has a platform integration plugin for it. Otherwise it won't work. Nothing has changed.

**Comment by peterix** [comment]
I removed the tray icon entirely.
