### ISSUE TITLE
Issue when Logging in via Microsoft profile

### ISSUE THREAD

**Issue by Corleone91** [MultiMC/MultiMC5#4031]
### Operating System

Windows 10 x64

### Description of bug

Its giving me the error invalid login or password when im trying to login via my Microsoft profile's Gmail and password

### Steps to reproduce

-Click accounts Tab
-Click Add account button
-Type Email and Password of Microsoft profile's gmail and password
-Hit Ok button

### Suspected cause

MultiMc is not adapted to recieve as Email Mirosoft profile's mail if its registered as Gmail and Mirosoft profile's pasword

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
Reproduction steps unclear, we're unable to help further without this information.

**Comment by insomnia-creator** [comment]
OS?

**Comment by Z-8Bit** [comment]
I could reproduce this easily, personally have a Microsoft Account bought in March-April

Steps to Reproduce: 
-Click Profiles - Manage Accounts
-Click the Accounts tab in the dialog box
-Click the Add button after being greeted with the welcome
-Type the Email and Password of the Microsoft account profile
-Hit the ok button

Error: Invalid credentials, Invalid username of password.

I am logged into my vanilla launcher with the same account, my mail and password are correct (cross-checked).
OS: Arch, but able to reproduce on Windows as well.

p.s I installed multimc from the AUR, multimc-bin
https://aur.archlinux.org/packages/multimc-bin

**Comment by Z-8Bit** [comment]
You have to enable the dev branch to log in using Microsoft accounts :)
note: After enabling said branch, restart MMC.

**Comment by arthomnix** [comment]
To change to the dev branch, go to settings > MultiMC and change the update channel to Development
Then press update and there should be separate 'add microsoft' and 'add mojang' buttons
