### ISSUE TITLE
Console window does not update logs

### ISSUE THREAD

**Issue by Boobies** [MultiMC/MultiMC5#4034]
### Operating System

Linux

### Description of bug

If you keep the console window open while running your window, you won't get to see any logs in the "Other logs" category that have been written until you close it and then reopen it.

### Steps to reproduce

Open the console window for an instance, launch the game, close it, etc. Check "Other logs" before and after reopening the console window.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by peterix** [comment]
This is on purpose, because watching thes files for changes is not reasonable. They also don't provide much benefit.

**Comment by Boobies** [comment]
No need to constantly scan for the logs. Only need to know when they are created. Whatever gets appended afterwards is fine so long as they show up.
