### ISSUE TITLE
MultiMC doesn't work anymore

### ISSUE THREAD

**Issue by orrinpants** [MultiMC/MultiMC5#4035]
### Operating System

Windows

### Description of bug

MultiMC doesn't work anymore...
I can't use mods anymore );

### Steps to reproduce

* Make an instance
* Launch

### Suspected cause

MultiMC corrupting all accepted passwords so you can't log in...
Or, there's a very low chance that this is the case, but maybe the migration.

### Crash report
Invalid credentials. Invalid username or password.

**Comment by orrinpants** [comment]
I restarted my computer and it works now.

**Comment by orrinpants** [comment]
Now it asks me for my password every time and I put all of my Minecraft passwords in and none of them worked.

**Comment by orrinpants** [comment]
Please help me

**Comment by orrinpants** [comment]
I'm just gonna go back to vanilla Minecraft until this is fixed

**Comment by jotoho** [comment]
This is a completely unrelated issue than the opening post. I'd advise you to close this issue and create a new one with more information than "login doesn't accept my passwords" or go ask on the multimc discord. (like instance logs, multimc logs, screenshots, etc.)
Btw, "password**s**"? An account shouldn't have more than one password. If you migrated your account to microsoft you'd need to switch to the dev update channel, if you didn't already.

**Comment by jotoho** [comment]
@orrinpants Did you migrate your Mojang account to Microsoft? Microsoft authentication within MultiMC is very experimental and limited to the development versions (dev channel), last I checked.

**Comment by jamierocks** [comment]
No, just no. Open a new issue, don't retroactively change your issue and reopen.

**Comment by orrinpants** [comment]
I did migrate, I put that in.

**Comment by orrinpants** [comment]
By passwords, I mean all memorizations of both my Microsoft account and Mojang account.
