### ISSUE TITLE
MultiMC-0.6.12-develop-2402: Instance update failed because: Component metadata update task failed while downloading from remote server:

### ISSUE THREAD

**Issue by EndlessEden** [MultiMC/MultiMC5#4037]
### Operating System

Windows

### Description of bug

After adding a new instance of ATM7 via curseforge, first launch results in a immediate crash during startup while downloading assets. 
The log showing 
`Instance update failed because: Component metadata update task failed while downloading from remote server:

Job 'Download of meta file net.minecraftforge/37.0.44.json' failed to process:
https://meta.multimc.org/v1/net.minecraftforge/37.0.44.json`

Full Log: https://gist.github.com/EndlessEden/ab31f65fd77b71aa0cb8d831f4e7c0b7

### Steps to reproduce

1. Download/Install ATM7 version: 0.0.4 (https://www.curseforge.com/minecraft/modpacks/all-the-mods-7/files/3437135) via the curseforge browser in "New Instance" menu.

2. First-Time Launch ATM7, with Java Version 16.0.1,

3. Fails to download meta file net.minecraftforge/37.0.44.json

### Suspected cause

37.0.44.json is currently 404. Ive confirmed nothing is blocking the connection from multimc, and have attempted to access the failing file from browser, curl and another machine. other directories/files work fine.

`$ curl -v https://meta.multimc.org/v1/net.minecraftforge/37.0.44.json
*   Trying 172.67.147.103...
* TCP_NODELAY set
* Connected to meta.multimc.org (172.67.147.103) port 443 (#0)
* schannel: SSL/TLS connection with meta.multimc.org port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 187 bytes...
* schannel: sent initial handshake data: sent 187 bytes
* schannel: SSL/TLS connection with meta.multimc.org port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with meta.multimc.org port 443 (step 2/3)
* schannel: encrypted data got 2830
* schannel: encrypted data buffer: offset 2830 length 4096
* schannel: sending next handshake data: sending 93 bytes...
* schannel: SSL/TLS connection with meta.multimc.org port 443 (step 2/3)
* schannel: encrypted data got 258
* schannel: encrypted data buffer: offset 258 length 4096
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with meta.multimc.org port 443 (step 3/3)
* schannel: stored credential handle in session cache
> GET /v1/net.minecraftforge/37.0.44.json HTTP/1.1
> Host: meta.multimc.org
> User-Agent: curl/7.55.1
> Accept: */*
>
* schannel: client wants to read 102400 bytes
* schannel: encdata_buffer resized 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data got 961
* schannel: encrypted data buffer: offset 961 length 103424
* schannel: decrypted data length: 898
* schannel: decrypted data added: 898
* schannel: decrypted data cached: offset 898 length 102400
* schannel: encrypted data length: 34
* schannel: encrypted data cached: offset 34 length 103424
* schannel: decrypted data length: 5
* schannel: decrypted data added: 5
* schannel: decrypted data cached: offset 903 length 102400
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 903 length 102400
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 903
* schannel: decrypted data buffer: offset 0 length 102400
< HTTP/1.1 404 Not Found
< Date: Tue, 24 Aug 2021 15:20:44 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< CF-Cache-Status: DYNAMIC
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=N8XRLuwLxoECNHwULK4RMhPJOu50Z9jnwDpk%2BnO95tnlLA3U65yy0AnfcGuM1VTjIxydlzXQnptuUTqsH97wdzSiIW4xF8yPkXHMi2ajueKq%2BJrmmaRS61IhbN4EqgOEjr3O"}],"group":"cf-nel","max_age":604800}
< NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< Server: cloudflare
< CF-RAY: 683d90feefeefe64-SYD
< alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400
<
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>
* Connection #0 to host meta.multimc.org left intact`

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Forge 1.17+ is currently not supported https://github.com/MultiMC/MultiMC5/issues/3936

**Comment by EndlessEden** [comment]
@phit Thanks, wasnt aware of this ^_^
