### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by JulikGame** [MultiMC/MultiMC5#4038]
### Operating System

Windows

### Description of bug

MultiMC closing when i am adding microsoft account and i tried again to add still can't it says "Logging in with Xbox and Mojang sevices" spamming 3 sec

### Steps to reproduce

there's no error

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
closing in favor of https://github.com/MultiMC/MultiMC5/issues/4050 which has a lot more detail
