### ISSUE TITLE
Ability to manage AT Launcher's modpacks right from MultiMC

### ISSUE THREAD

**Issue by KamranMackey** [MultiMC/MultiMC5#405]
I would find it really useful if we could manage AT Launcher's mod packs since you have FTB integration, so why not add AT Launcher integration as well?

**Comment by Aphenon** [comment]
Was this feature dropped? i would love to have this.

**Comment by RyanTheAllmighty** [comment]
I'm sad this never made it in. The fact it's still open provides hope, but only very little since it's been left here.

Any update on this or how I can help in anyway make this happen?

**Comment by peterix** [comment]
Yep. We don't have enough manpower.

Currently, all my effort goes into this:
https://github.com/MultiMC/MultiMC5/commits/feature/remote_version_files

Basically making a new instance format that can handle modpacks and direct resource downloads. Kinda like QuickMods should have been, only built from bottom up, not the other way.

**Comment by peterix** [comment]
Long time no see! I'm moving all the ideas to workflowy - a place better suited for the kind of structured organization and planning needed to actually manage hundreds of ideas.

The feature will most likely take the form of direct support - and import from the platform. Not tracking or launching of existing ATL instances.

So, this has been [moved to workflowy (Ideas -> Packs).](https://workflowy.com/s/2EyDMcp7CU)

**Comment by peterix** [comment]
So, I'm looking at this, and I don't think this can ever go forward.

1. I don't want to reimplement other launcher's logic just to be able to launch some arbitrary instances from them. It would tie MultiMC to their internals. It did that with FTB, and I'm not a fan of the mess it causes in the code. The launchers go in different directions, and the differences are often irreconcilable.
2. Import from platform is not possible.

I might do this in the 'direct import from platform' way on a private branch just for the heck of it... But it cannot be deployed.
