### ISSUE TITLE
Microsoft account has expired

### ISSUE THREAD

**Issue by bobcatfish9** [MultiMC/MultiMC5#4051]
### Operating System

Windows

### Description of bug

Opening multimc today I expected to jump right into a game but was greeted with a popup stopping me. The popup was about my microsoft account expired and needing to be logged into again.

To solve this now as I can not find a relog button, do I need to delete my microsoft account from multimc and re-add everytime this happens?

### Steps to reproduce

-open multimc launcher - development branch.
-have microsoft account in launcher that I added day before (was using it yesterday after logging it in without issue).
-double click 1.17.1 vanilla instance (or any instance).
-recieve popup window from multimc with message;
"Microsoft account has expired and needs to be logged into manually again."
-try my second account and have same experience.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by karimrir1** [comment]
This happened to me too
