### ISSUE TITLE
Manual override for Java runtime requirement

### ISSUE THREAD

**Issue by ReperakPro** [MultiMC/MultiMC5#4053]
### Role

Playing 21w19a+ with the [Not So New](https://github.com/Chocohead/Not-So-New) mod.

### Suggestion

Add an override to ignore the Java runtime requirement.

### Benefit

So I can use Not So New

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by peterix** [comment]
Use the correct Java version for the Minecraft version you are trying to play.

**Comment by jamierocks** [comment]
I'm of the opinion that mechanism should be supported by a metadata field (`minimumJavaMajorVersion` or similar), rather than the quick-and-dirty implementation currently in place. This would, tangentially, resolve this issue.

Having said that, I concur with peterix - use the appropriate version of Java for the version you're playing :)

**Comment by peterix** [comment]
Nah. We just need the defaults to be sane. That means using Mojang JREs and removing this limitation from the code.

It is put in there intentionally, for the good of the vast majority of users.

Your usecase is weird and I put the rest of the people's priorities over yours until the problem can be resolved properly.

**Comment by peterix** [comment]
That said, I heard you. It's just that this is not going to get acted upon until the Java runtime system gets redone.

**Comment by ReperakPro** [comment]
> It is put in there intentionally, for the good of the vast majority of users.
A normal user isn't going to be checking an option that says something along the lines of "Ignore incompatible Java runtime"

In VerifyJavaInstall.cpp a check can be added to look for a UI button's value.

**Comment by peterix** [comment]
I have said everything I wanted to on this topic.
