### ISSUE TITLE
1.17 modpacks can't identify java version

### ISSUE THREAD

**Issue by Mangofritter** [MultiMC/MultiMC5#4057]
### Operating System

Windows

### Description of bug

Whenever I try to load a 1.17 modpack, it exits and says anything past a certain snapshot requires Java 16. I downloaded Java 16 and set the Java path to that version, it did not work. After that it didn't tell me I had the wrong Java version, it said it couldn't tell what version it was. 

Weirdly enough, the only 1.17 installation that works is an edited version of fabulously optimized, where I added the mod version of terralith. I added the mod before an update that duplicated my multiMC folder. (I thought that update deleted all my installations until I discovered it created a new folder with all my old installations.) Don't know if that's a cue about what's wrong.

If the Java file needs to be in a specific folder to be usable, then that should be mentioned in the error code or in settings where you can select the path.

### Steps to reproduce

Unfortunately, I don't know how to reproduce it. I think this bug came with a recent update, but I don't use 1.17 all the time, so I don't know which one caused the problem. 
For reference of time period, I haven't had multiMC very long. I can't remember what day exactly, but if my folder properties are to be trusted, I got it on August 20th. This is not too reliable though, considering one of the updates duplicated the entire multiMC folder, but the duplicate is also allegedly from July 24th. I haven't had multiMC for more than 2 weeks

### Suspected cause

A recent update

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
please provide a log, i suspect you are mixing up versions or set the wrong path, especially if one is working

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
