### ISSUE TITLE
Minecraft 21w19a and above require the use of Java 16

### ISSUE THREAD

**Issue by TigiOnMinecraft** [MultiMC/MultiMC5#4059]
### Description of bug

I try to launch minecraft 1.17.1 but minecraft crash because Minecraft 21w19a and above require the use of Java 16.

### Steps to reproduce

create an instance in Minecraft 21w19a and above and be on a microsoft account.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jotoho** [comment]
It's your responsibility as a user of MultiMC to make sure that the correct Java version is installed and configured for the instance you are trying to use. You can find all needed information for configuring Java with MultiMC in the wiki. https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java

What is the purpose of this issue? What changes do you propose? 

It's also obvious that you didn't search the issue tracker for tickets like this, despite your claims. There's at least a dozen others discussing the Java 16 requirement.

**Comment by monokrome** [comment]
After installing the latest version of Java following the documentation, the same error appears. Maybe this is user error or a documentation issue?

This occurs with both these paths:

- C:/Program Files/Java/jre1.8.0_291/bin/javaw.exe
- C:/Program Files/Java/jre1.8.0_301/bin/javaw.exe

Maybe there's a different version we're supposed to be using? A missing step in the documentation possibly?

**Comment by phit** [comment]
docs are wrong, you need java 16, you got java 8, read https://gist.github.com/jamierocks/51569478cdf858bc93aa4fda80c126ef

**Comment by anhgelus** [comment]
Of course we have to use java 16 for Minecraft 1.17 but if we want to play in 1.16 or 1.12 for example, we can't or we have to change our java version.
It's not comfortable.
So, I have an idea for you: we can select two versions of java and the software will choose the right version to run Minecraft.
I think it won't be difficult to add because it has to take the instance version and choose the right java version, that's all.

**Comment by Janrupf** [comment]
You can already select the Java version for each instance individually. For now that solution exists, automatic selection support will come at some point

**Comment by ramast** [comment]
I am getting exact same error, even though I am using java 16

```
Checking Java version...
Java checker returned some invalid data MultiMC doesn't understand:
java.version=16.0.2
```

**Comment by phit** [comment]
1.18 needs java 17

**Comment by anilsg** [comment]
> 1.18 needs java 17

Ah thanks very much @phit that works.
But my we are changing Java versions extremely frequently now that Oracle has got hold of it.
