### ISSUE TITLE
This could be BIG!, Hear me out. MultiMC-Server

### ISSUE THREAD

**Issue by Nova3wii** [MultiMC/MultiMC5#4062]
Ok so MultiMC handles the client side right?  So now hear me out add like a separate tab or perhaps another application that handles the server side.  And you know follow MultiMC way of doing things, and have separate the server installs like you do for the client with all the configuration would be nice as well.

**Comment by insomnia-creator** [comment]
There already are clients which handle server side. I don't know if the devs would put time into something that isn't important at all.


Their minds should currently be on MSA support. Server side would be fine for MultiMC but imo their minds should  be on MSA rn.

**Comment by consoleaf** [comment]
Yeah, 
1) there are more than enough of server management tools already, some are even FOSS
2) making something like that takes a lot of effort, and nobody can guarantee that it will be worth it

**Comment by phit** [comment]
no, multimc is a client launcher and always will be

**Comment by peterix** [comment]
If we're going to do something like this, it won't be for managing servers. It will be for making the server part of modpacks and testing them.
