### ISSUE TITLE
crash when using custom minecraft.jar and forge

### ISSUE THREAD

**Issue by 8Ascoth8** [MultiMC/MultiMC5#4073]
### Description of bug

So, when I try to load my game with forge and a custom minecraft.jar (with the "Add to/Replace Minecraft.jar button), either it doesn't load, or it loads, but with no mods loaded and it crashes when I open a world.
For example, I'm not able to load this mod [https://github.com/Cubitect/Cubitick](url) with forge.
Please help me

### Steps to reproduce

Try to edit minecraft.jar bytecode and then click on the "add to minecraft.jar" button, then install forge and there you go, your game will crash

### Suspected cause

I think it's because when forge notice that minecraft.jar is modified it crashes, exept for some exeptions like optifine.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by 8Ascoth8** [comment]
Ok, i'll do that, thanks

**Comment by kb-1000** [comment]
Forge is not compatible with jarmods, so no surprise... jarmods are dead since like 1.5 or 1.6. Complain to the mod author, not the launcher
