### ISSUE TITLE
Ability to add forge/fabric manually

### ISSUE THREAD

**Issue by jdroo** [MultiMC/MultiMC5#4074]
### Role

Modded foprge/fabric

### Suggestion

Ability to add forge/fabric manually

### Benefit

When MultiMC has not updated the list of compatable mod loaders, yet they are out.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

It would allow using alpha versions of mod loaders, or ability to add it despite your database not detecting it.

**Comment by jamierocks** [comment]
You can already add components manually.

**Comment by peterix** [comment]
Forge? Impossible for most users due to how complex it is and how exposed that complexity is. Forge devs messed up and are continuing to mess up despite advice to the contrary ... so I don't think this is feasible at all.

Fabric? Sure ... Just change the libs around.

**Comment by peterix** [comment]
But nothing needs to be done here. You can already do this if you like invisible and intangible jigsaw puzzles that basically nobody understands.
