### ISSUE TITLE
Im a poopy face

### ISSUE THREAD

**Issue by somerandomguy666999** [MultiMC/MultiMC5#4075]
### Description of bug

My face has poop on it

### Steps to reproduce

Get someone to shit on ur face

### Suspected cause

Someone shitting on my face

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by somerandomguy666999** [comment]
@cpreh @kb-1000 @asiekierka @runlevel5 @CarrotCodes

**Comment by jamierocks** [comment]
Don't spam our bug tracker with this nonsense.
