### ISSUE TITLE
Add Microsoft logins on the accounts login

### ISSUE THREAD

**Issue by hi216** [MultiMC/MultiMC5#4077]
### Role

an Account Feature Because some people login with microsoft on minecraft

### Suggestion

Add Microsoft logins on the accounts login

### Benefit

to have more people

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Zetabite** [comment]
you havent read any issues. there are several latest closed. this is already support in dev, if not on stable (i am not using stable, so i wouldnt know)

**Comment by jamierocks** [comment]
> I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

Don't affirm to things you haven't done. In this case it's not only lazy on your part, but wastes time on our end...
