### ISSUE TITLE
Option to disable launch the instance by double right mouse click

### ISSUE THREAD

**Issue by TheByKotik** [MultiMC/MultiMC5#4079]
### Role

I working with many similar instances in same time and sometime i click RMC on wrong instance, then i click RMC again to hide dialog menu but this launch the instance. I know this just bad habit but i can't stop it. This not important feature and i just wanna to leave it in suggestions.

### Suggestion

Option to disable launch the instance by double right mouse click

### Benefit

I will finally stop running randomly instances

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
this seems like a feature of your OS that it treats double right click as a normal double click, I'm unable to reproduce this on macOS and Windows 10

even if this was a feature of MultiMC, disabling stuff like this would probably break the workflow of many users

**Comment by TheByKotik** [comment]
> this seems like a feature of your OS that it treats double right click as a normal double click

This works only in MultiMC (last from develop channel)
I can't find any system option controlled this.

> I'm unable to reproduce this on macOS and Windows 10

I'm using Windows 10 Pro 21H1 19043.1165
Also instance is launching only if double RMC was extremely fast.

> even if this was a feature of MultiMC, disabling stuff like this would probably break the workflow of many users

I understand it and suggest add an option, not removing it totally.
