### ISSUE TITLE
MultiMC complains about Microsoft Accounts only working on macOS 10.13 or newer with the latest MultiMC build

### ISSUE THREAD

**Issue by starcraft66** [MultiMC/MultiMC5#4081]
### Operating System

macOS

### Description of bug

I downloaded the latest build of MultiMC form TeamCity and launched it. I tried to add a Microsoft account and was greeted with the following error message:

![image](https://user-images.githubusercontent.com/1858154/132565172-ee5c3170-62cd-46fc-b772-76c355760982.png)

I am running the latest MultiMC and macOS 11.3 so I shouldn't be getting this error message.

### Steps to reproduce

- Download the latest MultiMC build form TeamCity on a Mac running macOS 11.3

- Open MultiMC

- Try to add a Microsoft Account

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by peterix** [comment]
And which build is that?

You probably need to update MultiMC, because this only shows up in the 'old' Qt 5.6 build.

**Comment by jamierocks** [comment]
> I downloaded the latest build of MultiMC form TeamCity

You probably downloaded the wrong one. There's another project for the newer Qt builds.

**Comment by starcraft66** [comment]
I probably downloaded the wrong one, I chose the download that wasn't suffixed by the Qt version.

**Comment by mattnield** [comment]
This is confusing me, I'm getting this error running macOS 13.3.1 and a _just downloaded_ `MultiMC 5 - Version 0.7.0-3738 on ossx64` that I got from the multimc.org homepage. What am I doing wrong here, is this not the latest MultiMC version?

**Comment by mattnield** [comment]
> This is confusing me, I'm getting this error running macOS 13.3.1 and a _just downloaded_ `MultiMC 5 - Version 0.7.0-3738 on ossx64` that I got from the multimc.org homepage. What am I doing wrong here, is this not the latest MultiMC version?

OK - for anyone else in here, I needed to update the client when it opened. I thought it was telling me that there were no updates.
