### ISSUE TITLE
Microsoft Account Authentication Fails due to Being Underaged, Even When Not Underaged

### ISSUE THREAD

**Issue by Avakining** [MultiMC/MultiMC5#4082]
### Operating System

macOS

### Description of bug

I tried to link my Microsoft account to MultiMC, and despite being over 16 and in the US, I get the following error:

> This Microsoft account is underaged and is not linked to a family.

MultiMC version: 0.6.13-develop-2502
Platform: osx64-5.15.2
macOS version: 12.0 beta 7

### Steps to reproduce

1. Go to account settings
2. Click "Add Microsoft"
3. Open the link and enter the code
4. Allow MultiMC to access Microsoft account
5. Return to MultiMC
6. Wait for MultiMC to process the linking
7. Get the following error message
<img width="821" alt="Screen Shot 2021-09-08 at 17 11 02" src="https://user-images.githubusercontent.com/25210618/132586114-f478e84b-fb08-4ae4-9773-15352e75b530.png">

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
the age limit is 18 not 16

**Comment by Avakining** [comment]
>child accounts are all accounts for those under the age of 16 for the US & EU

https://help.minecraft.net/hc/en-us/articles/360042649591

**Comment by peterix** [comment]
I do not make the rules, the XBox/Microsoft services do. And when they say you are underaged, you are underaged.

I can't fix this.
