### ISSUE TITLE
Microsoft Account Cannot Be Added on Linux

### ISSUE THREAD

**Issue by OriginCode** [MultiMC/MultiMC5#4087]
### Operating System

Linux

### Description of bug

The "Add Microsoft" button on Accounts page is grey and cannot be chosen.
OS: Arch Linux
The package is from AUR.
![image](https://user-images.githubusercontent.com/17294071/132857015-f5e0c059-5417-4e88-8dd3-0bb932c37f3c.png)

### Steps to reproduce

Launch MultiMC and go to `Settings -> Accounts`.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
This is a bug with the package you are using, seek support from them.

**Comment by JoelTroch** [comment]
Uninstall the `multimc-git` AUR package which is not supported here and install the proper one which is `multimc-bin`.

**Comment by OriginCode** [comment]
> Uninstall the `multimc-git` AUR package which is not supported here and install the proper one which is `multimc-bin`.

I'm using `multimc5` from AUR.

**Comment by Janrupf** [comment]
`multimc5` is not official either. Only `multimc-git` is

**Comment by JoelTroch** [comment]
I said [`multimc-bin`](https://aur.archlinux.org/packages/multimc-bin/). I did not said `multimc5`.

**Comment by OriginCode** [comment]
> I said [`multimc-bin`](https://aur.archlinux.org/packages/multimc-bin/). I did not said `multimc5`.

Is it because there are a secret key or token or something?

**Comment by JoelTroch** [comment]
To support Microsoft accounts: yes.

If you build MultiMC from source (which is what `multimc5` and `multimc-git` does), you are expected to supply your own secrets during the build process (not going to detail here). By doing so, you won't get support from the community/developers because your build is "custom".

So do yourself a favor and avoid all the pain by using the official builds. The `multimc-bin` AUR package is one of them.

**Comment by database64128** [comment]
Calling a binary package the "proper" one while dismissing proper source build packages is not the attitude I expect from a maintainer of an open source project. Guess it's lucky I haven't migrated yet, and probably never will.

**Comment by Zetabite** [comment]
Idk what you are complaining about. The mayority of packages in the official repos are binary packages. I also dont see how this is related to open source. There are other open source projects that arent even possible to compile. If people wanna build mmc, they need to follow standards, which multimc5 and multimc-git dont. You are welcome to use those, but arent entitled to support by us.

**Comment by Zetabite** [comment]
Why, its all on the website.

**Comment by Schmensch** [comment]
Oh ok I thought only the Ubuntu package was listed there.

**Comment by Schmensch** [comment]
As someone who is trying to package MultiMC as a Flatpak, I couldn't agree more.

**Comment by kb-1000** [comment]
> In which way do these two packages violate the "standards"? Can you elaborate on that?

They apply a patch that breaks compatibility with some older Minecraft versions by making you unable to use Java 6 or 7.

> But in the case of MultiMC, I don't see any good reasons why using an unreproducible binary from an untrustworthy third-party is the only recognized way for packaging. And it's really sad and even more concerning to see all the hostility from upstream maintainers towards downstream source build packages.

You want reasons? Well, MultiMC got a DRM to protect (Minecraft's, it's not a pirate launcher after all), most custom builds remove that DRM. Then, secrets are secrets... do you want to share your API keys with me?

> As someone who is trying to package MultiMC as a Flatpak, I couldn't agree more.

You don't need to build from source for flatpak, binaries do fine.

**Comment by peterix** [comment]
Do not put MultiMC 5 in flatpak.

**Comment by peterix** [comment]
In general, we're done here. Use the binaries.

**Comment by peterix** [comment]
The source will not build as `MultiMC` in the future either. I'm really sick and tired of lazy forks that mess with how things work that do not change the name. The hope is that they will change it if I call it something generic thaty nobody would want to call a launcher.

Creating a bigger barrier to making lazy forks is a goal here. You building unsupportable versions from source is not.

**Comment by database64128** [comment]
Time to remove MultiMC from all my devices, I guess. It’s really sad seeing the best Qt-based Minecraft launcher turn non-free and start doing all these shady stuff.

A bit of advice: Add a clarification to mention  that the distributed binary is not built from the code in the public repository. Might as well change to a non-free proprietary license.

**Comment by RDKRACZ** [comment]
Ah yes, good old I don't agree with the app dev team so I will publicly say I quit using it even tho nobody asked. You forgot about the part where you say bad things about the project and call devs names.
I have no idea how you managed to read "The source will not build as MultiMC in the future. I (will) call it something generic (to prevent lazy forks)."  as MultiMC going non-free but you can go back to the closed-source official launcher.
Going back from this Discord-like discussion to the original topic - the MultiMC bin package from AUR works fine with my MS account.

**Comment by kb-1000** [comment]
Actually, Firefox does the same... by default it does not brand itself as Firefox when built from source, and the repository is called mozilla-central or browser, not firefox.
It does not publish its API keys either, as far as I'm aware.

**Comment by peterix** [comment]
To be honest, I'm tempted to just take the source offline, but it's kinda like throwing the baby (collaboration and people contributing) out with the bathwater (unrelated third party devs not respecting the licenses and law in general).

Apache 2.0 clearly states that it does not apply to trademarks - and no, it does not specify any need for the trademark to be registered:
> 6. Trademarks.
> 
> This License does not grant permission to use the trade names, trademarks, service marks, or product names of the  Licensor, except as required for reasonable and customary use in describing the origin of the Work and  reproducing the content of the NOTICE file.

I did not put much of an emphasis on this before, because it wasn't an issue (or rather, it was a fringe issue that did not need much attention). With what's happening around MultiMC, the MS Indentity Platform terms of use, and general adversity, I cannot keep the default state of the source producing 'MultiMC'.

Right now, any build not made by the CI, and then distributed to users is essentially a trademark infringement. You doing something illegal should not be the default. If someone decides to impersonate MultiMC once the source is debranded, they will have no excuse of doing so by accident or unknowingly.

**Comment by peterix** [comment]
I do not want to paint you as the devil here, but I've had to deal with people repackaging MultiMC, cracked, on the snap store.

'MultiMC' comes from multimc.org. Period. Any other source may not distribute 'MultiMC'.

**Comment by peterix** [comment]
The only exception is a wrapper that gets you the unchanged binaries that are capable of automatic updates from multimc.org and are not tampered with.

**Comment by peterix** [comment]
If you do not like that, do a clean fork. Change the name. Run your own infrastructure.

**Comment by peterix** [comment]
And do not imply that anyone who contributed to 'MultiMC' has given it their blessing.

**Comment by shanoaice** [comment]
This is not the atitude an open source developer should have toward the community: publish the standards, specify them. Open source software's, or more clearly, libre software's (although I understand that Apache 2.0 License is a lesser general license, not those copyleft ones.) purpose is to make things open and reproducible, not just irresponsibly marking all unofficial builds unsupported and even trying to build a barrier to stop any other people packaging unofficial versions of the software. You are forgetting the true value of open source, @peterix

**Comment by peterix** [comment]
The facts:
- This is a launcher for a game owned by Microsoft. You have to buy it to be able to play it.
- People fork MultiMC, impersonate it, and 
- The terms of use for the identity platform state that (among others):
    - You must not:
        - Use the Platform or allow any user to use the Application in a way that violates applicable law, including:
Illegal activities, such as child pornography, gambling, piracy, violating copyright, trademark or other intellectual property laws.
    - Your Application does not infringe upon or misappropriate any intellectual property or personal right of Microsoft or any third party;
  
From what I see here, I can either abide by the rules, or shut everything down and go do something else.

Neither my or your sensibilities apply.

**Comment by peterix** [comment]
Before this, there was no legal framework for using Mojang account logins aside from some Minecraft devs talking on twitter.

**Comment by peterix** [comment]
AFAIK, I have no other options.

**Comment by peterix** [comment]
As for 'attitude' ... you are not working form Microsoft while doing this. You are not in a weird conflict of interest situation. You did not sign anything. You are just asking for me to go against the company I work for.

**Comment by peterix** [comment]
So, kindly take that elsewhere.

**Comment by peterix** [comment]
And you can always register your own application and provide the necessary `Access Credentials`, on your own, taking responsibility for `All activities that occur using your Access Credentials`.
