### ISSUE TITLE
Explicit Java Args Should Always Take Priority

### ISSUE THREAD

**Issue by Quest79** [MultiMC/MultiMC5#4089]
### Role

Custom ram needs per pack

### Suggestion

Custom ram needs per pack arg, and a fallback if no args given in terms of RAM

### Benefit

Better pack preformance

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

[See image](https://i.imgur.com/PaRSabR.png)

- When a pack has an explicit java argument for ram usage, this should automatically take priority over any other setting. 
- The manual (non arg) RAM setting per pack should take second priority.
- The general RAM setting inside the main settings of MultiMC should take the last priority as a catch-all
- The dialog that is X'ed out in the image above should never appear. It has no useful function other than to annoyingly cover a non-existent priority system when it should have just been a simple if statement to begin with.

I have custom and well tested java args for each pack I create and manage, I dont need to play tug of war with my launcher.

**Comment by peterix** [comment]
Absolutely not. Stop putting in the args.

**Comment by Quest79** [comment]
How ridiculous. You already have a priority system in place, you just refuse to finish it. Bad design coupled with stubbornness is not a great way to develop software.

**Comment by peterix** [comment]
You are the one proposing bad design.

**Comment by peterix** [comment]
An instance is **NOT** a mod pack. You are confusing the two. 

The system here is going to get redone with actual modpacks in mind, along with the java runtime auto install/select stuff.

That is, if a mod pack has minimum/recommended heap size, that should get used to inform the minimum in the ui, and the actual memory settings unless you change the value explicitly.

I'm not going to expand upon the current stuff, it's getting replaced.

And if anything, it will go further away from exposing custom args to most users. It's a constant source of issues. That aside, the stuff people put in these args is usually cargo culted nonsense someone posted on some site 6 years ago...

**Comment by peterix** [comment]
Not saying you do that, but you are a very rare exception if you actually put in the time to research and experimentally verify those args.
