### ISSUE TITLE
Java 16 misunderstood

### ISSUE THREAD

**Issue by HeavyMOnkey** [MultiMC/MultiMC5#4090]
### Description of bug

I tried to Launch multimc but it said "Minecraft 21w19a and above require the use of Java 16" even though i have the latest version of java.

### Steps to reproduce

I pressed launch on a 1.17.1 instance

### Suspected cause

i dont know what might be causing it

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Veradra** [comment]
Install Java 16, and use it for every version of minecraft released after and including 21w19a (1.17 snapshot). You need to specify which version of Java to use in the instance settings, and not globally (everything below this uses java 8). To do this, after installing Java 16, right click the 1.17+ instance -> Edit Instance -> Settings (In the menu that has just opened up) > click the checkbox for "Java installation" > Auto-detect... > Select one that [looks like this](https://cdn.discordapp.com/attachments/686429123182198956/886116600946761768/unknown.png) (Should be 16.something)

[Adoptium builds](https://adoptium.net/releases.html?variant=openjdk16&jvmVariant=hotspot)

You're looking for this one, specifically the .msi
![image](https://user-images.githubusercontent.com/31333156/132936916-8b6419e6-0b41-4f2c-95e5-b1b16bbccb2d.png)
