### ISSUE TITLE
Game crashes when I turn on full screen mode.

### ISSUE THREAD

**Issue by Doughcrafter** [MultiMC/MultiMC5#4092]
### Operating System

macOS

### Description of bug

I'm trying to turn on full screen mode to increase my fps but whenever I turn it on my game crashes and when I launch the game again it continues to crash. I am also using optifine.

### Steps to reproduce

1. Launch game
2. Turn on full screen mode in settings. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
