### ISSUE TITLE
Direct open Windows Connection Link wihout using

### ISSUE THREAD

**Issue by Starmania** [MultiMC/MultiMC5#4101]
### Role

All is in the title, just one click to config Microsoft account.

### Suggestion

replace https://www.microsoft.com/link by https://www.microsoft.com/link?otc=<Login CODE without less-than sign and more-that sign\>

### Benefit

N.A.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by LikeLakers2** [comment]
Hi there, I probably wouldn't recommend this, actually. 

The primary reason I recommend against it, is that Microsoft's implementation of the device authorization flow (which MultiMC uses for authorizing with a Microsoft account) does not provide a `verification_uri_complete` field, as noted [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code#device-authorization-response).

According to the [OAuth 2.0 Device Authorization Flow standard](https://datatracker.ietf.org/doc/html/rfc8628), specifically [section 3.2](https://datatracker.ietf.org/doc/html/rfc8628#section-3.2), the `verification_uri_field` field provides a URL that would automatically input the appropriate code for the user.

However, as Microsoft does not currently support that field, it means that the `?otc=` parameter proposed by this issue could be changed to something else (or even removed), without notice. And that would be both frustrating for the MultiMC devs, as well as bothersome for MultiMC users (who thought that MultiMC would input the code for them).

**Comment by peterix** [comment]
Where is this documented and how?

**Comment by Starmania** [comment]
I've found no docs, I search on the html page 

`<input name="otc" id="otc" class="form-control" type="text" maxlength="16" autocomplete="off" aria-required="true" data-bind="
            textInput: codeTextbox.value,
            ariaDescribedBy: 'loginHeader loginDescription',
            hasFocusEx: codeTextbox.focused,
            placeholder: $placeholderText,
            css: { 'has-error': codeTextbox.error }" aria-describedby="loginHeader loginDescription" placeholder="Code">`

To find on the original page, just search `#otc` in source code.

> Microsoft does not currently support that field

Wrong, I,ve test before sent this suggestion.

PS: I've edit my comment, some text didn't appear before.

**Comment by peterix** [comment]
Digging through code and finding some random thing doesn't mean it will be there tomorrow, or that its use won't get all MultiMC users blocked.

This will not be even considered.
