### ISSUE TITLE
Cannot adjust maximum RAM Allocation

### ISSUE THREAD

**Issue by Commandore32** [MultiMC/MultiMC5#4104]
### Operating System

Windows

### Description of bug

I'm on windows 10. When I go into the java section of the settings menu and set the maximum RAM allocation to 2048 MB (the amount recommended in the FAQ) started the instance, a window popped up saying "could not start java virtual machine". 

### Steps to reproduce

Open the settings menu

Set the RAM to 2048MB.

### Suspected cause

I upgraded from 32 bit java to 64 bit java and that fixed the issue.   https://www.java.com/en/download/manual.jsp  and then I clicked on windows offline (64bit) 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by arthomnix** [comment]
if you fixed the problem why did you open an issue?
