### ISSUE TITLE
Java.io.IOException error on all lan games

### ISSUE THREAD

**Issue by Admhackbar** [MultiMC/MultiMC5#4107]
### Operating System

Windows

### Description of bug

When we try to play a LAN game, it always shows the same error. The other player joins for a moment or too, but never loads anything before being kicked off.
[01:47:01] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: Flippedyfrogs lost connection: You have been disconnected due to an illegal client.
If you have added a mod to your client, please remove this mod before you join the server again.
Illegal Mods:
minecraft
forge
foamfixcore
randompatches
itemblacklist
concheckrmd
crafttweaker
mtlib
modtweaker
jei
abyssalcraft
actuallyadditions
forgeendertech
adhooks
aether_legacy
aiimprovements
akashictome
placebo
apotheosis
appleskin
ctm
appliedenergistics2
baubles
gbook_snapshot
thaumcraft
arcanearchives
astralsorcery
autoreglib
badwithernocookiereloaded
bdlib
betterbuilderswands
betterquesting
patchouli
bewitchment
bibliocraft
biomesoplenty
guideapi
bloodmagic
bonsaitrees
bookshelf
redstoneflux
cofhcore
boptools
botania
botanicbonsai
codechickenlib
chickenchunks
roots
mysticalworld
chisel
classiccombat
clumps
cofhworld
mantle
endercore
thermalfoundation
thermalexpansion
enderio
enderiointegrationtic
tconstruct
conarm
cookingforblockheads
cosmeticarmorreworked
ctgui
crafttweakerjei
cucumber
custommainmenu
cyclopscore
ding
eerieentities
ebwizardry
mysticalmechanics
embers
eplus
enchdesc
enderiobase
enderioconduits
enderioconduitsappliedenergistics
enderioconduitsopencomputers
enderioconduitsrefinedstorage
forestry
enderiointegrationforestry
enderiointegrationticlate
enderiomachines
enderiopowertools
enderstorage
endreborn
enhancedarmaments
everlastingabilities
evilcraft
evilcraftcompat
theoneprobe
extrabotany
extrautils2
zerocore
bigreactors
fastleafdecay
foamfix
forbidden_arcanus
forgelin
futureminecraf
gunpowderlib
ichunutil
teslacorelib
industrialforegoing
mysticalagriculture
mysticalagradditions
harvestcraft
randomthings
mcjtylib_ng
rftools
rustic
immersiveengineering
integrationforegoing
inventorytweaks
ironbackpacks
ironchest
itlt
journeymap
kinetic anti-cheat
lozmod
magicalmap
psi
magipsi
magicclover
mobdismemberment
morph
mousetweaks
llibrary
mowziesmobs
mystgears
naturesaura
netherchest
recipehandler
norecipebook
neid
oreexcavation
rats
xreliquary
resourceloader
roguelike
rusticthaumaturgy
rusticwitchcraft
scavenge
sit
soot
stg
thaumicenergistics
tcinventoryscan
thaumictinkerer
thaumicwonders
thermalcultivation
thermaldynamics
thermalinnovation
tinkersaether
tinkertoolleveling
tp
torchmaster
totemic
tropicraft
wanionlib
wards
waystones
woot
xnet
ynot
lemonlib
arcaneworld
phosphor-lighting
reauth
mysticallib
teslacorelib_registries
unidict

### Steps to reproduce

Try to join a LAN game.

### Suspected cause

No idea

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by Admhackbar** [comment]
So you mean to say, that every single game I run through MultiMC and try to do LAN is the fault of every mod pack available and not MultiMC?

**Comment by phit** [comment]
MultiMC doesn't claim anything, it just launches the game the message you are getting doesn't come from MultiMC like anything else you see in game.
