### ISSUE TITLE
I can't see 1.17 suitable version of forge on MultiMC5

### ISSUE THREAD

**Issue by Huso112** [MultiMC/MultiMC5#4108]
### Operating System

Linux

### Description of bug

multimc-bin package doesn't provide forge for 1.17
https://imgur.com/a/CKsWs98

----MY QUESTİONS----
Will it come? 
When will it come?
Is there any temporarily solution fot that?
I know this is duplicate but i want further information about that.
--------
### Steps to reproduce

Create new profile with 1.17
Click "edit profile"

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
read https://github.com/MultiMC/MultiMC5/issues/3936
