### ISSUE TITLE
Trying to play Minecraft Beta 1.7.3 crashes my game...

### ISSUE THREAD

**Issue by Nile64** [MultiMC/MultiMC5#4109]
I can't play Minecraft Beta 1.7.3, or any old version. Here is my error: https://docs.google.com/document/d/1jYmb_-L-CzFHlsOWbjIcO4_llrf238zvnDoGb3pCdPo/edit?usp=sharing

I only got it to run ONCE, and that time nothing even rendered. Only the UI except for text, and the sun rendered. What is going on?
OS: Windows 10
CPU: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz, 3200 Mhz, 4 Core(s), 4 Logical Processor(s)

Please give me an answer, I want to play old versions of Minecraft, install mods, and have fun. I can play new versions, but not versions that are 1.2.5 or lower. They just crash immediately.

**Comment by jamierocks** [comment]
This isn't a bug with MultiMC, but rather game support.

This is a bug tracker for MultiMC, and therefore not the appropriate place for game support. There are many communities which may be able to provide game support for you - the MultiMC Discord being one, but also the Minecraft subreddit, Minecraft Forums, the #minecrafthelp IRC channel, and potentially many more.
