### ISSUE TITLE
Microsoft account has expired and needs to be logged into again

### ISSUE THREAD

**Issue by FeedTheChunk** [MultiMC/MultiMC5#4110]
### Role

I play modded MC

### Suggestion

Re-enabling the link with MS is very "clunky"

### Benefit

Profide feedback on how to log into your MS account.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

There could be more information / feedback provided to the user on how to log into their MS account wiht MultiMC.  I was able to get it to work by going into the user manager and clicking "add Microsoft' which worked but was not very intuitive.

c

**Comment by phit** [comment]
this popping up all the time is tracked as a bug here https://github.com/MultiMC/MultiMC5/issues/4071
