### ISSUE TITLE
New Microsoft feature

### ISSUE THREAD

**Issue by aegd3** [MultiMC/MultiMC5#4111]
### Operating System
Linux

_No response_

### Description of bug

I updated my old multimc and was static to see that you now bring Microsoft accounts into the mix.
After trying to get my account into multimc, the code seems to expire as soon as i enter it, I feel like you are harbouring accounts. Maybe that is a paranoid accusation, but that is what one thinks when the Microsoft Code expires immediatelly.

Pls fix it, i would'nt want my account stolen.
Hope it is a bug.

### Steps to reproduce

Started multicmc, tried to add Microsoft account. Code expired in 20sec. (Did this 4 times, every Microsoft code was expired before I could finish).

### Suspected cause

Dont know, maybe a bug in the system... I hope.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
User code expiration time is set by Microsoft, we have no control over the length.

We don't 'harbour' user accounts, indeed all queries happen locally. The code is publically visible, so do whatever audit you please.
