### ISSUE TITLE
Multimc being unable to run modpack 

### ISSUE THREAD

**Issue by God3Tier** [MultiMC/MultiMC5#4112]
https://paste.ee/p/lRajq 
this is the crash log 
https://paste.ee/p/5mI3F
this is the load up log 
This happens for all the modpacks pls help me

**Comment by God3Tier** [comment]
Tested, there is no problem with 1.12.2 modpacks. only 1.16.5

**Comment by jotoho** [comment]
This is game support, not an issue with MultiMC. Try your luck somewhere else, this bug tracker is not the right place for these kinds of problems.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by phit** [comment]
make sure you uncheck
![image](https://user-images.githubusercontent.com/2097483/134182579-07135a2e-733b-4174-9ae7-6e8142380af5.png)

If you need further help you can try asking in the [MultiMC Discord](https://discord.gg/multimc).
