### ISSUE TITLE
Oceanblock File Download issue

### ISSUE THREAD

**Issue by TheEternalDerp** [MultiMC/MultiMC5#4114]
When I try to start a new game in Oceanblock (a FTB modpack) in its 1.0.1 version, the game launches but does not take you to the starter island. On top of this, a command you are supposed to use to make your island does not work. Went to the FTB discord to see if it was on their end and was told that it was a MiltiMC downloading issue, as the pack works just fine through the FTB app. The same bug happens in 1.0.0

**Comment by jamierocks** [comment]
This should be resolved as of https://github.com/MultiMC/MultiMC5/commit/433dd2d16168845889373ffb98a9f3b806ea1de2 :)
