### ISSUE TITLE
Can't add Microsoft account on linux

### ISSUE THREAD

**Issue by Alex-2Pi** [MultiMC/MultiMC5#4115]
Before I transferred my account to Microsoft, I was able to add an account to the launcher.
Or the walker to start adding, it wasn't finished, because launcher probably didn't want to add the account because I didn't have MC assigned to it.
After the transfer, the launcher obviously couldn't connect to the mojang account.
When I wanted to add a Microsoft account, it turned out that I could not click the button and it is grayed out.

**Comment by jamierocks** [comment]
This is a bug with the package you are using, seek support from them.
