### ISSUE TITLE
Fetch mods from CurseForge and download and install them from the launcher itself

### ISSUE THREAD

**Issue by tralph3** [MultiMC/MultiMC5#4116]
### Role

I play modded Minecraft

### Suggestion

I want MultiMC to provide an interface for browsing and downloading mods automagically on a specific instance, with warning for incompatible versions

### Benefit

It would make managing mods much easier, and you could create your own packs for re-downloading.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

If there's more questions about how this could work, I'm all ears. I think it's pretty self explanatory tho.

**Comment by jamierocks** [comment]
This is a duplicate of many previous issues.

**Comment by tralph3** [comment]
Could you please link to any of those? I haven't been able to find one. Thanks.

**Comment by jotoho** [comment]
@tralph3 These are just those that I found. There may be lots more on this bugtracker.

Duplicate of #3422, #3761, #3779, #3696 (and #3176 ?)
