### ISSUE TITLE
Can't login after migration

### ISSUE THREAD

**Issue by raygradzewicz** [MultiMC/MultiMC5#4119]
### Operating System

Windows

### Description of bug

I just migrated my mojang account to my microsoft account, and I can't login with my mojang account anymore. I can't find a way to login with a microsoft account either.

### Steps to reproduce

Migrate your account and try to login.

### Suspected cause

_Migration_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
Use Login with Microsoft.
