### ISSUE TITLE
Solution to increase portability

### ISSUE THREAD

**Issue by anoraktrend** [MultiMC/MultiMC5#4121]
### Role

I play Minecraft on my raspberry pi 400, and on nonstandard operating systems such as Iglunix, Aalbus, Chimera, and other operating systems that have all other dependencies but are unable to run the binary as is without significant patching.

### Suggestion

Update Build.MD to discuss how to enable microsoft account sign-in.

### Benefit

To be able to have a method to sign in to my Microsoft account to play Minecraft using multimc.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

As a bonus, this would allow home builds to be fully featured, giving gentoo ebuilds and AUR -git pkgbuilds more functionality.

**Comment by Zetabite** [comment]
There needs nothing to be add. Its in the relevant code on how to enable MSA. Furthermore, there are no plans to support platforms that arent supported by Minecraft Java Edition.
