### ISSUE TITLE
21w38a Telemetry

### ISSUE THREAD

**Issue by LONGACAT** [MultiMC/MultiMC5#4123]
### Role

Playing any version of Minecraft newer than 21w38a (2021-09-23)

### Suggestion

Add a toggle that can disable the telemetry, preferably disabling it by default

### Benefit

The telemetry is not fully anonymous, which is a privacy concern. To my knowledge, it collects way too much data and cannot be disabled

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
telemetry needs to be enabled by the launcher, MultiMC does not do this and there's no plan to do so

**Comment by Ohio2** [comment]
this makes no sense as to why it needs to be enabled by the launcher
