### ISSUE TITLE
stutters while playing

### ISSUE THREAD

**Issue by LookAgain2** [MultiMC/MultiMC5#4126]
i play on multimc for 1.16.1 speedruns so the only mods i have loaded are fabric and mrmangohands sodium. i checked the F3 screen and i have over 100 fps and my computer is very powerful. i am not using any other programs or mods and after about 10/20 minutes into a game or when i try to share my screen on discord i keep on getting extreme stutters despite still having high fps.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your game, you can try asking in the mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
