### ISSUE TITLE
Document which API keys are necessary, and how to get your own

### ISSUE THREAD

**Issue by FintasticMan** [MultiMC/MultiMC5#4129]
### Role

I want to build the launcher myself, with my own API keys.

### Suggestion

I want the documentation to explain what is necessary to build this project with all of the features such as Microsoft Accounts.

### Benefit

If there is proper documentation, creating a build for personal use will be easier.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I would like it to be explained in `BUILD.md` how to get and incorporate whatever is required to use a personal build of this launcher. I would rather not use a precompiled binary, and I understand that it's not possible to publish your API keys due to the Microsoft Terms of Service.

**Comment by jamierocks** [comment]
See https://github.com/MultiMC/MultiMC5/blob/develop/notsecrets/Secrets.cpp

**Comment by peterix** [comment]
We don't really have anything pointing people there. But yeah, that's where the MS client ID is.

**Comment by FintasticMan** [comment]
Thanks! I hadn't seen that before. I do still think it would be useful to add it somewhere more visible like the build instructions.
