### ISSUE TITLE
Default options on instance creation

### ISSUE THREAD

**Issue by 02JanDal** [MultiMC/MultiMC5#413]
When creating a new instance you often have to adjust some settings, like keybindings, GUI size etc. Minecraft stores this information in a key/value text file. It would be nice to have a settings page in MultiMC where you can enter some of these values, and they would then be used to create a default options file on instance creation.

This is relevant: http://minecraft.gamepedia.com/Options.txt

**Comment by TheDoctorsLife** [comment]
any update on this? this sounds like a really cool feature

**Comment by peterix** [comment]
Moved to [workflowy (Ideas -> Instance templates and default personal settings)](https://workflowy.com/s/2EyDMcp7CU).

**Comment by FolfyBlue** [comment]
Since this is closed, has this been implemented?

**Comment by Cwickks** [comment]
There should be a setting where it would create a main .minecraft folder that we could put files in it (options.txt, optionsof.txt, servers.dat, etc.). Then whenever we would launch an instance, or create a new instance (there should be a setting for this too), The files on the main .minecraft folder will overwrite the filles on the instance .minecraft folder. It could be further improved if it could convert the files if it is incompatible with the instance version.
