### ISSUE TITLE
Telemetry for all instances and launcher

### ISSUE THREAD

**Issue by nironotaken** [MultiMC/MultiMC5#4130]
### Role

To fix bugs and crashes 

### Suggestion

If instance or launcher crashes, telemetry is starting

### Benefit

Easier issues fixes for instances and launcher

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by jamierocks** [comment]
I'm not sure what you're suggesting?

**Comment by kb-1000** [comment]
MultiMC does not, and will not, collect crash reports automatically.
You can still upload your log manually and share the link, though.
