### ISSUE TITLE
Resource pack Folder button not work.

### ISSUE THREAD

**Issue by wllp** [MultiMC/MultiMC5#4134]
I installed multi mc form a backup I had and it seems to work we'll exception for some minor texture bug in game. I'm in the middle of troubleshooting an install of my Multi MC. I have this error message on most of my modded instances:![image](https://user-images.githubusercontent.com/16256066/135534249-587e848f-cec8-40c0-a69f-a6f02e58f883.jpeg)

It may or may not be related to my issue with loading said resource pack. I also wonder if it is indicative of a larger problem. I'm attempting a fresh install on a different file path. If that work I might also try a reinstall on the original (preferred "C :/games" file path.

**Comment by wllp** [comment]
Well the fresh install didn't help. So it's not where multi mc was or anything. Also I tried to make a mew instance and it didn't seem to have any issue so that's something. Must be something about my old instances then that's corrupt or wrong

**Comment by jamierocks** [comment]
Please re-submit, and fill in our issue template.

**Comment by wllp** [comment]
So sorry, I didn't know there was a templet. I was typing it out on my phone so maybe that had something to do with it? Where can I find this templet? I check the wiki and there was no mention of it. In the report a bug section.

**Comment by jamierocks** [comment]
It should appear with a list of templates when you go to create a bug report, if not https://github.com/MultiMC/MultiMC5/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug_report.yml should work :)
