### ISSUE TITLE
Random crash on startup ATM 6

### ISSUE THREAD

**Issue by KillerDamena** [MultiMC/MultiMC5#4136]
### Operating System

Windows

### Description of bug

On startup it crashed before loading into server.

### Steps to reproduce

Try and join.

### Suspected cause

Conflicting error codes.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by KillerDamena** [comment]
https://paste.ee/p/9xA8M

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
