### ISSUE TITLE
Allow the "Upload" button on screenshots page to send to ShareX

### ISSUE THREAD

**Issue by Permanently** [MultiMC/MultiMC5#4137]
### Role

I tend to take screenshots in Minecraft, then upload them in order to quickly get them online. A lot.

### Suggestion

It's pretty self-explanatory - but essentially it's just hooking into ShareX so that whenever the upload button is pressed on a screenshot, instead of uploading straight to Imgur it'll be sent to ShareX, and from there can be shared however the user wants.

### Benefit

So that users can keep all their uploaded screenshots in one place - as well as allowing users to customise how they share screenshots and where they are uploaded to.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I can't imagine it being particularly hard - [it's already in the context menu](https://i.imgur.com/3RNastZ.png) and there's two different browser extensions for ShareX. I wouldn't know, though.

**Comment by phit** [comment]
ShareX is Windows only and integrations with software like this makes no sense for MultiMC, just open the folder and use the existing context menu.
