### ISSUE TITLE
Cannot start Forge 1.12.2

### ISSUE THREAD

**Issue by pog5** [MultiMC/MultiMC5#4138]
### Description of bug

When trying to start a instance that has Forge 1.12.2, the game does not start. The Log Shows
```
Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance 1.12.2 Anarchy' failed to process:
https://files.minecraftforge.net/maven/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
https://files.minecraftforge.net/maven/com/typesafe/config/1.2.1/config-1.2.1.jar
https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2855/forge-1.12.2-14.23.5.2855-universal.jar
https://files.minecraftforge.net/maven/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
https://files.minecraftforge.net/maven/org/jline/jline/3.5.1/jline-3.5.1.jar
https://files.minecraftforge.net/maven/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
https://files.minecraftforge.net/maven/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
https://files.minecraftforge.net/maven/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
https://files.minecraftforge.net/maven/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
https://files.minecraftforge.net/maven/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
https://files.minecraftforge.net/maven/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
https://files.minecraftforge.net/maven/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
https://files.minecraftforge.net/maven/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
https://files.minecraftforge.net/maven/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
https://files.minecraftforge.net/maven/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
```
However, I can perfectly visit and download these files manually, the only way to play is to dowlnload all of them, put them i ntheir prespective folders (for ex: https://files.minecraftforge.net/maven/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar will be put in multimc\libraries\org\scala-lang\scala-xml_2.11\1.0.2) and then play offline mode, and for some reason, selecting offline mode puts me into online mode if i do not change the username, only complain is that there is no audio.

### Steps to reproduce

1. Create a new 1.12.2 Instance
2. Go In Versions > Install the newest Forge Version
3. Try to start the game.

### Suspected cause

Probably a bug regarding network conectivity.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Zetabite** [comment]
please upload the full log of the instance like that: https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by phit** [comment]
please try this https://github.com/MultiMC/MultiMC5/issues/4141#issuecomment-932809304

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, after trying the above solution, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
