### ISSUE TITLE
Can't Log With Mojang Account ?

### ISSUE THREAD

**Issue by SmolYee** [MultiMC/MultiMC5#4148]
### Operating System

Windows

### Description of bug

I haven't played Miencraft in a while, so when I opened the Minecraft Launcher it asked me to log in again, so I know my information are correct. When I opened MultiMC it asked me to log in again as well, but when I enter the same email and password I used for Mojang it says "Mojang user authentication failed" and I can't log back in to play... 

### Steps to reproduce

I tried deleting the account off of MultiMC, closing the program and opening it again, and someone told me to look for any errors in the program folders, didn't see anything either. I'm a bit clueless...

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Please don't make an issue when you are already getting support on Discord, the place for support.
