### ISSUE TITLE
Unable to launch MC even after downloading Java

### ISSUE THREAD

**Issue by beeouib** [MultiMC/MultiMC5#4160]
https://paste.ee/p/pYTUL

Wanted to try a modpack so I used this. I downloaded java (even though with the current mc launcher you don't need it?) but it still won't work. Apologies for the trouble

**Comment by phit** [comment]
Reboot your PC and try again, if you are still having issues after, the better way to get support is the [MultiMC Discord](https://discord.gg/multimc). Github is for feature request and bugs.
