### ISSUE TITLE
MultiMC on FreeBSD

### ISSUE THREAD

**Issue by glowiak** [MultiMC/MultiMC5#4162]
### Operating System

Other

### Description of bug

Hi.
MultiMC is working on Windows XP right? Even micro$hit auth works there;
There's an OS called FreeBSD ( http://freebsd.org ), which is used by more people than xp;
MultiMC doesn't provide official binaries for it, there are unofficial Ports ( http://freshports.org/games/multimc , https://git.cameronkatri.com/freebsd-ports/tree/games/multimc?h=main , https://codeberg.org/glowiak/FreeBSD-Ports/src/branch/master/games/multimc ), first one is still on 0.6.11, last two are on 0.6.13, but as MMC MSAID keys aren't published (and you've banned everyone, who leaked it), so M$ auth doesn't work on FreeBSD; Some time ago, there was ChunkLauncher ( https://github.com/herbix/chunklauncher ) that supported M$ accounts, but it recently broke;

There are several ways to make mmc m$ auth work on FreeBSD:
-publish official binaries for FreeBSD (this isn't too hard)
-publish MSAID key, so the Ports can be built from source and use it (better way)

Please, do something with this.
Thanks

### Steps to reproduce

Install any of those ports and look that 'Add microsoft' button is grayed out

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by glowiak** [comment]
There's also OpenBSD port ( http://openports.se/games/multimc ), but it's still on 0.6.12

**Comment by glowiak** [comment]
@jamierocks We have many ports with that Minecraft can work as normal. Only good launcher is missing.

**Comment by glowiak** [comment]
IT WORKS!!!

**Comment by glowiak** [comment]
For now, I'm asking if I can publish my port that uses MY MSAID key.

**Comment by peterix** [comment]
And what @phit said - every comment said there applies to this too.
