### ISSUE TITLE
screen record issue

### ISSUE THREAD

**Issue by OoYinYuoO** [MultiMC/MultiMC5#4174]
### Operating System

Windows

### Description of bug

Why i screen record the size don't fit, 3/4 of the video is black, only 1/4 of the video was my screen

### Steps to reproduce

idk

### Suspected cause

idk

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
