### ISSUE TITLE
[Parity] Allow underage accounts to log in without a family

### ISSUE THREAD

**Issue by jgcodes2020** [MultiMC/MultiMC5#4175]
### Operating System

Ubuntu 21.10, but should be reproducible on all operating systems

### Description of bug

I am under 18. On the official launcher I can log in just fine. MultiMC states that I need to link my account to a family or wait until I turn 18.

### Steps to reproduce

- Try to sign in with an underage account
- Find out that you can't sign in

### Suspected cause

This is likely due to MultiMC being a third-party service. Implementation of a bypass will either require more reverse-engineering or direct coordination with Microsoft themselves.

I doubt this bug can ever be resolved properly for the above reasons.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
Not a bug, intentional by Microsoft.
