### ISSUE TITLE
Ability to share resourcepacks/saves/screenshots between instances

### ISSUE THREAD

**Issue by ZephireNZ** [MultiMC/MultiMC5#42]
It'd be awesome if your saves and/or resourcepacks would persist across instances. It could be set up as a toggle globally, or per instance.
I use the same texture pack on multiple different instances, so the ability to update one and it would update all would be quite helpful.

To a lesser extent, a global place to store screenshots would be nice, but that's a pretty niche feature and doesn't impact the game terribly.

**Comment by DrZed** [comment]
Dammit I really want this soon :|

**Comment by Kilobyte22** [comment]
You can use symlinks now. The copy/delete thing is fixed.

**Comment by peterix** [comment]
Well, the `delete` thing is fixed on Windows.
Both `copy` and `delete` are fixed on unix.

But yes, you should be able to use symlinks, just need to fix things up after an instance copy on Windows.

**Comment by DrZed** [comment]
Symlinks? Explain?

**Comment by lekro** [comment]
With a symlink, you can make programs think they are accessing something at
their target path ( in this case, <instance path>/screenshots ), but
actually have this point to some other directory. If the screenshots folder
of all desired instances is actually a symlink to a centralized screenshots
directory, all of those instances will dump screenshots into the
centralized directory while thinking they just put them in the instance's
screenshots directory. This way, no modifications need to be made to
Minecraft to use the central screenshots directory.

**Comment by DrZed** [comment]
Yeah But what should I use for arguements and where do I put them?
I wanna put all resource packs dir as C:\games\multimc\resourcepacks
and for screenshots similar dir just screenshots

**Comment by lekro** [comment]
I don't think Minecraft takes arguments for screenshots.

Not sure about the Windows command for symlinking, but if you install [Link Shell Extension](http://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html), you can follow the following steps:

* Create the resourcepack directory `C:\games\multimc\resourcepacks`.
* Right click that directory and select `Pick Link Source`.
* Navigate to where the resourcepack directories in the MultiMC instances are, delete those directories (copying resourcepacks where needed), and right click in the instance folder's background and select Drop As... > Symbolic link.
* Repeat for screenshots.

In linux, it's easier with the terminal command...
`ln -s ~/multimc/screenshots ~/multimc/instances/myInstance/screenshots`

Of course, the existing screenshots directories in the instances need to be deleted and their contents moved before executing this command.

**Comment by DrZed** [comment]
Thanks guys :D I got bored
https://github.com/DrZed/DrZed-symlink-Script-D

Also command for windows is
mklink

**Comment by peterix** [comment]
Reclassified as idea..

Some of the approaches detailed here should be on the wiki, or some sort of article where people can read about them and learn to use them.

**Comment by peterix** [comment]
[Moved to workflowy (Chores -> Set up some sort of interview/article thingy, Ideas -> Share resources between instances)](https://workflowy.com/s/2EyDMcp7CU)

**Comment by ShayBox** [comment]
Some sort of checkbox area per instance that will automatically symlink the checked box's related files/folders to a set of global files/folders, etc check servers and resource packs, it will symlink them to a global set in the multimc folder, not impossible to do from a users end but annoying, and really the only reason I don't use this over the default launcher. It some files/folders it should include are

- resourcepacks
- texturepacks
- servers.dat
- options.txt
- optionsof.txt
- mods
- shaderpacks
- saves
- screenshots
- config

**Comment by peterix** [comment]
Symlinks are not usable.

**Comment by DrZed** [comment]
I beg to differ I already use them with my MMC for my Resource Packs... You need to run the command through cmd and it needs to be admin I'm 99% sure (I made my own Symlink script on my github)

**Comment by Artoria2e5** [comment]
Symlinks *are* usable across platforms. On \*nix systems the solution is obvious, while on Windows we can do junctions. True, junctions only apply to folders on the same file system, but all the requests here are done on the folder level anyways.

**Comment by rzimmerdev** [comment]
Hows this going along?
