### ISSUE TITLE
Add ability to use folders as resource packs.

### ISSUE THREAD

**Issue by ghost** [MultiMC/MultiMC5#421]
You can manually create a folder or symlink to a folder but there should be an add folder button to handle that automatically. Currently only .zip files can be selected.

Its fairly useful because it saves a bit of loading time if you have a slow processor and lets you edit the pack without rezipping, instead you can just press F3+T.

**Comment by peterix** [comment]
You can drag and drop folders in though.

**Comment by peterix** [comment]
Moved to workflowy (Ideas -> Resource pack list):
https://workflowy.com/s/2EyDMcp7CU
