### ISSUE TITLE
[Request] "Changelog" for the instance

### ISSUE THREAD

**Issue by dav20011** [MultiMC/MultiMC5#423]
Its really hard to know whats causing issues if I updates more than 10 mods and dont remember what mods these were. It would be very usefull if Multimc creates a log, wäre I can see, I updated TiC, Thaumcraft..., so I can test disabling these and fix The bug, otherthise I have to test every mod

**Comment by peterix** [comment]
Added to workflowy (Ideas -> Packs):
https://workflowy.com/s/2EyDMcp7CU
