### ISSUE TITLE
Use Breakpad for crash collection on Windows

### ISSUE THREAD

**Issue by 02JanDal** [MultiMC/MultiMC5#424]
The current crash handler barely works, and we still haven't got a system for converting a stacktrace to a human-readable format. It looks like [Breakpad](http://code.google.com/p/google-breakpad/) could be a nice fit for our usecase.

**Comment by peterix** [comment]
The idea is to write a minidump to the multimc folder and tell the user what to do with it on next startup:
* report bug on github
* provide the file

No breakpad-specific server part is needed in the first step.
The symbol file would then be only generated for the main binary.
Breakpad has to be installed on the builders -- that means Windows -- so MultiMC can be linked to the libs. CMake can find breakpad, and it could be customized to find the Windows install.

The symbol file should end up on the current mmc update repository or something similar. The json version files should include the symbol files that were generated for a particular build.
A script can scan the minidump for mmc version/build and grab the right symbol file.

The symbol file should not end up inside the distributed stable zip, or be downloaded during updates.

Windows has priority.

**Comment by 02JanDal** [comment]
All sounds correct, just wanting to clarify that there is no official breakpad server. Mozilla has a web interface for it called Socorro, but you can use breakpad without it. Given the symbol file and the minidump you can generate the stack trace on most operating systems.

I would also say we should include symbol files for Qt, even if Qt isn't compiled with debugging symbols you still get the (namewrangled) names in the stacktrace, which are quite useful.

**Comment by peterix** [comment]
Yeah, that can be done as the second step. I'd like to just have the bare minimum working first.

**Comment by 02JanDal** [comment]
Also, for good measure, link to Socorro: https://wiki.mozilla.org/Socorro

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Use Breakpad for crash collection)](https://workflowy.com/s/2EyDMcp7CU)

**Comment by peterix** [comment]
Let's just assume it doesn't crash, because I simply do not get reports of crashes all that often.
