### ISSUE TITLE
QuickMod: Unable to download NEI jar files

### ISSUE THREAD

**Issue by ZephireNZ** [MultiMC/MultiMC5#431]
Using my QuickMod repo (http://github.com/ZephireNZ/QuickMods) I've got a couple mods set up for NEI and its dependencies. The download URLs provided by chicken_bones (eg http://adf.ly/q7I9O) use an adfly link that further links to a downloader.

MultiMC isn't downloading the file, despite it downloading automatically inside of a web browser. The screen shown is this: http://i.imgur.com/l0WWK2u.png
The log, just in case: http://pastebin.com/szDKYP9C

**Comment by peterix** [comment]
Quickmods are being replaced by a better solution.
