### ISSUE TITLE
Sandbox mods

### ISSUE THREAD

**Issue by 02JanDal** [MultiMC/MultiMC5#437]
There's no good way to quickly tell if a mod is malicious or not, and currently they can write to everywhere on the filesystem where the current user has access, launch subprocesses, and access arbitrary ports on arbitrary hosts. This can be solved by adding a setting that installs a java.lang.SecurityManager that intercepts possibly dangerous calls.

**Comment by peterix** [comment]
I'm not going to consider doing this. It's too much, and it would break more than it would solve.

This should be done by whoever maintains the mod repositories.

**Comment by peterix** [comment]
Yeah... let's just say that this is a 'no'.
