### ISSUE TITLE
Silent updating

### ISSUE THREAD

**Issue by yuuka-miya** [MultiMC/MultiMC5#440]
As discussed on IRC. Add an option in settings for "always update, don't ask me".

This is especially useful for development channel users due to the frequency of updates on that channel.

Also, would be nice if you could do something about that finish button ;)

**Comment by peterix** [comment]
Looks like I forgot about this one.

I really do not want silent updating to be a thing. Looking at what sort of issues we got with 0.4.8, 0.4.9 and 0.4.10, it would be a support nightmare waiting to happen.

And read the changelogs if on develop before you update.

I added it as an idea to workflowy:
https://workflowy.com/s/2EyDMcp7CU (see Ideas -> Updater section)

**Comment by peterix** [comment]
Yeah, no.
