### ISSUE TITLE
Instance version broken based on account status

### ISSUE THREAD

**Issue by pexner** [MultiMC/MultiMC5#445]
Here are two logs.
No default Account set -> strange Icon and "edit instance" is grayed-out.
http://pastebin.com/raw.php?i=SeBb6CrP

Default Account IS SET -> no strange Icon. All seems OK.
http://pastebin.com/raw.php?i=uvbuNGck

Here's a screenshot:
https://dl.dropboxusercontent.com/u/23135995/StrangeIconWhenNoDefaultAccount.png

**Comment by peterix** [comment]
Well, I guess we'll never know ~_~
