### ISSUE TITLE
MultiMC freezes up for a while when a QuickMod has a lot of information to display

### ISSUE THREAD

**Issue by Heufneutje** [MultiMC/MultiMC5#450]
Thermal Expansion and Forestry are a good examples of this. Clicking on either of these in my QuickMods window tends to cause MultiMC to freeze up completely (registered as non responsive by Windows) for about 10 seconds. I imagine this is also influenced by the speed of the internet connection.

**Comment by peterix** [comment]
Quickmods are being replaced by a better solution.
