### ISSUE TITLE
FTB Packs - 'instMod' folder -  disappear after merging MultiMC and FTB

### ISSUE THREAD

**Issue by Slybianco** [MultiMC/MultiMC5#457]
I needed to modify some mods inside this folder, in particular, 'MinecraftForge.jar' the only way to access to this file is the instMod folder inside FTB pack folder. Creating a new istance from FTB, I'm able to access JarMod and instMod from FTB launcher, and physically, of course. But after opening these istances from MultiMC (Direwolf20 - Monster) I'm no more able to open/use/modify these folders. I tryed a new modpack from FTB launcher (Unleashed) and I can access JarMod and instMod.

**Comment by peterix** [comment]
No idea, closing.
