### ISSUE TITLE
Removing Resource Pack Crashes

### ISSUE THREAD

**Issue by TheOfficialJosh** [MultiMC/MultiMC5#471]
Removing a Resource Pack when the game is open or after the game closes, crashes MultiMC.

MultiMC-0.log: http://paste.ee/p/Nbfb7

**Comment by peterix** [comment]
Quickmods are being replaced by a better solution.

**Comment by peterix** [comment]
This was reported on that dev version that had quickmods in it - very briefly.

If it's still happening in current develop/unstable, please reopen.
