### ISSUE TITLE
Crash when removing Mod after game has been started once

### ISSUE THREAD

**Issue by Galaxy2Alex** [MultiMC/MultiMC5#476]
MultiMC crashes when trying to remove a mod after the game has been started once and the launcher has not been closed (set to "Keep Open"). Might also affect Ressourcepacks, haven't been able to check it.

MMC Version: 0.5-dev351

Windows Crash Log:
~ Log Start ~
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	MultiMC.exe
  Application Version:	1.0.0.0
  Application Timestamp:	01b54340
  Fault Module Name:	MultiMC.exe
  Fault Module Version:	1.0.0.0
  Fault Module Timestamp:	01b54340
  Exception Code:	c0000005
  Exception Offset:	000ee0ad
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	d1d9
  Additional Information 4:	d1d94a13d3609d6b740644c12508f581
~ Log End ~

**Comment by peterix** [comment]
If this is still a problem reopen.
