### ISSUE TITLE
QuickMod (G)UI/UX re-thinking

### ISSUE THREAD

**Issue by 02JanDal** [MultiMC/MultiMC5#478]
The current UI is a mess, because I suck at making things look good/be usable. Some ideas for improvement:

- [ ] Option to only have a single search line. To search for things like tags etc. you'd use #<tag> etc.
- [ ] QuickMods are a single list, removing the right part of the current QuickMods page. To view more information we could either have all items be big, or the current item show everything.
- [ ] Merge QuickMods page with Loader Mods. When clicking a button the dialog size would be doubled, and the current QuickMods page would be shown to the right of the current Loader Mods page. Would use d&d for installation, with an extra button if people don't get it.
    * Could also create a tab view on the right and have a tab for the central mods folder.
    * For the distant future: Merge Versions/Loader Mods/Core Mods/Resource Packs into one page. Either as a single flat list or as a tree with the current pages as root items.
    * Double clicking would open the full view in the same space as the list occupies
    * Breadcrumbs for tags, categories, etc.
- [ ] Remove the global QuickMods page from the settings dialog, and add it to the New Instance dialog somehow.

Feel free to comment with more suggestions.

**Comment by peterix** [comment]
This is now only a historical reference. Linked from workflowy.
