### ISSUE TITLE
Didn't select a version for...

### ISSUE THREAD

**Issue by Meegooo** [MultiMC/MultiMC5#483]
Tried to create one quickmod file for projectred, that will download all modules. Used "installType" : "group" for that. Got an error "Didn't select a version for projectred".
Tried to add some URL. Didnt work.
Tried to switch installType to "forgeMod". Didnt work either.
Just because i can, tried "forgeMod" without URL. You guessed, didnt' help
Tried to delete all dependencies. Worked.
Tried to add one back, didn't work.
Thought the problem was in modules' quickmod files. Tried to use them directly, it worked, but client crashed because FMP didnt download.
Added it manually. Client lauched after about 6th try, because MMC didn't want to resolve it. And when it did, MMC was crashing.
Tried to put dependencies back to that file... AND IT WORKED.
You can see everything i did in the dev branch.
Dev branch now works. https://github.com/Meegooo/QuickModsRepo/tree/dev
Created another branch and rolled back to the state, where it wasn't working https://github.com/Meegooo/QuickModsRepo/tree/Didn't-select-a-version-for-projectred

**Comment by peterix** [comment]
Quickmods are being replaced by a better solution.
