### ISSUE TITLE
Research using C++ QuickCheck libs for testing

### ISSUE THREAD

**Issue by 02JanDal** [MultiMC/MultiMC5#494]
I recently watched a talk on Haskell, and the part that probably interested me the most was QuickCheck, basically automatically generated unit tests.

There exist several C++ implementations of QuickCheck, so this issue is about seeing if one of them would be useful, as well as adding a few unit tests using the selected library.
The library would need to be able to handle custom (Qt or ours) data types.

* [QuickCheck++](http://software.legiasoft.com/quickcheck/)
* [autocheck](https://github.com/thejohnfreeman/autocheck)
* [CppQuickCheck](https://github.com/grogers0/CppQuickCheck)

**Comment by peterix** [comment]
OK. Maybe in a million years :)
