### ISSUE TITLE
Asset downloads fail without a sensible error reported to the user

### ISSUE THREAD

**Issue by SirMcArthur** [MultiMC/MultiMC5#509]
MultiMC4 Worked fine. however when i updated to MultiMC5 That's when stuff started to mess me up. everytime i try to make an Instance. it downloads stuff until it goes to the getting the assets files from mojang part. it's either gets stuck. or just shows me this error  
![screenshot_2](https://cloud.githubusercontent.com/assets/8802099/4298785/7ef3abf6-3e2b-11e4-9f1c-e9544afb1b14.png)
I tried reinstalling it. nothing worked. I am on the latest version. firewall and anti-virus is off yet it doesn't work. 
i am logged in with my minecraft account. nothing changed.

i tried to make other instances but those didn't worked too. I pretty much can't use MultiMC5 cause of this stupid bug...

Help please?

**Comment by peterix** [comment]
This is now generally a lot better - mmc will retry based on a queue where erroring downloads will go back to the end. Also, it no longer starts all those asset downloads at the same time and only does 6 at the same time.

So, closing.
