### ISSUE TITLE
Add ability to launch minecraft from edit instance / console window

### ISSUE THREAD

**Issue by luisfcosta** [MultiMC/MultiMC5#513]
Hello guys. I have long had a wish that MultiMC console window would allow me to relaunch mine craft from the console window. I don't think that would be too much of a hassle for you guys and It would be a major convenience feature for someone like me. We all know mine craft randomly crashes. I have the console set to stay open so I can see the log, but afterwards I have to click X and then double click the instance again. I know I am being lazy, but a simple "relaunch" next to "kill minecraft" would be very welcomed. Thank you for the great work!

**Comment by peterix** [comment]
Added to workflowy:
https://workflowy.com/s/2EyDMcp7CU

See Ideas -> Instance view

**Comment by peterix** [comment]
Done.
