### ISSUE TITLE
Runner script does not detect platform mismatch

### ISSUE THREAD

**Issue by Daboudreaux** [MultiMC/MultiMC5#522]
Not long ago I installed MultiMC on my younger son's computer.  I had to install some dependencies and finally got it working.  Now i'm trying to get it working on my older son's computer with the same operating system- Ubuntu 14.04.  I'm not sure what I'm missing this time.  Here is the error I get when I try to run it in the terminal:

cannot execute binary file: Exec format error

**Comment by peterix** [comment]
Why is this still open? We have a debian package now.
