### ISSUE TITLE
Only one copy of any given instance can launch at a time

### ISSUE THREAD

**Issue by CommunistWitchDoctor** [MultiMC/MultiMC5#526]
As stated in title, attempting to launch a second copy of a given instance only results in a crash

**Comment by peterix** [comment]
I will consider this in the upcoming launching rewrite. But right now, this is ``works as intended''. It protects users from disaster.

I am reclassifying this as an idea and moving it to workflowy (Next -> Separate out launcher part): https://workflowy.com/s/2EyDMcp7CU

**Comment by peterix** [comment]
Really, works as intended.
