### ISSUE TITLE
Modpack Testing Enhancement

### ISSUE THREAD

**Issue by RegisDeVallis** [MultiMC/MultiMC5#533]
This  is just a little feature. I don't expect anybody to add this to multimc. 

I enjoy creating instances with lots of mods. And I have always noticed that without looking at Minecraft, you can tell Minecraft loaded correctly just by reading the log. This works because when ever the Minecraft menu comes up,  the log says Opened initialized. 

It would be cool to have a feature for people  creating and testing modpack where you could press a button and multimc would launch Minecraft in nogui mode.  The  user can look at the log without having Minecraft in the way.  Also,  a notification would appear saying that the modpack worked because it logged the words OpenAl initialized. Also,  Minecraft would finish launching a lot faster because it isn't rendering anything. It's like starting a Minecraft server.

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Packs -> Modpack Testing Automation)](https://workflowy.com/s/2EyDMcp7CU)
