### ISSUE TITLE
OpenEye support

### ISSUE THREAD

**Issue by RegisDeVallis** [MultiMC/MultiMC5#544]
It's a new mod called OpenEye. Basically, it anonymously collects data and sends it to the mod makers. Its already compatable with most of the major mods, basically the FTB mods. Also, what makes this mod awesome is the fact that if minecraft crashes because of mods, it will tell you WHAT mod did it and HOW TO FIX the problem so it wont happen again.

http://openeye.openmods.info/faq

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Third party tool integration -> Integrate with OpenEye)](https://workflowy.com/s/2EyDMcp7CU)

It si much more likely that we'll use it for the raw data in its database, not the crash collection part.
