### ISSUE TITLE
Java 8u20 fix - Forge part

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#547]
Somehow implement this:
https://github.com/LexManos/LegacyJavaFixer

Requires sneaky ASM magic.

**Comment by peterix** [comment]
This should be implemented in wonko.

**Comment by TheDoctorsLife** [comment]
The legacy java fixer should only be put in on 1.6.4 versions of forge, as it's a forge bug.

**Comment by peterix** [comment]
and some 1.7.2 and 1.7.10 versions too...

Anyway, if you use latest forge on 1.6.4, the problem is gone.

**Comment by Kilobyte22** [comment]
You probably meant "if you use latest forge on 1.7.10"

**Comment by peterix** [comment]
No, there's actually an update for 1.6.4 forge, because Lex got tired of the people who couldn't find the LehacyJavaFixer :)

**Comment by TheDoctorsLife** [comment]
Oh gosh, that's ridiculous.

**Comment by peterix** [comment]
It makes this less of a real issue and more of a completionist thing :)

**Comment by peterix** [comment]
Not relevant anymore.
