### ISSUE TITLE
Opening imgur after uploading screenshot.

### ISSUE THREAD

**Issue by Meegooo** [MultiMC/MultiMC5#556]
Can you please make that configurable? Minecraft itself can eat about 4 gigs of ram, then you upload screenshot and chrome with tons of tabs opens => RIP PC.
I think making two buttons on window that pops up after uploading. First one being "Copy to the clipboard" and second one "Open in default browser"

**Comment by peterix** [comment]
Moved to workflowy (Ideas -> Screenshot upload):
https://workflowy.com/s/2EyDMcp7CU

**Comment by peterix** [comment]
I think this got fixed by us not opening the site in the first place.
