### ISSUE TITLE
SSL handshake error on Fedora 20 when adding new mojang account

### ISSUE THREAD

**Issue by kotoroshinoto** [MultiMC/MultiMC5#567]
http://pastebin.com/vvGbzhjY

no idea why the self-signed cert from the cert authority Starfield Technologies, Inc., Starfield Class 2 Certification Authority should be failing.

**Comment by asiekierka** [comment]
Can reproduce on CRUX, works fine on Arch Linux. I highly believe it is related to distro configuration - a "paranoid" or highly secure distro will fail on this kind of thing, as it's a Mojang fail.

**Comment by kotoroshinoto** [comment]
ya i'm still stuck on this one, tried again with the updated multimc

**Comment by kotoroshinoto** [comment]
@peterix  i'm not even sure its a fedora issue generally speaking. I might have done something while setting up and installing shit over the last year or 2 that borked security slightly just enough for it to care about minor definitions of wrong.

I have no idea what action I took caused this, so I also am equally mystified as to what I would have to do to revert the situation. My laptop has the same OS and many of the same packages installed.

I'll try running multimc on it and see if I have the same issue.

**Comment by kotoroshinoto** [comment]
It does indeed work properly on my laptop. Something is definitely different on the other system, but I'm at a loss as to what it is.

**Comment by peterix** [comment]
Just tested this on Fedora 23 and it's fine.

You just have to delete most of the libs MMC comes with and install Qt5 on the system.
For now, upgrade OS, the only keep the following files and folders in the MultiMC `bin` folder:
* jars
* libMultiMC_logic.so
* libnbt++.so
* librainbox.so
* libstdc++.so.6
* MultiMC
* updater

Everything else should be removed from the `bin` folder. Also remove the `plugins` folder from the main MultiMC folder.

Install system Qt5.

I'm going to look into packaging a minimal version and using system dependencies there.

**Comment by kotoroshinoto** [comment]
i think something is broken in my system's QT cacerts or security settings.
it only affects QT ssl. Makes no sense
