### ISSUE TITLE
Quickmods Issues

### ISSUE THREAD

**Issue by the-creamster** [MultiMC/MultiMC5#578]
I'm an admin of a small Aussie community and only recently built a custom 1.7.10 forge pack with quickmods; but when 3-5 of us tested it we all got varying degrees of bugs and successes. For example it downloaded every mod for me, but for 2 others it didn't download 1-5 mods, and was doing so inconsistently it couldn't be replicated easily.

Now the owner/head admin and me were going to do the pack with quickmods for simplicity purposes and had everything setup for a 120+ mod modpack, but due to the inconsistencies we've done it the old fashioned way(download, configure, then upload complete pack for each player to download themself).

Could we somehow get in touch with the quickmods devs to test/fix it??

Thanks, The_Creamster.
Note:
We do have a TS if you want to chat with us about it.
Website: http://technomancers-collective.com/

**Comment by peterix** [comment]
It is dead. I'm sorry :(
