### ISSUE TITLE
I'm having an issue with adding my account!

### ISSUE THREAD

**Issue by JerryWindhorn** [MultiMC/MultiMC5#582]
![multimc issue](https://cloud.githubusercontent.com/assets/9489231/4868946/e79c54b8-6145-11e4-8ffa-70f3bb0bd80e.PNG)

I have an internet connection and a proper Mojang account. I'm completely clueless right now! Please help!

**Comment by peterix** [comment]
Sorry, no idea and you probably either solved the issue yourself or gave up.
