### ISSUE TITLE
Error when trying to run any instance on Ubuntu 14.10 64 bit

### ISSUE THREAD

**Issue by TieMonkey** [MultiMC/MultiMC5#585]
I've been getting this error code (/usr/bin/java: symbol lookup error: /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0: undefined symbol: xcb_get_reply_fds) for the past few days with no luck on finding a fix myself so I figured I'd post it here to see if it's a bug in the program, or just a derp on my end.

paste.ee link for the full log is here:
http://paste.ee/p/ZAYEq

**Comment by olee** [comment]
Downloaded latest version from https://files.multimc.org/downloads/mmc-stable-lin64.tar.gz
Still getting this error directly at launch and cannot use MultiMC at all.

**Comment by peterix** [comment]
What error?

Also, make a new issue for it.
