### ISSUE TITLE
Enabling multi-mod checkbox select/deselect

### ISSUE THREAD

**Issue by Painstouch** [MultiMC/MultiMC5#589]
What bothers me when troubleshooting any mod without a specific error, is when I have to do a process of elimination of the mods installed in the MMC instance. And for that, I have to click each and every single little tiny itsy bitsy checkbox (at least half of them at the time) and start the instance, click again on each and every little tiny box (now for the quarter of them) and do troubleshooting in this rather painful way.

Is it possible to implement multi-mod selection/deselection?

Greatly appreciated!

**Comment by peterix** [comment]
Moved to workflowy.

**Comment by peterix** [comment]
Done.
