### ISSUE TITLE
IllegalStateException with Inventory Tweaks

### ISSUE THREAD

**Issue by tonythegardener** [MultiMC/MultiMC5#590]
Crash when adding Inventory tweaks mod in MultiMMC. Same Jar file works when using without MMC.
Removing this mod allows minecraft to load with all other mods installed.

Using MultiMMC 0.4, Minecraft 1.7.10
Logs attached

**Comment by peterix** [comment]
OH.

The issue was that you added mods into the minecraft jar (jar mods) instead of the mods folder (loader mods).

Sorry.

**Comment by tonythegardener** [comment]
Yep, created a new instance and put all the mods in the loader mods section instead of the jar mods section and was able to get it to work.
Thanks.
