### ISSUE TITLE
updating in quick mod mode is buggy?

### ISSUE THREAD

**Issue by Jiraiyah** [MultiMC/MultiMC5#596]
Hi
I tried to set the updating mode to quick mod, here is the problems when the update available window comes up:
1- If i choose to update now, the progress bar goes forward and then jumps backward, and for 14 files, it gets over 30-40 minutes and even then it is not finished yet !
2- If i choose to update after closing the multi mc, the files download right then ok, but when i restart multi mc, it says that there are updates to download !
also, no matter what i try , i can't find the quick mod option on editing the instance, not sure it's because i can't update the program correctly or what?

**Comment by peterix** [comment]
Quickmods will be replaced by something different. This is no longer relevant.
