### ISSUE TITLE
Add ability to run server instance

### ISSUE THREAD

**Issue by azmrv** [MultiMC/MultiMC5#60]
Ability to run server instance, an easy way to start your local minecraft server with mods and config from your single player instance, for fun with friends in local network.

**Comment by loordgek** [comment]
this is a cool idea i would use it for server dev/testing and w/ https://github.com/MultiMC/WonkoTheSane/issues/8 that would be very cool

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Server support)](https://workflowy.com/s/2EyDMcp7CU)

**Comment by jnm2** [comment]
I would love to have the ability to manage Minecraft servers and have them start non-interactively (running as local service without a user logging in) and viewing the console output realtime from an interactive session. Tall order, I'm sure!

**Comment by DPxKnightxZero** [comment]
Could you add this for server testing? It doesn't even have to be fancy I just like the file and java manager system.

**Comment by seylerius** [comment]
I'm going to chime in support of this, too. Some form of assisted server generation from MultiMC would be awesome. I use MultiMC to build up my own modpacks, and would greatly appreciate assistance in turning them into server-capable, fully-specced modpacks.

**Comment by finalsliver** [comment]
If this is going forward @peterix your thoughts on a file blacklist for servers? some mods still crash servers as SP only while other catch themselves and sit idly on servers doing nothing. 

Further a popup on server launch to confirm the Eula is probably a good idea. can't automate it sadly.

Also opens further avenues to add server monitoring features and a possible custom UI. but that would be a long way off.

**Comment by P3rf3ctXZer0** [comment]
@finalsliver If you are looking for a dev who already attempted such a feature state I believe at one point team COFH did. Also e_elix also. The issue is some mod devs to tick the proper syntax flags that tell minecraft (this is client) - (this is server) - (This is universal) how would you make sure you don't falsely flag something causing Multimc to blacklist valid mods?

**Comment by peterix** [comment]
Something like `.packignore` currently, where you can toggle things between client/server/both. Maybe pre-populated when the info is known? Maybe with heuristics?

The recen activity here is mostly just me reorganizing the github issues. If someone wants to pick up running local servers, I'll be glad and will give them as much support in getting up to speed with the dev stuff as I possibly can.

**Comment by P3rf3ctXZer0** [comment]
That would work. This would prevent any further acts of modpack creators accidently placing mods in server or client when working on large scale modpacks - I have given myself a large number of headaches in this fashion.

**Comment by Sorbe** [comment]
Now on year four of this request

**Comment by P3rf3ctXZer0** [comment]
@Sorbe it seems like this would be a priority feature with this level of thought XD (Sorry I know @peterix and the MultiMc team are re-working feature list table. I know @peterix has started sorting features @Sorbe just give him till like September plus its not like they are ignoring us and there is a lot of under the hood fixes. I still forsee MultiMc being the defacto launcher in the future either way.

**Comment by finalsliver** [comment]
Shelved long term, or dead dead?

**Comment by PhoneixS** [comment]
What about a simple local server?

Without ssh or other things, it should just be able to download de server.jar to a new folder and launch it. To add mods, a simple link to the folder and the user should download them manually. And for the integration of libraries like Forge and Fabric could be a link to the installer and let the user do the job or download de installer and launch it to let the installer guide the user.

I think is enough useful for friends who want to play in a local network (maybe Internet if they know how to open a port in the router) and maybe try different versions with different mods. However, not enough for a professional server. Just for users with enough knowledge to do it by themselves but a little easy to manage and in one place than having many folders, shortcuts, and bookmarks to the downloads.

**Comment by Merith-TK** [comment]
I agree with what Pheonix says, i currently am in an predictament where I am basically forced to run a server because the mod I am assisting in development, will NOT run using `./gradlew runServer`, 

This would also allow for testing a modpack without needing server hardware or extra setup
