### ISSUE TITLE
Bundle a sensible java runtime where possible

### ISSUE THREAD

**Issue by icsmouse** [MultiMC/MultiMC5#608]
I have a really hard time finding where to download the best Minecraft compatible Java for the game. Is it possible to add this in as an option or tab where we can just click on "Java Version Checker," for example, to see if we have the best Minecraft compatible java available on our system?

You have this cool "kitty" tab, I'm thinking something along those lines. a tab or icon that you click & it  checks that your java is correct & if it is out of date that it takes & downloads what you need, after notifying you that you need it , of course. 

I know this may seem like an obvious "everyone knows where to find this stuff" kind of thing. Seriously & honestly, I  have a hard time finding that kind of information.

What do you say, are you willing to add that kind of thing? I know some of use less techy people would really like it a lot. 
Thanks for your time.

**Comment by peterix** [comment]
Ok. All that is missing here is a bit of UI niceness.
Tell people they have bad java if it's `version <= 1.6.0` and make them install/select a good version.
Do not show `version <= 1.6.0` in the version list - it's not valid anymore - java 6 is very dead and the only remaining people with that seem to be on OSX.

**Comment by peterix** [comment]
The best possible java right now is 1.8.0_25. I am considering distributing this version along with MultiMC.

Too many people are having issues with other java versions.

If it weren't for the failure that is intel graphics drivers on windows 10, it would be latest java 8.

**Comment by peterix** [comment]
Ok. I linked this to the relevant item(s) on workflowy:
https://workflowy.com/s/2EyDMcp7CU

**Comment by peterix** [comment]
OK. We will absolutely have to distribute java with MultiMC. The next version is not compatilbe with current modded Minecraft and if people get forced by Oracle to 'upgrade', it will cause a lot of problems.

**Comment by robertefry** [comment]
It may not be the best idea to force-bundle a Java runtime environment. If a user already has a sensible jre installed, the binary should just use that, otherwise you're wasting resources.
Perhaps perform a scan for a compatible jre on installation, and/or include a button to install a jre within the MultiMC install directory.
