### ISSUE TITLE
I have an internet connection and a proper Mojang account. I'm completely clueless right now! Please help!

### ISSUE THREAD

**Issue by JerryWindhorn** [MultiMC/MultiMC5#609]
![multimc issue](https://cloud.githubusercontent.com/assets/9489231/5054643/76cacb3a-6c25-11e4-9edf-81481c632934.PNG)

I have an internet connection and a proper Mojang account. I'm completely clueless right now! Please help! (And yes I know this is a repost)

**Comment by peterix** [comment]
I'm going to guess: it's a generic 'blocked internet access' problem.

I can't help you if your network blocks access to minecraft servers.
