### ISSUE TITLE
eror updating instance

### ISSUE THREAD

**Issue by Mysterynin** [MultiMC/MultiMC5#620]
i keep getting this error message and dont know what to do.

org.multimc.jarmod.fb8b6a81-b35a-47c1-bd7a-e5f68cbd5534 has the same order as org.multimc.jarmod.f4320ea9-b99f-48ae-b7cc-1793420c4c58

**Comment by peterix** [comment]
Implicit defined order for patch files is deprecated and removed in current unstable.
