### ISSUE TITLE
Support for minecraft chat formatting in log

### ISSUE THREAD

**Issue by DheerajSurujprasad** [MultiMC/MultiMC5#622]
So in the Minecraft console in the current chat log sections. the logs are being messed up b'c from what i know it can't recognize the colour codes correctly and is placing "§" followed by the colour code number instead. Here is a picture of how it looks like to me http://prntscr.com/576wka
It was never like that before i updated the client to Version 0.4.4. which makes it very hard for me to understand who the player is and what they are somewhat saying,

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Minecraft chat processing)](https://workflowy.com/s/2EyDMcp7CU)
