### ISSUE TITLE
Ability to install Forge Mod Loader

### ISSUE THREAD

**Issue by DrZed** [MultiMC/MultiMC5#629]
So far you only allow installing Forge Package not exclusively Forge Mod Loader
http://files.minecraftforge.net/fml/1.8
this is Forge Mod Loader alone could you please add support I wanna play modded 1.8 seamlessly instead of annoyances with manual modding this isn't beta minecraft.

**Comment by peterix** [comment]
Moved to workflowy.

**Comment by DrZed** [comment]
:D

**Comment by DrZed** [comment]
Thank you Peter :D

**Comment by peterix** [comment]
Well, this just means it's on a different kind of list. Here: https://workflowy.com/s/2EyDMcp7CU

**Comment by DrZed** [comment]
Mai Gawd you have a lot on your plate...
Wish I could help, but I'm inept in C, C++,C#,etc...
