### ISSUE TITLE
Minecraft exited with exitcode 255

### ISSUE THREAD

**Issue by EthanCoy** [MultiMC/MultiMC5#630]
I have been trying to get this mod pack to work, but I am just not having any luck in the matter. If anyone could help me figure this out, it would be greatly appreciated. 
Below is the log. Sorry for the lengthy one.

http://paste.ee/p/JfOO6

**Comment by peterix** [comment]
Sadly, the log page is now dead.

I hope you've been able to reolve the issue yourself.

**Comment by chxngeling** [comment]
https://pastebin.com/LEeyraWh
I've been getting the same issue, so I thought that I should jump in and try and help.

**Comment by QuImUfu** [comment]
@chxngeling AFAIK your error is completely unrelated.  
Upgrade Forge to the newest available version. If the issue persists report to https://github.com/asiekierka/FoamFix/issues . See:  
https://bugs.mojang.com/browse/MCL-7376?focusedCommentId=387018&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-387018

**Comment by SpudHIHI** [comment]
Im having the same issue 2 years later java and forge are updated, its a pack downloaded from technic and I don't need all that "uh just download technic then" bullcrap cause I have other issues with that. 
heres the log: [https://pastebin.com/yRb3QbRj](url)

**Comment by phit** [comment]
@SpudHIHI dont necro ancient issues please, your log has nothing to do with this, you need java 8 for future support please make a new issue or better visit our discord https://discord.gg/multimc

**Comment by SpudHIHI** [comment]
ok then could you help me figure out why in the world forge makes multimc not work. like if I don't have forge Minecraft loads with the only issue being no mods but if I install forge I get the "Process exited with code 255." error

**Comment by QuImUfu** [comment]
@SpudHIHI because Forge did not work with Java versions > 8 in Minecraft 1.8.9. Just install Java 8 from https://adoptium.net/ or similar.
