### ISSUE TITLE
Show MC chat in a separate view, do not censor it

### ISSUE THREAD

**Issue by SoniEx2** [MultiMC/MultiMC5#634]
Idk who had the stupid idea of replacing <PROFILE NAME> but I hate it and wish I could disable it.

**Comment by Kilobyte22** [comment]
This issue will likely be solved together with #829

**Comment by peterix** [comment]
This has several parts as far as I'm concerned:
* Logs should not include server chat
* Logs should not include IP addresses or host names of servers connected to
* If chat is filtered away, it should be redirected to a different page/view
* Chat should be properly colored and formatted - use the Minecraft formatting tags

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Minecraft chat processing and Ideas -> Logging)](https://workflowy.com/s/2EyDMcp7CU)

Some of this actually gets the #security and #terrible tags...

**Comment by SoniEx2** [comment]
Do we get to log chat separately tho?

I have huge memory holes, being able to log chat would be awesome. Reminds me of client-side logging of IRC. It's nice <3

**Comment by peterix** [comment]
I think that was the original idea, so, yes.

**Comment by SoniEx2** [comment]
"I have huge memory holes" :)
