### ISSUE TITLE
Request: Old Config Files to install Modpack from Common Mod folder

### ISSUE THREAD

**Issue by PiggyWhiskey** [MultiMC/MultiMC5#636]
Reason: On an Update to a Modpack (which can be quite frequently) it results in my manually crawling through the mods to find which ones are different and using a different program to consolidate them (I use WinMerge to copy the files, and remove the other ones)

Alternatively, an option to download from the common launchers (AT, FTB, Technic) to facilitate updates.

As it stands I have several instances of Direwolf20 (FTB Launcher) for playing on different Servers which update at different times.

**Comment by peterix** [comment]
Related to #916 and wonko - will be solved by those, although in a slightly different way.

**Comment by peterix** [comment]
Reading the original request:

This is basically just modpack platform support. To that I'll say: Absolutely. And it has nothing to do with wonko or quickmods.

[This is already on workflowy (Ideas -> Packs)](https://workflowy.com/s/2EyDMcp7CU)
