### ISSUE TITLE
Fullscreen problem with retina display

### ISSUE THREAD

**Issue by Gr33nSn0w** [MultiMC/MultiMC5#637]
Hello,

First off, I have been testing this launcher for a couple a days now and it is amazing !
But i noticed a problem.
I have a minecraf in 1.7.10 and it works perfectly in fullscreen
and an other in 1.8 that doesn't work. it zooms in the left hand side corner
Retina macbook users had already reported this problem and i think it is why we find 2.9.2 version of lwjgl on vanilla minecraft which by the way works in fullscreen.

I am not a programmer so i wouldn't be able to tell but i think the problem comes from there 

thank you very much for your hard work .

**Comment by peterix** [comment]
No idea what happened here. I assume the problem actually got fixed somehow. The pastebins timed out.
