### ISSUE TITLE
Linux version opens multiple instances of console window and .jar window

### ISSUE THREAD

**Issue by syi666** [MultiMC/MultiMC5#642]
I noticed the other day that multiMC was sometimes producing multiple instances of the various minecraft related things in my side bar. at this moment I have 3 console windows, 1 terminal, thankfully, and 1 .jar. it's not uncommon for there to be more .jar windows and I was just curious if this wound be what's been bogging me down lately.

multiMC5 version 0.4.5 x64 running ubuntu 14.04

**Comment by peterix** [comment]
I don't think I can actually help you there without any further input. If the game is getting stuck when it should close, it's a problem with the game.
