### ISSUE TITLE
Improve scaling on high DPI displays

### ISSUE THREAD

**Issue by ChrisLane** [MultiMC/MultiMC5#647]
![image](https://cloud.githubusercontent.com/assets/925091/5274950/672624c2-7a94-11e4-9c5f-af7e15897449.png)

I have a 3200x1800 display on my laptop and MultiMC now looks rather small. Since it is a 13" display I have scaling turned on to 200% in Windows so that I can actually see things but MultiMC icons etc. still seem rather small.

Some other issues appear such as the "Play" arrow overlapping the text however I'm not sure that's related.

**Comment by peterix** [comment]
Update here: current Qt (5.4.1) has some initial support for DPI scaling on Windows!

You need to set the `QT_DEVICE_PIXEL_RATIO` environment variable to `auto` to test that.

Ideally in current develop or unstable branches, because those have new Qt versions.

**Comment by peterix** [comment]
See: http://doc.qt.io/qt-5/highdpi.html

**Comment by ChrisLane** [comment]
I just tested setting the program argument -platform windows:QT_DEVICE_PIXEL_RATIO=auto and it didn't seem to have any effect on the scaling of the MultiMC window.

I might try a few more of the options listed on the page you linked.

**Comment by peterix** [comment]
Really, this is a Qt issue.

**Comment by grennis** [comment]
I noticed this issue was closed as well as the other one, (but isnt fixed), so to repost my comment on the other issue: I added the command line parameter -platform windows:dpiawareness=0 and that fixed the scaling. MultiMC looks great on high DPI display.

**Comment by PaintNinja** [comment]
If you are having scaling issues with Win32 apps on Windows, you can override the scaling method by right clicking the exe, choosing properties and going to the compatibility tab. Some apps (such as Discord) work best when you allow Windows to give full scaling control to the "Application", whilst others work best with "System" or "System (Enhanced)" where you override the application's scaling control (with the Enhanced mode being more aggressive with trying to force system scaling over application scaling).

Personally I have no issue with MultiMC's scaling on Windows 10 Creators Update out of the box, without needing any CLI arguments or needing to use the scaling override feature in Windows.

![mmc](https://user-images.githubusercontent.com/3158390/28117801-bf974da0-6706-11e7-8bc3-c570ec06791b.PNG)
