### ISSUE TITLE
MMC opening again after Minecraft closes..

### ISSUE THREAD

**Issue by Eisys** [MultiMC/MultiMC5#650]
I looked all over the settings and here on the wiki for a solution but couldn't find it.. Is there a way to stop this? It's annoying that MMC opens again after I close Minecraft. Why does it do it in the first place? Could you implement a setting to stop this? Or am I missing something...

Thanks!

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Add an option to close MultiMC entirely on launch)](https://workflowy.com/s/2EyDMcp7CU)

**Comment by peterix** [comment]
WAI
