### ISSUE TITLE
Instances Save Anywhere

### ISSUE THREAD

**Issue by RegisDeVallis** [MultiMC/MultiMC5#661]
What if you could make it so instances could save anywhere on your computer, like google drive for backups of your main instance. Or like junk instances wherever you want. This feature would have to make instances portable and include the jar file in the instance, unlike now. Possible a way to 'install' instances to multimc by running a file in the instance folder. 

Great for sharing modpacks with worlds with friends, or like a lets play download of your world and modpack from youtube type thing. 

In the far future, you could make quickmods a part of the instance to save space. Or worlds download like mods in quickmods.

**Comment by peterix** [comment]
I'm sorry, not interested in implementing this.
