### ISSUE TITLE
Global servers.dat

### ISSUE THREAD

**Issue by BoureySR85** [MultiMC/MultiMC5#681]
Is there anyway you could implement a setting in MultiMC where we could select a Global servers.dat file so we don't have to copy the file manually into each new Instance? Also, maybe have MultiMC check the file for changes and sync them throughout each instance, or maybe an option to have each instance as a standalone or synced servers.dat file. This would be so very much helpful as I keep having to copy the file. And some less MC savvy people might be actually copying the servers manually....

Edit- Or maybe have an option where we can select a server.dat dependency, where we can select which instance the server.dat is copied from.

Thank you so very much for any input on this.

**Comment by peterix** [comment]
Added as an idea to workflowy:
https://workflowy.com/s/2EyDMcp7CU

It goes along with similar ideas of resource sharing between instances.
