### ISSUE TITLE
Instance doesn't launch after installing forge

### ISSUE THREAD

**Issue by needler4** [MultiMC/MultiMC5#682]
I wanted to make a decoration based modpack. I installed forge on a 1.7.2 using the applications own "Install Forge" button. When I launch instance multimc doesn't respond.

The console launches and displays some black and some red text, but it closes and scrolls throught too fast to copy or read.

(MultiMC5 on Windows 7)

**Comment by ElementTimes682** [comment]
I don't know anything about 1.7.2 on Java 8, But it ran fine for me.

**Comment by peterix** [comment]
Well, 1.7.2 + latest forge + java 8 + legacy java fixer = works.

If it doesn't you did it wrong.
legacyjavafixer belongs in the mods folder.
