### ISSUE TITLE
Java Setup Issues

### ISSUE THREAD

**Issue by xenephos** [MultiMC/MultiMC5#684]
I've been getting this error whenever I try to start up an instance.

MultiMC version: 0.4.5

Minecraft folder is:
C:/Users/Danielle/Desktop/MultiMC/instances/TestAgain/minecraft

Java path is:
C:/Program Files (x86)/Java/jre7/bin/javaw.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2048m, -Xmx2048m, -Duser.language=en, -jar, C:/Users/Danielle/Desktop/MultiMC/jars/NewLaunch.jar]

The java binary "C:/Program Files (x86)/Java/jre7/bin/javaw.exe" couldn't be found. You may have to set up java if Minecraft fails to launch.
Could not launch minecraft!

Can anybody tell me what is going on here? I have the newest version of Java (8, Update 25) and MultiMC (0.4.5)

**Comment by peterix** [comment]
I assume this was resolved.
