### ISSUE TITLE
When trying to Login on lancher get this error

### ISSUE THREAD

**Issue by LoOnyBin25** [MultiMC/MultiMC5#685]
Authentication operation failed due to a network error: Unable to init SSL Context: (99) 

Using Windows 7 64 - Bit

**Comment by peterix** [comment]
Usually, these problems got resolved by:
* Restarting various network boxes
* Fixing firewall settings
* Not using a network that filters traffic (schools, etc.)
* installing this: http://www.microsoft.com/en-us/download/details.aspx?id=29
