### ISSUE TITLE
Optifine 1.8.1

### ISSUE THREAD

**Issue by ElementTimes682** [MultiMC/MultiMC5#686]
I need this Optifine in 1.8.1 and I can't join in 1.8 on Mineplex since it has problem with 1.8.0 I guess, and I need it for Vanilla 1.8.1 somehow if any of you know how to do it, Since Optifine uses a jar installer. 

It can be used with Forge but Forge is "NOT" updated to 1.8.1. :/

**Comment by peterix** [comment]
Add it as a jar mod. Last I checked, the same jar file is a jar mod, a forge core mod, a tweaker mod AND an installer.

Just add optifine as a jar mod.

**Comment by ElementTimes682** [comment]
Does even peterix even understand.. The jar file is a jar installer. You are maybe talking about something else in 1.6

**Comment by peterix** [comment]
Nope.

**Comment by dmodoomsirius** [comment]
@ElementTimes682 It works fine as all 4 so just add it. Many mods come as an installer as well as the mod itself. all it does it copy its self to the right directory.

**Comment by alpharulesirulee** [comment]
btw it says Kicked whilst connecting to hub:
