### ISSUE TITLE
mega ram usage? 

### ISSUE THREAD

**Issue by odenthefish** [MultiMC/MultiMC5#694]
it seems that multimc gets corrupted by disabling mobius core in an instance folder causing my ram usage to skyrocket before disabling mobius core i sat at about 70% ram usage after disabling mobius core i get 97% ram usage standard 
it only happens upon disabling mobius core and its fixed by downloading a completely new multimc and installing it 
i have reinstalled it once before and it made it work and it only happens in game but i don't have as much ram allowed to the game as it is using AND changing ram allowed to the game makes no difference  
im sure im doing something wrong but there is no difference in the log (i read it every time i start my game) 

also my CPU usage has come up from  07% to 65%

**Comment by peterix** [comment]
Unless this is memory used by MultiMC, it's entirely unrelated to MultiMC.
