### ISSUE TITLE
Unable to launch FTB instance

### ISSUE THREAD

**Issue by megamanzteam** [MultiMC/MultiMC5#695]
I made a copy of the Direwolf20 1.7 modpack version 1.0.2. I can run it fine in the FTB launcher, just not in multimc. Here is my log: http://paste.ee/p/bBVH1 This has been happening with past instances that were copied as well. I had an old copy of Monster 1.1.0 that used to run fine in multimc, but no longer works.

I have tried force installing forge and removing the 1.7.10 folder, but have had no luck. If you require any additional information, just ask, I will be happy to provide anything I can.

**Comment by peterix** [comment]
I'm very sorry about not responding to this for so long.

Is it still a problem with current develop version?

**Comment by peterix** [comment]
Reopen if it is.
