### ISSUE TITLE
Starting MultiMC from UNC paths on Windows breaks forge

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#698]
If the UNC path maps to a local path, it should be fixed on mmc start.

**Comment by deuceman2008** [comment]
Have you found a way to fix this? An exact guide would REALLY help.

**Comment by robotbrain** [comment]
the fix would have to be in code.
To ensure it works make sure none of the folders in the path are shared
so if C:/Users/Bob/Games/MultiMC, make sure C:/ C:/Users C:/Users/Bob C:/Users/Bob/Games and C:/Users/Bob/Games/MultiMC are not shared

**Comment by peterix** [comment]
Well, the actual fix is to remap the UNC paths back to local paths while MultiMC starts.

As a workaround, you could try to make a shortcut to MultiMC.exe and set its work directory to the local directory? I haven't tried that, but it could work.

**Comment by deuceman2008** [comment]
I have checked. The directory in which I've stored MultiMC is not shared. Although, I don't have it in the games folder. Perhaps it will only work that way?

**Comment by robotbrain** [comment]
that was just an example path

**Comment by peterix** [comment]
Ok. I'll just say one thing: DON'T DO IT. PLEASE. Java can't deal with those paths.

I do not intend to work on this.
