### ISSUE TITLE
Weird window shifting in MC 1.5.2 and prior

### ISSUE THREAD

**Issue by Parker8283** [MultiMC/MultiMC5#699]
![2014-12-29_0156](https://cloud.githubusercontent.com/assets/5672271/5566670/1aa5ab26-8efe-11e4-99bd-b93be2e1c4cd.png)

Cuts off the bottom of the screen and has weird gray-ish bar across the top. Exists in all versions of MC 1.5.2 and prior. 1.6.0+ is fine.

**Comment by Parker8283** [comment]
Also, didn't see your second question in your first comment. Mac 10.7.5 Lion.

**Comment by peterix** [comment]
I'm simply going to assume this disappeared at some point, because this has been inactive for almost 4 years.
