### ISSUE TITLE
Error Launching my own modpack (Mac)

### ISSUE THREAD

**Issue by SoulsEater214** [MultiMC/MultiMC5#702]
So I wanted to make my own modpack, so I watched Bacon_Donut 'How to make your own modpack' but he only has 2 episodes so I just tried to do it myself. So I got some mods in my Test pack and whenever I launch it, it launches for 2 secs and than crashes. Here is the log http://paste.ee/p/XMMRl

I hope someone will help me,
SoulsEater214

(Sorry for my English still learning it)

**Comment by SoulsEater214** [comment]
Well thats the problem I am using the latest version 1.7.10R3.0.0B9 but it says I need at least version 1.7.10R3.0.0B7

**Comment by Heufneutje** [comment]
I see no problem here. B9 is newer than B7, so you already have at least B7.

**Comment by SoulsEater214** [comment]
Well it seemed like redstone arsenal was the problem I just deleted it for now

**Comment by peterix** [comment]
Alright.
