### ISSUE TITLE
Patreon list is not updating

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#705]
http://files.multimc.org/patrons.txt contains outdated or possibly wrong information.

**Comment by peterix** [comment]
Greenphlem has been asking about why he isn't on the credits list in mmc.

@Forkk do you plan on fixing this?

**Comment by peterix** [comment]
It's currently not running/updating.

**Comment by robotbrain** [comment]
Didnt this get fixed? Or did it break again?

**Comment by peterix** [comment]
Well, the server it was running on is dead.
