### ISSUE TITLE
Network error cant download

### ISSUE THREAD

**Issue by GamingMortal** [MultiMC/MultiMC5#706]
I am unable to download MultiMC as their seems to be a Network error on your end.

**Comment by Loetkolben** [comment]
I can download MMC without a problem. You're trying to download from multimc.org, right?
Also, could you give us a description of the error (something like _404 Not found_ or _403 Forbidden_, a connection time out)? If you can't reach the server, make sure you don't have a firewall or anti-virtus that blocks acces to multimc.org.

**Comment by GamingMortal** [comment]
its OK, I was finally able to download it after a kind soul sent me a copy of the software.

**Comment by dmodoomsirius** [comment]
That doesn't help others if they have the problem nor if you try to update it.
