### ISSUE TITLE
Minecraft crashing before opening up with MultiMC

### ISSUE THREAD

**Issue by dickey51** [MultiMC/MultiMC5#709]
Having problems with minecraft opening after I updated to Java 8. Crash report is https://paste.ee/p/5L7bC

**Comment by dmodoomsirius** [comment]
forge 964 is not java 8 compatible so lex made http://files.minecraftforge.net/LegacyJavaFixer/legacyjavafixer-1.0.jar install this and it will work.

**Comment by dickey51** [comment]
do i just add it in as a jar mod or do i have to replace the forge file with it?

**Comment by dmodoomsirius** [comment]
put that in the mods folder
