### ISSUE TITLE
Optifine 1.8 problem/issue

### ISSUE THREAD

**Issue by MahiricaNNo** [MultiMC/MultiMC5#714]
Hello , i have some problems with my optifine , when i have OP installed in my mc and i run and play in my survival world the mobs are not spawning correctly , but when i remove OP form "mods" folder and run again my survival world it's normal , the problem is that with OP mob despawning have limited block maybe 64 i guess , by the way i run 1.8 MC Version , i think you can understand this XD , it's a big problem form me , i can't play MC cuz off the low fps without OP , with OP it absolutely amazing . Thanks for the reading i hope you can fix it P.S i tried all of the 1.8 OP versions and it's the same .

**Comment by peterix** [comment]
I honestly don't see how I could fix it. The author of OP could.
