### ISSUE TITLE
Option to alter the JVM launch command line (Not launch switches)

### ISSUE THREAD

**Issue by Cluckyx** [MultiMC/MultiMC5#715]
Not JVM switches, but in certain instances sometimes something needs to be run other than just java.

Use Case: 

Standard Java launch is "> Java -jar FILE_PATH -Xms foo -Xmn bar"

Linux users using Bumblebee for their second graphics card need to activate their card by launching via "> optirun Java -jar FILE_PATH -Xms foo -Xmn bar" 

There is currently no percieved way to do this.

**Comment by Chreutz** [comment]
It can be rather easily done with a small script, though. With java in /usr/bin/java and primusrun, it works flawlessly like this:

    #!/bin/sh  
    primusrun /usr/bin/java "$@"

Set that as your java path in MultiMC and you're golden.

Cheers!

**Comment by peterix** [comment]
Implemented this as a feature in latest develop. Will be in 0.4.7
