### ISSUE TITLE
NEI crashing minecraft while using MultiMc

### ISSUE THREAD

**Issue by punkchic4Christ** [MultiMC/MultiMC5#716]
Hello...  No idea what I'm doing here but by clicking on a bazilion websites I have found that if I post a crash log someone may be able to help me....  Forgive me if I'm in the wrong area for this...  I'm trying to use MultiMC v5 and everything has worked when I open minecraft until I get to NEI.  It is the only mod that I can't get to work.  I have also put the CCC in.  All versions from what I see are the 1.7.2.  My JAVA is the newest I can get.  I just can't figure out what is causing the crash....mainly because I have no idea what I'm doing.  Any help will be greatly appreciated!  
My log is here: http://pastebin.com/qUCr4g7f

Here is a screenshot of my loader mods section:

![untitled](https://cloud.githubusercontent.com/assets/10444252/5657623/5ecdaa7e-96bf-11e4-841d-e3e348749fa4.png)

**Comment by justastranger** [comment]
You're using a dev build of NEI

**Comment by peterix** [comment]
Indeed. On the download page, you want the 'universal' file, not the 'dev' file.
