### ISSUE TITLE
Pre-existing FTB world crashes

### ISSUE THREAD

**Issue by Nereikx** [MultiMC/MultiMC5#717]
I am using Windows 8.1 64-Bit and I went to play Direwolf 20 1.7.10 pack. When I tried to launch my world it took a while then it crashed

**Comment by 02JanDal** [comment]
Please upload the full log using the Upload Log button.

**Comment by Nereikx** [comment]
Im sorry, I cant find that button

**Comment by 02JanDal** [comment]
When the game has crashed you should see a dialog with a lot of (partly colored) text; the log. There are some buttons, amongst them one for Uploading. If you don't see this dialog, or it disappears, go into the settings and ensure the setting for closing the console dialog when the game exits is disabled.

**Comment by Nereikx** [comment]
Oh right, thanks

**Comment by Nereikx** [comment]
http://paste.ee/p/Krl2k

**Comment by Nereikx** [comment]
It became unresponsive so I had to close it so it might not help

**Comment by robotbrain** [comment]
its out of memory. increase the max memory in settings

**Comment by Nereikx** [comment]
Ok, Thanks
