### ISSUE TITLE
Add logins / API keys to paste.ee to allow larger uploads

### ISSUE THREAD

**Issue by Keridos** [MultiMC/MultiMC5#719]
This was uploaded by MultiMC: https://paste.ee/p/J3JYl
This is the complete log I manually uploaded: https://paste.ee/p/E0JpH
Using MultiMC version: 0.4.5-dev409

**Comment by peterix** [comment]
``Unregistered users have a paste size limit of 2 MB. Register a free account and get this limit bumped up to 12 MB!''

Now, the uploaded size is about 835 KB, so nowhere near the 2MB limit.

**Comment by peterix** [comment]
The '&' character is the first that is not part of the upload.

**Comment by peterix** [comment]
Alright. New build is done and should behave better. The limit should still be 2MB though. That can't be changed without using a different site or implementing accounts/login for paste.ee

**Comment by Keridos** [comment]
Adding in Account Linking could be a nice solution, but I honestly have no clue how much work implementing that would be.

**Comment by peterix** [comment]
The paste.ee API is badly documented and doesn't include how to do logins at all. I assume something could be hacked/reverse engineered.

**Comment by Keridos** [comment]
I could ask them on IRC if they could document how to do logins with the API.

**Comment by peterix** [comment]
Alright. Looks like it should be really easy to use.

I'll add it soon-ish.

**Comment by peterix** [comment]
Actually, let me reclassify this as a feature. It also needs a multiauth.

**Comment by peterix** [comment]
OK. this is simple:

- [ ] Register an account for MultiMC and generate an API key.
- [ ] Use API key in MultiMC by default.
- [ ] Let user override the API key with a custom one.
