### ISSUE TITLE
Constant Redownloading of Assets

### ISSUE THREAD

**Issue by shadowzfire** [MultiMC/MultiMC5#721]
This does not occur on my desktop, it occurs on my laptop, it occurs on some of my friends computers too. Currently I do not have access to an error log. The issue has MultiMC constantly re-downloading assets. Several reports I have seen have been filed on this issue, so far it stills exists. A error log very similar to the ones of my friends machines is this one: http://paste.ee/p/HuCLn

**Comment by peterix** [comment]
Alright. A new devel build is available, where downloading in general was improved.

Instead of starting all the downloads at the same time, they are queued and processed, with 6 active at most per task.

Please see if that helps.

**Comment by peterix** [comment]
And one more build. It will take a while to complete :)

**Comment by shadowzfire** [comment]
I'll check it out, thanks for trying

**Comment by peterix** [comment]
Assuming it worked :)
