### ISSUE TITLE
Invalid heap size

### ISSUE THREAD

**Issue by Loganu98** [MultiMC/MultiMC5#726]
Well, I just switched over from windows 8, to windows 7 and now multi MC doesn't work, it gives me this weird error.
http://pastebin.com/1XFMMJP5

**Comment by 02JanDal** [comment]
Check to make sure that you're using a 64bit java, 32bit java doesn't allow using that much memory.

**Comment by peterix** [comment]
Well, looks like you also downgraded your java to a 32bit version.

**Comment by Loganu98** [comment]
My system is 64 bit, When I went to java I downloaded the recommended, could somebody please link me a system 32? I couldn't find it last night.

**Comment by Loganu98** [comment]
Wait, how do I check my java version? I'm pretty sure it's 64 bit.

**Comment by peterix** [comment]
http://download.oracle.com/otn-pub/java/jdk/7u71-b14/jre-7u71-windows-x64.exe

**Comment by Loganu98** [comment]
Thank you so much Peterix, it worked! :)
