### ISSUE TITLE
MultiMC don't lauch

### ISSUE THREAD

**Issue by TheNicolasM9** [MultiMC/MultiMC5#727]
When i click on play, it loads, and after 5 seconds, i don't havethe loading screen of minecraft (for example Minecraft 1.6.4) MultiMc come back to the instances sreen

Help me please !

**Comment by Heufneutje** [comment]
Please upload your MultiMC-0.log file from your MultiMC folder to a pastebin and post the link here.

**Comment by peterix** [comment]
Disable closing the console window on exit:
![broken1](https://cloud.githubusercontent.com/assets/203326/5738797/d01e5f44-9bf0-11e4-8aba-0f03a951bd6c.png)

You should be able to find out why is the game exiting.

**Comment by peterix** [comment]
Maybe we should just treat fast exits as crashes.

**Comment by TheNicolasM9** [comment]
I reinstalled it, i lost everything but now it's good
Thanks, guy, i will ask you if i have an other problem
