### ISSUE TITLE
Issue making my own modpack

### ISSUE THREAD

**Issue by SoulsEater214** [MultiMC/MultiMC5#730]
So I tried making my own modpack again, but I again didn't succeed. I don't really know what the problem is but I hope you guys know it and can help me.

Here is the log: http://paste.ee/p/OXIV5

Hope to hear from you guys soon.
-SoulsEater214

**Comment by peterix** [comment]
'net.minecraft.client.renderer.texture.ITickable.tick()V' looks like a decompiled name.

You are using the dev version of CoFHCore. Replace it
