### ISSUE TITLE
Minecraft crashes when loading own modpack

### ISSUE THREAD

**Issue by SoulsEater214** [MultiMC/MultiMC5#731]
So I tried to run my own modpack, but it keeps on crashing. In the log it says 'attempting connection with missing mods ....... all my mods. Don't know if that is the problem.

Here is the log: http://paste.ee/p/At1oq

Hope someone can help me.
-SoulsEater214

**Comment by 02JanDal** [comment]
Xeno's Reliquery 1.1.2 is for Minecraft 1.6.4, this is 1.7.10.

**Comment by peterix** [comment]
You may have a few other similar problems. Just go through your mods and make sure they are actually for the version of Minecraft you are using.
