### ISSUE TITLE
Launcher windows don't show title on Gnome Shell

### ISSUE THREAD

**Issue by GiantSox** [MultiMC/MultiMC5#732]
With most applications, the application name is shown in my top bar like this:
![image](https://cloud.githubusercontent.com/assets/6282089/5789712/b9a7296c-9e2a-11e4-8db8-da1fc38b87ef.png)
However with MultiMC it shows this: 
![image](https://cloud.githubusercontent.com/assets/6282089/5789717/f5d6ba6a-9e2a-11e4-8f09-4d9b40670d64.png)
This makes it more difficult to give MultiMC an icon from my icon pack. Can this please be fixed?

**Comment by 02JanDal** [comment]
What distro/DE are you using?

**Comment by GiantSox** [comment]
Ubuntu 14.04 with GNOME Shell.

**Comment by 02JanDal** [comment]
Seems to be a Qt bug: https://bugreports.qt.io/browse/QTBUG-22274

I guess the easiest solution would be finally creating a .desktop file :(

**Comment by GiantSox** [comment]
That's what I'm trying to do, I'd just prefer not to have to name it ".desktop". TeamSpeak also uses Qt and displays its name without any issues.

**Comment by 02JanDal** [comment]
It's not about naming the executable .desktop, but having a [.desktop](http://standards.freedesktop.org/desktop-entry-spec/latest/) file.

**Comment by peterix** [comment]
I don't see why a .desktop file should ever be a requirement, for anything.

**Comment by peterix** [comment]
Tested on latest Fedora with Gnome shell, it's not there anymore.
