### ISSUE TITLE
Can't allocate more memory

### ISSUE THREAD

**Issue by surfpikachu** [MultiMC/MultiMC5#734]
I can't allocate more ram to pixelmon. I want to allocate more ram so that I constantly freeze.
Please help me! Thank you.
I have a windows 8.1 gaming pc by IBuyPower.
I have a total of 4 gb ram
![untitled2](https://cloud.githubusercontent.com/assets/10577565/5790469/6d45e060-9e5f-11e4-8c88-c28efc80abc2.png)
![untitled3](https://cloud.githubusercontent.com/assets/10577565/5790468/6d41b9f4-9e5f-11e4-946f-c883af251814.png)
![untitled](https://cloud.githubusercontent.com/assets/10577565/5790467/6d3e735c-9e5f-11e4-84af-5dc93331e59f.png)

**Comment by peterix** [comment]
You need to navigate into the dialog window described here:
http://www.computerhope.com/issues/ch000549.htm

and delete the __JAVA_OPTIONS variable.

**Comment by peterix** [comment]
This should also be fixed in the dev versions... I'll check.

**Comment by peterix** [comment]
Right. A new develop build with the change is available. If you switch to develop and update, this should no longer be a problem.

**Comment by peterix** [comment]
Closing, because the issue should be gone. If you disagree, reopen.
