### ISSUE TITLE
Use minecraft profile name in offline mode

### ISSUE THREAD

**Issue by filip3712** [MultiMC/MultiMC5#735]
Please add options save nick in offline mode. 

Thanks :)

**Comment by peterix** [comment]
So, it would basically keep around the last used offline nick (one or more) and instead of showing you the main nick, it would show the last used one(s), so you don't have to type it all the time?

**Comment by filip3712** [comment]
No, show every time my minecraft.net nick no last used(sorry for my english)

Użytkownik Petr Mrázek <notifications@github.com> napisał:

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Use minecraft profile name in offline mode)](https://workflowy.com/s/2EyDMcp7CU)
