### ISSUE TITLE
Minecraft crashes when loading world

### ISSUE THREAD

**Issue by SoulsEater214** [MultiMC/MultiMC5#737]
First of all I want to thank you guys for helping me creating my own modpack, I got a lot further with it. At least Minecraft starts now, but now whenever I try to create a world it crashes and I have to open the world again. Then I get into the world, but  than when I try to move Minecraft crashes.

Here is the log: http://paste.ee/p/XblDm

I hope to hear from someone soon
-SoulsEater214

ps, Sorry for my English.

**Comment by 02JanDal** [comment]
Seems to be an issue with Waila, ensure that it, and all mods that depend on it, have correct versions.

**Comment by SoulsEater214** [comment]
Okay thanks, I will look at that.

**Comment by peterix** [comment]
The other error happens when journeymap looks for a part of the standard java Integer implementation and can't find it.

Try upgrading your java to 7 or 8.
