### ISSUE TITLE
screen shot Imgur delete hash doesnt work

### ISSUE THREAD

**Issue by Wferr** [MultiMC/MultiMC5#741]
If you try to delete a screen shot that you uploaded and how it pastes out the hash if you goto imgur.com/delete/[hash it gave you] it does not exist.

**Comment by peterix** [comment]
Yeah. Screenshots need some parts redone. This is actually supposed to be used together with the imgur API

**Comment by peterix** [comment]
Well, we don't show these anymore.

**Comment by rapus95** [comment]
@peterix well then, how can I delete an accidentally uploaded image? I uploaded 3 images and want to the delete the first one. That means, the link isn't in my clipboard anymore.
