### ISSUE TITLE
I am getting the following error report when trying to launch Direwolf20's latest modpack:

### ISSUE THREAD

**Issue by Pieguys** [MultiMC/MultiMC5#742]
http://i.imgur.com/HO2xt5a.png

I have the modpack installed and can launch it directly through the FTB launcher. I am new to MultiMC so I am sorry if I am being oblivious or I messed something up.

**Comment by peterix** [comment]
You are using 32bit java, which can't use more than ~1500MB of RAM.

In the MultiMC java settings, click the auto-detect button and pick 64bit java.

**Comment by Pieguys** [comment]
Ok, thanks. I thought I had updated my Java since I got my computer but I guess I am mistaken. Thanks for the quick response.

**Comment by peterix** [comment]
It's not really about the updating.

Thing is, if you go to the java site, it will give you 32bit java, because most web browsers are still 32bit, and it wants to install itself as a browser plugin.

**Comment by Pieguys** [comment]
Ok, but you know what I meant ;) It seems to be working now, thanks again.

**Comment by peterix** [comment]
Alright :)
