### ISSUE TITLE
Add option to disable permgen in launch for Java 8 users

### ISSUE THREAD

**Issue by finalsliver** [MultiMC/MultiMC5#743]
As some users have moved onto Java 8 and the wonders of MetaSpace old PermGen input while safe through messages into the console and logs. 

By adding an option to manually disable PermGen we can avoid a few extra people typing in about it as well as make everything a bit tidier

**Comment by peterix** [comment]
If you do not set permgen and leave the default 64 in, it is not propagated to java.
Eventually, java 7 will die. It will take care of itself.

**Comment by peterix** [comment]
... http://www.oracle.com/technetwork/java/eol-135779.html

In about 3 months.

**Comment by finalsliver** [comment]
Thanks for the clarification Peterix!

**Comment by 02JanDal** [comment]
Duplicate of #690, and related to #139 and #167.
