### ISSUE TITLE
Backup Save option

### ISSUE THREAD

**Issue by Shaithlis** [MultiMC/MultiMC5#745]
I wasn't sure if you monitored your MCF page, so it was suggested that I come here and post.  If this is the wrong place, then I apologize.  But, the request that I would like to recommend is maybe, if possible, adding in a "Backup Save" option like the ATLauncher has for each of its instances. Other that that little request, I don't seem to have any other issues, and truly enjoy using your program.

**Comment by 02JanDal** [comment]
Related to #661.

This has long been under consideration, but still requires quite some work.

If you're on Linux or OS X you can create a symlink between the instance folder and some folder that gets automatically backed up, for example Dropbox. You could also use Pre/Post commands to automatically backup the instance using an external program.

**Comment by peterix** [comment]
In the current version, you can drag the worlds out of the worlds tab in edit instance.

Anyway, the relevant information from here has been added to workflowy: (Ideas -> World management)
https://workflowy.com/s/2EyDMcp7CU
