### ISSUE TITLE
Title bar out of desktop in Lubunu linux

### ISSUE THREAD

**Issue by QuImUfu** [MultiMC/MultiMC5#748]
When i start MultiMC or MultiMC starts the console window these windows get placed to high so i can't see the Title bar. If i shift these windows down, everything works just fine, until i restart (they get placed to high again). it just annoys needing Alt-space shift this window again and again.
Edit: the window seems to get shifted up just one title bar with every restart.

**Comment by QuImUfu** [comment]
fixed sometime between version 0.4.7 and 0.4.11 (maybe Qt update?)

**Comment by peterix** [comment]
Maybe also fixed in LXDE... because that's what likely caused it in the first place.

**Comment by QuImUfu** [comment]
no, after downgrade to 0.4.7 it is bugged again. ^^
maybe you should close #879 too.

**Comment by peterix** [comment]
OK
