### ISSUE TITLE
java memory issue

### ISSUE THREAD

**Issue by dickey51** [MultiMC/MultiMC5#750]
my minecraft keeps crashing here is the link to the log from multimc 

http://paste.ee/p/1kPgh

**Comment by dickey51** [comment]
before this first log i also had this error log as well 

http://paste.ee/p/cx8Sq

**Comment by DreadWingKnight** [comment]
32-bit or 64-bit java?

**Comment by peterix** [comment]
clearly, 32bit. and not enough memory given to the instance for it to start.

Get 64bit java. Set it up in MultiMC - in java settings, click auto-detect and select one that isn't 'java'.

**Comment by dickey51** [comment]
Where do I get 64bit Java?

**Comment by DreadWingKnight** [comment]
http://java.com/en/download/manual.jsp
