### ISSUE TITLE
Allow customizing console colors

### ISSUE THREAD

**Issue by CaptainYarb** [MultiMC/MultiMC5#751]
An option for a darker console and smaller text would be an amazing feature for MultiMC. When comparing it's console to a more standard system it just doesn't fit in: https://cloudup.com/c1iJ1ExyBos

In regards to the font size, it can be a pain to look for mod errors and the such on startup when the text is so large :)

**Comment by peterix** [comment]
The font settings are there already, but color settings can be added for sure.

**Comment by peterix** [comment]
Moved to workflowy (Ideas -> Logging):
https://workflowy.com/s/2EyDMcp7CU
