### ISSUE TITLE
I am getting the following error when trying to open my custom 1.7.10 modpack.

### ISSUE THREAD

**Issue by Pieguys** [MultiMC/MultiMC5#754]
http://paste.ee/p/2XTLH

It was working before but Java kept trying to update to Java 8 and when I did it wouldn't work so I uninstalled Java 8 and re-installed Java 1.7.0_75 64 bit. If Java is no longer the issue and it is something I'm missing while reading through the report then I'm sorry for being oblivious.

**Comment by dmodoomsirius** [comment]
Does this happen on the vanilla launcher or any other launcher?

**Comment by Pieguys** [comment]
No, Vanilla Minecraft 1.7.10 works fine.

**Comment by Pieguys** [comment]
I'm not sure it will help but my pack contains the following mods (And Forge/LiteLoader):

Another One Bites The Dust 2
Applied Energistics 2
Aquaculture
Archimedes' Ships
ArmorStatusHUD
Aroma1997 COre
Aroma1997's Dimensional World
Artifice
Atum
Baubles
Better Sugar Cane
Better Title Screen
BetterChests
BiblioCraft
BiblioWoods: Biomes O' Plenty
Big Reactors
Biomes O' Plenty
Blood Magic: Alchemical Wizardy
Botania
bspkrsCore
Carpenter's Blocks
Chicken Chunks
Chisel 2
Code Chicken Core
CoFH Core
CoFHLib
ComputerCraft
CustomNPCs
Dense Ores
Ender IO
EnderStorage
Extra Utilities
Extra TiC
Fluxed Trinkets
Forestry
Funky Locomotion
Gravestones
Iron Chest
Iron Chest Minecarts
JABBA
Keithy Utils
Magic Bees
Magical Crops
Mantle
Metallurgy 4
Metallurgy Core
MineFactory Reloaded
Mystcraft
Natura
NEI Addons
NEI Integration
Nether Ores
Not Enough Items
OpenBlocks
OpenEye
OpenMods
Pandora's Box
ProjectE
Railcraft
Redstone Arsenal
Reliquary
Roguelike Dungeons
Simply Jetpacks
Solar Expansion
StatusEffectsHUD
Thaumcraft
The Twlight Forest
Thermal Expansion
Thermal Foundation
TiC Tool Tips
Tinkers' Construct
Tinkers' Mechworks
Vein Miner
Waila

**Comment by peterix** [comment]
Mechworks{33.c001660} [Tinkers' Mechworks] (TMechworks_mc1.6.4_0.1.6.jar) Unloaded

That is clearly for 1.6.4. You are using 1.7.10

**Comment by Pieguys** [comment]
Well, oops. I am obviously a noob at modding and didn't notice that.

**Comment by peterix** [comment]
Well, it's a thing to look for :)
