### ISSUE TITLE
Crash opon launching modded instance.

### ISSUE THREAD

**Issue by tonyism** [MultiMC/MultiMC5#755]
Worked fine before I left for work, returned home and attempted to play. Didn't get very far. :p

http://pastebin.com/4QtVqWDA

**Comment by Heufneutje** [comment]
> Failed to extract native library:
java.util.zip.ZipException: invalid block type

Looks to me like your Minecraft files got corrupted or whatnot. Does it work if you make MultiMC redownload Minecraft? (Go into your instance settings, change version back to Vanilla 1.7.10 and reinstall Forge/Liteloader)

**Comment by peterix** [comment]
Here are a few possibilities:
* The instance is still running, and the files that would be overwritten are still in use.
* the twitch jar files got corrupted. Find them in the libraries folder and delete them. MultiMC will download them again.

**Comment by tonyism** [comment]
Thank you I will try that and get back to you.

**Comment by tonyism** [comment]
I did set up a bukkit server, could that have messed with my files? I attempted to revert back to unmodded 1.7.10 and re-install forge and liteloader. It now throws a different error. when you say delete the old twitch jar files... which ones? Can I just delete the whole libraries/tv/twitch folder?

**Comment by tonyism** [comment]
Deleted twitch folder, problem solved. Thanks.

**Comment by robotbrain** [comment]
yes
