### ISSUE TITLE
1.8.1 viewdistance stuck at 16?

### ISSUE THREAD

**Issue by zastin17** [MultiMC/MultiMC5#757]
When using multi mc the view distance only goes to 16 for some reason in the vanilla launcher it goes to 32

**Comment by DreadWingKnight** [comment]
Java version  (including 32 vs 64 bit)?

**Comment by zastin17** [comment]
I have 64bit installed. I have a 64bit machine so that's fine. I uninstalled java just to make sure. still does not work. And again it only does this on multimc not the official launcher. Is this a bug? someone test this out.

**Comment by DreadWingKnight** [comment]
Make sure that multimc's settings are set to use the 64-bit java.

**Comment by zastin17** [comment]
it sais its using the 64bit version when I click test. This is where java is installed. C:/Users/Zboy/Desktop/runtime/jre-x64/1.8.0_25/bin/java.exe

**Comment by DreadWingKnight** [comment]
64-bit java 8 (1.8.31 installed to program files) here.
Works fine.

Memory allocation settings are set to what?

**Comment by zastin17** [comment]
Ok this is weird so I copied the jvm Arguments from the official launcher and copied to the multimc launcher and I get 32 view distance. But I constintly get a argument warning. this is the arguments I used. -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M

**Comment by zastin17** [comment]
I have uninstalled java entirely and installed it to the default location it installs to without luck.

**Comment by DreadWingKnight** [comment]
You didn't answer my question.

I've got 1GB and 6GB for mine. What do you have for yours?
