### ISSUE TITLE
Failed to read the assets index

### ISSUE THREAD

**Issue by Quincie** [MultiMC/MultiMC5#759]
HI there, I've installed Multi MC and done everything correctly thus far to launch the game but it keeps coming up with 'failed to read the assets index'. I have no idea what that means and any help would be much appreciated! 

Thanks

**Comment by Heufneutje** [comment]
Please hit the Upload button in your log window and post the link here.

**Comment by Quincie** [comment]
Hi there, 
Thanks for getting back to me so quickly but I seem to have fixed it. Have no idea what was wrong but its working now! One last question though is is there a way to get your worlds from regular mine craft and import them over to Multi mc?
ThanksMark
Date: Thu, 29 Jan 2015 23:56:00 -0800

**Comment by robotbrain** [comment]
copy the saves folder from .minecraft into the MultiMC instance minecraft
folder

**Comment by peterix** [comment]
Oh. I actually replied to your e-mail. Nevermind :)
