### ISSUE TITLE
Mod Un-Installing

### ISSUE THREAD

**Issue by ArkhamNightmare** [MultiMC/MultiMC5#760]
Whenever I try to uninstall a mod in an 1.7.10 instance the mod always comes back when I reopen MultiMC. I save everything, remove the mod or old versions of mods from the config file but they always come back.

**Comment by 02JanDal** [comment]
Which mod?

I assume you either delete it using the _Remove_ button in the Loader/Core Mods page, or by deleting it from the mods/ folder manually?

**Comment by robotbrain** [comment]
"from the config file" what does that mean?

**Comment by ArkhamNightmare** [comment]
To answer your question it's any mod or intance( I forgot to mention) and I use the Remove button. BTW thanks for replying.

**Comment by 02JanDal** [comment]
Hmm... Try removing a mod, then put MultiMC-0.log on pastebin or similar and post the link here

**Comment by peterix** [comment]
No idea what this is about. Closing.
