### ISSUE TITLE
Instances with Forge stopped working

### ISSUE THREAD

**Issue by Gamerocker77** [MultiMC/MultiMC5#763]
We have a lot of Minecraft instances with mods, and they all have Forge installed using MultiMC5 on my son's iMac.  They have been working great for several months.  Yesterday, they all stopped working.  We can still play Minecraft starting from MultiMC5, but the instances with Forge exit before they open.  I tried creating a new instance including Forge with no mod, and it also crashed before it opened.  What is causing this, and how do I fix it?

**Comment by DreadWingKnight** [comment]
Java 8? 1.6.4 and older instances?

If so there's a compatibility fix you need to install.

**Comment by peterix** [comment]
A java update can do this.

Anyway, upload and post the link to the game log first:
![log](https://cloud.githubusercontent.com/assets/203326/5988571/59e47cae-a966-11e4-81ce-b50ab484d99f.png)

If you don't get the console window, it can be enabled in the settings:
![log1](https://cloud.githubusercontent.com/assets/203326/5988576/98d215ac-a966-11e4-9f81-b9035af8ee7c.png)

**Comment by Gamerocker77** [comment]
Here is the log from a test I just did using Minecraft 1.7.2 and Forge and no mods.
MultiMC version: 0.4.5

Minecraft folder is:
/Applications/MultiMC/MultiMC.app/Contents/MacOS/instances/testing forge 3 1.7.2/minecraft

Java path is:
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: testing forge 3 1.7.2", -Xms512m, -Xmx1024m, -Duser.language=en, -jar, /Applications/MultiMC/MultiMC.app/Contents/MacOS/jars/NewLaunch.jar]

Using onesix launcher.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/instances/testing forge 3 1.7.2/natives

Traits:
  []

Libraries:
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/minecraftforge/forge/1.7.2-10.12.2.1161-mc172/forge-1.7.2-10.12.2.1161-mc172-universal.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/minecraft/launchwrapper/1.9/launchwrapper-1.9.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm-all/4.1/asm-all-4.1.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-library/2.10.2/scala-library-2.10.2.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-compiler/2.10.2/scala-compiler-2.10.2.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/google/guava/guava/15.0/guava-15.0.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/mojang/authlib/1.3/authlib-1.3.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/versions/1.7.2/1.7.2.jar

Params:
  [--username, <PROFILE NAME>, --version, 1.7.2, --gameDir, /Applications/MultiMC/MultiMC.app/Contents/MacOS/instances/testing forge 3 1.7.2/minecraft, --assetsDir, /Applications/MultiMC/MultiMC.app/Contents/MacOS/assets/virtual/legacy, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]

Window size: 854 x 480

Preparing native libraries...
Extracting jinput-platform-2.0.5-natives-osx.jar
Extracting lwjgl-platform-2.9.1-natives-osx.jar

[10:03:52] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[10:03:52] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[10:03:52] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[10:03:52] [main/INFO] [FML]: Forge Mod Loader version 7.2.217.1161 for Minecraft 1.7.2 loading
[10:03:52] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_31, running on Mac OS X:x86_64:10.10.2, installed at /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
[10:03:52] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[10:03:52] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[10:03:52] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[10:03:52] [main/ERROR] [LaunchWrapper]: Unable to launch
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_31]
	at java.util.ArrayList$Itr.remove(ArrayList.java:865) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:117) [launchwrapper-1.9.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Minecraft exited with exitcode 0.

**Comment by peterix** [comment]
You will have to add this mod to 1.6.4 and 1.7.2 instances:
http://files.minecraftforge.net/LegacyJavaFixer/legacyjavafixer-1.0.jar

**Comment by Gamerocker77** [comment]
I tried adding that jar mod to 1.7.2, and it still quit before starting Minecraft... Maybe I did not load the jar mod correctly?

MultiMC version: 0.4.5

Minecraft folder is:
/Applications/MultiMC/MultiMC.app/Contents/MacOS/instances/testing forge 3 1.7.2/minecraft

Java path is:
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -Xdock:icon=icon.png, -Xdock:name="MultiMC: testing forge 3 1.7.2", -Xms512m, -Xmx1024m, -Duser.language=en, -jar, /Applications/MultiMC/MultiMC.app/Contents/MacOS/jars/NewLaunch.jar]

Using onesix launcher.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/instances/testing forge 3 1.7.2/natives

Traits:
  []

Libraries:
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/minecraftforge/forge/1.7.2-10.12.2.1161-mc172/forge-1.7.2-10.12.2.1161-mc172-universal.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/minecraft/launchwrapper/1.9/launchwrapper-1.9.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm-all/4.1/asm-all-4.1.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-library/2.10.2/scala-library-2.10.2.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-compiler/2.10.2/scala-compiler-2.10.2.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/google/guava/guava/15.0/guava-15.0.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/mojang/authlib/1.3/authlib-1.3.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/instances/testing forge 3 1.7.2/jarmods/b68c3cfd-38cd-474c-ae31-362a9f68cf14.jar
  /Applications/MultiMC/MultiMC.app/Contents/MacOS/versions/1.7.2/1.7.2-stripped.jar

Params:
  [--username, <PROFILE NAME>, --version, 1.7.2, --gameDir, /Applications/MultiMC/MultiMC.app/Contents/MacOS/instances/testing forge 3 1.7.2/minecraft, --assetsDir, /Applications/MultiMC/MultiMC.app/Contents/MacOS/assets/virtual/legacy, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]

Window size: 854 x 480

Preparing native libraries...
Extracting jinput-platform-2.0.5-natives-osx.jar
Extracting lwjgl-platform-2.9.1-natives-osx.jar

[10:21:39] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[10:21:39] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[10:21:39] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[10:21:39] [main/INFO] [FML]: Forge Mod Loader version 7.2.217.1161 for Minecraft 1.7.2 loading
[10:21:39] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_31, running on Mac OS X:x86_64:10.10.2, installed at /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
[10:21:39] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[10:21:39] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[10:21:39] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[10:21:39] [main/ERROR] [LaunchWrapper]: Unable to launch
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_31]
	at java.util.ArrayList$Itr.remove(ArrayList.java:865) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:117) [launchwrapper-1.9.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Minecraft exited with exitcode 0.

**Comment by peterix** [comment]
Yes. It belongs in the mods folder, not the minecraft jar.

**Comment by Gamerocker77** [comment]
Oh, thank you.  I had added it as a jar mod, because it had the word "jar".  For 1.6.4 should I put it in the mods folder or the coremods folder?  (Forge is in the coremods folder.)

**Comment by peterix** [comment]
Forge is loaded by different means and shouldn't be in any folder anymore.

Since 1.6.4, the forge core mods are now loaded from the normal 'mods' folder. The 'coremods' folder should be gone. All mods should go into the 'mods' folder, unless it's something really weird.

**Comment by Gamerocker77** [comment]
I opened the instance folder, open the mods folder, and drag the "legacyjavafixer-1.0.jar" into the mods folder.  Are those the correct steps?

**Comment by robotbrain** [comment]
yes. make sure you delete the jarmods and use the install forge button

**Comment by peterix** [comment]
Yes. It is the same as if you dragged the file to the 'loader mode' page in the instance edit dialog.

**Comment by Gamerocker77** [comment]
Thank you so much for your help and patience with my ignorance!  You are a genius, peterix!

**Comment by peterix** [comment]
Alright :)

Having to add that mod is a bit of an inconvenience (you have to know you need it), so I'll see what can be done about including it automatically.

**Comment by AYDIN18** [comment]
![Снимок](https://user-images.githubusercontent.com/50381499/57329647-48c35400-7125-11e9-8cfd-8200c7aeecf8.PNG)

**Comment by Heufneutje** [comment]
Necroposting a 4 year old issue with an unrelated screenshot is not the right way to report an issue.
