### ISSUE TITLE
Assets never are downloaded

### ISSUE THREAD

**Issue by shadowrishabh** [MultiMC/MultiMC5#766]
Whenever i try to create an instance or play, everything works fine until the "Getting asset files from Mojang" Screen. The progress bar seems at random points loop back to some previous point and never seems to reach a definite end, and gets stuck in an infinite loop. I cant play minecraft as a result. I have tried everything, redownloading MultiMC, trying it again, creating a new instance, but nothing works.Please help me resolve this issue.

**Comment by peterix** [comment]
Try the develop version. You can switch to that using the MultiMC settings.

**Comment by shadowrishabh** [comment]
No, it didn't work sir. It still keeps looping back.

**Comment by peterix** [comment]
Alright. Can you put the mmc log on pastebin/gist and link it here? It should be named MultiMC.0.log - it gets overwritten with every start, so grab it after it fails.

**Comment by Panag0s** [comment]
I have the same problem you want all to MultiMC.0.log file or the point where i try to launch the instance and it can't download the assets?

**Comment by Heufneutje** [comment]
You can upload the whole thing.

**Comment by Panag0s** [comment]
https://gist.github.com/Panag0s/716b696e782858982d2f

**Comment by peterix** [comment]
try to switch to the devel version (in the multimc options) and updating.

**Comment by Panag0s** [comment]
I did and i had the same problem

**Comment by peterix** [comment]
then I'd say post the log from that, because it's supposed to fix that problem.

**Comment by Panag0s** [comment]
https://gist.github.com/Panag0s/40103d506c3ee03edcda 
with devel version

**Comment by peterix** [comment]
If you read the log, you'll see that it is still the stable version.

The git commit from the log matches that:
https://github.com/MultiMC/MultiMC5/commit/4ae0d8e0af6c0746e6d083829fc4c9a46fa15940

**Comment by Panag0s** [comment]
I changed it on the devel version :S

**Comment by peterix** [comment]
![button](https://cloud.githubusercontent.com/assets/203326/6154691/e8b314a2-b22d-11e4-8303-7a562fb893d7.png)

Click that button. It should show you the changelong and give you an option to actually update. Tell it to update.

**Comment by Panag0s** [comment]
https://gist.github.com/Panag0s/336b8f8c713092151976

**Comment by peterix** [comment]
```
server replied: Request has been forbidden by antivirus" while downloading ...
```
Downloads blocked by antivirus?

You might want to look into that. As someone who doesn't use anything like that, and had no need for it for 10+ years, I have no idea.

**Comment by peterix** [comment]
Anyway, the much smaller number of download failures in the log shows that it's better. Just not good enough to actually work. Your internet access is filtered, either by something you have installed, or by some network element (proxy that blocks files based on contents?).

**Comment by Panag0s** [comment]
I have an internet security... It that a problem?

**Comment by peterix** [comment]
Well, most likely it's blocking things it shouldn't. like perfectly fine sound/music files. That's most of what the minecraft assets are.

So, yes. You may have to whitelist the minecraft.net server in it.

**Comment by Panag0s** [comment]
Well i close the internet security and it's working now :S
