### ISSUE TITLE
My modpack crashes after trying launch

### ISSUE THREAD

**Issue by KakesRevenge** [MultiMC/MultiMC5#769]
Hello 
im trying to make my modpack, but everytime i trying to laucnh it something loads up and then crashes

here is my crash report : http://pastebin.com/tdJ4rNBc 
List Of Mods : http://pastebin.com/ejgJPdUW
Forge : 10.13.2.1300
Version : 1.7.10

Thx for any ideas :)) Btw : im sorry for my bad english im from czech :)

**Comment by QuImUfu** [comment]
Can not reproduce. Try updating all mods. Extracells and AE2 Tech require 2 different versions of  Applied Energistics 2, so it won't work with both of them. Why are you posting this in the multimc Bugtracker? This is clearly a minecraft mod bug, and not a MultiMC bug.
