### ISSUE TITLE
[Request] Forge Download button for Servers

### ISSUE THREAD

**Issue by malice936** [MultiMC/MultiMC5#770]
A useful feature for pack devs like my self would be a button that lets you download a specific version of the forge universal jar.

**Comment by 02JanDal** [comment]
... or at least a download URL. See also #60.

**Comment by kotoroshinoto** [comment]
actually a companion, sister program fork of MultiMC for servers (multi-tab, able to run more than one server at a time etc) would probably make more sense. Unless you'd want to add a server capability directly into the client-managing multimc (which could be annoying given that it hides itself when the client is launched).

**Comment by peterix** [comment]
@robotbrain is working on something like that: https://github.com/robotbrain/apoapsis

I think it's single server though.

Server jar downloads should be easily possible with the metadata repository approach:
https://github.com/02JanDal/WonkoTheSaneFiles/blob/master/net.minecraft/1.7.10.json#L289

It's in the data already.

**Comment by kotoroshinoto** [comment]
it probably wouldn't be that hard to make it tabbed and multi-server capable. Hell I had something much like this concept working with wxwidgets a while back. since it was server stuff I didn't need to do minecraft logins (and I wasn't doing automated versioning and downloads, as it was an alpha version it wasn't feature complete)

**Comment by peterix** [comment]
This is some ruby code running as a web app on the server, managing the server itself and using the metadata repo for installing minecraft/forge/mods.

**Comment by kotoroshinoto** [comment]
I'm planning on trying to write something that operates in a similar vein as byobu & screen for managing minecraft servers, but which is actually just a binary so it can be launched as a service.

haven't decided whether I should code it in java or C or something else, I'm flexible honestly. The idea would be similar to how RCON works, but I could build in better security once the main features are complete, or simply have the user rely on being able to ssh in and use localhost with the command-line client.

Any sort of remote admin feature is always a security risk and piggy-backing on existing remote access security might be safer initially. maybe  once I get the thing to a workable state, someone else could contribute a secure login system XD

**Comment by robotbrain** [comment]
Apoapsis at the current head can run forge servers and supports uploading mod files

**Comment by peterix** [comment]
I think just a 'forge download' is too little. I'd rather have local server support, where you can actually run a server for pack testing and even play (I'd think having two separate processes just work better, if you have the RAM and CPU cores for it).

#60 is relevant here.

Integration with a server side agent that manages servers is also a possibility. I'm kinda planning to treat the client the same way - so the agent(s) + server/client instances can continue running while MultiMC is closed. MultiMc would reconnect to the last seen local agents and probe remote server agents on start.

[Moved to workflowy (Ideas -> Server support and Ideas -> Server/client launch agent)](https://workflowy.com/s/2EyDMcp7CU)

**Comment by peterix** [comment]
Well, no. You can just go to the Forge download page on its server. This is scope creep.
