### ISSUE TITLE
Force Closing Modded with Forge (No Crash Reports)

### ISSUE THREAD

**Issue by VastoPenguin** [MultiMC/MultiMC5#772]
Specs of laptop:
Win7 Home Premium 32-bit SP1
Intel Mobile Core 2 Duo 1.83ghz CPU
3gb DDR2 RAM
"Intel Mobile Intel 965 Express Chipset" Family graphics card

Ever since I updated to the latest version of Java (around that time, may not be from Java could just be coincidental timing) any instances of Minecraft I try to open (generally 1.6.4 or 1.7.2 due to old graphics card in laptop) it will just force close and re-open MultiMC5.

It doesn't generate any crash reports, I went to play Pixelmon and the last crash report it has is from 16/10/14 15:58.

Also, when I want to install Forge, it says there aren't any available versions. I've just been duplicating my instances and renaming and re-modding them each time because Forge won't load in the list to install. My launcher says I have the latest version (0.4.5 at time of this post)

**Comment by dmodoomsirius** [comment]
If you are using java 8 install http://files.minecraftforge.net/LegacyJavaFixer/legacyjavafixer-1.0.jar in your mods folder.

**Comment by VastoPenguin** [comment]
You're a legend! thank you so much!

**Comment by 02JanDal** [comment]
When trying to install Forge, what version of Minecraft are you using for the instance? 1.8? 1.8.1?

Do this please: create a new instance, and try to add a Forge version (at least load the versions list). Then upload the contents of the file MultiMC-0.log to pastebin or similar and post the link here.

**Comment by peterix** [comment]
the way I see it, it's probably the forge version lists being broken/empty and stuck in cache.
If you remove the forge files from your main mods folder (it's right in the multimc folder), it should refresh them.

**Comment by VastoPenguin** [comment]
@02JanDal: I cant run any higher than 1.7.2 due to old graphics card (using a laptop so cant exactly replace this one)

@peterix Yeah that helped thanks :) never thought about doing that before but thank you :)

**Comment by peterix** [comment]
Alright. Everything seems to be fixed. Closing.
