### ISSUE TITLE
Optifine and Liteloader patch json won't work together

### ISSUE THREAD

**Issue by shinji257** [MultiMC/MultiMC5#773]
I'm getting the error "Caused by: joptsimple.MultipleArgumentsForOptionException: Found multiple arguments for option ['width'], but you asked for only one" when I try to run these together and I have no idea why.  It may be very well something I'm doing wrong.  The liteloader is a derivative of the normal one.  It just points to Jenkins instead.  The optifine is pretty much what is on the wiki as well.  Sorta by accident though.

The files themselves work on their own.

Normally I'd just install Forge and Liteloader through the GUI (if available) however Liteloader snapshots are not included yet and I can't use Forge on servers using BungeeCord.  At least not until they get that conflict sorted so I needed to create a separate Non-Forge build that at least included LiteLoader and Optifine.

Help?

Optifine JSON: https://pastebin.com/NXpQdSGp
Liteloader JSON: https://pastebin.com/AqCqCsNd

**Comment by shinji257** [comment]
Crash: https://pastebin.com/pBhcwkPK

On that note I tried with Forge and my json files.  Forge+Liteloader was ok however Forge+Optifine failed.  I know that Forge can load Optifine directly however it was a test and should of worked fine that way too. :(

**Comment by HeroCC** [comment]
A workaround for this is to remove the optifine JSON, and just use forge, and plop the optifine jar in the mods folder.

**Comment by shinji257** [comment]
If you had read my OP post you would see the whole point of this is because on some servers I can't use forge.

Quoted from my OP: "I can't use Forge on servers using BungeeCord"
Unless that's fixed in the Forge side now.  Have not tried lately.

**Comment by peterix** [comment]
Try to add this to the library entries that don't have it:
```
            "insert": "prepend",
```

**Comment by HeroCC** [comment]
I am not sure about the specifics of your forge problem, but I am using forge for 1.8 and I can connect to BungeeCord servers.

**Comment by shinji257** [comment]
Ok.  It's possible the servers updated then.  I know a patch went out to address the issue so I'll recheck my existing profile.  I posted this up before the patch was available.

**Comment by QuImUfu** [comment]
The easiest way would be to load optifine with liteloader. just put the Optifine jar it in the /mods/version folder and liteloader will load OF for you.

**Comment by shinji257** [comment]
I was unaware that Liteloader would auto-load Optifine.  I'll try that.

**Comment by dmodoomsirius** [comment]
btw @shinji257 you can connect using a forge server to a bungee cord server i have done it in 1.8 and 1.7.10.

**Comment by shinji257** [comment]
The issue in the past was that forge had issues connecting to BungeeCord due to an interoperability issue (it threw an error going past the bungeecord proxy) but it seems that issue has been sorted out.  Not sure who applied a fix and when but I noticed now that normal forge builds work fine rather than the patched one I was using for a bit.
