### ISSUE TITLE
Minecraft Modpack not working 1.7.10

### ISSUE THREAD

**Issue by HoFFNetwork** [MultiMC/MultiMC5#775]
Hello fellow minecrafters and coders,
I seem to be having trouble with a mod pack my friends and i have put together. When you open inventory or walk around in the slightest way, it crashes for client and server. We Dont know whats wrong or where to start. i could only think its a mod that isnt cooperative with another. We have turned to the experts for help. If you know the reason its not working please let me know.
- hoff

here is my crash report: http://pastebin.com/LqsVBZ17
here are the mods were using:
![screenshot_20150207212257](https://cloud.githubusercontent.com/assets/8715813/6097642/9ab20886-af7a-11e4-93fe-44ad9ec49907.png)
![screenshot_20150207212339](https://cloud.githubusercontent.com/assets/8715813/6097643/9dbdeb94-af7a-11e4-822e-a301b4aba1d7.png)

**Comment by shadowfacts** [comment]
This is not the place to be posting crash reports for Minecraft unless it has something specifically to do with MultiMC, which it doesn't. You are have a problem with NEI go ask @Chicken-Bones.

**Comment by Heufneutje** [comment]
We're usually pretty willing to help with modding problems. Though in this case, it does seem to be some kind of NEI issue.
