### ISSUE TITLE
Allow selection of themes on first start

### ISSUE THREAD

**Issue by supersammy7000** [MultiMC/MultiMC5#782]
I downloaded the latest version of multi mc and there was a bug with fluffy kitty. it was not selected by default this is one of the worst bugs ive ever seen. please fix this.

**Comment by robotbrain** [comment]
not everyone wants it on by default; afaik the majority of users leave it off

**Comment by peterix** [comment]
The :octocat: :heart: is _**R**_

Silly things aside. It's not enabled by default, but it's just a click away. That really shouldn't be a problem :)

**Comment by peterix** [comment]
You know... let's just do this.

@jadedcat says it's a grumpy kitty, but I disagree :)

**Comment by supersammy7000** [comment]
@peterix i disagree with @jadedcat as well.

**Comment by peterix** [comment]
Right. I feel bad about not doing this when I said I would. And it will still take some time ;)

I'm turning this into something more serious though and instead say that you get to choose the theme on first start. The cat background should be part of that.

Added to workflowy: https://workflowy.com/s/2EyDMcp7CU Ideas -> Theming
