### ISSUE TITLE
CodeChickenCore reportedly not installed - except it is. Help?

### ISSUE THREAD

**Issue by MiningPotatoes** [MultiMC/MultiMC5#783]
I've been trying to build my own personal singleplayer modpack, but recently I keep getting the same issue:
![crash screenshot](https://cloud.githubusercontent.com/assets/11001606/6198421/a4caec8a-b3c5-11e4-9b84-1b026b44bc57.PNG)
Normally, I could fix this by installing CodeChickenCore. The problem here is that I've already installed CodeChickenCore, and I have a feeling it's an issue with MultiMC seeing that it's a clean .jar file from an FTB instance.

Crash report is here: http://pastebin.com/LqsVBZ17
For those interested, here's my mod list:
![mod list pt 1](https://cloud.githubusercontent.com/assets/11001606/6198422/ac2d31ea-b3c5-11e4-872e-27b202ec8078.PNG)
![mod list pt 2](https://cloud.githubusercontent.com/assets/11001606/6198423/b072cf8a-b3c5-11e4-9256-c474caab3967.PNG)
Thanks for your help.

**Comment by robotbrain** [comment]
it looks like you put the nods in the central mods folder, which is seperate from the instances; it's really just a storage spot for when mmc downloads forge and liteloader 
you have to put them in the instance mods folder

**Comment by peterix** [comment]
Indeed.
