### ISSUE TITLE
Windows 7 Can't add account, "Unable to init SSL context" 

### ISSUE THREAD

**Issue by DatCanMan** [MultiMC/MultiMC5#784]
Exactly what it says on the tin. I'm on Windows 7, yet I'm having this issue that supposedly only Windows XP users should have, where I try to add an account and I get an error saying "Authentication operation failed due to a network error: Unable to init SSL Context (99)"

**Comment by Loetkolben** [comment]
Do you have an up-to-date Win7 SP1? As far as I know, M$ messed up thier root certificates (trough I had no problem on my Win7).... To check for updates, go to your control panel (or however "Systemsteuerung" is called in an english Windows) > System and Security > Windows Update.
Please post the MultiMC log, too (put it on GH gist, pastbin, etc.).

**Comment by DatCanMan** [comment]
My apologies, forgot to update this. I fixed it. I have no clue what the issue was, but a simple re-download solved it. Closing.
