### ISSUE TITLE
Various instance crashes

### ISSUE THREAD

**Issue by the-creamster** [MultiMC/MultiMC5#789]
It's been happening for a while now and somewhat at consistent times; basiclly after a period of time that any instance has been running, it'll momenterally freeze, the console won't be a selectable window  followed very shortly by 25+ "Microsoft Visual C++ errors". I can then close it and the instance still runs but with no console.

Another more recent one is when launching any FTB instance through Multimc 5 after some period of time again it'll randomly & unsuspectingly close with a code 1 error. It doesn't point to anything in the instance when it does that.

Any ideas as to why both of the above are occuring?

Thanks, The_Creamster.

**Comment by Heufneutje** [comment]
What happens if you run the instance with the check "Keep updating" in your log window disabled?

**Comment by peterix** [comment]
1. looks like the log gets overfilled and you run out of memory.
2. could be the same.

Try to turn off the log updating (it's in one of the corners of the log page)

**Comment by the-creamster** [comment]
I did that for the Direwolf FTB instance and it hasn't crashed since i've done so. As for the non FTB instance i haven't yet tried that one yet as we no longer use it (went from it to the Direwolf pack). So i'll return back here when i have the result for that instance(need to get pics for our webpage anyway).

**Comment by the-creamster** [comment]
Here you go, got a log for you; http://pastebin.com/Uh1Y7Rf5.

**Comment by peterix** [comment]
Hmm...

Could be memory corruption or some hardware problem?

I'd use memcheck if I were you, just to make sure it's not something like that: 
http://www.memtest86.com/

**Comment by the-creamster** [comment]
The memtest just finished and it came up clean with no errors so what's next on the 'to check list' to try and eliminate this?

**Comment by Loetkolben** [comment]
I'm not really good at reading these chrashlogs, but this stacktrace makes me think it's either a problem with the JRE or your JRE disliking a railcraft class:
> Stack: [0x000000001b010000,0x000000001b110000],  sp=0x000000001b10d840,  free space=1014k
Native frames: (J=compiled Java code, j=interpreted, **Vv=VM code**, C=native code)
V  [jvm.dll+0x4c9f67]
V  [jvm.dll+0x4e84bb]
V  [jvm.dll+0x4c4593]
V  [jvm.dll+0x46dffb]
V  [jvm.dll+0x4dec6b]
(Goes on with V dll's, look at the crashlogs if you want more..)

>Current CompileTask:
C2:10095915 44482       4       **mods.railcraft.common.blocks.aesthetics.lantern.BlockLantern::func_149666_a** (64 bytes)

Try using a diffrent version of Railcraft and / or updating Java if possible.

**Comment by the-creamster** [comment]
When i launch direwolf20 pack with the FTB launcher directly i don't get the instance crashes that have been occurring when launching FTB instances through multimc.

**Comment by robotbrain** [comment]
any news?

**Comment by the-creamster** [comment]
At the moment the server is down, got to get it working again. Will give an update when i can get on server again.

**Comment by the-creamster** [comment]
I have something which may be investigatable. My FTB client modpack version was 1.2.1 of which i thought the server version was so i backdated to 1.1.1 and i haven't crashed yet. But i was crashing with v1.2.1 of the pack so something to do with that update to the pack. Loetkolben did point out that the crash was referencing railcraft.

**Comment by the-creamster** [comment]
The server has been running V1.3.1 for a week now and haven't crashed yet when using FTB launcher. I will try Multimc 5 launcher again to see if it is V1.2.1 of the pack or Multimc 5.

**Comment by peterix** [comment]
Assuming this either got fixed or is no longer relevant.

**Comment by Revvilo** [comment]
The reason for me was that I had a load of commandblock timers, (the ones with the set redstone block and set air commandblocks) that were creating particles which I was using for texturing - EVEN THO I had commandblock output set to false, so just make them toggleable for a temp fix
