### ISSUE TITLE
Modpack will load superflat but not regular worlds

### ISSUE THREAD

**Issue by xBaragoniax** [MultiMC/MultiMC5#793]
Hi! Is there anyone willing to help me figure out this modpack issue? Ive been working on a modpack for a while and it loads superflat worlds just fine, but crashes whenever I try to make any other type of world. It wont let me enter the world after reloading either. 

Crashlog:
http://pastebin.com/KbZX92ci

Any help is appreciated!

**Comment by peterix** [comment]
`java.lang.NoClassDefFoundError: cofh/updater/IUpdatableMod`

Looks like some of your mods got out of sync. Possibly an incompatibility between CoFHCore and MFR.

**Comment by connor44566** [comment]
what modpack are you using?

**Comment by peterix** [comment]
Assuming this got fixed or worked around.
