### ISSUE TITLE
MultiMC crashes after listing available Forge versions on Mac osx64

### ISSUE THREAD

**Issue by keturn** [MultiMC/MultiMC5#794]
I have MultiMC running, version 0.4.5.
I've created an instance with minecraft 1.7.10.
(Started Minecraft. Looks fine. Closed it again.)
In MultiMC I do "Edit Instance" and click the "Install Forge" button
It says "Fetching version lists" with a progress bar. This completes successfully.
It shows a list of forge versions in the window for a moment.
But a moment later — without me touching anything — MultiMC crashes
SIGSEGV with KERN_INVALID_ADDRESS at 0x0

do you receive the problem reports from OS X, or should I attach that information here?

**Comment by peterix** [comment]
Hmm... receive? I guess that could be arranged somehow?

Anyway, please attach it.

**Comment by keturn** [comment]
Copy of this OS X Problem Report at https://gist.github.com/keturn/e13d7ddee2dbb2342fce

**Comment by peterix** [comment]
Removing libqtaccessiblewidgets.dylib fixes the problem.

Maybe this is a Qt bug? Maybe building on a more recent OSX version would help?

**Comment by keturn** [comment]
removing `Contents/MacOS/accessible/libqtaccessiblewidgets.dylib` makes it so it doesn't crash anymore (and subsequent forge installation is successful)

**Comment by refactorized** [comment]
This solved the problem for me, thanks

**Comment by robotbrain** [comment]
closing
