### ISSUE TITLE
Name Change Bug

### ISSUE THREAD

**Issue by TheCyberTronn** [MultiMC/MultiMC5#795]
I just wanted to bring it to your attention, but you are unable to join servers if you've changed your name. To fix this, you need to delete your account entry in MultiMC and recreate it to be able to log into servers.

Keep up the great work, guys!

**Comment by Ilan321** [comment]
Same thing with the vanilla Minecraft launcher, you have to log out and log back in to fix it.

**Comment by robotbrain** [comment]
related to #724

**Comment by peterix** [comment]
Added it to the FAQ: https://github.com/MultiMC/MultiMC5/wiki/FAQ
