### ISSUE TITLE
Fix QuaZIP building on Windows

### ISSUE THREAD

**Issue by 02JanDal** [MultiMC/MultiMC5#798]
The recent changes for how QuaZIP is built (and included) are broken on windows. Fix.

Build log: http://pastebin.com/NqfAM0Mc

**Comment by 02JanDal** [comment]
Also add a FindPatch like this one: https://github.com/desura/Desurium/blob/master/cmake/modules/FindPatch.cmake

**Comment by peterix** [comment]
Fixed by magic.
