### ISSUE TITLE
Minecraft exited with exitcode -1.

### ISSUE THREAD

**Issue by Blackskull62** [MultiMC/MultiMC5#799]
http://paste.ee/p/PF6YK

Please help, making a server for friends but i'm having difficulty having any idea what that means. Thanks!

**Comment by Loetkolben** [comment]
It seems to be a problem with something called "Bloodmoon", as it crashes with a NullPointerException.
Try removing "Bloodmoon" ad see if that helps.

**Comment by peterix** [comment]
```
  C:/Users/Brad/AppData/Local/Temp/Rar$EXa0.141/MultiMC/instances/Server Modpack/jarmods/13bb6f92-6ec7-45dd-b27c-eeeef0f50261.jar
  C:/Users/Brad/AppData/Local/Temp/Rar$EXa0.141/MultiMC/instances/Server Modpack/jarmods/e4eb2c22-fdb4-4f2d-85a9-be95401aa905.jar
  C:/Users/Brad/AppData/Local/Temp/Rar$EXa0.141/MultiMC/instances/Server Modpack/jarmods/1b7b67ed-3b06-4834-889e-b42b7cea576a.jar
  C:/Users/Brad/AppData/Local/Temp/Rar$EXa0.141/MultiMC/instances/Server Modpack/jarmods/54dac080-6279-4057-a5be-8e41ad4e3792.jar
  C:/Users/Brad/AppData/Local/Temp/Rar$EXa0.141/MultiMC/instances/Server Modpack/jarmods/f8e11b39-622f-42a5-856a-1557d408fbca.jar
  C:/Users/Brad/AppData/Local/Temp/Rar$EXa0.141/MultiMC/instances/Server Modpack/jarmods/eb6140de-16c0-4360-907c-43fdf77fe55b.jar
  C:/Users/Brad/AppData/Local/Temp/Rar$EXa0.141/MultiMC/instances/Server Modpack/jarmods/b2e25012-bb1d-463f-9dd2-ce36aab6aff1.jar
  C:/Users/Brad/AppData/Local/Temp/Rar$EXa0.141/MultiMC/instances/Server Modpack/jarmods/e227e449-afa0-4de3-8c8c-b80f0a60b218.jar
  C:/Users/Brad/AppData/Local/Temp/Rar$EXa0.141/MultiMC/instances/Server Modpack/jarmods/85f34b8b-8d70-44ff-bbe9-c567b29e3213.jar
  C:/Users/Brad/AppData/Local/Temp/Rar$EXa0.141/MultiMC/instances/Server Modpack/jarmods/e1f6b628-1965-45aa-92d8-17ca03d6eee7.jar
  C:/Users/Brad/AppData/Local/Temp/Rar$EXa0.141/MultiMC/instances/Server Modpack/jarmods/5eda1cfd-697f-4949-bc50-0c3f7e36c9c5.jar
  C:/Users/Brad/AppData/Local/Temp/Rar$EXa0.141/MultiMC/instances/Server Modpack/jarmods/9d161956-d2f7-4d1b-9e33-47f6f2b0b388.jar
```

You might want to install your mods into the mods folder, not into the minecraft jar.

**Comment by Blackskull62** [comment]
Removing bloodmoon allowed me to join.. Thanks a ton guys for your help! Also is there a tinkers' construct for 1.8 that I could use on my server?

**Comment by Loetkolben** [comment]
According to http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2218638-tinkers-construct there are beta builds avilable. You might want to check the form post.

**Comment by Blackskull62** [comment]
And I was hoping I could give the pack or w.e to my friends, is there a way?

**Comment by Blackskull62** [comment]
Oh never mind, i think i found how to do it. :)

**Comment by peterix** [comment]
The next version will have some simple pack import and export capabilities - roughly equivalent to what FTB and technic were doing in the past.

Basically a way to export instances and import them elsewhere either from a file, or URL.

So yeah, the way to do it now is just share files... because the instance is all files :)

**Comment by Blackskull62** [comment]
My server for some reason has stopped working, when I try to start it by clicking the fml .jar it no longer even opens. It tries to loads but then nothing happens. No start up or crashing just doesn't happen. Help?

**Comment by peterix** [comment]
Sorry. No idea about that...
