### ISSUE TITLE
Use Minecraft's local Java runtime with option to use the system's

### ISSUE THREAD

**Issue by KaizenNeko** [MultiMC/MultiMC5#801]
Since Mojang's new launcher installs a local copy of Java, it would be nice for MultiMC to use it by default. Of course there would be an option allow users to use the Java they have installed on their system if they desire.

**Comment by 02JanDal** [comment]
So adding the Mojang java as a search path. Sure, can be done.

In the meantime, you can manually enter the path of the Java you want to use.

**Comment by peterix** [comment]
Moved to workflowy (Idead -> Java):
https://workflowy.com/s/2EyDMcp7CU
