### ISSUE TITLE
Investigate forge version list consistency problems

### ISSUE THREAD

**Issue by willabusta** [MultiMC/MultiMC5#802]
No matter what version I try multimc says "there are no forge versions currently for minecraft_____" and I have proper web connection.
Also lightloader seems to be fine.

**Comment by Heufneutje** [comment]
To help us locate the problem, please start MultiMC, have it search for Forge on a few versions, then close MultiMC and upload the MultiMC-0.log file from your MultiMC folder to a pastebin.

**Comment by willabusta** [comment]
alright done. heres a pastebin link http://pastebin.com/WepuKwWF

**Comment by peterix** [comment]
inside the multimc folder, there's a mods folder and in there is a 'minecraftforge' folder

delete the jist.json and json files in there and try again

**Comment by willabusta** [comment]
Thank you. That fixed my problem but I'm just wondering how it happened. hmm.

**Comment by peterix** [comment]
MultiMC caches the responses it gets from the server.

In this case, the files are rewritten slowly when they are updated. So if there is a new forge release, you can run into an issue where you download the lists while they aren't complete yet. And it's saved into the cache. And it's stuck there until the next update on the server side, which can be in a few days.

Or it was some other random network error, leading to the same result.

**Comment by LegendaryAdmin** [comment]
I tried this and it did not fix my issue, it reloaded the list.json and json and continues to give me the same error when searching for a version. I also working on 1.8.1

**Comment by peterix** [comment]
Yes, there are no forge versions for 1.8.1. So that is not an error.

**Comment by Spyfiend13** [comment]
How do I get Light Loader for MultiMC 1.8. It's having the same problem.

**Comment by 02JanDal** [comment]
@Spyfiend13 nope, liteloader just hasn't been officially released for 1.8 yet. You can use the devel builds using this file (instructions at the bottom): https://gist.github.com/peterix/d5571257e7d4511a9018

**Comment by Spyfiend13** [comment]
@02JanDal I tried saving it but it keeps saving as a txt instead of a json.

**Comment by peterix** [comment]
well, rename it then

**Comment by Spyfiend13** [comment]
I tried it just changes back to com.mumfrey.liteloader.json.txt

**Comment by Spyfiend13** [comment]
Ok, now it's working I had to make it com.mumfrey.liteloader.json.json then take out the 1st .json.

**Comment by peterix** [comment]
http://www.pcadvisor.co.uk/how-to/software/3341794/how-show-or-hide-file-extensions/

**Comment by Spyfiend13** [comment]
Thanks

**Comment by robotbrain** [comment]
closing
