### ISSUE TITLE
Mineraft Closed With With Exitcode -1

### ISSUE THREAD

**Issue by wolverene71** [MultiMC/MultiMC5#804]
i have no clue what happened but it failed to launch minecraft entirely here is a paste.ee: http://paste.ee/p/RelOS also any suggestions would be greatly appreciated

**Comment by ajloveslily14** [comment]
well 1 your name is Wolverene, 2 multiMC is on your desktop and 3 remove the space after PotatoCraft

**Comment by robotbrain** [comment]
mmc on the desktop is fine

**Comment by wolverene71** [comment]
Alright thanks hopefully this fixes it

**Comment by wolverene71** [comment]
alright so now it crashes with this http://paste.ee/p/HNAj6

**Comment by ajloveslily14** [comment]
I am not the best at reading crash logs -however- it might be a problem with open mods, try updating that, else i have no clue(maybe openeye?)

**Comment by wolverene71** [comment]
Ok will do

**Comment by peterix** [comment]
I assume that fixed it.
