### ISSUE TITLE
exitcode -1

### ISSUE THREAD

**Issue by abused** [MultiMC/MultiMC5#805]
i am working on making a modpack but when i load it up it says Minecraft exited with exitcode -1
please help
the log is located here 
http://paste.ee/p/oWSMb

**Comment by Heufneutje** [comment]
> java.lang.NoClassDefFoundError: thermalfoundation/item/TFItems
at thermalexpansion.util.crafting.FurnaceManager.addDefaultRecipes(FurnaceManager.java:85) ~[FurnaceManager.class:?]

Looks like a version mismatch to me. Make sure your Thermal Foundation and Thermal Expansion are both up to date.

**Comment by abused** [comment]
yes i just did updated them and now i got a different error 
http://paste.ee/p/1Xzaw

**Comment by Heufneutje** [comment]
> [01:10:31] [Client thread/ERROR] [FML]: Caught exception from ProjRed|Compatibility
java.lang.NoClassDefFoundError: thermalexpansion/util/crafting/SmelterManager

Looks like your ProjectRed is outdated as well.

**Comment by abused** [comment]
ok just updated and the pack now works :)
thank you for ur help

**Comment by Heufneutje** [comment]
You're welcome!
