### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by abused** [MultiMC/MultiMC5#806]
i just made a modpack with multimc but when i install it to minecraft it crashes
the crash report is here
http://pastebin.com/EzhztFES

**Comment by 02JanDal** [comment]
Please upload the full log using the upload log button.

**Comment by abused** [comment]
yes the log is here
http://paste.atlauncher.com/view/7b9ae584

**Comment by Kilobyte22** [comment]
Looks like some mods are outdated. Can't easily see which though, as reading crash logs on phone is a pain

**Comment by Heufneutje** [comment]
Seeing as this is the same kind of issue you posted earlier, you might just want to check for updates on most of your mods, because a lot of them seem to be outdated. (also that is not a MultiMC log)

**Comment by abused** [comment]
I will try to update the mods. Also I tried launching this in the atlauncher which is why it isn't a multimc log

**Comment by abused** [comment]
if you dont mind can u post the mods that i need to update

**Comment by Heufneutje** [comment]
All of them, to be sure.
