### ISSUE TITLE
Just installed modpack: Crashes when entering server

### ISSUE THREAD

**Issue by Allthedogs** [MultiMC/MultiMC5#809]
I just recently gotten a modpack for my server, and things are going smooth enough to open out Minecraft with a minor "Not Responding" sort of thing. It doesn't crash until I try to log onto the server itself.

http://paste.ee/p/AmtnK

EDIT: I fixed it. It was a memory issue so I ended up uninstalling my Java 32-bit, and installed a 64-bit version. It looks great now!

**Comment by Loetkolben** [comment]
If you fixed it, just close the issuse please. (You should be able to...) Also, you might want to rename the issuse back to the original name, as it helps others who have the same problem to find a solution.

**Comment by Allthedogs** [comment]
Okay, I'll keep that in mind for next time. Thanks!
