### ISSUE TITLE
Installing jar mod won't work

### ISSUE THREAD

**Issue by abculatter2** [MultiMC/MultiMC5#810]
I'm trying to use MultiMC to make an instance of the latest Better than Wolves version, and I've added the BTW jar with the jarmods interface, but when I start Minecraft it starts as unmodified vanilla.
This is with 1.5.2 version of Minecraft, and MultiMC version 0.4.5.

**Comment by 02JanDal** [comment]
Please use the Upload log button and post the paste.ee link you get here.

**Comment by abculatter2** [comment]
http://paste.ee/p/NIMOT

**Comment by peterix** [comment]
Open the zip file. Read the instructions inside.

You will have to repackage the mod for it to work.

**Comment by abculatter2** [comment]
I already did that. I have a working instance on the vanilla minecraft launcher, which I set up by manually dragging the files in this jar into the minecraft jar.

**Comment by peterix** [comment]
There is no user-modifiable minecraft.jar in MultiMC anymore.

Take the stuff in 'MINECRAFT-JAR' (btwmodtex, net, textures, ...) and zip it. Add that zip as a jar mod in the version tab of the instance.

**Comment by peterix** [comment]
Most jar mods do not have this extra internal structure that would break that. BTW does.

**Comment by abculatter2** [comment]
I meant the launcher from Mojang, not MultiMC.

Also, I know that you meant look into the jar and find MINECRAFT-JAR and zip it. I've already done this, and used the zip I created in this way.

However, despite this, it's still not working.

**Comment by peterix** [comment]
![wrong](https://cloud.githubusercontent.com/assets/203326/6605952/56872df8-c834-11e4-9fd1-90cd7a228815.png)

**Comment by peterix** [comment]
make sure the zip doesn't have any extra folders on top of the actual content...

**Comment by abculatter2** [comment]
Re-did the zipping and it worked. I think it was because I used .jar for the file instead of .zip, thinking that was necessary...

Error between monitor and chair, thanks for the help.

**Comment by peterix** [comment]
No problem...

I tried it, after a long time... and got eaten by jungle spiders :)
