### ISSUE TITLE
Allow users to apply new icon themes without needing to recompile

### ISSUE THREAD

**Issue by Gotolei** [MultiMC/MultiMC5#812]
It creates a not-insignificant barrier for people looking to create themes.
Most people won't bother going to the trouble of setting up the build environment just to test them.

**Comment by 02JanDal** [comment]
Possible option: distributing stuff as zip or rcc

**Comment by peterix** [comment]
Moved to workflowy (Ideas ->? Theming):
https://workflowy.com/s/2EyDMcp7CU

**Comment by peterix** [comment]
A prototype is in current develop version now.

Ask on Discord if you are still interested in any of this..

**Comment by MichaelPriebe** [comment]
[custom.zip](https://github.com/MultiMC/MultiMC5/files/974987/custom.zip)
Here's an example of some of the icons! File tree is like 'MultiMC\iconthemes\custom\scalable\news.svg'
Folder has to be called custom for now, until theme overhaul happens.

**Comment by peterix** [comment]
File tree view, note the address on top :)
![image](https://cloud.githubusercontent.com/assets/203326/25686604/fb4f9c6c-306f-11e7-9dfc-27827cec8024.png)

**Comment by peterix** [comment]
Current ideas about themes:
https://workflowy.com/s/2EyDMcp7CU#/01817a441650
