### ISSUE TITLE
Add mcedit2.exe to mcedit detection

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#813]
In current develop/stable and the separated branch.

**Comment by codewarrior0** [comment]
Please do. Due to causes beyond my control, it won't run if you rename it to "mcedit.exe".

And yes, you can still pass the world folder or the level.dat as a command line arg.

**Comment by peterix** [comment]
Should be in the develop version. Does it work?

The 'unstable' branch doesn't have tools right now, and 'stable' needs some preparations done first.

**Comment by codewarrior0** [comment]
Will give it a try when I get a chance.

Do you happen to have anything like nightly builds I could download, in case I can't get a build running?

**Comment by 02JanDal** [comment]
You can go to settings, Update Channel, and change it to Develop. Then either restart or click the button next to the one for settings (search for new updates).

**Comment by codewarrior0** [comment]
Great! Working perfectly with 0.4.5-dev-436.
