### ISSUE TITLE
Implement 'trash' functionality

### ISSUE THREAD

**Issue by Eisys** [MultiMC/MultiMC5#814]
As the title states.. It said 'failed to download jar' so I deleted my instance not realising it would delete EVERYTHING.. 

PLEASE tell me there is a way to undo this.. I NEED those worlds/screens/RPs back...

And overall, deleting your instance within MultiMC SHOULD NOT delete the actual files.. Or atleast it should say in BIG BOLD RED TEXT that it will do so!

**Comment by Kilobyte22** [comment]
Check if it is in your `instances` directory inside your MultiMC install directory. If its not there you may want to take a look at File Recovery Software. I am pretty sure deleting an instance will also delete the files though.

**Comment by Eisys** [comment]
It wasn't there.. first place I looked, I wouldn't've even come here it was still there..
I had backed up my main world and rescource pack so the loss wasn't TOO bad..
And I was able to recover other things with Recuva, but still lost 30 out of about 100 screenshots which I wanted back the most, but oh well..

I don't know if the devs look at this or not, but if they do, for the love of god, give a bigger warning when deleting instances, or better yet, DO NOT delete the actual files after one simply deletes an instance in the MultiMC window! Perhaps give a second option after deleting the instance, asking whether you want to delete all the files as well!

**Comment by Kilobyte22** [comment]
The devs certainly check this. I'll leave this open as a reminder.

**Comment by robotbrain** [comment]
sorry, its gone :(

**Comment by Heufneutje** [comment]
The reminder that it's an operation that can't be undone is already there, hence why it asks you to confirm that you really do want to delete your instance. Wouldn't hurt to make it stand out a bit more though.

**Comment by 02JanDal** [comment]
Ofc the actual files should be deleted, it would be stupid otherwise.

While the warning does state that the instance will be permanently deleted, I guess it could be more clear that it will also delete it's files (though I personally think that's self explanatory). Maybe even reuse the notifications dialog so that the warning can't just be skipped?

**Comment by Heufneutje** [comment]
:+1:

**Comment by peterix** [comment]
A MultiMC instance IS NOT a mojang launcher profile, and never will be. You can delete everything else, and it's fine. Delete the instance? Yep, gone. It's not an entry in a config file, it's the actual thing.

Generally, this kind of problem is handled by moving the 'things' (mail, files, whatever) into some 'trash' area. This also means you don't need obnoxious warning dialogs.

**Comment by 4rz0** [comment]
But I as a poweruser want things to be deleted when I click "delete", not them being just pushed somewhere else.
Deleting is deleting for some reason.

**Comment by peterix** [comment]
Same here. With the amount of testing instances I go through, I'd rather add a mass delete option with none of those warning dialogs.

**Comment by peterix** [comment]
Possibly use a slider in the options that goes from 'use nag dialog' to 'don't ask'.
Default to the nag dialog on new installs.

**Comment by happy2pester** [comment]
I've run into an unfortunate deletion of my instance and would like to contribute a suggestion here:

Introduce a minimum delay before I can confirm that I want to delete the instance - just a second or so before I could confirm would have prevented the loss of a few days of progress. You could make it configurable, both for if you wanted this option at all, or for how long the delay should be.

**Comment by Heufneutje** [comment]
Yes, I believe the notification dialog Jan mentioned has/had the delay functionality.

**Comment by happy2pester** [comment]
Well, if it does have a delay, it's not functioning properly. Due to an unfortunate combination of keyboard smashing I managed to accidentally delete an instance, and have lost a few days progress because of that.

**Comment by Heufneutje** [comment]
No, not the one that's currently used. MultiMC had a notification popup that was used for QuickMods before that did have a delay.

**Comment by peterix** [comment]
Yeah, it's there and used for notifications. We don't use them much, but the code is in place for all kinds of dialog windows with timeouts.

**Comment by happy2pester** [comment]
Ah, okay, I understand what you were saying now Heuf.

**Comment by peterix** [comment]
So, I just tested it and the 'Yes' button is focused by default when it asks. I'll make it the 'No' button.

The second level is implementing system or our own 'Trash' support.

[Moved to workflowy (Ideas -> Make instances harder to delete accidentally)](https://workflowy.com/s/2EyDMcp7CU)

**Comment by wlhlm** [comment]
Maybe labeling the buttons "Delete instance" and "Cancel" could make it _slightly_ more obvious.

**Comment by peterix** [comment]
Maybe 'Delete instance forever'

**Comment by wlhlm** [comment]
Or this, yes. Reminds me of the "Delete World"-dialog in Minecraft "\<world\> will be lost forever! (A long time!)"

**Comment by peterix** [comment]
Going to implement trash after all. Not the system trash, but something specific to MultiMC.

**Comment by Snuggle** [comment]
I may have accidentally deleted an instance ~30 seconds ago (I'm a donut, I know!) and it's not in my system trash or `_MMC_TEMP`.

I have backups on another drive, but I'd love to see this implemented. :cat:

**Comment by peterix** [comment]
Yeah, it's near the top of the TODO list... relatively on top anyway. I will implement automatically downloading a suitable java runtime before this.

**Comment by Snuggle** [comment]
Okiedokie! Please also make the Java run-time downloading feature 100% optional, if that's not the plan already.

I don't want it to break anything. :joy_cat:

**Comment by peterix** [comment]
Or maybe java will wait. Because deleting instances is right now annoying, and oracle has not broken the universe yet.

**Comment by Dushess** [comment]
Immediately stop using this drive, install recuva on another disk, and maybe your files still readable.

**Comment by Dushess** [comment]
Or during "delete" phase show small window - "delete also saves, configs and screenshots"
