### ISSUE TITLE
Assets file converting from json to xml

### ISSUE THREAD

**Issue by vandench** [MultiMC/MultiMC5#815]
So I have been screwing with MultiMC on a school provided mac and I'm getting an error with the assets file for 1.7.10.  It works with 1.8.3 but when I tried to do anything the assets file changes itself: http://pastebin.com/3JQYnrTM  I have tried to copy the file from the .minecraft vanilla location but it just keeps changing and not running the game.  If I spam the button to play the game it starts to run but there are no sounds.  I can't figure out why the link is invoking an exception with forticlient (the schools system for blocking webpages) since I have gone to the location in my browser and it immediately downloads the file.  Is there any way to have MultiMC not try and change the 1.7.10.json file?

**Comment by robotbrain** [comment]
There is not afaik.

**Comment by peterix** [comment]
I would say you'll have to solve this one yourself.

Me being me, I would break the system. But that might not be a good idea. YMMV
