### ISSUE TITLE
MultiMC won't start/update

### ISSUE THREAD

**Issue by Devil-May-Kare** [MultiMC/MultiMC5#816]
When I try to start MultiMC, it immediately closes, regardless of whether it has the "auto-update" function turned on. If I tell it to start multiple times, occasionally a MultiMC window will pop up for a fraction of a second. However, if I disconnect internet, it starts in offline mode just fine and continues fine, even if I connect internet, until I tell it to update. Then it "has stopped working" and windows checks for a solution to the problem. If I close the "windows is checking for a solution to the problem" window, the program closes. I have tried re-installing MultiMC, and that has no effect.

Thank you for looking at this post. I hope it helps with the program's development in the future.

**Comment by Loetkolben** [comment]
Do you have a *MultiMC-0.log* file in your MMC folder? If yes, please post it on GH gist, pastebin, etc.
This file could help us spot the problem.

**Comment by Devil-May-Kare** [comment]
https://dl.dropboxusercontent.com/u/106586470/MultiMC-0.log
When I looked at it, it didn't seem to have any error messages, but I hope it helps. This time, it didn't immediately close. Windows checked for a solution, didn't find it, and closed the program.
This link is the log from when it immediately closed: https://dl.dropboxusercontent.com/u/106586470/MultiMC-4.log

**Comment by Loetkolben** [comment]
Well, to be honest, I have no idea either... Maybe one of the devs knows more?

**Comment by peterix** [comment]
Nope. Unless I can reproduce the issue, I have no idea.

Maybe some server response is getting mangled and we aren't handling the corrupted data right?
