### ISSUE TITLE
Crash after installing forge 1.7.2

### ISSUE THREAD

**Issue by Macruber** [MultiMC/MultiMC5#820]
Hi, I tried creating an instance with the version 1.7.2. I installed forge via MultiMC and tried to run the instance, and once the log window pops up, it scrolls through blue text and then red text and stops running, and doesn't open minecraft.

**Comment by 02JanDal** [comment]
Please use the Upload log button, and post the paste.ee link you get here.

**Comment by peterix** [comment]
You probably need the legacyjavafixer mod: http://files.minecraftforge.net/LegacyJavaFixer/legacyjavafixer-1.0.jar

**Comment by Macruber** [comment]
paste.ee link here:
http://paste.ee/p/D6qYw

I'll try legacyjava

**Comment by Macruber** [comment]
Ok, I added legacyjava and installed liteloader and it works. Thank you guys for your time.
