### ISSUE TITLE
Oh, no! Another problem!

### ISSUE THREAD

**Issue by GrimReaper03719** [MultiMC/MultiMC5#823]
Hello? My first problem was fixed.
But... Another big problem has been detected...
Please somebody help me.
If you know solution, please say them to me.
This is the problem's picture.
![default](https://cloud.githubusercontent.com/assets/11487374/6666608/44c57928-cc29-11e4-9809-929ac1afd04a.PNG)

**Comment by peterix** [comment]
Right.

First, switch to the dev update channel and see if it's a problem there. You can do so in the MultiMC settings - switch the channel do develop and after that, update.

**Comment by GrimReaper03719** [comment]
Thank you! The problem has been solved. Thank you very much.

**Comment by peterix** [comment]
Alright, in a week or two, we'll be doing some massive changes to develop and the current develop will be moving to stable. Unless you want to test some crazy new stuff and/or have a bunch of features missing, I'd advise moving to stable at that point ;)

We'll probably have an announcement on the blog and some nag screens about the changes in the application.

**Comment by GrimReaper03719** [comment]
Okay. I will. Thanks.
