### ISSUE TITLE
Minecraft not using GPU

### ISSUE THREAD

**Issue by EnderAndProud** [MultiMC/MultiMC5#827]
Hi, i have bit of a bug where my minecraft does not run on my Nvidia GTX 860M, instead just running on my integrated Intel 4600 HD Graphics. My specs (Lenovo Y50-70)-
Intel Core i7-4710HQ
Intel 4600 HD Graphics
Nvidia GTX 860M 
8GB DDR3 Memory
4 GB DDR5 Memory
8GB SSD
1 TB HDD

**Comment by 02JanDal** [comment]
Try renaming MultiMC.exe to minecraft.exe

**Comment by EnderAndProud** [comment]
Nice to see such afast response, but that didn't work

**Comment by 02JanDal** [comment]
See if there is some control panel for your graphics where you can add MultiMC.exe and/or javaw.exe to allow them to use the real GPU.

**Comment by Kilobyte22** [comment]
I assume you connected the monitor to the right GPU?

**Comment by EnderAndProud** [comment]
Yes i connected my display to my Nvidia GPU, & I put MultiMC.exe(renamed to minecraft.exe) to my Nvidia control panel

**Comment by EnderAndProud** [comment]
Plz reply!!

**Comment by peterix** [comment]
Then there's no reason why it shouldn't work.

Just renaming to Minecraft.exe is usually enough. Make sure you have 'show extensions for known file types' enabled. You could have it named 'Minecraft.exe.exe' now.

**Comment by EnderAndProud** [comment]
i checked that, & it still didn't fix the issue

**Comment by TheDoctorsLife** [comment]
It is using ur graphics card, right there in display second line geforce..... Your looking at the CPU

**Comment by EnderAndProud** [comment]
Well, how do u explain the low fps? I ask merely for information

**Comment by Heufneutje** [comment]
Considering it's at exactly 30 fps in both screenshots, I'd say something else is capping the framerate.

**Comment by EnderAndProud** [comment]
It wasn't 30 fps exactly, it was ranging from 25-32, for some reason it went to 30 during screenshots

**Comment by EnderAndProud** [comment]
Here are screenshots from all my instances, 
![2015-03-23_15 41 27](https://cloud.githubusercontent.com/assets/11524124/6777941/48115228-d174-11e4-8a48-25dd75922e84.png)
![2015-03-23_15 43 45](https://cloud.githubusercontent.com/assets/11524124/6777942/483a416a-d174-11e4-9755-0c7f130c8492.png)
![Uploading 2015-03-23_15.46.36.png . . .]()

**Comment by Kilobyte22** [comment]
What's the fps limit set to?

**Comment by EnderAndProud** [comment]
Unlimited, obviously

**Comment by KamranMackey** [comment]
@EnderAndProud Remove optifine, that might fix it

**Comment by EnderAndProud** [comment]
Extra bit of info:
My fps often jumps to 90 (in vanilla) when i connect to power

**Comment by KamranMackey** [comment]
@EnderAndProud Then that's why your FPS keeps dropping. Keep your computer connected to power at all times.

**Comment by EnderAndProud** [comment]
@KamranMackey wat about Vanilla? Optifine is not installed on 1.8.3

**Comment by Kilobyte22** [comment]
Minecraft performance mostly depends on your CPU, not your GPU. So when your CPU is slow you get lower fps. Often a CPU in laptops is throttled when on battery to conserve energy.

**Comment by EnderAndProud** [comment]
Well, how do i unthrottle it? My friend has GTX 780M, and Vanilla is like 60 fps on battery for him. Why does it not go to that on 860M?

**Comment by Kilobyte22** [comment]
Somewhere in system settings. Forgot where exactly. Been years since I last used windows

**Comment by KamranMackey** [comment]
@Kilobyte22 And why don't you use Windows anymore? Windows is a lot better than silly Linux.

**Comment by Kilobyte22** [comment]
Im a Linux user. Offers me better performance, more features and overall a more sane system

**Comment by EnderAndProud** [comment]
BACK to the issue at hand (ignoring attempts at firing shots), do u know, KamranMackey ?

**Comment by KamranMackey** [comment]
@EnderAndProud Sadly, I do not. You're best bet would just be to not use your laptop while unplugged. Sorry.

**Comment by peterix** [comment]
The exact multiples of 30 FPS also mean you probably have vsync enabled.
Which is not a problem.

**Comment by EnderAndProud** [comment]
V-sync is not enables, checked it a 100 times

**Comment by peterix** [comment]
I have absolutely no idea what was capping your FPS. Some global vsync option outside the game?

I have no way of fixing that.
