### ISSUE TITLE
What is causing this error?

### ISSUE THREAD

**Issue by Nianor** [MultiMC/MultiMC5#828]
Could a dev or someone who knows code make heads or tails of this, and tell me what I need to do to get it working?
https://paste.ee/p/r6bZH

**Comment by 02JanDal** [comment]
Please upload the full log using the Upload log button.

**Comment by Nianor** [comment]
Sorry, I can't find that. This is my first post.

**Comment by 02JanDal** [comment]
When running MultiMC, a "console" window with lots of colored text will show up. In it there is a button with the text **Upload** on it. Pressing it will give you a link to paste.ee. Post that link here.

If you don't get the console, open the MultiMC settings and find the checkbox called "Show console while the game is running?" and check it. Also make sure "Automatically close console when the game quits?" is NOT checked.

**Comment by Nianor** [comment]
I don't want my name being associated with this username.

**Comment by 02JanDal** [comment]
Then copy the log you get, edit out sensitive information, and re-post it on paste.ee, pastebin, or similar.

**Comment by Nianor** [comment]
Thanks.

**Comment by peterix** [comment]
This continues as #831
