### ISSUE TITLE
Mask system user name in console output.

### ISSUE THREAD

**Issue by Kilobyte22** [MultiMC/MultiMC5#829]
I have recently seen multiple people concerned about their privacy as in that they don't want their system username to be revealed when posting a crash log. We should at least consider masking said name, like we already do with profile name, UUID and access token.
However Qt has no way to natively do access the username, so we'd have to implement the logic ourselves. Especially cross-platform this isn't exactly easiest

My main question is: Is that a good idea and is it worth investing time into it?

**Comment by neclimdul** [comment]
maybe just supply a field and let the user populate it with strings they'd like replaced out of logs.

**Comment by Kilobyte22** [comment]
That certainly sounds an interesting approach, but we should define a couple default ones, that are populated automatically.

**Comment by TheDoctorsLife** [comment]
Like maybe the system user name? (I know people who use multimc on their school pc's where the username is firstname.lastname)

**Comment by peterix** [comment]
This makes a lot of sense.

Currently, unicode characters in paths are a problem for the updater. Anyway, that's a known, and already partially solved problem. Just needs the new updater to be finished/statically linked to QtCore.

We already censor the log output to some extent, mostly to prevent showing authentication details. So this would be an extension to that.

A second issue is that mojang uses e-mail addresses for the accounts, and those show up in the account selection menus. This could be a problem for people who make videos.

**Comment by TheDoctorsLife** [comment]
That's true, that would make a lot of people happy

**Comment by Kilobyte22** [comment]
Okay, let me outline what i am imagining for this.
Based on the idea of @neclimdul it would be a list of strings with a search -> replace mapping. There would also be a couple special strings (Profile Name, UUID, Access Token, System User and possibly more in the future) which automatically update depending on current needs and can't be deleted (however they possibly can be disabled). Users can add and remove their own masks.

Questions:
* Should we allow disabling the default ones? If so, all of them or only certain ones?
* Should we offer a possibility to disable ones added manually by a user?
* Should the setting be per instance, per profile or global?
* Generally, does anyone see any Issues?

**Comment by peterix** [comment]
https://github.com/MultiMC/MultiMC5/blob/feature/remote_version_files/logic/minecraft/Process.cpp#L47

For reference, the current code, in the freshest branch :)

**Comment by peterix** [comment]
Disabling in general ... maybe?
I would say global - it's a single step from the hardcoded ones.
User placeholders - sure.

**Comment by Kilobyte22** [comment]
Okay one issue i see from that code: How would we handle session properties? We possibly may have to do that independant from the actual list.

**Comment by peterix** [comment]
always censor the hell out of them, yes

**Comment by TheDoctorsLife** [comment]
Any update on this?

**Comment by peterix** [comment]
Now on workflowy:https://workflowy.com/s/2EyDMcp7CU #security
