### ISSUE TITLE
WHAT IS THIS! Failed to create instance Failed to create the instance directory.

### ISSUE THREAD

**Issue by MrMiles1st** [MultiMC/MultiMC5#830]
i really wanna fix this but don't know how im an admin on a server but ive been offline for 3 weeks im gonna lose my mind! I installed the latest java done the best I could but I couldn't fix it I made a instances folder for it but it still didn't work! 
![images1om0wa7h](https://cloud.githubusercontent.com/assets/11531197/6701685/55985be4-ccdd-11e4-9184-87224766c097.jpg)

![im-sad-and-confused](https://cloud.githubusercontent.com/assets/11531197/6701686/588198a2-ccdd-11e4-8a86-b236fdcd9cb3.jpg)

**Comment by Heufneutje** [comment]
Please locate the MultiMC-0.log file in your MultiMC folder and upload that to a Pastebin.

**Comment by 02JanDal** [comment]
Also: did you extract MultiMC from the zip? Where did you extract it too.

**Comment by peterix** [comment]
Probably some permission problem? If it can't create files/folders, it will never work.

MultiMC is supposed to run in a normal folder, owned by your user account, and not be blocked by random 'protection' software.

**Comment by MrMiles1st** [comment]
i don't have a log? and I put my multimc on my desktop its one folder called multimc I didn't make it and how do you do that

**Comment by MrMiles1st** [comment]
its doesn't show a log?

**Comment by MrMiles1st** [comment]
I don't see

**Comment by MrMiles1st** [comment]
a log sorry for these sort replies

**Comment by 02JanDal** [comment]
The log is a file called MultiMC-0.log in the same folder where you extracted MultiMC. Open it using a text editor and paste it's contents to a site like pastebin or similar, then post the link here.

**Comment by peterix** [comment]
Closed - no response.
