### ISSUE TITLE
MultiMC will use UNC paths when available, Minecraft+Forge don't like it

### ISSUE THREAD

**Issue by Nianor** [MultiMC/MultiMC5#831]
I would like to manually install forge as a .jar mod, without using the installer, as I think this may be the source of my issues. How would I go about doing this?

**Comment by robotbrain** [comment]
why? that isnt supported in any way by the forge people

**Comment by peterix** [comment]
It is not the source of your issues.

**Comment by Nianor** [comment]
I'm trying to get this to work over a restricted connection, and the installer is non-functional for normal minecraft. It can't get the files it needs to install.

**Comment by robotbrain** [comment]
there is an insttall forge button and using it as a jar mod wont work either

**Comment by peterix** [comment]
Right. Well, that just won't work.

You need about 20 different files, some from the forge people, some from mojang (not going to count them).

Current MultiMC finds out what to download by grabbing the installer, cracking it open and grabbing the list of required stuff from it.

**Comment by peterix** [comment]
Your best bet is to get those files while not going through a restricted connection.

Maybe use a proxy?

**Comment by Nianor** [comment]
Ah. Then I don't know why my MultiMc isn't working. This is my error log:
https://paste.ee/p/r6bZH

**Comment by peterix** [comment]
Right. Move the MultiMC install to an actual local harddrive. It's on some network share and that doesn't work.

**Comment by peterix** [comment]
even if it is local, for whatever reason, shared folders like that will use the network shared name in favor of the local name. So just make sure it's not shared.

**Comment by Nianor** [comment]
I don't know if these computers have local drives...

**Comment by peterix** [comment]
So those are school computers... well, MultiMC works from a flash drive, if you can connect those.

**Comment by Nianor** [comment]
It doesn't let us run apps from a flash drive. Any way to have the app run from a shared file but have the files it needs on a flash drive?

**Comment by peterix** [comment]
Hmm... maybe. You can run it like that:
`MultiMC.exe -d D:\whatever\mmc\root\path\you\want\`

It should use that path for files.

**Comment by Nianor** [comment]
Would I need to enter that into a command prompt?
'Cause that's disabled too.

**Comment by peterix** [comment]
Not really. If you can make/edit shortcuts or batch files.

**Comment by Nianor** [comment]
I don't think I can do either of those. Any other way to make it work?

**Comment by peterix** [comment]
well, a shortcut is just a file. You can make one on a different computer and use it elsewhere - maybe?

Can you use existing shortcuts?

**Comment by Nianor** [comment]
I don't know, I'll look into that. I'll tell you how it goes this time tomorrow.

**Comment by peterix** [comment]
Alright... a .bat file with something like this should work too:
```
C:\path\to\MultiMC.exe -d D:\path\to\files\
```

Adjust as needed.

**Comment by Loetkolben** [comment]
If you're using Windows 7 / Vista (not sure by the logs) and have the "Search Programs / Files" in the Start Menu, you should be able to ender the launch command there (you'll need an ablosute path).
For example:
*//CSSDFS06/Student_w$/***********/My Documents/MultiMC/MultiMC.exe -d D:\path\to\files\*

**Comment by Nianor** [comment]
I got it to run, and got these error logs:
https://paste.ee/p/aovsd
https://paste.ee/p/1nfoK
Sorry for the late response. I had to try a couple of things to get it working, and I am running it from a shortcut that links to a flash drive.

**Comment by peterix** [comment]
Well, bad news:
the computer(s) in question don't have a graphics card usable for 3d gaming. Anything past this would involve re/installing drivers or similar stuff.

I'm not sure how to proceed.

**Comment by peterix** [comment]
Does vanilla work?

**Comment by Nianor** [comment]
Vanilla runs, as well as a cracked version of the original Halo. Somehow that wound up on all the school computers. :\

**Comment by Nianor** [comment]
So the computers that are allowed to run it don't have the capabilities, and the computers that have the capabilities won't run apps from flash drives.

**Comment by peterix** [comment]
Right... what this is really about is MultiMC not using proper, local paths, when you start it from a 'shared' location on Windows.

It's a local folder, except shared. And it ends up using UNC paths throughout the application. MultiMC doesn't mind, Java just falls over.

**Comment by Nianor** [comment]
So you will try to fix it?

**Comment by peterix** [comment]
Yes.

**Comment by Nianor** [comment]
Thanks!

**Comment by peterix** [comment]
Well.

This is actually on a network share. I thought it was something else. There's no way to get around it that I see, at least not without fixing Forge, and likely countless mods.

See:
http://www.minecraftforge.net/forum/index.php?topic=27667.0

It's at the very least a Forge bug.

Also relevant - same bug, some other java software:
https://netbeans.org/bugzilla/show_bug.cgi?id=207060#c14

Is perhaps the same network share also mapped locally as a drive? (for example Y: or X:). If not, can you map the path as a drive? That could get around the issue, because java wouldn't see the weird windows paths.

**Comment by Nianor** [comment]
Possibly. I'll check tomorrow.

**Comment by robotbrain** [comment]
any news?

**Comment by Nianor** [comment]
I think I tried that. Still failed. I can make sure tomorrow.

**Comment by Nianor** [comment]
Nope. No such luck.

**Comment by peterix** [comment]
I fear there isn't much I can do with this not working.
