### ISSUE TITLE
Minecraft closing with Exitcode -1? 

### ISSUE THREAD

**Issue by Tampered** [MultiMC/MultiMC5#834]
http://paste.ee/p/C5aTA I'm not exactly sure what's happening. All I am doing is going into my furnace and it crashes.

**Comment by 02JanDal** [comment]
Please upload the full log using the Upload log button.

**Comment by Tampered** [comment]
http://paste.ee/p/vNfzl sorry bout that haha

**Comment by Loetkolben** [comment]
You're sure that this is the complete log? It does not contain that crash. Did you wait until the game chrashed before you pressed the *Upload Log-Button*?

**Comment by Tampered** [comment]
Yeah the game fully crashed and the only thing left open was the crash report. That's when I hit the Upload button.

**Comment by Tampered** [comment]
For some reason when I Upload the log it doesn't completely copy it. Only part of it.

**Comment by KamranMackey** [comment]
@Tampered Weird, maybe try launching the game again and this time, make sure you click "Upload Log" right after the game crashes.

**Comment by Tampered** [comment]
Yeah i've tried that twice. It seems that the log is too big to copy all of it.

**Comment by KamranMackey** [comment]
@Tampered Yeah, try copying the entire log manually by pressing Crtl + A, then copying & pasting the log onto paste.ee.

**Comment by KamranMackey** [comment]
And then hitting submit.

**Comment by peterix** [comment]
Well. This is from the 'levelup' mod. Make sure you don't have a developer version of it.

**Comment by Tampered** [comment]
https://paste.ee/p/12HJj There we go, and let me go check on that then.

**Comment by Tampered** [comment]
Totally got it working guys. Thanks for the help. Really appreciate it.

**Comment by KamranMackey** [comment]
@Tampered Glad to hear you sorted it out! Glad we were able to help you! :smiley:
