### ISSUE TITLE
Show an error dialog box when downloading update files fails

### ISSUE THREAD

**Issue by Loetkolben** [MultiMC/MultiMC5#835]
When MMC fails to download files from the update server, it just logs the error to a file:
> Error 202 : "Error downloading http://files.multimc.org/files/be5134cfe5f8656a08b5649962ae27f0-libstdc++-6.dll - server replied: Forbidden" while downloading  QUrl( "http://files.multimc.org/files/be5134cfe5f8656a08b5649962ae27f0-libstdc++-6.dll" )

Please make this error more obvious and visible to the user by showing an error dialog box that informs them and not just close the "Downloading Files" window (and do nothing else).

**Comment by peterix** [comment]
Fixed.
