### ISSUE TITLE
JVM Arguments question

### ISSUE THREAD

**Issue by igoutta** [MultiMC/MultiMC5#837]
The JVM arguments HeaddumpPath and Duser.language are from MultiMc or they are external lines?

-XX:MaxPermSize=256m, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx1536m, -Duser.language=en, -jar, C:/Users/Micro/Desktop/MultiMC/jars/NewLaunch.jar

**Comment by peterix** [comment]
They are from MultiMC.
HeapDumpPath is a workaround for faulty Intel graphics drivers.
user.language is a workaround for Minecraft localizing log messages, making them useless for troubleshooting.
