### ISSUE TITLE
Requesting Permission for creating Korean Localization Webpage introducing MultiMC

### ISSUE THREAD

**Issue by Abastro** [MultiMC/MultiMC5#840]
Hi, I'm Abastro, in Minecraft Mods Korean Localization Team.
We cannot find any other way to contact you, so please understand us though it may not make sense to post this here.
We, MMKL Team, want to create some Korean webpage introducing MultiMC. (like multimckr.org)
So we ask you for the permission. We will be greatly appreciated if it is possible.

**Comment by Kilobyte22** [comment]
A very easy way to contact basically any MultiMC developer is the #MultiMC channel on EsperNet

**Comment by Abastro** [comment]
Thanks!
