### ISSUE TITLE
Minecraft crashes with Null Pointer Exception

### ISSUE THREAD

**Issue by drifter397** [MultiMC/MultiMC5#843]
I recently updated forge and java to the latest version and launched my instance as usual but after a few seconds of pressing play, the game crashes with an exit code 0. I briefly read the console and saw something about forge. I am using the dev version of the launcher. Log: http://paste.ee/p/TMO7u

**Comment by Heufneutje** [comment]
> [21:17:03] [main/ERROR] [FML]: Unable to read the jar file Botania r1.5-170.jar - ignoring
java.util.zip.ZipException: error in opening zip file

Looks like your Botania JAR might be corrupt or something. I suggest redownloading it and see if that solves it.

**Comment by drifter397** [comment]
I did so, but got the same thing again.

**Comment by drifter397** [comment]
Ok, so I made a completely separate instance with nothing but forge and still get the same thing. But if I remove forge, making it just vanilla minecraft I get a way different crash. Log is here: http://paste.ee/p/UeVZ3

**Comment by drifter397** [comment]
Bingo! I have no clue what went on in the old workspace but the new one was just fine when I modified it. That makes this case closed. Just going to move my instances to the new workspace and go from there.
