### ISSUE TITLE
Service status icons for technic

### ISSUE THREAD

**Issue by 02JanDal** [MultiMC/MultiMC5#844]
Blocked by #469 

Once [this](https://twitter.com/Gen_Page/status/581357926079537152) is public we should have an option to show the status similar to how we show Mojang service status.

**Comment by peterix** [comment]
Moved to workflowy (Ideas->Packs->Technic)

**Comment by peterix** [comment]
We ... do not have technic integration. Maybe this would be valuable if we did, but we don't.
