### ISSUE TITLE
FTB instance does not load for unknown reason

### ISSUE THREAD

**Issue by BRFNGRNBWS** [MultiMC/MultiMC5#845]
I have the FTB Resurrection modpack installed, and when I click on it, the Minecraft window opens up, shows the Mojang logo, then it crashes and MultiMC log says exitcode -1. Does anyone know what that means? Here is my crash report btw:
http://tny.cz/d7b44078
Thanks.

**Comment by dmodoomsirius** [comment]
java.lang.NullPointerException: Initializing game
        at thaumic.tinkerer.common.enchantment.core.EnchantmentManager.registerExponentialCostData(EnchantmentManager.java:126)

It is thaumic tinker. 

Does it start up on the FTB launcher?

**Comment by BRFNGRNBWS** [comment]
Yeah it started up fine with the FTB launcher

**Comment by peterix** [comment]
OK.

Can you replicate the problem with latest unstable version? Just grab the fresh download:
https://files.multimc.org/downloads/mmc-unstable-win32.zip
And test.

**Comment by peterix** [comment]
Also, please post the actual log from the console window. Crash reports are useless.

**Comment by peterix** [comment]
Possibly not enough memory? Maybe? Hard to tell without an actual log. Closing.
