### ISSUE TITLE
multimc crash on open statistics (mmc5 - 0.4.5)

### ISSUE THREAD

**Issue by Cronosus** [MultiMC/MultiMC5#846]
on MP moded server, when player open Statistics from menu, client crashing
http://pastebin.com/GdgtWBGB

**Comment by Loetkolben** [comment]
Does it also crash when you have no mods installed (aka Vanilla)? If no, a mod is messing with MC's classes in a bad way what than causes the crash.

**Comment by Cronosus** [comment]
no, only with mods.. then i must test all mods

**Comment by peterix** [comment]
OK. Mod issue. Closing.
