### ISSUE TITLE
Log window frequently closes when computer is locked

### ISSUE THREAD

**Issue by Gotolei** [MultiMC/MultiMC5#848]
I know this was brought up in the IRC a couple weeks back, but it's happened more than five times so far today and quite frankly has been driving me nuts.
The window hides away, and until #403 is fixed it's impossible to bring it back without closing minecraft down, killing the process, and launching it again.

Problem appears to be unique to xubuntu (or perhaps all *buntu?), but I'm 99% sure some property or another is being set differently/incorrectly on the log window since I've never had problems with any other launchers' logs (or any other program for that matter) behaving like this.

**Comment by peterix** [comment]
OK. this will require making the console window into something that *isn't* a special snowflake :)

**Comment by peterix** [comment]
Well, the console window became an instance window... and it's a full top-level main window now. I don't think this is a problem anymore in current `develop` builds. Reopen if you disagree.
