### ISSUE TITLE
Screenshot upload to Imgur sometimes freezes & locks up the console window

### ISSUE THREAD

**Issue by LoyLT** [MultiMC/MultiMC5#849]
Screenshot upload to Imgur sometimes freezes & locks up the console window

(tried searching the bug reports first so forgive me if someone else has already reported it)

Any active game is still playable during this freeze up, but once the game is exited, the launcher has to be forcefully killed via task manager to do anything else.

**Comment by Kilobyte22** [comment]
Can you upload your MultiMC-0.log to https://gist.guthub.com please?

**Comment by LoyLT** [comment]
i would if gist.github.com would even come up for me right now... 
I've uploaded the file to paste.ee instead

http://paste.ee/r/cdbXK

took a while to find the right file though because whatever ya'll are doing to rotate logfile numbers isn't changing the creation date if an old logfile exists... the logfiles were dated 7/7/2014

**Comment by LoyLT** [comment]
from the logfile it looks like it attempted connection a few times and then failed..... unfortunately the popup window with the progress bar just stays there forever, and can't be closed

**Comment by peterix** [comment]
I think this should be fixed in current unstable branch:

Please grab a fresh download and check if it works for you:
https;//files.multimc.org/downloads/mmc-unstable-win32.zip

**Comment by robotbrain** [comment]
any news?

**Comment by LoyLT** [comment]
i haven't seen the issue in a while, but i also haven't seen hughesnet satellite internet have issues with imgur in a while either

**Comment by peterix** [comment]
Anyway, the news is that I changed a lot of download related logic in both develop and unstable with the changes above.

And it needs testing.

**Comment by peterix** [comment]
Looks good enough. Survives injecting of artificial errors.
