### ISSUE TITLE
Minecraft doesn't start up

### ISSUE THREAD

**Issue by jonasgo1998** [MultiMC/MultiMC5#850]
help!!! i just started using multimc and if i try to use start my vanilla instance i get this:
-------------------------------------------------------------------------------------------------------------
MultiMC version: 0.4.5

Minecraft folder is:
C:/Users/Jonas/AppData/Local/Temp/Rar$EXa0.283/MultiMC/instances/1.7.10/minecraft

Java path is:
C:/Program Files (x86)/Java/jre1.8.0_40/bin/javaw.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -jar, C:/Users/Jonas/AppData/Local/Temp/Rar$EXa0.283/MultiMC/jars/NewLaunch.jar]

Minecraft exited with exitcode 1.

ow and it cant find my java with the autosearch java
--------------------------------------------------------------------------------------

**Comment by Loetkolben** [comment]
Probably a problem with the MMC installation path, I think the *$* might be the problem. Move MMC to a location that does not have any non-standard letters in it's name and try again.

**Comment by jonasgo1998** [comment]
how do you meen ??? :3

**Comment by peterix** [comment]
`C:/Users/Jonas/AppData/Local/Temp/Rar$EXa0.283/` is not a good place, for anything.

Grab the MultiMC folder from there and put it on your desktop, for example.

**Comment by 02JanDal** [comment]
You need to extract MultiMC to somewhere, you are currently running it without extracting.

**Comment by jonasgo1998** [comment]
i work thank you all
