### ISSUE TITLE
Main Window - Groups should remain collapsed or expanded

### ISSUE THREAD

**Issue by Talicada** [MultiMC/MultiMC5#851]
The groups should remain either collapsed or expanded when starting up from the previous use. Probably best to store this information in the same file that controls what instances are in what group.

**Comment by 02JanDal** [comment]
There was some work on this at some point, I think it's pretty much abandoned by now though. Makes sense though.

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Instance view)](https://workflowy.com/s/2EyDMcp7CU)

**Comment by peterix** [comment]
Now implemented.
