### ISSUE TITLE
Add convenient way to post the MultiMC log

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#852]
Ideally, anonymized.

**Comment by spannerman79** [comment]
Perhaps using https://gist.github.com/ ?

**Comment by Kilobyte22** [comment]
We already use paste.ee for Minecraft logs, so I'd suggest also using that for MultiMC logs.

**Comment by TheDoctorsLife** [comment]
yeah, might be easier to use the same thing for pastes

**Comment by peterix** [comment]
Anyway, duplicate of GH-649
