### ISSUE TITLE
GTK+ not in CMakeLists.txt

### ISSUE THREAD

**Issue by tomelssjo** [MultiMC/MultiMC5#854]
This project seem to use GTK+, but it is not in the CMakeLists.txt as a dependice.
In order to use GTK+, something like this might work by adding it to the file:

```
find_package(GTK2 REQUIRED gtk)
```

Then, perhaps it is need in target_link_libraries() by adding ${GTK2_LIBRARIES} to the list.

**Comment by 02JanDal** [comment]
MultiMC itself doesn't use GTK, Qt for some reason does on some use it though. Not entirely sure how to solve this.

**Comment by peterix** [comment]
AFAIK, that should be only in the updater, and there, it's actually linked.

**Comment by peterix** [comment]
Anyway, MultiMC itself is definitely NOT using GTK in any way, shape or form.
