### ISSUE TITLE
MultiMC uses wrong guava version for forge

### ISSUE THREAD

**Issue by earlbrownie** [MultiMC/MultiMC5#855]
Just tried launching  the regrowth FTB pack and encountered an immediate crash
not even minecraft began I think:
http://pastebin.com/2sZs80Jr 
I tried on a custom pack with identical results

EDIT: rolled back to latest stable version and there was no crash

**Comment by peterix** [comment]
This is an issue with MultiMC using the wrong version of the guava library:
```
C:/Users/bench_000/Documents/Feed the Beast/libraries/com/google/guava/guava/15.0/guava-15.0.jar (missing)
```

Should be fixed in latest unstable. If you can, grab a fresh build:
files.multimc.org/downloads/mmc-unstable-win32.zip
And test that.

**Comment by peterix** [comment]
Workaround has been moved to develop.
