### ISSUE TITLE
Can't load Forge-versionslist

### ISSUE THREAD

**Issue by Yijare** [MultiMC/MultiMC5#858]
Hello
when I try to load a new forge version, the versions list is not even updating. i have to exut mmc per task-manager

**Comment by 02JanDal** [comment]
Please upload MultiMC-0.log to pastebin or similar and post the link here.

**Comment by Yijare** [comment]
INFO	MultiMC 5, (c) 2013-2014 MultiMC Contributors 
 INFO	Version                    :  "0.4.5" 
 INFO	Git commit                 :  "4ae0d8e0af6c0746e6d083829fc4c9a46fa15940" 
 INFO	Work dir before adjustment :  "D:/Program Files/mmc/MultiMC" 
 INFO	Work dir after adjustment  :  "D:/Program Files/mmc/MultiMC" 
 INFO	Adjusted by                :  "Command line D:/Program Files/mmc/MultiMC" 
 INFO	Binary path                :  "D:/Program Files/mmc/MultiMC" 
 INFO	Application root path      :  "D:/Program Files/mmc/MultiMC" 
 INFO	Static data path           :  "D:/Program Files/mmc/MultiMC" 
DEBUG	Detected default console font: "Lucida Console" , substitutions: "" 
 INFO	New FTB setup 
 INFO	FTB Launcher paths: "C:/Users/Martin/AppData/Local/ftblauncher" and "C:/Users/Martin/AppData/Roaming/ftblauncher" 
 INFO	Your language is "de" 
DEBUG	Loading MMC Language File for de ... 
 INFO	Instance path              :  "instances" 
 INFO	Loading Instances... 
 INFO	Loading MultiMC instance from  "instances/1.7.10" 
 INFO	Started watching  "D:/Program Files/mmc/MultiMC/icons" 
 INFO	Building version from multilayered sources. 
 INFO	Loading builtin version list. 
 WARN	Blacklisted legacy version ignored:  "rd-160052" 
 INFO	Loading local version list. 
 INFO	Loaded version "1.8" from local version list. 
 INFO	Loaded version "1.7.10" from local version list. 
 INFO	Loaded version "1.7.2" from local version list. 
 WARN	Order file doesn't exist. Ignoring. 
 INFO	Reading "net.minecraftforge.json" 
 INFO	Loaded instance  "YijaCraft 4.0.2.1"  from  "D:/Program Files/mmc/MultiMC/instances/1.7.10" 
 INFO	Loading MultiMC instance from  "instances/Awesomesauce" 
 INFO	Building version from custom.json within the instance. 
 INFO	Reading custom.json 
 INFO	Loaded instance  "Awesomesauce"  from  "D:/Program Files/mmc/MultiMC/instances/Awesomesauce" 
 INFO	Loading MultiMC instance from  "instances/Awesomesauce 1.7.2" 
 INFO	Building version from version.json and patches within the instance. 
 INFO	Reading version.json 
 WARN	Order file doesn't exist. Ignoring. 
 INFO	Reading "net.minecraftforge.json" 
 INFO	Loaded instance  "Awesomesauce 1.7.2"  from  "D:/Program Files/mmc/MultiMC/instances/Awesomesauce 1.7.2" 
 INFO	Loading MultiMC instance from  "instances/Test" 
 INFO	Building version from multilayered sources. 
 WARN	Order file doesn't exist. Ignoring.
 INFO	Loading accounts... 
DEBUG	Downloading Translations Index... 
 INFO	"Translations Index"  started. 
 INFO	Downloading  "http://files.multimc.org/translations/index" 
 INFO	Detecting proxy settings... 
 INFO	Using no proxy is an option! 
DEBUG	"FTB" > "" 
DEBUG	"FTB" > "" 
 INFO	"Status JSON"  started. 
 INFO	Downloading  "http://status.mojang.com/check" 
 INFO	"Startup player skins download"  started. 
 INFO	Reloading news. 
 INFO	"News RSS Feed"  started. 
 INFO	Downloading  "http://multimc.org/rss.xml" 
DEBUG	Checking for updates. 
DEBUG	Channel list isn't loaded yet. Loading channel list and deferring update check. 
DEBUG	Loading the channel list. 
 INFO	"Update System Channel List"  started. 
 INFO	Downloading  "http://files.multimc.org/update/win32/channels.json" 
 INFO	Didn't find any legacy assets to migrate 
 INFO	"Checking for notifications"  started. 
 INFO	Downloading  "http://files.multimc.org/notifications.json" 
 INFO	"Translations Index" progress: 1 / 1 
 INFO	"Translations Index" succeeded. 
DEBUG	Got translations index! 
 INFO	"Translations"  started. 
 INFO	Downloading  "http://files.multimc.org/translations/bg.qm" 
 INFO	Downloading  "http://files.multimc.org/translations/cs.qm" 
 INFO	Downloading  "http://files.multimc.org/translations/de.qm" 
 INFO	Downloading  "http://files.multimc.org/translations/es.qm" 
 INFO	Downloading  "http://files.multimc.org/translations/fi.qm" 
 INFO	Downloading  "http://files.multimc.org/translations/fr.qm" 
 INFO	Downloading  "http://files.multimc.org/translations/it.qm" 
 INFO	Downloading  "http://files.multimc.org/translations/ja.qm" 
 INFO	Downloading  "http://files.multimc.org/translations/ko.qm" 
 INFO	Downloading  "http://files.multimc.org/translations/nl.qm" 
 INFO	Downloading  "http://files.multimc.org/translations/pl.qm" 
 INFO	Downloading  "http://files.multimc.org/translations/pt_BR.qm" 
 INFO	Downloading  "http://files.multimc.org/translations/ru.qm" 
 INFO	Downloading  "http://files.multimc.org/translations/sv.qm" 
 INFO	Downloading  "http://files.multimc.org/translations/zh.qm" 
 INFO	"Update System Channel List" progress: 1 / 1 
 INFO	"Update System Channel List" succeeded. 
 INFO	Successfully loaded UpdateChecker channel list. 
DEBUG	Checking for updates. 
 INFO	"GoUpdate Repository Index"  started. 
 INFO	Downloading  "http://files.multimc.org/update/win32/stable/index.json" 
 INFO	"News RSS Feed" progress: 1 / 1 
 INFO	"News RSS Feed" succeeded. 
DEBUG	Finished loading RSS feed. 
DEBUG	Loaded news entry "Update to 0.4.5, Translations, Themes, and Technic" 
DEBUG	Loaded news entry "Version 0.4 out - Jar mods, UI changes, and more!" 
DEBUG	Loaded news entry "Introducing QuickMods - A better way to install mods" 
DEBUG	Loaded news entry "Support us on Patreon!" 
DEBUG	Loaded news entry "Heartbleed Vulnerability Update (fixed!)" 
DEBUG	Loaded news entry "Announcing MultiMC 6" 
DEBUG	Loaded news entry "MultiMC 5 - 0.3 update" 
DEBUG	Loaded news entry "First official MultiMC 5 release!" 
DEBUG	Loaded news entry "MultiMC Status Update" 
DEBUG	News loading succeeded. 
 INFO	"Status JSON" progress: 1 / 1 
 INFO	"Status JSON" succeeded. 
DEBUG	Finished loading status JSON. 
DEBUG	Status loading succeeded. 
 INFO	Following redirect to  "http://textures.minecraft.net/texture/3e8da065e42661baa7222b4b3848efdce81d3b1c212b40e1ae8ca14b482d49" 
 INFO	Downloading  "http://textures.minecraft.net/texture/3e8da065e42661baa7222b4b3848efdce81d3b1c212b40e1ae8ca14b482d49" 
 INFO	Loading remote version list. 
 INFO	Loaded version "15w14a" from remote version list. 
 INFO	Loaded version "1.8.3" from remote version list. 
 INFO	Loaded version "1.8.2" from remote version list. 
 INFO	Loaded version "1.8.2-pre7" from remote version list. 
 INFO	Loaded version "1.8.1" from remote version list. 
 INFO	Loaded version "1.8" from remote version list. 
 INFO	Loaded version "14w34d" from remote version list. 
 INFO	Loaded version "14w33c" from remote version list. 
 INFO	Loaded version "14w32d" from remote version list. 
 INFO	Loaded version "14w31a" from remote version list. 
 INFO	Loaded version "14w30c" from remote version list. 
 INFO	Loaded version "14w29b" from remote version list. 
 INFO	Loaded version "14w28b" from remote version list. 
 INFO	Loaded version "14w27b" from remote version list. 
 INFO	Loaded version "14w26c" from remote version list. 
 INFO	Loaded version "1.7.10" from remote version list. 
 INFO	Loaded version "14w25b" from remote version list. 
 INFO	Loaded version "1.7.10-pre4" from remote version list. 
 INFO	Loaded version "1.7.10-pre3" from remote version list. 
 INFO	Loaded version "1.7.10-pre2" from remote version list. 
 INFO	Loaded version "1.7.10-pre1" from remote version list. 
 INFO	Loaded version "14w21b" from remote version list. 
 INFO	Loaded version "14w20b" from remote version list. 
 INFO	Loaded version "14w19a" from remote version list. 
 INFO	Loaded version "14w18b" from remote version list. 
 INFO	Loaded version "14w17a" from remote version list. 
 INFO	Loaded version "14w11b" from remote version list. 
 INFO	Loaded version "1.7.9" from remote version list. 
 INFO	Loaded version "14w10c" from remote version list. 
 INFO	Loaded version "14w08a" from remote version list. 
 INFO	Loaded version "1.7.5" from remote version list. 
 INFO	Loaded version "14w07a" from remote version list. 
 INFO	Loaded version "14w06b" from remote version list. 
 INFO	Loaded version "14w05b" from remote version list. 
 INFO	Loaded version "14w04b" from remote version list. 
 INFO	Loaded version "14w03b" from remote version list. 
 INFO	Loaded version "14w02c" from remote version list. 
 INFO	Loaded version "1.7.4" from remote version list. 
 INFO	Loaded version "1.7.3" from remote version list. 
 INFO	Loaded version "1.7.2" from remote version list. 
 INFO	Loaded version "1.7.1" from remote version list. 
 INFO	Loaded version "1.7" from remote version list. 
 INFO	Loaded version "1.6.4" from remote version list. 
 INFO	Loaded version "1.6.2" from remote version list. 
 INFO	Loaded version "1.6.1" from remote version list. 
 INFO	Loaded version "1.6" from remote version list. 
 WARN	Blacklisted legacy version ignored:  "rd-160052" 
 INFO	Task succeeded 
 INFO	Discovered LWGL version "2.9.3" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.9.3/lwjgl-2.9.3.zip/download" 
 INFO	Discovered LWGL version "2.9.2" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.9.2/lwjgl-2.9.2.zip/download" 
 INFO	Discovered LWGL version "2.9.1" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.9.1/lwjgl-2.9.1.zip/download" 
 INFO	Discovered LWGL version "2.9.0" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.9.0/lwjgl-2.9.0.zip/download" 
 INFO	Discovered LWGL version "2.8.5" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.8.5/lwjgl-2.8.5.zip/download" 
 INFO	Discovered LWGL version "2.8.4" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.8.4/lwjgl-2.8.4.zip/download" 
 INFO	Discovered LWGL version "2.8.3" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.8.3/lwjgl-2.8.3.zip/download" 
 INFO	Discovered LWGL version "2.8.2" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.8.2/lwjgl-2.8.2.zip/download" 
 INFO	Discovered LWGL version "2.8.1" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.8.1/lwjgl-2.8.1.zip/download" 
 INFO	Discovered LWGL version "2.8.0" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.8.0/lwjgl-2.8.0.zip/download" 
 INFO	Discovered LWGL version "2.7.1" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.7.1/lwjgl-2.7.1.zip/download" 
 INFO	Discovered LWGL version "2.7" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.7/lwjgl-2.7.zip/download" 
 INFO	Discovered LWGL version "2.6" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.6/lwjgl-2.6.zip/download" 
 INFO	Discovered LWGL version "2.5" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.5/lwjgl-2.5.zip/download" 
 INFO	Discovered LWGL version "2.4.2" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.4.2/lwjgl-2.4.2.zip/download" 
 INFO	Discovered LWGL version "2.4.1" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.4.1/lwjgl-2.4.1.zip/download" 
 INFO	Discovered LWGL version "2.4" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.4/lwjgl-2.4.zip/download" 
 INFO	Discovered LWGL version "2.3" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.3/lwjgl-2.3.zip/download" 
 INFO	Discovered LWGL version "2.2.2" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.2.2/lwjgl-2.2.2.zip/download" 
 INFO	Discovered LWGL version "2.2.1" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.2.1/lwjgl-2.2.1.zip/download" 
 INFO	Discovered LWGL version "2.2.0" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.2.0/lwjgl-2.2.0.zip/download" 
 INFO	Discovered LWGL version "2.1.0" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.1.0/lwjgl-2.1.0.zip/download" 
 INFO	Discovered LWGL version "2.0.1" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.0.1/lwjgl-2.0.1.zip/download" 
 INFO	Discovered LWGL version "2.0" at "http://sourceforge.net/projects/java-game-lib/files/Official%20Releases/LWJGL%202.0/lwjgl-2.0.zip/download" 
 INFO	Loaded LWJGL list. 
 INFO	"Translations" progress: 1 / 15 
 INFO	"Translations" progress: 2 / 15 
 INFO	"Translations" progress: 3 / 15 
 INFO	"Translations" progress: 4 / 15 
 INFO	"Translations" progress: 5 / 15 
 INFO	"Translations" progress: 6 / 15 
 INFO	"Translations" progress: 7 / 15 
 INFO	"Translations" progress: 8 / 15 
 INFO	"Translations" progress: 9 / 15 
 INFO	"Translations" progress: 10 / 15 
 INFO	"Translations" progress: 11 / 15 
 INFO	"Translations" progress: 12 / 15 
 INFO	"Translations" progress: 13 / 15 
 INFO	"Translations" progress: 14 / 15 
 INFO	"GoUpdate Repository Index" progress: 1 / 1 
 INFO	"GoUpdate Repository Index" succeeded. 
DEBUG	Finished downloading repo index. Checking for new versions. 
DEBUG	Processing repository version list. 
 INFO	"Translations" progress: 15 / 15 
 INFO	"Translations" succeeded. 
DEBUG	Got translations! 
 INFO	"Startup player skins download" progress: 1 / 1 
 INFO	"Startup player skins download" succeeded. 
DEBUG	Processing authentication response. 
DEBUG	Getting new access token. 
DEBUG	Finished reading refresh response. 
 INFO	Task succeeded 
 INFO	Writing account list to "accounts.json" 
DEBUG	Building JSON data structure. 
DEBUG	Building account array. 
DEBUG	Writing account list to file. 
 INFO	Saved account list to "accounts.json" 
 INFO	"Version index"  started. 
 INFO	Downloading  "http://s3.amazonaws.com/Minecraft.Download/versions/1.7.10/1.7.10.json" 
 INFO	"Version index" progress: 1 / 1 
 INFO	"Version index" succeeded. 
 INFO	"qbjs   ,          fileId
 net.minecraft    id 1.7.10	  	 mainClass  net.minecraft.client.main.Main   minecraftArguments--username ${auth_player_name} --version ${version_name} --gameDir ${game_directory} --assetsDir ${assets_root} --assetIndex ${assets_index_name} --uuid ${auth_uuid} --accessToken ${auth_access_token} --userProperties ${user_properties} --userType ${user_type}  ?2   type   release   ?5   assets 1.7.109   releaseTime    2014-05-14T19:29:23+02:00 >   time   2014-05-14T19:29:23+02:00 ?   minimumLauncherVersionG  	 libraries ?	  4   d	  8      4      name   com.mojang:realms:1.3.5      H      D      name  ) org.apache.commons:commons-compress:1.8.1    H      D      name  * org.apache.httpcomponents:httpclient:4.3.3   D      @      name  % commons-logging:commons-logging:1.1.3    H      D      name  ( org.apache.httpcomponents:httpcore:4.3.2     4      0      name   java3d:vecmath:1.3.1     <      8      name   net.sf.trove4j:trove4j:3.0.3     @      <      name  " com.ibm.icu:icu4j-core-mojang:51.2   @      <      name  " net.sf.jopt-simple:jopt-simple:4.5   @      <      name  " com.paulscode:codecjorbis:20101023   @      <      name   com.paulscode:codecwav:20101023      H      D      name  ' com.paulscode:libraryjavasound:20101123      H      D      name  ) com.paulscode:librarylwjglopenal:20100824    @      <      name  " com.paulscode:soundsystem:20120107   @      <      name   io.netty:netty-all:4.0.10.Final      <      8      name   com.google.guava:guava:15.0      D      @      name  $ org.apache.commons:commons-lang3:3.1     8      4      name   commons-io:commons-io:2.4    @      <      name   commons-codec:commons-codec:1.9      @      <      name   com.google.code.gson:gson:2.2.4      8      4      name   com.mojang:authlib:1.5.16    L      H      name  , org.apache.logging.log4j:log4j-api:2.0-beta9     L      H      name  - org.apache.logging.log4j:log4j-core:2.0-beta9    4      0      name   tv.twitch:twitch:5.16    ?  	   ?     name   tv.twitch:twitch-platform:5.16	   natives   |      p   ?   windows    natives-windows-${arch}   ?   linux 
 natives-linux    osx    natives-osx   8   T      ?   extract   <      8   ?   exclude            	 META-INF/ ?     ?#   rules ?      ?   $             action allow    p      h      action disallow  ?   os<      4      name   linux    version                 $   ?    ?      8     t  	   d     name  & tv.twitch:twitch-external-platform:4.5
   natives   <      8   ?   windows    natives-windows-${arch}      ?   extract   <      8   ?   exclude            	 META-INF/ ?     ?   rules ?      |   p      h      action allow    os@      8      name   windows   ?   version          $          ?  ?      @   ?   ?  ?  ?  ?  #  ,  ?2  :  B  J  R  Z  c  l  t  |  ??  ?  ?  ?  ?  ?  ??  ?  ??  ?  ?     (   (  8   h     ?  ?  ?  " 
 INFO	Task succeeded 
 INFO	"YijaCraft 4.0.2.1" : downloading libraries 
 INFO	Building version from multilayered sources. 
 WARN	Order file doesn't exist. Ignoring. 
 INFO	Reading "net.minecraftforge.json" 
DEBUG	"" < "FTB" 
 INFO	"Bibliotheken f?r Instanz YijaCraft 4.0.2.1"  started. 
 INFO	"Bibliotheken f?r Instanz YijaCraft 4.0.2.1" progress: 1 / 2 
 INFO	Downloading  "http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.2.1352-1.7.10/forge-1.7.10-10.13.2.1352-1.7.10-universal.jar" 
 INFO	"Status JSON"  started. 
 INFO	Downloading  "http://status.mojang.com/check" 
 INFO	"Status JSON" progress: 1 / 1 
 INFO	"Status JSON" succeeded. 
DEBUG	Finished loading status JSON. 
DEBUG	Status loading succeeded. 
 INFO	"Status JSON"  started. 
 INFO	Downloading  "http://status.mojang.com/check" 
 INFO	"Status JSON" progress: 1 / 1 
 INFO	"Status JSON" succeeded. 
DEBUG	Finished loading status JSON. 
DEBUG	Status loading succeeded. 
 INFO	"Status JSON"  started. 
 INFO	Downloading  "http://status.mojang.com/check" 
 INFO	"Status JSON" progress: 1 / 1 
 INFO	"Status JSON" succeeded. 
DEBUG	Finished loading status JSON. 
DEBUG	Status loading succeeded. 
 INFO	"Status JSON"  started. 
 INFO	Downloading  "http://status.mojang.com/check" 
 INFO	"Status JSON" progress: 1 / 1 
 INFO	"Status JSON" succeeded. 
DEBUG	Finished loading status JSON. 
DEBUG	Status loading succeeded. 
 INFO	"Status JSON"  started. 
 INFO	Downloading  "http://status.mojang.com/check" 
 INFO	"Status JSON" progress: 1 / 1 
 INFO	"Status JSON" succeeded. 
DEBUG	Finished loading status JSON. 
DEBUG	Status loading succeeded. 
 INFO	"Status JSON"  started. 
 INFO	Downloading  "http://status.mojang.com/check" 
 INFO	"Status JSON" progress: 1 / 1 
 INFO	"Status JSON" succeeded. 
DEBUG	Finished loading status JSON. 
DEBUG	Status loading succeeded. 
 INFO	"Status JSON"  started. 
 INFO	Downloading  "http://status.mojang.com/check" 
 INFO	"Status JSON" progress: 1 / 1 
 INFO	"Status JSON" succeeded. 
DEBUG	Finished loading status JSON. 
DEBUG	Status loading succeeded.

**Comment by peterix** [comment]
Can't really see anything obviously wrong there.

Was this from such a frozen multimc?

Basically, what jan forgot to say:
1. Reproduce the issue
2. While keeping MultiMC frozen/crashed, post the MultiMC.0.log

They are log-rotated every time you run MultiMC - 0 becomes 1, 1 becomes 2, etc.

**Comment by Yijare** [comment]
yes peter, it was from such a frozen mmc.

it#s basicly just that instance on the computer of my friend. my own instance can load the versionslist.

i'll ask him for a newer multimc.0.log

**Comment by peterix** [comment]
Does the same happen with the development branch, the unstable branch?

If you want to check the unstable one, I'd suggest using a fresh install:
https://files.multimc.org/downloads/mmc-unstable-win32.zip

Unstable is not backwards compatible and... well, a bit unstable. But it handles things quite differently.

**Comment by Yijare** [comment]
unstable let's us load the versions list, but is, as you said unstable. anyways thank you for your help
