### ISSUE TITLE
Forge installation (on unstable branch) and MultiMC

### ISSUE THREAD

**Issue by luacs1998** [MultiMC/MultiMC5#860]
For 1.7.10, for example, the latest build that MMC sees is build 1307. There are [further builds than that](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html) but they have -1.7.10 appended to the version, which MMC does not detect. This may be the case on other MC versions as well.

It also seems that filtering of Forge versions by the MC versions is broken. 1307 (for 1.7.10) and 1306 (for 1.8) seem to be listed together, and the entire list shows every single build alll the way to the initial 1.6 alphas.

Is this a problem on your side or on Forge's side?

**Comment by peterix** [comment]
Unstable is actually not looking at the forge servers anymore, but a metadata repository. Which isn't really getting updated - it's just for testing right now and updates happen when @02JanDal runs some shell script :)

And yes, looks like some regexp somewhere needs to be tweaked.

Filtering isn't there, yes. We need dependency checking/resolution in the client for that. Before, it was a simple `if (mcVersion == instance mcVersion)`, now it will have to be a lot more generic.

**Comment by peterix** [comment]
The repo to look at: https://github.com/MultiMC/WonkoTheSane

**Comment by 02JanDal** [comment]
I just ran the script, so latest forge should be there again. The main blocker for running it continually is that we currently don't have a proper network cache. I'll get on that when I get back if @Kilobyte22 hasn't started on it yet then.

The further builds, are they listed in a different file than `http://files.minecraftforge.net/mave/net/minecraftforge/forge/json`? If yes then please open an issue in [MultiMC/WonkoTheSane](https://github.com/MultiMC/WonkoTheSane/issues).

**Comment by Kilobyte22** [comment]
I'll be working on the cache later or tomorrow. Didn't have time until now.

**Comment by peterix** [comment]
I think the question is answered :)
