### ISSUE TITLE
Failed to create instance Beast: Failed to create the instance directory.

### ISSUE THREAD

**Issue by TheEnglishLisle** [MultiMC/MultiMC5#862]
Failed to create instance Beast: Failed to create the instance directory.

**Comment by peterix** [comment]
Make sure you've actually extracted MultiMC and you're not running it from the zip file.

**Comment by TheEnglishLisle** [comment]
I have

**Comment by peterix** [comment]
Where did you extract it to?

**Comment by TheEnglishLisle** [comment]
I extracted the file again and it didn't work but the third time it did?

**Comment by TheEnglishLisle** [comment]
I guess it dosen't matter anymore

**Comment by peterix** [comment]
how odd. I guess it doesn't :)
