### ISSUE TITLE
64-Bit Windows

### ISSUE THREAD

**Issue by TYBeastMC** [MultiMC/MultiMC5#863]
I cant get 64 bit on windows even though i have a 64-bit computer

**Comment by Kilobyte22** [comment]
We do not provide 64-Bit builts for windows to my knowlage.

**Comment by dmodoomsirius** [comment]
32 bit works on a 64 bit system just like all other 32 bit applications. I use it and it works fine.

**Comment by Kilobyte22** [comment]
Yeah, generally most windows programs are 32-Bit only. MultiMC uses so little ram that it practically makes no difference.
