### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION | C  [ig75icd64.dll+0x47feed]

### ISSUE THREAD

**Issue by WarButter** [MultiMC/MultiMC5#869]
http://pastebin.com/b1Tx3PuD

The file ig75icd64.dll i think is my intel i7 haswell integrated gpu
Help please!!

**Comment by peterix** [comment]
Can you also post C:\Program Files\MultiMC\instances\1.8.3\minecraft\hs_err_pid22260.log ?

**Comment by WarButter** [comment]
http://pastebin.com/ckkCXVAa

**Comment by peterix** [comment]
You use Evolve. Apparently it's buggy.

See:
https://www.evolvehq.com/games/minecraft/topics/troubleshooting-minecraft-crashes-when

**Comment by WarButter** [comment]
Disabled Evolve overlay.
Minecraft runs again.
Thank you @peterix
