### ISSUE TITLE
Add legacy liteloader to metadata repository

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#871]
The 1.5.2 version does not work with our legacy launch method

It should be a jar mod?

**Comment by peterix** [comment]
Moved to workflowy

**Comment by VADemon** [comment]
Is it related to MultiMC saying there is no liteloader for old versions?

http://dl.liteloader.com/redist/legacy/

**Comment by peterix** [comment]
Yes, it is.
