### ISSUE TITLE
Launcher does not allow beta versions of LiteLoader

### ISSUE THREAD

**Issue by oscardssmith** [MultiMC/MultiMC5#873]
I am trying to create a version of 1.8 minecraft, and although liteloader has a 1.8 beta version, multimc doesn't let me add it.

**Comment by Heufneutje** [comment]
This is intentional behavior. The list provided by Mumfrey doesn't include beta versions. If you want to use it, you'll have to add it manually as described in #676

**Comment by peterix** [comment]
Will be trivially fixable in the future, when we do have our own version server.

**Comment by fanthos** [comment]
Build server of LiteLoader has a rss file, so this might be useful as temporary work around.
http://jenkins.liteloader.com/job/LiteLoader/rssAll

**Comment by peterix** [comment]
Any such temporary workaround would mean writing code which I will certainly throw away in a version or two.
