### ISSUE TITLE
Crashing and giving exit code -1

### ISSUE THREAD

**Issue by VastoPenguin** [MultiMC/MultiMC5#877]
Been using 1.6.4 for a while and every now and then i'll add new mods, but sometimes it just gives me the same exit code for no reason and doesnt want to work. in this particular instance i turned off extra utilities because it said that it had an error with that particular mod, and added in dartcraft. It doesnt seem to be dartcraft because it works in other instances.

Full report here: http://paste.ee/p/2zHAN

**Comment by Heufneutje** [comment]
> 2015-04-09 23:37:28 [SEVERE] [ForgeModLoader] Caught exception from Backpack
java.lang.NoClassDefFoundError: codechicken/nei/config/Option

It looks to me like Backpack is trying to do a thing NEI doesn't agree with. Are both of those mods up-to-date?

**Comment by VastoPenguin** [comment]
uh backpack is 1.26.29 and NEI is not installed in this instance. 

Mods installed are:
Applied Energistics
Backpack
Better Archery
BetterSignsMod
ComputerCraft
CraftGuide
DartCraft
Dimensional Anchors
EnderIO
Extra Utilities (disabled)
Immibis Core
Inventory Tweaks
Iron Chest
Open Blocks
OpenMod
Optifine
Random THings
RottenFleshToLeather
VeinMiner
VoxelMap

**Comment by peterix** [comment]
Well, the bakcpack mod is looking for some part of NEI... looks like it depends on it being there.

**Comment by VastoPenguin** [comment]
Its never been an issue before though, backpack has been in there since the start of putting this compilation together.

Removing it, and remaking the instance seems to have helped. So my issues were extra utilities and backpack. will close this now. thanks for the help guys!
