### ISSUE TITLE
Cannot open 1.4.7 modded with Optifine

### ISSUE THREAD

**Issue by Theta1996** [MultiMC/MultiMC5#878]
When I try to run my 1.4.7 modded Minecraft game, the FML window opens properly and closes to open the actual Minecraft Window. When the window is on the screen, it flashes the Mojang logo for a fraction of a second and then I get an error at the bottom of my console. The error from the log will be attached here and the entire log will be linked from here: https://drive.google.com/file/d/0Bybhhr1KlBA3Yk1BemkwYXExTU0/view?usp=sharing

![error](https://cloud.githubusercontent.com/assets/11872465/7068882/692a582c-decd-11e4-8514-a5834c22236c.png)

**Comment by peterix** [comment]
Please use that Upload button and post the resulting link here.

**Comment by peterix** [comment]
A related issue - NEI not working properly in 1.4.7 has been fixed in latest develop.

The issue was that we didn't name the main jar 'minecraft.jar', but 'temp.jar'. This sort of loading error could be the result of that.

You might want to check that out.

**Comment by peterix** [comment]
Actually:
![optifine](https://cloud.githubusercontent.com/assets/203326/7790156/43007f04-027d-11e5-9863-72a14ef5a298.png)

Works for me. You must have the jar mods added in the wrong order.
