### ISSUE TITLE
MultiMC launcher moves up tens of pixels every launch when not maximized (so that the title bar can no longer be seen)

### ISSUE THREAD

**Issue by ghost** [MultiMC/MultiMC5#879]
How to reproduce:

Get Ubuntu 14.04.2 64-bit installed on a computer
Run sudo apt-get install lubuntu-core --no-install-recommends in a terminal and follow the prompts (I don't have lubuntu-desktop meta package installed because I don't want the gunk that comes with it)
Log out
Select Lubuntu
Run MultiMC and if it's maximized, unmaximized it.
Quit MultiMC
Rerun MultiMC - notice how MultiMC has moved up a few ten or so pixels. Quit

It seems like there is a variable calculation issue somewhere.

Environment:

Ubuntu 14.04.2 64-bit - Lubuntu Core desktop
MultiMC 0.4.5
Java 8 (don't think that's necessary)

If you want a screen record let me know.

**Comment by peterix** [comment]
Sounds like this is specific to LXDE.

Related code:
https://github.com/MultiMC/MultiMC5/blob/unstable/application/main.cpp#L9
https://github.com/MultiMC/MultiMC5/blob/unstable/application/MainWindow.cpp#L1511

There is no room for error on MultiMC side and it works everywhere else.

**Comment by peterix** [comment]
I suggest filing a bug for the window manager you use.

**Comment by QuImUfu** [comment]
A simple workaround for people using Openbox/LXDE is forcing Openbox to place the MultiMC Window in the center. 
This can be done by adding: "<application name="MultiMC5" type="normal"><position force="yes"><x>center</x><y>center</y></position></application>"  to the something-rc.xml file in ~/.config/openbox/

**Comment by peterix** [comment]
See #748
