### ISSUE TITLE
Forge not found

### ISSUE THREAD

**Issue by SThomasW** [MultiMC/MultiMC5#882]
I was working on my instances but when I was doing forge I found that all versions didn't have a forge version for them and the instances who did have them still have them
HELP
![capture](https://cloud.githubusercontent.com/assets/11913136/7106514/4629b6b0-e111-11e4-84b3-c01b4cb2493b.PNG)

**Comment by peterix** [comment]
Click that refresh button. Does it help?

**Comment by SThomasW** [comment]
no it doesn't it just keeps saying that and I don't know why I am connected to the internet and everything

**Comment by robotbrain** [comment]
any news?

**Comment by SThomasW** [comment]
Well anything, I want to mod you know

**Comment by peterix** [comment]
Hmm. And what happens when you go into mods/minecraftforge/ and delete json and list.json?

If that doesn't work, getting the MultiMC log from the run of MultiMC you test the above with would help a lot. It's MultiMC-0.log

**Comment by SThomasW** [comment]
here is the log thig
INFO	MultiMC 5, (c) 2013-2014 MultiMC Contributors 
 INFO	Version                    :  "0.4.5" 
 INFO	Git commit                 :  "4ae0d8e0af6c0746e6d083829fc4c9a46fa15940" 
 INFO	Work dir before adjustment :  "C:/Users/Thomas/Desktop/desktop stuff/Multimc/MultiMC" 
 INFO	Work dir after adjustment  :  "C:/Users/Thomas/Desktop/desktop stuff/Multimc/MultiMC" 
 INFO	Adjusted by                :  "Command line C:/Users/Thomas/Desktop/desktop stuff/Multimc/MultiMC" 
 INFO	Binary path                :  "C:/Users/Thomas/Desktop/desktop stuff/Multimc/MultiMC" 
 INFO	Application root path      :  "C:/Users/Thomas/Desktop/desktop stuff/Multimc/MultiMC" 
 INFO	Static data path           :  "C:/Users/Thomas/Desktop/desktop stuff/Multimc/MultiMC" 
DEBUG	Detected default console font: "Lucida Console" , substitutions: "" 
 INFO	New FTB setup 
 INFO	FTB Launcher paths: "C:/Users/Thomas/AppData/Local/ftblauncher" and "C:/Users/Thomas/SkyDrive/Documents/ftblauncher" 
 INFO	Attempting to read "C:/Users/Thomas/SkyDrive/Documents/ftblauncher/ftblaunch.cfg" 
 WARN	Couldn't open "C:/Users/Thomas/SkyDrive/Documents/ftblauncher/ftblaunch.cfg" : "The system cannot find the path specified." 
 WARN	This is perfectly normal if you don't have FTB installed 
 INFO	Your language is "en" 
 INFO	Instance path              :  "instances" 
 INFO	Loading Instances... 
 INFO	Loading MultiMC instance from  "instances/1.6.2" 
 INFO	Started watching  "C:/Users/Thomas/Desktop/desktop stuff/Multimc/MultiMC/icons" 
 INFO	Adding  "icons/2014-10-29_15.24.36.png" 
 INFO	Building version from multilayered sources. 
 INFO	Loading builtin version list. 
 WARN	Blacklisted legacy version ignored:  "rd-160052" 
 INFO	Loading local version list. 
 INFO	Loaded version "15w14a" from local version list. 
 INFO	Loaded version "1.8" from local version list. 
 INFO	Loaded version "1.7.10" from local version list. 
 INFO	Loaded version "1.7.4" from local version list. 
 INFO	Loaded version "1.7.3" from local version list. 
 INFO	Loaded version "1.7.2" from local version list. 
 INFO	Loaded version "1.6.4" from local version list. 
 INFO	Loaded version "1.6.2" from local version list. 
 WARN	Order file doesn't exist. Ignoring. 
 INFO	Reading "net.minecraftforge.json" 
 INFO	Loaded instance  "1.6.2"  from  "C:/Users/Thomas/Desktop/desktop stuff/Multimc/MultiMC/instances/1.6.2" 
 INFO	Loading MultiMC instance from  "instances/1.6.4" 
 INFO	Building version from multilayered sources. 
 WARN	Order file doesn't exist. Ignoring. 
 INFO	Reading "net.minecraftforge.json" 
 INFO	Loaded instance  "1.6.4"  from  "C:/Users/Thomas/Desktop/desktop stuff/Multimc/MultiMC/instances/1.6.4" 
 INFO	Loading MultiMC instance from  "instances/1.6.41" 
 INFO	Building version from multilayered sources. 
 WARN	Order file doesn't exist. Ignoring. 
 INFO	Reading "net.minecraftforge.json" 
 INFO	Loaded instance  "1.6.4"  from  "C:/Users/Thomas/Desktop/desktop stuff/Multimc/MultiMC/instances/1.6.41" 
 INFO	Loading MultiMC instance from  "instances/1.7.10" 
 INFO	Building version from multilayered sources. 
 INFO	Reading "net.minecraftforge.json" 
 INFO	Loaded instance  "PLANES"  from  "C:/Users/Thomas/Desktop/desktop stuff/Multimc/MultiMC/instances/1.7.10" 
 INFO	Loading MultiMC instance from  "instances/1.7.101" 
 INFO	Building version from multilayered sources. 
 INFO	Reading "C:/Users/Thomas/Desktop/desktop stuff/Multimc/MultiMC/instances/1.7.101/patches/net.minecraftforge.json" by user order 
 INFO	Reading "net.minecraftforge.json" 
 INFO	Loaded instance  "My mods testing mc"  from  "C:/Users/Thomas/Desktop/desktop stuff/Multimc/MultiMC/instances/1.7.101" 
 INFO	Loading MultiMC instance from  "instances/1.7.2" 
 INFO	Building version from multilayered sources. 
 WARN	Order file doesn't exist. Ignoring. 
 INFO	Reading "net.minecraftforge.json" 
 INFO	Loaded instance  "bactira"  from  "C:/Users/Thomas/Desktop/desktop stuff/Multimc/MultiMC/instances/1.7.2" 
 INFO	Loading MultiMC instance from  "instances/1.7.4" 
 INFO	Building version from multilayered sources. 
 WARN	Order file doesn't exist. Ignoring. 
 INFO	Loaded instance  "1.7.4"  from  "C:/Users/Thomas/Desktop/desktop stuff/Multimc/MultiMC/instances/1.7.4" 
 INFO	Loading MultiMC instance from  "instances/1.8" 
 INFO	Building version from multilayered sources. 
 WARN	Order file doesn't exist. Ignoring.

**Comment by peterix** [comment]
The log doesn't include loading of the forge version lists.

MultiMC creates a new log file named MultiMC-0.log on every start, so the one that had it is now probably gone.

The version lists also got some significant changes in the recent development versions.

So:
1. make sure the json files from MultiMC/mods/minecraftforge/ are gone
2. Update MultiMC to the develop version - in the settings, set update channel to 'development' and then update (package with arrow icon on the main window toolbar).
3. Try adding Forge to an 1.7.10 or 1.8 instance
4. Then post the MultiMC-0.log, if it doesn't work.

**Comment by peterix** [comment]
Ok... you should now get some sensible errors out of the version lists now. Check out the latest stable/develop and reopen if you still have the same problem there.
