### ISSUE TITLE
Unable to remove Forge from an instance using MultiMC version 0.4.5-dev-468 on Windows

### ISSUE THREAD

**Issue by baddylan** [MultiMC/MultiMC5#887]
When I try to remove a jar mod from an instance, it shows it's removed, but if I press reload, it reappears.

After removing Forge from Jar Mods:

![image](https://cloud.githubusercontent.com/assets/7772177/7123779/3f8e0002-e1ea-11e4-86d0-0361589700f7.png)

Once I have pressed reload I then see the following:

![image](https://cloud.githubusercontent.com/assets/7772177/7123799/535077c8-e1ea-11e4-8133-fe8fa9b5d28f.png)

I am not sure why it is doing this, but I am hoping you're able to get this problem fixed

**Comment by 02JanDal** [comment]
Forge is not installed as a jarmod.

This is quite a serious issue though. After you tried to removing Forge, are there any files in `<instance>/patches`?

**Comment by baddylan** [comment]
I will check right now and let you know

**Comment by baddylan** [comment]
Yes, there is, the following was in <instance>/patches

![image](https://cloud.githubusercontent.com/assets/7772177/7124015/becbd5fa-e1eb-11e4-98ec-8a295a358a93.png)

**Comment by peterix** [comment]
Right. Make a copy of the instance.
From the copy, remove the minecraft folder.
Either export the copied instance, or zip it with an appropriate tool.
Upload that somewhere and link it here.

**Comment by baddylan** [comment]
Sure. https://www.dropbox.com/s/p4zsqb3tcbe6y1y/Copy%20of%20Instance.zip?dl=0

**Comment by peterix** [comment]
Should be fixed once this finishes building:
http://ci.multimc.org/waterfall
