### ISSUE TITLE
[Request] Copy Instance without copying Saves folder.

### ISSUE THREAD

**Issue by codewarrior0** [MultiMC/MultiMC5#888]
It would be nice to have a "Copy Saves" checkbox in the "Copy Instance" dialog. It's not always needed to copy the saves too. For example, if I want to update some mods and check for conflicts between them without changing the original instance, I won't need the saves folder. (And my saves folder is more than a gigabyte by now...)

**Comment by peterix** [comment]
Duplicate of GH-83
