### ISSUE TITLE
Automatic Legacy transfers without request.

### ISSUE THREAD

**Issue by Sarcadus** [MultiMC/MultiMC5#892]
My Modded MC 1.7.10 file was turned into legacy file for no reason and now I am unable to play on it or change it back to 1.7.10. Any suggestions or help?

**Comment by peterix** [comment]
Make a new instance, move over your mods, saves and configs there.

This thing should be already be fixed in the develop branch, so consider switching to that.

**Comment by Sarcadus** [comment]
Ok thanks for the help.

**Comment by robotbrain** [comment]
Any news?
