### ISSUE TITLE
One device not closed

### ISSUE THREAD

**Issue by Nianor** [MultiMC/MultiMC5#896]
Every time I launch, I get this crash:
https://paste.ee/p/VlIPG
Previously, my minecraft was pretty unstable, and I would get a crash like this about once every fifteen minutes, but I updated a mod, and now it does it every time I try to launch. Could someone help me find the root of the problem?

**Comment by MMC-translator** [comment]
What's in this?
```
C:\Users\Karla\Desktop\Files\Games\Minecraft\mmc-stable-win32\MultiMC\instances\1.7.10 Modded\minecraft\hs_err_pid7640.log
```

**Comment by Nianor** [comment]
https://paste.ee/p/9nDA7

**Comment by peterix** [comment]
Ok. OpenAL is a library for working with sound. This is not a java crash - this is something wrong between OpenAL, your OS and your hardware.

The hardware could be bad, the drivers could be bad. The OpenAL lib could be bad too.

I'm not sure what to do about this, except for some experiments:
* Try using 64bit java if possible. 64bit version of OpenAL could behave differently.
* Make sure your sound drivers are updated, or check if you didn't get an update that broke things.

**Comment by Nianor** [comment]
My java is 64 bit, and my sound drivers are up to date and have given me no problems. The mod causing it is Somnia, so I'm opening this thread on their Github too.

**Comment by peterix** [comment]
Alright... game problem.
