### ISSUE TITLE
 internal servers shutting down 

### ISSUE THREAD

**Issue by tevrenos** [MultiMC/MultiMC5#897]
I keep getting the internal servers shutting down error while creating a world or trying to load one, could someone please help

https://paste.ee/p/Kb4zN

**Comment by Loetkolben** [comment]
Do you have a minecraft cape? If yes, try disabling it in you Minecraft.net profile (if that's possible - i don't know, I don't have a cape :disappointed: )

**Comment by tevrenos** [comment]
neither do i, as far as i know.. ill have a look tho

**Comment by sholvax** [comment]
I have the same problem. Minecraft working again after i dissable Optifine.

**Comment by Kilobyte22** [comment]
Please keep in mind that optifine is known to cause random bugs

**Comment by peterix** [comment]
Post an actual MultiMC log.

**Comment by sholvax** [comment]
http://paste.ee/p/pjVfr

**Comment by tevrenos** [comment]
Gents, i have solved this out of luck, nothing else worked but, i recognised optifine HD b5 was the problem, i have loaded the b6 (newly updated) and it is golden now.. Hope it helps u people also

**Comment by Loetkolben** [comment]
So, it probably was an Optifine bug with downloading cape informatione or whatever....
