### ISSUE TITLE
Crash Report happening since i updated java

### ISSUE THREAD

**Issue by KiddRunaway** [MultiMC/MultiMC5#898]
MultiMC version: 0.4.5

Minecraft folder is:
C:/Users/User/AppData/Local/Temp/Rar$EXa0.942/MultiMC/instances/Kreatious/minecraft

Java path is:
java

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -jar, C:/Users/User/AppData/Local/Temp/Rar$EXa0.942/MultiMC/jars/NewLaunch.jar]

The java binary "java" couldn't be found. You may have to set up java if Minecraft fails to launch.
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object
Minecraft exited with exitcode 1.

**Comment by peterix** [comment]
1. You are running MultiMC from WinRar:
C:/Users/User/AppData/Local/Temp/Rar$EXa0.942/MultiMC/instances/Kreatious/minecraft
Don't do this. Extract it first somewhere. You'll lose the whole thing when Windows decides to clean up that temp folder.

2. In mmc settings, java page: click 'auto detect' and select a java to use.

**Comment by KiddRunaway** [comment]
I have done the WinRar thing, however when i go to change settings, java, auto-detect, it says no versions currently available , i have java 8 i think it is downloaded, i don't understand why its saying that, perhaps this version of multimc does not work with the recent version of java

**Comment by Kilobyte22** [comment]
It should work with all versions of Java Minecraft works with. Did you only download or also install it?

**Comment by KiddRunaway** [comment]
i believe both, but i'm gonna try to uninstall and reinstall it, hope it works

**Comment by KiddRunaway** [comment]
I reinstalled java, deleted the old versions and launched minecraft on the official launcher, it worked fine, but i use multimc for ease of acces and the report i got is this:

MultiMC version: 0.4.5

Minecraft folder is:
C:/Users/User/Desktop/MultiMC/instances/1.7.10/minecraft

Java path is:
java

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -jar, C:/Users/User/Desktop/MultiMC/jars/NewLaunch.jar]

The java binary "java" couldn't be found. You may have to set up java if Minecraft fails to launch.
Could not launch minecraft!



And i did use auto-detect in the settings and it still says thesame.

**Comment by 02JanDal** [comment]
Go into the MultiMC settings, go to the Java page, click _Auto detect_. Select one of the versions and click ok. Then retry.

**Comment by KiddRunaway** [comment]
Well i downloaded java 7 and it actually worked, thank for the help guys tho!
