### ISSUE TITLE
Request: "Activate All"-Button @ ModList

### ISSUE THREAD

**Issue by drsniper1000** [MultiMC/MultiMC5#901]
i would love to see a button on top of the mod lists to say activate all instead of activating them once at a time

**Comment by dmodoomsirius** [comment]
2nd this

**Comment by robotbrain** [comment]
thirding(?) this, confirmed

**Comment by TheDoctorsLife** [comment]
4th this

**Comment by peterix** [comment]
Ok. What does this mean?

Enable all mods?

Or select all mods?

**Comment by Lunatrius** [comment]
Pretty sure he means to enable all mods.

Do note that such a button might enable 2+ different versions of the same. Given that MultiMC already parses the mcmod.info file, a dialog could be displayed to warn the user of the potentially clashing mods (by checking whether all modids are unique or not).

**Comment by Heufneutje** [comment]
The mcmod.info file is not mandatory though, so I don't know if it's a source that can be relied on for that.

**Comment by peterix** [comment]
There are too many mods that have those wrong, empty, or just keep the 'Example mod' template with no changes.

The mod folder view is also ripe for an overhaul. It has features that are only used by 'Legacy' instances and you can't even create those anymore.
People wanted to have expandable folders (like the version folders inside 'mods').
So maybe these changes could be done as part of a larger rewrite based on QFileSystemModel, allowing multiple selections + operations on selections and no longer supporting the 'ordered jar mods list' features from Legacy.

**Comment by peterix** [comment]
Moved to workflowy:
https://workflowy.com/s/2EyDMcp7CU

**Comment by peterix** [comment]
Done.
