### ISSUE TITLE
UI styles/themes

### ISSUE THREAD

**Issue by 02JanDal** [MultiMC/MultiMC5#903]
There already exists #378, this issue is for implementing [this](http://stackoverflow.com/questions/15035767/is-the-qt-5-dark-fusion-theme-available-for-windows).

**Comment by peterix** [comment]
Moved to workflowy (Ideas -> Theming):
https://workflowy.com/s/2EyDMcp7CU

**Comment by KamranMackey** [comment]
@peterix Works on Windows, but some of the separators in the main window are still white, and all the text labels in the Settings menu are completely broken (as in, it isn't coloured and the text is white on white).

**Comment by peterix** [comment]
Yep. I can't use the Windows theme with custom colors. It will have to be Fusion.

For differences, see: http://doc.qt.io/qt-5/gallery.html

Fusion has full color scheme support, unlike the more native looking themes.

There's plenty of work to do:
https://workflowy.com/s/2EyDMcp7CU#/d65db4402e79

**Comment by peterix** [comment]
And I call this 'done'.
