### ISSUE TITLE
Java 8 compatability

### ISSUE THREAD

**Issue by spannerman79** [MultiMC/MultiMC5#907]
With Java 7 being pulled for public updates time to consider changing some of the features within MultiMC

The one thing I know needs to change is PermGen to -XX:MaxMetaspaceSize

PermGen was removed in Java 8 and replaced with MaxMetaspaceSize

Currently while using Java 8 and using Java arguments each and every time interacting with the instance shows the "You tried to manually set.." blah notification

**Comment by peterix** [comment]
Would you believe there are still people using java 6? Yes, there are.

Just don't set PermGen and it's fine.

**Comment by spannerman79** [comment]
Is there a switch to disable the "Manually set" notification until if/when there is an option for switching PermGen with MaxMetaspaceSize?

**Comment by Kilobyte22** [comment]
Set permgen to 256 MB in settings should do the job. That will remove the parameter.

**Comment by peterix** [comment]
I think that was 64 MB. I have no idea what you need MaxMetaspaceSize for though.

**Comment by Kilobyte22** [comment]
I agree. PermGen was officially removed. That's where in Java 7 and earlier classes get stored. In Java 8 classes get stored on the heap (I think)

**Comment by peterix** [comment]
> A new flag is available (MaxMetaspaceSize), allowing you to limit the amount of native memory used for class metadata. If you don’t specify this flag, the Metaspace will dynamically re-size depending of the application demand at runtime.

That means no more kids asking about PermGen OOM errors. I'm not going to promote reintroducing this nonsense.

**Comment by spannerman79** [comment]
PermGen was more or less replaced with MaxMetaspaceSize but has better GC (Garbage Collection)

**Comment by peterix** [comment]
I'll just make PermGen disappear when you have java 8.
If you want to add MaxMetaspaceSize, you can add it to the JVM args.

**Comment by Kilobyte22** [comment]
Do we have a reliable way to detect if the user runs java 8?

**Comment by peterix** [comment]
Well, there's the java checker. It will slow down launch a bit, but it's nothing too bad.

**Comment by peterix** [comment]
Alright. This is now mostly done in `develop`, along with some general improvements of the whole java checking logic.

MMC will test the java binary on instance launch and will remember the version based on binary modification time, so it's only done the first time it sees a new binary.

The 'Test' button in java settings now also takes JVm args into account - it first tests without args to probe if the binary is viable and what version it is, and then does a more thorough check with args.

... meaning, you can check your args from the settings and not have to launch an instance.

It also gives you the stderr output if there's any, regardless of whether the check failed or not.

Remaining tasks:
* Handle JavaOverride vs JavaLocationOverride in instance settings. Both need to be used, not just Location, although JavaOverride is deprecated.
* Thorough testing (this is where you guys come in :P)
* Put it in a video. I've been putting videos of what I finish on YouTube... no sound or anything, but I'd like to improve that.

**Comment by spannerman79** [comment]
Well seeing as I opened this issue I'd gladly be a guinea pig @peterix  :P Although I am not a coder so I have no idea how to compile 'develop' for windows to test for you.

OS: Win7 x64

**Comment by Heufneutje** [comment]
All you have to do is go into your MultiMC settings and switch the update channel to "develop".

**Comment by peterix** [comment]
And update, of course.

**Comment by peterix** [comment]
I now consider this done. Any further work on this will be separate bug issues.
