### ISSUE TITLE
Bug Language

### ISSUE THREAD

**Issue by Nyckoka** [MultiMC/MultiMC5#910]
I selected the portuguese language but the MultiMC is still in english!

**Comment by 02JanDal** [comment]
Did you restart it?

**Comment by Nyckoka** [comment]
yes

**Comment by 02JanDal** [comment]
It seems like the portuguese translation is quite unfinished, so it's highly likely that many parts will still use the default (english) language. If you want to help translating, go to [here](http://translate.multimc.org/projects/multimc/multimc/pt_BR/).

**Comment by Nyckoka** [comment]
ok thanks :D
