### ISSUE TITLE
1.7.10 Crashing with Forge and Optifine

### ISSUE THREAD

**Issue by WatsonB36** [MultiMC/MultiMC5#913]
Can't seem to figure it out. Optifine just doesn't seem to wanna play nicely. [Crash Report - Via Pastebin](http://pastebin.com/KY5ztCZa)

Any and all help that could be provided would be appreciated.
Thanks.

**Comment by peterix** [comment]
Downgrade forge to 10.13.2.1291

**Comment by WatsonB36** [comment]
Actually just figured that out. Thanks for the help!
