### ISSUE TITLE
Translations stalling MMC on at least Linux

### ISSUE THREAD

**Issue by TheWhoAreYouPerson** [MultiMC/MultiMC5#914]
When MultiMC is trying to load Translations, the entire thing stalls. Sometimes it needs to forced shut, other times you can wait it out. I personally think that it should load the user language, then put the other translations on the backside so it doesn't stall the client during loading.

It tends to happen around the
````
 INFO	"Translations" progress: 1 / 16 
 INFO	"Translations" progress: 2 / 16 
 INFO	"Translations" progress: 3 / 16 
 INFO	"Translations" progress: 4 / 16 
 INFO	"Translations" progress: 5 / 16 
 INFO	"Translations" progress: 6 / 16 
 INFO	"Translations" progress: 7 / 16 
````
area and not the 
````
DEBUG	Got translations index! 
 INFO	"Translations"  started. 
 INFO	Downloading  "http://files.multimc.org/translations/bg.qm" 
 INFO	Downloading  "http://files.multimc.org/translations/cs.qm" 
````
area.

**Edit: it seems to only stall when it's not finished loading, no matter how far along it is, as it started doing that after loading all the translations

**Comment by peterix** [comment]
This shouldn't be stalling anything - it's done as a background task.

Can you check if you have the same problem with the develop version of MultiMC?

You can switch to that in the settings and update.

**Comment by TheWhoAreYouPerson** [comment]
Sorry, turns out I have a few bad sectors on the drive I was storing MultiMC on. False alarm. So sorry!
