### ISSUE TITLE
[Request] Map/Save manager

### ISSUE THREAD

**Issue by Playermet** [MultiMC/MultiMC5#915]
How about a simple map/save manager?
How I see it:
 - Add button, which opens common saves folder on top panel;
 - Add 'Manage Saves' and 'Saves Folder' on right panel, and 'Saves' tab into 'Edit Instance' window;
 - 'Saves' looks like 'Loader mods', it contains 'Add', 'Remove', 'Rename', and 'Backup' (which copies save from instance to common map/saves folder) buttons;
 - Save name obtain (datetime) part after backed up, and losing it after copy to instance;

**Comment by 02JanDal** [comment]
So a 'Loader mods' for saves. Sounds reasonable.

**Comment by peterix** [comment]
Indeed.

Also:
* integrate with the mcedit support
* bring back world snapshots (old ferature from mmc3)

**Comment by Heufneutje** [comment]
:+1:

**Comment by peterix** [comment]
Well, this is done, isn't it?

World snapshots added to workflowy:
https://workflowy.com/s/2EyDMcp7CU Ideas -> World management
