### ISSUE TITLE
curse modpack downloading

### ISSUE THREAD

**Issue by loordgek** [MultiMC/MultiMC5#918]
can you ad curse modpack downloading to multimc
you can get the packs from here
http://www.curse.com/modpacks/minecraft

and maybe this will help you
https://github.com/portablejim/curseDownloader

**Comment by 02JanDal** [comment]
This will most likely have to wait until wonko is at least somewhat finished, hopefully in the next few weeks. We will add something like this though, that's for sure.

**Comment by loordgek** [comment]
you dont have to use use wonko from what i can see
take a look at this
https://github.com/portablejim/curseDownloader

**Comment by 02JanDal** [comment]
If we want to implement this in a non-hacky, future-proof way we'll need wonko. Technic support was put on halt for the same reason, the infrastructure is just not there yet (though it's getting closer).

**Comment by loordgek** [comment]
k
the minecraft luancher that curse is using is a BIG pile of poo that why i want this

**Comment by peterix** [comment]
Moved to workflowy - see Ideas -> Packs:
https://workflowy.com/s/2EyDMcp7CU

**Comment by phit** [comment]
would this [Curse.RestProxy](https://github.com/amcoder/Curse.RestProxy) be helpful to make this possible? After seeing the note on workflowy 
>Missing data and backwards formats... sadly.

**Comment by peterix** [comment]
Well, we have this already, it just got reopened because of mass issue manipulation.
