### ISSUE TITLE
No Mod Option in MultiMC5

### ISSUE THREAD

**Issue by gothangelblood** [MultiMC/MultiMC5#919]
I have no button to add or alter mods when I launch multimc, thus I am unable to even figure out how to load Forge into the launcher.

**Comment by peterix** [comment]
I have no idea what you mean.

**Comment by peterix** [comment]
You may want to take a look at this:
http://www.howtogeek.com/202661/how-to-manage-minecraft-instances-and-mods-with-multimc/
