### ISSUE TITLE
Differentiate 'No versions available' from 'couldn't fetch' in version lists

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#922]
![table1](https://cloud.githubusercontent.com/assets/203326/7350714/20dde88a-ed01-11e4-9399-952ae760f369.png)

Is it really not available, or did it just fail to fetch the list?

The suggested message for 'actually missing forge' is:
> forge hasn't been ported to 1.8.4 yet

**Comment by peterix** [comment]
Actually, the message could also serve as a simple progress bar (fetching...). Question is how to display it when there are items in the list already.

**Comment by Kilobyte22** [comment]
I'd suggest an additional status bar that can display things like "Fetching..." or "123 versions of forge found". This would always show the status. The full size message would only show when there are no versions to be displayed.

**Comment by peterix** [comment]
Not entirely related to this issue: something like that applies to a lot of the stuff we do right now.

Instead of modal dialogs that force the user to not mess with things, the action should run in the background and be interruptible. That means some restructuring of tasks and additions to the UI elements - 'throbbers', progress bars, unobtrusive status reporting.

**Comment by 02JanDal** [comment]
ProgressWidget in feature/multi_auth is there to not block user interaction, it could probably be used for the version selection dialog too.
