### ISSUE TITLE
Missing java version

### ISSUE THREAD

**Issue by LKHSogpit** [MultiMC/MultiMC5#923]
I am getting this error when launching any instance. Searching for similar issues has no solutions. I'm using  MMC5 - 0.4.5 stable. When I launch any instance I get this message:
```
MultiMC version: 0.4.5

Minecraft folder is:
C:/Users/Sogpit/Downloads/MultiMC/mmc-stable-win32/MultiMC/instances/Blast Off/minecraft

Java path is:
C:/Program Files/Java/jre7/bin/javaw.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2048m, -Xmx4096m, -XX:PermSize=256m, -Duser.language=en, -jar, C:/Users/PJ/Downloads/MultiMC/mmc-stable-win32/MultiMC/jars/NewLaunch.jar]

Could not launch minecraft!
```

I believe its to do with not being able to locate java. The first thing I did was check java on the website but it couldn't find it so I uninstalled java cleaned registry and reinstalled version 7u79 (64bit). Get the same error no instance will launch which they all did previously. I created a new 1.8 vanilla test instance in MMC and that doesn't launch so it definitely noting to do with mods! I tested Minecraft on the ATlauncher and everything lauched fine. I tried to update MMC to latest dev version 0.4.5-dev.483 it didn't fix it. 

When I do auto detect java it just says "no versions are currently available" I test and it says "The specified binary didn't work. you should use auto detect feature, or set the path to the java executable" so I manually locate java: C:/Program Files/Java/jre7/bin/javaw.exe. When I try to open the java console I get this:

![javauac](https://cloud.githubusercontent.com/assets/12150421/7366896/5c708f32-ed93-11e4-9116-65f3d4194249.PNG)

That has to do With UAC so running as admin opens the console window.

 I've been running instances from MMC for about a year now with the above Java Arguments its always being the most stable launcher for my system which is bare minimal.

I was playing a modpack last night just before everything went south. I right clicked an item in NEI the game hung a little and increased the RAM usage for each right click recipe search. The Game then froze and all available ram was maxed 5GB or so in task manager minecraft stopped responding! I threatened to kill minecraft from the console window and the game started responding again. This happened twice. I had to kill minecraft the second time as it wasn't responding at all and restarted computer and launched same instance. Everything was fine.

**Comment by LKHSogpit** [comment]
Many many lols just as I posted this it occurred to me that the link between the java console opening when I ran as admin fixed the evaluation error maybe running MMC as admin would fix it locating java. It did solution acquired! :facepalm:

Strange though I never had to run MMC as admin before and it suddenly stops working because of it.

Maybe somebody searching for same issues will come across this hopefully it will fix an issue for them.

**Comment by Kilobyte22** [comment]
There should not be any need to launch MultiMC as Admin. So this is clearly something wrong.

**Comment by LKHSogpit** [comment]
Well it fixed the issue so fingers crossed!

**Comment by peterix** [comment]
If you need admin to run MultiMC, there's something rather weird going on with your system. Not sure what. Anyway, you seem to be able to continue using it, so I'm closing this.
