### ISSUE TITLE
Import/Export pack expansion

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#924]
Import packs:
- [ ] By pasting the URL into the main window (CTRL+V)
- [ ] By dragging the link from a browser into the main window
- [ ] By dragging a zip file to the main window
- [ ] By dragging a folder to the main window

Export packs:
- [ ] By dragging an instance out of the main window

Later:
- [ ] do URL scheme integration -- make browsers redirect MMC pack URLs to MMC

**Comment by jaz000** [comment]
Awesome idea - I zip up and instance directory for friends already and that is working well but would like it to use the icon file from the instance directory if possible? so I am not limited to the built in icons - thanks

**Comment by peterix** [comment]
See the other issue: #904 ... I'll just merge them.

**Comment by peterix** [comment]
Add:

name
version
icon, detecting if the icon is custom, exporting the icon, importing the icon and using it on the other end
minimum memory requirements
package list
fluff metadata + web links

**Comment by peterix** [comment]
Icon files implemented in #1031

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Packs)](https://workflowy.com/s/2EyDMcp7CU)

**Comment by darthvader45** [comment]
Definitely a good idea.  I wished I had the chance to drag and drop a direct download link from Curseforge into MultiMC, and this sounds like it'd let me do just that.  Would make it so much easier to install modpacks.  Currently it just brings up the Import Instance screen on the Twitch tab, and there's a greyed out okay button and a dead-looking Twitch icon (you know, the Twitch icon with the anime x-x eyes)

**Comment by peterix** [comment]
No, this actuall has nothing to do with CurseForge.

**Comment by peterix** [comment]
Or Twitch.

**Comment by darthvader45** [comment]
Okay, so it has nothing to do with it, but does that mean it will NEVER happen, or could it become a future feature?

**Comment by Janrupf** [comment]
I wouldn't say it will never be implemented, but its not really priority at the moment.

**Comment by darthvader45** [comment]
Good, as long as there is a chance, there's hope.
