### ISSUE TITLE
Instance cleanup feature A: basics

### ISSUE THREAD

**Issue by dmodoomsirius** [MultiMC/MultiMC5#926]
A button to delete all the logs from the logs folder so when developing a modpack its easier to see new things. 

:+1:

**Comment by TheDoctorsLife** [comment]
+1

**Comment by peterix** [comment]
This can be done using the new functionality added to the instance export.

Basically, have a new page in edit instance, that is split into rules and a view of the instance.

You can check which files you want to delete in the instance view. You should be able to customize rules to include wildcards (think minecraft/logs/*, *.log, etc.).

More detailed wildcard/rule logic can be split off into a separate issue - the important part is that the user can have a persistent blacklist for files that should be removed - with a click of a button (and probably some summary/confirmation).

**Comment by peterix** [comment]
OK. This issue becomes point A in this document:
https://docs.google.com/document/d/1eitnu3tFPoaOLz0S2rH8eiE3XaLw5mWqSEQG2UIuUB4/edit?usp=sharing

**Comment by peterix** [comment]
- [ ] Implement the basic rule set types (abstract + implicit)
- [ ] Only do implicit rule sets, no user rule sets
- [ ] Other logs already recognize logs... -> make that a rule set instead

UI:
- [ ] Put cleaning shortcuts in places
    - definitely other logs
    - maybe instance export?

**Comment by peterix** [comment]
Tailored this to logs specifically.

Also added gzipped log support to 'other logs'.

**Comment by peterix** [comment]
Added in develop. OSX builds will have to wait for the OSX builder to be available.
