### ISSUE TITLE
Minecraft 1.8 No Text Appearing

### ISSUE THREAD

**Issue by GunnerBones** [MultiMC/MultiMC5#927]
Hello,
I'm using Minecraft Forge 1.8. However, when I load up Minecraft all the text boxes in the title screen are just boxes! It still lets me play but there is no font at all. The mods I am using are CodeChicken, Optifine, Shaders, Waila, and NEI.
-Gunner
The Log is too long to copy/paste.

**Comment by Kilobyte22** [comment]
You can post the log on gist.github.com. Also, for a start I'd try if the issue persists after removing optifine and shaders

**Comment by iwaw123** [comment]
This exact same thing happened to me, but its not just no font with empty boxes. sometimes they are little block thingies of different colors and sometimes they looks like dotted vertical lines in random colors. Can somebody please help me I'm getting really frustrated this keeps happening. I'm using TabbyChat mod for 1.7.10.

**Comment by QuImUfu** [comment]
This is a known bug with optifine and the shaders mod. Turn antialiasing, anisotropic filtering and fast rendering off (edit the option files). It should work then.

**Comment by caleywoods** [comment]
I'm using a fresh install of MC using the normal launcher with Forge and having this same issue. I don't see optifine or a shaders mod in the mine craft folder (this is on mac). I don't see which option files I should be editing.

**Comment by iwaw123** [comment]
I am on a Mac also but when I set the game to full screen then boom all the text is gone.
I need to manually make the window bigger. I was using the tabby chat mod when it was happening, it's the only mod that it happens with so far.

-iwaw123

**Comment by xeye17** [comment]
I have this problem too but on 1.7.10 without Optifine. When I install Optifine it crashes. It only happens when I resize the window or press one of the buttons.

**Comment by scoutchorton** [comment]
QuImUfu, I did it and it worked. I removed the shaders mod (just the .jar file), loaded minecraft, and changed the settings. I think it is fast render that did it, because that was the only thing I turned off. Make sure you turn off those settings!
