### ISSUE TITLE
Minecraft exited with exitcode -1

### ISSUE THREAD

**Issue by mhn3a** [MultiMC/MultiMC5#928]
https://pastee.org/deukd

this is the log.Can someone help me?

**Comment by loordgek** [comment]
you have a wrong mod can tell w/ one

**Comment by mhn3a** [comment]
how can i know what mod?

**Comment by loordgek** [comment]
post the full log

**Comment by mhn3a** [comment]
https://pastee.org/u4r9e here is the full log

**Comment by Heufneutje** [comment]
Looks similar to #917.

Try updating your Optifine to the latest version.

**Comment by Nixo7** [comment]
I have the same problem. Here is the log.
http://paste.ee/p/FteWN
Help please

**Comment by peterix** [comment]
You have a very different problem. Change your java - you are using something ancient.

**Comment by Nixo7** [comment]
i just updated java but I am still getting the exit code? Here is the new log.
http://paste.ee/p/qxSOI

**Comment by DreadWingKnight** [comment]
It's still using an old java
[15:21:58] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65

**Comment by peterix** [comment]
You need to change this in mmc settings.

**Comment by Nixo7** [comment]
It worked! Thank you

**Comment by Kilobyte22** [comment]
Just curious, why did you reopen this even though it was fixed

**Comment by Pyker** [comment]
That was another user. The original issue isn't fixed yet.

**Comment by Kilobyte22** [comment]
Oh okay, my bad

**Comment by peterix** [comment]
Well, I would say it was fixed, but waiting for @mhn3a to respond. It's the authlib + optifine thing though... so I think it might as well be closed.

@mhn3a you need to update optifine.

**Comment by Le1tus** [comment]
I have somewhat the same issue, again exit code -1 Here is the upload : http://paste.ee/p/hPY6f
and this is the whole consle log : http://paste.ee/p/KNDGk
Thanks in advance for looking at this

**Comment by peterix** [comment]
This issue is becoming a dump for all sorts of mod issues...

Anyway:
```
WirelessRedstone.cfg (The requested operation cannot be performed on a file with a user-mapped section open)
```

Do you have that file open in a text editor or something like that?

**Comment by Le1tus** [comment]
Nope, and i have tried upping the memory limits, updated java, and closed everything but the multimc instance and it is the same every launch.

**Comment by peterix** [comment]
`The requested operation cannot be performed on a file with a user-mapped section open` just means the file was locked for reading.

Try a reboot.

**Comment by Le1tus** [comment]
Can't believe that something that simple fixed it, thanks again for the help

**Comment by peterix** [comment]
Alright... so this issue was 3 issues in the end, from 3 different people. I'm just going to lock it now ;)
