### ISSUE TITLE
"Delete" for linked instances (like FTB) also deletes data

### ISSUE THREAD

**Issue by voxelcarrot** [MultiMC/MultiMC5#930]
When clicking "Delete" on FTB instances, the entire folder is removed. For FTB this includes things like backups. Should this option be enabled for "linked" instances? Maybe renamed such that its entry in MultiMC is only 'hidden', rather than the entire folder removed?

**Comment by peterix** [comment]
There are no such things as 'linked' instances. It works as it should.

**Comment by peterix** [comment]
Linked to: http://forum.feed-the-beast.com/threads/lost-everything-after-deleting-multimc-entry.83548
