### ISSUE TITLE
Justom Jar Version

### ISSUE THREAD

**Issue by Zendrex** [MultiMC/MultiMC5#935]
Well, I was looking through issues, and online and cant seem to figure this one out..

There is a mod called the crafting dead, it uses its own minecraft.jar file (its a dayz remake taking advantage of everything in minecraft), and I cant seem to figure out how to use a custom jar file for any instance. I tried changing the jar in the versions directory, etc and I cant seem to get it working. Any help or tutorial would be great. Thankyou.

**Comment by peterix** [comment]
Use it as a jar mod (edit instance, in the versions page). Make sure you use the right base Minecraft version.

**Comment by Zendrex** [comment]
Ah alright, thank you very much for the quick response! Good to know for the future :)
