### ISSUE TITLE
Trigger update after PreLaunch, not before it

### ISSUE THREAD

**Issue by Keridos** [MultiMC/MultiMC5#937]
Could you maybe add a function to reload the instance settings after the prelaunch command has been executed? This would allow it to update forge or liteloader etc. without having to restart minecraft for that to take effect via the prelaunch command.

**Comment by peterix** [comment]
A long term design problem. I was aware of it and then forgot, because it was a long time...

So let's get it fixed :)

**Comment by peterix** [comment]
Actually, have you tried in develop? This seems to be fixed there.

**Comment by peterix** [comment]
Actually, nevermind. This will need some bigger restructuring. The instance is reloaded after PreLaunch, but that's all done *after* updates are done.

**Comment by peterix** [comment]
Also, we seem to have an issue with some prelaunch scripts on windows.

See: http://pastebin.com/mMHXQFYt

This actually locks up. 
HYPOTHESIS: because MMC watches the folders for updates and this is trying to mess with them.

Test this case and make sure it works.

**Comment by Keridos** [comment]
Yeah I rarely have issues like that too, using git for updating and it spits out an exception when cleaning.

**Comment by peterix** [comment]
Fixed in `scratch/crazy`
