### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by abused** [MultiMC/MultiMC5#943]
I have a server with working cauldron but when i install my own custom modpack it crashes please help
http://pastebin.com/KaGJbMhg

**Comment by Keridos** [comment]
This has nothing to do with MultiMC...

**Comment by abused** [comment]
is this only for multimc?

**Comment by 02JanDal** [comment]
Well, let me check... Yep. It says "MultiMC / MultiMC5" at the top of the page...

**Comment by peterix** [comment]
yes. they aren't related in any way... I think they shared the name 3 years ago, and that was just due to a lack of awareness.

**Comment by Keridos** [comment]
Yes, this is the official repository for MultiMC, the launcher... Has nothing to do with mods or cauldron or minecraft bugs.

**Comment by abused** [comment]
well i made the modpack with miltimc but it doesnt load when i add it to the server

**Comment by Keridos** [comment]
That has nothing to do with MultiMC, still...

**Comment by peterix** [comment]
Well, make sure you don't have any client-side only mods in there then.

**Comment by peterix** [comment]
Also: SUPPORT STORM, **ENGAGE!**

This was a bit ridiculous.

**Comment by Keridos** [comment]
Try updating cauldron or just use vanilla forge. Cauldron does weird stuff sometimes. My own mod crashed with cauldron because I used a vanilla Minecraft Utility function and for some very weird reason that function was not present in Cauldron.

**Comment by abused** [comment]
lol but thank you

**Comment by abused** [comment]
yeh i have the lates version of cauldron but i cant use vanilla forge because it is going to be a public server so i need the plugins to keep things in order

**Comment by abused** [comment]
yes i can use the world edit mod and forge essentials but i also need a permissions mod or plugin and a claim plugin

**Comment by Keridos** [comment]
Doesn't FE have a complete permissions system and worldguard? Which is essentially what you need, correct?

**Comment by abused** [comment]
what is FE? and for the permissions i need one were i can set ranks and certain permissions for each rank or group

**Comment by Keridos** [comment]
Forge Essentials is FE...

**Comment by abused** [comment]
im not sure... but im going to try to contact my server host to see if they can help

**Comment by Meegooo** [comment]
And by the way... MultiMC is launcher for minecraft clients. And log you gave us clearly says that it's the server and is launched using Multicraft.
