### ISSUE TITLE
Mods installed but not working [Solved]

### ISSUE THREAD

**Issue by dark1272** [MultiMC/MultiMC5#948]
the mods are IN the game but they are not actually functioning, no crash report and no crashing, simply not working. I'm not sure if its multiMC's part or I'm just doing something wrong but whatever the case may be I have no way of showing you the issue as its just /not working/.
a good example is NEI is in the jar mods and loads the game but is not in the mods list nor does it work, pane in the glass is in but doesn't function, dynamic lights even toggles with L but it doesn't do anything anyway.

Solved, separate mods are loader mods, not jar mods

**Comment by dark1272** [comment]
another good example is better foliage is in the game, has a menu, is turned on and does nothing to the actual ingame look

**Comment by Loetkolben** [comment]
So, the mods are loaded (this is visible by for example the NEI pane showing) but they're not working (the pane is empty)? Well, than.. This is wired... I've never experienced such a thing before...
Please provide the full log using the "*Upload Log*" Button.

**Comment by dark1272** [comment]
NEI is in the JAR mod folder in the instance however it doesnt show in the imgame mod list nor does it work ingame at all. an unfortunate side effect is that the game is not crashing and its not spitting out a crash report but here are some logs from start to end.
http://paste.ee/p/YkJfM
http://paste.ee/p/HhAM8
http://paste.ee/p/LkGq3
there is a log for FML tweaked and its irrelevant but here it is
http://paste.ee/p/LLhsr

**Comment by Kilobyte22** [comment]
NEI is no jar mod, but a loader mod. At least 99.9% of all mods go on the loader mods tab, not jar mods

**Comment by dark1272** [comment]
i knew i must have been doing something wrong, thanks kilobyte22 :3
