### ISSUE TITLE
1.7.10 Modpack Crash Report

### ISSUE THREAD

**Issue by Final-Legacy** [MultiMC/MultiMC5#949]
I don't have very good programming skills, so I would like to ask the forums for some assistance. I am currently developing my own modpack and I am consistently getting the same crash report. Could someone please help me out? Here is a link to the crash report: http://paste.ee/p/N0sqn

Thanks for the assistance,
Fin

**Comment by DreadWingKnight** [comment]
You got a system that isn't running a java version from the dark ages?

**Comment by peterix** [comment]
`Java Version: 1.6.0_65, Apple Inc.`
You should definitely change the version of java you use.

Assuming you have 1.8 installed already, all you should need to do is change it in the MultiMC settings (java tab, auto-detect button).

**Comment by Final-Legacy** [comment]
I've updated my Java, but I'm still getting a crash report. I'm not sure if anything is different, so I'll post another link. http://paste.ee/p/R3QtY

**Comment by Final-Legacy** [comment]
I have updated Java, however, there is a new crash report. http://paste.ee/p/HiVrT

**Comment by peterix** [comment]
Looks like you are missing bibliocraft? Also, please use the actual Upload button in MultiMC.

**Comment by Final-Legacy** [comment]
Thanks so much for the help! Everything seems to be working now!

**Comment by Mattyproxx** [comment]
https://github.com/MultiMC/MultiMC5/issues/1291 help me
