### ISSUE TITLE
Minecraft exited with exitcode 1

### ISSUE THREAD

**Issue by BeboZorak** [MultiMC/MultiMC5#950]
https://paste.ee/p/mrpin

First time modding :/

**Comment by robotbrain** [comment]
Use the upload log button next time. I updated the issue to put it on paste.ee for you.

**Comment by peterix** [comment]
As for the problem: make sure all your mods are for the same version of minecraft.

**Comment by robotbrain** [comment]
Its a 1.8 mod in 1.7.10

**Comment by BeboZorak** [comment]
oh right, OK yeah I will make the changes now. Thanks for the help everyone, I'm new to this :3 Also, every time I try to include the mod 'NEI', it never works?

**Comment by peterix** [comment]
Probably because you also need CodeChickenCore.

**Comment by BeboZorak** [comment]
ah OK, I'll test everything out and let everyone know once I've finished :3

**Comment by BeboZorak** [comment]
Hey guys, I've done what you've said and this happened :/ http://paste.ee/p/AUUHE

**Comment by peterix** [comment]
You'll need to downgrade forge to a version without the new loading screen (look for versions without the `ls` suffix)

**Comment by BeboZorak** [comment]
Ok, yeah I've done that, the only problem is now that I go into the game, it says that I've lost connection to the server, I've tried playing offline and it will still happen :/

**Comment by Keridos** [comment]
Use Forge 1355, and update all your mods to the latest 1.7.10 version, that should work properly.
