### ISSUE TITLE
not loading

### ISSUE THREAD

**Issue by abused** [MultiMC/MultiMC5#953]
Hello. i just made a new modpack with multimc and whenever i load it, it crashes please help
the log is here http://paste.ee/p/xfOX3

**Comment by peterix** [comment]
Check your mods and their requirements. Some of them are ancient and for 1.6.4 - like binniecore.

**Comment by peterix** [comment]
BTW: you seem to be missing immersive engineering. but that's very much a WIP thing... I think you can get the source and build it, but can't redistribute because it has the default copyright (= all rights reserved).
