### ISSUE TITLE
Need Help Please

### ISSUE THREAD

**Issue by ChrissDis** [MultiMC/MultiMC5#954]
http://paste.ee/p/jKkvw

**Comment by Loetkolben** [comment]
Probably not a MMC problem...
Anyways, the problem is most likely
> at **net.epoxide.bladecraft**.util.Utilities.getRGBFromHex(Utilities.java:17) ~[Utilities.class:?] 

Check whether the problem persists after removing "Bladecraft".

**Comment by ChrissDis** [comment]
Thanks! It works perfectly now! :)
