### ISSUE TITLE
Log windows don't properly close in fullscreen on OS X

### ISSUE THREAD

**Issue by kinkodoyle** [MultiMC/MultiMC5#955]
If you use the native fullscreen feature in the more recent (Lion and beyond) versions of OS X and close a minecraft instance, the log window doesn't properly close. Instead, it creates a black screen that cannot be exited with CMD+W or brought out of full screen. The only way to get rid of it is by completely exiting MultiMC.

**Comment by peterix** [comment]
Definitely unintended.

**Comment by peterix** [comment]
If you switch to the development version (in mmc settings and then update), does that still happen?

**Comment by kinkodoyle** [comment]
Unfortunately, yes.

**Comment by peterix** [comment]
This seems awfully similar to #1387

**Comment by kinkodoyle** [comment]
The issue I have is the "black screen that doesn't react to anything" when a full-screened MultiMC window closes, be it either by CMD+W or when MultiMC closes a window (IE the instance selection screen closing when you launch minecraft). I can full-screen/minimize windows just fine.

**Comment by peterix** [comment]
Please re-test with current develop build.

**Comment by peterix** [comment]
No response, closing. Also, cannot reproduce this.
