### ISSUE TITLE
ftb infinity wont start in MultiMc

### ISSUE THREAD

**Issue by mlgpropig** [MultiMC/MultiMC5#956]
when i try to load up ftb infinity in MultiMC it just stops at like the 3/7 loading box in the starting Mojang screen.
here is the log http://paste.ee/p/Yfilq

**Comment by DreadWingKnight** [comment]
Set PermGen in your Multimc preferences - Java to 256MB or higher

**Comment by mlgpropig** [comment]
i tried to do it, and i taght it worked until mc just closed after loading.. 
http://paste.ee/p/4CikU

**Comment by Loetkolben** [comment]
>java.lang.OutOfMemoryError: GC overhead limit exceeded

More RAM? Increase the Max RAM (not PermGen) to something like 2GB (=2048M)

**Comment by mlgpropig** [comment]
tank u so much. it finally worked :)

**Comment by vinugaur** [comment]
Well, I had the same error, the game would stop and crash on loading 2/7, took me 4 days to try and figure this out, the game works fine, thank you for helping, not many people have answers for this, just takes mine 3 hrs to load :(
