### ISSUE TITLE
SSL handshake failed mac

### ISSUE THREAD

**Issue by albertoalegria** [MultiMC/MultiMC5#960]
I try to download minecraft 1.7.10 in MultiMC, but when I add my account MultiMC returns the error "SSL Handshake failed. "

**Comment by peterix** [comment]
Right. In the .app, you should be able to find MultiMC-#.log 0 is from the current run, 1 is from previous, etc.

Can you post the log from a run where this has failed?

**Comment by Orcinuss** [comment]
I just updated to dev 517 on the mac aswell and am getting this error now.
log snippet: http://pastebin.com/ycRRqCsB

**Comment by peterix** [comment]
Include the root cert:
http://www.infoworld.com/article/2911209/mac-os-x/yosemite-10103-breaks-some-applications-and-https-sites.html

**Comment by seaschell** [comment]
I'm using version 0.4.5 and this is also happening to me. It was working fine for me until today when it kept asking me to login offline. I first changed my proxy to 'none'. When that didn't work I deleted my minecraft account and attempted to add it again and that's when I got this error message. I have downloaded the suggested root cert in the article listed above (Root 1) with no change. PS - that error message is scary.  :P

**Comment by redwolfstone** [comment]
Same issue as the above running Mac OS Yosemite 10.10.3. Using the latest version (0.4.5) of MultiMC.
I installed Yosemite 10.10.3 yesterday and I could run MultiMC with no problems. But today when I tried logging in.. well, I couldn't. And when I tried re-adding my account I got the "SSL Handshake failed." error. I tried to fix the issue myself but that didn't work out. So I used Google :stuck_out_tongue: and then I got here. I added the Equifax certificate to my keychain; I still get the error though. 
Log file: http://pastebin.com/9Yqx0Ma6

Hopefully this issue will be resolved soon!

**Comment by peterix** [comment]
Please test the new develop build.

**Comment by PunKeel** [comment]
Same here, I'll try it thanks :)

**Comment by PunKeel** [comment]
Working, congrats !

**Comment by PunKeel** [comment]
Working, congrats @peterix !

**Comment by peterix** [comment]
Alright.

**Comment by seaschell** [comment]
It's working for me with the dev version 519. Thanks for the quick fix!
