### ISSUE TITLE
Could not create the Java Virtual Machine

### ISSUE THREAD

**Issue by DerKiba** [MultiMC/MultiMC5#961]
Hi i have this problem... http://paste.ee/p/bGfrK
i updatet my Java and have 64-bit and i have enough ram 12 GB...
please help

**Comment by peterix** [comment]
You are using 32bit java. If you don't have 64bit java, install it.

If you do, or after you install it, set java in MultiMC settings to the 64bit version.

**Comment by DerKiba** [comment]
Ok it fixed thanks

**Comment by Heufneutje** [comment]
Since MultiMC can detect some things about the selected Java version now, would it be possible to prevent or inform the user when they try to allocate more than 1.5 GB of RAM on 32-bit Java? This question has been asked quite a number of times.

**Comment by TheDoctorsLife** [comment]
hmm,  that's an nice idea, although this is already in the wiki if you press help on the java settings page "https://github.com/MultiMC/MultiMC5/wiki/Increasing-Java's-memory-allocation"

**Comment by Heufneutje** [comment]
Not everyone thinks to do that though.

**Comment by TheDoctorsLife** [comment]
Your right, I talked to @peterix he said it can be done, but it's not always going to be accurate if he were to implement this, Plus now we can link the wiki page when someone has another error like this.

**Comment by peterix** [comment]
Actually, have you tried putting in obviously broken values for min/max memory and clicking test in the new version?

**Comment by TheDoctorsLife** [comment]
I sure can try.

**Comment by TheDoctorsLife** [comment]
Yep I either get a "Failed to make virtual machine" with a dialog afterwards saying the arguments are invalid, or I get Success.
