### ISSUE TITLE
Minecraft version should be extracted from version patch when the patch is custom

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#966]
Let's have a generic function that allows querying version by uid and use that everywhere.

Split off from #952

**Comment by peterix** [comment]
Won't fix in old version list infrastructure, postponed to wonko.

**Comment by peterix** [comment]
Definitely not just wonko...

**Comment by TNTUP** [comment]
Sorry for commenting out an older issue, does it relates to the "custom" VersionType parameter? I can't seem where to rename it to the instance is named. I see (Minecraft/Vanilla/Custom) which Optifine is loaded as a library

**Comment by peterix** [comment]
No, this has nothing to do with optifine.

**Comment by TNTUP** [comment]
well, is there a way to change the --VersionType or I should ignore the "custom"? :P

**Comment by peterix** [comment]
Yes

**Comment by peterix** [comment]
Fixed in unstable.
