### ISSUE TITLE
Update help wiki pages

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#968]
Page dialog help buttons should all link to the right help wiki pages on github.
The wiki pages should be updated to reflect the new UI and functionality.

**Comment by TheDoctorsLife** [comment]
The help wiki is updated, finishing some last minute changes right now

**Comment by TheDoctorsLife** [comment]
Everything thing is documented from the current release,(0.4.6) however it's missing stuff for the next one(0.4.7).

**Comment by peterix** [comment]
Updated:
https://github.com/MultiMC/MultiMC5/wiki/FAQ
https://github.com/MultiMC/MultiMC5/wiki/Java-settings
