### ISSUE TITLE
Change the "Help" link in External tools and in "Accounts" in mmc settings

### ISSUE THREAD

**Issue by TheDoctorsLife** [MultiMC/MultiMC5#970]
External tools needs to be changed to https://github.com/MultiMC/MultiMC5/wiki/Tools
Accounts need to be changed to https://github.com/MultiMC/MultiMC5/wiki/Getting-Started#adding-an-account

**Comment by TheDoctorsLife** [comment]
Relates to #968

**Comment by TheDoctorsLife** [comment]
Cool!

**Comment by TheDoctorsLife** [comment]
Instance version needs to be changed from https://github.com/MultiMC/MultiMC5/wiki/Instance-version to https://github.com/MultiMC/MultiMC5/wiki/Instance-Versions

**Comment by peterix** [comment]
Hmmm... haven't noticed the added comments.

Alright.
