### ISSUE TITLE
Include libstdc++ in linux builds

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#974]
Because terrible ubuntu is terrible.

**Comment by neclimdul** [comment]
Lordy... is there no other way?

**Comment by peterix** [comment]
Yeah. Stop using c++11. And that's not happening.

**Comment by neclimdul** [comment]
Oh now I'm curious. Isn't most of c++11 syntax additions? What isn't available in libstdc?

**Comment by peterix** [comment]
It's that we need gcc 4.8 and the corresponding libstdc++ - that's not the default in Ubuntu 12.04.
MMC is built on 10.04, but with gcc 4.8 and the libstdc++ that comes with that.  This means the default system lib doesn't work with it.

So, for compatibility, we'll have to ship the library.

**Comment by neclimdul** [comment]
In that case, if my understanding is correct, you could specify the -fabi-version you want to build against and target a previous abi while using the newer compiler.

**Comment by peterix** [comment]
I'm not sure if that is a good idea. This is a bit of a minefield... then I'd need the older headers and things would start breaking.

The right solution is to ship the same libstdc++ I'm building with.

On start, compare the ABI versions of the system and our libstdc++. If the system is higher, use the system one. Otherwise use ours.
This is to prevent issues with local libraries being built with newer c++ libraries and being forced to work with an older one (= bad idea).

**Comment by peterix** [comment]
ldconfig -p | grep libstdc++.so.6 | cut -d ">" -f 2 | xargs

**Comment by peterix** [comment]
Tested the new develop build with Ubuntu Precise and Arch. Works.

**Comment by peterix** [comment]
It's possible to get the develop version directly here:
http://files.multimc.org/downloads/mmc-develop-lin64.tar.gz
