### ISSUE TITLE
Token error

### ISSUE THREAD

**Issue by Ratchet478** [MultiMC/MultiMC5#976]
Hello, when i tried to join in a server with multimc 5 v0.4.6 the game crashes with a unknow error

**Comment by 02JanDal** [comment]
Please use the _Upload Log_ button and post the paste.ee link you get here.

**Comment by Ratchet478** [comment]
I've got to let me connect to a server moving to a beta / aplha also I leave the log to see if it was a bug or was rare server
log: http://pastebin.com/9g6Pgn0N

**Comment by peterix** [comment]
Update optifine.
