### ISSUE TITLE
 v0.4.6 Crashes when loading with FTB tracker active

### ISSUE THREAD

**Issue by Nagapito** [MultiMC/MultiMC5#977]
If I disable the FTB tracker manually in the config options it opens correctly. 
If I enable the FTB tracker, the client just crashes.

Log: http://pastebin.com/0ZiDSP5S

Looking at the log, some of the packs MultiMC finds are not on my PC anymore... Maybe that is why its crashing?

**Comment by doskei** [comment]
I had the same problem.

In case it matters, Windows 8.1 x64, x64 java 8 u31.

I only had 2 FTB packs displayed prior to 0.4.6, and I can confirm both are still on my machine (EthoLP / Crash Landing).

Log: http://pastebin.com/4jfLjTpV

**Comment by peterix** [comment]
@doskei what is in C:/Games/FTB/EthosLPPack?

**Comment by peterix** [comment]
The develop version has a fix for FTB, but specific to Windows XP. I wasn't able to reproduce the crash here.

**Comment by Nagapito** [comment]
Just tested the development version, still does not work on Windows 8.1 x64. Same behaviour, crashes silently at startup. If FTB option is off and activate it, it just crashes the application.

I also tried the current 0.4.6 version on a Windows 7 x64 and it worked almost correctly. Maybe its a Windows 8.1 problem only?

And by almost correctly I mean it detected the FTB packs and didnt crashed and it saved the FTB packs directory correctly on the config file but once you reopened MultiMC, it removed all the "\" from the FTB path... D\:Documentos\Dropbox\FTB got converted to D:DocumentosDropboxFTB and obviously failed to find any packs, but it didnt crashed. This also happened with the development version.

Not sure if this a different issue or might still be related with the original problem.

**Comment by peterix** [comment]
Not really.

The backslashes shouldn't be used. That's an another bug.

Tested on Win 8.1 and it was fine. So what I'm thinking is that it's tripping over some of the data.

**Comment by Nagapito** [comment]
Ok... I messed around with the logs and possibly found the problem...

The log always ended laoding Agrarian Skies for 1.6.4 so I just renamed the folder and MultiMC loaded sucessfuly with FTB plugin on. After a breif look at the code I realized that it must be something in the instance.cfg file.

So, I renamed the folder to the original name but removed the instance.cfg file and MultiMC loaded but without Agrarian Skies (this was with the development version). Logs showed the following message for the pack:

Can't load instance  "c:/Jogos/FTB/AgrarianSkiesHQ"  because minecraft version  "1.6.4"  can't be resolved.

Ok.. it loads, I dont play the pack anymore, so its ok. But... lets try with the normal MultiMC version. Downgraded to the 0.4.6 and it also loaded with sucess, including the AG pack and also created a new instance.cfg file for the pack.

This is the original instance.cfg for the pack: http://pastebin.com/rV36tNT0
This is the new generated instance.cfg for the pack: http://pastebin.com/Dqq3ECEU

Hope this helps pinpointing the issue.

**Comment by peterix** [comment]
So that's odd.

The first one is a pure legacy instance config - not FTB at all. It makes zero sense for it to be like that and the best thing to do with it is a delete.
The second one is actually an FTB instance config.

**Comment by peterix** [comment]
OK. Current develop should now behave better.

When the instance config can't be loaded, it will delete it and create a new one.
When saving the paths, they will be passed through a 'normalize' function that replaces backslashes with normal slashes.

**Comment by peterix** [comment]
Seems to work fine :)

**Comment by peterix** [comment]
@Nagapito @doskei So, can you confirm that this works on your end with the current develop version?

**Comment by Nagapito** [comment]
Just tested it, it deleted the invalid file but didnt created a new one automatically. 
Had to hit the refresh button to detect the instance and create the file.

Not a big deal if you dont want to care about it. It will show up again after a refresh or restart so...

**Comment by peterix** [comment]
Yeah. that's pretty much what I made it do. Delete the bad file.

**Comment by peterix** [comment]
Fixed a tiny issue with the icon not being set properly on first load and removed some extra debug prints.

This is now DONE :)

**Comment by doskei** [comment]
Haven't tested yet but will try to remember to do so tonight.
