### ISSUE TITLE
0.4.6: It should be documented how to use MultiMC with optimus graphics on linux

### ISSUE THREAD

**Issue by grauerkoala** [MultiMC/MultiMC5#978]
**Edit for future reference:** This used to be about my wrapper script for running Minecraft using Optimus not working anymore. We later discovered this to be a problem not caused by MultiMC but by `optirun --status`.

---

Hello,

I've recently picked up using MultiMC. Because I own a notebook that features Nvidia Optimus and runs Debian, I need to run games using the primusrun command so that they are rendered using the Nvidia graphics chip rather than the Intel one that is used by default (for power saving). For that reason I have built a very simple script that passes on its parameters to `primusrun <java-path>/java`.

Not surprsingly, back in 0.4.5 testing the Java path from the settings dialog produced resulted in a failure, *however* launching the game still worked since apparently no check was performed then. Now that I have upgraded to 0.4.6, there appears to be a forced check when launching a modpack, resulting of course in a failure and therefore preventing the launch from happening at all:
```
MultiMC version: 0.4.6

Minecraft folder is:
/<blah>/Minecraft/MultiMC/instances/1.7.10/minecraft

Java path is:
/<blah>/Minecraft/minecraftjava

Checking Java version...
Could not start java:


Check your MultiMC Java settings.
```

So, is there any way to either run Minecraft using `primusrun` while providing a "valid" java path for MultiMC or to prevent it from checking for the java version when launching?

If not, this report can be considered a feature request. :)

Thanks! -koala

**Comment by peterix** [comment]
Hmmm... right. all it expects is that the script prints some values to stdout when run. If it doesn't see them, it fails.

I don't have that hardware and I doubt `primusrun` would work without it.

Can you post that script and what it prints on stdout when run?

**Comment by grauerkoala** [comment]
Good thing you asked me to do that! My script contains a check to see whether the discrete graphics card is being used already or not:
```
wmname LG3D && \
if optirun --status 2> /dev/null; then
    /usr/bin/primusrun /usr/bin/java $@
else
    /usr/bin/java $@
fi
```

During a recent upgrade of the optirun command it must have changed so that the message I'm trying to supress by writing it to /dev/null no longer appears on stderr but stdout. That resulted in this:

```
$ ./minecraftjava -version
Bumblebee status: Ready (3.2.1). X is PID 12533, 2 applications using bumblebeed.

java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

Long story short, I simply need to replace `2>` with `&>` and I should be golden (I'll test that once I can, but I'm confident it'll do the trick). Also it's not MultiMC's fault, so sorry and thanks for the help (also thanks for this great piece of software)! :D

-koala

**Comment by peterix** [comment]
Hmm... sounds like something that should be at least described in a FAQ somewhere.

**Comment by grauerkoala** [comment]
Here's what I found: Changing the wrapper script in the manner described previously works perfectly, the version check succeeds.

Apart from that, it would appear that MultiMC launches Minecraft by way of forking rather than spawning (which I could have figured beforehand, since the log is displayed through MultiMC), meaning that a different (and, depending on your taste, possibly cleaner) solution would be to simply run MultiMC using primusrun (or optirun) since it seems to apply to the whole subsequent process tree. Of course, in that case it might be a bad idea to also use the wrapper scribt described above (didn't test that though).

At least the fact that the version check is done by comparing the output of java the way it's done *could* be something worth mentioning in some kind of documentation, but that might only be interesting to a very small group of users.

**Comment by peterix** [comment]
I wouldn't take the numbers of users per platform into consideration. If I did, I would be turning this into a metro app right now.

*run switches to the nvidia graphics globally? What happens if you run MultiMC with it and just let it sit around on the desktop without starting Minecraft? Will it run the power hungry nvidia card?

**Comment by grauerkoala** [comment]
> I wouldn't take the numbers of users per platform into consideration. If I did, I would be turning this into a metro app right now.

Why not branch out..? But I see and approve of your point.

> *run switches to the nvidia graphics globally? What happens if you run MultiMC with it and just let it sit around on the desktop without starting Minecraft? Will it run the power hungry nvidia card?

Cursory investigation using dmesg seems to reveal that the discrete graphics are indeed enabled as soon as MultiMC (or anything really) is run using either primusrun or optirun:
```
[  391.117641] bbswitch: enabling discrete graphics
```
The estimated time for my battery to run dry drops as well. So you're probably right in assuming that running MultiMC using *run by default is wasteful.

**Comment by Gotolei** [comment]
Was MultiMC's behavior changed from 0.4.5 to 0.4.6 then? Granted I have bumblebee, but 0.4.6 still fails entirely whether I run it through the nvidia card or not while it worked perfectly fine in 0.4.5, but through intel graphics it at least gets as far as creating the log window.

**Comment by peterix** [comment]
With the newest changes, it's just adding the info about wrapper commands and the ability to use 'optirun' and similar as a wrapper command.

**Comment by peterix** [comment]
Updated wiki pages:
https://github.com/MultiMC/MultiMC5/wiki/FAQ
https://github.com/MultiMC/MultiMC5/wiki/Java-settings#custom-commands
