### ISSUE TITLE
multimc 0.4.6 fails to launch on 64-bit linux with a symbol error

### ISSUE THREAD

**Issue by SuperDoxin** [MultiMC/MultiMC5#979]
starting the latest multimc gives the following error:

    bin/MultiMC: symbol lookup error: bin/MultiMC: undefined symbol: _ZN6QDebugD1Ev

the previous version worked perfectly fine.

**Comment by peterix** [comment]
Do you run the binary directly? If so, use the wrapper script instead.

**Comment by peterix** [comment]
I've fixed some compatibility issue with libstdc++.so.6, so you could try the develop version.

From 0.4.5, update to develop.

It's also possible to get the develop version directly here:
http://files.multimc.org/downloads/mmc-develop-lin64.tar.gz

**Comment by SuperDoxin** [comment]
running the wrapper script works. oops.
