### ISSUE TITLE
TroubleShooting

### ISSUE THREAD

**Issue by TheDoctorsLife** [MultiMC/MultiMC5#981]
I need help with making a wiki page for common issues and how to fix them, here is what is done so far [Troubleshooting](https://github.com/MultiMC/MultiMC5/wiki/Troubleshooting). If you can just post some common errors you have came into while using multimc (Like the Java virtual machine one) Please comment the issue and how to solve it.

**Comment by peterix** [comment]
One of the most common issues comes from people trying to use mods for a different Minecraft version than they are meant for.

**Comment by 02JanDal** [comment]
Also often occuring: Putting forge/liteloader mods in Jarmods (usability issue)

**Comment by TheDoctorsLife** [comment]
Added both of these.

**Comment by TheDoctorsLife** [comment]
Going to close this for now, can be reopened if any other common things start appearing. (other than the ones listed here) if only github had a feature that made you read a wiki page before reporting, imagine the benefits.
