### ISSUE TITLE
v0.4.6 Japanese translation doesn't load

### ISSUE THREAD

**Issue by HawkEye1015** [MultiMC/MultiMC5#982]
I was translated into Japanese
But there is a possibility that Japanese translation file is not loaded :(

**Comment by peterix** [comment]
The translation files got updated for the new stable build, so it's possible quite a bit of the translation is broken right now. Simply wasn't updated yet.

**Comment by peterix** [comment]
Although... nothing seems translated.

**Comment by peterix** [comment]
Fixed.

**Comment by peterix** [comment]
This was a problem in the translation source files (.po). They were missing a header:
```
"X-Qt-Contexts: true\n"
```
