### ISSUE TITLE
NEI for 1.4.7 doesn't work with OneSix instance format

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#983]
Investigate.

**Comment by peterix** [comment]
Loads:
http://puu.sh/hV1DY/e0bb2b2e2d.jpg

Doesn't show up:
http://puu.sh/hV1CK/5f2b5e12a3.jpg

**Comment by peterix** [comment]
The problem is this ancient CCC and NEI require the minecraft jar to be named 'minecraft.jar'.

Eh.... Whatever.

**Comment by Timeslice42** [comment]
Man, it took me hours to figure this out... will switching MultiMC to the development channel give me this fix?

**Comment by peterix** [comment]
Yes.
