### ISSUE TITLE
Failure to start

### ISSUE THREAD

**Issue by Niko-Art** [MultiMC/MultiMC5#986]
After updating multi mc, it now fails to start. No process shows up in task manager.

**Comment by peterix** [comment]
What OS is that?

**Comment by Niko-Art** [comment]
Windows 8.1 With bing 64-bit

**Comment by peterix** [comment]
Did you use stable or develop?

**Comment by I5oK4** [comment]
Me too
And i have
on one pc ubuntu 15.04 64bit
in the other Elementary Os -Luna 64bit

**Comment by Niko-Art** [comment]
I use stable and I don't wish to lose my instances

**Comment by Kilobyte22** [comment]
In that case, back up your instances dir :)

**Comment by Niko-Art** [comment]
I haver just found out that my ftb instance tracking caused it.

**Comment by 02JanDal** [comment]
@Niko-Art: see #977
@I5oK4: Could that be the issue for you too? What happens if you open `multimc.cfg` in a text editor and change `TrackFTBInstances=true` to `TrackFTBInstances=false`? In any case, can you please put the contents of MultiMC-0.log on pastebin or similar and post the link here?

**Comment by Niko-Art** [comment]
I shall put it up in a bit as I am in lesson

**Comment by peterix** [comment]
This (FTB related crash bug on start) should now be fixed in develop.
