### ISSUE TITLE
Profile name matches domain name causes connection time out

### ISSUE THREAD

**Issue by taotau** [MultiMC/MultiMC5#987]
Hey, here's an odd little bug for you.

I have 2 minecraft accounts, and 2 profiles in MultiMC.  Lets call them diggerdude and minerdude.  I also own the domain diggerdude.net and host a personal server on minecraft.diggerdude.net.

minerdude can log in to the server with no issues.  However when diggerdude tries to connect he times out with the error 

```[18:29:15] [Client thread/INFO]: Connecting to minecraft.<PROFILE NAME>.net, 25565```

However if I set the minecraft client server entry to point at the IP address of minecraft.diggerdude.net, both accounts can log in fine.

It seems as if somewhere in your code you are doing some overzealous tokenisation.

Not show stopping and probably very circumstantial, but I found it an interesting quirk.

**Comment by peterix** [comment]
How odd.

The log page is censored so this sort of info doesn't show up in streams and similar settings. It should have no effect because the changes aren't done in Minecraft at all. It's just removing some known values from the Minecraft standard output.

**Comment by peterix** [comment]
Alright. This should be possible to investigate with the new profile name change feature Mojang added.

**Comment by peterix** [comment]
I don't think this is possible. The original issue probably was something completely different - some sort of network or DNS problem.

Closing.
