### ISSUE TITLE
Isolate Minecraft from MultiMC more, add a way to run Minecraft with a wrapper (prefix command)

### ISSUE THREAD

**Issue by Gotolei** [MultiMC/MultiMC5#991]
Instances which worked fine in 0.4.5.
Enabling/disabling FTB instance tracking brings no change in behavior. Java is auto-detected in settings.
Xubuntu 14.04, java 1.8.0_45

Run through bumblebee (*optirun* command, worked previously):
Runs as far as "getting instance files from mojang" before the process(es) closes. Does not create console window.
http://pastebin.com/ftxy7C9F (MultiMC-0.log)

Not run through bumblebee:
Opens console window, but then minecraft almost immediately crashes.
http://pastebin.com/VW5W4i8r (deleted previous MultiMC-0.log, new one generated)
http://paste.ee/p/QSqsa (integrated upload function)

**Comment by peterix** [comment]
You'll have to describe what 'run through bumblebee' means.

What does the 'Test' button in java settings tell you?

Make sure you have the console window set up to stay open when Minecraft exits:
![console](https://cloud.githubusercontent.com/assets/203326/7765636/7b0850ee-0060-11e5-9b0b-0e919da85d61.png)

The launch error looks like you have a 1.8 core mod in 1.7.10.

**Comment by Gotolei** [comment]
Bumblebee, an implementation for Nvidia Optimus graphics in linux.

    ~$optirun /home/raster/minecraft/MultiMC/MultiMC

[Java test success.](https://i.imgur.com/l9YqWB8.png)
[Console set as above.](https://i.imgur.com/q8XIoEO.png)

Looks like the 1.8 in 1.7 mod was curseforge being its usual self and downloading the wrong thing, removing a certain mod fixes minecraft's launch problem.

However the issue with Optimus graphics and 0.4.6 (where minecraft doesn't even start) remains and occurs regardless of which instance is run.

**Comment by peterix** [comment]
Try the wrapper script around java approach instread.

**Comment by Gotolei** [comment]
What wrapper script?

**Comment by peterix** [comment]
MultiMC is now blocking some environment variables from being passed to java, because that caused other problems.

Still, shouldn't crash and burn like that. Install gdb if you don't have it. Tweak the script:
https://github.com/MultiMC/MultiMC5/blob/develop/application/package/linux/MultiMC#L35

So the line looks like this:
gdb --args "${MMC_DIR}/bin/MultiMC" -d "${MMC_DIR}" $@

Run it.

Once it crashes, run the 'bt' command in gdb and post the resulting backtrace.

**Comment by peterix** [comment]
EDIT.

**Comment by Gotolei** [comment]
Edit noted.

http://pastebin.com/tNq9pV0A

**Comment by peterix** [comment]
So, I will add a way to run with wrappers. And isolate the external and internal environments even more. Because this seems to be breaking in a very unexpected way, possibly because of unwanted system/third party libraries getting in.

**Comment by peterix** [comment]
Works:
http://paste.ee/p/g34mx

valgrind apparently doesn't like java much, but hopefully optirun won't have a problem.

The java checks will be done without the wrapper commands.

**Comment by peterix** [comment]
In current develop, you should be able to just set optirun as the wrapper command in the global java settings. And stop using optirun for the whole application.

Please test :)

**Comment by Gotolei** [comment]
https://i.imgur.com/w1qxsiP.png

Appears to be working :smile:
