### ISSUE TITLE
Mods in the jar + Forge in the same instance

### ISSUE THREAD

**Issue by Revilo1803** [MultiMC/MultiMC5#993]
I have the problem that I can not play Forge instances any more. I have recreated the instacesm, but it will not work. Vanilla instances function properly. Can you fix it, please?

**Comment by Revilo1803** [comment]
This is the laucher-log:http://pastebin.com/EtyRW6SF

**Comment by peterix** [comment]
`C:/Users/******/Desktop/Minecraft/MultiMC/instances/Lay of the Land/temp.jar`

You are adding mods to the Minecraft jar and use them together with Forge. You'll have to move the mods you added to the Version page as jar mods to the mods folder (Loader mods).
See:
https://github.com/MultiMC/MultiMC5/wiki/Jar-Modding
https://github.com/MultiMC/MultiMC5/wiki/Instance-Versions#install

**Comment by Revilo1803** [comment]
Thank you very much for the tips

**Comment by Revilo1803** [comment]
Ok I found the problem. ChickenBone`s Mods are not usable with MultiMC any more

**Comment by 02JanDal** [comment]
???

Did you actually try what @peterix suggested?

**Comment by peterix** [comment]
Mod files belong here:
![modshere](https://cloud.githubusercontent.com/assets/203326/7800098/6ff74400-0310-11e5-8f4a-b9e38f23cde0.png)

Not into the Version page. If you Add jar mods using the 'add jar mod' button, don't expect anything to work, unless you know **very** well what you're doing.

**Comment by Revilo1803** [comment]
OK, I have done it. Thanks for the help!
