### ISSUE TITLE
Make jar modding less accessible

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#994]
Related to #993 and a lot of others.

Simply, it's the first 'add mod' button people see, so they use it without thinking or looking any further.

The **RIGHT** way to add mods should be the most accessible and the first way people try.

**Comment by Orcinuss** [comment]
Perhaps you could change the 'Loader Mods' to 'Edit Mods'. Then have two tabs within; one for loader mods and one for jar mods. Then, on the 'Version' sidebar tab, change 'add jar mod' to 'edit mods' which brings you to the 'loader mods' tab. If players really want to add a jar mod then they will have to click the jar mod tab but the first one should be loader mods. In the 'Version' tab, players will still be able to reorder their jar mods.

**Comment by Orcinuss** [comment]
![screen shot 2015-05-22 at 4 25 36 pm](https://cloud.githubusercontent.com/assets/7836002/7772848/025264fa-00a1-11e5-85ba-07a3c32d4995.png)
![screen shot 2015-05-22 at 4 30 42 pm](https://cloud.githubusercontent.com/assets/7836002/7772892/3f70be54-00a1-11e5-9e48-9ebd5813a38d.png)

**Comment by Kilobyte22** [comment]
This actally sounds fairly reasonable

**Comment by peterix** [comment]
Indeed. It even looks reasonable.
- the version page has packages... -> let's call it the 'Packages'
- the loader mods -> Let's call it 'Mods'
- and the jar mods part of it is for setting the specific order of the jar mods
- this could allow decoupling profile patch order from jar mod order... possibly we should even do away with the idea of profile patch order.

**Comment by peterix** [comment]
This needs to be done.

**Comment by peterix** [comment]
Went with a much simpler solution that doesn't add a whole new mod list.

Any further changes to the UI should be to support packages and wonko package repository stuff.
