### ISSUE TITLE
Notes not saving properly

### ISSUE THREAD

**Issue by AngleWyrm** [MultiMC/MultiMC5#997]
Accessing the notes via first going to the edit instance button seems to work fine, but pressing the edit notes button doesn't seem to save note edits.

**Comment by peterix** [comment]
Notes do not get saved for FTB instances.

**Comment by peterix** [comment]
FTB loading overwriting notes and other values now shouldn't be a thing in the develop version.

Is this still a problem? (you can switch to the develop channel in the settings and update to test)

**Comment by peterix** [comment]
Fixed in develop.
