### ISSUE TITLE
Error going Fullscreen (random startup "crash")

### ISSUE THREAD

**Issue by jjmcquaid** [MultiMC/MultiMC5#998]
Okay, first I really love MultiMC it's so incredibly useful. But here's my problem. This started happening when I updated to 0.4.6.

I'm using Minecraft Version 1.7.10 with Forge version 10.13.3.1408 (the latest at time of posting).

Whenever I start up my instance Minecraft loads up almost completely, however when it's done and the client goes to full-screen it gets stuck with a blank maximized window. It doesn't happen every time, but it does happen more often than not. Sometimes randomly it'll start up and run perfectly. But it takes about 10 or more tries.

Restarting my pc seems to help, but the problem is so random I can't tell if that's just coincidence.

I tried a bunch of things to fix this because I didn't think the problem was MultiMC. I rolled back forge, and a bunch of other mods I had updated prior to this problem starting. I uninstalled and reinstalled Java. I also tried switching between Java 7 and 8. Nothing worked.

So then I tried not using MultiMC and just modding Minecraft normally and now it starts fine every time. So I can't think of what else would be causing this. It doesn't generate a crash report so all I have is the server log (http://pastebin.com/B4UP4w1x). I hope this helps, and I hope you can fix it. I've only had this problem for a couple days, but I 'm already missing MultiMC incredibly. If you need any other info let me know. And thanks so much for all the work and effort you put into this awesome program.

**Comment by Loetkolben** [comment]
Looks like this is your problem:
```
[23:16:36] [Client thread/ERROR]: Couldn't toggle fullscreen
java.lang.IllegalStateException: From thread Thread[Client thread,5,main]: Thread[Thread-9,5,main] already has the context current
```
Maybe try starting without fullscreen enabled and see if that helps. Also, using the Vanilla Launcher, do you have Fullscreen enabled?

**Comment by peterix** [comment]
This might actually be an interaction between going fullscreen and the new loading screen.

I would say roll back to a version of forge that doesn't include the new loading screen (1388) and see if it still happens there.

**Comment by peterix** [comment]
Does it work if you start without fullscreen and then press F11 later?

**Comment by peterix** [comment]
That aside: I've never seen it work properly. Ever.

THIS is fullscreen on linux with two screens:
![fullscreen on linux fail](http://i.imgur.com/wJbUFff.png)

- it chooses the wrong screen
- the 'window' is 2x wider than the screen
- you can't move it without it going 'oh, I'm not fullscreen anymore'
- it doesn't work on launch at all
- it turns off the monitors for a second when you press F11

**Comment by peterix** [comment]
Another possibility:
your graphics card drivers are doing something very stupid - recognizing 'known' applications and 'adjusting' how they react based on that.

Try renaming 'MultiMC.exe' to 'Minecraft.exe' and see what happens.

**Comment by jjmcquaid** [comment]
Starting without fullscreen seems to help so far. Haven't had the problem happen again yet. Rolling back Forge to a version without the graphical loading screen and starting maximized does not. Thanks for the help though. I just have to remember to turn off fullscreen when I close Minecraft until this gets fixed.

**Comment by peterix** [comment]
Hmmm... what about the rename thing?

**Comment by jjmcquaid** [comment]
Trying that now. I gotta do it a couple times because sometimes it will randomly start the first time and I think it's fixed, then I do it again and it freezes. It's the randomness that makes this so annoying. But no, no help with renaming to Minecraft.exe, and also if I start Minecraft unmaximized then go fullscreen, that does work. I forgot to mention that.

**Comment by jjmcquaid** [comment]
Okay, so Forge version 1388 doesn't work but 1387 does. Just found that out with some testing. Even though 1388 doesn't have the graphic loader.

**Comment by peterix** [comment]
So, this is possibly an issue with Forge. Maybe in combination with being loaded differently?

**Comment by jjmcquaid** [comment]
Okay, I'll put a report over with them. But you really helped me out. I was starting to get really irritated when the usual things didn't work. So thanks a lot man. I appreciate it.

**Comment by peterix** [comment]
Just managed to reproduce this, I think, with my ghetto XP virtual machine:
http://paste.ee/p/6n2vz

It crashed after that too, because of other fun problems...

**Comment by peterix** [comment]
Seems to be only when you actually set fullscreen using the video settings in game.

**Comment by jjmcquaid** [comment]
Yeah, that's why I was saying I'll have to remember to unfullscreen it when I'm done.

**Comment by jjmcquaid** [comment]
But I don't think the issue is from my pc. I mean mine is pretty decent. It should be able to handle minecraft. Considering all the other games I can run at max graphics that are a lot more detailed than minecraft.

**Comment by peterix** [comment]
I think you can leave it 'unfullscreened' and just press F11 after start. Doesn't seem to save the option.

**Comment by peterix** [comment]
If you can, link the Forge bug report here and this one on their end... just so things can be tracked properly.

**Comment by jjmcquaid** [comment]
Forge bug report - https://github.com/MinecraftForge/FML/issues/662
